### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by MagaTailor** [paritytech/parity#1003]
I recently bought an Android 5.1 TV box (64-bit Cortex-A53, 2 GB RAM, S905 SoC, rooted) which I'm going to convert to Linux. But before I do, I thought maybe I could experiment with some recently developed functionality called `cargo-apk` that in turn uses `android-glue`.

I have never owned an android phone so I have no idea idea what to expect in the context of a CLI app like parity.

Should I even start reading into it? (on ARM Linux host) @tomaka

**Edit:**
This could be useful on any development board running Android instead of Linux. (eg. Odroid)

**Comment by tomaka** [comment]
There's probably not much point in building an apk for a CLI app.

**Comment by petevine** [comment]
As I said, I have no experience with android so it's not clear to me if CLI apps can be built easily through cross-compilation or it can't work at all? Thx.

**Comment by tomaka** [comment]
It can easily be built but you will get a black screen, no way to pass parameters, and the output will only be written to the logs which can only be read with debugging tools.

**Comment by petevine** [comment]
If you mean just the console output then it all sounds perfect for a network client like this :)  

Anyway, feel free to ping me from one of the `android-glue/cargo-apk` issues if the platform I described looks usable and you need some testing.

**Comment by gavofyork** [comment]
if it were combined with an web engine, then you'd have an android portal to web3 and a mobile wallet should be easy enough. shouldn't be too hard to do either, i'd say. probably not much use until PV63 state syncing is in, though.

**Comment by MeinFuehrer** [comment]
I've got termux installed so there's probably no reason why parity shouldn't be able to run inside it. 

Could someone build an `armv7-linux-androideabi` version for me?

**Comment by 5chdn** [comment]
@MeinFuehrer you could check out the Raspberry Pi images which include parity, see https://github.com/diglos/pi-gen (website http://ethraspbian.com/)

**Comment by MagaTailor** [comment]
It seems this issue is not about parity any longer, thanks to @malbarbo's rustc work.
