### ISSUE TITLE
Option/mode to avoid building (most of) extras DB

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#1021]
Make much of the extras DB optional like transaction tracing is now. This would make many of the RPCs slow, but further reduce storage footprint while still providing ability to mine/seal.

**Comment by 5chdn** [comment]
This _footprint_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still _epic_ to implement... :P If so, please add an assignee, or close otherwise.

**Comment by gavofyork** [comment]
reconsider.
