### ISSUE TITLE
Disable RocksDB debug logging

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#1100]

**Comment by gavofyork** [comment]
CLI option?

**Comment by 5chdn** [comment]
As far as I can tell, the RocksDB debug logging can't be disabled by configuration. I see two options here, either something rather dirty like setting `db_log_dir` to `/dev/null`, or just setting `keep_log_file_num` to `1` (0 is not allowed). The latter will maintain a single LOG file which is probably the cleanest and simplest solution, and does not clutter the db directories.
