### ISSUE TITLE
emitting debug info may inhibit optimizations

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1152]
Currently the release profile for parity emits debug information. There is conflicting information about whether it affects LLVM's ability to perform optimizations, but it seems that it may inhibit inlining and loop autovectorization in Rust: https://internals.rust-lang.org/t/benchmark-optimization-woes/1441

However, LLVM's official documentation says that debug info will not prevent optimizations from running: http://llvm.org/docs/SourceLevelDebugging.html#debugging-optimized-code.

It is probably worthwhile to look into benchmarking parity with and without debug info to see if there is a tangible difference.

**Comment by gavofyork** [comment]
we should probably have a separate "final" build which strips everything.

**Comment by arkpar** [comment]
Benchmarked importing blocks with debug on and off - no difference. Having debug symbols in release build helps diagnosing problems on users machines.

**Comment by 5chdn** [comment]
Closing as _wontfix_ as per @arkpar's comment. Feel free to reopen this if it's still relevant.

**Comment by arkpar** [comment]
Worth mentioning that we've disabled debug symbols by default anyway to improve compilation speed
