### ISSUE TITLE
Reverse sync algorithm

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#1295]
Initial headchain sync should work by tracing remote chain down until a known block is reached. Can be done efficiently using stepped 256 header chains.
- Identify remote's best hash (`h`).
- Get 256 hashes stepped by -256 blocks starting at `h` -> `H`.
- Let `j` be the last unknown hash in sequence `H`.
- Get 256 hashes stepped by -1 starting at `j` -> `J`.
- Let `k` be the last unknown hash in sequence `J`.

Blocks can now be downloaded normally forwards from `k`.

**Comment by rphmeier** [comment]
Benefits over the current algorithm?

**Comment by gavofyork** [comment]
fewer edges cases in the logic

**Comment by rphmeier** [comment]
Will probably use a variant of this for light client header-chain syncing:

rob
6:04 PM
I wonder if a "fractal" approach would be worthwhile when you're syncing from the genesis to a peer which is potentially millions of blocks ahead of you.
6:05
As in your initial request should be 256/512 stepped headerchains with just high enough step to close >= half the distance.
6:05
then halve the step and get a more compact stepped headerchain from there to halfway again to the beginning (edited)
6:06
and so on until you've reached back to the genesis. then you could sync forward and fill in more compact sparse headerchains in the gaps as you move forwards
6:06
interesting thing about this is that it has a more or less constant memory requirement regardless of sync distance

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's not assigned and postponed to 1.9 and beyond.

It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by gavofyork** [comment]
should be removed to the long-term bin.
