### ISSUE TITLE
Heartbeats on JSON-RPC WebSockets.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#1327]

**Comment by 5chdn** [comment]
Does _signer_ refer to the wallet ui in this case?

**Comment by tomusdrw** [comment]
Yes it did. I've updated the title. It would be needed only for very long lasting connectsion with no communication happening (like a dapp waiting for some rare event without querying anything else).
Since that's hardly ever a case I'm ok with closing this issue.
