### ISSUE TITLE
Reduce lock acquisitions

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1355]
LLVM stays away from optimizing atomics, so we can probably shave off some of the overhead from redundantly acquiring locks.

Seems to be common in the network/sync code. Probably elsewhere as well, given the prevalence of `RwLock` in the codebase.

Honestly, trawling through and optimizing lock acquisition patterns could account for a non-negligible increase in performance.

**Comment by nipunn1313** [comment]
Thinking about thread ownership of complex datastructures can often help.

One model I've found to tremendously help in reasoning about performance is
- One thread owns datastructure (no locks on data structure)
- Other threads post information to the "owning" thread async if they need to update the structure. "Posting" is often in the form of a locked FIFO queue, but would could envision other ways.

Obviously not applicable in all scenarios, but especially in places that are performance critical, it's nice to know that they aren't battling over the complex data structure (and dealing with locking overhead). Probably especially true on data structures with RW locks on them.

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still _nice to have_. If so, please add an assignee and a milestone, or close otherwise.

**Comment by rphmeier** [comment]
This is more suited to a coding style guide. Also, `parking_lot` provides pretty fast/small userspace locks that seem to be fast enough.
