### ISSUE TITLE
Benchmarking workspace

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#1480]
- [ ] ability to specify branch to bench
- [ ] predefined bench scenarios (sync to N-block from file, sync from M to N block)
- [ ] footprint diagnostic
- [ ] cpu usage
- [ ] backing io variance (fast/slow)
- [ ] ability to specify parameters e.g. which contracts, avg transaction/block, ratio of transaction types and have a deterministic, standardised chain created for profiling.
- [ ] should all fit into `cargo bench`.
- [ ] github bot (reacting to the "please bench" comment in PR)

**Comment by NikVolf** [comment]
@gavofyork probably it won't fit in standart `cargo bench` which performs a lot of runs of the same test, which we can't afford

also, there are some talks on rust forums that benches can be removed at all
https://internals.rust-lang.org/t/bench-status/2122/11

**Comment by gavofyork** [comment]
perhaps just importing a smaller chain (2000 blocks?) would suffice; `cargo bench` should work ok for that (each trial should be around 1 second).

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still _nice to have_. If so, please add an assignee and a milestone, or close otherwise.

**Comment by debris** [comment]
we should look at this issue again at some point, but I'm closing it for now, as it is too generic and currently we have no plans to fix these issues
