### ISSUE TITLE
Rework db-fix

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#1496]
since keeping track of open fails impedes the performance, this has to be reworked: #1494
to the raising file limit programatically in case of getting exception while opening database

the original bug was probably introduced because of user had a database in the old compaction style with thousands of files

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's postponed to 1.9 and beyond.

It probably needs a re-prioritization, or a proper deadline.

**Comment by debris** [comment]
I believe that this issue is not relevant anymore and will become even more obsolete as soon as we merge #7348. I'm closing
