### ISSUE TITLE
Use cargo workspaces when they stabilize

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1582]
Now that https://github.com/rust-lang/cargo/pull/2759 has landed.

This should improve build times and workflow for multi-crate projects like parity

**Comment by rphmeier** [comment]
Workspaces have hit nightly (and maybe beta), so I will start work on this in the next release or the following.

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's neither assigned and nor linked to a milestone.

It probably needs a re-prioritization, or a proper deadline and an assignee.
