### ISSUE TITLE
ipc path on windows should be configurable

### ISSUE THREAD

**Issue by debris** [paritytech/parity#1647]
Right now it is fixed to: `r"\\.\pipe\parity.jsonrpc"` for parity and `r"\\.\pipe\geth.ipc"` for parity with `--geth` compatibility mode.

**Comment by NikVolf** [comment]
don't see why it should be so, btw
unless we support scenario where two parity instances run on the same machine

**Comment by 5chdn** [comment]
> unless we support scenario where two parity instances run on the same machine

which eventually happens if you deploy a dev chain locally with multiple clients. see #5628

**Comment by tomusdrw** [comment]
We already have `--ipc-path`, so I think this issue can be closed.
