### ISSUE TITLE
Make coverage nice green 90-100%

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#1680]

**Comment by 5chdn** [comment]
The coveralls are broken. Who was taking care of this?

https://coveralls.io/github/paritytech/parity?branch=master can not be found, and

https://coveralls.io/github/ethcore/parity?branch=master stopped working in March.

@paritytech/core-devs @paritytech/ci

**Comment by General-Beck** [comment]
https://codecov.io/gh/paritytech and next step coveralls.io

**Comment by 5chdn** [comment]
Any progress on this? I removed the coveralls badge with #6229 for now.

**Comment by debris** [comment]
as this is not an issue, but a long-term goal I remove it from the issue list
