### ISSUE TITLE
Optionally run ec:recover (secp256k1) on GPU (opencl/vulkan)

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#1681]
- for as much blocks in the queue as possible at once

**Comment by NikVolf** [comment]
https://github.com/hhanh00/secp256k1-cl

worth checking if it fits this task

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still realistic to implement. If so, please add an assignee, or close otherwise.

**Comment by debris** [comment]
not realistic and definitely not a priority
