### ISSUE TITLE
migrate elasticarray to smallvec

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1822]
https://crates.io/crates/smallvec

Elastic array has numerous soundness holes when dealing with non-Copy elements. Smallvec works almost exactly the same.

**Comment by arkpar** [comment]
I've tried that some time ago and it did not fit for the reason I can't recall. I think it does not really support size greater than 32 bytes

**Comment by rphmeier** [comment]
it does now, at least: http://doc.servo.org/smallvec/trait.Array.html
you can make a smallvec for each of these sizes (0..32 and various powers of 2)

**Comment by nipunn1313** [comment]
I took a look at this. It seems like we may need to wait for `SmallVec` to impl `Hash` for kvdb.

Looks like there's an Open PR for this upstream. Maybe some of parity's other callsites can be converted.
https://github.com/servo/rust-smallvec/pull/26/files

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still realistic to implement. If so, please add an assignee and a milestone, or close otherwise.

**Comment by debris** [comment]
Latest attempt to implement this is in #4874. As of now `smallvec` performance is worse than `elasticarray` so I opt for closing the issue and pr until it changes (if ever).

**Comment by debris** [comment]
I think, we can close this one
