### ISSUE TITLE
Supprt mdns hostnames in interface options

### ISSUE THREAD

**Issue by nerdralph** [paritytech/parity#1880]
<pre>
parity ui --dapps-interface l1.local
Invalid Webapps listen host/port given: l1.local:8080
</pre>

The above fails, but substituting the IP address works.  There is no problem resolving l1.local, as "ping l1.local" resolves the IP (in this case a reserved 192.168 IP).

**Comment by tomusdrw** [comment]
AFAIR it works fine on Linux, it's platform-specific (perhaps it's even a difference in `std::net::TcpListenre::bind`)

**Comment by nerdralph** [comment]
@tomusdrw It is under linux that I get the error.
Linux l1.local 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 5chdn** [comment]
Can't reproduce this on linux.
