### ISSUE TITLE
Does sync work ok between parity nodes when there's a reorg?

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#1899]
> [09/08/2016, 22:12:16] Vitalik Buterin: hey, have you tried running a testnet with nothing but parity nodes?
> [09/08/2016, 22:19:29] Vitalik Buterin: I've heard from some devs that it doesn't work because for some reason parity nodes can't sync with each other if the chain reorgs
> [09/08/2016, 22:19:40] Vitalik Buterin: (and the same with c++)
> [09/08/2016, 22:20:17] Vitalik Buterin: (but it's all fine if there are some geth nodes in the network)

**Comment by gavofyork** [comment]
@jesuscript could you look into this?

**Comment by 5chdn** [comment]
@jesuscript did you look into this? ;-)

**Comment by 5chdn** [comment]
I'm tempted to close this as _stale_ unless someone cares to test this setup and answers this question on parity chain reorg.

@paritytech/ci or @paritytech/core-devs Please assign this issue to someone and decided on a deadline within 7 days, thanks.
