### ISSUE TITLE
Forked dependency tracking issue

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#1988]
## Forked dependencies
- [mio](https://github.com/ethcore/mio/tree/v0.5.x)
  - **Justification:** windows-support related 
  - PR: missing
- [rotor](https://github.com/ethcore/rotor)
  - **Justification:** depends on mio
  - PR: not necessary
- [hyper](https://github.com/ethcore/hyper)
  - **Justification:** depends on rotor
  - PR: not necessary
- [ws](https://github.com/ethcore/ws-rs/tree/mio-upstream-stable)
  - **Justification:** windows-support related
  - PR: missing? (@tomusdrw does https://github.com/carllerche/mio/pull/444 solve everything?)
- [ctrlc](https://github.com/ethcore/rust-ctrlc)
  - **Justification:** sigkill support
  - PR: missing
- [nanomsg](https://github.com/ethcore/nanomsg.rs)
  - **Justification:** build without CMake
  - PR: missing

These forked dependencies often fall months behind in development from their upstream counterparts. For small projects like `ctrlc`, this doesn't pose as much of an issue, but larger projects like `mio`, `hyper`, and `nanomsg` which are actively and heavily developed will not see upstream bug fixes and improvements. 

Please add any dependencies/justifications I may have missed.

**Comment by tomusdrw** [comment]
`ctrlc`: PR was (kind of) rejected -> https://github.com/Detegr/rust-ctrlc/pull/7
`ws`: windows-support (using mio#dev, mentioned issue should indeed solve this), file serving (responding to requests with HTML content (when ws handshake fails))

I will prepare proper PR for `ws-rs` with file handling when all issues with windows support are resolved in upstream (mio released, ws-rs stable released)

**Comment by gavofyork** [comment]
fork ctrlc and publish it as "exit-signal" or something?

**Comment by tymat** [comment]
Tracking this for FreeBSD support.  

nanomsg.rs won't build because it assumes GCC as the compiler (FreeBSD uses clang)

**Comment by 5chdn** [comment]
Do we need an issue to track forked dependencies? Please consider closing this issue and create a page on the wiki somewhere.

**Comment by rphmeier** [comment]
It's a _tracking_ issue to be closed when we use solely crates on crates.io

**Comment by 5chdn** [comment]
Thanks for clarification. I'm well aware of the implications, just was wondering if this could be tracked somewhere else. However, having a ticket for this makes sense.

**Comment by debris** [comment]
I'm closing this issue as most of these deps are no longer forked. the only 2 remaining forks are `ws` and `ctrlc`. There is already an open issue to replace ws - https://github.com/paritytech/jsonrpc/issues/158
