### ISSUE TITLE
Sync time over NTP

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#2062]
System clock skew causes a number of problems:
1. UDP discovery packets contain timestamp and might be considered expired - peer discovery stops working.
2. Miners produce blocks with timestamp in the future which are not accepted by other clients resulting in higher uncle rate.

Parity should be able to periodically sync local time correction with NTP server and not rely on system clock.

**Comment by ethernomad** [comment]
Surely this is the responsibility of the operating system?

**Comment by arkpar** [comment]
Unfortunately some operating systems and virtual environments don't do that reliably and we are getting issues reported because of this. We don't want to set the system clock. Just the local clock used in Parity only.

**Comment by General-Beck** [comment]
this question is very relevant! Many users complain about the sync.

**Comment by fjl** [comment]
We do it like this in go-ethereum:

If many outdated-looking discovery packets arrive the time is looked up via NTP and the user gets a warning message in the log. We have had zero problems with such bug reports since then.

**Comment by 5chdn** [comment]
The operating system should take care of time sync. The client should just recognized and warn the user. I'm in favor of closing this for #5604 (unless you also want this warning in the logs).

**Comment by arkpar** [comment]
I agree that warning (both in CLI and UI) will be enough
