### ISSUE TITLE
Port CLI to clap

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#2066]
https://github.com/kbknapp/clap-rs

Our CLI is lacking in a few key areas:
- no `--help` for subcommands themselves
- all options are available to all subcommands

This leads to our `--help` output being way too large while also not providing any information on what subcommands do.

**Comment by debris** [comment]
We should discuss that next week in Berlin. I have a few ideas. cc @tomusdrw

**Comment by rphmeier** [comment]
I don't think that #2070 necessarily makes us more tied into docopt, although Clap defines a CLI through Rust code as opposed to parsing text.

**Comment by tomusdrw** [comment]
Yes, actually I think it makes us less tied to docopt (I had to disable docopt filiing default values automatically).

It's worth consider a rewrite, but I think we can also use this opportunity to do a general overhaul (simplify) of CLI options (perhaps some of them should be only possible to set from config file).

**Comment by axelchalon** [comment]
I'd like to work on this! I'll port the CLI to clap first and see how it goes.
