### ISSUE TITLE
consider switching to material design lite

### ISSUE THREAD

**Issue by derhuerst** [paritytech/parity#2093]
[Material Design Lite](https://getmdl.io/) is focused more on being leightweight and accessible, but still offers most of the Material Design (Classic) components. [`react-mdl`](https://github.com/tleunen/react-mdl) is a React "wrapper".

With [`react-mdl@2`](https://github.com/tleunen/react-mdl/milestone/3), it will be more modularized (i won't bundle the whole mdl lib anymore). This will make it a nice replacement for `material-ui`.

We may need to replace components not included in `react-mdl` by plugins/modules.

**Comment by jacogr** [comment]
There are a number of places (Inputs, Selects) where we are not using the material-ui components directly. This was mostly originally for convenience, i.e. you don't need to pass 50 props through to set the thing up, it is standardised for our layouts) In these cases just changing our components in `js/ui` would filter through with no search & replace everywhere.

**Comment by jacogr** [comment]
Closing. UI-2 moving to Semantic-UI.
