### ISSUE TITLE
Module-specific memory instrumentation

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#2107]
As our memory usage seems to be a bit overblown lately, some instrumentation would help solve the issue. The memory usage issue needs to be solved by the 1.4 release.

Should really just involve implementations of `HeapSizeOf` everywhere.

Optional:
  RPC call for getting module-specific memory usage.

**Comment by arkpar** [comment]
`HeapSizeOf` won't report memory allocated by dependencies, such as hyper or rocksdb. Building against system allocator and using a heap profiler such as massif seems more reliable to me.

**Comment by 5chdn** [comment]
This _footprint_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still _nice to have_. If so, please comment below and add an assignee, or close otherwise.

**Comment by rphmeier** [comment]
Perhaps useful, but @arkpar is right that just building a custom `rustc` w/ system alloc and using a profiler works.
