### ISSUE TITLE
final confirmation for transaction sending

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2143]
confirmation dialog, i.e. "do you want to send this transaction to the signer confirmation queue" (Ken)

(Split from https://github.com/ethcore/parity/issues/2114)

**Comment by KenKappler** [comment]
This is for the 'Transfer' function in the wallet - not transactions generally.

**Comment by 5chdn** [comment]
I'm suspecting this is obsolete, since the signer itself is a confirmation step already.
