### ISSUE TITLE
Display a message when exporting from an empty DB.

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#2163]
I am running 

```
parity export test.rlp
```

It exists immediately and I can see a 0 bytes test.rlp file.

parity version:

```
Parity
  version Parity/v1.2.4-stable-a66fd11-20160809/x86_64-macos/rustc1.11.0
Copyright 2015, 2016 Ethcore (UK) Limited
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf.
```

**Comment by rphmeier** [comment]
What block were you synced to before export?

**Comment by chevdor** [comment]
I was definitely after the block causing troubles to geth and I was synced.
So around #2284998

**Comment by chevdor** [comment]
Hello @rphmeier, now having access to a keyboard so I can provide more details.
I have tried the export around block 1500000 and it failed as well.

I am now totally synced.
If I run the following command now:
```
parity export test.rlp
```
it returns without error and creates an empty file.
If I use --to and --from, I get an exception that I will report into another issue and link in a minute.

**Comment by chevdor** [comment]
I switched to Parity/v1.3.1-beta-2a82fa0-20160911/x86_64-macos/rustc1.11.0

the issue remains.

**Comment by chevdor** [comment]
The issue seems to be that I previously ran parity with --datadir /some/path
When I ran the export, I did not provide the --datadir option.
Providing it seems to behave properly.

So the issue left is simply to have a clear message saying "No db found in /your/path, provide --datadir if your data is in another location".

**Comment by rphmeier** [comment]
Ok, I think this kind of logging can be improved simply with an "initializing new db at {path}" message.

**Comment by tomusdrw** [comment]
But I think it shouldn't panic anyway - let's confirm that it's not panicking when DB is empty and the we can close it.

**Comment by 5chdn** [comment]
@tomusdrw I don't think it's panicking, just exiting because there is nothing to do.

**Comment by 5chdn** [comment]
Fixed.

    parity export blocks b.rlp
    2017-04-11 08:49:27  Configured for Foundation using Ethash engine
    2017-04-11 08:49:27  Export completed.
