### ISSUE TITLE
Parity export issue when using  --to

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#2170]
`parity export --from 2 test.rlp`=> no error but empty file created. See #2163 

`parity export --to 5 test.rlp` => returns the following error:

```
2016-09-19 14:56:30 Configured for Frontier/Homestead using Ethash engine
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

and with the backtrace:

```
2016-09-19 14:59:35 Configured for Frontier/Homestead using Ethash engine
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:        0x10a89edcb - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:        0x10a8a3f7a - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:        0x10a8a3baa - std::panicking::default_hook::heb8b6fd640571a4f
   4:        0x10a88b988 - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:        0x10a8a4556 - std::panicking::begin_panic::h941ea76fc945d925
   6:        0x10a88c5c8 - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:        0x10a8a41af - rust_begin_unwind
   8:        0x10a8cab30 - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:        0x10a8cae2c - core::panicking::panic::heeca72c448510af4
  10:        0x109ebb489 - parity::execute::h4228f2b3aef67c46
  11:        0x109eb22ff - parity::main::hc0b8b9a4c77213f8
  12:        0x10a8a376d - std::panicking::try::call::hca715a47aa047c49
  13:        0x10a8a462b - __rust_try
  14:        0x10a8a45c5 - __rust_maybe_catch_panic
  15:        0x10a8a3591 - std::rt::lang_start::h162055cb2e4b9fe7
```

**Comment by rphmeier** [comment]
Did you sync using a snapshot? This doesn't yet play nicely with export.

**Comment by tomusdrw** [comment]
I believe @chevdor is running `1.2.x` series, right?

**Comment by chevdor** [comment]
1.2.4 indeed.

**Comment by tomusdrw** [comment]
Could you run with `RUST_BACKTRACE=1`? Also is your DB not corrupted? Can you run sync Parity without any issues?

**Comment by chevdor** [comment]
The issue seems to be that I previously ran parity with --datadir /some/path
When I ran the export, I did not provide the --datadir option.
Providing it seems to behave properly.

So the issue left is simply to have a clear message saying "No db found in /your/path, provide --datadir if your data is in another location".

**Comment by adrianbrink** [comment]
The 'execute_export' (line 237) method in [blockchain.rs](https://github.com/ethcore/parity/blob/master/parity/blockchain.rs) seems to be the place that unwraps the Option with try! and then fails. However I can't narrow it down much more, since I just started looking at the codebase. Hope this helps.

**Comment by chevdor** [comment]
I did not test that but to reproduce the behaviour I saw, you probably can run:
`parity export --datadir /nonexistant/or/empty/dir --to 10 file.rlp`

**Comment by rphmeier** [comment]
@adrianbrink Yep, that's almost definitely the issue. Feel free to make a PR which has it return an error when the block doesn't exist. The `import/export` code needs to be made more resilient to incomplete chains in general, as with recent changes in the code there is no guarantee that we even store a continuous chain.

**Comment by SjonHortensius** [comment]
I have the same problem without using `import / export`; simply running `/usr/bin/parity --db-path /srv/parity` causes the same error. Is this expected?

**Comment by 5chdn** [comment]
Is this fixed? Tagged with _easy_ for half a year.

**Comment by rphmeier** [comment]
Not AFAIK. We've left it open so anybody looking for an easy issue can take a stab at it :)
The Hamburg Rust Meetup might do it tonight, as they're taking a look at a few of those.

**Comment by 5chdn** [comment]
Looks like fixed.

    parity export blocks b.rlp --from 2 --to 5
    2017-04-11 08:51:20  Configured for Foundation using Ethash engine
    Error exporting incomplete chain
