### ISSUE TITLE
Make State uncloneable

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#2221]
Ensure with the type system that we can't copy unnecessary state data.

Break snapshots out of `State` itself, and allow "forkable" snapshots, each building off of a base `State`. This will let us build the `UsingQueue` of closed blocks to mine on with minimal footprint.

**Comment by 5chdn** [comment]
This _footprint_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still _nice to have_. If so, please comment below and add an assignee, or close otherwise.

**Comment by Vurich** [comment]
I think the best thing to do here is to make `State` the equivalent of a patch reference and keep the `Clone` impl. We can hide all the complexity behind the methods and not have to change the callers at all.

**Comment by folsen** [comment]
Closing due to upcoming large changes to snapshots in general. Needs to be more specific if reintroduced.
