### ISSUE TITLE
RPC Solidity compilation returns bytecode only, rather than full JSON as per spec 

### ISSUE THREAD

**Issue by yarrumretep** [paritytech/parity#2272]
Most sources indicate that the RPC to compile solidity should return a JSON wodge that contains the ABI and other meta information relevant to the contract.
- JSON-RPC Documentation: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_compilesolidity

The above documentation suggests a single JSON document is returned, but other locations indicate that the result contains an entry for each contract defined in the source.
- Geth javascript doc: https://github.com/ethereum/go-ethereum/wiki/Contracts-and-Transactions/dfd59aa80ebe50218161140feccbad1f87d71c22
- Frontier Guide: https://ethereum.gitbooks.io/frontier-guide/content/compiling_contract.html
- web3.js documentation: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethcompilesolidity

Current parity behavior returns only the compiled binary:

`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_compileSolidity","params":["contract test { function multiply(uint a) returns(uint d) {   return a * 7;   } }"],"id":1}' -H "Content-Type: application/json" http://localhost:8545
{"jsonrpc":"2.0","result":"0x606060405260308060106000396000f3606060405260e060020a6000350463c6888fa18114601c575b6002565b346002576007600435026060908152602090f3","id":1}`

Propose to update the compile_solidity function in eth.rs to generate JSON responses like those expected by web3 - slightly different than what is specified in the JSON-RPC spec..

**Comment by rphmeier** [comment]
So actually the spec there actually implies that the `DATA` returned should be the compiled bytecode. This was also the case before the example was altered about a year and a half ago to no longer match the description: https://github.com/ethereum/wiki/wiki/JSON-RPC/e3c885a070fc5e25350a33fb54e6911f804cac6c

Now, given that it's been such a long time since it was changed it's possible we could come to support that format, but I'm not really sure why each "compile" call would have to return a ton of things like documentation, ABI format, etc. If you need that much additional info you could just invoke `solc` directly, and leave the `compileSolidity` call for nothing but compilation. Curious to hear others' takes on this.

**Comment by rphmeier** [comment]
(This isn't the only case where the existing specification has been unilaterally altered to match the behavior of a specific client -- as such I'm a bit hesitant to treat it as a formal standard at all :) )

**Comment by yarrumretep** [comment]
So - I'm still a bit fresh to this whole universe, please excuse unintended naiveté...

Robert, two questions:

1. Is there any reason NOT to include the extra meta-data in compilation results?  As a noob I have been working through various examples and most seem to assume a JSON blob as the result.  web3 certainly seems to.

1. Don't you usually need the ABI if you are going to create the contract - or am I confused with web3.js foo?

I do see that the other two compilers do not generate JSON globs so there does seem to be a consistency thing there...

**Comment by yarrumretep** [comment]
For reference, here is geth (1.4.12-stable-421df866) response:

`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_compileSolidity","params":["contract test { function multiply(uint a) returns(uint d) { return a * 7; } }"],"id":1}' -H "Content-Type: application/json" http://localhost:8545`

Result:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "test": {
            "code": "0x606060405260308060106000396000f3606060405260e060020a6000350463c6888fa18114601c575b6002565b346002576007600435026060908152602090f3",
            "info": {
                "source": "contract test { function multiply(uint a) returns(uint d) { return a * 7; } }",
                "language": "Solidity",
                "languageVersion": "0.4.3",
                "compilerVersion": "0.4.3",
                "compilerOptions": "--bin --abi --userdoc --devdoc --add-std --optimize -o /var/folders/yz/9d62ljjn3ljf419rx0x0x9z80000gn/T/solc384910493",
                "abiDefinition": [{
                    "constant": false,
                    "inputs": [{
                        "name": "a",
                        "type": "uint256"
                    }],
                    "name": "multiply",
                    "outputs": [{
                        "name": "d",
                        "type": "uint256"
                    }],
                    "payable": false,
                    "type": "function"
                }],
                "userDoc": {
                    "methods": {}
                },
                "developerDoc": {
                    "methods": {}
                }
            }
        }
    }
}
```

**Comment by yarrumretep** [comment]
For reference: The Parity JSONRPC documentation also indicates the full JSON response format:

https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_compilesolidity

These docs should be updated if this proposal is ultimately rejected.

**Comment by gavofyork** [comment]
The example is erroneous and simply documents Geth's (non-standard) output for that call. I just updated the example in the link above to agree with the spec.

I am, in principle, happy to change the spec to mimic Geth's output since it does indeed seem to be useful, however I'd prefer to have the specification stated in the standard and definitively agreed upon, lest the foundation teams unilaterally change it again.

**Comment by rphmeier** [comment]
@yarrumretep Yes, the data is useful in general but not if you're only looking to compile the code. Probably an optional parameter to the RPC for the full data-dump would be workable.

**Comment by tcoulter** [comment]
To add in my experience: Compiling code without getting the resultant ABI makes the compilation almost worthless. You can deploy the contract with that bytecode, yes, but it's otherwise very hard to interact with.

**Comment by tomusdrw** [comment]
Compilation is not supported any more, see https://github.com/ethereum/EIPs/issues/209
