### ISSUE TITLE
Bring in dapps-components structure for shared components between the apps

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2321]
- e.g. Identityicon is duplicated between Gavcoin, TokenReg & SignatureReg since we don't want to rely on src/ui (split repos for dapps, independent)

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/dapp-devs Please, confirm within 7 days if this is still on the roadmap for the 1.7 milestone. If so, please comment below, or modify the deadline, or close if fixed.

**Comment by ngotchac** [comment]
@paritytech/ui-devs I don't think that's relevant anymore with UI-2, right?
