### ISSUE TITLE
Cleanup parity/main.rs

### ISSUE THREAD

**Issue by debris** [paritytech/parity#2326]
move [2 expressions](https://github.com/ethcore/parity/blob/84ba75f7cb4dbf434042db4943a896f3d6bbfd08/parity/main.rs#L196-L200) `if sync_main ...` and `if probably_run` here -> [here](https://github.com/ethcore/parity/blob/84ba75f7cb4dbf434042db4943a896f3d6bbfd08/parity/main.rs#L132)

**Comment by debris** [comment]
@adrianbrink It's something easy to start with :)

**Comment by adrianbrink** [comment]
@debris thanks :-) I'll get to it tomorrow :-)

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. Even though @adrianbrink promised to get to it tomorrow :P

@paritytech/core-devs Please, confirm within 7 days if this is still a valid issue. If so, please comment below and add an assignee, or close otherwise.

**Comment by thiagobbt** [comment]
I believe this doesn't apply anymore as parity/main.rs has changed and doesn't contain those expressions anymore.
