### ISSUE TITLE
Account details column family

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#2479]
Store account details directly in a key-value store, with a journalled overlay that allows definitive state queries for any non-ancient block with a single DB lookup..

In-progress at https://github.com/ethcore/parity/tree/code-meta-col

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's not assigned and postponed to 1.9 and beyond.

It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by rphmeier** [comment]
I did finish an implementation of this, but under testing we found that it was actually slightly slower due to increased pruning overhead. I think it's possible to make this into a real optimization, but it would take a lot of refactoring of the pruning code. This is something @krl and I might be working on in a few months.

**Comment by folsen** [comment]
Could be resolved by ParityDB, closing in favor of that.
