### ISSUE TITLE
Update the parity_netPeers API return structure formatting & documentation

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2582]
From #2580

"
It _should_ be ok with the Parity UI in master (accessed via localhost:8080/home/ -> status) and will be for the new UI as well (js branch) since in both cases we only look at the active/connected/max members.

Once merged however I will update the JS branch (specifically the new Parity.js JSAPI to do proper formatting of the newly returned structure as well as update the documentation). Issue to be logged.
"

**Comment by 5chdn** [comment]
Isn't it active / connected / minimum?

Also what return structure does this issue refer to?

     $ curl --data '{"method":"parity_netPeers","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
      {
         "jsonrpc":"2.0",
         "result":{
            "active":0,
            "connected":45,
            "max":256,
            "peers":[ ... ]
         },
         "id":1
      }

**Comment by arkpar** [comment]
In the CLI log the third number is minimum if connected <= minimum, maximum otherwise

**Comment by debris** [comment]
please reopen if still applicable
