### ISSUE TITLE
SecureFixedHash

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#27]
so basically as present secrets are stored as plain old byte arrays e.g. the `H256` struct.
really, there should be a parallel `H256Secret` struct, which rather than storing the 256-bits of data in a plain array, stores it using a specialised secure data type (e.g. https://github.com/stouset/secrets/)
`H256Secret` and its kin should provide a similar api to the corresponding non-secret types (`H256` &c.) but should only be usable with their kin, in order to avoid secrets leaking to disk or sticking around in memory after use.

**Comment by arkpar** [comment]
consider using https://github.com/stouset/secrets/

**Comment by peterjoel** [comment]
From gitter:

gavofyork 23:41
so basically as present secrets are stored as plain old byte arrays
i.e. the H256 struct
really, there should be a parallel H256Secret struct, which rather than storing the 256-bits of data in a plain array, stores it using a specialised secure data type (e.g. https://github.com/stouset/secrets/)

gavofyork 23:44
H256Secret and its kin should provide a similar api to the corresponding non-secret types (H256 &c.) but should only be usable with their kin
in order to avoid secrets leaking to disk or sticking around in memory after use

**Comment by peterjoel** [comment]
The problem here is with packaging libsodium (c library) up with Parity. It's out of my expertise, and I'll leave it for someone else.

**Comment by Liamsi** [comment]
> The problem here is with packaging libsodium (c library) up with Parity. It's out of my expertise, and I'll leave it for someone else.

I don't see why this is related to packaging libsodium with parity. Shouldn't one first try if the proposed lib (https://github.com/stouset/secrets/) is sufficient for this PR (doesn't rely on libsodium)? Could you explain that further? 
Anyways, there are already [Rust bindings](https://github.com/dnaq/sodiumoxide) for libsodium if this was some kind of show stopper.

**Comment by peterjoel** [comment]
@Liamsi wrote:
> Could you explain that further? 

From what I remember, the problem is that both of these libraries require that you install `libsodium` on your system, separately from the Cargo-managed build. This isn't ideal.

But.. this is already a month ago, so I a bit hazy on the details.

**Comment by Liamsi** [comment]
> From what I remember, the problem is that both of these libraries require that you install libsodium on your system, separately from the Cargo-managed build. This isn't ideal.

Thanks for the clarification. I see, [you're right](https://github.com/stouset/secrets/blob/master/src/sodium.rs#L13). 
@gavofyork: Would that be a problem? Currently, the only externally linked lib seems to be evmjit.

**Comment by debris** [comment]
The whole lifetime of secrets is currently [here](https://github.com/ethcore/parity/blob/master/ethstore/src/account/safe_account.rs#L150-L153). So this issue is not so critical.

**Comment by 0x7CFE** [comment]
Pardon me for jumping in. Just wanted to give a [link to a scientific paper](https://www.sigops.org/hotos/hotos17/papers/hotos17-final92.pdf) that studies alternative approach to data safety.

So here's the abstract:

> Rust is a new system programming language that offers a practical and safe alternative to C. Rust is unique in that it enforces safety without runtime overhead, most importantly, without the overhead of garbage collection. While zero-cost safety is remarkable on its own, we argue that the superpowers of Rust go beyond safety. In particular, Rust’s linear type system enables capabilities that cannot be implemented efficiently in traditional languages, both safe and unsafe, and that dramatically improve security and reliability of system software. We show three examples of such capabilities: zero-copy software fault isolation, efficient static information flow analysis, and automatic checkpointing. While these capabilities have been in the spotlight of systems research for a long time, their practical use is hindered by high cost and complexity. We argue that with the adoption of Rust these mechanisms will become commoditized.

Page 4 may be particularly interesting in context of a secret storage.
