### ISSUE TITLE
Use strongly typed MIME types in Dapps and Signer

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#2772]
Currently we use Strings for mime types, we could consider using https://github.com/hyperium/mime.rs

**Comment by rphmeier** [comment]
Made some of this change in #2762, but the JS glue codegen needs to generate `File` instances with a strongly-typed field instead. You have to use the crate directly instead of the `hyper::mime` module which re-exports it in order to make use of the `mime!` macro (which is super useful).

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still realistic to implement _some day maybe_. If so, please comment below and add an assignee, or close otherwise.

**Comment by debris** [comment]
is it still relevant? I see that we use `mime_guess` crate now

**Comment by tomusdrw** [comment]
We do, but not everywhere. I would close for now or move to long term / easy issues.
