### ISSUE TITLE
Handle low bandwidth connections

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#2831]
Make batch sizes for block headers, bodies and receipts dynamic based on the timeout rate.

**Comment by rphmeier** [comment]
(As suggested in #3996, maximum peers could also be made dynamic)

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's neither assigned nor linked to a milestone.

@paritytech/core-devs It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by folsen** [comment]
We don't really want to make any major changes to devp2p, and throttling is already introduced for libp2p. If this issue is still relevant it should probably be described in the context of libp2p and it also needs more details for someone to be able to pick up and work on this.
