### ISSUE TITLE
Compilation feature to disable UI

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#2858]
### Goal
1. `cargo build --release` builds Parity with UI, with the UI using the pre-built assets.
2. `cargo build --release --features build-ui` builds Parity with UI, with the UI being built from source.
3. `cargo build --release --features no-ui` builds Parity without UI
### Solution

Since cargo features are additive we cannot disable a dependency when feature is present.
But:
1. We can include all dependencies as non-optional deps.
2. Each optional dependency can have a `lib.rs` file that looks like that:

``` rust
#[cfg(not(feature = "no-ui"))]
mod lib_optional;
```

The idea is that when such feature is present we can strip all code related to UI from build.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant feature. If so, please comment below and add an assignee, or close otherwise.

**Comment by folsen** [comment]
UI being moved.
