### ISSUE TITLE
Add paper wallet generation for offline storage

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2928]

**Comment by jacogr** [comment]
Duplicate of https://github.com/ethcore/parity/issues/2928

**Comment by bjornwgnr** [comment]
Especially useful as backup of mnemonic phrase when a new account is being created. (print w/o saving?)

**Comment by Tbaut** [comment]
Moving to a new repo https://github.com/parity-js/shell we will not migrate low prio issues. Please reopen if you believe it should be addressed soon.
