### ISSUE TITLE
Use CSS nesting where applicable to DRY up code

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#2986]
Probably a "touch as you go" instead of a "all at once" refactor.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/ui-devs Please, confirm within 7 days if this is still _nice to have_. If so, please comment below and add an assignee, or close otherwise.

**Comment by keorn** [comment]
@jacogr this probably refers to the old UI?
