### ISSUE TITLE
Native trusted signer on Mac OS with fingerprint ID

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3074]
Currently, the trusted signer is done through an authenticated websockets connection into the browser. We could have an additional app (menubar applet would work well) on Mac OS which also managed the job of trusted signer. This would be well-placed to interact with the new macbook pro's touch input bar allowing a user to see a transaction overview on the touch bar and sign it through a fingerprint ID if the account has been previously unlocked.

Maybe use Atom/Electron for swift development and code-reuse from main UI codebase, depending on how easy it is to get at the Apple APIs for touch ID/touchbar.

**Comment by rphmeier** [comment]
A native signer UI in electron which typically pins itself to the taskbar/system tray/etc. should be doable cross-platform

**Comment by derhuerst** [comment]
[`sudo-touchid` uses the `LocalAuthentication` framework](https://github.com/mattrajca/sudo-touchid).
