### ISSUE TITLE
Authentication signing app for Android & iPhone

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3075]
App should allow user to scan an unsigned transaction as a QR code, inspect it, sign it and place the signed transaction as a QR code on the screen of the device.

Requires external accounts #3243 .

UI should include means of knowing which accounts are handled in this way (i.e. owned accounts for which there is no JSON key) and when sending from one, signer would provide unsigned transaction as the QR code (rather than the password entry) and use user's camera to scan the signed QR code.

- [x] Basic desktop QR-code signing app (gav)
- [ ] Port to HTML app on Android
- [ ] Signer UI knows about external accounts and can offer unsigned hex tx-hash and accept hex sig 
- [ ] Signer UI can display QR-code of to-be-signed transaction-hash if external account is to sign it
- [ ] Signer UI can accept (via camera) signature if QR-code used for signing

**Comment by fckt** [comment]
I've just done a simple app as part of my research on ethereum tx format and signing process 
https://github.com/fckt/eth-signer-app

**Comment by debris** [comment]
app repo: https://github.com/paritytech/parity/issues/3075
