### ISSUE TITLE
Enable multicore/thread cargo build

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3079]
The current config build on a single core.

Sample for 8 cores:
```
[profile.release]
debug = false
lto = false
codegen-units = 8
```

**Comment by tomusdrw** [comment]
To read:
https://internals.rust-lang.org/t/default-settings-for-parallel-codegen/519
https://internals.rust-lang.org/t/parallel-codegen-plans/2253/3

Seems that the benefits are not that obvious, @General-Beck might be worth trying it out on our CI setup but for release builds some performance metrics might be required.

**Comment by gavofyork** [comment]
doesn't seem to build any faster with this...

**Comment by rphmeier** [comment]
i believe this just generates the IR in parallel, while our bottleneck is LLVM processing it and then linking everything together

**Comment by chevdor** [comment]
@gavofyork Please note that any change on the build options will trigger a full build at first. So the first build will definitely take longer.

I did not measure the time but on my side (i7), but I saw rustc going from using at most a single core at 100% to using up to the 8 available.

**Comment by General-Beck** [comment]
Maybe `cargo -j $(nproc)`

**Comment by chevdor** [comment]
No nproc on osx

**Comment by 5chdn** [comment]
This issue keeps coming up once in a while. Is it worth keeping this open here?

**Comment by General-Beck** [comment]
@5chdn I think you can close. Solution `cargo -j `
