### ISSUE TITLE
Introduce Directory contract and integrate into address-entry autocomplete

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3091]
Directory contract not strictly necessary: Initially, just enumerating the `Registry::ReverseConfirmed` events should also give a full list of names.

The names can be filtered to those with an associated address (`A` metadata record) and used to autocomplete the address-input box.

Example directory contract:

```
contract Registry {
    function reserved(bytes32 _name) constant returns (bool reserved);
}

contract Directory {
    function Directory(Registry _r) {
        registry = _r;
    }
    
    event Registered(uint index, string name);
    
    modifier only_reserved(string _name) { if (!registry.reserved(sha3(_name))) return; }
    
    function register(string _name) only_reserved(_name) {
        Registered(names.length, _name);
        names.push(_name);
    }
    
    function count() returns (uint) { return names.length; }
    
    function get(uint _i) returns (string) { return names[_i]; }

    string[] names;
    Registry registry;
}
```

**Comment by derhuerst** [comment]
See also #3991.

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon; and _easy_: Can be fixed by copy and pasting from StackOverflow. But it's neither assigned nor linked to a milestone.

It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by ngotchac** [comment]
This has been done in #4066
