### ISSUE TITLE
Minimize address hashing

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#3102]
- Store hash for deleted account entries.
- shortcut hash into trie rather than rehashing.
- hash outside of `note_account_bloom`.

It should be possible to hash each _dirty_ account's address at most once per commit (or even more strongly: produce the address hash for any account affected by the transactions in a given block at most once)

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close otherwise.

**Comment by folsen** [comment]
Closing because we don't know how much this actually affects performance. If we can produce a benchmark or profiling report that says this is a significant issue.
