### ISSUE TITLE
Add sync status (graphical) under status tab

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#3114]
Requires https://github.com/ethcore/parity/issues/3064

**Comment by 5chdn** [comment]
Graphical as in _progress bar_ or similar? It already shows the numeric progress xxx/zzz in footer.

**Comment by rphmeier** [comment]
The idea here was to have a graphical indicator of

`[ancient blocks][missing blocks post-warp][recent blocks]` 
or something like that.
