### ISSUE TITLE
Add ability to define which is the default account

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3135]
Currently, the default account (ie appearing in the list input address field by default) is the last account that was created.

It would be nice to:
1. let the user define its default account
OR
2. let the user define a custom ordering of the accounts and consider the default account as the first according to this ordering
OR
3. use by default the last account that was used

Opinions welcome on what option you would prefer from the 3 above.

**Comment by jacogr** [comment]
May need to look at this in conjunction with the white/gray/black list changes that is coming for the dapps. (Not from a functionality pov, but rather since we need one area where the accounts is to be managed, or at least components shared)

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's neither assigned nor linked to a milestone.

@paritytech/ui-devs It probably needs a re-prioritization, or a proper deadline and an assignee.
