### ISSUE TITLE
Terminate the build when there's no console output for 5 minutes

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#3188]
If someone makes a PR with a deadlocked test it should not block the CI queue.

**Comment by General-Beck** [comment]
switch docker from `aufs` to `overlay2`
need to test

**Comment by jesuscript** [comment]
anyone have any good ideas for how to do this?

**Comment by tomusdrw** [comment]
Check number of lines in the log file periodically and compare with current number of lines?

**Comment by jesuscript** [comment]
This is definitely better than my idea of running a build as subprocess. @General-Beck thought?

**Comment by jesuscript** [comment]
Reducing priority as thanks to other improvements, these stopped being as critical as they used to be. Nonetheless, it's a quick win so makes sense to do sooner rather than later

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's inactive for several months and not linked to a milestone.

@paritytech/ci It probably needs a re-prioritization, or a proper deadline.
