### ISSUE TITLE
Clean up function naming in RPC error module

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#3204]
Since usage is usually `error::foo`, it's redundant and a bit awkward if the function names end with `_error`.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close otherwise.

**Comment by rphmeier** [comment]
still relevant for a few function names, but I don't think anyone's done it because it's an "easy" issue for new contributors.

**Comment by 5chdn** [comment]
We should organize some rust-hack events :)
