### ISSUE TITLE
Ability to register (watch) a contract form a DAPP

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3217]
It would be nice to have in `parity.js` a way to propose a contract watch from a dapp.

The request could look like:
```
{
  name: 'Suggested name for the contract',
  description: 'This contract does this and that.....',
  address: '0x1234...',
  abi: '[.....]',
  tags: ['tag1', ...]
}
```

Obviously, we don´t want DAPPs to register contracts in the back of the user. Such a request shows a popup to the user with the details of the request. 
If the user rejects, well... life goes on :)
If the user confirms, the contract is added to the watched contracts. The user can edit the name, the description and the tags but not the address and the abi.

That would allow for instance users to register (watch) their Multisig Wallets from a DAPP that would only ask for the address.

In general, for DAPPs deploying contracts, it would allow making the user´s life easier and with less copy/paste always prone to errors.

I will propose the same in `web3.js`

**Comment by 5chdn** [comment]
What's preventing you to deploy a contract from a DApp with the existing tools right now?

**Comment by chevdor** [comment]
The goal is not to deploy a contract but to do with code what you do when you decide to watch a given contract in the UI.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
