### ISSUE TITLE
Binary builds should build js from source

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#3248]
CI binary builds should use

`cargo build --release --no-default-features --feature ui`

To include the JS from the repo as opposed to including the js-precompiled repo.

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/ci Please, confirm within 7 days if this is still on the road-map. If so, please comment below, add an assignee, and decide on a deadline; or close otherwise.

**Comment by jacogr** [comment]
Still a valid issues that should be addressed - we have had a number of releases gone bad due to the manual work required with releases and swapping branches. Binary release builds should build completely from source.

**Comment by debris** [comment]
guess I can close it since js has been moved out of parity repo
