### ISSUE TITLE
WIndows installer "advanced" mode

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#3268]
* Sets PATH for CLI
* Disables tray icon
* Installs ethkey and ethstore

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's inactive for more than 6 months and neither assigned nor linked to a milestone.

It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by 5chdn** [comment]
Suggestions from #4058:

> The current behavior of the Windows installer is to ...
>
> - launch Parity after the wizard completes
> - launch a web browser to present a UI
> - configure Parity to start at Windows login
>
> The user has no choice in any of this.  I think this is quite intrusive, and certainly doesn't conform to usual install wizard behavior.  
>
> One way to address this issue would be to add an extra page to the install wizard with 2 check boxes: one that says "Launch Parity now", and another that says "Start Parity at Windows login"  (or something similar).

**Comment by 5chdn** [comment]
We are removing installers.
