### ISSUE TITLE
Warp sync uses too much memory

### ISSUE THREAD

**Issue by diglos** [paritytech/parity#3304]
Hi,

I'm getting a crash testing the --warp option on a raspberrypi 3:

```
Fatal runtime error: out of memory
Illegal instruction
```
I tried to increase the cache but I get the same result.

Attached the full log (debug level).
[parity-1.4-armhf7-20161109.txt](https://github.com/ethcore/parity/files/580654/parity-1.4-armhf7-20161109.txt)

Let me know if you need anything else.

Regards.

**Comment by rphmeier** [comment]
There are definitely a few places where memory footprint while warp syncing could be lessened. I'll take a look into it later, would love to see this working on the pi.

**Comment by diglos** [comment]
Hi,

I tried with the 1.4.3 release. It seems to last a little bit longer and doesn't crash but snapshot syncing stops with the message:

2016-11-16 18:14:52 UTC IO Worker #1 WARN ethcore::snapshot::service  Encountered error during state restoration: Database write failure. Running low on memory perhaps?
2016-11-16 18:14:52 UTC IO Worker #2 WARN ethcore::snapshot::service  Encountered error during state restoration: Database write failure. Running low on memory perhaps?

and resumes the sync in normal mode.

Find attached the debug log.

[parity-warp-armhf-20161116.txt](https://github.com/ethcore/parity/files/595548/parity-warp-armhf-20161116.txt)

Regards.

**Comment by 5chdn** [comment]
This _footprint_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below, and add an assignee; or close otherwise.

**Comment by arkpar** [comment]
Fixed with #5526
