### ISSUE TITLE
Swift shutdown

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#3332]
Ctrl-C should result in faster program exit when syncing.
* `import_verified_blocks` should check exit condition for every block
* Snapshot restoration should check exit condition for every item (i.e. block or state account)

**Comment by rphmeier** [comment]
second point adressed in #3356

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon; and _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. But it's inactive for more than 6 months and neither assigned nor linked to a milestone.

@paritytech/core-devs Please, review this issue within 7 days. It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by rphmeier** [comment]
Slow NAT detection also an issue, reported by @tomusdrw in #4321: 
> ```
>  $ ./target/release/parity
> 2017-01-27 09:15:24  main INFO parity::run  Starting Parity/v1.6.0-unstable-f9eb13b-20170124/x86_64-linux-gnu/rustc1.16.0-nightly
> 2017-01-27 09:15:24  main INFO parity::run  State DB configuration: fast
> 2017-01-27 09:15:24  main INFO parity::run  Operating mode: active
> 2017-01-27 09:15:24  main INFO ethcore::service  Configured for Ropsten using Ethash engine
> 2017-01-27 09:15:25  hyper-client INFO miner  Updated conversion rate to Ξ1 = US$10.49 (11348677000 wei/gas)
> 2017-01-27 09:15:33  IO Worker #1 INFO import  Syncing  #419016 3db9…32dd    170 blk/s  247 tx/s  65 Mgas/s     185+ 1006 Qed    #420221    7/ 7/25 peers    218 MiB db    1 MiB chain    6 MiB queue  798 KiB sync
> ^C2017-01-27 09:15:35  main INFO parity::run  Finishing work, please wait...
> ^C^C^Z
> [1]+  Stopped                 ./target/release/parity
> $ kill %1
> $ kill -9 %1
> [1]+  Killed                  ./target/release/parity
> ```
> 
> It should close fast without waiting for `enode` line to be printed

**Comment by folsen** [comment]
Closing, if there's any more specific blocker to slow shutdown time please open separate issue.
