### ISSUE TITLE
DAPP: Add ability to specify which lib to inject from the manifest

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3352]
```
{
	"id": "YourDappID",
	"name": "My Killer Contract",
	"description": "A DAPP that ...",
	"version": "0.4.2",
	"author": "Chevdor",
	"iconUrl": "images/killerdapp.png",
	"inject": "web3" // web3 | parity | inject
}
```

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
