### ISSUE TITLE
Integrate ethabi

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3380]
- [ ] Merge into parity repo;
- [ ] Use `uint` crate for uint/hash types.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close it otherwise.

**Comment by debris** [comment]
replaced by #6360
