### ISSUE TITLE
Use consensus-specified metric to determine best block

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#3489]
Refactor to make `Blockchain` more general.

Right now it resolves the best chain based on total difficulty, which isn't always going to be the case.

Could be as a method of `Engine`

**Comment by keorn** [comment]
To mark it done it would be good to make difficulty `Ethash` specific or rename it to weight and make it always 1 if only height matters.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close it otherwise.

**Comment by keorn** [comment]
I think its fine to keep it called difficulty for now, can always rename it. Dont see any reason to have ordering by something else than a scalar.
