### ISSUE TITLE
HD wallet support

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3541]
Hierarchical deterministic wallet support.

Two forms of deriving a key, one which allows proof-of-parent (soft), one which does not (hard). Both are allowed. UI/RPC can create derivative keys at will, which yield an address. These addresses can be used to sign with the same security requirements as their root. All previously generated derivative addresses can also be found if the caller has "read access" to that account.

RPCs in `parity_personal`:

- `parity_addDerivativeKey(Address parentKey, Type type, H256 childIndex) returns (address child)`  where `Type` must be one of `"hard"` or `"soft"`.
- `parity_listDerivativeKeys(Address root) returns {hard: {childIndexInRoot: { address: Address, hard: { childIndexInFirstChild: { address: Address, hard: ..., soft: ... }, anotherChildIndexInFirstChild: ... }, soft: ... }, anotherChildIndexInRoot: ... }, soft: ... }`

**Comment by arkpar** [comment]
UI still pending. Also needs to support hardware wallets, i.e Ledger.

**Comment by NikVolf** [comment]
The referenced issue was supposed to be ui for that:
https://github.com/paritytech/parity/issues/3542

not sure what ui supposed to cover raw hd keys on it's own

**Comment by 5chdn** [comment]
should include #4905
