### ISSUE TITLE
Cash keys

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3542]
Follows on from #3541 

Currently ether/tokens stored in a key are replete of privacy - everyone can see these token balances and build a complete and unrefutable transaction history from them.

This uses hard-derivative addresses to hide the transaction history. Basically tokens are not kept in the account itself but in one of more of its derivatives. Whenever tokens are transferred (which may first need consolidating between multiple accounts if no single derivative account has sufficient balance), the remainder of the balance is transferred to one or more newly generated derivative accounts. The order of transfers is randomised.

When viewed in the wallet, balances should be summed across all derivative accounts.

They're called "cash keys", since they're useful only for fungible token-like accounts. This system wouldn't be useful for non-transferable/non-fungible assets like badges.

**Comment by ngotchac** [comment]
As #3541 is closed, what's the status of this issue?
