### ISSUE TITLE
Binary / installer for Alpine Linux (x86_64)

### ISSUE THREAD

**Issue by jesuscript** [paritytech/parity#3565]
Alpine is a very skinny Linux that plays very well with Docker. It would be *really* nice to have binaries or an installer package for it, if possible.

**Comment by 5chdn** [comment]
This _enhancement_ labelled issue is inactive since last year. 

@paritytech/ci Please, confirm within 7 days if this is still _nice to have_ a binary for alpine. If so, please comment below and add an assignee, or close it otherwise.

**Comment by jesuscript** [comment]
Yes, it would be still nice to have this

**Comment by maxbaluev** [comment]
It will be awesome

**Comment by dan-turner** [comment]
Any progress on this?

**Comment by andresilva** [comment]
https://gist.github.com/andresilva/ea8c77edcb66f646f298f281b973e4ec

I've built a docker image with this and it seems to be working properly.
