### ISSUE TITLE
Bind to extip address

### ISSUE THREAD

**Issue by rapsta** [paritytech/parity#3607]
ethereum port is hardcoded to 0.0.0.0 in configuration.rs 
`let listen_address = Some(SocketAddr::new("0.0.0.0".parse().unwrap(), port));`
Should it not equal to extip:<IP> if allow_ips is set to "public" ?

Or how else i can force parity to bind to specific IP-address without to change this configuration.rs line on each update?

**Comment by arkpar** [comment]
extip can't be used because it is supposed to be an external gateway address. I.e. if your node is behind a public-facing router you put router's address there. We could add a CLI for listen address though.

**Comment by rapsta** [comment]
Thank you for another example, extip as listen_address makes in this case, of course, no point.

A CLI option might be helpful, at the moment I solve my acute problem with an iptables REDIRECT.

**Comment by 5chdn** [comment]
Should work with --nat extip:<IP>

**Comment by tomachinz** [comment]
How about

`--nat extip:domainname.com
`
Possible to use domain names in this spec?
