### ISSUE TITLE
Add warning when adding to the address book a contract that is already watched 

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3684]
- watch a contract
- add it to the address book

=> the contract is gone from the contracts tabs (the opposite does the same)

Warning the user or allowing to have it in both places would be nice.

**Comment by derhuerst** [comment]
I made `AddAddress` (which is the modal for adding an address book entry) add a `contact: true` flag in `jr-contact-flag`. However, `api.parity.setAccountMeta` sets metadata *by address*, so it doesn't seem to be possible to multiple accounts with the same address right now.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since last year, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by 5chdn** [comment]
From: #5680

> 1. Watch a contract in the Contracts page.
> 2. Add that contract as an address in your address book.
> 3. Forget the address from your address book.
> 4. Notice that the contract is no longer watched on the Contracts page.

**Comment by MicahZoltu** [comment]
Curious why the user can't both watch an contract and have it in their address book?  The address book shows transactions history while he contract shows events.  If you want to see both, you have to add to both.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
