### ISSUE TITLE
Node stops accepting new RPC HTTP connections

### ISSUE THREAD

**Issue by etherchain-org** [paritytech/parity#3687]
After a while some of my nodes stop accepting RPC requests via HTTP. I cannot find any errors in the standard log messages. When I try to call an RPC method via CURL I just get the following error:

```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' localhost:8546
curl: (7) Failed to connect to localhost port 8546: Connection refused
```

This is on Parity v1.4.5-beta-a028d04-20161126

After restarting the node the RPC service is available again:
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' localhost:8546
{"jsonrpc":"2.0","result":"Parity//v1.4.5-beta-a028d04-20161126/x86_64-linux-gnu/rustc1.13.0","id":1}
```

**Comment by tomusdrw** [comment]
Could you run with `-lhyper=trace` and provide the logs when it happens? Is it the same set of nodes suffering from #3545 ?

**Comment by etherchain-org** [comment]
No, it is a different set of nodes compared to #3545. I have restarted the node with the tracing flag and will report back when it happens again.

**Comment by 5chdn** [comment]
@etherchain-org any news on this?
