### ISSUE TITLE
Windows version unusable

### ISSUE THREAD

**Issue by SteffenIvanhoe** [paritytech/parity#3688]
Tried again to install on Windows 10. Still not usable. Delivers "Unable to make a connection to the Parity Secure API" as popup menu on a web page. Recommends to "run parity signer new-token"??? What exactly does that mean? Why should I do that? Don't know how to do that (actually I probably would be able to find the parity.exe somewhere on my PC). But this is a very user unfriendly approach. As soon as you provide a version which does not require to be an IT specialist I might try again.

**Comment by tomusdrw** [comment]
Thanks for the report, we are working hard to make this as smooth as possible. Actually version `1.5` should never display this message for standard use cases.

The reason for it was that we've focused on securing the connection in the first place, currently solving the usability.

To generate the token you indeed need to use the `Command Line` currently:
```bash
cd "C:\Program Files\Ethcore\Parity"
parity.exe signer new-token
```

**Comment by TbLtzk** [comment]
@SteffenIvanhoe did you try to compile it yourself or just download the binary for windows?

I've parity running on windows 10 and it was a really smooth experience. I have version v1.4.4-beta-a68d52c-20161118/x86_64-windows-msvc/rustc1.13.0 installed from https://github.com/ethcore/parity/releases/tag/v1.4.4

**Comment by SteffenIvanhoe** [comment]
I have just downloaded the binary. I have checked that for someone else who is not an IT guy but interested in Ether and a good wallet. I thought Parity with the new UI and its fast sync would do it. But I was wrong. It is still not usable for "normal" people. (I have recommended my friend not yet to deal with Ether. Too many things still that just don't work.)

**Comment by 3esmit** [comment]
For obtaining this security token do the following:
1. Press `<Windows>+R`
2. Enter `cmd /k "C:\Program Files\Ethcore\Parity\parity.exe" signer new-token` 
3. Copy the 16 alfanumeric code by pressing `Ctrl+M` or right clicking the prompt and clicking on "select" option
4. Select the 16 alfaumeric code and right click the prompt
5. Paste that into the Parity UI at your internet browser.

**Comment by SteffenIvanhoe** [comment]
Thank you for taking the time to explain that. But I have already uninstalled Parity (I mainly checked it for someone else).

I brought this issue up because I wanted to let the developers know that the system as is is still unusable for non-programmers. Your algorithm does not change that.

I believe that the facts that the default Mist wallet has stopped synchronizing the blockchain two months ago and the alternative Parity wallet is still in alpha stage together play a role in why some non-technical people got frustrated and leave the ecosystem. At least that is what I see in my immediate vicinity.

**Comment by 3esmit** [comment]
Thanks for sharing your experience. If you willing to try parity again, come chat with us in https://gitter.im/ethcore/parity and I will be glad in helping you. 

It's planned to automatize the token signer, but for now this is a necessary step in order to garantee the security of your wallet.

**Comment by 5chdn** [comment]
Closing question as answered.
