### ISSUE TITLE
Expected value line 1 column 1

### ISSUE THREAD

**Issue by boehla** [paritytech/parity#3693]
I already had synced ethereum blockchain.
Then I runned parity with parameter "--chain=classic" and imported here some wallets and make payouts.

Today I want do ETH payouts, but I cant start parity now:
`C:\Users\daniel\Desktop>"C:\Program Files\Ethcore\Parity\parity.exe"`
`expected value at line 1 column 1`

with parameter "--chain=classic" it is running fine.

Running it on Windows 10. Latest Parity 1.4.5.

**Comment by rphmeier** [comment]
Haven't been able to reproduce this locally yet. My guess is it probably has something to do with the config.toml

**Comment by arkpar** [comment]
@boehla could you please attach here the following files?
C:\Users\daniel\.parity\906a34e69aec8c0d\user_defaults
C:\Users\daniel\.parity\906a34e69aec8c0d\network/nodes.json

**Comment by 5chdn** [comment]
@boehla can you still reproduce this issue?
