### ISSUE TITLE
UI: Automatically tag accounts and contracts

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#3696]
This is not an issue but an improvement.

It would be awesome to add a tag to any:
- created account
- account added to the addres book
- watched contract
- deployed contract

The tag being the current chain:
- homestead
- morden
- ropsten

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
