### ISSUE TITLE
Warn user in UI when sending transaction before ancient blocks are downloaded

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#3802]
Will need #3064

**Comment by rphmeier** [comment]
As discussed with @jacogr and @arkpar earlier.

**Comment by 5chdn** [comment]
Is this covered by this dialog? 

![screenshot at 2017-05-18 15-25-20](https://cloud.githubusercontent.com/assets/15729797/26204174/4cb5a5fa-3bde-11e7-8ea3-aba413c330cd.png)

Or should there be any additional warning?
