### ISSUE TITLE
Stop-CMD for parity daemon

### ISSUE THREAD

**Issue by SinErgy84** [paritytech/parity#3824]
Hey guys,
it would be nice to have an command for a clean stop of the running daemon instead of greping for the parity PID and executing `kill -15 PID` (sigterm)

**Comment by rphmeier** [comment]
This is a bit tricky with the library we currently use for daemonization (it supports start but not stop). If you require arbitrary starting and stopping of the daemon I recommend writing a system service file for now -- we might add this at some point. We have instructions on how to do so with `systemd` in our README.

**Comment by tomachinz** [comment]
how about this? im on Mac. 

kill -HUP PID
