### ISSUE TITLE
QR code to display the unsigned transaction hash & desired sender

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3869]
This goes hand in hand with #3243 and #3870 .

(Exactly) as mocked up in https://jsfiddle.net/7sutwwfy/1/#&togetherjs=dcJm6MIgF4

Note the format for providing the QR code is `01<unsigned transaction hash><sender address>`. It may be encoded in either hex or as raw bytes. Since JS has been known to do weird things when you put raw bytes into a string, if you use raw bytes encoding, be sure to check that it is reversible first. The JSFiddle does all of this.

**Comment by ngotchac** [comment]
This is done
