### ISSUE TITLE
Accept QR code for transaction signing

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3870]
This goes hand in hand with #3243 and #3869. Having provided the QR-code for the unsigned transaction data, it should turn on the user's camera to allow them to show the signed transaction back as a 65 byte QR code.

Format is `41<r><s><v>` with `v` being either 27 or 28, in line with the Ethereum transaction standard. Signer should be able to construct the entire signed transaction from that (using ethereumjs-tx npm package) and fire it off with `sendRawTransaction` RPC.

**Comment by ngotchac** [comment]
This is done
