### ISSUE TITLE
DRY up account creation validation with store

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#3887]
https://github.com/ethcore/parity/pull/3854

DRY-up the error checks & validation across the different parts and move to a store - validation is duplicated in the different sections

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/ui-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close it otherwise.

**Comment by ngotchac** [comment]
This can be closed, the account creations have been refactored already.
