### ISSUE TITLE
Unify parts of ethcore::Client and ethcore-light::Client

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#3905]
Operating mode, verification queue, certain blockchain APIs, importing to transaction queue are all shared.

These should be possible to unify somehow under a generic parameter similar to `queue::Kind` but more general.

**Comment by rphmeier** [comment]
Relevant: #4228

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close it otherwise.

**Comment by rphmeier** [comment]
Very relevant, but not sure how feasible.

**Comment by folsen** [comment]
@tomaka Is this something you intend to work on? I would close this in favor of something more specific that is directly actionable by a developer, right now it's a very general "refactor the code" type issue and isn't possible to pick up without deep knowledge and mentoring.

**Comment by tomaka** [comment]
@folsen I didn't look into this issue and have no specific plan.
