### ISSUE TITLE
External explorer links in UI should be chain-specific

### ISSUE THREAD

**Issue by arvicco** [paritytech/parity#3910]
Trying to play with Parity UI now, using "--chain=classic". All the tx/acct links point to etherscan regardless of "chain" option, instead of gastracker...

**Comment by tomusdrw** [comment]
We have chain-specific links for Ethereum mainnet and testnet, seems like adding a detection for Classic chain (and Classic testnet).

Related line:
https://github.com/ethcore/parity/blob/master/js/src/views/Signer/components/TxHashLink/txHashLink.js#L35

PRs welcome.

**Comment by Tbaut** [comment]
Moving to a new repo https://github.com/parity-js/shell we will not migrate low prio issues. Please reopen if you believe it should be addressed soon.
