### ISSUE TITLE
Contract entry fields should be more explicit

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#3925]
# For entering data:

Hash entry fields:
- Should be configurable to right or left packing when data given is less than 32-bytes.
- Should make it clear when interpreting data entry as hex (`0x` prefixed or not).
- Should make it clear when interpreting data entry as raw ASCII/UTF-8 encoded data.

Numeric entry fields:
- Should make it clear when interpreting the input as binary (`0b` prefixed), hex (`0x`-prefixed), decimal, octal (`0o`-prefixed).
- Should allow currency units to be given (`5 finney`, `100ether`).

Boolean entry fields:
- Should be a simple, standard [_|#] switcher (rather than a drop down as at present).

Address entry fields should work as standard.

# For displaying data:

Hash-entry fields:
- Should auto-detect addresses (last 12 bytes zero) and display as such, making the format clear.
- Should auto-detect ASCII (left-padded, at least one zero on right, bytes all in range 0x20-0x7f) and display as such, making the format clear.
- Should auto-detect raw hex, left or right padded, remove/reduce visual strength of zeroes and make padding clear.

Numeric entry fields:
- Should default to decimal for sensible numbers (<50000), hex otherwise and make encoding clear.
- Should provide a means of switching to base-encoding of user's choice, even when displayed as something else.
- Should auto-detect currency amounts (`n > 10**9 && n % 10**9 == 0`) and display then with highest unit that allows full precision.

**Comment by ngotchac** [comment]
We also might want to think about time/timestamps : would be useful in contract view to display timestamps as readable date (could be as simple as `if date(input * 1000) is in now +- 5 years => display as date`).

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since March and not assigned yet.

@paritytech/ui-devs Please review the 1.8 deadline and add an assignee within 7 days, thanks!
