### ISSUE TITLE
Get rid of `Weak` in RPC

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#3958]
Afair we used `Weak` because the servers were not closed correctly upon dropping and it kept the whole `Client` running.

I'm pretty sure that the servers are closing correctly now, so usage of `Weak` shouldn't be necessary.

**Comment by rphmeier** [comment]
It should actually be possible to use references instead given that the services are all created by the time the RPC is initialized.

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days if this is still relevant. If so, please comment below and add an assignee, or close it otherwise.

**Comment by tomusdrw** [comment]
Yes, would be nice to have. Labelled as `Q2-easy` - it's a good task for hackathon or a beginner wanting to contribute.

**Comment by andrebeat** [comment]
I think issue can be closed.

**Comment by tomusdrw** [comment]
Correct, thanks! Resolved by #5688
