### ISSUE TITLE
Windows installer gives user no choice to auto-launch Parity

### ISSUE THREAD

**Issue by russdirks** [paritytech/parity#4058]
The current behavior of the Windows installer is to ...

- launch Parity after the wizard completes
- launch a web browser to present a UI
- configure Parity to start at Windows login

The user has no choice in any of this.  I think this is quite intrusive, and certainly doesn't conform to usual install wizard behavior.  

One way to address this issue would be to add an extra page to the install wizard with 2 check boxes: one that says "Launch Parity now", and another that says "Start Parity at Windows login"  (or something similar).

**Comment by 5chdn** [comment]
Agreed, adding your suggestions to #3268.
