### ISSUE TITLE
Node crawler

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#4124]
Introduce a mode or a separate tool to connect to every available new peer and collect peer and chain information. 
Ping previously seen nodes periodically to see if they are still alive.
Dump all info including last seen timestamp to a json file.

**Comment by gavofyork** [comment]
*should fake protocol credentials to ensure it stays connected long enough to get peer info.

**Comment by gavofyork** [comment]
you ok taking this, @NikVolf ?

**Comment by mtbitcoin** [comment]
Perhaps couple this with some sort of data throttling? If we had 10k clients connected and was sending/receiving at full speed I could see this being an issue

**Comment by Roxxik** [comment]
I'm fiddling with the RLPx protocol. I just got started with this guide[0] and reimplemented[1] it in rust. I want to extend it further and my next step would be parsing of answers and then tackling neighbour discovery.

I'm only working on it in my free time, so you won't see it taking off too quickly, but it would be nice if this wouldn't just be an experiment, but also useful to others, so comment on it and point me to some features / protocol details that would be nice to have, and I'll see what I can do ;)

[0]: https://ocalog.com/post/10/ & https://ocalog.com/post/18/
[1]: https://github.com/Roxxik/ping_ether
