### ISSUE TITLE
User stats

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#4139]
Need ways of gathering some user stats. Download button clicks? @jesuscript could you look into that?

**Comment by jesuscript** [comment]
sorry didn't see this one. I'll see if we can get download rates from cloudfront or elsewhere. anything else?

**Comment by gavofyork** [comment]
not for now

**Comment by 5chdn** [comment]
- [Cache Statistics](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cache-statistics.html)
- [Popular Objects](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/popular-objects-report.html)

**Comment by debris** [comment]
@jacogr @jesuscript @tomusdrw what is the status of it?

**Comment by 5chdn** [comment]
"GDPR"? :D

**Comment by Tbaut** [comment]
GDPR is about some user info, we still can have a Mamota (ex Piwik) GDPR compliant to collect anonymous data...
