### ISSUE TITLE
Change all references to LES protocol to different subprotocol ID

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#4213]
To support our incompatible extensions/structures. Maybe `pls` (Parity Light Subprotocol)?

**Comment by 5chdn** [comment]
What does this mean? PLS?

**Comment by rphmeier** [comment]
Initially there was LES support in Parity, but it was a) unspecified as implemented in Geth and b) unsuitable to the direction we wanted to take the light client. We branched this off into the `PIP` protocol since.

**Comment by rphmeier** [comment]
I think this can be closed.
