### ISSUE TITLE
.gitlab-ci clean-up

### ISSUE THREAD

**Issue by jesuscript** [paritytech/parity#4226]
we can move the code from the `scripts` blocks into scripts, e.g.

```yaml
  script:
    - cargo build -j $(nproc) --release --features final $CARGOFLAGS
    - strip target/release/parity
    - export SHA3=$(target/release/parity tools hash target/release/parity)
    - md5sum target/release/parity > parity.md5
    - sh scripts/deb-build.sh amd64
    - cp target/release/parity deb/usr/bin/parity
    ...
```

can become

```yaml
  script:
    - ./scripts/run-build.sh
```

with run-build.sh containing

```bash
#!/bin/bash
cargo build -j $(nproc) --release --features final $CARGOFLAGS
strip target/release/parity
export SHA3=$(target/release/parity tools hash target/release/parity)
md5sum target/release/parity > parity.md5
sh scripts/deb-build.sh amd64
cp target/release/parity deb/usr/bin/parity
...
```

If nothing else, it will make the CI file much cleaner, as it's become a bit of a monster

**Comment by 5chdn** [comment]
@paritytech/ci anyone willing to do this?

**Comment by gooodmorningopenstack** [comment]
I can give it a hand, it seriously needs to be refactored/outsourced with scripts.
Also, we can rationalize the `.gitlab-ci.yml` file with YAML anchors to not repeat the same blocks.

**Comment by 5chdn** [comment]
@gooodmorningopenstack see #6600 before you start working on this :)

**Comment by gooodmorningopenstack** [comment]
Thanks, I see that it's almost done :+1:

**Comment by 5chdn** [comment]
f400a7e1718dddd77f4d60f65c91134dbbfb3a4a
