### ISSUE TITLE
Transactions with `min_block` should warn that further transactions need to wait that block.

### ISSUE THREAD

**Issue by 3esmit** [paritytech/parity#4230]
When I set a scheduled transaction to `min_block` all my other further transactions in that account are not being transmitted.

**Comment by rphmeier** [comment]
Subsequent transactions will have a higher nonce and won't be executable until the transaction waiting for `min_block` has been broadcasted/mined. Might be nice to include a small warning in the UI.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
