### ISSUE TITLE
Registry Middleware not conforming to codebase standards

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4246]
```
  const middleware = [
    settings.toMiddleware(),
    signer.toMiddleware(),
    errors.toMiddleware(),
    certifications.toMiddleware(),
    chain.toMiddleware(),
    registry
  ];
```

**Comment by 5chdn** [comment]
This issue is labelled with _trivial_: Can be fixed by anyone with access to a computer. But it is inactive for more than 3 months and neither assigned nor linked to a milestone.

@paritytech/ui-devs Please, review this ticket within 7 days, assign it and decide on a deadline. Thanks :)
