### ISSUE TITLE
Weird panic from Parity main when --help output piped through malformed 'grep' command

### ISSUE THREAD

**Issue by tjayrush** [paritytech/parity#4295]
I entered this command on my command line because I wanted to try to figure out how to do tracing:

>> parity --help | grep -i

It's malformed because I forgot to include what I was searching for.

Grep complained, but then parity also cored dumped with an ugly message. I thought I should report it. It's not a killer bug or anything, but it fails less gracefully than I would think it should with this message:

thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', ../src/libstd/io/stdio.rs:650
stack backtrace:
   1:        0x105f186ca - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
   2:        0x105f1fd8f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
   3:        0x105f1e47f - std::panicking::default_hook::h5897799da33ece67
   4:        0x105f1eab6 - std::panicking::rust_panic_with_hook::h109e116a3a861224
   5:        0x105f1e954 - std::panicking::begin_panic::hbb38be1379e09df0
   6:        0x105f1e872 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
   7:        0x105f0d6f0 - std::io::stdio::_print::he48522be5b0a80d9
   8:        0x105651cb7 - docopt::dopt::Error::exit::h6d74aa76313a7d2a
   9:        0x10550f049 - parity::main_direct::h29f665ab518f467e
  10:        0x10551136f - parity::main::he6796bb79ca73b7d

**Comment by svyatonik** [comment]
https://github.com/rust-lang/rust/issues/24821

**Comment by 5chdn** [comment]
Seems to be fixed upstream.

    parity --help | grep -i 
    Usage: grep [OPTION]... PATTERN [FILE]...
    Try 'grep --help' for more information.
