### ISSUE TITLE
Rollback database to the specific block/hash (cli command)

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#4324]
`parity rollback <hash/number>`

**Comment by maciejhirsz** [comment]
This might be a good one for me to pick up.

**Comment by maxidev** [comment]
Is there 'rollback' subcommand working on any version? 
Regards.

**Comment by 5chdn** [comment]
@maxidev this was never done.

**Comment by gituser** [comment]
Please please please make this feature!!!
It will save millions of hours time and save your hardware.

Monero automatically switches to the proper chain if you upgrade the software or you can pop certain amounts of blocks from the blockchain and start from certain number.

This is especially useful if you forgot to update your client at the time of the fork.

**Comment by benjaminbollen** [comment]
I can echo this would be a useful feature to have :); I just forgot to update my ropsten node :)

**Comment by joshua-mir** [comment]
@benjaminbollen this is in master/nightly, implemented in #9782
