### ISSUE TITLE
Thread panic when next block difficulty goes negative for certain parameters

### ISSUE THREAD

**Issue by lgpawel** [paritytech/parity#4370]
With the post-Homestead difficulty evolution function, if difficulty bound divisor is less than 99, and the block interval is large enough, then the next block's difficulty would be negative before taking into account the minimum difficulty. This should not lead to any unexpected behaviour, and also low values of the divisor may be useful for testing purposes. However, it causes Parity to crash.

Today's version `Parity/v1.6.0-unstable-27d00f6-20170131/x86_64-linux-gnu/rustc1.14.0` crashes (after turning on ethminer) for a chainspec that has Homestead transition at 0, divisor at `0x60` = 96 < 99, and genesis block time stamp at the Unix epoch. The full spec and crash log are here: https://gist.github.com/lgpawel/832a5feabfb6e397de879603877b68e6

When I just change `0x60` to `0x66` in the spec, the crash does not occur and mined block start to flow in.

**Comment by 5chdn** [comment]
This issue is labelled with _panic_: The client panics and exits without proper error handling. It's inactive for several months and neither assigned nor linked to a milestone.

@paritytech/core-devs Please, assign a developer to this issue and decide on a deadline within 7 days.

**Comment by Vurich** [comment]
Closed by https://github.com/paritytech/parity/pull/5975.
