### ISSUE TITLE
Make ethkey::Secret more compatible with other types

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#4402]
`ethkey` uses implements `Secret` as an `H256` which makes a valid secret key for SECP256k1, but it's not fully interoperable with `H256` types, making it more painful than needs be to use in tests &c.

**Comment by tomusdrw** [comment]
Seems that it already uses the same types? https://github.com/ethcore/parity/blob/master/ethkey/src/lib.rs#L52

`Secret` was refactored some time ago to prevent unintentional panics, since not every `H256` is a valid Secret:
https://github.com/ethcore/parity/pull/4119
https://github.com/ethcore/parity/pull/4159

**Comment by gavofyork** [comment]
it uses `Secret`, but thats a different `Secret` to that used in `ethcore`. it doesn't provide any sensible means of interoperating between the two. furthermore it doesn't effectively distinguish itself. if it really is a `ValidSecret`, it should be named as such and have proper i/o routes to the types that are used everywhere else.

**Comment by rphmeier** [comment]
`Secret` is a good enough name. The instantiation of the type should imply validity, no reason to be redundant about it

**Comment by tomusdrw** [comment]
I'm pretty sure we have just one `Secret` in the entire codebase and it's actually always imported from `ethkey`.

**Comment by NikVolf** [comment]
btw, `Public` should be also refactored with the same inner type + validation
because not every `H512` is a valid public key (in fact, most of `H512` are not), because it is made of two point coordinates that must be on secp256k1 curve

**Comment by tomusdrw** [comment]
There is `Secret::from_slice(&hash).unwrap()`

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. A patch is available but _inprogress_ for several months now without activity. 

Please check if the 1.8 deadline is still realistic :)

**Comment by debris** [comment]
I already started working on unifying [`ethereum-types`](https://github.com/paritytech/primitives) in all of our projects. It will be done in 1.10 and, will resolve this issue
