### ISSUE TITLE
Integrate coveralls with gitlab

### ISSUE THREAD

**Issue by jesuscript** [paritytech/parity#4445]

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's inactive for several months and neither assigned nor linked to a milestone.

@paritytech/ci It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by General-Beck** [comment]
https://codecov.io/gh/paritytech
https://github.com/paritytech/parity/pull/7593
