### ISSUE TITLE
Nice tutorial

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#4457]
![image](https://cloud.githubusercontent.com/assets/138296/22697933/f9d6449a-ed20-11e6-92d2-1afafaba86ea.png)
![image](https://cloud.githubusercontent.com/assets/138296/22691408/5c39c5a8-ed08-11e6-99cb-4390480a501f.png)

![image](https://cloud.githubusercontent.com/assets/138296/22697890/e1677726-ed20-11e6-9a64-c1832d2c36bf.png)
![image](https://cloud.githubusercontent.com/assets/138296/22694357/e9eae790-ed14-11e6-898b-932b56847a18.png)
![image](https://cloud.githubusercontent.com/assets/138296/22694526/9f1bf442-ed15-11e6-9e46-f3752f479b76.png)
![image](https://cloud.githubusercontent.com/assets/138296/22694918/fa77761c-ed16-11e6-9d18-7431c79eceb3.png)
![image](https://cloud.githubusercontent.com/assets/138296/22697591/e779b292-ed1f-11e6-8beb-2ff654e6ac02.png)
![image](https://cloud.githubusercontent.com/assets/138296/22697729/62243e2c-ed20-11e6-931a-1693dd865837.png)

![image](https://cloud.githubusercontent.com/assets/138296/22700240/ee7d922c-ed27-11e6-8976-25acd1ffdecb.png)
![image](https://cloud.githubusercontent.com/assets/138296/22700625/44b820f2-ed29-11e6-8fae-125303b677ce.png)
![image](https://cloud.githubusercontent.com/assets/138296/22701287/41c6e4f8-ed2b-11e6-94d9-d6b5e58cb911.png)
![image](https://cloud.githubusercontent.com/assets/138296/22701622/26a80d68-ed2c-11e6-8720-946e311a9b34.png)
![image](https://cloud.githubusercontent.com/assets/138296/22704760/d7468bcc-ed36-11e6-8411-320791d107e8.png)

![image](https://cloud.githubusercontent.com/assets/138296/22707674/8ca663f2-ed41-11e6-935b-1916fe9b30b6.png)
![image](https://cloud.githubusercontent.com/assets/138296/22707693/9726af26-ed41-11e6-99ae-ec706630ca32.png)
![image](https://cloud.githubusercontent.com/assets/138296/22708739/69cfdf9e-ed45-11e6-91aa-d01d440a25c7.png)
![image](https://cloud.githubusercontent.com/assets/138296/22709662/8e12672a-ed48-11e6-96a3-be0065ff8cbe.png)
![image](https://cloud.githubusercontent.com/assets/138296/22710003/c4168634-ed49-11e6-94af-177683da719d.png)
![image](https://cloud.githubusercontent.com/assets/138296/22710016/cad4cda0-ed49-11e6-9257-4dbd1885dc13.png)
![image](https://cloud.githubusercontent.com/assets/138296/22710059/f1572b8a-ed49-11e6-874a-7de1ff2ca519.png)

![image](https://cloud.githubusercontent.com/assets/138296/22712813/2e36a65c-ed54-11e6-896d-c123bd95d3d5.png)
![image](https://cloud.githubusercontent.com/assets/138296/22713122/2c8146e0-ed55-11e6-8809-c5329cf89bae.png)
![image](https://cloud.githubusercontent.com/assets/138296/22715524/3f1545cc-ed5f-11e6-9536-f7fd9fed423d.png)
![image](https://cloud.githubusercontent.com/assets/138296/22715677/1e3e2be2-ed60-11e6-9609-16475996e7f3.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/22750413/badb3b72-edfe-11e6-810b-9bcdb47a20a8.png)

**Comment by derhuerst** [comment]
FYI [the tutorial lives in the wiki right now](https://github.com/ethcore/parity/wiki/Tutorial-Part-I).

**Comment by 3esmit** [comment]
Still in progress, @derhuerst, see https://github.com/ethcore/parity/wiki/Tutorial-Part-VI

**Comment by 5chdn** [comment]
What's exactly missing here?

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24324260/8d166a56-1183-11e7-8c5f-98db20bfe232.png)
![image](https://cloud.githubusercontent.com/assets/138296/24324265/a612047a-1183-11e7-9536-83324ad97465.png)
![image](https://cloud.githubusercontent.com/assets/138296/24324263/9f3918fa-1183-11e7-8cbd-d04527addcd1.png)
![image](https://cloud.githubusercontent.com/assets/138296/24324268/b1a21bcc-1183-11e7-9154-5d2a90c69334.png)

**Comment by gavofyork** [comment]
the rest of the tutorials

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24465379/1a275082-14ad-11e7-88f4-140eb2c3ab74.png)
![image](https://cloud.githubusercontent.com/assets/138296/24465867/014d519a-14af-11e7-83f1-f39fa46a898a.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24588110/807cec58-17c2-11e7-8e08-610f972c63ed.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24588762/3e436f08-17cf-11e7-9d78-e7e6b528514a.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24861206/2a4a5046-1df8-11e7-8fd9-fc8ff9102c1c.png)
![image](https://cloud.githubusercontent.com/assets/138296/24861213/329d70d4-1df8-11e7-8251-624df30f2458.png)
![image](https://cloud.githubusercontent.com/assets/138296/24861219/397b32ce-1df8-11e7-8297-5bf3e8fc6a72.png)
![image](https://cloud.githubusercontent.com/assets/138296/24864065/5e3644ae-1e03-11e7-9046-80d58a84bdb3.png)
![image](https://cloud.githubusercontent.com/assets/138296/24864351/3a4fbb28-1e04-11e7-8879-6f1538af2cb8.png)
![image](https://cloud.githubusercontent.com/assets/138296/24864358/426e94a0-1e04-11e7-9253-8e3423268892.png)
![image](https://cloud.githubusercontent.com/assets/138296/24864365/47c02b30-1e04-11e7-88c6-79f5ef31d4f4.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24910906/88da3b5e-1ec9-11e7-9060-5776f20e89d3.png)
![image](https://cloud.githubusercontent.com/assets/138296/24910910/8ba7f420-1ec9-11e7-95a1-2aa5596709a4.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24923831/18de9f82-1ef3-11e7-84d2-a4ee1c5cbe78.png)
![image](https://cloud.githubusercontent.com/assets/138296/24924134/060692d8-1ef4-11e7-8ee4-a79c5a1055b4.png)
![image](https://cloud.githubusercontent.com/assets/138296/24924187/369c9ca8-1ef4-11e7-871f-d9bca011377f.png)

![image](https://cloud.githubusercontent.com/assets/138296/24924146/11ad5bd0-1ef4-11e7-9a99-11ad3f5ff80b.png)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/24996522/794af884-2033-11e7-8762-9e4e30d60967.png)

**Comment by 5chdn** [comment]
Closing because the tutorial is complete.
