### ISSUE TITLE
Flag --jsonrpc-cors should be improved to pre-process URL

### ISSUE THREAD

**Issue by 3esmit** [paritytech/parity#4476]
`--jsonrpc-cors "http://ethereum.github.io/"` will not work, instead you need to correctly specify `--jsonrpc-cors "http://ethereum.github.io"`

Also https://github.com/ethcore/parity/wiki/Private-development-chain suggests `--jsonrpc-cors "https://ethereum.github.io/browser-solidity"`, and AFAIK should not be `https` and will not work due `/browser-solidity` in URL.

**Comment by tomusdrw** [comment]
It should also validate the input, suggesting expected format. Affected options:
`--jsonprc-cors`, `--jsonrpc-hosts`, `--dapps-hosts`, `--dapps-cors`
