### ISSUE TITLE
Contract deployment doesn't allow editing of ETH value, gas & gasPrice

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4483]
Editing of gas/gasPrice is possibly in Signer, but should be in dialogs to mirror existing functionality.

**Comment by 3esmit** [comment]
Should also allow editing the send value.

**Comment by jacogr** [comment]
My mistake, I misread another issues that I thought covered the ETH value issues, on closer reading, it does not.

**Comment by ngotchac** [comment]
(from #4396: With payable constructor contract deployment wizard should allow you to specify value transfered with contract creation. Currently you cannot do this.)
