### ISSUE TITLE
Refactor signer to use futures instead of callbacks

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4490]
Details: https://github.com/paritytech/parity/pull/4485#discussion_r100246661

**Comment by 5chdn** [comment]
What are _futures_ in this context?

**Comment by debris** [comment]
https://crates.io/crates/futures

**Comment by 0x7CFE** [comment]
What's the status on this issue?

**Comment by kirushik** [comment]
@0x7CFE I've picked it up, and working on some final touches in #6689.

Let's chat in Matrix maybe if you want to join?
