### ISSUE TITLE
Trezor hardware wallet support

### ISSUE THREAD

**Issue by mcgravier** [paritytech/parity#4500]
While quite popular in cryptocurrency community, the only service that supports Trezor for Ethereum at the  time is Myetherwallet - it would be far better to have direct implementation in Parity

**Comment by rphmeier** [comment]
#4486 lays the foundation for other HW wallets, probably will come decently soon afterwards. The main blocker is just that we haven't got a Trezor wallet to test with.

**Comment by 3esmit** [comment]
@prusnak @slush0 could donate a Trezor wallet to Parity team, and even collaborate in the development.

**Comment by prusnak** [comment]
Has Ethereum foundation run out of all its money?

**Comment by rphmeier** [comment]
@prusnak Not too familiar with the foundation's financial situation; they might be able to answer that better. The donation bit wasn't meant to be interpreted literally, just a little tongue-in-cheek comment.

**Comment by prusnak** [comment]
I have no problem with donating a dev unit, hit me with an email to stick@satoshilabs.com with the address of a core dev.

I just hate that we live in a world where every cryptocoin raises million dollars in crowdfunding that are burnt on useless stuff, yet everyone thinks we hardware wallet producers are obliged to give away free devices to everyone developer out there.

**Comment by rphmeier** [comment]
Thanks @prusnak, AFAIK we have already made plans to order a Trezor, it just hasn't arrived yet.

**Comment by mcgravier** [comment]
@prusnak I understand the frustration - There was commitment from multiple parties to integrate it, yet noone did since firmware support has been released (6 months ago). AFAIK you had to do integration for MyEtherwallet by yourself which is just sad. 

Since I'm not software developer,  all I can do is submitting issues at relevant github repos :(

**Comment by gavofyork** [comment]
> Has Ethereum foundation run out of all its money

fyi Parity Technologies (fka Ethcore) has no connection whatsoever with Ethereum Foundation. We have never received any aid of any kind from them. We have no relationship with them, professional or otherwise.

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's inactive for several months and neither assigned nor linked to a milestone.

Do we have a Trezor yet? It probably needs a re-prioritization, or a proper deadline and an assignee.

**Comment by rphmeier** [comment]
We have a Trezor, but this will have to be done UI-side as opposed to node-side since Trezor requires showing a visual pattern to the user.

**Comment by klungler** [comment]
Can we maybe get this going before I have to trade out for a Ledger Nano S?

**Comment by prusnak** [comment]
Which visual pattern? Do you mean PIN entry?

**Comment by arkpar** [comment]
@prusnak Exactly. Parity is architectured to have a core that provides an RPC API to the UI, but can also run as a service or CLI app. Adding support for Ledger devices into the core was straightforward as it has on-device PIN entry. Trezor wallet however requires interactive PIN entry so we can't just wrap it into our API and expose it as another type of account as we did with Ledger.

**Comment by prusnak** [comment]
TREZORv2 will have on-device PIN entry.

If there is anything I can do to help you integrate TREZORv1, tell me ...

**Comment by folsen** [comment]
@prusnak Is there any more detailed documentation than the protobufs on what wire-protocol is followed. AFAICT it's not using APDU like the Ledger, judging from what I can see on the Python and Java implementations. For instance, looking at this: https://github.com/trezor/trezor-android/blob/master/trezor-lib/src/main/java/com/satoshilabs/trezor/lib/TrezorManager.java#L250-L261
Where does all the magic numbers (and chars) come from?

**Comment by prusnak** [comment]
This is our own protocol. Documented here: https://github.com/trezor/trezor-common/blob/master/protob/protocol.md

**Comment by csillag** [comment]
FYI: Trezor support has been merged to geth: https://github.com/ethereum/go-ethereum/pull/14885

**Comment by mcgravier** [comment]
Small suggestion - Myetherwallet is supporting Trezor with derivation path m/44'/60'/0'/0 - Using this path will make switching between MEW and Parity more intuitive/user frendly. 

Another argument for using this path is that Jaxx, Metamask and few other wallets are using it as well - that would simplify wallet restoration from seed in case Trezor is lost or damaged

**Comment by folsen** [comment]
@mcgravier this is the path that is supported in the current implementation, but we want to add the functionality to let the user switch to whatever path they want.

**Comment by prusnak** [comment]
I am not against the user switch, but it has to be well hidden and not shown by default, because otherwise people will choose incompatible paths.
