### ISSUE TITLE
Force-cancel transaction

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#4519]
Publish a new transaction with higher gas-price that does nothing (e.g. transfers 0 ether to itself). Should be in signer.

**Comment by 3esmit** [comment]
When a transaction is set with too low gas other nodes not even accept it, in this case is not even necessary to publish a newer one. So maybe a option to just lower the nonce or to force nonce overwrite?

**Comment by 3esmit** [comment]
Maybe this should be included with editing (#4229).

**Comment by 5chdn** [comment]
Is #4958 solving this issue? Can this be closed?

**Comment by tomusdrw** [comment]
I don't think so, IIRC still don't have "cancel via replace with no-op transaction" implemented.

**Comment by CraigglesO** [comment]
This may be closed now.

**Comment by rphmeier** [comment]
@CraigglesO could you link to the PR where it was addressed for posterity?

**Comment by CraigglesO** [comment]
yep, should have done that. Apologies.

https://github.com/paritytech/parity/pull/5899
