### ISSUE TITLE
Feature request: include own(out of block size) transaction queue into a pending state

### ISSUE THREAD

**Issue by lastperson** [paritytech/parity#4529]
Consider a situation:
```
contract {
    bool public state;
    function setToTrue() { state = true; }
}

Block gas limit: 4M
Pending block: { gasUsed: 4M, transactions: [A] }
Pending transactions queue: [
  A { gasUsed: 4M, from: addrC },
  B { gasUsed: 1M, from: addrC, data: setToTrue() }
]
Pending state: { transactions: [A] }
contract.state.call('pending', {from: addrC}) -> false
// if B could be included in pending state, result would be true
```

Idea is to be able to see result of a call on pending block affected by all pending transactions, even those that are not included in current pending block. Pending state should include at least transactions submitted through this particular node(to protect from ddos), and at least transactions from the same sender(strict order).

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.
