### ISSUE TITLE
Show timer/block countdown for scheduled transactions

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4557]
Signer pending list -

- show scheduled transactions in account tx list along with countdown
- show our pending/scheduled transactions with countdown/peer publication info
- allow editing of blockNumber/datetime before submitted

**Comment by 3esmit** [comment]
This issues are related to `min_block`: Warn about further locked transactions (#4230); Allow editing (#4229).

**Comment by jacogr** [comment]
Related https://github.com/ethcore/parity/pull/4570

**Comment by CraigglesO** [comment]
I'm pointing to #4958 as I added this feature in the edit/cancel PR.

**Comment by ngotchac** [comment]
Closed via #4598

**Comment by doppio** [comment]
To clarify, this was closed via **#4958**, not **#4598**. @ngotchac, are you able to update your comment with the correct ID for the pull request?
