### ISSUE TITLE
Use standard cache directory for cached files.

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#4565]
Cached files should use XDG cache path on linux, `~/Library/Caches` on Mac, and a separate directory on windows (`%TEMP%` maybe?). This includes:
* Ethash light DAG cache
* Fetched DApps and files

**Comment by MicahZoltu** [comment]
On Windows, I believe the right location for a cache managed by the application is `%LOCALAPPDATA%/paritytech/parity`.  It is up to the application to ensure the cache is cleared as necessary.  `%TEMP%` should be used if you truly have temp files that *should* be deleted as soon as the process that created them exits.  In this case, since this is a cache it presumably should live across runs of the application and therefore go into an application managed cache folder such as ``%LOCALAPPDATA%/paritytech/parity`

**Comment by 5chdn** [comment]
> I'm seeing this error when running parity with --base-path under a user with heavily restricted permissions. It would appear that parity is trying to write the cache file to some directory other than what is set using --base-path and failing since it is not allowed access to whatever path it is attempting to use.
> 
> Confirmed with strace that it is trying to use a non-existing home folder even though --base-path is set to /var/lib/parity:
> ```
> [pid 101910] stat("/home/parity/.ethash/light/c67d12cb817cfe2de207e4823f6fa22ac14b924c3072e1ccc9b7718329287d1c", 0x7f760abf9e10) = -1 ENOENT (No such file or directory)
> [pid 101910] stat("/home/parity/.ethash/light", 0x7f760abf9d10) = -1 ENOENT (No such file or directory)
> [pid 101910] stat("/home/parity/.ethash", 0x7f760abf9c40) = -1 ENOENT (No such file or directory)
> [pid 101910] stat("/home/parity", 0x7f760abf9b70) = -1 ENOENT (No such file or directory)
> [pid 101910] stat("/home", {st_mode=S_IFDIR|0755, st_size=16, ...}) = 0
> [pid 101910] mkdir("/home/parity", 0777) = -1 EACCES (Permission denied)
> 2017-06-09 13:22:47  Light cache file write error: Permission denied (os error 13)
> ```

**Comment by jameshilliard** [comment]
Why not just put everything inside --base-path? For server deployment permissions it's much easier to have everything in the same place.

**Comment by 5chdn** [comment]
Regarding `.ethash` it used to be shared with geth / cpp-eth. Can't comment on `/tmp` though.

**Comment by jameshilliard** [comment]
is that something still ever done in practice? maybe put geth / cpp-eth compatibility behind a config flag

**Comment by 5chdn** [comment]
Stay tuned. @tomusdrw will look into that on monday.
