### ISSUE TITLE
Handle DB atomicity better (for saner DBRestore)

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#4572]
In practice, the `ethcore::snapshot::DBRestore` trait shouldn't be necessary, and our DB-using structs should handle the atomic nature of the underlying database well enough to recover when the store is replaced under them. The intuition is that code like this:

```rust
if let Some(val) = db.get(my_key)? {
    let next_key = get_key_from(val);
    let next_val = db.get(next_key)?.unwrap();
}
```
can fail.

Our blockchain, tracedb, and RPC layer don't fully respect this property. If it did, we could do away with the slightly hacky `ethcore::snapshot::DBRestore` trait altogether.

**Comment by 5chdn** [comment]
Is this still valid / desired?

**Comment by arkpar** [comment]
Requires some experimenting and would also require changes in the database API. 
See https://github.com/facebook/rocksdb/wiki/Transactions#repeatable-read
Given that we want to migrate to a custom database I would set this to lowest priority.

**Comment by folsen** [comment]
Closing in favor of work on ParityDB.
