### ISSUE TITLE
Short-lived signer sessions per Account/DappID

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#4574]
Basically: unlock your account for a specific DApp for a short period of time, expiring after 15 minutes or so. Perhaps with some limitations like "with a maximum transfer of X (eth,token, etc.) during this period".

There are some pretty strong arguments for and against this, so this might not ever come to fruition.
I am of the opinion that requesting a password on each transaction (no matter how small) encourages users to choose weaker passwords, lowering their security in general.

**Comment by tomusdrw** [comment]
On RPC level we already support `signWithToken` and it could be used for UI support of this while still maintaining a decent security (since private keys are only decrypted for a short while and tokens are one-time passwords)

**Comment by jacogr** [comment]
This is actually closely related to white/grey/blacklists - https://github.com/ethcore/parity/issues/2281 (the idea being that a whitelisted app doesn't require the same hoops)

**Comment by rphmeier** [comment]
@jacogr I believe that short-lived sessions are better than a permanent list of any kind; this has parallels to standard practices in online banking and other websites storing potentially sensitive information.
@tomusdrw Yes, I thought that tokens might be a possible avenue for implementing this.

However, we need to be careful if doing any of this stuff in the UI, there's a much larger attack surface for our JS code than stuff which occurs within the node.

It's much easier to check whether token/eth transfers fall within a limit on the UI side, but much more secure to set the limits and check them node-side w/ DApp Id.

**Comment by 5chdn** [comment]
What's the status of this? There was recently (again) a series of hacks related to unlocked accounts via RPC. I would recommend to only allow such a feature for development on non-main chains. Every user should be fine with signing every single transaction that includes real-value tokens.

**Comment by folsen** [comment]
Closing because UI is moving.
