### ISSUE TITLE
Test for all possible chain jsons

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4586]
Seems that we're missing a test which verifies that all spec files are valid.

**Comment by arkpar** [comment]
Valid as in parse correctly?

**Comment by tomusdrw** [comment]
Yes (valid JSON + valid types of required parameters)

**Comment by axelchalon** [comment]
I'd like to work on this!

Here is how I would see it:
- Write a JSON spec file using [JSON Schema](http://json-schema.org/) based on the information here https://github.com/paritytech/parity/wiki/Chain-specification#json-chain-spec-format
- In the test, validate every JSON file in `ethcore/res/ethereum/` against that JSON Schema spec (using https://github.com/rustless/valico)

This would also allow us to verify if the provided JSON chain file when launching Parity with a custom chain is valid, and Valico would provide an explicit error message about what is wrong with the json file.

Does this sound like the right way to do it for you?

**Comment by arkpar** [comment]
Don't think an additional json schema is necessary. We already define a schema in rust code with serde. Just creating a `Spec` object out of all json files inside `ethcore/res/` and `ethcore/res/ethereum` should be enough.

**Comment by axelchalon** [comment]
You're right. I didn't know about that; just had a look and this definitely looks like the way to go.
