### ISSUE TITLE
StateDiff on trace module not showing storage updates for some transactions

### ISSUE THREAD

**Issue by ana0** [paritytech/parity#4592]
I've found something anomalous on the stateDiff section of the trace module, as returned by trace_replayTransaction, for some transactions - not sure whether it's on the side of parity, or the contract.  

For example, tx `0x7f5fe00ce8ce985cac8166ec0a641e3ba303597cce813e0bcc09401512586eec` looks like a standard erc20 transferFrom call with input args:

`0x23b872dd000000000000000000000000e08e9002bb787f8223b85b0e72e7796f3b4164fb000000000000000000000000f59f102dbbdd3191574215d4aeb5feda14a778420000000000000000000000000000000000000000000000000000000017d78400`

This looks like it should move 400000000 of this token from `0xe08e9002bb787f8223b85b0e72e7796f3b4164fb` to `0xf59f102dbbdd3191574215d4aeb5feda14a77842`, which would result in two writes to storage at the contract address the transaction was sent to: `0xedbaf3c5100302dcdda53269322f3730b1f0416d`. 

For this tx though, the stateDiff is this:
```
{ '0x1746ee2f5b8719c518dd234cbe1ce203489a4181': 
    { balance: { '*': { from: '0xdabcfd84f159373', to: '0xdaa02f30d4c4373' } } },
      code: '=',
      nonce: { '*': { from: '0xf85', to: '0xf86' } },
      storage: {} },
  '0xea674fdde714fd979de3edf0f56aa9716b898ec8': 
    { balance: { '*': { from: '0x32ed33069d6304491b', to: '0x32ed34d382a4cd991b' } }, 
      code: '=', 
      nonce: '=', 
      storage: {} } 
}
```
Which shows only the payment of the mining fees in eth.  

What could be going on here?  This is the only contract I've found this on so far, but I've found it on this contract multiple times.  

My application is still in the early stages of testing, so I don't know if it will turn up on further contracts, but I'm happy to post them here if they do.

**Comment by 5chdn** [comment]
It's not clear what contract resides at `0xeDBaF3c5100302dCddA53269322f3730b1F0416d` and I have issues to figure out how we can help you with this question. I also don't see how this is related to parity. Have you tried asking this very same question on [Ethereum Stack Exchange](https://ethereum.stackexchange.com/)?
