### ISSUE TITLE
Docker images should reference a volume.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#4596]
Docker containers are designed to be transient.  Any data that is in them will disappear when the container goes away.  Since the Ethereum blockchain is not trivial to re-download it should be (optionally) stored in an attached volume rather than inside the container.  Similarly, there should probably be a mechanism for allowing the user to attach a volume that references their keys as well.

In the Dockerfile, this is as simple as `VOLUME /chaindata` and then making sure that parity when running inside the container stores chain data in `/chaindata` (can be any path you like).  Launch instructions for Docker should tell the user to launch it like, `docker run --rm -v /path/to/chaindata/on/host/filesystem:/chaindata -p 8180:8180 parity

In addition, the user probably will want to store their keys outside of the docker container so there should be a second volume mount for those.  It would work exactly like above, and the user would provide a second directory to mount when they run the container.

More details on Docker volumes can be found here: https://docs.docker.com/engine/tutorials/dockervolumes/

**Comment by vincentserpoul** [comment]
I agree with you for the chain data.
For keys, I think a secure way of injecting the keys in the container should be promoted: docker secrets, www.vaultproject.io, kubernetes secrets...

**Comment by rphmeier** [comment]
cc @General-Beck

**Comment by davidpsys** [comment]
@General-Beck @arkpar Any thoughts on this? It's not a much to change but should this maybe be a -e option instead of changing the default which some people may also find strange.

**Comment by arkpar** [comment]
I would agree this should optional with clear instructions. This is mostly about documenting best practices.

**Comment by 5chdn** [comment]
rfc https://github.com/paritytech/parity/wiki/Docker#persistent-data-directory

**Comment by MicahZoltu** [comment]
@5chdn Recommend just linking to DockerHub rather than explaining complicated CLI commands on how to query for images and/or versions.  If someone wants to use the CLI to query docker hub, they can read the Docker docs on that.  Teaching users the CLI seems out of scope for this, and the web interface is intuitive enough that teaching isn't necessary.

In the ports section, you may want to mention something like, "Now you can browse to `http://localhost:8180` from the docker host computer to access the UI."

**Comment by MicahZoltu** [comment]
https://github.com/paritytech/parity/wiki/Docker#run-in-background I believe that `-d` and `-it` don't really make sense together.  If you want to run in the background you can just do `-d`.  Setting it up to be interactive but in the background doesn't really make sense.

**Comment by General-Beck** [comment]
What privileges we will consider and how to connect the volume. I would be glad to hear your suggestions. For example, if it's just a Ubuntu server or it's Ubuntu core

**Comment by 5chdn** [comment]
@MicahZoltu thanks for your feedback.

**Comment by MicahZoltu** [comment]
Are the instructions for this up-to-date?  I'm trying to deplay with Docker and mounting `/root/.local/share/io.parity.ethereum/docker` to a docker host volume results in re-syncing the chain after every run.

Also, I just realized that the Docker image still doesn't have a VOLUME tag in it, which means tooling can't auto-detect what volume should be mounted.

**Comment by 5chdn** [comment]
@paritytech/ci ^

**Comment by MicahZoltu** [comment]
I believe I was reading the instructions wrong, recommend updating them to have path be `/path/on/host:/mnt` rather than giving a real-looking path for the host.

That being said, I do think this should remain open and `VOLUME` be added to the docker image so tooling can auto-detect and mount.  I was trying to use Docker Cloud which has a UI for volume mounting which is part of where the confusion arose from.  Also, on Windows `/root/.local/share/io.parity.ethereum/docker` doesn't exist.

Also, I believe the current mechanism for volume mounting requires the user _also_ pass in a command line argument when starting the container to tell it to point the chain to `/mnt`.  I recommend setting up the docker image so that it separates the chain from everything else at whatever path is specified by `VOLUME` so someone can do `/path/on/host:/path/specified/in/image` without any additional command line arguments and have an externally stored cahin.

**Comment by folsen** [comment]
@ddorgan @fevo1971 Could you please move this issue to devops repo. Go over the docker image and make sure it follows best-practices, is documented correctly and has a `VOLUME` declared (if it's supposed to use volumes).
