### ISSUE TITLE
Internally sealing Engines should not issue work packages

### ISSUE THREAD

**Issue by keorn** [paritytech/parity#4605]
Return error and show warning.

**Comment by sjeohp** [comment]
Does this mean _all_ client engines besides Ethash should error&warn on call to `work`?

**Comment by keorn** [comment]
Currently yes (and in the future, since we are unlikely to have more PoW `Engine`s).

**Comment by sjeohp** [comment]
Should `set_engine_signer` error for `Ethash`?  Currently it returns `Ok(())` but does nothing.

**Comment by keorn** [comment]
Yes, it should.
