### ISSUE TITLE
Better support for high-privacy browser settings

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#4615]
Currently with browser settings sufficiently high to forget the auth token, there's no (non-CLI) easy way for the user to start a new Parity Wallet session.

Should be made easy to do this from the menu bar/system tray/application short cut icon.

**Comment by arkpar** [comment]
This is implemented already for mac and windows. 

1. The tray app has an "Open" command that creates a "parity ui" command which issues a new token if required and opens a browser window.

2. When tray app is launched and it detects that it is already running it does the same - launches "parity ui". So when user starts "Parity Ethereum" shortcut on windows or opens the mac app it opens the browser just the same.
