### ISSUE TITLE
Linux: /home/you/.local/share/parity not created automatically

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#4670]
<img width="771" alt="screen shot 2017-02-24 at 16 30 12" src="https://cloud.githubusercontent.com/assets/738724/23309730/2f416abe-fab0-11e6-862f-7e3232e65b76.png">

The following folder is automagically created:
`/home/you/.local/share/`

`/home/you/.local/share/parity` so automatic updates fail and complain with "unable to copy update".

**Comment by arkpar** [comment]
Has been fixed a while ago by @gavofyork
