### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#4678]
There still a few steps that are done manually and need to be automated:

* Bumping up version in https://github.com/ethcore/homebrew-ethcore/blob/master/parity.rb
* Bumping URL in https://github.com/ethcore/scripts/blob/master/install-parity.sh (beta releases only)

**Comment by 5chdn** [comment]
Would love to get there with 1.9.0!

**Comment by folsen** [comment]
This is an important topic but isn't really a single thing for this issue. People are being hired to help figure out release automation together with Afri.
