### ISSUE TITLE
TokenReg tla length limited with 3 symbol

### ISSUE THREAD

**Issue by Mikefluff** [paritytech/parity#4698]
Parity has this limit here - https://github.com/ethcore/contracts/blob/master/TokenReg.sol#L31
Our token name is TIME, which is 4 symbol, there are also a lot of tokens which actively trades on exchanges, which have 4 or even 5 symbols. I want to offer to extend this limit to 4 or 5 symbols. I don’t think it will harm anything else.

**Comment by ngotchac** [comment]
@gavofyork @jacogr Any plan on upgrading the TokenReg Contract ?

**Comment by arkpar** [comment]
This can be supporting with token metadata. No need to upgrade the contract as far as I can see

**Comment by ngotchac** [comment]
@arkpar The thing is that TLAs are supposed to be unique. Adding them in metadata won't ensure that. So it's whether a contract change, or we register tokens with random free TLAs and add the real one in the metadata...

**Comment by tomusdrw** [comment]
Solving uniqueness issue can be handled by GUI (using some ranking or just taking the one that was registered first (currently the uniqueness pretty much works like that)).

**Comment by ngotchac** [comment]
But then how to let the user that want to register the same TLA that it's already taken and that his token won't show up in the Wallet?

**Comment by 5chdn** [comment]
The main issue really is that the 'T' in TLA stands for 'three' :-p

**Comment by AmethystWizard** [comment]
I just downloaded parity, the first thing i did was want to create a token name (which is 4 letters) I couldn't this is really annoying.

**Comment by AmethystWizard** [comment]
why not just have TLA stand for Token Letter Acronym rather than Three Letter Acronym

**Comment by 5chdn** [comment]
Let's continue working on this here: https://github.com/paritytech/contracts/issues/83
