### ISSUE TITLE
More flexible chain spec format

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#4721]
Rather than specifying transitions, specify rules for ranges of blocks.

(contrived example)
```json
"1": {
    "engine":  { },
    "rules": {
        "eip158": "on",
        "maxCodeSize": 23000,
    }
}
"100000": {
    "engine": { },
    "rules" : {
        "eip158": "on",
        "maxCodeSize": 30000,
        "maxGasLimit": 4700000
    }
}
```

Some rules are simple toggles, which are assumed to be "off" unless specified as "on".
Others are parameterizable by number (or perhaps other fields).

This will let us clean up transitions, swap out engines and other consensus rules more easily.
We might want some section where we can declare engines so we don't have to re-define them in each section. Alternatively, allow recursive definitions which inherit from their ancestors where not explicitly overridden.

**Comment by rphmeier** [comment]
This will need some bikeshedding over format. Implementation will require another indirection between the `Arc<Engine>` most services hold and the actual consensus engine.

**Comment by arkpar** [comment]
IMO this will lead to confusion. Most of the transitions are one way only.

**Comment by rphmeier** [comment]
Many of them don't have to be. The DAO transition would just be activated for 10 blocks, for example. Our ethash implementation could be less if-else soup for the various transitions.

Switching out engines at block numbers would ease the switch to PoS on the mainnet and moving to a validator contract on kovan.
