### ISSUE TITLE
Build release binaries with fresh (non-precompiled) JS

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4724]
The cargo.lock files references the relevant `js-precompiled` branches for master, beta & stable - however we do get it wrong and then release broken builds -

https://github.com/ethcore/parity/issues/4712

Caused by

https://github.com/ethcore/parity/blob/v1.4.12/Cargo.lock#L1252

To make 100% sure we build the binary with the code in the branch, we should be building the release binaries with

`cargo build --release --no-default-features --features ui`

CC @arkpar @tomusdrw @General-Beck

**Comment by debris** [comment]
Closing, cause js is being moved from this repo
