### ISSUE TITLE
Add ERC20 Token History in Parity UI

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#4754]
The Parity UI currently shows the number of a particular ERC20 token you have, e.g., REP or MKR.  However, it doesn't currently provide a transaction history of those tokens, such as who you received them from, when, or in what volume.  It would be nice if the UI showed you a token history for your account for any tokens you currently hold.  I recognize that token transfers aren't transactions to/from your account which is why they don't currently show up in the Transaction history, none the less I think the information would be valuable to end-users who may not understand the distinction.

**Comment by rphmeier** [comment]
This would require scanning all logs for the history of the blockchain. You can get the history, but you might have to wait a few minutes on an SSD full node (or days on a light node). Not sure if it's worth doing; this kind of log-scanning should be actively discouraged at the DApp layer IMO.

**Comment by MicahZoltu** [comment]
Hmm, I didn't consider (though it makes sense) that the destination address for an ERC20 transfer is encoded in the contract parameters and not readily available for indexing.  I suspect (without much thought or understanding) that the only way to index this would be to have Parity have a special understanding of ERC20 contract transfers and create a special-purpose index on all such transactions?

**Comment by 5chdn** [comment]
Etherscan shows token transfers but they don't expose it via API.. (yet?)

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
