### ISSUE TITLE
Detect & notify about insufficient free storage space

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#4758]
Node should regularly check for 'sufficient' free storage space and notify user in case it's running low.

**Comment by 5chdn** [comment]
What would be _sufficient_?

**Comment by bjornwgnr** [comment]
I'm not the right person to answer this.
There was talking about 500MB when chain has already been fully synced.

Might be worth to implement checks with different quotas according to:
-before/after full sync
-sync mode
-chain
