### ISSUE TITLE
IPC implementation incompatible with nc

### ISSUE THREAD

**Issue by ppratscher** [paritytech/parity#4783]
Piping RPC command directly into nc does not work properly:

`echo '{"method":"eth_getBlockByNumber","params":["0x1b4", false],"id":1,"jsonrpc":"2.0"}' | nc -U ~/.local/share/io.parity.ethereum/jsonrpc.ipc`
returns nothing.

If you start nc manually with
`nc -U ~/.local/share/io.parity.ethereum/jsonrpc.ipc`
and the paste
`{"method":"eth_getBlockByNumber","params":["0x1b4", false],"id":1,"jsonrpc":"2.0"}[ENTER]`
It will correctly return the result of the API call.

**Comment by tomusdrw** [comment]
Seems that sometimes adding `-n` executes a previously sent request?
Perhaps some buffering issue?

**Comment by tomusdrw** [comment]
Might be important for: https://github.com/ethcore/jsonrpc/issues/56
