### ISSUE TITLE
Feature Request: Ability to configure Parity via the web UI.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#4793]
As a user, I want to be able to interact with Parity entirely through the web interface.  I install with a GUI installer, it runs as a system tray app/service, I never interact with a command prompt.  However, there are a number of things I cannot do as this kind of user including:
* ~Change what chain I'm talking to.~ Tracked in #4682 
* Enable/disable/configure HTTP JSON-RPC server.  - related to #3417
* Enable/disable/configure IPC JSON-RPC server.  - related to #3417
* Restart Parity node.
* (maybe others, this is what pops into my head)

**Comment by jacogr** [comment]
Chain switching has been logged previously in https://github.com/ethcore/parity/issues/4682

Feel free to update the list as other configs pop up, all worth-while to make things as simple as possible.

**Comment by tomusdrw** [comment]
RPC interface control logged here: https://github.com/ethcore/parity/issues/3417

**Comment by rphmeier** [comment]
> Start/stop mining

There's no miner included in parity, so this won't really be possible. Everything else seems like it can be done.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
