### ISSUE TITLE
Improve UX of port-in-use.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#4795]
I run Parity on Windows which just has a system tray icon.  I had geth running on port 8485 (Parity's default HTTP port).  I forgot about it and when I tried to launch Parity, the system tray app would just spontaneously close on me.  There was no indicator of what the problem was, it just simply shutdown.  While I suspect the logs (wherever they are) give me more detailed information, for the average user this will result in a support request.

I recommend adding some kind of feedback to the tray app when Parity fails to start.  Since the UI is launched via the tray app, it seems like it could just fallback on another port.  While this would be a nice usability feature, I also think it is important that the Parity tray app be capable of surfacing errors to the user when it runs into a problem during startup.  Either make it so the UI *can't* fail to start or give the tray app a native way of surfacing errors to the user.  Windows 10 Action Center may be the appropriate solution here, though I haven't played with it much.  Alternatively, add an item to the context menu that when selected will bring up a simple error dialog with some user friendly error messaging.

**Comment by 5chdn** [comment]
Was `parity ui` what you are looking for?

**Comment by MicahZoltu** [comment]
I'm not sure I understand the question.  I believe `parity ui` is the shortcut I am running that launches the tray app if that is what you are asking?

**Comment by 5chdn** [comment]
Sorry, I was misreading the first paragraph.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
