### ISSUE TITLE
Health check API endpoint

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4801]
`curl -v http://localhost:8080/api/status` should return basic health of the node: number of peers, syncing status

**Comment by adrianbrink** [comment]
Is there a tag for low hanging fruit or easy? This is probably a good intro. Also, in which crate do all the end points live?

**Comment by tomusdrw** [comment]
Hi @adrianbrink! I've tagged this as `Q2-easy`.

The right place to put this would be here:
https://github.com/ethcore/parity/blob/81b57a57c713d9bc67efd8950ef1c94e0a0238a5/dapps/src/api/api.rs#L147-L152

It will be required to push through additional dependencies like `SyncStatus` and `Client` to get peers and some other stats (like latest block number perhaps).

**Comment by adrianbrink** [comment]
Awesome. I'll send a PR by Sunday. :-)

**Comment by adrianbrink** [comment]
@tomusdrw sorry, I'll send it tomorrow. Didn't have enough time today.

**Comment by andrebeat** [comment]
I think this can be closed now.
