### ISSUE TITLE
Save address (via /address/:address) needs to autoFocus

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4802]

**Comment by 5chdn** [comment]
This issue is labelled with _trivial_: Can be fixed by anyone with access to a computer. But it is inactive for more than 2 months and neither assigned nor linked to a milestone.

@paritytech/ui-devs Please, review this ticket within 7 days, assign it and decide on a deadline. Thanks :)

**Comment by ngotchac** [comment]
Is the action bar button that needs to be auto focused? Not sure why...
