### ISSUE TITLE
Feature-request: batch import of blocks (but not necessarily a valid chain) 

### ISSUE THREAD

**Issue by holiman** [paritytech/parity#4830]
I did some hive-specific optimisations to geth: https://github.com/ethereum/go-ethereum/commit/544247c91828b5f99d7d2bd61b98cc51e2b23e44

So, when running consensus-tests in hive, there are a sequence of RLP-encoded blocks to import. And since the test may contain invalid blocks, we can't just concat all RLP-blocks into a single file, but need to import each file, one block per file, and not error out in case one of them is 'bad'. 

In the case of `lotsOfBranchesOverrideAtTheEnd`, that means 16+ executions of the client. 

What I did for geth is to make it possible to do `geth --import file1 file2 file3`, thus importing all 16 blocks in one execution. That is a very hive-specific optimization, but it makes a huge difference:

![image](https://cloud.githubusercontent.com/assets/142290/23740876/e3302476-04a5-11e7-9334-214b4022de57.png)

Would it be possible to have the same thing implemented in Parity - or is it already possible even?

**Comment by rphmeier** [comment]
@holiman To clarify, the feature request here is to change import to accept a sequence of files, import from them in order, and simply skip the remainder of any given file on a bad block within it rather than bailing completely?

**Comment by holiman** [comment]
Yes, exactly!

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.
