### ISSUE TITLE
Parity-as-a-library

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#4842]
- [ ] APIs for running full and light nodes
- [ ] C interface

**Comment by rphmeier** [comment]
...and then the ability to cross-compile this library to IoS and Android.
@debris in your experience what will be the hardest part of that?

**Comment by debris** [comment]
> ... what will be the hardest part of that?

Probably cross-compiling libraries containing C code... Besides that, writing C interfaces itself, cause it's super time consuming

**Comment by arkpar** [comment]
The C interface can be simple enough. It's mostly configuration, creating, starting and stopping Parity service and polling for status to detect critical errors. In the simplest implementation configuration can be done by passing a text in toml format. So basically just 3 functions.
```
parity_service_handle parity_create(const char* config);
void parity_destroy(parity_service_handle handle);
void parity_poll_status(parity_service_handle handle, parity_status* status);
```
All other communication goes over RPC/IPC.

If we want to expose our rich API to C, these bindings need to be auto-generated from the RPC traits.

**Comment by rphmeier** [comment]
That definitely seems like a good approach.
I wonder about the viability of running an RPC server for a hosted node within an app. We might want to just have a native code RPC endpoint

`char* parity_rpc(parity_service_handle handle, char* request);`
which just wraps a thread pool + event loop + `future.wait()` internally.

**Comment by adrianbrink** [comment]
@debris But wouldn't that be the worry about an implementor to compile libraries that contain C code. From our side we would only need to worry about writing the C interfaces (which will take a lot of time).

**Comment by adrianbrink** [comment]
To expose the C api something like [rusty-binder](https://gitlab.com/rusty-binder/rusty-binder) or [rusty-cheddar](https://github.com/Sean1708/rusty-cheddar) would be good to use. 

Also, let's see if the rust team will support this in the [future](https://github.com/rust-lang/rust/issues/10530).

**Comment by rphmeier** [comment]
@adrianbrink I think @debris was referring to C/C++ libraries we have as dependencies, which may be hard to cross-compile.
To expose a C API we can just use `#[no_mangle] pub extern fn` in Rust code.

**Comment by adrianbrink** [comment]
Oh right. Didn't know parity had C/C++ deps. 
Yeah, rusty-cheddar/binder could be used then to auto-generate the C header files.

**Comment by tomaka** [comment]
Reopening as I'm going to work on this soon-ish.
