### ISSUE TITLE
Trace & Fat DB module improvement suggestions

### ISSUE THREAD

**Issue by gobitfly** [paritytech/parity#4858]
While developing [Etherchain Light](https://github.com/gobitfly/etherchain-light) I came across some nice to have improvements for the tracing & fat-db module:

* Include traces for block and uncle rewards (in the trace_block and trace_filter calls)
* Allow reverse account enumeration with the parity_listAccount call (e.g. via an negative range parameter)
* Align the vmTrace output of the trace_replayTransaction call with Geths debug_traceTransaction format so that Parity can be used as a backend for the Remix debugger or at least provide the same level of information
* Allow paging in the trace_filter call to limit the number of returned traces (e.g. include an sort order, offset and limit parameter to the call). The start & end block parameters are not helpful for accounts that receive a high number of tx (e.g. Poloniex wallet).

If those features are implemented it would allow Etherchain Light to display all balance movements of an account (currently only tx are shown, but no mining rewards), navigate the account list not only forward but also backward and to integrate the remix debugger.

Thanks,
Peter

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's inactive for 2 months and not assigned.

@paritytech/core-devs Please make sure this is correctly prioritized, assigned, and the selected milestone 1.7 still realistic.

**Comment by grbIzl** [comment]
Hi @gobitfly I'm working on this issue. I've created PRs for rewards and paging (they are not merged yet). I have a couple of questions about 2d and 3d parts of this issue.
>Allow reverse account enumeration with the parity_listAccount call (e.g. via an negative range parameter)
What do you mean? To output accounts just in reversed order? If yes, it seems more appropriate to make such reversion on client's side. Array.prototype.reverse() for example.
>Align the vmTrace output of the trace_replayTransaction call with Geths debug_traceTransaction format so that Parity can be used as a backend for the Remix debugger or at least provide the same level of information
Also not clear for me. Which exactly parameters are missed now? I've compared outputs for these methods (Parity's and Geth's). There is difference indeed. From the first glance Geth's version provides more info about stack, storage etc.  But I need to understand your use case first. Can you provide more details for that? You've mentioned using it in Remix. Can you expand your idea a little bit?

**Comment by gobitfly** [comment]
Hello,

thanks for addressing this ticket. Most of the functionality would be nice to have in order to built a suitable blockchain explorer based just on Parity.

Regarding your questions:
- Reverse account enumeration would allow backwards paging in the following view: https://light.etherchain.org/accounts. Currently only forward paging is possible.

- The idea is to use Parity as a backend for the Remix debugger. Remix is just a visualization tool for the traces generated by Geth. If Parity would generate similar traces it would be possible to integrate Remix into Etherchain Light and allow interactive debugging of transactions.

Thanks!

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.

**Comment by gavofyork** [comment]
@5chdn this one might be worth keeping current.

@NikVolf point 3 should be addressable through an alternative serialisation of the existing trace datastructure.

**Comment by debris** [comment]
@grbIzl what is the status of it? Do you think we could move remaining work to 1.10?

**Comment by rstormsf** [comment]
Now truffle debugger also using `debug_traceTransaction` :-(
https://github.com/trufflesuite/truffle-debugger/blob/feaebc3be9b8589be07544d176051fd8a375cedd/lib/web3/adapter.js#L16

which parity doesn't support

**Comment by tcoulter** [comment]
Came hear to say what @rstormsf said. `debug_traceTransaction` is really important to portable debuggers, and we'd love to help make that output standard.

**Comment by 5chdn** [comment]
> Let us know what we can do.

Submit a pull request :)

**Comment by folsen** [comment]
@grbIzl I've unassigned you from this for now, could you give an up to date summary on what the state of this issue is; what remains to be done? Also please re-assign yourself if you would like to do it.

**Comment by grbIzl** [comment]
@folsen two requirements were implemented (include traces for block and uncle rewards and 
allow paging in the trace_filter call to limit the number of returned traces).
For the third one (align the vmTrace output of the trace_replayTransaction call with Geths debug_traceTransaction) @gavofyork  wanted to write some js adapter. Frankly, I would create a separate issue for this (or may be include into the scope of #8672 ). It would be more logical, when to mix such different issues in this one.
The second requirement (allow reverse account enumeration with the parity_listAccount call) was postponed, as it's value was not clear for me. Again, can be separated into the other issue and prioritized.

**Comment by folsen** [comment]
@grbIzl Thanks for the summary, moving the first issue to #8672 and closing this one.
