### ISSUE TITLE
eth_sendTransaction extremely slow

### ISSUE THREAD

**Issue by AdvancedStyle** [paritytech/parity#4875]
I just upgrade from Parity 1.4.9 to Parity 1.5.7 and the eth_sendTransaction JSON API is now extremely slow (takes about 30-60 seconds, whereas on 1.4.9 it took less than a second or 2)

**Comment by tomusdrw** [comment]
Potentially related to new JSON-RPC implementation or hardware wallets support.

Is is the only method that takes so long for you? Could you test `eth_sign` as well?

**Comment by AdvancedStyle** [comment]
Everything seems kind of slow, for example:
- personal_unlockAccount  takes between 1-10 seconds
- eth_sign takes between 2-15 seconds

But eth_sendTransaction seems to be the slowest, taking between 15-60 seconds

Also eth_sendTransaction seems to be randomly messing up the nonce and putting a 0 nonce; when the account already has confirmed transactions.

* Note that the keystore has around 40,000 keys in it (but it had same number for 1.4.9 with no issues)

**Comment by AdvancedStyle** [comment]
Also is there a simple way to rollback to 1.4.9?  1.5.7 appears to have rearranged the directory structures and moved everything into .local

What directory moves would be required in order to rollback?

**Comment by tomusdrw** [comment]
What about RPC methods that are not dealing with accounts? It looks like some kind of regression with account handling. Will have a look.

Important directories:
`~/.local/share/io.parity.ethereum/chains/ethereum -> ~/.parity/db`
`~/.local/share/io.parity.ethereum/keys/ethereum -> ~/.parity/keys`

Did you compile parity on your own? Did you use `--release` flag?

**Comment by AdvancedStyle** [comment]
I'm running 1.5.7 from release downloads.

Here are the flags I'm using:
parity --jsonrpc-apis web3,eth,net,parity,traces,rpc,personal --geth --keys-path /home/me/keystore --cache-size-db 1024 --gas-floor-target 1500000 --gasprice 20000000000 --gas-cap 1500000 --relay-set strict --force-sealing

My peer count appears to be way down also, varying between 0 and 2 connections most of the time.

Non-account RPC methods are also slow sometimes too, for example: `net_peerCount` just took 10 seconds to run.

RE: Rollback, so basically just move the chains db, and the keys back, then I'm all good to re-install the 1.4.9 release without any expected problems?

**Comment by AdvancedStyle** [comment]
Just built/upgraded to v1.7.0 and now it seems to be working fine:
- Not slow
- Connecting with peers OK
- Not dropping nonces

So i guess the issues have already been fixed/commits, just not in the 1.5.7 release
