### ISSUE TITLE
Non-ETH token icons don't show up (correctly) in default account selection (signer bar) when using chrome extension

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#4885]
![icon](https://cloud.githubusercontent.com/assets/17831185/23864780/e3e68376-0813-11e7-81fe-0fe2c3344de1.jpg)

They show up when using the parity browser though.

**Comment by ngotchac** [comment]
This should be fixed from https://github.com/ethcore/parity-extension/pull/66
