### ISSUE TITLE
Use optimal C code for SHA3

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#489]
Use SIMD version for newer chips:

http://bench.cr.yp.to/impl-hash/keccakc512.html

**Comment by debris** [comment]
this might be helpful: https://github.com/huonw/simd

**Comment by arkpar** [comment]
Would be easier just to use an existing C impl, there are sources for multiple impls available here:
https://github.com/gvanas/KeccakCodePackage
and in within the benchmarking tool archive: http://hyperelliptic.org/ebats/supercop-20141124.tar.bz2

Also, there for simd version to be any useful it needs to be called to compute multiple hashes at once.
MemoryDB must support batched insertions, Trie update code needs to be updated, etc.

**Comment by arkpar** [comment]
I've tried the top performing code from supercop package above and it does not perform any better than tinykeccak. `simple-sha3` branch

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still _nice to have_ and realistic to implement or close otherwise.

**Comment by arkpar** [comment]
Seems like we are using the best implementation already
