### ISSUE TITLE
Integrate libsnark into parity

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#4896]
Tracking issue for libsnark

The library itself:
https://github.com/scipr-lab/libsnark

Mostly abandoned "hackish bindings"
https://github.com/ebfull/hackishlibsnarkbindings

Initially we need

1. bn128 pairing 
2. bn128 curve operations (add, multiply)

**Comment by rphmeier** [comment]
cc @ebfull 

It's been quite some time since the tinysnark experiment; have there been any changes or improvements you're aware of that would make integration with Rust code easier now?

**Comment by NikVolf** [comment]
Closing since `bn` pure rust library appears to be not much slower substitute of what we need (thanx @ebfull !):

https://github.com/zcash/bn/tree/master/shootout
