### ISSUE TITLE
Please allow access to more than the first account from hardware wallets

### ISSUE THREAD

**Issue by bokkypoobah** [paritytech/parity#4905]
Parity only give access to the first account from a hardware wallet (Ledger Nano S in my case). 

Could you please provide access to the next accounts after the previous account is used. Ideally, provide access to the next few accounts. 

MyEtherWallet allows the user to scroll through a whole list of accounts.

`geth` provides the next account after the previous account has a transaction.

Reference: https://www.reddit.com/r/ledgerwallet/comments/5zbva0/how_to_access_next_account_from_nano_s_in_parity/

**Comment by Bunjin** [comment]
I agree that this feature is a must for HW support :)!

**Comment by rudolfix** [comment]
Ideal scenario would be to provide derivation path when account from hardware wallet is added, the workaround would be to provide the root from which several accounts are derived in the settings. For example you can provide `44'/60'/103'` and several accounts like `44'/60'/103'/0'` `44'/60'/103'/1'`...

**Comment by MicahZoltu** [comment]
At the moment BIP32 derivation paths are a [bit of a mess in Ethereum](https://github.com/ethereum/EIPs/issues/84#issuecomment-292324521).  Because of this, allowing the user to provide a custom derivation path is fairly essential.

Going forward, hopefully EIP 600, 601 and 602 will go through that will provide a more user friendly solution in this space.

**Comment by MicahZoltu** [comment]
For anyone wondering what derivation path Parity is using with a Ledger device attached it is `m/44'/60'/0'/0`.

**Comment by rudolfix** [comment]
FYI: I've modified current master to allow passing derivation path in command line. It's dirty and I use it myself now but if anyone is interested here it is: https://github.com/Neufund/parity . I'll try to clean it up and then make a pull request. Command line is like this: `parity ui --chain dev --hardware-wallet-key-path "44'/60'/103'/0"`

**Comment by arkpar** [comment]
This goes with HD account support in the UI. #3541

**Comment by 5chdn** [comment]
Closing in favour of #3541
