### ISSUE TITLE
Ledger - sending transactions impossible

### ISSUE THREAD

**Issue by rindertb** [paritytech/parity#4906]
Amount shown on Ledger is not the amount to send: when giving in 0.1 Ledger shows 0.072...
When confirming big red error at the bottom: 
[-32010] Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 100420000000000000 and got: 0.

https://www.reddit.com/r/ledgerwallet/comments/5z8whx/ledger_nano_s_on_parity_162/

**Comment by arkpar** [comment]
Would be good to know the OS, ledger firmware and app version.

**Comment by rindertb** [comment]
W10, 1.3.1 and 1.0.8
In the reddit thread mentioned all 3 reporters have W10. u/btchip wrote in another thread: 'Windows seems to be the pattern here. Also the transport code looks different for Windows'
I also tried on a live Mint CD. No problems there.

https://www.reddit.com/r/ledgerwallet/comments/5zayfe/how_to_access_ledger_nano_s_accs_via_parity_162/dexj0vj/

**Comment by arkpar** [comment]
Does the account actually have balance to execute the transaction?
Could you please do the following?

1. Exit Parity, and all Ledger apps.
2. Connect Ledger Nano and start ethereum app.
3. Open command prompt
4. Execute `"C:\Program Files\Ethcore\Parity\parity.exe" -l hardware_wallet=trace ui`
5. Attempt to execute transaction again.
6. Copy console output (or logs from Parity management page) and post it here

**Comment by rindertb** [comment]
[NODE LOGS.txt](https://github.com/paritytech/parity/files/848309/NODE.LOGS.txt)

**Comment by arkpar** [comment]
It appears that your account has exactly 0.1 Ether. Transaction requires additional 0.00042 Ether for the fee. Try transferring a lower amount.

**Comment by arkpar** [comment]
`got: 0.` - This part is misleading and needs fixing

**Comment by rindertb** [comment]
You can see it holds 0.1 and I try to send 0.05 ...

**Comment by arkpar** [comment]
This is weird indeed, the transaction passed to the device has a value of exactly 50000000000000000 wei, and that's what the device should display. I'll do some more digging.

**Comment by arkpar** [comment]
Should be fixed in 1.6.4
