### ISSUE TITLE
Remove Encodable for Option<T>

### ISSUE THREAD

**Issue by debris** [paritytech/parity#4910]
link to discussion
https://github.com/paritytech/parity/pull/4873#pullrequestreview-26878274

**Comment by sjeohp** [comment]
I see [#4873](https://github.com/paritytech/parity/pull/4873#pullrequestreview-26878274) has been merged.  Is this still an issue?

**Comment by debris** [comment]
Yes, although I don't know what is the correct way of solving the issue :/ @arkpar ?

**Comment by debris** [comment]
I'm closing it as it is not a priority, not a bug and it is not clear how it could be improved
