### ISSUE TITLE
.parity folder in my user removed after install new parity

### ISSUE THREAD

**Issue by Pwnmanship** [paritytech/parity#4918]
My whole .parity folder, so also the keys folder are deleted when I install the new parity. 
I duplicated this in a local VM and also deleted the .parity folder and the keys there.

**Comment by arkpar** [comment]
What version are you installing? Some of the directories are moved to new locations when upgrading to 1.5.x or higher. See release notes here: https://github.com/paritytech/parity/releases/tag/v1.5.0

**Comment by Pwnmanship** [comment]
Just talked to you in the chat and indeed the folder was changed.
I don't use parity for eth but only etc. When I download the new parity it automaticly starts parity after the install and moved all my keys to the 'ethereum' folder and not the 'classic' folder and also removed the .parity folder. So it doesn't matter if I restart it with the 'classic' chain parameter because the folder is already gone.

Please make it an option to start parity automaticly after an install so people who use it for ETC don't get an auto ETH startup because they didn't add parameters to the startup.

**Comment by 5chdn** [comment]
How did you install it, via installer? And what OS?

What was your old version?

**Comment by gavofyork** [comment]
the key movement is a one-off event; the workaround is to rename `keys/ethereum` to `keys/classic`.
