### ISSUE TITLE
Minimize tx sending progress

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4921]
As soon as the transaction gets into waiting for tx state, the dialogs (transfer, contract deploy, contract execution, etc.) the tx dialog should 

- minimise to the bottom right
- multiples can be stacked
- keep track of confirmation count
- disappear when x (6/10) confirmations received

Basically it should allow the user to get on with his/her job while still allowing them to keep an eye on the transactions busy.

**Comment by ngotchac** [comment]
NB : could be nice to have them semi-persistent (ie. in local storage), especially for contract deployments : be able to close the UI when the contract is being deployed (eg. with a min block param) and still have it added to the contracts view when it's deployed

**Comment by ngotchac** [comment]
Closed via #4942
