### ISSUE TITLE
Support ENS queries in address lookups

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#4928]

**Comment by jandetlefsen** [comment]
this is an essential feature to prevent fraud in ICOs. this should really have higher priority imo.

**Comment by Arachnid** [comment]
Let me know if there's anything I can do to help get this implemented.

**Comment by chris-remus** [comment]
I'm happy to help @Arachnid help you get this done :)

**Comment by joeyurgz** [comment]
We plan to make use of district.eth to receive contributions for our fundraiser next week. If there is any way support for ENS queries could be added before July 18th that would be amazing.

**Comment by chris-remus** [comment]
Hi from the Volunteer ENS PM! Let me know if there's anything I can do to help make this happen.

**Comment by kayabaNerve** [comment]
What's the progress on this? My Parity version doesn't seem to support it (if it's been added in, is on by default...). If it is added in, how can I enable it?

Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0

**Comment by 5chdn** [comment]
@kayabaNerve No, it's not done yet.

**Comment by Arachnid** [comment]
Can I ask why you closed this?

Does parity not intend to support ENS?

**Comment by jandetlefsen** [comment]
I would read it as a clear statement that this feature is not planned.

**Comment by 5chdn** [comment]
@Arachnid I'm reorganizing tickets. The current UI does not receive any new features anymore. We are launching a new version in a future release and only fix critical bugs. All tickets like this one will be revisited once the new UI is in place. The overall checklists are available here: https://github.com/paritytech/parity-long-term-issues/issues/2
