### ISSUE TITLE
Ubuntu 14.04 The package is of bad quality

### ISSUE THREAD

**Issue by loiluu** [paritytech/parity#4937]
Trying to install Parity 1.6.3 on my machine, and got the above message. More details:

> The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

**Comment by 5chdn** [comment]
Could you also _include the details beneath_ that message?

**Comment by 5chdn** [comment]
Also reported on Gitter, probably related: 

> The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20

For convenience, here is [Debian Policy 5.6.20](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Installed-Size):

> ### 5.6.20 Installed-Size
> 
> This field appears in the control files of binary packages, and in the Packages files. It gives an estimate of the total amount of disk space required to install the named package. Actual installed size may vary based on block size, file system properties, or actions taken by package maintainer scripts.
> 
> The disk space is given as the integer value of the estimated installed size in bytes, divided by 1024 and rounded up.

**Comment by 5chdn** [comment]
@paritytech/ci could you assign this issue to anyone at devops and decide on a deadline? Are we going to improve the debian binaries or are we going to switch to swap? Please, update this ticket within 7 days.

**Comment by General-Beck** [comment]
https://github.com/paritytech/parity/commit/a4a36422d40cf8e2944df3163a0d7308fd85728f
