### ISSUE TITLE
Couldn't get the chain backup with export option

### ISSUE THREAD

**Issue by alptolga** [paritytech/parity#4955]
I use 1.6.3 and I couldn't get the backup. Can you help me?
parity export chain.rlp
Invalid arguments.

Usage:
  parity [options]
  parity ui [options]
  parity dapp <path> [options]
  parity daemon <pid-file> [options]
  parity account (new | list ) [options]
  parity account import <path>... [options]
  parity wallet import <path> --password FILE [options]
  parity import [ <file> ] [options]
  parity export (blocks | state) [ <file> ] [options]
  parity signer new-token [options]
  parity signer list [options]
  parity signer sign [ <id> ] [ --password FILE ] [options]
  parity signer reject <id> [options]
  parity snapshot <file> [options]
  parity restore [ <file> ] [options]
  parity tools hash <file>
  parity db kill [options]

**Comment by rphmeier** [comment]
Try `parity export blocks chain.rlp`

**Comment by alptolga** [comment]
Thank you
