### ISSUE TITLE
Stop snippets from being included automatically

### ISSUE THREAD

**Issue by DaveAppleton** [paritytech/parity#4959]
I tried building a contract based on Zeppelin's sample contracts.

I loaded the various files which include StandardToken.sol, ERC20.sol etc.

When I build I get errors because it is trying to include the snippet StandardToken.sol.

This is clearly undesirable and should be an opt-in behaviour.

**Comment by 5chdn** [comment]
Can you please add what exact error message you get and clarify which steps lead to that issue? Thanks

**Comment by DaveAppleton** [comment]
Zeppelin and most other token contracts will use the same names as the contracts that you use for the token builder.

So even though I save a file called StandardToken.sol, it includes your version instead of mine.

I will try again when I get back on Kovan and report.

**Comment by 5chdn** [comment]
Sorry, I can not reproduce this. Please reopen this issue if you can provide exact steps on what you are doing which allows us to reproduce this very same issue. Thanks!
