### ISSUE TITLE
cannot install parity --master or --beta on several tries macos el capitain 10.11.6

### ISSUE THREAD

**Issue by bg1156** [paritytech/parity#4971]
Last 15 lines from /Users/xxxxxxxxxxx/Library/Logs/Homebrew/parity/02.multirust:

    --- stderr
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    note: Run with `RUST_BACKTRACE=1` for a backtrace.
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
    thread '<unnamed>' panicked at 'explicit panic', .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127

    Build failed, waiting for other jobs to finish...
    error: build failed

    If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
    ethcore/ethcore

    /usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
    curl: (22) The requested URL returned error: 422 Unprocessable Entity
    curl: (3) <url> malformed
      from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
      from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
      from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
      from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
      from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:334:in `issues'
      from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:396:in `dump'
      from /usr/local/Homebrew/Library/Homebrew/brew.rb:130:in `rescue in <main>'
      from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'

**Comment by bg1156** [comment]
==> Installing parity from ethcore/ethcore
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/byroncglenn/Library/Caches/Homebrew/parity--git
==> Checking out tag v1.6.3
==> multirust update stable
==> multirust run stable cargo build --release --features final
Last 15 lines from /Users/xxxxxxxxxx/Library/Logs/Homebrew/parity/02.multirust:
   Compiling blastfig v0.3.3
error[E0277]: the trait bound `&&std::vec::Vec<std::string::String>: std::iter::Iterator` is not satisfied
   --> .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.6.2/build.rs:227:10
    |
227 |         .args(&args)
    |          ^^^^ the trait `std::iter::Iterator` is not implemented for `&&std::vec::Vec<std::string::String>`
    |
    = note: `&&std::vec::Vec<std::string::String>` is not an iterator; maybe try calling `.iter()` or a similar method
    = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `&&std::vec::Vec<std::string::String>`

error: aborting due to previous error

error: Could not compile `ring`.
Build failed, waiting for other jobs to finish...
error: build failed

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
ethcore/ethcore

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:334:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:396:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:130:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'

**Comment by debris** [comment]
There was indeed an issue with compiling ring with latest version of compiler, but we bumped it to version `0.7.1` and it's working again. It looks like you have an outdated brew tap and repo. It may be caused by our organisation name change. I've just [fixed it](https://github.com/paritytech/homebrew-paritytech/commit/7735db982ae87be2e4f4b6b3234517573de94612).

please try:

```
brew untap ethcore/ethcore
brew tap paritytech/paritytech
# now everything should be working fine
brew install parity
```

**Comment by bg1156** [comment]
byroncglenns-iMac:~ byroncglenn$ brew untap ethcore/ethcore
Untapping ethcore/ethcore... (161 files, 94.4KB)
Untapped 4 formulae
byroncglenns-iMac:~ byroncglenn$ brew tap paritytech/paritytech
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
arangodb            goffice             libgtop             vim
aws-sdk-cpp         gucharmap           syncthing
ctop                lean-cli            translate-shell
gnumeric            libgee              varnish

==> Tapping paritytech/paritytech
Cloning into
'/usr/local/Homebrew/Library/Taps/paritytech/homebrew-paritytech'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 3), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Tapped 4 formulae (33 files, 26.3KB)
byroncglenns-iMac:~ byroncglenn$ brew install parity
Updating Homebrew...
==> Installing parity from paritytech/paritytech
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/byroncglenn/Library/Caches/Homebrew/parity--git
==> Checking out tag v1.6.3
==> multirust update stable
Last 15 lines from
/Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust:
2017-03-21 07:53:41 -0500

multirust update stable


If reporting this issue please do so at (not Homebrew/brew or
Homebrew/core):
https://github.com/paritytech/homebrew-paritytech/issues

These open issues may also help:
Parity installation fails
https://github.com/paritytech/homebrew-paritytech/issues/27
osx failed to install parity 1.6.3 (worked with 1.5.11)
https://github.com/paritytech/homebrew-paritytech/issues/39
Brew install parity installs 1.4.10 rather than 1.5.X
https://github.com/paritytech/homebrew-paritytech/issues/36

**Comment by bg1156** [comment]
byroncglenns-iMac:~ byroncglenn$ brew install parity --master
==> Installing parity from paritytech/paritytech
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/byroncglenn/Library/Caches/Homebrew/parity--git
==> Checking out branch master
==> multirust update stable
Last 15 lines from
/Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust:
2017-03-21 08:20:11 -0500

multirust update stable


If reporting this issue please do so at (not Homebrew/brew or
Homebrew/core):
https://github.com/paritytech/homebrew-paritytech/issues

These open issues may also help:
Parity installation fails
https://github.com/paritytech/homebrew-paritytech/issues/27
osx failed to install parity 1.6.3 (worked with 1.5.11)
https://github.com/paritytech/homebrew-paritytech/issues/39
Brew install parity installs 1.4.10 rather than 1.5.X
https://github.com/paritytech/homebrew-paritytech/issues/36
byroncglenns-iMac:~ byroncglenn$ brew install parity --beta
Updating Homebrew...
==> Installing parity from paritytech/paritytech
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/byroncglenn/Library/Caches/Homebrew/parity--git
==> Checking out tag v1.6.3
==> multirust update 1.15.1
Last 15 lines from
/Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust:
2017-03-21 08:21:26 -0500

multirust update 1.15.1


If reporting this issue please do so at (not Homebrew/brew or
Homebrew/core):
https://github.com/paritytech/homebrew-paritytech/issues

These open issues may also help:
Parity installation fails
https://github.com/paritytech/homebrew-paritytech/issues/27
osx failed to install parity 1.6.3 (worked with 1.5.11)
https://github.com/paritytech/homebrew-paritytech/issues/39
Brew install parity installs 1.4.10 rather than 1.5.X
https://github.com/paritytech/homebrew-paritytech/issues/36

**Comment by 5chdn** [comment]
can you please run it again with the `--verbose` flag? the log does not show any error messages at all. thanks

**Comment by bg1156** [comment]
ok do you mean (not a Techie) brew install parity --verbose?

**Comment by 5chdn** [comment]
yes, exactly :)

**Comment by bg1156** [comment]
$ brew install parity --verbose
Updating Homebrew...
==> Installing parity from paritytech/paritytech
==> Cloning https://github.com/ethcore/parity.git
Updating /Users/byroncglenn/Library/Caches/Homebrew/parity--git
git config remote.origin.url https://github.com/ethcore/parity.git
git config remote.origin.fetch +refs/tags/v1.6.3:refs/tags/v1.6.3
==> Checking out tag v1.6.3
git checkout -f v1.6.3 --
HEAD is now at ccc5732... js-precompiled 20170314-121823
git reset --hard v1.6.3
HEAD is now at ccc5732 js-precompiled 20170314-121823
git submodule foreach --recursive git submodule sync
Entering 'ethcore/res/ethereum/tests'
git submodule update --init --recursive
==> multirust update stable
Failed to execute: multirust update stable

==> Formula
Tap: paritytech/paritytech
Path:
/usr/local/Homebrew/Library/Taps/paritytech/homebrew-paritytech/parity.rb
==> Configuration
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b0a8468bfeab9b147ec5e8a311557a17d1e4722e
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby =>
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH:
/usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH:
/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR:
/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.11
ACLOCAL_PATH: /usr/local/share/aclocal
PATH:
/usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: paritytech/paritytech/parity 1.6.3 did not build
Logs:
     /Users/byroncglenn/Library/Logs/Homebrew/parity/00.options.out
     /Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust
If reporting this issue please do so at (not Homebrew/brew or
Homebrew/core):
https://github.com/paritytech/homebrew-paritytech/issues

These open issues may also help:
Parity installation fails
https://github.com/paritytech/homebrew-paritytech/issues/27
osx failed to install parity 1.6.3 (worked with 1.5.11)
https://github.com/paritytech/homebrew-paritytech/issues/39
Brew install parity installs 1.4.10 rather than 1.5.X
https://github.com/paritytech/homebrew-paritytech/issues/36

**Comment by debris** [comment]
look like there is an issue with `multirust` :/
Can you paste the content of `/Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust` here? To copy content of the file simpy run

```
cat /Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust | pbcopy
```

and paste it here

**Comment by bg1156** [comment]
byroncglenns-iMac:~ byroncglenn$ cat /Users/byroncglenn/Library/Logs/Homebrew/parity/01.multirust
2017-03-21 16:08:46 -0500

multirust update stable

Failed to execute: multirust update stable

HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b0a8468bfeab9b147ec5e8a311557a17d1e4722e
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.11
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/multirust/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by bg1156** [comment]
was able to finally get 1.7.0 up and running, thanks to all @ paritytech
