### ISSUE TITLE
Merge `parity/dir.rs` and `ethstore/src/dir/paths.rs`

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4972]

**Comment by guanqun** [comment]
Is this still a valid issue? If so, I'll can help fix this, this seems to be a small ticket. Basically I believe we'd move stuff move `ethstore/src/dir/paths.rs` to `util/path/src/lib.rs`.

**Comment by debris** [comment]
Yes it is. Any help is much appreciated ;)

**Comment by guanqun** [comment]
Thank you @debris  I'll get some spare time to fix this.

**Comment by debris** [comment]
closing in favor of #6209
