### ISSUE TITLE
Latest master corrupts chain

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#4985]
I created a Private PoA chain.
Using 1.6, all works fine.
Using v1.7.0-unstable-badb3729c-20170320, if I send a tx, I get a 
```
Stage 4 block verification failed for #307 (814c…1d9d)
Error: Block(InvalidReceiptsRoot(Mismatch { expected: 584d201b2d27d8579a79f85c7c6e5cfc2581affd7183f9cd71c2a67d5c2ff5ab, found: 45bef3c8f45af0174311babea84ed659c7380a7249e2fe1ac5d7749f2918a383 }))
```
and parity 1.7 never recovers from it.

Workaround: delete the db, restart using 1.6.

**Comment by keorn** [comment]
Which version of Parity was the chain started with (more specifically, has there been any blocks issued with Parity 1.5)?
Can you describe the scenario in more detail i.e.:
1. Some blocks were issued with Parity x
2. Transaction is submitted
3. Parity y makes a block
4. Parity z rejects the block

**Comment by chevdor** [comment]
Hi @keorn,

Let me try giving you all the details.
The PoA chains starts from a node running version **Parity/v1.5.0-unstable-d2e6fc0-20170119/arm-linux-gnu/rustc1.14.0**. There is a single Authority there.

After few blocks, I connect a second node running **v1.7.0-unstable-badb3729c-20170320**. The sync works good until I send a tx with this node. At that point, the v1.5 node keeps going happily, my colleague on windows with **Parity//v1.5.3-beta-0f99b1e-20170220/x86_64-windows-msvc/rustc1.14.0** keeps happily getting blocks.

Then I stop this 1.7 node and restart with **version Parity/v1.6.0-unstable-b4ff08b-20170118/x86_64-macos/rustc1.14.0** (after removing the db). Using 1.6, the sync goes beyond the block that was blocking (no pun intended).

I saw the issue 2/2 times so I think this is reproducable 100%.

**Comment by keorn** [comment]
Yep, this is an issue with the default [EIP98](https://github.com/paritytech/parity/pull/4296/files).
When moving to 1.6 series it is necessary to add `"eip98Transition": "0x7fffffffffffffff"` field to the `"params"` field of the spec. However if you have already issued a few blocks without that you will need to add `"validateReceipts": false` to the spec (soon to be `"validateReceiptsTransition": "0x7fffffffffffffff"`). Sorry for the hassle.

**Comment by 5chdn** [comment]
had the same issue yesterday, too #5006

adding the `eip98Transition` to `params` did the trick.
