### ISSUE TITLE
Clickable elements in SelectionList should be `a` not `div`

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#4991]
You cannot click those elements using `vimium` cause they are not recognised as links :)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since March, neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
