### ISSUE TITLE
Brew install error [brew linkapps]

### ISSUE THREAD

**Issue by traviagio** [paritytech/parity#4994]
Last 15 lines from /Users/georgio/Library/Logs/Homebrew/parity/02.multirust:
       Compiling primal-estimate v0.2.1
    error[E0277]: the trait bound `&&std::vec::Vec<std::string::String>: std::iter::Iterator` is not satisfied
       --> .brew_home/.multirust/toolchains/stable/cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.6.2/build.rs:227:10
        |
    227 |         .args(&args)
        |          ^^^^ the trait `std::iter::Iterator` is not implemented for `&&std::vec::Vec<std::string::String>`
        |
        = note: `&&std::vec::Vec<std::string::String>` is not an iterator; maybe try calling `.iter()` or a similar method
        = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `&&std::vec::Vec<std::string::String>`

    error: aborting due to previous error

    error: Could not compile `ring`.
    Build failed, waiting for other jobs to finish...
    error: build failed

    If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
    ethcore/ethcore

    /usr/local/Homebrew/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
    curl: (22) The requested URL returned error: 422 Unprocessable Entity
    curl: (3) <url> malformed
      from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:184:in `open'
      from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:233:in `issues_matching'
      from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
      from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
      from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:334:in `issues'
      from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:396:in `dump'
      from /usr/local/Homebrew/Library/Homebrew/brew.rb:130:in `rescue in <main>'
      from /usr/local/Homebrew/Library/Homebrew/brew.rb:31:in `<main>'
    Warning: `brew linkapps` has been deprecated and will eventually be removed!

    Unfortunately `brew linkapps` cannot behave nicely with e.g. Spotlight using
    either aliases or symlinks and Homebrew formulae do not build "proper" `.app`
    bundles that can be relocated. Instead, please consider using `brew cask` and
    migrate formulae using `.app`s to casks.
    Error: No such keg: /usr/local/Cellar/parity

**Comment by debris** [comment]
```
brew untap ethcore/ethcore
brew tap paritytech/paritytech
brew install parity
```
😄
