### ISSUE TITLE
Make Dapps server light-client friendly

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5001]
Specifically regarding the registrar: the light client can make calls to it, but they may take an indeterminate amount of time to resolve. 

Maybe `hash_fetch::urlhint::ContractClient` should yield futures?
Will be optimized by having the light client attempt to cache all storage of certain contracts, but that's not implemented yet.

cc @tomusdrw

**Comment by tomusdrw** [comment]
Returning `Futrue` sounds good although it might complicate dapps router (if using our current `hyper` version; next version is future-based), but it's doable :)
