### ISSUE TITLE
Error Block InvalidReceiptsRoot Mismatch on private Geth network

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#5006]
I'm trying to add a parity node to a geth private network, and getting:

    Stage 4 block verification failed for #527 (0dbb…a8de)
    Error: Block(InvalidReceiptsRoot(Mismatch { expected: 34f7500a5c01d8fe18cafabb16dc2485692f0d7cffd8e19ece0949a8d25ffa81, found: 45bef3c8f45af0174311babea84ed659c7380a7249e2fe1ac5d7749f2918a383 }))

It's reproducable with the following setup:

    parity --chain ebloc.json --network-id 23422 --gas-floor-target 994712388 --reserved-peers ebloc.txt

Where the genesis is:

    {
      "name": "Ebloc",
      "engine": {
        "Ethash": {
          "params": {
            "gasLimitBoundDivisor": "0x400",
            "minimumDifficulty": "0x20000",
            "difficultyBoundDivisor": "0x800",
            "durationLimit": "0xd",
            "blockReward": "0x4563918244F40000",
            "registrar": "0x81a4b044831c4f12ba601adb9274516939e9b8a2",
            "homesteadTransition": 0,
            "eip150Transition": 9223372036854775807,
            "eip155Transition": 9223372036854775807,
            "eip160Transition": 9223372036854775807,
            "eip161abcTransition": 9223372036854775807,
            "eip161dTransition": 9223372036854775807
          }
        }
      },
      "params": {
        "accountStartNonce": "0x0",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID": "0x5B7E"
      },
      "genesis": {
        "seal": {
          "ethereum": {
            "nonce": "",
            "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
          }
        },
        "difficulty": "0x400",
        "author": "0x3333333333333333333333333333333333333333",
        "timestamp": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x0",
        "gasLimit": "0x3B4A1B44"
      },
      "accounts": {
        "0xda1e61e853bb8d63b1426295f59cb45a34425b63": {
          "balance": "1000000000000000000000000000000"
        }
      }
    }

And a working reserved peers: 

    enode://2d4c7f94298188051afca86334fdda698d1842d2a8e2e1802137843c1b78cc4a88808e8077a476bb6d45afe7481caad7f008285d6f868c3bb58fdf756434733d@91.64.222.166:30303
    enode://7f3bebdd678d5a0ebe2701b2f7858763f5ce03fc531fe989fb7bb41d2e8e1237ae5b092666171a180afba0c47f1aad055e2bf6e1287fcdc756f183902764eba2@79.123.177.145:3000
    enode://4d331051d8fb471c87a9351b36ffb72bf445a9337727d229e03c668f99897264bf11e1b897b1561f5889825e2211b06858139fa469fdf73c64d43a567ea72479@193.140.197.126:3005

I'm not sure what's causing this and how to proceed connecting the parity node into the existing geth network. cc @avatar-lavventura

**Comment by arkpar** [comment]
try adding `"eip98Transition": "0x7fffffffffffffff"` to `params` section

**Comment by 5chdn** [comment]
Reset the database, added eip98 to params, but same result.

**Comment by 5chdn** [comment]
Ok, that worked until block 30039, now I'm stuck with the same error again:

    2017-03-23 12:47:59  Verifier #1 WARN client  Stage 4 block verification failed for #30039 (f3b5…7560)
    Error: Block(InvalidStateRoot(Mismatch { expected: 0fb93e9ff7824d71b654d347c984e1e2ad7dbc5cd3557793b16ce92c5714be99, found: fb13f27d8cd691676d390ebcecac15a46430b29e92390f6045b79e8f6074e3ac }))
