### ISSUE TITLE
RLP nested list encoding/decoding is asymmetric

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5008]
If you have a `Vec<Vec<u8>>`, you can only encode it with `begin_list` and then `append_list` in a loop. But you can then decode it (wrongly) with `as_list`, which calls `as_val` internally.

Example:
```rust
struct Foo(Vec<Vec<u8>>);
impl Encodable for Foo {
    fn append_rlp(&self, s: &mut RlpStream) {
        s.begin_list(self.0.len());
        for i in &self.0 { s.append_list(i) }
    }
}

impl Decodable for Foo {
    fn decode(rlp: &UntrustedRlp) -> Result<Self, DecoderError> {
        Ok(Foo(rlp.as_list()?))
    }
}

fn main() {
    let foo = Foo(vec![vec![1, 2, 3], vec![4, 5, 6]]);
    let raw = ::rlp::encode(&foo);
    assert!(UntrustedRlp::new(&raw).as_val().is_err());
}
```

**Comment by debris** [comment]
we have discussed the problem. it's symetric. Current api requires encoding to be either

```rust
s.append_list::<Vec<u8>, _>(&self.0)
```

or 

```rust
s.begin_list(self.0.len());
        for i in &self.0 { s.append(i); }
```

**Comment by rphmeier** [comment]
Yep, just gonna downgrade this to annoyance; the fact that I had to supply a type hint made me think that I wasn't supposed to use that method for this purpose.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's inactive since March, neither assigned nor linked to any milestone.

@paritytech/core-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by rphmeier** [comment]
@debris interested in taking this one? if you think it's not worth refactoring feel free to close, since I don't see an immediate API solution to make it better.
