### ISSUE TITLE
Provide way to submit correction tx at same nonce

### ISSUE THREAD

**Issue by flyswatter** [paritytech/parity#5010]
I've recently spoken to several users who did this, and were able to get our Parity backend into a bad state:

Submit a tx at an account's current nonce with a gas price too low to be mined.

Parity keeps that tx in its queue, and will reject subsequent txs with higher gas and the same nonce.

Either parity should accept same-nonce transactions that haven't been mined yet, or should provide a method to unqueue unmined transactions.

**Comment by tomusdrw** [comment]
Parity will accept the transaction with higher *gas price* and the same nonce.
We're currently working on some UI improvements to indicate such errorneous state to the user #4958 and also give them couple of remedies like `parity_removeTransaction` RPC #4949

**Comment by flyswatter** [comment]
Oh, good to know, thank you!

**Comment by 5chdn** [comment]
Closing as fixed as per patches in #4958 and #4949 .
