### ISSUE TITLE
DappReg content registration needs repo/owner + commit 

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5017]
Extracting to `https://codeload.github.com/<owner>/<repo>/zip/<hash>` as the final URL - bear in mind these are logged as `<owner>/<Repo> + <hash>` in the underlying contract (Manual process found with @CraigglesO to get it in)

**Comment by ngotchac** [comment]
Wouldn't inputting the right URL be enough? Not sure I understand this one..

**Comment by ngotchac** [comment]
Users can enter `https://codeload.github.com/<owner>/<repo>/zip/<hash>` in the Dapp edit dialog, and the dapp will load correctly. Thus, closing this issue.
