### ISSUE TITLE
Add evm_increaseTime

### ISSUE THREAD

**Issue by KenKappler** [paritytech/parity#5022]
It would be useful to be able to advance time in the evm as in test rpc: <https://github.com/ethereumjs/testrpc>
when you are running parity with --chain=dev

This would mean that truffle and embark could integrate better with Parity for testing

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.
