### ISSUE TITLE
Transfer allows character inputs and attempts sending thereof

### ISSUE THREAD

**Issue by CraigglesO** [paritytech/parity#5026]
Step 1) Instead of sending a number value [ amount to transfer (in ETH) ] send a character (a-z, A-Z)

Step 2) go to the account and see what happens
a) nothing shows up for the amount
b) error:
![alt](https://cdn.pbrd.co/images/Nz09sjx2i.png)

**Comment by ngotchac** [comment]
I'm not sure I really understand this issue ; I cannot reproduce it. If something else than a number is entered in the value input, it will send 0 ETH.

**Comment by ngotchac** [comment]
@CraigglesO Any update on this ?

**Comment by CraigglesO** [comment]
I updated to the latest and no longer receive the error.

![alt-img](https://cdn.pbrd.co/images/GCLlNpeM.png)

Should we make sure it says 0.00Eth instead of nothing though?

**Comment by ngotchac** [comment]
Definitely !
