### ISSUE TITLE
Owner list of an imported Mist multisig wallet

### ISSUE THREAD

**Issue by iisi85** [paritytech/parity#5029]
For the imported Mist multisig wallet 0x96815Ef9e0cD8e57FF88a40008aa2328a43fb8a3 with owners:

- 0x3C15b3511df6F0342E7348cC89af39A168B7730f 
- 0x333113fCcF6E55969d71257d8552d194147B160e
- 0xe5C6F768EbC8CD2cB7FFc8C5Bf0d7C4714C20ef5

the account 0x3C15b3511df6F0342E7348cC89af39A168B7730f is shown twice in the owners list. Feature or bug?

**Comment by 5chdn** [comment]
Looks like a bug, thanks for reporting.

![screenshot at 2017-03-27 11-22-21](https://cloud.githubusercontent.com/assets/15729797/24349640/fb755ea0-12df-11e7-816d-083d10d584f0.png)
