### ISSUE TITLE
Parity adds itself to Windows startup

### ISSUE THREAD

**Issue by D-Nice** [paritytech/parity#5301]
It's quite an annoyance, with every new update, having to disable Parity from Windows startup. Could there at the very least be an option or prompt to disable this.

**Comment by arkpar** [comment]
Should not do that on upgrade

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for 2 months. It's neither assigned nor linked to a milestone.

Please, decide on a deadline and assign this ticket to a developer within 7 days or close it otherwise.

**Comment by debris** [comment]
please reopen if still occurs
