### ISSUE TITLE
Stage 2 block verification failed on Kovan testnet

### ISSUE THREAD

**Issue by D-Nice** [paritytech/parity#5306]
Attempting to sync to Kovan, on a Windows 7 x64 machine. Attempted with parity 1.6.3 and 1.6.4.

Paramaters used: --chain=kovan --no-warp

After it syncs to the best block, I get the following error, and lose connection to all peers:
    
    Stage 2 block verification failed for 866d.9b1a: Block(InvalidSeal)

Here is a longer example of the output

```
2017-03-27 15:48:13  Syncing  #510319 a0d8.c195   976 blk/s   88 tx/s  65 Mgas/s      0+    0 Qed   #510319    4/ 5/25 p
eers   188 MiB db    4 MiB chain  0 bytes queue    5 MiB sync  RPC:  2 conn, 13 req/s,  34 µs
2017-03-27 15:48:14  Stage 2 block verification failed for 866d.9b1a: Block(InvalidSeal)
2017-03-27 15:48:48     0/ 0/25 peers   188 MiB db    4 MiB chain  0 bytes queue   11 KiB sync  RPC:  2 conn, 10 req/s,
 28 µs
```

**Comment by keorn** [comment]
Make sure that your https://time.is/ exact.

**Comment by D-Nice** [comment]
@keorn Thank you, it indeed seems to be sync'd fine now. It was only 6.5 seconds behind though prior, what is the allowed threshold, and I presume the verification failed due to a timestamp mismatch with my local clock?

**Comment by keorn** [comment]
4 seconds away should be good enough. Any NTP server is fine, but it seems that it can drift pretty fast (was also the case for another Windows user).
