### ISSUE TITLE
Parit  1.6.4 cannot display VSL token amounts correctly in wallet address 

### ISSUE THREAD

**Issue by pplwjd** [paritytech/parity#5310]
My Parity 1.6.4 in Windows  displays wrong VSL token amounts  in wallet address. It displays  as follow:  3,888,888,888,888,888,888,888.9 VSL

**Comment by tomusdrw** [comment]
Seems that the amount of decimals is configured incorrectly. How many decimals is your token supposed  to have?
![screenshot from 2017-03-28 09-29-37](https://cloud.githubusercontent.com/assets/581548/24393644/20eba090-1399-11e7-8cb7-8badb9481186.png)

**Comment by pplwjd** [comment]
I don't think it is because of decimals configuration. The number is  also totally wrong.   The number 3,888,888,888,888,888,888,888.9 seems weird and has no any relation with the token amounts that I have.

**Comment by pplwjd** [comment]
Parity 1.6.5 still has this issue. Any progress?

**Comment by 5chdn** [comment]
Can you provide an address and/or maybe a screenshot?

**Comment by pplwjd** [comment]
![parity_vsl](https://cloud.githubusercontent.com/assets/5856591/24845521/4a2a1e5e-1de5-11e7-9824-b325580a3adc.png)

**Comment by pplwjd** [comment]
The amount displayed in Mist  is Ok.

**Comment by jamesgroton** [comment]
We are in the process of fixing this issue now. A small mistake was made putting the token listing back up.

**Comment by 5chdn** [comment]
Fixed this last week.
