### ISSUE TITLE
Tx progress should display tokens in the case of token transfers

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5315]
Currently is just indicates that a method is executed (Incoming txs shows tokens, it would be good if the outgoing tracker can do the same)

![parity 2017-03-28 14-20-08](https://cloud.githubusercontent.com/assets/1424473/24405185/3ba4edf8-13c4-11e7-936b-ff5bff7b68d6.png)

**Comment by ngotchac** [comment]
Closed via #5324
