### ISSUE TITLE
Cannot see ETH in parity wallet

### ISSUE THREAD

**Issue by rrevanth** [paritytech/parity#5326]
I transferred ETH from my coinbase to parity wallet installed on my mac.

The transaction in my coinbase account shows done but I still cannot see the transaction in my parity wallet.

how much time will it take until its reflected?

**Comment by tomusdrw** [comment]
Make sure you are:
1. Connected to the right network (homestead?)
2. Fully synced (compare the block number)

In case you're not synced:
1. Check how many peers do you have (should be something like `0/10/25 peers`)
2. Check if you time is in sync (https://time.is should render "Your time is exact.")
3. Check that Parity is not blocked by a firewall.

Before you're fully synced you can pre-verify that the transfer took place by checking some block explorers (etherscan.io, etherchain.org).

**Comment by piotrbednarczyk** [comment]
I noticed this issue as well. Transferred amount from Poloniex, transaction is confirmed (checked at etherscan.io), client is in sync and what is more, it shows me the incoming transaction on the transaction list for account, but still "There are no balances associated with this account".

**Comment by rrevanth** [comment]
After full sync, I got it in my account! Sorry about that!

Closing the issue!

**Comment by 5chdn** [comment]
@piotrbednarczyk can you update to the latest release? 

https://github.com/paritytech/parity/releases

**Comment by piotrbednarczyk** [comment]
After update to 1.6.5 works fine. Thanks.
