### ISSUE TITLE
Unable to fetch update: HashMismatch. Infinite re-fetch leads to out of disk space

### ISSUE THREAD

**Issue by AntonioJuliano** [paritytech/parity#5327]
Parity [stable-release docker image](https://store.docker.com/community/images/ethcore/parity) has been repeatedly trying to fetch an update, and failing with a HashMismatch:

```
2017-03-29T06:06:53.506785173Z 2017-03-29 06:06:53 UTC Attempting to get parity binary d002…b3c8
2017-03-29T06:06:53.510099273Z 2017-03-29 06:06:53 UTC Imported #3438186 00c9…4643 (7 txs, 0.20 Mgas, 7.37 ms, 1.47 KiB)
2017-03-29T06:06:54.865579647Z 2017-03-29 06:06:54 UTC Unable to fetch update (1.5.12-stable-0caa…775d): HashMismatch { expected: d0024f1b713d46ff189e72a2af15cc3e256cf917b686d3cd808bfcf53f0eb3c8, got: 77dfb57885d21d75f7997ef785a690ce6f5141c92b01556bf36a120993c7a9e7 }
2017-03-29T06:06:56.538403057Z 2017-03-29 06:06:56 UTC Attempting to get parity binary d002…b3c8
2017-03-29T06:06:56.540792728Z 2017-03-29 06:06:56 UTC Imported #3438187 23ef…c386 (3 txs, 0.08 Mgas, 7.93 ms, 0.92 KiB)
2017-03-29T06:06:57.374802299Z 2017-03-29 06:06:57 UTC Unable to fetch update (1.5.12-stable-0caa…775d): HashMismatch { expected: d0024f1b713d46ff189e72a2af15cc3e256cf917b686d3cd808bfcf53f0eb3c8, got: 77dfb57885d21d75f7997ef785a690ce6f5141c92b01556bf36a120993c7a9e7 }
...
```

This issue is made much worse because it appears every time it tries to do the fetch it stores something in the tmp/ folder which is not cleaned up afterwards. This causes the size of the image to keep growing indefinitely until all the space on the host is taken up, and parity crashes from there being no free space left. Parity ended up downloading over 100GB before it crashed my node.

I'm running the latest version (as of this writing) of the parity stable-release dockerfile with the default arguments, running on Docker version 1.11.2, on an Ubuntu 14.04.5 server. If you need any more information or logs, please let me know.

**Comment by 5chdn** [comment]
Same happens via brew, reported on gitter:

> Noob question: So I decided to upgrade parity to 1.6.5 (running on macOS, homebrew) and ran brew update && brew upgrade and the following error occurred: Any suggestions?
>
>        Error: SHA256 mismatch
>        Expected: 6700743239f6aa4b2b7a2d8b9a98ddab22f7362be827c4a54cccd65e74bcd692
>        Actual: 65b32bd3178f442ddd9e2eb24d04ba16a6dad933f46ad7fec215900fa9358cfb

**Comment by zertrin** [comment]
Confirmed here too (Debian Jessie, Docker 17.03.1-ce, Parity stable-release from dockerhub):

![image](https://cloud.githubusercontent.com/assets/1447163/24593468/5cb03d86-1856-11e7-95b6-b81b877aeaa1.png)

Parity's container `/tmp` ate about 1 TB of disk space, downloading a 27.7 MB file over and over again.....

Good that I caught it today by checking the logs and then finding this issue, and then checking the monitoring graphs. Given the trend, the disk would have been full by tomorrow. 😨 

My current workaround:
 - `docker rm myparitynode` to get rid of the files from the container (the database and config is stored in a separate volume of course). _(Note: I tried to do `rm /data/docker/docker-data/aufs/diff/5f4718a7051d20b2666b77f5e08de7c3e3cd4c040af7b931f1f87657d23ad4f3d/tmp/*` first, but rm complained that there was too many arguments... (too many files for rm to handle... that's the first time it happens to me!))_
 - add the following options in addition to the normal ones while running docker run: `--no-download --auto-update none`

**Comment by 5chdn** [comment]
@paritytech/ci `stable-release` docker image is still on 1.5.11

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

@zertrin @AntonioJuliano the initial issue should be fixed for quite a while now, and this issue is the `stable-release` branch on docker is pointing to an outdated version of parity. See #5435 - please use version string till this is fixed by @paritytech/ci - e.g. `docker pull ethcore/parity:v1.6.6` - closing as stale. Please reopen if latest versions of parity still show this behavior.
