### ISSUE TITLE
Typo in Readme/Build from Source

### ISSUE THREAD

**Issue by mmervecerit** [paritytech/parity#5328]
<img width="921" alt="screen shot 2017-03-29 at 10 34 45" src="https://cloud.githubusercontent.com/assets/15267081/24443957/5ee3b69c-146d-11e7-93ef-5ef269e8ffc1.png">

"git clone https://github.com/ethcore/parity" should be replaced with "git clone https://github.com/paritytech/parity".

**Comment by 5chdn** [comment]
spotted while wildly grepping the source:

    github.com/ethcore
    githubusercontent.com/ethcore
    ethcore.github.io

unsure whether the following items are affected:

    travis-ci.org/ethcore
    coveralls.io/github/ethcore

still working with the old name:

    gitter.im/ethcore

**Comment by rphmeier** [comment]
Fixed in #5330
