### ISSUE TITLE
UI WS API should not queue transactions when not connected

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5333]
Return error, retry on UI when node is available (stops the flood of requests when node comes back up, which will be very detrimental to public & light nodes)

Needs a full end-to-end test of all functionality once done.

**Comment by jacogr** [comment]
Drop it around here, returning exception -

https://github.com/paritytech/parity/blob/master/js/src/api/transport/ws/ws.js#L243

(As well as removing sending queued messages when re-connected).

**Comment by Tbaut** [comment]
Stale issue. Please reopen to https://github.com/parity-js/shell/ if you think it's still relevant for Parity UI
