### ISSUE TITLE
Make it easier to use Parity for continuous integration testing.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5335]
At the moment, Parity is a bit awkward to use for integration testing because it is designed to be secure (generally a good thing).  This means things like `unlockAccount` RPC call only last for a single request and creating a new account (`parity_newAccountFromPhrase`) needs to be run against a live node.

The ideal outcome of this issue would be for Parity to have a well established pattern for using it as part of a headless dApp integration testing suite.  This means a clear, supported, and well documented workflow for using Parity in a non-secure but easy to test against way.

One potential solution would be to make it so `--chain dev` came with several accounts baked in and unlocked, with one of them as the coinbase and all of them having various amounts of ETH available (at least one should have no ETH and at least one should have a ton of ETH).  By default, the one with a lot of ETH should be the current coinbase.  This would allow integration test authors to spin up a node with a new chain, upload contracts, test contract/dApp behavior, and then tear down the chain.

Whatever the solution, for security purposes it may make sense to make the solution *only* work for dev chains or otherwise be disabled for main network chain (not sure how feasible this is).

**Comment by 5chdn** [comment]
This issue is labelled with _asap_: No need to stop dead in your tracks, however the issue should be addressed as soon as possible. But it is inactive for more than 2 months and not assigned.

@paritytech/core-devs Please, review this ticket within 7 days, assign it to a developer and decide if the 1.7 milestone is a realistic deadline. Thanks :)

**Comment by Pet3ris** [comment]
Hi @MicahZoltu , was this ever documented ? I'm struggling with this problem in the following Issue: https://github.com/paritytech/parity/issues/9090.

**Comment by MicahZoltu** [comment]
@Pet3ris I don't remember the specifics of this issue, but I do have a workflow for testing against a Parity node that isn't too bad.  [This repository](https://github.com/Keydonix/parity-instantseal) has a parity node with one account that has a bunch of ETH and is running instant seal, so blocks are mined as soon as transactions are submitted.  This makes for very fast integration tests using something like docker-compose.  Note: You can get that image pre-built from [Docker Hub](https://hub.docker.com/r/keydonix/parity-instantseal/)

The caveat is that the account isn't unlocked, but the private key is well known, so your dapp/tests need the ability to sign transactions on their own.  If your dapp is written to use a web3.currentProvider, you can use a library like `ethers.js` to create a `web3.currentProvider` that can sign with this private key and then submit the transaction to the backing Parity node pre-signed.

As far as I know, there still isn't a way in Parity to have an account "unlocked" in the sense that any transactions submitted to it are auto-signed.
