### ISSUE TITLE
Incorrect error message when passing invalid interface to CLI.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5339]
Due to a mistake in a script, I called parity with the following (note that shell expansion didn't occur for the code between the backticks):
```
parity --ui-interface `hostname -I`
```
The error printed to stdout was `Invalid port specified: 8180`.

Expected error message would be:
```
Invalid interface: `hostname -I`
```

**Comment by tomusdrw** [comment]
Should be covered with #4474

**Comment by 5chdn** [comment]
Closing in favor of #4474.
