### ISSUE TITLE
Add support for wildcard interface binding.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5340]
When running parity it defaults to only binding the UI to localhost, which is good (secure).  However, when running a dev chain for testing it is often useful to bind to an external port (incredibly insecure).  It would be nice if the UI allowed for binding to a wildcard (`*`) as a developer ergonomic issue.  Binding to a specific interface requires the script that is launching Parity to know what interface it should bind to which results in a lot of complexity if you want to enable turn-key development (i.e., new dev can just run the script and it works no matter his environment).

At the moment, my workaround is to bind to `hostname -I`, though this will not work for all developers and it adds complication to running inside of docker (which is my primary use case) because docker's recommended mechanism for entrypoints doesn't support shell expansion.

**Comment by tomusdrw** [comment]
Using `--ui-interface 0.0.0.0` should work fine, but you will also need to run it with `--ui-no-validation` flag to disable `Host/Origin` validation.
As part of #4474 we will also introduce an option to automatically listen on all interfaces using `--ui-interface all`

**Comment by MicahZoltu** [comment]
`0.0.0.0` worked.  Feel free to close this if you believe #4474 covers the usability/documentation aspects of this such as providing a consistent and documented mechanism for port/host binding across the various CLI options.
