### ISSUE TITLE
Zero Ether

### ISSUE THREAD

**Issue by xmaenx** [paritytech/parity#5342]
Hi ,

yesterday I downloaded the mac version, and new account successfully done. But when I transferred ETH from my exchange to my parity account wallet address , Nothing went to my address although in etherscan the transaction was done,
Should I wait more time or something is wrong ? the transaction now passed 10 hours and nothing happened still my wallet address haas 0 ETH

**Comment by xmaenx** [comment]
Sorry I was not syced ,
the issue resolved

**Comment by 5chdn** [comment]
which version was that?
