### ISSUE TITLE
Evaluation/compare UglifyJS to Babili

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5343]
Swap if benefits in terms of size, fit into build pipeline

**Comment by ngotchac** [comment]
The benchmarks (https://github.com/babel/babili#benchmarks) aren't quite satisfying yet... And it seems that it targets newish browsers (compiles to ES2015+), which might be fine but we need to make a decision on that.

**Comment by debris** [comment]
please reopen if still relevant
