### ISSUE TITLE
Windows download from ethcore.io website gave me Parity 1.4.3

### ISSUE THREAD

**Issue by housemobile** [paritytech/parity#5347]
Had to get it from github

**Comment by hcekne** [comment]
I had the same issue..

**Comment by rphmeier** [comment]
cc @paritytech/ci

**Comment by 5chdn** [comment]
had multiple support requests on reddit and stack exchange with the same issue.

**Comment by 5chdn** [comment]
Is this fixed?

**Comment by jesuscript** [comment]
yeah, we fixed it
