### ISSUE TITLE
Tx display doesn't handle syncing very well

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5349]
1. Node was syncing
2. Send tx to contract (contract interface)
3. Tx display doesn't update, even after node indicated Tx has been mined
4. UI refresh still doesn't make the display update

![parity 2017-03-30 16-15-37](https://cloud.githubusercontent.com/assets/1424473/24508619/4c054142-1564-11e7-9c62-d3fd8f01cd63.png)

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's assigned to @ngotchac but not linked to a milestone.

Please, decide on a deadline within 7 days or close it otherwise.
