### ISSUE TITLE
Tx minimised should not use localSorage

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5358]
Get transactions for local/available from the Node as per the Signer views.

**Comment by jacogr** [comment]
Should also resolve #5349

**Comment by jacogr** [comment]
Should also resolve https://github.com/paritytech/parity/issues/5359

**Comment by ngotchac** [comment]
I don't think we want that. The main issue is for contract deployment : the node doesn't know anything about contract deployment, it just executes transactions. Storing them in localstorage enables the UI to recover a contract deployment even if it's closed in the middle of the mining.
