### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by songproducer** [paritytech/parity#5369]
When I run:

curl https://sh.rustup.rs -sSf | sh

I get:

curl: (35) Unknown SSL protocol error in connection to sh.rustup.rs:443

**Comment by jackweath** [comment]
I can't reproduce this. 

What version of cURL are you using? `curl -V` should tell you. 

Is the error persistent on different networks?

**Comment by songproducer** [comment]
curl 7.38.0 (x86_64-apple-darwin14.0.0) libcurl/7.38.0 OpenSSL/0.9.8zd zlib/1.2.8 libidn/1.20 libssh2/1.4.3

When I tried:
multirust override beta
I got:
-bash: multirust: command not found

**Comment by arkpar** [comment]
@songproducer You don't need `multirust` or `rustup` to install on macOS unless you want to build from source for some reason. Just use the installer download available here https://github.com/paritytech/parity/releases or homebrew.

**Comment by jackweath** [comment]
@songproducer Also, your version of cURL is from 2014, so you may want to update it.
