### ISSUE TITLE
Parity burning CPU.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5370]
Standard Windows install of `Parity/v1.5.2-beta-948a538-20170208/x86_64-windows-msvc/rustc1.14.0`.  Today I caught Parity burning 15%-25% of CPU steadily and it would not stop.  I am fully synced to main network.  Restarting Parity resolved the issue.

When I opened up the logs I saw the following error message spammed multiple times per second consistently (and no other logs):
```
WS Error <Io(Error { repr: Os { code: 10053, message: "An established connection was aborted by the software in your host machine." } })>
```

I don't believe I had anything connected to/talking to Parity at the time of the incident.

Chrome debugger of the web UI showed what appears to be normal polling behavior over the web socket but nothing out of the ordinary.

I do not know how to reproduce this issue, but let me know here if there are additional debugging steps I can take should the problem recur.

**Comment by tomusdrw** [comment]
Are you using only WS interface (port 8180; Parity UI) or are there also some requests happening over HTTP RPC (port 8545)?

**Comment by MicahZoltu** [comment]
At the time, I believe I was only using the UI.  It is possible that I had at some point used the HTTP JSON-RPC (likely on accident while testing), though I had restarted my computer not long before so the chances of that are mildly low.

It definitely could have been #4389.

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

@paritytech/core-devs Please, assign this issue and decide on a deadline within 7 days or close it as duplicate of #4389 otherwise.
