### ISSUE TITLE
Add in-app documentation about Vaults.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5371]
I installed Parity 1.6.x today and noticed the Vaults button.  I clicked on it and couldn't easily figure out what they were.  Recommend adding some documentation to the Vaults page (perhaps even a short tutorial) explaining what the feature is.

**Comment by 5chdn** [comment]
will draft a wiki page which explains accounts, wallets and vaults and recommend something for in-app documentation which could be used in-app.

**Comment by 5chdn** [comment]
@MicahZoltu any feedback welcome. 

https://github.com/paritytech/parity/wiki/Accounts,-Wallets,-Vaults#vaults

**Comment by MicahZoltu** [comment]
I would recommend changing the wording around Vaults from `security` to `privacy`.  Vaults don't really add any additional _security_, but they do add some additional _privacy_.  I think the distinction is important for readers, especially those who don't really understand the cryptography.  By using the phrase "additional layer of _security_", the naive user will assume that adding a vault is necessary to keep their funds as secure as possible, but in reality they aren't really getting any additional security by adding a Vault wrapper.

**Comment by 5chdn** [comment]
Thanks for your feedback, updated.
