### ISSUE TITLE
Enable use by launchd on OSX

### ISSUE THREAD

**Issue by SilverPin** [paritytech/parity#5375]
I'd quite like to be able to run a node in the background on my computer and simply forget about it. Ideally I want the node to startup automatically when I open my computer and not clutter up my desktop with terminal windows. I figure it would maximise my node's uptime whilst being un-intrusive for me. 

One way to do this is to add it to launchd so the daemon launches on startup. I tried to do this by creating a .plist, which I added to `/library/launchdaemons`, however that did not work. I also tried to add it to `/library/launchagents`, but that did not work either. Diagnostics showed that I would get an error code, and I eventually tracked down the error output which was many iterations of:

> Invalid arguments.
> 
> Usage:
>   parity [options]
>   parity ui [options]
>   parity dapp <path> [options]
>   parity daemon <pid-file> [options]
>   parity account (new | list ) [options]
>   parity account import <path>... [options]
>   parity wallet import <path> --password FILE [options]
>   parity import [ <file> ] [options]
>   parity export (blocks | state) [ <file> ] [options]
>   parity signer new-token [options]
>   parity signer list [options]
>   parity signer sign [ <id> ] [ --password FILE ] [options]
>   parity signer reject <id> [options]
>   parity snapshot <file> [options]
>   parity restore [ <file> ] [options]
>   parity tools hash <file>
>   parity db kill [options]

I don't really know why this is the case, as the daemon will execute automatically when I run it, but not when it is executed by launchd. Interestingly I am able to add Geth to launchd, however I'd quite like to use Parity because a) The blockchain is smaller and b) I should theoretically still be able to access it from the localhost in my web browser, which I cannot do with Geth. 

I would appreciate it if this could be made possible. 

Thanks.

**Comment by SilverPin** [comment]
Sorry, user error. I wrote a bad .plist!

**Comment by SilverPin** [comment]
A good idea, @5chdn.

I had inadvertently included an invalid argument in the plist, which was causing the daemon to crash on startup. Here is a copy of the working plist for others to use in `/Library/Launchdaemons` or `/Library/LaunchAgents`.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>Parity</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/Cellar/parity/1.5.12/bin/parity</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/Users/ACarrithers/Documents/stderr</string>
	<key>StandardOutPath</key>
	<string>/tmp/Parity.out</string>
</dict>
</plist>
```

**Comment by arkpar** [comment]
Our macOS installer now includes an alternative way to auto start Parity at log on. This can be toggled with the icon menu in the menu bar.

**Comment by SilverPin** [comment]
@arkpar 

I wish I had known that before I spent hours teaching myself to write and troubleshoot a plist ;)
