### ISSUE TITLE
Parity is creating %USERPROFILE%/.ethash on startup.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5378]
For the most part, parity is doing the right thing on Windows and storing its files in `%APPDATA%` and `%LOCALAPPDATA%`.  However, every time I launch Parity (`parity.exe -ui`) it creates a folder at `%USERPROFILE%/.ethash`.  This folder has a single subfolder named `light` with a 32MB file inside it named with a hash of some kind.  Sometimes I find that there are multiple such files in this folder.

Parity should be writing these files to `%LOCALAPPDATA%/paritytech/parity` (or `ethcore`) on Windows.

**Comment by MicahZoltu** [comment]
The problem appears to be here: https://github.com/paritytech/parity/blob/master/ethash/src/compute.rs#L108-L114

I don't know how to resolve this properly in rust, but presumably using the same logic for file location as the rest of Parity.

**Comment by 5chdn** [comment]
Seeing same behavior on Linux `~/.ethash`, I always assumed this was by-design.

**Comment by arkpar** [comment]
The idea was that these files can be shared between different client implementation, e.g. geth. This turned out to be not much of an issue. Anyway we already have an issue for this here: https://github.com/paritytech/parity/issues/4565
