### ISSUE TITLE
QR scan should show if invalid address added

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5382]
Currently with the non-compliant native-signer, the error is just swallowed. The UI should report if errors are found in the actual QR decoding.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!
