### ISSUE TITLE
Signer bar sometimes pop up on top right

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5387]
Originally reported by @tomusdrw 

![riot 2 2017-04-03 13-54-43](https://cloud.githubusercontent.com/assets/1424473/24608097/3730ddf8-1875-11e7-84ab-e3611df045cb.png)

**Comment by tomusdrw** [comment]
Seems that the issue happens only on `#/home`.
Recent Dapps component is loading some dapps, which in turn fire `loaded` event in `dappsStore`, that event is received by `ParityBar` and last dapp setting is actually applied (for me it was Pairty Web3 Console).
