### ISSUE TITLE
Add support for --jsonrpc-apis all

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#5394]
It would be nice to be able to use:
`parity --jsonrpc-apis all`

with all being the entire list of available apis.

**Comment by tomusdrw** [comment]
Great idea!
I'll implement sth like this:
- `all` - All APIs exposed (warning should be printed)
- `readonly` - Read only APIs exposed (safe APIs)

and maybe additional syntax for:
- `all,-parity_accounts` - All APIS without `parity_accounts`

**Comment by chevdor** [comment]
@tomusdrw `readonly` and the `-api` features would definitely be a cool extra to `all`!

In the context of `--chain dev`, it would make it convenient, as you mentioned, to have things like `all,-parity_accounts` to start quicker.

`safeonly` may be a better name than `readonly` since you felt the need to explain that `read only` APIs are the safe ones.
