### ISSUE TITLE
Is there any way to run parity with less memory?

### ISSUE THREAD

**Issue by georgek146** [paritytech/parity#5407]
I am trying to run parity on a low memory vps, and I am getting fatal runtime error: out of memory. Is there any way that I could run parity with less memory? If not how much memory do I need to be able to reliably run it?

**Comment by 5chdn** [comment]
How much memory do you have available?

You can use `--cache 16` which reduces the internal caching in memory to a minimum of 16MB.

**Comment by tomusdrw** [comment]
Also try this:
`--pruning-history 16 --pruning-memory 16`, but note this will cause your node to be unable to handle more than 16 blocks long forks.

What version are you running?

**Comment by 5chdn** [comment]
Closing as answered.
