### ISSUE TITLE
Contract deployment doesn't watch contracts automatically.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5411]
Running `--chain dev`. Doesn't matter if I use "Deploy" or "Develop".
When the contract is deployed (the transaction is mined) it doesn't popup in the watched contracts list.

Not sure if the error is related:
![screenshot from 2017-04-06 09-38-36](https://cloud.githubusercontent.com/assets/581548/24743009/d71154b8-1aac-11e7-8349-2ae6ae287e1a.png)

**Comment by tomusdrw** [comment]
Related #5400

**Comment by chevdor** [comment]
This is not only `--chain dev`. I get the exact same issue + error with `--chain testnet`

**Comment by chanwit** [comment]
+1

I was using `truffle migrate` and it got hang by this bug.

**Comment by chevdor** [comment]
I compiled master from today and this issue is no longer there. I would close this issue.

**Comment by ngotchac** [comment]
Yes this should be fixed now. Please re-open if it happens again.

**Comment by saitam1** [comment]
Parity still doesn't show a successfully deployed contract automatically. At least not with this setup:

Parity client version: v1.10.8-stable-bd20c45-20180628/x86_64-linux-gnu/rustc1.27.0
Parity UI version: 0.1.4
Operating system: Linux
Installed via: .deb file
Fully synchronized: Yes
Network: Kovan

And if watching the contract manually, parity doesn't show any values on the variables which were assigned in the constructor.

**Comment by chevdor** [comment]
That sounds like a UI problem so you are better off reporting this issue in
the UI repo.
