### ISSUE TITLE
Creating new account doesn't properly refresh the list of accounts

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5412]
![screenshot from 2017-04-06 10-07-01](https://cloud.githubusercontent.com/assets/581548/24744037/e34a9bc8-1ab0-11e7-8842-7e48db5ddb19.png)

Note that newly imported account BLUE has verification icons, and `Green Boi` doesn't have them anymore.
![screenshot from 2017-04-06 10-07-20](https://cloud.githubusercontent.com/assets/581548/24744052/f5e7a76c-1ab0-11e7-8341-ec50ce44e524.png)

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

@paritytech/ui-devs Please, decide on a deadline within 7 days or close it otherwise.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
