### ISSUE TITLE
Rename `light::request::Requests` to `Batch`

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5413]
...and move it and the builder into a "batch" module.

"Batch" conveys the role of the structure w.r.t. partially handling responses much better.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/core-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by asymmetric** [comment]
Interested in taking this. Should [`RequestBuilder`](https://github.com/paritytech/parity/blob/f1a050366f62804a5122ff7c975690ee0f9a3192/ethcore/light/src/types/request/builder.rs#L30) become `BatchBuilder`?

Also, where should the newly created `batch` module live?

**Comment by rphmeier** [comment]
@asymmetric it could just be called `Builder` since it can be referenced with `batch::Builder`. The batch module should live where the "builder" module does now, so essentially just a file and type rename.

**Comment by asymmetric** [comment]
I'm working on this so I'd be happy to be assigned :)

**Comment by rphmeier** [comment]
thanks and noted, but unfortunately we can't assign issues to people outside the organization :(
