### ISSUE TITLE
ENODE Returned Has Odd + Symbol as Part of Port

### ISSUE THREAD

**Issue by BHSDuncan** [paritytech/parity#5420]
I was trying to follow that Demo PoA Tutorial, and I got to a point where I'm trying to call "parity_addReservedPeer" via RPC but the ENODE value I'm entering isn't working. 

The call to "parity_enode" actually returns a value that's slightly odd to me (take a look at the port section towards the end), and so when I pass it in, adding a reserved peer returns "invalid port value". here's the enode i get back and am using:
enode://5f183614bd9608499415c08ef0543b8306ec8594faf4c2bea8b020a5608275d38ccd79ae183dab99775cca8ac1551dc0f517bda1726e872624c749db920d8431@<some_ip_v4_address>:41529+63229

I get the same value from the initial parity startup.

I followed the tutorial entirely.  Obviously the issue crops up after I add in the signer accounts and then start up Parity.

If I remove the + sign and the number after it, the RPC call passes; however, the node isn't recognized and nothing seems to change, i.e. I still see 0/0/25.

Version: Parity/v1.6.5-beta-987390f-20170328/x86_64-macos/rustc1.16.0

Running: MacOS Yosemite 10.10.5 (would prefer not needing to update my MacOS version)

**Comment by arkpar** [comment]
`+`  appears when your UDP port is different from TCP port. Parity tries to map both ports to the external network to allow incoming connections over NAT. And I guess your router assigned different ports for TCP and UDP. If you are trying to connect the from internal network you should use internal IP and default port (30303). You can also disable NAT mapping with `--nat=none`

That said, the enode with a '+' should not be causing errors. And we should probably provide an API to return internal enode URL as well.

**Comment by BHSDuncan** [comment]
The "+" causing the error was my best guess, since it says "invalid port value", and removing the "+" sign allows the RPC call to go through (but the peer doesn't look to be actually registered since it's using what would appear to be an incorrectly mapped or somehow invalid port).

Regardless, starting Parity with the --nat=none flag gave me an ENODE value that worked with adding the node to the net. From there I was able to complete the PoA tutorial and make the other RPC calls necessary.  Thank you for your time and attention to this!

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

@paritytech/core-devs is `--nat none` a valid workaround or should the ports containing `+` issue be addressed? Please, assign a developer and decide on a deadline within 7 days or close it otherwise.
