### ISSUE TITLE
gui overlays my other tabs with sign button, is not closeable

### ISSUE THREAD

**Issue by greggdourgarian** [paritytech/parity#5421]
Hi
When I run Parity, it presents a button on the bottom right of my Windows screen for signing transactions.  This button appears even if I'm on another page.  It gets in the way and is uncloseable.

**Comment by tomusdrw** [comment]
On what page does it happen for you? I suspect you're talking about Parity Chrome Extension. Are you using any other ethereum-related extensions?

**Comment by 5chdn** [comment]
@greggdourgarian just tested. this is probably not parity but the parity-chrome-extension. you can disable it via `chrome://extensions`. but yes, it should be possible to move and hide it.

**Comment by 5chdn** [comment]
Closing in favor of https://github.com/paritytech/parity-extension/issues/72

**Comment by 5chdn** [comment]
On more note, if you access etherdelta via the parity dapp browser, the signer is movable. (just enter `etherdelta.github.io` on parity's home page in the address field and hit enter.

**Comment by tomusdrw** [comment]
@5chdn please note that the behaviour of Parity's home page address field differs if the extension is installed or no. The case you're referring to is when the extension is disabled/not installed.
Updated extension supporting moving of the bar will be released soon as well.

**Comment by greggdourgarian** [comment]
?tx!


________________________________
________________________________
