### ISSUE TITLE
Hardware wallet not recognized as multi-sig owner

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#5424]
If you create a multi-signature wallet with one hot key from parity, one cold key (i.e., paper wallet) and one key from nano ledger s, the signer does not allow me to sign the transaction with the hot key + ledger key.

All it says is that it requires an additional signature from another owner. But it does not realize that the ledger key is available for immediate signing :)

> PENDING CONFIRMATIONS
> No transactions needs confirmation right now.

**Comment by ngotchac** [comment]
@5chdn Could you confirm that this is still happening? I cannot reproduce the issue.

**Comment by 5chdn** [comment]
@ngotchac Actually this is not about hardware wallets, but if you have two of the required keys in your local accounts, parity signer does not request the 2nd signature.

**Comment by 5chdn** [comment]
Needs documentation. The pending requests are not at the signer tab but at the wallet details.
