### ISSUE TITLE
Have `Handler::on_connect` return a flag indicating whether the peer is kept

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5429]
Could be an enum or a simple bool.
If no `Handlers` keep the peer, `LightProtocol` should disconnect them.

Ensure that at least one of the full node handlers says to keep peers.

@adrianbrink Maybe one you'd be interested in?

**Comment by adrianbrink** [comment]
@rphmeier I'll take this one too :-)

**Comment by rphmeier** [comment]
Thanks!

**Comment by Vurich** [comment]
This can be closed now
