### ISSUE TITLE
Start CI for pull requests, not branch heads

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5430]
cc @paritytech/ci 

Otherwise nobody outside the org can contribute effectively!

**Comment by adrianbrink** [comment]
I agree :-)

**Comment by adrianbrink** [comment]
Maybe it could a system, where a member has to comment ```[ci/check]``` and only then does it build the PR and all subsequent pushes to it.

**Comment by 5chdn** [comment]
This issue is labelled with _sometimesoon_: Issue is worth doing soon. But it's inactive for more than a month and neither assigned nor linked to a milestone.

@paritytech/ci Please make sure this is correctly prioritized, assigned, and decide on a proper deadline.

**Comment by debris** [comment]
It's done
