### ISSUE TITLE
docker versions do not match tags

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#5435]
related to #5354, docker hub images versions do not match:

    docker pull ethcore/parity:stable  # 1.6.3 - should be 1.5.12
    docker pull ethcore/parity:v1.5.12 # 1.7.0 - should be 1.5.12
    docker pull ethcore/parity:beta    # 1.7.0 - should be 1.6.5-beta
    docker pull ethcore/parity:v1.6.5  # 1.6.5 - correct \o/
    docker pull ethcore/parity:latest  # 1.6.3 - should be 1.7.0-unstable

**Comment by 5chdn** [comment]
Also, what's the difference between stable and stable-release?

    $ curl -sS 'https://registry.hub.docker.com/v2/repositories/ethcore/parity/tags/'  | jq '."results"[]["name"]' |sort
    "beta"
    "latest"
    "master"
    "nightly"
    "stable"
    "stable-release"
    "v1.5.12"
    "v1.6.4"
    "v1.6.5"
    "v1.6.6"

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The CI behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ci Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by 5chdn** [comment]
Actually, this is more than just _annoyance_.

**Comment by General-Beck** [comment]
@5chdn we move to https://hub.docker.com/r/parity/parity/ with reorganisation

**Comment by debris** [comment]
imo, the problem is caused by [this line](https://github.com/paritytech/parity/blob/2f757babb9d29607682fcb5a8c1f6af18033281c/docker/ubuntu/Dockerfile#L32)

- Dockerfile:

```dockerfile
RUN git clone https://github.com/paritytech/parity
```

Cloning repo always takes the latests version of given repo, whereas we should use [local copy](https://github.com/paritytech/parity-bitcoin/blob/228c97ad85a4dd1de530804a18d293f315a97df3/docker/ubuntu/Dockerfile#L3) of the repo 

- Dockerfile

```dockerfile
ADD . /build/parity
```

- build command:

```
docker build -t parity-ubuntu -f docker/ubuntu/Dockerfile .
```

**Comment by General-Beck** [comment]
@debris for hub we use https://github.com/paritytech/parity/tree/master/docker/hub and https://github.com/paritytech/parity/blob/master/.gitlab-ci.yml#L515

**Comment by 5chdn** [comment]
Should I update the docs to reflect the switch to parity/parity? Or is this still work-in-progress?

    $ sudo docker run parity/parity:v1.6.8
    2017-06-14 11:49:44 UTC Starting Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.18.0
    ^C
    $ sudo docker run parity/parity:v1.5.13
    2017-06-14 11:50:30 UTC Starting Parity/v1.5.13-stable-69efb27-20170612/x86_64-linux-gnu/rustc1.16.0
    ^C

They seem to work very well. Would be nice to have tag synonyms for stable, beta and latest.

**Comment by 5chdn** [comment]
Needs docs, too.

**Comment by 5chdn** [comment]
Can we please remove ethcore/parity as soon as this is finished? What else is needed? @paritytech/ci

**Comment by General-Beck** [comment]
@5chdn https://hub.docker.com/r/parity/parity/tags/ or
`curl -sS 'https://registry.hub.docker.com/v2/repositories/parity/parity/tags/'  | jq '."results"[]["name"]' |sort`

**Comment by 5chdn** [comment]
I'm asking because people still pull ethcore/parity - see #5885 

If this is done, please remove the ethcore repository. I already updated the docs.

**Comment by General-Beck** [comment]
@5chdn done

**Comment by 5chdn** [comment]
Thanks!
