### ISSUE TITLE
Transaction reception Issue 

### ISSUE THREAD

**Issue by FortHart** [paritytech/parity#5436]
Parity Wallet : 0x00B8658026c34c50E30E214e3a51BE75557fAFD4

Txid: 0xfa64ba00afab0508d71f96602991e94690208851ac9290edda28f4575be9a23b

The problem is that the Block says the transaction was complete and the funds are inside the Parity wallet. The reality is that the balance of the wallet is 0, And nothing appears on the transaction historty 

its been 5 days since both the wallet creation and the trasaction were made

**Comment by 5chdn** [comment]
Hi. Which Parity version are you using? Which operating system? Are you fully synchronized?

**Comment by FortHart** [comment]
Hello there , Im using the last release on this website "https://parity.io/index.html" i dont know how to check which version i got  , Windows 10 not sure if im fully Synchronized i just downloaded the client and did a normal installation , if you want pictures or any other information just ask it . I appreciate the help

**Comment by 5chdn** [comment]
Could you open the Wallet (`parity ui`) by navigating your browser to http://127.0.0.1:8180/ ? This will show version, synchronization status, and connected peers in footer.

**Comment by FortHart** [comment]
Parity//v1.6.5-beta-987390f-20170328/x86_64-windows-msvc/rustc1.16.0
Unknown capability

2,401,062/3,515,526  syncing  HOMESTEAD  0/1/25 peers

**Comment by 5chdn** [comment]
You are not fully synchronized. Your balance will show up as soon as this process is finished. You might want to switch to warp sync. 

https://github.com/paritytech/parity/wiki/FAQ#why-is-warp-synchronization-so-fast
