### ISSUE TITLE
What does the IPFS API in Parity do?

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#5438]
From Gitter:

> Matt.Tan @mtbitcoin 06:46
> what does the "--ipfs-api" in parity do? Are there are any corresponding documentation for this?

Needs docs.

**Comment by rphmeier** [comment]
Pretty good description here: https://github.com/paritytech/parity/issues/4172

**Comment by 5chdn** [comment]
thanks.

**Comment by 5chdn** [comment]
Work in progress https://github.com/paritytech/parity/wiki/IPFS

**Comment by rustyx** [comment]
https://wiki.parity.io/IPFS
