### ISSUE TITLE
Event Log links to Etherscan don't work

### ISSUE THREAD

**Issue by belgacoin** [paritytech/parity#5441]
In Parity//v1.5.11-stable-f067f12-20170314/x86_64-macos/rustc1.15.1
when clicking "Registry" you'll get a new window with the Event Log.
when clicking on a Ether address, the link to etherscan.io has a double https:// in front so it doesn't work properly.

**Comment by 5chdn** [comment]
duplicate of #4941 #5377 and should be fixed in #4984 with 52c81fe4eeed111d5f6e1ce6debcafa2960f6e0d on master

@ngotchac this needs backporting, does it?

**Comment by ngotchac** [comment]
@5chdn Yes it does indeed !
