### ISSUE TITLE
Parity crash at startup.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5442]
Windows 10

I turned on my computer this morning (Parity set to auto-start) and I received this error while all of my various startup apps were being loaded.

Parity version: `Parity//v1.6.5-beta-987390f-20170328/x86_64-windows-msvc/rustc1.16.0 Capable`

```
---------------------------
parity.exe - Application Error
---------------------------
The instruction at 0x00007FF61A321CD0 referenced memory at 0x0000020D0FD62000. The memory could not be read.


Click on OK to terminate the program
---------------------------
OK   
---------------------------
```

**Comment by 5chdn** [comment]
This issue is labelled with _panic_: The client panics and exits without proper error handling. It's inactive for one month and neither assigned nor linked to a milestone.

@paritytech/core-devs Please, assign a developer to this issue and decided on a deadline within 7 days.

**Comment by 5chdn** [comment]
@MicahZoltu is this reproducible? If yes, could you try to run it from command prompt and post the logs / trace here?

**Comment by arkpar** [comment]
This should be fixed in 1.6.8. Would be good to confirm.

**Comment by MicahZoltu** [comment]
Not reproducible, it happens randomly on startup.  :/

**Comment by 5chdn** [comment]
Please, just report back if this still happen with 1.6.8+ - thanks! :)
