### ISSUE TITLE
Cant Sync please help

### ISSUE THREAD

**Issue by FortHart** [paritytech/parity#5444]
Im trying to get my parity wallet to work , someone told me that i may be out of sync so i checked it out and this was the outgoing message

"
>
web3.eth.syncing
<
Object { currentBlock: 2401062 , highestBlock: 3519090 , startingBlock: 2401062 , warpChunksAmount: null , warpChunksProcessed: null }
"

Paritiy info: 
Parity//v1.6.5-beta-987390f-20170328/x86_64-windows-msvc/rustc1.16.0
Unknown capability

2,401,062/3,519,107 syncing HOMESTEAD 3/5/25 peers

**Comment by 5chdn** [comment]
Looks good, you are syncing fine. You might be wondering why it is so slow? Read this: https://ethereum.stackexchange.com/questions/9883/why-is-my-node-synchronization-stuck-extremely-slow-at-block-2-306-843

To circumvent this, you can use warp sync by resetting your database with `parity db kill` and starting parity again.
