### ISSUE TITLE
Parity UI doesn't connect to local node that was previously set to --mode offline

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5446]
Steps to reproduce:

1) In UI: change 'mode of operation' to 'Parity doesn't sync'
2) Restart node (no mode config, --> default: last)
3) UI persistently shows `Connecting to the Parity Node. If this informational message persists, please ensure that your Parity node is running and reachable on the network.`

OR

1) start node with `--mode offline`
2) UI persistently shows `Connecting to the Parity Node. If this informational message persists, please ensure that your Parity node is running and reachable on the network.`

**Comment by tomusdrw** [comment]
`enode` not available?

**Comment by ngotchac** [comment]
@bjornwgnr Is this still happening ? I cannot reproduce the issue.

**Comment by bjornwgnr** [comment]
@ngotchac It is not happening on my `Parity//v1.7.0-nightly-8fdda2f-20170503/x86_64-windows-msvc/rustc1.17.0` anymore.

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior; and is inactive for one month. It's neither assigned nor linked to a milestone.

Closing as _stale_ as it can not be reproduced anymore.
