### ISSUE TITLE
Update wiki subsection Back-up & Restore (for 1.7 release)

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5450]
[Back-up & Restore wiki subsection](https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring) needs to be updated to account for [In-Wallet acc export functionality](https://github.com/paritytech/parity/pull/4973).

Probably on hold until 1.7 is released.

**Comment by 5chdn** [comment]
> Sadly, since GitHub Wiki's aren't actually Wikis (no outside contributions allowed) I can't make this edit myself.
>
> https://github.com/paritytech/parity/wiki/Backing-up-%26-Restoring shows the Windows path as %HOMEPATH%/AppData/Roaming/Parity/Ethereum/keys. This path isn't actually correct as the roaming profile folder may be moved to a different location depending on OS settings. The correct path is %APPDATA%/Parity/Ethereum/keys/ethereum. I'm less confident about the trailing ethereum, but that is where I had to go to find my keys as Parity/Ethereum/keys is juts a folder with a single subfolder ethereum in it.

> Also on that same page there are no restore instructions for Windows, perhaps this is because it is assumed the user is using Explorer to backup, so it is a bit undefined exactly how they would restore?
>
> There may be value in splitting this page up into high-level sections for each OS. Right now it jumps around between Windows, Mac and Linux and some of the instructions are for Linux/Mac and don't apply for Windows but also don't specify that they are Linux/Mac specific.

**Comment by 5chdn** [comment]
Björn, I created a branch on the wiki called `nightly-1.7` which we can use to update the docs for upcoming release.

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring
