### ISSUE TITLE
CLA website is not working correctly

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5457]
http://take.ms/XeX9x
Some issues with SSL and callback URL.

Related #5455

**Comment by rphmeier** [comment]
cc @jesuscript

**Comment by jesuscript** [comment]
my bad, will fix it up today

**Comment by 5chdn** [comment]
This issue is labelled with _bug_ but neither assigned nor linked to a milestone.

@paritytech/ci @jesuscript Please, assign this and decide on a deadline within 7 days.

**Comment by ddorgan** [comment]
Will setup a new cla-bot for this...

**Comment by 5chdn** [comment]
Cool, @ddorgan could you enable it for parity-bitcoin, too? 

https://github.com/paritytech/parity-bitcoin/pull/416#issuecomment-299699301

**Comment by ddorgan** [comment]
Resolved for both cla.parity.io and cla-bitcoin.parity.io
