### ISSUE TITLE
Parity does not allow sending ETH while creating a contract.

### ISSUE THREAD

**Issue by clesaege** [paritytech/parity#5459]
Some contracts need to receive ETH when they are created (you can perfectly make the constructor payable), however parity does not show a field to specify the amount of ETH sent at the creation of the contract and does not send any ETH.

A way to fix this would be to add a field to specify the amount of ETH to be sent at contract creation.

**Comment by ngotchac** [comment]
This has been done in #4919
Note that you need to add the `payable` modifier to the constructor function.
