### ISSUE TITLE
Parity wallet running in ropsten should use ropsten.etherscan.io

### ISSUE THREAD

**Issue by reiven** [paritytech/parity#5464]
Hi!

I'm using Parity and Parity Walletwith Ropsten, but in the wallet i cannot see the related transactions in etherscan because looks like is searching in testnet.etherscan instead of ropsten.etherscan. 
It will be posible to detect the network and use the appropiate 'blockexplorer'?

Thanks

**Comment by 5chdn** [comment]
> It will be posible to detect the network and use the appropiate 'blockexplorer'?

That's exactly what Parity is doing, however, last week etherscan decided to move Ropsten from `testnet.` to `ropsten.` sub-domain. Thanks for reporting.

**Comment by ngotchac** [comment]
This should have been fixed in #5455
