### ISSUE TITLE
What is a step and what happens when the next primary doesn't broadcast?

### ISSUE THREAD

**Issue by qnimate** [paritytech/parity#5465]
I don't actually understand what a step is and what's it's use? Does a node always keep updating the step? And when time to create to create and broadcast a block comes it will take the current step value and check if he should broadcast or not. 

What do you mean by "Blocks from more than 1 step into the future are rejected."? Does this mean that if block time is 5 seconds then the next block timestamp should be exactly 5 seconds higher.

And also what happens when the next primary doesn't broadcast? How does the network deal with it? All the next blocks should get invalidated right because they won't follow a timestamp difference of 5 seconds.

**Comment by keorn** [comment]
To be clear this question refers to Aura, let me know if the [wiki page](https://github.com/paritytech/parity/wiki/Aura) does not answer your questions.

**Comment by qnimate** [comment]
@keorn I had already read the wiki page. The wiki page is very high level. Can you answer the specific questions I mentioned above?

**Comment by rphmeier** [comment]
@qnimate One block may be issued per step, and only one authority is allowed to issue a block for any given step. 

Each step corresponds to an `N`-second interval in "real-world" time.
Longer step times give more leeway for authorities' clocks to be out of sync, but also lead to a longer block time. Accepting blocks from 1 step in the future also helps deal with clocks being out of sync.

**Comment by qnimate** [comment]
@rphmeier What happens when the next primary doesn't create and broadcast block?

**Comment by rphmeier** [comment]
Nothing happens. When the next step after that starts, the next primary has the opportunity to build on the existing chain. The only negative effect is a longer block time during the steps where no blocks are produced.

**Comment by qnimate** [comment]
@rphmeier Thanks.

**Comment by qnimate** [comment]
@rphmeier How do nodes calculate and find the next validator. I am assuming this formula

```
setInterval(
   function(){console.log((new Date().getTime() % 5) % 45);
}, 5000);
```

Here 45 is the length of validators list and 5 is the step_duration.

Here the output is sometimes 1 and 4. I don't get any other number. Am I doing something wrong?

**Comment by keorn** [comment]
its `t / 5 % 45`

**Comment by rphmeier** [comment]
@qnimate you might want to head over to our gitter channel at https://gitter.im/paritytech/parity
or https://gitter.im/paritytech/parity-poa for more questions.

Github issues aren't really suitable for back-and-forth discussion; we prefer to use them to track bugs and enhancements.
