### ISSUE TITLE
Accounts selector in the Dapp should display all accounts.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5468]
Currently the accounts are limited only to the ones that are exposed.

In the snippet it should be possible to:
1. Select a default account
2. Expose accounts for a dapp

but you should be able to choose from all accounts available, currently it seems that only a subset is available.

Not sure if it's only for the Extension bar or for iframed dapps as well (i.e. without extension)

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by ngotchac** [comment]
Should it display all accounts like so?
![image](https://cloud.githubusercontent.com/assets/2864519/25898767/b994bf50-358d-11e7-805d-6445d86526dd.png)

**Comment by tomusdrw** [comment]
I think it should be sometihng like this, but:
1. The dialog should close after single click.
2. Single click should select default account
3. Making account visible should be done by a smaller checkbox (like default on a screenshot)

Cause here the use case is "Select an account", not "Select visible accounts"

**Comment by ngotchac** [comment]
Ok, I agree.
