### ISSUE TITLE
IPC endpoint gets into invalid state when accessed concurrently

### ISSUE THREAD

**Issue by dstarcev** [paritytech/parity#5470]
IPC endpoint seems to get broken when there are more than two connections to it.
I have written a small script that helps to reproduce the bug by sending requests from 5 concurrent connections and printing how many of them succeed.
https://github.com/dstarcev/parity-ipc-killer

**Comment by NikVolf** [comment]
The fix will require synchronizing api of two libs (tokio-uds/tokio-named-pipes) and will take some (hopefully short) time

**Comment by 5chdn** [comment]
This issue is labelled with _bug_: The client fails to follow expected behavior. It's assigned to @NikVolf but not linked to a milestone.

I'm closing this as fixed as a patch is available in #5489 and attaching it to milestone 1.7.
