### ISSUE TITLE
Chrome background image doesn't fill without gaps

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#5472]
![parity 2017-04-19 12-00-04](https://cloud.githubusercontent.com/assets/1424473/25174921/3182eda2-24f9-11e7-87f7-359d1ac33d36.png)
![parity 2017-04-19 12-03-36](https://cloud.githubusercontent.com/assets/1424473/25174922/319f2774-24f9-11e7-83ef-6bc79f62edb6.png)

**Comment by jacogr** [comment]
Also with dialogs.

![parity 2017-03-22 13-48-27](https://cloud.githubusercontent.com/assets/1424473/25240612/92b18d90-25f3-11e7-913f-d4ae75d4db62.png)

**Comment by ngotchac** [comment]
@jacogr Did #5475 fixed it ?

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Did #5475 fix this? Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by ngotchac** [comment]
I talked with @jacogr and #5475 did not fix this. If anyone can reproduce it would help.
