### ISSUE TITLE
PIP: Get transaction (and receipt) by txhash 

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5482]
Transaction responses are easily verifiable, but receipts less so. We will need to require a merkle proof of the receipt and corresponding transaction in the header's receipt and transaction tries, respectively

Without these RPCs, a lot of UI functionality doesn't work.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/core-devs Please decide on a deadline and add an assignee within 7 days, thanks!
