### ISSUE TITLE
Word Search in Develop Console

### ISSUE THREAD

**Issue by PhABC** [paritytech/parity#5483]
Hello all,

I find it rather inconvenient that one can't use 'ctrl+f' in order to search through solidity code. In addition, it would be cool if identical selected words could be highlighted in the current contract, as many IDE do.

If there is already a way to search, please excuse me, I couldn't find it.

**Comment by ngotchac** [comment]
Nope you're right, search haven't been implemented yet...

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
