### ISSUE TITLE
Account names lost / incorrect for all accounts BANDIT_EVENT_INTEREST_BUTTON_COPY

### ISSUE THREAD

**Issue by tjayrush** [paritytech/parity#5485]
The attached image shows the problem very clearly. The names of all accounts is very obviously wrong. I'm running 'parity --tracing on --pruning archive' from the command line on a Mac with macOS Seirra, 10.12.4. Safari browser.

<img width="1467" alt="screen shot 2017-04-21 at 7 03 55 am" src="https://cloud.githubusercontent.com/assets/5417918/25275077/65d9de62-2661-11e7-9ab8-6fbeb0c56a37.png">

**Comment by ngotchac** [comment]
What happens if you try to modify the names ?

**Comment by tjayrush** [comment]
I didn't want to do that because it seemed kind a messed up, so I simply rebooted my machine, and I haven't seen the problem since.

**Comment by ngotchac** [comment]
Okay, looks strange but totally unrelated to Parity. If it ever occurs again please re-open :)

**Comment by 5chdn** [comment]
Was reproduced, now tracking in #5660
