### ISSUE TITLE
Export state null characters

### ISSUE THREAD

**Issue by realcodywburns** [paritytech/parity#5487]
OS: Windows 10
Ver: 1.6.6
Config: 
`warp = false
[footprint]
fat_db = "on"
db_compaction = "hdd"
cache_size_db = 640
cache_size_blocks = 80
cache_size_queue = 500
cache_size_state = 250`

Command: parity.exe export state >> h:/04212017.json

Expected outcome: json file with all accounts

Actual outcome: json file with all accounts, but after each character a null character is inserted creating a file twice as large as necessary (3.5gb classic chain) and unreadable by json importers.

Header and first account:

`FF FE 7B 00 20 00 22 00 73 00 74 00 61 00 74 00 65 00 22 00 3A 00 20 00 5B 00 0D 00 0A 00 22 00 30 
 00 78 00 38 00 32 00 61 00 33 00 33 00 63 00 66 00 32 00 33 00 39 00 61 00 35 00 65 00 64 00 65 00 61 
 00 31 00 35 00 64 00 30 00 30 00 35 00 37 00 39 00 61 00 66 00 36 00 39 00 34 00 33 00 31 00 36 00 65 
 00 39 00 66 00 31 00 61 00 37 00 31 00 31 00 22 00 3A 00 20 00 7B 00 22 00 62 00 61 00 6C 00 61 00 6E 
 00 63 00 65 00 22 00 3A 00 20 00 22 00 30 00 78 00 22 00 2C 00 20 00 22 00 6E 00 6F 00 6E 00 63 00 65 
 00 22 00 3A 00 20 00 22 00 30 00 78 00 22 00 7D`

` ÿþ{. .".s.t.a.t.e.".:. .[.....".0.x.8.2.a.3.3.c.f.2.3.9.a.5.e.d.e.a.1.5.d.0.0.5.7.9.a.f.6.9.4.3.1.6.e.9.f.1.a.7.1.1.".:. .{.".b.a.l.a.n.c.e.".:. .".0.x.".,. .".n.o.n.c.e.".:. .".0.x.".}"`

After find and replace `00`:

`FF FE 7B 20 22 73 74 61 74 65 22 3A 20 5B 0D 0A 22 30 78 38 32 61 33 33 63 66 32 33 39 61 35 65 64 65 61 31 35 64 30 30 35 37 39 61 66 36 39 34 33 31 36 65 39 66 31 61 37 31 31 22 3A 20 7B 22 62 61 6C 61 6E 63 65 22 3A 20 22 30 78 22 2C 20 22 6E 6F 6E 63 65 22 3A 20 22 30 78 22 7D`

`ÿþ{ "state": [.."0x82a33cf239a5edea15d00579af694316e9f1a711": {"balance": "0x", "nonce": "0x"}`

**Comment by arkpar** [comment]
What shell are using on windows? Is it configured to produce UTF-16 output? If you are using standard cmd.exe try configuring it for UTF-8 with `CHCP 65001`

**Comment by realcodywburns** [comment]
Using powershell

**Comment by arkpar** [comment]
Or just pass a filename to parity instead of piping it through the shell
`parity.exe export state h:/04212017.json`

**Comment by realcodywburns** [comment]
Removing the pipe resolves the issue.
