### ISSUE TITLE
UI: Value input fields: add support for 1eX

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#5491]
Improvement.

Since the default values are in wei, entering small realistic values (from the equivalent of 1cent to 1 euro/dollar) requires quite some zeroes.

Supporting exponential notation would help as:
- 1 finney = 1000000000000000 wei = 1e15 wei

Sure there is the ETH switch but this is not the default and still require a bunch of zeroes.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
