### ISSUE TITLE
Missing link to install Chrome extension. 

### ISSUE THREAD

**Issue by AlexanderSupersloth** [paritytech/parity#5493]
I did not install the Chrome extension when I first installed Parity. Now I cannot find it in the Chrome store. I have tried searching for "Parity" and "Ethereum", but it is not there. I followed an old link I found on Github, but it went to a 404. 

I have uninstalled and reinstalled Parity in an attempt to get it to query whether I want to install the extension, but there must be a file somewhere on my laptop that I cannot find because it seems to install with some of my pre-existing preferences, so does not ask me if I want to install the extension.

**Comment by tomusdrw** [comment]
The extension can be found here: https://chrome.google.com/webstore/detail/parity-ethereum-integrati/himekenlppkgeaoeddcliojfddemadig

The UI will prompt you to install it in the future if you won't do it, but there should also be a link available in the Settings tab. @jacogr do we have it there?

**Comment by SilverPin** [comment]
Thank you for that link. It is curious that a search for neither "Parity" nor "Ethereum" turns up that result. So much for Google having the best search engine!

I am certain there is no link in the settings tab.

**Comment by tomusdrw** [comment]
Yeah, the extension is not public, cause it doesn't make much sense without a node.

**Comment by 5chdn** [comment]
We should add such a link to settings maybe. And an option to turn off/dismiss the notification if you have it installed but deactivated.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by MicahZoltu** [comment]
@tomusdrw Neither of your comments above appear to be true with 1.7.0.  The UI no longer prompts to install when I open it and the Settings page does not have a link to install it.

**Comment by AlexanderSupersloth** [comment]
@MicahZoltu I regularly get prompted to install the extension on 1.7.0, even though I already have it installed. It is very irritating.

**Comment by tomusdrw** [comment]
@AlexanderSupersloth The issue is already addressed on the development branch of the Extension and will be released shortly.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
