### ISSUE TITLE
Check the validity of passphrase before recovering

### ISSUE THREAD

**Issue by hrishikeshio** [paritytech/parity#5494]
Currently if you generate a new account by clicking "Recover using passphrase" and do not fill any details, it generates this address

https://etherscan.io/address/0x00a329c0648769A73afAc7F9381E08FB43dBEA72

As you can see someone possibly generated this address using above method and used it to store real ether. This mistake can happen from anyone. Please check validity of passphrase before recovering account.

**Comment by gavofyork** [comment]
this is not a "passphrase" and nowhere is stated as such. it clearly states "IMPORT ACCOUNT", and is labelled "recover from passphrase". there are good reasons for recovering from phrases of fewer than 12 words, such as conveniently sharing low-security accounts on a test net or dev chain.

when using a piece of software that is potentially handling real value such as parity, it is generally sensible to pay close attention to the indications on screen and not to make assumptions about what may or may not happen when you "do not fill any details" of any given form.

**Comment by gavofyork** [comment]
replaced with https://github.com/paritytech/parity/issues/5495
