### ISSUE TITLE
Mist gets plenty of peers, parity only gets 0-3

### ISSUE THREAD

**Issue by bizwarp** [paritytech/parity#5497]
This is for Linux. I installed Mist and synched the blockchain quickly due to lots of peers. Parity is only getting 0 to 3.  303030 is open.  Not sure why Parity is behaving differently than Mist/geth.  Any ideas?  Thanks very much.

**Comment by 5chdn** [comment]
Please share your parity node log to start looking into this. You can also run the node with `-lsync=trace,network=trace` and paste the output somewhere.

**Comment by arkpar** [comment]
@bizwarp how exactly do you measure peer count?

**Comment by bizwarp** [comment]
@arkpar It shows up on the parity feed in the terminal.  I am running for 2 hours and I finally got to 3/ 3/25.
I will post a log shortly.  I have to do my crappy day job for a little while :)

**Comment by bizwarp** [comment]
Getting 5/5/25 now.  I guess it takes a while to acquire peers.  I am closing this.  Thanks for your help.
