### ISSUE TITLE
SecretStore: dynamically generate KeyPairs

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity#5502]
During encryption/decryption session, every KS[i] -> KS[j] message is encrypted with SHARED_KEY=GENERATE(KS[i].KeyPair.Public, KS[j].KeyPair.Public).
KeyPair.Private of KS[i] is currently stored in plain text in configuration file on KS[i].

As @keorn suggested, it would be good not to store this in plain text => suggestion is to generate these values when encryption session is initializing, so we do not need to store it in configuration files.

**Comment by svyatonik** [comment]
The same key is used to confirm that we are contacting with exactly same server we want to contact => by dynamically generating this key, there will be no way to make sure this happens.
There must be another way not to store this in plain text.

**Comment by keorn** [comment]
You can store the current list in a contract. Similar to `ValidatorSet` or enodes that @arkpar is working on.

**Comment by svyatonik** [comment]
Discussed this in private.
1) this issue is about storing private keys in configuration files. This must be resolved as:
1.1) every KeyServer must have corresponding account from ethstore (insert new account if not provided)
1.2) on startup, password for this account must be provided
1.3) use this account as KS KeyPair
2) next issue is about maintaining list of KeyServers. It is what @keorn comment is about. I'll add a separate issue with explanation.
