### ISSUE TITLE
Account verification state

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#5516]
Flow:
1. Open Parity
2. Click verify
3. initiate a contract(request)
4. Close the Verification window
5. Open Signer tab
6. Confirm the request(Pay 0.007eth)
Receive SMS, but have no way to enter it if the Verification window was previously closed.

**Comment by 5chdn** [comment]
Doesn't the signer pop after step 3? You should not be required to do steps 4 and 5.

**Comment by rstormsf** [comment]
You are right that I'm not required to do step 4 and 5, but it happens that I closed my browser tab with partiy and opened it again and made a payment in signer tab.

**Comment by 5chdn** [comment]
Closing as _intended_. The verification window explicitly tells you not to close it :-)

**Comment by rstormsf** [comment]
@5chdn I'd expect that since it's contract, you can access the contract and call a method with parameters of my SMS message.
