### ISSUE TITLE
Sms verified accounts are not displayed in KOVAN

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#5517]
I just sms-verified my account in FOUNDATION chain.
When I switched to Kovan, I don't see that account.

**Comment by 5chdn** [comment]
And what if you import that account from your foundation keys?

**Comment by rstormsf** [comment]
@5chdn sure I can import the account and have some Kovan ether in that. But it shouldn't be that way, right? Please correct me if my expectations are wrong.

**Comment by 5chdn** [comment]
Yes, that's a valid concern.

**Comment by 5chdn** [comment]
This issue is labelled with _annoyance_: The client behaves within expectations, however this "expected behaviour" itself is at issue. It's neither assigned nor linked to any milestone.

@paritytech/ui-devs Please decide on a deadline and add an assignee within 7 days, thanks!

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
