### ISSUE TITLE
When trying to make an IPC connection on 1.7

### ISSUE THREAD

**Issue by chrisfranko** [paritytech/parity#5530]
`thread '<unnamed>' panicked at 'assertion failed: self.remaining_mut() >= src.len()', /home/notroot/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-0.4.1/src/bytes.rs:1122
stack backtrace:
   1:     0x55fded3cf66c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55fded3d71de - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55fded3d6de4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55fded3d767b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55fdecb8463f - std::panicking::begin_panic::h5b9f7cee516d51a9
   6:     0x55fdecb84e81 - <jsonrpc_ipc_server::stream_codec::StreamCodec as tokio_io::framed_write::Encoder>::encode::h68358534ca1b2bc5
   7:     0x55fdec863b00 - <futures::stream::split::SplitSink<S> as futures::sink::Sink>::start_send::hf232fb344d531172
   8:     0x55fdec8a6ad6 - <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::h6d954502dc5ff92f
   9:     0x55fded0d32a1 - tokio_core::reactor::Core::poll::h6873bb3ac0cf66e8
  10:     0x55fdeccabd16 - std::panicking::try::do_call::hec23705e9b80a4f4
  11:     0x55fded3de29b - <unknown>
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_abort/lib.rs:40
Aborted (core dumped)
`

**Comment by NikVolf** [comment]
hi can you please run node with extra argument `-lipc=trace` and post the result?

**Comment by chrisfranko** [comment]
yes ill be able to do it later, flying on planes today

**Comment by NikVolf** [comment]
No worries, got log from another issue
Must be related to 
https://github.com/paritytech/jsonrpc/issues/132
