### ISSUE TITLE
Parity v1.6.6-beta running on Kovan doesn't update to nightly

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5535]
Running `Parity//v1.6.6-beta-8c6e3f3-20170411/x86_64-windows-msvc/rustc1.16.0`

> 2017-05-02 17:46:53 Attempting to get parity binary 593e…d499
> 2017-05-02 17:46:53 Unable to fetch update (1.7.0-nightly-81c4…62d0): InvalidStatus

**Comment by bjornwgnr** [comment]
It worked for me this morning.

**Comment by 5chdn** [comment]
Closing as fixed.
