### ISSUE TITLE
No identities have been found on the page.

### ISSUE THREAD

**Issue by YangNation** [paritytech/parity#5537]
Hi, 

Parity throws the message

"Connecting to the Parity Node. If this informational message persists, please ensure that your Parity node is running and reachable on the network."

Parity Ethereum Integration throws this error message:

"No identities have been found on the page."

I have tried re-installing Parity and restarting my computer. Neither fixed the issue.

Please help.

Yang

**Comment by YangNation** [comment]
![capture](https://cloud.githubusercontent.com/assets/15274205/25646835/c8fd50be-2fee-11e7-9c62-ab03fa35dfff.PNG)

**Comment by YangNation** [comment]
Parity's keystores reside here
1 - %HOMEPATH%/AppData/Roaming/Parity/Ethereum/keys/ethereum

Parity's chain data resides here:
%HOMEPATH%/AppData/Local/Parity/Ethereum


Delete the chain data and reboot Parity to solve this problem.

**Comment by 5chdn** [comment]
No need to remove the database, just (re)start parity.
