### ISSUE TITLE
How to run a private chain with Docker?

### ISSUE THREAD

**Issue by myqq0000** [paritytech/parity#5550]
Hi! I'm new to Parity. I try to run a private chain with Docker these days. I follow 
[https://github.com/paritytech/parity/wiki/Docker](url) to write a configuration file and mount it with `docker -v`. But it returns ```Could not load specification file.```
I thinked it because the configuration file doesn't mount at first. But then I tried default configuration file, it run successfully. So I think it because I write a "demo-spec.json" to set a private chain in my configuration file. I put this json file in the directory which I mount. But it doesn't work, too. I try to use [Parity Config Generator](https://paritytech.github.io/parity-config-generator/), but it seems not support upload my own chain... 
So what should I do to run a private chain? Thanks a lot.
This is my config.toml:

```
[parity]
chain = "demo-spec.json"
[ui]
port = 8180
interface = "0.0.0.0"
[network]
port = 30300
[rpc]
port = 8545
interface = "0.0.0.0"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
hosts = ["all"]
[dapps]
port = 8080
interface = "0.0.0.0"
hosts = ["all"]
```

**Comment by 5chdn** [comment]
You have to pass the demo-spec.json also to your docker container, something like this:

    $ mkdir -p ~/.local/share/io.parity.ethereum/docker/
    $ touch ~/.local/share/io.parity.ethereum/docker/config.toml
    $ touch ~/.local/share/io.parity.ethereum/docker/demo-spec.json

Edit config and spec as you wish, and add the full path to the config:

    [parity]
    chain = "/mnt/demo-spec.json"

Note this is the path inside the docker container, after running this:

    $ docker run -ti -v ~/.local/share/io.parity.ethereum/docker/:/mnt/ ethcore/parity:beta --config /mnt/config.toml

Hope that helps.

**Comment by myqq0000** [comment]
![image](https://cloud.githubusercontent.com/assets/19700709/25695212/cf32fb5e-30e4-11e7-8538-7ed0ba1c811f.png)
Oh! I forget the configuration is effective in docker, not in my local directory. That's so stupid.
I just change the

>  chain="demo-spec.json" 

to 

> chain="/mnt/demo-spec.json"
in the config.toml. It works successfully!

Thanks a lot!!

**Comment by ddorgan** [comment]
Hi Myqq0000,
        
     Have you looked at the parity POA page at: https://github.com/paritytech/parity/wiki/Private-development-chain, it has some very useful references. Basically if you only want to do a one node system with instant sealing, you can run parity with the option --chain dev and that's it! You should then be able to open the UI and see an account with lots of ether in it and instant sealing.

For a multi-node setup you could take a look at something like Illya13's parity POA repo which contains multiple proof of authority and a gateway etc... https://github.com/illya13/parity-poa

Hope this helps,
David

**Comment by myqq0000** [comment]
@ddorgan That helps me a lot! Thank you very much! 👍

**Comment by ddorgan** [comment]
@myqq0000 there's also a new deployment script, maybe worth a try. 

http://github.com:paritytech/parity-deploy.git

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity-deploy

I'm working on the docs for this, please let me know if you have any questions regarding parity-deploy.

**Comment by resolver** [comment]
hi ddorgan - my parity runs in an unusual directory structure after parity-deploy.sh
how can i run my docker with the mount a local directory and replicate what a local node would have?

it runs here: ed@ubuntu:~/dev_lab/test/parity-deploy/data$ 
not here:
ed@ubuntu:~/.local/share/io.parity.ethereum/keys/ethereum$ 


~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/

**Comment by resolver** [comment]
one of them "spec.json":

{

	"name": "parity",
    	"engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "2",
                "validators" : {
                    "list": [ "0x5f0d4538231a913af91769562a7f9d6f0aefe7a9", "0x8ba39f58f31da45453deadea716c2c67bd24ef43" ]
                }
            }
        }
    },

    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "gasLimitBoundDivisor": "0x400",
        "networkID" : "0x11"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x1312D00"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x5f0d4538231a913af91769562a7f9d6f0aefe7a9": { "balance": "1000000000000000000000000000000000000000000000000000000000000000000000000" },
        "0x8ba39f58f31da45453deadea716c2c67bd24ef43": { "balance": "1000000000000000000000000000000000000000000000000000000000000000000000000" }
    }
}



the other file "reserved_peers":

enode://bbbc17cdeb4446ddd58c450aeca73d621c3a25786950d944ca890e29b737c1e01807355caf737d362256c786e2ba432c3b1f48790e1e258597241d452eee57a9@host1:30303
enode://66e6bac70661f9fcd857ad4f642c4eef9cdb8eb3f08c7ad079040300c88688e88a2b62e946d83df1e5437058064115707f381c0aebbfaf3ee6a0a03196bce901@host2:30303

**Comment by resolver** [comment]
how can i start mine and and add miner account to blockchain with the docker container?

because without parity in bash, how can i do this?

**Comment by ddorgan** [comment]
@resolver this is using the AuRa proof of authority consensus engine, no mining is required.

See: https://wiki.parity.io/Aura.html

**Comment by resolver** [comment]
oh :D 
And how i get ETH to my Test Accounts, if i create a new Account in Parity UI?

**Comment by ddorgan** [comment]
@resolver there's already an account provisioned within the chain with lots of eth. You can download the json file and import it: https://transfer.sh/i8Luj/testchain_recovery.json ... WARNING: This is an account with an empty recovery phrase. Never use on a public network.

Or you can edit the spec file and add a line like this in the accounts section:
```
"0xxxxxxxxxxxxxxxxxxxxx": { "balance": "1606938044258990275541962092341162602522202993782792835301376",
```

**Comment by resolver** [comment]
many thanks ;)

my last question: how can i add this acount for example: "0xxxxxxxxxxxxxxxxxxxxx" in my Parity UI Wallet to interacte firstly in the WebInterface to learn how it works?

**Comment by resolver** [comment]
many thanks ddorgan - i hope this thread is also helpul to other guys, which learn ethereum fantastic blockchain ;)

**Comment by resolver** [comment]
i have importet the account but the balance of ETH is 0. when i created an account in parity UI the balance is 0. how to i get eth to an account to test transaction and deploy smart contracts?

**Comment by Tbaut** [comment]
This is outside of the scope of this issue @resolver, please get in touch on the (Gitter channel)[https://gitter.im/paritytech/parity-poa] if you have any question related to PoA.

**Comment by resolver** [comment]
i have accounts in spec.json (chain spec):

{

	"name": "parity",
    	"engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "2",
                "validators" : {
                    "list": [ "0x5f0d4538231a913af91769562a7f9d6f0aefe7a9", "0x8ba39f58f31da45453deadea716c2c67bd24ef43" ]
                }
            }
        }
    },

    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "gasLimitBoundDivisor": "0x400",
        "networkID" : "0x11"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x1312D00"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x5f0d4538231a913af91769562a7f9d6f0aefe7a9": { "balance": "1000000000000000000000000000000000000000000000000000000000000000000000000" },
        "0x8ba39f58f31da45453deadea716c2c67bd24ef43": { "balance": "1000000000000000000000000000000000000000000000000000000000000000000000000" }
    }
}

But i don't see this accounts in Parity UI. Thats my Problem. I have used this one: https://github.com/paritytech/parity-deploy
