### ISSUE TITLE
Parity stoped syncing after block 860047/860048 [ropsten]

### ISSUE THREAD

**Issue by marekkirejczyk** [paritytech/parity#5551]
I run parity on 3 separate computers, two different locations. And both stopped syncing. One is stuck on block #860047 and the second is stuck at #860048.

After couple restarts, they got to #860054. Anyone else experiencing that?

Parity v1.6.5, Tried on macOS Sierra and Ubuntu 16.04.

Screenshot attached:
<img width="1266" alt="foodtoken_ _deploy_sss-staging____apps_sss_current_log_ _ssh_deploy_188_226_151_71_ _211x41" src="https://cloud.githubusercontent.com/assets/197522/25692448/fffc9264-30a2-11e7-9e0f-ea44a9fbf174.png">

**Comment by 5chdn** [comment]
What mode of operation is configure, could you check this? (UI -> Settings -> Parity)

**Comment by marekkirejczyk** [comment]
> the syning mode for the Parity node
> Parity continuously syncs the chain

**Comment by 5chdn** [comment]
Ropsten is dead again, probably someone attacked it. You could switch to kovan or a develop chain meanwhile.

**Comment by 5chdn** [comment]
Closing as this is beyond our control.

**Comment by 5chdn** [comment]
If this is only a temporary chain reorganization you could try to reset your ropsten database with `parity --chain ropsten db kill` and increase pruning history to something like `parity --chain ropsten --pruning-history 512` to prevent medium sized forks from interfering with your chain.

**Comment by marekkirejczyk** [comment]
Thanks for update (switched to kovan)
