### ISSUE TITLE
defaultAccount not working for browser extension

### ISSUE THREAD

**Issue by slothbag** [paritytech/parity#5576]
When using the browser extension I change the default account using the parity overlay/popup panel that appears, however defaultAccount still shows the first address.

**Comment by 5chdn** [comment]
What do you mean by _'still shows the first address'_? You can't change the default account? What steps to reproduce this (working for me)?

**Comment by slothbag** [comment]
When using a custom dapp with the parity browser extension it shows a small html overlay in the bottom right of the browser, when you click on that overlay it shows a list of accounts, and you can click on an account and it gets highlighted.. I assume by highlighting the account it sets it as the 'default'?

If that is the case, then doing a web3.eth.defaultAccount from within the dapp does not return the newly selected account, it returns the first account.  I could be way off base with my assumptions about how that process works.

**Comment by 5chdn** [comment]
Are you talking about the browser available at http://127.0.0.1:8180/#/web (this overaly is the parity trusted signer) ? Or the _browser extension_ you see on external sites like https://etherdelta.github.io ?

**Comment by slothbag** [comment]
The latter, the browser extension you see on external sites.. 

Am I assuming correctly that clicking on one of your accounts in the parity overlay that it changes the defaultAccount?

**Comment by tomusdrw** [comment]
@slothbag Could you provide a code snippet? We update `web3.eth.defaultAccount` on a global `web3` object (https://github.com/paritytech/parity-extension/blob/086ca27447f687c0ec8453ae6bfd296e038562c1/web3/provider.js#L94)
If you initialize `web3` on your own like this:
```js
var web3 = new Web3(web3.currentProvider);
```
then `web3.eth.defaultAccount` is not updated (since we don't even have a reference to your `web3` instance)
In such case you should rely on having `defaultAccount `as first account on the list: `web3.accounts[0]`.

**Comment by slothbag** [comment]
Ahhh, thanks that makes sense.

So I updated the code to not do a `web3 = new Web3(web3.currentProvider)` and it still does not appear to be working.. it always returns the same address which funnily enough is not [0], now its [5], but always [5] even after a refresh.

**Comment by slothbag** [comment]
Interesting, if I disable the extension and then re-enable the extension then the defaultAccount is updated, but it clicking on new accounts does not update (unless I disable/re-enable the extension)

**Comment by nt8587** [comment]
I am also experiencing this issue. Its very annoying and is currently forcing me to use metamask instead. @tomusdrw, here is a [code snippet](https://gist.github.com/nt8587/052594670f4ba8a84bab683e3a229b2b) demonstrating the problem:
- Load the page
- Note the displayed address
- Wait for the parity extension overlay to appear then change the account to something else
- Refresh the page
- Notice the overlay shows the new default account selection, but the displayed address has not updated
