### ISSUE TITLE
Kovan testnet not syncing beyond 32,321

### ISSUE THREAD

**Issue by adrianbrink** [paritytech/parity#5589]
I'm using the newest build of parity master.

Command
```
./target/release/parity ui --chain kovan --no-warp
```

```
Parity
  version Parity/v1.7.0-unstable-0bd4d5bb0-20170507/x86_64-macos/rustc1.19.0-nightly
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```
<img width="1280" alt="screen shot 2017-05-10 at 12 50 59" src="https://cloud.githubusercontent.com/assets/11320251/25895269/7e47b672-357f-11e7-8b21-31687d591cd8.png">

I would expect Kovan to fully sync. Any idea why this doesn't work? Also, how to I reset my entire chain history, but ideally only for Kovan.

**Comment by keorn** [comment]
Should be fixed in the PR above. To reset the Kovan chain use `parity db kill --chain kovan`.

**Comment by lgpawel** [comment]
Sadly, after `git pull`, `git checkout revert-aura`, `cargo build --release`, and `parity db kill --chain kovan` the result is the same.

**Comment by adrianbrink** [comment]
The issue still persists

**Comment by keorn** [comment]
Please check with the current branch, works fine for me.

**Comment by lgpawel** [comment]
After re-cloning the repo, `git submodule init` and `update`, and `cargo build --release`, unfortunately cannot confirm. The version number I get is `Parity/v1.7.0-unstable-8146cbdae-20170510/x86_64-linux-gnu/rustc1.17.0`.

**Comment by keorn** [comment]
You will need `git checkout revert-aura`, its the pending fix.

**Comment by lgpawel** [comment]
OK, seems to work now. Thanks!

**Comment by rphmeier** [comment]
@adrianbrink Have you tried as well?
