### ISSUE TITLE
"Invalid params" for simple sendRawTransaction

### ISSUE THREAD

**Issue by yuanfeiz** [paritytech/parity#5615]
I have the following simple snippet to transfer ether

    let rawTx = {
      nonce: '0x06',
      gasPrice: '0x09184e72a000',
      gas: '0x2710',
      to: '0x007798de8A3a892c6cB1cce33F6aE88f3e2dfa55',//config.registrar.address,
      value: '0x0de0b6b3a7640000',
      data: '0x00',
    };

    let tx = new Tx(rawTx);
    tx.sign(Buffer.from(privKey, 'hex'));

    let signedTx = tx.serialize().toString('hex');

    web3.eth.sendRawTransaction(signedTx, (err, result) => {
      console.log(err, result); // invalid params
    });

I found #1317 which states that all params should be prefixed with `0x` and I found https://gitlab.parity.io/parity/parity/blob/master/rpc/src/v1/types/bytes.rs#L84 which states the length of each param should be even. With both satisfied, still getting the invalid error.

**Comment by tomusdrw** [comment]
All `Bytes` fields (`data`) should have even length and also `to` should have fixed length. Other fields (`nonce`,`gasPrice`,`gas`,`value`) should be encoded as `QUANTITY` and leading `0` should be omitted:

```js
let rawTx = {
  nonce: '0x6',
  gasPrice: '0x9184e72a000',
  gas: '0x2710',
  to: '0x007798de8A3a892c6cB1cce33F6aE88f3e2dfa55',//config.registrar.address,
  value: '0xde0b6b3a7640000',
  // if you don't want any data you can also just skip the field. `0x00` means a single byte with value `0` will be attached to transaction
  data: '0x',
};
```

Can you run Parity with `-lrpc=trace`? What version do you run? We have enhanced RPC errors recently and it should be displaying some more details.

**Comment by yuanfeiz** [comment]
I figured out it was caused by `signedTx` not prefixed by `0x`. Other than that, everything works fine. While that worked in geth really trapped me. So glad to know the errors would be more verbose .

Thanks for the help!
