### ISSUE TITLE
Document CLI parity account import

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#5618]
There is no clear way of explaining how to import an account using CLI method
`parity account import` 
What are the arguments? Json file? Password? Mnemonics phrase? Private keys? 

I've tried to use:

```
 parity account import  UTC--2017-05-14T22-02-46Z--717e724c-5bec-e5bb-1eb9-ab92354084b2 --chain dev
```
Importing accounts failed.

**Comment by tomusdrw** [comment]
This command expects a keys directory as an input. Inside there should be a per-chain directory containing key files.

Perhaps it makes more sense to actually change the command to import key files directly:
```
$ parity account import <key-file>...
```

**Comment by 5chdn** [comment]
Crossposted here: https://ethereum.stackexchange.com/questions/16164/how-to-import-an-account-in-parity-using-cli

@rstormsf are you trying to import an existing account?

**Comment by rstormsf** [comment]
Ok. Works as expected. It just needs a better documentation.
Here is how I got it working:

```
mv ~/.local/share/io.parity.ethereum/keys/DevelopmentChain ~/someFolder
cd ~/someFolder/DevelopmentChain
parity account import . --chain dev

```
Caveat: if you don't specify the chain, it will import to HOMESTEAD by default.

**Comment by rstormsf** [comment]
@tomusdrw @5chdn 
Another question regarding import:
How would you import keys using CLI mode for private chain? 
Private chains have different folder path, so how should I construct my CLI command in order to import it succesfully into the right.
Here is what I tried:
```
parity account import ./someFolder/keys/DemoPoA/* --chain demo-spec.json --keys-path node0/keys
```

**Comment by 5chdn** [comment]
Yes, the import command accepts chain and path parameters. Will add this to the wiki. Thanks.
