### ISSUE TITLE
Expanse chain sync fail

### ISSUE THREAD

**Issue by zet-tech** [paritytech/parity#5625]
Expanse chain sync fail both as a continuation from previously synced blockchain and from fresh db after kill db. Tested both on 1.4.10 and 1.6.6

Logs on 1.6.6 show:
IO Worker #3 INFO import  Imported #605723 0e0f…c384 (0 txs, 0.00 Mgas, 0.18 ms, 0.53 KiB) + another 47 block(s) containing 65 tx(s)
IO Worker #0 WARN client  Stage 1 block verification failed for 4bfc…2a14: Transaction(InvalidNetworkId)
IO Worker #0 INFO import  Syncing  #605723 0e0f…c384     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed   #589340    1/11/20 peers   191 MiB db   11 MiB chain  0 bytes queue  288 KiB sync  RPC:  0 conn,  9 req/s, 128 µs

On 1.4.10 it hangs and prints peers indefinitely.

**Comment by 5chdn** [comment]
Could you add more verbose log output, maybe run with `-lsync=trace` and paste the output somewhere?

Can you confirm your parity 1.6.6 node stops synchronizing after this message?

**Comment by 5chdn** [comment]
I can not reproduce this with latest master.

**Comment by zet-tech** [comment]
I tried on another machine running Parity 1.5.11 (I know that it is not the last stable). Result is exactly the same as on 1.6.6. As you can see in the log it does not stop sync after error message (both 1.5.11 and 1.6.6)

.

I attach logs. Full trace log is to bigto attach: [https://ufile.io/843dd](https://ufile.io/843dd)
[parity-expanse-out.txt](https://github.com/paritytech/parity/files/1004373/parity-expanse-out.txt)

**Comment by rphmeier** [comment]
cc @chrisfranko: do other nodes use a different network ID for expanse than specified here? https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/expanse.json#L31

**Comment by chrisfranko** [comment]
<600,000 doesnt have a chain id, the network has always been network id 1,
and now post block 600k is chain id 2

**Comment by zet-tech** [comment]
I see that the issue is fixed on master. Will it be included in next release and when can it be expected ?

As a workaround we tried to use .json file form master pasted as a --chain argument to parity. Unfortunately Parity is still unable to sync with Expanse blockchain. There is no error but "Syncing  #606291 fbf6…f9b1" goes forever despite 7 peers.

**Comment by 5chdn** [comment]
@zet-tech if you don't want to wait, you can download the json and run it directly against expanse. like:

    wget https://raw.githubusercontent.com/paritytech/parity/master/ethcore/res/ethereum/expanse.json
    parity --chain ./expanse.json

Closing as fixed in #5351 - added the patch label to make sure it will be included in next beta release.
