### ISSUE TITLE
Ethstats is down

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#5626]
http://stats.ethdev.com/ - http://www.isitdownrightnow.com/stats.ethdev.com.html 
It looks like it's down. 

The reason why I filed it here because on the landing page: https://parity.io/parity.html it states: 
"...On Ubuntu this script will also offer to install the Netstats client and connect it to stats.ethdev.com"

So, we have to either remove it from landing page, or fix the server.

**Comment by tomusdrw** [comment]
The correct address is https://ethstats.net/, indeed requires fixing.

**Comment by rstormsf** [comment]
@tomusdrw show me where is the repo for landing page and I will submit a PR

**Comment by tomusdrw** [comment]
@rstormsf PR already submitted, but the repo is private.

**Comment by rstormsf** [comment]
Ohh I see. Thank you, @tomusdrw

**Comment by tomusdrw** [comment]
@jesuscript Can you have a look at this?

**Comment by jesuscript** [comment]
Hey Tomasz. Travelling and afk this week, can you please ping David?

**Comment by tomusdrw** [comment]
Sure, no worries. @ddorgan Can you have a look at the website issue?

**Comment by ddorgan** [comment]
Should be resolved, can you confirm.

**Comment by 5chdn** [comment]
THanks
