### ISSUE TITLE
Transactions List and blockexplorer

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#5638]
**Feature Request**
When I run PoA, am I supposed to see a list of transactions if I send some from 1 account to another in my private chain?
Cause it says on the UI that 
```
Transaction list powered by etherscan.io
```
So I shouldn't expect it, right?

How would I enable it then? is it possible? 

2. The same goes for blockexplorer, how would it be possible to have a blockexplorer for PoA chain?

**Comment by 5chdn** [comment]
Indeed this should not happen on a private chain.

**Comment by keorn** [comment]
For the block explorer you can try [Etherchain Light](https://github.com/gobitfly/etherchain-light).
Otherwise it would be cool if the UI would leverage different database types if available on the local node.

**Comment by rstormsf** [comment]
I guess https://github.com/trufflesuite/ganache might be also supported if pointed to a different chain

**Comment by 5chdn** [comment]
related #3910 #4123 #6228

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
