### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by erelsgl** [paritytech/parity#5639]
I tried to install Parity on Ubuntu 16.04 in three different ways, all of which failed.

* Using the Debian package http://d1h4xl4cr1h0mo.cloudfront.net/v1.6.6/x86_64-unknown-linux-gnu/parity_1.6.6_amd64.deb , I get an error: "The package is of bad quality - The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20."

* Using "bash <(curl https://get.parity.io -Lk)", I get:

    dpkg: error processing archive /tmp/parity.deb (--install):
     trying to overwrite '/usr/bin/ethkey', which is also in package ethkey:amd64 1.2.9-SNAPSHOT--20160629-6a05dd7~xenial-0ubuntu2
    dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
    Errors were encountered while processing:
 /tmp/parity.deb
    ==> Parity is missing
    ==> Installation failed

* I also tried "**sudo** bash <(curl https://get.parity.io -Lk)", and got:

      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     bash: /dev/fd/63: No such file or directory
    100   154  100   154    0     0    334      0 --:--:-- --:--:-- --:--:--   33440-G3:~$ 
    100   154  100   154    0     0    165      0 --:--:-- --:--:-- --:--:--   165
     33 13856   33  4686    0     0   3197      0  0:00:04  0:00:01  0:00:03 2694k
    curl: (23) Failed writing body (2169 != 2759)

**Comment by tomusdrw** [comment]
Seems that there is a conflicting binary, please remove `ethkey` and then try the second method again.
```
$ sudo apt-get remove ethkey
$ bash <(curl https://get.parity.io -Lk)
```

We're aware of the deb package issues, I believe it was already fixed and next release will work ok.

**Comment by erelsgl** [comment]
This solved the issue, thanks

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by sasikumar13** [comment]
same error as erelsgl
