### ISSUE TITLE
cargo install --git https://github.com/paritytech/parity.git parity

### ISSUE THREAD

**Issue by xussr** [paritytech/parity#5643]
xussr@etc:~$ cargo install --git https://github.com/paritytech/parity.git parity
    Updating git repository `https://github.com/paritytech/parity.git`
failed to parse manifest at `/home/xussr/.cargo/git/checkouts/parity-ac147543390062a1/master/Cargo.toml`

Caused by:
  could not parse input as TOML
.cargo/git/checkouts/parity-ac147543390062a1/master/Cargo.toml:67:9 expected a key but found an empty stri            ng
.cargo/git/checkouts/parity-ac147543390062a1/master/Cargo.toml:67:9-67:10 expected `.`, but found `'`

**Comment by tomusdrw** [comment]
Please update to latest `rustc/cargo`.
Using `rustup update stable`
