### ISSUE TITLE
Document how to run test.sh

### ISSUE THREAD

**Issue by guanqun** [paritytech/parity#5648]
I try to run this, but apparently, it complains:

`rpc/src/v1/tests/../../../../ethcore/res/ethereum/tests/BlockchainTests/bcRPC_API_Test.json` is missing, where should I pull these json files?

**Comment by NikVolf** [comment]
hi, json tests are in the submodule

just run `git submodule update --init` in the repository root

**Comment by guanqun** [comment]
Thank you!
