### ISSUE TITLE
how to cancel signer tx

### ISSUE THREAD

**Issue by lampax** [paritytech/parity#5650]
There is 100 eth in my wallet.
First I submit a tx sending 100eth use "send after BlockNumber"  tx(tx1) at block N and it's still not reach that block N. Then I submit another tx(tx2) sending 100eth  use "send after BlockNumber"  at block N-10(before N).
Now the best block reach at block N-10, what will happen? tx2 will execute first? 
Or until reach at block N execute tx1, then tx2?

btw: Is there a way to cancel signer tx?

**Comment by tomusdrw** [comment]
Transactions are always executed in the order they were signed, so Parity will wait till block `N` and execute `tx1` and then `tx2`.

There is an option to cancel transaction in version 1.7 (unstable), on previous versions you can try to replace the transaction with a no-op transaction using RPC. Alternatively you can remove the chain data - this will clear the transactions as well.
