### ISSUE TITLE
Enabling Ledger Nano S 'contract support' makes the account unavailable

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#5652]
Normal:

- Connect Ledger Nano S
- Disable contract support
- Disable browser Support
- Ledger account visible (colored icon, desired)

Contract Support broken:

- Enable contract support
- Ledger account unavailable (grey icon, unexpected)

Workaround:

- Enable browser support
- Disable browser support (toggle off and on)
- Ledger account available again (colored icon, now with contract support enabled)

**Comment by arkpar** [comment]
Linux?

**Comment by 5chdn** [comment]
Yes linux.

**Comment by thekevinb** [comment]
I'd like to confirm.  Problem as described and work around as described.

I am also working on Parity 1.6.7 on Ubuntu 16.04 LTS.   

Thankyou for the work around 5chdn

**Comment by arkpar** [comment]
This is fixed in https://github.com/LedgerHQ/blue-app-eth/commit/dca33eab262730e94353c9c6ea57027389bb03da
Pleas update ethereum app on the device to at least 1.0.12
