### ISSUE TITLE
Multisig confuses balances of owner account with balance of wallet in some cases.

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#5658]
Reported on Gitter, can reproduce this.

>TSWesselius @TSWesselius May 18 22:29
>Hi I'm here to report a bug on Parity's multisig. When wanting to transfer an amount from the multisig wallet contract that is higher than the amount of ETH on the account that initiates the transaction, it warns that 'the tranaction total is higher than the available balance (though there is enough in the multisig contract wallet, just not in the account that sends the execute command to the contract) Don't know if someone can reproduce this?
>v1.6.6-beta-8c6e3f3-20170411/x86_64-macos/rustc1.16.0

**Comment by jayman2989** [comment]
We really need this patched. I need to be able to access my Ether!

**Comment by gavofyork** [comment]
@5chdn i haven't been able to reproduce - could you give specific steps? is it reproducible on master?

**Comment by 5chdn** [comment]
Just tried hard with 1.6.8 and I'm not able to reproduce it anymore, it was some edge case I discovered while taking screenshots for the wiki. But it was clearly a bug that reads the wrong account's balance under certain circumstances. But maybe it's that kind of JavaScript hick-up or otherwise hard to catch bugs. Maybe @jayman2989 or @TSWesselius could tell us how to reproduce it? Any idea?

**Comment by jayman2989** [comment]
I don't think I'm able to reproduce anymore... Sorry for my lack of info before.
