### ISSUE TITLE
Account name not displaying correctly on accounts page

### ISSUE THREAD

**Issue by AlexanderSupersloth** [paritytech/parity#5660]
Often the names of my various accounts on the accounts page do not display correctly. Instead, all of the names appear as:

    _E_0K2H

I cannot find how to reproduce the bug. However, this never occurs to accounts individually - it is either happening to all of them or none of them. 

Moreover, the names always display correctly when I enter the account managements homepage of any individual account. 

Finally, the names always display correctly when sending a transaction and looking at my address book.

I am running Parity 1.6.6 on MacOS Sierra.

**Comment by 5chdn** [comment]
Seems like you are not alone. Is this similar? #5485

**Comment by SilverPin** [comment]
Yes, it does look similar. Now that I think about it, there are other nonsensical names that it cycles through sometimes. However, none are the same as names that appear in the issue you quoted.

To overcome the problem I often just have to close the page and reopen it, however sometimes it persists.

I will take a screenshot next time it happens.

**Comment by SilverPin** [comment]
Here is the bug in action. This time there is a different nonsensical string. This has happened twice today, which is not at all unusual. 

![parity](https://cloud.githubusercontent.com/assets/24178244/26258748/f3b23078-3cbd-11e7-8aab-55ae734c0d61.jpg)

**Comment by SilverPin** [comment]
Another incarnation, this time with another slightly different string:

![parity](https://cloud.githubusercontent.com/assets/24178244/26396467/3969f8f2-406b-11e7-9313-d2516faa6675.jpg)

**Comment by 5chdn** [comment]
Does this still happen?

**Comment by AlexanderSupersloth** [comment]
I'm not sure. I haven't been opening the Parity UI much lately. I will keep an eye on it and let you know.

**Comment by AlexanderSupersloth** [comment]
Yes, it is still happening. Since I first reported this bug I have upgraded to 1.7.0. 

![screen shot 2017-08-26 at 15 21 53](https://user-images.githubusercontent.com/24178244/29742263-b045321e-8a73-11e7-8d6e-5bf486b7797f.jpg)

**Comment by AlexanderSupersloth** [comment]
This one may give some clue as to the cause, because it happened just after I logged into my Protonmail email account:

![screen shot 2017-08-30 at 20 28 40](https://user-images.githubusercontent.com/24178244/29892170-841883b2-8dc5-11e7-9a48-9bb16163f2da.jpg)

**Comment by 5chdn** [comment]
But that's not your "Proton Mail Password" ... in the screenshot, is it?

What browser is that, and do you use any extensions for password management?

**Comment by AlexanderSupersloth** [comment]
Nope, though you did just give me a mini heart attack. I read PWD as 'print working directory' rather than 'password'. 

I use Chrome and LastPass. 

I should stress Protonmail was not actually open at the time this happened, but it had been open very recently. The word 'Proton' and 'Mailbox' could be coincidental, though that seems somewhat unlikely. 

Other than that I am really out of ideas. This seems like a very strange bug and I cannot reproduce it at all. I have done a fresh install of my OS since this first appeared and also upgraded Parity to 1.7.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
