### ISSUE TITLE
Block verification failed (InvalidSeal)

### ISSUE THREAD

**Issue by MasX** [paritytech/parity#5661]
Private PoA network: 2 nodes Parity 1.6.6 Beta, of which one sealing, 4 nodes Parity 1.7.0 Unstable of which one sealing. The 1.7.0 mining node has 
`reseal_on_txs = "none"
force_sealing = true`. 
Mining nodes are connected to eachother, the rest is connected to their same version mining node.

After a few days one of the non-mining 1.7.0 got:
`Stage 3 block verification failed for #349440 (f9a0…08a6) Error: Block(InvalidSeal)`. Error is always on the latest block.
Tried: Removing chain and resyncing, `--no-seal-check`, upgrading parity to unstable of 20170518 (this changes 'Stage'  to 4).
16 hours after, both Parity 1.6.6 nodes got the same error. No problems on identical Parity 1.7.0 nodes.

**Comment by keorn** [comment]
There is a few changes that have been added to the validation in unstable, but I dont think that is it. Could you make sure you run NTP on those? What is the `stepDuration`?

**Comment by MasX** [comment]
NTPd was not running, but something else is calling ntpdate on a regular basis. However, requests were blocked by the firewall. Can we make sure that this is the issue?

`stepDuration` is 5.

Is there a way to 'recover' the current chain?

**Comment by keorn** [comment]
First try to simply restart each node, drop by to https://gitter.im/paritytech/parity-poa to debug.

**Comment by keorn** [comment]
Indeed clock drift seems to have been the reason.
