### ISSUE TITLE
Minor wiki update.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5666]
Sadly, since GitHub Wiki's aren't actually Wikis (no outside contributions allowed) I can't make this edit myself.

https://github.com/paritytech/parity/wiki/Backing-up-%26-Restoring shows the Windows path as `%HOMEPATH%/AppData/Roaming/Parity/Ethereum/keys`.  This path isn't actually correct as the roaming profile folder may be moved to a different location depending on OS settings.  The correct path is `%APPDATA%/Parity/Ethereum/keys/ethereum`.  I'm less confident about the trailing `ethereum`, but that is where I had to go to find my keys as `Parity/Ethereum/keys` is juts a folder with a single subfolder `ethereum` in it.

**Comment by MicahZoltu** [comment]
Also on that same page there are no restore instructions for Windows, perhaps this is because it is assumed the user is using Explorer to backup, so it is a bit undefined exactly how they would restore?

**Comment by 5chdn** [comment]
Yes, this page really needs some love, will try to do it this week. Thanks for the pointer.

**Comment by 5chdn** [comment]
Closing in favor of #5450 - on hold for the 1.7 release
