### ISSUE TITLE
dApp registration should support a root directory option.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5673]
dApp projects tend to consist of several pieces including the contracts, the UI, tests, deployment scripts, etc.  At the moment, dApp registration requires the user put the `index.html` file in the root of the repository.  This prevents the dApp author from using any other directory structure besides content root == repo root.

Add an additional parameter to dApp registration that allows the user to provide a non-default content root path.  e.g., `client/dist/`

**Comment by folsen** [comment]
Closing as UI is being moved.
