### ISSUE TITLE
Bytecode uploaded by Parity contract uploader does not match the Bytecode produced by any other online compiler.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5675]
1. Open Parity UI
1. go to contracts
1. new
1. change compiler version to 0.4.10
1. paste in the code from https://github.com/Zoltu/recoverable-wallet/blob/6a14076f2d4d0d37853eb302ac7a04a00828e62f/contracts/recoverable-wallet.sol
1. check "Optimise"
1. Click compile
1. Choose `RecoverableWalletFactory` contract
1. go to http://remix.ethereum.org
1. create a new file
1. name in the same as the file in Parity
1. paste in the same code
1. change compiler to 0.4.10
1. enabled optimization
1. goto contract tab
1. contract details on `RecoverableWalletFactory` contract
1. Compare the Bytecode output of Parity with Remix.
1. Notice that they don't match at all.

You can upload the contract and repeat the process for etherscan.io, which matches pretty closely (except a little bit at the end which I believe is a separate issue).

**Comment by ngotchac** [comment]
Unable to reproduce : https://kovan.etherscan.io/address/0xC7BEFBF7696fE7451571c1e5799FB67B668D2789#code

Here is the verified contract on Etherscan
