### ISSUE TITLE
Wrong balance shown in webwallet for private chain

### ISSUE THREAD

**Issue by reiven** [paritytech/parity#5681]
I've created a bunch of addresses and balances for a private chain in the genesis.json file. 
Example:

```bash
cat genesis.json| grep 0xab86980462339941c4f9207c6fb7fc74bd720aae
	"0xab86980462339941c4f9207c6fb7fc74bd720aae": { "balance": "119655097624"},
```
If i query the RPC, it shows the right balance

```python
>>> int(api.eth_getBalance('0xab86980462339941c4f9207c6fb7fc74bd720aae') ,16)
119655097624
```

But if i import the corresponding private key for this address, it show no balance:

![image](https://cloud.githubusercontent.com/assets/362717/26329499/e933d28e-3f1d-11e7-9682-f7851a0e4817.png)

I dont know where is the webwallet is getting the balance?

**Comment by 5chdn** [comment]
Yes, it's rounding the balance to 3 decimals. 

    119655097624 / 1e18 = 0.000000119655097624

Try to add something bigger to your chain spec, like `1196550976243563453453`.

**Comment by reiven** [comment]
my fault @5chdn i've been using 1e8. Thanks
