### ISSUE TITLE
Publish parity.js and parity.js.min somewhere.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#5682]
I would like to be able to just grab the latest version of parity.js and embed it in my dApp, but at the moment it appears the only way to get it is via npm and I think that means I have to package it myself.  Since I don't have other dependencies coming from NPM, this results in a lot of infrastructure work juts to download a single file.

**Comment by debris** [comment]
I believe this can be closed. All of our js repos are now a part of [parity-js](https://github.com/parity-js) org
