### ISSUE TITLE
Allow configuring a gas price for all transactions

### ISSUE THREAD

**Issue by rainbreak** [paritytech/parity#5690]
At present it is necessary to set the gas price on every transaction if you want something that is different to that given by RPC.

It would be useful to have an option to override this and set a default gas price that is then applied to all transactions.

**Comment by cduchesne** [comment]
This is definitely something that annoys me every time - it would be great to allow a setting to configure the default gas price for transactions. The current default is way too high and it takes me a good 5-10 seconds of extra effort every time I go to send a transaction. I have also sent plenty of transactions in which I've forgotten to change the gas price - this costs me a good $0.50 extra each time when working with contracts.

**Comment by cduchesne** [comment]
side-note ( can the gas price section show the denominator in something more readable? like in Mwei or Gwei instead of wei - I am sure people have accidentally typed in the wrong number of zeroes before and overpaid. )

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
