### ISSUE TITLE
No possibility to skip "account create" in parity ui, when I already know that I just want to use recovery phrase to restore my account

### ISSUE THREAD

**Issue by noisy** [paritytech/parity#5693]

**Comment by 5chdn** [comment]
You could restore that account from via JSONRPC call before accessing the UI.

    curl --data '{"method":"parity_newAccountFromPhrase","params":["stylus outing overhand dime radial seducing harmless uselessly evasive tastiness eradicate imperfect","hunter2"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module#parity_newaccountfromphrase

Once the account is there, you can SKIP the account creation process in the UI.
