### ISSUE TITLE
When running parity I get ERR_CONNECTION_REFUSED in browsers

### ISSUE THREAD

**Issue by madvas** [paritytech/parity#5701]
When I start parity I start to get "This site can't be reached" for any website in any browser. If I refresh page many times, sometimes a page loads. Everything starts working properly after I quit parity. 

I'm using: 
Mac OS Sierra 10.12.5
Parity version Parity/v1.6.7-beta-e128418-20170518/x86_64-macos/rustc1.17.0

![image](https://cloud.githubusercontent.com/assets/3857155/26519818/35016a56-42f1-11e7-8d91-0d178505201a.png)

**Comment by tomusdrw** [comment]
Does it happen when you run Parity with `--mode offline`? Or go to "Settings -> Parity -> Mode" in Parity Wallet.

Perhaps Parity uses your whole bandwidth to sync the chain, and other pages are not accessible. What kind of internet connection do you have?

**Comment by madvas** [comment]
Thanks for a quick reply. Doesn't seem to be happening with `--mode offline`. That's actually very good point, because I'm on a hotel wifi, which is throttled per user, but to reasonable speed, it's not slow. So it would be still nice if parity was able to operate under such conditions.

**Comment by tomusdrw** [comment]
There is an issue to handle low bandwidth connections: #2831. As a workaround you can limit number of peers and wait until Pairty is fully synced, it should require much less bandwidth then.
