### ISSUE TITLE
automatic install command crashes

### ISSUE THREAD

**Issue by arielgabizon** [paritytech/parity#5702]
I tried to run
`cargo install --git https://github.com/paritytech/parity.git parity`

and it crashed while compiling hidapi v0.3.1
![image](https://cloud.githubusercontent.com/assets/5689834/26519899/1a036e68-42d1-11e7-919d-86dea90cfc34.png)

**Comment by tomusdrw** [comment]
Please `apt-get install libudev-dev`.

**Comment by arielgabizon** [comment]
Just tried that. I get these failed to fetch errors (also tried after with --fix-missing)

![image](https://cloud.githubusercontent.com/assets/5689834/26519936/d1f98048-42d1-11e7-959f-8a09fee2d5fb.png)

**Comment by arielgabizon** [comment]
Ohh but I'm rerunning the cargo install and it seems to be making more progress now

**Comment by tomusdrw** [comment]
Please run `apt-get update` before you run `apt-get install libudev-dev`. Anyway installing this package should help compiling Parity.

**Comment by arielgabizon** [comment]
OK, it ended up helping and now I'm stuck on ethsync 

![image](https://cloud.githubusercontent.com/assets/5689834/26520409/bd11114c-42da-11e7-9cc9-79a050a924d0.png)

**Comment by tomusdrw** [comment]
You need to update your rust compiler.
