### ISSUE TITLE
problems with tutorial

### ISSUE THREAD

**Issue by arielgabizon** [paritytech/parity#5703]
When trying to follow the tutorial and use webpack I get this error

![image](https://cloud.githubusercontent.com/assets/5689834/26521378/d430bd2c-42ef-11e7-8eea-3273e8c16559.png)

**Comment by CraigglesO** [comment]
Either:
1) pull from branch "jr" and npm install OR
2) run the init script which will install these dependencies for you. ("./init-script" I think?)
3) Install the dependency yourself: `npm install --save babel-loader` BUT you are going to have to do that for every dependency error you get... so do 1 or 2

**Comment by arielgabizon** [comment]
Thanks, I ran `./init.sh`
which helped.
Then I ran webpack again, which gave some warning but not an error.
Though I didn't get what the tutorial claimed would happen - an `index.js` file in my `dist` path.

**Comment by arielgabizon** [comment]
Also, in the tutorial there's a picture of some GUI browser but when I run parity from the command line I just got some stats printed out in the shell.
How do I get to this GUI?

**Comment by CraigglesO** [comment]
Warnings are normal. Will still work.

Ah, Yes, this tutorial is definitely focused upon using Parity's UI. If you don't want to be restricted to parity-ui than use web3 directly. But the solidity contracts are by no means bound by a ui.

At some point a tutorial has to diverge to a specific set of tools; it goes without saying that a parity tutorial would use parity tech.

Closing as this seems to be solved.

**Comment by arielgabizon** [comment]
> Ah, Yes, this tutorial is definitely focused upon using Parity's UI. If you don't want to be restricted to parity-ui than use web3 directly. But the solidity contracts are by no means bound by a ui.

My point was simply that it doesn't say you need to run `parity ui` and that can confuse someone who is trying to follow the tutorial and doesn't understand how to get to the gui.

**Comment by CraigglesO** [comment]
Ah, I see. Thanks for your input!
