### ISSUE TITLE
Accounts not displayed in Safari

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5706]
Reported via support e-mail:
Safari version 10.1 (12603.1.30.0.34)

<img width="1280" alt="screen shot 2017-05-27 at 11 34 31 pm" src="https://cloud.githubusercontent.com/assets/581548/26554230/63cbd99e-448f-11e7-80a4-a7c5c0704128.png">

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
