### ISSUE TITLE
 Parity - waiting for confirmations .. forever

### ISSUE THREAD

**Issue by Sherpi** [paritytech/parity#5713]
Hi,

I am trying to send out some eth from parity but all I recive is -waiting for confirmations- after pressing the send button. What confirmations? Do I have to confirm from somewhere?

What am I doing wrong?

Edit: I can see the transactions under the tab SIGNER but there is no button to sign ..

**Comment by tomusdrw** [comment]
Please go to `Applications -> TxQueueViewer` and let us know if the transactions are there and if they were propagated.

Most likely you have a scheduled transaction sent from this account and it's blocking every subsequent transaction.

**Comment by Sherpi** [comment]
I do have 4 transactions under my local transactions with status In queue: Pending 0 (0 peers)

Transactions in the queue # Propagated 0 (0 peers)

**Comment by tomusdrw** [comment]
Please update to 1.6.7, there is a cancel option on "Signer" tab.

**Comment by Sherpi** [comment]
thank you. How do I update it to 1.6.7? :)

**Comment by tomusdrw** [comment]
Latest version always available here: https://github.com/paritytech/parity/releases

**Comment by Sherpi** [comment]
Thank you.

I update to the latest version and could cancel it.

I sent it again and there was *waiting for confirmations* which didnt seem to stop. I pressed close but couldnt find anything under SIGNER. It removed the ETH from my balance. Looks like it went out after all.

If I schedule a transaction for a certain date or blocknumber .. I cant do any other transactions in the meantime? Is that right?
