### ISSUE TITLE
Can't send transaction, can't "Reveal" on ENS - nothing happens!

### ISSUE THREAD

**Issue by coyotito1** [paritytech/parity#5715]
In the last few hours I haven't been able to reveal any bids, it just says "Revealing" and when I come back to it I need to do it again, nothing happens.

I also can't make any new bids, or even send transactions to my other ETH accounts. It just says "Waiting for confirmations...." forever.

Anyone knows what's going on?

**Comment by tomusdrw** [comment]
Please go to `Applications -> TxQueueViewer` and let us know if the transactions are there and if they were propagated.

Most likely you have a scheduled transaction sent from this account and it's blocking every subsequent transaction.

**Comment by coyotito1** [comment]
Yes there's a bunch there - how do I cancel them all?

**Comment by tomusdrw** [comment]
Update to 1.6.7 and you should be able to cancel them on Signer tab.

**Comment by coyotito1** [comment]
Updated, restarted... still no way to cancel. 

Screenshot: http://imgur.com/a/JUtmC

**Comment by tomusdrw** [comment]
You need to go to this tab:
![screenshot from 2017-05-30 16-13-05](https://cloud.githubusercontent.com/assets/581548/26587522/e65f749c-4552-11e7-83b0-9286d802858c.png)

**Comment by coyotito1** [comment]
Hmm, still shows me this: http://imgur.com/a/JAYZc

**Comment by tomusdrw** [comment]
Please restart your node with `--no-persistent-txqueue`, seems like a bug in the UI.

**Comment by coyotito1** [comment]
I don't understand what that means, do I type that in somewhere? :)

**Comment by tomusdrw** [comment]
Yes, you should close Parity and run it from terminal (only once) like this: `$ parity --no-persistent-txqueue`

Alternatively you can create a config file:
https://paritytech.github.io/parity-config-generator/#config=eyJtaW5pbmciOnsibm9fcGVyc2lzdGVudF90eHF1ZXVlIjp0cnVlfSwiX19pbnRlcm5hbCI6eyJwbGF0Zm9ybSI6Ik1hYyBPUyJ9fQ==

Restart Parity and then remove it afterwards (it will use persistent queue in future,will just clear it for a single time).

**Comment by coyotito1** [comment]
Sorry I am not technical at all, how do I run it from "Terminal" ?

**Comment by tomusdrw** [comment]
Sorry, just noticed that you're on Windows.
Please download this config file:
https://paritytech.github.io/parity-config-generator/#config=eyJtaW5pbmciOnsibm9fcGVyc2lzdGVudF90eHF1ZXVlIjp0cnVlfSwiX19pbnRlcm5hbCI6eyJwbGF0Zm9ybSI6IldpbmRvd3MifX0=

And put it to `%AppData%\Local\Parity\Ethereum\config.toml`

**Comment by coyotito1** [comment]
Still not working mate.... all my transactions get stuck "in queue" regardless of gas price!

**Comment by coyotito1** [comment]
![namnlos](https://cloud.githubusercontent.com/assets/29064203/26644008/9f786516-4633-11e7-8b03-79dae4926894.png)

Just loads of these..... whatever I do, whatever gas price I set.... nothing happens! I am afraid I am going to loose a lot of auctions that need revealing etc!!

**Comment by tomusdrw** [comment]
Are you fully synced with the chain? please follow this steps:
https://github.com/paritytech/parity/wiki/FAQ#what-can-i-do-when-parity-has-trouble-getting-in-sync

Can you see your transctions on etherscan?
