### ISSUE TITLE
Where are all the config files on MacOS?

### ISSUE THREAD

**Issue by davidhq** [paritytech/parity#5719]
Parity (in command line) starts in `offline` mode for me and I cannot find the `config.toml` file or any config file anywhere, references in wikis are wrong. So what is the location and I can also help update the wiki. thank you

**Comment by tomusdrw** [comment]
Parity starts in last mode you used, so you can just run once with `--mode active` and it will remember the setting.
Note: the default setting for `--mode` is `auto` which means exactly this. You can override this by using `config.toml`.

Internal state is stored in `~/.local/share/io.parity.ethereum/chains/ethereum/user_defaults` on linux for `foundation` chain, but those files are not meant to be modified by users.

**Comment by davidhq** [comment]
So no default `config.toml` parity searches for when not run with `--c [some_config]`?

**Comment by tomusdrw** [comment]
So `$BASE/config.toml` is the default location where Parity looks for a config file, but the config file itself is not there (it's not necessary). Settings in config can override default settings and config settings can be overridden by CLI flags.

`$BASE` it's what you've set your `--base-path` to. By default it will be `/Users/<username>/Library/Application Support/io.parity.ethereum/` on Mac.

To create a config file you may have a look at https://paritytech.github.io/parity-config-generator

**Comment by davidhq** [comment]
Now it's clear how it works, thank you.
