### ISSUE TITLE
How to update Parity installed via Terminal (Bash) on Ubuntu

### ISSUE THREAD

**Issue by lifyd** [paritytech/parity#5720]
Hi, I used `bash <(curl https://get.parity.io -Lk)` in Terminal to install Parity on Ubuntu.

How do I manually upgrade via the Terminal to 1.67? Thanks

**Comment by lifyd** [comment]
Solution: Use `bash <(curl https://get.parity.io -Lk)` again to update.

**Comment by 5chdn** [comment]
Exactly :)
