### ISSUE TITLE
Export Account is shown but doesn't work for External Accounts

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5723]
Doesn't work as External Accounts are not password protected. Export could maybe provide a JSON with address & metadata similar to export of addressbook.

`Parity//v1.7.0-nightly-38ed39e-20170511/x86_64-windows-msvc/rustc1.17.0`

**Comment by tomusdrw** [comment]
Will also need a matching import option (currently you can only add new external account by scanning a QRCode iirc).
