### ISSUE TITLE
[WIKI] Updated screenshot for Dapp tutorial

### ISSUE THREAD

**Issue by louisgv** [paritytech/parity#5725]
New screenshot for the Dapp tutorial. If the quality is not up to pair, feel free to use this repo to quickly replicate and reproduce each screenshot:

https://github.com/louisgv/parity-dapp-tutorial-screenshot-generator

@gavofyork

**Comment by louisgv** [comment]
> Tutorial 1

![0](https://cloud.githubusercontent.com/assets/6723574/26618231/7b96fae0-458e-11e7-98f8-b021d7eaf823.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618232/7bad21bc-458e-11e7-9fd4-0575618e4020.png)

**Comment by louisgv** [comment]
> Tutorial 2

![0](https://cloud.githubusercontent.com/assets/6723574/26618244/85fea37a-458e-11e7-88e2-24bb29467900.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618249/861887cc-458e-11e7-9884-c7b736882d48.png)
![2](https://cloud.githubusercontent.com/assets/6723574/26618246/8604c91c-458e-11e7-8b86-b73bedbcd7f0.png)
![3](https://cloud.githubusercontent.com/assets/6723574/26618247/8605821c-458e-11e7-9945-6a50e7ffb400.png)
![4](https://cloud.githubusercontent.com/assets/6723574/26618248/860958c4-458e-11e7-82ca-73c91765ea5b.png)

**Comment by louisgv** [comment]
> 3
![0](https://cloud.githubusercontent.com/assets/6723574/26618262/98928cf4-458e-11e7-99a6-aa8ce51d1543.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618263/98b69482-458e-11e7-856f-6e2d441efcb0.png)
![2](https://cloud.githubusercontent.com/assets/6723574/26618267/98c6efda-458e-11e7-8e00-6efaa5b3e89d.png)
![3](https://cloud.githubusercontent.com/assets/6723574/26618268/98c77cac-458e-11e7-8eb4-b4cabadc8388.png)
![4](https://cloud.githubusercontent.com/assets/6723574/26618264/98c3b784-458e-11e7-8957-196c8f13db23.png)
![5](https://cloud.githubusercontent.com/assets/6723574/26618265/98c3bf72-458e-11e7-9b31-8ce3d66897c2.png)
![6-0](https://cloud.githubusercontent.com/assets/6723574/26618266/98c51624-458e-11e7-99ae-f76cd7a786d3.png)
![6-1](https://cloud.githubusercontent.com/assets/6723574/26618269/98e90ae8-458e-11e7-80b9-f1d51fde2bf7.png)
![7](https://cloud.githubusercontent.com/assets/6723574/26618271/98ed017a-458e-11e7-92a6-ff42979c0b14.png)
![8](https://cloud.githubusercontent.com/assets/6723574/26618270/98ed105c-458e-11e7-8fca-d6ea4d4f3155.png)

**Comment by louisgv** [comment]
<details> 
  <summary> 4 </summary>

![0](https://cloud.githubusercontent.com/assets/6723574/26618262/98928cf4-458e-11e7-99a6-aa8ce51d1543.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618263/98b69482-458e-11e7-856f-6e2d441efcb0.png)
![2](https://cloud.githubusercontent.com/assets/6723574/26618267/98c6efda-458e-11e7-8e00-6efaa5b3e89d.png)
![3](https://cloud.githubusercontent.com/assets/6723574/26618268/98c77cac-458e-11e7-8eb4-b4cabadc8388.png)
![4](https://cloud.githubusercontent.com/assets/6723574/26618264/98c3b784-458e-11e7-8957-196c8f13db23.png)
![5](https://cloud.githubusercontent.com/assets/6723574/26618265/98c3bf72-458e-11e7-9b31-8ce3d66897c2.png)
![6-0](https://cloud.githubusercontent.com/assets/6723574/26618266/98c51624-458e-11e7-99ae-f76cd7a786d3.png)
![6-1](https://cloud.githubusercontent.com/assets/6723574/26618269/98e90ae8-458e-11e7-80b9-f1d51fde2bf7.png)
![7](https://cloud.githubusercontent.com/assets/6723574/26618271/98ed017a-458e-11e7-92a6-ff42979c0b14.png)
![8](https://cloud.githubusercontent.com/assets/6723574/26618270/98ed105c-458e-11e7-8fca-d6ea4d4f3155.png)

</details>

**Comment by louisgv** [comment]
<details> 
  <summary> 5 </summary>

![0](https://cloud.githubusercontent.com/assets/6723574/26618262/98928cf4-458e-11e7-99a6-aa8ce51d1543.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618263/98b69482-458e-11e7-856f-6e2d441efcb0.png)
![2](https://cloud.githubusercontent.com/assets/6723574/26618267/98c6efda-458e-11e7-8e00-6efaa5b3e89d.png)
![3](https://cloud.githubusercontent.com/assets/6723574/26618268/98c77cac-458e-11e7-8eb4-b4cabadc8388.png)
![4](https://cloud.githubusercontent.com/assets/6723574/26618264/98c3b784-458e-11e7-8957-196c8f13db23.png)
![5](https://cloud.githubusercontent.com/assets/6723574/26618265/98c3bf72-458e-11e7-9b31-8ce3d66897c2.png)
![6-0](https://cloud.githubusercontent.com/assets/6723574/26618266/98c51624-458e-11e7-99ae-f76cd7a786d3.png)
![6-1](https://cloud.githubusercontent.com/assets/6723574/26618269/98e90ae8-458e-11e7-80b9-f1d51fde2bf7.png)
![7](https://cloud.githubusercontent.com/assets/6723574/26618271/98ed017a-458e-11e7-92a6-ff42979c0b14.png)
![8](https://cloud.githubusercontent.com/assets/6723574/26618270/98ed105c-458e-11e7-8fca-d6ea4d4f3155.png)

</details>

**Comment by louisgv** [comment]
<details> 
  <summary> 6 </summary>

![0](https://cloud.githubusercontent.com/assets/6723574/26618262/98928cf4-458e-11e7-99a6-aa8ce51d1543.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618263/98b69482-458e-11e7-856f-6e2d441efcb0.png)
![2](https://cloud.githubusercontent.com/assets/6723574/26618267/98c6efda-458e-11e7-8e00-6efaa5b3e89d.png)
![3](https://cloud.githubusercontent.com/assets/6723574/26618268/98c77cac-458e-11e7-8eb4-b4cabadc8388.png)
![4](https://cloud.githubusercontent.com/assets/6723574/26618264/98c3b784-458e-11e7-8957-196c8f13db23.png)
![5](https://cloud.githubusercontent.com/assets/6723574/26618265/98c3bf72-458e-11e7-9b31-8ce3d66897c2.png)
![6-0](https://cloud.githubusercontent.com/assets/6723574/26618266/98c51624-458e-11e7-99ae-f76cd7a786d3.png)
![6-1](https://cloud.githubusercontent.com/assets/6723574/26618269/98e90ae8-458e-11e7-80b9-f1d51fde2bf7.png)
![7](https://cloud.githubusercontent.com/assets/6723574/26618271/98ed017a-458e-11e7-92a6-ff42979c0b14.png)
![8](https://cloud.githubusercontent.com/assets/6723574/26618270/98ed105c-458e-11e7-8fca-d6ea4d4f3155.png)

</details>

**Comment by louisgv** [comment]
<details> 
  <summary> 7 </summary>
![0](https://cloud.githubusercontent.com/assets/6723574/26618366/0c211ae6-458f-11e7-8ae5-6a536bea9b01.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618367/0c24e900-458f-11e7-971d-92c201acc490.gif)
![1](https://cloud.githubusercontent.com/assets/6723574/26618368/0c2aff3e-458f-11e7-9bc0-0349f58138ed.png)

</details>

**Comment by louisgv** [comment]
<details> 
  <summary> 8 </summary>

![0-0](https://cloud.githubusercontent.com/assets/6723574/26618514/75c16f6e-458f-11e7-8e9f-335db70f1b42.png)
![0-1](https://cloud.githubusercontent.com/assets/6723574/26618515/75d44288-458f-11e7-84b6-e34f077f0427.png)
![0-2](https://cloud.githubusercontent.com/assets/6723574/26618513/75c0d00e-458f-11e7-90d3-48fd0580e847.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618512/75bf9ee6-458f-11e7-8684-c8a76fefac39.png)

</detail>

**Comment by louisgv** [comment]
<details> 
  <summary> 8 </summary>

![0-0](https://cloud.githubusercontent.com/assets/6723574/26618535/8a182a7a-458f-11e7-9625-18086a875b0b.png)
![0-1](https://cloud.githubusercontent.com/assets/6723574/26618533/8a09fd42-458f-11e7-9cc8-93cf08c8d984.png)
![0-2](https://cloud.githubusercontent.com/assets/6723574/26618532/8a07ea98-458f-11e7-8348-8a018096eda8.png)
![1](https://cloud.githubusercontent.com/assets/6723574/26618536/8a19b5f2-458f-11e7-8ae6-777a4bcb9829.png)
![1-3](https://cloud.githubusercontent.com/assets/6723574/26618537/8a1bb65e-458f-11e7-85f8-8299a922e345.gif)
![4](https://cloud.githubusercontent.com/assets/6723574/26618534/8a0bf6e2-458f-11e7-9134-4a4e1b830a83.gif)
![5](https://cloud.githubusercontent.com/assets/6723574/26618538/8a201c9e-458f-11e7-8518-20ff53aed425.gif)


</details>

**Comment by louisgv** [comment]
<details> 
  <summary> 10 </summary>

![Uploading 0.gif…]()
![0](https://cloud.githubusercontent.com/assets/6723574/26618556/9d51cb8c-458f-11e7-9477-78251ca1a476.png)


</details>

**Comment by 5chdn** [comment]
Thanks for sharing them!
