### ISSUE TITLE
testing a wrong password and leaving it on it makes change password error (tries to use data from other field)

### ISSUE THREAD

**Issue by 3esmit** [paritytech/parity#5726]
I created a bunch of accounts, all without password, now I need to unlock all them, so I need to add a password to put in the password file.
Then I sometimes think I already set password to that account, so I first test it, it goes wrong, I try to change it to new password, but it fails.

**Comment by 5chdn** [comment]
How did you create accounts without password?

**Comment by 3esmit** [comment]
>How did you create accounts without password?
Just don't put any password and `Next ->`

**Comment by 5chdn** [comment]
Ah wow, that's an interesting find. Can reproduce now.

Changing password fails if wrong password is entered in "test password" field.

**Comment by 3esmit** [comment]
Indeed,, I was surprised of such bug and imagine that the same dataspace is being used for this check. And please, don't enforce passwords! I use no password for kovan because I don't want to type any password!

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
