### ISSUE TITLE
Parity stuck at submitting 

### ISSUE THREAD

**Issue by brbatv** [paritytech/parity#5735]
Hello
i tried to buy BAT with a block order
![image](https://cloud.githubusercontent.com/assets/22215204/26640579/6b8df69a-4628-11e7-867a-d6dc775c6b06.png)

now it's stuck for nearly an hour and the transaction is out of the blockchain : https://etherscan.io/tx/0x320398a325ae3a92204f2f63f7f452060c3d1c0d9469562647c53609a6449871

I noticed that when i refresh Parity (i'm on google chrome with extension), i have a little opportunity to click cancel before it turns into " Submitting" : 
![image](https://cloud.githubusercontent.com/assets/22215204/26640697/bb9b49da-4628-11e7-89e6-f992681cd9e8.png)

Should i cancel it ? Or anything else ? 
You help is very much appreciated, i fear for my money. 

Thank you for your attention

**Comment by brbatv** [comment]
Lol i accidentally pressed cancel, and that was the solution ... I feel so much better now

**Comment by mpolavieja** [comment]
I had the same problem.  I programmed a transactions two blocks before the BAT ICO and it didn´t go through until much later.  I could see the transactions as "pending" within signer tab.   The transactions were finally processed several hours later.   Quite disappointing.

**Comment by CraigglesO** [comment]
blocks during the BAT ICO was overloaded with transactions. People prepared for the ICO days in advanced and pushed really high gas prices to beat the competition. This is the limitation of the current Ethereum protocol and not Parity itself. All blockchains are looking for methodologies to reach visa level transactions per second, please bear with the engineers. ^_^

**Comment by xinmiqipei** [comment]
bull shit! why others block does not stuck?my parity does not sync at all during the ico!!

**Comment by CraigglesO** [comment]
http://www.coindesk.com/35-million-30-seconds-token-sale-internet-browser-brave-sells/
Someone payed over $6,000 in mining fees to participate.

ICO's can bogged down the transactions. And mining software by default chooses the transactions with the highest reward (biggest mining fees)

**Comment by xinmiqipei** [comment]
Forget the ICO, i means the block number does not sync sometimes. Not only during the  ICO rush time,but also happend in normal time. I have already change the setting to "parity continuosly syncs the chain",but it doesn't work.it seems more likely "Parity syns intially,then sleep and wakes regularly to resync."

**Comment by 5chdn** [comment]
The blocks were full for 7 hours. Next time you could try to increase the gas price.
