### ISSUE TITLE
Can't make any transactions with Parity

### ISSUE THREAD

**Issue by coyotito1** [paritytech/parity#5736]
I had this issue yesterday too, then it started working out of the blue.

Now, no transactions can be made, nothing happens!!

Can't reveal bids, can't make new bids... it just is stuck on "Bidding..." and when I refresh the page I need to do it all over again, but nothing ever happens.

The blockchain says I haven't made a transactions in a couple of hours: 0x004398361D0FAD60D7fCf5533D94398Ee9Fc8ddc

But in reality I've tried making like 50 different ones, I have tried editing the gas price and all the amounts but nothing.
![namnlos](https://cloud.githubusercontent.com/assets/29064203/26645467/640effbc-4638-11e7-8b4c-efb00d66c891.png)
![namnlo2s](https://cloud.githubusercontent.com/assets/29064203/26645519/8f8caedc-4638-11e7-819a-03632c096080.png)

Please help me resolve this....  I am genuinly scared I will lose a lot of ETH by not being able to reveal my bids on the ENS and so on.

Thank you!

**Comment by coyotito1** [comment]
![namnlos2](https://cloud.githubusercontent.com/assets/29064203/26645845/d64013f4-4639-11e7-9301-702dddbb52bd.png)

And I tried making a manual transfer to my friend's ETH address, it shows the above..... never confirming!! What is going on ??

**Comment by CraigglesO** [comment]
Do you mind sharing which version of parity you are using / which OS? It's clear you are on an older version though. Would you mind updating.

**Comment by hukkinj1** [comment]
The version is visible in his/her screenshot (bottom left corner). Seems to be v1.6.7 for Windows. I'm having similar issues using the same version number on Ubuntu, and trying to send ERC20 tokens. Seems like the transactions are never sent to the network (at least according to Etherscan.io).

**Comment by coyotito1** [comment]
Yes that is correct, 1.6.7 and Windows 10.

Still not working. Can't delete the stuck transactions (dont know how to?) and nothing happens when I try send any Ether (to any address).

**Comment by 5chdn** [comment]
The blocks were full for 7 hours. Next time you could try to increase the gas price.

Deleting transactions is possible with the upcoming 1.7 release. However, your transactions were already broadcasted, so they will be mined at some point.
