### ISSUE TITLE
Parity bug. Can not send anything out. Status shows (0 peers); restarting computer does not help.

### ISSUE THREAD

**Issue by vlady-m** [paritytech/parity#5737]
After attempt to participate in BAT ICO. Parity just stuck. Transactions are in the queue. After signing nothing gets broadcasted.
Status shows (0 peers)
Even restarting computer does not help.
Many experienced this problem now!
[ParityBug.docx](https://github.com/paritytech/parity/files/1042686/ParityBug.docx)
[ParityBug.docx](https://github.com/paritytech/parity/files/1042689/ParityBug.docx)

**Comment by xinmiqipei** [comment]
I'm stuck too.and the block does not sync for a long time !!

**Comment by 5chdn** [comment]
The blocks were full for 7 hours. Next time you could try to increase the gas price.
