### ISSUE TITLE
Synced Mist Wallet can't send 

### ISSUE THREAD

**Issue by gtrider** [paritytech/parity#5738]
I am new to this.  I have set-up Parity,  synced my mist wallet, but I can't seem to figure out how to send money from it?  There is no "send" button.  There is a note saying that there are no "owners" in the wallet but i cant figure out how to add an owner. 
Any help would be much appreciated!

**Comment by 5chdn** [comment]
Which Parity version are you using and how are you running it? Which operating system?

Are you using Mist on top of Parity? Which Mist version? Are you talking about a multisignature wallet? In Mist or Parity?
