### ISSUE TITLE
Generate recovery phrase for private key

### ISSUE THREAD

**Issue by Limeth** [paritytech/parity#5743]
I've added an account by importing a private key and now I would like to create a recovery passphrase for it.
Is that possible, maybe via the command line?

**Comment by rphmeier** [comment]
Private key is derived from the recovery phrase as a one-way operation, not vice-versa. That's why you can't get back the recovery phrase once you move beyond that page of account creation, even though your password gives you access to your private key.

**Comment by 3esmit** [comment]
Maybe would be interesting to have a warning at creation: "if you don't save this information now it will be lost".

**Comment by 5chdn** [comment]
@3esmit a similar feature is already in master afaik, can't find the pull request right now.
