### ISSUE TITLE
Latest Master Branch: Invalid Token - UI does display token modal

### ISSUE THREAD

**Issue by CraigglesO** [paritytech/parity#5745]
Blocked connection from http://localhost:8180 using invalid token.
even using `--ui-no-validation` or `--ws-origins all` I can't get the parity to work with the UI. No modal to give a valid token showing up.

**Comment by 5chdn** [comment]
Probably related to #5722 - should we track this in one ticket?

**Comment by tomusdrw** [comment]
It's fixed in #5710, let's track it as one.

**Comment by CraigglesO** [comment]
No, I'm sorry but I think this is a JS issue that has not been resolved even in your PR. I pulled it and I still got:
`Connecting to the Parity Node. If this informational message persists, please ensure that your Parity node is running and reachable on the network.`

**Comment by tomusdrw** [comment]
You need to build with `cargo build --release --no-default-features --features ui` cause it's indeed JS stuff that I broke and you need to recompile it as well.
