### ISSUE TITLE
How can I connect Parity to an other node and to an other blockchain ?

### ISSUE THREAD

**Issue by Nogreedy** [paritytech/parity#5753]
Hello,
I use Parity 1.6.7 .... and I appreciate it so much...
I use Parity (with web interface) on my Windows 10 PC (192.168.0.1) and it works very well (blockchain OK and synced)...
I use Parity Config Generator (config.toml) to set parameters...
but now I have a new Linux PC on my local network (192.168.0.2)... and I'd like to use Parity also on this new PC (to use MultiSig...) ... but this new PC has a slow HDD and I can't download blockchain on this new PC.
Is there a concrete way to connect this Linux PC to my Windows 10 PC (192.168.0.1) to use only one blockchain (node?) ?
What is the correct CLI commands and options (rpc or ipc options???) or Parity Config Generator parameters (config.toml) to use to connect to an other blockchain?
Thanks in advance for your answer.

**Comment by 5chdn** [comment]
On your Windows machine create a file `C:\reserved.txt` (or place it anywhere you like) with the following content, with only one line containing the full enode address of your Linux machine, but replace the IP with the LAN IP:

    enode:/....@192.168.0.2:30303

Do the same vice versa on your Linux machine `~/reserved.txt`:

    enode:/....@192.168.0.1:30303

And run Parity on Windows like `parity.exe --reserved-peers C:\reserved.txt` and on Linux `parity --reserved-peers ~/reserved.txt`. This way, both clients will try to keep a connection to each other. Hope this helps.
