### ISSUE TITLE
Apparent Babel show-stopper in Tutorial Part 1

### ISSUE THREAD

**Issue by nickwit** [paritytech/parity#5755]
Hi all

I'm trying the tutorial here:
https://github.com/paritytech/parity/wiki/Tutorial-Part-I

All good - but when I get to:

webpack

It didn't work (because it isn't installed). When I try to install it it says:

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1`

I don't know if that's important or not... but when I try to run webpack it says 

`ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/home/nick/mydapp'`

when I try to install babel-cli -g, I get the same warnings as above (I don't know if they're important or not), and still get 

`ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/home/nick/mydapp'`

when I try to run webpack

Any ideas as to what I need to do next?

**Comment by tomusdrw** [comment]
Try `npm install babel-loader --save`.

**Comment by 5chdn** [comment]
Actually, try to run `./init.sh` in `/skeleton` https://github.com/paritytech/skeleton/blob/master/init.sh

    npm i --save babel-core webpack webpack-dev-server
    npm i --save-dev babel-loader babel-preset-es2015 babel-preset-react
    npm i --save bignumber.js react react-dom
    npm i --save oo7 oo7-parity oo7-react parity-reactive-ui

Might be worth adding to the docs.

**Comment by nickwit** [comment]
Hello World !

Brilliant - thank you :)

**Comment by 5chdn** [comment]
Closing in favor of https://github.com/paritytech/skeleton/issues/4
