### ISSUE TITLE
parity / ff crash on windows

### ISSUE THREAD

**Issue by unknownhostname** [paritytech/parity#5761]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	parity.exe
  Application Version:	0.0.0.0
  Application Timestamp:	591dd7f9
  Fault Module Name:	parity.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	591dd7f9
  Exception Code:	c000001d
  Exception Offset:	0000000000a7e124
  OS Version:	6.1.7601.2.1.0.256.49
  Locale ID:	1033
  Additional Information 1:	dc18
  Additional Information 2:	dc18aafd27d0d96c6b47389ed0e48a11
  Additional Information 3:	0f3a
  Additional Information 4:	0f3aed1e7f73eec814fa96e781336498

**Comment by 5chdn** [comment]
Could you open a command prompt (`cmd`) and run Parity from there?

    > cd "C:\Program Files\Ethcore\Parity\"
    > parity.exe

And paste what you get during the crash here?

**Comment by unknownhostname** [comment]
C:\Program Files\Ethcore\Parity>parity.exe
2017-06-06 12:54:15  Starting Parity/v1.6.7-beta-e128418-20170518/x86_64-windows
-msvc/rustc1.17.0
2017-06-06 12:54:15  State DB configuration: fast
2017-06-06 12:54:15  Operating mode: passive
2017-06-06 12:54:15  Configured for Foundation using Ethash engine
2017-06-06 12:54:16  Updated conversion rate to ?1 = US$259.03 (459590050 wei/ga
s)
2017-06-06 12:54:24  Public node URL: enode://ad2b2954f8ee3d17a1d20f8c5bd18b0205
5fcfd6b94d52d6a7fca305e8eac950c95c4bfe5eabd9646c0c6f50703fe347d172e21698d38ffe5c
747182cc84be7d@127.0.0.1:30303
2017-06-06 12:54:35  Syncing #3821767 8fc5.d131     0 blk/s   16 tx/s   0 Mgas/s
      0+  118 Qed  #3821889    4/ 4/25 peers   130 MiB db  138 KiB chain    4 Mi
B queue 1021 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
thread 'IO Worker #0' panicked at 'DB flush failed.: "IO error: Failed to WriteF
ile: C:\\Users\\Unknown\\AppData\\Local\\Parity\\Ethereum\\chains\\ethereum\\
db\\906a34e69aec8c0d\\overlayrecent\\db/002141.sst: There is not enough space on
 the disk.\r\n"', src\libcore\result.rs:859
stack backtrace:
   0: hid_error
   1: hid_error
   2: hid_error
   3: hid_error
   4: hid_error
   5: hid_error
   6: hid_error
   7: hid_error
   8: hid_error
   9: hid_error
  10: hid_error
  11: hid_error
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: hid_error
  18: <unknown>
  19: <unknown>
  20: <unknown>
2017-06-06 12:54:41  Syncing #3821771 b46d.46d5     0 blk/s   41 tx/s   1 Mgas/s
      0+  622 Qed  #3822397    4/ 4/25 peers   130 MiB db  177 KiB chain   22 Mi
B queue  489 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

C:\Program Files\Ethcore\Parity>11a

**Comment by 5chdn** [comment]
Your disk is full. You might want to troubleshoot that first :)
