### ISSUE TITLE
Not all the tokens are displayed

### ISSUE THREAD

**Issue by JanKalin** [paritytech/parity#5765]
A minor annoyance: Not all tokens are displayed. I can see DGD and GNT, but not EMV (Ethereum Movie Venture, https://etherscan.io/address/0xb802b24e0637c2b87d2e8b7784c055bbe921011a). I can add it in the "Contracts" tab of Parity and check the amount by calling `balanceOf`. 

The token does show up in MEW and is supposedly an ERC20 token.

Is there somewhere a list of tokens that Parity scans?

**Comment by 5chdn** [comment]
Parity only displays tokens which are registered with the token registry dapp.

You can check the status in the wallet > applications > token registry and search for the token you are missing. If it's not there, go ahead and register it. All you need is the public token contract address, the numbers of decimals, and an icon.

**Comment by matt93310** [comment]
What if it doesn't work and I get the message "The address is not a regular token contract address"?

**Comment by JanKalin** [comment]
Could you share the address? 

What is probably happening is that the contract does not have the [standard ERC20 functions](https://theethereum.wiki/w/index.php/ERC20_Token_Standard), most importantly the `balanceOf` function that is used in Parity to check balances of accounts and addresses in the addressbook. If it doesn't have the `transfer` and `transferFrom` functions, it is also impossible to send tokens.

**Comment by 5chdn** [comment]
> What if it doesn't work and I get the message "The address is not a regular token contract address"?

You are either not fully synchronized or the total supply is 0.

**Comment by JanKalin** [comment]
Again nothing critical, but a token is not displayed properly. It is registered in the registry

![image](https://user-images.githubusercontent.com/18305372/33261472-251dc190-d363-11e7-9cd2-32bdb124ea2d.png)

but it doesn't show up in the wallet info:

![image](https://user-images.githubusercontent.com/18305372/33261548-5fa96de6-d363-11e7-892c-8900ba3f7e58.png)

or the smart contract info

![image](https://user-images.githubusercontent.com/18305372/33261592-7f8be602-d363-11e7-9dab-e7cc02851f84.png)

**Comment by 5chdn** [comment]
Parity version? Did you try to reset your browser cache yet?

**Comment by JanKalin** [comment]
Sorry for leaving this out: Parity//v1.8.1-beta-0e4a06d-20171020/x86_64-windows-msvc/rustc1.20.0
And I just cleaned browser cache.

The thing is, it *was* displaying properly when I added the token to the registry a few days ago.

**Comment by 5chdn** [comment]
I could dig through the changelog now, but please do me the favor and test if this is still an issue with our _latest_ release.

**Comment by JanKalin** [comment]
Was the same with the latest release. But, strangely, the token registry now showed that the image did not exist. So I re-added metadata. And now everything works as it should.

Although I did change the icon *after* I had entered a GitHub URL as metadata: https://github.com/JanKalin/misc/commit/5d04b3a52bb77af7d1be9a3049a1ead3b055f37d, https://github.com/JanKalin/misc/commit/09d6dfe8a1b86e0a1dbb2acc5f8387b23d00ce99 and https://github.com/JanKalin/misc/commit/aa5c7fda058a9366482c6cb682f506f8ac9dbd62. 

But I looked at the GithubHint contract at 0x27c41d20014fA87291006D02Ddd81B2128039BD7 and that should not matter? In any case, the two hints, 0x8858beaea897b989fc1a4f56206046296a96766d56943aa913c422368c7518ed (original, before icon change) and 0xed94649484312e7ef91cfc681de9c2817ad9f1ff12b7a5a3d757570be527014b (just not) point to exactly the same URL.

I'll let you know if the issue reappears.

**Comment by uberfounder** [comment]
Hey guys, 
First of all - Happy New Year! 
I have a quick question: I have just deployed a new token ERA with the total supply of 100,000,000,000 - then I have registered the token using the registry app and it shows up a 1,000.00. Have I messed something up with the number of decimals? 
Thanks!
Evgeni

**Comment by 5chdn** [comment]
If the balances are not correctly displayed - yes :)

**Comment by matt93310** [comment]
Hi all,
could you please stop copying me in this email chain.
My issue has long been resolved by the community and I thank everyone involved towards that outcome.
Mathieu

**Comment by 5chdn** [comment]
Just unsubscribe on Gihtub. We can not do that for you :)
