### ISSUE TITLE
Email verification does not work

### ISSUE THREAD

**Issue by lekanovic** [paritytech/parity#5769]
I have tried to use the email verification functionality in parity, but the problem is I never received the email with the confirmation code. 

OS: Ubuntu 14
Parity: 1.6.7

Please let me know if you need any other information.

**Comment by 5chdn** [comment]
@paritytech/ci could you look into this?

**Comment by eddiewang** [comment]
email and sms features don't work for me. 
I get a 'failed to get contract data'. Nodes are fully synced.
![image](https://user-images.githubusercontent.com/2057997/26947977-b84db3a4-4c62-11e7-83ee-fc1ad47faab2.png)

**Comment by ddorgan** [comment]
Hi Eddie,
           Can you confirm you are connected to the Mainnet (Foundation) when trying to do this. Could you maybe let us know what's on the bottom right of your browser. E.g. which network name/block number and amount of peers.

Thanks,
David

**Comment by eddiewang** [comment]
I was originally connected to HOMESTEAD but I switched to MAINNET using the --chain flag. The bottom displays MAINNET now and I have synced up to the latest blocks. Same error occurs.

**Comment by ddorgan** [comment]
Hi Eddie,

           Can you send a screenshot of the bottom right hand side of your screen. You should be connected to the main network and fully synced up.

Thanks,
David

**Comment by veeresh-hubballi** [comment]
<img width="1249" alt="screen shot 2017-11-05 at 11 46 37 pm" src="https://user-images.githubusercontent.com/3492187/32425803-c46feeda-c283-11e7-8336-9c6ddfdd14f0.png">

**Comment by 5chdn** [comment]
@veeresh-hubballi see #6859
