### ISSUE TITLE
Parity does not start, "CannotWriteVersionFile" error

### ISSUE THREAD

**Issue by ksharp77** [paritytech/parity#5770]
When attempting to start the Parity browser I immediately get the following error: "Error upgrading parity data: CannotWriteVersionFile". I have uninstalled and reinstalled parity and the issue remains.

**Comment by CraigglesO** [comment]
Which browser?
Which OS?

**Comment by ksharp77** [comment]
I am using Windows 10. I usually run it in Windows Edge or Google Chrome. Opening parity.exe and running parity through cmd both give me that error message. Trying to access Parity through the Chrome extension gives me this message: "You are not connected to a local Parity Node. Seamless integration with the Ethereum network is thus not available."

**Comment by 5chdn** [comment]
Could you post the full error message here?

**Comment by KingEyes** [comment]
I'm having the samy problem. (You are not connected to a local Parity Node. Seamless integration with the Ethereum network is thus not available). Any idea how to fix it?

**Comment by AdamAtlasAttorney** [comment]
same issue

**Comment by 5chdn** [comment]
Could you post the full error message here?

**Comment by unixfox** [comment]
I've the same error, here is the logs:
```
parity@vps:~$ /usr/bin/parity --config /home/parity/.local/share/io.parity.ethereum/configetc.toml
Loading config file from /home/parity/.local/share/io.parity.ethereum/configetc.toml
Error upgrading parity data: CannotWriteVersionFile
```

**Comment by thorstenhirsch** [comment]
There's no longer error message.
It happens when db_path is not writable, thus chains/ver.lock cannot be created.

**Comment by holiman** [comment]
Had this aswell -- I was running everything as root (it's an instance dedicated for this purpose only), and using the parity docker image. However, the parity client within the docker image does not run as root, so suddenly it could not write to it's own database.

**Comment by joshua-mir** [comment]
@holiman if you are having this issue now, it's probably more related to [this](https://github.com/paritytech/parity-ethereum/issues/9791#issuecomment-432109817)
