### ISSUE TITLE
parity signer new-token --> "No such file or directory"

### ISSUE THREAD

**Issue by clayt0nk** [paritytech/parity#5771]
Parity version 1.6.6 and it's UI in a web browser is working fine on one Debian machine. rsync'ed everything over to another Debian machine, same OS version but sligtly newer parity 1.6.7. Now pointing browser at http://localhost:8080/ results in "Unable to make a connection to the Parity Secure API. To update your secure token or to generate a new one, run parity signer new-token" etc.....

When I run parity signer new-token in a terminal, I get an error message with the text "No such file or directory".

There is no obvious way to get a more informative error message.

**Comment by tomusdrw** [comment]
Can you check if `~/.local/share/io.parity.ethereum/signer` exists? And let me know if inside this directory you can find `authcodes` file.

**Comment by clayt0nk** [comment]
Yep, both directory and file are present, no visible permission problems, and the time stamp on authcodes looks like earlier today when I was trying to authorize.

**Comment by tomusdrw** [comment]
Do you use a config file as well? What chain are you running?

**Comment by clayt0nk** [comment]
As far as I am aware everything is default, I neither created nor edited a config file, and whatever chain is running should be the default. I don't even know what chain options there are to choose from.

**Comment by tomusdrw** [comment]
Can you run `parity signer new-token -lsigner=trace`?

**Comment by clayt0nk** [comment]
Sadly, I think that just gave us one extra not-so-useful line:

$ parity signer new-token -lsigner=trace
2017-06-07 16:53:10  main TRACE signer  New authentication token generated.
Error generating token: Error { repr: Os { code: 2, message: "No such file or directory" } }

**Comment by tomusdrw** [comment]
@clayt0nk It gives some useful information actually. The file is readable, cause it loaded and managed to generate a new token, and the failure is caused when the file is being written to the disk. So the most obvious issue I can think of is that:
1. Parity is running as a different user then the command you just run
2. File permissions are read for both users but write only for that one.

Can you verify it?
```
ls -al ~/.local/share/io.parity.ethereum/authcodes
```

**Comment by clayt0nk** [comment]
Not sure what file it might be reading:

user@x220i:~/.local/share/io.parity.ethereum$ ll
total 4
lrwxrwxrwx 1 user user 22 Jun  6 13:23 chains -> /scratch/parity-chains
drwxrwx--- 1 user user  0 Jun  5 15:40 dapps
drwxrwx--- 1 user user 16 Jun  5 15:40 keys
drwxrwx--- 1 user user  6 Jun  6 09:15 network
drwxrwx--- 1 user user 18 Jun  6 09:15 signer
user@x220i:~/.local/share/io.parity.ethereum$

"user" is the userid running parity, both the daemon and the signer. Just for thoroughness, root seems the same thing:

root@x220i:~# ll /home/user/.local/share/io.parity.ethereum/
total 4
lrwxrwxrwx 1 user user 22 Jun  6 13:23 chains -> /scratch/parity-chains
drwxrwx--- 1 user user  0 Jun  5 15:40 dapps
drwxrwx--- 1 user user 16 Jun  5 15:40 keys
drwxrwx--- 1 user user  6 Jun  6 09:15 network
drwxrwx--- 1 user user 18 Jun  6 09:15 signer
root@x220i:~# 

All that said, I not a normal user, I am a security-paranoid user, and I just had an idea about what might be going on. Let me try something else and get back to you a little later.

**Comment by tomusdrw** [comment]
It's trying to read `authcodes` file inside `signer` directory, can you also check permissions there?

**Comment by clayt0nk** [comment]
That looks good too, I think:

user@x220i: $ ls -al ~/.local/share/io.parity.ethereum/signer/authcodes 
-rw------- 1 user user 77 Jun  6 14:35 /home/user/.local/share/io.parity.ethereum/signer/authcodes
user@x220i:~$

**Comment by clayt0nk** [comment]
So I think I know what is happening, but not why.....

I take some extra-ordinary precautions. I have two main user accounts on my desktop, let's call them (for descriptive purposes) "secure" and "insecure". Secure is where my PGP keys and password database are located (for instance) and more to the point, my cryptocurrency wallet keys. Therefore wallets must be run as the "secure" user, as that is where the keys are (readable only by the "secure" user and root).

I usually login to my desktop as the "insecure" user, and under "insecure" I run, well, insecure applications: all web browsers, podcasters, video/audio players, etc.... Basically everything I have not specifically designated a "secure" application. While logged in as "insecure", if I want to use a "secure" application (like parity, for instance) I su (or ssh -X) in a terminal to "secure" and run the secure application in that terminal. That was precisely the scenario that was failing.

Just now I logged into "secure" directly from the desktop, started parity, and then ran "parity signer new-token" not only as the "secure" user, but also under a "secure" desktop session. That finally worked, and the token generated worked in a browser (running under "insecure", I might add).

So it looks like I am in, but something about "parity signer new-token" cannot handle my corner case, while the main parity daemon can: from the status screen, it looks like it is reading the chaining fine, and adding to it starting from yesterday afternoon.

**Comment by tomusdrw** [comment]
Great that you figured it out. Maybe the issue is that the file is already opened by "secure" process and that's why the "insecure" one cannot write to it at the same time?

**Comment by clayt0nk** [comment]
https://www.techwalla.com/articles/how-to-switch-users-in-a-linux-shell

"su - user" (note the addition of a dash) works, "su user" (what I usually do) does not. So it is the difference in environment variables that is tripping up parity signer but not the parity daemon, I think. It has been so long since the last time I ran into this, I think most applications must be hardened to be able to handle if environment variables are not right.
