### ISSUE TITLE
Allow registry lookup in "add saved address" on addressbook tab

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5776]
I'd suggest that the field "network address" behaves like the "recipient address" field in transfers.
cc @fabiangmpf

**Comment by 5chdn** [comment]
What's the point of adding a known address to parity? Just trying to wrap my head around this special case.

**Comment by bjornwgnr** [comment]
Because this allows one to save _registered_ addresses under a (more memorable) alias. E.g. ngotchac -> Nicolas. I also fail to see any real downside of adding it.
