### ISSUE TITLE
getTransactionreceipt returns null for some transaction on ETC blockchain

### ISSUE THREAD

**Issue by miningpoolhub** [paritytech/parity#5779]
Hi
I'm currently running ETC with Parity/v1.4.10-stable-4e6329a-20170118/x86_64-linux-gnu/rustc1.15.0

At block 3862300,
Calling eth_getTransactionReceipt to 0x0e914f05f01f3aa28c092bd1140094dffc32917a06352517ff0e96aa396ce901
returns null which should give some valid value.

gastracker also outputs error on viewing 3862300 block.
http://gastracker.io/block/3862300
( http://gastracker.io/block/3862301 works well. Seems like gastracker is using parity behind )

I can explore that block from etcchain block explorer.
https://etcchain.com/block/number/3862300

0x0e914f05f01f3aa28c092bd1140094dffc32917a06352517ff0e96aa396ce901
transaction has 0 amount transfer.
I think this caused some bug retrieving eth_getTransactionReceipt.

**Comment by splix** [comment]
I can confirm this issue. It seems that Parity calculates tx hash incorrectly for some of the transactions.

For example block `0x5a27889310c457b3c3bf7739ffa7d6c5a463b104255fe39390f564b704319249`. For Parity eth_getBlockByHash RPC returns following transactions: 
```
"transactions": [
	"0xe608e8c84c5a6ff3338a0b240e6ef500e54fcf75ce38a54790388c4ddbf5435c",
	"0xa9a1571663a7f2682d753a71180985b69c9283294bae009cc237136e6c254919"
],
"transactionsRoot": "0x3b4823d87c253eb22261b4fed467b32df7a8cd91079d4bf753e6e9f86184e8a1"
```

But Geth gives:
```
"transactions": [
	"0xe608e8c84c5a6ff3338a0b240e6ef500e54fcf75ce38a54790388c4ddbf5435c",
	"0x241901a9a7d64f1b8e157afc6659f97a2f40b5146d27b5f820d018773ab506b7"
],
"transactionsRoot": "0x3b4823d87c253eb22261b4fed467b32df7a8cd91079d4bf753e6e9f86184e8a1"
```

If you try to fetch tx data for tx `0xa9a1571663a7f2682d753a71180985b69c9283294bae009cc237136e6c254919` by using eth_getTransactionByHash RPC it returns `null`. But both works for `0x241901a9a7d64f1b8e157afc6659f97a2f40b5146d27b5f820d018773ab506b7`

```
{"jsonrpc":"2.0",
 "method":"eth_getTransactionByHash",
"params":["0x241901a9a7d64f1b8e157afc6659f97a2f40b5146d27b5f820d018773ab506b7"],"id":1}
```
Parity returns:
```
{
	"jsonrpc": "2.0",
	"result": {
		"blockHash": "0x5a27889310c457b3c3bf7739ffa7d6c5a463b104255fe39390f564b704319249",
		"blockNumber": "0x3ad4cf",
		"hash": "0xa9a1571663a7f2682d753a71180985b69c9283294bae009cc237136e6c254919",
```

Notice that JSON output has invalid value for _hash field_.

Can reproduce with Parity 1.5.2 and 1.5.12. Chain resync didn't fix the issue

**Comment by arkpar** [comment]
Fixed in 1.6.8. A re-sync is required.

**Comment by splix** [comment]
@arkpar is there any plans to release a stable release with that fix?

**Comment by arkpar** [comment]
@splix The fix is in the `stable` branch, but we'll probably release 1.7 and stabilize 1.6 sooner instead.
