### ISSUE TITLE
Parity on Macbook Pro Safari Version 10.1.1 (12603.2.4)

### ISSUE THREAD

**Issue by BluBeast** [paritytech/parity#5780]
Cannot get Parity to work properly on Safari.  I got it to set up, sync, load some ETH, but it will not allow me to access anything but my account...cannot access settings, transfer, etc.  Home brew is installed.

**Comment by CraigglesO** [comment]
The best browser to use is Chrome, I highly suggest it. Sometimes Firefox will have issues with parity as well. Fixes are in the works.

Let us know if Chrome fixes your problems ^_^

**Comment by 5chdn** [comment]
@BluBeast could you clarify what your exact issue is? Or maybe provide a screenshot? Why can't you access settings in Safari?

**Comment by BluBeast** [comment]
Thanks for getting back so quickly.  I am stuck trying to sync in Safari and am not sure how to get Parity to install inside Chrome. Perhaps the issue is that the nodes need to sync fully except that I am not seeing any updated nodes or blocks.  I have disabled anti-virus, anything that blocks java or ads, no VPN, tried to install through command line and ended up rolling back to my original install (Parity zip package for OS X).  It just spins at the account window. See screenshot.  
<img width="1271" alt="screen shot 2017-06-07 at 09 28 59" src="https://user-images.githubusercontent.com/19832715/26889819-3a77a790-4b64-11e7-9a40-85e34d9574eb.png">

**Comment by CraigglesO** [comment]
You're synced. It would specify next to "HOMESTEAD" with a sync and blocks. But it already says you are at best block. This is good.

if you install parity like so:
1) `curl https://sh.rustup.rs -sSf | sh`
2) Than open terminal `CMD+space -> terminal` or find it in applications.
3) open chrome and in the top address bar type: `localhost:8180`

This all could easily be a browser issue, as it seems parity is running fine.

Please try this and get back to us.

**Comment by BluBeast** [comment]
I picked up a Lenovo laptop this afternoon and installed Parity after adding my VPN.   It loaded in about 15 seconds and worked flawlessly.  My Mac, although brand new, was locked down with security and just wasn't suited for Parity.  Thanks a lot for your directions.  I'll see if I can get OSX to loosen it's grip.

**Comment by CraigglesO** [comment]
<3 glad to hear! Have fun.
