### ISSUE TITLE
Slow calls after large number of empty blocks

### ISSUE THREAD

**Issue by MasX** [paritytech/parity#5788]
Parity `v1.6.6-beta` and `v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0`
Web3, both ipc (with `geth attach`) and http (node.js module).

Issue: calls get very slow after sealing 10k+ empty blocks, speed up again after a mined transaction. Calls take 1.3s after 85k empty blocks, after a new transaction only 25ms.
The call I have been using reads a `string public` variable from a contract (created >80k blocks before). `getBalance` call is not affected by slowness.

Reproduce: 
PoA genesis: 
```
"engine": {
    "authorityRound": {
      "params": {
        "gasLimitBoundDivisor": "0x400",
        "maxCodeSize": 98304,
        "stepDuration": "1",
        "validators" : {
          "list": [
            "0x0000"
          ]
        }
      }
    }
"params": {
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1999999999999998",
    "networkID" : "0x76C"
  },
  "genesis": {
    "seal": {
      "authorityRound": {
        "step": "0x0",
        "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    "difficulty": "0x20000",
    "gasLimit": "0x1999999999999998"
  },
``` 
config: 
`reseal_on_txs = "none"`
`force_sealing = true`.

Stepsize 1 is not a necessity, works with 10 too. Being a sealing node is not necessary to encounter slowness, nor is being a sealing node necessary to 'benefit' from speeding up again when a transaction is processed by another node.

**Comment by debris** [comment]
I believe I fixed a relevant cache problem some time ago. Please try the latest version of parity an reopen if still occurs
