### ISSUE TITLE
Failed build nanomsg (alpine linux)

### ISSUE THREAD

**Issue by General-Beck** [paritytech/parity#5794]
https://gitlab.parity.io/parity/parity/builds/57035

**Comment by Vurich** [comment]
This is because the `gcc` crate requires a minimum of `cc` to be in the path as a build-time dependency, but as Alpine just uses busybox it has no `cc` installed by default. My vote is for won't fix, we can put clang or gcc as a dependency in the aport.

**Comment by arkpar** [comment]
Looks like nanomsg build config needs updating for `musl` support. It needs to use `musl` version of `getaddrinfo` instead of `getaddrinfo_a` from `libanl`. Other C/C++ dependencies might need updating to enable `musl` support as well.

**Comment by andresilva** [comment]
We no longer depend on `nanomsg`. I was able to build and run parity on alpine using this Dockerfile (https://gist.github.com/andresilva/ea8c77edcb66f646f298f281b973e4ec).
