### ISSUE TITLE
Crash when using --force-sealing

### ISSUE THREAD

**Issue by SeanBannister** [paritytech/parity#5803]
I'm new to parity so I don't have any debugging knowledge.

When I run Parity with `--force-sealing` parity crashes as soon as it tries to process any transaction. The following error is shown:
`thread '<unknown>' has overflowed its stack`

I'm running Windows 8.1.

The exact command I'm running is:
`parity.exe --geth --force-ui --chain dev --force-sealing`
Removing `--force-sealing` the command runs fine.

I'm not 100% sure I need this command, just trying to get a testing environment going.

**Comment by keorn** [comment]
There is no need for `--force-sealing` for `--chain dev`. What Parity version are you using?

**Comment by SeanBannister** [comment]
Thanks keorn, I'm running: v1.6.8-beta-c396229-20170608/x86_64-windows-msvc/rustc1.17.0

The reason I was trying to use `--force-sealing` is when I submitted a transaction the UI said it still required more confirmations, if I submitted another transaction it would cause the confirmation count to increase. I know there must be a way to get parity to continue to perform confirmations and I presumed this was it?

**Comment by keorn** [comment]
There is no need to wait for additional confirmations, this only applies to the public network where you can get chain reorganisations.

**Comment by guanqun** [comment]
Should we simply add a check to reject the combination of these two options?

**Comment by keorn** [comment]
Would be great, it's a rather simple fix. Dev chain has `reseal_min_period` set to 0 [here](https://github.com/paritytech/parity/blob/master/parity/configuration.rs#L335). `--force-sealing` should not be allowed whenever it's 0.
