### ISSUE TITLE
Ability to get new token from the tray apps.

### ISSUE THREAD

**Issue by keorn** [paritytech/parity#5806]
Right now if someone wants to use a different browser, they have to use the CLI which is not easy for some.

**Comment by tomusdrw** [comment]
Should probably be implemented in the UI and the tray app should just open a proper page.

**Comment by 5chdn** [comment]
Or just chose the browser which opens the UI from tray, i.e., Open With > Internet Explorer 6

**Comment by 5chdn** [comment]
No more tray soon.
