### ISSUE TITLE
No hash rate displayed for Stratum or parellel mining

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#5807]
Re-posted from: https://github.com/paritytech/parity-ui/issues/118 & https://github.com/paritytech/parity-ui/issues/119

- [ ] When connecting miners to stratum proxy the hashrate is not displayed in the UI.
- [ ] When parallel miners are using RPC the hashrate is displayed incorrectly (seems that one might be more tricky)

**Comment by NikVolf** [comment]
Well stratum protocol contains nothing about submitting hashrate to the client

**Comment by tomusdrw** [comment]
I see, also tracking individual miners in RPC might not really be possible unless they send some kind of id.
I will have a quick look and if it's tricky we can close the issue.

**Comment by NikVolf** [comment]
There is a method to send very easy job first and evaluate how quickly stratum miners will solve it, deducing their hashrate from it. It's far from trivial, but we can keep issue open.

**Comment by micwebnet** [comment]
Benchmarking on warm-up is a good step to assess stratum miners, but folks mining still want to monitor hash rates of their distributed solo mining effort. 

Stratum being a push protocol, it knows when the work is sent and knows when the response is returned. Is that not enough to compute hashrate?

**Comment by NikVolf** [comment]
@micwebnet 

With solo mining, the responses on real network difficulty are rare. Expected time between responses from a single GPU are measured in days, and you need at least few samples.

**Comment by micwebnet** [comment]
My understanding was that with multiple miners all mining against the same Ethereum pure node (e.g. parity), the work gets split up across them, thus increasing mining hash rate. Does that help? Getting a historical read is still better than no read, even if it's a daily one. We miners are in this for the long haul)

**Comment by tomusdrw** [comment]
Just realized it's a duplicate of #1987
