### ISSUE TITLE
wiki: Wrong path for nodes file

### ISSUE THREAD

**Issue by zeenix** [paritytech/parity#5814]
The [FAQ says](https://github.com/paritytech/parity/wiki/FAQ#what-can-i-do-when-parity-has-trouble-getting-in-sync):

> Remove your nodes file ($HOME/.local/share/io.ethereum.parity/network/nodes.json) while Parity is not running.

However the correct path seems to be: `$HOME/.local/share/io.parity.ethereum/network/nodes.json` . The difference being` io.parity.ethereum` vs `io.ethereum.parity`.

**Comment by 5chdn** [comment]
Well spotted, thanks.
