### ISSUE TITLE
Tutorial feedback : webpack --watch issues

### ISSUE THREAD

**Issue by nickwit** [paritytech/parity#5815]
Hi all.

I'm working through the tutorial here:

https://github.com/paritytech/parity/wiki/Tutorial-Part-II

And have run into a bit of a snag. 

I've run:

**sudo npm install --save oo7 oo7-react**

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN babel-loader@7.0.0 requires a peer of babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc but none was installed.
```
I've seen the first to warnings before... not the 2nd one though. Not sure if this is a problem.

Then

**npm start** 

appears not to work - finishing with a request for the log file - which is:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle skeleton@0.1.5~prestart: skeleton@0.1.5
6 silly lifecycle skeleton@0.1.5~prestart: no script for prestart, continuing
7 info lifecycle skeleton@0.1.5~start: skeleton@0.1.5
8 verbose lifecycle skeleton@0.1.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle skeleton@0.1.5~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/nickwit/mydapp/node_modules/.bin:/home/nickwit/bin:/home/nickwit/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle skeleton@0.1.5~start: CWD: /home/nickwit/mydapp
11 silly lifecycle skeleton@0.1.5~start: Args: [ '-c', 'webpack-dev-server --content-base build' ]
12 info lifecycle skeleton@0.1.5~start: Failed to exec start script
13 verbose stack Error: skeleton@0.1.5 start: `webpack-dev-server --content-base build`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid skeleton@0.1.5
15 verbose cwd /home/nickwit/mydapp
16 error Linux 4.4.0-78-lowlatency
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error skeleton@0.1.5 start: `webpack-dev-server --content-base build`
24 error spawn ENOENT
25 error Failed at the skeleton@0.1.5 start script 'webpack-dev-server --content-base build'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the skeleton package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     webpack-dev-server --content-base build
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs skeleton
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls skeleton
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```

I've upgraded node - running

node -v

gives v8.0.0

but the log file shows that an old version is still being used.

Does anyone know how to get it to use the new version - if this is in fact the problem?

...........................

(Sorry - bad title. I also tried to run **webpack --watch** to no avail, but I suspect there is a problem in the previously run code

Webpack -watch hangs on:

```
WARNING in ../~/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
```

)

**Comment by CraigglesO** [comment]
If you don't mind, can you change branches:
`git checkout jr`
and then:
`npm install`
and lastly:
`npm start`

And tell me if you still have problems?

As for `iconv-loader.js` that might still be a problem in the jr branch and I can walk you through that as well.

**Comment by nickwit** [comment]
Is there something else that I need to do with 

**git checkout jr**

?

- it says:

`error: pathspec 'jr' did not match any file(s) known to git.`

**Comment by CraigglesO** [comment]
Hmm, I just tested it again, no issues.
try over:
`git clone https://github.com/paritytech/skeleton mydapp`
`cd mydapp`
`git checkout jr`

As for the master branch,
you did `./init.sh` command before npm start, correct?

**Comment by nickwit** [comment]
I didn't do **./init.sh** - I'm just following the commands in the tutorial.

If I do that before **npm start** it is a whole lot mor encouraging.

What it gives now are successful (I think) compile messages, followed by

```
WARNING in ./~/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
webpack: Compiled with warnings.
```

I'm not sure what it's supposed to do next - it's not returning to a command line... looks like it's stuck?

If I try to load the dapp, ( http://127.0.0.1:8180/#/app/mydapp ) it returns a blank screen.

I haven't changed the branch... should I still try this? - given that it might just have been the **./init.sh**  that was missing?

**Comment by CraigglesO** [comment]
👍 That's good. You should still try moving to the jr branch if you are still having issues. I wanted to recreate that same issue, but I think its because you have v8 of node (you're using Linux I am assuming) and it's a depreciated package. I think you can either `webpack --watch` or try the other method.

**Comment by nickwit** [comment]
WAY HEY!!!!

I tried branching it and it worked :)

Thank you very much - I am most pathetically grateful :)
