### ISSUE TITLE
Signer default account only allows first 10 accounts to be selected

### ISSUE THREAD

**Issue by jorisbontje** [paritytech/parity#5816]
When switching the default account in the Signer, only 10 accounts can be selected (the 10 oldest by the looks of it). Instead I'd like to be able to select any of my accounts.

Parity//v1.6.7-beta-e128418-20170518/x86_64-macos/rustc1.17.0

**Comment by tomusdrw** [comment]
Perhaps just the scroll is missing?

**Comment by jorisbontje** [comment]
Screenshot (note that if it was just a missing scroll, I'd think that the bottom left and bottom right UI positions would also be filled):
![screenshot 2017-06-12 13 46 32](https://user-images.githubusercontent.com/620959/27032674-54af8860-4f76-11e7-84f7-93c450a61869.png)

**Comment by tomusdrw** [comment]
You're right. I think the issue might be that the other accounts are in general not whitelisted.
Can you go to `Applications -> Permissions` and check if all of them is whitelisted there?

There is a separate issue to fix this: https://github.com/paritytech/parity/issues/5468

**Comment by jorisbontje** [comment]
Correct, when I whitelist the accounts per `Applications -> Permissions` it does allow me to select them in the signer.

**Comment by tomusdrw** [comment]
Ok, closing as duplicate then. Thanks for a detailed report!
