### ISSUE TITLE
Account export filename should default to pub address

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5818]
Imo, the default filename for the account export function through the UI should be set to the pub address (or alternatively to the Account Name; this can be problematic though since special characters are allowed in our UI). The UUID has no meaning to the user and the UUID filename could confuse the user as it is (also) hex encoded.

**Comment by 5chdn** [comment]
I 'think' this is a privacy feature not exposing the public address. But it would be an idea to allow the account name as file name.

**Comment by bjornwgnr** [comment]
I'm only talking about exporting accounts from the UI, not about the naming convention for key files stored in the parity keys folders.

Besides, I'm interested to learn how much more secure it is containing the pub address in cleartext only  inside the key file than having it also in the key file name itself.
