### ISSUE TITLE
Parity browser does not sync to blockchain "Network: unknown" Mac OSX

### ISSUE THREAD

**Issue by Hogue** [paritytech/parity#5823]
I downloaded the mac osx package instead of using homebrew and I can't get the browser to sync with the blockchain or even connect. When I go into "Status" it says that the network is "unknown" and in the bottom right hand corner of the browser it reads "0/0 syncing(UNKNOWN)0/0/25 peers".

Is there some kind of configuration I am missing? I am also using a Mist wallet so I'm not sure if that is conflicting with Parity's ability to connect to the blockchain.

Thanks for the help.

Here's an image for reference, 

<img width="1499" alt="screen shot 2017-06-12 at 2 27 41 pm" src="https://user-images.githubusercontent.com/11980767/27048844-5b69003c-4f7b-11e7-8b4c-4ecd5850bce1.png">

**Comment by zpv** [comment]
Make sure no other wallet applications are running, including Mist.

**Comment by 5chdn** [comment]
Are you running Parity via launchtl? Or manually? Do you use a config file?

Also, do you have Parity installed via brew and the installer package?
