### ISSUE TITLE
Deposit stock

### ISSUE THREAD

**Issue by wirdum** [paritytech/parity#5828]
I have send ether from mew to parity but after 3 hours is still not there. I wanted to join Bancor but that failed.
Somebody any suggestions?? Do I need to restore everything or is there a chance I lose everything then?
I just created my parity wallet. Are there some things you have to do to activate it before first transactions? Verify or something else??
IN MEW its confirmed

**Comment by 5chdn** [comment]
make sure you are fully synchronized before checking balances. what does the footer status say (or the status page)?
