### ISSUE TITLE
Parity UI (web3 console) says connection refused

### ISSUE THREAD

**Issue by ke-shen** [paritytech/parity#5829]
Checked firewall and specifically allowed port 8080 for all connections, checked antivirus, also it used to work. 

On chrome it says "ERR_CONNECTION_REFUSED"

Error happens when it ry to connect to Parity through 127.0.0.1:8080

**Comment by 5chdn** [comment]
Which version is that? How are you running Parity? The wallet UI is located on port 8180 btw.

**Comment by ke-shen** [comment]
Simple error, I was running parity with the --geth note attached to the
shortcut, I did this initially to get eth wallet synced but now i decided
to use the parity client instead.
