### ISSUE TITLE
Transactions won't send

### ISSUE THREAD

**Issue by JohnJ2** [paritytech/parity#5831]
Transactions won't send.  Do I need to wait for synching to complete before they will show?  Synching is really slow.

**Comment by 5chdn** [comment]
Which operating system are you using? Which version of Parity? Are you fully synchronized?

Warp sync is enabled by default and should get you to the latest block within a few minutes. If that's not the case, you would have to provide more details (logs, status, etc.), so we can troubleshoot your setup.

Transaction sending is independent from your sync status, also there is a difference between transactions not being _sent_ and transactions not being _mined_. Could you use the TX QUEUE application to review your pending transactions and check how many peers have seen your transaction yet?
