### ISSUE TITLE
Bonds not work in Safari and IE

### ISSUE THREAD

**Issue by LiJinyao** [paritytech/parity#5832]
Hi, I have problem with Bonds in front end. I followed the wiki to build my own front end. First I display the blockchain height with the following code:
```
<Rspan>height: {bonds.height}</Rspan>
```
in Chrome it works well and shows:
```
height: 0
```
but in Safari and IE11 it not shows the number:
```
height: 
```
I try log the value `bonds.height.tie(console.log)`, Chrome out put is:
```
0
```
 Safari and IE11 is:
```
[object Object]{_a: undefined, _c: Array[0], _d: false, _h: 0, _n: false, _s: 0, _v: undefined}
```
it seams the output is varies in different browsers.

**Comment by gavofyork** [comment]
sorry it's not well tested amongst browsers yet. i guess there is some crazy JS incompatibilities. feel free to track the bug down further and let me know if it's something that can be easily fixed.
