### ISSUE TITLE
Can't send GNT anywhere

### ISSUE THREAD

**Issue by cckelly21** [paritytech/parity#5834]
I am trying to send GNT to an ETH address, selecting GNT as the "type of token transfer" but it keeps showing the transaction amount in ETH and gives me "the transaction total is higher than the available balance". I originally thought this was because I had 0 ETH in the account, but I just moved a very small amount to it and I still get the same problem. Any ideas here? Let me know if you need more info.

**Comment by 5chdn** [comment]
Is this a normal account or a contract wallet? 

Just to give you a hint, to transfer GNT out of your account you would require the following amount of ETH for transaction fees at 4GWei gas price:

    62218 * 4000000000 / 1e18 ETH = 0.000248872 ETH

However, if you are using a contract wallet, it could be related to this issue: #5658

If it's a normal account, we need to investigate further.

**Comment by cckelly21** [comment]
I found the problem, I transferred .0005 ETH to that wallet which rounded up to .001 ETH so when I had a tx amount of around .0006 ETH I thought I had enough but didn't. I transferred some more over and it went through, apologies for the confusion. Might be a good idea to make the rounded number more precise.
