### ISSUE TITLE
[-32023] Error signing transaction with hardware wallet SNGLS

### ISSUE THREAD

**Issue by Yuripetusko** [paritytech/parity#5835]
Hello.

I am on 1.6.8 beta version on OSX

trying to transfer SNGLS from my Ledger Nano S, when clicking confirm on transaction inside of Parity I get this errror `[-32023] Error signing transaction with hardware wallet`

**Comment by Yuripetusko** [comment]
![screenshot 2017-06-13 23 39 06](https://user-images.githubusercontent.com/666169/27107773-d0c435a6-5091-11e7-846f-8fc6260e4940.png)

**Comment by Yuripetusko** [comment]
Found the solution. I had to turn on Contract mode, then disconnect ledger, then reconnect it back, and only then it would allow me to send tokens

**Comment by 5chdn** [comment]
probably related: #5652
