### ISSUE TITLE
My parity is not sync

### ISSUE THREAD

**Issue by panicape** [paritytech/parity#5837]
It stops and it doesn't want to start again and says this:
parity -l sync=trace
2017-06-14 11:19:00  main INFO parity::run  Starting Parity/v1.6.6-beta-8c6e3f3-20170411/x86_64-linux-gnu/rustc1.16.0
2017-06-14 11:19:00  main INFO parity::run  State DB configuration: fast
2017-06-14 11:19:00  main INFO parity::run  Operating mode: passive
2017-06-14 11:19:00  main INFO ethcore::service  Configured for Foundation using Ethash engine
2017-06-14 11:19:01  hyper-client INFO miner  Updated conversion rate to Ξ1 = US$388.84 (306160930 wei/gas)
thread 'main' panicked at 'failed to update version: "Corruption: block checksum mismatch"', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x559ddb78790c - <unknown>
   2:     0x559ddb78edfe - <unknown>
   3:     0x559ddb78ea04 - <unknown>
   4:     0x559ddb78f29b - <unknown>
   5:     0x559ddb78f134 - <unknown>
   6:     0x559ddb78f059 - <unknown>
   7:     0x559ddb78efe7 - <unknown>
   8:     0x559ddb7bbcdd - <unknown>
   9:     0x559ddb1c9268 - <unknown>
  10:     0x559ddb2fce58 - <unknown>
  11:     0x559ddb2c9ed8 - <unknown>
  12:     0x559ddb2f9b32 - <unknown>
  13:     0x559ddae5038b - <unknown>
  14:     0x559ddae6f828 - <unknown>
  15:     0x559ddae767aa - <unknown>
  16:     0x559ddae79475 - <unknown>
  17:     0x559ddb795ebb - <unknown>
Abortado (`core' generado)

**Comment by 5chdn** [comment]
Your database is corrupted. The easiest way is to resync. Just run

    parity db kill
    parity

And you should be back to normal within a few minutes. By the way, you might want to upgrade to 1.6.8 soon.

**Comment by panicape** [comment]
i usually do that but sometimes i do resync and it do it again...
Now it is working ok but is it any way to avoid this corruption? anyway...
Also, how can i upgrade it to 1.6.8?

**Comment by 5chdn** [comment]
How did you install it? Usually the same procedure. If you are on linux, try

    bash <(curl https://get.parity.io -Lk)

**Comment by panicape** [comment]
i downloaded the .deb installer and execute it.
i just have to execute it again or i have to unistall de previous one??

**Comment by panicape** [comment]
ok, thanks, i'm going to do it
