### ISSUE TITLE
Tutorial feedback : 'Undefined' when attempting to get blockchain info

### ISSUE THREAD

**Issue by nickwit** [paritytech/parity#5844]
Hi All.

I've gotten to page 3 of the tutorial here:

https://github.com/paritytech/parity/wiki/Tutorial-Part-III

It might be an idea to have an example of the entire file **app.jsx**

I've replaced the App class... and now have

```
import React from 'react';
import {Bond, TimeBond} from 'oo7';
import {TextBond, Rspan} from 'oo7-react';
import styles from '../style.css';

export class App extends React.Component {
	render() {
		return (
			<Rspan>{parity.bonds.height}</Rspan>
		);
	}
}
```

I'm fairly sure I don't need 2 and 3 of those import lines... but have left them in in case. 

Whey I run it though, it simply says "undefined".

Any clues, miuch appreciated.

**Comment by nickwit** [comment]
Am still stuck

If I look at the console in Developer Tools (Chrome) it says:

`Invalid 'X-Frame-Options' header encountered when loading 'http://127.0.0.1:8080/mydapp2/': 'ALLOW-FROM http://127.0.0.1:8180' is not a recognized directive. The header will be ignored.
bundle.js:1327 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
printWarning @ bundle.js:1327
warning @ bundle.js:1351
get @ bundle.js:194
(anonymous) @ bundle.js:22318
(anonymous) @ bundle.js:22325
__webpack_require__ @ bundle.js:20
(anonymous) @ bundle.js:59
__webpack_require__ @ bundle.js:20
(anonymous) @ bundle.js:40
(anonymous) @ bundle.js:43
bundle.js:30339 setupBonds...
bundle.js:30341 setupBonds: on chain homestead`

If I look in the network dept, there are numerous RPC calls to **http://127.0.0.1:8080/rpc/**

returning (for example)

`{jsonrpc: "2.0", result: ["0x0060083d0d4a150f9c2174998ded91213413b3d9"], id: 981}`

**Comment by nickwit** [comment]
If I can't get help with this here, does anyone know where I can?

**Comment by 5chdn** [comment]
You could check if someone on Gitter experiences similar issues or ask for help on Ethereum Stack Exchange - I'm currently not able to go through the tutorial to assist you with that. 

- https://gitter.im/paritytech/parity.js
- https://ethereum.stackexchange.com

Just a thought. Sorry.

**Comment by nickwit** [comment]
Cool - thank you.

**Comment by 5chdn** [comment]
Tutorial moved https://github.com/paritytech/parity/wiki/Tutorial-Part-3
