### ISSUE TITLE
workpackage by url

### ISSUE THREAD

**Issue by panicape** [paritytech/parity#5848]
I just saw that parity can notify me by http post to an url when a workpackage is created but, how do i know how to get this notification in the destiny? i supose i have to create a POST webservice in producer mode to get this notification but what is the json scheme of this package?.
Thank you very much for your help

**Comment by 5chdn** [comment]
where did you see that?

**Comment by arkpar** [comment]
The payload is the same you would receive in response to `eth_getwork` API call in the "result" field.
https://github.com/paritytech/parity/wiki/JSONRPC-eth-module#eth_getwork

**Comment by panicape** [comment]
ah, ok, but it is not triggered by something, i just have to call this webservice, isn't it? @arkpar
