### ISSUE TITLE
Run parameter for redirect .ethereum directory

### ISSUE THREAD

**Issue by BorilloB** [paritytech/parity#5849]
Hello.
I run parity 
`parity --base-path /123/.ethParity/ --geth --jsonrpc-interface 127.0.0.1 --jsonrpc-port 5679 --no-secretstore --no-dapps`
And in root home directory creating .ethereum directory. What parameter i need use for create this directory in base-path ?

**Comment by arkpar** [comment]
Pretty sure parity does not create ".ethereum". What's your Parity version. Could it be you are also running geth or official ethereum wallet app?

**Comment by BorilloB** [comment]
```
 parity -v
Parity
version Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
If i run without key "--geth",  directory not created.
I check several time.

**Comment by arkpar** [comment]
Ah, right `--geth` initializes geth key store, and that creates a directory probably. This needs to be fixed. The directory should be empty anyway.

**Comment by BorilloB** [comment]
So, can I run multiple copies and there will not be a conflict?

**Comment by arkpar** [comment]
@BorilloB there should be no conflict
