### ISSUE TITLE
Stage 5 block verification failed InvalidReceiptsRoot Mismatch happens on importing transaction in block

### ISSUE THREAD

**Issue by astudnev** [paritytech/parity#5850]
I have a private network with 2 nodes:

parity node 
version Parity/v1.7.0-unstable-8aa2ed175-20170613/x86_64-macos/rustc1.18.0

connected to geth node:
1.6.6-unstable-80f7c6c2

when transaction commited to block on geth node ( which is bootnode for parity ), the parity returns error and stops to sync with message:

$ ./target/release/parity --chain /Users/studnev/dev4bc/parity/chain.json --bootnodes enode://9cb6e35163980853b65ffd7052704852e2cd893df47fe1e336f3bc2b9e052b84e41ea54a1020b9bfb812442026d0afc17bd3460d5066a4566faa346f3dc90c1b@144.76.13.143:30303 --no-discovery --network-id 20017
2017-06-15 23:27:58  Starting Parity/v1.7.0-unstable-8aa2ed175-20170613/x86_64-macos/rustc1.18.0
2017-06-15 23:27:58  State DB configuration: fast
2017-06-15 23:27:58  Operating mode: active
2017-06-15 23:27:58  Configured for GethTranslation using Ethash engine
2017-06-15 23:27:59  Updated conversion rate to Ξ1 = US$320.82 (371072930 wei/gas)
2017-06-15 23:27:59  Public node URL: enode://ff1d9e905918910eec0c9a908dc1eb6be3e526a3ef04942b0c7b7e0a3643681f4c0ff71a43bfd7a44745a09c1ee05c3fe176ccf32c9c22bfcdbdb3bfd683bb27@192.168.0.101:30303
2017-06-15 23:28:07  Stage 5 block verification failed for #149 (b095…10f0)
Error: Block(InvalidReceiptsRoot(Mismatch { expected: d50a3f0afbf67b0d7fcf12dce5fab58cbaf7f09a51654ce787d5d529ec9eb54b, found: 45bef3c8f45af0174311babea84ed659c7380a7249e2fe1ac5d7749f2918a383 }))

genesis file for geth is:
{
"mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
"coinbase": "0x3333333333333333333333333333333333333333",
"timestamp": "0x00000000000000000",
"extraData": "0x",
"nonce": "0x0000000000000042",
"config": {
        "chainId": 20017,
        "homesteadBlock": 0,
        "eip98Transition": "0x7fffffffffffffff",
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "eip160Block": 0
    },
    "difficulty": "2000000",
    "gasLimit": "21000",
    "alloc": {
        "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": { "balance": "300000" },
        "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": { "balance": "400000" }
    }
}

and chain.json for parity is:
{
  "name": "GethTranslation",
  "engine": {
    "Ethash": {
      "params": {
        "gasLimitBoundDivisor": "0x400",
        "minimumDifficulty": "0x20000",
        "difficultyBoundDivisor": "0x800",
        "durationLimit": "0xd",
        "blockReward": "0x4563918244F40000",
        "registrar": "0x81a4b044831c4f12ba601adb9274516939e9b8a2",
        "homesteadTransition": 0,
        "eip150Transition": 0,
        "eip155Transition": 0,
        "eip160Transition": 0,
        "eip161abcTransition": 0,
        "eip161dTransition": 0,
        "eip98Transition": "0x7fffffffffffffff"
      }
    }
  },
  "params": {
    "accountStartNonce": "0x0",
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID": 20017
  },
  "genesis": {
    "seal": {
      "ethereum": {
        "nonce": "0x0000000000000042",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    "difficulty": "2000000",
    "author": "0x3333333333333333333333333333333333333333",
    "timestamp": "0x00000000000000000",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x",
    "gasLimit": "21000"
  },
  "accounts": {
    "7df9a875a174b3bc565e6424a0050ebc1b2d1d82": {
      "balance": "300000",
      "nonce": "0x0"
    },
    "f41c74c9ae680c1aa78f42e5647a62f353b7bdde": {
      "balance": "400000",
      "nonce": "0x0"
    }
  }
}

**Comment by astudnev** [comment]
On 1.6.8 the error exists with different stage number (Stage 4 block verification failed)

MacBook-Pro-Rasid:parity-1.6.8 studnev$ ./target/release/parity --chain /Users/studnev/dev4bc/parity/chain.json --bootnodes enode://9cb6e35163980853b65ffd7052704852e2cd893df47fe1e336f3bc2b9e052b84e41ea54a1020b9bfb812442026d0afc17bd3460d5066a4566faa346f3dc90c1b@144.76.13.143:30303 --no-discovery --network-id 20017
2017-06-16 00:31:37  Starting Parity/v1.6.8-unstable/x86_64-macos/rustc1.18.0
2017-06-16 00:31:37  State DB configuration: fast
2017-06-16 00:31:37  Operating mode: active
2017-06-16 00:31:38  Configured for GethTranslation using Ethash engine
2017-06-16 00:31:38  Public node URL: enode://9f636402d5a2ce91a6c56db5c014680a2cef76826c72fc3eb9bc877c2fbd0486cc97e2f11dd664e34009f518b5c425c7e9e3c7d5c3fe02ab4bef6394a4b11493@192.168.0.101:30303
2017-06-16 00:31:38  Updated conversion rate to Ξ1 = US$334.25 (356163400 wei/gas)
2017-06-16 00:31:47  Stage 4 block verification failed for #149 (b095…10f0)
Error: Block(InvalidReceiptsRoot(Mismatch { expected: d50a3f0afbf67b0d7fcf12dce5fab58cbaf7f09a51654ce787d5d529ec9eb54b, found: 45bef3c8f45af0174311babea84ed659c7380a7249e2fe1ac5d7749f2918a383 }))
^C2017-06-16 00:31:59  Finishing work, please wait...

**Comment by astudnev** [comment]
I figured out that the issue was caused by config.
"eip98Transition": "0x7fffffffffffffff" should be in the root params section ( not Ehcache )

It is not clear from the documentation, however.
After i placed this in right section in config, issue resolved

**Comment by 5chdn** [comment]
Yes, people keep approaching me about this. I have a good solution in mind, will add this to the wiki asap.

**Comment by astudnev** [comment]
Also make sense to modify https://github.com/keorn/parity-spec to generate this config automatically

**Comment by keorn** [comment]
True, thanks for finding it.

**Comment by 5chdn** [comment]
wip: https://github.com/5chdn/crossclient-chainspec
