### ISSUE TITLE
Run from non root user

### ISSUE THREAD

**Issue by BorilloB** [paritytech/parity#5857]
Hello. 
```
Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
Linux ubuntu 4.4.0-78-generic
```

Try run from another user
```
sudo -u parity0 bash -c '/usr/bin/parity --jsonrpc-interface 127.0.0.1 --jsonrpc-port 5679 --no-secretstore --no-dapps'
Error upgrading parity data: CannotCreateConfigPath
```
or

```
sudo -u parity0 /usr/bin/parity --jsonrpc-interface 127.0.0.1 --jsonrpc-port 5679 --no-secretstore --no-dapps
Error upgrading parity data: CannotCreateConfigPath
```

**Comment by 5chdn** [comment]
Related, probably: #4565

does it work if you switch user and run it?

    sudo su - parity0
    /usr/bin/parity --jsonrpc-interface 127.0.0.1 --jsonrpc-port 5679 --no-secretstore --no-dapps

**Comment by BorilloB** [comment]
If i switch to parity0 first and run /usr/bin/parity all work fine.

**Comment by BorilloB** [comment]
Fixed, use sudo with -H key
`sudo -u parity0 -H /usr/bin/parity --jsonrpc-interface 127.0.0.1 --jsonrpc-port 5679 --no-secretstore --no-dapps`
