### ISSUE TITLE
exporting state fails "specified block not found"

### ISSUE THREAD

**Issue by wanderer** [paritytech/parity#5859]
when doing `parity export state` the result is  "specified block not found". This  hold true if `--at` is used.

Using Parity/v1.7.0-unstable-8d04dffe6-20170615/x86_64-linux-gnu/rustc1.19.0-nightly, with a freshly synced chain

**Comment by 5chdn** [comment]
$ parity --no-config export state
    2017-06-19 09:54:55  Configured for Foundation using Ethash engine
    Specified block not found
    { "state": [1 $ parity --no-config export state --at 1337
    2017-06-19 09:55:05  Configured for Foundation using Ethash engine
    Specified block not found
    { "state": [1 

Same for 1.6.8

**Comment by arkpar** [comment]
You need to sync with `--fat-db on` first. The error message is misleading and needs to be fixed.

**Comment by arkpar** [comment]
Assuming that was the cause
