### ISSUE TITLE
What is “a public key under ECIES”, and how to get it?

### ISSUE THREAD

**Issue by myqq0000** [paritytech/parity#5863]
Hi there. 

I read the JSONRPC document of Parity these days.

And I want to encrypt my message with the public key and private key of the accounts in Parity.

I found a JSONRPC in this web [parity_encryptMessage](https://github.com/paritytech/parity/wiki/JSONRPC-parity-module#parity_decryptmessage)

It refers that

> "Encrypt some data with a public key under ECIES."

And one of its parameters is

> "Hash - Public EC key generated with secp256k1 curve, truncated to the last 64 bytes."

I can't understand it. I don't know how to get it. It generate by Parity or it should generate by myself? Please give me some advice. Thanks a lot~ :)

**Comment by rphmeier** [comment]
@myqq0000 Right now I think you can only obtain the public key of the signer of a transaction (use `getTransactionByHash` or similar RPC and get `publicKey` member. 
There currently isn't an RPC call to get the public key for a stored account, although it's definitely possible.

**Comment by arkpar** [comment]
@myqq0000 You can generate new private/public key pairs with a tool, such as ethkey
https://github.com/paritytech/parity/tree/master/ethkey

**Comment by 5chdn** [comment]
https://ethereum.stackexchange.com/questions/18208/what-is-a-public-key-under-ecies-and-how-to-get-it
