### ISSUE TITLE
Ethereum Sent from Coinbase - transaction confirmed and nothing in wallet? Please help!

### ISSUE THREAD

**Issue by Jacks2High** [paritytech/parity#5864]
Hi, 

I have just installed the latest version of Parity 1.6.8 and installed on windows 7 with Chrome.  I have sent some ether to the one account address from coinbase and nothing has appeared hours after the transaction. 

I have checked there are 229 confirmations on etherscan yet nothing is appearing in my wallet. As a new user fairly worried about this, but am hoping its a simple config issue that can be fixed straight away. I have double checked the address and it is correct and checked all the settings and can't see anything wrong. 

Please could someone help as soon as possible as i need the ether uregently for an ICO closing soon. 

Many thanks 

Mickey

**Comment by rphmeier** [comment]
Please ensure your node is fully synced -- compare the block number in the bottom right corner to the one on etherscan.
