### ISSUE TITLE
Parity does not filter `100.64.0.0/10` ip range when `--allow-ips=public`

### ISSUE THREAD

**Issue by offlinehacker** [paritytech/parity#5872]
All these private bogon ip addresses must be blocked https://www.team-cymru.org/Services/Bogons/bogon-bn-agg.txt

**Comment by 5chdn** [comment]
It seems Parity only blocks RFC1918 private network connections, but it should also block reserved IPs. This is not really a bug but an annoyance as 100.64.0.0/10 is not a private network.

We should consider blocking all reserved IP address spaces. https://en.wikipedia.org/wiki/IPv4#Special-use_addresses

I personally use iptables to circumvent this issue. https://ethereum.stackexchange.com/a/9964

**Comment by sjeohp** [comment]
Just confirming that the solution here is to filter all [reserved ips](https://en.wikipedia.org/wiki/Reserved_IP_addresses) from the public list?

**Comment by sjeohp** [comment]
Also it looks like the only current criteria for the `--allow-ips=private` list is being not-[global](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#method.is_global), so some reserved IPs (loopback, link-local, etc) can be included.  Should probably filter those too?

**Comment by arkpar** [comment]
@sjeohp This should really be addressed by allowing custom ranges in addition to predefined "public" and "private" sets. E.g. `--allow-ips="100.64.0.0/10 2.3.0.0/32"`

**Comment by 5chdn** [comment]
On a practical note, it might be easier (from a user perspective) blacklisting rather than whitelisting sets of ip adresses, i.e., `--block-ips="private,100.64.0.0/10,2.3.0.0/32"`

**Comment by sjeohp** [comment]
I've refactored to exclude more of the reserved/special-use IPs including `100.64.0.0`, but there are still ambiguities in the official reserved lists, hence why Rust's `std::net` IP functions have been unstable for so long.

I can add both `--allow-ips` and `--block-ips`.  Only issue I can see would be potential conflicts,  e.g. passing `--allow-ips="100.64.0.0/10 2.3.0.0/16" --block-ips="private,100.64.0.0/10,2.3.0.0/32"`, but I think an error in that case makes sense.

**Comment by sjeohp** [comment]
On second thought maybe something like `--allow-ips="private,100.64.0.0/10,-2.3.0.0/16"`?  Where that would allow all in the private list and the 100.64.0.0/10 range, and block 2.3.0.0/16, with order indicating precedence, either ascending or descending.

**Comment by arkpar** [comment]
I'd be happy with either solution. `--allow-ips` can be moved to legacy options and `--block-ips` made a priority if specified.
