### ISSUE TITLE
Can not choose network interface

### ISSUE THREAD

**Issue by lordi** [paritytech/parity#5878]
When there are multiple network interfaces available, parity seems to choose the first one. It would be nice to specify the network interface on the command line via a ``--network-interface`` option.

**Comment by arkpar** [comment]
Parity should bind to all available interfaces, not just the first. Could you give more details on your setup if this is not the case?

**Comment by lordi** [comment]
I had WiFi and VPN connection. Default route was through the VPN interface, but parity kept opening connections through the WiFi. Setting ``--nat`` to ``extip:x.x.x.x`` didn't help.

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.

**Comment by Serpent6877** [comment]
I don't see this on the list. I need this option as well when running multiple parity on a server with multiple IP's. Each parity has it's own IP. Yes I could change the ports. But would be nice to use the same port and assign an IP.
