### ISSUE TITLE
Didnt recive eth

### ISSUE THREAD

**Issue by Fest1990** [paritytech/parity#5883]
Hi, I made a wallet on parity today (windows). I sent etherum 4hours ago and I still cant see eth on parity. 

Eth was correctly sent: https://etherscan.io/address/0x0067D39633b55D79F67e6Daa6b6E7D7b269992c5

Any idea why I cant see eth on parity?

**Comment by anthonyThe3rd** [comment]
Did you send it to the default account address?

**Comment by tomusdrw** [comment]
Most likely you are not fully synced. Have a look at bottom right corner to see syncing status and follow these steps in case it's not progressing:
https://github.com/paritytech/parity/wiki/FAQ#what-can-i-do-when-parity-has-trouble-getting-in-sync
