### ISSUE TITLE
Just set up Parity. Sent ETH to stock address. Never received

### ISSUE THREAD

**Issue by anthonyThe3rd** [paritytech/parity#5884]
I send the funds to the default account "address" that is automatically created during Parity installation.

**Comment by tomusdrw** [comment]
Most likely you are not fully synced. Have a look at bottom right corner to see syncing status and follow these steps in case it's not progressing:
https://github.com/paritytech/parity/wiki/FAQ#what-can-i-do-when-parity-has-trouble-getting-in-sync

**Comment by anthonyThe3rd** [comment]
I looked t the bottom right corner. It does not seem to be syncing. Also, it says, "0/0/25" peers". 

This is my first experience with this product. On the "What can I do when Parity has trouble getting in sync?" article, it says, "Remove your nodes file ($HOME/.local/share/io.parity.ethereum/network/nodes.json) while Parity is not running." Yet I suspect that doing this will make it impossible to access my funds. 

Any suggestions? Please help. Thanks ...

**Comment by tomusdrw** [comment]
Removing the file won't remove your keys. Your keys are in `~/.local/share/io.parity.ethereum/keys/ethereum` make sure to back them up (as well as recovery phrases).

Make sure your time is in sync: https://time.is

Please send a screenshot what it shows exactly in the bottom right corner like this:
![screenshot from 2017-06-19 10-16-56](https://user-images.githubusercontent.com/581548/27528523-1856864e-5a51-11e7-9512-056202c0960c.png)

**Comment by anthonyThe3rd** [comment]
Screenshot attached. Thanks for your help.
![parity-eg](https://user-images.githubusercontent.com/29584733/27528821-b3396b32-5a41-11e7-8463-73b2b449f41f.jpg)
![image](https://user-images.githubusercontent.com/29584733/27528879-f4672626-5a41-11e7-9601-728966f9bb51.png)

**Comment by tomusdrw** [comment]
What about the https://time.is ? What does it say on that site?

**Comment by anthonyThe3rd** [comment]
"Your clock is 2.2 seconds behind.
Accuracy of synchronization was ±0.063 seconds"

**Comment by tomusdrw** [comment]
@anthonyThe3rd Your clock needs to be in perfect sync for Parity to work. Please refer to system-specific time synchronization methods.
