### ISSUE TITLE
config.toml with [dapps] from 1.6.7 to 1.6.8 breaks

### ISSUE THREAD

**Issue by DeloitteDigitalDan** [paritytech/parity#5885]
I recently updated from 1.6.7 to the 1.6.8 tag of ethcore-parity in the Docker Registry Hub and I'm now receiving this error message probably due to my [dapps] section in my config.toml. Due to how Synology Docker support is, I'm forced to use config.toml to pass command-line arguments to Parity.

```
Option '--dapps-interface' is deprecated. Please use '--jsonrpc-interface' instead.
Option '--dapps-hosts' is deprecated. Please use '--jsonrpc-hosts' instead.
```

I cannot find the proper way to modify my [dapps] section and couldn't find where in the 1.6.8 changelog that would create this problem.  Thanks in advance.

**Comment by tomusdrw** [comment]
It seems that you have updated to laster `master` (version 1.7) instead of `1.6.8`. These options are deprecated in 1.7 because :8545 and :8080 servers has been merged and corresponding `--dapps-*` options are no longer necessary (you can remove `interface` and `port` from dapps section entirely).

**Comment by 5chdn** [comment]
Use parity/parity docker not ethcore/parity and downgrade to 1.6.8

see #5435 or https://github.com/paritytech/parity/wiki/Docker

**Comment by BlockchainDan** [comment]
Ah. Looks like ethcore-parity/1.6.8 is actually 1.7. I've switched over to parity/parity and wiped my DB (since 1.7 already upgraded it) and redownloaded the blockchain. Thanks!

**Comment by 5chdn** [comment]
Yes, sorry for the confusion. ethcore/parity is now removed.
