### ISSUE TITLE
Balance Not Reflecting on Parity wallet

### ISSUE THREAD

**Issue by anant1gupta** [paritytech/parity#5888]
Hi,
I transferred ether from CEX to my parity wallet but unable to see the balance in my wallet.  The amount has been deducted from CEX wallet. It has been more than 12 hours. Searching for the tx ID does not yield any result on ether scan. 

Please help !

**Comment by tomusdrw** [comment]
If the transaction is not visible on etherescan then most likely it hasn't been sent by the exchange.
Please contact their support since there is nothing we can do about it.
