### ISSUE TITLE
Urgent help please: Parity not sending, 'waiting for confirmation'

### ISSUE THREAD

**Issue by cryptoboss** [paritytech/parity#5890]
Hi,

I had a working install of Parity but then for some reason it seems to have stopped working and I can't send anything . 

I must admit I'm not very technical... I installed the latest mac version with installer but possibly led to 2 versions running. And somehow it got out of sync.

So I killed the database and resynced with "parity --warp". I think it's syncing, but for some reason when I try to send payment it's stuck at 'waiting for confirmation", and stays tehre.

Also, bottom of my screen shows: Parity//v1.6.7-beta-e128418-20170518/x86_64-macos/rustc1.17.0 Unknown capability 3,905,697

I need this resolved for an urgent matter asap and trying to export my wallet to another app to use if I can't resolve this (like MetaMask) but I also can't seem to import the JSON file there. 

I would like to have Parity fixed but not really sure what commands I should run, or if I uninstall it would my accounts with funds remain intact?

Thank you in advance if you can help out a non-techinical newbie on what to do next, really appreciate it.

**Comment by cryptoboss** [comment]
actually just went to web3 console and typed in 'web3.eth.syncing' and I'm getting 'false' .

Perhaps this this the cause of the problem? My parity isn't fully synced?

Would appreciate any suggestions on what to do next...

**Comment by tomusdrw** [comment]
Please update to version 1.6.8 and then go to "Signer" tab and check if there are any transactions pending.

**Comment by 5chdn** [comment]
Network is highly congested. Might take a few hours till your transactions get mined. https://etherscan.io/txsPending
