### ISSUE TITLE
libssl1.0.0 is not available anymore

### ISSUE THREAD

**Issue by jpritikin** [paritytech/parity#5893]
Do you plan to migrate to the [libssl 1.1.0f-3](https://packages.debian.org/stretch/libssl-dev) available in newly release debian stable?

**Comment by 5chdn** [comment]
ssl 1.1.0 has been around for a while, if dinosaurs like debian make the switch, we are probably good to do that, too :+1:

**Comment by jpritikin** [comment]
Is this already fixed by PR #4260 ?

**Comment by 5chdn** [comment]
No, PR #4260 introduced this issue.

**Comment by calvintam236** [comment]
Actually, can you [build and release static binary](https://chr4.org/blog/2017/03/15/cross-compile-and-link-a-static-binary-on-macos-for-linux-with-cargo-and-rust/) of parity?

**Comment by iFA88** [comment]
If you wish to use parity on Debian 9 ( stretch ) you need download the package from https://packages.debian.org/jessie/libssl1.0.0 and install like `dpkg --install libssl1.0.0_1.0.1t-+deb8u6_amd64.deb` as root. For me works.

**Comment by 5chdn** [comment]
Or just build parity from source.

**Comment by calvintam236** [comment]
@5chdm the problem is that stretch does not have this old version in package manager. how can you build one without dependency?

@iFA88 not ideal for production environment

**Comment by 5chdn** [comment]
@calvintam236 building from source just links the binary against any available libssl version.

This issue is that the precompiled binaries link against a certain version. But Ubuntu didn't make the switch to 1.1.x yet.... It's really hard to understand why. The only things I can recommend here is either stop using Debian-based systems or compile from source :)

**Comment by calvintam236** [comment]
@5chdn that's why I suggest to release a static build binary - all dependencies are included the binary, so it can run on any Linux.

**Comment by l0rb** [comment]
@calvintam236 We are running parity in a docker container for production, that solves all the issues with dependencies.

**Comment by 5chdn** [comment]
Could anyone check if our debian binaries/packages work?


- debian | x86_64 | [parity 1.7.10](http://d1h4xl4cr1h0mo.cloudfront.net/stable/x86_64-unknown-debian-gnu/parity) | 6019681788349877c1fbb591d62e7d8e
- debian | x86_64 | [parity_1.7.10_amd64.deb](http://d1h4xl4cr1h0mo.cloudfront.net/stable/x86_64-unknown-debian-gnu/parity_1.7.10_amd64.deb) | db151bee67c2ed12b04e2edccae6161a
- debian | x86_64 | [parity 1.8.4](http://d1h4xl4cr1h0mo.cloudfront.net/v1.8.4/x86_64-unknown-debian-gnu/parity) | 10a6c69047ffa61008efd7850f3100c8
- debian | x86_64 | [parity_1.8.4_amd64.deb](http://d1h4xl4cr1h0mo.cloudfront.net/v1.8.4/x86_64-unknown-debian-gnu/parity_1.8.4_amd64.deb) | 01ecf9e6246b67d4ddefbc356b7ce52b

**Comment by iFA88** [comment]
`Parity/v1.8.4-beta-c74c8c1-20171211/x86_64-linux-gnu/rustc1.22.1`  Works on `3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19)`

**Comment by 5chdn** [comment]
Ok, thanks for confirming.

**Comment by calvintam236** [comment]
I ran the binary in docker using base `debian:stretch-slim`. I get this error with `libssl1.1` installed: `parity: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`. Tried installing binary on the same container, same error @iFA88 have.

**Comment by 5chdn** [comment]
On it. We have a debian pipeline, I just need to figure out why it does not link the new ssl lib.

**Comment by General-Beck** [comment]
Parity also requires gcc, g++, libssl-dev/openssl, libudev-dev and pkg-config packages to be installed.
See pls https://github.com/paritytech/parity/blob/master/README.md#build-dependencies

**Comment by 5chdn** [comment]
Someone with Debian, please test if this works for you!

debian | x86_64 | [ethkey](http://d1h4xl4cr1h0mo.cloudfront.net/nightly/x86_64-unknown-debian-gnu/ethkey) | 350fb2550e01243dff41670d65d73fe3
debian | x86_64 | [ethstore](http://d1h4xl4cr1h0mo.cloudfront.net/nightly/x86_64-unknown-debian-gnu/ethstore) | a694cc4c085968d68b14dc1a322fdda2
debian | x86_64 | [parity-evm](http://d1h4xl4cr1h0mo.cloudfront.net/nightly/x86_64-unknown-debian-gnu/parity-evm) | a16da5032c77b66f782bb3b7e4887188
debian | x86_64 | [parity_1.10.0_amd64.deb](http://d1h4xl4cr1h0mo.cloudfront.net/nightly/x86_64-unknown-debian-gnu/parity_1.10.0_amd64.deb) | f5d313ad9ea6b980feac2b9fe9837dcf
debian | x86_64 | [parity](http://d1h4xl4cr1h0mo.cloudfront.net/nightly/x86_64-unknown-debian-gnu/parity) | d820ef51b34f79a62abe46e224df4f33

Preferable on a system that has no custom libssl 1.0.x - thanks!

**Comment by 5chdn** [comment]
Ok was able to test this. It's working now. Next release will contain deb for Debian!

**Comment by 5chdn** [comment]
And CentOS

![screenshot at 2018-01-17 16-48-41](https://user-images.githubusercontent.com/15729797/35051804-5bc07aec-fba6-11e7-996e-e749ab6e0215.png)
