### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by voidzero** [paritytech/parity#5898]
Hello,

It looks like the docker images were moved from ethcore/parity to parity/parity. I've just pulled the images - nightly failed to download (missing hash), and when I try to start parity (v1.6.8, beta, and stable) now, it says:

> Database was created with newer client version. Upgrade your client or delete DB and resync.

Could you give it a look? I was a bit careless and deleted the ethcore/parity images which were working for me.

**Comment by 5chdn** [comment]
Run `parity db kill` to reset the database. The old docker images were pulling the wrong versions, see #5435
