### ISSUE TITLE
error: Could not compile `untrusted`.

### ISSUE THREAD

**Issue by bitcoiners** [paritytech/parity#5900]
```
$ cargo build --release
...
Compiling untrusted v0.5.0
error: struct field shorthands are unstable (see issue #37340)
   /home/slava/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:313:21
    |
313 |             Slice { bytes }
    |                     ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/slava/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:327:51
    |
327 |             self.bytes.get(r).map(|bytes| Slice { bytes })
    |                                                   ^^^^^

error: aborting due to 2 previous errors

error: Could not compile `untrusted`.

```

**Comment by 5chdn** [comment]
which `rustc` and `cargo` version? which os? did you try running `cargo clean`?

**Comment by bitcoiners** [comment]
cargo --version
cargo-0.17.0 (built 2017-03-24)
rustc --version
rustc 1.16.0
Ubuntu 17.04

tried cargo clean

**Comment by 5chdn** [comment]
beta requires rust 1.17 and nightly 1.18, if you could upgrade your rust and try again, please? :)

**Comment by bitcoiners** [comment]
that helped, but now I get new error:

`Compiling rust-crypto v0.2.36
error: failed to run custom build command for `hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#9a127c1d)`
process didn't exit successfully: `/home/slava/dev/parity/target/release/build/hidapi-f79bbfacbd2e9e41/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("release")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-o" "/home/slava/dev/parity/target/release/build/hidapi-0765e35f0d7be915/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c"
cargo:warning=etc/hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
cargo:warning= #include <libudev.h>
cargo:warning=                     ^
cargo:warning=compilation terminated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /home/slava/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.43/src/lib.rs:1127
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
`

**Comment by arkpar** [comment]
Make sure you have `libssl-dev` and `libudev-dev` packages installed.

**Comment by bitcoiners** [comment]
installed those packages, run again, now this error:

`Compiling ring v0.9.5
error: failed to run custom build command for `openssl-sys v0.9.13`
process didn't exit successfully: `/home/slava/dev/parity/target/release/build/openssl-sys-97441479eeff6b6d/build-script-build` (exit code: 101)
--- stdout
run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-gnu
    openssl-sys = 0.9.13


It looks like you're compiling on Linux and also targeting Linux. Currently this
requires the `pkg-config` utility to find OpenSSL but unfortunately `pkg-config`
could not be found. If you have OpenSSL installed you can likely fix this by
installing `pkg-config`.

', /home/slava/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.13/build.rs:176
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
`

**Comment by arkpar** [comment]
As the message suggests you should install `pkg-config` as well.
I recommend you follow README instructions. All the required dependencies are listed there.

**Comment by bitcoiners** [comment]
thanks, that worked.
