### ISSUE TITLE
transactions never arriving to Parity

### ISSUE THREAD

**Issue by fidaaayoub** [paritytech/parity#5911]
Hello support,
i have done 5 transactions from 3 different sources to my Parity wallet. all sources shows that Transfer completed. Also in Etherscan i can see all 5 transaction with age of 2 days and 12 hours. However, nothing appearing in Parity.  Any help?

**Comment by 5chdn** [comment]
Please make sure you are fully synchronized first. You can check the progress in your terminal, in the wallet footer (at the bottom), or in the wallet status tab.

**Comment by fidaaayoub** [comment]
I have closed it fully abd relaunched again, still nothing appears in the transactions part on the footer

How i can make sire its fully synchronized then?

Best Regards,

Fidaa Ayoub, PMP
Program Manager, IBM-Etihad Airways Partnership 
IBM Security 
IBM Middle East and Africa 
Mobile: 00971502188456
Email: fidaa_ayoub@ae.ibm.com
