### ISSUE TITLE
[Web Face] broken link to etherscan.io

### ISSUE THREAD

**Issue by fzzr-** [paritytech/parity#5914]
version: latest release `1.5.12 stable`

On the web-face of parity at the top-right corner there button with all accs. Click to any of this => open new page with url = `https://https//etherscan.io/address/0x...`.

**Comment by rphmeier** [comment]
I think this was fixed in a recent version -- could you try updating to 1.6.8 and see if it's still there?

**Comment by fzzr-** [comment]
Currently I don't know why but brew don't want to do it.
![screen shot 2017-06-23 at 20 31 21](https://user-images.githubusercontent.com/888526/27493620-082b2d60-5853-11e7-8ce6-6eb009d76f42.png)

I'll try again soon and tell you.
