### ISSUE TITLE
1 min after every start crashing

### ISSUE THREAD

**Issue by 3eph1r0th** [paritytech/parity#5915]
Every time i try to start my Parity i receive crash of app:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	parity.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5939637b
  Fault Module Name:	parity.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5939637b
  Exception Code:	c000001d
  Exception Offset:	0000000000a8c5e4
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1049

I saw similar issue https://github.com/paritytech/parity/issues/4416 and that deletion of blockchain folder helped. How can i delete my blockchain folder? Where is it? What should i do? I cannot even get access to my money because it is crashing 30 seconds after start.

OS: Windows 7

**Comment by keorn** [comment]
Are you sure Parity is not already running (it runs as a deamon if you use the installer)? Try going to the UI.
