### ISSUE TITLE
Parity wallet demands: "update your secure token or to generate a new one, run parity signer new-token"

### ISSUE THREAD

**Issue by Pepco** [paritytech/parity#5918]
I opened a Parity wallet, logged the account address.
I work on a PC running on Windows 7 (32bit)
After the account was open the page requested that I create a signer certificate or something at a fee in ETH.  
Since the account was empty, I  transferred ETH to the wallet.
The email verification did not send me any email, or I did not receive it.
ISSUE ONE: When I wanted to check the balance, the page instructs me to _"To update your secure token or to generate a new one, run parity signer new-token"_
I open the command prompt and enter: parity signer new-token
The I receive the following response:  _'parity' is not recognised as an internal or external command, operable program or batch file._
I am at a loss. The ETH shows up in in my Parity account on Eatherscan, but after hours of reading on various web sites, I am unable to find a solution to my problem.
ISSUE 2: I opened a new Parity account from other PC, but find no instructions anywhere for how to import a standard Parity account into my new Parity profile.
I really hope that someone can help met to resolve either issue one or two please. 
Thanks

**Comment by maciejhirsz** [comment]
@Pepco On Windows you will have to run `parity.exe signer new-token` within the context of the folder where your parity installation is. This might be of some help: https://superuser.com/questions/747684/how-can-i-run-an-application-with-arguments-from-windows-explorer

**Comment by Pepco** [comment]
Thanks, I did that and it works.  I can open my account.
Now there is one problem still:
The ETH that I transferred to this address shows as the correct balance on Etherscan, but is does not show up in the corresponding address in my Parity wallet.
Do you have any ideas please of what I must do to make this happen?
Thanks for your trouble.

**Comment by maciejhirsz** [comment]
Most likely you aren't synced yet, check that the block number (bottom right in the UI). Once you sync up to the block on which you sent funds to your account, the funds should show up in Parity.

**Comment by tg-kim** [comment]
I am having a same issue. Except on OSX. If possible, can you please tell me how to solve this issue in plain and simple English?

**Comment by maciejhirsz** [comment]
@tg-kim OSX should be fairly simple: Open Terminal (cmd+space, type "Terminal", enter), then on the command prompt type `parity signer new-token`
