### ISSUE TITLE
High system resource usage.

### ISSUE THREAD

**Issue by UNST4BL3** [paritytech/parity#5923]
Operating system: Windows 10
Parity version: 1.6.8
Geth version: 1.6.6

Parity appears to have finished syncing the blockchain after it reports in the interface "3,925,008 best block". Despite this, the Windows task manager shows that Parity is constantly consuming huge amounts of system resources for no reason.

Resource usage:  
![image](https://user-images.githubusercontent.com/9488054/27512460-623bc4a0-5938-11e7-8087-25f88e73e451.png)

Interface:
![image](https://user-images.githubusercontent.com/9488054/27512465-75955c96-5938-11e7-85c1-3abda834ef32.png)

**Comment by bjornwgnr** [comment]
I'm also experiencing this issue.

`Parity//v1.7.0-nightly-d152fa3-20170620/x86_64-windows-msvc/rustc1.18.0`
`Windows 10 Version: 10.0.14393 Build 14393`

![resources2](https://user-images.githubusercontent.com/17831185/27518479-2ac97054-59e1-11e7-8517-8eda8645f2af.JPG)
![resources](https://user-images.githubusercontent.com/17831185/27518474-0e334b40-59e1-11e7-89af-9cef378a6439.JPG)

> [25.6.2017, 19:56:21]  #954013 10/16/25 peers 60 MiB db 5 MiB chain 0 bytes queue 9 MiB sync RPC: 2 conn, 55 req/s, 12755 µs
> [25.6.2017, 19:56:15] Imported #3928908 b60c…e886 (80 txs, 3.91 Mgas, 1057.05 ms, 14.59 KiB)
> [25.6.2017, 19:56:06] Imported #3928907 5335…3331 (46 txs, 4.05 Mgas, 126.58 ms, 8.80 KiB)
> [25.6.2017, 19:55:51] #944654 3/23/25 peers 60 MiB db 7 MiB chain 0 bytes queue 15 MiB sync RPC: 2 conn, 3 req/s, 4468 µs
> [25.6.2017, 19:55:30] Imported #3928906 0f03…f9a0 (66 txs, 4.34 Mgas, 139.06 ms, 11.64 KiB)
> [25.6.2017, 19:55:28] Imported #3928906 d43f…9617 (56 txs, 4.69 Mgas, 228.65 ms, 9.45 KiB)
> [25.6.2017, 19:55:17] #940661 2/19/25 peers 60 MiB db 6 MiB chain 0 bytes queue 6 MiB sync RPC: 2 conn, 7 req/s, 303 µs
> [25.6.2017, 19:55:12] Imported #3928905 a006…dfd1 (8 txs, 1.16 Mgas, 326.75 ms, 4.26 KiB)
> [25.6.2017, 19:54:56] Imported #3928904 cc5d…d595 (5 txs, 0.19 Mgas, 11.57 ms, 1.54 KiB)
> [25.6.2017, 19:54:44] #931506 9/17/25 peers 60 MiB db 9 MiB chain 0 bytes queue 8 MiB sync RPC: 2 conn, 97 req/s, 4856 µs
> [25.6.2017, 19:54:09] #918932 16/24/25 peers 60 MiB db 7 MiB chain 0 bytes queue 10 MiB sync RPC: 2 conn, 1 req/s, 144 µs
> [25.6.2017, 19:53:48] Imported #3928899 518c…daad (31 txs, 3.87 Mgas, 577.81 ms, 14.23 KiB)
> [25.6.2017, 19:53:36] #913599 15/24/25 peers 60 MiB db 5 MiB chain 0 bytes queue 8 MiB sync RPC: 1 conn, 81 req/s, 10753 µs

**Comment by UNST4BL3** [comment]
@bjornwgnr How did you acquire the blockchain data? Through Parity? Or did you sync using Geth in light mode like I did?

**Comment by tomusdrw** [comment]
It might be the database compaction. Can you guys run with `--mode offline --no-jsonrpc --no-ipc --no-ws --no-dapps --no-ui` and check if the problem is present as well?
A config file with those settings: https://paritytech.github.io/parity-config-generator/#config=eyJfX2ludGVybmFsIjp7ImNvbmZpZ01vZGUiOiJhZHZhbmNlZCJ9LCJ1aSI6eyJkaXNhYmxlIjp0cnVlfSwicnBjIjp7ImRpc2FibGUiOnRydWV9LCJ3cyI6eyJkaXNhYmxlIjp0cnVlfSwiaXBjIjp7ImRpc2FibGUiOnRydWV9LCJkYXBwcyI6eyJkaXNhYmxlIjp0cnVlfX0=

**Comment by UNST4BL3** [comment]
@tomusdrw Dragging that config.toml to the C:\Users\Connor\AppData\Roaming\Parity\Ethereum causes Parity to crash and exit on launch.

**Comment by tomusdrw** [comment]
@UNST4BL3 Since you're using 1.6.8 please remove the `[ws]` section from the config file it should work fine afterwards.

**Comment by UNST4BL3** [comment]
@tomusdrw Okay, performance seems to be normal with that configuration file. Idling at about 0.5% CPU and 200MB of RAM. Unable to access web interface but I believe that's intentionally defined in the configuration file.

**Comment by arkpar** [comment]
`[25.6.2017, 19:54:44] #931506 9/17/25 peers 60 MiB db 9 MiB chain 0 bytes queue 8 MiB sync RPC: 2 conn, 97 req/s, 4856 µs` 
This means that Parity is still downloading and verifying historical block data after the initial warp sync is complete and is currently at block #931506. This background process may take a few hours. Once it is done resource usage becomes minimal.
