### ISSUE TITLE
ENS Registrar dapp doesn't work with chrome extension

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#5925]
[ENS Registrar dapp](http://registrar.ens.domains) doesn't work with my fully-synced `Parity//v1.7.0-nightly-d152fa3-20170620/x86_64-windows-msvc/rustc1.18.0` and most recent build of chrome extension (not the published one).
<img width="960" alt="2017-06-25 1" src="https://user-images.githubusercontent.com/17831185/27518366-86628200-59de-11e7-83e0-9e11c950d6ed.png">

Maybe related to #5923

**Comment by tomusdrw** [comment]
Can you let me know what settings do you have in extension options? Is it only ENS registrar? Does `https://wallet.ethereum.org` work?

**Comment by tomusdrw** [comment]
Fixed by https://github.com/paritytech/parity-extension/pull/83
