### ISSUE TITLE
Using parity and mist simultaneously?

### ISSUE THREAD

**Issue by NinjaTurtle007** [paritytech/parity#5927]
Right now seems like I can't run them both at the same time because they listen at the same port. Is there a way around that?

**Comment by tomusdrw** [comment]
You can specify different ports for Parity, for instance with this config file:
https://paritytech.github.io/parity-config-generator/#config=eyJuZXR3b3JrIjp7InBvcnQiOjMwMzA1fSwicnBjIjp7InBvcnQiOjg2NDV9LCJkYXBwcyI6eyJwb3J0Ijo4MDAwfX0=
