### ISSUE TITLE
Cannot connect to remote parity security API

### ISSUE THREAD

**Issue by RuiAlves** [paritytech/parity#5928]
I have a linux machine running parity. I can connect locally with the browser when I go to 127.0.0.1:8180  - everything works well.

I try to connect on another machine (windows 10, not on same LAN) and I use putty with port forwarding as explained here: https://github.com/paritytech/parity/wiki/Wallet-Remote-Access

On the windows machine I can connect to the client with the browser and it asks me for the token. I generate one using the putty console I used to setup the port forwarding and paste the token but it never accepts my connection with "Unable to make a connection to the Parity Secure API".

I did:
1. go to time.is on both machines I get that the time is synced on both machines.
2. I tried chrome and firefox both with the same result

Could this be an issue with this perhaps uncommon setup or am I doing something wrong?

**Comment by tomusdrw** [comment]
What address do you use on Windows box? Is it also `http://127.0.0.1:8180` ?
What version do you run? 1.7 will require port :8546 to be forwarded as well.

Can you run Parity with `-lsigner=trace`.

**Comment by RuiAlves** [comment]
I'm on 1.7 and forwarding of port 8546 did make it all work on the remote machine. Thank you.

**Comment by tomusdrw** [comment]
Great! The docs will be updated when 1.7 stabilises.
