### ISSUE TITLE
does un-install and reinstall parity help in fixing zero peers issue?

### ISSUE THREAD

**Issue by fidaaayoub** [paritytech/parity#5930]
the max number of peers i got is 2/2/25 ..... for few minutes then back to 0/0/25 .

if i totally remove parity and try to re-install it....does it help

and if i do the removal and install again, directly it will prompt me to create new account....how i can restore my account

**Comment by rphmeier** [comment]
Hi @fidaaayoub,

I understand you're having some trouble finding peers on the network. Typically this involves some combination of poor network connectivity and time being out of sync. That said, could we keep discussion of this issue to https://github.com/paritytech/parity/issues/5913?
