### ISSUE TITLE
Backing up & Restoring wiki needs updated

### ISSUE THREAD

**Issue by amazingandyyy** [paritytech/parity#5932]
[backup wiki](https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring)
```
cd $HOME/Library/Application Support/io.parity.ethereum/keys && tar czf $HOME/Desktop/parity-keys-backup.tgz * && cd -
```
should be changed to 
```
cd $HOME/Library/Application\ Support/io.parity.ethereum/keys && tar czf $HOME/Desktop/parity-keys-backup.tgz * && cd -
```

I don't know how to do a PR to wiki

**Comment by ddorgan** [comment]
Updated at: https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring
Does it look ok?

Thanks,
David
