### ISSUE TITLE
Parity build from source error

### ISSUE THREAD

**Issue by myqq0000** [paritytech/parity#5933]
Hi there.
Yesterday I tried to build ethkey to generate my key. (I asked some days ago about how to generate [private key.)](https://github.com/paritytech/parity/issues/5863)
And when I try to build it with cargo (which is mentioned in this [question](https://ethereum.stackexchange.com/questions/16546/how-can-i-run-ethkey-under-parity/16551#16551))
But it return an error : 

> error: Package `parity v1.7.0 (file:///home/ubuntu/Parity/parity)` does not have these features: `ethkey-cli`

> error: Package `ethkey v0.2.0 (file:///home/ubuntu/Parity/parity/ethkey)` does not have these features: `ethkey-cli`

And then I try to build full Parity with command
`cargo build --release`

But it returns these errors:
```
error: struct field shorthands are unstable (see issue #37340)
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:313:21
    |
313 |             Slice { bytes }
    |                     ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/untrusted-0.5.0/src/untrusted.rs:327:51
    |
327 |             self.bytes.get(r).map(|bytes| Slice { bytes })
    |                                                   ^^^^^

error: aborting due to 2 previous errors

error: failed to compile `parity v1.7.0 (https://github.com/paritytech/parity.git#4900e901)`, intermediate artifacts can be found at `/tmp/cargo-install.PaN5ThqMI1Ep`

Caused by:
  Could not compile `untrusted`.

To learn more, run the command again with --verbose.
```

How to fix it?
My rust version is 1.15.1.

**Comment by tomusdrw** [comment]
Please update to rust 1.18.
