### ISSUE TITLE
Unable connect to UI hosting on VPS

### ISSUE THREAD

**Issue by EasonWang01** [paritytech/parity#5943]
I was using google GCE.
```
parity --chain demo-spec.json -d /tmp/parity0 --port 30300 --jsonrpc-port 8540 --ui-port 8115 --dapp
s-port 8080 --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts
```

All ports are open in firewall. 

But why still not able connect it using GCP server ip address?

**Comment by tomusdrw** [comment]
Parity listens on local interface by default, not external IP address. You will need to use corresponding flags to open it up, like `--ui-interface <publicip>`. Note this approach is not recommended.
More details:
https://github.com/paritytech/parity/wiki/Wallet-Remote-Access#directly-exposing-to-external-connections
