### ISSUE TITLE
Something wrong with ethstore document

### ISSUE THREAD

**Issue by myqq0000** [paritytech/parity#5947]
Hi there.
I build the ethstore and follow the document [ethstore](https://github.com/paritytech/parity/tree/master/ethstore) to test it today.
But at second command which mentioned in examples,
`ethstore insert `ethkey generate random -s` "this is sparta"`
It returns `Invalid arguments`.
I think it may because of the password. But I don't know how to change it.
Thanks a lot~  :)

**Comment by arkpar** [comment]
This examples requires bash-like shell. Output of `ethkey generate random -s` is passed as an input to `ethstore`. If you are using some other shell you can just run these commands separately and copy-paste the output.

**Comment by tomusdrw** [comment]
I think the docs are also out of date: `<password>` needs to be a file containing the password not just any string.

**Comment by 5chdn** [comment]
Are these examples generated somewhere or was that a manual write-up?

**Comment by debris** [comment]
is was a manual write-up

**Comment by debris** [comment]
so, I actually this that the docs are fine. They properly describe the `<password>`

https://github.com/paritytech/parity/tree/master/ethstore#examples

> `<password>` - account password, file path
