### ISSUE TITLE
Unable to open Parity on MEW

### ISSUE THREAD

**Issue by istackhigh** [paritytech/parity#5948]
Hello,

For a recent ICO, i created a parity account to send Ether. I am unable to see the Tokens in my Parity account.
I was advised to use parity on MEW to be able to see the token and transfer them.

However, now i realize that MEW is not accepting parity Phrase any more.

I am totally stuck here. Can anybody please help me, on how can I open on parity account on MEW?
I only have the 12 word alphabet provided by parity while opening the account.

**Comment by rphmeier** [comment]
For a pretty technical workaround, you can build and run ethkey from source (ensure Cargo and git are installed)
  1. clone the git repo and cd into it.
  2. `cargo build -p ethkey-cli --release`
  3. `target/release/ethkey generate brain -s YOUR TWELVE WORD PHRASE`

Your secret key should be printed to the terminal. You can import this to MEW if you want.

I'm looking into finding a pre-built `ethkey` binary you can do this with.

**Comment by tomusdrw** [comment]
You can also find your keyfile and use that in MEW.
Keys are located at:
- `%AppData%\Parity\Ethereum\keys\ethereum` (Windows)
- `~/.local/share/io.parity.ethereum/keys/ethereum` (Linux)
- `/Users/<username>/Library/Application Support/io.parity.ethereum/keys/ethereum` (MAC)

What issues did you have with Parity? If you're not fully synced then most probably your time is not exact: https://time.is
Reach me out on Gitter if you need help with setting up Parity.

**Comment by istackhigh** [comment]
It worked guys. 
I used tomusdrw's steps and I was able to access parity wallet in MEW.

rphmeier - Thank you for your efforts. It was too technical for me though. I am such a noob a lol
