### ISSUE TITLE
Padding problem with bytes

### ISSUE THREAD

**Issue by jefffreey** [paritytech/parity#5963]
Hi,

I'm using Parity/v1.6.7-beta-e128418-20170518/x86_64-linux-gnu/rustc1.17.0

When I type `0x123` in a bytes32 field, I expect it to be padded as `0x123000...`, however it is converted to `0x1203000..` (notice the extra 0 behind the 3).

If I add trailing zeros manually, i.e. type `0x1230`, it works as expected, but not sure why it doesn't for the first case.

Thanks,

**Comment by Vurich** [comment]
This looks like we're parsing it byte-by-byte, i.e. `str.chunks(2).map(u8::from).collect()`.

**Comment by jefffreey** [comment]
I see, so I **should** type `0x1230`.

**Comment by jefffreey** [comment]
I see, so I **should** type `0x1230`.

**Comment by Vurich** [comment]
That's a workaround and not a fix. We can keep this open, but it's a bug in the UI so I can't fix it myself. Ideally, you should be able to write any hex number and have it be parsed correctly. You were right to file the bug, but yeah, for now just type it out using a multiple of 2 digits.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
