### ISSUE TITLE
Problem handling Monaco (MCO) tokens after re-issuance

### ISSUE THREAD

**Issue by viklas** [paritytech/parity#5967]
Not sure if this is a specific parity issue, or just an edge case, but an issue has emerged today when the Monaco tokens were listed on Bittrex. Transferring tokens purchased during the ICO failed, it appears because between the ICO (closed a couple of weeks ago) and the Bittrex listing today, Monaco had to 're-issue' the tokens, due to a problem with the initial token contract.

I'm in touch with devs from Monaco but they aren't sure what to do. Hoping for some help from the Parity community. 

Happy to provide screenshots or eth transaction links if it helps to debug.

**Comment by viklas** [comment]
https://gist.github.com/viklas/2cd5fab8832b956983c75dfc82fcf96c

Workaround process, but 're-issued' tokens are still not showing in the Parity UI.

**Comment by viklas** [comment]
Can also confirm that sending MCO tokens from Bittrex to a new parity wallet, transaction confirmed on chain but tokens not appearing in parity.

**Comment by tomusdrw** [comment]
The token contract address should be registered using `Token Registry` dapp. From what I understand it's pointing to an old contract.
The address can be updated by a person who registered the token in the first place. If you don't know who did it please contact `info@parity.io` asking for an ownership change.

**Comment by viklas** [comment]
Thanks for the info - I'll pass it on. Feel free to close the issue.
