### ISSUE TITLE
Use unstable sort on nightly

### ISSUE THREAD

**Issue by Vurich** [paritytech/parity#5972]
The best way to do this is to have an `UnstableSort` trait (and a corresponding function) that we call into, and then have a nightly implementation that uses `sort_unstable` and a stable implementation that just calls `sort`. `sort_unstable` is, um, _unstable_ (this will get confusing), but about 2x faster than the standard library sort method.

Alternatively alternatively, we can just wait until it hits stable and run `sed` over the codebase.

**Comment by Vurich** [comment]
`sort_unstable` is stablised on beta right now, we can close this as of the next stable release (should be at the end of this month).

**Comment by debris** [comment]
I'm closing this one, cause it is a guideline, not an actual issue.
