### ISSUE TITLE
Clarify our opinions on code style

### ISSUE THREAD

**Issue by Vurich** [paritytech/parity#5976]
I don't like the RFC style and we're never going to make it fit what we want it to do, but there is clear confusion about what the style should be. For example:

```
➤ rg '^\s+} else ' | wc -l
711
➤ rg '^\s+else ' | wc -l
70
```

Also, I just got a comment saying that I should use `match` on bool instead of an `if` expression, but:

```
➤ rg '= if ' | wc -l
110
➤ rg '= match ' -A 1 -t rust | rg '(true|false) => ' | wc -l
21
```

Also, just as a personal thing: manually maintaining the style is a total pain in the ass and I'd rather do it with `rustfmt`.

**Comment by rphmeier** [comment]
to be clear, I meant matching on bool when both arms are single-line

**Comment by Vurich** [comment]
```
➤ rg '= match ' -A 1 -t rust | cat | rg '(true|false) => \{' | wc -l
3
➤ rg '= if.*\{.*\}' | wc -l
37
```

**Comment by Vurich** [comment]
To be clear, it's not that I hate the existing style, but that there is no existing style. At least, not a consistent, unambiguous one. If PRs are getting rejected for style I would prefer if it was clear what style needs to be adhered to to prevent rejection.

**Comment by NikVolf** [comment]
The PRs are not rejected, there are just suggestion to alter the style based on some tribal lore everyone has agreed (or was silent) at some point

**Comment by Vurich** [comment]
It has yet to be merged, and the only comment on it is a style issue. I understand the point that you are making, but it is evidently not agreed upon, since it is very inconsistently applied across the codebase. I don't want to come across like I'm trying to enforce my own style at the expense of yours, I just think we are hitting real problems because of how we're doing things right now and I'm proposing a possible solution. Probably, the title should be "clarify what our opinions on code style" or something less specific. That's my bad.

**Comment by 5chdn** [comment]
#6443 is this the same issue?

**Comment by 5chdn** [comment]
Should this go into #6443 or https://github.com/paritytech/parity/wiki/Coding-guide ?
