### ISSUE TITLE
Allow engines to specify their own parallel verification strategy

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#5979]
The current multithreaded verification queue is only helpful if `verify_block_unordered` for that engine is very heavy (like PoW verification). 

For cases like PoA, where `verify_block_unordered` does nothing, it can actually be a deoptimization (where import is bottlenecked on N threads competing over how fast they can move blocks from one  locked deque to another)

**Comment by folsen** [comment]
@NikVolf whatever happened to this? Is this still desirable?

**Comment by NikVolf** [comment]
i don't think the outcome is worth the effort and increase in complexity

**Comment by rphmeier** [comment]
kind of disagree. a specialized queue for validator-set based engines which essentially runs a light client would be a fairly massive performance improvement.
