### ISSUE TITLE
How to Uninstall on Mac

### ISSUE THREAD

**Issue by bryaan** [paritytech/parity#5981]
I tried running the uninstall script found on the net but it seems to be dated.

I get this error:

/var/root/Library/LaunchAgents/io.parity.ethereum.plist: No such file or directory

How can I stop the service and uninstall it?

**Comment by arkpar** [comment]
If you used the installer just move `Parity Ethereum` app to trash. Use the menubar icon to stop.
Additionally, if you want to delete blockchain data and your account keys:
`rm -rf ~/Library/Application\ Support/io.parity.ethereum/`

**Comment by amanuelz91** [comment]
I've installed Parity using the MacOS installer package. However, when running the following command 

` rm -rf ~Library/Application Support/io.parity.ethereum ` 

I even moved the ` Parity Ethereum ` application to the trash and emptied the recycling bin yet Parity is still a running process.  

Even worse, Parity keeps syncing the blockchain causing me to have to manually delete the chain data.

**Comment by 5chdn** [comment]
@amanuelz91 the instructions above apply to parity installed via the installer.

the binary you observed was probably installed via homebrew.

**Comment by hiroki-money** [comment]
version 2.30 beta => x
version 2.29 stable => x
version 2.27 stable =>
