### ISSUE TITLE
Recovering Parity

### ISSUE THREAD

**Issue by KiwiATC** [paritytech/parity#5982]
How can I recover my account without the recovery phrase. I have my account name, password and address. Everything except the phrase.

**Comment by tomusdrw** [comment]
You either need Recovery Phrase or a JSON key file. Name, password and address are not enough to recover your wallet.
Please see instructions here:
https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring

**Comment by KiwiATC** [comment]
Hi,

 

If that’s the case then I have lost access to the account. Is there anything that can be done? Can you resend my last transaction? My last transaction failed due to lack of gas but I have since added more ether on there. Can you resend the transaction? Should be transaction hash 0xbf553baf1a618c3cd930323287874561780e7c67f4ec0276f6ff5284b9731b00

 

Thanks,

Keegan

**Comment by rphmeier** [comment]
@KiwiATC Sorry, it's impossible to re-send a transaction which has already been included in the chain. Any further transaction would need to be signed by your account, which seems to be lost.
