### ISSUE TITLE
Reduce dynamic dispatches in the database code

### ISSUE THREAD

**Issue by Vurich** [paritytech/parity#5985]
It's not a bottleneck, but it does hamstring us somewhat. For example, the `get_with` method has to incur dynamic dispatches _and_ indirect writes in order to do its work, purely because of the dynamic nature of the databases. We might want to do something simple like making it a `?Sized` type parameter but then always setting the parameter to be `HashDB` or whatever, just as a stepping stone to making it "properly" generic. Just reducing dynamic dispatches is good, but the extra optimisation that the compiler can do as a result is gooder.

**Comment by debris** [comment]
I'm closing this one, cause it is a guideline, not an actual issue.
