### ISSUE TITLE
Migrate to serde 1.0

### ISSUE THREAD

**Issue by debris** [paritytech/parity#5988]
- [x] migrate crates which utilize serde `0.9` to serde `1.0`
- [x] migrate executables which use docopt `0.7` to docopt `0.8`
- [x] migrate toml from `0.2` to `0.4`
- [x] migrate code that uses `rustc_serialize::json::Json`
  - [x] `ethcore/src/miner/price_info.rs`
  - [x] `util/network/src/node_table.rs`

**Comment by 0x7CFE** [comment]
What is the status for this issue? I think I could handle it, if it's not taken.

**Comment by debris** [comment]
I believe we still use `rustc_serialize` in several places

```
ethcore/benches/evm.rs:24:extern crate rustc_serialize;
ethcore/benches/evm.rs:78:      use rustc_serialize::hex::FromHex;
util/network/src/lib.rs:72:extern crate rustc_serialize;
util/network/src/node_table.rs:35:pub use rustc_serialize::json::Json;
```

**Comment by 0x7CFE** [comment]
What about `ethcore/src/miner/price_info.rs`? I couldn't see this path on `master`.

**Comment by debris** [comment]
it was relocated to `price-info/src/lib.rs` and it's already updated and uses serde

**Comment by 0x7CFE** [comment]
Looks like we've finished all of the related work. Should this issue be closed for now?

**Comment by debris** [comment]
yes, definitely!
