### ISSUE TITLE
[FEATURE] HTTPS Wallet for getUserMedia

### ISSUE THREAD

**Issue by louisgv** [paritytech/parity#5990]
In order to initialize getUserMedia API for webrtc locally, it is required that the page be served over https.

Thus, making parity default to https should solve this problem. I believe SSL dev server is also becoming standardize in other front-end ecosystem as well.

@tomusdrw @gavofyork

**Comment by tomusdrw** [comment]
Would need a self-signed certificate (or generate one randomly on the flight).
I think we can have an optional feature like this.

Should be easy to address after migration to latest `hyper` (we already have a dependency on `rust-native-tls`), so will be considered only after that's done (most likely 1.8)

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
