### ISSUE TITLE
Choose Specific Account when Restoring with Parity Phrase

### ISSUE THREAD

**Issue by cstegmann** [paritytech/parity#5994]
When you want to restore an account with a Parity Phrase you cannot choose which of the 6 (i think) accounts you want to use, unlike when you create the account for the first time.

This leads to you having a different avatar/icon and also losing your transaction history.

Currently the only workaround is to restore the account with the parity phrase 1-5 times until you get the account you want back and then you delete the rest.

**Comment by tomusdrw** [comment]
Each Recovery Phrase matches exactly one private key (and one address/account). The icons you see while creating an account are backed by completely different phrases.

Can you tell me more about "Restore the account [...] 1-5 times" - do you get different address while restoring from the same phrase?

**Comment by cstegmann** [comment]
Yes I do, hence the different icons/avatars.

**Comment by tomusdrw** [comment]
@cstegmann What version do you run and what browser? Do you use RPC or the `+ Restore` button in Parity Wallet?

**Comment by cstegmann** [comment]
Parity//v1.6.8-beta-c396229-20170608/x86_64-windows-msvc/rustc1.17.0
Using the + Restore button in the Parity Wallet (website).

**Comment by cstegmann** [comment]
Can't replicate it, will ask a friend who had the same problem to try. Sorry.
