### ISSUE TITLE
Bad display of event boolean

### ISSUE THREAD

**Issue by keorn** [paritytech/parity#5998]
Last element is a bool, but the value (`false`) appears invisible.

![screenshot_2017-07-05_09-26-17](https://user-images.githubusercontent.com/7750981/27855906-219d957a-6164-11e7-9054-9c05e9f8c00d.png)

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
