### ISSUE TITLE
Allow inline comments in peers.txt

### ISSUE THREAD

**Issue by kosullivansita** [paritytech/parity#6004]
It will be useful to be able add comments to entries in peers.txt, particularly for private networks.

example:

```
# This is the validating node, owned by XXX corp
enode://1111-redacted-6eaf@172.0.0.1:30303
# This is another validating node, owned by YYY corp
enode://222-redacted-6eaf@172.0.0.1:30303
# This is a  non-validating node, owned by ZZZZ corp
enode://333-redacted-6eaf@172.0.0.1:30303
```

See also https://ethereum.stackexchange.com/questions/19480/can-i-add-inline-comments-in-peers-txt

**Comment by rphmeier** [comment]
Should just be an additional `.filter(|s| !s.starts_with("#"))` on the lines iterator.
One for @axelchalon?
