### ISSUE TITLE
Parity cannot be installed with `cargo install`

### ISSUE THREAD

**Issue by ranveerkunal** [paritytech/parity#6007]
Installing parity fails:
cargo install --git https://github.com/paritytech/parity.git parity --verbose

<img width="668" alt="screen shot 2017-07-06 at 1 43 54 am" src="https://user-images.githubusercontent.com/83186/27890739-b3cccc30-61ec-11e7-9822-5c415ae541d7.png">

**Comment by bgort** [comment]
Same issue here.

**Comment by bgort** [comment]
I was able to get it installed by using the 'Build from source' install method:

```
# download Parity code
$ git clone https://github.com/paritytech/parity
$ cd parity

# build in release mode
$ cargo build --release
```

**Comment by rphmeier** [comment]
@ranveerkunal Ensure you have at least Rust 1.18.0. Run `rustup update stable` if you're not sure.

**Comment by Vurich** [comment]
Does `cargo install` take `Cargo.lock` into account? We depend on some git repositories where the head of master is incompatible with the version we use.

**Comment by 5chdn** [comment]
Will check the docs and clarify this.
