### ISSUE TITLE
Pin unpinned git dependencies

### ISSUE THREAD

**Issue by Vurich** [paritytech/parity#6008]
Dependencies on git master branches are easy to break, even more so than wildcard dependencies. We control all the crates we have git dependencies on, but it's still easy to accidentally break the build by committing something bad to any of the crates we depend on transitively. I'd advocate for either "proper" crates.io semver dependencies, git submodules combined with local (`path = ...`) dependencies, or git dependencies pinned to specific tags or commits. The latter is the easiest to migrate to, but the submodule method is the easiest to maintain.

**Comment by debris** [comment]
I opt for pinning dependencies to specific tags

**Comment by arkpar** [comment]
Dependencies are effectively pinned already in `Cargo.lock`. Changing things in dependency repo won't break build for parity unless you do `cargo update` . You can also run `cargo update -p <package> --preciese <commit>` to pin to a specific commit.

**Comment by Vurich** [comment]
`Cargo.lock` is very coarse-grained, though. You can't update one dependency without them all updating to the current master. Not to mention the documentation aspect.

**Comment by arkpar** [comment]
`cargo update -p` does exactly this, updates a single dependency.

**Comment by Vurich** [comment]
Ok sure, but it's still a significant footgun with no real upside

**Comment by Vurich** [comment]
Yep, so I just shot myself in the foot with this. I had cleared out my `Cargo.lock` (yesterday morning, before realising we had unpinned dependencies) to update my git dependencies and just now I hit a compilation failure because `jsonrpc` had been updated to an incompatible version. I'm going to post a PR to pin all these dependencies.
