### ISSUE TITLE
Web app is extremely slow in Safari

### ISSUE THREAD

**Issue by paulmillr** [paritytech/parity#6011]
The web app simply stucks forever in Safari. Like there's some crazy background loop. Not sure how to debug this.

Reproducible on any Safari w the latest MacOS. Seems to work just fine in Chrome.

**Comment by 5chdn** [comment]
Can you confirm that the wallet is slow in Safari while it's running fine with Chrome _at the very same time_?

**Comment by 5chdn** [comment]
#6387
