### ISSUE TITLE
Transaction not showing up in blockchain

### ISSUE THREAD

**Issue by Pwnmanship** [paritytech/parity#6013]
Using 'eth_sendTransaction' of parity to send coins.
We get back a transactionid/hash but even after a few days the transaction is still not in the blockchain.
Other transactions before and after this transaction are in the blockchain and all are using more then high enough fee and gas.

**Comment by keorn** [comment]
Did you use the Signer in the UI? How are you submitting your request?

**Comment by Pwnmanship** [comment]
By rpc, when I the 'eth_getTransactionByHash' rpc call afterwards (don't know if I can try this instantly) it gives back an empty response for the transaction like it doesn't exist.

**Comment by keorn** [comment]
You need to sign a transaction using the [Signer](https://github.com/paritytech/parity/wiki/Parity-Wallet).
Otherwise there is `personal_sendTransaction` where you provide a password and no Signer is necessary.

**Comment by Pwnmanship** [comment]
But why wouldn't eth_sendTransaction suffice? I send 90% of my coins with that call.

**Comment by 5chdn** [comment]
But you need to sign the transaction. Parity only can do it if you either use the signer (UI) or unlock the account manually (not recommended).
