### ISSUE TITLE
Ethereum not showing up in wallet

### ISSUE THREAD

**Issue by ecrump4** [paritytech/parity#6014]
I'm very new to Parity  and have been experiencing issues when I tried sending some ethereum from my Bittrex account to my Ether wallet. The transaction has gone through according to Bittrex and yet there has been no Ether deposited. I realized after the fact that my account had not been verified at the time i sent the ether. if I verify the account now will it still be connected to the same address? On a side note, im wondering what this gas price has to do with the verification process and how you are supposed to verify a wallet if there isn't any ether in it. Help would be greatly appreciated.

**Comment by keorn** [comment]
There is no need to verify an account to use Parity. Can you post a transaction hash from Bittrex?

**Comment by ecrump4** [comment]
How would I find the hash?

**Comment by keorn** [comment]
Bittrex should display it in your withdrawal history, if not then get in touch with their support.

**Comment by ecrump4** [comment]
So I see both the address and the TxId number in bittrex and the address matches the one for my Parity Wallet. I also see a Uuid in my Parity wallet, could this have something to do with it?

**Comment by 5chdn** [comment]
Which version of Parity is that? Are you fully synchronized? Are you connected to any peers?

**Comment by pierreDev33** [comment]
Hello,

I have exactly the same problem, I sent some ethereum from my Bittrex account to my Parity Ether wallet. The transaction has gone through according to Bittrex and etherscan.io  yet there has been no Ether deposited. When I enter my Parity wallet adress at etherscan.io, everything looks good (I see the transaction with the right amount).

In Parity I only see one transaction I did 2 months ago.

 I'm running:
>
> - **Parity version: Parity//v1.6.10-stable-1a5b176-20170721/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows
> - **And installed**: via installer

14.68% warp restore  -   homestead   - 14/25 peers

Thanks for your help.

**Comment by 5chdn** [comment]
@pierreDev33 you need to wait until your wallet is fully synchronized.

**Comment by girraficlife** [comment]
Hello, 

I have a similar issue. I signed up for parity because I thought it would be a straight forward way to request and bid for domain names on the ethereum name service. I transferred ethereum to my parity account and its is not showing up in my account. 

Parity//v1.6.10-stable-1a5b176-20170721/x86_64-macos/rustc1.18.0

13.98% warp restoreHOMESTEAD25/25 peers
