### ISSUE TITLE
Ether not showing up in wallet

### ISSUE THREAD

**Issue by JediJuice** [paritytech/parity#6019]
I am new to this and maybe I am doing something wrong. I had a few bucks in ether and sent some to the wallet. It has been over 40mins, I tried to reinstall with the new commits but still nothing. What should I do now? Not sure, but is this a problem ( 3,984,791/3,993,330 syncing )?

**Comment by keorn** [comment]
Yes, your node needs to finish syncing to see the latest state (and most likely your transfer).

**Comment by JediJuice** [comment]
What is the command to speed that up using a mac from the terminal?
