### ISSUE TITLE
Can't visit UI if Parity use --geth to set geth mode

### ISSUE THREAD

**Issue by myqq0000** [paritytech/parity#6021]
I use --geth to set Parity to geth mode. Because I want to use personal.unlockAccount and unlock an account permanently.(If don't set geth mode, it can't unlock permanently... which mentioned in this issue.)

But when I use --geth when I start my Parity. I can't visit my Parity UI... Before I set it, I can visit it with `localhost:8180`. But after I set it, I can't visit it with `localhost:8180` or `127.0.0.1:8180` even `10.4.20.69:8180`... How can I find back my webUI under geth mode? Thanks a lot.

This is my config:

```
[parity]
chain = "HyperAlbum-chain.json"
base_path = "node0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "10.4.20.69"
[ui]
port = 8180
[dapps]
port = 8080
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00765Cc7584E3Ed11aE092b74d10AE2cE875aEAb"
reseal_on_txs = "none"
usd_per_tx = "0"
```
Thanks a lot. :)

**Comment by 5chdn** [comment]
Can reproduce this. `--geth` mode somehow makes the UI inaccessible. 

However, you do not need `--geth` to use the `personal` api. Did you try it without the geth flag yet?

**Comment by tomusdrw** [comment]
Please run with `--geth --force-ui`
