### ISSUE TITLE
Registering a new erc20 token in the Parity Token Registry.

### ISSUE THREAD

**Issue by dsxxxx** [paritytech/parity#6022]
Hello Parity,

We would like to register our newly created token within the Parity Token Registry. Please can I ask for your instructions as-to how this might be achieved? Many thanks.

**Comment by 5chdn** [comment]
Yes, this needs instructions. As per #5852 

For now, go to Applications, find the token registry, click 'register' and follow the instructions. If you have any further questions, ask them here.

**Comment by Ranguna** [comment]
+1 on this. I created a smart contract token and when I try to add it to the registery it says "The address is not a regular token contract address".

I have all the standard ERC20 functions and events.

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity/wiki/Token-Registry

**Comment by Samyoul** [comment]
I'm attempting to register the following token contract on the main-net registry https://etherscan.io/address/0x2c3c1f05187dba7a5f2dd47dca57281c4d4f183f .

However I get the following error:

`The address is not a regular token contract address`

The contract has all standard ERC-20 methods plus some additional methods. Does the token have to match and ERC-20 interface exactly? If so why?

**Comment by matt93310** [comment]
Hi, I am having the same problem here, with the same message  "The address is not a regular token contract address". but It is for coins that I am supposed to receive 
Please see below
https://etherscan.io/tx/0x546e264ea5952199f5845fa01d5796fe3bde24918801a0bb8a97c0c72e23a166

Any idea?
Thanks guys

**Comment by iam-peekay** [comment]
Any resolution on this?

**Comment by 5chdn** [comment]
Just read #6794
