### ISSUE TITLE
Error during compilation: fatal runtime error: failed to initiate panic, error 5

### ISSUE THREAD

**Issue by adrianbrink** [paritytech/parity#6024]
Hi,

I am trying to install parity from source on Ubuntu 16.04.

However I am getting the error:
```
fatal runtime error: failed to initiate panic, error 5
error: Could not compile `ethcore`.
```

Any ideas why that happens?

**Comment by 5chdn** [comment]
No, could you share how you are installing it and share the full log?

**Comment by rphmeier** [comment]
(would downgrade it to bug as the panic is in `rustc` and not Parity)

**Comment by sjeohp** [comment]
FWIW I can build on 16.04 with either Docker or VM with no trouble.
