### ISSUE TITLE
Skip transaction fee for specific addresses

### ISSUE THREAD

**Issue by artjoma** [paritytech/parity#6026]
Guys, how I can specify the list of addresses(specific addresses) that do not pay the transaction fee? I use POA private network with validator contract. Can Parity team provide this functionality in validator contract or maybe it will be a new specific contract?

`function excludeFeeFor() constant returns (address[]) {
        return excludeAddrArr;
 }`

**Comment by rphmeier** [comment]
There is a workaround, although it's a little complicated:
1. deploy a contract with a `function certified(address) returns bool` that returns true for any zero-fee senders.
1. deploy a name registry contract with a `getAddress` function [like this](https://github.com/paritytech/contracts/blob/master/Registry.sol#L22)
1. the name registry should return the address of the first contract for the name "service_transaction_checker"

**Comment by artjoma** [comment]
Cheers mate!
