### ISSUE TITLE
TokenRegistry allows scammers to hijack the token registration

### ISSUE THREAD

**Issue by dip239** [paritytech/parity#6030]
# Problem
Actual `TokenRegistry` allows any person to create an registration record and makes the perso to registration record owner and thus to give him full and exclusive control about essential information about the token, which parity user relays on. 
It creates an attac vector for scammer. 

# Solution
Many token contracts are owned (where owner is trusted account to perform administration tasks around the token). A `TokenRegistry ` contract could try to read owner property of the target token account and make it to co-owner of the registration record too.

**Comment by 5chdn** [comment]
Valid concerns and the token registry overhaul is long overdue.

**Comment by rstormsf** [comment]
Here is the problem: 
1)In my token ERC20 contracts, I reassign an owner to crowdsale contract.
2)Some people use Ownable.sol `owner == msg.sender` some other TokenController.sol `controller == msg.sender `. So there is no way to know which contract is used to check ownership. 

What we can do, however, is to find the creator of the contract and check the ownership.

**Comment by 5chdn** [comment]
Should be tracked in Parity-Contracts

https://github.com/paritytech/contracts/issues/110

**Comment by sorpaas** [comment]
Migrated to https://github.com/parity-contracts/token-registry/issues/3
