### ISSUE TITLE
Get respone 'Method not found' when run signer_requestsToConfirm with curl

### ISSUE THREAD

**Issue by zhangdongbo** [paritytech/parity#6034]
version:  version Parity/v1.6.7-beta-e128418-20170518/x86_64-linux-gnu/rustc1.17.0

Parity is run as below in local machine and sync is finished:
` parity --max-peers 30 --jsonrpc-port 8888 --jsonrpc-hosts all --jsonrpc-interface all --db-path ./database/db `

Run below command:
```
$ curl --data '{"method":"signer_requestsToConfirm","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8888
```
Got below result:
`{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":null},"id":1}`

**Comment by tomusdrw** [comment]
`signer_*` methods are not exposed via jsonrpc by default. You need to run with `--jsonrpc-apis web3,eth,pubsub,net,parity,parity_pubsub,traces,rpc,secretstore,signer` to expose it.

**Comment by liuhongjiang** [comment]
would you update the wiki correspondingly?

**Comment by tomusdrw** [comment]
@liuhongjiang What exactly do you have in mind? There already is a note that some APIs are not available by default: https://github.com/paritytech/parity/wiki/JSONRPC#enabled-apis-default

Also different transports (IPC, HTTP, WebSockets) have different list of exposed APIs - the defaults are listed in help.

**Comment by liuhongjiang** [comment]
@tomusdrw sorry for the misunderstanding, I mean, maybe should `signer` be added to this line:

```
Possible name are all, safe, web3, eth, net, personal, parity, parity_set, traces, rpc, parity_accounts.
```

**Comment by tomusdrw** [comment]
Oh, fair point. Wiki updated will prepare a PR to update help as well.

**Comment by liuhongjiang** [comment]
may us have the honor to do this contribution?

**Comment by tomusdrw** [comment]
@liuhongjiang Sure!
