### ISSUE TITLE
windows command line

### ISSUE THREAD

**Issue by panicape** [paritytech/parity#6040]
Does anyone knows how to choose the blockchain to use? i'm currently using a node in linux but in windows i just installed and i can't configure anything. By command line it doesn't identify parity

**Comment by akae33** [comment]
same thing here, can't get the command line to accept "parity"

**Comment by 5chdn** [comment]
In windows it's `parity.exe`

You might have to change directory first `cd "C:\Program Files\Ethcore\Parity\"` and then execute `parity.exe` with your favourite flags. In addition, you can create a config file, see https://github.com/paritytech/parity/wiki/Configuring-Parity#config-file
