### ISSUE TITLE
parity.exe won't start

### ISSUE THREAD

**Issue by akae33** [paritytech/parity#6042]
when i try to start the Parity exe from within the ethcore folder it opens a cmd window for one sec and then nothing

**Comment by 5chdn** [comment]
Could you open a command prompt and start parity from within that?

1. click the start button
2. directly type `cmd`
3. change directory `cd "C:\Program Files\Ethcore\Parity\"`
4. execute `parity.exe`

And share the output here? (screenshot / copy-paste)

**Comment by akae33** [comment]
thanks for the quick Answer. With that i get it to work, except for the lock file


~ 
Christoph Herrmann 
Bühneninspektor ~ stagemaster 
cherrmann1@dresden.de
T +49 351 3 20 42 743 ~ T +49 176 63 25 09 84

tjg. theater junge generation 
Kinder- und Jugendtheater Dresden ~ theatre for children and young audiences 
Kraftwerk Mitte ~ Wettiner Platz 1 ~ 01067 Dresden 
Postanschrift ~ Postfach 12 00 20 ~ 01001 Dresden 
Tickets und Info +49 351 3 20 42 777 ~ tjg-dresden.de <http://tjg-dresden.de/> 

Premieren März/April 2017
Mi 08. Mrz 2017 ~ Wind <http://www.tjg-dresden.de/premieren.html> UA ~ Jugendliche spielen für die Allerkleinsten ~ 2+ 
Sa 08. Apr 2017 ~ Deportation Cast <http://www.tjg-dresden.de/premieren.html> ~ von Björn Bicker ~ spartenübergreifend ~ 14+ 
Do 20. Apr 2017 ~ Auerhaus <http://www.tjg-dresden.de/premieren.html> ~ von Bov Bjerg ~ Schauspiel ~ 14+ 
Fr 28. Apr 2017 ~ Tage der Freiheit 1 <http://www.tjg-dresden.de/generator.html> ~ spartenübergreifend ~ 16+ 
Sa 29. Apr 2017 ~ Tage der Freiheit 2 <http://www.tjg-dresden.de/generator.html> ~ spartenübergreifend ~ 16+

**Comment by 5chdn** [comment]
Your Parity is probably already running. Do you see the tray icon or the process in task manager?
