### ISSUE TITLE
ipfs-api - does not respond to eth-storage-trie CID

### ISSUE THREAD

**Issue by kumavis** [paritytech/parity#6043]
trying to lookup the state trie nodes for a contract's storage via the `eth-storage-trie` CID type fails with `CID codec not supported`

it does work with `eth-state-trie`

ethereum's IPLD resolvers differentiate between `block->account` and `account->storage` tries to help resolve the leaf types

**Comment by kumavis** [comment]
cc @maciejhirsz

**Comment by 5chdn** [comment]
According to #4545 `eth-storage-trie` is not implemented yet. See also: https://github.com/paritytech/parity/wiki/IPFS#implementation-status

Since #4172 is still open I would like to keep this conversation over there, if you don't mind.

**Comment by kumavis** [comment]
thanks/ didnt know about the wiki, nice
happy to keep it in one ticket
