### ISSUE TITLE
Parity with rinkeby testnet

### ISSUE THREAD

**Issue by kgcorps** [paritytech/parity#6045]
I'm trying to run parity so that it would connect to rinkeby testnet, so far I've installed the client (version: version **Parity/v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0**). Converted my rinkeby genesis block config using this as input: https://www.rinkeby.io/rinkeby.json and using this tool mentioned on the github wiki page: https://github.com/keorn/parity-spec. Which resulted in this config file: https://gist.github.com/kgcorps/3b67338bc5ea204372f993ed25389e88

When trying to start parity with the following command: 
`parity --chain=res.json --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303 --identity=kgcorps --datadir=$HOME/.rinkebyParity
`
I have hunch I've made stupid mistake somewhere with the config conversion. The source config is good to go since I've used it with geth without any problems.

**Comment by keorn** [comment]
That tool is only for Ethash (PoW engine), rinkeby PoA algorithm is not supported by Parity.

**Comment by kgcorps** [comment]
So my only option in order test various scenarios such as internal transaction tracking, smart contract deployment/testing could be achieved only using **dev** mode of the parity client? Due to the fact that in the other testnets coming by test eth is fairly difficult.

**Comment by keorn** [comment]
There is also `kovan` and `ropsten`

**Comment by 5chdn** [comment]
https://github.com/goerli/testnet

**Comment by thefallentree** [comment]
You can now join rinkeby with parity, with my version of parity: https://github.com/thefallentree/parity-clique , just download , build and run parity --chain rinkeby
