### ISSUE TITLE
Epoch transitions for tendermint chains

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#6046]
1. `epoch_end_signal` function which functions the same as `authority_round`
2. `is_epoch_end` function which checks if there is a pending transition for current block.
3. finality proof is simply the block header with a valid seal under the given validator set
4. `snapshot_components` that returns `PoASnapshot`.

Warp sync will now work seamlessly for contract-based tendermint chains.

**Comment by feynmanliang** [comment]
Would this task be appropriate for a first-time contributor? I'm willing to invest some time ramping up.

**Comment by 5chdn** [comment]
@feynmanliang yes, the [Q2-Easy](https://github.com/paritytech/parity/labels/Q2-easy) label is to encourage first-time contributions.
