### ISSUE TITLE
Support iteration over both buffered and unbuffered database entries

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#6048]
Currently only flushed data is iterated over. I can mentor.

I wrote a little crate that may help: https://crates.io/crates/interleaved-ordered

**Comment by efyang** [comment]
I'd be interested in taking this issue. What general part of the repo would this involve?

**Comment by debris** [comment]
`util/kvdb-rocksdb/src/lib.rs`

**Comment by efyang** [comment]
So basically we just want to interleave both `Database.overlay` and `Database.flushing` into [`iter`](https://github.com/paritytech/parity/blob/master/util/kvdb-rocksdb/src/lib.rs#L513)?

**Comment by debris** [comment]
closed in #7048
