### ISSUE TITLE
The --no-color option is only partly implemented

### ISSUE THREAD

**Issue by hiqua** [paritytech/parity#6052]
The --no-color option implemented in #1135 no longer covers all output by the parity CLI. An example of output not covered is:
`./parity signer new-token`
which uses white and bold styling by running
`Colour::White.bold().paint(...)`
instead of redefining paint and using
`paint(Colour::White.bold(), ...)`
as has been done in a0bc1f9dae00ee8a84bd466632b78862970caf89.

**Comment by Vurich** [comment]
Can this be closed now?
