### ISSUE TITLE
WASM: Solidity->wasm compiler 

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#6055]
1. For legacy contracts
2. Actually, solidity performance can be increased dramatically by tools like binaryen which can optimize wasm to produce faster wasm. Also, many uses of 256-bit operations can be avoided.
  
Pretty standalone task.

**Comment by Vurich** [comment]
Could we write an EVM->WASM compiler instead? That might be simpler since you don't need to have a "real" parser and you could just do a basic one-one translation and let binaryen clean up the garbage.

**Comment by NikVolf** [comment]
But you will have to use 256-bit word size where you could have avoided by compiling Solidity directly on the first place. I haven't research it in details, maybe it's not an issue though.

**Comment by Vurich** [comment]
We'd need to emulate 256-bit arithmetic either way, right? We can just convert mathematical operations to a call to a shim function that gets linked or compiled into the binary, which would avoid having to set a huge word size.

**Comment by Lbqds** [comment]
hey guys,
now eWASM was supported in parity1.17, and I have a question:
how to deploy and call wasm contract in parity, what is the different with deploy evm contract?
thanks

**Comment by Lbqds** [comment]
@NikVolf 
Hi, is there any other method compile contract to wasm?
Now parity1.17 support ewasm, if I want to deploy wasm contract, how can I trans evm contract to wasm?
thanks

**Comment by NikVolf** [comment]
@Lbqds 
Hi, please see 
https://github.com/paritytech/wasm-tests for contracts and api usage examples

You can use Rust for contract source, you don't need to transcompile evm

**Comment by Lbqds** [comment]
@NikVolf 
Thanks for your reply. 
I saw the wasm-tests and parity/ethcore/wasm/* file. The way of call contract is put contract's address and args into wasm memory, it will find contract code in state storage. But I still have a question.

If solidity compiler support wasm, I can write contract with solidity and compile it to wasm. Then, I can use eth_sendTransaction jsonrpc method deploy it and call contract with hash of function signature.

But if I write contract with Rust or C/C++, and compile to wasm, if I can deploy and call contract just like solidity? I means the function signature maybe different.

**Comment by NikVolf** [comment]
Oh, it's up to ABI, which is still in development. The ABI will be pretty much compatible with Solidity.

For now, if you like experiments, you can manually inspect incoming arguments (which is just a array of bytes) and dispatch according to the method hash in the main entry of the contract, `call` function.

I will add an testable example in a bit to show the above in code

**Comment by Lbqds** [comment]
@NikVolf 
Get it, thank you very much. :+1:

**Comment by debris** [comment]
that's an epic task an I believe that it should not be a part of our issue list at parity repo, as it is most likely a standalone project

**Comment by drgorb** [comment]
there is an effort underway https://github.com/hyperledger-labs/solang
