### ISSUE TITLE
Cannot Access Parity User Interface

### ISSUE THREAD

**Issue by hiroprotagonist2000** [paritytech/parity#6058]
Hi,

I am new to Parity and recently opened an account. Two days ago, I was able to login via  http://127.0.0.1:8180/ (as describes on the Basis Usage site: https://github.com/paritytech/parity/wiki/Basic-Usage)

I am no longer able to access this website. How can I connect to my Parity User interface?

Many thanks in advance!

**Comment by 5chdn** [comment]
Which version of parity is this? Which operating system? Do you see any specific error messages?

**Comment by paleov** [comment]
If you run parity with `-d /foo` then `parity signer new-token` will not generate a valid secure token.  you must run `parity -d /foo signer new-token`
