### ISSUE TITLE
Cannot transfer ETH to smart contract

### ISSUE THREAD

**Issue by nosuchip** [paritytech/parity#6067]
I have smart contract deployed [there](https://ropsten.etherscan.io/address/0xdbf07450d66d3739b9490d1bc3121e0cd81cf220), source code provided below. Contract deployed via Remix connected to locally running Parity that is Ropsten node (command line is `parity --chain=ropsten --author=0x9cA70053E6D3663814B491638B7D5ed1B9AB14b6 --rpcapi="web3,eth,personal" --jsonrpc-interface=127.0.0.1 --jsonrpc-port=8545 --jsonrpc-cors="https://remix.ethereum.org"`)

I can transfe ETH to contract (and get desired random numbers) via Remix ([this](https://ropsten.etherscan.io/tx/0xc166ada00adb34a6e0820d48aacf3d9114340dd157bba73cf9cd89a45d1de437) is original transaction and [this one](https://ropsten.etherscan.io/tx/0x643a12b09772d1b05d2de9507fc561f0a18f4be075bdfda77b60df93c433ef92) is oraclize.it callback). And it called successfully via web3: `RandomContractInstance.update({from: '0x007f621a451bD6836adB215685219C4881687830', value: 1000000000000000})` (maybe it is incorrect, IDK how to transfer ETH to contract other ways), [original transaction](https://ropsten.etherscan.io/tx/0x7e1d4b374149e6c6e62070f5d9930e19bf2363a937d50cb31a134dc30997e68e) and oraclize.it [callback](https://ropsten.etherscan.io/tx/0x1e7ffb7499043647070d8ad3a16984c63c3727712af76069e4c332596ff99ff7).

But when I am trying to send money via Parity web UI I always got an error like [this one](https://ropsten.etherscan.io/tx/0xe585f249c46ad0c6231f1aa8f187a522f5e98aa067d84e7db0cc41ac7598c56e). Generally almost all canceled transactions was made through Parity UI.

```
pragma solidity ^0.4.0;

import "./oraclizeAPI_0.4.sol"; // Provided in Remix as second SOL file

contract GetRandom is usingOraclize {
    event newRandomNumber(bytes);
    event numbers(uint n1, uint n2, uint n3);

    function GetRandom() {
        oraclize_setProof(proofType_Ledger);
    }

    function __callback(bytes32 _queryId, string _result, bytes _proof) oraclize_randomDS_proofVerify(_queryId, _result, _proof) {
        // if we reach this point successfully, it means that the attached authenticity proof has passed!
        if (msg.sender != oraclize_cbAddress()) throw;

        bytes memory n = bytes(_result);

        numbers(uint(n[0]), uint(n[1]), uint[n2]);
        newRandomNumber(bytes(_result));
    }

    function update() payable {
        uint N = 3; // number of random bytes we want the datasource to return
        uint delay = 0; // number of seconds to wait before the execution takes place
        uint callbackGas = 200000; // amount of gas we want Oraclize to set for the callback function

        // this function internally generates the correct oraclize_query and returns its queryId
        bytes32 queryId = oraclize_newRandomDSQuery(delay, N, callbackGas);
    }
}
```

**Comment by nosuchip** [comment]
It seems that problem with "transferring" ethers. Remix performs just "call" to a `payable` function meanwhile funds transfer failed.

**Comment by Neurone** [comment]
Via Remix and via web3 you are calling correctly the contract method "update". In the latter case, you use Parity to simply **transfer** funds (please note tx details: input data is void) but the contract does not have a proper fallback function so the transfer fails. If you want to correctly use Parity UI to interact with a contract go to "Settings", enable "Contracts", go to "Contracts" and use "Watch" feature. Once the contract is referenced in Parity UI, you can correctly call the update method from there also.

**Comment by 5chdn** [comment]
Exactly, in laymen's terms, the contract basically has no idea what to do with your ether unless you explicitly tell by providing a function signature. I didn't check, but `0xa2e62045` is probably the `update()` function. To execute it, just provide it via the data load of the value transfer transaction.

If you have any further questions, please let me know.
