### ISSUE TITLE
Remove "logs", "postStateRoot", "out" from state integration tests

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6070]
corresponding tests repo pr: https://github.com/ethereum/tests/pull/232

state tests parser: https://github.com/paritytech/parity/blob/8404edb656693270ec1cd3956d204f625d28ec7c/json/src/state/state.rs#L24-L44

**Comment by arkpar** [comment]
Already implemented in https://github.com/paritytech/parity/blob/master/json/src/state/test.rs#L50
