### ISSUE TITLE
Engine generic over state machine

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#6073]
Goal: decouple consensus rules from transaction/block processing rules.

`Engine` -> `Engine<T: machine::Machine>`. We can bound the `Machine` trait further for `Engine` implementations to enable self-referential consensus (like contract-based PoA).

A primary implementation of the `Machine` trait would be the `EthereumMachine`, but we can make this itself generic over a VM (EVM or WASM or EWASM or ...) cc @NikVolf as discussed.

A `Machine` should define its own `Block`, `Header` and `Transaction` types. Preparing a sufficiently general `Client` to handle all `Machine`s would probably be intractable at this time, so I'd opt to have it specify a `Client` type as well.

**Comment by NikVolf** [comment]
https://github.com/paritytech/parity/pull/6591

related, is it done?

**Comment by rphmeier** [comment]
Yep, that addresses all the important points of this issue.
