### ISSUE TITLE
Existing parity account's index incremented on new account creation

### ISSUE THREAD

**Issue by D-Nice** [paritytech/parity#6077]
Whenever a new account is added, it seems to be prepended to the account list, rather than appended, causing all current accounts to shift. This appears to be an odd design decision, as it has caused confusion for myself and a number of other people I have seen, as I may expect a certain account to be at index 2, but it is no longer there because it was shift, but I don't know if there is some specific purpose to this that I am not aware of.

**Comment by 5chdn** [comment]
Are you talking about RPC or UI?

**Comment by D-Nice** [comment]
Via the UI

**Comment by 5chdn** [comment]
You can sort accounts by tags, name, and balance already with the button on the top right.

**Comment by D-Nice** [comment]
Ah ok, so they can indeed be reordered then, and it affects the way they are sorted in web3.eth.accounts?

**Comment by 5chdn** [comment]
No, as far as I am aware this is only affecting the user interface.

**Comment by D-Nice** [comment]
Sorry, I was speaking in regards to the ordering within web3. If an account is added via the UI or other methods, all existing accounts have their index incremented, and the new account is inserted at index 0, which seems counter-intuitive as I think most expect it to be appended to the list instead, and that previous accounts keep their indices intact. This is moreso a suggestion, but again, there may be implications if you choose to change it now, after already implementing it the other way, but walking people through parity, it has caused confusion a number of times already.

**Comment by 5chdn** [comment]
The output of eth.accounts is sorted alphabetically. Just tested by creating accounts both via RPC and UI. The index does not get incremented, but the full list gets reordered.

**Comment by D-Nice** [comment]
Ok, thank you for the clarification and taking the time to test!

**Comment by D-Nice** [comment]
I'm reopening this issue, because I'm working with something again where we're utilizing parity and creating accounts, and it seems even more counter-intuitive, than what I had initially though was a simple prepending of accounts, to actually resort them alphabetically. Why wasn't a simple method of appending just chosen to allow for reliable and consistent account indices?

**Comment by 5chdn** [comment]
Not sure what you are trying to do, but how can you ever be certain that account you are looking for is behind that very same index in your request? Even if we had this feature, I do not see how this could be of any use for you. Why don't you just use the address instead of the index?
