### ISSUE TITLE
Hardware wallets don't support signing arbitrary messages: "Unknown binary data"

### ISSUE THREAD

**Issue by iRomain** [paritytech/parity#6083]
I'm using Parity/1.6.8/1.17.0/ma
I'm using the latest Parity Chrome extension
I'm using a Nano Ledger S with Ethereum app v1.0.8
I'm browsing the Dapp https://etherdelta.github.io

If I try to place a buy or a sell order on a pair, I get the following error and I cannot confirm request (it doesn't even come up on the nano like it should do)
![screen shot 2017-07-18 at 18 43 21](https://user-images.githubusercontent.com/3155568/28329236-69d683e4-6be9-11e7-9b99-0ff601c355ac.png)

When I go to my parity UI, I can see in the signer this request and when I try to confirm it from there, it throws the error "[-32021] Account password is invalid or account does not exist." while the expected behaviour is to prompt on my hardware wallet to confirm transaction.
![screen shot 2017-07-18 at 18 52 12](https://user-images.githubusercontent.com/3155568/28329504-543ebf32-6bea-11e7-9270-730a872a9aad.png)

To be noted that I can fill existing buy or sell orders, but cannot place them. It works like a charm with the default parity wallet without using a hardware wallet.

**Comment by 5chdn** [comment]
Just to make sure, is contract support enabled on your ledger?

Does your ledger show up in accounts list as colored identicon or gray?

**Comment by iRomain** [comment]
Yes contract support is enabled. Ledger shows up as a colored icon.
Food for thoughts: I believe Etherdelta handles placing a buy/sell order differently than actually buying or selling into an existing order. It seems like it's not doing a transaction but rather authorizing Etherdelta to make this transaction later. @frenchhoudini could help understand this.

**Comment by zackcoburn** [comment]
Correct. Placing an order on EtherDelta involves signing a message, whereas
trading against an existing order involves sending a transaction.

**Comment by alfiehub** [comment]
I also have the experience the same problem using Parity 1.7.0 and EtherDelta.
If anyone has any pointers to where the problem might lie I'll be glad to help out.

**Comment by tomusdrw** [comment]
Looks like hardware support for signatures is missing, somewhere over here:
https://github.com/paritytech/parity/blob/604ea5d684b05f63ab2a32f68fdf50b8bbe38498/rpc/src/v1/helpers/dispatch.rs#L516

I'll have a look.

**Comment by tomusdrw** [comment]
Since the hardware wallets don't support signing arbitrary messages yet it's not possible to implement that.
Please re-open if the hardware supports this.

**Comment by btchip** [comment]
It should support personal signing (see https://github.com/LedgerHQ/ledger-node-js-api/blob/master/src/ledger-eth.js#L113) - is this what you're looking for ?

**Comment by arkpar** [comment]
@btchip Interesting, this could use some documentation at https://raw.githubusercontent.com/LedgerHQ/blue-app-eth/master/doc/ethapp.asc

What is the minimum required eth app version that supports this? Is the message presented on the device display hex-encoded?

**Comment by btchip** [comment]
that's right, I'll update the documentation. This message has been added into version 1.0.8 - the device displays a sha256 hash of the encoded message (to handle the case where a long binary message is sent)

**Comment by 5chdn** [comment]
This is not limited to hardware wallets, isn't it?

![normal](https://files.gitter.im/paritytech/parity/XDpB/ed1.PNG)

**Comment by mrbrdo** [comment]
This is crucial to support using EtherDelta with Ledger Nano through Parity (I don't think there is any other alternative right now to use ED with a hardware wallet)!

👍  @arkpar

**Comment by niklasad1** [comment]
Update, I got it working but it will take some time to get it `PR` ready!
