### ISSUE TITLE
Civic contract showing in Etherscan, tokens not in Parity

### ISSUE THREAD

**Issue by mjbayly** [paritytech/parity#6089]
Hi there - my contract has been executed in etherscan, but the tokens aren't showing in Parity:
https://etherscan.io/address/0x001c933cef167204216c3ad6934d310dcc064c18#tokentxns

You can see in the below screenshot, i've searched the contract address for my wallet address and nothing is showing as a balance. I've tried to execute the contract by sending null, but this hasn't changed the situation. Is anyone able to help me troubleshoot? Thanks
![image](https://user-images.githubusercontent.com/29106686/28359222-9a8ec05a-6cc5-11e7-9f47-e11e9fd68745.png)

**Comment by 5chdn** [comment]
Is the civic token registered with the token registry dapp?

**Comment by mjbayly** [comment]
Yes, from what I can see it's correct. Any ideas?
![image](https://user-images.githubusercontent.com/29106686/28361607-6b0a6b88-6ccd-11e7-9b00-b359e3583cc7.png)

**Comment by 5chdn** [comment]
Could you provide me with the civic contract address? I'll check the registry.
