### ISSUE TITLE
Log Description

### ISSUE THREAD

**Issue by deanstef** [paritytech/parity#6091]
Hi all, 
could someone explain me the meaning of all informations printed by nodes on log?
e.g. 
`Imported #191 d108…633a (0 txs, 0.00 Mgas, 4.65 ms, 0.56 KiB)`
`2017-07-18 03:04:12     2/25 peers   101 KiB db  170 KiB chain  0 bytes queue   29 KiB sync  RPC:  0 conn,  0 req/s, 15657 µs`

Thanks

**Comment by 5chdn** [comment]
- `Imported` means the network broadcasted a new block, `Syncing` means it's still catching up with the global status
- `#191` is the number of the imported block, and `d108…633a` the truncated hash.
- `0 txs` is the number of transactions included in this block, `Mgas` the number of used gas, followed by the processing time and block size.

---

- `2017-07-18 03:04:12` is the current date and time
- `2/25 peers` means you are connected to two peers and configured a minimum of 25 (default)
- `101 KiB db 170 KiB chain 0 bytes queue 29 KiB sync` is your client's current memory footprint
- `RPC: 0 conn, 0 req/s, 15657 µs` is the number of RPC connections, the number of RPC requests per second and the approximated roundtrip time for a single request
