### ISSUE TITLE
i can't do any transaction

### ISSUE THREAD

**Issue by panicape** [paritytech/parity#6097]
chain=kovan
I just validate my account through sms-verification and i tried to do some transaction in kovan chain and ask for eth in kovan (i receive them) and then i'm trying to deploy contracts or doing transactions and it says that the password is wrong or the account don't exists but i'm sure that is correct. i check that it wasn't some keyboard problem.
what i can do in this case?
thanks so much for them that can help me

**Comment by 5chdn** [comment]
You can use the wallet to check your password:

- click the account
- click password
- test password

If this does not match your entry, you probably did something wrong. Feel free to create a new account and ask me here or on gitter for kovan ether.
