### ISSUE TITLE
Suggestion: If sending tokens from a wallet that contains more than one type of token,  force the user to choose a token type rather than defaulting to ETH

### ISSUE THREAD

**Issue by tasdienes** [paritytech/parity#6099]
If a wallet contains multiple types of tokens, it is easy to accidentally send ETH instead of another token.  This can be a costly mistake :).  It may be better to force the user to make a choice.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
