### ISSUE TITLE
Potential injection?

### ISSUE THREAD

**Issue by gbxl** [paritytech/parity#6106]
Isn't this https://github.com/paritytech/parity/blob/02d462e2636f1898df3e7556364260c594b112e6/js/src/contracts/snippets/enhanced-wallet.sol#L432 a potential security hole? Unless the content of `msg.data` is escaped/controlled.

**Comment by fzzr-** [comment]
I agree but how to make it differently?
I think `delegatecall(msg.data)` is ok only if there test `msg.sender in owners` or something like that.

**Comment by EricR** [comment]
Injection of what and into what?

The delegation is performed to forward calls to the WalletLibrary contract. My understanding is that this was done to manage wallet code independent of deployed wallets (so that the library can be updated), as well as make it cheaper for users to deploy.

**Comment by keorn** [comment]
@gbxl please reopen if you have a specific concern.
