### ISSUE TITLE
Waiting for Confirmations 

### ISSUE THREAD

**Issue by gtrider** [paritytech/parity#6109]
Hi, 
Noob here.  I have been trying to send ETH to my wallet outside of parity and after pressing send it is "waiting for confirmations" ... it's been doing this for over 2hrs.  Any ideas?  I've tried to send this eth for the past 2 night with more and more gas and nothing gets sent.  so frustrating.

**Comment by gtrider** [comment]
here's the txid 0xc0b2f91860d473ded313a4eaccbc7e1f8417273150d4f90695487d8bc47e9dff

**Comment by 5chdn** [comment]
Which version of Parity are you using? Are you fully synchronized? Are you connected to any peers?

**Comment by rphmeier** [comment]
> with more and more gas

how much gas? there is a limit to how much gas can be used in a single block (currently around 6.7M) so if you specify more than that, it will be impossible to include the transaction in a block.

it is better to increase the gas price than the gas if you want to increase the priority of the transaction.

**Comment by gtrider** [comment]
Thanks for the responses.  it finally posted.  took 4 hours. 
Yeah i bumped the gas price not the other gas.
