### ISSUE TITLE
Ethash "sealFields" should return RLP decoded values

### ISSUE THREAD

**Issue by keorn** [paritytech/parity#6123]
Values in `"sealFields"` should be equal to `"mixHash"` and `"nonce"` fields.
Before someone looks at poor https://github.com/ethereum/EIPs/issues/95

**Comment by feynmanliang** [comment]
I'd like to work on this. Is the related code under `rpc/src/v1/{types,impl}`?

**Comment by keorn** [comment]
Yep and `ethcore/src/ethereum/ethash.rs` in `fn extra_info`

**Comment by tomusdrw** [comment]
Duplicate of #1090
