### ISSUE TITLE
Whisper CLI

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#6138]
Whisper-only binary. Should be in `whisper/cli`.
  - DevP2P configuration 
  - RPC server kinds 
  - ports 
  - whisper resident pool size
  - should have its own `Metadata` type for pub-sub.
  - Should only serve whisper RPCs.

**Comment by rphmeier** [comment]
I would say this is `Easy` in difficulty, but `Substantial` in the amount of work. I can mentor

**Comment by 5chdn** [comment]
:-)

**Comment by axelchalon** [comment]
I'd be interested in working on this!

**Comment by niklasad1** [comment]
@rphmeier @axelchalon 
What is the status on this? 
I can take over this if you want

**Comment by axelchalon** [comment]
I had started some work on this a while back (https://github.com/axelchalon/parity/tree/whisper-v6-cli for what it's worth). I think you can take it over.
