### ISSUE TITLE
WASM: Rust traits generating abi + dispatch

### ISSUE THREAD

**Issue by NikVolf** [paritytech/parity#6143]

**Comment by debris** [comment]
`ethabi_derive` could be used here. It doesn't have dispatch yet, but this could be easily implemented.

**Comment by NikVolf** [comment]
isn't ethabi_derive is the other way around - generating invokes from json?

**Comment by NikVolf** [comment]
solidity-compatible abi generation so far:
https://github.com/NikVolf/pwasm-abi

**Comment by debris** [comment]
@NikVolf can this issue be closed?
