### ISSUE TITLE
Replace usages of ::std::env::temp_dir with tempdir crate in tests

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6147]
https://github.com/paritytech/parity/pull/6140#discussion_r129265892

**Comment by GeorgiosAthanasiadis** [comment]
WIP - Replace usages of ::std::env::temp_dir with tempdir crate in tests #6146

**Comment by kirushik** [comment]
@GeorgiosAthanasiadis Hi!
What's your status with this issue? Do you need any help in finalizing your work?

Please keep in mind that only PRs submitted in October (which ends tomorrow) qualify for Hacktoberfest.
