### ISSUE TITLE
dapp not reachable when deploying with docker behind nginx

### ISSUE THREAD

**Issue by dfherr** [paritytech/parity#6154]
i deployed parity on my server via docker and forward 8080 and 8180 to parity using nginx.

I have to use interface "0.0.0.0" on both the dapp and the parity ui or I will be unable to connect to parity running in docker even from localhost.

Reaching parity ui ` mydomain:8180` works with the `--ui-no-validation` option (as he expects 0.0.0.0). edit: But won't show any information about the running chain...

But connection to `mydomain:8080/#/app/myapp` will redirect me to `0.0.0.0:8180/#/app/myapp`

These unsolicited redirections are really annoying. Any way to use the simple dapp structure with docker on a server?

**Comment by 5chdn** [comment]
Sounds like the docs need some love. Let me look into this tomorrow.

**Comment by 5chdn** [comment]
@dfherr Note, the `:8080` dapps port is deprecated. For everything else, please test the configuration suggested in the wiki:

https://github.com/paritytech/parity/wiki/Docker#open-ports

And make sure you are using the parity/parity repository on docker hub instead of ethcore.
