### ISSUE TITLE
ERR_CONNECTION_REFUSED on network as soon as parity runs

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6157]
I am opening this issue here to keep track and try gathering clues on the problem.
I have seem similar issues but describing a problem that is likely different.

The computers of my network get often some ERR_CONNECTION_REFUSED. It happens especially with GitHub. 

The issues seems to only occur when parity runs on my network! 
I have tested with parity 'v1.6.7-beta-e128418-20170518/arm-linux-gnu/rustc1.17.0’ (in a RPi3). 
As soon as I turn it on, I get a bunch of those ERR_CONNECTION_REFUSED on my network. 
As soon as I shutdown parity, the issues vanish. 

I have seen people describing similar problems on low bandwidth networks.
I have a 450MBits / 20MBits connection so I doubt the bandwidth would be the issue here. 

It is btw not related to the RPi or the old version of parity. 
I get the same issue with a fresh build from master.

As soon as parity runs, my network gets messed up somehow. If I run parity on machine A, none of machine A and B can do a `brew update` (just using that as a test but it occurs on random sites which I know are not down or rejected by HTTP requests) for instance and it looks like:
```
$ brew update
fatal: unable to access 'https://github.com/ethereum/homebrew-ethereum/': Failed to connect to github.com port 443: Connection refused
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Failed to connect to github.com port 443: Connection refused
fatal: unable to access 'https://github.com/ethcore/homebrew-ethcore/': Failed to connect to github.com port 443: Connection refused
fatal: unable to access 'https://github.com/Homebrew/homebrew-dupes/': Failed to connect to github.com port 443: Connection refused
fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': Failed to connect to github.com port 443: Connection refused
fatal: unable to access 'https://github.com/WyseNynja/homebrew-bitcoin/': Failed to connect to github.com port 443: Connection refused
Error: Fetching /usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew/Library/Taps/ethcore/homebrew-ethcore failed!
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-dupes failed!
Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
Fetching /usr/local/Homebrew/Library/Taps/wysenynja/homebrew-bitcoin failed!
```

**Comment by chevdor** [comment]
I found the similar related issues: #5829 #5701

**Comment by chevdor** [comment]
New test today:
- using parity/master on mainnet => syncing remains at #4060364 => the issue does not show up
- starting my node on RPi3 => the issue occurs immediately as soon as parity starts

On the RPi3, I am running a private blockchain using PoA on a single node.
As soon as I stop parity on this node, the issue stops.

**Comment by chevdor** [comment]
Interesting:
- starting geth (alone) => issue occurs
- stopping geth => issue stops

It sounds like my network does not like Ethereum and that the issue is not a Parity only issue.

To exclude bandwidth issues, I ran a speedtest:
![image](https://user-images.githubusercontent.com/738724/28661579-6c161c6c-72b7-11e7-843f-7405e1c2b011.png)
which shows basically that I am hitting the limits of what my Wifi can do.

**Comment by chevdor** [comment]
NOTE: At that point, I don´t exclude the issue to come from my internet provider (Unitymedia), parity being then just 'a' thing loading a bit the network.

**Comment by arkpar** [comment]
You router or your ISP can't handle high connection rate. Try running parity with `--max-pending-peers 10`

**Comment by chevdor** [comment]
@arkpar thanks for the tip. Any hint on how to measure/check that to figure out if this is router or ISP? If this is the ISP, I would like to 'prove' it to them.

I did a first test with --max-pending-peers and it did not seem to make a difference.

**Comment by dev-dan** [comment]
Experiencing this issue on windows 10 64bit after upgrading to 1.7.

**Comment by 5chdn** [comment]
@dev-dan could you clarify what exactly are you experiencing?

**Comment by 5chdn** [comment]
@chevdor does this still occur? does this also happen if you run parity with `--mode offline` ?

**Comment by dev-dan** [comment]
@5chdn Absolutely, although in taking a moment to consider, my issue might be slightly different though very similar so I still thought it relevant here:

I am running parity 1.7.0 on windows 64bit. Using the main net. When I launch parity, my network slows down, although some services still work. Github and other sites will not respond in browser, the Gitter App and other similar apps using electron will show ERR_CONNECTION_TIMED_OUT. Some apps returning 502 bad gateway. Oddly enough, other sites like facebook are entirely functional. (Original Poster commented both that 

> It happens especially with GitHub.

and

> it occurs on random sites which I know are not down or rejected by HTTP requests

It seems to CONSISTENTLY effect github and gitter, while other sites will seem to work. 

--max-pending-peers has no effect. 

When I close parity, everything goes back to normal within 1 minute. 

Did not experience this on 1.6.8, only 1.7.0.

**Comment by chevdor** [comment]
I am seeing the same issue when starting **geth** btw.
@5chdn using --mode offline, the issue seems not to occur. I will let it run a little longer though.

**Comment by chevdor** [comment]
@dev-dan what router do you have?
I am using a Fritzbox 6490.

**Comment by chevdor** [comment]
@5chdn using --mode offline seems to NOT trigger the issue.

**Comment by 5chdn** [comment]
Can you try one more thing? Does this also happen with the following reduced networking configuration?

    parity --min-peers 4 --max-pending-peers 4 --max-peers 8 --allow-ips=public --no-discovery

Thanks.

**Comment by chevdor** [comment]
@5chdn sure, happy to test anything that could help spotting the issue.
with parity running as:
`parity --min-peers 4 --max-pending-peers 4 --max-peers 8 --allow-ips=public --no-discovery
`
I do NOT see the issue, even after a few minutes.

**Comment by 5chdn** [comment]
> I do NOT see the issue, even after a few minutes.

Then I'm happy to inform that this is neither a parity nor geth issue, but probably your router (unlikely) or ISP (more likely) blocking your internet access because it believes you are trying to spam the network / scan the network / hack the whole internet of things, or whatever an ISP could think you do.

Try to play around with the network configuration and check https://github.com/paritytech/parity/wiki/Network-Configuration for details. Let me know if you have any further questions.

**Comment by chevdor** [comment]
I am not so happy as you are 😄 but agree with your conclusion.
I also tested with my VPN on and tada, no more issues. I will have a call with my ISP...

**Comment by 5chdn** [comment]
Hard to tell what exactly triggers. You could play around with lifting the flags until you find something that works out for you without breaking the internet, try for instance:

    parity --max-pending-peers 10 --no-discovery

Or only one of the two flags above.

**Comment by chevdor** [comment]
thanks @5chdn, much appreciated
