### ISSUE TITLE
Skipping the account creation wizard fails

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6158]
Occurs when parity has no account defined (ie you cleared browser storage)

Instead of skipping, it goes to the confirmation page where the user cannot move forward or backward.

In the case you do have already accounts and just need to re-import them, skipping would be nice to prevent the creation of dummy accounts that have to be deleted later.

![image](https://user-images.githubusercontent.com/738724/28660860-f8e84f96-72b4-11e7-932c-c95a04a9db8c.png)

**Comment by 5chdn** [comment]
Could you explain the steps how to reproduce this?

**Comment by chevdor** [comment]
as far as I recall:
- clear local storage
- start parity
- follow the guide

I may have clicked 'next' and 'back' a few times though.

**Comment by jacogr** [comment]
Closing, not applicable for 1.9+
