### ISSUE TITLE
Can Parity import blockchain which created by geth?

### ISSUE THREAD

**Issue by jdcrew** [paritytech/parity#6160]
Hi,Guys

Yesterday I created a node with command
geth --datadir data_1 init genesis.json
geth --datadir data_1
>personal.newAccount("password")
"0xb40fec41d4055b21c507e032c252b14e5e62093a"
>personal.newAccount("password")
"0x90bf19f88e370ea20b03ee7788c635f971966e6b"

then, my question is :

Can parity import the blockchain/node I have created yesterday with the former 2 accounts in it ?

**Comment by 5chdn** [comment]
Yes. Not sure what exactly you want to do but I will just cover everything below:

Once you initialized Geth with your genesis,

    geth init --datadir data_1 geth.json

and have been running it or mining with it, stop it,

    geth --datadir data_1
    ^C

and export the blockchain.

    geth export --datadir data_1 geth.blocks

Assuming you are running parity with a compatible chain spec on `data_2`

    parity --chain parity.json --db_path data_2
    ^C

Stop it and import the `geth.blocks`

    parity --chain parity.json --db_path data_2 import geth.blocks 

Note, that Geth works with a genesis file and parity with a chain specification. You can use this tool to convert your genesis to a chainspec:

- https://github.com/keorn/parity-spec

To reuse the same accounts, just copy them from `data_1/keystore` to `data_1/keys`, or import them via the Wallet UI.

See also:

- https://github.com/paritytech/parity/wiki/Private-development-chain
- https://github.com/5chdn/crossclient-chainspec
