### ISSUE TITLE
MMAP in ethash DAG used for verification

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#6165]
Would significantly reduce memory usage in light client.
@vurich one for you?

**Comment by andrebeat** [comment]
Can I take this?

**Comment by Vurich** [comment]
Sorry @andrebeat, [a PR is open already](https://github.com/paritytech/parity/pull/6193).

**Comment by 5chdn** [comment]
Please always link issues to PRs. https://github.com/blog/1506-closing-issues-via-pull-requests
