### ISSUE TITLE
 execution time of eth.account call is increasing exponentially with numbers of managed account

### ISSUE THREAD

**Issue by rachyandco** [paritytech/parity#6170]
# Description

The execution time of the eth.account call is increasing exponentially with the number of account managed by Parity.

# Expected behavior

Parity should be able to manage a large number of accounts without having a exponential increasing computation cost. Linear progression is expected.

# Setup info:

Network         : 1 --> LIVE(Homestead)
NodeVersion     : Parity//v1.6.9-stable-d44b008-20170716/x86_64-linux-gnu/rustc1.18.0
Server Ubuntu 8Gb memory 4 cores

Parity is running inside a docker container with the following settings:

`--jsonrpc-interface all --jsonrpc-hosts all --no-ipc --no-dapps --cache-size-db 1024 --gas-floor-target 2000000 --gasprice 20000000000 --gas-cap 1500000 --warp --jsonrpc-apis web3,eth,net,parity,traces,rpc,personal`

# How to reproduce
We ran the following code with web3 connected to the node:

```
def checkaccount():
  for i in range(0, len(web3.eth.accounts)):
    account               = web3.eth.accounts[i]
    balance               = web3.eth.getBalance(account)

cProfile.run("checkaccount()")
```

We run this code with different sets of accounts. The number of ncalls is the same as the number of account tested.

> 
>   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
> 
>       151    0.001    0.000    0.260    0.002 eth.py:113(getBalance)
>       152    0.000    0.000    0.473    0.003 eth.py:98(accounts)
> 
>       193    0.001    0.000    0.316    0.002 eth.py:113(getBalance)
>       194    0.001    0.000    0.581    0.003 eth.py:98(accounts)
> 
>       344    0.003    0.000    0.601    0.002 eth.py:113(getBalance)
>       345    0.001    0.000    1.466    0.004 eth.py:98(accounts)
> 
>       574    0.004    0.000    1.321    0.002 eth.py:113(getBalance)
>       575    0.002    0.000    3.750    0.007 eth.py:98(accounts)
> 
>      1158    0.008    0.000    2.457    0.002 eth.py:113(getBalance)
>      1159    0.004    0.000   11.012    0.010 eth.py:98(accounts)
> 
>      1540    0.011    0.000    4.109    0.003 eth.py:113(getBalance)
>      1541    0.005    0.000   22.123    0.014 eth.py:98(accounts)
> 
>      6350    0.067    0.000   35.240    0.006 eth.py:113(getBalance)
>      6351    0.029    0.000  575.509    0.091 eth.py:98(accounts)
> 
>     19006    0.175    0.000  549.608    0.029 eth.py:113(getBalance)
>     19007    0.083    0.000 11910.565    0.627 eth.py:98(accounts)

**Comment by rachyandco** [comment]
I am adding the observium graphs of the VM corresponding to the 2 last batches of 6000 and 19000 accounts.
![screenshot from 2017-07-28 11-16-17](https://user-images.githubusercontent.com/2358699/28710980-4fcc358a-7386-11e7-8f51-08d9598421e8.png)
![screenshot from 2017-07-28 11-12-06](https://user-images.githubusercontent.com/2358699/28710979-4fb18898-7386-11e7-9169-b2d032ff94e7.png)

It seems the CPU and network usage is hitting a limit.

**Comment by tomusdrw** [comment]
What kind of RPC transport are you using? Do you see the same pattern on both HTTP and IPC transports?

**Comment by rachyandco** [comment]
@tomusdrw we only use HTTP. IPC is disabled.

**Comment by rachyandco** [comment]
Similar testing using IPC

```
      168    0.001    0.000    0.077    0.000 eth.py:113(getBalance)
      169    0.000    0.000    0.298    0.002 eth.py:98(accounts)

      319    0.001    0.000    0.220    0.001 eth.py:113(getBalance)
      320    0.001    0.000    0.930    0.003 eth.py:98(accounts)

     1754    0.016    0.000    2.001    0.001 eth.py:113(getBalance)
     1755    0.005    0.000   31.149    0.018 eth.py:98(accounts)


     6560    0.067    0.000    8.865    0.001 eth.py:113(getBalance)
     6561    0.056    0.000  720.634    0.110 eth.py:98(accounts)
```

interesting how `getBalance` is faster with IPC and `accounts` is slower.

**Comment by rachyandco** [comment]
Again another test with the following settings:

- RPC
- Docker Privilege mode on
- ulimit -n 262144

```
     1764    0.014    0.000    4.100    0.002 eth.py:113(getBalance)
     1765    0.006    0.000   21.071    0.012 eth.py:98(accounts)

     6570    0.063    0.000   18.460    0.003 eth.py:113(getBalance)
     6571    0.025    0.000  275.113    0.042 eth.py:98(accounts)

    19223    0.175    0.000  616.777    0.032 eth.py:113(getBalance)
    19224    0.078    0.000 9327.725    0.485 eth.py:98(accounts)
```
The `accounts` is a bit faster, and the `getBalance` like twice as slower.

**Comment by rachyandco** [comment]
@tomusdrw if you need more testing, just ask.

**Comment by rachyandco** [comment]
Behavior is consistent on latest version 
`Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.19.0`

**Comment by folsen** [comment]
Closing on the assumption that it is fixed in https://github.com/paritytech/parity/pull/6827, if it's still reproducible then please reopen.
