### ISSUE TITLE
Run parity as a system service on Ubuntu

### ISSUE THREAD

**Issue by schmidsi** [paritytech/parity#6171]
I followed the [instructions in the FAQ](https://github.com/paritytech/parity/wiki/FAQ#can-i-run-parity-as-a-daemon-or-system-service) but the following command fails:

```bash
sudo systemctl enable io.parity.ethereum
> Failed to execute operation: No such file or directory
```

Furthermore, I want to configure this service to run on the Kovan chain. So the question is:
- Is there a predefined possibility to run parity as a service on Ubuntu (or Linux in general)
- If yes, how can I configure it to run on the Kovan chain. Furthermore: unlock accounts, etc. Basically everything that can be [configured](https://github.com/paritytech/parity/wiki/Configuring-Parity)
- If no: Can someone point me how to do this? Where do I find the installed binaries? How to create a systemctl service by myself, ... I'm happy to write the instructions back here in the wiki or somewhere.

**Comment by 5chdn** [comment]
The FAQ only covers macos. For Ubuntu, try the following:

- Service file can be found here: https://github.com/paritytech/parity/blob/master/scripts/parity.service

        sudo wget https://raw.githubusercontent.com/paritytech/parity/master/scripts/parity.service -O /etc/systemd/system/parity.service
        sudo chmod +x /etc/systemd/system/parity.service
        sudo systemctl enable parity
        sudo systemctl start parity

- For default configuration with Kovan, please check the wiki for the default config file options: https://github.com/paritytech/parity/wiki/Configuring-Parity#config-file

        [parity]
        chain = "kovan"

Hope that answers your questions.

**Comment by 5chdn** [comment]
user@eros:~$ sudo systemctl status parity
    ● parity.service - Parity Daemon
       Loaded: loaded (/etc/systemd/system/parity.service; enabled; vendor preset: enabled)
       Active: active (running) since Fri 2017-07-28 12:39:06 CEST; 5min ago
     Main PID: 25972 (parity)
        Tasks: 38 (limit: 4915)
       CGroup: /system.slice/parity.service
               └─25972 /usr/bin/parity

    Jul 28 12:43:27 eros parity[25972]: 2017-07-28 12:43:27  Syncing snapshot 118/388        #0   17/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:43:32 eros parity[25972]: 2017-07-28 12:43:32  Syncing snapshot 120/388        #0   17/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:43:37 eros parity[25972]: 2017-07-28 12:43:37  Syncing snapshot 122/388        #0   18/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:43:42 eros parity[25972]: 2017-07-28 12:43:42  Syncing snapshot 125/388        #0   18/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:43:47 eros parity[25972]: 2017-07-28 12:43:47  Syncing snapshot 128/388        #0   19/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:43:52 eros parity[25972]: 2017-07-28 12:43:52  Syncing snapshot 131/388        #0   18/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:43:57 eros parity[25972]: 2017-07-28 12:43:57  Syncing snapshot 134/388        #0   18/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:44:02 eros parity[25972]: 2017-07-28 12:44:02  Syncing snapshot 135/388        #0   20/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:44:07 eros parity[25972]: 2017-07-28 12:44:07  Syncing snapshot 139/388        #0   20/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
    Jul 28 12:44:12 eros parity[25972]: 2017-07-28 12:44:12  Syncing snapshot 142/388        #0   20/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

**Comment by schmidsi** [comment]
Worked perfectly. Thanks for pointing out. I [documented our setup publicly](https://github.com/melonproject/docs/blob/e8af5577e90134f64e7195e0a3d16d73d61ea421/Software%20Architecture/hosting.md), so this could maybe help others too.

**Comment by 5chdn** [comment]
Updated the docs. :)

**Comment by fafrd** [comment]
Since this is the top google result for 'parity systemd', I'd like to note that the current systemd unit file is located here: https://github.com/openethereum/openethereum/blob/master/scripts/openethereum.service
