### ISSUE TITLE
Warn users when interacting with malicious accounts or contracts

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#6172]
- https://github.com/MyEtherWallet/ethereum-lists

**Comment by 5chdn** [comment]
For extension (URLs): https://github.com/paritytech/parity-extension/issues/91

**Comment by 5chdn** [comment]
_"We could integrate the phishing list in Signer, which is used by the UI and the Chrome Extension"_

**Comment by 5chdn** [comment]
related #2281

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/78
