### ISSUE TITLE
DApps not accessible in 1.7.0

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#6174]
I use this artifact 'https://gitlab.parity.io/parity/parity/-/jobs/61863/artifacts/download to test 1.7.0
I created a single node and open http://$IP:8180 to access DApps.

1. It notifies me that I have a single node and probably there's a connection issue - which is fine, but in chrome console every ~ 1 sec I see these requests ending in errors
```
Request URL:http://$IP:8180/api/health
Request Method:GET
Status Code:412 Precondition Failed
Remote Address:40.71.41.241:8180
Referrer Policy:no-referrer-when-downgrade
```
The response is returned though: `{"peers":{"status":"bad","message":"You are not connected to any peers. ...`
Is this OK?

2. When I open my DApp I get this error:
```
Refused to display 'http://$IP:8540/KeysGenerator/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 0.0.0.0:8180 *.web3.site:8180 home.web3.site localhost:3000".
```

Here's part of config.toml
```
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
interface = "all"
port = 8180
```

**Comment by 5chdn** [comment]
Will be patched in 1.7.1, thanks for the heads-up.
