### ISSUE TITLE
Use annotated tags for releases

### ISSUE THREAD

**Issue by elopio** [paritytech/parity#6180]
Congratulations on the 1.7 release!

I think it would be nicer and safer to use git annotated tags for the following releases:
https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags

-- a satisfied user :)

**Comment by 5chdn** [comment]
Interesting:

> - annotated tags can contain a message, creator, and **date different than the commit they point to**. So you could use them to describe a release without making a release commit.

And:

> If we would just create an annotated tag on an old commit, GitHub would take the date for the release from the tag object. In contrast, when we've created a lightweight tag for this old commit, the release started showing the correct (old) date.

@arkpar this is something that certainly would help not only with authenticity of releases, but also for organizing releases, e.g., putting stable releases always below beta releases independent of the commit time-stamp.

**Comment by arkpar** [comment]
`v1.7.0` tag is now annotated

**Comment by elopio** [comment]
awesome @arkpar. Thanks!

**Comment by elopio** [comment]
Hey @arkpar, I've just noted that 1.7.2 was not annotated. Maybe something to note down in your release procedure?
