### ISSUE TITLE
Public node documentation

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#6181]
Documentation explaining how to run a public node.

**Comment by 5chdn** [comment]
@maciejhirsz I can draft something and show you for review, if this helps.

**Comment by maciejhirsz** [comment]
@5chdn sure if it's not too much of a trouble for you.

**Comment by WyseNynja** [comment]
Any movement on this? I have haproxy running with SSL certs in front of 8180, but am not sure how to setup the other ports. I was hoping for something where the client uses 443 for everything and haproxy (or nginx or w/e) routes to the proper backend.

**Comment by VoR0220** [comment]
This would be very useful right about now. I'm going through a very complicated process to run a remote node access routine, and it would be nice to have this simplified.

**Comment by 5chdn** [comment]
Well, let me get a coffee and draft that right now. 

Meanwhile try running:

    parity --public-node

And report back if it works for you. ;)

**Comment by WyseNynja** [comment]
Thanks @5chdn! I'd be happy to test and review your docs :-)

**Comment by 5chdn** [comment]
_(I didn't even make it to the coffee machine yesterday.)_

**Comment by 5chdn** [comment]
Started the draft. Need @maciejhirsz to confirm a list of additional / disabled features.

https://github.com/paritytech/parity/wiki/Public-Node

**Comment by WyseNynja** [comment]
Do hardware wallets not work with public nodes? I was really hoping they would, but given the instructions for ledger say to disable browser mode, I think not. I was hoping it worked like myetherwallet does.

**Comment by 5chdn** [comment]
Did you try it, yet? I'm not aware why it should not work.

**Comment by WyseNynja** [comment]
Yes, I tried it at https://wallet.parity.io/ and at my own localhost node. I couldn't get my Ledger S to be recognized by either.

**Comment by daithi-coombes** [comment]
In issue referenced above is an `nginx` configuration I'm using to run `parity` over `ssl`, some may find it usefull... also solution, when I find it, may be worth putting in docs?

**Comment by BransonGitomeh** [comment]
im also having the same issues @daithi-coombes with the proxy redbird over letsencrypt ssl proxying the ws connections to 8546 on parity, im getting the error `WebSocket connection to 'wss://parity.braiven.io:8546/' failed: Error in connection establishment: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH` on the browser

any clue how i can fix this?

**Comment by 5chdn** [comment]
Public node feature is discontinued and to be removed in 1.11
