### ISSUE TITLE
When switching between chains, you must create an account before switching to another one.

### ISSUE THREAD

**Issue by destenson** [paritytech/parity#6189]
The heading says it all. I was experimenting with this new feature of adding ETC and EXP to my client when I accidentally switched to one of the test chains. Now I can't switch back to one of the live chains without going through all the rigamarole of creating a new account on the testnet. Obviously it's not a huge problem, but it is an annoying waste of time when I just want to switch back to a live chain.

Also switching between chains in general seems very hokey and feels like it was implemented as an afterthought, and has not been well tested at all.. There are many little bugs related to it, such as not keeping separate dapps for different chains, and calling the main coin on all chains ETH even though it may be ETC, or EXP or something else.. I'm sure there are many more. It would've seemed appropriate to warn that this feature as of pre-release quality and not to expect it to work well.

**Comment by keorn** [comment]
Logged the token names separately: #6191

**Comment by 5chdn** [comment]
> There are many little bugs related to it, such as not keeping separate dapps for different chains

What exactly do you mean by this? All chains have their separate DApps.

Default token name, see #4123

**Comment by tomusdrw** [comment]
I think @destenson meant local dapps, but that works as desgined. Developers should be able to easily test the same dapp on Kovan and Mainnet.

**Comment by destenson** [comment]
I'd have to try it out again to be sure, but IIRC, when I would switch chains, all of the DApps remained as if I were on the same chain. But since the chains have different DApps deployed on them and at different addresses, icons & images had broken links and smart contracts weren't functional (different deployment addresses, etc). Overall, from a user experience, it just seemed to be quite broken.

**Comment by 5chdn** [comment]
That's a browser caching issue. If you switch chains, you should hard-refresh (CTRL+F5) or start a new session. Regarding account creation see #6367
