### ISSUE TITLE
Authority Round in 1.7.0 with validation via contract

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#6190]
Hello,
I use this artifact 'https://gitlab.parity.io/parity/parity/-/jobs/61863/artifacts/download to test 1.7.0

We have an AuthorityRound network where validators are added via contract.
Initially there is a single mining node (`dd0b…7126`) hardcoded into the contract, new validators may join the network later.

We've used the same contract in 1.6.x and it was working, but now it seems that only the initial mining node produces new blocks.
We have `force_sealing = true` so new blocks are created about once a second and none of them are by miners that joined later.
If I stop the initial node, others remain connected to each other but don't produce new blocks.

Here are logs from the initial node (with `engine=trace`):
```
2017-07-30 20:46:59 UTC IO Worker #1 TRACE engine  Fetched proposer for step 300289524: dd0b…7126
2017-07-30 20:47:00 UTC IO Worker #1 TRACE engine  generate_seal: Issuing a block for step 300289524.
2017-07-30 20:47:00 UTC IO Worker #1 DEBUG engine  Expected topics for header 6648…bedf: [55252fa6eee4741b4e24a74a70e9c11fd2c2281df8d6ea13126ff845f7825c89, 9f8a199de8fae439ebf0cd84b8f03610ad435f55e4d862163541deaa6521f19b]
```

Here are logs from one of other mining nodes:
```
2017-07-30 20:57:30 UTC IO Worker #2 TRACE engine  Fetched proposer for step 300289650: dd0b…7126
2017-07-30 20:57:30 UTC IO Worker #2 TRACE engine  generate_seal: 85a6…e3c0 not a proposer for step 300289650.
2017-07-30 20:57:30 UTC Verifier #0 DEBUG engine  Expected topics for header decd…f74d: [55252fa6eee4741b4e24a74a70e9c11fd2c2281df8d6ea13126ff845f7825c89, bc5d5751889925478eefe141d18ac83826e8dcf6677ae5c36d1595a46a25615e]
```

If I stop the initial node, these messages keep repeating
```
2017-07-30 21:13:30 UTC IO Worker #2 TRACE engine  Fetched proposer for step 300289842: dd0b…7126
2017-07-30 21:13:30 UTC IO Worker #2 TRACE engine  generate_seal: 85a6…e3c0 not a proposer for step 300289842.
2017-07-30 21:13:35 UTC IO Worker #2 TRACE engine  Fetched proposer for step 300289843: dd0b…7126
2017-07-30 21:13:35 UTC IO Worker #2 TRACE engine  generate_seal: 85a6…e3c0 not a proposer for step 300289843.
2017-07-30 21:13:40 UTC IO Worker #2 TRACE engine  Fetched proposer for step 300289844: dd0b…7126
2017-07-30 21:13:40 UTC IO Worker #2 TRACE engine  generate_seal: 85a6…e3c0 not a proposer for step 300289844.
```

**Comment by keorn** [comment]
Can you post the contract? The interface is a bit different, have a look [here](https://github.com/paritytech/parity/wiki/Validator-Set#contracts).

**Comment by phahulin** [comment]
Thanks, this is probably the reason, we'd need a bit of time to rewrite our contract and do tests.

One more question then: if we have a network running on 1.6 is there a "migration plan" to 1.7? Can we update contract without hard fork? Should  we somehow update files?

**Comment by rphmeier** [comment]
@phahulin You can continue to use the old behavior by setting the `immediateTransitions` flag in the `authorityRound` configuration to `true`. There is no ability for migration of the same chain, as such a chain can never support light clients or warp sync securely.

**Comment by rphmeier** [comment]
@phahulin if you are aware of all the points at which the `getValidators` set changed, you might also be able transition by replacing the `contract` entry of the `multi` validator set with fixed lists at those points.

**Comment by phahulin** [comment]
@rphmeier can I switch contracts instead?
```
"0": {
    "contract": "0x previous contract"
},
"1000": {
    "contract": "0x new contract"
} 
```

**Comment by keorn** [comment]
Yes, you should be able to switch contracts.

**Comment by phahulin** [comment]
Does look like it, nodes start from 0, instead of continuing from the last block

**Comment by keorn** [comment]
Can you provide more detail about the steps that you take?

**Comment by phahulin** [comment]
0. Initially we have 13 nodes in our test network, running docker parity 1.6.8
1. Stop them one by one with `docker stop`
2. Update `spec.json` file, specifically, initially we have
```
    "validators": {
        "safeContract": "0x...12345"
    }
```
I changed it to
```
    "validators": {
        "multi": {
            "0": {
                "safeContract": "0x...12345"
            },
            "669586": {
                "safeContract": "0x...12346"
            }
        }
    },
   ...
   "accounts": {
       "0x...12346" : {
           "balance": 1,
           "constructor": "0x606..."
       }
    }
```

where 669586 is `last block + 1`, "0x...12345" is old contract's byte code address (already in spec.json) and "0x...12346" is new contract's byte code address, that I also add to spec.json.

3. On UI node, change node.toml (add `[websockets]`, comment out `[dapps]`) and forward port 8546 in docker. On mining nodes there's nothing to update in node.toml.

4. Pull v1.7.0 docker image from parity/parity

5. Start docker on all nodes one by one

**Comment by keorn** [comment]
Adding a contract to `accounts` changes the genesis state, which makes a different chain. To conduct a fork you will need to deploy the contract under `0x...12346` onto the chain first. Get its' address and the use it in your `multi` set.

**Comment by phahulin** [comment]
Thanks. Unfortunately, same thing happens: blocks start from 0.

**Comment by rphmeier** [comment]
I don't think forking to a new contract to gain the new features will really be possible. Either the chain support light client and warp sync (via finalized transitions) or it doesn't. Since there are some blocks which contain unfinalized transitions, the security of any further transitions is unverifiable from a light client's perspective.

What _may_ work is a series of transitions to fixed lists, but that will also be blocked on #6241 making its way into a release.
