### ISSUE TITLE
Problem after installing 1.7.0 with simple one-line installer

### ISSUE THREAD

**Issue by sandakersmann** [paritytech/parity#6198]
After installation I get this error when trying to run Parity 1.7.0:

```
$ parity --cache 2048 --datadir "/media/marius/My Files/ParityEthereumData"
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by parity)
parity: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by parity)
```

**Comment by sandakersmann** [comment]
This is on Linux Mint 17.3

**Comment by 5chdn** [comment]
Which g++ and libstdc++ version?

- https://stackoverflow.com/questions/23494103/version-cxxabi-1-3-8-not-found-required-by

- https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx

- https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

- https://stackoverflow.com/questions/16605623/where-can-i-get-a-copy-of-the-file-libstdc-so-6-0-15
