### ISSUE TITLE
Automatically verifiable contracts in etherscan

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#6200]
I'm curious how do you call etherscan API to make MultiSig contract already verifiable as soon as you create it ? 
It only work in mainnet, it doesn't work in testnets.

Please let us know of this cool trick that you used there.

**Comment by 5chdn** [comment]
It matches the bytecode of deployed contracts. If there are exact matches (i.e., multiple instances of deployed multi-signature contracts), etherscan knows this contract is already existing. If some users verifies one of these deployed contracts, etherscan also knows this is the exact code used for all of the other contracts.

**Comment by rstormsf** [comment]
hmmm...why it is not the case when I deployed multisig with 1.6.10 
Also how does it know which Constructor params were passed in ?

**Comment by 5chdn** [comment]
It's because we recently updated our contracts and nobody verified it yet.
