### ISSUE TITLE
enhanced-wallet is using return of delegatecall as return of functions it is calling

### ISSUE THREAD

**Issue by 3esmit** [paritytech/parity#6201]
```
  // As return statement unavailable in fallback, explicit the method here

  function hasConfirmed(bytes32 _operation, address _owner) external constant returns (bool) {
    return _walletLibrary.delegatecall(msg.data);
  }

  function isOwner(address _addr) constant returns (bool) {
    return _walletLibrary.delegatecall(msg.data);
}
```
This should not return the isOwner return from delegatecall, but true if delegatecall was success, and false if throwed.

http://solidity.readthedocs.io/en/latest/control-structures.html
`send and the low-level functions call, delegatecall and callcode – those return false in case of an exception instead of “bubbling up”.`
`If you call a function via a message call but it does not finish properly (i.e. it runs out of gas, has no matching function, or throws an exception itself), except when a low level operation call, send, delegatecall or callcode is used. The low level operations never throw exceptions but indicate failures by returning false`

http://solidity.readthedocs.io/en/latest/security-considerations.html
`Note that .send() does not throw an exception if the call stack is depleted but rather returns false in that case. The low-level functions .call(), .callcode() and .delegatecall() behave in the same way.`

**Comment by ngotchac** [comment]
Hey, thanks for the heads-up!
However, I think the Solidity docs are not up-to-date on this one. Here's a little example:

```
contract TestContract {
    uint value;
    
    function set (uint _value) external {
        value = _value;
    }
    
    function get () external constant returns (uint) {
        return value;
    }
    
    function get_delegated () external constant returns (bool) {
        return this.delegatecall(bytes4(sha3("get()")));
    }
}
```

The method `get_delegated` will return `false` only and only if `value == 0` ; `true` otherwise

**Comment by 3esmit** [comment]
This might be considered a solidity bug?

**Comment by axic** [comment]
There is a difference between `call`/`delegatecall`/etc on a contract and on an address type, the latter is called "low-level" usage.

`address(this).delegatecall()` should only return a boolean of execution status, while `this.delegatecall()` should throw an exception on failure.

**Comment by ngotchac** [comment]
In the above example, replacing `this.delegatecall()` with `address(this).delegatecall()` has the same result.

**Comment by axic** [comment]
I think it should either return the status or an exception based on the status, but not the data, since there's no way to tell the size returned.

**Comment by axic** [comment]
Sorry, I've confused to internal cases, it always returns a boolean. The only usage of delegatecall which throws exception is when used via libraries.

**Comment by ngotchac** [comment]
Yes, I agree. The current behavior would still be doable if wanted in inline assembly.

**Comment by axic** [comment]
So it seems this is a bug and is being fixed. The documentation is correct and it should only return a boolean of execution outcome.

**Comment by 3esmit** [comment]
Glad in contributing. I'm working with delegatecalls and redoing the enhanced-wallet thing for consensys multisig. The return constant functions I'm writing all again, I just use delegatecall for functions that write in the contract. 
Would be interesting to have the feature of returning the value of  constants when delegating call of everything.
BTW, the bug I reported seems like to be useful for parity, or their wallet is acually vulnerable to something?
Because the function isOwner is used inside wallet library and is a very sensitive one! should never be handled that way, and a simple rewrite of the function that might not costs too much will make it look better.

**Comment by 3esmit** [comment]
This is how I managed to do the same you did @ngotchac but for Consensys, https://github.com/3esmit/commiteth/blob/erc20-multisig/contracts/enhanced-multisig.sol#L578 

See that I'm not delegating call for constructor, nither for constrant returns. I might remove some storages from delegator contact to make cheaper, or consider a delegate call to do the stuff needed in constructor. I'm still considering beneficts vs. gas costs.

**Comment by ngotchac** [comment]
Hey, thanks for sharing this ! So the thing I was concerned about was the complexity and maintenance of the contracts. How easy would it be to verify that the two contracts (w/ or wo/ the library) works as intended ? How easy would it be to update the wallet w/ library contract if a bug is found, etc.

My take on this is here : https://github.com/paritytech/contracts/pull/74
Basically, the library should be as close as possible as the original contract (should just modify the constructors), and the actual wallet contract should be kept as simple as possible (here just delegate all the calls basically).

**Comment by chriseth** [comment]
Just a heads up: We just merged the bugfix into solidity develop.

The Solidity compiler actually has a feature called "clones", which automatically generates almost what you were doing manually. The only difference is that the construction-time code stays in the clone. It was not widely announced because it of course fails for dynamic return data. With Metropolis, we will pick up that feature again.

**Comment by 3esmit** [comment]
@chriseth this clones feature is interesting, I would be interested in using it, I guess it works like library? Metropolis will be awesome!

@ngotchac The way I did I actually don't have any difference in the Library contract, I just delegate call to the functions that write in storage. The constant return functions and the constructor are not delegatedcall (but I don't find any problem in making a delegatecall inside constructor, but I wanted to make the "easier to understand" as possible)
