### ISSUE TITLE
Option: Automated Import for Wallets 

### ISSUE THREAD

**Issue by pjeroff** [paritytech/parity#6203]
Hi! 

It's come to some frustration, by ignorance (not knowing what type of wallet I possessed) when it came to testing out parity. 

I believe a simple option of IMPORT would be beneficial to newcomers, as it is now, it's rather easy to get swamped with the ...6 options, when, if a user already has a file at hand (i.e.) all the user wants to do is to upload and move on, not to pick which option is the right one, this could be handled automatically.

Regards

**Comment by 5chdn** [comment]
Each import option has an explanation what it does and what it requires to create, import, or restore the account.

- New: Create a new account
- External: Attach via QR
- Geth: Import from Geth keystore
- JSON: Import an account backup file
- Private: Import a plain private key
- Presale: Import a presale wallet
- Restore: From parity phrase

General rule of thumb: If you do not know what it means, it's probably not what you are looking for :)
