### ISSUE TITLE
evmjit update

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6205]
- it should use https://github.com/ethereum/evmjit
- it should not be excluded from CI https://github.com/paritytech/parity/pull/6187#discussion_r130561517
- cargo should automatically detect if evmjit is available and if tests should be run

**Comment by General-Beck** [comment]
https://github.com/paritytech/scripts/commit/554b47e047f7e77f0786b94751fa5eae1266d9be

**Comment by debris** [comment]
@General-Beck `evmjit` tests most likely won't work anyway, so it's better to wait with updating scripts on master

**Comment by General-Beck** [comment]
@debris let me know
