### ISSUE TITLE
Unify debug/display for Address/Public/Secret

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6206]
https://github.com/paritytech/parity/pull/6187#discussion_r130560976

**Comment by jvalleroy** [comment]
@debris Would you expect address/public to be displayed in abbreviated form like ```c4c5…fcf4```? That's due to the display function implementation for the bigint.hash types.

**Comment by debris** [comment]
sry for late response.

it would be perfect if we could get something like this:

- debug equal to `[derive(Debug)]`
- display in form of `c4c5…fcf4`
- display with [alternate flag](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.alternate) displaying the whole hash

but to be honest, it doesn't matter to me how it is displayed as long as it is consistent ;)

take a look at this snippet:

https://github.com/paritytech/parity/blob/eecd823d32b3f4d88f64a6c41acec9c2b0b78994/ethkey/cli/src/main.rs#L170-L177

it would be good if we could unify this

**Comment by kirushik** [comment]
@jvalleroy Hi!
I guess you're trying to participate in Hacktoberfest with this issue, right?
What's your current status with it? Do you need any help in finalizing your work?

Please keep in mind that only PRs submitted in October (which ends tomorrow) qualify for Hacktoberfest.
