### ISSUE TITLE
parity/dir.rs should be a standalone crate

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6209]
and it should be used by `ethstore` instead of `ethstore/src/dir/paths.rs`

**Comment by asymmetric** [comment]
Hi, I'm trying to take this issue and I have a question. At the moment there are 3 files that seem to contain helper functions dealing with paths:

* [parity::dir](https://github.com/paritytech/parity/blob/master/parity/dir.rs)
* [ethstore::dir::paths](https://github.com/paritytech/parity/blob/master/ethstore/src/dir/paths.rs)
* [util::path](https://github.com/paritytech/parity/blob/master/util/path/src/lib.rs)

My questions are:
* Should all the paths-related functions from those modules be moved to a new crate?
* Where should the crate live? `util::path` seems like a good place :)

**Comment by kirushik** [comment]
@asymmetric Hi!
What's your status with this issue? Do you need any help in finalizing your work?

Please keep in mind that only PRs submitted in October (which ends tomorrow) qualify for Hacktoberfest.
