### ISSUE TITLE
Unable to make a connection to the Parity Secure API

### ISSUE THREAD

**Issue by woftor** [paritytech/parity#6210]
Followed https://github.com/paritytech/parity/wiki/Wallet-Remote-Access this guide to connect to my linux box running parity with UI. Worked wirh 1.6.x but with 1.7.0 it will not accept any tokens generated with 

> parity signer new-token

Time is exact on both the linux box and the pc where I connect from, it comes back with: Unable to make a connection to the Parity Secure API
Reverted back to 1.6.10 --> That works.
I start with commandline:

> parity --nat extip:[MYIP] --identity SomeName

**Comment by tomusdrw** [comment]
Additional ports are required to be exposed on Parity 1.7.
I've updated documentation, thanks for the heads up.

**Comment by sonpython** [comment]
I have the same problem

**Comment by 5chdn** [comment]
@sonpython what's your exact problem?

**Comment by sonpython** [comment]
@5chdn The parity GUI does not accept the new created token using 
`parity signer new-token`

Unable to make a connection to the Parity Secure API

I'm using parity 1.7
It used to worked before

**Comment by 5chdn** [comment]
@sonpython which operating system? which user is running the parity client?

**Comment by sonpython** [comment]
@5chdn 
===
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
===
I'm running parity under `root`

**Comment by 5chdn** [comment]
@sonpython so you have to run `sudo parity signer new-token` (or simply as root)

or grab one valid token from `/root/.local/share/io.parity.ethereum/signer/authcodes`

**Comment by sonpython** [comment]
@5chdn 

`sudo parity signer new-token` ==> also NOT WORK

but the token grabbed from `/root/.local/share/io.parity.ethereum/signer/authcodes` worked

thank you man!!

**Comment by PavelNiedoba** [comment]
Which ports needs to be open and where's the documentation ?

**Comment by folsen** [comment]
@PavelNiedoba Link to documentation is in original post: https://github.com/paritytech/parity/wiki/Wallet-Remote-Access
The ports required are 8180, 8545 and 8546

**Comment by PavelNiedoba** [comment]
@folsen thank you. I stil cannot figure out how to access wallet thorough corporate proxy which allows only ports 433 (and 80 which is not an option). I can open  parity on https default port, but "parity signer new-token" will not work even when time is right

**Comment by tomusdrw** [comment]
@PavelNiedoba IMHO the best way to access the node in such restricted environment would be:
1. Start an SSH server on port 443 on the host machine.
2. Create an SSH tunnel from Client to Host (since 443 is open that should go through, unless there is some http-only proxy on the way)
3. Setup port mapping as described in the docs.

If that's not an option you need to:
1. Setup two domains pointing to the host machine (say, 'parity' and 'ws-parity').
1. Setup an nginx server running on Host machine.
2. Use VirtualHosts and proxy_pass `parity` to `localhost:8180` and `ws-parity` to `localhost:8546`
3. Run parity with `--ws-hosts ws-parity` and `--ui-hosts parity`.

**Comment by PavelNiedoba** [comment]
Thank you, I got it working. I had to add --ws-origins=all to make it work

`/opt/parity/parity \
  --chain=ropsten \
  --db-path=/disk2/ethereumBlockchain \
  --jsonrpc-apis=all \
  --jsonrpc-interface=127.0.0.1 \
  --ws-hosts parity-ws.domain.com \
  --ws-origins all \
  --ui-hosts parity-web.domain.com`

**Comment by Office-Julia** [comment]
@tomusdrw could you please paste link here for the documentation resolving this problem on Windows
It may help for further reference of the users who stuck with this issue.
Thanks.

**Comment by lucas7788** [comment]
how to solve this problem???
<img width="1273" alt="2018-01-12 2 46 37" src="https://user-images.githubusercontent.com/13885466/34862846-72794d48-f7a7-11e7-87ff-bfbeec31eb1e.png">

**Comment by shadowpho** [comment]
Same issue... followed the wiki for Nginx setup.

I'm running parity on a local server and connect to the UI with my laptop. The clocks on both machines are in sync.

Local server runs debian 9 with nginx 1.10.3, andParity/v1.8.6-beta-2d051e4-20180109/x86_64-linux-gnu/rustc1.22.1

**Comment by Tbaut** [comment]
@CorentinPacaud this is a very old and closed issue. Could you please open your own with your details what did you do, what happen etc..
