### ISSUE TITLE
Multi Validator Set panic

### ISSUE THREAD

**Issue by ddorgan** [paritytech/parity#6211]
Spec file:

{

	"name": "test",
       "engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "5",
                "validators" : {
                "multi": {
                    "0": {
                    	"list": [ "0x485fe5bce1a36bf60d018768dea5c6a6caddcbaf" ]
                    },
                    "9": {
                         "list": [ "0x2cd3127ae110a89b89ca6bcee92e1022ca615a77"]
                    }

                    }
                }
            }
        }
     },

    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x8888"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x5B8D80"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
	"0x00Ea169ce7e0992960D3BdE6F5D539C955316432": { "balance": "1606938044258990275541962092341162602522202993782792835301376" }  
    }
}

Run on host 1:
parity --chain spec.json -engine-signer 7ab79cc8b06bb94a50ac92c391ad12125a4c6045 --password pass --force-sealing --reseal-on-txs none

Run on host 2:
parity --chain spec.json --engine-signer fdb2b4d60907e3e66a7e363d19c64bfe1173eaf3 --password pass --force-sealing --reseal-on-txs none

Error on host 1:

2017-08-02 09:07:19 UTC Imported #10 5c7a��1402 (0 txs, 0.00 Mgas, 0.53 ms, 0.56 KiB)
thread 'IO Worker #1' panicked at 'proof produced by this engine; therefore it is valid; qed: Util(Decoder(RlpExpectedToBeList))', /checkout/sr
c/libcore/result.rs:859
stack backtrace:

**Comment by ddorgan** [comment]
Versions tested:

Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
Parity/v1.8.0-nightly-fbb9aff-20170729/x86_64-linux-gnu/rustc1.18.0

**Comment by keorn** [comment]
@rphmeier wasnt that fixed?
