### ISSUE TITLE
IO error: overlayrecent/db/007937.log: No such file or directory

### ISSUE THREAD

**Issue by BatLesStakes** [paritytech/parity#6216]
Hey, 

I try to run a ETH pool and here is my problem : 

====================

stack backtrace:
   0:     0x55869d09c36c - backtrace::backtrace::trace::h18b17b72e62d3e01

Thread 'Verifier #0' panicked at 'DB flush failed.: "IO error: /root/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/007937.log: No such file or directory"', /checkout/src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted

This problem happens everytime I launch it. I have to precise it's a new instance and I don't know not that much about Linux. Can it come from GETH ?

Thanks

**Comment by rphmeier** [comment]
@BatLesStakes 

How is your machine doing on disk space remaining? Could you try clearing the DB with `parity db kill` and starting again with a fresh database?

**Comment by BatLesStakes** [comment]
I think it's a parity problem cause now I have "parity: command not found"

**Comment by BatLesStakes** [comment]
I'll reinstall Ubuntu cause lot of things are wrong, I don't know why.
Parity uninstalls himself, makefiles can't finish...

**Comment by 5chdn** [comment]
Sounds pretty much like either your disk is full or corrupted. Please report back if it keeps coming up again.

**Comment by dipenjoshi** [comment]
happens to me once every week. running it on staging AWS-micro instance with 90GB storage. `df -h` shows 50% disk usage, ram ~500MB out of 1GB. also swap enabled with 2GB assigned. 
I don't think this is a storage full issue. Seems more like a `# of files open` at any given time, issue.
