### ISSUE TITLE
parity --trace on

### ISSUE THREAD

**Issue by zhumingu** [paritytech/parity#6218]
When I run 'parity' in default to the latest date and modify to run 'parity --pruning archive --tracing on ', it report 'TraceDB resync required'. 
How can I  resync  TraceDB? or when I open 'trace on', must I run in the full data model?

**Comment by 5chdn** [comment]
Just reset the database with `parity db reset` and run again with tracing on.

**Comment by zhumingu** [comment]
'parity db reset' reports 'Invalid arguments'.  It not works

**Comment by 5chdn** [comment]
Excuse me, it's `parity db kill`.

**Comment by zhumingu** [comment]
After running 'parity db kill', it reports 'Database deleted', but when running 'parity --pruning archive --tracing on',  it reports 'TraceDB resync required' too.

**Comment by 5chdn** [comment]
Could you paste full logs here (or a screenshot)? Which version is that?

**Comment by arkpar** [comment]
`parity db kill --pruning archive` should do it

**Comment by zhumingu** [comment]
will  `parity db kill` reset db? `--tracing on` be must full data? Is there a fast sync method? I just need the trace after current block.

**Comment by 5chdn** [comment]
Unfortunately not, tracing only works from the beginning.

**Comment by zhumingu** [comment]
thanks. How much disk space does full data need now? and daily increase?

**Comment by 5chdn** [comment]
Some users report around 200GB.
