### ISSUE TITLE
InstantSeal engine does not seal consecutive transactions

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6224]
InstantSeal engine does not seal consecutive transactions if the period of time between them is shorter than `reseal_min_period` - default 2 seconds

**Comment by tomusdrw** [comment]
Running with `--chain=dev` overwrites this setting to 0. Do you have a custom spec file with `InstantSeal`?

**Comment by keorn** [comment]
Now the solution is to run `--config dev` or set `reseal_min_period` to 0. This should be fixed by having `Engine` specific default configs.
