### ISSUE TITLE
Parity UI - Balances should not round (up) [suggestion]

### ISSUE THREAD

**Issue by ajthenewguy** [paritytech/parity#6236]
If you want to round balances on the Accounts tab, please round down, NOT UP.

Even better would be not to round at all; you have what you have, if you only want to show 3 decimal places, fine, show them, but please don't alter them. Also it would be nice to be able to configure how many decimal places to display.

**Comment by gavofyork** [comment]
this will be fixed properly once the new "UI-2" branch is merged and wallet is reworked to use the Bond-based parity-reactive-ui components.

**Comment by ajthenewguy** [comment]
Looking forward to it!
Thanks for your work.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
