### ISSUE TITLE
Cannot import wallet from myetherwallet

### ISSUE THREAD

**Issue by okmrponcho** [paritytech/parity#6240]
I exported the keystore file from myetherwallet to my desktop. I am trying to import the wallet into Parity. I press "+Account", "JSON File",  upload the file, and it won't let me enter a password. The password field is grayed out. I get an error "[-32023] Could not create account."

**Comment by 5chdn** [comment]
Which version of Parity is that?

**Comment by okmrponcho** [comment]
The latest version, 1.7

**Comment by 5chdn** [comment]
Can not reproduce this issue. Could you post a screenshot of that view?

And also, could you open the JSON file and post the first 5 and the last 5 characters here?
