### ISSUE TITLE
Cannot authenticate through parity web ui when using docker

### ISSUE THREAD

**Issue by pydo** [paritytech/parity#6245]
### Bug description
The parity ui always asks me for signer tokens when I'm running it through the docker images. It always  returns a 403 response on any token I enter.

**Affected versions**
v1.6.9, v.1.7.0

### Procedure
**Scenario**: Using parity *v.1.6.9*

`Given` I start parity through docker `docker run -ti -d --name parity -p 8180:8180 -p 8545:8545 -p 30303:30303 -v ~/.local/share/io.parity.ethereum/docker/:/mnt/ parity/parity:v1.6.9 --jsonrpc-apis personal,eth --ui-interface 0.0.0.0 --jsonrpc-hosts all --ui-no-validation --jsonrpc-interface all --base-path /mnt/`

`When` I go to `127.0.0.1:8010` parity asks me for a new-token

`Then`I get a shell into the docker container `docker exec -it parity bash`

`When` I copy the authcodes into a path parity can find `cp ./mnt/authcodes ~/.local/share/io.parity.ethereum/signer/`

`And` I generate a new token `/parity/parity signer new-token`

`Then` I enter the token in the parity web ui

`And` parity returns a 403

------------------------
**Scenario**: Using parity *v.1.7.0*

`Given` I start parity through docker `docker run -ti -d --name parity -p 8180:8180 -p 8545:8545 -p 30303:30303 -v ~/.local/share/io.parity.ethereum/docker/:/mnt/ parity/parity:v1.7.0 --jsonrpc-apis personal,eth --ui-interface 0.0.0.0 --jsonrpc-hosts all --ui-no-validation --jsonrpc-interface all --base-path /mnt/`

`When` I go to `127.0.0.1:8010` parity asks me for a new-token

`Then`I get a shell into the docker container `docker exec -it parity bash`

`When` I copy the authcodes into a path parity can find `cp ./mnt/authcodes ~/.local/share/io.parity.ethereum/signer/`

`And` I generate a new token `/parity/parity signer new-token`

`Then` I enter the token in the parity web ui

`And` parity returns a 403

### Expected behaviour
I should be able to access the web ui when using parity through  docker using these options `docker -v` and parity `--base-path`

### Notes
Sometimes after refreshing the parity web ui page a 100 times it well let me access the web service.
This issue doesn't appear to happen when I don't mount a persistent volume with `docker -v` and `parity --base-path`.

**Comment by pydo** [comment]
I found finally found a workaround. The wiki suggest mounting parity dir to `/mnt`, that's what was making it impossible for me to generate valid tokens. Instead I mount the dir like so (note I abbreviated the command for readability) :

`docker  -v ~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/ `

I can make a PR to update the wiki

**Comment by 5chdn** [comment]
Thanks, I updated the docs.
