### ISSUE TITLE
Unify bloom type

### ISSUE THREAD

**Issue by debris** [paritytech/parity#6249]
todo: 

- [x] update `bloomchain` crate from `0.1` to `0.2`
  - function `contains` has been renamed to `contains_bloom`
- [x] build blooms using `ethbloom 0.2`
- [x] use `ethbloom::Bloom` instead of `Bloom`/`LogBloom`/whatever else we use now
- [x] remove `util/bloomable`

benchmarks:
- `bloomchain 0.2` is 25% faster than `0.1`
- `ethbloom` benches:
  ```
  test accrue_hash                  ... bench:          19 ns/iter (+/- 3)
  test contains_hash                ... bench:         345 ns/iter (+/- 20)
  test does_not_contain_hash        ... bench:         145 ns/iter (+/- 38)
  test does_not_contain_random_hash ... bench:      22,577 ns/iter (+/- 6,791)
  ```

- `parity`, benches - branch [bloomable_benches](https://github.com/paritytech/parity/compare/bloomable_benches?expand=1)
  
  ```
  test accrue_hash                  ... bench:         368 ns/iter (+/- 31)
  test contains_hash                ... bench:         371 ns/iter (+/- 81)
  test does_not_contain_hash        ... bench:         373 ns/iter (+/- 79)
  test does_not_contain_random_hash ... bench:      48,444 ns/iter (+/- 13,557)
  ```

`accrue_hash` - accrues 2 hashes
`contains_hash` - checks if bloom contains 2 hashes (positive)
`test_does_not_contain_hash` - checks if bloom contains 2 hashes (negative)
`test does_not_contain_random_hash` checks if bloom contains 256 hashes (negative)

links:
- [ethbloom](https://crates.io/crates/ethbloom)
- [bloomchain](https://crates.io/crates/bloomchain)

**Comment by stankec** [comment]
Hey! I've started working on this but got a bit confused.

I've updated bloomchain and added ethbloom and started switching out Bloom and LogBloom for ethbloom::Bloom. Though I'm not sure if that should be done to the Bloom type from `ethcore/src/basic_types.rs` (that uses the definition from `ethcore/types/src/log_entry.rs`)

My changes so far - https://github.com/stankec/parity/commits/feature/unify_bloom_type

**Comment by debris** [comment]
> I've updated bloomchain and added ethbloom and started switching out Bloom and LogBloom for ethbloom::Bloom. Though I'm not sure if that should be done to the Bloom type from ethcore/src/basic_types.rs (that uses the definition from ethcore/types/src/log_entry.rs)

Ideally, we would like to also get rid of these two declarations, although it may be quite difficult at first, cause `ethbloom::Bloom` does not implement `rlp::Encodable` / `rlp::Decodable` which is required e.g. [here](https://github.com/paritytech/parity/compare/master...stankec:feature/unify_bloom_type#diff-a703fbc58b8e12c8bc97e68f87976db3L6).

So if something requires `rlp::Encodable` or `rlp::Decodable`, either do not change it (at least not in the first pr) or create a wrapper types which are used only for serialization. 

Does it answer your question? Are there any other issues with the code?

**Comment by stankec** [comment]
I started converting the Bloom definition from `ethcore/types/src/log_entry.rs`, so far I've run into a problem with some missing traits. Namely the two you mentioned and the `Eq` trait.

Also, I'm not sure if this is the correct way to accrue data from H256. I'm not sure if `keccak` is necessary.
```Rust
impl LogEntry {
	/// Calculates the bloom of this log entry.
	pub fn bloom(&self) -> Bloom {
		self.topics.iter().fold(
            Bloom::from(&(&keccak(&self.address).hex())[..]),
            |b, t| {
                b.accrue(
                    Input::Raw(&(&keccak(&self.address).hex())[..].from_hex().unwrap())
                );
                b
            }
        )
	}
}
```

**Comment by stankec** [comment]
Pardons for the double comment. But, I think that `etcbloom` V0.2.4 is broken. While compiling it throws an error that there was an unexpected `@` symbol in the `unroll!` macro from `crunchy` 
(Compiling with 1.22-nightly on darwin). For the moment I downgraded to V0.2.3 to resolve this issue.

**Comment by kirushik** [comment]
@stankec Hi!
What's your status with this issue? Do you need any help in finalizing your work?

Please keep in mind that only PRs submitted in October (which ends tomorrow) qualify for Hacktoberfest.

**Comment by stankec** [comment]
@kirushik  sorry I got swamped with work. I couldn't get it to work, there as always some incompatibility, and no matter how many modules I converted to the new Bloom type there popped up more and more.

Could you perhaps better point out what exactly needs to be changed? 
Hacktober isn't that important to me, I'll try to do it anyway.

**Comment by kirushik** [comment]
@stankec not a problem, work is work.

As stated in the issue descripion, expected result is the ability to drop `util/bloomable` form the codebase completely. So all the occurences should be migrated to use `ethbloom::Bloom`. I can easily understand how this could lead to a really large scope of work.

Your work is on the https://github.com/stankec/parity/tree/feature/unify_bloom_type branch, right? Let me check it out then...

**Comment by kirushik** [comment]
@stankec I've checked out your branch, and looks like it already contains 80% of what needs to be done; I'm currently adding some final touches like RPL encoding for `Bloom` class, and fixing conversions to and from `H2048`.

I'll submit a PR from my private fork to yours, and then you can submit your own PR to the Parity core repo.

Meanwhile, can you please sign our Contributor License Agreement?
https://cla.parity.io/

**Comment by stankec** [comment]
Thanks for the help :)
I signed the CLA
