### ISSUE TITLE
Link to the actual account on Etherscan

### ISSUE THREAD

**Issue by stefek99** [paritytech/parity#6253]
Context-wise it should be obvious.

I'd much rather see the history on my account, not the homepage.

<img width="772" alt="parity" src="https://user-images.githubusercontent.com/249703/29053445-65ea4f42-7bf0-11e7-9bf0-423ca40e49d2.png">

**Comment by shane1900** [comment]
In Chrome PC the link does not work and I don't see my transaction ID until the transaction fully goes thru.

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
