### ISSUE TITLE
Transaction latency - PoA

### ISSUE THREAD

**Issue by deanstef** [paritytech/parity#6257]
Hi all,

through the `trace` module is it possible to know the time passed between the transaction receipt and transaction commitment to the block chain (in a block) ?

Thanks

**Comment by debris** [comment]
Transaction receipt is created when transaction is committed to the blockchain (included in a block), so it's exactly the same time.

If you wanted to ask, if it's possible to know, what time has passed between sending(publishing) the transaction and including it in a block, the answer is no. We do not expose such api

**Comment by deanstef** [comment]
I know the commit time by the block timestamp yes, but i'm not able to find the sending time, i mean when a transaction is submitted to the network.

**Comment by debris** [comment]
We don't store these kind of information, sry

**Comment by deanstef** [comment]
Ok, thanks !
