### ISSUE TITLE
I've just restored the account that may suggest I have backup phrase - do I need to prompted to backup it again?

### ISSUE THREAD

**Issue by stefek99** [paritytech/parity#6272]
![image](https://user-images.githubusercontent.com/249703/29161023-7f95b8b0-7dac-11e7-87c2-1375cdc578c0.png)

_(don't try to reverse engineer blur - always blurring multiple times)_

**Comment by 5chdn** [comment]
> do I need to prompted to backup it again?

Not really, but better safe than sorry. See it as a reminder not to remove your backup after restoring your keys. :)

**Comment by stefek99** [comment]
I'm not that dumb to destroy recovery phase.

I'd much rather be reminded "this is the same recovery phrase, keep it safe"

Prompting to backup suggests it's a new one...

**Comment by 5chdn** [comment]
Thanks, I appreciate your feedback. We are currently only fixing bugs for the UI, but if you have an idea how to improve this, pull requests are certainly welcome :)
