### ISSUE TITLE
Status bar has nonsensical states

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#6273]
I'm running:

- **Parity version**: 1.7.0
- **Operating system**: Any
- **And installed**: Any

---

e.g.:
![image](https://user-images.githubusercontent.com/138296/29163356-7ebc8274-7dbc-11e7-9490-7c84013ea43c.png)

There are currently three criteria contributing to the overall status:

- Chain synchronised (`chain`)
- Connected peers (`peers`)
- Time synchronised (`time`)

In reality, only two are needed and they should be combined in such a way:

- Green iff `peers && chain`
- Orange iff `peers && !chain`
- Red otherwise.

The time being synchronised should be used only as a trouble-shooting mechanism, not as an indication of whether Parity Wallet is "good to go".

**Comment by tomusdrw** [comment]
We also display a warning state if you are connected to only one peer, although it may be nonsensical for private chains.
I wanted to disable that check on non-public networks, do you think it's better to disable it everywhere?

**Comment by 5chdn** [comment]
No, it's fine for private chains. Developers should certainly understand why their private network only has 1-2 peers.

**Comment by 5chdn** [comment]
This is related / should be merged with #6130
