### ISSUE TITLE
Forks not handled appropriately in PoA network

### ISSUE THREAD

**Issue by MasX** [paritytech/parity#6275]
I'm running:
- **Parity version**: 1.6.6
- **Operating system**: Linux 
- **And installed**: via binaries / from source 
- Two authority nodes (AuthorityRound, no authority contract), three normal nodes

Chain of events:
- Chain forks (reason unknown)
- Peer count drops
- `Reorg to #934372 5726…b3bb (bbd1…b202 ff99…29e6 81c8…3c5d 02c6…851a 207a…017e 0f69…7def #934365 74e1…6711 5784…7b31 a7d4…a9aa f229…6344 39f2…753a f6b2…2762 3203…241d)`
- Peer count back to normal

Network traffic increases (starting out at 50kB/s up to 2MB/s)
Double block imports on some nodes:
`2017-08-10 11:13:35  Imported #937015 d4ef…5ce7 (0 txs, 0.00 Mgas, 1.29 ms, 0.57 KiB)
2017-08-10 11:13:40  Imported #937015 3d09…d744 (0 txs, 0.00 Mgas, 1.48 ms, 0.57 KiB)
`
Authority nodes do not seem to recognise anything happening.

Possibly authority nodes are not able to follow the canonical chain? How to fix?

**Comment by 5chdn** [comment]
Could you upgrade to 1.6.10 stable or 1.7.0 beta and clarify what your issue exactly is you experience? Are your nodes on different chains tips?

**Comment by MasX** [comment]
Upgrading would be possible, but only if improvement is expected. 

Yes, the nodes are on different chain tips. 
Issues are:
- Very high data usage after the fork (up to 200GiB/day), at around 20 transactions (ether transfers) per day
- Non-authority nodes see the same blocknumber twice, with different hash. Are they on two tips at the same time?
- Authority nodes do not recognise any issues with the chain they are minting for. No error messages about rejected blocks, and peer count stays up. 

If there is a forked state, I expect nodes to choose a preferred chain. At the moment it looks like they stick with both.

**Comment by keorn** [comment]
There were indeed some fixes in 1.6.7, so upgrading is recommended.
What is the `stepDuration`?

**Comment by MasX** [comment]
Ok, I will look into upgrading.

`stepDuration` is 5. `force_sealing` is true.

**Comment by MasX** [comment]
Unfortunately upgrading is not possible, as we have a `Error: Engine(DoubleVote(852902070f097e5ee70824104cdf9cc3c6ac2dab))` when syncing 1.6.10 and 1.7.0, but not with 1.6.6. I do realise that is an issue in 1.6.6 that has been fixed, but we can not start with a new chain at this point, unless there is a way to port all transactions.

We will disable `force_sealing` to decrease the likelihood of another forked chain and continue on.
