### ISSUE TITLE
Feature Request : Estimate Gas for multiple Transactions

### ISSUE THREAD

**Issue by simon-jentzsch** [paritytech/parity#6281]
In order to test whether a transaction will be executed succesfully, we use `eth_estimateGas`, which is part of the standard JSON-RPC. But in maqny cases we have dependend Transactions ( like a call to approve a ERC20 transfer and then the actual transaction ). 
Is there a chance to implement a version of this call which takes an array of transactions, which will be executed in that order with the state depending on each other?
This would be very helpful.

**Comment by tomusdrw** [comment]
Have a look at #6195.
`parity_call` will just return an array of results, but you should be able to use `trace_callMany` to get gas estimates.
