### ISSUE TITLE
Unable to create wallet after upgrading Parity to 1.7

### ISSUE THREAD

**Issue by nueverest** [paritytech/parity#6285]
I'm trying to create a new parity wallet using version 1.7.  I've created wallets before with the browser interface without an issue under version 1.6.8.

Issue is cross posted here:
https://ethereum.stackexchange.com/q/24162/7187

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Windows 7
> - **And installed**: via installer 
> - **Browser**: Opera

- I just upgraded Parity to 1.7.
- The syncing with the Foundation chain has not completed. 
- I decided to create a new Account while the syncing was happening. 
- I am using the browser interface.

Everything went well until it asked for the owner recovery phrase. I carefully entered this phrase. Clicked the create button. Received this error:

```[-32601] Method not found CLOSE```

I tried re-entering the owner recovery phrase. It still doesn't work. Any thoughts on how to resolve this?

**Comment by dev-dan** [comment]
I had experienced this previously with multiple versions of parity when using the Edge browser, I resolved it by using Firefox instead. Of course this is a work around not a solution...

**Comment by 5chdn** [comment]
@nueverest could you test whether this happens with firefox too, if possible?

**Comment by tomusdrw** [comment]
@nueverest @dev-dan do you guys any `config.toml`? Is `parity_accounts` API enable on WebSockets interface?

**Comment by tomusdrw** [comment]
@nueverest Couple of additional questions:
1. What Opera version did you use?
2. How did you get Parity 1.7? Can you tell us the price version string (bottom left corner of the Wallet)

**Comment by dev-dan** [comment]
I would like to clarify my comment, I am not currently experiencing the issue, though have many times experienced this 'method CLOSE not found' error in my original installation. I experienced it on more than one system as well. I should have been more clear, in my initial comment --  I had said I "previously" experienced this, but I did not provide clear context as to when and under what version. It was with a previous version of parity(not 1.7) and only occurred in the edge browser(not chrome or FF, though I did not try opera). Now that I am running a more recent version I am not experiencing it.

**Comment by nueverest** [comment]
Opera 47.0.2631.39

**Comment by nueverest** [comment]
When I try to open with Firefox I get:

![image](https://user-images.githubusercontent.com/2917370/29301463-383af20e-8131-11e7-8df3-71d484dc3df2.png)

**Comment by 5chdn** [comment]
What happens if you follow the instructions in Firefox?

**Comment by 5chdn** [comment]
Does this still occur?

**Comment by nueverest** [comment]
I found that running `parity signer new-token` fixes the issue. However, I have to run this command every time I start Parity or open a new browser window.  It also makes me accept the terms of service every time. This is getting cumbersome.

**Comment by 5chdn** [comment]
> I found that running parity signer new-token fixes the issue. However, I have to run this command every time I start Parity or open a new browser window. It also makes me accept the terms of service every time. This is getting cumbersome.

You are probably deleting cookies and clearing cache on shutdown? There is not much we can do about,  except this #6331.

**Comment by 5chdn** [comment]
@tomusdrw might be authentication issues.

**Comment by debris** [comment]
please reopen if still relevant
