### ISSUE TITLE
Add a comandline option to execute a custom stateTest 

### ISSUE THREAD

**Issue by winsvega** [paritytech/parity#6286]
With random state test generation we need a support option from the clients to run a custom .json file that is a StateTest.

The file format is here:
https://github.com/ethereum/tests/blob/develop/GeneralStateTests/stExample/add11.json

The usage should be like following:
./parity --runfile "/GeneralStateTests/stExample/add11.json" --format "StateTest"

the client should return whether the test execution was success or not.
if it is a failure it should provide information on which fork rule there was an error.
so then we could debug it more carefully.

**Comment by tomusdrw** [comment]
I think it fits more to `parity-evm` binary.
