### ISSUE TITLE
problem of time synchronized on Mac system

### ISSUE THREAD

**Issue by blockchainhong** [paritytech/parity#6287]
> I'm running:
> - **Parity version**: 1.7.0
> - **Operating system**:  MacOS 
> - **And installed**: via installer 

i juat download the parity installer for Mac, then create a new account and try to run it, but before that the system warning was all-time show up like this:
---Unable to reach time API: NTP error: NTP server is not provided.. Make sure that your clock is synchronized.

How Can i fix this problem, on Mac system how synchronize my local computer time with internet time, and must use to be solve it with tool of NTP, or not? 

Thanks a lot

**Comment by blockchainhong** [comment]
why my computer  local time is forever automatically 2 sec slower than standard UTC time although whatever i do? how can fix this?

**Comment by 5chdn** [comment]
You can ignore that warning. It will be improved with the next release.

See #6130 and #6273.

**Comment by blockchainhong** [comment]
@5chdn thanks, but i'm worried about normally while i using thansfer especially transfer after exact block function without solve this problem, or it doesn't effect them. thanks a lot.

**Comment by blockchainhong** [comment]
i have sent Ether from my another wallet to my new one(parity), and already in network confirmed, why can't it  just display? cause of  parity wallet not syned yet?

**Comment by crsCR** [comment]
V. 1.7.2-beta Windows 10 64... Still problem with this - have tried resynching with time servers, turning off and on, etc. Keep getting 'Your clock is not in sync...'

**Comment by AntoniosHadji** [comment]
@blockchainhong Yes, if your parity wallet is not synced you will not see transactions from the blocks that have yet to be synced.
