### ISSUE TITLE
Recover account

### ISSUE THREAD

**Issue by Mandelliant** [paritytech/parity#6288]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows / MacOS / Linux
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

Not so much an issue as an error on my part- I had a Parity account set up with a wallet used to receive Storj... on a computer that has since been reformatted. If I can somehow dig up information (key/address), is there any way to recover and gain access to that account?

**Comment by tomusdrw** [comment]
To restore an account you need either:
1. Recovery phrase or
2. password-protected JSON key file

If you have either one you will be able to recover your account via Parity Wallet (Click "+ Restore" or "+ New -> JSON keyfile")
