### ISSUE TITLE
Parity down

### ISSUE THREAD

**Issue by Surfang** [paritytech/parity#6289]
ubuntu16.04
rustc 1.19.0

stack backtrace:
   0:     0x55c559278abc - backtrace::backtrace::trace::h32de0b1a6d8ad154

Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:537

open ethereum pool
2017/08/13 10:25:26 Error while refreshing pending block on main: Post http://127.0.0.1:8540: EOF
2017/08/13 10:25:26 Error while refreshing pending block on main: Post http://127.0.0.1:8540: EOF
2017/08/13 10:25:26 Error while refreshing pending block on main: Post http://127.0.0.1:8540: dial tcp 127.0.0.1:8540: getsockopt: connection refused
2

**Comment by 5chdn** [comment]
Which parity version? How did you configure your client?

**Comment by Surfang** [comment]
$ git clone https://github.com/paritytech/parity
$ cd parity

# build in release mode
$ cargo build --release

**Comment by 5chdn** [comment]
What's the output of `parity --version`? And what configuration are you using? Any config file or command line flags you can share?

**Comment by Surfang** [comment]
version Parity/v1.8.0-unstable-604ea5d-20170810/x86_64-linux-gnu/rustc1.19.0

**Comment by 5chdn** [comment]
Ok, please subscribe to #6239 - I didn't see this before. If you don't need latest nightly builds, you can still use 1.7.0 which is not affected.
