### ISSUE TITLE
Theme issue: Hard to read text (almost invisible)

### ISSUE THREAD

**Issue by madnight** [paritytech/parity#6290]
![](https://i.imgur.com/vltNZFt.png)

Is it just me or is "0 outgoing transactions" hard to read?

**Comment by 5chdn** [comment]
Which Parity version? Which operating system? And which browser do you use?

**Comment by madnight** [comment]
All parity versions (at least for this year). Arch Linux (up to date). Chromium / Firefox.

**Comment by 5chdn** [comment]
Yeah, that's a very dark gray `rgb(18, 18, 18)` on a very opaque black.

**Comment by jon-choi** [comment]
Think the simplest solution is actually upping the opacity from 0.25 to 0.5. PR coming.

`js/src/views/Account/Header/header.css`
![image](https://user-images.githubusercontent.com/9872658/29635030-9d4177ce-8800-11e7-91b0-2cf7ee35198b.png)

before
![image](https://user-images.githubusercontent.com/9872658/29635071-bd1077e4-8800-11e7-825f-eff5a77400f8.png)

after
![image](https://user-images.githubusercontent.com/9872658/29635094-c9e069f2-8800-11e7-8c49-bc0a1929461c.png)

**Comment by madnight** [comment]
yes, that should fix the issue, the "after" screenshot is also perfectly readable on my screen
