### ISSUE TITLE
Database error when attempting to run

### ISSUE THREAD

**Issue by dataninja23** [paritytech/parity#6291]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: most recent
> - **Operating system**: Windows 
> - **And installed**: via installer 

_Open the parity application
---
receive the error:

Client service error: Client(Database("Invalid argument: You have to open all column families. Column families not opened: col0, col1, col2, col3, col4, col5, col6"))

**Comment by 5chdn** [comment]
There is nothing like a most recent version, could you state which version exactly you are running? Thanks

**Comment by dataninja23** [comment]
I am not sure how to tell since the application won’t open?  Can you assist?

**Comment by 5chdn** [comment]
`parity --version` should print out the version string without opening the database. Should work.

`parity db kill` is the first thing I would check if my database misbehaves. Please report back if this resolves your issue.

**Comment by dataninja23** [comment]
Yes…the db kill resolved my issue.
