### ISSUE TITLE
DentToken won't send

### ISSUE THREAD

**Issue by mjbayly** [paritytech/parity#6292]
Hi there

I've tried multiple times to send my Dent tokens from Parity to My Ether Wallet and to my HitBTC Dent address. What's happening? I've pumped the gas, have sufficient gas in my wallet and everything.

https://etherscan.io/tx/0xb465da1b4b03ef02dd820a74919c7cc1a64a113dadae50216bdb9fd94555e884

**Comment by 5chdn** [comment]
You only provided 50_000 gas, try something like 200_000 and it should work.
