### ISSUE TITLE
Array size limit of a returned array from a contract function call in Solidity

### ISSUE THREAD

**Issue by msbachler** [paritytech/parity#6293]
I have a contract storing rdf data in various mappings on our Parity dev chain. It is all  working lovely except for large array returns. I have functions to  return arrays of hashes matching certain criteria. I have found, through  testing, that a function call to the contract that returns an array of 36,000 bytes32 hashes works fine. However, a function call to the contract that should return an array of 100,000 records fails (later refined to 60,000 worked but 63,000 didn't). 

An example function I am calling is:

>// return a bytes32 array of hashes matching a subject search hash
>function getSubjectArray(bytes32 which) public constant returns (bytes32[]) {
>    return subjectindex[which];
>}

I was originally testing using web3 function calls to the contract, then I decided to test using direct curl commands to see if it was a web3 issue. But it behaves the same using curl. A result array of 36,000 hashes returns from the curl call successfully, but a result array of 100,000 returns just '0x'.

>curl --data '{"id":1,"jsonrpc":"2.0","method":"eth_call","params":
>[{"to":"0x0a0bdad3a719adacf6ef29299b25f4799c3961ba","data":"0xd6cf19ffa6ccec97d46345da54fa1ac
>0a269b860a855d19895705920f2fdfb4eb786817a"},"latest"]}' -H "Content-Type: application/json" -X 
>POST 127.0.0.1:55200

>{"jsonrpc":"2.0","result":"0x","id":1}

I have stepped though this large results array using a separate function passing an index, so I know all the 100,000 records are there to be returned. So it seems to be a limit on the size that an array returned from a function call to a contract can be.

Can anyone confirm if there is a limit that an array being returned from a function can be?

**Comment by 5chdn** [comment]
Thanks for opening this issue, context: https://ethereum.stackexchange.com/questions/23918/what-is-the-array-size-limit-of-a-returned-array-from-a-contract-function-call-i

**Comment by tomusdrw** [comment]
I was able to reproduce that, still need to identify the issue.

**Comment by tomusdrw** [comment]
The issue is that the transaction is running out of gas, the default is 50M. As a workaround you can specify gas limit manually.

**Comment by msbachler** [comment]
I did try the maximum amount of gas and it made no difference in my tests (see stack exchange thread)

**Comment by msbachler** [comment]
As I said in the stack exchange, I thought reads where free. I am not specifying even an account to take money from and it gets an array of 60,000 records. So where would it be taking the ether from?

**Comment by tomusdrw** [comment]
Yes, reads are indeed free, but `eth_call` is just creating a "virtual" transaction that gets executed in the context of the blockchain. It's not subject to block gas limit that you tried (4.7M), but still gas calculation is being done for anything that `eth_call` does (for instance to prevent infinite loop). Our default gas limit was `50M` and taking out ~64k of `bytes32` was hitting the limit, you should try specifying something much larger like `2**50`

**Comment by msbachler** [comment]
Sorry for my ignorance. Is this something I do on the individual call or in the parity config/spec of my chain?

**Comment by tomusdrw** [comment]
It's an optional parameter of `eth_call`:
```
curl -H "Content-Type: application/json" -X POST 127.0.0.1:55200 \
  --data '{"id":1,"jsonrpc":"2.0","method":"eth_call","params":
[{"to":"0x0a0bdad3a719adacf6ef29299b25f4799c3961ba","data":"0xd6cf19ffa6ccec97d46345da54fa1ac
0a269b860a855d19895705920f2fdfb4eb786817a", "gas":"0x4000000000000"},"latest"]}'
```

**Comment by msbachler** [comment]
Thank you for your clear explanation. I thought if I specified more than the 4.7M it would throw and error. I will test.

**Comment by msbachler** [comment]
Finally, after one of my Parity chains was just refusing to play, I managed, on a different chain, to pull down 100,000 bytes32 array by specifying the massive gas on the function call. Thank you so much again for walking my brain through this issue.
