### ISSUE TITLE
error: `pub(restricted)` syntax is experimental (see issue #32409)

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6294]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0

From current source tree 14 August 2017

> - **Operating system**: Windows / MacOS / Linux

Debian 9

> - **And installed**: via installer / homebrew / binaries / from source

Attempting to install from source.

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am attempting to install from source on Debian 9.

The following are fine:
`# apt-get install openssl libssl-dev libudev-dev`

`$ curl https://sh.rustup.rs -sSf | sh`

`$ git clone https://github.com/paritytech/parity`
`
$ cd parity`

Then I alter my path and then I type:
`
$ cargo build --release`

Compilation proceeds and then aborts.  Here is a printout beginning when things are still green/good:

>    Compiling libflate v0.1.9
   Compiling unicode-width v0.1.4
error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/zlib.rs:202:9
    |
202 |     pub(crate) fn read_from<R>(mut reader: R) -> io::Result<Self>
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
  --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/gzip.rs:98:5
   |
98 | pub(crate) struct Trailer {
   |     ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/gzip.rs:370:9
    |
370 |     pub(crate) fn read_from<R>(mut reader: R) -> io::Result<Self>
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
  --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/deflate/mod.rs:29:5
   |
29 | pub(crate) mod symbol;
   |     ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
  --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/non_blocking/deflate/decode.rs:72:9
   |
72 |     pub(crate) fn bit_reader_mut(&mut self) -> &mut TransactionalBitReader<R> {
   |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:143:9
    |
143 |     pub(crate) fn state(&self) -> BitReaderState {
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:150:9
    |
150 |     pub(crate) fn restore_state(&mut self, state: BitReaderState) {
    |         ^^^^^

error: `pub(restricted)` syntax is experimental (see issue #32409)
   --> /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/libflate-0.1.9/src/bit.rs:171:5
    |
171 | pub(crate) struct BitReaderState {
    |     ^^^^^

error: aborting due to 8 previous errors

I have searched for issue 32409 and it seems like a closed issue with rust.  I do not understand why Parity is triggering this error.

I'm probably doing something foolish.

---

**Comment by 5chdn** [comment]
https://github.com/rust-lang/rust/issues/32409

Are you building from master branch? What's the output of `rustc --version`?

**Comment by stone212** [comment]
```
$ rustc --version
rustc 1.17.0 (56124baa9 2017-04-24)
```
I think I am building from master branch.  I am typing what it says in the instructions.  Here is my Git command:

`$ git clone https://github.com/paritytech/parity`

**Comment by 5chdn** [comment]
Parity requires Rust version 1.19.0 to build.

**Comment by stone212** [comment]
Thank you.  But if that is true then maybe it's time to update this page:
https://github.com/paritytech/parity/blob/master/README.md

Specifically, the part where it says:

`Build dependencies

Parity requires Rust version 1.18.0 to build

We recommend installing Rust through rustup. If you don't already have rustup, you can install it like this:

    Linux:

     

> $ curl https://sh.rustup.rs -sSf | sh

`

**Comment by 5chdn** [comment]
Yes. Will update this now. Did you manage to build it with Rust 1.1.19?

**Comment by stone212** [comment]
Yes, can confirm success with Rust 1.19.0.  (Also, the way to update to 1.19.0 from the instructions on your README.md is to make sure your environment is set and then then run the following command:

`$ rustup update stable`

)
