### ISSUE TITLE
No Snapshots downloaded when using warp with Ubuntu 16

### ISSUE THREAD

**Issue by PhABC** [paritytech/parity#6297]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**:  Linux
> - **And installed**: via binaries

Using the `parity --warp` command in my Ubuntu 16 console, I was expecting to see some snapshots being downloaded via the warp function. Not specifying the `--warp` argument results in the same behavior, where no snapshots seem to be downloaded. My girlfriend synced her parity on her windows machine in about 15 minutes after not opening it for > 1 months, and it took me about the same time to sync the few hours I missed while my linux machine wasn't syncing. I could see in her log that snapshots were downloaded, but I personally only see that parity is "syncing" (see this [image](https://i.imgur.com/mpHMBZU.png)).

---

**Comment by 5chdn** [comment]
Note, `--warp` is enabled by default and the flag does nothing. If you have issues with snapshot restoration, try adding additional warp sync peers with something like `--snapshot-peers 15`.

**Comment by arkpar** [comment]
Snapshot sync only kicks in if the node is more than 100000 blocks behind the head of the chain. We might want to revise that constant give that recent blocks are much slower to process.

**Comment by PhABC** [comment]
@5chdn Yes I know, just wanted to make it explicit. I will try to use the `snapshot-peers' argument next time.

@arkpar 100k seems like a lot. Even 10k can take up to 1-2 hours.

**Comment by kommen** [comment]
I'm running into the exact same issue here. 
Partity 1.7.0 on Ubuntu 16.

Then it starts syncing one block at a time, which will take me ages to catch up to the latest block.

**Comment by 5chdn** [comment]
@PhABC yes, this is due to the huge amount of transactions per day currently processed by the Ethereum blockchain. 100k blocks used to be no issue one year ago.

**Comment by fugroup** [comment]
Any way to force snapshotting? Version 1.7.10 and 1.8.4beta is not fetching snapshots at all, sync is horribly slow. It used to fetch snapshots though, it's weird, but no more.

**Comment by 5chdn** [comment]
Try to remove your nodes.json and increase the number of --snapshot-peers

**Comment by slavicd** [comment]
This should not have been closed: confirmed behavior in 1.8.4: no snapshots are used either before or after deleting the db.

**Comment by 5chdn** [comment]
@slavicd #6372
