### ISSUE TITLE
Improve filesystem error logging

### ISSUE THREAD

**Issue by MasX** [paritytech/parity#6298]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Linux
> - **And installed**: from source

Parity failed to save its cache folder (already fixed (#6207)), but not in the version I'm running. The issue here is how I/O errors are reported.

Issue: logged error is vague:
```
Loading config file from /path/to/node.toml
Permission denied (os error 13)
```
The actual problem is writing a `$BASE/.cache`, NOT reading the toml as the log suggests.

Expected:
```
Loading config file from /path/to/node.toml
Failed to write cache folder at /home/parity/.cache
```

**Comment by 5chdn** [comment]
That's already fixed in master #6207 via #6212 - please wait for the 1.7.1 release.
