### ISSUE TITLE
Parity is incorrectly displaying REP as AUG.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6301]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

Augur's REP token had to be migrated to a new contract due to a Serpent bug in the original contract.  The original contract still exists and has balances but they are non-transferable.  In the UI, the old broken REP contract is showing up as REP tokens while the new, correct, contract is showing up as AUG.  I'm not sure where the AUG came from, the Augur team has made it clear that the new token is REP and the contract reports REP as its symbol.

This is causing confusion for Augur users as they both see two balances, and the one that is labeled correctly (REP) is _not_ their actual REP balance while the one that is labeled incorrectly (AUG) is their REP balance.  What needs to happen to get this fixed?

**Comment by 5chdn** [comment]
Thanks for the reminder, will do that asap.

**Comment by 5chdn** [comment]
Fixed.
