### ISSUE TITLE
Error upgrading parity data: CannotCreateConfigPath when starting parity

### ISSUE THREAD

**Issue by WouterSchaekers** [paritytech/parity#6303]
**actual behavior**
Error upgrading parity data: CannotCreateConfigPath

**expected behavior**
Start parity.

**steps to reproduce**
Run: $parity

> I'm running:
>
> - **Parity version**: v1.7.0-beta-5f2cabd6e-20170727/x86_64-linux-gnu/rustc1.19.0
> - **Operating system**: Arch Linux
> - **And installed**: binaries (Pacman)

**Comment by 5chdn** [comment]
Could you paste the full log output here please?

**Comment by WouterSchaekers** [comment]
There is nothing in the logfile, even when I run with --log-file.
I found out I can run parity with sudo, so it had to do with permissions. Seems like it tries to find the blockchain and keys in a different folder than before.
After supplying --db-path and --keys-path, the problem was fixed.

**Comment by 5chdn** [comment]
Please, don't run Parity with superuser privileges.

I didn't refer to a log file, but the terminal output. Where do you see `CannotCreateConfigPath`? Is there anything else?

**Comment by WouterSchaekers** [comment]
_Error upgrading parity data: CannotCreateConfigPath when starting parity_
is the only thing I see.

**Comment by HaleTom** [comment]
@WouterSchaekers is the output of:

```
strace -fs 80 parity --light |& grep ENO | uniq
```

**Comment by kot-begemot** [comment]
If you use `--db-path` to specify database path, make sure that your storage is properly mounted and and writable

**Comment by tomachinz** [comment]
miner@nuzilan:~/.safe$ parity --db-path="/balls/parity/"
Error upgrading parity data: CannotCreateConfigPath
miner@nuzilan:~/.safe$ strace -fs 80 $parity |& grep ENO | uniq

miner@nuzilan:~/.safe$
miner@nuzilan:~/.safe$

**Comment by celeduc** [comment]
This happens when installing stable parity from a snap (`sudo snap install parity`). It does not happen when installing stable parity from a `.deb` (`bash <(curl https://get.parity.io -L)`.

**Comment by quantumproducer** [comment]
Yep, switching to .deb install from snap fixed it for me.

**Comment by 0x-genesys** [comment]
Got this error when --db-path provided was incorrect or storage was not mounted
