### ISSUE TITLE
Parity will not open

### ISSUE THREAD

**Issue by AndrewKralovec** [paritytech/parity#6306]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
parity_1.7.0
> - **Operating system**: Windows / MacOS / Linux
Windows 10
> - **And installed**: via installer / homebrew / binaries / from source

Windows installer found here `https://parity.io/parity.html`

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hey guys, i have parity installed. I had it originally working and put some etherum in it. It has been a few weeks since i opened it and i decided to open it to look at my balance. However, it longer will open. Does anyone have some trouble shooting tips to get it started? Or know where i can get some help with it
I have windows 10, and i can see the icon show up in the task bar vary preferably, then it disappears. I'm also open to how to get my etherum out of my parity wallet. 

I tried running it in cmd and i get this following output

```
C:\Program Files\Ethcore\Parity>parity.exe ui
2017-08-15 22:11:09  Starting Parity/v1.6.8-beta-c396229-20170608/x86_64-windows-msvc/rustc1.17.0
2017-08-15 22:11:09  State DB configuration: fast
2017-08-15 22:11:09  Operating mode: passive
2017-08-15 22:11:09  Configured for Foundation using Ethash engine
2017-08-15 22:11:09  Updated conversion rate to Ξ1 = US$286.24 (415901400 wei/gas)
Client service error: Client(Database("Invalid argument: You have to open all column families. Column families not opened: col0, col1, col2, col3, col4, col5, col6"))
```
---

**Comment by AndrewKralovec** [comment]
Update, someone suggested i do, parity db kill is 
And now it opens. But my wallet is empty
Did i just lose my etherum ?

**Comment by folsen** [comment]
Your database is not really associated with your private keys, as long as you didn't delete your private keys you will not have lost any Ether.

Are you sure that you have synced to the best block? Make sure your node is fully synced and your Ether should show up again!

**Comment by 5chdn** [comment]
You are not the first reporting this issue. Could you try resetting your database with `parity.exe db kill`.

**Comment by AndrewKralovec** [comment]
@5chdn I did parity.exe db kill, but my wallet is now empty. 
@folsen  i don't think i deleted my keys. My wallet address is the same. You can even see that i sent ETH to it from my coin base account. But the balance just inst there. Do you think sycning would fix this issue, and how do i do that ?

![image](https://user-images.githubusercontent.com/6210337/29393267-65074876-82c8-11e7-9507-572206eb65f4.png)

**Comment by 5chdn** [comment]
Are you fully synchronized? Please check the status page. Balance will not show up unless you fetched the latest state.

**Comment by AndrewKralovec** [comment]
@5chdn , yeah i re-synced it and waited a few hours. The balance is now showing up correctly.

**Comment by Basguy** [comment]
I am having a similar issue, but when I try the `parity.exe db kill` function I get 
"this app cant run on your PC" error and the command prompt says access denied.
As far as I know I am the admin of this computer, any suggestions?
