### ISSUE TITLE
How do I restore account / wallet from private key?

### ISSUE THREAD

**Issue by stefek99** [paritytech/parity#6307]
Research: https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring

It's related to - https://0xproject.com/sale - I'd like to configure Parity to send after a certain block / timestamp...

So I need to use whitelisted account, so I need to import wallet into Parity... Just don't know how?

UI:

<img width="1201" alt="screen shot 2017-08-16 at 09 20 36" src="https://user-images.githubusercontent.com/249703/29354075-3e4c816a-8264-11e7-9320-c5be68fbb3cf.png">

**Comment by 5chdn** [comment]
Go to ACCOUNTS -> click + ACCOUNT -> and select PRIVATE KEY -> click NEXT and enter your hexadecimal private key.

**Comment by AyushyaChitransh** [comment]
How can it be done using CLI or without using UI?

**Comment by 5chdn** [comment]
curl --data '{"method":"parity_newAccountFromSecret","params":["0x1db2c0cf57505d0f4a3d589414f0a0025ca97421d2cd596a9486bc7e2cd2bf8b","hunter2"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

https://wiki.parity.io/JSONRPC-parity_accounts-module#parity_newaccountfromsecret
