### ISSUE TITLE
Memory leak with pruning=fast on Kovan

### ISSUE THREAD

**Issue by ANDYVDL** [paritytech/parity#6309]
I'm running: Parity 1.6.9 on Linux via installer

Parity constantly runs out of memory when i'm using 'pruning = "fast"' on Kovan. On the mainnet pruning works fine. 'pruning = "archive"' also works flawless on Kovan.
Somehow it synced to block ~2.000.000 before it started leaking, since then it just eats up my 3GB memory till it crashes. I tried playing around with the cache-size and pruning-history/memory settings but Parity seems to ignore them.

**Comment by 5chdn** [comment]
Does this also happen with 1.6.10 or 1.7.0?

**Comment by 5chdn** [comment]
Can not reproduce with 1.7.0, user not responding.

**Comment by ANDYVDL** [comment]
I think it was my fault due to a too high pruning history setting.
Still struggling with random mem leaks from time to time.

**Comment by 5chdn** [comment]
Thanks!
