### ISSUE TITLE
Parity account does not credit deposits (ETH)

### ISSUE THREAD

**Issue by gregMartin12** [paritytech/parity#6310]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7
> - **Operating system**: Windows 
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---ETH deposits to my parity account do not appear and are not credited even though etherscan shows deposit successfully going in and displays correct account balance

**Comment by blockchainhong** [comment]
i have same questions, have you solved it already ?

**Comment by 5chdn** [comment]
What's your node status? Do you have any peers? Are you fully synchronized?

**Comment by blockchainhong** [comment]
@5chdn  it show up all-time like this:
 Unable to reach time API: NTP error: NTP server is not provided.. Make sure that your clock is synchronized.
connect peers was stabilize between 6~7

**Comment by 5chdn** [comment]
And block number? Are you fully synchronized?

**Comment by blockchainhong** [comment]
@5chdn  see that on right lower corner? by me it just shows up %0.00 warp restore, and now the status of node health shows like this:**Your node is still syncing, the values you see might be outdated. Wait until it's fully synced.**
and what makes me very disappointed is , the client crashed all time  so that i have to always restart it.

**Comment by 5chdn** [comment]
Which version, which operating system? What crash message do you see?

**Comment by blockchainhong** [comment]
@5chdn 
mac installer
version:1.7.0
Crash means it dosen't reaction any more whatever i do, so i have to close it by forcing...then restart, however it happened this again and again.

**Comment by 5chdn** [comment]
Don't force a shutdown. It's writing the chain and state to the database. Your balance will display as soon as your client is fully synchronized.
