### ISSUE TITLE
When setting point in the future to send funds - allow resolution up to the second.

### ISSUE THREAD

**Issue by stefek99** [paritytech/parity#6315]
https://www.reddit.com/r/0xProject/comments/6tplja/0x_token_sale_megathread/

> Day 2 starts at 8h00m12s PT today, August 16th.

Of course it will be sold in a single block!

![image](https://user-images.githubusercontent.com/249703/29370218-9a2d413a-829c-11e7-85ab-8ab51c8c2fb0.png)

**Comment by 5chdn** [comment]
We are not adding any features to the current user interface until the new version is released. This ticket will be revisited once the release is out. Meanwhile it's logged [here](https://github.com/paritytech/parity-long-term-issues/issues/2).
