### ISSUE TITLE
Question - is it possible to schedule transaction in the future and execute while being offline, or do I need to be connected all times?

### ISSUE THREAD

**Issue by stefek99** [paritytech/parity#6320]
I'll be taking a plane.

I've transmitted some ETH to Jaxx wallet so I can participate in the ICO on mobile.

Is is possible to schedule transaction in the future (while still online) to be executed while on the plane (offline)?

https://twitter.com/decentraland/status/897869824080175104

![image](https://user-images.githubusercontent.com/249703/29403489-59e331b8-8330-11e7-9d38-54b981870b31.png)

**Comment by 5chdn** [comment]
You need to be online to broadcast the scheduled transaction.
