### ISSUE TITLE
Improve container support.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6324]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Linux
> - **And installed**: Docker

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

At the moment, several of Parity's configuration options come in via files only, such as reserved node list.  When running Parity in a container (e.g., Docker), adding custom configuration files to a deployment is much harder than configuring via environment variables or command line options.  At the moment I have a Parity node running in my Docker cluster but I have no mechanism to add a reserved node without building a custom docker image anytime I want to change a reserved node.  This is because while my docker containers keep the chain data on disk, everything else (e.g., config files) is stored on Docker container ephemeral disks and not easily mutable.

Ideally, all of Parity's configuration options become available via environment variables as this is usually the easiest way to inject dynamic configuration in most container orchestration systems.  Alternatively, at least making all options available via command line and/or environment variables would be a big step up.

**Comment by 5chdn** [comment]
Moved inactive feature requests to the [long-term enhancement-list here](https://github.com/paritytech/parity-long-term-issues/issues/3) to keep our bug-tracker clean.
