### ISSUE TITLE
Withdraw from SSH

### ISSUE THREAD

**Issue by BatLesStakes** [paritytech/parity#6325]
Hey, 

I have 3.75 ETH on a Parity's instance.
This is a VPS without graphic interface so I can't access the Parity's website.
I was also searching how to withdraw from SSH connection, I don't have it neither.
Do anyone has a solution to withdraw my coins ?

Thanks

**Comment by 5chdn** [comment]
You have multiple options here. You can either copy the keys to your local machine (scp, rsync) and use then with your local node; Or you use [eth_sendTransaction](https://github.com/paritytech/parity/wiki/JSONRPC-eth-module#eth_sendtransaction) RPC call to create the transaction from command line, like this:

    curl --data '{"method":"eth_sendTransaction","params":[{"from":"0xb60e8dd61c5d32be8058bb8eb970870f07233155","to":"0xd46e8dd67c5d32be8058bb8eb970870f07244567","value":"0x9184e72a"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

Note, if you have no access to the signer, you will have to unlock your account first: [personal_unlockAccount](https://github.com/paritytech/parity/wiki/JSONRPC-personal-module#personal_unlockaccount).
