### ISSUE TITLE
DB corrupted due to 'cannot access stderr during shutdown'

### ISSUE THREAD

**Issue by xenoexclusive** [paritytech/parity#6326]
I'm running:
> - **Parity version**: 1.7.0
> - **Operating system**: Ubuntu 16.04
> - **And installed**: via one-line installer

Upon terminating Parity in terminal via CTRL+C, parity has the following error, which leads to a corrupted database/chain:

_'thread '<unnamed>' panicked at 'cannot access stderr during shutdown', /checkout/src/libcore/option.rs:794
stack backtrace:
    0: <unknown>
    1: <unknown>
    2: <unknown>
    3: <unknown>
    4: <unknown>
    5: <unknown>
    6: <unknown>
    7: <unknown>
    8: <unknown>
    9: <unknown>
    10: <unknown>
    11: <unknown>
    12: <unknown>
    13: <unknown>
    14: <unknown>
    15: <unknown>
    16: <unknown>_

Displayed in image linked http://imgur.com/8B8Y83A

**Comment by xenoexclusive** [comment]
Rendering Parity basically unusable as of 1.7.0.

About 50 percent of sessions end up corrupting so I'm having to warp sync every use.

**Comment by tomusdrw** [comment]
Most lilkely related to WS errors being printed out. @xenoexclusive do you have any service connecting to websockets interface? Do you use Parity Wallet in the browser?

**Comment by xenoexclusive** [comment]
@tomusdrw Yes I am using the Parity Wallet in browser in Chrome.

**Comment by lght** [comment]
@xenoexclusive I'm having trouble reproducing this issue. Could you try upgrading to the latest build to see if the error still occurs?

**Comment by xenoexclusive** [comment]
I no longer seem to have this error upon updating.

**Comment by 5chdn** [comment]
Replaced by #7032.
