### ISSUE TITLE
Feature Request: Separate UI from Node

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6327]
My recent performance problems with Parity on my laptop have given me a desire to use my cloud Parity node (which seems to have no problems) as a backend for my current local Parity frontend.  However, I am not comfortable with putting my private keys on my cloud node and I want to be able to use the Parity UI.

I would like to see the Parity UI split from the Parity Ethereum Node so that I can run them on different machines.  This would also allow me to put Parity UI on all of my computers and sync them up to my cloud node.  I would also be able to run a cloud node for my friends and allow them to get into Ethereum quickly by just installing Parity UI and pointing at my cloud node.

**Comment by 5chdn** [comment]
Probably what you are looking for: This feature is already implemented and called _public node_. It's not very well documented yet, but if you have a cloud node, run it with the `--public-node` flag. This will serve a public accessible user interface on your remote instance. But all keys and configuration are stored locally in your browser. We need this documented #6181

Please, let me know if you have any other questions.
