### ISSUE TITLE
mainnet chain spec file is 404

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6328]
Go to here:
https://github.com/paritytech/parity/wiki/Chain-specification

Click on mainnet link:
https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/frontier.json

See 404 Jedi.  Be sad. :(

---

**Comment by 5chdn** [comment]
Thanks, fixed.

https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json
