### ISSUE TITLE
Inconsistent JSON-RPC results for Ethereum Classic - network id

### ISSUE THREAD

**Issue by gagarin55** [paritytech/parity#6330]
> I'm running:
>
> - **Parity version**: v1.6.8-beta-c396229-20170608/x86_64-linux-gnu/rustc1.17.0
> - **Operating system**: Linux

Having Parity with --chain=**classic**

`net_version` returns **network id = 1**

```
curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' https://mewapi.epool.io           

{"jsonrpc":"2.0","result":"1","id":67}
```

Whereas `eth_getTransactionByHash` return **network id = 61**

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x2039db8df5291bb103ef2c52a22119b0df1635b0562c5d634ffc58209d649787"],"id":67}' https://mewapi.epool.io

{"jsonrpc":"2.0","result":{
...
"networkId":61,
...
},"id":67}

````

Should we have equal network id in both cases ?

---

**Comment by sorpaas** [comment]
Related to https://github.com/paritytech/parity/pull/6329

Just think that there're also several cases in Parity which should be called `chain_id` but instead is `signing_network_id`, which creates some confusion.

**Comment by tomusdrw** [comment]
Indeed, `net_version` returns the network id (used for networking) not the chain id (used for signing). Working on a PR to fix up the naming.
