### ISSUE TITLE
web3.eth.getBlock returns null on certain blocks (e.g. 924645)

### ISSUE THREAD

**Issue by ValeryDubrava** [paritytech/parity#6334]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Linux (Debian 8)
> - **And installed**: binaries 

**actual**

**web3.eth.getBlock** method returns null for block 924645. But previous block (924644) exists! Even more, the latest and the earliest blocks are existing.

**expected behavior**
Method should return information about block (you can found it on https://etherscan.io/block/924645).
 
**steps to reproduce**

Parity run with script:
`$ parity daemon ./parity.pid --db-compaction ssd --cache-size 1024 --identity someproject `
Chain Synchronized - yes.

**Comment by 5chdn** [comment]
How are you calling getblock? Can not reproduce via JavaScript console.

    > eth.getBlock("0x6d9d3292485e2e43991e9ef245867ee08086290dafb689b8e32f6e4fe1acb707")
    {
      author: "0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da",
      difficulty: 10825574453474,
      extraData: "0xd783010400844765746887676f312e352e31856c696e7578",
      gasLimit: 3141592,
      gasUsed: 102947,
      hash: "0x6d9d3292485e2e43991e9ef245867ee08086290dafb689b8e32f6e4fe1acb707",
      logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000400000000040000000000000000000002000000000000000000000000000000000000000000000000800000000000000000000100000100000000000000400000020000000000000000000a02000000000000000000000000000000000000000000000000500004000000000000000000000000000000000000000000000000000000000400000000000000000000000000000408000800000000010000000000000000000000000000000000080000000000000000000000000020000000000000100000000000080000000000000000000000004000000000000000",
      miner: "0x68795c4aa09d6f4ed3e5deddf8c2ad3049a601da",
      mixHash: "0x578e0bc46ff3ae7af6d318792b4d742a4760fb9e6384c1d67588a94d09bebea7",
      nonce: "0x459baaf3da146e1d",
      number: 924645,
      parentHash: "0x15de41b7ebb263241af00947e33e8e50a5514a45ce41a42632e1cd306032522b",
      receiptsRoot: "0x34617af6e41667939d414e8b3cbd3a09aed39f604f74186840714f45860e50d4",
      sealFields: ["0xa0578e0bc46ff3ae7af6d318792b4d742a4760fb9e6384c1d67588a94d09bebea7", "0x88459baaf3da146e1d"],
      sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      size: 1232,
      stateRoot: "0x247e102a8be460590fe542fd0cc48738aed982b47a48cc2b2c42f68460924816",
      timestamp: 1454110278,
      totalDifficulty: 6289880805748609541,
      transactions: ["0x42ef16655befbce749124c76d96ca08da588d983516c2707798215356fd3ec12", "0x24505ed1d11758f4ecb8ac7c84d9943bd6732a48de353d374aa8211ddcd4f81a", "0xd29320aa59fa3155dec05763c15142e181440338e3bbb650ef9868842d056745"],
      transactionsRoot: "0xaa59682583b9774f297e97991e12eab19986c3e48567939eae46827371544483",
      uncles: []
    }
    > eth.getBlock("0x15de41b7ebb263241af00947e33e8e50a5514a45ce41a42632e1cd306032522b")
    {
      author: "0x580992b51e3925e23280efb93d3047c82f17e038",
      difficulty: 10830862960651,
      extraData: "0xd783010400844765746887676f312e352e31856c696e7578",
      gasLimit: 3141592,
      gasUsed: 193894,
      hash: "0x15de41b7ebb263241af00947e33e8e50a5514a45ce41a42632e1cd306032522b",
      logsBloom: "0x00000000000000000000000000000000000000000000002000000000000000000000000000000000040000000000000000040002000000000000000000000000000000000000000000000000000000000000000000000100000100000000000000400000020000000000000000000a02000000000000000000000000000000000000000000000000500006000000000000000000000000000000000000010000000000000000000400000000000000000000000000000408000800000000010000000000000000100000000000000000080000000000000000000000000020000000000000100000400000080000000000000000000000000000000000000000",
      miner: "0x580992b51e3925e23280efb93d3047c82f17e038",
      mixHash: "0x57c28f49153e322141e82100ba7ed3149aee2d1ae1926540ab75981de66fbfa0",
      nonce: "0x89576b1b728577c3",
      number: 924644,
      parentHash: "0x2b39b77e348350974df82639960f37e7add53cd658b524a225adb244011792e0",
      receiptsRoot: "0x1ae93c0788d28a212a261539bbe701a8a9247fe8421dcff110883b767cd83f8a",
      sealFields: ["0xa057c28f49153e322141e82100ba7ed3149aee2d1ae1926540ab75981de66fbfa0", "0x8889576b1b728577c3"],
      sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      size: 1698,
      stateRoot: "0xd6cccdfadb61da840c83f2ef7e65a14240847bdc7d249bdf78468c5629c155f5",
      timestamp: 1454110244,
      totalDifficulty: 6289869980174156067,
      transactions: ["0x95365b5fa740f4b8ebb3dc76ea72ba7f0a99b8e50654fead2d98a220997d7200", "0xdbe3ecf6ff02534b79237bec952ce1c9330e59ed578dc3a7bc49fa374352f458", "0xede63e5d8d47090c19db9cedcfb8829418581121a29b37b164ed6512db32a5d5", "0xa93d61a071ae36c0344d2e19beb97591fdf214a52a8046491d7de7857035d01f"],
      transactionsRoot: "0xa907d702636ae5e278f379164de31e1bba5a6913a1fe419e2be92b9722f3de27",
      uncles: []
    }

**Comment by 5chdn** [comment]
Your client is probably still fetching ancient blocks.

**Comment by GeeeCoin** [comment]
@5chdn this still occurs when I query for "latest" block about 10-15% of the time.
