### ISSUE TITLE
My transaction was not cancelled.

### ISSUE THREAD

**Issue by UNST4BL3** [paritytech/parity#6335]
> - **Parity version**: Parity//v1.6.8-beta-c396229-20170608/x86_64-windows-msvc/rustc1.17.0
> - **Operating system**: Windows 10
> - **And installed**: Installer

A transaction from my address to another was sent.
While this transaction was still being confirmed, I clicked the "cancel transaction" button.
The transaction was not cancelled and the ether arrived at the destination.

**Comment by 5chdn** [comment]
Once broadcasted, a transaction can not be cancelled anymore. 

Was your client still synchronizing the chain while this happened?

**Comment by rphmeier** [comment]
Right, only scheduled transactions can be reliably canceled (and only then when they haven't reached the scheduled point). Parity will _try_ to replace a broadcasted transaction with another that miners will be more likely to accept, but the miners may still choose to include the previously broadcasted one.
