### ISSUE TITLE
Changing password results in multiple passwords existing??

### ISSUE THREAD

**Issue by patrick99e99** [paritytech/parity#6336]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: MacOS
> - **And installed**: initially via homebrew, but had problems so uninstalled and then installed via installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

1. When I initially created my account and was asked for a password.

2. I performed and signed various transactions successfully.

3. Much time went by without using parity, and the next time I needed to make a transaction, I used the password that I thought I had chosen and it was incorrect.  Confused... I tried many times, finally realizing that I had a made a mistake when initially entered my password...  The password had a letter that I had intended to be a number...  So I entered my password again, replacing the number with the letter and the transaction went through successfully.

4.  I then decided I was going to be annoyed by this, so I changed my password so that it contained the number instead.

5.  I sent various other transactions with the password including the number and they worked fine...

6.  Much time passed by and I did not use parity...  Eventually I needed to make a transaction, so I launched it, and put in my password the number and it was once again incorrect...  I then tried the version with the letter and it was... once again correct....  ????  Frustrated by this, I decided to  just stick with that password...

7.  Again, many uses of parity over the weeks, transactions sending all the time, using the original password with the letter instead of the number..  All is well..

8.  No use of parity for 2-3 weeks, and today I launch it and put in my password with the letter instead of the number, it tells me my password is incorrect!!  I try the version with the number instead of the letter-- and it works.

It's almost like my system has two different parity instances, and each has a different password.. and every time I launch the parity server, sometimes I get the one with the numbered password version, and sometimes I get the letter password version.........  Super weird.  I don't quite get it, but this always gives me a bit of a heart attack because I am afraid one day neither password will work and I will never be able to access my crypto-assets!!

**Comment by 5chdn** [comment]
This is interesting. Could you please check manually your key files? It's possible that Parity created a new key file without removing the old one.

Your keys are in `~/Library/Application\ Support/io.parity.ethereum/keys`. You will see the public address by checking the JSON field `address`? Could you check if there are multiple files containing this address?

**Comment by patrick99e99** [comment]
Ah.. There are two files starting with a utc timestamp, and both of them have identical address and name fields..  Yet only one has my password hint under meta, but both have the exact same timestamp under meta...  What do you advise?  I should delete one of these files?

**Comment by 5chdn** [comment]
Well, deleting is nothing I could recommend when it comes to handling key files :)

What you can do now, is _move_ on of the files out of that directory (i.e., to your Desktop), and see if the password is the one you desire. If it's not, move the file back and move the other out, test again. :-)

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
