### ISSUE TITLE
District0x Token has wrong TLA in the Token Registry

### ISSUE THREAD

**Issue by cstegmann** [paritytech/parity#6340]
Current TLA: D0X
Correct TLA: DNT

Token Contract Address: 0x0AbdAce70D3790235af448C88547603b945604ea
Token Contract Creator: 0x395ABb8B97268480229e6c3784a545dAEe325A83

I'm running:

Parity version: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
Operating system: Windows
And installed: via installer

**Comment by 5chdn** [comment]
DNT on the Parity Token Registry is DENT, and District0x is D0X.

I can fix both entries, but the communities should decide first which token gets which TLA. Maybe DENT is fine with DEN?
