### ISSUE TITLE
ERC20 deposit do not fire Deposit on Multisig

### ISSUE THREAD

**Issue by reiven** [paritytech/parity#6348]
Hi, looks like the Deposit event do not track ERC20 token deposits because normally token transfers have 0 ether value

I'm using parity 1.7.0 on linux, and Wallet contract link is https://github.com/paritytech/parity/blob/6b0e4f9098be6b841353e7c4f116aa86b7c2e3d6/js/src/contracts/snippets/enhanced-wallet.sol

**Comment by 5chdn** [comment]
![screenshot at 2017-08-22 10-25-25](https://user-images.githubusercontent.com/15729797/29555895-5892d35c-8724-11e7-8277-99bc0cc76069.png)

Wallets fully support ERC20 tokens. What kind of event are you talking about? Notifications?

**Comment by reiven** [comment]
Thats for mainnet only, correct?
I've deployed a ERC20 compatible wallet in Ropsten and the wallet didnt see the transaction, just ETH transactions. Also, the token was deployed using parity

![image](https://user-images.githubusercontent.com/362717/29563679-0c8fa5fc-8715-11e7-942f-e52b4c0700d1.png)

**Comment by 5chdn** [comment]
That screenshot was taken on Kovan. After deploying your token, you need to register it with the Token Registry Dapp. https://github.com/paritytech/parity/wiki/Token-Registry
