### ISSUE TITLE
Byzantine nodes stress Aura - Finality

### ISSUE THREAD

**Issue by deanstef** [paritytech/parity#6357]
Hello,
I'm running:
Parity version: 1.7.0
Operating system: Linux
And installed: from source

I'm trying to stress Parity Aura engine with some byzantine behaviours of custom malicious nodes. 
Actually i'm thinking to implement a byzantine authority who sends, at it's turn, different blocks. For example if i've three nodes A,B C; the byzantine primary sends one block to A, B and a similar block, but with different transactions, to C. 

Is finality resilient to this situation?

**Comment by keorn** [comment]
Yes, should work fine. With [Validator Set contract](https://github.com/paritytech/parity/wiki/Validator-Set#contracts) the malicious authority should also get kicked out.

**Comment by deanstef** [comment]
Thank you. But how the network reacts to this? Nodes A,B will have a different block from C, they simply rejects the block from the malicious node?

**Comment by keorn** [comment]
A,B can not know its malicious before they receive another block from the same authority through the node C.

**Comment by deanstef** [comment]
Thank you.
