### ISSUE TITLE
token shows wrong balance by decimals

### ISSUE THREAD

**Issue by Fredouh** [paritytech/parity#6358]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7
> - **Operating system**:  / MacOS /
> - **And installed**: installer /

token (contract adress: 0xb110ec7b1dcb8fab8dedbf28f53bc63ea5bedd84) shows wrong balance by decimals (1.23456 instead of 1,234.56).
balance appears right on etherscan. fully synced. parity doesnt let me transfer the token saying
"the transaction total is higher than the available balance". seems to be an issue with token registry where 12 decimals appear, while on etherscan 8. balance is wrong by 4 decimals. is it to be fixed by parity devs or the project devs?

---

**Comment by 5chdn** [comment]
Which token is that? Can you confirm it's 8 decimals not 9?

**Comment by Fredouh** [comment]
0xb110ec7b1dcb8fab8dedbf28f53bc63ea5bedd84 SphreAir-token. Yes its 8 decimals. @5chdn

**Comment by 5chdn** [comment]
Removed the entry, you can go ahead and register it with 8 decimals.
