### ISSUE TITLE
Is this release for real?

### ISSUE THREAD

**Issue by chpio** [paritytech/parity#6361]
Is the v1.7.1 release for real or are you going to silently swap some commits like it happened for 1.7.0 and 1.6.10?

**Comment by arkpar** [comment]
Releases are "for real" when they are published on the releases page. Before that tag might be pulled if it fails internal testing

**Comment by chpio** [comment]
ok, thank you.

**Comment by 5chdn** [comment]
Now it's real. https://github.com/paritytech/parity/releases/tag/v1.7.1

**Comment by chpio** [comment]
but now it's just the 1.7.0 version showing up in the release page, 1.7.1 & 1.7.2 isn't. so i assume they are broken and the latest stable version is 1.7.0?

**Comment by 5chdn** [comment]
Yes, we pulled 1.7.1 due to a bug in the interface. 1.7.2 will be next but needs further testing.

Latest stable is 1.6.10 by the way. Latest beta is 1.7.0.
