### ISSUE TITLE
Allow skipping Parity UI account creation.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6367]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Windows
> - **And installed**: via installer

---

When installing Parity on a new machine, upon launch of the UI you are prompted to create an account.  There does not appear to be a way to skip account creation, even if you only plan on using Parity for monitoring on-chain contracts, or you plan on importing keys via import, or if you plan on using a hardware signing device.

While I recognize that I can just create a dummy account and then immediately delete it, it would be nice if there were a skip option for this step, even if it was in very small letters at the bottom of the screen and strongly discouraged.

**Comment by 5chdn** [comment]
The Parity wallet is not intended to work without accounts and might fail at certain points if there was no account. But I agree, instead of an account creation, there should be an import option.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.

**Comment by hopkinskong** [comment]
Is the new user interface out now? When I am using https://wallet.parity.io/ it seems that I still need to create a new account instead of importing exists accounts.

**Comment by 5chdn** [comment]
Not yet.
