### ISSUE TITLE
Creating account - password problem 

### ISSUE THREAD

**Issue by sbuljac** [paritytech/parity#6375]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: MacOS
> - **And installed**: homebrew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

When I try to create a new account and as password paste randomly generated 32 ch long password with upper letters, lower letters, numbers, and special characters the Parity UI block/stucks and I need to refresh the page.  I am unable to create the new account with this type of password.

**Comment by 5chdn** [comment]
> I am unable to create the new account with this type of password.

Please specify what exactly is happening. Please also share logs or screenshots.

**Comment by 5chdn** [comment]
Had a similar experience with changing password today. Probably #6387
