### ISSUE TITLE
我看有中文语言文件呢，为什么浏览器里还是显示的英文呢。。。

### ISSUE THREAD

**Issue by hankuksui** [paritytech/parity#6378]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - version Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
> - **Operating system**: Linux
> - **And installed**: from source

浏览器
navigator.language："zh-CN"
navigator.languages：["zh-CN", "zh", "zh-TW", "en", "en-US"]

---
怎么让它显示中文呢？

**Comment by keorn** [comment]
Question about how to enable Mandarin in the UI.

**Comment by CraigglesO** [comment]
I was going to take pictures to answer this with steps. But I don't see language setting in the UI anymore.

**Comment by hankuksui** [comment]
@CraigglesO 非常感谢！是的，现在是看不到修改语言的功能，我是在代码里看到的。
实在不好意思，我的英文不太好，还在努力学习，给你们添麻烦了。

**Comment by 5chdn** [comment]
The language selector is not yet released. Stay tuned.
