### ISSUE TITLE
application crash when changging syncing ropsten blocks in setting tabs on windows

### ISSUE THREAD

**Issue by ixiangjin** [paritytech/parity#6379]
> I'm running:
>
> - **Parity version**: 0.1.7
> - **Operating system**: Windows 
> - **And installed**: via installer

_ anyone has that problem？  when i choose to sync ropsten test network， the brower stop and no repondding

- some place said could use ropsten.json to start. but not found any ropsten.json file
---

**Comment by 5chdn** [comment]
Can you try to run parity from a command prompt?

```bash
cd "C:\Program Files\Ethcore\Parity\
parity.exe --chain ropsten
```

And see if this produces any useful error messages?
