### ISSUE TITLE
help for "double vote"

### ISSUE THREAD

**Issue by ethshan** [paritytech/parity#6380]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.6.10
> - **Operating system**: Linux
> - **And installed**: binaries

the console show me error info "double vote" when i run pairity with private chain(POA) ,two nodes.
I have migrate some smart contract on my chain,and send transaction to the contracts.The error info will come when hundreds of block mining.

my config like this
contract-product-spec.json:
{
    "name": "ProductPoA",
    "engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "2",
                "validators" : {
                        "contract": "0x0000000000000000000000000000000000000005"
                }
            }
        }
    },
    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x2323"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x10000",
        "gasLimit": "0x12a05f200"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x0000000000000000000000000000000000000005": { "balance": "1", "constructor" : "0x6060604052604080519081016040528073d8df4fe78eb40b6d9903fc958316f3bb6509df8473ffffffffffffffffffffffffffffffffffffffff1681526020017318a9763da59e3194fd496f91f02f79a0877a55e473ffffffffffffffffffffffffffffffffffffffff16815250600090600261007d929190610130565b50341561008957600080fd5b5b60008090505b60008054905081101561012957806001600080848154811015156100b057fe5b906000526020600020900160005b9054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055505b8080600101915050610090565b5b506101fd565b8280548282559060005260206000209081019282156101a9579160200282015b828111156101a85782518260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555091602001919060010190610150565b5b5090506101b691906101ba565b5090565b6101fa91905b808211156101f657600081816101000a81549073ffffffffffffffffffffffffffffffffffffffff0219169055506001016101c0565b5090565b90565b6106c18061020c6000396000f30060606040523615610081576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806335aa2e441461008657806340a141ff146100e95780634d238c8e14610122578063b7ab4db51461015b578063bfc708a0146101c6578063d8f2e0bf146101ff578063fd6e1b5014610254575b600080fd5b341561009157600080fd5b6100a7600480803590602001909190505061028d565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34156100f457600080fd5b610120600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506102cd565b005b341561012d57600080fd5b610159600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190505061044c565b005b341561016657600080fd5b61016e610500565b6040518080602001828103825283818151815260200191508051906020019060200280838360005b838110156101b25780820151818401525b602081019050610196565b505050509050019250505060405180910390f35b34156101d157600080fd5b6101fd600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610595565b005b341561020a57600080fd5b610212610599565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b341561025f57600080fd5b61028b600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506105bf565b005b60008181548110151561029c57fe5b906000526020600020900160005b915054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006001600080549050038154811015156102e457fe5b906000526020600020900160005b9054906101000a900473ffffffffffffffffffffffffffffffffffffffff166000600160008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000205481548110151561035f57fe5b906000526020600020900160005b6101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550600160008273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009055600060016000805490500381548110151561040357fe5b906000526020600020900160005b6101000a81549073ffffffffffffffffffffffffffffffffffffffff021916905560008054809190600190036104479190610604565b505b50565b600080548060010182816104609190610630565b916000526020600020900160005b83909190916101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050600160008054905003600160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020819055505b50565b61050861065c565b600080548060200260200160405190810160405280929190818152602001828054801561058a57602002820191906000526020600020905b8160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019060010190808311610540575b505050505090505b90565b5b50565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b80600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505b50565b81548183558181151161062b5781836000526020600020918201910161062a9190610670565b5b505050565b815481835581811511610657578183600052602060002091820191016106569190610670565b5b505050565b602060405190810160405280600081525090565b61069291905b8082111561068e576000816000905550600101610676565b5090565b905600a165627a7a7230582072b54c4ae32d2bfdda3439b8ce864881c6a281f7c3643d9b1f7e98e69853ba040029" },
        "0x18a9763da59e3194fd496f91f02f79a0877a55e4": { "balance": "10000000000000000000000" }
    
    }
}

node1.toml:
[parity]
chain = "contract-product-spec.json"
base_path = "./chainData/networks/parity0"
[network]
reserved_peers = "reservedPeers.enode"
reserved_only = true
port = 30313
[rpc]
interface ="192.168.1.119"
port = 8553
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
interface ="192.168.1.119"
port = 8193
[account]
unlock = ["0x18a9763da59e3194fd496f91f02f79a0877a55e4"]
password = ["node.pwds"]
[mining]
#author = "0x18a9763da59e3194fd496f91f02f79a0877a55e4"
engine_signer = "0x18a9763da59e3194fd496f91f02f79a0877a55e4"
reseal_on_txs = "none"
reseal_min_period = 1000
usd_per_tx = "0"
gas_floor_target = "20000000"
# Gas limit will be raised at most by 62831840000 gas.
#gas_cap = "9000000"
# Parity will reject transactions above 30000000 gas.
#tx_gas_limit = "30000000"

help!
---
OGM， This problem again，I just set 4 noods  and send transaction to my contracts without validator contract.
my parity version is 1.6.10

3 nodes's console log like this:

2017-09-01 10:58:48  Imported #1013 271c…17dd (3 txs, 11.36 Mgas, 12.35 ms, 2.10 KiB)
2017-09-01 10:59:00  Imported #1014 1fe8…9b81 (2 txs, 0.11 Mgas, 0.80 ms, 0.89 KiB)
2017-09-01 10:59:00  Stage 3 block verification failed for #1015 (b26e…05e9)
Error: Engine(DoubleVote(deccdcf58c71d0ca3b8f01298c5257e8b961d8b7))
2017-09-01 10:59:04     1/25 peers    20 MiB db    2 MiB chain  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-01 10:59:07  Imported #1015 5edc…0ef8 (5 txs, 0.28 Mgas, 0.58 ms, 1.38 KiB)
2017-09-01 10:59:17  Imported #1017 2230…e74a (2 txs, 0.26 Mgas, 1.02 ms, 1.14 KiB)
2017-09-01 10:59:34     2/25 peers    20 MiB db    2 MiB chain  0 bytes queue   11 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-01 10:59:36  Reorg to #1018 9dfc…4b7e (2230…e74a a164…452d 5edc…0ef8 #1014 1fe8…9b81 e904…c636 79e4…e9bb ce66…1d46)
2017-09-01 10:59:36  Imported #1018 9dfc…4b7e (8 txs, 1.40 Mgas, 2.94 ms, 2.32 KiB) + another 1 block(s) containing 2 tx(s)
2017-09-01 10:59:48  Imported #1019 ec37…541d (2 txs, 0.26 Mgas, 0.49 ms, 1.69 KiB)
2017-09-01 10:59:48  Stage 3 block verification failed for #1020 (628a…16e6)
Error: Engine(DoubleVote(deccdcf58c71d0ca3b8f01298c5257e8b961d8b7))
2017-09-01 11:00:04     1/25 peers    20 MiB db    2 MiB chain  0 bytes queue   19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-01 11:00:12  Imported #1020 9abf…5aeb (1 txs, 0.20 Mgas, 0.40 ms, 0.78 KiB)
2017-09-01 11:00:20  Imported #1021 7b62…7e72 (3 txs, 0.58 Mgas, 0.37 ms, 1.24 KiB)
2017-09-01 11:00:34     1/25 peers    20 MiB db    2 MiB chain  0 bytes queue   19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-01 11:00:56  Reorg to #1022 59eb…f57a (7b62…7e72 9abf…5aeb ec37…541d #1018 9dfc…4b7e c8ea…96a3 60c7…5a57 b4cc…cb63)
2017-09-01 11:00:56  Imported #1022 59eb…f57a (14 txs, 2.19 Mgas, 6.05 ms, 4.91 KiB)

**Comment by 5chdn** [comment]
Please share your complete logs here, including the full error message.

**Comment by ethshan** [comment]
@5chdn  
the console log like this:
Reported malicious calidator 590c....710e
stage 3 block verification failed for #44(2a07....c8c6)
Error:Engine(Douvlevote(590c1d7b99aa4134ca0d17793b3750c9c2d2710e))

and the current block's "step" less than the parent's block's "step"

**Comment by keorn** [comment]
Are you running both nodes with node1.toml or configs that have the same `engine_signer`? This is not something that you should do (see [docs](https://github.com/paritytech/parity/wiki/Proof-of-Authority-Chains#running-the-authority-nodes)), since it can lead to consensus failure. You need to run the second node with a different or no `engine_signer`.

**Comment by ethshan** [comment]
@keorn yeah,I have run it with two computers and the different engine_signer.

**Comment by keorn** [comment]
Can you try with 1.7, contract validator set has been changed there?

**Comment by ethshan** [comment]
@keorn I haven't found the 1.7's contract.Could you show me? thanks.

**Comment by keorn** [comment]
See the docs: https://github.com/paritytech/parity/wiki/Validator-Set#contracts
