### ISSUE TITLE
QR Scanner fails to launch computer camera on Safari

### ISSUE THREAD

**Issue by gegereno** [paritytech/parity#6382]
> I'm running:
>
> - **Parity version**: v1.7.0-beta
> - **Operating system**: MacOS
> - **And installed**: via installer

--
**Actual Behaviour**

![screen shot 2017-08-25 at 4 56 08 pm](https://user-images.githubusercontent.com/7646945/29720901-97f91e2c-89bb-11e7-9ac0-245b03710562.png)

**Expected Behaviour**

Inside the box to show a live camera view in order to scan QR Code (as it does on Chrome)

**Steps to Reproduce**
1. Launch Parity using Safari Version 10.1.2 (12603.3.8)
2. Try to scan QR code from Signer App
3. See camera fail to launch

---

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
