### ISSUE TITLE
TraceDB resync required

### ISSUE THREAD

**Issue by mi2zha** [paritytech/parity#6386]
_Before filing a new issue, please **provide the following information**._

> I'm running:
parity db kill
parity --pruning archive --base-path /Volumes/mnt/parity --port 3304 --rpcport 8550
parity --tracing on

TraceDB resync required

curl --data '{"method":"trace_transaction","params":["0xc7213d1f6a356ceb889eb138865ee104133c3cda2760ae0beb23a4a1d843d5cc"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8550
{"jsonrpc":"2.0","result":null,"id":1}

> Parity version: version Parity/v1.8.0-unstable-4bda7bf17-20170822/x86_64-macos/rustc1.19.0
> Operating system:  MacOS 
> And installed:  from source

**Comment by 5chdn** [comment]
You need to enable tracing on first run

    parity --tracing on --pruning archive --base-path /Volumes/mnt/parity --port 3304 --rpcport 8550

You can also use a config file: https://github.com/paritytech/parity/wiki/Configuring-Parity#config-file

**Comment by ajit-soman** [comment]
Tried to run tacing as first option but not working. 
I am already running a private blockchain .
parity version: Parity-Ethereum/v2.3.7-stable-7d1415a-20190320/x86_64-linux-gnu/rustc1.33.0
```
parity  --tracing on --pruning archive --base-path /home/ubuntu/.local/share/io.parity.ethereum --config parity-node.toml
Loading config file from parity-node.toml
TraceDB resync required
```
