### ISSUE TITLE
Token Registry lookups cause 1000's of eth_calls if you have multiple accounts

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#6387]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Linux
> - **And installed**: binaries

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Token Registry lookups cause 1000's of eth_calls if you have multiple accounts. Token registry currently has more than 300 entries. They are queried for each account you have and cause the RPC to not being able to catch up. The UI becomes very slow.

**Comment by debris** [comment]
So the problem is caused by each call creating a new state copy. afaik @tomusdrw recently addressed this issue by added `parity_call` rpc method which reuses a single state copy for multiple calls. Our ui should use this method and check all balances together

**Comment by 5chdn** [comment]
Just looking at the logs: it's currently around 100-thousand RPC requests per minute.

**Comment by 5chdn** [comment]
#6471 closes this, does it?

**Comment by tomusdrw** [comment]
Indeed.

**Comment by 5chdn** [comment]
:tada:
