### ISSUE TITLE
Parity web interface nags about chrome extension even though it's already installed

### ISSUE THREAD

**Issue by Grix** [paritytech/parity#6388]
I'm running:
- **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
- **Operating system**: Windows 10
- **installed**: Via installer
- **Chrome version**: 60.0.3112.113 (Official Build) (64-bit)
- **Parity extension version**: 2.7.2

Sometimes the parity web interface will display the chrome extension message even though it's already installed and connected: http://i.imgur.com/BsDCISd.png

**Comment by 5chdn** [comment]
Yeah, we are aware of and a fix is already available. Will be probably included in the next version of the extension.

**Comment by 5chdn** [comment]
@tomusdrw could you comment on this if you have time, you mentioned somewhere this is fixed. can we close this issue?

**Comment by tomusdrw** [comment]
So it seems it's a bug in both extension and Parity detection code. Working on the fix now.
