### ISSUE TITLE
Issue accessing funds in parity wallet

### ISSUE THREAD

**Issue by kkrasick** [paritytech/parity#6396]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows / MacOS / Linux
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
Hello,

I am a Parity user on Windows - installed through the installer application and I am having trouble as some coins I recently purchased have confirmed the transaction was complete through etherscan, however when I view my wallet in parity I see a question mark next to the coin rather than it's correct logo.

Can you please assist me in confirming my transaction and accessing my coins in parity?

**Comment by 5chdn** [comment]
The question mark just means that nobody has registered an icon in the token registry for your tokens. That's no issue. You can go to applications > token registry and query the registry by TLA or Address to confirm the correct token is registered. If not, get back to me.
