### ISSUE TITLE
Parity Wallet Not Opening 

### ISSUE THREAD

**Issue by Basguy** [paritytech/parity#6401]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
(most recent 1.7.0 I think?)
> - **Operating system**: Windows / MacOS / Linux
Windows
> - **And installed**: via installer / homebrew / binaries / from source
Installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Expected: Click on parity app icon which normally opens a browser tab connecting my Parity wallet

Actual: Click on parity causing it to show up momentarily in the task bar before disappearing. Nothing further happens. I suspect from reading other issues that the blockchain was corrupt so I have attempted to clear the db by using the function "parity db kill" in the command line which returns the error "access denied" due to "This app can not run on your pc, to find a version that works with your pc check with publisher" I have searched far and wide trying to find a way to avoid this error only to realize that in windows 10 home I cannot change the setting usually affecting this.

Is there any way to go around this problem and clear the database? or does anyone have any other suggestions? would be most appreciated.

Cheers!
---

**Comment by 5chdn** [comment]
Please see if you can open a command prompt, and change the directory to your installation:

```bash
cd "C:\Program Files\Ethcore\Parity\"
```

and execute Parity:

```bash
parity.exe
```

And share the logs here if there is any issue.

**Comment by Basguy** [comment]
I am currently at work, but I will do this as soon as I get home (4 ish hours) 
I appreciate the speedy reply, sorry I cannot hold up my end right about now

**Comment by Basguy** [comment]
I attempted to change the directory but was given this message (possible I deleted ethcore while trying to delete and reinstall from scratch)

<img width="960" alt="2017-08-28" src="https://user-images.githubusercontent.com/20199669/29796319-af959cbe-8c0d-11e7-8586-858c49d8c208.png">

**Comment by 5chdn** [comment]
Can you manually check where your Parity installation is?

**Comment by Basguy** [comment]
Absolutely

<img width="960" alt="2017-08-29" src="https://user-images.githubusercontent.com/20199669/29822733-beedb9fe-8c89-11e7-9249-549fdad19812.png">

**Comment by 5chdn** [comment]
All right, could you open the properties of that shortcut and figure out the full path of the link?

**Comment by Basguy** [comment]
whoops sorry, is this what you were looking for?
<img width="960" alt="2017-08-29 1" src="https://user-images.githubusercontent.com/20199669/29823183-22c6124a-8c8b-11e7-9e2e-fef5b2814bf7.png">

**Comment by 5chdn** [comment]
Yes, thank you, now let's start over again.

Please, see if you can open a command prompt, and change the directory to your installation:

```bash
cd "C:\Program Files\Parity\Parity\"
```

and execute Parity:

```bash
parity.exe
```

And share the logs here if there is any issue.

**Comment by Basguy** [comment]
no on no, thank you! And here you are, 

<img width="960" alt="2017-08-29 2" src="https://user-images.githubusercontent.com/20199669/29834510-462b130e-8cac-11e7-90a3-b0a8c9321786.png">

**Comment by 5chdn** [comment]
Ah yes, that happens sometimes. Your database is corrupted. If you have the prompt still open:

    parity.exe db kill

And after that you can run Parity from your start menu entry again.

**Comment by Basguy** [comment]
much appreciation!
