### ISSUE TITLE
Make the transaction hash in the new transaction popup clickable

### ISSUE THREAD

**Issue by yudilevi** [paritytech/parity#6407]
Hi,

In the new version (1.7.0 / Windows), once you execute a transaction, instead of the old huge popup, there's a smaller popup on the bottom right of the screen.
This is actually a great change, but one of the features that was really useful in the previous version was the ability to click the transaction hash which opened the transaction on etherscan.
Would be great to have that feature added to the new smaller popup as well.

Thanks!

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
