### ISSUE TITLE
Where are keys ?

### ISSUE THREAD

**Issue by BatLesStakes** [paritytech/parity#6409]
Hello, 

I'm searching my ETH keys but as long as I searched I didn't have found them yet.
Can anyone help me about it ? This is for a ETH pool and people are waiting.

Thanks

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity/wiki/FAQ%3A-Backup%2C-Restore%2C-and-Files#where-can-i-find-paritys-local-files

https://github.com/paritytech/parity/wiki/Backing-up-%26-Restoring

If you tell me your OS and Parity version, I tell you where your keys are.

**Comment by BatLesStakes** [comment]
Last Parity version, Ubuntu 16.04

**Comment by 5chdn** [comment]
```bash
~/.local/share/io.parity.ethereum/keys/
```

**Comment by BatLesStakes** [comment]
On io.parity.ethereum I have the folder "keys". Inside there is a file named "ethereum" and inside there's nothing

**Comment by BatLesStakes** [comment]
On a root account I have "address_book.json" and there's only "{}" on it

**Comment by BatLesStakes** [comment]
When I type curl --data method: parity_expôrtaccount I have this : 
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}

**Comment by 5chdn** [comment]
How did you create the accounts?

Which Parity version are you running? ('Last' is no version.)

Which chain are you using? Could you share your configuration?

**Comment by BatLesStakes** [comment]
I created account by "parity account new" and I'm using the v1.8.0 unstable.
To sync, I ran "parity" simply.

**Comment by 5chdn** [comment]
What's the output of `parity account list` ?

**Comment by BatLesStakes** [comment]
Two addresses

**Comment by BatLesStakes** [comment]
That I have created
And one has some money inside

**Comment by 5chdn** [comment]
What's the output of 

    find ~/.local/share/io.parity.ethereum/ | grep -i utc\-\-

**Comment by BatLesStakes** [comment]
/root/.local/share/io.parity.ethereum/keys/ethereum/UTC--2017-08-05T19-16-24Z--eaed8862-365c-1e16-b01d-531382f82ec9
/root/.local/share/io.parity.ethereum/keys/ethereum/UTC--2017-08-05T19-16-36Z--72b8166f-342a-095f-6788-39fe5eb1535f

**Comment by 5chdn** [comment]
Congratulations, that's your two keys :)

**Comment by BatLesStakes** [comment]
Oh ayy nice thanks haha

**Comment by BatLesStakes** [comment]
How can I add it to my Windows wallet now that I have the key and the address ?

**Comment by 5chdn** [comment]
Copy it to `C:\Users\<You>\AppData\Roaming\Parity\Ethereum\keys\ethereum`
