### ISSUE TITLE
Using of the methods personal_unlockAccount or parity_unlockAccount

### ISSUE THREAD

**Issue by nodermann** [paritytech/parity#6412]
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
> - **Operating system**: Linux ubuntu 16.04
> - **And installed**: bash <(curl https://get.parity.io -kL)
---

## Long story short
I need unlock my account in the kovan testnet using **personal_unlockAccount** or **parity_unlockAccount**
I don't want to use a geth but I have no choice. Please enable it as before.

## Actual behaviour
**personal_unlockAccount**
curl --data '{"method":"personal_unlockAccount","params":>
["0x...","password",null],"id":1,"jsonrpc":"2.0"}' -H > "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","error":{"code":-32601,"message":"**Method not found**"},"id":1}
**parity_unlockAccount**
curl --data '{"method":"parity_unlockAccount","params":>
["0x...","password",null],"id":1,"jsonrpc":"2.0"}' -H > "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","error":{"code":-32601,"message":"**Method not found**"},"id":1}

## About
I found a [261250311](https://github.com/paritytech/parity/issues/3485#issuecomment-261250311) that you believe the use of these methods not secure, but the solution with the launch of the looks as a crutch, I mean something like:

_parity --testnet --unlock 0x... --password passwords.txt_

Is not a solution, because it is very inconvenient to use, also, I can't access the web interface when I point the path to the password, it starts the console, but does not start the web server.

I am a skilled developer, but I can't find a solution without direct code changes.

relevant urls:
#3485
https://github.com/paritytech/parity/blob/master/rpc/src/v1/traits/personal.rs#L25
https://github.com/paritytech/parity/blob/master/rpc/src/v1/traits/parity_accounts.rs#L26

---
Besides, you need to change the documentation, because it is not true, if you want to develop the best client, you need to cooperate with the community or there is someone who will do it better than you, I think the idea of parity is very competitive. Thank you!

**Comment by 5chdn** [comment]
What flags are you running Parity with? Do you use any config file?

Did you enable the JSONRPC APIs for `parity_accounts` or `personal`?

> I am a skilled developer, but I can't find a solution without direct code changes.

Feel free to contribute a pull request.

> Besides, you need to change the documentation, because it is not true, if you want to develop the best client, you need to cooperate with the community or there is someone who will do it better than you, I think the idea of parity is very competitive. Thank you!

Feel free to draft updates to the documentation or point me to the docs that failed you and I can look into that.

**Comment by nodermann** [comment]
>What flags are you running Parity with?

$ parity --testnet
>Do you use any config file?

No
>Did you enable the JSONRPC APIs for parity_accounts or personal?

I use parity_accounts, I created the accounts using parity. I didn't enable JSONRPC because it is enabled by default, for example the method **eth_sendTransaction** working fine via jsonrpc.

Thanks!

**Comment by rphmeier** [comment]
Certain groups of RPC APIs are not enabled for HTTP transport by default because they are considered sensitive. You can manually override this by supplying `parity_accounts` to the `--jsonrpc-apis` flag: by default, the list of APIs allowed for http is `web3,eth,pubsub,net,parity,parity_pubsub,traces,rpc,secretstore,shh,shh_pubsub`

**Comment by nodermann** [comment]
BTW If I use
$ parity --testnet --unlock 0x...1 --password passwords.txt

The parity ui http://127.0.0.1:8180/#/accounts doesn't work, however jsonrpc continues to work, I check it with this command:
{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id": 1}

{'jsonrpc': '2.0', 'result': '0x3502af', 'id': 1} // 3474095

**Comment by rphmeier** [comment]
UI is disabled when you use `--unlock`, but you can force it with the `--force-ui` flag.
