### ISSUE TITLE
Unable to do transfers

### ISSUE THREAD

**Issue by micaldas1** [paritytech/parity#6414]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows / MacOS / Linux
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

I'm running Parity 1.7.0 in windows 10, installed via installer.
Since this morning I'm unable to complete any transfers. I'm able to do all the process in Parity, he gives a hash number, but this number never appears in the blockchain. There were transfers I've done at 11h in the morning that still don't appear in the blockchain.
There's no error message, it simply doesn't appear.
Any help would be apreciated.
Thank you

**Comment by 5chdn** [comment]
What's the status of your client? Are you fully synchronized? Are you connected to any peers? Did you check Etherscan if your transactions are visble in the explorer?
