### ISSUE TITLE
Snapshot sync is started from scratch after restart

### ISSUE THREAD

**Issue by kondratovich** [paritytech/parity#6415]
I'm starting new parity node with empty state. Snapshot sync in progress. When I restart node, all synced snapshots are ignored and counter starts from zero.

Does snapshot sync has some disk state?

**Comment by 5chdn** [comment]
Slightly related to #6350.

I'm not entirely sure how the snapshot sync works in this case. Did you restart the node immediately? Or was there some time passing between stopping and starting the node? It's quite possible that the client started fetching a _new_ snapshot and therefore started from scratch.

**Comment by BreezeRo** [comment]
This just occurred to me running 1.7.0 on docker

**Comment by 5chdn** [comment]
@BreezeRo  Did you restart the node immediately? Or was there some time passing between stopping and starting the node?

**Comment by kondratovich** [comment]
@5chdn In my case - few seconds, maybe minute

**Comment by 5chdn** [comment]
Fixed in #8544
