### ISSUE TITLE
add newPendingTransactions to subscriptions

### ISSUE THREAD

**Issue by tzapu** [paritytech/parity#6426]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
> - **Operating system**: Linux

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
**actual**
when trying to subscribe for new pending transactions you get a not implemented message
```
> {"method":"eth_subscribe","params":["newPendingTransactions"],"id":1,"jsonrpc":"2.0"}
< {"jsonrpc":"2.0","error":{"code":-32000,"message":"This request is not implemented yet. Please create an issue on Github repo."},"id":1}
>
```

**expected**
to be able to subscribe for new pending transactions

thank you

**Comment by artemii235** [comment]
Hello. Please note that for compatibility with web3.js this subscription should be called just `pendingTransactions`: https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-pendingtransactions. Thanks!

**Comment by tomusdrw** [comment]
Will probably be implemented together with transaction queue refactoring.

**Comment by k06a** [comment]
```
web3.eth.subscribe('pendingTransactions', function(error, result){
    console.log(error);
})
.on("data", function(trxData){
    web3.eth.getTransaction(trxData).then(console.log);
});
```
=>
```
This request is not implemented yet. Please create an issue on Github repo.
```

**Comment by finndev** [comment]
Is there any fork that has this implemented already? @tomusdrw
