### ISSUE TITLE
Some spec params from kovan are not described in docs

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#6429]
Hello,
> I'm running:
>
> - **Parity version**: 1.7.0

There are some parameters in [kovan's chain spec](https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/kovan.json) that are not described neither in [general parity docs](https://github.com/paritytech/parity/wiki/Configuring-Parity) nor in PoA specific docs [[1](https://github.com/paritytech/parity/wiki/Proof-of-Authority-Chains)], [[2](https://github.com/paritytech/parity/wiki/Chain-specification)] and [[3](https://github.com/paritytech/parity/wiki/Pluggable-Consensus)]
Namely,

* validateScoreTransition
* validateStepTransition
* validateReceiptsTransition
* eip155Transition

if they are described some place else, please provide a link, if not it'd be good to have description for them too.

**Comment by rstormsf** [comment]
👍

**Comment by 5chdn** [comment]
What do you need it for? It's basically small bug fixes or improvements to the kovan network. Just looked through the change-logs:

> `eip155Transition`

This is an Ethash parameter for EIP 155 (replay protection), but also available for PoA.

- EIP: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md
- Docs: https://paritytech.github.io/parity/ethcore/ethereum/ethash/struct.EthashParams.html#structfield.eip155_transition

> `validateReceiptsTransition`

This is a Kovan-specific transition introduced in #4892 to validate block receipts root. I'm not aware, however, if this is used in any other chain configuration yet.

- Src: https://github.com/paritytech/parity/blob/master/ethcore/src/spec/spec.rs#L76

> `validateStepTransition`

The block from which monotonic steps start, via #5587, see #5589 for more details.

- Src: https://github.com/paritytech/parity/blob/master/json/src/spec/authority_round.rs#L39

> `validateScoreTransition`

The block at which score validation should start, via #4988.

- Src: https://github.com/paritytech/parity/blob/master/json/src/spec/authority_round.rs#L36

If you want to run your own PoA network, you can either omit these transitions or set them to 0.

**Comment by phahulin** [comment]
Yes, we want to run our own PoA network. This question is related to the last one (still unanswered) question asked in https://github.com/paritytech/parity/issues/6342
where we are trying to figure out discrepancy between our PoA network and Kovan in relation to out of gas txs.

Since these parameters are not listed in docs, I couldn't know if we need them, thank you for the clarifications.

**Comment by phahulin** [comment]
@5chdn Hello, could you tell me: if these parameters are not included in `chain.json` of a new AuRa network build on parity 1.8, will corresponding bugfixes still apply?
If not then these parameters **must** be included and set to `0` in every new network?
