### ISSUE TITLE
Incorrect behavior when providing a different base path

### ISSUE THREAD

**Issue by marciobuss** [paritytech/parity#6430]
I'm running:
- **Parity version**: v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
- **Operating system**: Linux Ubuntu 16.04.3 LTS
- **And installed**: via "bash <(curl https://get.parity.io -Lk)"

I ran parity with the default options and everything worked (chain = homestead). I also wanted to have a local copy of chain "classic", on another folder, so I did the following:

mkdir \~/Experiments; mkdir \~/Experiments/ethereum-classic
parity --mode active --chain classic --base-path \~/Experiments/ethereum-classic --author 0x<omitted>

Awkwardly Parity is **actually creating** a directory actually called "\~" and another directory called "$BASE", both under \~/:

user@machine:~$ ls -l
total 52
drwxrwxr-x 3 user user 4096 Aug 31 20:36 \~
drwxrwxr-x 3 user user 4096 Aug 31 20:36 $BASE
drwxr-xr-x 2 user user 4096 Aug 30 14:06 Desktop
drwxr-xr-x 2 user user 4096 Aug 30 14:06 Documents
drwxr-xr-x 2 user user 4096 Aug 30 17:06 Downloads
drwxr-xr-x 1 user user 4096 Aug 30 14:06 Experiments
:

It also splits the expected folder structure into these two awkwardly created directories as such (note the double "\~/\~/" on the second line below):

user@machine:~$ cd \\\~
user@machine:\~/\~$ ls -l
total 12
45088793 drwxrwxr-x  3 user user 4096 Aug 31 20:58 Experiments

user@machine:\~/\~$ cd Experiments
user@machine:\~/\~/Experiments$ ls -l
total 28
45088796 drwxrwxr-x 3 user user 4096 Aug 31 20:36 chains
45088809 drwxrwxr-x 2 user user 4096 Aug 31 20:36 dapps
45088806 drwxrwxr-x 3 user user 4096 Aug 31 20:36 keys
45088871 drwxrwxr-x 2 user user 4096 Aug 31 20:36 network
45088807 drwxrwxr-x 2 user user 4096 Aug 31 20:36 signer

user@machine:\~/\~/Experiments$ cd ; cd \$BASE
user@machine:\~/$BASE$ ls -l
total 4
drwxrwxr-x 2 user user 4096 Aug 31 20:36 cache

In a sense Parity is partially considering the --base-path parameter since it does create a directory called "Experiments", however inside the awkward "~" folder (similarly happening with "$BASE" folder).

I also played with --base-path and figured that if I used the full path:

parity --mode active --chain classic --base-path /home/user/Experiments/ethereum-classic --author 0x<omitted>

Then Parity only creates "$BASE" (and puts "cache" inside it). The remaining folder structure ends up correctly created under the manually created "/home/user/Experiments"

The same happens when translating these CLI options into TOML.

Thanks.

**Comment by 5chdn** [comment]
Thanks for the report.

That's already fixed in master #6207 (#6298) via #6212 - please wait for the 1.7.2 release including the fix.

@tomusdrw can you confirm #6212 also fixes `~` directories, not only `$BASE` (see above)?

@marciobuss Please note, you don't need the base-path parameter if you run a different chain configuration. Parity will take care of that and create different sub-dirs for each chain inside the Parity working directory.
