### ISSUE TITLE
Pending events filters don't work

### ISSUE THREAD

**Issue by LogvinovLeon** [paritytech/parity#6432]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity
  version Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-macos/rustc1.18.0
> - **Operating system**: Windows / **MacOS** / Linux
> - **And installed**: via installer / homebrew / binaries / **from source**

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

I've set up a filter for all pending events from EtherDelta on mainnet and I get all the events, but I don't get them at the moment - the transaction appears in the mempool, but I get them right before the new block arrives - which makes them useless.

**Comment by LogvinovLeon** [comment]
@tomusdrw Helped me to solve this issue by suggesting to run parity with: `--force-sealing --reseal-min-period=1 --reseal-on-txs=all`
Closing now.

**Comment by abrahamchaibi** [comment]
hello! I know this is closed but @LogvinovLeon were you able to get this to work with --infinite-pending-block? I am having exactly the same issue you are describing with the below command: `./target/release/parity --cache=4048 --jsonrpc-apis=all --min-peers=500 --snapshot-peers=5000 --no-ui --no-dapps --rpcaddr=0.0.0.0 --no-persistent-txqueue --jsonrpc-threads=10 --jsonrpc-server-threads=10 --no-serve-light --no-periodic-snapshot --infinite-pending-block --force-sealing --reseal-on-txs=all --reseal-min-period=1 --tx-queue-mem-limit=0 --tx-queue-size=1000000 --tx-queue-gas=off --tx-queue-strategy=gas_price` @tomusdrw any direction here would be immensely helpful as none of the other ethereum clients have an infinite pending block option!

**Comment by LogvinovLeon** [comment]
I ended up just using `eth_getLogs` instead of subscriptions

**Comment by abrahamchaibi** [comment]
ah interesting and then you basically poll that against pending? that actually makes a lot of sense it just never (and honestly it's been longer than I care to admit) occurred to me to try. Giving it a shot now many thanks!!

**Comment by LogvinovLeon** [comment]
Web3.js doesn't support that, but you can use ethers.js or the provider directly. Or just JSON-RPC directly. Or maybe 1.0.beta does. Dunno

**Comment by abrahamchaibi** [comment]
thanks again much appreciated!!!

**Comment by abrahamchaibi** [comment]
ugh so @LogvinovLeon sorry to bug you again but I tried running with infinite pending block, force sealing, and then just polling eth_getLogs (using fetch) for relevant topics. Still not getting the right pending events. Also tried using mem pool watcher in 0x and it's largely the same. Has this really worked for your team in practice?

**Comment by LogvinovLeon** [comment]
Mem pool watcher depends on proper node config.
This article has our node config described. https://0xproject.com/wiki#Mempool-Setup-Guide
I haven't tried that in a while (2-3 month) but the last time I did - it worked and got me all the events from an infinite pedning block.
