### ISSUE TITLE
[-32023] Could not create account.

### ISSUE THREAD

**Issue by anardo** [paritytech/parity#6439]
I'm running:

- **Parity version**: 1.7.0
- **Operating system**: MacOS Sierra 10.12.6
- **And installed**: Via installer

Hello,

While trying to recover my account I received the following error.

![screen shot 2017-09-01 at 11 11 55 pm](https://user-images.githubusercontent.com/2040769/29992568-8ea9fad8-8f6c-11e7-983c-6cb42479db21.png)

**Steps to recreate:**

Went to ~/Library/Application Support/io.parity.ethereum/keys/Ethereum/

1) Moved the Ethereum folder (Saved it of course)
2) Next, went "Accounts" tab and press "+ Restore" in the action bar. After providing my recovery phrase, account name, and new password I pressed the "Import" button, and received the above error.

Context: I lost my password when LastPass generated the password, but did not store it. As a result, I need to restore my account because I have ETH I am unable to access.

Any help would be greatly appreciated!

**Comment by roninkaizen** [comment]
best to ask the devs within gitter chat- https://gitter.im/paritytech/parity
just to get a chance get this solved

**Comment by 5chdn** [comment]
If you lose your password, you can still recover your account with the recovery phrase. Otherwise there is not much we can do.

Ref #4764
