### ISSUE TITLE
Feature Request - Update account balance before sync

### ISSUE THREAD

**Issue by tshachaf** [paritytech/parity#6444]
Parity is a great software, but syncing ethereum can take a while, it would be nice if parity would listen in on any information concerning specific user accounts while it is syncing. So the user wouldn't have to wait to be updated on any important transactions.

**Comment by 5chdn** [comment]
It's not possible to know the balance of an account without reading it from the blockchain, and in most cases this means a full synchronization process.

Parity eases this by introducing the warp-sync which downloads the latest snapshot and takes you _fast-forward_ to the latest chain head allowing you to display your account balance before the ancient block sync is fully finished.
