### ISSUE TITLE
UI glitch on parity when ERC20 token name too long

### ISSUE THREAD

**Issue by matiwinnetou** [paritytech/parity#6447]
I'm running:
- **Parity version**: 1.7.0 (beta?)
- **Operating system**: Linux
- **And installed**: Arch installation (AUR) 
(https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/parity)

![image](https://user-images.githubusercontent.com/335933/30002417-421f7bc8-90a9-11e7-9075-a7c7341910b9.png)

Actual behaviour: There seems to be wrong folding or lack of space for TokenCard tokens. In addition, it is weird that other tokens have question marks.

Expected behaviour: TokenCard tokens are wrapped or nicely aligned in UI

**Comment by 5chdn** [comment]
Can you check this source of this please? It looks like the link to the TokenCard Token image is just broken and it displays the alternative text instead. There is not much we can do, the maintainer of the token has to keep the icons updated.

**Comment by matiwinnetou** [comment]
I think you *could do* something about this to fallback better but of course you are free to ignore this and focus on more important items.

**Comment by 5chdn** [comment]
Thanks. Added it to https://github.com/paritytech/parity-long-term-issues/issues/1 until we release the new UI.
