### ISSUE TITLE
[wiki] Demo PoA tutorial

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#6448]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Linux
> - **And installed**: via installer

### Expected behavior

Both the nodes that are created by toml files are able to run alongside each other.

### Actual behavior

Before `and create the second authority account:` in heading `3. Setting up the two nodes` it says to start second node with `parity --config node1.toml`. But following errors come up:

```
Unable to listen on 127.0.0.1:8546
WebSockets address 127.0.0.1:8546 is already in use, make sure that another instance of an Ethereum client is not running or change the address using the --ws-port and --ws-interface options.
```
### Possible Fix

Update `node1.toml` and add following lines:

    [websockets]
    port = 8457

### Other Updates

 - **UI section in step 3** refers user to open `localhost:8080`, but user is unable to connect. According to `node0.toml` and `node1.toml`, UI is available at `localhost:8180` and `localhost:8181`. Step number 2 and 8 within UI need to be corrected.

 - **Step 5:** Contents of `node.pwds` can be described more clearly, that the lines written below are the contents to be stored in file named `node.pwds`.

**Comment by 5chdn** [comment]
Thanks, will look into it.

**Comment by 5chdn** [comment]
Note to self:

- [ ] Option '--dapps-port' is deprecated. Please use '--jsonrpc-port' instead.
- [ ] 2017-09-07 12:18:55  Unable to listen on 127.0.0.1:8546
- [ ] WebSockets address 127.0.0.1:8546 is already in use, make sure that another instance of an Ethereum client is not running or change the address using the --ws-port and --ws-interface options.
- [ ] Go to localhost:8080 in your browser and go through the initial setup
- [ ] Go to localhost:8081
- [ ] [dapps]
- [ ] password file

**Comment by 5chdn** [comment]
Updated everything. Except:

> - **Step 5:** Contents of `node.pwds` can be described more clearly, that the lines written below are the contents to be stored in file named `node.pwds`.

Not sure how I can make this more clearly: It says _let's create a file_ and _each line will contain a password_.

**Comment by AyushyaChitransh** [comment]
Towards the end of paragraph we can write:

> contents to be stored in file named `node.pwds` are:

**Comment by 5chdn** [comment]
Done :+1:
