### ISSUE TITLE
Signer UI should sort transactions by nonce

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6450]
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows
> - **And installed**: via installer

---

Using MetaMask (backed by local Parity node) and Etherdelta, when I deposit funds it creates two transactions back to back.  The first is an approval, and the second is a transaction to withdraw the approved funds from my account.  In this scenario, the approve transaction has a lower nonce than the withdraw transaction.  Since MetaMask is connected to my local Parity node, I can look at the signer UI and see the two transactions as they are local.  However, the transactions show up as pending in the wrong order.  The transaction with the lower nonce is on top, and the transaction with the higher nonce is on bottom.

There is a strong guarantee that the lower nonce transaction _will_ be mined first, so it should show up lower down the list which is sorted newest to oldest.

**Comment by MicahZoltu** [comment]
Note: Once the transactions are mined, they show up in the correct order in the list.

**Comment by 5chdn** [comment]
And what's the issue you experience with the unordered list of transactions in the signer tab?

**Comment by MicahZoltu** [comment]
The problem was that I found it very confusing when I was reviewing transactions.  The approval transaction was showing up higher on the list (newer) which, if true, would result in a failure of the second transaction (which was showing up lower).   I almost cancelled the transactions because I thought one was going to fail.  However, I first verified the  order in another tool (etherscan) and it showed correctly.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
