### ISSUE TITLE
Make Parity Signer UI live update as blocks are mined.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6451]
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows
> - **And installed**: via installer

---

If you open the Parity signer UI and just let it sit it will populate with new transactions as they are submitted to the chain.  However, when a block is mined with one of the transactions in the list in it, the UI does not update to indicate the the transaction has been mined and instead just sits with the transaction in a pending state.  The only way I have found to get the UI to correctly display is to switch to a different tab of the UI and then switch back, which will trigger a full reload of pending and recent local transactions (which takes a surprising long time for relatively few transactions) at which point the UI will now correctly display the transactions as mined.

Instead, the UI should simply update the rows in the local transactions list anytime a block is mined that contains one of the transactions in the list.

**Comment by 5chdn** [comment]
Closing this UI-bug/-annoyance issue as _stale_ and tracking it in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference. There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now.
