### ISSUE TITLE
Missing opcode name in `trace_call`

### ISSUE THREAD

**Issue by gkapkowski** [paritytech/parity#6453]
I'm running:

- **Parity version**: latest from docker hub
- **Operating system**: Linux/Docker
- **And installed**: docker

`trace_call` is missing `opcode` name.

```
"ops": [
            {
                "cost": 3,
                "ex": {
                    "mem": null,
                    "push": [
                        "0x60"
                    ],
                    "store": null,
                    "used": 918405
                },
                "pc": 0,
                "sub": null
            },
            {
                "cost": 3,
                "ex": {
                    "mem": null,
                    "push": [
                        "0x40"
                    ],
                    "store": null,
                    "used": 918402
                },
                "pc": 2,
                "sub": null
            },
```

I would expect additional `opcode`/`instruction` key containing information about what opcode is being executed.

The serialization code at https://github.com/paritytech/parity/blob/50495c68984c6907a9dfa5977488d0fc71794a0b/rpc/src/v1/types/trace.rs#L107 does not contain `opcode` but when generating `VMOperation` object at https://github.com/paritytech/parity/blob/50495c68984c6907a9dfa5977488d0fc71794a0b/ethcore/src/trace/executive_tracer.rs#L207 it contains `instruction` information.

**Comment by gavofyork** [comment]
this is a feature. you can look up the opcode manually from the `code` value given in the parent json element and the `pc` value of the opcode element.
