### ISSUE TITLE
MD5 for parity 1.6.10 OSX doesnt match

### ISSUE THREAD

**Issue by madhavajay** [paritytech/parity#6454]
MD5 (parity-1.6.10-osx-installer.pkg) = e9509312a33798f59a8b31132e167492

Page says:
https://github.com/paritytech/parity/releases
darwin | x86_64 | parity-1.6.10-osx-installer.pkg | fe25d71a0396e0aeab83ac421e8c4754

**Comment by 5chdn** [comment]
Indeed, it does not match. @paritytech/ci any idea why? cc @arkpar

**Comment by 5chdn** [comment]
Updated the checksums to Sha256 #6473 #4672

**Comment by madhavajay** [comment]
Awesome 👍
