### ISSUE TITLE
how to change the web gui

### ISSUE THREAD

**Issue by hankuksui** [paritytech/parity#6457]
> I'm running:
>
> - **Parity version**: version Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
> - **Operating system**: ubuntu server 16
> - **And installed**: from source

I want to change text:

> Connecting to the Parity Node. If this informational message persists, please ensure that your Parity node is running and reachable on the network.

TO:

> Connecting to the Parity Node.

---

I think it should automatically check the network and show some tips to user. But I don't know what to do.

---

**Comment by 5chdn** [comment]
Have you tried turning it off and on again? The node? Your computer?

Are you on a server environment? How are you trying to connect? How's your client configured?

**Comment by hankuksui** [comment]
5chdn I use this url: http://192.168.1.127:8180. I start parity on 192.168.1.127:
         `parity --geth --ui-interface 192.168.1.127 --ws-interface 192.168.1.127 --force-ui --jsonrpc-cors "all" --jsonrpc-interface all --jsonrpc-hosts="all" --ui-hosts "all"`

**Comment by hankuksui** [comment]
@5chdn Thanks you. Sorry I forgot this.

**Comment by 5chdn** [comment]
Your configuration has some issues<sup>1</sup>,<sup>2</sup>, but that's not related to the warning you see.

Have you tried to restart your parity node yet? Is your node fully synchronized, or is it still downloading ancient blocks? Is there anything in the logs?

<sup>1</sup>) Do you really need the `--geth` flag? If not, you can remove it and `--force-ui` all together.
<sup>2</sup>) Please, do never ever enable **all** json-rpc apis and at the same time expose them to all hosts on all interfaces. Please, double-check if you really want that. I suppose you do not have any value stored in this node.

**Comment by hankuksui** [comment]
@5chdn Thank you for your reply. I want to customize those pages, and this warning does not matter to me. : )
