### ISSUE TITLE
Windows Installer for 1.7 does not upgrade from 1.6 versions of Parity.

### ISSUE THREAD

**Issue by CyberLizard** [paritytech/parity#6462]
- **Parity version**: 1.7.0
- **Operating system**: Windows
- **And installed**: via installer

Is the versioning correct?

Installed the latest release 3x now since it's been published and the bottom left footer reckons "Parity//v1.6.10-stable-1a5b176-20170721/x86_64-windows-msvc/rustc1.18.0
Unknown capability"

**Comment by 5chdn** [comment]
Did you restart the client after installing the update?

**Comment by CyberLizard** [comment]
Well, I started it after installing the 1.7 tagged release version from GitHub. I'm saying that I am getting the same version number "since" the release and I've since installed for the 3rd time.  I thought that the version might not have been changed prior to the latest release. If that is not the case then I don't know, just reporting an issue I've noticed as "user".

![screenshot_1](https://user-images.githubusercontent.com/2921922/30063030-7a5e35ce-924d-11e7-85bb-b9c496f3f911.jpg)

However, I would very much like to run Parity in light mode.

**Comment by 5chdn** [comment]
Opening the user interface is probably just connecting to the old parity version still running. You would have to shut it down (i.e., in task manager). Could you check if this resolves your problem?

**Comment by CyberLizard** [comment]
I think we're talking past each other. What I am saying is that I have installed the 1.7 release several times since the release, my system has been shut down many times between those installs, I installed today again after pulling v1.7 from GitHub and Parity wasn't running prior to this, neither is it now (also not in the task manager. 

However, if this is only happening to me then it must be on my end instead of an "issue". Thus feel free to close this.

**Comment by 5chdn** [comment]
Just tested. Installs 1.7.0.

Have you tried uninstalling the old version first?

**Comment by CyberLizard** [comment]
I've installed v1.7 to a new folder and it's working fine now. Thus it appears if one simply installs that version to the directory of a previous version the wallet will not update properly.

**Comment by 5chdn** [comment]
Should be working with 1.7.2 now.
