### ISSUE TITLE
Restoring a wallet from the 12 words seeds generating new address ?

### ISSUE THREAD

**Issue by pierreDev33** [paritytech/parity#6477]
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows
> - **And installed**: via installer
---

hi, I have deleted parity and installed it again and I'd like to get my account (with ETH on it) back. I have my 12 words seed which i writted down when creating my account 2 months ago, and also a backup from C:\Users\xxx\AppData\Roaming\Parity\Ethereum\keys\ethereum   folder.

Which option should I use through user interface to restore my account with my ETH adress ? I tried the "Restore" option, adding my 12 words seed, but it actually created a new ETH adress instead of restoring mine. Maybe i'm wrong somehere.

Thanks a lot for your help.

**Comment by IdiomoftheGods** [comment]
Hello pierreDev33,

To import the account from a json file backup open command line and type

`C:\Users\USER> path\to\parity.exe account import path\to\long_hex.json`

Then refresh/restart parity ui to see the account under the account tab

**Comment by pierreDev33** [comment]
Thanks a lot, it worked instantly !

**Comment by hansik377** [comment]
hi,
I had installed Parity browser and have used it to acquire  .eth domain names, there are some .eth on it as well.
Now the Parity browser is disabled... could you please tell me how I can access my funds and domain names? Should I first create a .eth wallet on another platform? I have very little knowledge.
I do have a copy of my ethereum folder and the 12 words seed.
Thanks!

**Comment by 5chdn** [comment]
You can use your keys on https://mycrypto.com or https://myetherwallet.com

As far as I know they do support ENS.

**Comment by hansik377** [comment]
thanks. I should choose "Unlock your Mnemonic Phrase" correct?
I understand it's not a standard way to use this in the browser, but for once...

But that doesnt work when I paste my 12 words seeds. I am being asked an optional password, but no idea which one. 

Sorry if I sound stupid, I have no experience.

**Comment by Tbaut** [comment]
The password asked is to secure your account. As you pointed out, it's optional. You can chose any password, that you will need to type in any time you want to make a transaction or extract your keys (to use it on MyCrypto for instance)

**Comment by hansik377** [comment]
I don't know what I'm doing wrong, but after giving in the 12 words... there is no OK button or NEXT button or so... does that mean there is an issue? The words are separated by one space.

**Comment by Tbaut** [comment]
@hansik377 please create a new issue in the Parity UI repo: https://github.com/parity-js/shell/issues/new mentioning your setup (what OS, Parity version, Parity UI version etc) for us to provide the best possible support.
