### ISSUE TITLE
Parity Missing admin API

### ISSUE THREAD

**Issue by rickw** [paritytech/parity#6479]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.6.7
> - **Operating system**: MacOS / Linux
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
When trying to access the admin API interface I get an error

`ReferenceError: 'admin' is not defined
    at <anonymous>:1:1`
---

**Comment by 5chdn** [comment]
What are you trying to do? We have a lot of other interesting APIs to offer.

https://github.com/paritytech/parity/wiki/JSONRPC

**Comment by rickw** [comment]
The web3.admin API:

admin
———
addPeer
peers
nodeInfo
datadir
importChain
exportChain
startRPC
stopRPC
startWS
stopWS
verbosity
setSolc
sleep
sleepBlocks
startNatSpec
stopNatSpec
getContractInfo
register
registerUrl

**Comment by 5chdn** [comment]
That's a specific API to configure Geth and not available for Parity.

**Comment by rickw** [comment]
So in Parity there is no way to list the connected peers?

**Comment by 5chdn** [comment]
Try `parity_netPeers` :)

https://github.com/paritytech/parity/wiki/JSONRPC-parity-module#parity_netpeers

**Comment by rickw** [comment]
Thanks, apologies for missing that.

**Comment by 5chdn** [comment]
Just ask me if you need anything else. Most of the APIs are similar in the different clients. We prefix all APIs that are custom with `parity_`.

**Comment by 5chdn** [comment]
let me format that for you https://jsonformatter.curiousconcept.com/ :smile: 

```json
{
  "jsonrpc":"2.0",
  "result":{
    "active":2,
    "connected":2,
    "max":25,
    "peers":[
      {
        "caps":[

        ],
        "id":"575bbc154d3c37c35d5f91a42813641fef4389bc288c0e50cf2ab1cbbde014287b93d3748336ff02c99a11e7d58ab54868933c7a9804c36a071078cb9a586ca8",
        "name":"",
        "network":{
          "localAddress":"77.23.7.15:39741",
          "remoteAddress":"Handshake"
        },
        "protocols":{
          "eth":null,
          "les":null
        }
      },
      {
        "caps":[
          "eth/63",
          "eth/62"
        ],
        "id":"4d331051d8fb471c87a9351b36ffb72bf445a9337727d229e03c668f99897264bf11e1b897b1561f5889825e2211b06858139fa469fdf73c64d43a567ea72479",
        "name":"Geth/v1.5.9-stable-a07539fb/linux/go1.7.1",
        "network":{
          "localAddress":"77.13.17.145:35507",
          "remoteAddress":"13.40.17.95:3000"
        },
        "protocols":{
          "eth":{
            "difficulty":null,
            "head":"3060e08b5cd0b90adb3c464342f6df13482361e8ef09724d7525cae48abbaf59",
            "version":63
          },
          "les":null
        }
      },
      {
        "caps":[

        ],
        "id":"13d6cc66f445072d2e389c5d47d1557543ec9f96237576a38072a5b76b67ba445050641219e1f42c1443a7287fab6cb3f4c078fa886520cbf3577ac23f5e0cad",
        "name":"",
        "network":{
          "localAddress":"77.13.17.15:44079",
          "remoteAddress":"Handshake"
        },
        "protocols":{
          "eth":null,
          "les":null
        }
      },
      {
        "caps":[

        ],
        "id":null,
        "name":"",
        "network":{
          "          lo
```

JSON is not meant to be human-readable. What are you trying to do?

**Comment by avatar-lavventura** [comment]
ah got it :) Well I was just trying the obtain connected peers information such as their ip-addresses, enode-id, their open port etc.@5chdn

**Comment by qiluge** [comment]
please help me to fetch [admin.netInfo](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_nodeinfo) by rpc, thx.@5chdn
