### ISSUE TITLE
Insufficient funds while trying to send a transaction

### ISSUE THREAD

**Issue by sjStefan** [paritytech/parity#6481]
>
> - **Parity version**: 1.7.0
> - **Operating system**: Ubuntu 16.04 LTS
> - **And installed**: via deb Package from https://parity.io/parity.html
> - **cmd line**: parity daemon /foo/bar/parity.pid

## Actual behaviour:
From time to time I'm stumbling upon the error
> Insufficient funds. The account you tried to send transaction from does not have enough funds. Required xxx and got: xxx

while trying to send the entire amount of the address (minus the cost for gas) by using personal_sendTransaction.

In my specific case I'm trying to empty an address which owns 1 ETH.

The details for the transaction looked like this:

- gasPrice: '27221063327' in wei
- gas: '21000'
- value: '999428360000000000' in wei

Converted to hex all of this looked like this:
- gasPrice: '0x65680769f'
- gas: '0x5208'
- value: '0xddeaecc58405000' 

As a result I'm running into the following error:

> Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000000002329867000 and got: 1000000000000000000

I had explicitly specified the gas price and quoted the hex values.

I managed to successfully send another transaction quite a bit later, but I have no clue why.
The sender-address once again had a balance of 1 ETH and here are the transaction-details:

- gasPrice: '35500000000' in wei
- gas: '21000'
- value: '999254500000000000' in wei

Converted to hex all of this looks like this:
- gasPrice: '0x843F70300'
- gas: '0x5208'
- value: '0xDDE10AC68B5E800' 

I don't get it. In both cases the total costs for the transaction (value + (gas * gasLimit)) are 1 ether. And this is the exact balance of the address.

## Expected behaviour:
Sending the entire balance of an address in a transaction should not end up in an error.

**Comment by 5chdn** [comment]
Without testing the RPC, your math is off by some wei:

```
1e18-27221063327*21000
= 999428357670133000

ans-999428360000000000
= -2329867000
```

Which is exactly:

> Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 1000000002329867000 and got: 1000000000000000000

How are you calculating these numbers?

**Comment by sjStefan** [comment]
You're right. Shame on me.
The issues lies in the language I'm using for this.
The precision for the calculations wasn't high enought, as I calculated the total gas cost (gas * gasAmount) in ether in the first place and converted this value to wei, which ended up in a much shorter number.

Thanks.
