### ISSUE TITLE
Failed on creating contract

### ISSUE THREAD

**Issue by ValeryDubrava** [paritytech/parity#6482]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Debian Linux
> - **And installed**: from deb package

Fill the contract creating form (with advanced). After all, "create" button do nothing. In chrome development console I've found the error:
![image](https://user-images.githubusercontent.com/1236525/30202210-3731bd94-9486-11e7-91ea-07a2609f3297.png)

```
vendor.js:1 Uncaught Error: Cannot convert function to valid ParamType
    at a (index.e9b5956b9a.js:1)
    at new e (index.e9b5956b9a.js:1)
    at index.e9b5956b9a.js:1
    at Array.map (<anonymous>)
    at Function.value (index.e9b5956b9a.js:1)
    at new e (index.e9b5956b9a.js:1)
    at index.e9b5956b9a.js:1
    at Array.map (<anonymous>)
    at Function.value (index.e9b5956b9a.js:1)
    at t.e (index.e9b5956b9a.js:1)
```
---

**Comment by 5chdn** [comment]
Please share the contract and ABI, I can try to look into this.

**Comment by ValeryDubrava** [comment]
Api:

`[{"constant":false,"inputs":[{"name":"myid","type":"bytes32"},{"name":"result","type":"string"}],"name":"__callback","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"queryId","type":"bytes32"},{"name":"result","type":"string"},{"name":"","type":"bytes"}],"name":"__callback","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"target","type":"address"},{"name":"startBlock","type":"uint256"},{"name":"endBlock","type":"uint256"},{"name":"callback","type":"function"}],"name":"query","outputs":[{"name":"","type":"bool"}],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[],"name":"getPrice","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"","type":"uint256"}],"name":"Price","type":"event"}]`

**Comment by ValeryDubrava** [comment]
I will try to check this on small contract with the same signature.

**Comment by 5chdn** [comment]
Please also share the contract, not only the ABI.
