### ISSUE TITLE
Graceful exit when invalid CLI flags are passed

### ISSUE THREAD

**Issue by ngotchac** [paritytech/parity#6485]
Parity should panic and exit with an non-0 exit code when invalid CLI flags are passed.

**Comment by rphmeier** [comment]
panicking seems a little drastic. a helpful message and exit should be fine

**Comment by 5chdn** [comment]
I'm not sure what this ticket is about.

    0 ✓ user@alcor ~ $ parity --please-exit-gracefully
    Unknown flag: '--please-exit-gracefully'

    Usage:
      parity [options]
      parity ui [options]
      parity dapp <path> [options]
      parity daemon <pid-file> [options]
      parity account (new | list ) [options]
      parity account import <path>... [options]
      parity wallet import <path> --password FILE [options]
      parity import [ <file> ] [options]
      parity export (blocks | state) [ <file> ] [options]
      parity signer new-token [options]
      parity signer list [options]
      parity signer sign [ <id> ] [ --password FILE ] [options]
      parity signer reject <id> [options]
      parity snapshot <file> [options]
      parity restore [ <file> ] [options]
      parity tools hash <file>
      parity db kill [options]
    1 ✗ user@alcor ~ $ parity --tracing noway
    Loading config file from /home/user/.local/share/io.parity.ethereum/config.toml
    Invalid switch value: noway
    1 ✗ user@alcor ~ $ 

It always exits with a non-`0` exit code (`1` in both cases above, note the `1 ✗` in my `PS1`). This is 1.7.2.

**Comment by ngotchac** [comment]
It used to work this way, but doesn't actually on `master`.

**Comment by 5chdn** [comment]
True.

**Comment by axelchalon** [comment]
So, this is caused by
```rust
.global_setting(AppSettings::AllowLeadingHyphen) // allow for example --allow-ips -10.0.0.0/8
```
https://github.com/paritytech/parity/blob/master/parity/cli/usage.rs#L540
