### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by KenoLeon** [paritytech/parity#6486]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: v1.6.10-stable
> - **Operating system**: MacOS
> - **And installed**:homebrew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Actual: When running parity Ui from terminal Safari opens and freezes.
expected behavior:  Can click the next button.

Solution/Workaround: Worked on chrome.

---

**Comment by 5chdn** [comment]
Probably #6387.

Does Safari _always_ freeze? Does it work if you leave it like that for 15 minutes and try again? Might be also #6280. Are you on SSD or HDD?

**Comment by KenoLeon** [comment]
After about 10 tries it freezes every single time, I got it past the splash/account creation part but when trying to consult transaction history it froze again. I am on SSD. It does work on chrome without issues.

**Comment by 5chdn** [comment]
Can you please try again with 1.7.2? And can you confirm it freezes for more than a short amount of time?

**Comment by KenoLeon** [comment]
Err, I am having issues, do I need to uninstall and then reinstall without --stable, upgrade does not seem to work:

Error: parity 1.6.10 is already installed
To upgrade to 1.7.2, run `brew upgrade parity`
Kenos-MacBook-Air:~ kenoleon$  brew upgrade parity
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
paritytech/paritytech/parity 1.7.2
==> Upgrading paritytech/paritytech/parity --stable
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.6.10/x86_64-apple-darwin
Already downloaded: /Users/kenoleon/Library/Caches/Homebrew/parity-1.6.10
Error: Empty installation

**Comment by KenoLeon** [comment]
@5chdn : Uninstalled and reinstalled and now it works great on Safari Thanks
