### ISSUE TITLE
Token Registration is not allowed if totalSupply is 0

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#6487]
Example: 
100% valid token contract with 0 totalSupply (Mintable) 

https://etherscan.io/address/0x1C3beD5bD4B0E6a8389EfD0D2876F948a907ab5b 

https://github.com/paritytech/parity/blob/8404edb656693270ec1cd3956d204f625d28ec7c/js/src/dapps/tokenreg/Inputs/validation.js#L85

Because of this validation it thinks that it's not valid. So I had to register this token by calling TokenReg contract directly: 
https://etherscan.io/address/0x5F0281910Af44bFb5fC7e86A404d0304B0e042F1#code
`register` function with 0.05eth fee

**Comment by 5chdn** [comment]
Yes, the idea is to keep the registry clean from dead tokens. A mintable token is a lovely idea, however, we will probably not remove that constraint in the UI since you already have proven it works out well for advanced users by simply calling the contract directly.

**Comment by rstormsf** [comment]
Got it. and I made a mistake there: I set `base`: `18` while I should have set to 1e18 ( 1000000000000000000) so now I'm looking for an owner of this contract to call `unregister` with an ID of 448.
@5chdn any help on that? 
Do you know who is the owner of this contract? [owner](https://etherscan.io/address/0x3ff047e5e803e20f5ef55ea1029adb89618047db)

[TokenReg](https://etherscan.io/address/0x5F0281910Af44bFb5fC7e86A404d0304B0e042F1#readContract)

**Comment by rstormsf** [comment]
Someone told me that you are the owner of TokenReg.sol @5chdn 
You can also find me in Telegram or gitter: @rstormsf
