### ISSUE TITLE
Problems with Parity Sync - Slower than new blocks are being formed!

### ISSUE THREAD

**Issue by CryptoMagnetron** [paritytech/parity#6489]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: MacOS
> - **And installed**: via Terminal based installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

Hi!  First time poster on github, so please bear with me.  If you can assist me in diagnosing and fixing my issues here, your time and help will be greatly appreciated!  

My parity wallet is syncing slower than normal.  In fact, it's syncing so slow "best blocks" are showing up slower than new blocks are being created, so I'm literally falling furhter and further behind.   Not sure what to do in order to fix it.  I've got a decent internet connection at 15mbs, but when I first open Parity, I'm often times left waiting for it to even load and connect to the network for quite some time.  It used to be much faster and more stable!   Why might this be and how would you suggest I fix it so it's faster to load and sync?

Another strange thing that keeps happening is that no matter how many times I select "Start at Logon", after a little while it resets so that I have to select this option again.  This often leads to my parity node not loading and being online when I expect it to be, and therefor falling out of sync, which I'd like to avoid altogether.  

I am also rarely able to connect to any peers in the first column of connected peers.  i.e. X/8/25  Is this normal?  Is there a way to connect to more peers?  Maybe a list of stable peer URL's to manually connect to somehow?  Any help in solving these issues and optimizing my parity setup would be greatly appreciated!  Thanks for at least taking the time to read this, your help will be anxiously anticipated as I've got some ICOs I'm hoping to take part in coming up, and this issue is making me nervous about using Parity to invest..  Thanks again!

**Comment by 5chdn** [comment]
Please share some logs. Does your mac contain an SSD or HDD?

Might be either #6372 or #6280

**Comment by CryptoMagnetron** [comment]
Hi!  Thanks for trying to help me out.   It's an HDD.  Is this what you're looking for?

NODE LOGS
-

[9/12/2017, 2:11:18 AM]
 Syncing #4264846 8de6…cac6 0 blk/s 27 tx/s 0 Mgas/s 0+ 384 Qed #4265231 16/25 peers 6 MiB chain 84 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 13 req/s, 246 µs

[9/12/2017, 2:11:08 AM]
 Syncing #4264845 2c7b…a837 0 blk/s 0 tx/s 0 Mgas/s 0+ 384 Qed #4265231 16/25 peers 6 MiB chain 84 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 11 req/s, 128 µs

[9/12/2017, 2:11:03 AM]
 Syncing #4264845 2c7b…a837 0 blk/s 0 tx/s 0 Mgas/s 0+ 384 Qed #4265231 16/25 peers 6 MiB chain 84 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 12 req/s, 149 µs

[9/12/2017, 2:10:58 AM]
 Syncing #4264845 2c7b…a837 0 blk/s 0 tx/s 0 Mgas/s 0+ 384 Qed #4265231 16/25 peers 6 MiB chain 84 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 10 req/s, 154 µs

[9/12/2017, 2:10:53 AM]
 Syncing #4264845 2c7b…a837 0 blk/s 9 tx/s 0 Mgas/s 0+ 384 Qed #4265231 14/25 peers 6 MiB chain 84 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 7 req/s, 57510 µs

[9/12/2017, 2:10:48 AM]
 Syncing #4264844 c9f3…2691 0 blk/s 28 tx/s 0 Mgas/s 0+ 384 Qed #4265231 16/25 peers 6 MiB chain 85 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 0 req/s, 6450942 µs

[9/12/2017, 2:10:38 AM]
 Syncing #4264843 caa7…c3c7 0 blk/s 0 tx/s 0 Mgas/s 0+ 384 Qed #4265231 15/25 peers 7 MiB chain 85 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 3 req/s, 12332055 µs

[9/12/2017, 2:10:33 AM]
 Syncing #4264843 caa7…c3c7 0 blk/s 0 tx/s 0 Mgas/s 0+ 384 Qed #4265231 15/25 peers 7 MiB chain 85 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 113 req/s, 7399534 µs

[9/12/2017, 2:10:28 AM]
 Syncing #4264843 caa7…c3c7 0 blk/s 0 tx/s 0 Mgas/s 0+ 384 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 41 MiB queue 13 MiB sync RPC: 2 conn, 254 req/s, 21505 µs

[9/12/2017, 2:10:18 AM]
 Syncing #4264843 caa7…c3c7 0 blk/s 8 tx/s 0 Mgas/s 0+ 384 Qed #4265231 15/25 peers 5 MiB chain 85 MiB db 41 MiB queue 13 MiB sync RPC: 1 conn, 2 req/s, 8123756 µs

[9/12/2017, 2:10:08 AM]
 Syncing #4264842 007c…8dff 0 blk/s 0 tx/s 0 Mgas/s 0+ 388 Qed #4265231 16/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 3 req/s, 407 µs

[9/12/2017, 2:09:58 AM]
 Syncing #4264842 007c…8dff 0 blk/s 15 tx/s 0 Mgas/s 0+ 388 Qed #4265231 16/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 5 req/s, 343 µs

[9/12/2017, 2:09:48 AM]
 Syncing #4264841 8cf0…68cb 0 blk/s 0 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 4 req/s, 320 µs

[9/12/2017, 2:09:38 AM]
 Syncing #4264841 8cf0…68cb 0 blk/s 15 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 4 req/s, 297 µs

[9/12/2017, 2:09:28 AM]
 Syncing #4264840 3fc9…f5ae 0 blk/s 0 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 3 req/s, 297 µs

[9/12/2017, 2:09:18 AM]
 Syncing #4264840 3fc9…f5ae 0 blk/s 23 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 2 req/s, 347 µs

[9/12/2017, 2:09:08 AM]
 Syncing #4264839 e523…5edb 0 blk/s 0 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 0 req/s, 384 µs

[9/12/2017, 2:09:03 AM]
 Syncing #4264839 e523…5edb 0 blk/s 0 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 4 req/s, 384 µs

[9/12/2017, 2:08:53 AM]
 Syncing #4264839 e523…5edb 0 blk/s 0 tx/s 0 Mgas/s 0+ 388 Qed #4265231 15/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 3 req/s, 384 µs

[9/12/2017, 2:08:48 AM]
 Syncing #4264839 e523…5edb 0 blk/s 28 tx/s 0 Mgas/s 0+ 388 Qed #4265231 14/25 peers 6 MiB chain 85 MiB db 42 MiB queue 13 MiB sync RPC: 1 conn, 3 req/s, 318 µs

[9/12/2017, 2:08:38 AM]
 Syncing #4264838 ae06…1c2a 0 blk/s 0 tx/s 0 Mgas/s 0+ 392 Qed #4265231 14/25 peers 6 MiB chain 85 MiB db 43 MiB queue 13 MiB sync RPC: 1 conn, 5 req/s, 325 µs

[9/12/2017, 2:08:33 AM]
 Syncing #4264838 ae06…1c2a 0 blk/s 0 tx/s 0 Mgas/s 0+ 392 Qed #4265231 14/25 peers 6 MiB chain 85 MiB db 43 MiB queue 13 MiB sync RPC: 1 conn, 2 req/s, 13751809 µs

[9/12/2017, 2:08:23 AM]
 Syncing #4264838 ae06…1c2a 0 blk/s 0 tx/s 0 Mgas/s 0+ 392 Qed #4265231 13/25 peers 6 MiB chain 85 MiB db 43 MiB queue 13 MiB sync RPC: 1 conn, 0 req/s, 13718059 µs

[9/12/2017, 2:08:13 AM]
 Syncing #4264838 ae06…1c2a 0 blk/s 0 tx/s 0 Mgas/s 0+ 392 Qed #4265231 13/25 peers 6 MiB chain 85 MiB db 43 MiB queue 13 MiB sync RPC: 1 conn, 144 req/s, 3645234 µs

[9/12/2017, 2:08:08 AM]
 Syncing #4264838 ae06…1c2a 0 blk/s 10 tx/s 0 Mgas/s 0+ 392 Qed #4265231 13/25 peers 6 MiB chain 85 MiB db 43 MiB queue 13 MiB sync RPC: 1 conn, 4 req/s, 292 µs

**Comment by 5chdn** [comment]
I'm afraid we are getting close to the limits of modern hard-drives.

Can you try again with 1.7.2? We improved warp sync to get you faster to the top.
