### ISSUE TITLE
Resending transaction with TxQueue Viewer fails

### ISSUE THREAD

**Issue by ChristophSiegenthaler** [paritytech/parity#6492]
> I'm running:
> - **Parity version**: v1.8.0-unstable-8f434cd02-20170906
> - **Operating system**: ArchLinux
> - **And installed**: from source (git)

Can't resend transaction with a higher gas price. Parity tries to send the old transaction double instead of sending the new one with the higher gas price.

Expected behavior:
1. Send transaction
2. Resend transaction with higher gas price in TxQueue Viewer
3. ... sends new transaction and makes old transaction obsolete.

Actual behavior: 
1. Send transaction
2. Can't resend transaction with higher gas price. Error message hints at parity trying to double send the old transaction instead of sending the new one.
3. Error message in console: Error importing transaction: Transaction(TooCheapToReplace)
---

**Comment by tomusdrw** [comment]
How big is the gas price increment? Parity will only accept transaction if gas price is at least 12.5% higher.

**Comment by ChristophSiegenthaler** [comment]
It was indeed lower. Okay, I wasn't aware of that and didn't make the right connection there. Thanks for the clarification.

**Comment by tomusdrw** [comment]
Yeah, it's a new feature present in version 1.7 to prevent excessive traffic that could be caused by constantly-replaced transactions. The UI should suggest the expected increase in the gas price, that will be implemented in UI2.
