### ISSUE TITLE
Password hints are shown in upper case

### ISSUE THREAD

**Issue by tom-seddon** [paritytech/parity#6493]
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0 [note: copied by hand, VirtualBox clipboard isn't working for me]
> - **Operating system**: Linux
> - **And installed**: via installer

Password hints are displayed in upper case, which is unhelpful, as my password hints are case-sensitive.

Thanks,

--Tom

**Comment by 5chdn** [comment]
There will be new user interface in one of the upcoming releases and the current wallet will only receive critical fixes for now. However, I'm tracking your annoyance in the meta issue [here](https://github.com/paritytech/parity-long-term-issues/issues/1) for future reference.
