### ISSUE TITLE
ShapeShift transfer from ETH origin coin type non-operational

### ISSUE THREAD

**Issue by xorxornop** [paritytech/parity#6494]
> I'm running:
>
> - **Parity version**: 1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows 10 Pro
> - **And installed**: via installer

---

When attempting to use the ShapeShift functionality, in Step 1 where you select the origin coin type for the transfer, when attempting to use ETH as this type, the text in the button to proceed to the next step is : `No price match was found for the selected type`, and further progress is blocked. 

![parity shapeshift eth price match error](https://user-images.githubusercontent.com/3627862/30253737-70782efc-96df-11e7-9461-1085a8d410c8.png)

This does not occur for any other coin type that I attempted (particularly puzzling given that I am, after all, using an ETH wallet as the very client for doing so..!)

**Steps to reproduce:**

1. Begin a ShapeShift operation from within the Account Management section of the client.
2. Select _ETH_ as the coin type for the field labelled "fund account from".
3. That's it.

This is not an error originating from ShapeShift, as I am still able to use their website and mobile application to do so - i.e. it is possible to transfer ETH to any other of their supported coin types independently of Parity.

**Comment by 5chdn** [comment]
> particularly puzzling given that I am, after all, using an ETH wallet as the very client for doing so..!

Well, what's the general plan here? You want to fund your ETH parity wallet with ETH through shapeshift?

You could simply generate a new account and transfer the ETH directly without any intermediary.

**Comment by xorxornop** [comment]
No, the intention was to transfer ETH to BTC.
