### ISSUE TITLE
Logger is broken

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#6495]
> - **Parity version**: v1.8.0-unstable-dcea17f8c-20170910/x86_64-linux-gnu/rustc1.19.0
> - **Operating system**:  Ubuntu GNU/Linux 17.4
> - **And installed**: from source dcea17f8c-20170910

Expected:

	-l, --logging=[LOGGING]

Actual:

`-lrpc=trace` does nothing / is ignored.

Probably introduced with #6356 /cc @axelchalon ref #2066

**Comment by axelchalon** [comment]
isn't `-l rpc=trace` the correct syntax? the latter works fine for me

**Comment by 5chdn** [comment]
Ok, can work with that. :p
