### ISSUE TITLE
Panicked at 'DB flush failed'

### ISSUE THREAD

**Issue by thomasfire** [paritytech/parity#6501]
I'm running:
**Parity version**: Parity/v1.8.0-unstable-246b528-20170908/x86_64-linux-gnu/rustc1.20.0
**Operating system**: Linux
 **And installed**: from source

I just run either `parity --db-compaction ssd --cache 1024` or `parity --db-compaction ssd --cache 2048`, and soon after running i have this panic message:
```
stack backtrace:
   0:     0x5579079765ec - backtrace::backtrace::trace::h9b9a5fb45660e72d

Thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)
```
And I cannot sync it normally!

**Comment by 5chdn** [comment]
Does this also appear after you reset your database with `parity db kill`?

**Comment by thomasfire** [comment]
No, after resetting db it syncs normally, but I thought that parity would just delete corrupted block (or next blocks), but wouldn`t panic so that and I would have to download whole blockchain again.

**Comment by rphmeier** [comment]
"block" in this case is referring to a rocksdb chunk of data, not a block in the chain. It means that the database has become corrupted, and there's not much that can be done in that case.
