### ISSUE TITLE
Flag to start a parking_lot deadlock detector

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#6502]
https://amanieu.github.io/parking_lot/parking_lot/deadlock/index.html

Should basically just do the same as the example there:
  1. check for deadlocks every N seconds
  2. print backtraces
  3. exit

**Comment by rphmeier** [comment]
Should wait for the feature to become non-experimental, though.

**Comment by folsen** [comment]
It is still experimental, someone re-raise this issue if it ever becomes non-experimental (seems unlikely).
