### ISSUE TITLE
Parity fails syncing blockchain

### ISSUE THREAD

**Issue by andrewbernard** [paritytech/parity#6506]
I'm running:
**Parity version**: 1.8.0 head revision branch master from git
**Operating system**: Ubuntu Xenaial 16.0.4. LTS
**And installed**: from source

Unable to sync blockchain. Following log explicity says this failure is a bug.

---

stack backtrace:
   0:     0x5631a497f024 - backtrace::backtrace::libunwind::trace
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace<closure>
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:     0x5631a497f3df - backtrace::capture::{{impl}}::new
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:     0x5631a22d1c33 - panic_hook::panic_hook
                        at panic_hook/src/lib.rs:53
   3:     0x5631a22cf978 - core::ops::function::Fn::call<fn(&std::panicking::PanicInfo),(&std::panicking::PanicInfo)>
                        at /checkout/src/libcore/ops/function.rs:48
   4:     0x5631a5115556 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   5:     0x5631a51153e4 - std::panicking::begin_panic_new<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:553
   6:     0x5631a51152e9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   7:     0x5631a511527a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:497
   8:     0x5631a5143630 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:92
   9:     0x5631a37ecb58 - core::result::unwrap_failed<alloc::string::String>
                        at /checkout/src/libcore/macros.rs:41
  10:     0x5631a36bef32 - core::result::{{impl}}::expect<(),alloc::string::String>
                        at /checkout/src/libcore/result.rs:762
  11:     0x5631a3b9e582 - ethcore::client::client::{{impl}}::import_verified_blocks
                        at ethcore/src/client/client.rs:582
  12:     0x5631a3c4a921 - ethcore::service::{{impl}}::message
                        at ethcore/src/service.rs:193
  13:     0x5631a330590f - ethcore_io::worker::{{impl}}::do_work<ethcore::service::ClientIoMessage>
                        at /root/parity/util/io/src/worker.rs:123
  14:     0x5631a3306d67 - ethcore_io::worker::{{impl}}::work_loop<ethcore::service::ClientIoMessage>
                        at /root/parity/util/io/src/worker.rs:101
  15:     0x5631a33052b5 - ethcore_io::worker::{{impl}}::new::{{closure}}<ethcore::service::ClientIoMessage>
                        at /root/parity/util/io/src/worker.rs:79
  16:     0x5631a3524b47 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  17:     0x5631a35a508d - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /checkout/src/libstd/thread/mod.rs:364
  18:     0x5631a32ccbd7 - std::panic::{{impl}}::call_once<(),closure>
                        at /checkout/src/libstd/panic.rs:296
  19:     0x5631a35aaf76 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /checkout/src/libstd/panicking.rs:479
  20:     0x5631a511c0ab - panic_abort::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_abort/lib.rs:40

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by 5chdn** [comment]
Which exact version are you running? Does it still occur if you reset your database with `parity db kill`?

**Comment by CryptoMagnetron** [comment]
@5chdn, I'm also having trouble syncing and tried using the command you suggested to try to reset my database.  Is that something you're supposed to paste into Terminal?  Because when I do, I get "-bash: /usr/local/bin/parity: Permission denied" and no luck resenting the database..  Am I doing something wrong, or is there something wrong that this isn't working?  (sorry to jump in!)

**Comment by 5chdn** [comment]
@CryptoMagnetron you are welcome to jump in. Which OS are you using?

**Comment by roninkaizen** [comment]
@5chdn it seems as if this is not a real bug.
i have seen this before, but noticed that the database was corrupted therefore killed it.
As i was told i issue an error after third time of appearance.
@CryptoMagnetron i am in gitter- we could go through it step by step just to assure your parity.confidence- as this does not lead to stable running software, you will be able to report issues better in a way to help solving it

**Comment by roninkaizen** [comment]
thx, agree,ack
