### ISSUE TITLE
In nightly 1.8 gasLimitBoundDivisor field is set in multiple locations

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#6508]
> I'm testing nightly:
>
> - **Parity version**: Parity/v1.8.0-nightly-8f434cd-20170906/x86_64-linux-gnu/rustc1.19.0
> - **Operating system**: Linux Ubuntu 16.04
> - **And installed**: binary

It seems that starting from parity 1.8 `gasLimitBoundDivisor` field became required in `params` block of spec, I get this error trying to start a node with 1.7 spec:
```
Spec json is invalid: missing field `gasLimitBoundDivisor` at line
```
We are trying to setup private PoA network and in [docs](https://github.com/paritytech/parity/wiki/Pluggable-Consensus) there is also  `gasLimitBoundDivisor` field in `engine.authorityRound.params`.

How are they related, should we keep both or one is redundant?

**Comment by rphmeier** [comment]
@phahulin for 1.8.0 we are currently undergoing a refactor to make all consensus engines compatible with an abstract notion of a chain. This includes moving some parameters relevant only to ethereum-like chains (like `gasLimitBoundDivisor` and some hard forks) into the more general "params" section. 

Upcoming PRs will shuffle things around further, so the advice I can currently give is to stay with 1.7.x.

**Comment by phahulin** [comment]
@rphmeier Could you reopen this and keep it opened until PR that solves it is issued.
We are making a private PoA network, currently we use 1.7, and it is important to us to start testing 1.8 as soon as possible to mitigate possible problems.
Thank you.

**Comment by rphmeier** [comment]
Instability of the master branch will not be solved until it becomes the beta branch. There isn't much more I can do about that.
