### ISSUE TITLE
Non-determinism caused by wasm floats [question] 

### ISSUE THREAD

**Issue by chpio** [paritytech/parity#6511]
Hi,

Floating point operations can introduce non determinism into the system. Non determinism is really bad for crypto systems (eg. breaks hash validity on some machines). Are there already measures in place to avoid that?

I think we should avoid that by disallowing `wasm`s float operations all together (marking a contract invalid if there are float ops).

**Comment by NikVolf** [comment]
Hi, there is no floating point non-determinism in WebAssembly except some cases of handling NaN arguments across various platforms.

NaN can cause some problems, but we might handle them in exchange of reduction in performance by requiring interpreters to canonicalize NaN always. See https://github.com/WebAssembly/design/blob/master/Rationale.md#nan-bit-pattern-nondeterminism if you need some details.

We still can run into problems when interpreter(s) will be replaced by native code generation from WASM, so banning floats might be a good idea anyway.

We should come to the final solution before 1.8 release and are open to ideas/discussion

**Comment by NikVolf** [comment]
Would like to keep it open for some discussions

**Comment by NikVolf** [comment]
and we close it since we decided to ban floats from wasm (but they may reappear if we figure out how to avoid NaN non-determinism)
