### ISSUE TITLE
TokenReg upgrade proposal

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#6515]
1)I believe the way it should work - it has to read Symbol and Decimals from the token contract without user's input. 

Example: 
Register Token -> Enter address -> scan blockchain to find:
1)Symbol
2)Decimals

to prevent somebody to just take your symbol name from registry. 

There should also be somehow proof-of-ownership. But it's more complicated:
find who created the contract If isNotContract(address) = return address, 
if some contract deployed the token, find in the tree of contracts the original creator at the end of the chain.  That would be separate Dapp that can prove and register an owner. Only then you would register a token contract once your proved your ownership. (just an idea)

**Comment by 5chdn** [comment]
Thanks for your proposal, I added it to our long-term goals in https://github.com/paritytech/parity-long-term-issues/issues/1

**Comment by 5chdn** [comment]
Strongly related to #6030
