### ISSUE TITLE
Badge display no longer works

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6518]
See #3665
This feature used to work. I report this one now as I just noticed it but I think the regression is rather old. I also see the issue on `Parity/v1.7.0-unstable-f22745eb0-20170630/x86_64-macos/rustc1.18.0`

> I'm running:
> - **Parity version**: `Parity/v1.8.0-unstable-e9abcb2f6-20170912/x86_64-macos/rustc1.20.0`
> - **Operating system**: MacOS 
> - **And installed**: from source / master

Your issue description goes here below. 
**actual** The badges do not show up (tested on mainnet with the SMS verif and ropsten with the Oprah contract)
**expected behavior** The badges show up
**steps to reproduce** Get a badge (Oprah on ropsten makes it easy), and look at your account.

---

**Comment by 5chdn** [comment]
Thanks for confirming. Adding it to https://github.com/paritytech/parity-long-term-issues/issues/1 until we release the new UI.

**Comment by 5chdn** [comment]
@chevdor Could you tell me, do you see token balances on ropsten? It seems the registries are broken.

**Comment by chevdor** [comment]
On ropsten, good question. I need to check. On Kovan I am positive that
everything related to tokens is ok: I see both balance and image.

**Comment by chevdor** [comment]
After a check on ropsten, I confirm: I can see token balances:
![image](https://user-images.githubusercontent.com/738724/30521010-650ccd88-9bb8-11e7-8ac7-22e8015207d5.png)
(You made me buy some GavCoins 🥇 )

**Comment by chevdor** [comment]
Oprah confirms I am 'OK' :)
![image](https://user-images.githubusercontent.com/738724/30521097-daa4a0e2-9bb9-11e7-9dd8-0dcc395bf907.png)

**Comment by chevdor** [comment]
@5chdn There is something weird.
I am assuming that BadgeReg on Ropsten is 0xcF5A62987294fd2087252FD812443508528C52bF
I am assuming that the Oprah badge is 0xdD6a26f8971dF44698a2A3213512A5e3a0f97F61

The BadgeReg is not aware of 0xdD6a26f8971dF44698a2A3213512A5e3a0f97F61
![image](https://user-images.githubusercontent.com/738724/30521624-af63490c-9bc2-11e7-8cc4-f32341a05544.png)

**Comment by chevdor** [comment]
Closing this issue. The problem was in the issue providing the addresses of the badges on ropsten.
I found the real Oprah badge contract: 0x72f4b7a806d8fd0a2f7d66c0CD1D71ea40Be5669
The contract was deployed 2 times and the first deploy probably had an issue and got revoked.

This one IS in the BadgeReg and it works all fine on Ropsten as the picture below shows.

That also answers my previous question: on ropsten, the BadgeReg = 0xcF5A62987294fd2087252FD812443508528C52bF

![image](https://user-images.githubusercontent.com/738724/30521747-d66f942c-9bc4-11e7-9a42-de298d616703.png)

**Comment by 5chdn** [comment]
For future reference: All registries used by the wallet can be found in the JS console.

    [lookupAddress] dappreg: 0xD36d48C274af1a169857C9721e122aa023A0eE01
    [lookupAddress] signaturereg: 0x61792B7bB39b2C359660Ed1082154c1daf7fc96a
    [lookupAddress] tokenreg: 0x04a4FA2AdABbDbE6910A3222BfE73Eab472ec9E2
    [lookupAddress] githubhint: 0xFf73370Ff5AF5B3A1D5B97a7E368392fD7457429
    [lookupAddress] badgereg: 0x4154A2671b7474883286a4493B97848f116395C6

^ Kovan

**Comment by 5chdn** [comment]
The following issues are probably related:

- #6636 all tokens no longer show up
- #6549 new registered tokens do not show up
- #6534 badges are gone after browser refresh
- #6518 all badges no longer show up

In addition, tokens like GavCoin are totally malformed in the wallet, missing TLA and icon, and decimal places are ignored.

I marked these issues with highest priority as this needs to be fixed before the DOTs allocation and to distribute PICOPS badges.

If possible, this should go into 1.7.3 to enable beta users with proper badges and token balances again.

**Comment by chevdor** [comment]
I am closing this one since the token issues are now fixed and #6534 is there and describes the issue better.
