### ISSUE TITLE
Gas calculation wrong/skipped at first run

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6526]
> I'm running:
>
> - **Parity version**: master
> - **Operating system**: MacOS & Linux
> - **And installed**: from source

It seems that parity calulcates wrong (or not) when executing the first tx after a new install on a new system. I usually see 21000 no matter what. Helping on the first, things seem to resolve with the next txs.

---

**Comment by 5chdn** [comment]
That's in the wallet (UI) isn't it?

**Comment by chevdor** [comment]
Yep

**Comment by 5chdn** [comment]
Please check if this happens with the new UI, too.
