### ISSUE TITLE
 After loading Root Certs, loaded==false: NSS error code: -8018

### ISSUE THREAD

**Issue by ItsmeJulian** [paritytech/parity#6530]
![pa](https://user-images.githubusercontent.com/16867291/30521705-688facee-9bc4-11e7-909f-bed8ec8b54c1.png)
i installed via bash <(curl https://get.parity.io -Lk) on
chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.8 (64-bit), **no extension** **EDIT**

installed build dependencies and are up to date
then i start parity with parity ui
Starting Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0

Created new window in existing browser session.

and it crashes, <1s after it showed the screenshot with:
ah snap sth wen wrong, then in chromium dev tool console:
```
The Content-Security-Policy directive 'worker-src' is implemented behind a flag which is currently disabled.
http://127.0.0.1:8180/#/auth?token=foobar:1 The Content-Security-Policy directive 'worker-src' is implemented behind a flag which is currently disabled.
index.e9b5956b9a.js:1 Ledger:checkJSSupport false
index.e9b5956b9a.js:1 SW is setup
index.e9b5956b9a.js:1 [checkUpgrade] available: null version: 
Object {major: 1, minor: 7, patch: 0}
 consensusCapability: unknown
index.e9b5956b9a.js:1 registry at 0xfoobar, code 0xfoobar, version 2
index.e9b5956b9a.js:1 [lookupAddress] dappreg: 0x0000000000000000000000000000000000000000
index.e9b5956b9a.js:1 [lookupAddress] signaturereg: 0x0000000000000000000000000000000000000000
index.e9b5956b9a.js:1 [lookupAddress] tokenreg: 0x0000000000000000000000000000000000000000
index.e9b5956b9a.js:1 [lookupAddress] githubhint: 0x0000000000000000000000000000000000000000
index.e9b5956b9a.js:1 [lookupAddress] badgereg: 0x0000000000000000000000000000000000000000
﻿```

Then on terminal:

﻿```
￼Created new window in existing browser session.
[6589:6615:0916/230154.301139:ERROR:nss_util.cc(808)] After loading Root Certs, loaded==false: NSS error code: -8018

﻿```

​parity continues syncing blockchain.
what is wrong?
---

**Comment by 5chdn** [comment]
Do you use the parity chrome extension? Or does this happen without?

cc @tomusdrw

**Comment by tomusdrw** [comment]
The errors/warnings you see are unrelated to the issue (and not even related to Parity at all). My guess is that the browser does a lot of work right after it's started (#6387) and it causes Chrome to kill it. Most likely fixed in 1.7.2

**Comment by 5chdn** [comment]
Parity 1.7.2 will be released today, please report back if this still persists with the new version.

**Comment by ItsmeJulian** [comment]
built from source  :
Starting Parity/v1.8.0-unstable-9196c72-20170918/x86_64-linux-gnu/rustc1.19.0

same error:

```
Created new window in existing browser session.
[13134:13160:0918/194030.919894:ERROR:nss_util.cc(808)] After loading Root Certs, loaded==false: NSS error code: -8018
```

parity 1.6 worked fine until i clicked update in the bottom bar. Then removed all installed new ( then openend issue), now built new version from source, same behaviour. Could y at least give me pointers, what is the error code etc?

**Comment by 5chdn** [comment]
That's not a parity log but a browser log.

**Comment by ItsmeJulian** [comment]
**chromium Version 57.0.2987.98 Built  bug confirmed**

**Comment by Mitteau** [comment]
Same problem with GpsTab of bitcraze/crazyflie-clients/python in gitHub repository...
What can I do?
Jean-Claude

**Comment by 5chdn** [comment]
@Mitteau not sure, this is the Parity bug tracker.
