### ISSUE TITLE
Badges do not survive browser refresh

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6534]
> I'm running:
>
> - **Parity version**: master
> - **Operating system**: MacOS
> - **And installed**: from source
> - **And Browser**: Chrome

See also #6518.

I am using a badge known as working (Oprah2).
After certification (calling the certify() function of the badge contract), I wait for the event to fire.
At that point, the badge appears in Parity without any user action.

If the user refreshes the page, the badges are no longer displayed... ever. No refresh, parity restart, etc... make the badge appear again.

The only workaround I found is to revoke() and certify() again. Then the badge shows up again until the next refresh.

**Comment by chevdor** [comment]
This applies to stopping parity, closing the web page and restarting parity.
So the TTL of badges is currently rather short 😢 
I just testing that as well on Fundation.

**Comment by 5chdn** [comment]
Thanks for your report, added this to the long list of annoyances which are not going to be fixed until the new wallet is released. :)

**Comment by chevdor** [comment]
Looking forward to the new wallet then :)

**Comment by 5chdn** [comment]
The following issues are probably related:

- #6636 all tokens no longer show up
- #6549 new registered tokens do not show up
- #6534 badges are gone after browser refresh
- #6518 all badges no longer show up

In addition, tokens like GavCoin are totally malformed in the wallet, missing TLA and icon, and decimal places are ignored.

I marked these issues with highest priority as this needs to be fixed before the DOTs allocation and to distribute PICOPS badges.

If possible, this should go into 1.7.3 to enable beta users with proper badges and token balances again.

**Comment by chevdor** [comment]
The current workaround for anyone having the issue is to keep your parity open and running, do no refresh, revoke your badge, grant the badge again.
Your badge will show up until you close parity. This is of course a poor workaround but allows you validating your Badge until this issue is fixed.

**Comment by 5chdn** [comment]
This is not an acceptable workaround :D

**Comment by chevdor** [comment]
I see improvements 👏 but there is still an issue.
Open an account, you will see the badges, now refresh the page => they are gone.

**Comment by 5chdn** [comment]
are you saying you just pulled latest master and it does not work?

**Comment by chevdor** [comment]
Yes. It works better but there is still the issue I described.

**Comment by 5chdn** [comment]
Did you rebuild the UI too?

**Comment by jacogr** [comment]
It does disappear when on account and then refreshing. Not a P0 issue atm, but an annoyance indeed.

**Comment by 5chdn** [comment]
@chevdor adding you to the list of heros for this night.

**Comment by 5chdn** [comment]
#6730

**Comment by chevdor** [comment]
Thank you @jacogr and @5chdn. I am not judging on Prio, just reporting what I see not working as I think it is easier to fix things when they are fresh. I will test again :)
