### ISSUE TITLE
personal_importRawKey throws method not found

### ISSUE THREAD

**Issue by giacomolicari** [paritytech/parity#6537]
Hi guys,
I'm getting **Method Not Found** error when executing **importRawKey**.

I'm running:
- **Parity version**: Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
- **Operating system**: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-107-generic x86_64
- **And installed**: bash <(curl https://get.parity.io -kL)

Here is the stacktrace:
    self.web3.personal.importRawKey(self.privkey, password)            
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/web3/personal.py", line 31, in importRawKey
    [private_key, passphrase],
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/web3/providers/manager.py", line 51, in request_blocking
    raise ValueError(response["error"])
ValueError: {u'message': u'Method not found', u'code': -32601}

---

**Comment by 5chdn** [comment]
There is no importRawKey in the personal API:

https://github.com/paritytech/parity/wiki/JSONRPC-personal-module

You probably want `parity_newAccountFromSecret`:

https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module#parity_newaccountfromsecret

**Comment by giacomolicari** [comment]
Thanks @5chdn , using parity_newAccountFromSecret works.
