### ISSUE TITLE
Pruning: method and history defaults

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#6544]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Ubuntu 16.04
> - **And installed**: apt-get

No issue here, just a clarification needed.

[Here](https://github.com/paritytech/parity/wiki/Configuring-Parity) it says the default pruning method is "auto" and pruning_history = 64

[Here](https://github.com/paritytech/parity/wiki/FAQ:-Basic-Operations,-Configuration,-and-Synchronization) it says the default method is "fast" and pruning_history = 1200.

The latter doc is only one day older than the former.  Please advise.

**Comment by 5chdn** [comment]
> "auto" and pruning_history = 64

This is the default. Will update the docs.

    --pruning METHOD               Configure pruning of the state/storage trie. METHOD
                                   may be one of auto, archive, fast:
                                   archive - keep all state trie data. No pruning.
                                   fast - maintain journal overlay. Fast but 50MB used.
                                   auto - use the method most recently synced or
                                   default to fast if none synced (default: auto).
    --pruning-history NUM          Set a minimum number of recent states to keep when pruning
                                   is active. (default: 64).
    --pruning-memory MB            The ideal amount of memory in megabytes to use to store
                                   recent states. As many states as possible will be kept
                                   within this limit, and at least --pruning-history states
                                   will always be kept. (default: 32)

**Comment by 5chdn** [comment]
auto defaults to fast btw if no preset is found.
