### ISSUE TITLE
update failes with homebrew

### ISSUE THREAD

**Issue by zimmerflo8** [paritytech/parity#6545]
# parity --version
    version Parity/v1.6.10-stable-1a5b176-20170721/x86_64-macos/rustc1.18.0

    # brew update
    ==> Upgrading paritytech/paritytech/parity --stable
    ==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.6.10/x86_64-apple-darwin/parity
    ######################################################################## 100.0%
    Error: Empty installation
    Warning: Skipping paritytech/paritytech/parity: most recent version 1.7.2 not installed

how to fix? after that parity has lost it's executable flag.
sorry for language want to stay anonymouse

**Comment by 5chdn** [comment]
You are on the stable channel. Try

    brew install parity --beta

**Comment by zimmerflo8** [comment]
why not update stable channel? beta is beta and is not stable @5chdn

**Comment by 5chdn** [comment]
You already have 1.6.10 installed which is our latest stable.

**Comment by zimmerflo8** [comment]
yes correct, but doing "brew update" I get an error message "Error: Empty installation" (see OP)
no error with --beta version but using stable and running "brew update" I get error
when is it fixed in stable? i dislike beta

**Comment by arkpar** [comment]
@zimmerflo8 try updating homebrew itself with `brew upgrade` this should fix confusing error message, but as @5chdn said you already have the latest stable version installed.
