### ISSUE TITLE
Online installer not working in FRESH Ubuntu 16.04. Nor in any other distro.

### ISSUE THREAD

**Issue by drobsarma** [paritytech/parity#6548]
Hello. I Love Parity. 
But since 10 hours nobody is installing parity any longer via the online installerlllll.
Actually i hardly believe any non developer can install parity on ubuntu since the .deb package has not worked, ever.
Thanks, its amazing software, and i hope for online installers archive with older versions.
And i really need an online installer of the previous version

Here is the issue after running the bash command:

basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install: 

i made github reg just to write this as i urgently need my parity..
Thank you.

**Comment by ddorgan** [comment]
Can you please re-try now...

**Comment by drobsarma** [comment]
Thank you, it is now working.
 it will be really really great if there are online installers of the previous versions.
Or atleast a fokder wjth bash installers of older versions.
Thanks.

**Comment by 5chdn** [comment]
What's not working with the deb?

**Comment by coinsoncoins** [comment]
not sure if this is related, but i am getting the same error on Mac OS

$ bash <(curl https://get.parity.io -Lk)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0    170      0 --:--:-- --:--:-- --:--:--   257
100  2990  100  2990    0     0   2990      0  0:00:01 --:--:--  0:00:01  2990
Release selected is: beta
Running on Apple
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
sort: invalid option -- V
Try `sort --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install:

**Comment by ddorgan** [comment]
Can you give it a try now.

**Comment by coinsoncoins** [comment]
works now, thanks

**Comment by tjones94** [comment]
I'm having this issue as well.  Ubuntu 16.04.3

"basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install:"

**Comment by ddorgan** [comment]
Tjones, is this still an issue?

**Comment by milankragujevic** [comment]
Can confirm still an issue:

```
milan-MacBookAir Paratii # bash <(curl https://get.parity.io -Lk)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0    426      0 --:--:-- --:--:-- --:--:--   427
100  2990  100  2990    0     0   1446      0  0:00:02  0:00:02 --:--:--  8542
Release selected is: beta
grep: /etc/upstream-release: Is a directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   396  100   396    0     0    747      0 --:--:-- --:--:-- --:--:--   748
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   396  100   396    0     0    900      0 --:--:-- --:--:-- --:--:--   900
basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install: 
milan-MacBookAir Paratii #
```

**Comment by stasbar** [comment]
The same issue here 
```
pi@raspberrypi:~ $ bash <(curl https://get.parity.io -Lk)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     100   170    0   170    0     0    492      0 --:--:-- --:--:-- --:--:--   492
100  5296  100  5296    0     0   6800      0 --:--:-- --:--:-- --:--:--  6800
Release selected is: beta
basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install:
```

**Comment by 5chdn** [comment]
@ddorgan can you check what's breaking `basename`?

**Comment by Melvillian** [comment]
Yes, still an issue

**Comment by ddorgan** [comment]
Yes did some debugging, basename isn't found it the host cannot be resolved or nothing comes back:

e.g. after adding 127.0.0.1 vanity-service.parity.io to /etc/hosts:

```
Release selected is: beta
curl: (7) Failed to connect to vanity-service.parity.io port 443: Connection refused
curl: (7) Failed to connect to vanity-service.parity.io port 443: Connection refused
basename: missing operand
Try 'basename --help' for more information.

```

**Comment by sammy1991106** [comment]
What is the fix for this?

**Comment by folsen** [comment]
@sammy1991106 If it still doesn't work (I thought the fix was the above comment about name resolution), please let us know again what the error message is. If you're just looking for the latest version just head to github.com/paritytech/parity/releases

**Comment by celsoendo** [comment]
Still an issue for me.

OS: Ubuntu 16.04.4

Basename:
```
$ basename --version
basename (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

I can reach the domain `vanity-service.parity.io`:

```
$ ping vanity-service.parity.io
PING vanity-service.parity.io (104.27.133.10) 56(84) bytes of data.
64 bytes from 104.27.133.10: icmp_seq=1 ttl=51 time=0.575 ms
64 bytes from 104.27.133.10: icmp_seq=2 ttl=51 time=0.616 ms
```

Output from one-line installer:

```
$ bash <(curl https://get.parity.io -Lk) -r stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0   1072      0 --:--:-- --:--:-- --:--:--  1075
100  4278  100  4278    0     0  14053      0 --:--:-- --:--:-- --:--:-- 14053
Release selected is: stable
basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install:
```

**Comment by folsen** [comment]
@ddorgan any idea of what could be up here?

**Comment by ddorgan** [comment]
@celsoendo thanks for the update. So all is working ok now? 

@folsen the http response never came back (e.g. there was an issue with the vanity service) so no file names were returned. I'm going to move this service to a better home...

**Comment by celsoendo** [comment]
@ddorgan Yup, everything's good now! Thanks!

**Comment by rohstar** [comment]
Still having this issue: 

`ubuntu@ip-172-17-1-44:~$ bash <(curl https://get.parity.io -L)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0    612      0 --:--:-- --:--:-- --:--:--   611
100  4347  100  4347    0     0   8454      0 --:--:-- --:--:-- --:--:--  8454
Release selected is: beta
basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install:`

**Comment by Genysys** [comment]
Having this issue on on RHEL 7.4. Worked two days ago. :(

**Comment by Genysys** [comment]
> @celsoendo thanks for the update. So all is working ok now?
> 
> @folsen the http response never came back (e.g. there was an issue with the vanity service) so no file names were returned. I'm going to move this service to a better home...

Is this better home down now?

**Comment by celsoendo** [comment]
> > @celsoendo thanks for the update. So all is working ok now?
> > @folsen the http response never came back (e.g. there was an issue with the vanity service) so no file names were returned. I'm going to move this service to a better home...
> 
> Is this better home down now?

I installed 2 days ago and it worked fine
