### ISSUE TITLE
Registered new token but balance still not showing up

### ISSUE THREAD

**Issue by GelatinousFury** [paritytech/parity#6549]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Windows 10
> - **And installed**: Via Installer

A few moments ago I registered the Propy token in the Parity token registry (I had to use PR0 because PRO was already taken...I had no other choice).  I sent my Propy tokens to my Parity wallet last night (tx https://etherscan.io/tx/0x93bd3e6a5e832685ae3d497ccbf58e6601e725f3fd2ffaf1de1d0d506c497760), not knowing that the Propy ICO team had not done this step themselves already.  

So, the Propy token is now registered within the Parity token registry but my Propy tokens I sent last night are still not appearing.  Parity is showing a PR0 balance of 0.000.  Parity is fully sync'ed up.

I added the PR0 token address as the following, which is the Propy token contract address:
0x226bb599a12c826476e3a771454697ea52e9e220

Retrieved from here:
https://etherscan.io/token/0x226bb599a12c826476e3a771454697ea52e9e220

Any help would be appreciated.  I know my Propy tokens are in my Parity wallet because Etherscan tells me they're sitting in my Parity wallet address.

As an additional check, I even added the same Propy token contract address to the "Contracts" section of Parity, then used the "balanceOf" function to query the token balance of my Parity wallet address.  The "balanceOf" function works perfectly and tells me I have a finite amount of Propy tokens sitting in my Parity wallet., but I still can't see them from my Parity "Accounts" wallet page.....I am seriously confused at this point. 

Could it have anything to do with me using PR0 for the token registry instead of PRO?  Another difference I spotted after the fact was that I registered PR0 as having 16 decimal places, but I later saw that the token contract states that there are only 8 decimal places.

Any help would be appreciated.

---

**Comment by 5chdn** [comment]
Can you please check this with 1.7.2 ?

**Comment by GelatinousFury** [comment]
I just installed 1.7.2 but the problem persists.  My Propy balance is still listed as 0.000.  Anything else to try?

**Comment by 5chdn** [comment]
Are you fully synchronized? What's your node status?

**Comment by GelatinousFury** [comment]
Node Health
Chain Synchronized (yes)
Connected Peers (25/25)
Time Synchronized (862 ms):  "Your clock is not in sync.  Detected difference is too big for the protocol to work: 862ms.  Synchronize your clock."

**Comment by 5chdn** [comment]
It's not registered yet, just checked. If tell me the number of decimals I can try it for you.

**Comment by GelatinousFury** [comment]
When you say "it", do you mean the transaction itself?  If so, the transaction amount was exactly 1501.85947999

**Comment by 5chdn** [comment]
No the token in the registry.

**Comment by GelatinousFury** [comment]
That doesn't make sense to me.  This morning I searched the token registry by address, entered in the contract address for the Propy token and it queried the token successfully.

**Comment by GelatinousFury** [comment]
Any updates or other suggestions to get Parity to show these Propy tokens?

**Comment by 5chdn** [comment]
I removed PR0 today, you can go ahead and register it again.

**Comment by 5chdn** [comment]
Someone registered it with 18 decimals, that's why your parity node showed 0.000.

**Comment by GelatinousFury** [comment]
I'm unable to re-register the Propy token.  Parity tells me "This Token address is already registered".

Token address is 0x226bb599a12c826476e3a771454697ea52e9e220

**Comment by 5chdn** [comment]
Probably someone else registered it. Is your balance displayed correctly?

**Comment by GelatinousFury** [comment]
My balance is still not showing up.  Upon further inspection, the Propy token was re-registered as "Pro" but for some reason the decimal places are wrong again.  The decimal places should be 8, but the token registry is telling me someone put the decimal places in as 0.9030899869919435.

You may need to remove Propy from the registry again and register it correctly.  Is this something you can do on your end to make sure it's done right?

Token Address:  0x226bb599a12c826476e3a771454697ea52e9e220
Token Short Name:  Pro (or) PR0
# of decimals:  8
Token Name:  Propy

Thanks for your continued diligence on this issue.

**Comment by 5chdn** [comment]
Can you please share your public account address, you can also PM me on gitter, I want to look into this.

**Comment by GelatinousFury** [comment]
My public address is 0x00af741329ca16Ff38F9230F7f6856c79acF6dF1

Let me know if you need anything else.

**Comment by Fredouh** [comment]
Having the same issue with token XID 0xb110ec7b1dcb8fab8dedbf28f53bc63ea5bedd84

i saw a balance wrong by decimals a while ago. now it is gone again, so i registered it myself, without any result. I see the balanace on etherscan and in BalanceOf function but not in my account, so I can not transfer them

**Comment by AlexanderSupersloth** [comment]
I am also having this problem. I am running Parity//v1.7.2-beta-9f47909-20170918/x86_64-macos/rustc1.19.0 installed via the installer. 

I registered the ChainLink token as LNK (usual name LINK). The token is visible on the token registry. However, I cannot view it in Parity. 

I downgraded to 1.7.0 where the token is viewable. When I upgraded back to 1.7.2, I am once again unable to see the token.

Token address: 0x514910771AF9Ca656af840dff83E8264EcF986CA

https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca

I have shared screenshots with @5chdn of my browser console and address balances which shows no errors. There are also no errors present in my Parity javascript console. I am not running any special configurations. 

I notice that a theme here is that it is Token Registry registrants who are unable to view their tokens. I have deleted the original account that I used to register the token (it was only a temp account). This has not resolved the problem.

**Comment by GelatinousFury** [comment]
In my case, Propy was not registered correctly within the Parity token registry.  So the first thing to do is get it registered correctly in the token registry.

**Comment by AlexanderSupersloth** [comment]
I'm unable to register LINK exactly as it appears, because the registry only accepts symbols of 3 characters in length. LNK was the closest I could get. 

I registered everything else correctly.

**Comment by GelatinousFury** [comment]
I would suggest making a separate thread for your issue, since it's different than mine.

**Comment by AlexanderSupersloth** [comment]
From what I can tell, neither of us are able to see a newly registered token in our accounts. That is the important factor here. 

I don't think the problems during registration are having a meaningful effect one way or another on that core problem. Those differences between our reports are superficial. 

However I can move it if @5chdn thinks the problems are different.

**Comment by GelatinousFury** [comment]
In your case, the LINK token is registered correctly (although named LNK, which is only an annoyance) but you still cannot see your LINK (LNK) balance in your Parity wallet.

In my case, the Propy token is not registered correctly.  The decimal places are wrong in the Parity token registration database, which prevents my Propy balance from being shown in my Parity wallet.

To know if I have the same problem as you, the Propy token has to first be registered correctly in the Parity token registry.  It's possible that after Propy is registered properly I still don't see a balance in my Parity wallet.  At that point we would have the same issue.

**Comment by AlexanderSupersloth** [comment]
I can see your incorrectly registered tokens when I add your address to my address book. They should be showing up in your account as I see them here. I think this is the same problem.

Anyway, I am sure Afri can decide if they're the same. He has the ability to split issues and whatnot. We'll leave it to his trained eye.

![screen shot 2017-09-21 at 16 55 41](https://user-images.githubusercontent.com/24178244/30705601-cb0b6440-9eed-11e7-9467-c3ef5d53ce63.png)

**Comment by GelatinousFury** [comment]
That's very interesting.  I've run both 1.7.0 and 1.7.2 and those Propy tokens do not show up at all for me, as you're seeing them.  We may be experiencing the same issue after all, then.

**Comment by GelatinousFury** [comment]
Interestingly, here's what I'm seeing on my screen at the moment.  As you can see, although the token registry for "PR0" was deleted, Parity never updated for me.  It's still showing PR0 as well as a balance of 0.000.  Since then, a new version (Pro) was registered, but Parity is not recognizing it (I believe because the decimal places are wrong.  That token registry entry needs to be deleted as well by 5chdn).
![parity screenshot](https://user-images.githubusercontent.com/32066600/30724845-4ca31288-9f06-11e7-940a-f3d89a7a67fa.PNG)

**Comment by GelatinousFury** [comment]
UPDATE:

Out of curiosity, I just reinstalled Parity 1.7.0.  Parity now actually shows me my Pro tokens, but the balance is completely wrong since the number of decimals in the token registry is wrong.  This should be corrected to the correct 8 decimal places.  Here's what I'm seeing now:

![parity 2](https://user-images.githubusercontent.com/32066600/30724966-ebac6802-9f06-11e7-8d3c-2a0e03d439bc.PNG)

**Comment by GelatinousFury** [comment]
5chdn, are you able to change the number of Propy decimals in the token registry to 8?  

I'm guessing that's why my balance is showing up wrong.

**Comment by 5chdn** [comment]
I already removed PR0, please, make sure you register it with the correct number of decimals.

**Comment by GelatinousFury** [comment]
@5chdn Yes, but someone re-registered it under "Pro".  That registry needs to be deleted before I can re-register the Propy contract with the correct number of decimal places.  Thanks in advance.

**Comment by GelatinousFury** [comment]
I checked the token registry again this morning but Pro still has not been deleted yet (contract 
 0x226bb599a12c826476e3a771454697ea52e9e220).  Please remove this token from the registry so I can re-register it correctly.

Thanks in advance.

**Comment by ignus2** [comment]
I also had problems with just-registered tokens' balance not showing up. For me it was some browser caching issue. Using a different browser and connecting to parity with a new security token (see "parity signer new-token") the token balance did show up correctly.
So going back and deleting the cookies for 127.0.0.1 in my original browser and re-connecting to parity made the token balance show up there too.
Hope this helps some.

**Comment by AlexanderSupersloth** [comment]
This fix worked for me. 

The first time I tried it, nothing happened. Then I restarted my browser and the Parity app, and now my tokens are showing.

Thank you, @ignus2!

**Comment by GelatinousFury** [comment]
FINALLY, after re-registering the Propy token (PR0) in the Parity Token Registry, and also deleting my browser cookies, my Propy balance is correctly showing in Parity 1.7.2.

Thanks for all the help!

**Comment by 5chdn** [comment]
The following issues are probably related:

- #6636 all tokens no longer show up
- #6549 new registered tokens do not show up
- #6534 badges are gone after browser refresh
- #6518 all badges no longer show up

In addition, tokens like GavCoin are totally malformed in the wallet, missing TLA and icon, and decimal places are ignored.

I marked these issues with highest priority as this needs to be fixed before the DOTs allocation and to distribute PICOPS badges.

If possible, this should go into 1.7.3 to enable beta users with proper badges and token balances again.

**Comment by cyrilclaire** [comment]
Hello Everybody,

I transferred 2 Eth from Coinbase to Parity and it is not showing
Apparently, it is because the chain isn't synchronized.
But it is... The clock isn't synchronized 

Apparently I am on the 1.7.2 version, I don' know if it is the reason. I've tried to execute the version 1.8 but nothing changed. 

I am as well waiting for another token from a recent ICO and nothing is shown neither

I hope you can help me out

Thanks

**Comment by kirushik** [comment]
@cyrilclaire Can you please open a new issue and give us some more specifics there? We'll try to triage your problem and give you some advice there.

This bug is already closed, and I'm not even sure that the things you're describing is even the same issue...
