### ISSUE TITLE
Wrong number of decimals for Propy token

### ISSUE THREAD

**Issue by nandod** [paritytech/parity#6554]
I'm running:

- **Parity version**: 1.7.2
- **Operating system**: Windows
- **And installed**: via installer

Propy tokens (PR0, please mind the zero) are registered in the token registry with the wrong number of decimals (18 instead of 8), thus the balance in Parity is displayed incorrectly.
The contract is located at 0x226bb599a12C826476e3A771454697EA52E9E220.

I have WATCHed the contract in the hope that it would take precedence over the token registry app, but unfortunately it doesn't (it appears that Parity only uses the original/vanilla version of the ERC20 ABI, which lacks the decimals symbol).

**Comment by 5chdn** [comment]
Removed it.
