### ISSUE TITLE
Malwarebytes blocking port and IP's

### ISSUE THREAD

**Issue by CyberShivago** [paritytech/parity#6567]
> I'm running:
>
> - **Parity version**: 1.7.0 beta
> - **Operating system**: Windows 
> - **And installed**: via installer 

I run Malwarebytes 3.2.2.2018 & nothing else on my PC (basically fresh install) besides Antivirus, Anti-keylogging, FW. No web surfing done, no cookies, scanned  and fresh. PC is in DMZ and can not speak to the rest of my network.

Sometimes I see a popup, blocking a specific IP and Port called by Parity.exe.

ex:
178.62.219.246 port 58079
178.62.219.246 port 63697
93.170.123.197 port 55352

1. Why?  Are these really malicious,  or actually false positives on a fresh machine with a fresh OS?

2. Is there a formal IP/PORT list that is updated regularly or even running live, that shows what IP and Ports are verified as clean and permitted?  That way I can exclude these false positives that keep coming up.

3. Are there actually bad actors pretending to be Ethereum nodes?  Is this a big concern?

Thanks!
---

**Comment by CyberShivago** [comment]
I found an answer to this in Stack Exchange, can someone confirm this is true and I should unblock all outbound access from Parity?:

_______________________
You can think of the Ethereum blockchain as a big file or database that is constantly being updated. When you use a web browser like Chromium to download a file, the file comes from a single (centralized) provider (though they may have several servers that actually satisfy the request). There is no single canonical information provider for Ethereum which contribute to its decentralized nature. Instead, Ethereum uses peer-to-peer (P2P) technology as found in software like Bittorrent (or, more specifically, the P2P flavour used in Kademlia). This means you are constantly exchanging parts of the blockchain with strangers on the Internet to stay up to date. Since each Ethereum node is both a consumer and sharer of the blockchain, there is no need to have a special hosting service for Ethereum: everyone contributes their up and down bandwidth to cooperate to keep the network healthy.

The strangers come from different places and hence have different Internet Protocol (IP) addresses. They might also be behind firewalls or routers that prevent direct connection, so the port number also varies. Thus, in order for your Ethereum node software, Parity, to exchange parts of the blockchain, it needs to connect to different IP addresses and ports. This is expected behaviour. If you let your firewall software block Parity, it will be unable to download the blockchain and you be isolated from the Ethereum network. This means your node will be unable to receive the latest blocks nor will you be able to post transactions through Parity. You should make Parity an exception and allow it through your firewall if you intend on using it in the normal way.

https://ethereum.stackexchange.com/questions/21474/parity-connecting-on-random-outbound-ports-to-ips-and-being-blocked-by-malware-b

**Comment by 5chdn** [comment]
> Why?

Parity is a peer in a peer-to-peer network. It connects to other nodes directly.

> Is there a formal IP/PORT list

No.

> Is this a big concern?

No :)
