### ISSUE TITLE
UTC Stage 1 block verification failed

### ISSUE THREAD

**Issue by aas312** [paritytech/parity#6568]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.6.8,1.7.2
> - **Operating system**: Ubuntu
> - **And installed**: https://github.com/dstarcev/parity-poa-playground

I am running the https://github.com/dstarcev/parity-poa-playground.  On member0 I get the error UTC Stage 1 block verification failed
I have checked time.is and my time is exact.
Block numbers on authority0, 1, and 2 are same
Block numbers on member0, 1 and 2 are same
But blocknumbers on member nodes are different than on authority nodes

---

**Comment by 5chdn** [comment]
please report at https://github.com/dstarcev/parity-poa-playground

or follow our demo poa tutorial https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial

**Comment by aas312** [comment]
I think this is related to the parity docker image and not with the parity-poa-playground.

**Comment by 5chdn** [comment]
Please share the full logs please.

**Comment by aas312** [comment]
[logs.txt](https://github.com/paritytech/parity/files/1324556/logs.txt)

**Comment by aas312** [comment]
![screenshot from 2017-09-22 08-47-50](https://user-images.githubusercontent.com/26353423/30745068-c655d824-9f72-11e7-867d-5e5bfc635363.png)

**Comment by aas312** [comment]
![screenshot from 2017-09-22 08-49-04](https://user-images.githubusercontent.com/26353423/30745108-f0f21a16-9f72-11e7-813f-11ec0992ad2f.png)

**Comment by aas312** [comment]
So I deleted the volumes which had the db data.  After that it works.

**Comment by artjoma** [comment]
Parity 1.7.0 POA
Same problem :
2017-09-28 17:03:32  Stage 1 block verification failed for 6a96…e8af: Block(DifficultyOutOfBounds(OutOfBounds { min: None, max: Some(340282366920938463463374607431768211455), found: 340282366920938463463374607431768211456 }))

**Comment by 5chdn** [comment]
this happens if two validator nodes are using the same key to author blocks.

**Comment by jackieWhn** [comment]
@5chdn, i got this problem too. I use parity 1.7.8, two validator nodes, and each node has its own validator.

**Comment by jackieWhn** [comment]
@5chdn what do you mean the same key?

**Comment by 5chdn** [comment]
please share how you run both nodes here
