### ISSUE TITLE
Spammy Pop-up Warning

### ISSUE THREAD

**Issue by jeffanthony** [paritytech/parity#6571]
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Linux
> - **And installed**: via installer

Upon fresh install, warp sync complete and initial wallet creation the window which states "Your node is still syncing, the values you see might be outdated. Wait until it is fully synced." displays and disappears too quickly to check the box and then click 'I understand' when the node is on the last block and appears to happen each time it is behind by one block.

An annoyance because the window comes up every 20 seconds or so.

**Comment by MaxXor** [comment]
Noticed this too, the warning popup should stay visible for at least 5sec so you get the chance to check `Do not show again`.

**Comment by 5chdn** [comment]
@tomusdrw could you check that?

**Comment by tomusdrw** [comment]
Sure. Probably caused by switching to pub/sub, it now fires the notifcations too often. The UI should debounce triggering of the action.
