### ISSUE TITLE
Parity repeatedly crashes after watching multisig created before Byzantium hf

### ISSUE THREAD

**Issue by ethdevrook** [paritytech/parity#6577]
[Report.txt](https://github.com/paritytech/parity/files/1326719/Report.txt)

> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Windows 10
> - **And installed**: via installer

I had parity v1.7 and installed https://github.com/paritytech/parity/releases/tag/v1.7.2

I deleted my \AppData\Local\Parity\Ethereum\chains\test folder.

Re-synced the entire blockchain to the current 173**** block.

Added my wallet created before the byzantium hf.

As soon as i add my multisig wallet to be watched ( created before byzantium hf) parity crashes. Relaunching parity will immediately crash.

Exact issue occurs on a fresh install on mac os as well. 

The fix is to delete the file address_book.json from the ropsten folder. This removes the multisig account.

Report attached. Any ideas on the potential fix?

**Comment by 5chdn** [comment]
> Report attached. Any ideas on the potential fix?

Can't find the logs, can you attach them again please?

**Comment by debris** [comment]
as there are not enough details to reproduce this issue I am closing it
