### ISSUE TITLE
Still problem with 'your clock is not in sync...'

### ISSUE THREAD

**Issue by crsCR** [paritytech/parity#6578]
V. 1.7.2-beta / Windows 10 64 / installer.

Still problem with this - have tried resynching with time servers, turning off and on, etc. Keep getting 'Your clock is not in sync...'

**Comment by crsCR** [comment]
Actually, seems to have sorted itself after a few hours… See how it goes.

**Comment by 5chdn** [comment]
Can you explain what exactly is happening, what do you mean by _keeps dropping out_?

Are you fully synchronized? How is your Parity configured? What is the difference in actual versus expected behavior?

**Comment by crsCR** [comment]
I keep getting 'your clock is out of sync...' message. Fully synced - have tried with with Parity set to sync continuous and to sleep/wake - same. I'm running the node 24/7 to help the network - I'm getting a message telling me the protocol can't work because of this issue. How serious that actually is, I don't know - but not much point in me wasting electricity if it's not helping.

**Comment by 5chdn** [comment]
You can ignore this warning. As long as you are connected to peers and fully synced with the network, you are fine. Is the status indicator green?

**Comment by crsCR** [comment]
Everything green apart from Time Synchronized.

**Comment by 5chdn** [comment]
What offset does it display (in ms)?

**Comment by crsCR** [comment]
Last time I looked was 900 or so ms.

**Comment by 5chdn** [comment]
Ok, there is nothing you have to worry about.

**Comment by amal** [comment]
Same problem with Parity 1.7.3

```
Your clock is not in sync. Detected difference is too big for the protocol to work: 1120ms. Synchronize your clock.
```

**Comment by 5chdn** [comment]
@amal see #6684

**Comment by ltfschoen** [comment]
I've always had that 'your clock is not in sync' message, even if everything else is green.
It just shows the message but doesn't provide a link with any guidance on how a user would go about resolving the issue.
I'm using Parity v1.8.9-stable. See attached screenshot:
![screen shot 2018-02-08 at 7 32 54 am](https://user-images.githubusercontent.com/6226175/35940163-5ddf7bcc-0ca2-11e8-92d1-b2b84b5621f2.png)
