### ISSUE TITLE
Rename "Gas" to "Gas limit"in UI

### ISSUE THREAD

**Issue by bitxchg** [paritytech/parity#6579]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**:v1.7.2-beta-9f47909-20170918
> - **Operating system**:  Linux
> - **And installed**: via installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

Is it possible to rename the field "gas" to "Gas limit" in the UI when sending transaction?
Right now It's really confusing what's field is what

Also  "gas" and "price"  are in different units? If yes it would be useful to specify which ones
Right now: 
gas (estimated: 21000)
price (current 21,000,000,000)
In Metamask these fields are much more obvious

**Comment by 5chdn** [comment]
> Also "gas" and "price" are in different units?

What different units? Unit for gas is `1` ("1 unit of gas") and for price is `wei` ("1 wei").

"gas, estimated: 21000" is twenty-one thousand units of gas. "price, current: 21000000000" is twenty-one giga-wei. 

What do you propose?

**Comment by rphmeier** [comment]
I don't think transaction gas should be conflated with the block gas limit. Maybe "gas provided"?

**Comment by tomusdrw** [comment]
`gas limit` is actually quite common. I think it would be best to just put additional explanations to those fields and change the default unit for `gas price` to `gwei`.
Something for UI2 though.

**Comment by rphmeier** [comment]
Although transaction gas is commonly referred to as gas limit, it's only loosely correct and confusing because gas limit usually refers to the block gas limit.

Default unit of GWei makes sense, but it should be manipulable at a 0.1 granularity easily. Often gas prices in the 1-2GWei range are more than enough

**Comment by 5chdn** [comment]
Added to UI-2 checklist. https://github.com/paritytech/parity-long-term-issues/issues/1
