### ISSUE TITLE
Unable to adjust gas price with limited funds in account.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6583]
> I'm running:
>
> - **Parity version**: Parity//v1.7.0-beta-5f2cabd-20170727/x86_64-windows-msvc/rustc1.18.0
> - **Operating system**: Windows 10
> - **And installed**: via installer

---

I have an account that has a small amount of ETH in it, enough to submit 1-2 transactions with low gasprice (1-4 nanoeth).  When attempting to transact, Parity blocks me from moving forward with the error
> the transaction total is higher than the available balance

This error appears _before_ I get a chance to adjust the gas price and checking the `advanced sending options` box does not let me move forward (Next button is greyed out).  The problem here is that Parity is assuming that I will use its default gas price (20 nanoeth) for the transaction and I do not have enough ETH available for such a transaction.

My expectation would be that such a failure would happen _after_ I am given the option to adjust the gas price.

**Comment by 5chdn** [comment]
Yeah I also noticed this recently. :)

**Comment by 5chdn** [comment]
Added this to the UI-2 checklist. https://github.com/paritytech/parity-long-term-issues/issues/1
