### ISSUE TITLE
Make wiki community editable

### ISSUE THREAD

**Issue by HaleTom** [paritytech/parity#6585]
I want to update the [parity with mist wiki page](https://github.com/paritytech/parity/wiki/Using-Parity-with-Mist) with how to put the equivalent of `--geth` in the config file as it [was not obvious to me](https://github.com/paritytech/parity/issues/6580) how to do it.

I'd be happy to make this edit online.

In gitter, @AyushyaChitransh suggested using https://docs.readthedocs.io.

Any chance of having the Wiki community editable?

**Comment by AyushyaChitransh** [comment]
I think keeping documentation content in a separate repository would

 - Ease out mapping docs to the releases
 - Encourage user to suggest edits and improvements
 - Easily add and verify new content from other community members.

+1 for https://docs.readthedocs.io

**Comment by 5chdn** [comment]
Note to self http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

https://github.com/5chdn/parity-docs

**Comment by 5chdn** [comment]
Wiki migrated to: https://paritytech.github.io/wiki/

Submit your pull requests here: https://github.com/paritytech/wiki
