### ISSUE TITLE
Geth and parity disagree on correct gasUsed of mined block

### ISSUE THREAD

**Issue by edevil** [paritytech/parity#6587]
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Linux
> - **And installed**: via binaries

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

I have a testnet with several geth nodes, which are mining, and a parity node which is not mining. This has been running fine for some months but yesterday the parity node stopped syncing the block chain due to a disagreement with the gasValue of a mined block:

```
2017-09-24 22:27:10 UTC Stage 5 block verification failed for #415756 (79ff…3b70)
Error: Block(InvalidGasUsed(Mismatch { expected: 10944, found: 13444 }))
```

The block in question:
```
> eth.getBlock(415756, true)
{
  difficulty: 1673216,
  extraData: "0xd783010600846765746887676f312e382e31856c696e7578",
  gasLimit: 4712388,
  gasUsed: 10944,
  hash: "0x79ff4377b3f696db4da1985c2957df22fbe93cb7fdb65ddc1296ce01339c3b70",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0xad94486b5005418dbb46a77eb2fd0c8046bfb858",
  mixHash: "0x1a23c9443c078ba33254dbabfc2677e4dfdb662e4214859a5fd04e89fe638068",
  nonce: "0x2b04e0bf595fc478",
  number: 415756,
  parentHash: "0xde4d58060904a8645166054774be170b2bcd4b078f6c3431fc2b7334710cc748",
  receiptsRoot: "0x8832cf7e048b0fd4d9aa0097d631c07fb8b77064f9e74095d89cf8625fde9245",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 651,
  stateRoot: "0x4ace268313b6ad86e290f1984e0882ede0043b5c85b63c73984b9ac06078f20b",
  timestamp: 1506261859,
  totalDifficulty: 450539221396,
  transactions: [{
      blockHash: "0x79ff4377b3f696db4da1985c2957df22fbe93cb7fdb65ddc1296ce01339c3b70",
      blockNumber: 415756,
      from: "0x6509389cdf535b4652036daf63df63b488e385ce",
      gas: 32830,
      gasPrice: 21000000000,
      hash: "0x2a239cd3dcbd6d9dccf6b1d48e5cd7b6e590072383f2d2e5f1358ff23a26cd1a",
      input: "0x41c0e1b5",
      nonce: 5,
      r: "0x529f9fe89d8f5c67d592b1eeee2d3d52741d0ab2020a9ba9efc8b3594b41df47",
      s: "0x9ce1b67014e6bcb9b05b12f39a444ec0f9d1a33a659acf2ad4964650737ab20",
      to: "0x977069a679a60cc9981ce569cfb8b7ab707b2023",
      transactionIndex: 0,
      v: "0x50eaf88",
      value: 0
  }],
  transactionsRoot: "0xe6db10e0f4998ef8c26ae4a07e4a10ed12cc3f84e293606457a107ac209c7612",
  uncles: []
}
```

Geth 1.6.x genesis block:
```
{
  "alloc": {
    "ad94486b5005418dbb46a77eb2fd0c8046bfb858": {
      "balance": "1000000000000000000000000000000"
    }
  },
  "config": {
    "homesteadBlock": 0,
    "chainID": 42424242,
    "eip155Block": 0,
    "eip158Block": 0
  },
  "nonce": "0x0000000000000042",
  "difficulty": "0x6666",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
  "gasLimit": "0x4c4b40"
}
```

Parity chain configuration:
```
{
  "name": "GethTranslation",
  "engine": {
    "Ethash": {
      "params": {
        "gasLimitBoundDivisor": "0x400",
        "minimumDifficulty": "0x20000",
        "difficultyBoundDivisor": "0x800",
        "durationLimit": "0xd",
        "blockReward": "0x4563918244F40000",
        "registrar": "0x81a4b044831c4f12ba601adb9274516939e9b8a2",
        "homesteadTransition": 0,
        "eip150Transition": 0,
        "eip155Transition": 0,
        "eip160Transition": 0,
        "eip161abcTransition": 0,
        "eip161dTransition": 0
      }
    }
  },
  "params": {
    "accountStartNonce": "0x0",
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID": 42424242,
    "eip98Transition": 9223372036854775807
  },
  "genesis": {
    "seal": {
      "ethereum": {
        "nonce": "0x0000000000000042",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    "difficulty": "0x6666",
    "author": "0x0000000000000000000000000000000000000000",
    "timestamp": "0x00",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
    "gasLimit": "0x4c4b40"
  },
  "accounts": {
    "ad94486b5005418dbb46a77eb2fd0c8046bfb858": {
      "balance": "1000000000000000000000000000000"
    }
  }
}
```

I have also tried altering the parity param "eip150Transition" to "9223372036854775807" and the gas calculation is affected, but it still does not match:
```
Error: Block(InvalidGasUsed(Mismatch { expected: 10944, found: 10794 }))
```

**Comment by 5chdn** [comment]
I'm running out of ideas for that one, what we tried so far:

- disable the eip150 transition
- disable the eip160 transision
- disable the eip161 transision
- disable the eip161abc transision
- add builtin solidity contracts 0x1 - 0x4

If starting a new chain is not an option, I do not know how to dive into that further.

**Comment by edevil** [comment]
Yeah, I've also ran out of ideas. If I can provide more information please say so.

For now I'll just mandate that every node has to run Geth, parity is not supported.

Thanks for the help anyway.

**Comment by 5chdn** [comment]
For future reference, I would advise to base new shared networks on something close to the ropsten genesis/chainspec:

- https://github.com/5chdn/crossclient-chainspec
- https://ethereum.stackexchange.com/questions/16866/geth-not-connecting-to-private-network/25640#25640
- https://dev.to/5chdn/solving-the-problem-with-ethereum-cross-client-private-networks

**Comment by DanielSel** [comment]
@5chdn For our private network I used EXACTLY the ropsten genesis/chainspec (except for the network ID) and we just hit he same error:

Stage 5 block verification failed for #10816 (2cfaâ¦281a)
Error: Block(InvalidGasUsed(Mismatch { expected: 10909, found: 13409 }))

Any update on the resolution of this?

Thanks!

**Comment by DanielSel** [comment]
More info: From Geth the two blocks look like this:

`> eth.getBlock(10815)
{
  difficulty: 3227819,
  extraData: "0xd683010702846765746885676f312e398664617277696e",
  gasLimit: 4712388,
  gasUsed: 0,
  hash: "0x115d4d249d5dfa6d4c4986a8a1c9c59b39c44d0e6a24cf775d84d199d3dd5c0c",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x4580a059cc0dd76a431e2cb246814b6b741e7a9b",
  mixHash: "0xc489f61356cc02e646d71a6a7a81c627b0208bde65a05bad6507080340f55b88",
  nonce: "0x37255b14372eb9d1",
  number: 10815,
  parentHash: "0x1dd2317d73e9d74bfefdbb920ce9ee6336dd45fc5378f5c79ceeb188750e6a6f",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x134ba6cd49f176683a94567d6763c00fb6ade187f161f1dd2903c8325bcf9120",
  size: 1071,
  stateRoot: "0xb2f80f8bf548b8714d2611b8f26c9434de6f80894c74d39f38eb1f3caa01c36b",
  timestamp: 1510775737,
  totalDifficulty: 13260641297,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: ["0x913632e431e1a9aa7c2ea1982166bc5e6e1470b573d1917d980e21e24b3167a7"]
}
> eth.getBlock(10816)
{
  difficulty: 3229395,
  extraData: "0xd783010702846765746885676f312e398777696e646f7773",
  gasLimit: 4712388,
  gasUsed: 10909,
  hash: "0x2cfa6cc04dc359cb2a2353510eef1c8cce548f44cf929c877b3ebe7c4db3281a",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x666000733a320d54ebcf66fa38b3e9f25baf4c7b",
  mixHash: "0x6f3e22bf1b7cddef7b5893612434a0f44f4fbb232cf8e6654d66a976871cea51",
  nonce: "0x5eccc93ca9dff31c",
  number: 10816,
  parentHash: "0x115d4d249d5dfa6d4c4986a8a1c9c59b39c44d0e6a24cf775d84d199d3dd5c0c",
  receiptsRoot: "0xd9efaed844ff6f3784265a0dc27af8b976cf0eb8ff36d91764b8ecd77eb03a4a",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 651,
  stateRoot: "0x617b92bf38f06334bdc05b407a5854f5b9fef7fef465a7bfaf0b71fc9b76fd49",
  timestamp: 1510775748,
  totalDifficulty: 13263870692,
  transactions: ["0x4fd58bd23524c9ddaffd93d3c04309dd58dc3a16626acd9b5ab4b7960d01edc9"],
  transactionsRoot: "0x68e1e086eafd62f4904433d45231f85a497539b2f95a6e6923c32e972e2485c7",
  uncles: []
}
`

**Comment by Taces** [comment]
Yesterday we experienced the same problem as Daniel did - even with the exact gas expected and gas found values. I assumed that it is due to some misconfiguration in enabled/disabled EIPs but I tried around with those for 3 hours and couldn't get it working.
