### ISSUE TITLE
default parity.service file allows unclean exit

### ISSUE THREAD

**Issue by AntoniosHadji** [paritytech/parity#6592]
Using the default parity.service file on linux I get the follow log messages after 
`sudo systemctl stop parity.service`

`Sep 25 17:45:09 hadji systemd[1]: Stopping Parity Daemon...  `
`Sep 25 17:45:09 hadji parity[14783]: 2017-09-25 17:45:09  main INFO parity::run  Finishing work, please wait...  `
`Sep 25 17:45:14 hadji parity[14783]: 2017-09-25 17:45:14  IO Worker #0 INFO import  Syncing  #4311484 e9fb…e28d     0 blk/s   `
`Sep 25 17:45:14 hadji parity[14783]: 2017-09-25 17:45:14   WARN jsonrpc_ws_server::session  Error while sending response: WS E  `
`Sep 25 17:45:14 hadji parity[14783]: pure virtual method called  `
`Sep 25 17:45:14 hadji parity[14783]: terminate called without an active exception  `
`Sep 25 17:45:14 hadji systemd[1]: parity.service: Main process exited, code=killed, status=6/ABRT  `
`Sep 25 17:45:14 hadji systemd[1]: Stopped Parity Daemon.  `
`Sep 25 17:45:14 hadji systemd[1]: parity.service: Unit entered failed state.  `
`Sep 25 17:45:14 hadji systemd[1]: parity.service: Failed with result 'signal'.  `

To improve , the main change is that I added 
`KillSignal=SIGHUP` 
in the `[Service]` section.

Here is a link to my current [parity.service](https://gist.github.com/AntoniosHadji/45d379e8dab45bfaf2742f3c0c0b6006)

Now running `sudo systemctl stop parity.service` I see the following when I check status.
`● parity.service - Parity Daemon  `
`   Loaded: loaded (/etc/systemd/system/parity.service; enabled; vendor preset: enabled)  `
`   Active: inactive (dead) since Mon 2017-09-25 19:29:25 EDT; 6s ago  `
` Main PID: 19607 (code=killed, signal=HUP)  `
...
`Sep 25 19:29:25 hadji systemd[1]: Stopping Parity Daemon...  `
`Sep 25 19:29:25 hadji systemd[1]: Stopped Parity Daemon.  `

On restart, the jsonrpc.ipc file had not been removed but it was handled cleanly.  

Should I submit this as a pull request instead?  I wanted to share this information. I don't have a current issue.

I'm running: 
version Parity/v1.7.0-beta-5f2cabd-20170727/x86_64-linux-gnu/rustc1.18.0
on 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
installed via installer

**Comment by 5chdn** [comment]
Feel free to submit a PR, https://github.com/paritytech/parity/blob/master/scripts/parity.service :)
