### ISSUE TITLE
Auto_update flag not working within config.toml file

### ISSUE THREAD

**Issue by noswald** [paritytech/parity#6594]
I'm running:
**Parity version**: 1.7.0
**Operating system**:  Linux
**And installed**: via installer or source (can't remember which)

I recently noticed that parity was not auto updating on my machine, even after using the config.toml file, as outlined here: https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options

The config.toml file has the following lines:

    [parity]
    # Auto-updates to every release.
    auto_update = "all"

Is this a known issue? What is the recommended fix to enable auto_updates?

**Comment by 5chdn** [comment]
Can reproduce with `--auto-update all --release-track beta` on 1.6.10

**Comment by tomusdrw** [comment]
Is it a Parity issue or the new release was just not pushed to the contract?

**Comment by 5chdn** [comment]
Probably not pushed. Where is the contract?

**Comment by debris** [comment]
we've investigated this issue with @arkpar . It has been fixed in `1.7.7` and in `1.8.0`. Master will be fixed once #6742 is merged
