### ISSUE TITLE
Error when I set websockets section on Windows

### ISSUE THREAD

**Issue by KimiWu123** [paritytech/parity#6601]
version: v1.6.10-stable-1a5b176-20170721
platform: Windows 10

I set the following in my config file as wiki suggested

    [websockets]
    disable = false
    port = 8546
    interface = "192.168.1.103"
    apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]

but I execute parity --config node.ini, it shows 

    You have some extra fields in your config file:
    [websockets]
    disable = false
    port = 8546
    interface = "192.168.1.103"
    apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]

If I remove [websockets] section, it works well. If I copy node.ini (with websockets section) to my my Ubuntu machine, it also works, too.

Any limitations or different wordings on Windows platform? 

Thanks.

**Comment by 5chdn** [comment]
The wiki describes 1.7.x beta :)

Websockets are not available in 1.6.10 stable, please upgrade :)
