### ISSUE TITLE
Allow community editing of wiki

### ISSUE THREAD

**Issue by HaleTom** [paritytech/parity#6603]
I would like to update the page:

https://github.com/paritytech/parity/wiki/FAQ:-Backup,-Restore,-and-Files

To say to stop parity before removing the database.

Could the wiki be community editable?

What about using https://readthedocs.org/ ?

**Comment by 5chdn** [comment]
Duplicate of #6585

**Comment by 5chdn** [comment]
Working on something. Stay tuned.

**Comment by HaleTom** [comment]
@5chdn Sorry, my workflow on this sucked to not catch that issue already raised!!

Thanks!

**Comment by 5chdn** [comment]
Meanwhile just write here what you want to add to the wiki, I can pass this through.

**Comment by HaleTom** [comment]
The change would be to add:

`Stop parity, then`

before the text `[E]xecute parity db kill.`

**Comment by 5chdn** [comment]
Updated, thanks
