### ISSUE TITLE
Allow --no-light if `light = true` in configuration

### ISSUE THREAD

**Issue by HaleTom** [paritytech/parity#6604]
> I'm running:
>
> - **Parity version**: version Parity/v1.7.2-beta-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Linux svelte 4.13.3-2-MANJARO #1 SMP PREEMPT Wed Sep 20 15:53:16 UTC 2017 x86_64 GNU/Linux
> - **And installed**: via installer pacman

I have:
```
light = true
```
In my configuration file.

`--warp` has `--no-warp`. Is there a way of disabling light mode from the command line?

```
$ parity --no-light
Unknown flag: '--no-light'
```

**Comment by 5chdn** [comment]
you can just use `--no-config` :)

**Comment by HaleTom** [comment]
@5chdn The problem with that work-around is that I would need to re-specify *every single* option that I have set in my configuration file at the command line.

What about a generic `--no` parameter that sets the following config item to `false`? Eg:

    parity --no light --no geth --no public_node --no force_direct --no fast_unlock ...

I've edited the title to reflect this more generic case and ask that you consider re-opening this issue.

**Comment by 5chdn** [comment]
What prevents you from creating different config files?

**Comment by rphmeier** [comment]
a smart config parser that lets you toggle flags with `--light=on` and `--light=off`, with defaults customizable would solve this issue. clap might be able to do it, but we'd have to break backwards compatibility.

**Comment by HaleTom** [comment]
@5chdn granted, my last example was a bit contrived. I'm currently using `--light` or not, so specifying this (or not) is easier than naming a config file.
