### ISSUE TITLE
improve: current binary download url is not https

### ISSUE THREAD

**Issue by detailyang** [paritytech/parity#6607]
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: MacOS 
> - **And installed**:  binaries

Hello. Now the release url like [http://parity-downloads-mirror.parity.io/v1.7.0/x86_64-unknown-linux-gnu/parity_1.7.0_amd64.deb](http://parity-downloads-mirror.parity.io/v1.7.0/x86_64-unknown-linux-gnu/parity_1.7.0_amd64.deb) looks like forget  enable HTTPS as default. It's potential risk especially in china although we have provided the sha256 checksum.

**Comment by 5chdn** [comment]
Fixed.

**Comment by detailyang** [comment]
Good work:)
