### ISSUE TITLE
Provided Host header is not whitelisted.

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6609]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.0 unstable
> - **Operating system**: Linux
> - **And installed**: binary

After setting a reverse proxy to point to my Parity UI and visiting [ip-address]:8180, I get the following error:

Provided Host header is not whitelisted.

I am invoking Parity with --jsonrcp-hosts="all"

This is the result if my Apache2 reverse proxy directive includes "ProxyPreserveHost On" because that tells Parity that the host it is serving on is the public IP not localhost.

If I turn "ProxyPreserveHost Off" then the UI appears and I get this other bug: https://github.com/paritytech/parity/issues/6586  Specifically what happens is that I am asked for a trusted signer token even though --ui-no-validation is added to Parity, and the UI does not accept the token that I create at that moment.

I am starting to wonder if there is a new config option that I don't know about that causes me to have all of these problems.  Because problems are usually my fault.  Did I miss a meeting? :)

**Comment by tomusdrw** [comment]
Please start with `--unsafe-expose` and check if it works. After that you can start to secure your instance by using `--*-hosts` and `--*-interface` options.

**Comment by stone212** [comment]
@5chdn What do you mean?  This is the output from starting Parity:

017-10-01 09:32:14 UTC Starting Parity/v1.8.0-unstable

It is 1.8.0 unstable as I said.  Is there something I don't understand?

I will try these suggestions soon.

**Comment by stone212** [comment]
@tomusdrw I will try this when I can but why would --jsonrcp-hosts="all" not fix the error?  You can see why the error sounds like it would be fixed with --jsonrcp-hosts="all", yes?

**Comment by tomusdrw** [comment]
You most likely need `--ui-hosts=all` not `--jsonrpc-hosts`.

**Comment by stone212** [comment]
@tomusdrw oh of course!  I don't know why I didn't realize that.  It's so obvious when you write those two things next to each other.  Yes, this fixed this problem.  I still have the other bug (https://github.com/paritytech/parity/issues/6586) so I can't use the interface yet but this bug is solved.  Thank you.

**Comment by stone212** [comment]
whoops
