### ISSUE TITLE
unable to start parity

### ISSUE THREAD

**Issue by ydaniels** [paritytech/parity#6614]
Sorry this is it 
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.3
> - **Operating system**:  Linux
> - **And installed**: via installer and binaries 

I have tried all possible setup apart from building , I can't get parity to work on my server Debian x64 wheezy.
I have also installed openssl libssl-dev libudev-dev
But I always get this error 

parity: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory

**Comment by ydaniels** [comment]
Sorry this is it 
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.3
> - **Operating system**:  Linux
> - **And installed**: via installer and binaries 



I have tried all possible setup apart from building , I can't get parity to work on my server Debian x64 wheezy.
I have also installed openssl libssl-dev libudev-dev
But I always get this error 

parity: error while loading shared libraries: libudev.so.1: cannot open shared object file: No such file or directory

**Comment by 5chdn** [comment]
Try installing from source (see README for instructions) if the binary does not work.
