### ISSUE TITLE
What format must have a password file?

### ISSUE THREAD

**Issue by AndreyNag** [paritytech/parity#6615]
> I'm running:
>
> - **Parity version**: v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.19.0
> - **Operating system**: Ubuntu 16.04 Linux
> - **And installed**: via installer

Hi. I try to use parity to local ETC wallet. But can't unlock acc by password file. 
When i start parity i have recieve this message:

    Loading config file from /home/user/parity/config.toml
    You might have supplied invalid parameters in config file.
    invalid type: string "$HOME/.local/share/io.parity.ethereum/ppp", expected a sequence for key 
    `account.password`

What format must have a password file?
Thnx.

**Comment by knarz** [comment]
`echo "mypassword" > passwordfile` should do the trick, i.e. just a simple file containing your password on a single line.

**Comment by 5chdn** [comment]
exactly, a simply text file containing your password.
