### ISSUE TITLE
wallet.parity.io

### ISSUE THREAD

**Issue by wnz99** [paritytech/parity#6619]
I'm running:

**Parity version**: 1.8.0-unstable
**Operating system**: Linux
**And installed**: from source

I set up remote node with nginx proxy.

Is there a way to run my own node as configured on wallet.parity.io, meaning that users are required to create an account on the first visit?

I have searched the wiki and looked into all the possible parameters but really could not figure out how to achieve that.

**Comment by rphmeier** [comment]
Check out the `--public-node` flag.

**Comment by wnz99** [comment]
I did and apparently I can create an account from the accounts tab. However, I am not presented with a Welcome guided page as in https://wallet.parity.io. Is that something custom for your that specific node?

**Comment by tomusdrw** [comment]
Try clearing `localStorage` / running in private mode, maybe `firstRun` is set to `false`, because you visited the same domain in the past.

**Comment by wnz99** [comment]
that worked. Many thanks.
