### ISSUE TITLE
Non-stop pending transactions under signer tab

### ISSUE THREAD

**Issue by dondreytaylor** [paritytech/parity#6622]
> I'm running:
>
> - **Parity version**: 1.7.3
> - **Operating system**: Linux
> - **And installed**: via installer

For some reason I keep getting a flurry of pending transactions coming in. I'm not the one initiating them and even when I reject them all they keep coming back. Has anyone experienced this issue before. I'm connected to the Kovan network and according to Parity I'm at the most current block when this occurs. I've included a screenshot below. 

Here is the command that I'm using to run parity. 

`parity --warp --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 1024 --ui-no-validation --jsonrpc-interface 0.0.0.0   --jsonrpc-cors "*" --jsonrpc-hosts="192.168.1.10"`

Really appreciate if anyone could help.

![screen shot 2017-10-02 at 1 40 58 pm](https://user-images.githubusercontent.com/3202583/31091227-4b4aa732-a778-11e7-8021-388587509948.png)

**Comment by tomusdrw** [comment]
Running with `--jsonrpc-interface 0.0.0.0` exposes your node to outside world. *Anyone* within the same network can access the RPC interface and request some transactions to be sent.

Seems that there is either a python script running on you machine or some other machine in your local network that tries to request those transactions.

Solution: Don't expose the RPC interface to the world or protect yourself with a firewall/ip whitelisting.

**Comment by dondreytaylor** [comment]
Oh wow, you're right @tomusdrw. I had made it open like that in an attempt to connect from an outside IP, but that seemed to be the issue. Changing the jsonrpc interface to the local IP of the machine seemed to work. Thanks for pointing this.

**Comment by techtravis** [comment]
Made this mistake too.   Thanks
