### ISSUE TITLE
First time syncing...taking forever. Makes no sense. 

### ISSUE THREAD

**Issue by ctzjc** [paritytech/parity#6626]
I'm running:
**Parity version**: 1.7.2
**Operating system**: Windows
 **And installed**: via installer

I have been waiting for sync of block chain for over 12 hours now, and it is only 1/2 done.
Tried reinstall. Tried deleting database. Tried starting over and over.
No change, still slow as shit. My connection is 100mbps through my ISP.

What am I doing wrong? 
This is really disgusting if this is "normal" behavior. 

Thank you.

**Comment by rphmeier** [comment]
The bottleneck is block processing, not block download. The blocks at around 2.3 to 2.5 million are extremely heavy due to some DoS attacks at the time and will take a long time to process, especially with an HDD.

**Comment by ctzjc** [comment]
Thats what I read.....that the Ethereum block never recovered. 
Can I ask, will Metropolis effect Parity?
Will it make it faster?

**Comment by rphmeier** [comment]
You should run "parity.exe" with that flag after shutting down the currently running instance of "parity.exe".

Metropolis will only affect the rules for creating new blocks. But it's a blockchain and the new blocks depend on older ones. The old blocks will still be heavy to process.

**Comment by ctzjc** [comment]
ohhhhhhh.....but im afraid to do it because what if I will have to load all over? Or that wont happen? lol...im at 2.5 mil...thats was a lot of time XD

And I understand. So basically these old blocks cannot be purged or discarded at ANY point of the block existence?

**Comment by 5chdn** [comment]
A snapshot sync takes around 30 minutes to get you to the latest head. You don't have to be afraid to start over :)

**Comment by ammar4243** [comment]
But Total Block are Almost 5.7 Million What Should 2.4 Million done in 72 hours but still Incomplete

**Comment by Tbaut** [comment]
@ammar4243 please join the [Gitter channel](https://gitter.im/paritytech/parity) to get help if you have any problem to sync.
