### ISSUE TITLE
Wallet export doesn't show password hint

### ISSUE THREAD

**Issue by tom-seddon** [paritytech/parity#6627]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.19.0 (copied by hand, VirtualBox copy/paste doesn't work for me)
> - **Operating system**: Linux (VirtualBox VM)
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

When using Export Account, parity asks for the account password, but no hint is shown and there's no obvious way to get it.

This applies to export of an individual account (`ACCOUNTS` tab, select account, `EXPORT` button) and bulk export (`ACCOUNTS` tab, `EXPORT` button).

Parity should never prompt for a password without providing a way to access the hint.

Thanks,

--Tom

**Comment by 5chdn** [comment]
Thanks for the report. Will add this to the UI-2 checklist for the next generation wallet we will publish soon. https://github.com/paritytech/parity-long-term-issues/issues/1
