### ISSUE TITLE
Dear Parity,

### ISSUE THREAD

**Issue by gellesrinivas** [paritytech/parity#6628]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity 1.7.2
> - **Operating system**: Windows 
> - **And installed**: via installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am new to Parity and I created an account and transferred ETH from myEthernetwallet.com to Parity. I do not see the balance on my Parity UI.

Below is the transaction.

https://etherscan.io/tx/0xf809e706335bd07fbf0d86d2e867ffa5cab3e9ebdea185d0465ce1bd5d4cd8a9

Please help!!
---

**Comment by 5chdn** [comment]
I see your balance, no worries. You need to wait until your wallet is fully synchronized.
