### ISSUE TITLE
Multiple external IPs

### ISSUE THREAD

**Issue by WyseNynja** [paritytech/parity#6629]
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Linux
> - **And installed**: via binaries

My node is behind a NAT and has both IPv4 and IPv6 addresses. Right now I've set `--nat extip:IPV6:ADDR:HERE::`, but that means I think I'm not announcing my IPv4 address to peers. Does that matter? Is there any way to advertise both IPs?

**Comment by 5chdn** [comment]
Why would they need to use both IPv4 and IPv6 address if IPv4 is available? Nodes do not implement any preference to connect over IPv6 and peer selection is random.

Parity will only listen on IPv6 interface if it is specified in the `listen_address` config option.

**Comment by WyseNynja** [comment]
I'm trying to transition all my systems over to IPv6 but not all of them support it yet. I also have some systems that are IPv6 only. While I wait for AWS to support IPv6, I was hoping to have one of my systems bridge both v4 and v6 so that all my nodes can connect directly.

Is it possible to pass listen_address through the command line? I don't have a file config for this nodes since they are just docker containers. I only see references to listen address in the code and not the docs, but from what I can see, it defaults to "0.0.0.0:30303" which should be all interfaces.

**Comment by 5chdn** [comment]
Actually, it doesn't matter how you configure it, parity is listening on all network devices. If you run a node listening on

    172.16.16.11:30303

and IPv6 is available on the same device, its also available on

    [f8:59:71:1c:e8:14]:30303

You could try to simply wire IPv4-only nodes to

    enode://ac1977d...4ed44b8@172.16.16.11:30303

and IPv6-only nodes to

    enode://ac1977d...4ed44b8@[f8:59:71:1c:e8:14]:30303

Assuming that the node on `172.16.16.11`/`f8:59:71:1c:e8:14` supports both protocol versions.
