### ISSUE TITLE
~/.parity used instead of $XDG_DATA_HOME/io.parity.ethereum

### ISSUE THREAD

**Issue by HaleTom** [paritytech/parity#6634]
I'm running:
>
> - Parity/v1.7.2-beta-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0
> - Linux tara 4.9.47-1-MANJARO #1 SMP PREEMPT Sat Sep 2 07:29:38 UTC 2017 x86_64 GNU/Linux
> - **And installed**: via installer pacman

I run two Manjaro Linux boxen, both updated to the latest packages (it's a rolling release distro).

On one machine, `parity` mentions `~/.local/share/io.parity.ethereum` in its startup for the DB location.

On the other, it mentions `~/.parity`. The only difference I can think of is that on this machine I first ran v1.7.0 before upgrading to 1.7.2. 

---
```
$ parity --version | grep version
  version Parity/v1.7.2-beta-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
$ echo $XDG_DATA_HOME
/home/ravi/.local/share
$ parity
2017-10-04 22:07:45  Starting Parity/v1.7.2-beta-9f47909ed-20170918/x86_64-linux-gnu/rustc1.20.0
2017-10-04 22:07:45  Keys path /home/ravi/.parity/keys/Foundation
2017-10-04 22:07:45  DB path /home/ravi/.parity/chains/ethereum/db/906a34e69aec8c0d
2017-10-04 22:07:45  Path to dapps /home/ravi/.parity/dapps
```
----
Is there some configuration I'm not aware of causing `parity` to look in this location rather than in `$XDG_DATA_HOME/io.parity.ethereum`?

**Comment by HaleTom** [comment]
As a work-around I have:
```
$ ls -l ~/.parity
lrwxrwxrwx 1 ravi ravi 32 Oct  4 01:31 /home/ravi/.parity -> .local/share//io.parity.ethereum
```

**Comment by 5chdn** [comment]
old versions used ~/.parity - nothing wrong with this.
