### ISSUE TITLE
Tokens no longer show up

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6636]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.8.0-unstable-7cc43893d-20170928/x86_64-macos/rustc1.20.0
> - **Operating system**: / MacOS /
> - **And installed**: from source

I no longer see tokens:
- no icon attached to the accounts
- no longer appearing in the list when doing a transfer

Some of the tokens I expect to see are valid ERC-20 that showed up 2 weeks ago.
If I query the balance of contract, I can see that some of my accounts do have a positive balance.

---

**Comment by 5chdn** [comment]
Does this state persist or do the tokens show up after waiting a while?

cc @ngotchac

**Comment by chevdor** [comment]
I cannot say I tested for hours but definitely nothing shows up even after a few minutes.
Neither the icons, nor the tokens in the lists beside Ether.

**Comment by chevdor** [comment]
I just rebuilt, the issue remains but I did an additional test: I see the issue on Kovan and NOT on fundation.

**Comment by chevdor** [comment]
I rebuilt a version from 18.09 (commit 9196c7268abad6c0f0dc872d6c5936ace5d794d8) and my tokens do show up again.

**Comment by 5chdn** [comment]
The following issues are probably related:

- #6636 all tokens no longer show up
- #6549 new registered tokens do not show up
- #6534 badges are gone after browser refresh
- #6518 all badges no longer show up

In addition, tokens like GavCoin are totally malformed in the wallet, missing TLA and icon, and decimal places are ignored.

I marked these issues with highest priority as this needs to be fixed before the DOTs allocation and to distribute PICOPS badges.

If possible, this should go into 1.7.3 to enable beta users with proper badges and token balances again.

**Comment by rphmeier** [comment]
it was caused by changes which are only in master. there isn't anything to backport.

**Comment by chevdor** [comment]
I just rebuilt and I can confirm that I now see many tokens again. Happy we caught it in master.
![image](https://user-images.githubusercontent.com/738724/31234642-bc7395bc-a9ef-11e7-8fcc-0b376a6d3ad4.png)

The last fixes DID some good to the Badges as well. 
#6534/#6518 are still issues but at least now, if a Badge is issued it DOES show up when the event is 'heard'.
