### ISSUE TITLE
Ledger Nano S not detected

### ISSUE THREAD

**Issue by akahncmu** [paritytech/parity#6642]
> I'm running:
>
> - **Parity version**: v1.7.2-beta-9f47909-20170918
> - **Operating system**: Linux 4.10.0-35-generic #39-Ubuntu 17.04  
> - **And installed**: via debian package

Parity does not recognize my Ledger Nano S.  I see the following in the output when I run parity with cmdline args "-l hardware_wallet=trace"

`2017-10-04 21:55:38  hw_wallet TRACE hardware_wallet::ledger  Checking device: HidDeviceInfo { path: "/dev/hidraw5", vendor_id: 11415, product_id: 1, serial_number: Some("0001"), release_number: 512, manufacturer_string: Some("Ledger"), product_string: Some("Nano S"), usage_page: 65535, usage: 65535, interface_number: 0 }`

So, it does see my Ledger nano S.  But then I see this:

` hw_wallet DEBUG hardware_wallet::ledger  Error reading device info: USB communication error: Unable to open hid device`

Am I missing something?

**Comment by 5chdn** [comment]
Is browser support disabled? Have you previously been able to use the device with parity? Or any other vendor (My Ether Wallet, Ledger Wallet)? Did you follow [this guide for Ledger on Linux](http://support.ledgerwallet.com/knowledge_base/topics/ledger-wallet-is-not-recognized-on-linux)?

**Comment by chevdor** [comment]
@5chdn FYI: I tested on master with 223467c81 and the Nano S pops up nicely.

**Comment by akahncmu** [comment]
Got it!  I had to run this script - https://www.ledgerwallet.com/support/add_udev_rules.sh (which I found thanks to @5chdn ) thanks all for the help!
