### ISSUE TITLE
Error (0xc000007b) at starting application after installation 

### ISSUE THREAD

**Issue by bipbippp** [paritytech/parity#6643]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Windows /
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

i install parity via installer and after installation when i tried to start it gives me error unable to start correctly (0xc000007b)

---

**Comment by 5chdn** [comment]
Can you please open a command prompt and 

`cd "C:\Program Files\Parity\Party"`

and run

`parity.exe`

And share the output here?

**Comment by bipbippp** [comment]
https://i.imgur.com/qNcSDXM.png

**Comment by bipbippp** [comment]
i tried few different versions and still that error

**Comment by arkpar** [comment]
@bipbippp Is your windows version 32-bit? Parity only supports 64-bit windows
