### ISSUE TITLE
token deployment application:  link to etherscan.io does not work 

### ISSUE THREAD

**Issue by qjawe** [paritytech/parity#6644]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: MacOS 
> - **And installed**: via installer 

_Your issue description goes here below. Try to include **https://** https// vs. **https://https//** and **go to token deployment and check on the link of any token deployed and you get the error on https://https//  example https://https//etherscan.io/tx/0x06d56c8652778440cad29ee1bb4dbd1b686da1862788382621cb3519aaa5484a ** the issue._

Under the token deployment when clicking on contract details
double entry of https://https// will popup in chrome which did not happen before in 1.7.1

<img width="845" alt="screenshot 2017-10-05 17 14 00" src="https://user-images.githubusercontent.com/16167774/31219694-b6138b86-a9f0-11e7-936c-3e713b79e582.png">

---

**Comment by folsen** [comment]
Closing as UI is moving.
