### ISSUE TITLE
parity clock not syncing while my time is exact

### ISSUE THREAD

**Issue by fidaaayoub** [paritytech/parity#6645]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7
> - **Operating system**:  MacOS 
> - **And installed**: via installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

my clock is exact, but parity showing time not synced

screenshots attached

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/29645094/31222240-87737fac-a9d7-11e7-881a-11bdc72548c3.png">
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/29645094/31222273-a0a7035e-a9d7-11e7-9cd9-3986f64a8aec.png">

---

**Comment by 5chdn** [comment]
That's an ntp warning you can ignore.
