### ISSUE TITLE
Incorrect Chain Synchronized flag

### ISSUE THREAD

**Issue by radek1st** [paritytech/parity#6662]
> I'm running:
>
> - **Parity version**: Parity//v1.7.2-beta-9f47909-20170918/x86_64-macos/rustc1.19.0
> - **Operating system**: MacOS
> - **And installed**: via homebrew
---
This is minor. I'm half way though syncing and when I lost all the peers in the UI I could see `Chain Synchronized (yes)`. I would expect it to be still `no`. It corrected itself when I connected to some peers again.  I didn't manage to get a screenshot, will attempt if it repeats.

**Comment by tomusdrw** [comment]
There is no way to figure out what is the highest block if you are not connected to any peers. The status should show that chain is synchronized, although additional warning regarding no peers should be presented and the general status should still be warning/error.

**Comment by radek1st** [comment]
Yeah, that's what I thought, but I didn't notice any other warnings. Thanks.
