### ISSUE TITLE
An error occurred: Request not found 

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6669]
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Debian 9
> - **And installed**: binaries

I am deploying a test contract while running parity on --chain dev.  I am using Truffle 3.4.11, migrating to the development network (localhost:8545) and this happens:

1 - Truffle command line migration seems successful and says "Saving successful migration to network" as expected.

2 - Parity, as expected, asks me to confirm each transaction with an empty password for the development account.  I do this and each time (the contract actually is broken into many pieces) I see the Parity error saying:

"An error occurred: Request not found"

The error appears as the top, red bar in every box in the bottom right of the UI, where I just accepted each contract.

**So my question is:** what does this error usually mean and how can I debug it?

I have other evidence that the test migration was successful.  The contract is behaving as expected locally via its own api.  That is why I assume this is a Parity error and not truffle, or the contract.

---

**Comment by Vourhey** [comment]
I'm having the same problem. Every transaction seems to be successful, but parity says "an error occurred: request not found"

Parity
  version Parity/v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.19.0

**Comment by stone212** [comment]
I am not having this problem after upgrading to 1.7.6.

**Comment by 5chdn** [comment]
yeah it's fixed in #6725

**Comment by davux** [comment]
@5chdn Can you confirm in which release this was fixed?
