### ISSUE TITLE
gasLimit and minGasLimit same value in wiki?

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6671]
This is related to the files found here:
https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/expanse.json
and here:
https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json

Both of these have the value of 0x1388 for these two variables:

gasLimit
minGasLimit

I am not an expert and I still wish I had documenation that tells me what each of these things do (see other ticket) but can you verify that this is the correct setting?  It just... seems wrong.  If one of them is the Block Gas Limit and one of them is the Gas Transaction limit, then they can't be the same.

Am I crazy?

I have tried sooooooo many things before writing the question, including many questions on StackExchange.  I do not open the issue for trivial reasons.   <-- this is what I say when I expect to receive a simple answer and feel very stupid. :)

**Comment by jdjkelly** [comment]
Seems like @stone212 got an answer to his question here: https://ethereum.stackexchange.com/questions/28486/why-is-block-gas-limit-set-to-5000

@5chdn hypothetically, where would documentation for this kind of thing even go? JSON doesn't support comments, so they can't be in-line, and ultimately the answer here is historical

**Comment by rphmeier** [comment]
one is the gas limit of the genesis block. the other is the _minimum_ allowed gas limit for any block under that chain configuration.

**Comment by stone212** [comment]
@jdjkelly @5chdn

Yes I did get the answer on SE and I forgot to close this here and point to it.  Thank you for doing that.

To answer your question: the documentation would go on this page:
https://github.com/paritytech/parity/wiki/Chain-specification

So it would say something like:

> gasLimit: This parameter *not* refer to the "gasLimit" parameter on Page 4 of the Yellow Paper but sets the default Block Gas Limit for the chain, starting at the genesis block.  (Note that current Block Gas Limit may change from this default over time).

**Comment by rphmeier** [comment]
it is the gasLimit parameter on page 5 of the Yellow Paper.

**Comment by stone212** [comment]
@rphmeier  Then the definition should say that.  Now we have:

> gasLimit: This parameter refers to the *block gas limit*,  referenced as "gasLimit" on Page 5, Paragraph 4.4 of the Yellowpaper where it is defined as "A scalar value equal to the current limit
of gas expenditure per block".  (It is *not* the "gasLimit" parameter on Page 4 of the Yellow Paper as that is the *transaction gas limit*).  It sets the default block gas limit for the chain, starting at the genesis block. (Note that current Block Gas Limit may be higher or lower than this value due to miner voting over time).
