### ISSUE TITLE
Forever loading transactions history on multi-sig

### ISSUE THREAD

**Issue by mirocana** [paritytech/parity#6672]
> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**:  MacOS
> - **And installed**: via installer

I created a new multi-sig wallet and unable to see the transactions. It's loading forever. 

![photo_2017-10-08_20-20-19](https://user-images.githubusercontent.com/20560640/31319102-22371cac-ac66-11e7-8d3a-b920865a4469.jpg)

**Comment by 5chdn** [comment]
implication: does not show pending requests. should be addressed asap.

also affected: transaction lists of normal accounts.
