### ISSUE TITLE
Invalid transaction block number

### ISSUE THREAD

**Issue by ngotchac** [paritytech/parity#6674]
> I'm running:
>
> - **Parity version**: Parity//v1.8.0-unstable-223467c81-20171005/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Linux
> - **And installed**: from source

On Kovan, after sending a transaction that got stuck on my local node (could not get it mined, not sure why), this happens:
![image](https://user-images.githubusercontent.com/2864519/31331950-bb4fde8c-ace4-11e7-8c9c-ecb263113912.png)
It seems (wrongly) that it's included in a block. But on new block, the block number sent back by `eth_getTxByHash` is increasing...

**Comment by rphmeier** [comment]
Workaround: check if `r.blockHash` is null or present

**Comment by ngotchac** [comment]
Yep sure. `eth_transactionReceipt` returns `null` as well. But the main issue is that in the UI it shows the transaction as already included in a block, which is mis-leading

**Comment by folsen** [comment]
Closing as UI is moving.
