### ISSUE TITLE
Account does not display all available (older) transactions

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#6677]
As reported via e-mail.

---

It turns out to me that, after upgrading to Parity v1.7.2, the Transaction history is no longer visible to me. That worked good before upgrading.

Steps:
1. The account history was showing properly this morning, on Parity v1.7.0
2. Then I downloaded and upgraded to latest v1.7.2, Win64
3. After upgrading, I waited some time before blocks synced to latest.
4. the Transaction history becomes invisible. Even after I rebooted my desktop twice. It is still no visible.

---

Additional comments -

Looking at the supplied address, the last transactions are >21 days old. In this case no transactions show up since they are all "older".

Reproducing with an account with recent transactions, only the recent transactions will show up fully, and older transactions (although the hashes are retrieved via Etherscan) are not visible. e.g, in the attached screenshot (Kovan) only the most recent tx shows up in the list although 25 are retrieved to be displayed -

![parity 2017-10-09 13-26-09](https://user-images.githubusercontent.com/1424473/31336075-8d7ad5c8-acf5-11e7-991f-e212b0f19cee.png)

This is on a newly synced warp chain.

**Comment by jacogr** [comment]
List does show up on latest master once warp-sync blocks have caught up.

![parity 2017-10-09 13-56-17](https://user-images.githubusercontent.com/1424473/31336999-aae05756-acf9-11e7-885c-00b10360d61e.png)

**Comment by andrewbernard** [comment]
I have the  same issue on a new install of 1.7.4. How long does one have to wait for the warp-sync to complete, and where can one see the status of that operation? My home page reports 'Chain Synchronizxed (yes)'.

**Comment by 5chdn** [comment]
@andrewbernard usually 30 minutes. if the status indicates you are synced, then you probably are :)
