### ISSUE TITLE
Trace module methods not found

### ISSUE THREAD

**Issue by assafY** [paritytech/parity#6679]
I'm running Parity version 1.7.0 on a Linux machine, installed from sources.

I am using the following flags:
`--rpcaddr=127.0.0.1 --tracing=on --rpc --datadir=/var/parity --no-ui --rpcapi=eth,net,parity,traces,web3`

I am trying to call the `trace_transaction` method from a nodeJS service via web3.js as follows:

```js
web3.currentProvider.sendAsync({
      method: "trace_transaction",
      params: ["0xc4b6f998dba610ada54c775fd727fba4a25cda38cb6275b2efd3ff17dc36d0b5"],
      id: "1",
      jsonrpc: "2.0"
    }, (err, res) => {...})
```

I expected this method to be found, as I added the `--tracing=on` flag mentioned in the documentation. However, the RCP response is

```sh
{ jsonrpc: '2.0',
  error: { code: -32601, message: 'Method not found' },
  id: 1 }
```

Any idea what I am missing here?

**Comment by 5chdn** [comment]
The RPC module is called `trace` not `traces` :)

**Comment by assafY** [comment]
Thanks, but FYI, it actually should be `traces`. Anyway, the issue was a separate internal one and unrelated to Parity. 

https://github.com/paritytech/parity/wiki/JSONRPC
