### ISSUE TITLE
Config toml is prioritized over chain specification file for picking network-id

### ISSUE THREAD

**Issue by jbentke** [paritytech/parity#6680]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: MacOS
> - **And installed**: via installer

In the wiki is no mentioning that the parity configuration file is overruling the chain specification file. I guess its a question of taste, but I expected the chain specification file to act like an unchangeable part of one specific network.

Tested on 1.7.0 and 1.8.0 with mac and aws. Network size tested with 2 and 3 nodes.

_Config takes precedence over specification_
**steps to reproduce**: Setup a PoA network as in the [wiki tutorial](https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial). After it runs and nodes are connected, stop the nodes and add for node0 the network-id parameter with value 1.
**expected behavior**: nodes connect
**actual**: nodes do not connect

_Specification gets ignored with a set config_
**steps to reproduce**: When network-id is set for both nodes in config to 1, create a new demo-spec.json where the networkID is different. Change the config of node0 to use the newly created specification file.
**expected behavior**: nodes do not connect
**actual**: nodes connect 

Could someone clarify which part of the chain specification file is in fact unchangeable (like the genesis file)?

**Comment by 5chdn** [comment]
Priority is ordered like that (top overrides bottom):

0. Command-Line Flags (fastest way to change the behavior)
1. Configuration File (fast way to change the behavior, but more persistent than CLI)
2. Chain Spec (you usually only change that once per chain and use client configuration for everything else)
3. Client Defaults (you usually do not alter the parity code base to change network params but use a chain spec)
