### ISSUE TITLE
Support for Etherite fork

### ISSUE THREAD

**Issue by sayyesman** [paritytech/parity#6682]
# FEATURE REQUEST

Please support Etherite, it is a fork of Ethereum to keep the block reward at 5 ether, removing the difficulty bomb and keeping in the other features of the fork.

Please add it as an option like in classic, right now only geth is supported!

https://www.reddit.com/r/Etherite/comments/75bttb/what_is_etherite_and_how_to_help_out/

**Comment by 5chdn** [comment]
Do you have a working chain-spec? Feel free to create a pull-request.

**Comment by opcahf** [comment]
@5chdn We will need this, too. LOL our competitor

**Comment by 5chdn** [comment]
@opcahf sure, just submit a PR and we will discuss implementation details there.

**Comment by wjcloud** [comment]
@5chdn Hold sec, we will pr when the premine is ended.

**Comment by 5chdn** [comment]
@wjcloud ok :laughing:
