### ISSUE TITLE
eth_estimateGas issues "Transaction execution error"

### ISSUE THREAD

**Issue by sjStefan** [paritytech/parity#6685]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.7.3-beta-d097956-20171009/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1037-aws x86_64
> - **And installed**: via binaries

**Actual bevaviour:**

Executing eth_estimateGas with a contract address

`{
  "jsonrpc": "2.0",
  "id":   1,
  "method": "eth_estimateGas",
  "params": [
    {
      "to": "0x459F7854776ED005B6Ec63a88F834fDAB0B6993e",
      "value": "0x6f05b59d3b20000"
    }
  ]
}`

issues the following error:

Error-Message: Transaction execution error
Error-Code: -32015

A look into the logfile just say:
`2017-10-10 09:43:19   TRACE estimate_gas  estimate_gas failed with 1000000000000`

Changing the address to a different one **works** or even using a docker-image (Parity/v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.20.0) for reproducing the issue still **works**, which is quite confusing.

**Comment by rphmeier** [comment]
This means that the node couldn't find an amount of gas that leads to the call succeeding. The behavior of `eth_estimateGas` in such a case is undefined, so Parity chooses to return an error. Can you ensure that the contract call doesn't unconditionally throw?

**Comment by sjStefan** [comment]
I'm sorry.
I don't understand, what you're trying to say with "contract call doesn't unconditionally throw".
The thing is, on a different node, which uses a docker-image and parity 1.7.2, the command finely works.

**Comment by 5chdn** [comment]
What do you mean by _changing the address to a different one_?

**Comment by sjStefan** [comment]
> What do you mean by changing the address to a different one?

Rather than using the contract address (0x459F7854776ED005B6Ec63a88F834fDAB0B6993e) as a recipient-address, I can use this address for instance: 0xacf14ab404274b72e919f22ae4638f52797833a3

Calling eth_estimateGas with 0xacf14ab404274b72e919f22ae4638f52797833a3 works perfectly.

**Comment by 5chdn** [comment]
Yes, of course, this depends on the contract you are calling.

**Comment by sjStefan** [comment]
I was just wondering, as geth is returning a "proper" value rather than returning an error.
