### ISSUE TITLE
Can't add new abi when adding new erc20 Token

### ISSUE THREAD

**Issue by KenoLeon** [paritytech/parity#6692]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**:  MacOS 
> - **And installed**: homebrew

Parity//v1.7.2-beta-9f47909-20170918/x86_64-macos/rustc1.19.0

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
---

Actual:

Trying to add an erc20 Token, the Abi field is locked displaying the information of a previous Token 

Expected: 
I should be able to either clear the field or the field should be cleared upon adding a new Token

**Comment by chevdor** [comment]
you need to select *custom*, then you can enter the ABI of your choice.

**Comment by 5chdn** [comment]
what @chevdor said. ^

**Comment by KenoLeon** [comment]
@5chdn @chevdor Thanks, got it working both ways.
