### ISSUE TITLE
Cannot access personal APIs using Parity/web3 console app

### ISSUE THREAD

**Issue by skozin** [paritytech/parity#6696]
> I'm running:
>
> - **Parity version**: v1.6.10-stable-1a5b176-20170721/x86_64-macos/rustc1.18.0
> - **Operating system**: MacOS
> - **And installed**: homebrew

I'm running Parity with these flags:

```
parity --rpcapi 'eth,net,web3,personal'
```

(I also tried to run it with `--dapps-apis-all` with the same result.)

Trying to unlock my default account in "Parity/web3 console" application fails with "Method not found" error. No `personal` APIs seem to work, not just `unlockAccount`:

```
> web3.personal.unlockAccount(web3.eth.accounts[0], "anything")
Unhandled exception: ,Method not found,

> web3.personal.lockAccount(web3.eth.accounts[0])
Unhandled exception: ,Method not found,

> web3.personal.listAccounts()
Unhandled exception: ,Method not found,

> web3.personal.newAccount("smth")
Unhandled exception: ,Method not found,
```

`web3.eth.accounts` contains my accounts, though.

Inspecting HTTP request for `listAccounts` using Chrome devtools yields the following (I dropped some non-significant headers):

```
Request:

POST http://127.0.0.1:8080/rpc/ HTTP/1.1
Accept: */*
Content-Length: 70
Content-Type: application/json
Host: 127.0.0.1:8080
Origin: http://127.0.0.1:8180

{"jsonrpc":"2.0","id":92,"method":"personal_listAccounts","params":[]}


Response:

HTTP/1.1 200 OK
Content-Type: application/json

{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found","data":null},"id":92}
```

Also, I tried to access the same APIs using `web3` in NodeJS. `unlockAccount` works, but `lockAccount` still throws the same "Method not found" error.

Is this the expected behavoir? What could be wrong in this setup?

**Comment by 5chdn** [comment]
`lockAccount` is not implemented in Parity. See https://github.com/paritytech/parity/wiki/JSONRPC-personal-module

some more dedicated APIs are available in https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module :)

**Comment by skozin** [comment]
@5chdn thanks, didn't know it. But `unlockAccount` is implemented, right? The problem is that it doesn't work in console app.

I've updated the issue description to mention only supported APIs, which still don't work in console app.

**Comment by 5chdn** [comment]
Does it work if you directly call that API with `curl`? (see wiki for examples)
