### ISSUE TITLE
I have two questions. Please let me know

### ISSUE THREAD

**Issue by iceVeryCold** [paritytech/parity#6698]
1.What does the source code do？
2.Is the Parity client connected directly to the Ethernet server?
thanks

**Comment by 5chdn** [comment]
> 1.What does the source code do？

Thank you for that question, I'll try to quickly wrap this up. This repository contains source-code for multiple connected projects. This is mainly the Parity Ethereum Client implementation (see `parity/`, `ethcore/`, etc.) and the graphical user interface, the so called Parity Wallet (see `js/`, `dapps/`, etc.). This repository also includes some more rust crates and binaries, most importantly tools like `ethkey/`, `ethstore/`, `evmbin/`, etc. If you have any more specific questions, please let me know.

> 2.Is the Parity client connected directly to the Ethernet server?
thanks

Yes, however, Ethereum is not a _server_ in traditional terms. Ethereum is a peer-to-peer network powering a decentralized computing platform. The _server_ in this context is the Ethereum blockchain. You might want to skim through the [FAQ on Reddit](https://www.reddit.com/r/ethereum/comments/6mteq5/welcome_to_rethereum_the_reddit_front_page_of_the/). Parity is an independent implementation of the Ethereum protocol and enables you to be part of this network with a full or light node.

**Comment by iceVeryCold** [comment]
Thanks。But I still have a question, what does the Parity mainly do, what is the purpose of providing the source code

**Comment by 5chdn** [comment]
> Parity is an Ethereum client, written from the ground-up for correctness-verifiability, modularisation, low-footprint and high-performance. To this end it utilises the Rust language, a hybrid imperative/OO/functional language with an emphasis on efficiency. It is professionally developed by Parity Technologies, a VC-funded UK-based company. We aim to have all important logic 100% unit-tested, all public APIs 100% documented, all code reviewed by multiple peers and follow a pipelined 7-ish-week release cycle similar to the Rust compiler.

Please check our wiki for some more details on what it does.

https://github.com/paritytech/parity/wiki

**Comment by iceVeryCold** [comment]
I want to configure a local ETH chain. Do you have a detailed tutorial? thank you

**Comment by 5chdn** [comment]
Yes! https://github.com/paritytech/parity/wiki/Private-development-chain

**Comment by iceVeryCold** [comment]
If I use the Parity client, I can only use the dapps to realize the function I want to achieve?

**Comment by 5chdn** [comment]
Depends on what you want to do, but usually DApps are the way to go yes.

**Comment by iceVeryCold** [comment]
1.If I want to use the Parity client, can I only write smart contracts?
2.Can you modify the Parity source to implement the local chain of your server？
Thank you very much.
