### ISSUE TITLE
No installer works on MacOS

### ISSUE THREAD

**Issue by jorgeorpinel** [paritytech/parity#6699]
> I'm running:
>
> - **Parity version**: N/A
> - **Operating system**: MacOS
> - **And installed**: via installer / homebrew

I tried https://github.com/paritytech/homebrew-paritytech and the brew install finished, then I even ran `brew services start paritytech/paritytech/parity` Now what? The documentation doesn't give any more info. There's no apps on my OS, no local server running.

Then tried https://github.com/paritytech/parity#simple-one-line-installer-for-mac-and-ubuntu which simply doesn't work (I use oh-my-shell). I had to manually download that shell script and run it. The installation sort of works, but at some point starts alerting me that "no keychain is found" with an option to reset something to which I obviously click [Cancel]. **Sketchy**. Then the app is added to my OS but never opens.

I deleted the app from Applications/ but how do i make sure it's completely uninstalled?

**Comment by 5chdn** [comment]
Please share the exact error messages. I just installed 1.7.3 on macos high sierra yesterday both via installer and brew, so technically it should work, but I can look into it if you could share some details on how it's failing.

**Comment by jorgeorpinel** [comment]
Hi

1.
> the brew install finished, then I even ran brew services start paritytech/paritytech/parity Now what?

2.
> Then tried https://github.com/paritytech/parity#simple-one-line-installer-for-mac-and-ubuntu which simply doesn't work (I use oh-my-shell). I had to manually download that shell script and run it.

In reference to https://get.parity.io . Here's what happened

![image](https://user-images.githubusercontent.com/1477535/31429132-292d3f24-ae3b-11e7-8e46-caea5adb49dd.png)

Safari opens and displays this numerous times: ![image](https://user-images.githubusercontent.com/1477535/31429156-3682ba5a-ae3b-11e7-97ab-e26c974920f6.png)

I click [Cancel] as the option is: 
![image](https://user-images.githubusercontent.com/1477535/31429178-5069b2d4-ae3b-11e7-86e8-21c820ee1799.png)

Result:
![image](https://user-images.githubusercontent.com/1477535/31429189-5a74bef4-ae3b-11e7-8e7a-45568f52b673.png)

I then do have the app:
![image](https://user-images.githubusercontent.com/1477535/31429210-6e0c3fb4-ae3b-11e7-9a35-9144f1e4e0cc.png)

but the UI never opens, the process just hogs my CPU:
![image](https://user-images.githubusercontent.com/1477535/31429278-9b6b2c2c-ae3b-11e7-8cd0-2169d37a27a9.png)
so I force quit it and remove the App.

**Please confirm that is all that's needed to fully remove this software.**

Thanks

**Comment by 5chdn** [comment]
These are some weird macos issues unrelated to Parity.

What happens if you run `parity ui` in your terminal?

**Comment by jorgeorpinel** [comment]
I doubt it.

```sh
➜  ~ parity ui
Database was created with newer client version. Upgrade your client or delete DB and resync.
```

Can you at least confirm the steps to fully remove this software from my Mac?

**Comment by 5chdn** [comment]
Just delete it from applications :)

If there is a binary in /usr ... then you probably used brew, try `brew uninstall parity`.

**Comment by jorgeorpinel** [comment]
Thanks
