### ISSUE TITLE
But I still have a question

### ISSUE THREAD

**Issue by iceVeryCold** [paritytech/parity#6703]
What does the Parity mainly do, what is the purpose of providing the source code？ Thanks

**Comment by 5chdn** [comment]
You might wish to read up some comments by Richard Stallman on Free/Libre Open Source Software: https://www.gnu.org/philosophy/floss-and-foss.en.html

Wikipedia is also a helpful resource here. https://de.wikipedia.org/wiki/Free/Libre_Open_Source_Software

You can use our source-code to compile your Parity software on your own, or you can contribute to the development by cloning our repository.
