### ISSUE TITLE
Stage 1 block verification failed

### ISSUE THREAD

**Issue by bert2002** [paritytech/parity#6704]
Hi,
> I'm running:
>
> - **Parity version**: Parity/v1.7.2-beta-9f47909-20170918/x86_64-linux-gnu/rustc1.19.0
> - **Operating system**:  Linux
> - **And installed**: binaries

I tried to export and import the kovan chain from a healthy node and it fails with following error:

```
2017-10-11 07:00:14 UTC Stage 1 block verification failed for 4e35…bf9e: Block(InvalidTransactionsRoot(Mismatch { expected: de15355e1ead3172bb4a4887dc75d5eb847e674849c806369c6bca9c9db5742a, found: e25cd4c610435472319bc8b0bab99645a7d8dae1b26b7e61bd98d238d44070b5 }))
Cannot import block: Block(InvalidTransactionsRoot(Mismatch { expected: de15355e1ead3172bb4a4887dc75d5eb847e674849c806369c6bca9c9db5742a, found: e25cd4c610435472319bc8b0bab99645a7d8dae1b26b7e61bd98d238d44070b5 }))
```
The export and import was made by following commands:
```
parity --chain kovan export blocks backup.rlp
parity db kill --chain=kovan
parity --chain=kovan --pruning archive import backup.rlp 
```
Any help appreciated. If you need more information, let me know :) 

bert

**Comment by 5chdn** [comment]
Should be fixed actually.
