### ISSUE TITLE
UI: Account search currently broken

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6709]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity//v1.8.0-unstable-e3fa46037-20171010/x86_64-macos/rustc1.20.0

> - **Operating system**: Windows / **MacOS** / Linux
> - **And installed**: via installer / homebrew / binaries / from **source**

I just noticed that the search function is broken and returns incorrect results.

To reproduce:
- pick one of your accounts
- Click on Transfer to send Ether or Tokens to another
- Click in the recipient address field
- The search dialog opens, that´s where the issues are:
    - the results of the search is incoherent, the **accounts** show up as accounts (OK), **contacts** (NOT OK) and **contracts** (NOT OK)
    - also the search is broken, search for the name of one of your contracts, it will not be found/be displayed

**Comment by 5chdn** [comment]
git pull :)

#6701

**Comment by chevdor** [comment]
I have seen also the issue in the latest stable binary for windows btw.

**Comment by 5chdn** [comment]
latest beta? shouldn't be broken in stable. backport is in #6713
