### ISSUE TITLE
Notification of orphan block

### ISSUE THREAD

**Issue by qchen006** [paritytech/parity#6722]
Hi, when the client is notified a new block, then the block becomes a orphan block. Can the client be notified in some way?

I don't find a similar api that I can use here:https://github.com/ethereum/wiki/wiki/JSON-RPC

**Comment by qchen006** [comment]
@tomusdrw  @gavofyork  @jacogr   Can you please kindly help?

**Comment by 5chdn** [comment]
There are no orphan blocks in Ethereum.

https://ethereum.stackexchange.com/questions/34/what-is-an-uncle-ommer-block

**Comment by qchen006** [comment]
I mean the same transaction may be included in two different blocks, which are contained in two different chains. 

How can I determine which transaction should be valid on the mainchain from the parity JSON API?

**Comment by qchen006** [comment]
@5chdn

**Comment by AFDudley** [comment]
This will tell you if the transaction was included in the chain or not. https://github.com/paritytech/parity/wiki/JSONRPC-eth-module#eth_gettransactionreceipt
https://github.com/paritytech/parity/wiki/JSONRPC-eth-module#eth_getblockbyhash

If the block is "Far enough away" from the head, it's safe to assume it won't be re-organized out of the chain. 12 blocks is standard, nothing wrong with doubling it to 24 if you're paranoid.
