### ISSUE TITLE
curl script doesn't update ver 1.7.3 to already annonced 1.7.4 version

### ISSUE THREAD

**Issue by dip239** [paritytech/parity#6728]
human@EtherDev:~$ bash <(curl https://get.parity.io -L)
...
Parity 1.7.3 already installed

**Comment by 5chdn** [comment]
Yeah stay tuned, we are in the process of releasing 1.7.5

**Comment by 5chdn** [comment]
should be fixed now. you should get 1.8.0, if not please report back.

**Comment by dip239** [comment]
got 1.8.0. thanx.
