### ISSUE TITLE
Starting Parity causes my cable modem Cisco EPC3825 to crash

### ISSUE THREAD

**Issue by visadb** [paritytech/parity#6729]
> I'm running:
>
> - **Parity version**: 1.7.4
> - **Operating system**: Windows 10
> - **And installed**: via installer

Each time I start Parity or it starts on boot, my cable modem Cisco EPC3825 crashes and reboots after a few minutes. Expected behavior: modem not crashing. :)

No other program I use, including geth, does this. Yeah, the bug is probably in the modem, but it is a pretty popular one so it would be nice if there was a workaround.

Steps to reproduce:
1) Install said modem with firmware epc3825-v302r125574-150224c (pushed by ISP, not user-flashable) as your default gateway
1) start parity

**Comment by 5chdn** [comment]
having the same issue with my fritz.box :)

my workaround is to tunnel everything through VPN. But I feel your pain.

**Comment by izetex** [comment]
The same with Asus RT-N56U

Immedeately after parity 1.8 start it crashes

**Comment by arkpar** [comment]
Does it crash if you run parity with `--no-discovery`? How about `--allow-ips=public`?

**Comment by 5chdn** [comment]
It's reproducible on our office-router by the way, we can look into on one of our many bored afternoons :-p

**Comment by izetex** [comment]
parity --no-discovery --allow-ips public
with Parity/v1.7.5-stable-5a1a7f6-20171012/x86_64-macos/rustc1.20.0
2017-10-13 16:55:28  Keys path /Users/studnev/Library/Application S

is OK

**Comment by ddorgan** [comment]
Are there any limits on connections currently?

**Comment by visadb** [comment]
Here too, no modem crash with config.toml equivalents of --no-discovery and --allow-ips public

**Comment by arkpar** [comment]
@ddorgan  Limits are 32 pending connections + 25 established connections by default. There's also a limit of 16 new connections per second.

**Comment by 5chdn** [comment]
parity --no-discovery --allow-ips public

resolved this for me
