### ISSUE TITLE
Encountered error during state restoration: Snapshot restoration aborted.

### ISSUE THREAD

**Issue by izetex** [paritytech/parity#6734]
> I'm running:
>
> - **Parity version**: Parity/v1.8.0-nightly-e3fa460-20171010/x86_64-macos/rustc1.20.0
> - **Operating system**: MacOS
> - **And installed**: brew

I fail to synchronize parity using default snap synchronization. It fails every time ( and after complete database removal ) on average block.

I have many attempts, all them failed - i attaching 2 logs

Complete log:
[parity.log](https://github.com/paritytech/parity/files/1381656/parity.log)

[parity2.log](https://github.com/paritytech/parity/files/1381792/parity2.log)

**Comment by 5chdn** [comment]
Could you share less verbose logs? I can't skim through 1500 unrelated error messages.

Try `-l sync,snapshot=trace`
