### ISSUE TITLE
Parity doesn't have connected peers. Chain is not synced.

### ISSUE THREAD

**Issue by AndreyUS** [paritytech/parity#6735]
> I'm running:
>
> - **Parity version**: 1.7.3 - beta
> - **Operating system**: Linux  3.13.0-125-generic x86_64
> - **And installed**: via installer binaries

---
I'm trying to setup parity on my server but it doesn't have connected peers.
I tried on my mac and it works well.
Could you help find solution for the issue?   
I use config.toml

[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "none"
release_track = "current"
no_download = false
no_consensus = false
no_persistent_txqueue = false

chain = "ropsten"
base_path = "my/path"
db_path = "my/path"
keys_path = "my/path"
identity = ""

[ui]
force = false
disable = false
port = 8880
interface = "127.0.0.1"
path = "my/path"

[network]
port = 30303
min_peers = 10
max_peers = 15
nat = "any"
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64

[rpc]
disable = false
port = 8545
interface = "local"
cors = "null"
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "parity_accounts", "personal"]
hosts = ["none"]`

**Comment by AndreyUS** [comment]
Removed [network] params. Now it works well.

**Comment by 5chdn** [comment]
Yeah you basically removed the bootnodes.
