### ISSUE TITLE
how to implement clique consensus in parity

### ISSUE THREAD

**Issue by akshay951228** [paritytech/parity#6736]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows / MacOS / Linux
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

**Comment by 5chdn** [comment]
The logic needs to be added to the core.
