### ISSUE TITLE
Typo in 'sign data' copy text

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#6737]
> I'm running:
>
> - **Parity version**: 1.7.5
> - **Operating system**: MacOS 
> - **And installed**: via installer

---

> WARNING: **This** consequence**s** of doing this...

should probably read:

> WARNING: **The** consequences of doing this...

<img width="404" alt="screen shot 2017-10-13 at 09 52 16" src="https://user-images.githubusercontent.com/17831185/31535732-6a3f63f8-affc-11e7-840e-6db4db66d266.png">

**Comment by 5chdn** [comment]
Where does this message come from? The DApp? AFAIK the DApp is not maintained by Parity. Does anyone know who created it?

**Comment by bjornwgnr** [comment]
Does it come from a Dapp? Thought it comes from the UI/Signer. @jacogr ?

**Comment by 5chdn** [comment]
The signer just signs whatever you pass in.

**Comment by bjornwgnr** [comment]
I'm talking about the copy text in red, not the text in the box.

**Comment by 5chdn** [comment]
Sorry.
