### ISSUE TITLE
Low image quality certification badge

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#6738]
> I'm running:
>
> - **Parity version**: 1.7.5
> - **Operating system**: MacOS
> - **And installed**: via installer

---

<img width="180" alt="screen shot 2017-10-13 at 09 57 50" src="https://user-images.githubusercontent.com/17831185/31535897-0bed3112-affd-11e7-92e6-41ce58159394.png">
<img width="51" alt="screen shot 2017-10-13 at 09 57 58" src="https://user-images.githubusercontent.com/17831185/31535898-0c092386-affd-11e7-9ccc-3dbe674a71c6.png">

**Comment by 5chdn** [comment]
Please check now.

**Comment by bjornwgnr** [comment]
@5chdn looks good now, but shouldn't it rather say "PICOPS certified" instead of "PICOPS certifier"?
<img width="206" alt="screen shot 2017-10-13 at 12 16 51" src="https://user-images.githubusercontent.com/17831185/31541961-8e084c5a-b010-11e7-8be5-422e57a17aa5.png">

**Comment by 5chdn** [comment]
That's the name of the contract. Refresh please.

**Comment by 5chdn** [comment]
![screenshot at 2017-10-13 12-18-46](https://user-images.githubusercontent.com/15729797/31542148-378fc096-b011-11e7-9877-0834d66661f3.png)

**Comment by 5chdn** [comment]
^ that's the title @gavofyork had chosen.
