### ISSUE TITLE
Add PICOPS to "verify" view in UI

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#6740]
For the time being perhaps just a hyperlink to picops.parity.io?

Eventually an embedded version or at least a hyperlink that passes the to-be-certified address as a parameter would be nice.

**Comment by chevdor** [comment]
Considering PICOPS as one way to do KYC, I think it would be more elegant to have PICOPS as a DApp, registered on the Network and tag it with a 'KYC' or 'Verification' tag for users to identify their options.

As far as I can see, the Verify button is even completely gone on master btw.

**Comment by 5chdn** [comment]
Added it to the news section :)
