### ISSUE TITLE
Latest commit on master crashes parity on startup

### ISSUE THREAD

**Issue by NiklasKunkel** [paritytech/parity#6749]
Parity version: master (#6716)
Ubuntu 16.04.3 LTS
rustup v1.5.0 (92d0d1e9e 2017-06-24)

> 2017-10-13 20:15:24 UTC Starting Parity/v1.9.0-unstable-1294572-20171013/x86_64-linux-gnu/rustc1.19.0
> 2017-10-13 20:15:24 UTC Keys path /home/nkunkel/.local/share/io.parity.ethereum/keys/Foundation
> 2017-10-13 20:15:24 UTC DB path /home/nkunkel/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
> 2017-10-13 20:15:24 UTC Path to dapps /home/nkunkel/.local/share/io.parity.ethereum/dapps
> 2017-10-13 20:15:24 UTC State DB configuration: fast
> 2017-10-13 20:15:24 UTC Operating mode: active
> 2017-10-13 20:15:24 UTC Configured for Foundation using Ethash engine
> 2017-10-13 20:15:24 UTC Updated conversion rate to Ξ1 = US$338.49 (351702000 wei/gas)
> 
> ====================
> 
> stack backtrace:
>    0:     0x560ad2438d8c - backtrace::backtrace::trace::hdaa42453d8ce8a14
> 
> Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:860
> 
> This is a bug. Please report it at:
> 
>     https://github.com/paritytech/parity/issues/new
> 
> Aborted (core dumped)

**Comment by 5chdn** [comment]
That's fixed in #6665, reset your DB with `parity db kill` #6659.
