### ISSUE TITLE
Parity KYC

### ISSUE THREAD

**Issue by Julle1000** [paritytech/parity#6752]
Have got verified 2 times with 2 different ETH wallets, passport scan and all. First time with a hardware wallet(nano S). Second time with Exodus Wallet. Then I read you should use the parity wallet, so I installed it. Wont get verified now. Why did it work on 2 differnent wallets, but not the third? Im in for the Polkadot ICO. And if I use eather the verified Nano S adress or the verified Exodus adress, should it work anyway? I mean in 2 years? Is it going to be troubles claiming my DOTs?

**Comment by AyushyaChitransh** [comment]
You might want to contact picops@parity.io and explain the problem to them. You can also talk on the [gitter](https://gitter.im/paritytech/parity) channel for support.
