### ISSUE TITLE
sendTransaction hangs when replacing transaction with same nonce

### ISSUE THREAD

**Issue by sdrobs** [paritytech/parity#6763]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.7.3-beta
> - **Operating system**: Linux (Ubuntu 14.04)
> - **And installed**: via installer

---
Expected behavior:
1. Using node.js web3 module over IPC, send a transaction of gas price P and you will receive a transaction hash back.
2. Attempt to overwrite this pending transaction by calling sendTransaction again with the same nonce as step 1, and a 1.25x the gas price P from step 1
3. The txn from step 1 should be overwritten.
---
Actual Behavior:
1. Using node.js web3 module over IPC, send a transaction of gas price P and you will receive a transaction hash back.
2. Attempt to overwrite this pending transaction by calling sendTransaction again with the same nonce as step 1, and a 1.25x the gas price P from step 1
3. No callback is received from step 2, and the transaction is not overwritten. The call to sendTransaction simply hangs.
---
Steps to reproduce:
1. Run parity
2. Run the following node.js script, which should create a transaction then overwrite it in 3 seconds. You will need to npm install "read" and then replace < yourusername >, myAccount, and toAccount with your own. When run, you should see a transaction hash from the first sendTransaction appear along with the details printed, but the replacedTxn callback will never occur.

```
var Web3 = require('web3')
var net = require('net')
var read = require('read')

var client = net.Socket();
var ipcNode = '/home/<yourusername>/.local/share/io.parity.ethereum/jsonrpc.ipc';

web3 = new Web3(new Web3.providers.IpcProvider(ipcNode, client));

var myAccount = <your account address>
var toAccount = <account to send txn to>

read({ prompt: 'Password: ', silent: true }, function(passErr, pass) {
    if(passErr){
        console.log("Error reading password")
        process.exit(1)
    }

    web3.personal.unlockAccount(myAccount, pass, function(unlockErr, res){
        if(unlockErr){
            console.log(unlockErr)
            process.exit(1)
        }

        web3.eth.sendTransaction({
            to: toAccount,
            from: myAccount,
            gas: 250000,
            gasPrice: web3.toWei(3, 'gwei') // low gas price so that it stays pending
        }, function(sendErr, txnHash){
            if(sendErr)
                console.log(sendErr)
            else{
                console.log(txnHash)
                web3.eth.getTransaction(txnHash, function(txnErr, txn){
                    if(txnErr)
                        console.log(txnErr)

                    console.log(txn)

                    setTimeout(function(){
                        console.log(txn.nonce)
                        web3.eth.sendTransaction({
                            to: toAccount,
                            from: myAccount,
                            gas: 60000,
                            gasPrice: web3.toWei(10, 'gwei'),
                            nonce: txn.nonce
                        }, function(replacedTxnErr, replacedTxnHash){ // this callback never occurs
                            if(replacedTxnErr)
                                console.log(replacedTxnErr)
                            else
                                console.log(replacedTxnHash)
                        })
                    }, 3000)

                })
            }
        })
    })
})
```

**Comment by sdrobs** [comment]
Also just tested on 1.7.6 stable and experienced the same behavior.

**Comment by tomusdrw** [comment]
@sdrobs Unlock account is not safe to use, beause of that we only unlock your account for a single transaction (not for some specified time).
So to fix your example you need to unlock the account for the second time after you sent the first transaction or better use `personal.sendTransaction(txOptions, password)` method (no need to unlock).

**Comment by sdrobs** [comment]
@tomusdrw Confirmed that this did solve the problem, and I agree with the reasoning behind it, but maybe it would be worth returning an actual exception in this case? It seems a bit misleading to a) allow unlocking with a time based parameter when it doesn't really work, and B) leaving sendTransaction hanging without any response at all. Not sure if that falls under parity's domain or not though, since web3 is mostly just an interface to it.

**Comment by tomusdrw** [comment]
Seems that your code is not using time-unlocking (3 parameters call) which should return error (unless running in `--geth` compatibility mode).

The hanging happens because the transaction is awaiting user confirmation in Trusted Signer. If you'd open the Parity Wallet it should actually display the transaction details and ask you for the password. After the transaction is confirmed (or rejected) the IPC call will resolve to a hash (or error).

**Comment by sdrobs** [comment]
@tomusdrw Three param time unlocking actually does not throw an exception- I forgot to include it in my previous example, but this is the line I was using in my actual code:

```
web3.personal.unlockAccount(myAddress, password, "0x" + (3600).toString(16), function(err, res){
// do stuff
})
```

Seems like it accepts it without complaint as long as the time is encoded in base 16.

**Comment by tomusdrw** [comment]
@sdrobs Thanks for the test, we should indeed make it throw.
