### ISSUE TITLE
Byzantium Chain Spec File?

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6764]
Now that 1.7.6 is out, is is possible to post the Byzantium chain spec file here: 

https://github.com/paritytech/parity/wiki/Chain-specification

**Comment by 5chdn** [comment]
The first in the list is Byzantium-ready. 

https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json

**Comment by MicahZoltu** [comment]
It appears that this config file includes fork details in the engine section.  How does one apply those to different engines, in particular those that don't have params like InstantSeal?

**Comment by 5chdn** [comment]
instant seal isn't meant to be highly customizable. it's designed to provide a hassle-free developer environment. 

if you want to add byzantium-features to another engine, you should have a look at aura.

**Comment by arkpar** [comment]
EIPs that are are not related to difficulty or reward changes are applied in common params section:
https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/foundation.json#L155-L158
