### ISSUE TITLE
validators contract in AuthorityRound not working

### ISSUE THREAD

**Issue by akshay951228** [paritytech/parity#6767]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**:1.7.2-beta
> - **Operating system**: Linux
> - **And installed**: via installer

We have an AuthorityRound network where validators are added via contract.Initially there is a single mining node (0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e) hardcoded into the contract, new validators may join the network later.
but it giving error while start node
the error is this
![ter](https://user-images.githubusercontent.com/25878082/31582645-306df566-b1a7-11e7-90fe-9f0ee20da6c8.png)

my gensisus block is this
![gensisus block](https://user-images.githubusercontent.com/25878082/31582648-62f55c9a-b1a7-11e7-87df-47118f04ef2d.png)

**Comment by keorn** [comment]
As the error message indicates you will need to first import your authority account for that chain. Each chain has a separate key file directory.

**Comment by akshay951228** [comment]
metamask mnemonic gives different address in parity and why?

**Comment by akshay951228** [comment]
PARITY GENEARTED ADDRESS **0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e** 
WHEN VALIDATOR CALLS IT RETURNS THIS "0xbd138abd70e2f00903268f3db08f2d25677c9e".
AND HOW TO SOLVE THIS

**Comment by tomusdrw** [comment]
@akshay951228 The first address seems to be too long. It should be only 20 bytes. Solidity is trimming the address.

**Comment by akshay951228** [comment]
no man it removing 00 in fornt of address

**Comment by tomusdrw** [comment]
Just to give you a comparison:
```
0x00a329c0648769a73afac7f9381e08fb43dbea72 (Parity generated address)
0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e (your address)
```
