### ISSUE TITLE
Add placeholder for broken token icons.

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#6768]
<img width="585" alt="screen shot 2017-10-15 at 11 25 57" src="https://user-images.githubusercontent.com/17831185/31583421-b054610e-b19b-11e7-9630-f3d39eb2a66a.png">

**Comment by ottodevs** [comment]
This is not alignment fault, is just the alt label for inexistent logo in SIM token, you should ask Simoleon team to implement a logo following the standard practices.

**Comment by tomusdrw** [comment]
We should replace missing images with some placeholder (both tokens and dapps).

**Comment by mattdorst** [comment]
I also think this should default to the placeholder ? mark icon used for other tokens without images.

**Comment by 5chdn** [comment]
@mattdorst it has an icon but the link is broken. what you describe is already the case.

**Comment by agryaznov** [comment]
Isn't it some worse issue, which lets anybody to reproduce the trick done in SIM ERC20 contract to bother EVERY Ethereum account with uninvited token?

**Comment by 5chdn** [comment]
@bjornwgnr fixed in 1.8.1

@agryaznov yes that's an issue, but we fixed it in 1.8.1
