### ISSUE TITLE
metamask mnemonic gives different address in parity and why?

### ISSUE THREAD

**Issue by akshay951228** [paritytech/parity#6770]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.2
> - **Operating system**: Linux
> - **And installed**: via installer 
PARITY GENEARTED ADDRESS **0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e**
WHEN VALIDATOR CONTRACT CALLS IT RETURNS THIS **0xbd138abd70e2f00903268f3db08f2d25677c9e**
AND HOW TO SOLVE THIS.
metamask mnemonic gives different address in parity and why?

**Comment by ottodevs** [comment]
Mnemonic dynamics in parity is different from the metamask one.

You can check it, by visiting to myetherwallet, Mist and Metamask mnmonic passphrase are supported but Parity is not https://www.myetherwallet.com/#send-transaction

**Comment by akshay951228** [comment]
actually I want to implement POA in private network using parity but I need to add validators dynamical by **validator contract in genesius file** but smart contract truncate the 00 in public address
![sol](https://user-images.githubusercontent.com/25878082/31584653-1dbc2a04-b1d0-11e7-82ba-3c2f54e2b8fa.png)
see the address input and output in the image

**Comment by 5chdn** [comment]
parity uses a different derivation path.
