### ISSUE TITLE
please publish the checksum for the binaries, not just the installers

### ISSUE THREAD

**Issue by ezredd** [paritytech/parity#6778]
> I'm running:
>
> - **Parity version**: 1.7.7
> - **Operating system**:  MacOS 
> - **And installed**: homebrew

Parity does not publish the checksum for the parity binary itself, just for the various (non-homebrew) installers. Therefore i don't know how i can verify that the payload downloaded by homebrew is not malicious. 

Could you please publish the sha256sum for the binaries  themselves ? thanks a lot!

**Comment by 5chdn** [comment]
It's here. https://github.com/paritytech/homebrew-paritytech/blob/master/parity.rb#L6-L17
