### ISSUE TITLE
Cannot sign transaction using trezor hardware wallet

### ISSUE THREAD

**Issue by mirage007** [paritytech/parity#6781]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.8.0-beta-9882902-20171015/x86_64-macos/rustc1.20.0
> - **Operating system**: Mac OSX
> - **And installed**: via brew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

The parity signing dialog shows a CONFIRM REQUEST button, after clicking it seems the trezor hardware wallet shows "enter pin". At this point I would expect a grid to pop up just like when the wallet was first plugged in, however no window pops up in the parity browser UI making it impossible to send.

**Comment by 5chdn** [comment]
@folsen can you look into this too?

**Comment by folsen** [comment]
@mirage007 The pin matrix should show up immediately after plugging in the Trezor device. The account shouldn't actually show up in the wallet at all until you've unlocked it once. So you must have connected and then unlocked it, but you're saying that after you unlocked it the first time, when you went to sign a transaction the device asked to be unlocked again? Could you tell me whether you've successfully unlocked it all at any point. If you just plug it in and don't try to send a transaction does it still not show up?

**Comment by mirage007** [comment]
I open parity ui, plug in device, pin pad shows up. I enter pin, wallet now shows up. I try to send a transaction from that wallet. Pop up asking to confirm request shows up. No pin pad shows up on the parity ui, but the trezzor displays a pin pad.

**Comment by mirage007** [comment]
I tested it again, and it seems this time it worked, upon clicking the confirm request, the trezor shows the transaction amount and has a confirm button on it instead of the pin. Not sure how reproducible this is but I'll reopen in case I figure out the exact sequence of events that fails.
