### ISSUE TITLE
Tokens not showing

### ISSUE THREAD

**Issue by puddy5689** [paritytech/parity#6782]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/1.8.0/1.20.0/wi
> - **Operating system**: Windows
> - **And installed**: via installer
Recently bought some tokens on from the Worldcore ico, says they have been sent but they are not showing in my wallet, I used Parity because it advertises as ERC20 compatible, pls help
---

**Comment by puddy5689** [comment]
UPDATE: something has shown, 10000 Simoleon rather than the 700~ WRC i was expecting? Pls help what have i done

**Comment by 5chdn** [comment]
Removed the SIM. WRC is not registered. See https://github.com/paritytech/parity/wiki/Token-Registry
