### ISSUE TITLE
Support for Trezor Passphrase

### ISSUE THREAD

**Issue by ncsolar** [paritytech/parity#6784]
> - **Parity version**: Parity//v1.8.0-beta-9882902-20171015/x86_64-macos/rustc1.20.0
> - **Operating system**: MacOS 
> - **And installed**:  binaries 

Expected: After connecting the Trezor and entering the correct pin and being ask to enter a passphrase on the trezor a new field to enter that info

Actual: After entering the correct pin, Parity shows that the pin is incorrect but the trezor ask to enter a passphrase, there is no new field to enter that info

**Comment by 5chdn** [comment]
@folsen this one is your's, probably needs some checks if entering pin succeeded.

**Comment by folsen** [comment]
@5chdn & @ncsolar we don't support passphrase right now, but all the framework is in place so adding support in the future wouldn't be too hard!

**Comment by iinstances** [comment]
I experiment the same issue. Good point @ncsolar!

**Comment by oryband** [comment]
any chance to continue development of this issue?

**Comment by folsen** [comment]
@oryband we've been working on some big refactorings of the UI, so this has been continually downprioritized. There just aren't all that many trezor users and even fewer that use the passphrase option. That said, it would still be nice to get it in there. With the UI split off in its own repo maybe it'll be easier to attract contributions from those who actually intend to use the feature.

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/81
