### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by vega40k** [paritytech/parity#6790]
> I'm running:
>
> - **Parity version**: Parity/v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0

> - **Operating system**:  Linux
> - **And installed**: via installer 

stack backtrace:
   0:     0x55a7a893cdfc - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860

---

**Comment by vega40k** [comment]
parity db kill helps :-)

**Comment by 5chdn** [comment]
db kill is your friend ;)

if this happens more frequently, check the health of your disks.
