### ISSUE TITLE
Unable to make connection

### ISSUE THREAD

**Issue by rsthery** [paritytech/parity#6793]
> I'm running:
>
> - **Parity version**: 1.7.7
> - **Operating system**: MacOS 
> - **And installed**: via installer

Trying to run parity and receiving this message:
"Unable to make a connection to the Parity Secure API. To update your secure token or to generate a new one, run parity signer new-token and paste the generated token into the space below."

not sure how to proceed...

---

**Comment by 5chdn** [comment]
To generate a new signer token, type:

    /Applications/Parity\ Ethereum.app/Contents/MacOS/parity signer new-token

in your terminal.
