### ISSUE TITLE
The address is not a regular token contract address

### ISSUE THREAD

**Issue by Samyoul** [paritytech/parity#6794]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.0-beta-9882902-20171015/
> - **Operating system**: x86_64-windows-msvc/rustc1.20.0
> - **And installed**: via installer

---

I'm attempting to register the following token contract on the main-net registry https://etherscan.io/address/0x2c3c1f05187dba7a5f2dd47dca57281c4d4f183f .

However I get the following error:

`The address is not a regular token contract address`

The contract has all standard ERC-20 methods plus some additional methods. Does the token have to match and ERC-20 interface exactly? If so why?

![parity](https://user-images.githubusercontent.com/5702426/31619018-6e6734c4-b28b-11e7-9b55-a6f9a81fc255.png)

---

The same contract has been registered on the Kovan network with out issue. https://kovan.etherscan.io/address/0x6ccd3e3c7ff94c1e54a67217b4c731c87c0a7c08

**Comment by tomusdrw** [comment]
The `totalSupply` of the token needs to be greater than 0.

**Comment by Samyoul** [comment]
Ok, thank you very much for your feedback. Increasing the totalSupply worked for the contract.

**Comment by Hackdom** [comment]
The folks needing this token are having the same issue.
 https://etherscan.io/address/0x6e5d3e9ce88a0fba4e096e2eb8d2b3dc54685dd2

I can't put my finger on the problem.

**Comment by 5chdn** [comment]
@Hackdom 

    totalSupply  -->  0

**Comment by Hackdom** [comment]
I saw that in the previous issue but the initialSupply is full here. Etherscan is reading the variable here https://etherscan.io/address/0x6e5d3e9ce88a0fba4e096e2eb8d2b3dc54685dd2#readContract

**Comment by Hackdom** [comment]
Not sure...

**Comment by Samyoul** [comment]
I've seen the `totalSupply` of this contract show both `0` and `90000000000000000000000000`, there could be some issue with propagating the data via the network. Try it again, because I am getting a success with this contract.

![parity](https://user-images.githubusercontent.com/5702426/31725818-30d5db72-b41d-11e7-930e-8b37d2858570.png)

**Comment by Hackdom** [comment]
Ok, doing it.. I'm out of pocket, but the guys requesting this token will follow up with me asap.

**Comment by Hackdom** [comment]
Ok it's all good. Their chain wasn't synced up enough, thx for the quick responses guys. I'm sure we'll be in touch again.

**Comment by matt93310** [comment]
What does that mean that their chain wasn't synced up enough. I am expecting to receive coins from an ICO as well and I get the same message that you got "The address is not a regular token contract address".I am quite the novice and am kind of lost here.

**Comment by Hackdom** [comment]
So when syncing, you're obtaining the data from the network block-by-block. In their case, they had not yet reached the block at which the token contract was created. Therefore, that address had no bytecode in it until they were able to reach that block.

**Comment by knuck-io** [comment]
I am also experiencing this error, where the totalSupply is 208,523,125 so I do not understand. Please assist.

0x66d8dbcdb253ee5d66081f0b45cc1f02a7adc58a

**Comment by 5chdn** [comment]
@knuck-io are you fully synchronized?
