### ISSUE TITLE
Reseal period does not work with instant seal chains

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6796]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.0
> - **Operating system**: Linux
> - **And installed**: Docker

---

`config.toml`
```
[parity]
chain = "dev"
[mining]
reseal_min_period = 2000
reseal_max_period = 2000
reseal_on_txs = "all"
force_sealing = false
```

The above config results in blocks being sealed as soon as transactions arrive, not every 2 seconds.  Changing `reseal_on_txs` to `none` makes it so blocks are never mined.

I would have expected that the above config with `reseal_on_txs` set to `none` would have resulted in a block every 2 seconds.

**Comment by 5chdn** [comment]
this is intended :)

instant seal instantly seals the blocks. If you want a more configurable environment, please use aura.
