### ISSUE TITLE
Placeholder and Name Display Issue when Adding Contract

### ISSUE THREAD

**Issue by mattdorst** [paritytech/parity#6797]
> I'm running:
>
> - **Parity version**: 1.7.7
> - **Operating system**: MacOS
> - **And installed**: via installer

Placeholder and inputted text within the eth address field when adding a contract to watch has some UI glitches. This happens when typing in the address or copying the address. Existing contracts don't seem to have this issue.

<img width="888" alt="screen shot 2017-10-16 at 1 33 59 pm" src="https://user-images.githubusercontent.com/215049/31626242-f9b74a74-b276-11e7-9bfb-0d045682ab85.png">

<img width="1431" alt="screen shot 2017-10-16 at 1 34 30 pm" src="https://user-images.githubusercontent.com/215049/31626253-064372d6-b277-11e7-8b5c-faf75b9ceecb.png">

<img width="482" alt="screen shot 2017-10-16 at 1 34 19 pm" src="https://user-images.githubusercontent.com/215049/31626249-ffcc310e-b276-11e7-88ed-92fcf4e6e806.png">

---

**Comment by 5chdn** [comment]
Same happens in Brave.

**Comment by Tbaut** [comment]
Could not reproduce in v1.10
