### ISSUE TITLE
InstantSeal chain config examples are invalid.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#6800]
> I'm running:
>
> - **Parity version**: 1.8.0
> - **Operating system**: Linux
> - **And installed**: Docker

---

https://github.com/paritytech/parity-deploy/blob/master/config/spec/engine/instantseal and https://github.com/paritytech/parity/wiki/Pluggable-Consensus#instant-seal both show:
```
"engine": {
	"instantSeal": { "params": {} }
}
```
However, when trying to load a chain spec with that engine I receive an error:
> Spec json is invalid: invalid type: map, expected unit at line 4 column 25

That error is right after the open `"instantSeal": {`.

**Comment by MicahZoltu** [comment]
For future readers, the following resolves the error and appears to work: `"instantSeal": null`

**Comment by 5chdn** [comment]
Thanks, updated the wiki :)

**Comment by 5chdn** [comment]
@Office-Julia created a PR, thanks!

**Comment by ddorgan** [comment]
There are actually a few option changes we need to take into account here. Lucky for us we no longer need to support older versions, since they won't sync with mainnet anyway. We at least need to move all the parameters that were in engine and have moved to params ...
Looking into this...

**Comment by 5chdn** [comment]
Instant seal doesn't have any parameters, does it?

https://github.com/paritytech/parity-deploy/pull/32 works for me

**Comment by MicahZoltu** [comment]
If InstantSeal doesn't have parameters, how do you set it up to have block 0 be where Byzantium starts?
