### ISSUE TITLE
Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData'

### ISSUE THREAD

**Issue by bluecloudmatrix** [paritytech/parity#6802]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.9.0
> - **Operating system**:  Linux
> - **And installed**:  from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
stack backtrace:
   0:     0x7f56fe033b5c - backtrace::backtrace::trace::h3d7946faa2473996
   1:     0x7f56fe033b9b - backtrace::capture::Backtrace::new::hbeb31b9a68424764
   2:     0x7f56fe032a58 - panic_hook::panic_hook::hf8cf75703e1d4347
   3:     0x7f56fe064f26 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x7f56fe064db4 - std::panicking::begin_panic_new<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:553
   5:     0x7f56fe064cb9 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:521
   6:     0x7f56fe064c4a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:497
   7:     0x7f56fe093130 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:92
   8:     0x7f56fd7e0e16 - core::result::unwrap_failed::h77c8573da360367a
   9:     0x7f56fd8dadb7 - <KVDB as ethcore::db::Readable>::read::h812740a74197f60e
  10:     0x7f56fda22343 - ethcore::blockchain::blockchain::BlockChain::epoch_transition::hcac7db44a3b96619
  11:     0x7f56fd8a6e40 - ethcore::client::client::Client::new::ha11bc028cc657b10
  12:     0x7f56fd95044b - ethcore::service::ClientService::start::h4d6d4828d20e0f22
  13:     0x7f56fd361f50 - parity::run::execute::h1cd6899c6f67463c
  14:     0x7f56fd37a113 - parity::execute::h88dafd984771d54f
  15:     0x7f56fd38012f - parity::main_direct::hd3ae9c9fccbe31c5
  16:     0x7f56fd384463 - parity::main::hb509fdecee1e429f
  17:     0x7f56fe06ba2b - panic_abort::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_abort/lib.rs:40

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', /checkout/src/libcore/result.rs:860

**Comment by apstemmer** [comment]
could you try removing the db and then restarting?
cd ~/.local/share/io.parity.ethereum/chains
rm -rf ethereum

**Comment by rphmeier** [comment]
yeah, there was an issue with formatting of a specific value in the database which accidentally changed temporarily in master. master now follows the same format as 1.7.x but previous master databases will be broken.

**Comment by bluecloudmatrix** [comment]
Yes, it needs to removing previous db
