### ISSUE TITLE
Parity crashes when toggling browser support on Ledger

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#6805]
> I'm running:
>
> - **Parity version**: Parity//v1.7.6-stable-1953533-20171013/x86_64-windows-msvc/rustc1.20.0
> - **Operating system**: Windows 
> - **And installed**: via installer

---

- the Ledger had support for browser turned on
- I tried sending a small amount of ETH from Parity
- The signer asked for comfirmation
- On the Ledger I turned off the browser support
And at that point Parity crashed and had to be restarted. Nothing shows up in the logs.

From: https://github.com/paritytech/parity/issues/5672#issuecomment-337151043

**Comment by folsen** [comment]
This seems like it might be from the fact that the Ledger will acquire a USB lock when asked to sign, and if you never sign, it won't let go of that lock until the device times out. For the Trezor I put in a timeout, but I don't know what the situation is for the Ledger.

**Comment by tomusdrw** [comment]
Although it shouldn't lead to crash, but just a deadlock right?

**Comment by folsen** [comment]
Ah yes, so my liberal interpretation of "crash" here is "application stops working". Since he said it doesn't output anything to logs, I don't think it's an _actual_ crash.

**Comment by tomusdrw** [comment]
Oh, I see. Makes sense then.
