### ISSUE TITLE
Parity and MEW Trezor hardware wallet derivation path don't match

### ISSUE THREAD

**Issue by mirage007** [paritytech/parity#6811]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**:  Parity/v1.8.0-beta-9882902-20171015/x86_64-macos/rustc1.20.0
> - **Operating system**: MacOS
> - **And installed**: via homebrew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
This relates to issue #4500 .

I just plugged in a trezor and it asked me to authenticate with pin in the Parity UI. Upon authentication, I see an account pop up, however the public address doesn't match that of MEW.

Using the Trezor command line, I manually compared the path of the trezor wallet by running:

`trezorctl ethereum_get_address -n "m/44'/60'/0'/0"`

This matches the address of the Parity Wallet. However, when I run the Trezor via MEW integration, the first wallet that shows up seems to be generated from the below:

`trezorctl ethereum_get_address -n "m/44'/60'/0'/0/0"`

Not sure where is the best place to put this, but at least I would throw it out there, given this is a new feature perhaps it's better to synchronize sooner rather than later.

**Comment by 5chdn** [comment]
> The [default derivation paths](https://blog.trezor.io/trezor-integration-with-myetherwallet-3e217a652e08) used by TREZOR for ETH/ETC are as follows:
>
> ETH: m/44'/60'/0'/0/
> 
> ETC: m/44'/61'/0'/0/

Sounds like a MEW issue. @folsen please confirm ;)

**Comment by folsen** [comment]
@mirage007 could you confirm what your address is if you use the application from Trezor themselves? We do indeed use the `"m/44'/60'/0'/0"` derivation path, and I was under the impression that MEW did the same (during my testing that seemed to be the case, maybe they've changed something?)

**Comment by folsen** [comment]
Investigating this further, I can't actually really tell who's right or wrong here. But it definitely seems like MEW is adding a `/0` to any derivation path.

If you select the derivation path for Ledger in the MEW UI, you get the Parity-derived address for the Trezor. This address does indeed correspond to the output from `trezorctl ethereum_get_address -n "m/44'/60'/0'/0"` like @mirage007 posted. However in the MEW UI it's saying the path that it's using is `m/44'/60'/0'`, so it does look like it's adding a `/0` to the end of every path. I don't know why that would be. According to what I can read from the "standard" it shouldn't be added.

Would be good if we could get a comment from someone at MEW about this. It would obviously be very preferable if we both derived the same.

**Comment by mirage007** [comment]
The reason I found this is because when I first started using Trezor I
couldn't match the default MEW address with sample docs in Trezor.

Clicking the default MEW derivation path box, or the custom derivation path
with the same path filled in generates different addresses.


If you use the MEW UI and put a custom path of:

m/44'/60'/0'/0

It indeed matches Trezor. If you click on the MEW default derivation path
box which "displays"

m/44'/60'/0'/0

It seems it actually uses:
m/44'/60'/0'/0/0

This means the default MEW UI is implemented inconsistently or at the very
least the labeling is misleading.

**Comment by folsen** [comment]
@mirage007 Indeed I think the labeling is misleading or confusing. What they show is "the base path" upon which they build the _actual_ address path. But it's not "the path" used to derive the address. However, it makes sense in the context of wanting to generate multiple sub-addresses to use the documented address as the base path to build further paths on.

**Comment by mirage007** [comment]
I guess that just means we are actually not matching MEW in terms of
addresses. If the intent is to do so, it seems we should make:
m44'/60'/0'/0/0 the default. And also probably put a ticket on MEW about at
least changing the language?

**Comment by folsen** [comment]
@mirage007 see https://github.com/paritytech/parity/pull/6815
I agree Parity should mirror what MEW is doing, at least for nothing else but to reduce future confusion. When Parity has path selection it will be easier to give the option to use the base path or some derivation of the base path.
