### ISSUE TITLE
'No space left on device' crash but plenty of free space

### ISSUE THREAD

**Issue by jimmykl** [paritytech/parity#6814]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.8.0-beta-9882902-20171015/x86_64-macos/rustc1.20.0
> - **Operating system**: MacOS 10.13 (17A405)
> - **And installed**: via homebrew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

A few minutes after running parity crashes:

```
stack backtrace:

Thread 'IO Worker #2' panicked at 'DB flush failed.: "IO error: /Users/jimmy/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/090428.log: No space left on device"', src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

[1]    23048 abort      parity --geth --force-ui --min-peers 125 --max-peers 250 --db-compaction ssd
```

The drive which parity is installed on has 30GB free, the blockchain resides on a drive which has 92GB free so I'm not sure what's going on.

**Comment by 5chdn** [comment]
this is going on #6280  :)
