### ISSUE TITLE
Can parity be used for ETC?

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6816]
Can parity be used for ETC? If yes, how to config for it?
Thanks

**Comment by 5chdn** [comment]
Yes. `--chain classic`

**Comment by gaoxiangxyz** [comment]
Thanks @5chdn 
Does parity have plan of a long term support for classic chain? I find parity is not in the client list of  [ETC wiki](https://github.com/ethereumproject/wiki/wiki)

**Comment by 5chdn** [comment]
That's the ETH wiki copied to ETC and not updated.

The classic chain was implemented right from the beginning and is still maintained by @whilei @splix @sjmackenzie et al.

**Comment by whilei** [comment]
Thanks for the heads up -- I will update that today.
