### ISSUE TITLE
Feature Request: Tell the user to update software, when update is needed.

### ISSUE THREAD

**Issue by tshachaf** [paritytech/parity#6820]
**Feature Request:** Tell the user to update software

**Problem:** I was running Parity 1.70 for the last few days and it would not sync. 
     (Today I figured out I needed to update to a newer version so I updated to 1.77, and it is working.)

**Solution:** Parity should check while running if its version is OK or an update is needed, and should notify the user if it needs to be updated.

Thank You.

**Comment by 5chdn** [comment]
There is an update button that shows up as soon as an update is available.

https://github.com/paritytech/parity/wiki/Automatic-Updating

This feature had issues and is fixed with 1.7.7.
