### ISSUE TITLE
Method not found when use web3.eth.traceTransaction on web3 console of parity.js

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6822]
parity config as below:
parity.exe --no-warp --pruning archive --tracing on --base-path d:\parity --ui-no-validation --rpc --rpcapi rpc,eth,net,parity,web3,traces 

17:58:39.192
[HMR] connected
>
17:58:59.914
web3.eth.traceTransaction("0xc63c8f6c0f95582cc68be61eb8b850ccf391f56269c1a6e8c48bea5dbd3ce6e9")
✖
17:59:00.516
Error: Method not found

Thanks

**Comment by 5chdn** [comment]
trace_transaction is in traces module not in eth.

https://github.com/paritytech/parity/wiki/JSONRPC-trace-module#trace_transaction

what are you using to call that?
