### ISSUE TITLE
how to uninstall Parity 1.8.0-beta which install by $ bash <(curl https://get.parity.io -kL) and install Parity 1.7.7-stable

### ISSUE THREAD

**Issue by tonywang5671** [paritytech/parity#6831]
Hello all......I am trying to run tutorial from https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial but it is fail because error Spec json is invalid: missing field `gasLimitBoundDivisor` when I start Parity.

I though it may cause by Parity 1.8.0-beta.....so I would like to uninstall it and install Parity 1.7.7-stable to see if it is the problem. But I can not find how to do that.

Is there anyone can advise? I am new to Parity, many thanks!

**Comment by 5chdn** [comment]
Just go to https://github.com/paritytech/parity/releases and get the version you desire.

The one-line installer always defaults to latest beta.
