### ISSUE TITLE
One line installer on latest OSX 10.13

### ISSUE THREAD

**Issue by maaktweluit** [paritytech/parity#6835]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: stable
> - **Operating system**: MacOS
> - **And installed**: one line install script

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
---

Actual:
```
$ bash <(curl https://get.parity.io -kL)
# install messages without errors, seems good

$ parity --version
parity not found.
```
Expected:
```
$ parity --version
v1.7.7
```

Small note is that a keychain error is popping up, not sure if its related but it only gives the option to reset my whole keychain, hitting cancel a lot of times removes the popup.

**Comment by Office-Julia** [comment]
Hello.
Have you tried open new terminal tab before running 'parity --version' command?

**Comment by Office-Julia** [comment]
If it doesn't work try adding Parity to your ~/.bash_profile or may try using relative path instead: 
/Applications/Parity\ Ethereum.app/Contents/MacOS/parity --version

**Comment by maaktweluit** [comment]
Just tried it in a new tab, no results.

After calling it from the full path it works!

Should i change this issue into something about not adding to path?

**Comment by maaktweluit** [comment]
P.S. I'm using `zsh`, maybe this breaks it?
