### ISSUE TITLE
personal_newAccount very slow

### ISSUE THREAD

**Issue by AdvancedStyle** [paritytech/parity#6839]
> I'm running:
>
> - **Parity version**: Parity/v1.9.0-unstable-52e2adc-20171019/x86_64-linux-gnu/rustc1.21.0
> - **Operating system**: Ubuntu 16.04.3 LTS
> - **And installed**: from source

Actual behavior:
When operating with a large keystore the personal_newAccount call gets extremely slow.  It can take up to 1 minute or more to generate 1 new keyfile.   (Tested with 150,000 keys)

Expected behavior:
personal_newAccount call should probably take less than 1 second to generate a key.

**Comment by Office-Julia** [comment]
Hello.
You've created a similar issue 4 days ago:
https://github.com/paritytech/parity/issues/6787

And there you mentioned you're using 'master' branch:
https://github.com/paritytech/parity/pull/6827

May I ask which parity version and branch you are actually using at the moment where you experience these problems?

**Comment by AdvancedStyle** [comment]
Issue occurs on all versions that I can remember...on 1.7.2, 1.7.6, 1.8.0, 1.9.0.  But just did not bring it up before it.

**Comment by AdvancedStyle** [comment]
Issue occurs on all versions that I can remember...on 1.7.2, 1.7.6, 1.8.0, 1.9.0.  But just did not bring it up before it.

**Comment by AdvancedStyle** [comment]
After installing PR #6827 and delete/rsyncing the chain then this issue is fixed also.
