### ISSUE TITLE
Does parity client verifies transactions in the block when it syncs?

### ISSUE THREAD

**Issue by wjcloud** [paritytech/parity#6846]
Hello here!
I am the head developer of Ethereum Vega and I'd like to implement our chain params for parity!

Well I am new for parity or rust lang, I'd like to know that does parity client verifies transactions in the block when it syncs.

So go-ethereum verifies signatures of the transactions in the block therefore we needed to change a total structure of our go-client to work out because we had changed the chain_Id value. https://github.com/EthereumVega/weth/commit/aeb9578291db4848b393577394983f3a4ec8b6b7 

If parity doesn't verify transactions in blocks when it syncs, we can adopt our chain easily by changing chain_id value, however, if parity verifies it and throws an error like BAD BLOCK, we need to find the way.

Please give me some advice. I will happily wait for the support.

**Comment by rphmeier** [comment]
Yes, Parity verifies signatures and executes transactions when it syncs (unless in light client mode). Which part of that exactly is the issue? It may still be possible to configure parity for your use case.
