### ISSUE TITLE
Very weird display after failed import

### ISSUE THREAD

**Issue by tjayrush** [paritytech/parity#6849]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
1.7.7
> - **Operating system**: Windows / MacOS / Linux
MacOS
> - **And installed**: via installer / homebrew / binaries / from source
homebrew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I tried to import an old gnosis wallet using Parity's http://127.0.0.1:8180/#/accounts interface using the "+ Wallet" "JSON file" option. It allowed me to make a password and select a file with no problem, but when I submitted it returned something like "Invalid file".  All okay so far.

When I closed that screen and returned to the display of all my accounts I got this screen (note that I removed all the identifying information (I hope)).

<img width="1100" alt="screen shot 2017-10-21 at 12 50 09 pm" src="https://user-images.githubusercontent.com/5417918/31853962-cef166d4-b65f-11e7-9e6e-75d00f0a08a7.png">

Every account has this weird IBZ..... mumbo jumbo.  Very disconcerting. I closed my browser and returned to that screen and everything looks okay now. I did not try to repeat the action for fear of a worse outcome.

**Comment by 5chdn** [comment]
#5485 :D

![](https://upload.wikimedia.org/wikipedia/commons/3/3b/Marmot-edit1.jpg)

#5660

Probably an extension or some Javascript injection. The only google search result is this weird JS snippet in an Irish Mediation Meetup.... https://www.meetup.com/Meditation-Sahaja-Yoga-Waterford/events/240792689/?eventId=240792689

Can you wipe your disk and try again? (Just kidding, no idea really.)

**Comment by tjayrush** [comment]
I wiped my disk on your advice....still has the same problem....all my eth is gone!!!....and yet the issue is closed....

I'm just kidding...since you did...none of that happened.

So you're saying not Parity's problem? Thought it was worth reporting anyway. Cheers.
