### ISSUE TITLE
Unregister CAL on Kovan Testnet

### ISSUE THREAD

**Issue by kristiano92** [paritytech/parity#6850]
Hello,
I would like to unregister CAL on Kovan Testnet, because I made a mistake and I only created 1 CAL but I wanted 100 000 000 CAL. My address is 0x0094C156c24CD6D3b78bF8eA609B45B9602C8D5C. Contract address is 0x667278C5e28E40076b6F9206FEd2504d5F143B8c. I really need this TLA. Please help me resolve it.

**Comment by Office-Julia** [comment]
Could you please provide more details for this issue?
Which version of Parity / operating system are you using?
Are you using any custom configuration file or running parity with additional flags beside --chain kovan?

**Comment by kristiano92** [comment]
Parity 1.8.0/Windows
No, only --chain kovan
Do you need more details ?

**Comment by Office-Julia** [comment]
Kovan is a testnet, so actually there is no need to remove anything created by mistake. 
You can create 100 000 000 CAL right away.

**Comment by keorn** [comment]
Testnet does not make it possible to reregister tokens at will.

**Comment by kristiano92** [comment]
Token TLA - CAL is already registered. I can't create 100 000 000 CAL. @5chdn told me that it is possible to unregister.

**Comment by rphmeier** [comment]
@keorn Kovan has a different contract for the registry than mainnet? We might want to redeploy.

**Comment by keorn** [comment]
Yes, the node pulls from the chain that it syncs with.
