### ISSUE TITLE
RPC raw transactions are being lost when running dev chain

### ISSUE THREAD

**Issue by jmontineri** [paritytech/parity#6851]
> I'm running:
>
> - **Parity version**: 1.8.1
> - **Operating system**: Same issue on Windows and Linux (through WSL)
> - **And installed**: Windows via installer, Linux from binaries

The issue occurs when using a local development chain, using InstantSeal. When sending multiple successive raw transactions through RPC, some transactions are processed correctly while others simply disappear. There is no error in the console, the transactions never appear there, and they are never mined. The transaction hash is however returned correctly over RPC.

The code generating those transactions works flawlessly on older versions of Parity, such as 1.7.2 and 1.7.4.

---

**Comment by Office-Julia** [comment]
Thanks for reporting the issue.
Are you fully synchronised? Which flags you run Parity with? 

Please notice that version 1.8.0 and 1.8.1 are still in Beta, latest stable release is Parity 1.7.7-stable.
Could you please check if same problem appears on the latest stable version? (1.7.7)

**Comment by jmontineri** [comment]
Syncing isn't relevant here, I am running a purely local chain. I will try again using 1.7.7 as soon as I can.
