### ISSUE TITLE
Identity Parameter no longer working

### ISSUE THREAD

**Issue by MysticRyuujin** [paritytech/parity#6852]
I've been using the `--identity=` for many releases now but it looks like somewhere around v1.7.6 or v1.7.7 (possibly earlier...) the parameter stopped being passed in the node information...

I was on v.1.7.7 earlier today when I noticed it, I updated to `Parity/v1.8.1-beta-0e4a06d-20171020/x86_64-linux-gnu/rustc1.21.0` and it still seems to be missing when I look at it in my peer list...

I can identify my own node by the use of the internal private IP but the name no longer includes my identity specified in the parameter

**Comment by Office-Julia** [comment]
Hello. Could you please share the following information:
1. Which version of Parity are you running? ("master" or "git" is not a version)
2. Which operating system(s) are you running?
3. How did you install Parity? (binary, installer, from source, which branch?)
4. What flags are you running Parity with? (including passed --identity= value)
5. Do you use any custom config file?
6. Please, share the exact error message (if you get any), or provide logs

**Comment by MysticRyuujin** [comment]
1. `Parity/v1.8.1-beta-0e4a06d-20171020/x86_64-linux-gnu/rustc1.21.0`

2. Ubuntu 16.04.3 x64

3. Official deb package

4. --identity MysticRyuujin-PARITY01 --ui-interface <redacted> --ui-hosts all --port 30302 --nat extip:$(curl -s ipinfo.io/ip) --reserved-peers /root/parity-reserved-peers --jsonrpc-interface <redacted> --jsonrpc-hosts all --ws-interface <redacted> --ws-origins all --ws-hosts all --no-secretstore

5. No

6. No errors

**Comment by rphmeier** [comment]
Probably related to #2066. @MysticRyuujin can you try with the identity in quotes and can you clarify whether you run with `--identity=` or just `--identity`? the parser might not handle those cases exactly the same.

**Comment by MysticRyuujin** [comment]
So my CLI options are exactly as above, just `--identity` with a space then the string. I modified the startup script to include quotes around the string but that did not change the behavior and in fact the running process shows no quotes (still) which makes sense as the bash interpreter is consuming the quotes anyway.

```
chase@PARITY01:~$ ps -ef | grep parity
root        993    963 59 08:18 ?        00:00:19 /usr/bin/parity --identity MysticRyuujin-PARITY01
```

Shortened for brevity

I then tested `--identity=MysticRyuujin-PARITY01` which results in:

```
root@PARITY01:~# ps -ef | grep parity
root       1052    974 64 08:21 ?        00:00:16 /usr/bin/parity --identity=MysticRyuujin-PARITY01
```

For completion I tested with `--identity="MysticRyuujin-PARITY01"` as well, no change

```
chase@PARITY01:~$ ps -ef | grep parity
root        978    944 50 08:25 ?        00:00:41 /usr/bin/parity --identity=MysticRyuujin-PARITY01
```

In call cases my Geth client only shows this:
`name: "Parity/v1.8.1-beta-0e4a06d-20171020/x86_64-linux-gnu/rustc1.21.0"`

I suppose it's possible that the issue is actually on the Geth side. Is there a debug trace I could run to see what my node is sending as an identity / hello message?

I'm under the impression that the recent merges should be rejecting invalid CLI options and not ignoring them, so I think all of these are "valid" they're just not doing anything 😄 or it's Geth...

**Comment by MysticRyuujin** [comment]
Actually I have my node connected to EthStats.net too and when I hover over the node I see
Parity**//** as if there's nothing in the identity field. So I don't think it's a Geth issue...

**Comment by MysticRyuujin** [comment]
@rphmeier Anything else I can do to help verify the bug?

**Comment by MysticRyuujin** [comment]
This hasn't changed as far as I'm aware:

Run a Parity node with the `--identity` parameter, then check its name against a peer:

I run with `--identity "MysticRyuujin-PARITY01"`

But my peers only see:
```
name: "Parity/v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0",
```

They should see:
```
name: "Parity/MysticRyuujin-PARITY01/v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0"
```

On ethstats.net you used to see the identity under 'node type' field, however for Parity you just see:
`Parity//v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0` two slashes at the front because the identity is blank?

ethstat.net may or may not be related as Geth has ethstat.net built in, no need to configure that pm2 task or set identity in the app.json file. Harmony doesn't allow for an identity parameter (as far as I can tell and I'm the only one running a node connected to ethstats.net anyway). So the --identity and the name passed to ethstat.net for Parity is probably unrelated, or only partially connected.

`--identity` does nothing as far as I can tell - I see zero reference to the identity I pass anywhere in the client and it no longer provides peers with whatever I pass it.
