### ISSUE TITLE
Parity never loads the transaction history, not any past transaction detail shown

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#6853]
_Before filing a new issue, please **provide the following information**._

    I'm running:

        Parity version: 1.7.6
        Operating system: Windows
        And installed: via installer

Description::
Open the Accounts tab, click on your available Ethereum account

Expected result::
account information is displayed with full transaction history 
-------------
Actual Bug::
There is not any past transaction information displayed, not any history. After opening an account, I see for c. 3seconds the "loading" symbol at the spot where the transaction history should be displayed. But the loading symbol always disappears after c. 3seconds without having loaded anything. 
-------------

My wallet is always fully synched, open and active for many hours, longer than 1day, still never saw my transaction history! 

Why is this essential account information missing, how can we fix so that all sent and received transactions are displayed properly?

Thank you very much for any solution

**Comment by Office-Julia** [comment]
Hello. Could you please share more details on this issue:
Parity Issue-Checklist
1. Have you tried turning Parity client off and on again?
2. Have you tried to upgrade to 1.7.7? It's Parity latest stable release version.
3. Which version of Windows are you using now?
4. What flags/params are you running Parity with?
5. Do you use any specific config file?
6. Please, share the exact error message if there is any or your logs 
7. Could you double check are you connected to any peers at the moment when problem occurs?
8. What's your time? Is it synchronised to time.is ?

**Comment by slothbag** [comment]
Could this be related to the broken filters? https://github.com/paritytech/parity/issues/6637

**Comment by zumbatan** [comment]
@slothbag  @Office-Julia 
thanks for reply, here more details:


    Have you tried turning Parity client off and on again? yes, often
    Have you tried to upgrade to 1.7.7? It's Parity latest stable release version. - no (but shouldn't it also work with 1.76?) ->In my view this seems to be a global bug coming and going, because until now i have seen this issue on EVERY past version.

    What flags/params are you running Parity with? -i am on ethereum foundation server
    Do you use any specific config file? no
    Please, share the exact error message if there is any or your logs. - there is not any error
    Could you double check are you connected to any peers at the moment when problem occurs? - i am always connected to several peers
    What's your time? Is it synchronised to time.is ?  my time is never synched (always about 50 to 500ms). but there is another open bug for this time synch issue, too, i guess.  But this should not be the trigger for the missing transaction historiy, right? because the tx history was displayed sometimes although time was not in sync.


I can imagine displaying the transation history should not be any issue, at the end it is just past, static data to be fetched/retrieved from etherscan.  why is it strongly malfunctioning? Any ideas for the cause? Do you know of other users who observed this?

**Comment by 5chdn** [comment]
Probably issues with Etherscan-API.

**Comment by a1654** [comment]
I'm having exact same issue; any solutions here?

**Comment by jacogr** [comment]
The way it operates is that it gets the hashes from Etherscan and then tries to find the blocks on the local node. If these are pruned/not available, it won't display. (e.g. currently for me it only displqays the tx's made in the last 1k blocks)

Fixable by falling back to the Etherscan values when not in the local node - however would need to be done for 1.10 with applicable backports.

**Comment by vveljk** [comment]
I have the same problem....some transactions are visible and some are not. Could it be possible that DB is partly corrupted? I also don't see any Altcoin and I could see them like week or two ago.
Is there any solution to recheck DB and fix it if needed? Or do I need to make full sync again in order to solve this issue?

**Comment by Eriksn1970** [comment]
I have the same issue: using version 1.7.8 and always could see my tokens, but since 2 days not anymore?
It's fully synced, time ok. What should I do?

**Comment by 5chdn** [comment]
Token balances will be fixed with 1.9.1 and 1.8.8 - apparently the token registry is too big right now this causes issues.
