### ISSUE TITLE
Parity 1.8.1-beta crashs on start if any start param is given

### ISSUE THREAD

**Issue by Onkovat** [paritytech/parity#6858]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.1beta
> - **Operating system**: Windows 97 pro 64bit
> - **And installed**: via binaries 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

actual... parity tray shows up in tray and vanishs
expected behaviour... parity starts as it started before and is using the params given

"P:\Ethereum Parity\Parity\ptray.exe" ui --db-compaction hdd --mode active --tracing off --pruning fast --cache-size 512 --max-peers 150 --min-peers 125 --reserved-peers reserved.txt --warp --ntp-server ptbtime3.ptb.de:123

That's the path I used till now with a previous version. Now it is crashing regardless of which option is there. Only without options it works. Though I have a hybrid disc so partiy is syncing slow while it could have used hdd compaction for example.

How to use the params now?

**Comment by Office-Julia** [comment]
Hello.
Can you please share exact error message?

**Comment by arkpar** [comment]
@Onkovat try removing `--warp` as it is enabled by default now.

**Comment by Onkovat** [comment]
@Office-Julia can you please tell me where to find or how to enable error messages? I failed to add the params on a start command a month ago when I created this setup so I started a .lnk file which contains the params. So I do not have a batch that shows something. It probably would close anyway. Or can I start the .lnk and write the outputs of ptray into a file even though lnk is between?

@arkpar that doesn't help.

**Comment by arkpar** [comment]
@Onkovat could you try running `"P:\Ethereum Parity\Parity\parity.exe"`  with the same arguments in the console and post the error message if any?

**Comment by arkpar** [comment]
Also try moving "ui" to the end of the command line:

```
"P:\Ethereum Parity\Parity\ptray.exe" --db-compaction hdd --mode active --tracing off --pruning fast --cache-size 512 --max-peers 150 --min-peers 125 --reserved-peers reserved.txt  --ntp-server ptbtime3.ptb.de:123 ui
```

**Comment by Onkovat** [comment]
@arkpar I was able to start it with ui at the end and with the last 2 params taken out. I then tried with console and parity.exe. Taking out --reserved-peers reserved.txt resulted in nothing happening. the parity shell didn't open. The same happened with the --ntp-server ptbtime3.ptb.de:123 param.

Not sure what happened but both of them did fatally break something on start. reserved.txt is empty cause I never found a list of good nodes somewhere. Might be new version can't handle that. And the time sync check seems to run now automatically by parity.

What works is the following and it takes the params. Checked with min peers.

start "" "P:\Ethereum Parity\Parity\parity.exe" --db-compaction hdd --mode active --tracing off --pruning fast --cache-size 512 --max-peers 150 --min-peers 125 ui

**Comment by Onkovat** [comment]
@arkpar well, judging from the cpuusage I have to assume that the hdd encryption part is not used. Except somehow it was possible to lower harddisc usage and cpu usage a lot. HDD was on full work anyway with the old version also so I can't tell.
