### ISSUE TITLE
account verification via SMS or email fail

### ISSUE THREAD

**Issue by HuguesDohmen** [paritytech/parity#6859]
_Before filing a new issue, please **provide the following information**._

> I'm running: windows 10
>
> - **Parity version**: 1.7.7
> - **Operating system**: Windows
> - **And installed**: via installer

Installed parity today.
I tried to verify my account but it returns this message:
Failed to fetch the contract: Certifier smsverification does not exist.
---

**Comment by Office-Julia** [comment]
May be related to:
https://github.com/paritytech/parity/issues/4782

**Comment by Tbaut** [comment]
Duplicates https://github.com/paritytech/parity/issues/8312
