### ISSUE TITLE
account verification

### ISSUE THREAD

**Issue by HuguesDohmen** [paritytech/parity#6865]
_Before filing a new issue, please **provide the following information**._

> I'm running: windows 10
>
> - **Parity version**: 1.7.7
> - **Operating system**: Windows
> - **And installed**: via installer / 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
Verifying  (sms verification) account results in: Failed to fetch the contract: Certifier smsverification does not exist.

Parity is not fully synced yet, but I suppose this cannot cause the problem
---

**Comment by tomusdrw** [comment]
Actually SMS certification requires a synced chain to work for many reasons:
1. Address of certification contract (taken from registry)
2. Checking if an account/number is already verified
3. Sending a transaction with valid nonce.

Please re-try after you are fully synced.
