### ISSUE TITLE
Propagate mempool transactions to all reserved peers

### ISSUE THREAD

**Issue by LogvinovLeon** [paritytech/parity#6869]
> I'm running:
>
> - **Parity version**: latest master
> - **Operating system**: MacOS
> - **And installed**: from source

---
Parity randomly shuffles peers and then chooses the peers it propagates the pending transaction to.
I think - it makes sense to always propagate the transaction to reserved peers first and then do the same.

My use case for that:
I want to have an accurate mempool representation. I have multiple nodes in multiple parts of the world. They're connected as reserved peers. But I get a much more complete mempool if I manually fetch the mempools from all of them instead of fetching it only from a single node.
I guess - it's because the propagation algorithm is randomized.

**Comment by 5chdn** [comment]
It's not on the roadmap, yet.
