### ISSUE TITLE
Parity not launching

### ISSUE THREAD

**Issue by egferro** [paritytech/parity#6872]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: I tried them all
> - **Operating system**: Windows 
> - **And installed**: via installer / 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
I used to use parity and it was working. Then I had to uninstall it. Since then I tried installing every release but when I launch the program it does not appear in the list of processes , it does not start the browser and when I write the 127.0...address in the browser it says it cannot connect. I checked all network settings. 
Can anyone offer some help please?
Thanks.
EF.
---

**Comment by Office-Julia** [comment]
Hello.
May I ask if tray icon appeared? (top right corner on OSX, bottom right corner on Windows)? 
Which port do you try to connect on 127.0.0.1?
Could you please share your Parity logs?
