### ISSUE TITLE
Nicer token display support

### ISSUE THREAD

**Issue by jedahan** [paritytech/parity#6881]
running Parity 1.8.0 on macOS installed via homebrew

I have a few accounts that have 0 ETH and some amount of an ERC20 token

In these cases, maybe parity UI should default to having the token balance first (and expanded), and the ETH balance hidden (mouseover to expand)

How do we feel about this?

**Comment by Tbaut** [comment]
Stale issue. Moving to the new reop, we will not migrate low prio issues.
