### ISSUE TITLE
Can't upgrade macOS after v1.7.0

### ISSUE THREAD

**Issue by cryptogineer** [paritytech/parity#6884]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: MacOS
> - **And installed**: via installer

Prior to v1.7.0, an "Upgrade" link always showed up on the bottom left status bar.  Now I'm stuck on v1.7.0 at the pre-byzantium block (4,370,000) and no upgrade link.  How do I upgrade without losing my wallets and vaults?

**Comment by Office-Julia** [comment]
Hello. Let me assist with your issue.

Please note version 1.8.1 is not the latest one.
Our latest Beta release is 1.8.2,
and latest stable release is 1.7.8.
Please kindly let us know if you tried to install these versions and if the problem happens there again?

Personally I would recommend to upgrade o 1.7.8, nothing will be lost - your keys, wallets, etc. remain safe by simply upgrading.

Reference: https://github.com/paritytech/parity/releases

**Comment by 5chdn** [comment]
There was a hard-fork on block 4370000.

The Updater users a on-chain smart contract to check for new versions. If your chain is out of sync, you will have to manually upgrade your client.
