### ISSUE TITLE
RPC API result issues

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6887]
> I'm running:
> - **Parity version**: v1.8.0-beta-9882902-20171015
> - **Operating system**: Windows
> - **And installed**: via installer

1. The "status" of result of eth_getTransactionReceipt is always null.
2. The "result[i].result.gasUsed" of trace_transaction is always 0 for value transfer.
3. If a contract call transaction failed (for example, "Bad Instruction"), the result of trace_transaction for the transaction has no "result" field, but actually the transaction is mined, so there should be a "gasUsed" for it.

**Comment by LogvinovLeon** [comment]
The status is null only for pre-Byzantinium transactions.
Unfortunately it's 1 or 0 for post-Byzantinium, which is not standard-compliant as standard requires it to be represented as a hex `0x1` or `0x0`
https://github.com/ethereum/wiki/wiki/JSON-RPC#example-31

**Comment by gaoxiangxyz** [comment]
@LogvinovLeon thanks

**Comment by gaoxiangxyz** [comment]
@LogvinovLeon I create a private chain and the status of transaction that eth_getTransactionReceipt returned is still null. What is the definition of post-Byzantinium transaction on private chain? Does it mean the transaction in the block  whose number is larger than about 4,370,000?

**Comment by tomusdrw** [comment]
@gaoxiangxyz You can configure transitions in your spec file, see https://github.com/paritytech/parity/blob/3e5d9b92c19d50493364bee68c2a54c85e37518d/ethcore/res/ethereum/foundation.jsonL158

**Comment by 5chdn** [comment]
Related? #6911

**Comment by tjayrush** [comment]
@tomusdrw Missing link above.

**Comment by gaoxiangxyz** [comment]
@5chdn no, I can get result, just some fields have problem

**Comment by gaoxiangxyz** [comment]
@tjayrush https://github.com/paritytech/parity/blob/3e5d9b92c19d50493364bee68c2a54c85e37518d/ethcore/res/ethereum/foundation.json#L158

**Comment by gaoxiangxyz** [comment]
@tomusdrw After I add "eip658Transition": 437 (current block number is 110000+) to the chain-spec file and do sendTransaction,  there is  an error in log as below and the connection between parity and a geth miner node breaks. Does it mean I must start a new private chain and lost all blocks have mined in my old private chain if I want to do this change to the chain-spec file?

```
2017-11-08 21:00:21  Stage 5 block verification failed for #111489 (9ec8…91dc)
Error: Block(InvalidReceiptsRoot(Mismatch { expected: 9a29713efe4a8f4c12964beea9
c7056605394899d853f9a11a2585b6e9e909f8, found: 056b23fbba480696b65fe5a59b8f2148a
1299103c4f57df839233af2cf4ca2d2 }))
```

**Comment by tomusdrw** [comment]
@gaoxiangxyz sorry, just noticed your message. Glad you found the solution, indeed you need to fork the network by setting the transition block in the future.

**Comment by AyushyaChitransh** [comment]
The same problem exists in private chains too! I am using the fix as described by @gaoxiangxyz After I create `eip658Transition` in my genesis file and set its value to my current block number, it gives correct `status`.

**Comment by lght** [comment]
@tomusdrw @5chdn does @gaoxiangxyz's solution resolve this issue, or is there still work to be done?

**Comment by gaoxiangxyz** [comment]
@lght my solution is only for resolve issue 1, which makes status is not null.

**Comment by gaoxiangxyz** [comment]
@lght my solution is only for resolve issue 1, which makes status is not null.

**Comment by JokerCatz** [comment]
Hi , did version 1.9.6_stable is merge this ? I get status is null of eth_getTransactionReceipt in dev chain ...

**Comment by Tbaut** [comment]
@JokerCatz As explained in the comments above, adding `eip658Transition`, [as seen here](https://github.com/paritytech/parity/blob/3e5d9b92c19d50493364bee68c2a54c85e37518d/ethcore/res/ethereum/foundation.json#L158), with a block number in the future will let you see the status field as wished (starting from this block).

**Comment by Tbaut** [comment]
@JokerCatz [The dev chain](https://github.com/paritytech/parity/blob/master/ethcore/res/instant_seal.json) does have this eipTransition. Tested with v1.10.1 and the status is present and not null. Your problem seems not related to this issue, please open a dedicated one if you can't figure out what's wrong.

**Comment by JokerCatz** [comment]
@Tbaut I use latest stable version (1.9.6 stable) and default dev chain ... so this will not fix in 1.9.x version?

**Comment by Tbaut** [comment]
I'm not sure if it's related to the client or to the chain spec. Just can you try to copy [this file](https://github.com/paritytech/parity/blob/master/ethcore/res/instant_seal.json) on your computer, and launch parity with `--chain /path/to/file.json`?

**Comment by JokerCatz** [comment]
yep , I know & I tried it and succeeded by add `eip658Transition` or just use latest version of `instant_seal.json` ... but I think just merge the fix then latest "stable version" will be work , right? ...

**Comment by Tbaut** [comment]
@Joker, the next release will be in less than 2 weeks so I don't think we'll add this to a minor one considering the workaround.

**Comment by folsen** [comment]
@gaoxiangxyz Closing this issue as 1) is a misconfigured spec file, please report separate issues for 2) and 3) if the problem still exists. It seems like 2) and 3) is the result of running Parity without `--tracing on`.
