### ISSUE TITLE
Wiki: Development chain issue 

### ISSUE THREAD

**Issue by DeRain** [paritytech/parity#6894]
https://github.com/paritytech/parity/wiki/Private-development-chain#customizing-the-development-chain

In example of private network config shoud be following configuration:

`"engine": {
    "instantSeal": null
  },`

**Comment by Office-Julia** [comment]
Hello. Let me assist you in resolving this issue.

The config definition is correct.

However could you please share more information to resolve your problem:
1. Have you tried turning it off and on again?
2. Are you fully synchronized?
3. Which version of Parity are you running? ("master" or "git" is not a version)
4. Which operating system are you running?
5. How did you install Parity? (binary, installer, from source, which branch?)
6. What flags are you running Parity with?
7. Do you use any config file?
8. Please, share the exact error message!
9. Is there anything in the logs?
10. Are you connected to any peers?
11. What's your time? Is it synchronized? time.is

**Comment by 5chdn** [comment]
Upgrading to the latest version does probably solve this issue.
