### ISSUE TITLE
In PoA 1.8.1 txs from non-validator nodes are not mined

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#6898]
Hello

> I'm running:
>
> - **Parity version**: 1.8.1-beta-0e4a06d-20171020/x86_64-linux-gnu/rustc1.21.0
> - **Operating system**: Linux Ubuntu 16.04
> - **And installed**: via deb package

We have a private PoA network with validation via safeContract.
When I start local node, connect to the network and make a transaction e.g. send money to myself, this transaction is not mined. It will be mined only if I run the node as a validator.
We tested also on parity 1.7 and it works both for validator's node and non-validator's node. Could it be that configuration needs to be changed in some way?

Here is my node.toml (non-validator)
<details>
<pre>
[parity]
chain = "spec.json"
base_path = "parity"
[network]
bootnodes=[]
nat="extip:<IP address here>"
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
interface = "0.0.0.0"
port = 8180
[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]
[dapps]
cors = "all"
interface = "0.0.0.0"
hosts = ["all"]
port = 8080
[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"
[misc]
logging = "sync=trace"
log_file = "parity.log"
</pre>
</details>

[Here](https://raw.githubusercontent.com/oraclesorg/oracles-scripts/sokol/spec.json) is our spec.json

**Comment by phahulin** [comment]
Could someone please take a look if this is a bug or a misconfiguration?

**Comment by keorn** [comment]
Validator accepts own transaction regardless of gas price, you can either submit higher gas price or run the authority with `min_gas_price = 0`
