### ISSUE TITLE
Parity compile failing due to commit 0abc2b1374f4746dc2ae3f3587f414d1525279aa

### ISSUE THREAD

**Issue by NiklasKunkel** [paritytech/parity#6900]
> I'm running:
>
> - **Parity version**: Latest commit on master (0abc2b1374f4746dc2ae3f3587f414d1525279aa)
> - **Operating system**: Ubuntu 10.04
> - **And installed**: via source through rustc 1.21.0 (3b72af97e 2017-10-09)

Cloned latest commit on master on Ubuntu 10.04 and compiled via cargo.
Compile fails:

```
Compiling parity-ui-precompiled v1.9.0 (https://github.com/paritytech/js-precompiled.git#9ad7b443)
error: Could not compile 'parity-ui-precompiled'.
```

**Comment by tomusdrw** [comment]
Can you try with `cargo clean && cargo build --release --verbose`?

**Comment by 5chdn** [comment]
> Ubuntu 10.04

:scream:
