### ISSUE TITLE
JSON-RPC eth_call with strange results

### ISSUE THREAD

**Issue by panicape** [paritytech/parity#6901]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: v1.7.0-beta-5f2cabd-20170727
> - **Operating system**: ubuntu 16.05
> - **And installed**: via installer 

Hi everyone:
I was trying to use eth_call and it gives me strange results:
i have created a contract that only do an add:

Modify:
(sorry i writted here so fast that i didn't took in a count what i wrote)

contract Test {
      function sumar(uint256 a, uint256 b) returns (uint256) {
            return (a + b);
      }
}

i upload this contract in kovan chain and when i try to use eth_call to call sumar Method enconding it with sha3 and its parameters as hexadecimals i get this query (same way as tutorial):
0xfd61371e00000000000000000000350000000000000000000037
The first 4 bytes are from encoded method signature and the last part are from its parameters.
The result i got is this:
0x0000000000000000000035000000000000000000003700000000000000000000
When i change numbers it only change it into the return but it doesn't seem to be a trustful result. 
Is it something wrong? i try it in different ways and it was the best result i got.
---

**Comment by tomusdrw** [comment]
The code does not look valid at all (`b` is missing, there is no `returns` nor `constant`, also `public` modifier is missing).
Can you post a complete example?

It would also be helpful to run Parity with `-lrpc=trace` and post the exact `eth_call` being made to Kovan contract so that we can reproduce the issue.

**Comment by panicape** [comment]
@tomusdrw what do you mean with this public modifier? i have to writte it before "constant" and public is to be returned outside solidity?

**Comment by tomusdrw** [comment]
You should use the latest solidity compiler and add a `pragma` statement to enforce that compiler version. The compiler will let you know where you should put the modifier, but yes it should be something like that:
`public constant returns (uint256)` - it means that the function is:
1. is callable by sending a transaction to it (`public`)
2. Doesn't alter the state (is read-only) and can be queried without blockchain transaction (`constant`)
