### ISSUE TITLE
Trezor can't select address

### ISSUE THREAD

**Issue by xzlt** [paritytech/parity#6908]
Parity 1.8.2 beta use first address as default,  can't select address as in MEW.

**Comment by Office-Julia** [comment]
Hello, could you please answer the following questions:
1. Have you tried turning it off and on again?(Parity client)
2. Are you fully synchronized?
3. Which version of Parity are you running? ("master" or "git" is not a version)
4. Which operating system are you running?
5. How did you install Parity? (binary, installer, from source, which branch?)
6. What flags are you running Parity with?
7. Do you use any config file?
8. Please, share the exact error message!
9. Is there anything in the logs?
10. Are you connected to any peers?
11. What's your time? Is it synchronized? time.is

**Comment by 5chdn** [comment]
@xzlt Yes, selecting the address is not possible yet #3541
