### ISSUE TITLE
How to complie parity source code to build ethstore

### ISSUE THREAD

**Issue by iceVeryCold** [paritytech/parity#6909]
I have tow question:
   question one :
I get the parity source code from github,then i complie the code follow the steps of the document:
   (1)cargo build --release
   (2)~/.cargo/bin/cargo build --release
when finish these steps, I open the file use Xcode on Mac,a kind of "exec" file named parity was came,but the "exec" file named ethstore was not ,now the parity just can be runned from console but not web.
So i want to know how to build the "exec" file named ethstore form source code and open the parity on web. 
question two:
what is the "exec" file named ethstore function and how it compiled from,such as github or other way?

please tell me,thank you very much!!!

**Comment by tomusdrw** [comment]
To compile individual packags you need to run it like that:
```
$ cargo build --release -p <package>
```
So for instance to compile ethstore (with CLI) you need to run
```
$ cargo build --release -p ethstore-cli
```

**Comment by iceVeryCold** [comment]
I follow your advise and compile the ethstore successfully,but when i  run it from Xcode on Mac,an error comes :
[1;31merror:[0m Found argument '[33m-N[0m' which wasn't expected, or isn't valid in this context

USAGE:
    parity [FLAGS] [OPTIONS] [SUBCOMMAND]

For more information try [32m--help[0m

what is the reason and how can i do to run it successfully?

The next question : How can i do If i want to rewrite the UI code ?After i view the source code , was UI part source code  stored on github,when we compile it ,it was downloaded  and completed to complie. so , if i need to push my UI code to one  github  and define it in "toml" file ?

**Comment by tomusdrw** [comment]
After you compile `ethstore-cli` you will have a separate `ethstore` binary in `./target/release`. So you should run it instead of `parity`:
```
$ ./target/release/ethstore
```

**Comment by iceVeryCold** [comment]
Sorry,I still hava a question:
Now the parity and ethstore were complied successfully,we can run the parity use command ,but if i want show the accounts ,transaction and other something about parity ,what do i run other service ,maybe tomcat nodejs and others?   IN one word ,i just to run it from source code and the result is the same as i run another parity use installer install, what is the command to run?
