### ISSUE TITLE
stack backtrace 1.8 Parity keeps crashing.

### ISSUE THREAD

**Issue by marleydude** [paritytech/parity#6914]
_Before filing a new issue, please **provide the following information**._

> I'm running: 1.8
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows 10
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
====================

stack backtrace:
   0:     0x7ff6ab5496e4 - hid_error
   1:     0x7ff6ab549beb - hid_error
   2:     0x7ff6aad6c6f4 - <no info>
   3:     0x7ff6ab6c2674 - hid_error
   4:     0x7ff6ab6c24e9 - hid_error
   5:     0x7ff6ab6c23c2 - hid_error
   6:     0x7ff6ab6c2330 - hid_error
   7:     0x7ff6ab6cbc4f - hid_error
   8:     0x7ff6aaefa78c - <no info>
   9:     0x7ff6aafcba22 - <no info>
  10:     0x7ff6aaea238b - <no info>
  11:     0x7ff6aaea7f7a - <no info>
  12:     0x7ff6ab6c3c22 - hid_error
  13:     0x7ff6aaefafb6 - <no info>
  14:     0x7ff6ab6c075c - hid_error
  15:     0x7ff899ac2774 - BaseThreadInitThunk

Thread 'IO Worker #0' panicked at 'DB flush failed.: "IO error: fsync failed at Sync() for: C:\\Users\\calle\\AppData\\Local\\Parity\\Ethereum\\chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/049970.sst: The request could not be performed because of an I/O device error.\r\n"', src\libcore\result.rs:860

This is a bug. Please report it at:
---

**Comment by 5chdn** [comment]
Can you please reset your database and try again? Open a command prompt and execute

    "C:\Program Files\Parity\Parity\parity.exe db kill"

**Comment by 5chdn** [comment]
Not much Parity can do about device I/O errors.
