### ISSUE TITLE
maccos 10.11 ?

### ISSUE THREAD

**Issue by makc** [paritytech/parity#6915]
just downloaded macos installer today - it worked, but the app won't start saying
> You have OS X 10.11.6. The application requires OS X 10.12 or later.

what was the last version that could run on 10.11 ?

**Comment by 5chdn** [comment]
Just use homebrew for older macos versions, or upgrade macos :)

**Comment by 5chdn** [comment]
https://github.com/paritytech/homebrew-paritytech#homebrew-paritytech
