### ISSUE TITLE
Spec json is invalid: missing field `gasLimitBoundDivisor` at line

### ISSUE THREAD

**Issue by nmgavhane** [paritytech/parity#6916]
> I'm running:
>
> - **Parity version**: Parity/v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Linux
> - **And installed**:  binaries 

Though I have the  below parameters mentioned in the configuration file
"gasLimitBoundDivisor":"0x400",  "stepDuration": "5".

I am getting the error "Spec json is invalid: missing field `gasLimitBoundDivisor` at line".

while starting the node with parity --config.

---

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity/blob/master/CHANGELOG.md#parity-v180-2017-10-15

> Further, users upgrading from 1.7 should acknowledge the following changes:
>
> -The chain-engine was further abstracted and chain-specs need to be upgraded. #6134 #6591

Move `registrar`, `gasLimitBoundDivisor`, and `eip155Transition` from engine (Ethash/AuthorityRound/etc.) to general params section.

**Comment by nmgavhane** [comment]
Thanks.

**Comment by themandalore** [comment]
Can you guys update the demoPOA to reflect these changes?  
https://wiki.parity.io/Demo-PoA-tutorial.html

**Comment by Tbaut** [comment]
I don't get it, it is in the general params in the wiki: 
![image](https://user-images.githubusercontent.com/33178835/41649381-bbc6ef18-747b-11e8-9c43-22b5b090bcff.png)

**Comment by 5chdn** [comment]
Sorry, I'm blind. :see_no_evil:

**Comment by 5chdn** [comment]
@themandalore please upgrade your node
