### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by danieldevofficial** [paritytech/parity#6919]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows / MacOS / Linux
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---

**Comment by 3esmit** [comment]
?
