### ISSUE TITLE
Wrong type of 'status' field of transaction receipt (v1.8.1)

### ISSUE THREAD

**Issue by msvprogs** [paritytech/parity#6920]
> I'm running:
>
> - **Parity version**: 1.8.1 (also tried 1.8.2)
> - **Operating system**: Windows
> - **And installed**: via installer

I'm trying to get transaction receipt via 'eth_getTransactionReceipt' method using mainnet blockchain. 
Expected behavior:
Response contains 'status' field of type QUANTITY (hexadecimal number - JSON string) as stated here: [Ethereum docs](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt)

Actual behavior:
Type of the 'status' field is an ordinary JSON integer number (decimal). It causes Nethereum library to throw invalid cast exception when deserializing the response.

---

**Comment by sammy007** [comment]
Dealing with rpc of this client is one of the biggest mistake in my life.

**Comment by tomusdrw** [comment]
Related #6887
