### ISSUE TITLE
Brew update gives "Error: Empty installation"

### ISSUE THREAD

**Issue by dfinzer** [paritytech/parity#6923]
> I'm running:
>
> - **Parity version**: 1.6.10
> - **Operating system**: MacOS
> - **And installed**: homebrew

When I attempt to upgrade to 1.7.8 via Homebrew, I get the following issue:

```
brew update && brew upgrade parity
Already up-to-date.
==> Upgrading 1 outdated package, with result:
paritytech/paritytech/parity 1.8.2
==> Upgrading paritytech/paritytech/parity --stable
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.7.8/x86_64-apple-darwin/parity
######################################################################## 100.0%
Error: Empty installation
```

Any ideas?

**Comment by Office-Julia** [comment]
Try running separately

> brew tap paritytech/paritytech & brew update 

and later:

> brew upgrade parity

**Comment by dokterbob** [comment]
Didn't work for me:

```
~ $ brew upgrade parity
==> Upgrading 1 outdated package, with result:
paritytech/paritytech/parity 1.8.2
==> Upgrading paritytech/paritytech/parity --stable
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.7.8/x86_64-apple-darwin/
Already downloaded: /Users/drbob/Library/Caches/Homebrew/parity-1.7.8
Error: Empty installation
```

**Comment by jonnyhsy** [comment]
same error here.

**Comment by 5chdn** [comment]
You are on stable channel, try

`brew install parity --beta`

**Comment by dokterbob** [comment]
Thanks for the tip! 

But that still doesn't fix the bug: brew install --upgrade should not result in an error condition. 

Afri Schoedon <notifications@github.com> schreef op 1 november 2017 22:51:29 GMT+00:00:
>Closed #6923.

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by 5chdn** [comment]
Homebrew raises an "Empty installation" exception if it appeared that no significant files were included during install.

**Comment by dokterbob** [comment]
Yes and it tries to upgrade even though it should not; it goes off to try and install the beta version, which then it doesn't, yielding the exception. 

Afri Schoedon <notifications@github.com> schreef op 2 november 2017 13:32:41 GMT+00:00:
>Homebrew raises an "Empty installation" exception if it appeared that
>no significant files were included during install.

-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by robtg4** [comment]
Has this been solved? I am also having this issue..

**Comment by dokterbob** [comment]
Nope. 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by 5chdn** [comment]
I can not reproduce this. Did you try removing and reinstalling Parity? What steps are required to reproduce this? Can you run brew with `--verbose` and share the log here?

**Comment by dokterbob** [comment]
It seems that, now, a clean install seems to work fine. Will report if subsequent updates fail again.

```
~ $ brew uninstall --force parity
Uninstalling parity... (2 files, 40.7MB)
~ $ brew install -v parity
==> Installing parity from paritytech/paritytech
/usr/bin/sandbox-exec -f /tmp/homebrew20171113-30578-1lfnzwu.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/paritytech/homebrew-paritytech/parity.rb --verbose
==> Downloading http://d1h4xl4cr1h0mo.cloudfront.net/v1.8.2/x86_64-apple-darwin/parity
/usr/bin/curl --show-error --user-agent Homebrew/1.3.7 (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --location --remote-time --continue-at - --output /Users/drbob/Library/Caches/Homebrew/parity-1.8.2.incomplete http://d1h4xl4cr1h0mo.cloudfront.net/v1.8.2/x86_64-apple-darwin/parity
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.8M  100 42.8M    0     0  3643k      0  0:00:12  0:00:12 --:--:-- 6404k
==> Verifying parity-1.8.2 checksum
==> Cleaning
==> Finishing up
ln -s ../Cellar/parity/1.8.2/bin/parity parity
/usr/bin/sandbox-exec -f /tmp/homebrew20171113-30671-mh13t2.sb nice /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/paritytech/homebrew-paritytech/parity.rb -v
==> Caveats
To have launchd start paritytech/paritytech/parity now and restart at login:
  brew services start paritytech/paritytech/parity
==> Summary
🍺  /usr/local/Cellar/parity/1.8.2: 4 files, 42.9MB, built in 23 seconds
```

**Comment by 5chdn** [comment]
We did a minor logic change in the brew script which could have caused this; I do not necessarily see why though. Please let me know if this happens again.

**Comment by sbenario** [comment]
FWIW I'm also seeing the empty installation issue as well. Previously installed stable using homebrew, and now homebrew upgrade results in `Empty installation`. 

Happy to try some other debugging steps to help figure out the issue.

**Comment by 5chdn** [comment]
I'm clueless, how could this commit have caused this: https://github.com/paritytech/homebrew-paritytech/commit/a4002b07bd06b836d5759365d10519e2602e5e1c

Smells like a brew bug. Any ideas?

**Comment by Sjors** [comment]
uninstall and reinstall worked for me as well, maybe as a result of the recent fix.
