### ISSUE TITLE
EthStore insert_derived API has result mismatch with ExtendedKeyPair derive 

### ISSUE THREAD

**Issue by fabware** [paritytech/parity#6924]
> I'm running:
>
> - **Parity version**: Parity/v1.7.7
> - **Operating system**: MacOS
> - **And installed**: from source
> - **Source code reproduce the issue**:  https://bitbucket.org/fabware/parity_store_derive/src/6a19163f1db72d2915e56f8c0da0854c6aa1ae2b/src/main.rs

I'm experimenting parity ethstore and ethkey API lately, and manged to have ExtendedKeyPair generate correct address for standard ETH path: m/44'/60'/0'/0/0. Sadly EthStore insert_derived API gives me different address which is incorrect according to https://iancoleman.github.io/bip39 .

**mnemonic phrase without password**
lemon voice require wisdom rain soft allow sing mule flee fox scare

**actual**
derived address: 0x832576b00d8c16625c2bd0841f894b13f064d667

**expected behavior**
derived address: 0xd610c21cCaAEbe0DFfc256206A9b1C7e89d3DE97

**steps to reproduce**
1. cargo run the source code
2. check last line in output, which has incorrect derived address

I'm fairly new to rust and parity code base, maybe I did something wrong, attach usage snippet of the whole working repository below for a quick look.

```
pub struct U32Derivation(Derivation<u32>);

impl U32Derivation {
    fn child_number(&self) -> ChildNumber {
        match self.0 {
            Derivation::Hard(value) => ChildNumber::Hardened(value - 0x80000000),
            Derivation::Soft(value) => ChildNumber::Normal(value),
        }
    }

    fn derivation(&self) -> Derivation<u32> {
        match self.0 {
            Derivation::Hard(value) => Derivation::Hard(value),
            Derivation::Soft(value) => Derivation::Soft(value),
        }
    }

    fn index_derivation(&self) -> IndexDerivation {
        match self.0 {
            Derivation::Hard(value) => IndexDerivation {
                soft: false,
                index: value,
            },
            Derivation::Soft(value) => IndexDerivation {
                soft: true,
                index: value,
            },
        }
    }
}

fn store_derive(seed: &[u8], paths: &[U32Derivation]) -> Address {
    let secret_key = ExtendedKeyPair::with_seed(seed).unwrap();
    println!("root secret: {:?}", secret_key.secret().as_raw());

    let dir = TransientDir::create().unwrap();
    let store = EthStore::open(Box::new(dir)).unwrap();

    let sref = store
        .insert_account(SecretVaultRef::Root, secret_key.secret().as_raw().clone(), "")
        .unwrap();

    let mut new_paths: Vec<IndexDerivation> = vec![];
    for item in paths {
        let index_derivation = item.index_derivation();
        println!("index derivation: {}, {}", if index_derivation.soft { "Soft" } else { "Hard" }, index_derivation.index);
        new_paths.push(index_derivation);
    }

    let derived = store
        .insert_derived(
            SecretVaultRef::Root,
            &sref,
            "",
            StoreDerivation::Hierarchical(new_paths),
        )
        .unwrap();

    // println!("derived secret: {:?}", store.raw_secret(&derived, "").unwrap().into());
    // remove root account
    store.remove_account(&sref, "").unwrap();
    derived.address.hex()
}
```

**Comment by NikVolf** [comment]
Hi!

you have to use actual u32 for hard derivation (`index + 2 << 30`)

i.e.
`M/0'/1`

is actually 
`[Derivation::Hard(2 << 30), Derivation::Soft(1)]`

our bug is that it does not return error on Hard(0), for example, I will fix it

**Comment by fabware** [comment]
@NikVolf Thanks for your reply. I indeed figured out I have to use actual u32 for hard derivation. It would be much easier to comprehend if you can fix it through.

And I don't think the problem caused by incorrect input of derivation path (which you can tell from the following program output), can you kindly take a look further?

```
phrase: lemon voice require wisdom rain soft allow sing mule flee fox scare
seed: 1a42e1fa51c447c16c6f84e8c8dcfdc10f7474d75e6d4773d24fd3c76f7630f796a2cd15763c5ff16269a2753d57caf95b59a7f218ae306142e8f0a02001e96a
password: 
path: m/44'/60'/0'/0/0
parsed paths: [Hard(2147483692), Hard(2147483708), Hard(2147483648), Soft(0), Soft(0)]

Rust-bitcoin bip32
------------------------
root secret: SecretKey(d0f46b802fb0243924fbea15cd732f6493451d72d2586220059746effc0d538b)
public_key: 04f862c8983f54981f75ef06b60a7d20cb20292e38f85904e3e9da26c1b1e5cbfa18615b1f25b5f07b946126332e44316ce7d63dcf63fd3b2627237494ed3a60fc
private key: 951e7d440c5bb9d8a8ef1d5e5c6b54a81414e61aca4d94b6699b85cd51fe90ae

Parity extended
------------------------
root secret: Secret: 0xd0f4..538b
public_key: f862c8983f54981f75ef06b60a7d20cb20292e38f85904e3e9da26c1b1e5cbfa18615b1f25b5f07b946126332e44316ce7d63dcf63fd3b2627237494ed3a60fc
address: d610…de97
private key: 951e7d440c5bb9d8a8ef1d5e5c6b54a81414e61aca4d94b6699b85cd51fe90ae

EthStore insert_derived
------------------------
root secret: Secret: 0xd0f4..538b
index derivation: Hard, 2147483692
index derivation: Hard, 2147483708
index derivation: Hard, 2147483648
index derivation: Soft, 0
index derivation: Soft, 0
derivation: 2147483692, 2147483708, 2147483648... 
derived address: 832576b00d8c16625c2bd0841f894b13f064d667
```

**Comment by NikVolf** [comment]
oh, but our derivation by the test vectors from here:
https://en.bitcoin.it/wiki/BIP_0032_TestVectors
(https://github.com/paritytech/parity/blob/master/ethkey/src/extended.rs#L491)

I'm not sure why you think `0xd610c21cCaAEbe0DFfc256206A9b1C7e89d3DE97` is the correct address for this particular derivation

**Comment by fabware** [comment]
Yes, I had read those tests. I also can't believe it since ExtendedKeyPair derive gives me the right address while ethstore insert_derived not. 

I'm sure 0xd610c21cCaAEbe0DFfc256206A9b1C7e89d3DE97 is the correct one because:
1. parity ExtendedKeyPair derive gives me this address;
2. code using rust-bitcoin gives me this address;
3. online [bip39 caculator](https://iancoleman.github.io/bip39) gives me this address;

The following is a screenshot of "bip39 caculator" supplying with the same Mnemonic: 
![image](https://user-images.githubusercontent.com/160636/32214197-02f1e96c-be59-11e7-9b90-ad7af19b9ccd.png)

**Comment by NikVolf** [comment]
Oh, now I got it
You see, `ExtendedKeyPair` does not only contains the secret, it is also holds so-called `chain_code`

So when you reduce `ExtendedKeyPair` to just secret here:

`        .insert_account(SecretVaultRef::Root, secret_key.secret().as_raw().clone(), "")`,

`chain_code` goes nowhere

and `ethstore` does not actually have any means to store this `chain_code`, it's generated from root secret using sha3, so it does not match that `chain_code` you generated from seed (via `ExtendedKeyPair::from_seed`)

currently there is no way to force `ethstore` to use custom `chain_code` from seed

**Comment by fabware** [comment]
Ok, I see, ```ethstore.insert_derived``` using default sha3 chain_code, while ```ExtendedKeyPair``` using different chain_code from seed, which causes different address.

It would be great make it possible to use custom ```chain_code```, so that we can easily make it standard compatible. A small tip above the function would be very helpful for clueless people like me.

Thanks a lot for your help!

**Comment by NikVolf** [comment]
Yep, I will add an issue for storing `chain_code` in the vault
