### ISSUE TITLE
[feature request] py-parity (fork of py-geth)

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#6927]
During my getting-an-overview of useful python ethereum tools, I have come across this one:

https://github.com/pipermerriam/py-geth

and soon there was this wish:

**"feature request: same for parity" https://github.com/pipermerriam/py-geth/issues/37**

idea: perhaps you can collaborate on that one?

**Comment by Office-Julia** [comment]
Thanks for the proposal.
Currently we don't have a Python implementation
The thing I can advise you to do is post directly to 
https://github.com/pipermerriam/py-geth/issues

Regards,
Julia.

**Comment by drandreaskrueger** [comment]
yes, done that, been there: https://github.com/pipermerriam/py-geth/issues/37#issuecomment-339413011

**Comment by 5chdn** [comment]
https://github.com/pipermerriam/py-parity

**Comment by drandreaskrueger** [comment]
yes: https://github.com/pipermerriam/py-parity/commits/master
