### ISSUE TITLE
Remove local transactions

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6929]
Is there any way to remove local pending transactions, similar to remove transactions.rlp of geth?

**Comment by Office-Julia** [comment]
Hello. Let me assist you with this issue.
Could you please ask the following questions:

1. Have you tried turning it off and on again?
2. Are you fully synchronized?
3. Which version of Parity are you running? ("master" or "git" is not a version)
4. Which operating system are you running?
5. How did you install Parity? (binary, installer, from source, which branch?)
6. What flags are you running Parity with?
7. Do you use any config file?
8. Please, share the exact error message!
9. Is there anything in the logs?
10. Are you connected to any peers?
11. What's your time? Is it synchronized? time.is

Regards, 
Julia.

**Comment by gaoxiangxyz** [comment]
@Office-Julia Thanks
1. Yes
2. Yes
3. Parity version: v1.8.0-beta-9882902-20171015
4. Operating System: Windows
5. Installer
6. Flags : --config D:\parity\private\config.toml
7. Config File: Yes, I do. Content is at bottom.
8. No error message
9.  -
10. To a miner geth node in a private chain
11. My time is about 9:38AM when I submit this comment. I am not sure how to check whether synchronized.in time, compare the log time?

I create a private chain using geth as miner node. I meet this [transaction not mined problem](https://github.com/ethereum/go-ethereum/issues/15388)  before, and non-miner geth node is working now by clearing the txpool (deleting transactions.rlp file), but non-miner parity node is still not working, I guess the reason is similar with geth's (there are some little gas transactions not mined block all subsequent transactions), so I want to try to do the similar thing what I do for geth.

Config File Content:
# This config should be placed in following path:
#   %AppData%\Parity\Ethereum\config.toml

[parity]
# Ethereum Classic
chain = "d:\\parity\\private\\chain-spec.json"
# Blockchain and settings will be stored in d:\parity\private.
base_path = "d:\\parity\\private"
# Parity databases will be stored in d:\parity\private\chains.
db_path = "d:\\parity\\private\\chains"
# Your encrypted private keys will be stored in d:\parity\private\keys.
keys_path = "d:\\parity\\private\\keys"
# You will be identified as 'private' amongst other nodes..
identity = "private"

[ui]
# You will need to unlock accounts manually if Wallet is disabled.
# disable = true

[network]
# Parity will listen for connections on port 31337.
port = 31337
# Disable Warp Sync
no_warp = true
# Network ID of the chain will be overridden to: 12345
id = 12345
# Override the bootnodes from selected chain file.
bootnodes = ["enode://c0ad2f6260c4248c95e8377e34166777be74241757ccb2d0d1e8d1daae20ce1586b46b7225f6279ed76453224f56aff237fa9a8168104d948ca6e600652e1cea@192.168.10.232:30303"]

[rpc]
port = 8545
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore", "personal"]

[websockets]
# UI won't work and WebSockets server will be not available.
# disable = true

[secretstore]
# You won't be able to encrypt and decrypt secrets.
# disable = true

[footprint]
# Keep all state trie data. No pruning.
pruning = "archive"
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Increase performance on HDD.
db_compaction = "hdd"

[misc]
# Logs will be stored at d:\parity\private\parity.log.
log_file = "d:\\parity\\private\\parity.log"
# Enables colors in logs.
color = false

**Comment by tomusdrw** [comment]
There is an RPC method `parity_removeTransaction('0xtransactionhash')` if that's what you need.
It will remove the transaction from the local queue (even if it's scheduled for later), but:
1. if the transaction was already propagated it might get into the queue again
2. If the transaction is already in pending block it will be mined anyways

**Comment by gaoxiangxyz** [comment]
@tomusdrw The "parity_removeTransaction" api return error "Method not found".
The "parity" item is add to "apis" array in config file.
The "parity_pendingTransactions" works fine.

**Comment by tomusdrw** [comment]
@gaoxiangxyz The method is available in `parity_set` api and is not available on JSON-RPC transport by default.

**Comment by gaoxiangxyz** [comment]
@tomusdrw thanks, it works.

**Comment by tomusdrw** [comment]
Cool. Closing the issue then.

**Comment by Parean** [comment]
@tomusdrw Could you please tell me if transactions with too high nonce are propagated to other nodes from local queue by parity? I want to understand what happens with tx when I create tx with too high nonce. It's saved in a local queue, but do other nodes get the information about this tx? I don't know, can I remove tx from the queue before it's mined and be sure that it won't be mined later by some node that received that tx before I removed it.

**Comment by tomusdrw** [comment]
@Parean AFAIR only transactions from the `ready` part of the transaction pool are propagated, so if the nonce is set too high, such transaction will never end up being broadcasted to peers.

**Comment by Parean** [comment]
Thank you!
