### ISSUE TITLE
whisper: Method not found

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#6930]
( I have come to this via trying out web3.py https://github.com/pipermerriam/web3.py/issues/384 )

> I'm running:

```
parity --version
  version Parity/v1.8.0-unstable-684b14271-20170921/x86_64-linux-gnu/rustc1.20.0

uname -a
Linux ... 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
```

**expected behavior**  
able to try out whisper rpc calls

**actual behavior**    
"Method not found"  

**steps to reproduce**

Have I perhaps not opened the whisper rpc correctly?

```
parity --whisper --jsonrpc-apis shh,eth --chain ropsten --warp
```

I get these results:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"shh_version","params":[],"id":67}' http://localhost:8545 
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":67}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"shh_newIdentity","params":[],"id":73}' http://localhost:8545
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":73}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"shh_info","params":[],"id":73}' http://localhost:8545
{"jsonrpc":"2.0","result":{"memory":0,"messages":0,"targetMemory":10485760},"id":73}

curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":73}' http://localhost:8545
{"jsonrpc":"2.0","result":"0x1db47b","id":73}
```

I found this https://github.com/ethereum/go-ethereum/wiki/Whisper-v5-RPC-API - which of those does parity actually support already?

**Comment by drandreaskrueger** [comment]
This issue said 1.8  https://github.com/paritytech/parity/issues/5515#issuecomment-297483280, but perhaps you are not there yet? What about then either 

returning an error when I try `parity --whisper --jsonrpc-apis shh,eth`  

or 

returning a "Method not implemented yet" instead of "Method not found"

?

**Comment by 5chdn** [comment]
Hi, for now, you could just use our wiki to check the available RPCs.

https://github.com/paritytech/parity/wiki/JSONRPC-shh-Module

**Comment by drandreaskrueger** [comment]
Thanks a lot.

I guess until the "*the global whisper API, the geth whisper API, and the parity whisper API all differ*" ([384](https://github.com/pipermerriam/web3.py/issues/384#issuecomment-340486629)) situation is resolved ... I simply ignore whisper for now?  

I came to this only because I was trying out the `web3.py` examples - and they took this position now: https://github.com/pipermerriam/web3.py/issues/384#issuecomment-340506567

**Comment by 5chdn** [comment]
No, whisper v6 is implemented in parity, and the work on v6 has started in go-ethereum.

https://github.com/ethereum/go-ethereum/pull/15324

It will take some time to test and mature this, and API wrappers like web3.py need to adapt at some point, but in the long haul, it should work. And if not, we need to look closer why.
