### ISSUE TITLE
UI rendering breaks with error "ServiceWorker is not available in your browser" in the console

### ISSUE THREAD

**Issue by ehsan** [paritytech/parity#6936]
> I'm running:
>
> - **Parity version**: 1.9.1
> - **Operating system**: Linux
> - **And installed**: from source (latest trunk)

When I build the latest source code with `cargo build --release` from trunk and run it with `cargo run --release` locally and navigate to http://127.0.0.1:8180/, the rendered UI which seems to be recently changing is now broken.

In the Web Console in Firefox I get several errors starting with "ServiceWorker is not available in your browser" followed by "TypeError: s is not a constructor".

Debugging this, I narrowed the issue down to [this code](https://github.com/paritytech/parity/blob/152e56c5d9859072350db7ca34ccd2b93722945e/js-old/src/redux/providers/worker.js#L64).  Here, `PromiseWorker` is null, since the imported module promise-worker doesn't exist.  The ES5 code transpiled from [this block](https://github.com/paritytech/parity/blob/152e56c5d9859072350db7ca34ccd2b93722945e/js-old/src/redux/providers/worker.js#L17) generates a block like this:

```
  try {
    PromiseWorker = require('promise-worker');
    runtime = require('serviceworker-webpack-plugin/lib/runtime');
    WebWorker = require('worker-loader!~/webWorker.js');
  } catch(error) {
    // ...
  }
```

And the first line in the try block would throw there.  So by the time we get to line 64, `new PromiseWorker()` would also throw (which is where the "TypeError: s is not a constructor" error presumably comes from also.)

**Comment by Office-Julia** [comment]
Hello, let me help resolving your issue.

May I ask which browser and version are you using to connect? 
Have you tried upgrading browser version or use another browser?

Regards,
Julia.

**Comment by ehsan** [comment]
Hi,

Thanks for getting back to me!  Sorry that I forgot to mention this.  I have tested this in Firefox Nightly, Firefox release and Chrome release and I get the same error in all of those browsers.

By the way, in case it's helpful for debugging things on your ends, here is [http://127.0.0.1:8180/bundle.js](https://gist.github.com/anonymous/0b1f660862b8dc178866480a78cd6c69) and [http://127.0.0.1:8180/bundle.js.map](https://gist.github.com/anonymous/3e08df897d5358334a8b03b74f63d9f0).

Please let me know if there is any other information I can provide that would be helpful.

**Comment by 5chdn** [comment]
the 1.9 UI is currently being replaced and non-functional. I recommend compiling the beta branch instead.
