### ISSUE TITLE
Ethstore::import_wallet cost too much time

### ISSUE THREAD

**Issue by ssshen** [paritytech/parity#6937]
> I'm running:
>
> - **Parity version**: 1.9.0
> - **Operating system**:  MacOS
> - **And installed**: from source

I'm trying to use ethstore to import and export keystore. But when i use `Ethstore::import_wallet()` to import exist account , it cost too much time.

**actual**
function Ethstore::import_wallet() cost at least 2 minutes

**expected behavior**
function Ethstore::import_wallet() cost few seconds to import keystore

```
[dependencies]
ethstore = { git = "https://github.com/paritytech/parity" }
```
```
extern crate ethstore;

use ethstore::{EthStore, SecretStore, SecretVaultRef};
use ethstore::dir::RootDiskDirectory;
use std::time::SystemTime;

fn main() {
    println!("start import: {:?}", SystemTime::now());
    let dir = RootDiskDirectory::at("tests");
	let store = EthStore::open(Box::new(dir)).unwrap();
    let keystore = b"{\"version\":3,\"crypto\":{\"mac\":\"cf712637db71590fede4e0bde6416144bdfd9535f2448a12b5790d9bc5af13f2\",\"cipherparams\":{\"iv\":\"660f50f83339ad48f3a1da876e8f5e28\"},\"kdfparams\":{\"dklen\":32,\"r\":8,\"salt\":\"fb7b24137b203f58eaeca470457ed3a8434b4274992ed74ceaa58988fe9ae151\",\"p\":1,\"n\":262144},\"cipher\":\"aes-128-ctr\",\"ciphertext\":\"4c49be86d2a1d3dac39b08dece335698c060feaaab9880612cd2282f21ea9a53\",\"kdf\":\"scrypt\"},\"id\":\"52d6f0da-142e-41b7-b40c-71db5bffc7f8\",\"address\":\"3d91831df09d92a3ebd4ad025f5c4806664c06be\"}";
    let accountref = store.import_wallet(SecretVaultRef::Root, keystore, "12345678");
    println!("finished import: {:?}", SystemTime::now());
}

```
When i run  `cargo run`, it cost 229 seconds. Logs as follow:
```
start import: SystemTime { tv_sec: 1509421412, tv_nsec: 760213000 }
finished import: SystemTime { tv_sec: 1509421641, tv_nsec: 953591000 }
```
When i run `cargo build`, and then run binary file, it cost 151 seconds. Logs as follow:
```
start import: SystemTime { tv_sec: 1509424448, tv_nsec: 450439000 }
finished import: SystemTime { tv_sec: 1509424599, tv_nsec: 269324000 }
```
When i run `cargo build r--release`, and then run binary file, it cost 2 seconds. Logs as follow:
```
start import: SystemTime { tv_sec: 1509422323, tv_nsec: 887391000 }
finished import: SystemTime { tv_sec: 1509422325, tv_nsec: 591925000 }
```

I can't understand why there is such a big difference between debug and release.And it cost too much time to test my code.
Or is there something wrong with the usage of ethstore?

**Comment by 5chdn** [comment]
`--release` optimizes the build. Anything compiled without that flag is _expected_ to be very slow.
