### ISSUE TITLE
Documentation of "durationLimit" chain spec parameter?

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#6938]
I am looking for a definition of the "durationLimit" chain spec parameter on the chain specifications here:

https://github.com/paritytech/parity/wiki/Chain-specification

It seems that it is not a generic genesis file parameter, but rather a Parity-specific option that is not documented.

Please point me to the documentation or please tell me what the parameter means and how I can add the documentation myself if you would like.

**Comment by arkpar** [comment]
See here: https://github.com/paritytech/parity/wiki/Pluggable-Consensus#ethash

**Comment by stone212** [comment]
@arkpar Yes that is perfect.  Thank you.  I've been to that page so many times, but was looking for this on the chain spec page.  This is exactly why I think that page needs work, but anyway yes this Issue is resolved.  Thank you.

**Comment by Office-Julia** [comment]
durationLimit is a chain-specific param: 
https://github.com/paritytech/parity/wiki/Chain-specification

**Comment by stone212** [comment]
@Office-Julia That is what I thought initially.  But it does go into the params section under the engine section so I'm not sure anymore.

When you go to the exact link that you sent, you will not find "durationLimit" anywhere.  But since it is a chain-specific parameter, maybe a separate issue should be opened in order to have the definition live on this page: https://github.com/paritytech/parity/wiki/Chain-specification?

**Comment by arkpar** [comment]
The engine section explicitly links to the pluggable consensus page:
> + **`"engine"`** field describes the consensus engine used for a particular chain, details are explained in the [Consensus Engines](Pluggable-Consensus) section.

There's nothing wrong is having the documentation split into multiple pages. This is what web is about.

**Comment by stone212** [comment]
@arkpar

> There's nothing wrong is having the documentation split into multiple pages.  This is what web is about.

That's only the case when appropriately-used hyperlinks are used.  If a page purports to define a thing, and an integral subset of that thing is not on the page in question and there is no hyperlink to a page that *does* have the sub-thing, then this is poor engineering.  It's not a huge deal, but it's worth opening an Issue and suggesting a fix.

So the actual issue is:

a) is durationLimit a chain-specific param as @Office-Julia  says?

b) Is https://github.com/paritytech/parity/wiki/Chain-specification an attempt to give thorough information on Parity chain specs?

c) If (a) and (b) are each true, perhaps the F5-documentation flag was correct and "durationLimit" should be added to https://github.com/paritytech/parity/wiki/Chain-specification, or at least a hyperlink should be added to that page, with the hyperlink pointing to some other page that you consider more appropriate for the definition of "durationLimit".
