### ISSUE TITLE
Deploying token on local sevrer

### ISSUE THREAD

**Issue by sparshprogrammer** [paritytech/parity#6940]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.0
> - **Operating system**: Linux
> - **And installed**: via  binaries 

how to deploy the token on local server.(Is it even possible).
After deploying (it shows your token has deployed).But i dont get any token and token address for creating contract.
---

**Comment by Office-Julia** [comment]
Hello. Let me assist you in resolving this issue.

Could you please share sequence of actions which you tried take to do it. 

Regards, 
Julia.

**Comment by 5chdn** [comment]
@sparshprogrammer you can just go to applications in your parity wallet and find the "token deployment" dapp. follow the instructions.
