### ISSUE TITLE
Search and backup account key file programmatically

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6941]
I create accounts by rpc api personal_newAccount, and it only returns an address. Then I need to backup account key file before using the account. All above are done programmatically.
Is there any way to find key file without reading the file content? Is there some relationship between address and name or id of the key file ?

**Comment by tomusdrw** [comment]
You can use `parity_exportAccount('0xaddress', 'password')` rpc method for that. There is no relation between uuid and the address.

**Comment by gituser** [comment]
@gaoxiangxyz there is no mechanism, but you can grep files in the keydir for needed address and determine the uuid you'd need or just use `parity_exportAccount()` as @tomusdrw suggested.

**Comment by gaoxiangxyz** [comment]
@tomusdrw @gituser  Thanks both. Do you have any suggestion about max number of account key file in one parity node? I may have several million or more accounts. Is there any problem if I put all key file in only one node. Will parity_exportAccount or other account related operation be very slow?

**Comment by tomusdrw** [comment]
We had issues with large number of keys, but #6827 should fix them.

**Comment by gaoxiangxyz** [comment]
@tomusdrw Thanks. 
Which release will include this fix?

Is the name of key file will not changed forever? 
What operations will change the content of key file? As I know, changing password, account name, description, password hint. Is there anything I miss?

**Comment by tomusdrw** [comment]
> Which release will include this fix?
It was released with 1.8.2.

> Does the name of key file not change forever?
No the key files are never renamed by Parity

> What operations will change the content of key file? As I know, changing password, account name, description, password hint. Is there anything I miss?
That's about it. Other key-related things that you can do from the UI as well, like: tags, categories, etc.
(see `parity_setAccountMeta`)

**Comment by gaoxiangxyz** [comment]
@tomusdrw Thanks

**Comment by tomusdrw** [comment]
Closing as answered. Please re-open if you have any more questions regarding this.

**Comment by gaoxiangxyz** [comment]
@tomusdrw Parity 1.8.2 installed by installer on Windows get error when started as administrator.
Unable to create IPC directory at \\.\pipe\: <Client has no permissions(Not English)>。 (os error 1314)

**Comment by 5chdn** [comment]
This is another issue, stay tuned for 1.8.3

**Comment by gaoxiangxyz** [comment]
@5chdn Ok, Thanks
