### ISSUE TITLE
Issue connecting to Kovan network

### ISSUE THREAD

**Issue by magimagister** [paritytech/parity#6945]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**:Parity//v1.8.2-beta-1b6588c-20171025/x86_64-windows-msvc/rustc1.20.0
> - **Operating system**: Windows 10
> - **And installed**: via installer

I switched to the Kovan network but I continue to get
You are not connected to any peers. There is most likely some network issue. Fix connectivity.
Your clock is not in sync. Detected difference is too big for the protocol to work: 2864ms. Synchronize your clock.

If I keep the Ethereum network I see the sync in progress, the peers are growing and no issue on time.

Any suggestion?

**Comment by Office-Julia** [comment]
Hello. Let me assist you with this issue.

May I ask you to answer my questions first:
1. Is your internet connection stable? Have you tried different ISP instead?
2. What flags are you running Parity with?
3. Do you use any specific config file?
4. Is there anything in the logs?
5. What's your time? Is it synchronized? time.is


Regards,
Julia.

**Comment by magimagister** [comment]
Hi

Is your internet connection stable? Have you tried different ISP instead?
- yes fiber stable connection. I'm able to properly sync with ethereum network but not able to sync with kovan network.  I tried my mobile connection with the same result.

What flags are you running Parity with?
- no flag. I start Parity from Windows menu and then, in Settings tag, I switched to kovan network

Do you use any specific config file?
- no

Is there anything in the logs?
- I see some 018282.log but it is not readable. Where can I find others? 

What's your time? Is it synchronized? time.is
- I changed the sync time and now it is green but still no peer connected.

Could you try removing the nodes.json file in the chains subdirectory of your db path?
- I removed the nodes.json file chains\kovan\network folder. It has been created from scratch but nothing changed...

thanks for your support
m

**Comment by 5chdn** [comment]
Could you share the logs please?

**Comment by magimagister** [comment]
can you please lead me exactly where I can find the log? thanks

**Comment by magimagister** [comment]
I just uninstalled and installed the stable version 1.7.8 and now it works without other changes.

**Comment by 5chdn** [comment]
Can you create a config file in `%UserProfile%\AppData\Roaming\Parity\Ethereum\config.toml`

with the following contents

```toml
[misc]
logging = "sync=trace"
log_file = "C:\\parity.log"
```

This will get loaded by parity and create a log file in `C:\parity.log` (change the path as you like). Restart Parity and leave it running for some minutes, and please share the log here :)

**Comment by 5chdn** [comment]
Fixed.
