### ISSUE TITLE
db kill doesn't work with --chain anymore

### ISSUE THREAD

**Issue by chuacw** [paritytech/parity#6950]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity/v1.8.1-beta-0e4a06d-20171020/x86_64-windows-msvc/rustc1.20.0
> - **Operating system**: Windows
> - **And installed**: via installer

parity db kill doesn't work with --chain=kovan or --chain kovan anymore.

So, if I issue a db kill, which database does it remove?

**Comment by axelchalon** [comment]
Have you tried putting `--chain=kovan` before `db kill` ? `parity --chain=kovan db kill`

**Comment by chuacw** [comment]
Ah ha! Thanks very much! So, options before commands.

**Comment by axelchalon** [comment]
Yes, global options come before the command now; but command-specific options still come after the command.
In case of doubt `--help` should clear it up (it's also possible to call `--help` on a command)
