### ISSUE TITLE
parity contract editor produces invalid binary output

### ISSUE THREAD

**Issue by dip239** [paritytech/parity#6951]
_Before filing a new issue, please **provide the following information**._

> I'm running: Parity//v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21. 
> on Linux 
> installed from parity_1.8.2_amd64.deb using using apt-get install over 1.8.1 version.

consider very simple contract being developed and compiled in parity
```
pragma solidity ^0.4.17;
contract OneLiner {} 
```
freshly reloaded development parity site displays an error as shown:
---
![grafik](https://user-images.githubusercontent.com/4574735/32258159-3132c886-beb9-11e7-95bc-072602d15ffd.png)

after setting up switches and recompile I have compiled contract as shown
![grafik](https://user-images.githubusercontent.com/4574735/32258631-e829caba-bebb-11e7-98cb-811729058624.png)

the binary code produced is:
`0x60606040523415600e57600080fd5b603580601b6000396000f3006060604052600080fd00a165627a7a7230582081874e62438daec97d8d170f5c00bbb3aa05ec7e7a295e542f5ef231a093d97e0029`

this binary code can't be verified in etherscan and differ from binary code from remix, which can be verified perfectly:
'0x60606040523415600e57600080fd5b603580601b6000396000f3006060604052600080fd00a165627a7a723058200334fbac17011dcf9914018e6c0a66652ca31c2c34d1bd655c588f181e463d2a0029'
[example on etherscan](https://etherscan.io/address/0x442EfA42459c1d13ed2Eb93A56c43A950296396f#code)

Remix Settings:
`{"compiler":{"version":"0.4.17+commit.bdeb9e52"},"language":"Solidity","output":{"abi":[],"devdoc":{"methods":{}},"userdoc":{"methods":{}}},"settings":{"compilationTarget":{"browser/OneLiner":"OneLiner"},"libraries":{},"optimizer":{"enabled":true,"runs":200},"remappings":[]},"sources":{"browser/OneLiner":{"keccak256":"0x7a7860400e2e5014d2cd303b96b8c130832a151afb0b553c9df3905a9513357c","urls":["bzzr://207704555699b7dca9bfe919be39a834e58970ff2da8267e7b03642f6661d022"]}},"version":1}`

**Comment by 5chdn** [comment]
First issue: #6082

Second issue: The blob on etherscan exactly matches the parity output, what's the issue here you are describing?

**Comment by dip239** [comment]
> The blob on etherscan exactly matches the parity output, what's the issue here you are describing?

they do not match for me:
the blob from [etherscan](https://etherscan.io/address/0x442EfA42459c1d13ed2Eb93A56c43A950296396f#code)  (pulled from remix) is

60606040523415600e57600080fd5b603580601b6000396000f3006060604052600080fd00a165627a7a723058200334fbac17011dcf9914018e6c0a66652ca31c2c34d1bd655c588f18**1e463d2a**0029

the blob from parity is
60606040523415600e57600080fd5b603580601b6000396000f3006060604052600080fd00a165627a7a7230582081874e62438daec97d8d170f5c00bbb3aa05ec7e7a295e542f5ef231**a093d97e**0029

they are different, although the compiler settings are the same. 
Therefore I was unable to etherscan-verify the parity compiled code

**Comment by debris** [comment]
I believe that's just a hash of a different compiler version. Please reopen if still occurs in latest version of parity
