### ISSUE TITLE
Thread 'IO Worker #1' panicked at 'DB flush failed

### ISSUE THREAD

**Issue by MistokenToken** [paritytech/parity#6955]
---
stack backtrace:

Thread 'IO Worker #1' panicked at 'DB flush failed.: "IO error: /Users/user/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/105120.sst: No such file or directory"', src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6
Mac-mini running El Capitan installed via Brew, Parity 1.8.1

**Comment by 5chdn** [comment]
If this prevents you from running parity, and it's reproducible, please reset your database with `parity db kill` and try again.
