### ISSUE TITLE
UI in light mode. ERC20 aren't being shown and thus no way to send them 

### ISSUE THREAD

**Issue by bitxchg** [paritytech/parity#6958]
> I'm running:
>
> - **Parity version**: v1.8.2beta
> - **Operating system**:   Linux
> - **And installed**: via installer

When running parity in light mode, there is now way to send ERC20 tokens since they aren't being shown. The blockchain is synced

---

**Comment by 5chdn** [comment]
Yeah, the UI is not ready yet for the light mode because not all RPCs are available afaik.

**Comment by Tbaut** [comment]
moved to https://github.com/parity-js/shell/issues/75
