### ISSUE TITLE
'DB flush failed

### ISSUE THREAD

**Issue by kulibih** [paritytech/parity#6960]
> I'm running:
>parity --author 0xd*************** --no-ws --no-dapps --rpc --jsonrpc-port 8547 --jsonrpc-interface 192.168.0.80 --port 30305 --no-ui --min-peers 250 --max-peers 350 --work-queue-size 60 --max-pending-peers 300 --no-serve-light --tx-queue-mem-limit 0
> - **Parity version**: 1.8.2.2beta
> - **Operating system**: Linux
> - **And installed**: via installer / homebrew / binaries / from source
auto apdate
stack backtrace:
   0:     0x56198d04f34c - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

---

**Comment by 5chdn** [comment]
Please reset your database with `parity db kill`

And try again.
