### ISSUE TITLE
Force-sealing option false is ignored in config file

### ISSUE THREAD

**Issue by Ochir** [paritytech/parity#6965]
> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Ubuntu 16.04
> - **And installed**: via installer 

my node.toml config

[parity]
chain = "morden.json"
base_path = "eth"
db_path = "eth/db"
keys_path = "eth/keys"

[ui]
disable = true

[network]
port = 30303

[rpc]
disable = false
interface = "all"
cors = "*"
hosts = ["all"]
port = 8545

[websockets]
disable = true

[ipc]
disable = true

[dapps]
disable = true

[secretstore]
disable = true

[account]
unlock = ["<hash>"]
password = ["passw"]

[mining]
usd_per_tx = "0.0"
force_sealing = false
tx_queue_mem_limit = 0
engine_signer = "<hash>"

[misc]
logging = "own_tx,sync=debug"
log_file = "parity.log"

Force-sealing options works OK for versions prior 1.7x. It is set to false as you can see from config above. 
Every 120 seconds (I guess it is reseal-max-period option) new block is created anyway and it is not expected behavior.

**Comment by Ochir** [comment]
sealing stopped when I added option "reseal_on_uncle = false"

**Comment by Ochir** [comment]
I set reseal_max_period = 31536000000 (1yr) so it doesn't seal so often.

**Comment by arkpar** [comment]
`--force-sealing` is off by default in 1.7.0 and 1.8.2 as well. Setting it to `false` does not really change anything. What was the expected behaviour in 1.8.2 and how does it differ from 1.8.2?

**Comment by Ochir** [comment]
Expected behavior that blocks are not created each 120 seconds.
Actually, a new block  is created each 120 seconds if reseal_max_period is not set. 
Currently, I set it to 31536000000 and no new blocks are crated. 
Possibly option "reseal_max_period" ignores force-sealing setting.

**Comment by 5chdn** [comment]
Hi, mind sharing your chainspec?

**Comment by Ochir** [comment]
sure, the same config file for 2 machines in PoA cluster.

{
    "name": "Muuu",
    "engine": {
                "authorityRound": {
                        "params": {
                           "stepDuration": "0x1",
                           "validators" : {
                                        "list": [
                                           "<hash1>",
                                           "<hash2>"
                                        ]
                                }
                        }
                }
        },
        "params": {
                "accountStartNonce": "0x0100000",
                "frontierCompatibilityModeLimit": "0x789b0",
                "gasLimitBoundDivisor": "0x0400",
                "maximumExtraDataSize": "0x20",
                "minGasLimit": "0x1388",
                "networkID" : "0x77"
        },
        "genesis": {
                "seal": {
                        "authorityRound": {
        "step": "0x0",
        "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                        }
                },
                "difficulty": "0x20000",
                "author": "0x0000000000000000000000000000000000000000",
                "timestamp": "0x00",
                "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "extraData": "0x",
                "gasLimit": "0x2fefd800"
        },
    "nodes": [
               "enode://55068b195c4bec5dface17f4d1d6330015d5b4479502621c4f6fe5bab069528098540b5d0bb59fdd6a818c337787e2d73d6775fcc04185097500004fc0813664@10.0.0.9:30303",
               "enode://7c7544f93dc9e977fe5b7ba30f453982a2b9faeb3347eb3b7c1d219670eaf55249529311c3637a70610db0e38beb1205a048026ba9af29e654e24e33ffafd57a@10.0.0.11:30303"
    ],
    "accounts": {
        "0000000000000000000000000000000000000001": { "balance": "1", "nonce": "1048576", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0000000000000000000000000000000000000002": { "balance": "1", "nonce": "1048576", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0000000000000000000000000000000000000003": { "balance": "1", "nonce": "1048576", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0000000000000000000000000000000000000004": { "balance": "1", "nonce": "1048576", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "<hash1>": { "balance": "1606938044258990275541962092341162602522202993782792835301376", "nonce": "1048576" },
        "<hash2>": { "balance": "1606938044258990275541962092341162602522202993782792835301376", "nonce": "1048576" }
    }
}
