### ISSUE TITLE
eth_hashrate

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6966]
I want to get the hash rate similar to hash rate showed at top left blue part at [etherscan](https://etherscan.io/) in my private chain. Is the eth_hashrate api what I want?

**Comment by tomusdrw** [comment]
Nope, `eth_hashrate` just returns a reported hashrate of the miner connected to your local node.

Network hashrate can be estimated by looking at total difficulty and block timestamps of last couple blocks.

**Comment by gaoxiangxyz** [comment]
@tomusdrw I would greatly appreciate it if you could provide some materials about how to estimate network hashrate.

**Comment by 5chdn** [comment]
https://ethereum.stackexchange.com/questions/18162/how-is-average-network-hashrate-determined
