### ISSUE TITLE
Build from source hangs on `Updating git repository ...js-precompiled.git`

### ISSUE THREAD

**Issue by Math3v** [paritytech/parity#6969]
> I'm running:
>
> - **Parity version**: 1.7.8
> - **Operating system**: MacOS / Linux
> - **And installed**: from source

---

**Expected behavior:**
Parity builds from source.

**Actual behavior:**
Parity build hangs on `Updating git repository https://github.com/paritytech/js-precompiled.git`

**Steps to reproduce:**
I'm trying to create a Heroku buildpack: https://github.com/PrimeHammer/heroku-buildpack-parity

This buildpack should install parity, but the build process hangs.

**Comment by 5chdn** [comment]
It does not hang, it just takes very long depending on your setup. Does it hang for more than 30 minutes?

**Comment by saarshah** [comment]
same here with me hang more than an hour ... ????

**Comment by saarshah** [comment]
I have source code of some project project i just want to test it , but it hang more than an hour during initial steps and showing only Updating git repository `https://github.com/paritytech/parity-ethereum`
