### ISSUE TITLE
Unable to reach time API: NTP error: NTP server is not provided？

### ISSUE THREAD

**Issue by itcodes** [paritytech/parity#6971]
Your node is still syncing, the values you see might be outdated. Wait until it's fully synced.

Unable to reach time API: NTP error: NTP server is not provided.. Make sure that your clock is synchronized.

How can I solve this problem?
Any idea how I can get the clock synchronized, and what it means now that it's not synchronized?

Thank you!

**Comment by 5chdn** [comment]
You can ignore this warning if services like https://time.is report your clock is in sync.
