### ISSUE TITLE
Recommend decreasing usd_per_tx

### ISSUE THREAD

**Issue by MysticRyuujin** [paritytech/parity#6973]
Currently the default for `usd_per_tx` is `0.0025` however, `.1 GWei` and even smaller transactions are fairly common.

A standard transaction with 21000 gas @ .1 Gwei is only about $0.0006 right now... that means that a significant chunk of transactions fall below the minimum gas price as calculated by `usd_per_tx`

**Comment by 5chdn** [comment]
There is nothing wrong with paying a quarter-cent for a transaction by default. 

If you really desire to lower your transaction fees significantly, you can fully control this behavior with `--usd-per-tx 0.0006`

**Comment by Office-Julia** [comment]
Actually we can accept, but only a well thought-through PR.
You should be sure to provide statistics that back up and proves requirement of any alteration you would like to make. 

Regards,
Julia.

**Comment by MysticRyuujin** [comment]
@5chdn while I agree there is nothing wrong with paying a quarter-cent for a transaction, I guess I don't understand why Parity is defining a minimum at all, let alone one that is well below the current "Safe Low" defined by https://ethgasstation.info/ by an order of 4x
