### ISSUE TITLE
High CPU usage when syncing

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#6978]
> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Windows Server 2008 R2,  64bit
> - **And installed**: via installer

I use parity as a fully sync node of main net. When it is syncing, the CPU usage of it will be 99% occurring at irregular intervals. Is there any optimization I can do? 
Machine configuration:  2 CPU(2.13GHz), 48GB RAM, HDD.

```
# This config should be placed in following path:
#   %AppData%\Parity\Ethereum\config.toml

[parity]
# Blockchain and settings will be stored in d:\parity\mainnet.
base_path = "D:\\deploy\\parity\\mainnet"
# Parity databases will be stored in d:\parity\mainnet\chains.
db_path = "D:\\deploy\\parity\\mainnet\\chains"
# Your encrypted mainnet keys will be stored in d:\parity\mainnet\keys.
keys_path = "D:\\deploy\\parity\\mainnet\\keys"
# You will be identified as 'mainnet' amongst other nodes..
identity = "ws_mainnet"

[ui]
# You will need to unlock accounts manually if Wallet is disabled.
disable = true

[network]
# Disable Warp Sync
no_warp = true

[ipc]
disable = true

[rpc]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_set"]

[websockets]
# UI won't work and WebSockets server will be not available.
disable = true

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true

[ipfs]
# You won't be able to hash-query blockchain data.
disable = true

[footprint]
# Keep all state trie data. No pruning.
pruning = "archive"
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Increase performance on HDD.
db_compaction = "hdd"

[misc]
# Logs will be stored at d:\parity\mainnet\parity.log.
log_file = "D:\\deploy\\parity\\mainnet\\parity.log"
# Enables colors in logs.
color = false
```

**Comment by jedahan** [comment]
Likewise, on 1.8.2, installed via homebrew on macOS 10.13 I am getting around 125% cpu usage and fans on full for late 2012 macbook pro 13. Any simple way to limit this?

**Comment by jedahan** [comment]
For now I installed cputhrottle and set it to 50% cpu and it seems to be an okay workaround, though repeatedly suspending and resuming is not great.

**Comment by 5chdn** [comment]
That's actually a feature, Parity is a full Ethereum client that consistently talks to other peers in the network, receives, verifies, and propagates new blocks, and receives, verifies, and propagates new transaction.

At current Ethereum utilization, your node has to process around 4-5 blocks and 300-400 transactions per minute.
