### ISSUE TITLE
Parity 1.8.2 (1.9??) Issues 

### ISSUE THREAD

**Issue by lrgeoemtry** [paritytech/parity#6980]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Windows
> - **And installed**: via installer /  from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Expected Behavior:
Run Parity
Node Syncs
Contract Development Gui Works
dApps (Token Deployment / Token Registry) Work

Actual Behavior
Run Parity
Node Syncs
Contracts Ticker in Settings Does Not Show
dApps do not load

Comments:
Weird how I went to download the 1.8.2 and on the bottom it says Parity//v1.9.0-unstable-b03117b-20171015/x86_64-linux-gnu/rustc1.20.0

Working Build: 1.7.8
Expected Behavior
Send Eth to Wallet Address
Receive Eth

Actual Behavior
Does Not Receive Eth

However, When logged into 1.8.2 build it received the eth. 

Thoughts? 
---

**Comment by 5chdn** [comment]
Can you open http://127.0.0.1:8180 please and take a screenshot of your settings few? 

What does your configuration look like? Are you running a public node? 

Can you check your browser's address bar and make sure you are not connected to https://wallet.parity.io ?
