### ISSUE TITLE
Parity icon disappearing from menu bar

### ISSUE THREAD

**Issue by bamos01** [paritytech/parity#6986]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: MacOS Sierra
> - **And installed**: via installer 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am able to install Parity successfully, but the parity icon that is usually in the menu bar on my mac disappears after a few seconds after launching the program

---

**Comment by Office-Julia** [comment]
Hello.
Let me try to help you with this issue.

Have you tried to re-install the application?
Is there any error message in the logs? 

Regards,
Julia.

**Comment by bamos01** [comment]
Hi Julia-

I have tries reinstalling - i don't know how to check the error logs- (where is it stored?) - I am not having a slightly different problem.  The icon is staying in the menu bar but when I click on "open parity" - nothing happens.

**Comment by phzi** [comment]
Same thing is happening to me after upgrading from 1.81 to 1.82, on Windows 2012 R2 today.

Parity simply closes after a few seconds (tray icon disappears).  I tried downgrading, re-installing, etc, still same problem.

**Comment by phzi** [comment]
When launching daemon via parity.exe, works fine,  
ptray.exe also runs if you exclude the ui param.

So for now, I was able to get my node back and running by running ptray without any params.

**Comment by 5chdn** [comment]
@bamos01 can you open a terminal and manually execute:

    /Applications/Parity\ Ethereum.app/Contents/parity

And see if there are any errors?
