### ISSUE TITLE
Not Sure; Flush the db? Thanks for suggestions!

### ISSUE THREAD

**Issue by infopirate** [paritytech/parity#6989]
> I'm running:
>
> - **Parity version**: 1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
> - **Operating system**: Linux (Ubuntu 16.04)
> - **And installed**: via steps on github//

Simply running Parity and leaving, I came back to this crash report, I re-executed parity, it started up fine, ran for about 15- 20 minutes and spit this ugly error out at me. Any help is appreciated. 

====================

stack backtrace:
   0:     0x563c384026cc - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

---

**Comment by infopirate** [comment]
====================

stack backtrace:
   0:     0x55bfedecc6cc - <no info>

Thread 'Verifier #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)


when trying to run it after the crash

**Comment by infopirate** [comment]
Will not even load now; same error every time i attempt to run it, Verifier panic; Damn experimental technologies. =)

**Comment by Office-Julia** [comment]
Hello.
Let me help you to resolve this issue.

Have you tried to re-install parity-app? 
Have you tried flush DB manually? 
`parity db kill --chain=<your_chain>`

Regards,
Julia.

**Comment by roninkaizen** [comment]
also had that twice-
as Julia wrote, 
try to flush the database with parity db kill
that worked for me fine when it occured and try to give a feedback, thx!

**Comment by cryptIt** [comment]
parity db kill did the trick, I kept getting error's when trying to give it the --chain flag but with just "parity db kill" it worked fine and flushed the db and started right up and started syncing.. Awesome, thank you very much for your help with this everyone!

**Comment by infopirate** [comment]
parity db kill did the trick, I kept getting error's when trying to give it the --chain flag but with just "parity db kill" it worked fine and flushed the db and started right up and started syncing.. Awesome, thank you very much for your help with this everyone!
