### ISSUE TITLE
Snapshot to json format

### ISSUE THREAD

**Issue by Hirama** [paritytech/parity#6996]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.8
> - **Operating system**:  MacOS
> - **And installed**: homebrew

Do you have documentations how to do dump or snapshot in json format not RLP format?

---

**Comment by Office-Julia** [comment]
Hello. Let me assist in resolving this issue.

Here you can find an answer to your question:

> Although Parity supports JSON export, the state snapshot format for Parity Warp Sync (also implemented in EthereumJ) is fully documented at https://github.com/paritytech/parity/wiki/Warp-Sync-Snapshot-Format, never re-includes duplicate code, and is designed to allow out-of-order restoration of chunks. It uses RLP, which is already a core part of most Ethereum clients and is the de facto standard for serialization within this space.

Reference: https://github.com/ethereum/EIPs/issues/227

Regards,
Julia.

**Comment by arkpar** [comment]
```
parity export state [--no-storage] [--no-code] --min-balance=[WEI] --max-balance=[WEI] --at=[BLOCK] file.json
```
This requires parity to be synced with --fat-db=on
