### ISSUE TITLE
unable to "parity signer new-token" 

### ISSUE THREAD

**Issue by aphilippi** [paritytech/parity#6998]
> I'm running:
>
> - **Parity version**: 1.8.2 Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
> - **Operating system**: Linux
> - **And installed**: via binaries

parity signer new-token
returns 

error: Found argument '--can-restart' which wasn't expected, or isn't valid in this context

USAGE:
    parity-1.8.2-1b6588cb279ecaa85a766e0a52a8837ea6d8be21 signer new-token

Any help is appreciated. 

---

**Comment by aphilippi** [comment]
it actually worked when I used the executable from ~/.local/share/io.parity.ethereum-updates

~/.local/share/io.parity.ethereum-updates/parity-1.8.2-1b6588cb279ecaa85a766e0a52a8837ea6d8be21 signer new-token

**Comment by axelchalon** [comment]
linked to https://github.com/paritytech/parity/issues/6906
a fix is being worked on

**Comment by axelchalon** [comment]
fixed with https://github.com/paritytech/parity/pull/7004
