### ISSUE TITLE
Cannot async request to server using method "POST" by Dapp browser

### ISSUE THREAD

**Issue by ropod7** [paritytech/parity#6999]
Parity version: 1.8.2
Operating system: Linux
And installed: via installer
---
Parity converts any POST request to GET using AJAX. Server returns 405 (Method not allowed).

**Comment by Office-Julia** [comment]
Hello.
Let me help you in resolving this issue.

Please describe in detail how you making a request and which tool are you using?

Regards,
Julia.

**Comment by ropod7** [comment]
Not fully described because have thoughts that its your security feature.
1. I'm using your UI: http://127.0.0.1:8180/#/web and Chrome browser
2. Going into etherecho.com
3. After a long-long time when page loaded up to show header blockchain values and long time more, check out Developer tools -> console. and
4. Exception: `**GET** http://127.0.0.1:8544/web/D9VPPTV1E5R42CBT95KK4EA594NPGX3ME1SKMBSFCNT6GSBJCNHPGVSECDQPT/dapp_signin 405 (Method Not Allowed)`

In place that was created through POST method. Probably requested preparing too long time.

**Comment by tomusdrw** [comment]
@ropod7 it's indeed a security measure, we don't allow any non-GET/HEAD requests. We believe that the dapps should only serve frontend and be server-less, all the state should be stored on the blockchain.

Do you know what the POST request is required for in that specific dapp? Is it crticial for the dapp to work?

**Comment by ropod7** [comment]
@tomusdrw I think it's critical if we are creating any large project with multiple features when server side content depends from Smart contracts data. If we are using small narrowly specialized Dapps, you are right, but not in every moment if we are talking about large infrastructure. Not every data will be registered on the blockchain side. It's question about cost of the data movement.

Thanks.

**Comment by ropod7** [comment]
Ok. We will investigate all of your suggestions. 

Thanks.
