### ISSUE TITLE
reward trace

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#7001]
I use trace_transaction to get all traces of main net, but there is no trace of reward type (the last number of block I have synced is about 2,200,000). Does reward type trace  only work after some block number? Is there any way to get all miner reward records from node?

**Comment by debris** [comment]
what version of parity are you using? (`parity --version`)

**Comment by gaoxiangxyz** [comment]
@debris 1.8.2

**Comment by 5chdn** [comment]
Can you please rephrase your question? Are you trying to get information about block rewards from blocks your client didn't synchronize yet? That's not possible; you will need an entirely synchronized Parity client first.
