### ISSUE TITLE
help -how I know if my wallet is affected?

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#7007]
Hi, 
please can someone tell me how exactly (i use v1.78-windows) I can determine whether my wallet is affected by this current super-bug , or if I have a "normal" not-affected wallet? 

thank you

**Comment by nomelc** [comment]
The easiest method that I have found so far is to enter your address [here](https://affected.parity.io/).
5chdn mentioned this link in a reddit [thread](https://www.reddit.com/r/ethereum/comments/7bl6da/megathread_parity_multisignature_library/) so I am fairly certain the site is legit.
Another way is through [etherscan](https://etherscan.io/) but I have not tried this myself.

**Comment by folsen** [comment]
A multisig wallet is not a "normal" wallet/account that just has one owner, it's a process you would have to go through to deploy and move funds to. If you don't know what a multisig wallet is, you're unlikely to be affected, however the site that @nomelc linked is indeed legit and is https://affected.parity.io

**Comment by zumbatan** [comment]
thank you guys , all clear now

**Comment by zumbatan** [comment]
just dont understand why anyone would use such multisig wallets. or i just dont see the advantages
