### ISSUE TITLE
All funds gone, Balance is zero

### ISSUE THREAD

**Issue by sokoleden** [paritytech/parity#7010]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: Parity//v1.7.2-beta-9f47909-20170918/x86_64-windows-msvc/rustc1.19.0

> - **Operating system**: Windows 10 64bit
> - **And installed**: via installer / homebrew / binaries / from source

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
All funds gone Balance zero,

Have sent some ETH yesterday to the my adress on parity, did know there ist a super-bug. Yesterday the transaction was pending whole time. Today it shows no funds at all.

Are there all funds gone forever?

What could i do to get my funds back?

Thank anyone for help.

**Comment by 5chdn** [comment]
Please upgrade to 1.8.2 and make sure your client is fully synchronized.

**Comment by sokoleden** [comment]
Thank you for your help.

 

I could see my funds after installing the update and could take the funds out.

 

But after this bad experience, maybe you can understand, that I will think at least twice before I will ever transfer any funds to a parity wallet , or will want to deal with the company which has created parity in the future.

 

Best regards and wish you the very best

 

Sokol Mihajlovic

 

Von: Afri Schoedon [mailto:notifications@github.com] 
Gesendet: Freitag, 10. November 2017 16:49
An: paritytech/parity <parity@noreply.github.com>
Cc: sokoleden <info@finmakler.de>; Author <author@noreply.github.com>
Betreff: Re: [paritytech/parity] All funds gone, Balance is zero (#7010)

 

Please upgrade to 1.8.2 and make sure your client is fully synchronized.

**Comment by 5chdn** [comment]
If you have any suggestions how we can improve this workflow, please, let me know.
