### ISSUE TITLE
set up Parity. Sent BTC to default address. Never received

### ISSUE THREAD

**Issue by cryptogrumpy** [paritytech/parity#7012]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Windows 8.1
> - **And installed**: via installer

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
set up Parity. Sent BTC to default address to fund account. In details window the progress went from 
1 details to 2 awaiting deposit to 3 awaiting exchange but did not progress to 4 completed. I clicked outside the detail window to look for answers and now cannot find that specific window again. 
Never received funds

---

**Comment by 4budab1** [comment]
Check whole video 
https://www.youtube.com/watch?v=WNT2O6xyDmM

**Comment by 5chdn** [comment]
Please contact https://shapeshift.io support. We do not handle the BTC converter.
