### ISSUE TITLE
Account balance not up to synch

### ISSUE THREAD

**Issue by nosko07** [paritytech/parity#7021]
I'm running:
Parity version: 1.19.0
Operating system: Windows 
And installed: Via installer 
My account balance is not up to synch, nor has it been for close to a month.  A new transfer will not go through, and it says that past transfers are still pending, despite funds being received quite some time ago.
Also my nodes in the bottom-right corner always say they are synching. I have ran the program before for well over an hour and it always says it is not fully synched. 
When I attempt to download a new version it brings me to a screen in which is having me download a whole new version of Parity and asks for a new wallet to be created. I have not gone this route for fear it will affect me accessing my remaining funds in my current Parity account. I just want to update my current account to the newest version to see if that assists with proper nodes and then lists my actual ETH left in my account, rather than setting up a new account.
Any Ideas?

**Comment by 5chdn** [comment]
The Parity 1.19 milestone is scheduled for February 2019. Can you check again which Parity version you are using? To display your correct balances, you will require the latest Parity release with a fully synchronized blockchain.

**Comment by nosko07** [comment]
Sorry, looks like it's 1.7.2.   How do I get Parity to be fully synched? If
there is a guide you have as to downloading the latest Parity upgrade you
can send over, I'd be very grateful. I'm newer to this and I find Parity
incredibly difficult to manage. Doesn't appear to be the best platform for
a newbie.

**Comment by 5chdn** [comment]
Please, upgrade to 1.7.8 or 1.8.2

https://github.com/ethereum/go-ethereum/releases/latest
