### ISSUE TITLE
Low sync after upgrade to 1.8.2

### ISSUE THREAD

**Issue by Ferdi07** [paritytech/parity#7023]
> I'm running:
>
> - **Parity version**: 1.8.2
> - **Operating system**: Windows 10
> - **And installed**: via installer 

After the hard fork, I understood I have to download and install the new version 1.8.2. 
After the installation The Parity client starts to sync, but this was very slow. To sync 100 bockchain It takes 10/20 minutes. 
Today I'm at the the block 4,413,371. I miss about 100,000 blocks
Is there something I can do to make faster the sync?

I noticed the peers actives are always 0 or 1 (ex: 0/25/25). Is it normal?

Thank You!

---

**Comment by 5chdn** [comment]
Looks good, if you are on an HDD, you might wish to consider buying an SSD at some point in the future.
