### ISSUE TITLE
help please: cannot transfer ERC20 tokens from Parity

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#7024]
> - **Parity version**: 1.7.8
> - **Operating system**: Windows
> - **And installed**: via installer 

---

"You can manually execute the erc20 token contract to initiate a transfer."
->please can someone give a concrete short step by step guide? I mean this is at the end real money, and in the parity.wiki there is not such guide given. You could easily do mistakes.

I clicked on the mentioned "execute" button within the "contracts" tab-> but for example there are 3 different options "approve"/ "transfer" / "transferfrom" ->what is each of them meaning? How to transfer my erc20 token to another ethereum wallet exactly (not all of the balance, just some of it)?

Thank you very much

**Comment by 3esmit** [comment]
Go to contracts tab, click watch, then choose option ERC20, click next, fill the options, next, and should apper as a coin option if you have balance in that account. remember to check if node is synced.

**Comment by 3esmit** [comment]
if no contracts tab, go to settings, dig there somewhere you will find to enable contracts tab

**Comment by zumbatan** [comment]
HI thanks. But you described a guide which I already followed. Please read again my above text. I am already in the "watch" screen. I can already see my erc20 tokens and balances.  I am talking now about the "Execute" function -> how to transfer the tokens? because there are 3 types of execute options: 
 "approve"/ "transfer" / "transferfrom" ->what is each of them meaning? How to transfer my erc20 token to another ethereum wallet exactly (not all of the balance, just some of it)?

**Comment by rphmeier** [comment]
@zumbatan I agree a wiki page would be nice, although note that transfer of tokens doesn't require use of the contracts tab. The UI already makes transfer of tokens easy when the token is in the on-chain registry (which in turn the client uses to know what tokens to fetch balances for). The contracts tab is disabled by default for a reason, though, which is that it is an "advanced" feature for users who feel comfortable with Ethereum ABIs in general and the contracts that they are used for.

**Comment by zumbatan** [comment]
@rphmeier  @5chdn    thank you but this is not possible in my case, its an current open bug  
https://github.com/paritytech/parity/issues/6759

It is not possible as you described to transfer erc20 tokens via the usual transaction screen. Therefore, I have to do it by the contracts tab.  So please, just give me the short guide how to do it via the contracts+execute function?

Thank you.

**Comment by 5chdn** [comment]
Can you please PM me on Gitter, I have issues to follow you here, and we need to go through this step by step. In #6759 you say you can't see your tokens, and therefore you are unable to transfer them. In this ticket, you say you see all your tokens. 

Can you please give me _eyes_, screenshots, anything that allows me to understand where in the process you are stuck? Thanks.

**Comment by thaynetaylor** [comment]
This is an essential topic. It would really be helpful to those of us who are fairly new if such a guide would be made to help us all.

**Comment by zumbatan** [comment]
@rphmeier  @5chdn  
 you guys are usually so much into details, why is there an issue of understanding now with this simple issue -i from the start provided precise screenshots via this link
->https://github.com/paritytech/parity/wiki/Tokens  
this github page exactly shows my issue->the LAST 3 pictures are depicting what I am NOT able to see/do.

I clearly stated here and there that the issue is ONLY about the ACCOUNTS tab. Even the issue headline says "...not being displayed within the ACCOUNTS tab ".  And therefore, I am not able to transfer my tokens. Therefore, I need help. 

you even started to understand me and started to provide an alternative way of transfering tokens->by using the "execute" function within the "contracts" tab-> i asked you 2 times, please give a short precise guide how to use the "execute" function. So that me & the community learns about that.

But you won't explain and rather ask questions back to me. 
Again, I am able to see all tokens using the addressbook and contracts tabs. BUT they do not appear within the ACCOUNTS tab, which they should by software requirement.

Now, my suggestion is: as long as this issue is open, please give us (i think i am not the only one in need)  precise explanation about the "execute" function- because this function is misleading. i see there are 3 different options "approve"/ "transfer" / "transferfrom" ->what is each of them meaning and how to achieve that X amount of "GOLEM" is sent to address Y? What about gas prices, where to set them within this "execute" screen, or it doesnt matter?

Thanks a lot for your help, hope it is clear now. I will write you in Gitter, too.

**Comment by 5chdn** [comment]
1. Take GOLEM ERC 20 address, https://etherscan.io/token/Golem `0xa74476443119A942dE498590Fe1f2454d7D4aC0d`
2. Open Parity Wallet Contracts view http://127.0.0.1:8180/#/contracts
3. Click Watch > Token > Address `0xa74476443119A942dE498590Fe1f2454d7D4aC0d` > Name `Golem Network Token` > Add
4. Open the Golem Network Token in the Contracts view > click EXECUTE
5. Select the Account with the GNT balance, 
6. Select a "to" address (receiver)
7. Enter amount "value" to transfer: 1 GNT = 1000000000000000000 (because GNT uses 18 decimals, use the switch on the right to check the amount)
8. Leave transaction value empty
9. post transaction
