### ISSUE TITLE
eth_sendTransaction 0x957cD4Ff9b3894FC78b5134A8DC72b032fFbC464

### ISSUE THREAD

**Issue by ablazhey** [paritytech/parity#7026]
Every transactions send to 0x957cD4Ff9b3894FC78b5134A8DC72b032fFbC464

**Comment by 5chdn** [comment]
Cool!

**Comment by kirushik** [comment]
@ablazhey Can you please clarify, what version of Parity are you using, on which OS, what exactly steps should be taken to reproduce the issue, and what you expect to see, and what happens instead?

Without those details, it's impossible for us to do something about your issue, unfortunately.

**Comment by grazz** [comment]
Was this ever clarified? That's an address that has been used to store stolen ethereum. It's still being actively used right now.

**Comment by kirushik** [comment]
@grazz @ablazhey I think it's OK to use this bug for you to figure out the whole situation (I don't understand it at the moment, unfortunately. Like, what is "stolen" ethereum and so on) — but it will remain closed unless we figure out that Parity is involved in the problem.
Please mention me or @5chdn if you decide this is indeed something we should address.

**Comment by tomusdrw** [comment]
@grazz @ablazhey Could you guys please clarify how the account was created? My guess would be that it used a weak brain wallet phrase, that's easily crackable.
