### ISSUE TITLE
ETH Transaction not showing up in Parity wallet

### ISSUE THREAD

**Issue by thaynetaylor** [paritytech/parity#7050]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: MacOS 10.12.6
> - **And installed**: via installer / homebrew

Been working on this off and on for weeks! I sent Parity some ETH when I first set it up just to test and it did not show up. The transaction shows up in Etherscan.io though. I thought the problem was that Parity was not syncing to the network. Resolved that problem but NTP Time will not sync , Peers is synced. I read on Github and Parity wiki that Time sync was not a problem or issue. But the ETH I send still has not shown up. If anyone can help would sure be appreciated!

Aloha,
Thayne

---

**Comment by 5chdn** [comment]
Please upgrade to the latest Parity version, 1.7.0 is not able to synchronize beyond the Byzantium hard-fork.

**Comment by thaynetaylor** [comment]
Please note that I was on Parity 1.7.0 but I took your advice 5chdn and upgraded to the latest version which now is 1.7.9 for Mac and the NTP synced right away. Still waiting for Chain to sync to see if my Parity transactions will end up in my wallet. Stay tuned.

**Comment by baskinsy** [comment]
I have this issue on a fully synced 1.8.4-beta, is there any way to debug it?

**Comment by kirushik** [comment]
@baskinsy can you please share the etherscan.io link to the transaction you're missing? I will check this out, and will open a new issue about your case, if it will be reproducible. (Can you please double-check that your local Parity node is not on some alternative network, where the transaction never happened, by the way?)

**Comment by cgruber** [comment]
I'm running 1.8.5 beta and I'm still not seeing any transactions either (all transactions from imported geth accounts).  I am running in --light mode.  Is that possibly the issue?

**Comment by 5chdn** [comment]
Depends, what are you looking at? The wallet's account details? This is an etherscan API.

**Comment by cgruber** [comment]
Wallet account details - there's a box for transactions in the UI, and it's empty.

**Comment by 5chdn** [comment]
Hopefully, the new User Interface will fix this.

**Comment by baskinsy** [comment]
Upgraded to 1.8.5 beta and still the same issue as @cgruber reported. I think the issue should be re-opened.

**Comment by 5chdn** [comment]
It's a different issue, the wallet does not work with `--light` currently.

**Comment by baskinsy** [comment]
I'm not using ``--ligth`` mode.

**Comment by cgruber** [comment]
@5chdn - can you link in the issue related to --light not working? I'd like to track that.

**Comment by 5chdn** [comment]
See #6958

**Comment by amishcon** [comment]
I had the same issue.  Turned out Paity was showing fully synced when it wasn't.  After a refresh or two, started syncing again.  Once fully synced, ETH showed up.

**Comment by baskinsy** [comment]
Still having the same issue on a fully refreshed 1.8.6beta...

**Comment by Submariner78** [comment]
Having the same issue on a freshly installed 1.8.6 beta.
:(

**Comment by scottguild** [comment]
1.8.7 PC having same issue.
