### ISSUE TITLE
Use annotated tags for releases (take 2:)

### ISSUE THREAD

**Issue by elopio** [paritytech/parity#7060]
I reported #6180 suggesting to use annotated tags for releases. More info about it here:
https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags

The v1.7.0 release was annotated and that bug was closed, but all the following releases haven't been annotated. So here it is the same suggestion for future releases.

**Comment by 5chdn** [comment]
1.7.9 and 1.8.3 are annotated.

**Comment by elopio** [comment]
You are right @5chdn, I was looking at the wrong place. Sorry!
