### ISSUE TITLE
kovan is not synced. consensus is broken.

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#7065]
https://authorities.kovan.network/

<img width="1133" alt="screen shot 2017-11-15 at 10 42 46 am" src="https://user-images.githubusercontent.com/9360827/32854044-36f33bae-c9f2-11e7-8bc1-259891308633.png">

Can't send transactions, transaction are being lost, no one can mine them.

Nodes are not in sync. 
Probable cause #6761 

http://testnet.oracles.org:3000/ - oracles testnet works fine because we have removed checks for uncle blocks

transactions can't be mined, got lost/stuck
https://kovan.etherscan.io/tx/0xf5f37b2dd8032f9fab4f841ce29f4e292b92cf6621b3b2495d01464c74a5862a

**Comment by retotrinkler** [comment]
pinged

**Comment by ddorgan** [comment]
The nodes are now syncing and should all be up to date soon.

**Comment by 5chdn** [comment]
Thanks, David!

**Comment by retotrinkler** [comment]
@5chdn could we also increase `GasLimit` to `7000000`?

**Comment by 5chdn** [comment]
@ddorgan ^ ?

**Comment by bjornwgnr** [comment]
@igorbarinov 
>Afri, how can we as a community apply to be validators on Kovan network and keep it alive?

Thanks for your interest in supporting the Kovan network! The Kovan Validator Onboarding Initiative is in the works and I just added you to the list of proposed authorities. The network needs to upgrade to contract-based validators first afaik.

**Comment by rstormsf** [comment]
@bjornwgnr I'd also love to mine Kovan

**Comment by 5chdn** [comment]
FYI #7080

**Comment by rstormsf** [comment]
@5chdn @bjornwgnr it's happening again!
http://authorities.kovan.network/

**Comment by michaelScoff** [comment]
@5chdn @bjornwgnr any updated?

**Comment by 5chdn** [comment]
It's a mess :)

We will provide two new releases this week and prepare a hard-fork for Kovan as soon as possible.
