### ISSUE TITLE
HELP account stuck in address book

### ISSUE THREAD

**Issue by Trancenow** [paritytech/parity#7069]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.3/1.20.0/wi
> - **Operating system**: Windows / 10
> - **And installed**: via installer 

Just installed Parity. Added a wallet address which ended up in the address book tab. I transferred ETH to that wallet but I cannot send any ETH from that address even though the funds are there??? WHat specifically can be done to get my money? I can see it but when I go to transfer the only option I have is the main account I setup which has 0 balance. :(
---

**Comment by kirushik** [comment]
Dear @Trancenow.
Where did you get that address you've added?
Are you sure you have control over that wallet's private key?

From your description it sounds like you've transfered your ETH to some other person, and now unable to spend money from their wallet — which is exactly how it it supposed to work.
Please feel free to add additional info here, if you still think that you've encountered a bug in parity client — and we'll reopen this bug.
You can also join our chats on Gitter/Matrix to get more general help.
