### ISSUE TITLE
add a flag to download only canonical blocks 

### ISSUE THREAD

**Issue by tzapu** [paritytech/parity#7070]
Hello and thanks for all your hard work.

It would be useful for us to have a flag to only download canonical blocks (200001, 1150001, 1920001 ... 4370001) but not all other ancient blocks.

We use this to establish that you are indeed on mainnet and we could then have some parity nodes using less hdd space.

Cheers
Alex

**Comment by 5chdn** [comment]
If you want to use less hdd-space, just skip the full ancient block download with `--no-ancient-blocks`, but that will only safe 7-9 GB disk space and is super insecure. 

I don't see such a feature implemented anytime soon. Either you want the history or you do not want it. But having a partial block-history is equal to having no history at all (security-wise).

**Comment by oancius** [comment]
It's not only about the hdd-space, the blocks after fork could be used to check if you really are on the mainnet so the best solution it would be to can prioritize the fetch of the blocks near forks in background node sync...

**Comment by 5chdn** [comment]
But how is the client supposed to know about a fork block if it does not fetch the blocks before? Peers could provide any block really, and the client has to "accept" it.

**Comment by tzapu** [comment]
fair point @5chdn , thanks for looking into this
as an alternative, could we maybe have an always download block#s cli command? 

so it's an on demand thing and we can specify some blocks we always need to be available?

**Comment by 5chdn** [comment]
By default all blocks are available.

**Comment by tzapu** [comment]
sry, was not explicit enough, a whitelist for --no-ancient-blocks, so it only downloads the ones in the whitelist
