### ISSUE TITLE
Token registry indicates invalid address but it was address provided by ICO

### ISSUE THREAD

**Issue by dataninja23** [paritytech/parity#7072]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
> - **Operating system**: Windows  10
> - **And installed**: via installer 

Participated in CarTaxi ICO and tokens were provided (I can see them with my parity wallet address through their portal.  I attempted to register the toke using the address, (0x662aBcAd0b7f345AB7FfB1b1fbb9Df7894f18e66) and it indicates "The address is not a regular token contract address".  This is the correct address.  Can you assist?

---

**Comment by 3esmit** [comment]
Seems like its not an ERC20 token. Probably you will get better support with CarTaxi team, as they are the ones who know how to use this software they created. You can try using Custom Contract and placing the ABI provided here https://etherscan.io/address/0x662aBcAd0b7f345AB7FfB1b1fbb9Df7894f18e66#code

**Comment by 5chdn** [comment]
3.  totalSupply    0 uint256

Only tokens with supply > 0 can be registered.
