### ISSUE TITLE
Missing eth in parity

### ISSUE THREAD

**Issue by chw00** [paritytech/parity#7073]
> I'm running:
>
> - **Parity version**: 1.7
> - **Operating system**:  MacOS 
> - **And installed**: via installer open via google chrome

**I transfer from exchange address only 5.45698076 Ether to my parity wallet address
TxReceipt Status:Success **
https://etherscan.io/address/0x001a247E077BfEAD567c39Ff827e277B6DEEaC00

![screen shot 2560-11-17 at 8 56 11 am](https://user-images.githubusercontent.com/31642276/32925686-d26b4124-cb75-11e7-877a-b72656764f2b.png)

but it's already about 9 hours and i can't find any eth in my parity wallet. It's still 0.00 eth

![screen shot 2560-11-17 at 8 59 40 am](https://user-images.githubusercontent.com/31642276/32925728-01a82d9e-cb76-11e7-9a84-5c165512628c.png)

Anyone has any suggestion?

Regards
---

**Comment by 5chdn** [comment]
Are you fully synchronized? Which version of Parity are you running?

**Comment by chw00** [comment]
Hello Thank you for notice me.
I think the issue was
> Chain Synchronized (no)
> Your node is still syncing, the values you see might be outdated. Wait until it's fully synced.

Still i try update parity today to 1.8

![screen shot 2560-11-17 at 7 25 30 pm](https://user-images.githubusercontent.com/31642276/32947194-3bc2f3fe-cbcd-11e7-82b5-032e8049d89c.png)

![screen shot 2560-11-17 at 7 25 41 pm](https://user-images.githubusercontent.com/31642276/32947197-3e00a5da-cbcd-11e7-8fe4-4d05fb3a17d9.png)

**Comment by chw00** [comment]
Hello i still haven't receive my coin yet still i don't know why admin close my issues.
Please give me advice or explanation.

**Comment by kirushik** [comment]
Dear @chw00. So far it looks like you haven't yet synchronised with the blockchain fully (at least you've never shared a screenshot stating othewise).
Obviously, you won't be able to see your tokens if your client is not fully synchronized.
Please wait till it happens -- and then let's see if you still need our help afterwards.
While waiting, you might find it worth your time reading our [wiki page on Tokens in Parity](https://github.com/paritytech/parity/wiki/Tokens) and how to use them.
