### ISSUE TITLE
No Workie .... 

### ISSUE THREAD

**Issue by davidweirshousky** [paritytech/parity#7076]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.89-beta
> - **Operating system**: Linux
> - **And installed**: via  binaries 

Beta with bug and contract fix on ubuntu 17.04 fails to sync after shutting down. Will not restart block syncro, just runs on. The previous  version runs bug free but the issues are a problem I feel for anything but test net

---

**Comment by 5chdn** [comment]
Could you share the exact error message?

**Comment by davidweirshousky** [comment]
over night and the 1.8.3 deb pkg came out so it's not beta now, it works, a little work on time servers to sync correctly
