### ISSUE TITLE
Use `Failure` crate to enhance error handling

### ISSUE THREAD

**Issue by 0x7CFE** [paritytech/parity#7077]
[Failure crate](https://crates.io/crates/failure) reflects [new approach to error handling](https://boats.gitlab.io/blog/post/2017-11-16-announcing-failure/) in Rust. 

It natively supports backtraces, error downcasting, and is backward compatible with `io::Error` through blanket impl. Detailed information, as well as various use cases may be found in [documentation](https://boats.gitlab.io/failure/).

I think, we may consider migrating to this crate once it became stable enough.

**Comment by debris** [comment]
It looks interesting. Do you know if it supposed to be complementary to [error_chain](https://crates.io/crates/error_chain) or is it supposed to be a replacement for it?

**Comment by 0x7CFE** [comment]
Failure was intentionally designed to be backwards compatible with std. If I understood correctly, it may operate with other error types within a single crate without much pain.

Regarding `error_chain` interoperability, I believe, it would be supported someday. Right now it may be achieved using the standard `Error` trait, but maybe later we would have some specific options.

The very same question was asked on Bay Area meetup. You may check [the video](https://air.mozilla.org/bay-area-rust-meetup-november-2017/) at `1:43:30`.

**Comment by 0x7CFE** [comment]
It is expected, that [Failure would hit 1.0.0 on March 15](https://boats.gitlab.io/blog/post/2018-02-22-failure-1.0/).

I think it's a good time to reconsider, whether we want adopting it in the near future (at least for new code).

**Comment by folsen** [comment]
A month later it is still not 1.0, I think we should consider it for new code, but closing this issue until it is in a more stable place.
