### ISSUE TITLE
scheduler certification. HOWTO

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#7078]
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid Transaction.","data":"Sender is not certified."},"id":1}
```
do I have to be certified in order to use http://txsched.parity.io/#raw  
also u have a bug in `curl` example: double `::` in http and missing space in `-HContent-Type`

**Comment by rstormsf** [comment]
how to become a certified?

**Comment by tomusdrw** [comment]
The scheduler requires a PICOPS-certified account. See https://picops.parity.io

**Comment by rstormsf** [comment]
please reopen in order to specify on the website, please also take into account a few typos that I found in `curl` example @tomusdrw @5chdn

**Comment by rstormsf** [comment]
it doesn't seem to be working:
I sent 1 tx - nothing happened.
I sent another one the id is not even incremented:
```
{"jsonrpc":"2.0","result":"accepted","id":1}
```
another big issue on the UI side is that it only allows to select 30 min timeframes while the CURL script accepts unix timestamp. Such a big UX issue.

**Comment by tomusdrw** [comment]
Hi @rstormsf thanks for comments. The PR addressing the UI issues here: https://github.com/paritytech/transaction-scheduler/pull/13
There is only fine-tune option where you can supply the timestamp manually, not full UI to select specific time. Contributions for better UI support are welcome.

The ID of the request is never incremented (it's JSON-RPC request id, not ID of the transaction you schedule).

Can you provide more details on the transaction you attempted to send? I can check the logs but need to now either:
- network you used and time/block it was scheduled for
- or sender's address

**Comment by rstormsf** [comment]
@tomusdrw FYI - how do I specify the network used for the `curl` script? 
I used `/txsched.parity.io` which means mainnet, right? 
The address to send from/to:
`0x02dee0B9caA39f4E16B63822EEB6DE8DD68464AD` 
I tried to send to self and to `0x0039F22efB07A647557C7C5d17854CFD6D489eF3`

**Comment by tomusdrw** [comment]
Just checked logs and there was an issue with Parity instance running on that server (it didn't auto-update itself properly before hard fork and got stuck on some old block).
There is a fallback mechanism that sends the transaction to infura, but it had issues as well.

Updated the node (but it's still syncing) and fixed fallback, we also added those nodes to the internal monitoring system to prevent such issues from happening in the future.

Regading `http/https` it depends if you are on `https://txsched.parity.io` or `http://txsched.parity.io` - we support both and the curl examples adapt to the website you are on.

You can find kovan version of the scheduler at `https://txsched-kovan.parity.io`

**Comment by rstormsf** [comment]
I'd appreciate some  "thank you" for raising the alarm for this service. :-) 
0x0039F22efB07A647557C7C5d17854CFD6D489eF3 just send me some Kovan ether, for God sake :-)

**Comment by tomusdrw** [comment]
@rstormsf Thank you for that indeed :1st_place_medal: :) Kovan ETH sent.

**Comment by rstormsf** [comment]
@tomusdrw thank you so much Tomas. I value Kovan more than anything 👍 Would love to mine some

**Comment by rstormsf** [comment]
@tomusdrw let me know when I can test it again, so it's up and working.
