### ISSUE TITLE
Password Fails on Test Password But Accepted When Exporting Account

### ISSUE THREAD

**Issue by cliquenoir** [paritytech/parity#7085]
I'm running:
**Parity version**: v1.7.7-stable-eb7c648-20171015/x86_64-macos/rustc1.20.0
**Operating system**: MacOS
**And installed**: Installer (if I remember correctly)

I've just encountered an unexpected issue after updating Parity (via the in-app automatic update): my account password now returns "This password is not correct" on the Password > Test Password page; however, the same password is accepted on the Export > Export Account page.

I've tried changing the password to no avail. When attempting to do so, the app provides no feedback as to whether the original password was entered incorrectly.

Can you please provide any insight as to why this might be the case, what may be happening, or how I can resolve the issue? I need to be able to access my account ASAP.

Thanks in advance.

**Comment by 5chdn** [comment]
I can not reproduce this with either 1.7.9 or 1.8.3, could you try upgrading your client, please?

And if this still failing, please share the exact steps required to reproduce this issue.
