### ISSUE TITLE
Parity block checksum mismatch error

### ISSUE THREAD

**Issue by moadif** [paritytech/parity#7088]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.3
> - **Operating system**: Windows
> - **And installed**: via installer
stack backtrace:
   0:     0x7ff6ed7e2054 - hid_error
   1:     0x7ff6ed7e255b - hid_error
   2:     0x7ff6ed001134 - <no info>
   3:     0x7ff6ed95b564 - hid_error
   4:     0x7ff6ed95b3d9 - hid_error
   5:     0x7ff6ed95b2b2 - hid_error
   6:     0x7ff6ed95b220 - hid_error
   7:     0x7ff6ed964b0f - hid_error
   8:     0x7ff6ed19014c - <no info>
   9:     0x7ff6ed261822 - <no info>
  10:     0x7ff6ed1388fb - <no info>
  11:     0x7ff6ed13ec6a - <no info>
  12:     0x7ff6ed95cb12 - hid_error
  13:     0x7ff6ed1920c6 - <no info>
  14:     0x7ff6ed95964c - hid_error
  15:     0x7ffd50d38364 - BaseThreadInitThunk

Thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', src\libcore\result.rs:860

**Comment by 5chdn** [comment]
Please, reset your database with `parity.exe db kill` in your command prompt.

**Comment by 5chdn** [comment]
Duplicate of #7087

Duplicate of #7029

Duplicate of #6974

Duplicate of #6960

Duplicate of #6905

Duplicate of #6798

Duplicate of #6790

Duplicate of #6670

Duplicate of #6506

Duplicate of #6501

Duplicate of #5837

Duplicate of #3634

Duplicate of #3432

Duplicate of #2830

Duplicate of #2640

Duplicate of #2603

Duplicate of #763
