### ISSUE TITLE
Parity will not run after upgrade

### ISSUE THREAD

**Issue by six20** [paritytech/parity#7089]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 1.8.3
> - **Operating system**: Windows 10
> - **And installed**: via upgrade link within parity running in chrome

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

---
I clicked the upgrade link in the lower left portion of parity running in the chrome browser.  Windows defender blocked access and then I gave it permission to run.  Upgrade appeared to get hung up.  After that, parity will not open.  Parity icon flashes in tray when double clicking icon to start as usual, but parity will not open.  I have tried to run the parity exe directly through explorer and the same result.  System rollback not available.  Any suggestions would be appreciated.  Thank you.

**Comment by 5chdn** [comment]
> I have tried to run the parity exe directly through explorer and the same result.

Can you try to run it from inside a command prompt? This should yield a descriptive error message!

**Comment by six20** [comment]
Thanks for the response.  Here is a screenshot

![image](https://user-images.githubusercontent.com/33790988/33101158-2567102a-cee5-11e7-9ded-affe05a6fdde.png)

**Comment by 5chdn** [comment]
Not sure what could have caused this, it seems you upgraded from a very old version. Could you try the following? Please reset your database by executing in the command prompt:

    parity.exe db kill

And try to run Parity again.

**Comment by six20** [comment]
Thanks again for your timeb.  No change after running suggested command.  Actually I had the most recent version of parity running before upgrading.  Another screen shot post db kill command attached.  I am at a loss also.

![image](https://user-images.githubusercontent.com/33790988/33222756-8912974a-d127-11e7-8d72-0e7cc4e36d8a.png)

**Comment by Benparity** [comment]
cant run parity since last log in in oct.!!!

How can I solve it? is my account freezed? website ist not accessable it shows on webbrowser

**Comment by 5chdn** [comment]
Please upgrade to 1.8.3!
