### ISSUE TITLE
Missing ETH

### ISSUE THREAD

**Issue by moadif** [paritytech/parity#7092]
> I'm running:
>
> - **Parity version**: 1.8.3
> - **Operating system**: Windowד
> - **And installed**: via installer

I've had some ETH tokens in my wallet couple of days ago I tried to send a transaction to some address earlier but it failed and according to this: 
https://etherscan.io/address/0x009aabfBdDb96A0Cf33273E1495C7536aa4847b8
The transaction was canceled and I got my tokens back but I don't see them in my wallet it's been a few days already.
Thanks.

**Comment by 5chdn** [comment]
Are you fully synchronized?

**Comment by moadif** [comment]
The problem is when I try to open it now it won't fully synchronize for some reason it just displays an undisposable message on the screen saying it's synchronizing or something yet it goes forever.
Thanks

**Comment by 5chdn** [comment]
Yes, please wait until your chain is fully synchronized.

**Comment by moadif** [comment]
Are you serious? It goes forever, literally.....
