### ISSUE TITLE
Panic on DB flush

### ISSUE THREAD

**Issue by tjayrush** [paritytech/parity#7093]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: 0.0.0
1.8.1

> - **Operating system**: Windows / MacOS / Linux

Mac OS

> - **And installed**: via installer / homebrew / binaries / from source

homebrew

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Just running as normal (been running parity for many (>15) months with --tracing on --pruning archive. Recent versions seem to use huge amounts of disc space, and my guess is that disc temporarily filled. I restarted Parity, and the hard drive space returned to about 400 GB free, and it is now running okay.
---

====================

stack backtrace:

Thread 'IO Worker #2' panicked at 'DB flush failed.: "IO error: /Users/jrush/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/archive/db/1457940.log: No space left on device"', src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6

**Comment by dudalev** [comment]
same thing happened to me, 1.8.3 on linux from deb

**Comment by 5chdn** [comment]
> No space left on device

@tjayrush ^ ;-)
