### ISSUE TITLE
Feature request: Tool to support software improvement process for superior user experience

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#7094]
## Feature request
I'd like to propose the implementation of a feature that allows the node to publish some general info about the network it's connected to, and potentially its use. A new flag would allow the user to opt-in, or specify a different receiver. 

Published info could include:
- **chain spec: chain id, consensus engine & its configuration**
- client mode: full; light; light-server; (all flags / the node's config)
- some health stats: e.g. number of connected peers

## Mid/long-term extensions: Publication website || I2P/Whisper for obfuscation of origin
Further down the road, we could provide a register/website that publishes some/all of this data and its analyses to the public, similar to ethstats but 'one level up'. It could also serve as a platform to share additional information and learn about running (Parity) Ethereum-based open/public networks.
Moreover, a different routing protocol (libp2p+I2P / Whisper) could be used to obfuscate the origin of reports.

## Rationale
Currently, there is little way for us to understand the _who_, _how_ & _why_ of usage of the Parity client and I'd argue that this significantly impedes our ability to improve Parity and prioritise on its different parts. Through many conversations with Parity users, I've learned that only a fraction of potential feedback & feature requests are brought forward to us via GitHub issues and the usual comms channels (gitter, riot).

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity-long-term-issues/ :+1:

**Comment by folsen** [comment]
Currently this is partially served by services like stats.parity.io and related. While I agree this would be a nice-to-have, I'm closing this in favor of tracking it in long-term-issues.
