### ISSUE TITLE
Parity Account Password

### ISSUE THREAD

**Issue by teichd63** [paritytech/parity#7103]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7
> - **Which operating system?**: Windows / **_MacOS_** / Linux
> - **How installed?**: via installer / **_homebrew_** / binaries / from source
> - **Are you fully synchronized?**: **_no_** / yes
> - **Did you try to restart the node?**: no / **_yes_**

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Need help with finding the password to my parity account. Dont ever remember creating a password. Hoping you can help with this process. Thanks.

**Comment by 5chdn** [comment]
If you don't remember setting up one, try an empty password.

**Comment by teichd63** [comment]
Hi Afri,

Thanks for reaching out. I attempted to use an empty password and it still
said password invalid or account does not exist. I have tried all the
passwords that it would be set as, so I am assuming the account does not
exist. What are your recommendations on the next steps I should take? I am
trying to export funds from my wallet.

Thank You,

Daniel

**Comment by 5chdn** [comment]
Do you remember anything about a potential password?

We have an experimental feature that brute-forces passwords, namely

    ethkey recover <address> <known-phrase>

But we didn't release thus yet #6961 and this also requires that you have a gist of what your password was. Otherwise, there is not much we can do.

**Comment by teichd63** [comment]
Yes, I have a couple ideas of what the password would include. I would feel
confident using this new feature that I would resolve my issue.

**Comment by 5chdn** [comment]
ok, open a terminal and try the following (assuming you have brew installed)

    $ brew install rustup 
    $ rustup update stable
    $ git clone https://github.com/paritytech/parity.git
    $ cd parity
    $ git checkout td-ethstore-crack
    $ cargo build --release -p ethkey-cli
    $ cd target/release
    $ ./ethkey recover <address> <known-phrase>

Did not test the commands above, please let me know if you get stuck anywhere.

**Comment by teichd63** [comment]
I ran into an issue pretty early along in the process. In my terminal when
I try to update stable it errors out. So I typed in 'brew install stable'
and it comes back with the error message shown below. Hoping you can help
me with this issue. Thanks again.

Dans-MacBook-Pro:local DanTeich$ brew install stable
Error: No available formula with the name "stable"
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
This similarly named formula was found:
pony-stable
To install it, run:
  brew install pony-stable
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by 5chdn** [comment]
What's the output of `rustup update stable` ?

**Comment by teichd63** [comment]
The output is: 'Dans-MacBook-Pro:local DanTeich$ rustup update stable
-bash: rustup: command not found'

This is interesting because when I upgrade rustup I get the output of
'rustup 1.6.0 already installed'. But the rustup command does not work.

**Comment by 5chdn** [comment]
What's the output of `brew upgrade rustup --verbose` ?

**Comment by teichd63** [comment]
Dans-MacBook-Pro:local DanTeich$ brew upgrade rustup --verbose
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
fluent-bit          kontena             libgosu             q
ghc                 kotlin              libmaxminddb        qca
git-annex           libcddb             micro               sfk
grails              libcdio             plzip               swiftformat
jhipster            libdivecomputer     pyvim               vcdimager

Error: rustup 1.6.0 already installed
Error: Kernel.exit
Dans-MacBook-Pro:local DanTeich$

**Comment by teichd63** [comment]
I am also seeing below response when I try the 3rd step.

Dans-MacBook-Pro:local DanTeich$ git clone
https://github.com/paritytech/parity.git
fatal: could not create work tree dir 'parity': Permission denied

**Comment by 5chdn** [comment]
I'm sorry, what macos version is that? The system looks like it has some serious issues. Could you try removing and reinstalling homebrew and rustup from scratch?

**Comment by teichd63** [comment]
Hi Afri,

I am convinced the latest Parity security breach is the reason I am having
trouble. I wrote down every process while setting up parity on a sheet of
paper including the recovery key, wallet address, wallet name and
everything. I would not have omitted the password if I had set one up. Has
this been a common occurrence for a lot of parity users? I know there was
$300M of Ethereum lost. Thanks,

Dan

**Comment by 5chdn** [comment]
The hacks are unrelated to your problem.

If you did not set a password, you should be able to use your account with an empty password. If it does not accept an empty password, you must have created a password to encrypt the wallet. There is nothing in-between.

**Comment by 5chdn** [comment]
> I wrote down every process while setting up parity on a sheet of
paper including the **recovery key**, wallet address, wallet name and
everything.

D'oh, how could we have missed that? Just restore your wallet by using the recovery phrase you have written down. In your wallet, go to ACCOUNTS > RESTORE > and enter your phrase.

**Comment by teichd63** [comment]
I thought all hope was lost. But I successfully recovered my account using
the recovery key. Thank you so much for all your help Afri!

Thanks again,

Dan
