### ISSUE TITLE
Kovan spec is invalid

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#7104]
Current gasLimit in kovan network is 7000000, however the spec.json tells me a different story:
https://github.com/paritytech/parity/blob/master/ethcore/res/ethereum/kovan.json#L51

`0x5B8D80` = `6000000` 
So, where is most updated spec.json

**Comment by igorbarinov** [comment]
I do agree. Gas limit in the current spec is not the same as on netstats http://authorities.kovan.network

gas limit increased (after this comment? https://github.com/paritytech/parity/issues/7065#issuecomment-344910090) but the spec is not updated

**Comment by 5chdn** [comment]
That's the genesis gas limit, only relevant for the block 0.

**Comment by rstormsf** [comment]
How did they increase gas limit then? @5chdn

**Comment by rphmeier** [comment]
yep, gas limits change over time as the sealers change it slightly per block

**Comment by rstormsf** [comment]
What happened now? it moved back to 4700000 ? 
http://authorities.kovan.network/
@rphmeier @5chdn

**Comment by 5chdn** [comment]
@ddorgan can we increase the block gas limit on Kovan?

    --gas-floor-target 6713337

**Comment by rstormsf** [comment]
https://authorities.kovan.network/ - broken AF @5chdn @bjornwgnr

**Comment by rstormsf** [comment]
@5chdn please reopen the issue

**Comment by rstormsf** [comment]
![screen shot 2017-12-05 at 11 35 51 am](https://user-images.githubusercontent.com/9360827/33626794-7d04a696-d9b0-11e7-8f44-90adacb84b61.png)

**Comment by 5chdn** [comment]
We are on it, Roman, stay tuned for new releases this week with PoA and Kovan fixes. See #7080 for progress.
