### ISSUE TITLE
Parity uses flawed implementation of ECC and secp256k1

### ISSUE THREAD

**Issue by RorschachRev** [paritytech/parity#7105]
The required constants to actually implement secp256k1 were not included in the Parity code. There was no tests to see if random numbers fell on the secp256k1 curve, which is somewhat irrelevant because the curve wasn't used. Both conditions must be met, with a random value for n, in order to implement ECC correctly.

Your crypto is dangerous, bad, false sense of security and could be broken in a cost effective manner to steal money.
Constants listed: https://en.bitcoin.it/wiki/Secp256k1
Here's what happens if you use cryptography incorrectly: Sony 2010. https://www.schneier.com/blog/archives/2011/01/sony_ps3_securi.html

**Comment by 5chdn** [comment]
We are using the optimized C library for EC operations on curve secp256k1 from [bitcoin-core/secp256k1](https://github.com/bitcoin-core/secp256k1).

You can review our Rust language bindings for Bitcoin secp256k1 library here [paritytech/rust-secp256k1](https://github.com/paritytech/rust-secp256k1).

If you think this issue persists after reviewing the bindings and the library, please report it upstream, or if applicable to the Parity client only, follow the instructions in [SECURITY.md](https://github.com/paritytech/parity/blob/master/SECURITY.md).

**Comment by kirushik** [comment]
To add some details to @5chdn comment up there.

Here is the `p_minus_order` constant setting for our secp256k1 library: https://github.com/paritytech/rust-secp256k1/blob/6370d63adf4e8c91e2eae9225eef4b4e0294c5d0/depend/secp256k1/src/ecdsa_impl.h#L36-L47
I can't say I understood your complaint about "testing if random numbers fell on the secp256k1 curve" as well, isn't this the test you're looking for? https://github.com/paritytech/rust-secp256k1/blob/6370d63adf4e8c91e2eae9225eef4b4e0294c5d0/depend/secp256k1/src/testrand_impl.h
One can run those tests by building the C library with `make` and then running the resulting `tests` artifact.

The code in our library is a direct clone of bitcoin-core/secp256k1@6ad5cdb4, you can run a diff manually to see that we haven't changed a work in their implementation, just added several functions on top of it.
