### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by moadif** [paritytech/parity#7107]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: yes

I've been trying to get the client to synchronize for the past week already, tried reseting my db as I also had some issue with it, tried synchronizing through CMD yet it still won't update my wallet with my missing ETH tokens, few seconds after I open the client it displays a message that can't be closed saying the following: 
https://i.imgur.com/Po5HYDV.png

I opened an issue yesterday and someone closed it saying "wait for it to synchroinze".
What does that even mean if it won't ever synchronize, it goes forever it's not working so please take into consideration the info I've provided before replying by just reading the title.
Thanks.

**Comment by 5chdn** [comment]
Please ensure your parity node is actually running :)

**Comment by moadif** [comment]
When I run it from command prompt it basically just starts syncing endlessly until it crashes at one point, the message that appears that I mentioned above no longer appears after I reset the DB, but it still won't sync.

**Comment by 5chdn** [comment]
Please take a screenshot as soon as it crashes. I want to see the actual error message.
