### ISSUE TITLE
Warp doesn't get triggered

### ISSUE THREAD

**Issue by Onkovat** [paritytech/parity#7111]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8
> - **Which operating system?**: Windows 
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**:  yes

I am currently 90.000 blocks behind. There is no setting disabling warp so it should be enabled. However it loads blocks just normally and warp isn't triggered. I tried restarting a couple of times and it runs a good bunch of hours without warping.

What might be the problem?

**Comment by iFA88** [comment]
Warp would be enabled if you have connect to client who supports warp. If you have only geth clients you will not syncing with warp. Try restart your client, for me works.

**Comment by Onkovat** [comment]
Thank you for the tip. I guess raising the minimum and maximum peers would also fix this issue? Will try.

**Comment by 5chdn** [comment]
> I am currently 90.000 blocks behind. 

Warp only triggers if you are more than 100.000 blocks behind :)

**Comment by Onkovat** [comment]
I can't confirm that it only triggers over 100K. I was around 85K when it started. I first started with peers around 100, didn't reach it of course, closed parity around 50 active peers and restarted. Then it started warping with one of the already known good peers somehow.
