### ISSUE TITLE
Improve usability of Connection Dialogue

### ISSUE THREAD

**Issue by bnvk** [paritytech/parity#7112]
Currently, the `Connection Dialogue` is a bit technical and not as user friendly as it could be. For instance when no websockets token exists, the message reads:

```
Unable to make a connection to the Parity Secure API...
```

A more user friendly message would be something like:

```
Unable to connect to the Parity app...
```

There are multiple Connection Dialogues throughout the application, so I will send more detailed specific suggestions / fixes in individual pull-requests.

**Comment by 5chdn** [comment]
Thanks, pull requests are much appreciated :)

**Comment by Tbaut** [comment]
Moving to a new repo, we will not migrate low prio issues. Please reopen it in the new repo if you believe it should be addressed: https://github.com/parity-js/shell/issues/new
