### ISSUE TITLE
trace_transaction api bug

### ISSUE THREAD

**Issue by gaoxiangxyz** [paritytech/parity#7115]
> I'm running:
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

I use trace_transaction api to get traces of transaction "0x0c4298cfb123d7acd45d9a4782e10a091a2bdaa8bbbec33f8346e594db05a327", there are two traces 
have out of gas error as below, but the transaction has "Contract execution completed" flag on ethersacn.io, [see here](https://etherscan.io/tx/0x0c4298cfb123d7acd45d9a4782e10a091a2bdaa8bbbec33f8346e594db05a327).

TraceAddress [2,0,1,2]  out of gas
TraceAddress [2,0,1,3,0] out of gas

**Comment by 5chdn** [comment]
Please share your observations here: #7109
