### ISSUE TITLE
Why won't Parity sync? 

### ISSUE THREAD

**Issue by ArranMcC** [paritytech/parity#7120]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.0
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no, that's the problem. But the clock is synchronised
> - **Did you try to restart the node?**: yes many times

Expected behaviour - When I send ether or tokens to my Parity wallet, and the transfer is logged on etherscan. they will be available to view immediately, or at least within a few hours
Actual behaviour - Parity simply does not sync, despite regularly having 15-20 peers connected. It eventually reaches 100% warp restore, then freezes on one of the millions of blocks, or moves one block at a time. It also makes my laptop run very slowly, despite having 12GB ram and about 800gb hard drive space. I was given advice on gitter such as 'run geth' or 'inject web3 into something'. I have no idea how I would do any of these things, and feel like surely it should be Parity's responsibility to provide a wallet which doesn't have these issues. I've browsed other similar threads, seems like a lot of people have this problem, and there never seems to be a solution. Will my coins and tokens just be locked in this wallet forever, unable to be used?

**Comment by 5chdn** [comment]
At what block are you after warp restore? Are you on HDD? Please, consider getting an SSD.

Also, there is not much full clients can do about. Ethereum is processing 500k transactions per day, your client has to process them, this does not only mean a lot of CPU cycles on verifying transactions, contract executions, and blocks, but also a lot of disk I/O writing and reading state(s) to/from the database.

**Comment by ArranMcC** [comment]
Currently 4,600,504. Only about 2000 away but right now the total blocks are increasing much faster than my synced blocks, so the blocks still to be synced is constantly increasing. Seems to be syncing one block about every 10 seconds. I'll take the SSD advice on board. Is it standard for parity users to wait several hours, or several days, just for their wallet to sync? And then make a transfer, or view the wallet contents, and wait the same amount of time the next time they want to sync the wallet?

**Comment by ArranMcC** [comment]
Should also point out that I have 13 peers connected right now, there's no issue with that

**Comment by 5chdn** [comment]
> Is it standard for parity users to wait several hours, or several days, just for their wallet to sync? 

This is _standard_ for all users running a full Ethereum node, unfortunately.
