### ISSUE TITLE
Parity can't sync for 5 days: tries endlessly same IP addresses with closed 30303

### ISSUE THREAD

**Issue by mikhail-manuilov** [paritytech/parity#7122]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.8/1.7.9
> - **Which operating system?**: Linux
> - **How installed?**: via parity/parity:v.1.7.8/v1.7.9
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
parity options:
`- --db-path /usr/.parity/chains --auto-update none --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-cors '*' --nat extip:<ext ip of load balancer with open 30303>`

I'm running parity via StatefulSet in kubernetes 1.6.6 kubernetes in Azure and no cni works ok and syncing in one-two days.

But running parity in kubernetes 1.7.9 with calico cni 2.6.1 in five containers only one can sync successfully in normal time.

I've checked all nodes and ones not syncing have 8-13GB db size and 0-3 peers. The one that is syncing. Traffic from all of them goes through same external IP of load balancer (same setup as k8s 1.6.6)

I've decided to see some network traffic and got inside of each container:

```
# apt update && apt install tcpdump

# Whom we're sending syns (run for a 5 mins)
export DUMPHOST=`ifconfig eth0 | grep -P  'inet addr' | awk '{ print $2; }' | cut -d ':' -f2` && sudo tcpdump -n "((src host ${DUMPHOST}) and (dst port 30303)) and tcp[tcpflags] & (tcp-syn) != 0" |  awk '{ print $5; }' > syns

# Who sending RST to us (run for a 5 mins)
export DUMPHOST=`ifconfig eth0 | grep -P  'inet addr' | awk '{ print $2; }' | cut -d ':' -f2` && sudo tcpdump -n "((dst host ${DUMPHOST}) and (src port 30303)) and tcp[tcpflags] & (tcp-rst) != 0" |  awk '{ print $3; }' > rsts

# sort syns | uniq > syns_uniq
# sort rsts | uniq > rsts_uniq
```

After comparing saw nearly identical IP addresses:
```

136.243.154.244.30303:
138.201.144.135.30303:
163.172.187.252.30303:
212.47.247.103.30303:
216.158.85.185.30303:
37.128.191.230.30303:
46.20.235.22.30303:
51.15.42.252.30303:
52.16.188.185.30303:
54.94.239.50.30303:
88.212.206.70.30303:
```

And very little like 1 to 500 connects to another IP addresses, that picture was the same in every container but the one which is syncing ok and has 35GB db.

What's happening? Why parity tries these endlessly and has no success (because they are really closed, i've checked with nmap) and do not connect to another peers?

**Comment by 5chdn** [comment]
Please remove your nodes.json and try this again with 1.8.5.
