### ISSUE TITLE
Clarify parameters related to gas

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#7123]
> I'm running:
>
> - **Which Parity version?**: 1.8.x

Hello,

help me understand parameters that correspond to `gas`, specifically `gas limit` and `gas price`.
I'm using https://github.com/paritytech/parity/wiki/Configuring-Parity and https://github.com/paritytech/parity/wiki/Chain-specification as guides.

1. `gas-floor-target` Amount of gas per block to target when sealing a new
                                   block (default: 4700000).

what does it do exactly? I'm confused by "to target", how does it relate to gas limit? It seems like in PoA when sealing empty blocks without txs (--force-seal) this number is the block's gas limit.

2. do I understand correctly that gas limit of genesis block is set in spec and later controlled by `tx-gas-limit` of each mining node? Gas limit may change from block to block within limits set by `current gas limit*(1 ± 1/gasLimitBoundDivisor)`, but not higher than `--gas-cap`? Does it change because nodes update their `tx-gas-limit` or is it recalculated by the network?

3. how is gas price set? Neither of two docs above mention it, except for `--gasprice` option under `legacy` section in toml. Is it a network-wide value set in spec or does it also change from node to node?

Thanks

**Comment by 5chdn** [comment]
1. Yes, this is the target block gas limit (here: 4700000). If you change this, your client tries to raise/decrease the block gas limit towards the new target.

2. Yes, initially in the genesis block. And no, it is `--gas-floor-target` to change the block gas limit. `--tx-gas-limit` is only affecting transactions to be mined (or not if above that transaction gas limit).

3. Transaction gas price can be set with each new transaction individually. If you are asking about the minimum accepted transaction gas price, it's controlled by `--min-gas-price`. This is not network-wide, this can be set for each mining/sealing node individually.
