### ISSUE TITLE
Tokens not showing up

### ISSUE THREAD

**Issue by JediJuice** [paritytech/parity#7126]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3
> - **Which operating system?**: MacOS
> - **How installed?**: via installer download for mac
> - **Are you fully synchronized?**: yes, briefly this morning and not now.
> - **Did you try to restart the node?**: yes and reboot as well.

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
The following transaction does not appear in parity wallet, however, the PNS coin does and a small amount of ether does?

https://ethplorer.io/tx/0x88a7c70740285afc81e1f30a3e94ca56456032143ce98a74dbe6a88ba6f39f8f

**Comment by marshallstokes** [comment]
I have this same issue. I own a fully compliant ERC20 token, added the contract address to my watch list in Parity, but it won't display my balances or even the transactions for the token. Several other ERC20 tokens in Parity accounts are visible as expected.

**Comment by 5chdn** [comment]
@JediJuice mind sharing a screenshot?

**Comment by JediJuice** [comment]
![parity 23 nov](https://user-images.githubusercontent.com/13371797/33184910-70af51d4-d03c-11e7-9122-ed449c0e530e.png)

**Comment by Neurone** [comment]
This isn't an issue, it's an intended behaviour. Parity looks up only for tokens submitted in its own [Token Registry](https://github.com/paritytech/parity/wiki/Token-Registry), it does not show all ERC20 compatible tokens an address owns.

**Comment by harishperfect** [comment]
@Neurone From a dumb user perspective, it simply makes sense to have a hide option on the tokens displayed. Nobody wants to see Penis Coin as soon as they open a new wallet account. #Rant

**Comment by marshallstokes** [comment]
@Neurone I suppose this explains why I cannot interact with what seems to be a growing number of ERC20 tokens - they aren't in the registry. This alone is likely a deciding factor for countless end users when choosing a wallet to use or recommending wallet software to new users. The registry's 3-character limit on token tickers creates confusion and seems arbitrary and uncooperative; while it is nice to have a logo associated with token balances, only Parity users will see it, so if your token's ticker is TOKEN it might be better all around to instruct users to avoid Parity :(

I much prefer compatibility and freedom to choose for end users. Maybe Parity's team will consider allowing end users to see token balances of any ERC20 contract they are watching. It's a bit surprising this isn't the functionality already.

**Comment by 5chdn** [comment]
@harishperfect @marshallstokes see #6783 

@JediJuice see https://github.com/paritytech/parity/wiki/Token-Registry

**Comment by svenpohl** [comment]
Hi. Just for my interest: is the 'old' and 'unbelievable useful'  parity function to send Token directly from the wallet tokens to other addresses (similar to ETH - sending) "hidden"? Can I activate it somewhere? Is there a new hidden 1.9 function to re-enable the Token-View function? Thank you very much.

**Comment by 5chdn** [comment]
No, tokens are broken, please wait for 1.9.1

**Comment by svenpohl** [comment]
Thank you! Maybe offtopic, but I'm afraid to create a now issue-topic. Even in the "Parity syncs initially, then sleeps and wakes regularly to resync" - Mode my CPU - utilization is 100 - 250% (MacBook, permanent fan), since update to 1.9. Is this issue connected to the token-issue?... maybe some thread is trying to connect an external service, doesn't sleep after unsuccessful connect (just for example). The other functions seems to work excellent in parity 1.9.

**Comment by 5chdn** [comment]
No, this is the db compaction when upgrading, please let it running for some hours and it will finish eventually.

**Comment by svenpohl** [comment]
Thank you very much for supporting my question!

**Comment by 5chdn** [comment]
Just let us know if this persists for more than a reasonable time (i.e., if this still happens after 3 days). Another option is to reset the database and try again (if that is possible for you).

**Comment by rjfinn** [comment]
Every once in a while I can't see any tokens, including long standing ones.  Recently, it's consistently showing no tokens at all.  I can't xfer them using Parity and have to launch MyEthereumWallet, but I'd rather use Parity.

**Comment by 5chdn** [comment]
Please upgrade to 1.8.9

**Comment by tjomk** [comment]
It's the same with 1.9.3
