### ISSUE TITLE
Genius paste block in UI

### ISSUE THREAD

**Issue by crackcomm** [paritytech/parity#7127]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.8.3-beta-b49c44a-20171114/x86_64-linux-gnu/rustc1.21.0
> - **Which operating system?**: Linux

I would expect to be able to paste in this field - ![](https://screenshots.firefoxusercontent.com/images/db61aae0-5b3b-4a33-8057-b46f9b79c183.png)

It happens on firefox

**Comment by tomusdrw** [comment]
Pasting is disabled intentionally on Foundation chain, to prevent lost phrases.
We're forcing you to write down the phrase somewhere and re-type it in that field.

I imagine that it is inconvenient, but we were informed of many cases where people did not back the phrase up, so we decided to try to force them to do so.

**Comment by crackcomm** [comment]
This is what in title it says `"genius"`.

**Comment by 5chdn** [comment]
You can set `allYourBaseAreBelongToUs` to `true` in local storage to allow pasting. But I will not support you recovering any losses, better make sure you print out or write down the phrase somewhere.

https://github.com/paritytech/parity/commit/41c3b05a20d9be1100714ca4cc771135f0261824#diff-c3b306c9e26b82caff87d668e0502423R227

**Comment by crackcomm** [comment]
@5chdn thank you.
