### ISSUE TITLE
About two parity nodes as load balanced

### ISSUE THREAD

**Issue by johnluan** [paritytech/parity#7137]
Hi Guys, 
I have no where to ask, so have to create an issue here.

1) Identical parity nodes
I want to create two identical parity nodes to provide mining work. So I can load balance them. 
But how can I make the getwork content identical for two server? I assume the generated header hash not only use wallet address,  also use mac address.
 2)Health check
If we cannot do this, I can do Master + slave mode, but is there a health check service for parity?

Regards,

**Comment by 5chdn** [comment]
Just do the load balancing a step earlier and assign different clients to different servers. No need to provide the same work.
