### ISSUE TITLE
Simple one-line installer for Mac not working/failing silently

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#7143]
> I'm running:
>
> - **Which Parity version?**: 0.0.0 (Not installed yet)
> - **Which operating system?**: 
      System Version: macOS 10.13.1 (17B48)
      Kernel Version: Darwin 17.2.0
> - **How installed?**: bash <(curl https://get.parity.io -Lk)
> - **Did you try to restart the system?**: yes

 **Expected behavior** 

I expected one line installer would install parity. And if it fails in any case I should have been shown some error message.

**Actual**
I try to install parity using the one liner but the installation does not work. Here is the complete output of the command:

```
Ayushyas-MacBook-Pro:~ ayushyachitransh$ bash <(curl https://get.parity.io -Lk)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0    129      0 --:--:--  0:00:01 --:--:--   129
100  2990  100  2990    0     0    596      0  0:00:05  0:00:05 --:--:--  1377
Release selected is: beta
Running on Apple
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408  100   408    0     0    280      0  0:00:01  0:00:01 --:--:--   280
Upgrading parity from 0.0.0 to 1.8.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.9M  100 17.9M    0     0  1357k      0  0:00:13  0:00:13 --:--:-- 1814k
Password:
installer: Package name is Parity
installer: Upgrading at base path /
installer: The upgrade was successful.
Ayushyas-MacBook-Pro:~ ayushyachitransh$ which parity
Ayushyas-MacBook-Pro:~ ayushyachitransh$ 
```

After the message `installer: The upgrade was successful.` I am redirected to my browser at `127.0.0.1:8180` but that says `Failed to open page` and then I return to see terminal and find that parity was not installed.

**Comment by ddorgan** [comment]
I don't think it's normally put in your $PATH by the way. It would be launched via the icon (maybe this should change).

Can you see the binary file at: /Applications/Parity Ethereum.app/Contents/MacOS/parity ?

**Comment by AyushyaChitransh** [comment]
No, there is no such file at : /Applications/Parity Ethereum.app/Contents/MacOS/parity

**Comment by ddorgan** [comment]
Can you try again, did some updates on the script. If there's still an issue can you add set +x at the top of the script, run it and send all the output. Thanks!

**Comment by AyushyaChitransh** [comment]
Before testing the above process, I had parity 1.7.9 installed. Here are the steps I followed, and their output:

 - `parity --version`
> version Parity/v1.7.9-unstable-12940e4ed-20171113/x86_64-macos/rustc1.22.1

 - `bash <(curl http://get.parity.io -kL)`
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
100   170    0   170    0     0     35      0 --:--:--  0:00:04 --:--:--   397
100  5296  100  5296    0     0    916      0  0:00:05  0:00:05 --:--:-- 16866
/dev/fd/63: line 6: lsb_release: command not found
Release selected is: beta
Running on Apple
Upgrading parity from 0.0.0 to parity_1.9.0_macos.pkg
Password:
installer: Package name is Parity
installer: Upgrading at base path /
installer: The upgrade was successful.

 - `parity --version`
> version Parity/v1.7.9-unstable-12940e4ed-20171113/x86_64-macos/rustc1.22.1

 - Saved the script and put a `set +x` just after comments.
 - Tried again: `bash getParity.io.sh `
>\getParity.io.sh: line 8: lsb_release: command not found
Release selected is: beta
Running on Apple
Upgrading parity from 0.0.0 to parity_1.9.0_macos.pkg
Password:
Sorry, try again.
Password:
installer: Package name is Parity
installer: Upgrading at base path /
installer: The upgrade was successful.

 - ` parity --version`
> version Parity/v1.7.9-unstable-12940e4ed-20171113/x86_64-macos/rustc1.22.1

 - `whereis parity` returnd blank
 - `which parity` returned
>/usr/local/bin/parity

I suppose that this is the older one which was installed previous to the setup.

**Comment by AyushyaChitransh** [comment]
I verified that parity was installed at `Applications/Parity\ Ethereum.app/Contents/MacOS/parity`. I think that the problem lies with making an entry in the $PATH.

**Comment by sarthakumrao** [comment]
I too am facing the same issue. After installing from one liner, safari opened and complained something about keys.

After installation, I was not able to run parity. It still said `-bash: parity: command not found` Further diagnosis revealed that parity was installed at `Applications/Parity\ Ethereum.app/Contents/MacOS/parity` Adding this to path variable works:


    export PATH=$PATH:/Applications/Parity\ Ethereum.app/Contents/MacOS

**Comment by AyushyaChitransh** [comment]
Or another solution could be to create a soft link inside the existing path variables:

    ln -sF /Applications/Parity\ Ethereum.app/Contents/MacOS/parity /usr/local/bin/parity

**Comment by 5chdn** [comment]
the lsb_release issue is fixed https://github.com/paritytech/scripts/pull/24

**Comment by 5chdn** [comment]
the ln -sF is suggested in https://github.com/paritytech/scripts/pull/25 but up for discussion.

it should be also added to the uninstall script / cc @fevo1971
