### ISSUE TITLE
Whisper problem: PoW too low to compete with other messages (and potential source of error)

### ISSUE THREAD

**Issue by zot** [paritytech/parity#7144]
I'm running parity 1.8.3 on Linux, testing with both an installed release and a release built from source on a dev network. My Dapp is using web3.js 1.0.0-beta.18.

When I post a whisper message, I always get the error: "PoW too low to compete with other messages". I'm using using priority 10000 and ttl 100 (I've tested with many variations).

I added some debug logs and got an inconsistent result which I think may be linked to the problem.

`Whisper::post()` will return `Err(whisper_error("PoW too low to compete with other messages"))` if `relay()` returns `false`.  `Relay` is bound to `PoolHandle::relay()` in [whisper.rs, line 51](https://github.com/paritytech/parity/blob/master/parity/whisper.rs#L51) but relay seems to be behaving oddly, based on some debug logs I put in.  Here is the change I made:

```rust
fn relay(&self, message: Message) -> bool {
	let mut res = false;
	let mut message = Some(message);
	debug!(target: "whisper", "RELAYING...");
	self.net.with_proto_context(whisper_net::PROTOCOL_ID, &mut move |ctx| {
		if let Some(message) = message.take() {
			res = self.handle.post_message(message, ctx);
			debug!(target: "whisper", "POSTED MESSAGE, RES: {}", res);
		} else {
			debug!(target: "whisper", "NO MESSAGE POSTED");
        	}
	});
	debug!(target: "whisper", "FINISHED RELAYING, RES: {}", res);
	res
}
```
This produces the following log messages:
> 2017-11-26 13:53:01   DEBUG whisper  RELAYING...
> 2017-11-26 13:53:01   DEBUG whisper  POSTED MESSAGE, RES: true
> 2017-11-26 13:53:01   DEBUG whisper  FINISHED RELAYING, RES: false

The `with_proto_context block()` sets `res` to `true` but outside of the block, `res` is still `false`. This returns `false` to `Whisper::post()` and, I believe, results in the (wrongly reported) error.

**Comment by yrashk** [comment]
@zot I think your assessment is spot on. The reason `relay` compiles is because `bool` implements Copy and that's what happens within the move semantics. The value just gets copied.

**Comment by rphmeier** [comment]
Technically it's just an RPC error if the messages actually did get posted to the network. But nice catch and fix regardless!
