### ISSUE TITLE
v1.7.9 compile issue.

### ISSUE THREAD

**Issue by miningpoolhub** [paritytech/parity#7145]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.7.9
> - **Which operating system?**: Linux. Ubuntu
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Can't compile v1.7.9
Here's the log

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/paritytech/rust-secp256k1`
    Updating git repository `https://github.com/paritytech/rust-rocksdb`
    Updating git repository `https://github.com/paritytech/bn`
    Updating git repository `https://github.com/paritytech/hyper`
    Updating git repository `https://github.com/paritytech/jsonrpc.git`
    Updating git repository `https://github.com/paritytech/nanomsg.rs.git`
    Updating git repository `https://github.com/paritytech/libusb-rs`
    Updating git repository `https://github.com/paritytech/hidapi-rs`
    Updating git repository `https://github.com/paritytech/wasm-utils`
    Updating git repository `https://github.com/paritytech/rust-ctrlc.git`
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
error: failed to load source for a dependency on `parity-ui-precompiled`

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git?branch=stable#bbc5b6c3

To learn more, run the command again with --verbose.
```

**Comment by 5chdn** [comment]
Does it persist if you do a `cargo clean`?

**Comment by debris** [comment]
commit mentioned in the log exists on stable branch: https://github.com/paritytech/js-precompiled/commit/bbc5b6c3e3a43ab21b94d37922cdbed766c7b5c8

Each time we update our ui, cargo downloads the new version of it from github. Unfortunately, it does it by cloning the whole repository to a new location. Currently `paritytech/js-precompiled` is quite big, so it may take several seconds to download it. I guess that something interrupted your connection to a github server and this caused the build to fail.

related: https://github.com/rust-lang/cargo/issues/4373

**Comment by miningpoolhub** [comment]
I could compile parity by flushing .cargo/git
Seems like some file was corrupted.
Thanks
