### ISSUE TITLE
Export of current blockchain takes about 81 days 

### ISSUE THREAD

**Issue by mikhail-manuilov** [paritytech/parity#7148]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.9
> - **Which operating system?**: Linux
> - **How installed?**: parity/parity:v1.7.9
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
I'm doing export of 35GB blockchain according to https://github.com/paritytech/parity/wiki/FAQ:-Backup,-Restore,-and-Files

```
#du -h -d 0 /usr/.parity/chains
35G	/usr/.parity/chains
```
```
# /parity/parity --db-path /usr/.parity/chains export blocks /usr/.parity/chains2/bckp.rlp - 30 mins run
Logs:
2017-11-27 13:00:19 UTC Configured for Foundation using Ethash engine
2017-11-27 13:22:00 UTC #10000
2017-11-27 13:37:51 UTC #20000


# tar cf /usr/.parity/chains2/chains.tar /usr/.parity/chains - 13 mins run
```

```
ls -lah /usr/.parity/chains2
total 13G
drwxr-xr-x 4 root root 4.0K Nov 27 13:12 .
drwxr-xr-x 4 root root 4.0K Nov 27 13:00 ..
-rw-r--r-- 1 root root 8.9M Nov 27 13:30 bckp.rlp - will take 35000/18MB/24 =81 days to finish
-rw-r--r-- 1 root root  13G Nov 27 13:30 chains.tar - 1GB/min (16MB/s) - will take 35 mins to finish
```

Is it usable to backup and restore parity blockchain using official documentation?

**Comment by 5chdn** [comment]
IMHO you should just `rsync` the chaindata if you want to move this.

**Comment by robbiehanson** [comment]
Is it safe to just use `rsync` ? Is there a chance the database would get corrupted ?

**Comment by tjayrush** [comment]
I've copied the full parity database (--tracing on --pruning archive) from an internal SSD hard drive to an external SSD hard drive and back. It works "most" of the time. I've done it three or four times. It worked two or three of those copies. I think it failed once and then I had to re-build the whole thing. Copying the database with only --tracing on (no --pruning archive), I've done a lot more times than that, and it almost always works.

**Comment by robbiehanson** [comment]
To be more specific: I'm sure that `rsync` would work fine if parity server is NOT running. However, what if the parity server IS running? Is it safe to use rsync then? Does this present a possibility of corruption?

**Comment by tjayrush** [comment]
Never copied while Parity was running.

**Comment by 5chdn** [comment]
Yes, stop it for the rsync.

**Comment by yxliang01** [comment]
@5chdn Any advice for backing up while running? I need it kept running but meanwhile I also need to backup frequent..

**Comment by DangerDawson** [comment]
@yxliang01 could you not run multiple nodes? and then just bring that node down and rsync it

**Comment by yxliang01** [comment]
no... constrained by resource.. @DangerDawson
