### ISSUE TITLE
websockets.origins in config file not being parsed correctly

### ISSUE THREAD

**Issue by TrekDev** [paritytech/parity#7149]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.8.3-beta-b49c44a19-20171114/x86_64-linux-gnu/rustc1.21.0
> - **Which operating system?**: Linux
> - **How installed?**: pacman
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

`parity --ws-origins all` seems to work fine however using the config.toml 
```
[websockets]
origins = "all"
```
I get
```
Loading config file from config.toml
You might have supplied invalid parameters in config file.
invalid type: string "all", expected a sequence for key `websockets.origins`
```

**Comment by tomusdrw** [comment]
Can you try with
```
[websockets]
origins = ["all"]
```
?

**Comment by TrekDev** [comment]
Thank you that works. I was using the parity config generator to generate the config, so maybe this is really an issue for that.

**Comment by tomusdrw** [comment]
@TrekDev addressed in https://github.com/paritytech/parity-config-generator/pull/27 Thanks for reporting!
