### ISSUE TITLE
(Problem) Current limitation of number validators: 2400 max size

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#7151]
Validator_set engine depends on `InitiateChange` event that requires storing full list of validators.
 Since it's an array, this event could only be propagated with no more than 2400 array elements in it with gas Limit of 4700000.
It's design flaw dependency that could be eliminated if `InitiateChange` would only require signaling the system to make a call to `finalizeChanges`, not storing full members of the new list and then `finalizeChange` would apply necessary changes. 

https://github.com/paritytech/parity/wiki/Validator-Set
```
    event InitiateChange(bytes32 indexed _parent_hash, address[] _new_set);
```

why is there a need to store an array of members at all in the event?

**Comment by debris** [comment]
iirc, the array is not stored in an event, but only a hash of the array. Regardless, hashing so many elements is indeed a waste of resources.

@rphmeier @snd what do you think?

**Comment by rphmeier** [comment]
> It's design flaw dependency that could be eliminated if InitiateChange would only require signaling the system to make a call to finalizeChanges, not storing full members of the new list and then finalizeChange would apply necessary changes.

That won't work for light clients (or warp sync) unless we also add a `getPendingValidators() -> [Address]` function used to generate the necessary state proofs.

Embedding the new validator set in a log event means we don't have to store indefinitely state proofs for justification to light clients while syncing. Aura and Tendermint both will not function effectively with anywhere near 2400 validators, but you can always raise the gas limit.
