### ISSUE TITLE
Name registration ens.domains failed

### ISSUE THREAD

**Issue by roninkaizen** [paritytech/parity#7155]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
Parity version?**: 1.8.2
operating system?**: Linux
installed?**:  binaries 
fully synchronized?**:  yes
restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

After confirming my bid and 
controlling it on etherscan.io with following ID
https://etherscan.io/tx/0x5a9d20e202295bcae0fef85dd63a71658d491a909189c26ca8fa1520ff9c015f
there is a StartAuction with a complete different name. On demand i will write.
I only used parity and saved the bid. 
I am also looking for the log and will post it on demand.
As this behaviour is not wanted by me, it could be a bug.

**Comment by 5chdn** [comment]
Yes, this is how ENS works, it tries to obfuscate your actual bid. 

Not Parity-related at all.

**Comment by roninkaizen** [comment]
thanks, did as told.
