### ISSUE TITLE
Wallet UI not loading

### ISSUE THREAD

**Issue by foglerek** [paritytech/parity#7158]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity v1.9.0-20171127 unstable
> - **Which operating system?**: MacOS
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes (light)
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

The UI is mostly blank, I can't do anything with my wallet.

From a pruned db state, I run `parity --light` and this is the fully synced state.

<img width="1372" alt="screen shot 2017-11-28 at 09 09 41" src="https://user-images.githubusercontent.com/4604973/33326958-fd059cbe-d41b-11e7-8b71-27ac47d12af0.png">

**Comment by 5chdn** [comment]
Please check out `beta` branch before building parity from source. Master does not contain any functional user interface currently.

**Comment by foglerek** [comment]
This is also happening on stable and beta.

**Comment by foglerek** [comment]
@5chdn

**Comment by 5chdn** [comment]
Please, clear your browser cache or try a hard refresh.
