### ISSUE TITLE
ICO Tokens stuck on Contract - cant withdrawal to parity wallet

### ISSUE THREAD

**Issue by BlockwareSolutions** [paritytech/parity#7161]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?** yes
> - **Did you try to restart the node?**:yes
Hello -

I need some help, I got a bit confused with Parity and had created a contract from my Parity Wallet - then the tokens of the ICO that I participated in were sent to the contract Address.

I am the owner / creator of this contract. I need to figure out how I can transfer these tokens from that contract to my actual parity wallet. I have tried for a couple of months and am stuck, I originally did this when I was newer to Crypto Currencies - hence the mistake.

Appreciate any help I can get.

**Comment by 5chdn** [comment]
Make sure you have Ether on the owner of the contract to pay the transaction fees. Otherwise, just transfer the tokens with the UI like you would do it with any other account.
