### ISSUE TITLE
Blockchain data gets deleted every time I restart parity

### ISSUE THREAD

**Issue by travs** [paritytech/parity#7169]
I'm running:
```
$ parity --version
Parity
  version Parity/v1.8.2-beta-1b6588cb2-20171025/x86_64-linux-gnu/rustc1.21.0

$ uname -r
4.13.11-1-ARCH #linux
```

Installed via `pacman -S parity` (I think the package install just downloads a binary).

> **Are you fully synchronized?**: yes, but then no
> **Did you try to restart the node?**: yes

---

I run parity on the mainnet using the following arguments:

```
  parity \
    --chain mainnet \
    --author $ACCOUNT_DEPLOYER \
    --unlock $ACCOUNT_DEPLOYER \
    --rpcport 8545 \
    --auto-update=all \
    --cache-size 1024 \
    --snapshot-peers 36 \
    --mode active \
    --jsonrpc-apis all \
    --password  ~/prg/keys/mainnet/account_mainnet
```

I let it sync, it does its thing and syncs fully, then I close parity at some point.
When I restart it sometime later (could be hours or even minutes), it begins syncing snapshots again from the beginning.
I expect it to start from where it left off (near the latest block).

Could it be due to the `--mode active` flag and I just misunderstand [the docs](https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options)?

Apologies if this has already been reported; I can't find this one in the bug tracker.

**Comment by 5chdn** [comment]
If it starts the warp sync again, you are probably not even close to being fully synchronized. 

You might be affected by #6350. Can you confirm the block number is 4,649,000+ before you shut down Parity?

**Comment by 5chdn** [comment]
This? #6415

**Comment by travs** [comment]
> If it starts the warp sync again, you are probably not even close to being fully synchronized.

Ah I see, perhaps I was not fully synced, though I thought I was.
I am restarting my node frequently today, and have not had this issue again yet, after letting it sync overnight.
I am synced past the block number you mentioned right now, so will re-open if it happens again.
