### ISSUE TITLE
http://parity.io/ is the default website for parity on search results. and does not redirect to https://parity.io/

### ISSUE THREAD

**Issue by satoshe** [paritytech/parity#7181]
http://parity.io/ is the default website for parity on search results. and does not redirect to https://parity.io/

and https://parity.io/ does not work while http://parity.io works.

what is the reason for this? does the admin of parity.io want users to download comprimised wallets?

**Comment by satoshe** [comment]
![screenshot-2017-12-2 www parity io 502 bad gateway](https://user-images.githubusercontent.com/34113686/33510162-af66c996-d700-11e7-9567-1693154df9b4.png)

**Comment by kirushik** [comment]
Thanks for reporting this, everything should be back to normal now — please add another comment here if it's not for you.
