### ISSUE TITLE
What is the minimum hardware requirements to process payments for ETH and ERC20 tokens?

### ISSUE THREAD

**Issue by lugrugzo** [paritytech/parity#7182]
> I'm running:
>
> - **Which Parity version?**: version Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer binaries
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

I have 40 GB VPS and want to run parity to **process payment for both ETH and ERC20 tokens**. However when I run parity with following commands, blockchain size fills 40 GB:

`parity  --pruning fast`

**What is the minimum hardware requirements to process payments for ETH and ERC20 tokens?** I know for ERC20 I need full blockchain state for filter changes, but I wonder if a pruned node can work for me.

**Comment by lugrugzo** [comment]
Any tip would be helpful.

**Comment by Rexota** [comment]
This is one of the secrets in Ethereum community. You can't find any information when it comes to payments or other commercial stuff.

Jokes aside, maybe you can look at ethereum contracts.

**Comment by 5chdn** [comment]
I'll give it a shot

- 1 GB RAM
- 2 CPU Cores
- 50 GB SSD

Should work with a default parity configuration.

**Comment by lugrugzo** [comment]
I am using v1.8.2-beta.

**Comment by 5chdn** [comment]
Might be #6280

**Comment by roninkaizen** [comment]
get at least a dual core system with 2 GB RAM,
OS-up to you, would suggest linux, experience in curl-based transacting or willing to learn.
good luck!
