### ISSUE TITLE
Installing web3 as instructed will not work.  Please modify doc.

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7184]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.9
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: not necessary

The doc (https://github.com/paritytech/parity/wiki/Basic-Usage) says to run "npm install web3" but that installs a default version that will not work.  It is necessary to do:

> npm install web3@0.20

After that, the other instructions work.

**Comment by 5chdn** [comment]
Why is it not working with the latest web3 release? Can you tell?

**Comment by stone212** [comment]
@5chdn This is what I see without implementing the workaround:

```
    { [Function: send]
        method: [Object],
        request: [Function: bound ],
        call: 'shh_getSymKey' },
     deleteSymKey: 
      { [Function: send]
        method: [Object],
        request: [Function: bound ],
        call: 'shh_deleteSymKey' },
     newMessageFilter: 
      { [Function: send]
        method: [Object],
        request: [Function: bound ],
        call: 'shh_newMessageFilter' },
     getFilterMessages: 
      { [Function: send]
        method: [Object],
        request: [Function: bound ],
        call: 'shh_getFilterMessages' },
     deleteMessageFilter: 
      { [Function: send]
        method: [Object],
        request: [Function: bound ],
        call: 'shh_deleteMessageFilter' },
     post: 
      { [Function: send]
        method: [Object],
        request: [Function: bound ],
        call: 'shh_post' } },
  bzz: 
   Bzz {
     givenProvider: null,
     currentProvider: null,
     isAvailable: [Function],
     upload: [Function],
     download: [Function] } }
> web3.eth.blockNumber
undefined
> 
```

**Comment by debris** [comment]
I strongly disagree that it is a problem with parity. It is a problem with shitty web3 internals and should be resolved over there.

**Comment by stone212** [comment]
@debris I didn't say it is a problem with the Parity code.  But the doc gives instructions that do not work.  I gave the modified instructions that will work (as of 3 Dec!  Not sure why you are commenting now?)

**Comment by stone212** [comment]
@debris Are you saying that the problem is that web3 is "broken" somehow that means that Parity can't support it?  Specifically how so I can bring this to them.

@5chdn Is there a roadmap to have web3 1.0 working with Parity?  If not then you must have some knowledge of what is broken with web3 that needs to be fixed for Parity compatibility.  Then I can bring that Issue to web3.

**Comment by debris** [comment]
> Not sure why you are commenting now?

We are just going through old issues.

> Are you saying that the problem is that web3 is "broken" somehow that means that Parity can't support it? Specifically how so I can bring this to them.

Yes, it's just broken and we should not do any compromises. It should be resolved over there

> Is there a roadmap to have web3 1.0 working with Parity? If not then you must have some knowledge of what is broken with web3 that needs to be fixed for Parity compatibility. Then I can bring that Issue to web3.

I guess that at start web3 is just making some silly requests that are not supported by parity (we don't have shh interface). But this **should never** break the whole library. It's a web3 bug

**Comment by stone212** [comment]
> we should not do any compromises

Absolutely correct.  Two questions:

1. Is it possible to find out what these "silly requests" are so you or I or someone can take the Issues to the web3 team?

2. What is "shh interface"?  Did you mean ssh?  How does ssh interface have anything to do with web3?
