### ISSUE TITLE
cannot unregister token

### ISSUE THREAD

**Issue by davidqw** [paritytech/parity#7185]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.0
> - **Which operating system?**: MacOS
> - **How installed?**: via installer Homebrew
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have registered a token with parity Dapp some days before, now we deploy a new token for replacing the formal one. But I found the contract shows only the dapp's owner have the right to unregister, can you help me?

**Comment by davidqw** [comment]
@skddc @folsen @barrymac @celeduc @patrick99e99  anyone I should contact with? Thanks

**Comment by 5chdn** [comment]
I can do it. Please give me the TLA and Address.

**Comment by davidqw** [comment]
Thanks. A total of 2 TLA, i need to unregister them and register the 7A01 Address with PRO
PRO：0x20c11E5E049CC1F13B3F27780Cc7830059d92984
PRN：0x9041Fe5B3FDEA0f5e4afDC17e75180738D877A01

**Comment by davidqw** [comment]
@5chdn please refer the information above

**Comment by 5chdn** [comment]
Hey @davidqw I removed them both!

**Comment by davidqw** [comment]
@5chdn thanks a lot, but i can still find "PRO" in Token Registry Dapp

**Comment by davidqw** [comment]
@5chdn will you help me to remove the 'PRO' Token as well?  The 'PRN' has disappeared, thanks

**Comment by davidqw** [comment]
@5chdn The two token are both deployed by me with a same contract owner address :)

**Comment by davidqw** [comment]
@5chdn 
ID:390
NAME:ProToken
TLA: PRO

For more information in Etherscan, this token contract is no longer used by our team:)
https://etherscan.io/token/0x20c11E5E049CC1F13B3F27780Cc7830059d92984

**Comment by 5chdn** [comment]
Removed PRN

**Comment by 5chdn** [comment]
Removed PRO

**Comment by pirasath1985** [comment]
Hi Rando, Can you please delete my token please . Please see below information 
NAME:Organicco
TLA: ARG
Account Owner : Organicco Acc 
this contract address : 0x4acedbb500bebf6119770e4ad03ffc2bae75cc1a
https://etherscan.io/token/0x4acedbb500bebf6119770e4ad03ffc2bae75cc1a.
Thank you for your help.
