### ISSUE TITLE
https://get.parity.io redirects to wrong location

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#7189]
**Expected behavior**
One line installer should install parity. I should be able to install parity using 

`bash <(curl https://get.parity.io -kL)`

**Actual Behavior**

I get the following output on a linux system and same on OSX system:

```
bash <(curl https://get.parity.io -kL)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!doctype html>'
100 16002    0 16002    0     0  18621      0 --:--:-- --:--:-- --:--:-- 18606
curl: (23) Failed writing body (382 != 1363)
```

**Probable cause**
http://get.parity.io redirects to a webpage which is same as http://parity.io

**Comment by 5chdn** [comment]
@paritytech/ci asap please!

**Comment by barrymac** [comment]
Fixed redirect in old parity.io server
