### ISSUE TITLE
v1.8.3 - Can't use the UI - Chrome Error: WebSocket connection to 'ws://localhost/' failed

### ISSUE THREAD

**Issue by AntoniosHadji** [paritytech/parity#7199]
Parity Version 1.8.3
Ubuntu 16.04.3 
Chrome Version 62.0.3202.94 (Official Build) (64-bit)
installed via deb package from this repo
node fully synchronized
I did not restart after install.  

I have been running v1.7.9 with no issues.  
Today I upgraded to 1.8.3 via deb package I can't login to the UI. 

I see this error in chrome console:
```WebSocket connection to 'ws://localhost/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED```

after running ```parity signer new-token``` I get the same browser error message when launch from given link.  Also same error result if I manually paste token into dialog.

I see no errors in parity log.

**Comment by dhruvbansal** [comment]
I see the same error -- shouldn't Parity UI be trying to reach `ws://localhost:8546` ?

**Comment by AntoniosHadji** [comment]
This issue does not exist for me when installing 1.8.10
