### ISSUE TITLE
No Option To Create Multi-Sig Wallet?

### ISSUE THREAD

**Issue by PiedPieper** [paritytech/parity#7200]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?** Parity/1.7.9/1.21.0/ma
> - **Which operating system?**: MacOSX
> - **How installed?**: brew
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: yes

I am on the ropsten chain trying to learn. There is no option to create a multi-sig wallet, only to "watch a wallet". In some docs:http://johnmathews.eu/ethereum-parity-multisig-wallet.html it shows an option to create the multi-sig. Why is this option not here?

**Comment by kirushik** [comment]
Currently we only support third-party multisig wallets, and not automatically deploying a new one for you.
You can pick any third-party multisig wallet you trust (those are just smart-contracts controlling the corresponding funds in Ethereum, after all) -- and after deployment you'll be able to add it into the Parity interface.

THis our approach might or might not change in the future.

**Comment by 5chdn** [comment]
We are still supporting them, you just have to manually chose and deploy one.
