### ISSUE TITLE
Contract Page is too slow if contract sends too much events

### ISSUE THREAD

**Issue by 3esmit** [paritytech/parity#7201]
Since: Parity Web.

Solution: Provide option to select what events I want to listen, if any.

**Comment by 5chdn** [comment]
Please, use our issue template. ;)

**Comment by 3esmit** [comment]
I think that the template didn't fit the case, and this shouldn't be the case for close it and set invalid, anyway feel free to reopen this issue in the model you wish, @5chdn.

**Comment by 5chdn** [comment]
Okay, maybe just be more verbose about what you are experiencing, or maybe add some steps to reproduce and I will be able to look into it.

**Comment by 3esmit** [comment]
What I'm experiencing: I'm having slowness while in CryptoKitties watched contract, seems like its for too much events.
How to reproduce: Watch for both CryptoKitties contract, and try using that for a while.

**Comment by 5chdn** [comment]
Thanks :)

**Comment by Tbaut** [comment]
Moving to a new repo, we will not migrate low prio issues. Please reopen it in the new repo if you believe it should be addressed: https://github.com/parity-js/shell/issues/new
