### ISSUE TITLE
Mined block was not propagated. 

### ISSUE THREAD

**Issue by mzanoli** [paritytech/parity#7207]
I'm running:

- **Which Parity version?**: 1.8.2
- **Which operating system?**: Linux Ubuntu 16.04 lts
- **How installed?**: binaries
- **Are you fully synchronized?**: yes
- **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I'm running a pool. After a worker mined a block, parity confirmed it, but the block was rewarded to another pool. This is the parity log line:
Dec  4 20:16:49 parity001 parity[5581]: 2017-12-04 20:16:49  Submitted block imported OK. #4675746: ec8bd8ce80482feff81e90a12b3ab772195852404ad2cbe506dca44bc5b13611

Normally after this log line we'd get the reward, but not this time. Our network is fully connected, we have a public static ip and parity is connected regularly to 50 peers.

Any idea? Maybe a bug in parity?

**Comment by 5chdn** [comment]
Thanks for raising this. Your block above was mined seven seconds after block 4675746 was mined. Not sure if this qualifies as an uncle.

So the issue might have been that your parity node did not get the block in time.

**Comment by mzanoli** [comment]
Do you think it could be a problem related to other peers or to a bad configuration? We run a pool of 22ghs connected with a static ip address. Outside network ping is 11ms, very low. I'm asking how we got the block 7 seconds late...

**Comment by gambol** [comment]
hi, I also got this problem.
