### ISSUE TITLE
Thread 'main' panicked at 'failed to update version

### ISSUE THREAD

**Issue by ronalterde** [paritytech/parity#7209]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.8.3-beta-b49c44a-20171114/x86_64-linux-gnu/rustc1.21.0
> - **Which operating system?**: Linux
> - **How installed?**:Installed via Ubuntu 14.04 packet manager.
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

2017-12-05 21:39:23  State DB configuration: fast
2017-12-05 21:39:23  Operating mode: active
2017-12-05 21:39:23  Configured for Foundation using Ethash engine
2017-12-05 21:39:24  Updated conversion rate to Ξ1 = US$458.04 (259906600 wei/gas)

====================

stack backtrace:
   0:     0x7fd57d12d08c - <no info>

Thread 'main' panicked at 'failed to update version: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

**Comment by 5chdn** [comment]
please reset your database and try again

    parity db kill

**Comment by ronalterde** [comment]
This fixed it. Thanks!
