### ISSUE TITLE
parity stops returning filtered pending transactions

### ISSUE THREAD

**Issue by tzapu** [paritytech/parity#7211]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3
> - **Which operating system?**: Linux
> - **How installed?**: docker
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Hello,

At times parity simply stops returning anything on `eth_getFilterChanges`

I have added a trace log, it's quite big, but shows transactions in and out and get filter changes working and then simply not returning anything anymore. 

I can't figure out what could cause this, any hints in helping pinpoint this further are welcome.

https://gist.github.com/tzapu/df6a35075cd7e685729bf9c1120990e7

Thank you very much

**Comment by debris** [comment]
There were recently fixes done for this rpc and the issue should be solved. Please try the latest version of parity and reopen the issue if still relevant

**Comment by cubedro** [comment]
Awesome, thank you @debris!

**Comment by kamilk91** [comment]
`{"jsonrpc":"2.0","result":[],"id":1}
`

parity 1.9.7, ubuntu 17.04, still empty
