### ISSUE TITLE
Error { repr: Os { code: 2, message: "No such file or directory" } }

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7212]
> I'm running:
>
> - **Which Parity version?**: 1.7.9
> - **Which operating system?**: Debian 9
> - **How installed?**: via binaries (error does not happen when compiling from source)
> - **Are you fully synchronized?**: no (not applicable)
> - **Did you try to restart the node?**: yes

Cannot generate a new signer token.  This happens:

```
# parity signer new-token
Error generating token: Error { repr: Os { code: 2, message: "No such file or directory" } }
```

What " file or directory" is it looking for?

Is it possible that the error is because libssl-dev was not installed?  That package has to be manually installed to compile Parity from source but it is not a dependency of the .deb package.

**Comment by 5chdn** [comment]
It's looking for 

    ~/.local/share/io.parity.ethereum/signer/authcodes

Probably. What are the permissions on this file?

**Comment by stone212** [comment]
I will look for that the next time I have this issue.  This time I simply compiled from source.

**Comment by ravensorb** [comment]
I too am running into this issue using the latest docker container

**Comment by ravensorb** [comment]
Any update on being able to generate new tokens? 

I am getting the following

```
./parity signer new-token -lsigner=trace
```

```
2018-04-06 12:12:58 UTC main TRACE signer  New authentication token generated.
Error generating token: Error { repr: Os { code: 2, message: "No such file or directory" } }
```

I am running as root inside a docker container 

```
root@040972efe4a8:/parity# ls -al /opt/parity/signer/
total 12
drwxr-xr-x 2 root root 4096 Mar 24 10:54 .
drwxr-xr-x 9 root root 4096 Apr  5 18:39 ..
-rw------- 1 root root   38 Mar 25 18:12 authcodes
```
and yes, I have remapped the location of the base folder inside the docker container via config.

Note: I can generate wallet addresses without issue.

**Comment by stone212** [comment]
@ravensorb What version of Parity are you using?  I opened this ticked with 1.7.x but have not had the error with 1.9.x.

**Comment by ravensorb** [comment]
I am running the docker stable image right now.

**Comment by Tbaut** [comment]
Please give it a try with the following flags :
`sudo docker run --rm -ti --name parity -p 8180:8180 -p 8545:8545 -p 30303:30303 -p 8546:8546 -v ~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/ parity/parity:beta --ws-interface all --jsonrpc-interface all --ws-origins all --ui-interface all`
Please make sure that you eventually replace "all" with your IP

**Comment by trappist** [comment]
I just fixed possibly the same problem (same symptoms) on ubuntu by installing the xdg-utils package. `strace -e -fF trace=file` showed `xdg-open` as the missing file.

**Comment by ravensorb** [comment]
Good find -- the hard part is, those are part of the Desktop system (X windows based) correct?  If so, that doesn't go over to well on a server deployment :)

**Comment by trappist** [comment]
It does sound like that kind of thing, and this was on a headless ubuntu box (which may have X headers and libs installed).
