### ISSUE TITLE
Rejecting a request to edit/cancel a transaction removes said transaction from the Signer tab

### ISSUE THREAD

**Issue by sorccu** [paritytech/parity#7220]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
Parity//v1.8.3-beta-b49c44a-20171114/x86_64-macos/rustc1.21.0
> - **Which operating system?**: Windows / MacOS / Linux
Mac
> - **How installed?**: via installer / homebrew / binaries / from source
Installer
> - **Are you fully synchronized?**: no / yes
Yes
> - **Did you try to restart the node?**: no / yes
Yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

It seems that if you attempt to cancel or edit a pending transaction and then reject request, the transaction still gets removed from the Local Transactions list. This makes it seemingly impossible to attempt a cancellation again.

I'm not very familiar with the Parity codebase, but looking at https://github.com/paritytech/parity/blob/41eabfcc1e26c9a72828f5e6b85080c36d75acad/js-old/src/ui/TxList/store.js#L133 and https://github.com/paritytech/parity/blob/41eabfcc1e26c9a72828f5e6b85080c36d75acad/js-old/src/ui/TxList/store.js#L157, it seems that the transaction is first removed, and then a new transaction is created. However, if that new transaction is then rejected, no attempt is made to recover the original transaction. I would expect it to reappear since no change was actually made.

I expect many people to hit this issue now that the gas prices are out of control and it's easy to have a low-priced transaction get stuck.

Also note that I use a Ledger Nano S.

**Comment by Tbaut** [comment]
Moving to a new repo, we will not migrate low prio issues. Please reopen it in the new repo if you believe it should be addressed: https://github.com/parity-js/shell/issues/new
