### ISSUE TITLE
Not compiling on Ubuntu

### ISSUE THREAD

**Issue by jbentke** [paritytech/parity#7225]
> I'm running:
>
> - **Which Parity version?**: latest
> - **Which operating system?**: Linux
> - **How installed?**: from source

**steps to reproduce** Follow instructions given for installing from source
**actual** compiling fails on multiply library's 
**expected behaivior** compiles without errors

I get rust errors that warn against experimental features. I installed on fresh Ubuntu with 

```$ curl https://sh.rustup.rs -sSf | sh ```

I got it to work using

```$ curl -sf -L https://static.rust-lang.org/rustup.sh | sh```

**Comment by 5chdn** [comment]
This is certainly a rustup issue.

Good think the other link worked for you.
