### ISSUE TITLE
sometimes trace_filter returns empty array whilst in fact there is a transaction matching the filter

### ISSUE THREAD

**Issue by gituser** [paritytech/parity#7228]
I'm running:

*Which Parity version?**: 1.7.8
**Which operating system?**: Linux
**How installed?**: from source
**Are you fully synchronized?**: yes
**Did you try to restart the node?**: yes

I'm running `Parity/v1.7.8-unstable-d5fcf3b-20171025/x86_64-linux-gnu/rustc1.19.0` self-compiled with options `/home/ethereum/parity --author xxx --chain=frontier --mode=active --mode-timeout 10 --mode-alarm 30 --cache-size 10240 -l 3 --datadir /home/ethereum/.parity --port xxx --min-peers 50 --max-peers 100 --jsonrpc-interface x.x.x.x --jsonrpc-port xxxx --ipc-apis web3,eth,net,personal,traces,rpc,parity,parity_set,parity_accounts --jsonrpc-apis web3,eth,net,personal,traces,rpc,parity,parity_set,parity_accounts --ipc-path /home/ethereum/.parity/parity.ipc --db-path /home/ethereum/.parity --keys-path /home/ethereum/.parity/keys --dapps-path /home/ethereum/.parity/dapps --no-ui --no-dapps --allow-ips=public --pruning-history 1024 --tracing on`

Sometimes `trace_filter` returns `array(0) {}` when in fact there is a transaction matching that address.

Strangely enough I've tried `trace_filter` on another node with the exact same version and exact same options (as I posted above) and it works there!

What could be the reason and how to fix if possible?

Both nodes ofc are synced to the top of the blockchain.

**Comment by 5chdn** [comment]
related #7211

**Comment by gituser** [comment]
Thanks for the acknowledgement. Would be nice to fix this issue ASAP if possible.

**Comment by gituser** [comment]
still no update on this? running `v1.8.6` and still the same bug

**Comment by ALFAcashier** [comment]
Anything on this? Still getting this issue from time to time.

Thanks.

**Comment by gituser** [comment]
5 more releases and still no fix for this?

**Comment by 5chdn** [comment]
Pull requests welcome :)

If you know Rust developers with some free time, feel free to send them my way. Any help appreciated!

**Comment by gituser** [comment]
What happened with all your parity developers?

I'm not good in Rust, so unfortunately can't fix the issue myself.

**Comment by 5chdn** [comment]
They are busy hacking polkadot, parity-wasm, rust-libp2p, parity-bridge, etc. pp. We need more hands on the Ethereum client.

**Comment by gituser** [comment]
>They are busy hacking polkadot, parity-wasm, rust-libp2p, parity-bridge, etc. pp. We need more hands on the Ethereum client.

do you mean that frozen contract? is there anything possible to do with it except forking?

parity was always the leading client in terms of performance but now starting to fall back again due many bugs (e.g. losing peers from time to time - the only workaround i've found is to stop node, remove nodes.json and start it again so it syncs again) and this bug with tracing is quite annoying as well.

would be nice to pick up the focus back on parity as it's a core software from you guys imo.

thanks.

**Comment by gituser** [comment]
I guess the fix has only been applied to `1.9.4` ?

`1.9.4` is failing for me right now on testnet: https://github.com/paritytech/parity/issues/7999#issuecomment-371208226

**Comment by gituser** [comment]
So, just to re-iterate, to get this issue fixed you need:
* latest version of `parity 1.9.6` (right now)
* full re-sync of the blockchain with `tracing=On`
