### ISSUE TITLE
Error on starting parity

### ISSUE THREAD

**Issue by nicholasfoden** [paritytech/parity#7229]
> I'm running:
> - version Parity/v1.8.3-beta-b49c44a-20171114/x86_64-windows-msvc/rustc1.20.0
> - via installer windows 10 x64
> - was fully synced when last closed
> - here is the terminal output on starting parity from the command line.
> - third time this week I have had to completely resync parity

```
./parity.exe
2017-12-06 21:36:44 UTC Starting Parity/v1.8.3-beta-b49c44a-20171114/x86_64-windows-msvc/rustc1.20.0
2017-12-06 21:36:44 UTC Keys path C:\Users\nick\AppData\Roaming\Parity\Ethereum\keys\Foundation
2017-12-06 21:36:44 UTC DB path C:\Users\nick\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d
2017-12-06 21:36:44 UTC Path to dapps C:\Users\nick\AppData\Roaming\Parity\Ethereum\dapps
2017-12-06 21:36:44 UTC State DB configuration: fast
2017-12-06 21:36:44 UTC Operating mode: passive
2017-12-06 21:36:44 UTC Configured for Foundation using Ethash engine
2017-12-06 21:36:44 UTC Updated conversion rate to Ξ1 = US$431.00 (276212580 wei/gas)

====================

stack backtrace:
   0:     0x7ff7792d2054 - hid_error
   1:     0x7ff7792d255b - hid_error
   2:     0x7ff778af1134 - <no info>
   3:     0x7ff77944b564 - hid_error
   4:     0x7ff77944b3d9 - hid_error
   5:     0x7ff77944b2b2 - hid_error
   6:     0x7ff77944b220 - hid_error
   7:     0x7ff779454b0f - hid_error
   8:     0x7ff779454b80 - hid_error
   9:     0x7ff778eb6ea4 - <no info>
  10:     0x7ff778d751eb - <no info>
  11:     0x7ff778b3f200 - <no info>
  12:     0x7ff7788a75ed - <no info>
  13:     0x7ff7788c07f7 - <no info>
  14:     0x7ff7788c61c3 - <no info>
  15:     0x7ff7788c9cf7 - <no info>
  16:     0x7ff77944cb12 - hid_error
  17:     0x7ff77944bce2 - hid_error
  18:     0x7ff779662b99 - hid_write
  19:     0x7ffbb2c52774 - BaseThreadInitThunk

Thread 'main' panicked at 'First block is always set to an existing block or `None`. Existing block always has a number; qed', src\libcore\option.rs:819

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

```

**Comment by nicholasfoden** [comment]
deleting overlayrecent from the chains/ethereum folder fixes the problem. however I am unsure how the chain got itself into this state.

**Comment by nicholasfoden** [comment]
I re synced my blockchain and this happened again after parity had restarted a few times. will try and replicate the issue and provide steps.

**Comment by nicholasfoden** [comment]
To replicate:
> Have previously synced blockchain
> Delete %APPDATA%/Local/Parity/chains folder
> Wait for warp to complete 
> shutdown parity
> start parity
> wait for chain to warp and sync
> have latest blocks syncing 
> restart computer
> open parity
> get error

**Comment by 3esmit** [comment]
Can you check the disk space?

**Comment by geiszla** [comment]
I get the same error, just with all of them being "hid_error" and not "<no info>", and I have ~70GB free space on the partition where the blockchain database is. Another thing to note is that this error only came up at a later point of syncing (at block #4463711). Before it I had no problem at all.

**Comment by niklasad1** [comment]
@nicholasfoden

Hi, can you upgrade to `parity 1.9.4` or later and verify if you still have this issue.

If that is the case, can you verify if you get these errors running parity without hardware-wallet:
```
parity.exe --no-hardware-wallets
```

If that works then run parity with hardware wallet and provide the logs please:
```bash
parity.exe -l hardware_wallet=trace
```

**Comment by nicholasfoden** [comment]
@niklasad1
Seems to be fixed now!

**Comment by nicholasfoden** [comment]
updated to Parity v1.9.5-20180321 stable
it is stuck on 
5,334,029/5,337,843 syncing
25/25 peers
for the last 2 hours now.

**Comment by nicholasfoden** [comment]
ok after restarting with `--no-hardware-wallets` it is still stuck (after warp restore) at:

... `Syncing #5334029 ed32…7635     0 blk/s    0 tx/s   0 Mgas/s      0+ 1237 Qed  #5335269   25/25 peers      3 MiB chain   62 MiB db   93 MiB queue    4 MiB sync  RPC:  1 conn, 18 req/s, 296 µs` ... 

now deleting chains folder and starting with  `--no-hardware-wallets`  again... 

will post again if it syncs or not...

**Comment by niklasad1** [comment]
@nicholasfoden 

Ok, so if I understand `parity` doesn't crash anymore with or without hardware wallet? 

Instead, syncing is stuck? 

That's a different issue and If you can confirm I will close this issue and you have to open another issue regarding the syncing.

**Comment by nicholasfoden** [comment]
oops, yes. it doesn't crash anymore. sorry you are correct this is a different issue. I was getting this behaviour before it started crashing last time. I will find the relevant issue and post there.
