### ISSUE TITLE
How to trace my own token(Ethereum-based token) issued on Ethereum?

### ISSUE THREAD

**Issue by Feuda** [paritytech/parity#7247]
For example, my token's name is O2O, how can I trace an O2O transaction on special address? As we know that an address can hold multiple types of token, ETH, O2O, .etc, how can I trace the type to know that the transaction belongs to which token? Does the JSON-RPC method 'trace_filter' work and which param hold the type?

**Comment by 5chdn** [comment]
Hey @Feuda - tokens are just a smart contract that store balances for each token holder.

To trace transactions related to your token, all you have to do is filtering the token contract executions for transfers.
