### ISSUE TITLE
Synchronizing Parity Signer with accounts.

### ISSUE THREAD

**Issue by Krum3l88** [paritytech/parity#7249]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:1.8.2. beta
> - **Which operating system?**:  MacOS 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Where at first I needed to sign transactions by password I now need to do so with Parity signer app on my telephone. How can I get synchronized between telephone and computer Parity? I seem only to be able to add new accounts within the Parity signer app. As such, I cannot sign transactions. Please help me out!

**Comment by 5chdn** [comment]
Hey @Krum3l88 - you don't need external accounts, you can open your Wallet and go to ACCOUNTS, click + ACCOUNT, and select NEW ACCOUNT, this will create an account on your computer without the link to the mobile signer app. Let me know if you have any further questions.

**Comment by Krum3l88** [comment]
Dear Afri,


I already have Parity accounts, but I need to sign with Parity signer to make a transfer. Before I just needed to insert my password, but somehow I now need to sign it with Parity signer. Do I still need to make a new account? Even though, I already have an account? Hope you can help me out. Thanks in advance!


kind regards,


Lucas


________________________________
Van: Afri Schoedon <notifications@github.com>
Verzonden: dinsdag 12 december 2017 09:30
Aan: paritytech/parity
CC: Krum3l88; Mention
Onderwerp: Re: [paritytech/parity] Synchronizing Parity Signer with accounts. (#7249)


Hey @Krum3l88<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkrum3l88&data=02%7C01%7C%7C9e59efaafbcc41ea501008d54175517f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636486894483527068&sdata=uDentfCanovfmpIOJksu5rozSNgi1GsRX5V7spKQ1nQ%3D&reserved=0> - you don't need external accounts, you can open your Wallet and go to ACCOUNTS, click + ACCOUNT, and select NEW ACCOUNT, this will create an account on your computer without the link to the mobile signer app. Let me know if you have any further questions.

**Comment by 5chdn** [comment]
I am not sure if I understand your issue. What do you mean by "Parity Signer"? The mobile signer app? Or the small Overlay in the wallet that pops up?

**Comment by Krum3l88** [comment]
The overlay in the wallet says I need to scan a QR code with Parity signer or something like that. Whereas in the past I needed to use my password.

Greetings, Lucas

Verstuurd vanaf mijn iPhone

Op 12 dec. 2017 om 18:57 heeft Afri Schoedon <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I am not sure if I understand your issue. What do you mean by "Parity Signer"? The mobile signer app? Or the small Overlay in the wallet that pops up?

**Comment by 5chdn** [comment]
But have you ever used the mobile signer app?

**Comment by Krum3l88** [comment]
No I have not. Downloaded it after Parity somehow changed to Parity signer instead of password though.

Verstuurd vanaf mijn iPhone

Op 14 dec. 2017 om 12:52 heeft Afri Schoedon <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


But have you ever used the mobile signer app?

**Comment by 5chdn** [comment]
I see, this should not happen.

**Comment by Krum3l88** [comment]
Anyone knows how to fix this? Still having this problem

**Comment by russianNinja** [comment]
I have this problem too

**Comment by 5chdn** [comment]
@jacogr do you know what's going on here?

**Comment by Tbaut** [comment]
This issue hasn't been updated for a while. Please reopen it in the dedicated UI repo if it still happens https://github.com/parity-js/shell/issues/new
