### ISSUE TITLE
Wiki update required

### ISSUE THREAD

**Issue by GoldenDave** [paritytech/parity#7250]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.8
> - **Which operating system?**: / MacOS /
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Wiki states : 

eth_newBlockFilter
-------------------

Creates a filter in the node, to notify when a new block arrives. To check if the state has changed, call eth_getFilterChanges.
.......

-----

This is correct but the section on `eth_getFilterChanges` does not mention that the return data is different when you have a BlockFilter

eth_getFilterChanges
----------------------

Polling method for a filter, which returns an array of logs which occurred since last poll.

----

Would be better modified to say 

eth_getFilterChanges
----------------------

Polling method for a filter which, depending on the filter returns an array of 

* logs which occurred since last poll if a Log Filter is used

* block hashes which occurred since last poll if a Block Filter is used

with examples of each given

**Comment by 5chdn** [comment]
Hi Dave, these docs are generated from the source code.

    $ cd parity/js
    $ npm i && npm run build:markdown
    $ ls -lsha docs/*.md

You can suggest improvements directly by editing the source at: ... where did the source go lol... @jacogr can you comment on this for a second?

**Comment by folsen** [comment]
Closing as stale documentation issue. If still relevant please submit issue to wiki repo.
