### ISSUE TITLE
money gone

### ISSUE THREAD

**Issue by hiheyhi** [paritytech/parity#7253]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/1.7.0/1.18.0/wi
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**:yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I tried to transfer eth out, but it stop syncing at 4370,001 , so I delete the file here
C:\Users\user\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d\overlayrecent\db
then I open my wallet, my eth shows 0 !!! Why???? where are my eth??
so worry about it, please help!!

**Comment by brandoncurtis** [comment]
You can only know your Ether balance when you node is fully synchronized with the network.  Please resynchronize your node and check again.

In the meantime, if you know your Ethereum address, you can check the balance here: https://etherscan.io/

**Comment by 5chdn** [comment]
Try to update your software. https://github.com/paritytech/parity/releases
