### ISSUE TITLE
Build Failed on CentOS 7.4

### ISSUE THREAD

**Issue by vsdigitall** [paritytech/parity#7255]
Hello, and thanks for what you're doing.

I am trying to build parity from sources with following command query:

> $ git clone https://github.com/ethcore/parity
> $ cd parity
> $ cargo build --release

And I am getting constantly this error (tested on two powerful servers):

>    Compiling primal v0.2.3
> error: failed to run custom build command for `hidapi v0.3.1 (https://github.com/paritytech/hidapi-rs#2e618213)`
> process didn't exit successfully: `/root/parity/target/release/build/hidapi-403d0991c4ed2193/build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("3")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("false")
> running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/root/parity/target/release/build/hidapi-9d76d20f26bef325/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c"
> cargo:warning=etc/hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
> cargo:warning= #include <libudev.h>
> cargo:warning=                     ^
> cargo:warning=compilation terminated.
> exit code: 1
> 
> --- stderr
> thread 'main' panicked at '
> 
> Internal error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "etc/hidapi/hidapi" "-Wall" "-Wextra" "-o" "/root/parity/target/release/build/hidapi-9d76d20f26bef325/out/etc/hidapi/linux/hid.o" "-c" "etc/hidapi/linux/hid.c" with args "cc" did not execute successfully (status code exit code: 1).
> 
> ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:4
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by vsdigitall** [comment]
If I use this method:
> $ cargo install --git  https://github.com/paritytech/parity.git parity

I receive the following error:
>  Downloading foreign-types-shared v0.1.1
> error: failed to compile `parity v1.9.0 (https://github.com/paritytech/parity.git#fcddc775)`, intermediate artifacts can be found at `/tmp/cargo-install.f7tF7m4Q4pap`
> 
> Caused by:
>   Multiple packages link to native library `ring-asm`. A native library can be linked only once.
> 
> Package `ring v0.9.7`
>     ... which is depended on by `multihash v0.6.0`
>     ... which is depended on by `parity-rpc v1.9.0 (https://github.com/paritytech/parity.git#fcddc775)`
>     ... which is depended on by `parity-rpc-client v1.4.0 (https://github.com/paritytech/parity.git#fcddc775)`
>     ... which is depended on by `parity v1.9.0 (https://github.com/paritytech/parity.git#fcddc775)`
> links to native library `ring-asm`.
> 
> Package `ring v0.12.1`
>     ... which is depended on by `multihash v0.7.0`
>     ... which is depended on by `cid v0.2.3`
>     ... which is depended on by `parity-rpc v1.9.0 (https://github.com/paritytech/parity.git#fcddc775)`
>     ... which is depended on by `parity-rpc-client v1.4.0 (https://github.com/paritytech/parity.git#fcddc775)`
>     ... which is depended on by `parity v1.9.0 (https://github.com/paritytech/parity.git#fcddc775)`
> also links to native library `ring-asm`.
>

**Comment by Frzifus** [comment]
same here

**Comment by 5chdn** [comment]
Please update your rust to 1.21.0+ thanks!

**Comment by vsdigitall** [comment]
Hello, rust 1.22.1, the same error..

**Comment by Frzifus** [comment]
i did try this in a new archbase docker container. Doesnt work for me.

**Comment by vsdigitall** [comment]
looks like we need to use ubunto or mac to get parity work..

**Comment by tomusdrw** [comment]
Cargo install is broken, please don't use it like this:
`$ cargo install --git https://github.com/paritytech/parity.git parity` 
Details: #6007

To build parity clone the repo and build using:
`$ cargo build --release && sudo cp ./target/release/parity /usr/loca/bin/parity`

**Comment by vsdigitall** [comment]
actually I tried both methods with no success, looks like developers are using mac & ubuntu, and other *nix-es are not tested yet

**Comment by tomusdrw** [comment]
Just noticed:
```
cargo:warning=etc/hidapi/linux/hid.c:44:21: fatal error: libudev.h: No such file or directory
```

Did you install required dependencies:
https://github.com/paritytech/parity#build-dependencies

?

**Comment by vsdigitall** [comment]
You mean this? 

**`yum install gcc g++ libssl-dev openssl libudev-dev pkg-config`**

These deps are installed..

> [root@3 parity]# yum install gcc g++ libssl-dev openssl libudev-dev pkg-config
> Loaded plugins: fastestmirror, langpacks
> Loading mirror speeds from cached hostfile
>  * base: mirror.denit.net
>  * epel: mirror.nl.leaseweb.net
>  * extras: mirror.i3d.net
>  * updates: mirrors.supportex.net
> Package gcc-4.8.5-16.el7_4.1.x86_64 already installed and latest version
> No package g++ available.
> No package libssl-dev available.
> Package 1:openssl-1.0.2k-8.el7.x86_64 already installed and latest version
> No package libudev-dev available.
> No package pkg-config available.
> Nothing to do
>

**Comment by vsdigitall** [comment]
After installing

**pkg-config:**
```
$ wget ftp://mirror.switch.ch/pool/4/mirror/scientificlinux/7.4/x86_64/os/Packages/pkgconfig-0.27.1-4.el7.x86_64.rpm
$ rpm -i pkgconfig-0.27.1-4.el7.x86_64.rpm
```

**libudev-devel (systemd-devel)**
```
# Create repo for systemd-container
$ cat >/etc/yum.repos.d/systemd.repo <<EOF
[systemdcontainer]
name=CentOS-\$releasever - systemd-container
baseurl=http://dev.centos.org/centos/7/systemd-container/
gpgcheck=1
enabled=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
EOF

$ yum -y install systemd-devel
```

Compilation successfully passed hidapi/ring-asm error. Thanks a lot.
