### ISSUE TITLE
Adding external account without having a camera on the PC running the Parity node

### ISSUE THREAD

**Issue by xorxornop** [paritytech/parity#7256]
> I'm running:
>
> - **Which Parity version?**: 1.8.3-beta-b49c44a-20171114/x86_64-windows-msvc/rustc1.20.0
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: _irrelevant_

I need to add an external account, so that I may use Parity Signer on my Android phone to sign transactions. However, I have no webcam, and therefore I cannot scan the necessary QR code.

Please add some way of achieving this - or even just let me know how I may create the necessary file (eg. the `/keys/ethereum/` folder contains files such as `UTC--2017-12-08T22-06-35Z--7b21a114-dd27-52b3-5473-XXXXXXXXXXXX` (some redacted with X's, as unknown whether this is sensitive or not...) which are JSON that describe my accounts. Unfortunately, I cannot find the specification of how such JSON should look for an external account, so I can't 'fake' having created one by constructing such a file representing the desired external account.

Is there any way that you can add the necessary functionality (not requiring a webcam on the PC which is running the Parity node) - or that I can "trick" Parity into thinking that I have created an external account?

**Comment by 5chdn** [comment]
That's not possible, unfortunately, even if you would _trick_ your Parity client into believing it knows the external account, you won't be able to sign a transaction without a webcam.
