### ISSUE TITLE
Unexpected backspace behavior in uint256 field on contract execution interface

### ISSUE THREAD

**Issue by epheph** [paritytech/parity#7257]
> I'm running:
>
> - **Which Parity version?**: 1.8.3 and 1.9 nightly
> - **Which operating system?**: Linux
> - **How installed?**: via docker
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: n/a

When executing a transaction-creating function on a custom contract with a uint256 field, the interface does something unexpected when backspacing when in "eth" mode (rightmost slider flipped right, to blue). Whenever you are deleting the first number after the period, it deletes the number _AND_ the decimal itself. For example, type:

`1.3`
then try to erase the 3 to replace with a 4. When this issue is encountered, you end up with "14" instead of 1.3.

This seems like a small issue, but I have run into several cases where I was at risk of transferring 10x the value i was expecting

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/74
