### ISSUE TITLE
Allow user to reset light client to a trusted block hash

### ISSUE THREAD

**Issue by rphmeier** [paritytech/parity#7263]
By default, the light client will attempt to download synchronize all headers from the genesis. This is a costly operation but necessary for bootstrapping trust.

If a user has some block hash that they've obtained from e.g. etherscan or some other trusted source, they should be able to bootstrap their light client from that block hash. The only downside is that data like historical logs, block bodies, etc. won't be available until the full header chain has finished downloading.

Bonus: allow this to be done over RPC

**Comment by tomaka** [comment]
cc #8075

**Comment by 5chdn** [comment]
While #8075 is the groundwork for this I would appreciate more control options for the end user here
