### ISSUE TITLE
Using multiple keyboard blocks inputs system-wide.

### ISSUE THREAD

**Issue by dushad** [paritytech/parity#7268]
I'm running:
>
> - Parity v1.8.0-beta-9882902-20171015/x86_64-windows-msvc/rustc1.20.0
> - Windows 7 x64
> - Binaries
> - Synchronized in light mode
> - Multiple times

Starting parity with this command line: parity --chain kovan --light --db-path E:\Ether
Console starts up as expected and then keyboard is blocked effectively for the entire system - it looks just like control key is stuck.
Shutting down the console doesn't help, only PC reboot helps.

**Comment by dushad** [comment]
Ok, screen keyboard shows that Ctrl+Alt+Shift is always pressed.
The issue tracks down to my multiple keyboard - I have my old PS/2 keyboard, Logitech wireless keyboard with touchpad and separate numpad USB keyboard. If I leave only one, it works fine. I guess I'll have to recompile from sources while dropping anything related to keyboard filtering.
Thanks.

**Comment by rphmeier** [comment]
Maybe something to do with hardware wallet implementation
cc @folsen @arkpar

**Comment by arkpar** [comment]
Try adding `--no-hardware-wallets`

**Comment by niklasad1** [comment]
@dushad 

Can you give us an update on this? 
Do you still have this problem on ```Parity 1.9.4```?

**Comment by 5chdn** [comment]
Or 1.10.0 :)

**Comment by dushad** [comment]
@niklasad1 

Hi, this problem still can be reproduced in 1.9.5.
I connected my numpad-only keyboard (so no Ctrl, Alt, Shift keys) - and the situation repeated, but it was slightly different, looks like Shift and Alt keys weren't blocked, only Ctrl - since i was able to use Alt+Tab and use mouse selection on desktop.

**Comment by niklasad1** [comment]
@dushad 

Ok
1. Do you still have problem when running parity without the hardware wallet? 
You can do that by running parity with the following configuration:
```
parity.exe --no-hardware-wallets
````
2. Can you run parity and provide the logs :
```
parity.exe -l hardware_wallet=trace 
```

**Comment by debris** [comment]
Closing as stale. Please reopen if it still occurs
