### ISSUE TITLE
can't recover account

### ISSUE THREAD

**Issue by PhilosopherRex** [paritytech/parity#7273]
> I'm running:
>
> - **Which Parity version?**: 1.8.4
> - **Which operating system?**:  Linux
> - **How installed?**: x64 .deb binary
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

This is likely a noobish problem, so apologies.  I've updated to 1.8.4 and when I go into the ui 127.0.0.1:8180   it immediately wants me to create a new account.  I don't want a new account, I want to get into my existing accounts .... do I have to create a new account everytime update before I can import old/existing accounts?  What am I doing wrong?

To be clear, I was able to do this in previous versions - I don't remember specifically how, but assumed it just asked me if I wanted a new account or to recover old one ... but maybe I'm wrong - just what I remember.

**Comment by PhilosopherRex** [comment]
I did find this link:  https://blog.ethcore.io/restoring-blank-seed-phrase/ 

but it is only for AFTER you are already into the accounts page - and I can't get there without creating a NEW account in the popups that come up when the ui loads.

**Comment by PhilosopherRex** [comment]
On a related note, in order to get to the area where I could actually recover my existing account, I was compelled to create a new temporary account ... unfortunately I didn't record the password as I was going to immediately delete it ... much to my chagrin however, when deleting accounts it asks for the account password ... lol ... SO ... how do I delete accounts when I have no password?

**Comment by 5chdn** [comment]
You can import your existing account manually into your keystore by copying the json file into 

    ~/.local/share/io.parity.ethereum/keys/ethereum/
