### ISSUE TITLE
Does Algorithm::OverlayRecent works in the right way?

### ISSUE THREAD

**Issue by EighteenZi** [paritytech/parity#7274]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no

I'm reading the source code of overlayrecentdb, and get confused of the usage of 'journal_under'. 
In 'journal_under', the rlp key of the journalEntry that will be stored into disk contains 'index', which is the number of JournalEntries in the vector, as the Value of journal hashmap. But the 'index' will always be '0', because it just be call once. It has the same times of usage with 'mark_canonical'. the input 'id' is always equal to journal.id. So there will be nothing really deleted.
Am I clear?  Every reply is welcome.

**Comment by rphmeier** [comment]
> But the 'index' will always be '0', because it just be call once.

`index = n` for the n'th block journaled at that height. In general there will be only one block journaled per height, but there can be reorgs and small forks that must be handled.

Note that journalled insertions and deletions are kept in a separate overlay. When marking a block in an era canonical, all of the inserted items in each candidate are removed from that overlay. The insertions and deletions of the canonical era are applied in the backing database.

**Comment by EighteenZi** [comment]
yes, the backing_overlay stores `insertions` and don't store 'deletions'.

I have another question: is to_short_key(&k)  necessery? what's the purpose of this?
Could you help me on this question?

thans a lot.
