### ISSUE TITLE
build error: latest version of parity on an out-of-the-box Fedora 27

### ISSUE THREAD

**Issue by ng0177** [paritytech/parity#7281]
Hi, in the latest version of parity on an out-of-the-box Fedora 27, cargo --build release results in this error (no prior tweaks etc.):

   Compiling ethcore-io v1.9.0 (file:///home/ng0177/parity/util/io)
error: failed to run custom build command for `snappy-sys v0.1.0 (https://github.com/paritytech/rust-snappy#858eac97)`
process didn't exit successfully: `/home/th6mas/parity/target/release/build/snappy-sys-2969a7227891cc9d/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("false")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "snappy/" "-I" "." "-std=c++11" "-DNDEBUG=1" "-Wall" "-Wextra" "-o" "/home/th6mas/parity/target/release/build/snappy-sys-19520a159c646d5e/out/snappy/snappy.o" "-c" "snappy/snappy.cc"
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("false")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "snappy/" "-I" "." "-std=c++11" "-DNDEBUG=1" "-Wall" "-Wextra" "-o" "/home/th6mas/parity/target/release/build/snappy-sys-19520a159c646d5e/out/snappy/snappy-c.o" "-c" "snappy/snappy-c.cc"
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("false")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "snappy/" "-I" "." "-std=c++11" "-DNDEBUG=1" "-Wall" "-Wextra" "-o" "/home/th6mas/parity/target/release/build/snappy-sys-19520a159c646d5e/out/snappy/snappy-sinksource.o" "-c" "snappy/snappy-sinksource.cc"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `c++` installed?

', /home/th6mas/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.54/src/lib.rs:1670:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by 5chdn** [comment]
You need gcc installed. Please check the build dependencies: https://github.com/paritytech/parity#build-dependencies

**Comment by gengxuelei** [comment]
centos6 install c++11，gcc11：
https://edwards.sdsu.edu/research/c11-on-centos-6/


Install the devo repo:
```
wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
```
Once you have installed that, do an upgrade on yum:
```
yum upgrade
```
Next, install C++11:
```
yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
```
Finally, use the software collections to **enable it in the current shell**:
```
scl enable devtoolset-2 bash
```
Check the version again:
```
# gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
When you log out, you will be using the default system version.
