### ISSUE TITLE
How to send coins to new addresses, private network.

### ISSUE THREAD

**Issue by nezzard** [paritytech/parity#7290]
Hi, i'm looking for information, how to create smart contract wich send coins to new wallets?
Or maybe,  can i execute contract without gas?

I'm trying to create app with user registration system. And when new user is registerred, contract must to send him coins.

But, for other transactions gas must be as in a main network.

Sorry, for my English :)

**Comment by 5chdn** [comment]
What you are looking for is a faucet for your chain.

You can run one, for example:

- https://github.com/transmute-industries/eth-faucet
- https://github.com/Nethereum/Nethereum.Faucet
- https://github.com/brytorres/ethereum-faucet-epay

Users can request coins from the faucet on their own. All you need to do is to keep a positive balance :)

**Comment by nezzard** [comment]
@5chdn It's not what i'm looking for. 
For example, when user registering in Akasha, he receive coins from them, it's automatically. 
I thought, if user can execute contract, so contract send him coins, but, for execute contract he need coins. 
I need to automize it, faucet bad choise

**Comment by 5chdn** [comment]
From what I understand, does Akasha implement their custom form of a faucet and preload each new user account with a balance.

**Comment by nezzard** [comment]
@5chdn i thought about it. But i ask again, is it real to execute specific contract without gas?

**Comment by 5chdn** [comment]
Not without hacking the EVM.
