### ISSUE TITLE
Newbie with "Unable to make a connection to the Parity Secure API" issue on Mac

### ISSUE THREAD

**Issue by kennygay** [paritytech/parity#7291]
> I'm running: Mac os x
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: MacOS 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: no

I have been running Parity with no issues for a couple of months. I upgraded to the latest parity recently. The update worked for at least a day but now when I open parity i get the "Unable to make a connection to the Parity Secure API" alert.

When I enter `parity signer new-token` into terminal i just get `-bash: parity: command not found`

I am a newbie so please speak in as layman terms as you can.

**Comment by 5chdn** [comment]
Just click the Parity tray icon and select "Open".

Or install the binary via homebrew:

    brew install parity

You can also try to find the binary in your application contents, but I don't have access to a mac right now and can not tell you the correct path.
