### ISSUE TITLE
"One liner install" on Linux gives 1.8.2, but latest to download is 1.8.4

### ISSUE THREAD

**Issue by OneOfMany07** [paritytech/parity#7293]
I downloaded a .deb file for x86 64 bit Linux, but then noticed the wiki had a one liner script for install.  Running it on Ubuntu 17.10 I just received version 1.8.2_amd64, but the download I have is 1.8.4.  I assume something needs to happen to update that other installation method to use the latest beta version as the wiki claims.

Steps to repro:
bash <(curl https://get.parity.io -Lk)
(then enter password for sudo when prompted)

Result:
Not latest built version available for download

Expected:
Always to have the same, recent version on both.

**Comment by debris** [comment]
@paritytech/ci can you look into it?

**Comment by ddorgan** [comment]
Is this still an issue? basically get.parity.io will given the latest beta (and it just tried to install 1.8.5). 
To use stable you need to specify the -r flag, e.g.:

bash <(curl https://get.parity.io -Lk) -r stable

Which currently tries to fetch 1.7.11 ..

**Comment by 5chdn** [comment]
This is working now, but not fixed.
