### ISSUE TITLE
Update Branding Everywhere for 1.9.0

### ISSUE THREAD

**Issue by 5chdn** [paritytech/parity#7294]
I don't want to see the old logo on any interface, installer, etc. after the 1.9.0 release. :)

This blocks #7071

**Comment by amaurymartiny** [comment]
#7370 updates all logos in the interface. I'll see next week about the installer.

**Comment by 5chdn** [comment]
thanks @amaurymartiny can you also check the installers?

**Comment by amaurymartiny** [comment]
@arkpar is taking care of it

**Comment by jacogr** [comment]
Installers are a bit of an issue - I don't know anybody apart from @arkpar that knows how these fit together. (And how test build, test)

**Comment by 5chdn** [comment]
#7469
