### ISSUE TITLE
Wallet does not remember permissions approval

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/parity#7295]
On master.

Repro:
- Go to Wallet
- Accept the `accountInfo` permission request in the orange bar
- Navigate to the Accounts tab

Expected:
The `accountInfo` permission request does not show again.

Actual:
The `accountInfo` permission request shows up again.

Notes:
In the localStorage, the permission for v1 is correct. v1 is just not reading it somehow.
Behavior works fine with other dapps.

**Comment by amaurymartiny** [comment]
Freshly built, and cannot reproduce. @jacogr Would like to see if you can reproduce. If not we can close this.

**Comment by jacogr** [comment]
Tested on 127.0.0.1:8180 with a fresh build after clearing permissions - cannot reproduce. Must have been a glitch in the matrix.
