### ISSUE TITLE
ERC20 Token Symbol shown incorrectly or missing when multiple Token Symbols that have the same first three letters are held at the same Ethereum address

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7303]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.8.4-beta
* Note: same issue occurs with Parity v1.8.3-beta
> - **Which operating system?**: MacOS
* macOS Sierra 10.12.6
> - **How installed?**: Installer
* Downloaded https://parity-downloads-mirror.parity.io/v1.8.4/x86_64-apple-darwin/parity-1.8.4-macos-installer.pkg
* Validated checksum with `shasum -a 256 parity-1.8.4-macos-installer.pkg`
* Run parity-1.8.4-macos-installer.pkg
* Updating to latest Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes
* Yes, I've restarted Parity, restarted Google Chrome, and emptied browser cache with hard reload

_Your issue description goes here below. Try to include **actual** vs. **expected behaviour** and **steps to reproduce** the issue._

**Actual Behaviour** 
The problem occurs when you have both DATAcoin [with DATA symbol](https://etherscan.io/token/0x0cf0ee63788a0849fe5297f3407f701e122cc023) tokens and Datum [with DAT symbol](https://etherscan.io/token/0x81c9151de0c8bafcd325a57e3db5a5df1cebf79c#readContract) tokens. Say for example you have "x" DATA tokens and "y" DAT tokens, then in your Wallet view (of the Accounts tab in the Parity Client) it only displays that you have "x" DAT tokens using the Datacoin icon (i.e. it **correctly** shows your DATA holdings and the DATAcoin logo, but it shows the **incorrect** ERC20 token symbol, as it should display DATA instead of DAT). 
Is this because the Parity Client clips off the last letter from the Token Symbol name (so it appears with only 3 letters, instead of 4, such that it could be confused as being a holding of another Token Symbol entirely)?
Also, it does not show anywhere in your Wallet view that you have "y" DAT, even though it shows that you do actually have "y" DAT when you go to https://etherscan.io/address/<YOUR_ETHEREUM_ADDRESS>#tokentxns.

**Expected Behaviour** 
If you have "x" DATA tokens and "y" DAT tokens, then in your Wallet view (of the Accounts tab in the Parity Client) it should display that you have:
* "x" DATA tokens (using the DATA icon)
* "y" DAT tokens (using the DAT icon)
These should correspond with the balances, token symbols, and icons shown in the Token Tracker view of your account at Etherscan https://etherscan.io/address/<YOUR_ETHEREUM_ADDRESS>#tokentxns, the [DATAcoin contract address](https://etherscan.io/token/0x0cf0ee63788a0849fe5297f3407f701e122cc023), and the [Datum contract address](https://etherscan.io/token/0x81c9151de0c8bafcd325a57e3db5a5df1cebf79c)

**Steps to Reproduce**
Send both DATA tokens and DAT tokens to the same Ethereum address and then open that Ethereum address in Parity Client v1.8.4-beta and go to the Ethereum Wallet view within the Accounts section and observe actual behaviour described above

**Comment by 5chdn** [comment]
The token registry only accepts TLA, where T stands for _three_.

So probably one of them is not registered? 

https://github.com/paritytech/parity/wiki/Token-Registry
