### ISSUE TITLE
ERC20 Tokens not appearing in Wallet view (of the Accounts tab in Parity Client)

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7304]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.8.4-beta
* Note: same issue occurs with Parity v1.8.3-beta
> - **Which operating system?**: MacOS
* macOS Sierra 10.12.6
> - **How installed?**: Installer
* Downloaded https://parity-downloads-mirror.parity.io/v1.8.4/x86_64-apple-darwin/parity-1.8.4-macos-installer.pkg
* Validated checksum with `shasum -a 256 parity-1.8.4-macos-installer.pkg`
* Run parity-1.8.4-macos-installer.pkg
* Updating to latest Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes
* Yes, I've restarted Parity, restarted Google Chrome, and emptied browser cache with hard reload

_Your issue description goes here below. Try to include **actual** vs. **expected behaviour** and **steps to reproduce** the issue._

**Actual Behaviour** 
With a holding of the following tokens in an Ethereum address, none of them appear in the Wallet view of the Parity Client for an Ethereum address, even though they are all shown with a holding when you go to https://etherscan.io/address/<YOUR_ETHEREUM_ADDRESS>#tokentxns
* [VIU symbol tokens](https://etherscan.io/token/0x519475b31653e46d20cd09f9fdcf3b12bdacb4f5)
* [JOT symbol tokens](https://etherscan.io/token/0xdb455c71c1bc2de4e80ca451184041ef32054001)
* [SET symbol tokens](https://etherscan.io/token/0xe06eda7435ba749b047380ced49121dde93334ae)
* [GZE symbol tokens](https://etherscan.io/token/0x8c65e992297d5f092a756def24f4781a280198ff)
* [COV symbol tokens](https://etherscan.io/token/0xe2fb6529ef566a080e6d23de0bd351311087d567)
* [LEIA symbol tokens](https://etherscan.io/token/0x96e2ffddd5aab73def197df5fdc4653a72976837)
* [INSP symbol tokens](https://etherscan.io/token/0x52903256dd18d85c2dc4a6c999907c9793ea61e3)
* [CAT symbol tokens](https://etherscan.io/token/0x68e14bb5a45b9681327e16e528084b9d962c1a39)

The only tokens that I know of that successfully appear are:
* ETH, COB, LRC, OMG, DOT, QSP, RDN, WRC

**Expected Behaviour** 
If your Ethereum address has a balance of any ERC20 token such as VIU, JOT, SET, GZE, COV, LEIA, INSP, or CAT, then in your Wallet view (of the Accounts tab in the Parity Client) it should display that ERC20 token Symbol, its corresponding icon, and the correct balance, which should all match details shown in the Token Tracker view of your account at Etherscan https://etherscan.io/address/<YOUR_ETHEREUM_ADDRESS>#tokentxns

**Steps to Reproduce**
Send one of the above mentioned ERC20 tokens such as VIU, JOT, SET, GZE, COV, LEIA, INSP, or CAT tokens to an Ethereum address and then open that Ethereum address in Parity Client v1.8.4-beta and go to the Ethereum Wallet view within the Accounts section and observe actual behaviour described above whereby that ERC20 token does not appear

**Comment by Neurone** [comment]
This isn't an issue, it's an intended behaviour. Parity looks up only for tokens submitted in its own [Token Registry](https://github.com/paritytech/parity/wiki/Token-Registry), it does not show all ERC20 compatible tokens an address owns.

**Comment by thaynetaylor** [comment]
Neurone - so who's responsibility is it to register tokens, the one who receives or the one who issues the token?

**Comment by ltfschoen** [comment]
I've requested GZE and COV via their respective Telegram groups to register on the Parity Token Register. GZE has informed me that they will contact their developers and then respond.
I'm surprised that they don't offer a bounty for reminding them. What's stopping anyone else from just creating a token symbol with the same three letter acronym as theirs and squatting on it, all for just 0.05 ETH. If I didn't think doing so was unethical I'd do it myself.

**Comment by Neurone** [comment]
There's no "responsability", anyone (the owner, a token holder or simply a fan of that token) can send 0.05 ETH and register a token. If there's interest to see that token apper in the Parity UI, the person with more interest in it will do the registration.

**Comment by 5chdn** [comment]
It's a decentralized application. Go ahead and register the tokens :)
