### ISSUE TITLE
Bandwidth usage of Parity extension when connected to remote server 

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#7307]
I don't have Parity installed on my (Win10) machine. I have the Chrome extension and parity is running on a VPS (Ubuntu Xenial).

The Parity Chrome Extension uses copious amounts of bandwidth when I have the SSH tunnel to the node active.

It is my impression this is the default behavior. But is there a setting in parity (node or client) which I can use to diminish the amount of bandwidth my local computer uses when connected to the node? It does so even when I don't have a Parity tab (localhost:8180) open.

**Comment by gaia** [comment]
Also opened here (https://github.com/paritytech/parity-extension/issues/110). Not sure where would be best since the issue nor the solution are in the Extension itself.

**Comment by tomusdrw** [comment]
There are ongoing efforts in Parity UI to reduce the bandwidth by using Pub/Sub. This should improve with 1.9, although please note that it's not really our main goal - we optimize for local node experience.
