### ISSUE TITLE
change token registration

### ISSUE THREAD

**Issue by dcxblockchain** [paritytech/parity#7311]
Hi,

Some time ago i registered a token, back when i didnt totally comprehentet the impact of this.... Now i want or actually need to change the token adress as the on i use then isn;t the one thats actually used in crowdsale.

- can i somehow change the registered contract address and number of decimals?
- and if not, can you then please delete the entry so i can re-register?

**Comment by dcxblockchain** [comment]
Hi,

sorry for late reply, i was in hospital unfortunatly. Correct DCX token is 0xbE8eb4c36a6f6ccB9bdB8533bE70DC5988011466

**Comment by 5chdn** [comment]
Removed DCX

Get well soon!
