### ISSUE TITLE
Clarification about some AuRa chain options

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#7313]
> I'm running:
>
> - **Which Parity version?**: 1.8.4
> - **Which operating system?**: Any
> - **How installed?**: via installer

This question is related to https://github.com/paritytech/parity/issues/6429
Could you clarify: when building a new AuRa-based network using parity v >= 1.8.4 can these chain.json options (validateScoreTransition, validateStepTransition, validateReceiptsTransition, eip155Transition) be safely omitted or they _must_ be specified in chain.json and set to `0`? In the latter case, in there a list of all hf-related parameters that need to set when starting a new network?

**Comment by phahulin** [comment]
Could someone please take a look at this?

**Comment by yrashk** [comment]
To the best of my understanding:

1. validateScoreTransition, validateStepTransition are AuRa params, validateReceiptsTransition and eip155Transition common params.
2. All of them are specified as `Option<Uint>` in the specification for JSON structures.
3. All of them WILL be set to 0 if omitted:

https://github.com/paritytech/parity/blob/master/ethcore/src/spec/spec.rs#L181-L182
https://github.com/paritytech/parity/blob/master/ethcore/src/engines/authority_round/mod.rs#L80-L81

Let me know if this helps.

**Comment by phahulin** [comment]
Great, thank you
