### ISSUE TITLE
Parity fails to build on Raspberry Pi

### ISSUE THREAD

**Issue by nicexe** [paritytech/parity#7315]
> I'm running:
>
> - **Which Parity version?**: HEAD
> - **Which operating system?**: Raspbian Linux (stretch)
> - **How installed?**: from source
> - **Are you fully synchronized?**: N/A
> - **Did you try to restart the node?**: N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I'm trying to build Parity on my Raspberry Pi (rev. 2) from source but `syntex_syntax` seems to be failing.
`cargo build --release -vv` exits with  
```
error: Could not compile `syntex_syntax`.

Caused by:
  process didn't exit successfully: `rustc --crate-name syntex_syntax /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=4a36a237506902ec -C extra-filename=-4a36a237506902ec --out-dir /home/pi/git-repos/parity/target/release/deps -L dependency=/home/pi/git-repos/parity/target/release/deps --extern unicode_xid=/home/pi/git-repos/parity/target/release/deps/libunicode_xid-897f1383fdd3f278.rlib --extern syntex_pos=/home/pi/git-repos/parity/target/release/deps/libsyntex_pos-d3e237d407e57974.rlib --extern rustc_serialize=/home/pi/git-repos/parity/target/release/deps/librustc_serialize-c674b9633186e424.rlib --extern log=/home/pi/git-repos/parity/target/release/deps/liblog-577999f09b0d3d8e.rlib --extern bitflags=/home/pi/git-repos/parity/target/release/deps/libbitflags-90e51c78559b5050.rlib --extern syntex_errors=/home/pi/git-repos/parity/target/release/deps/libsyntex_errors-88410d200fb97da4.rlib --cap-lints warn` (signal: 9, SIGKILL: kill)
```

**Comment by nicexe** [comment]
This might be more helpful to the `syntex_syntax` devs. Its all the output that I could capture before failing
[https://gist.github.com/nicexe/0920714071e196d83b951c8287954de2](https://gist.github.com/nicexe/0920714071e196d83b951c8287954de2)

**Comment by nicexe** [comment]
This might be more helpful to the `syntex_syntax` devs. Its all the output that I could capture before failing
[https://gist.github.com/nicexe/0920714071e196d83b951c8287954de2](https://gist.github.com/nicexe/0920714071e196d83b951c8287954de2)

**Comment by 5chdn** [comment]
There is no error in your log at all. It only says "killed". This usually happens if your device runs out of memory.
