### ISSUE TITLE
Top status bar icons are not aligned in latest Chrome

### ISSUE THREAD

**Issue by jacogr** [paritytech/parity#7319]
<img width="109" alt="parity 2017-12-18 15-13-21" src="https://user-images.githubusercontent.com/1424473/34110177-2a5ba628-e406-11e7-99aa-abf9b0b6f22b.png">

**Comment by jacogr** [comment]
Still an issue :(

**Comment by jacogr** [comment]
And gone again.

**Comment by amaurymartiny** [comment]
Present on :8180, but not on :3000
