### ISSUE TITLE
Use `Faster` crate to enhance number crunching

### ISSUE THREAD

**Issue by 0x7CFE** [paritytech/parity#7322]
[Faster](https://github.com/AdamNiederer/faster) is a SIMD library for humans. Faster allows convenient application of explicit SIMD to existing code. It allows you to write explicit SIMD code once and compile it for any target, regardless of architecture, SIMD capability, or age.

As stated in the project readme:

Easy, powerful, portable, absurdly fast numerical calculations. Includes static dispatch with inlining based on your platform and vector types, zero-allocation iteration, vectorized loading/storing, and support for uneven collections.

It looks something like this:

```Rust
let lots_of_3s = (&[-123.456f32; 128][..]).simd_iter()
    .simd_map(|v| { f32s::splat(9.0) * v.abs().sqrt().rsqrt().ceil().sqrt() -
                    f32s::splat(4.0) - f32s::splat(2.0) })
    .scalar_collect();
```

Which is analogous to this scalar code:

```Rust
let lots_of_3s = (&[-123.456f32; 128][..]).iter()
    .simd_map(|v| { 9.0 * v.abs().sqrt().sqrt().recip().ceil().sqrt() -
                    4.0 - 2.0 })
    .collect::<Vec<f32>>();
```

The vector size is entirely determined by the machine you’re compiling for - it attempts to use the largest vector size supported by your machine, and works on any platform or architecture (see below for details).

**Comment by rphmeier** [comment]
Is there any specific bottleneck or place you're thinking of using this for now? I can see it used in keccak computation perhaps.

**Comment by Vurich** [comment]
@rphmeier `ethash` and `tiny-keccak`

**Comment by Vurich** [comment]
So I spent a couple hours converting `ethash` to use `stdsimd` (I didn't need `faster`'s iterators and `faster` didn't include some patches to `stdsimd` that I needed included) and the results are promising:

```
 name                                                 preopt.bench ns/iter  opt.bench ns/iter  diff ns/iter  diff %  speedup 
 benchmarks::bench_light_compute_memmap               1,029,909             1,021,808                -8,101  -0.79%   x 1.01 
 benchmarks::bench_light_compute_memmap               1,028,433             1,075,134                46,701   4.54%   x 0.96 
 benchmarks::bench_light_compute_memmap               1,018,117             1,010,237                -7,880  -0.77%   x 1.01 
 benchmarks::bench_light_compute_memory               860,962               795,760                 -65,202  -7.57%   x 1.08 
 benchmarks::bench_light_compute_memory               854,024               794,254                 -59,770  -7.00%   x 1.08 
 benchmarks::bench_light_compute_memory               847,897               786,185                 -61,712  -7.28%   x 1.08 
 benchmarks::bench_light_from_file_round_trip_memmap  1,666,681             1,680,182                13,501   0.81%   x 0.99 
 benchmarks::bench_light_from_file_round_trip_memmap  1,772,209             1,688,550               -83,659  -4.72%   x 1.05 
 benchmarks::bench_light_from_file_round_trip_memmap  1,705,988             1,693,618               -12,370  -0.73%   x 1.01 
 benchmarks::bench_light_from_file_round_trip_memory  4,940,355             5,006,280                65,925   1.33%   x 0.99 
 benchmarks::bench_light_from_file_round_trip_memory  4,967,773             4,961,616                -6,157  -0.12%   x 1.00 
 benchmarks::bench_light_from_file_round_trip_memory  5,007,532             5,154,959               147,427   2.94%   x 0.97 
```

No-or-negligible slowdown on `from_file` and when using a memmap, 7-8% speedup when calculating a new cache in-memory. The code is [here](https://github.com/Vurich/parity/blob/ethash-simd/ethash/src/compute_simd.rs).

**Comment by folsen** [comment]
Closing as unspecific, if there are any particular places we can benefit from using the faster crate then open new issues.
