### ISSUE TITLE
Add UI to educate users on potential reasons for sync slowdowns

### ISSUE THREAD

**Issue by benjamincburns** [paritytech/parity#7328]
Boilerplate:
> I'm running:
>
> - **Which Parity version?**: 1.8.4-beta
> - **Which operating system?**: Linux
> - **How installed?**: Docker
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: oh god yes

Description:
As a user experiencing a slowdown during a node sync, all I know is that the current "Best Block" isn't increasing, or at least that it isn't increasing as quickly as it might've been a few minutes ago. Given the time involved for a full archive sync, having to figure out whether action is required when slowdowns occur, let alone _which_ action is required, makes the initial sync feel much more high-effort and risky than it needs to be.

Sync slowdowns could be due to any of the following (and more):
- Slow internet connection
- Slow peers
- Synchronizing [blocks which contained DoS attacks or are otherwise known to be very expensive](https://ethereum.stackexchange.com/a/9892/17829)
- Otherwise saturated disk I/O
- Not enough Cache/RAM other swapping/thrashing issues
- Other [known issues](https://github.com/paritytech/parity/issues/6280#issuecomment-334466911)

It'd save new users and Parity project members lots of time if Parity:

1. Detected when sync slowdowns are occurring
2. Indicated sync slowdown status in the UI
3. Tested for known potential problems on slow sync
4. Displayed in the UI indication of detected potential sync slowdown causes
5. Displayed in the UI whether a detected sync slowdown cause is anomalous (example: block contains known low gas price attack)
6. Bonus: exposed all of the above information via RPC
7. Bonus: collected per-block sync time statistics (on an opt-in basis, please!) and made this data openly available

**Comment by Tbaut** [comment]
Moving the project to https://github.com/parity-js/shell we will not migrate lower prio issues. Please reopen it there if you really think it's needed.
