### ISSUE TITLE
When making a transfer, no suggested accounts are shown

### ISSUE THREAD

**Issue by amaurymartiny** [paritytech/parity#7335]
If I remember correctly, when transferring to another account, a list of accounts was shown here before.

![screen shot 2017-12-19 at 2 37 38 pm](https://user-images.githubusercontent.com/1293565/34159690-664a7dac-e4ca-11e7-9f5e-f1b63c1ace2e.png)

**Comment by jacogr** [comment]
Removing `overflow: auto` here shows the cards, although they are then massive.

<img width="354" alt="parity 2017-12-19 17-59-10" src="https://user-images.githubusercontent.com/1424473/34169030-5ae41c04-e4e6-11e7-9d58-7d434239e438.png">

**Comment by jacogr** [comment]
And there is an additional general issue now with modals, e.g. this one (had to remove the `flex` as shown)

<img width="992" alt="parity 2017-12-19 18-01-16" src="https://user-images.githubusercontent.com/1424473/34169153-b99d991e-e4e6-11e7-9f41-edda0cc7cbc9.png">

**Comment by jacogr** [comment]
The last one is probably the general solution - it also shows the content in the address box, however the sizing is not correct of the scrollable area. (Rather fix the general issue as per the last imaqge and then the specific one to extend the box)

**Comment by jacogr** [comment]
Yes first flex removal plus this one seems to do the trick -

<img width="311" alt="parity 2017-12-19 18-06-32" src="https://user-images.githubusercontent.com/1424473/34169381-815f6c16-e4e7-11e7-8961-ea3c2777aa3b.png">
