### ISSUE TITLE
Transaction mark invalid

### ISSUE THREAD

**Issue by wiryonolau** [paritytech/parity#7341]
> I'm running:
>
> - **Which Parity version?**: 1.7.9
> - **Which operating system?**: Ubuntu 14.04
> - **How installed?**: DEB
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Hi, I try sending normal tx from normal address to normal address ( not smart contract ), using current smallest gas price which is 1 gwei.

On the parity log, my transaction is always mark as invalid.
Why was that ? On etherscan and ethgasprice website there is a lot of tx send with gas price equal to 1 gwei.

I check the smallest price from parity_getPriceHistogram whis smaller then 1 gwei.

Is there any specific option for parity to use small fee ?

**Comment by tomusdrw** [comment]
@wiryonolau usually this means that the transaction has been created incorrectly. Could you please run your node with `-lown_tx=trace` command line option and send us the logs?

**Comment by wiryonolau** [comment]
i only specify put from, to, gasLimit and gasPrice no other parameters.

It sometime work when I use average fee calculated from priceHistogram. 

I'll post the traced failed tx later.
