### ISSUE TITLE
Parity personal_unlockAccount doesn't work as described

### ISSUE THREAD

**Issue by dzmitro** [paritytech/parity#7342]
> I'm running:
>
> - **Which Parity version?**: 1.8.4
> - **Which operating system?**:  Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

I'm trying unlock account for send transaction as described here
https://github.com/paritytech/parity/wiki/JSONRPC-personal-module#personal_unlockaccount
by passing third parameter as integer, but getting unexpected behavior:
"error":{"code":-32602,"message":"Invalid params: invalid type: integer `300`, expected a 0x-prefixed, hex-encoded number of length 32."}

**actual**

curl --data '{"method":"personal_unlockAccount","params":["**address**","**password**",300],"id":323,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid params: invalid type: integer `300`, expected a 0x-prefixed, hex-encoded number of length 32."},"id":323}

**expected behavior**
{"jsonrpc":"2.0","result":true,"id":323}

when I send hex-encoded number - no problem.

**Comment by wiryonolau** [comment]
all integer parameters need to be in hex format.
It still integer :D

**Comment by dzmitro** [comment]
wiryonolau, yes :), I'm understand your sarcasm , but go-geth use non-hex(integer) format in json-rpc requests, and we cannot switch to parity without pain :(

**Comment by tomusdrw** [comment]
> When encoding QUANTITIES (integers, numbers): encode as hex,

https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding

We don't recommend using `personal_unlockAccount` at all. It's better to provide password for one time usage with `personal_sendTransaction(transaction, password)`. Alternatively sign transaction externally and use `eth_sendRawTransaction`.

**Comment by wiryonolau** [comment]
need to have double quote

**Comment by wiryonolau** [comment]
try adding double quote in the value

**Comment by sg552** [comment]
Still not work.  

```
{"jsonrpc":"2.0","error":{"code":-32000,"message":"Time-unlocking is only supported in --geth compatibility mode.","data":"Restart your client with --geth flag or use personal_sendTransaction instead."},"id":1}
```

I thin I have to switch my code from Geth to Parity .  ...

**Comment by wiryonolau** [comment]
the quote thing is correct, not it show different problem xD. Why don't you use personal_sendTransaction directly ?

**Comment by sg552** [comment]
thanks @wiryonolau    .  

My legacy code uses Geth interface to make transaction. it contains 2 steps: 
1. unlock the coinbase account
2. send transaction (without password) 

But I found Geth is too heavy and hard to use, and unstable, so I switched to Parity. 

OK,  I will change my code and use personal_sendTransaction method as you suggested.
