### ISSUE TITLE
IO Error, Permission denied

### ISSUE THREAD

**Issue by kantium** [paritytech/parity#7344]
Hello, 

My node was syncing on Kovan (#3956916 f8a0…2bdf) and suddenly crashed :

====================
stack backtrace:
   0:     0x55acea221d9c - backtrace::backtrace::trace::hc468106bb72538f7
   1:     0x55acea221dd2 - backtrace::capture::Backtrace::new::hcac85f526df079fd
   2:     0x55ace9831de8 - panic_hook::panic_hook::hdec4e963f0478d78
   3:     0x55acea3ce426 - std::panicking::rust_panic_with_hook at /checkout/src/libstd/panicking.rs:578
   4:     0x55acea3ce2b4 - std::panicking::begin_panic<alloc::string::String> at /checkout/src/libstd/panicking.rs:538
   5:     0x55acea3ce1b9 - std::panicking::begin_panic_fmt at /checkout/src/libstd/panicking.rs:522
   6:     0x55acea3ce14a - std::panicking::rust_begin_panic at /checkout/src/libstd/panicking.rs:498
   7:     0x55acea4078a0 - core::panicking::panic_fmt at /checkout/src/libcore/panicking.rs:71
   8:     0x55ace9b80955 - core::result::unwrap_failed::h08a8538360fd4dc9
   9:     0x55ace9c4d316 - ethcore::client::client::Client::import_verified_blocks::h0b196a73d6aa8234
  10:     0x55ace9b966a0 - <ethcore_io::service::IoChannel<Message>>::send_sync::h7eb699b77fba2615
  11:     0x55ace9d5d2f4 - ethcore::verification::queue::QueueSignal::set_sync::h5a1079d147791502
  12:     0x55ace9b2100d -
 std::sys_common::backtrace::__rust_begin_short_backtrace::he928b2a64ee940ab
  13:     0x55ace9b2345d - std::panicking::try::do_call::h23d4fbb3ac7b0c63
  14:     0x55acea3d4e0b - panic_abort::__rust_maybe_catch_panic at /checkout/src/libpanic_abort/lib.rs:38

`Thread 'Verifier #0' panicked at 'DB flush failed.: Error(Msg("IO error: /root/snap/parity/6574/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/325089.log: Permission denied"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906`

This is a bug. Please report it at:
    https://github.com/paritytech/parity/issues/new
Aborted (core dumped)`

Now when I try to launch parity again I get : 

`Client service error: Client(Database(Error(Msg("Invalid argument: You have to open all column families. Column families not opened: col7, col6, col5, col4, col0, col1, col2, col3"), State { next_error: None, backtrace: None })))`

hardware : `AWS EC2 (t2.micro)`
Parity version : `version Parity/v1.9.0-unstable-25a3c00-20171219/x86_64-linux-gnu/rustc1.22.1`
Linux version : `Linux 4.4.0-1044-aws #53-Ubuntu SMP Mon Dec 11 13:49:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Installed with : `snap install parity --edge`
Run with :  `parity --chain=kovan --no-warp  --jsonrpc-hosts=all`

SDD Usage (there is space): 
`df -h`
Filesystem      Size  Used Avail Use% Mounted on
udev            488M     0  488M   0% /dev
tmpfs           100M  4.6M   95M   5% /run
`/dev/xvda1       30G   14G   16G  48% /`
tmpfs           496M   76K  496M   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           496M     0  496M   0% /sys/fs/cgroup
/dev/loop0       22M   22M     0 100% /snap/parity/6538
/dev/loop3       84M   84M     0 100% /snap/core/3604
tmpfs           100M     0  100M   0% /run/user/0
/dev/loop4       22M   22M     0 100% /snap/parity/6574
/dev/loop1       22M   22M     0 100% /snap/parity/6608

**Comment by folsen** [comment]
For some reason you didn't have permission to write the logs to that particular file when it was trying to, and it seems because it crashed in the middle of doing that, the database then got corrupted so when you're trying to start now it can't read the database correctly.

A 30GB drive may not be enough, while syncing there can be significant write amplification due to how RocksDB works (we're working on tuning that to minimize it). Seeing an amplification of 2x what it requires is not uncommon and may be what you ran into.

Running `parity db kill` will reset your database and force a resync, but I would recommend a larger disk to see if the sync succeeds then.

**Comment by tomusdrw** [comment]
@kantium Please re-open if killing the database doesn't solve your problem.

**Comment by kantium** [comment]
Hello @folsen, sorry for the delay. I Indeed killed the DB et relaunched Parity, but it only works for 5-7 days. I redo the trick and it crash after 3-4 days and so on... I finally upgraded the HDD to 100 Go, and no more problem occurred since. It confirm the HDD problem. Thank you for your support
