### ISSUE TITLE
parity crash

### ISSUE THREAD

**Issue by SJablonska** [paritytech/parity#7349]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.4
> - **Which operating system?**: Debian Stretch
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no, it crashes
> - **Did you try to restart the node?**: yes, multiple times including delete the database

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
====================

stack backtrace:
   0:     0x564d0f5b084c - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

stack backtrace:
   0:     0x564d0f5b084c - <no info>

Thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

====================

stack backtrace:
   0:     0x55eccbe5584c - <no info>

Thread 'IO Worker #0' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', /checkout/src/libcore/option.rs:839

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by folsen** [comment]
This looks like a database corruption issue. `parity db kill` and resyncing would probably fix it, but of course has the downside of requiring resyncing. A corruption can happen for several reasons though so it's hard to pinpoint from just this information.

**Comment by tomusdrw** [comment]
@SJablonska please re-open if `db kill` doesn't solve your issue.

**Comment by 5chdn** [comment]
Duplicate of #7334
