### ISSUE TITLE
Can't list new MKR token in Token Registry

### ISSUE THREAD

**Issue by NiklasKunkel** [paritytech/parity#7351]
Apologies if this issue is filed in the wrong place, I wasn't quite sure how to get in contact with someone at Parity.

The MKR token was recently deployed to enable some new functionality. I tried to register it in the Token Registry but was met with the error "This TLA address is already registered".

Okay, so apparently you can't have two tokens with the same TLA. Fine I'll look up the old MKR token and edit its info to point to the new contract. Then I'll re-register the old contract as Old_MKR. 

Unfortunately I can't edit the previously registered MKR token because I am not the owner (nor is anyone in the MakerDAO organization). The owner seems to be:
>0x3FF047E5E803e20f5eF55eA1029aDB89618047Db

>OLD_MKR = 0xc66ea802717bfb9833400264dd12c2bceaa34a6d
>MKR = 0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2

How do we go about resolving this? Ideally I would like to be the owner for both so I can change the contracts and icon in the future.

EDIT: After further review this account seems to almost exclusively interact with the Token Registry contract. This leads me to believe the current owner of the MKR token in the Token Registry is someone working for Parity.

https://etherscan.io/address/0x3ff047e5e803e20f5ef55ea1029adb89618047db
https://etherscan.io/address/0x5f0281910af44bfb5fc7e86a404d0304b0e042f1#code

**Comment by NiklasKunkel** [comment]
It seems some 3rd party has registered the new MKR token with the MAC TLA. Please delete this TLA when the "MKR" TLA is released.

**Comment by 5chdn** [comment]
Removed MKR

**Comment by 5chdn** [comment]
Removed MAK
