### ISSUE TITLE
Problem with synchronization between nodes in PoA 

### ISSUE THREAD

**Issue by Ochir** [paritytech/parity#7354]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.10/1.8.4
> - **Which operating system?**: Ubuntu 16.04 Server
> - **How installed?**: via installer
> - **Are you fully synchronized?**:  n/a
> - **Did you try to restart the node?**:  yes

2 nodes in PoA cluster at one machine are run. Periodically after some usage, especially after heavy load, I met such error messages:

_2017-12-21 09:39:35 UTC IO Worker #1 DEBUG own_tx  Imported to Current (hash 1bf351520afa05b7102047205b59df55e997fdc074ee6448117e461c7b4d5b78)
2017-12-21 09:39:35 UTC IO Worker #1 INFO import  Imported #8268 117c…c4bd (1 txs, 2.40 Mgas, 119.65 ms, 2.77 KiB)
2017-12-21 09:39:35 UTC IO Worker #0 DEBUG sync  Connected 10:Parity/v1.7.10-stable-3931713-20171211/x86_64-linux-gnu/rustc1.22.1
2017-12-21 09:39:35 UTC IO Worker #2 DEBUG sync  Disconnected 10
2017-12-21 09:39:36 UTC IO Worker #1 DEBUG sync  Connected 35:Parity/v1.7.10-stable-3931713-20171211/x86_64-linux-gnu/rustc1.22.1
2017-12-21 09:39:36 UTC IO Worker #0 DEBUG sync  Disconnected 35
2017-12-21 09:39:37 UTC IO Worker #3 DEBUG sync  Connected 0:Parity/v1.7.10-stable-3931713-20171211/x86_64-linux-gnu/rustc1.22.1
2017-12-21 09:39:37 UTC IO Worker #3 DEBUG sync  Disconnected 0_

I already met this issue in #5739 and it looks like it is reproduced again. 
After killing DB at one of nodes, this problem dissappears for some time and then appears again.

I use following config file: 

_[parity]
mode = "active"
chain = "morden.json"
base_path = "eth"
db_path = "eth/db"
keys_path = "eth/keys"

[ui]
disable = true

[network]
port = 30303
bootnodes = [
   some nodes here
]

[rpc]
disable = false
interface = "local"
cors = "*"
hosts = ["all"]
apis = ["eth","rpc", "net"]
port = 8545

[websockets]
disable = true

[ipc]
disable = true

[dapps]
disable = true

[secretstore]
disable = true

[account]
unlock = ["0x987e0fbc516d2c1ccd9d25e67ce9e5ee318c6b82"]
password = ["pp"]

[mining]
usd_per_tx = "0"
tx_queue_size = 10240
reseal_on_txs = "none"
reseal_max_period = 31536000000
tx_queue_mem_limit = 0
engine_signer = "0x123e0fbc123d2c1ccd9d25e12ce9e5ee318c6b82"

[footprint]
cache_size = 768 # Overrides above caches with total size
scale_verifiers = true
num_verifiers = 4
tracing = "off"
pruning = "fast"
db_compaction = "ssd"

[misc]
logging = "own_tx,sync=debug"
log_file = "parity.log"_

**Comment by tomusdrw** [comment]
@Ochir what do you mean by "heavy usage"? Perhaps the synchronization thread is starved when doing a lot of DB reads over RPC. Can you please try runing with `--jsonrpc-processing-threads 4` and version 1.8?

**Comment by Ochir** [comment]
@tomusdrw I don't see the option "jsonrpc-processing-threads". Did you mean jsonrpc-threads?

**Comment by tomusdrw** [comment]
Oh, sorry. Just noticed you are on 1.7, the option was introduced in 1.8. You can try `--jsonrpc-threads` as well, but note it may change the behaviour of HTTP jsonrpc server (since 1.7 contains an experimental implementation).

**Comment by Ochir** [comment]
@tomusdrw I installed 1.8 as you asked. However, I don't see the option jsonrpc-processing-threads in documentation as well.

**Comment by Ochir** [comment]
I configured Parity with jsonrpc-threads, I will write if it helps.

**Comment by Ochir** [comment]
"jsonrpc-threads" didn't help, the same error appears.

**Comment by 5chdn** [comment]
Can you please attach the logs of both nodes with `-l sync=trace` ? Thanks
