### ISSUE TITLE
Parity account is not updated with balance

### ISSUE THREAD

**Issue by leonardok** [paritytech/parity#7360]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.8.4-beta-c74c8c1-20171211/x86_64-windows-msvc/rustc1.22.1
> - **Which operating system?**: Windows
> - **How installed?**: binaries
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

My node is not showing up my account balance. I did a test transfer and it is not showing up.
This is the account: https://etherscan.io/address/0x009fb0671906722427aA7Fb04Ba286b6B8Db991B

In my config file:
```
[parity]
base_path = ".\\data"
db_path = ".\\data\\chains"

[ui]
path = ".\\data\\signer"
```

**Comment by leonardok** [comment]
![image](https://user-images.githubusercontent.com/214789/34279537-8e3753f6-e698-11e7-9bc8-6e538dea1047.png)

**Comment by tomusdrw** [comment]
Can you pleast post a screenshot from `Status` page (click the signal indicator)

**Comment by black2714** [comment]
Same for me! It doesn't reflect the transaction I made yesterday... My address is: 0x00fCD1d33dd1506d3a22cd22bB18B85556D2A4A3 

I have a mac
Parity version: Parity//v1.8.2-beta-1b6588c-20171025/x86_64-macos/rustc1.21.0

I am new on this, what can I do? I am not a developer, I would be really grateful if you please explain it simply!

Thank you very much!

![screenshot 2017-12-23 at 19 30 07](https://user-images.githubusercontent.com/34797732/34321899-7b380458-e819-11e7-99ed-db07276dc2e1.png)

**Comment by leonardok** [comment]
There it is the screenshot. I had it run all the sync again against parity 1.7 stable with no luck.

![image](https://user-images.githubusercontent.com/214789/34343558-302d5fe6-e9bb-11e7-9e7c-b56f318e75ea.png)

**Comment by leonardok** [comment]
I am waiting for a full resync with parity 1.7 stable

**Comment by tomusdrw** [comment]
@leonardok @black2714 Please make sure you are fully synced with the chain. `Status` page should show all green.

Also try clearing your browser's cache and site data and see if this works. Please re-open if the issue persists.
