### ISSUE TITLE
no-serve-light can not take effect

### ISSUE THREAD

**Issue by zhangdongbo** [paritytech/parity#7361]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.10
> - **Which operating system?**: / Linux
> - **How installed?**: via  binaries 
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**:   yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

run parity with --no-serve-light true
error ' invalid arguments' is shown
Aftger remove  --no-serve-light true , all is ok
![image](https://user-images.githubusercontent.com/5865113/34285513-1f952d9c-e715-11e7-924c-f6e7872f0473.png)

**Comment by tomusdrw** [comment]
It's either `--no-server-light` (for 1.7+) or also `--no-server-light=true` (for 1.8+)
