### ISSUE TITLE
Thread 'IO Worker #3' panicked - no space left?

### ISSUE THREAD

**Issue by Shekelme** [paritytech/parity#7362]
_Before filing a new issue, please **provide the following information**._

I'm running:

- **Which Parity version?**: 1.8.3
- **Which operating system?**: Linux
- **How installed?**: binaries 
- **Are you fully synchronized?**: yes
- **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I found this in terminal: (https://snag.gy/bOYxls.jpg)

But there are more than 100 Gb is free on my SSD: (https://snag.gy/74rO98.jpg)

**Comment by Shekelme** [comment]
Filesystem                 Size  Used Avail Use% Mounted on
udev                       7,6G     0  7,6G   0% /dev
tmpfs                      1,6G  9,7M  1,6G   1% /run
/dev/mapper/mint--vg-root  442G  401G   19G  96% /
tmpfs                      7,7G  188K  7,7G   1% /dev/shm
tmpfs                      5,0M  4,0K  5,0M   1% /run/lock
tmpfs                      7,7G     0  7,7G   0% /sys/fs/cgroup
/dev/sda2                  473M  270M  179M  61% /boot
/dev/sda1                  511M  3,5M  508M   1% /boot/efi
cgmfs                      100K     0  100K   0% /run/cgmanager/fs
tmpfs                      1,6G   28K  1,6G   1% /run/user/1000
/home/kazna/.Private       442G  401G   19G  96% /home/kazna


If this still matters.

**Comment by 5chdn** [comment]
You have a virtual encrypted file system in ~/.Private that has only 19GiB space available.

Try running parity with `--db-path /srv/parity` this will write outside of that filesystem

**Comment by Shekelme** [comment]
No-no, now the parity is running OK. The reason was in something else I guess.
