### ISSUE TITLE
Server taken down by datacenter network security for repeated perceived port scans

### ISSUE THREAD

**Issue by oliverw** [paritytech/parity#7364]
I'm running:

 **Which Parity version?**: 1.7.10
 **Which operating system?**: Linux
 **How installed?**: DEB Package
 **Are you fully synchronized?**: yes
 **Did you try to restart the node?**: N/A

Command Line: 

`/usr/bin/parity --chain $ETH_CHAIN --base-path "/data" --mode "active" --no-ui --no-dapps --jsonrpc-interface "0.0.0.0" --jsonrpc-threads 4 --no-discovery --jsonrpc-apis "eth,net,web3,personal,parity,parity_pubsub,rpc" --ipc-path "/data/geth.ipc" --nat $ETH_NAT --author $ETH_COINBASE --cache-size 512 --logging "info" --ws-port 18545 --ws-interface all
`

A server running two instances of parity was taken down by the network security team of the datacenter hosting the server for repeated activity that appears like a port scan. Why parity does this by default on the LAN is honestly beyond me.

**Comment by tomusdrw** [comment]
@arkpar could you please take a look? `--no-discovery` and `--nat` is present in the CLI flags, what else might cause this?

**Comment by kirushik** [comment]
@oliverw I guess the "datacenter hosting" mentioned is Hetzner, am I right ;-)?
I guess we need to contact their security team sooner or later, I'm getting like 1 report per week about Parity causing the security lockdown there in my private channels -- maybe we can help them to set their IDS/IPS straight, or change our networking to be less agressive.

Please add `--allow-ips=public` flag (as specified in [Network Configuration wiki page](https://github.com/paritytech/parity/wiki/Network-Configuration#summary)) and try again.

**Comment by oliverw** [comment]
@kirushik Yes, it was hetzner 👍

**Comment by kirushik** [comment]
@oliverw please feel free to reopen this bug if `--allow-ips=public --no-discovery` won't help your case.

**Comment by 5chdn** [comment]
Duplicate of #2478
