### ISSUE TITLE
Unable to read password file. Ensure it exists and permissions are correct.

### ISSUE THREAD

**Issue by ahrcoin** [paritytech/parity#7367]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.8.4-beta-c74c8c1-20171211/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

I keep getting this same error no matter where I place the pass.txt file.  One other thing that is strange is that when I create a new account and run the parity account list function.....the accounts listed do not match my account I created.

here is my config file:

[parity]

chain = "classic"

[account]
unlock = ["0x72e.....etc"]
password = ["~/.local/share/io.parity.ethereum/pass.txt"]

[rpc]
disable = false
port = 8545
interface = "local"
cors = "null"
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

I am pretty new to this and am still learning.  Sorry if this is a dumb question.

**Comment by tomusdrw** [comment]
Config files don't support environment variables, or bash-like `~` for home directory, please use absolute path: `/home/user/.local/...`

**Comment by ahrcoin** [comment]
Thank you very much.  That is what it was.
