### ISSUE TITLE
Parity sent 2 transactions with *almost* the same input

### ISSUE THREAD

**Issue by enriquefynn** [paritytech/parity#7369]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v0.1.0-unstable-d80dd81d7-20171222
> - **Which operating system?**: MacOS
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no

Unfortunately it would be quite difficult to reproduce this behaviour, but it's really scary that it could happen (that's why it's an unstable version I guess)
I signed one transaction to an address never used before, input only one time password, 2 transactions were created with different nonces with the same inputs.
Since I put the gas price extremely low, I was able to cancel one and make the other pass. But if not, both would have passed. 

In etherscan it was said there were a 10s gap between the transactions.
Couldn't reproduce the error :-(

**Comment by tomusdrw** [comment]
@jacogr Could you please make sure that it's not possible to press `Confirm` button twice on the signer page?

**Comment by jacogr** [comment]
Confirmed. There is a breakage on current master when the actual isSending state is not pulled through into the pending item list.

**Comment by 4budab1** [comment]
Happened with me aswell, 1.9.2 Windows version, gladly that sum was low and receiver send it back
