### ISSUE TITLE
failed to run custom build command for keccak-hash v0.1.0

### ISSUE THREAD

**Issue by leejy016** [paritytech/parity#7372]
_Before filing a new issue, please **provide the following information**._

> I'm running: build error
>
> - **Which Parity version?**: 0.0.0

> - **Which operating system?**: ubuntu 16.04
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

root@q352-2643:~/parity# ~/.cargo/bin/cargo build --release

   Compiling arrayvec v0.4.4
   Compiling textwrap v0.8.0
   Compiling rustc_version v0.2.1
   Compiling aho-corasick v0.6.3
   Compiling futures-cpupool v0.1.6
   Compiling bytes v0.4.5
   Compiling vergen v0.1.1
   Compiling msdos_time v0.1.5
   Compiling transient-hashmap v0.4.0
   Compiling ethcore-devtools v1.9.0 (file:///root/parity/devtools)
   Compiling tempdir v0.3.5
   Compiling syn v0.11.11
   Compiling syntex_pos v0.58.1
   Compiling num-complex v0.1.40
   Compiling bn v0.4.4 (https://github.com/paritytech/bn#c9831a8d)
   Compiling num-bigint v0.1.40
   Compiling unicase v2.0.0
error: failed to run custom build command for `keccak-hash v0.1.0 (file:///root/parity/util/hash)`
process didn't exit successfully: `/root/parity/target/release/build/keccak-hash-dbec563582c04b95/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("...")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "..." "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/root/parity/target/release/build/keccak-hash-22cd5ab75504ec67/out/src/tinykeccak.o" "-c" "src/tinykeccak.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `...` installed?

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.0/src/lib.rs:1645:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

build error help....

**Comment by tomusdrw** [comment]
Please make sure to install all build dependencies:
https://github.com/paritytech/parity#build-dependencies

Especially `apt install build-essential`

Re-open if the issue persists after installing the deps.

**Comment by AndreiD** [comment]
having the same issue: I installed all deps. Here's the output with verbose

~~~~
 Compiling tiny-keccak v1.4.1
     Running `rustc --crate-name tiny_keccak /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tiny-keccak-1.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=e74fa962fc091614 -C extra-filename=-e74fa962fc091614 --out-dir /home/ubuntu/energyweb-client/target/release/deps -L dependency=/home/ubuntu/energyweb-client/target/release/deps --extern crunchy=/home/ubuntu/energyweb-client/target/release/deps/libcrunchy-0021ad0431652524.rlib --cap-lints allow`
error: Could not compile `tiny-keccak`.

Caused by:
  process didn't exit successfully: `rustc --crate-name tiny_keccak /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tiny-keccak-1.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=e74fa962fc091614 -C extra-filename=-e74fa962fc091614 --out-dir /home/ubuntu/energyweb-client/target/release/deps -L dependency=/home/ubuntu/energyweb-client/target/release/deps --extern crunchy=/home/ubuntu/energyweb-client/target/release/deps/libcrunchy-0021ad0431652524.rlib --cap-lints allow` (signal: 9, SIGKILL: kill)
~~~~
