### ISSUE TITLE
Core dump when out of storage space

### ISSUE THREAD

**Issue by frisnit** [paritytech/parity#7373]
I'm running:
- Parity/v1.8.4-beta-c74c8c1-20171211/x86_64-linux-gnu/rustc1.22.1
- Linux 4.4.0-1043-aws #52-Ubuntu SMP Tue Dec 5 10:49:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Installed from one line install script
- Not fully synchronised
- Didn't restart node as the storage volume was at 100%

While syncing the storage volume ran out of space and Parity quit with the following error:

```
Thread 'IO Worker #3' panicked at 'DB flush failed.: "IO error: /media/storage/io.parity.ethereum/chains/ethereum/db/635b34e12def8c0d/overlayrecent/db/1096874.log: No space left on device"', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)
```
## How to reproduce
Try to sync with inadequate disk space to store the chain

**Comment by tomusdrw** [comment]
@frisnit what would be an acceptable behaviour for you?

Parity is not able to operate when there is not enough disk space. Right now it crashes with this error message, the only difference I could think of would be to just print a different error message in case it runs out of disk space (without core dump), but it would require some significant refactorings. Feel free to submit a Pull Request for this.

**Comment by frisnit** [comment]
Thanks @tomusdrw yes I would just suggest the absence of the core dump but understand if the solution is more complicated than the problem justifies.

**Comment by 5chdn** [comment]
regarding disk space #6280
