### ISSUE TITLE
How to unregister a token?

### ISSUE THREAD

**Issue by joycoin** [paritytech/parity#7376]
Before filing a new issue, please **provide the following information**._
I'm running:
**Which operating system?**: Windows
**How installed?**: via installer
**Are you fully synchronized?**:yes
**Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

How to unregister a token from the token registry?  I too unexpectedly hit up against the 0 balance when I registered a token today. 

I was following the walk through guide on the wiki for "teh token" creation. Everything seemed to be going fine. I created and transferred the token, the parity contract view  and etherscan both seemed to have the amount of tokens I was looking for. (100,000,000) So I progressed to the registration page but the tokens registered for 0 balance. 

What are the steps to unregister?

**Comment by joycoin** [comment]
Executed the contract and found the function details. I will go with unregister and hope for the best.

**Comment by joycoin** [comment]
Transaction went through, unregister was called on he correct ID but it is still listed in the registry.

**Comment by tomusdrw** [comment]
@joycoin could you please send a link to the transaction so that we can inspect it?

**Comment by joycoin** [comment]
0xbca9253ee4e8103cb6c66172e225e48b5edaffb74fd6f0595de168c020337ded

Function: unregister(uint256 _id)

MethodID: 0xa02b161e
[0]:00000000000000000000000000000000000000000000000000000000000002eb

**Comment by tomusdrw** [comment]
@joycoin the transaction cannot have any `value` associated with it, please send the same transaction but with value `0` instead.

**Comment by joycoin** [comment]
Would a new transaction done with the same function the job? If so, the new tx would be 0x8fa5bb786e5888c4d7c662c47f61f4a0158df29625212b908b95f853fc190354
Function: unregister(uint256 _id)

MethodID: 0xa02b161e
[0]:00000000000000000000000000000000000000000000000000000000000002eb

**Comment by 5chdn** [comment]
Users can not unregister tokens. Please let me know which one and I'll do it for you.

**Comment by joycoin** [comment]
Thank you 5chdn, ideally I only wanted to update the contract portion into 0x143832e4bc4757114D4610fEf606eC0a7a3C02D0 for id 747 not unregister and attempt to start all over. The rest of the registration was correct, the owner remains the same 0x00059091346be9009287BCFe79c76a2fc666A892 it is 18 decimals and it has the desired TLA. If that cannot be done, I would rather wait for your 1.9 update so that I can control the timing and reduce any snipe opportunities during the transition. Keeping the TLA ownership is vastly more important to me than it displaying correctly. If you can make the contract update to the registry, tell me where to send the fee, I am willing to pay .1, double the registration fee, from the owner address upfront, for this very important update.

**Comment by 5chdn** [comment]
Can't find neither 747 nor 0x143832e4bc4757114D4610fEf606eC0a7a3C02D0

**Comment by joycoin** [comment]
ID is 747, not the tla. I will try to be more clear.
In contract 0x5F0281910Af44bFb5fC7e86A404d0304B0e042F1 (token registry)
there is a query called "token". In the field "_id: uint256" set it to "747" and query. You should see:
addr: 0xcBA8F31997504223aD5E46A7f9eaD57e7bf3c454 RFT
tla: rft
base: 1000000000000000000
name: Rubicon Financial Technologies
owner: 0x00059091346be9009287BCFe79c76a2fc666A892 Rubicon Financial Technologies

I would like the addr updated to match the verified Rubicon Financial Technologies token contract listed in etherscan: 
addr is: 0x143832e4bc4757114D4610fEf606eC0a7a3C02D0
creator: 0x00059091346be9009287BCFe79c76a2fc666A892
This way both parity and etherscan are showing the same token information in their token registries.

I am hoping that by updating the parity token registry to the correct token contract addr the supply would update in the parity registry to show the desired balance.
totalSupply: 100000000000000000000000000

**Comment by 5chdn** [comment]
Removed RFT

**Comment by nueverest** [comment]
Please unregister our token
Creator: 0x002cB47bf231ec986A1D6dCB5995A77bBDABBBD4
Token: 0xb9fd87c44f5046c73D60492614793872b6Ac23c1
PHT
Purple Heart Token

**Comment by 5chdn** [comment]
Note to self: Melon

**Comment by 5chdn** [comment]
Unregistered PHT

**Comment by 5chdn** [comment]
Removed MLN
