### ISSUE TITLE
"reseal_min_period" does not work!

### ISSUE THREAD

**Issue by jackieWhn** [paritytech/parity#7378]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.8
> - **Which operating system?**:  Linux(Ubuntu)
> - **How installed?**: via parity_1.7.8_amd64.deb
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**:  yes

I set up two nodes under private network by using POA. 
Every node got one validator. 
In the node config file, I set force sealing = true and reseal_min_period = 300000(5minutes). But the new block was created about 2-4 seconds without any transcation. But i want 5 minutes. pls help me to see whether something wrong with my configuration, thanks!!!

This this the chain spec
__{
    "name": "ProductPoA",
    "engine": {
        "authorityRound": {
            "params": {
                "gasLimitBoundDivisor": "0x400",
                "stepDuration": "2",
                "validators" : {
                   "safeContract": "0x0000000000000000000000000000000000000005"

               }
            }
        }
    },
    "params": {
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x2323"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x12a05f200"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x0000000000000000000000000000000000000005": { "balance": "1", "constructor" : "0x60....." },
        "0x0a4e5b8c09a49d770e6019db811028c34346cf83": { "balance": "10000000000000000000000000000000000000000" },
        "0x26106c7ecf09de39ee7bc8e7ed6eae79830f4b22": { "balance": "10000000000000000000000000000000000000000" }
    }
}__

This is the node config file

[parity]
chain = "contract-product-spec.json"
base_path = "./chainData/networks/parity0"
[network]
reserved_peers = "reservedPeers.enode"
reserved_only = true
port = 30311
[rpc]
interface ="0.0.0.0"
port = 8551
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
interface = "0.0.0.0"
port = 8547
[ui]
interface ="0.0.0.0"
port = 8191
hosts =["all"]
[account]
#unlock = ["0x26106c7ecf09de39ee7bc8e7ed6eae79830f4b22"]
password = ["node.pwds"]
[mining]
engine_signer = "0x26106c7ecf09de39ee7bc8e7ed6eae79830f4b22"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 300000
reseal_max_period = 3000000
usd_per_tx = "0"
gas_floor_target = "20000000"

**Comment by tomusdrw** [comment]
@jackieWhn Since you are running with `stepDuration: 2` and `--force-sealing` it means that authority will produce blocks every 2 seconds.
If you want a block time of 5 minutes, please run with `stepDuration: 300`, if you don't want empty blocks to be created, ditch the `--force-sealing` flag (authority will only seal new block if there is at least one pending transaction).
You can also use `--reseal-max-period` to force new empty block in case there were no transactions for given time.

Please re-open in case you have any further questions.
