### ISSUE TITLE
Not enough gas to claim EOS

### ISSUE THREAD

**Issue by nezyav** [paritytech/parity#7380]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - Parity//v1.7.10-stable-3931713-20171211/x86_64-windows-msvc/rustc1.22.1

> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: no

Hello, 2 days ago I sent ethereum to claim EOS.

I followed a guide step by step and I'm pretty sure I did it correctly. I've added EOS to my contracts and have tried to claim my tokens using the 'claim all' button to the account I used to buy them.

The transactions to claim all keep failing. Etherscan states there is not enough gas. I have tried using more gas, to the point where I now hardly have any ether left in my parity account to try and claim EOS again. 

https://etherscan.io/address/0x00745fc0c45ee80a003a615ee7ab0cfdfaee1a7b 

The above link shows the transactios. There are 7 which have failed. 

Can someone let me know if I am doing something wrong? Do I just need to use more Eth/Gas? if so, how much?

Thank you very much. I'd appreciate any answer. This driving me mad!

**Comment by tomusdrw** [comment]
@nezyav Seems that the last transaction went through correctly:
https://etherscan.io/tx/0x0c8fc5c62208523f324d72ac3dffa81f30e57891373b489a493e6d050e5dcf97

Parity should estimate the required gas automatically and inform you if the transaction is likely to fail. Also please make sure to follow EOS guideline regarding claiming carefuly, although I haven't read it I'm pretty sure they specify what parameters should be set.

Please re-open if you feel that it's still an issue.
