### ISSUE TITLE
Token Supply is unexpectedly very small

### ISSUE THREAD

**Issue by nueverest** [paritytech/parity#7382]
> I'm running:
>
> - **Which Parity version?**: 1.7.10
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

- Switched and sync'd to the Kovan Testnet.
- Opened the builtin Token Deployment App
- Entered 125 into the supply.  
- Registered the Token via the Token Registry App.

**Expected:** Since it says base 1,000,000 I expected to see **125,000,000 tokens**.

**Actual:** Instead, I see **0.000000000125 tokens** in the wallet that owns the contract.

Why is one of the most important parameters **total supply** not intuitive?
  
How do I unregister the test token?

Apparently, I need to type **125000000000000000000** into total supply so that I can have **125000000** tokens.  

Is this a correct understanding?

**Comment by tomusdrw** [comment]
The unit depends on the decimal number you set later on, most likely you have set `12`.
If you are the owner of the entry in TokenReg you can easily unregister it using the Token Registry dapp.
