### ISSUE TITLE
Another Parity Sync Question

### ISSUE THREAD

**Issue by ArranMcC** [paritytech/parity#7384]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: yes

Hi, I really need help. My Parity node is at 4,602,142 and falling further behind all the time, syncing at 0 blks/s. I've restarted the node and computer several times. I've read it's possible to speed up sync by using an argument like: parity --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 1024. But in command prompt I just get the message ' 'desktop\parity' is not recognised as an internal or external command, operable program or batch file.' Should I try this argument elsewhere, or is there another magic way to synchronise parity?

**Comment by tomusdrw** [comment]
@ArranMcC We are working on improving the sync speed in release 1.9, as a workaround for now you can try warp-syncing from scratch. Please try to:
1. Stop Parity
2. Wipe-out `%AppData%\Parity\Ethereum\chains\ethereum` directory
3. Restart Parity

Also make sure to store parity database on a fast SSD drive.
