### ISSUE TITLE
cannot unregister token

### ISSUE THREAD

**Issue by libotony** [paritytech/parity#7385]
> I'm running:
>
> - **Which Parity version?**: 1.7.8-stable
> - **Which operating system?**: MacOS
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Apologies if this issue is filed in the wrong place. We had announced through our official twitter (@vechainofficial) and medium, VeChain Token is in the process of being rebranded from VEN to VET. Hence VET will be the new name of our token, the trading symbol will remain the same.

We checked the source code of token registry smart contract, only the contract owner can do the token unregister, you can find the related info below:

TLA: VEN
Address: 0xD850942eF8811f2A866692A623011bDE52a462C1

We would greatly appreciate if you could kindly assist with VEN un-registration process, and we will proceed VET registration matter.

**Comment by davidqw** [comment]
@5chdn  @tomusdrw 
ID:390
NAME:ProToken
TLA: PRO
Address: 0x20c11E5E049CC1F13B3F27780Cc7830059d92984

Thanks for unregister our useless address, we will replace with new address below
https://etherscan.io/token/0x9041Fe5B3FDEA0f5e4afDC17e75180738D877A01

**Comment by 5chdn** [comment]
Removed PRO

**Comment by 5chdn** [comment]
Removed VEN
