### ISSUE TITLE
[wiki] Proof of Authority Chains links to aura and tendermint incorrectly

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#7386]
Towards the bottom of the page [Proof of authority chains](https://github.com/paritytech/parity/wiki/Proof-of-Authority-Chains) it contains a link to aura and tendermint and link redirects to page of `Consensus engine` which is non existent.

** Expected Behavior**
 - `Aura` redirects to https://github.com/paritytech/parity/wiki/Aura or https://github.com/paritytech/parity/wiki/Pluggable-Consensus#aura
 -  `Tendermint` redirects to https://github.com/paritytech/parity/wiki/Pluggable-Consensus#tendermint

** Actual Behavior**

 - `Aura` redirects to https://github.com/paritytech/parity/wiki/Consensus-Engines#aura
 - `Tendermint` redirects to https://github.com/paritytech/parity/wiki/Consensus-Engines#tendermint

The page `consensus engine` does not exists or was probably renamed to `Pluggable Consensus`

**Comment by tomusdrw** [comment]
Fixed, thanks!
