### ISSUE TITLE
eth_getFilterChanges don't receive logs in pending state when toBlock: 'pending'

### ISSUE THREAD

**Issue by cheeselord1** [paritytech/parity#7391]
> I'm running:
>
> - **Which Parity version?**: 1.7.10-stable
> - **Which operating system?**: Linux
> - **How installed?**: via from source
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

Steps to reproduce:

1) Pick an address
2) Open a filter in RPC eth_getFilter with specified address and toBlock: "Pending"
3) Send a 0 ETH transaction to that address. Low Gwei gives more time for step 4
4) Before the transaction occurs, call eth_getFilterChanges on the created filterId

Result: eth_getFilterChanges only displays the described transaction when it is mined into the latest block, not when the transaction is added to the pending state
Expected Behavior: Transaction should be displayed in the pending state, before it is confirmed. E.g. when transaction still has blockNumber and blockHash = "null"

Previously, I used Geth where eth_getFilterChanges displays the expected behavior. I found this old Geth issue that was opened in 2015 - I believe it addresses the issue described above. Maybe Parity has the same issue which was never addressed?
https://github.com/ethereum/go-ethereum/issues/852

**Comment by tomusdrw** [comment]
@cheeselord1 Parity is not producing pending block by default (note that light clients won't do that either). Please include `--force-sealing` flag if you require pending block.
