### ISSUE TITLE
Why empty block still be issued while Force-sealing = false?

### ISSUE THREAD

**Issue by jackieWhn** [paritytech/parity#7394]
Before filing a new issue, please provide the following information.

    I'm running:

        Which Parity version?: 1.7.8
        Which operating system?: Linux(Ubuntu)
        How installed?: via parity_1.7.8_amd64.deb
        Are you fully synchronized?: yes
        Did you try to restart the node?: yes

I set up two nodes under private network by using POA.
Every node got one validator.
In the node config file, force sealing = false by defult.
But the new empty block was still issued about 2 minutes. why? 
I think it should be no block if no any transacation. 

This this the chain spec
__{
"name": "ProductPoA",
"engine": {
"authorityRound": {
"params": {
"gasLimitBoundDivisor": "0x400",
"stepDuration": "2",
"validators" : {
"safeContract": "0x0000000000000000000000000000000000000005"

           }
        }
    }
},
"params": {
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID" : "0x2323"
},
"genesis": {
    "seal": {
        "authorityRound": {
            "step": "0x0",
            "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        }
    },
    "difficulty": "0x20000",
    "gasLimit": "0x12a05f200"
},
"accounts": {
    "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
    "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
    "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
    "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
    "0x0000000000000000000000000000000000000005": { "balance": "1", "constructor" : "0x60....." },
    "0x0a4e5b8c09a49d770e6019db811028c34346cf83": { "balance": "10000000000000000000000000000000000000000" },
    "0x26106c7ecf09de39ee7bc8e7ed6eae79830f4b22": { "balance": "10000000000000000000000000000000000000000" }
}

}__

This is the node config file

[parity]
chain = "contract-product-spec.json"
base_path = "./chainData/networks/parity0"
[network]
reserved_peers = "reservedPeers.enode"
reserved_only = true
port = 30311
[rpc]
interface ="0.0.0.0"
port = 8551
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
interface = "0.0.0.0"
port = 8547
[ui]
interface ="0.0.0.0"
port = 8191
hosts =["all"]
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x26106c7ecf09de39ee7bc8e7ed6eae79830f4b22"
usd_per_tx = "0"
gas_floor_target = "20000000"

**Comment by tomusdrw** [comment]
Please set `--reseal-max-period` to a very high value, otherwise authorities might be creating new blocks even if they are empty.
