### ISSUE TITLE
[enhancement] Don't show conversion rate for non Eth chains

### ISSUE THREAD

**Issue by Varunram** [paritytech/parity#7396]
Parity version: master at https://github.com/paritytech/parity/commit/26e4fc680c7bbe5654ba65627af5e6852f8a8235

It'd be nice to omit this line in the console output when syncing non Ethereum chains:
```
2017-12-28 12:52:35  Updated conversion rate to Ξ1 = US$699.62 (170160400 wei/gas)
```
(This is the line just below the "configured for xxx using yyy Engine" part)

**Comment by tomusdrw** [comment]
Duplicate of #6228 
Fixed in #6877

**Comment by tomusdrw** [comment]
Hmm just noticed, that you mentioned latest master. Can you please post full log including chain and version?

**Comment by Varunram** [comment]
@tomusdrw I noticed I was running parity from an outdated version (v1.8.0, which was before the commit came into place.) Running from my other directory, where master is at, it works great. Thanks and sorry!
