### ISSUE TITLE
One Bug of OverlayRecentDB??

### ISSUE THREAD

**Issue by EighteenZi** [paritytech/parity#7398]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: latest
> - **Which operating system?**:  Linux
> - **How installed?**:  from source
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Thesee days i'm reading the source code of OverlayRecentDB. 
I have an question:  Will the backing_overlay's size in memory keep in growing, bigger and bigger??
 In 'journal_under', the k-v data will be inserted into backing_overlay from transaction_overlay, and in 'mark_canonical', the method 'remove_and_purge' will reduce the backing_overlay's size, but it won't clear it, so at last it will grow bigger and bigger?

Is it a bug?

**Comment by tomusdrw** [comment]
@rphmeier ?

**Comment by rphmeier** [comment]
The `backing_overlay` is basically just a hash map. We remove elements from it, but don't ever call `shrink_to_fit` (the only way I know of to reclaim memory used in a hash map). The allocated memory can be reused for other elements.

Thus the size of the backing overlay will remain at the peak necessary during a given run of the Parity node.

One simple improvement would be to periodically (every few minutes) try to collect some garbage.
