### ISSUE TITLE
1.9.0 does not read 1.7.10-valid chain spec file and vice versa

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7399]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.0-unstable | 1.7.10 stable
> - **Which operating system?**: Linux
> - **How installed?**: via binary
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no (not applicable)

On a private blockchain running versions up to and including 1.7.10, the gasLimitBoundDivisor parameter goes under the "engine" section of the chain spec.

However as of version 1.9.0 it must move to the params section or it gives an error when starting parity from the command line:

> Spec json is invalid: missing field `gasLimitBoundDivisor` at line 38 column 2

Now if I move the gasLimitBoundDivisor line to the params section the error goes away for 1.9.0.  But in that case, the chain spec file is not usable by 1.7.10.  If I use the chain spec that does work with 1.9.0 with 1.7.10 I get this error:

> Spec json is invalid: missing field `gasLimitBoundDivisor` at line 22 column 4

**Comment by tomusdrw** [comment]
Yes, unfortunatelly you need two different spec files if you want to support both 1.7 and 1.9 nodes. The file structure has been altered in 1.9, the migration guide will be included in release notes when 1.9 is out.

**Comment by stone212** [comment]
@tomusdrw Thank you.  Is there any guess when 1.9.0 will be out?  (Or some other stable release that supports the new file structure)?

**Comment by tomusdrw** [comment]
@stone212 Sure, please PM me on Gitter.

**Comment by 5chdn** [comment]
This was changed in 1.8 already and is documented in the changelog
