### ISSUE TITLE
2FA on Parity?

### ISSUE THREAD

**Issue by ArranMcC** [paritytech/parity#7400]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3.
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: yes

I asked this on Gitter yesterday and no one replied. How do you set up 2FA for a Parity wallet? There's no option for it in Home, Settings, Signer, in the wallet under Passwords, or anywhere else. And it's not mentioned in the Parity User Guide, or anywhere online. It is possible, right?

**Comment by tomusdrw** [comment]
There is no 2FA in Parity itself. However you can use:
1. A multisig with a second account on a different machine.
2. Parity Mobile Signer https://paritytech.io/blog/announcing-parity-1-8.html - allows you to store your private key on air-gapped mobile device and sign transactions by scanning qrcodes.
