### ISSUE TITLE
trace_filter missing an internal transaction

### ISSUE THREAD

**Issue by mingfang** [paritytech/parity#7402]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.8.4-beta-c74c8c1-20171211/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Linux
> - **How installed?**: wget binaries from https://parity-downloads-mirror.parity.io/v1.8.4/x86_64-unknown-linux-gnu/parity
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

There is a transaction in block 3851974 with txnHash 0x8bead8b.. sent to address 0x851b7f3...
You can see it here https://etherscan.io/tx/0x8bead8b3681af9ce385cfe4f2ce5a114a07df0daec127a581a2263317aec5ee9
But this transaction is not returning when using the trace_filter.

**steps to reproduce** 
step 1:  call trace_filter setting the from address

```curl -s --data '{"method":"trace_filter","params":[{"fromBlock":"3851974","toBlock":"3851974","fromAddress":["0x9f7dfab2222a473284205cddf08a677726d786a0"]}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545 | jq .``` 

does return the expected response, which is

```{
      "action": {
        "callType": "call",
        "from": "0x9f7dfab2222a473284205cddf08a677726d786a0",
        "gas": "0x33a2",
        "input": "0xa9059cbb000000000000000000000000851b7f3ab81bd8df354f0d7640efcd7288553419000000000000000000000000000000000000000000000b976ef8aec5fc430000",
        "to": "0x6810e776880c02933d47db1b9fc05908e5386b96",
        "value": "0x0"
      },
      "blockHash": "0x93d3273b5df93d9d0e42036cd760b6a13916eb76fcfe7e12e25fa357bcd87969",
      "blockNumber": 3851974,
      "result": {
        "gasUsed": "0x33a1",
        "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
      },
      "subtraces": 0,
      "traceAddress": [],
      "transactionHash": "0x8bead8b3681af9ce385cfe4f2ce5a114a07df0daec127a581a2263317aec5ee9",
      "transactionPosition": 11,
      "type": "call"
    }
```

The input field says transfer(0xa9059cbb) to address 0x851b7f3ab81bd8df354f0d7640efcd7288553419.

step 2: make same trace_filter call but this time setting to address

```curl -s --data '{"method":"trace_filter","params":[{"fromBlock":"3851974","toBlock":"3851974","toAddress":["0x851b7f3ab81bd8df354f0d7640efcd7288553419"]}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545 | jq .```

I expected to see the same transaction but instead it returns 
```{
  "jsonrpc": "2.0",
  "result": [],
  "id": 1
}
```

This seems like a bug.

**Comment by tomusdrw** [comment]
Token transfer is not an internal call, it's just a change in internal contract storage mapping balances to accounts.
Since there is no internal call to `0x851b...` it's not possible to use `trace_filter` for that. You can however use `topics` to filter for `Transfer` event with that address as destination.

**Comment by gituser** [comment]
@tomusdrw 
>You can however use topics to filter for Transfer event with that address as destination.

I'm just trying to integrate tokens right now with parity and stuck with the same issue that `trace_filter` isn't showing token transaction hashes to my address. The only way is to filter with `trace_filter` to the particular token contract address, then check every transaction there if it contains any of my addresses which is kinda costy.

Can you elaborate more on the subject with examples?

Thank you.

**Comment by tomusdrw** [comment]
@gituser 
````
eth_filter({
  "fromBlock":"3851974",
  "toBlock":"3851974",
  "topics": [
     "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef", // Transfer Event
     "0x000000000000000000000000851b7f3ab81bd8df354f0d7640efcd7288553419", // from address (can be left null)
     "0x000000000000000000000000851b7f3ab81bd8df354f0d7640efcd7288553419" // to address (can be left null) 
})
```

Any contract-supporting library should provide high level api for such requests.

**Comment by gituser** [comment]
@tomusdrw thank you for your reply.

what is the best practice to accept tokens?

e.g. generate a new address for each (standard ethereum address) or make a contract and when contract receives a transaction automatically accumulate tokens on some other address ?

the problem is though with a contract how to distinguish different user payments?

thanks

**Comment by gituser** [comment]
I've checked furthermore `eth_newFilter` RPC call with `eth_getFilterLogs` it seems to work only once.

So that means that you need to set each time if you expect another transaction there?
