### ISSUE TITLE
Upgrades, release branches questions

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#7403]
A) Why are there two release branches being updated?
https://github.com/paritytech/parity/releases/tag/v1.7.11
https://github.com/paritytech/parity/releases/tag/v1.8.5

B ) Which one should I use headless on ubuntu?

C) Why does 
`bash <(curl https://get.parity.io -Lk)`
update it to 1.8.4 not 1.8.5?

**Comment by tomusdrw** [comment]
The release process looks like this:
1. We create a tag on github
2. Our CI servers produce binaries for that tag and upload them to S3 buckets
3. In the meantime we draft release notes
4. We hit the red button and publish the release everywhere.

You caught us in the middle of the process, version 1.7.11 and 1.8.5 will be released today.

**Comment by 5chdn** [comment]
> Why are there two release branches

We maintain stable (think LTS) and beta release channels.
