### ISSUE TITLE
Parity CLI options have "Default" values that are not included in "Available" values. "eth_pubsub" and "ssh" JSONRPC Modules are missing from the Configuring Parity Wiki page 

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7405]
# INFO
**Which Parity version?**: 1.8.4-beta
**Which operating system?**: MacOS
**How installed?**: homebrew
**Are you fully synchronized?**: N/A
**Did you try to restart the node?**: N/A

# **actual behaviour**

Some values shown in the list of "Default" CLI Options are not shown in the list "Available" CLI Options. Below I have highlighted the "Differences".

For the CLI's Options described at https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options:
  * API and Console Options `[rpc]`:
    * `--jsonrpc-apis` aka `apis`
      * "Available" APIs:
        ```
        "all", "safe", "web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"
        ```
      * "Default" APIS:
        ```
        "web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "secretstore"
        ```
      * **Difference:**
        ```
        `"pubsub", "parity_pubsub", "secretstore"`
        ```

  * WebSockets Server Options `[websockets]`:
    * `--ws-apis` aka `apis`
    * "Available" APIs: 
      ```
      "web3", "eth", "pubsub", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"
      ```
    * "Default" APIs:
      ```
      "web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "secretstore"
      ```
    * **Difference:**
      ```
      `parity_pubsub", "secretstore"`
      ```

Additionally, in the JSONRPC Guide at https://github.com/paritytech/parity/wiki/JSONRPC, it mentions a further possible "Available" APIs including: `"signer", "parity_accounts"`. 
It also provides links at the bottom of that JSONRPC Guide page https://github.com/paritytech/parity/wiki/JSONRPC#full-api-documentation to API documentation, such as modules for "eth_pubsub", "pubsub", "ssh". 

"eth_pubsub", "ssh" are not included in the Configuring Parity page https://github.com/paritytech/parity/wiki/Configuring-Parity

# **expected behavior**

Why is it that some values shown in the "Default" lists are not shown in the "Available" list? 

For instance, why aren't `"pubsub", "parity_pubsub", "secretstore"` included in the "Available" list for `--jsonrpc-apis` given that they are used in its "Default" list? And why aren't `parity_pubsub", "secretstore"` included in the "Available" list for `--ws-apis` given that they are used in its "Default" list?

The link to "pubsub" at the bottom of the page https://github.com/paritytech/parity/wiki/JSONRPC#full-api-documentation actually redirects the user to the "parity_pubsub" Wiki page, so I think the link should be renamed to "parity_pubsub" https://github.com/paritytech/parity/wiki/JSONRPC-Parity-Pub-Sub-module

The links to "eth_pubsub" (JSONRPC Eth Pub Sub Module) and "ssh" (JSONRPC shh Module) at the bottom of the page https://github.com/paritytech/parity/wiki/JSONRPC#full-api-documentation should be included in the Configuring Parity page https://github.com/paritytech/parity/wiki/Configuring-Parity

How do we contribute to updating the Parity Wiki?

# **steps to reproduce**

Observe the differences in the Configuring Parity section of the Parity Wiki at https://github.com/paritytech/parity/wiki/Configuring-Parity

**Comment by tomusdrw** [comment]
The list of available APIs in parity help can be updated here:
https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs#L459

We are also preparing a community-contributable version of Parity Wiki really soon, stay tuned.

**Comment by Tbaut** [comment]
For [rpc] https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs#L444 has per default
`"web3,eth,pubsub,net,parity,parity_pubsub,traces,rpc,shh,shh_pubsub"`

For [websockets] https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs#L477 has per default
`"web3,eth,pubsub,net,parity,parity_pubsub,traces,rpc,shh,shh_pubsub"`

For [ipc] https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs#L498 has per default 
`"web3,eth,pubsub,net,parity,parity_pubsub,parity_accounts,traces,rpc,shh,shh_pubsub"`

For https://github.com/paritytech/parity/blob/master/parity/rpc_apis.rs#L87 shows available
`web3, net, eth, pubsub, personal, signer, parity, parity_pubsub, parity_accounts, parity_set, traces, rpc, secretstore, shh, shh_pubsub` plus `all` and `safe`
