### ISSUE TITLE
Parity CLI options that are "required" are not included correctly in the Sample TOML config file

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7406]
# INFO
**Which Parity version?**: 1.8.4-beta
**Which operating system?**: MacOS
**How installed?**: homebrew
**Are you fully synchronized?**: N/A
**Did you try to restart the node?**: Yes

# **actual behaviour**

Some examples of where CLI options are specified as being "required" at https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options, but are not actually used the Sample TOML file at https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml are shown below. Also an example where there appears to be an opportunity to fix missing default values.

For the CLI's Options described at https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options:
  * Secret Store Options (Key Server) `[secretstore]`:
    * `--secretstore-secret` aka `secret` is shown to be a `(required, default: None).` but this option is not included in the Sample TOML config file that is provided (i.e. why does the Sample TOML config file not include `secret = "None"`)

    * `--secretstore-nodes` aka `nodes` is shown to be a `(required, default: ).` and seems to be used correctly in the Sample TOML config file that is provided (i.e. `nodes = []`). Why is it not shown as `(required, default: []).`

# **expected behavior**

Why is it that some of the options that are said to be "required" options in https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options, but are not actually included in the Sample TOML config file https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml?

Why are no errors shown when the Sample TOML config file is used to run Parity even though some "required" options are not included?

Where in the Parity codebase could we incorporate such error handling to warn the user that they are missing a "required" option in their CLI arguments or in their TOML config file?

# **steps to reproduce**

Refer to the Configuring Parity section of the Parity Wiki at https://github.com/paritytech/parity/wiki/Configuring-Parity

**Comment by tomusdrw** [comment]
Config file does not need to contain all possible Parity parameters. It's only used to override some of the Parity defaults, while leaving the rest untouched.
The parameters are applied in this order:
1. Internal Parity defaults (all parameters listed in `--help` with default values)
2. Parameters set in the config file override the defaults.
3. Paremeters set via CLI flags override the defaults and config file.

To give you an example:
1. Default value for `--chain` is `foundation`
2. I can specify `chain = "kovan"` in config file (so now when I put it to default location and run `parity` it will connect to Kovan network)
3. But run parity with `parity --chain=classic` to temporarily override that parameter and connect to Ethereum Classic chain.

Default config file in the wiki is just not fully in sync with parameters from latest master - it's there only to show all possible options.
You can use https://paritytech.github.io/parity-config-generator/ to create a config file with only the options you need (note that it might not contain everything as well, feel free to create corresponding issues).
