### ISSUE TITLE
Parity Sample TOML config file uses different Default values than those specified in CLI options

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7407]
# INFO
**Which Parity version?**: 1.8.4-beta
**Which operating system?**: MacOS
**How installed?**: homebrew
**Are you fully synchronized?**: N/A
**Did you try to restart the node?**: N/A

# **actual behaviour**

In the CLI Options for API and Console Options it specifies that for `--jsonrpc-cors` the Default value of `"None"`, but in the Sample TOML config file they use a value of "null"
```
[rpc]
cors = "null"
```

In the CLI Options for IPFS API Server Options it specifies that for `--ipfs-api-cors` the Default value of `"None"`, but in the Sample TOML config file they use a value of "null"
```
[ipfs]
cors = "null"
```

In the CLI Options for Footprint Options the Default values differ that the values that are included in the Sample TOML config file (see my comments in the config file code snippet below), however there is no explanation as to why they have not simply used the Default values from the CLI Options. Does the use of values in the Sample TOML config file that differ from the Default values shown in the CLI Options imply that the Default values in the CLI Options should be changed or vice versa?
```
[footprint]
# Note: Differs from Default of 32 in CLI Options
pruning_memory = 500
# Note: Differs from Default of 32 in CLI Options
cache_size_db = 64
# Note: Differs from Default of 40 in CLI Options
cache_size_queue = 50
```

# **expected behavior**

Since the Sample TOML config file is simple example that is critical for new users who wish to learn how to use Parity, perhaps it should map consistently to the CLI Options and use the same Default values so as to avoid confusion.  Where values used in the Sample TOML file do not use the Default values from the CLI Options, then it would be helpful to include an explanation as to why the author of the Wiki chose to provide values that deviated from the Default values, and perhaps even include a Use Case for each value that differed. 

# **steps to reproduce**

Observe the Sample TOML config file and CLI Options in the Configuring Parity section of the Parity Wiki at https://github.com/paritytech/parity/wiki/Configuring-Parity

**Comment by Tbaut** [comment]
```				ARG arg_pruning_memory: (usize) = 32usize, or |c: &Config| c.footprint.as_ref()?.pruning_memory.clone(),
			"--pruning-memory=[MB]",
			"The ideal amount of memory in megabytes to use to store recent states. As many states as possible will be kept within this limit, and at least --pruning-history states will always be kept.",

			ARG arg_cache_size_db: (u32) = 128u32, or |c: &Config| c.footprint.as_ref()?.cache_size_db.clone(),
			"--cache-size-db=[MB]",
			"Override database cache size.",

			ARG arg_cache_size_blocks: (u32) = 8u32, or |c: &Config| c.footprint.as_ref()?.cache_size_blocks.clone(),
			"--cache-size-blocks=[MB]",
			"Specify the prefered size of the blockchain cache in megabytes.",

			ARG arg_cache_size_queue: (u32) = 40u32, or |c: &Config| c.footprint.as_ref()?.cache_size_queue.clone(),
			"--cache-size-queue=[MB]",
			"Specify the maximum size of memory to use for block queue.",
```
in https://github.com/paritytech/parity/blob/master/parity/cli/mod.rs#L773

Should be 
```bash
pruning_memory = 32 #not 500
cache_size_db = 128 #not 64
cache_size_queue = 40 #not 50
```
