### ISSUE TITLE
Parity Sample TOML config file does not show how to use Import/Export, Legacy, and Internal CLI Options

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/parity#7408]
# INFO
**Which Parity version?**: 1.8.4-beta
**Which operating system?**: MacOS
**How installed?**: homebrew
**Are you fully synchronized?**: N/A
**Did you try to restart the node?**: N/A

# **actual behaviour**

The Parity CLI Options https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options show how to use "Import/Export Options", "Legacy Options", and "Internal Options" as CLI flags.

However, the Sample TOML config file https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml does not incorporate those CLI Options.

The Parity Wiki does not show a mapping between those CLI flags and how they would be used in a TOML config file.

# **expected behavior**

It would be helpful to update the Sample TOML config file to show an example of how to incorporate the default CLI flags for "Import/Export Options", "Legacy Options", and "Internal Options" 

# **steps to reproduce**

Observe the Sample TOML config file and CLI Options in the Configuring Parity section of the Parity Wiki at https://github.com/paritytech/parity/wiki/Configuring-Parity

**Comment by thorstenhirsch** [comment]
I guess one will update https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml to resolve this issue, so I add another point to this issue:

- the current default config in the wiki also enables mining

This results in the error message "Consensus signer account not found for the current chain" unless additional setup has been done. So my suggestion is to present a default config file **without** mining, which is also the default cli option I think (thus my suggestion fits well in this issue). And maybe add another config file for the miners somewhere else in the wiki.

**Comment by ltfschoen** [comment]
@thorstenhirsch Yes, great suggestion. I think we'll all be able to contribute to this soon, as I've received messages from @tomusdrw stating that Parity are are working on making the Parity Wiki pages amendable by the community!

The current [Default Config TOML](https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml) uses the Proof-of-Work (PoW) chain Homestead. It also provides the Homestead chain's corresponding [Network ID](https://ethereum.stackexchange.com/a/17101/9680) of 1. I think the Network ID was introduced into [Chain specifications](https://github.com/paritytech/parity/wiki/Chain-specification) as an outcome of implementing [EIP 155 - Simple Replay Attack Protection](https://trello.com/c/FjZGXUtR/124-replay-attack-protection-see-eip155), such that signatures of transactions made using Ethereum Nodes and Wallet Clients that support EIP 155 also include the Network ID for which the transaction is being signed, so that mining nodes are able to identify and reject transactions that are suffering a Replay Attack and being replayed onto another chain.

```
[parity]
chain = "homestead"

[network]
id = 1
```

I think the error `Consensus signer account not found for the current chain` is caused because although its configured in `[parity]` and `[network]` to use the Homestead PoW chain (i.e. for [Testnets such as Ropsten](https://trello.com/c/DivUQkhq/80-testnets)), it is also configured at the same time to use a Proof-of-Authority (PoA) chain by assigning a value to `engine_signer` in the `[mining]` section, because in the [CLI Options](https://github.com/paritytech/parity/wiki/Configuring-Parity#cli-options) it says that the `engine_signer` is relevant only to non-PoW chains, such as [Proof-of-Authority (PoA) chains](https://github.com/paritytech/parity/wiki/Proof-of-Authority-Chains) (i.e. using [Testnets such as Kovan and Rinkeby](https://trello.com/c/DivUQkhq/80-testnets), which requires [Setting up a PoA Network](https://github.com/paritytech/parity/wiki/Proof-of-Authority-Chains) with multiple "validator" nodes (authorities) and configuring [Validator Engines](https://github.com/paritytech/parity/wiki/Pluggable-Consensus#validator-engines) to achieve consensus using these authorities), where PoA chains are a modified form of Proof-of-Stake (PoS) chains](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ) (i.e. [Serenity implementing Casper PoS algorithm](https://trello.com/c/itQT5iPX/32-serenity-casper-pos-on-chain-scalability-sharding-plasma-transaction-speeds)).
```
[mining]
...
engine_signer = "0xdeadbeefcafe0000000000000000000000000001"
```

**Comment by folsen** [comment]
Closing as we now have https://github.com/paritytech/wiki/, please submit PR or issue to there.
