### ISSUE TITLE
A strange failed issue

### ISSUE THREAD

**Issue by v-gu** [paritytech/parity#7410]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
Parity/v1.8.3-beta-b49c44a-20171114/x86_64-linux-gnu/rustc1.21.0

> - **Which operating system?**: Windows / MacOS / Linux
Linux in Docker

> - **How installed?**: via installer / homebrew / binaries / from source
Docker hub: parity/parity:v1.8.3

> - **Are you fully synchronized?**: no / yes
yes

> - **Did you try to restart the node?**: no / yes
no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

A transaction was mined but failed

0x6170f594c794513fd62ddc269293cd7ca9f1048467bce866d44262e14f60cb7d

I didn't see any obvious reason, the error could be spotted from trace. Any help?

**Comment by 5chdn** [comment]
Please ask the bitmart support for help. Are you allowed to move the tokens?

**Comment by v-gu** [comment]
I'm the developer of Bitmart, this is what we spot on our node

**Comment by 5chdn** [comment]
The transaction ends with a REVERT opcode. Maybe a bug in your contract code? 

	PUSH1	36744	3	1
	PUSH1	36741	3	1
	MSTORE	36738	12	1
	PUSH1	36726	3	1
	CALLDATASIZE	36723	2	1
	LT	36721	3	1
	PUSH2	36718	3	1
	JUMPI	36715	10	1
	PUSH1	36705	3	1
	CALLDATALOAD	36702	3	1
	PUSH29	36699	3	1
	SWAP1	36696	3	1
	DIV	36693	5	1
	PUSH4	36688	3	1
	AND	36685	3	1
	DUP1	36682	3	1
	PUSH4	36679	3	1
	EQ	36676	3	1
	PUSH2	36673	3	1
	JUMPI	36670	10	1
	DUP1	36660	3	1
	PUSH4	36657	3	1
	EQ	36654	3	1
	PUSH2	36651	3	1
	JUMPI	36648	10	1
	DUP1	36638	3	1
	PUSH4	36635	3	1
	EQ	36632	3	1
	PUSH2	36629	3	1
	JUMPI	36626	10	1
	DUP1	36616	3	1
	PUSH4	36613	3	1
	EQ	36610	3	1
	PUSH2	36607	3	1
	JUMPI	36604	10	1
	DUP1	36594	3	1
	PUSH4	36591	3	1
	EQ	36588	3	1
	PUSH2	36585	3	1
	JUMPI	36582	10	1
	DUP1	36572	3	1
	PUSH4	36569	3	1
	EQ	36566	3	1
	PUSH2	36563	3	1
	JUMPI	36560	10	1
	DUP1	36550	3	1
	PUSH4	36547	3	1
	EQ	36544	3	1
	PUSH2	36541	3	1
	JUMPI	36538	10	1
	DUP1	36528	3	1
	PUSH4	36525	3	1
	EQ	36522	3	1
	PUSH2	36519	3	1
	JUMPI	36516	10	1
	DUP1	36506	3	1
	PUSH4	36503	3	1
	EQ	36500	3	1
	PUSH2	36497	3	1
	JUMPI	36494	10	1
	DUP1	36484	3	1
	PUSH4	36481	3	1
	EQ	36478	3	1
	PUSH2	36475	3	1
	JUMPI	36472	10	1
	DUP1	36462	3	1
	PUSH4	36459	3	1
	EQ	36456	3	1
	PUSH2	36453	3	1
	JUMPI	36450	10	1
	DUP1	36440	3	1
	PUSH4	36437	3	1
	EQ	36434	3	1
	PUSH2	36431	3	1
	JUMPI	36428	10	1
	JUMPDEST	36418	1	1
	CALLVALUE	36417	2	1
	ISZERO	36415	3	1
	PUSH2	36412	3	1
	JUMPI	36409	10	1
	JUMPDEST	36399	1	1
	PUSH2	36398	3	1
	PUSH1	36395	3	1
	DUP1	36392	3	1
	DUP1	36389	3	1
	CALLDATALOAD	36386	3	1
	PUSH20	36383	3	1
	AND	36380	3	1
	SWAP1	36377	3	1
	PUSH1	36374	3	1
	ADD	36371	3	1
	SWAP1	36368	3	1
	SWAP2	36365	3	1
	SWAP1	36362	3	1
	DUP1	36359	3	1
	CALLDATALOAD	36356	3	1
	SWAP1	36353	3	1
	PUSH1	36350	3	1
	ADD	36347	3	1
	SWAP1	36344	3	1
	SWAP2	36341	3	1
	SWAP1	36338	3	1
	POP	36335	2	1
	POP	36333	2	1
	PUSH2	36331	3	1
	JUMP	36328	8	1
	JUMPDEST	36320	1	1
	PUSH1	36319	3	1
	DUP3	36316	3	1
	PUSH20	36313	3	1
	AND	36310	3	1
	EQ	36307	3	1
	ISZERO	36304	3	1
	ISZERO	36301	3	1
	ISZERO	36298	3	1
	PUSH2	36295	3	1
	JUMPI	36292	10	1
	JUMPDEST	36282	1	1
	PUSH1	36281	3	1
	DUP2	36278	3	1
	GT	36275	3	1
	ISZERO	36272	3	1
	ISZERO	36269	3	1
	PUSH2	36266	3	1
	JUMPI	36263	10	1
	JUMPDEST	36253	1	1
	DUP1	36252	3	1
	PUSH1	36249	3	1
	PUSH1	36246	3	1
	CALLER	36243	2	1
	PUSH20	36241	3	1
	AND	36238	3	1
	PUSH20	36235	3	1
	AND	36232	3	1
	DUP2	36229	3	1
	MSTORE	36226	3	1
	PUSH1	36223	3	1
	ADD	36220	3	1
	SWAP1	36217	3	1
	DUP2	36214	3	1
	MSTORE	36211	3	1
	PUSH1	36208	3	1
	ADD	36205	3	1
	PUSH1	36202	3	1
	SHA3	36199	42	1
	SLOAD	36157	200	1
	LT	35957	3	1
	ISZERO	35954	3	1
	ISZERO	35951	3	1
	ISZERO	35948	3	1
	PUSH2	35945	3	1
	JUMPI	35942	10	1
	PUSH1	35932	3	1
	DUP1	35929	3	1
	REVERT	35926	0	1

**Comment by v-gu** [comment]
Found the reason, not enough token balance.

**Comment by bvandermeersch** [comment]
Can you elaborate on not enough token balance? The actual contract didnt have enough? Or the sender of the transaction? If the contract how did you resolve the issue? Just sent more ETH to the contract?
