### ISSUE TITLE
kovan parity stops progressing, must wipe node.json

### ISSUE THREAD

**Issue by Melvillian** [paritytech/parity#7413]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: version Parity/v1.7.10-stable-3931713-20171211/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Expected behavior: parity stays fully synced to the latest block

Actual behavior: parity randomly stops getting new blocks from peers, and the peer count goes to 0. Restarting does not help. We've found an intermediate solution, which is to wipe the /path/to/parity/chains/kovan/network/nodes.json file and then restart parity, recreating the nodes.json file and connecting to new peers.

**Comment by 5chdn** [comment]
This is fixed in 1.7.11 and 1.8.5 :)

Randomly flashing nodes.json is a good idea though :)

**Comment by jlopp** [comment]
@5chdn can you specify which commit fixed this issue?

**Comment by 5chdn** [comment]
Yes https://github.com/paritytech/parity/pull/7296/commits/4a9a0f6f554e49b75d0c1da44481b0b48faa915f
