### ISSUE TITLE
Problem syncing, corrupt SSD? 

### ISSUE THREAD

**Issue by Canalytic** [paritytech/parity#7414]
Am running: Parity//v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0
installed with one-line
have been synced through 3-4 previous versions until last week.

I've read through many similar issues.  Don't know if this should be grouped with #6372, #3247, or #7807
The error:
`stack backtrace:
   0:     0x55cf448c0dfc - <no info>

Thread 'IO Worker #3' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860`

At first I received: `stage 4 block verification failed for #2427723 (f9d2…28b4)
Error: Block(InvalidStateRoot(Mismatch { expected: e0833d7ce4196c9c704404f31b61346d6af4e758e7985c63e538618a3898c957, found: 2d27a3b2e4ffff9dd183cc240e58a0036d59ffd4b7a7d5b079a5d2739419390b }))`

I tried deleting the node.json file.  Didn't work then I tried db kill.  Since then I have had the DB flush failed error.

The only answer I've found is that if this problem persists it means the SSD is corrupt? The SSD is only a few months old so, I doubt this?  Though I haven't checked for corruption on the disk.

I am currently trying to sync in light mode.  Anything else could solve this issue?

**Comment by Canalytic** [comment]
I was synced until a few days ago, I found I was stuck somewhere around 4700000.  I at first thought it was similar to problem in #6371 that warp wasn't warpy anymore.

**Comment by Canalytic** [comment]
And I was sometimes getting the error from #3247.  Yet the advice was to run with --warp enabled, but from 1.8 --warp is enabled by default.

**Comment by 5chdn** [comment]
Please upgrade to 1.7.11 or 1.8.5 :)

**Comment by 5chdn** [comment]
The db issue is tracked here #7334

**Comment by Canalytic** [comment]
I've upgraded to 1.8.5 and problem still persists.  Should I move the issue to #7334 ?

**Comment by 5chdn** [comment]
Yes :)
