### ISSUE TITLE
Parity will not open from Start Menu

### ISSUE THREAD

**Issue by rr8187** [paritytech/parity#7415]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Just installed it today
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When i try to run Parity Ethereum from the start menu it won't open.  A window pops up for a second and then disappears.

Here is the output when I run parity.exe

![pairty](https://user-images.githubusercontent.com/34986092/34462967-d5d878b2-ee1c-11e7-82d6-9559326b2563.png)

**Comment by tomusdrw** [comment]
Please upgrade to 1.8.5-beta, there was an issue in CLi arguments parsing that could lead to this behaviour.

**Comment by 5chdn** [comment]
Where did you download parity from?

**Comment by rr8187** [comment]
I installed the stable version from parity.io.  But I just updated to 1.8.5 beta and that seems to have corrected the issue.
