### ISSUE TITLE
dev-chain: Couldn't connect to node http://127.0.0.1:8545/rpc/ in web-browser

### ISSUE THREAD

**Issue by klimenko** [paritytech/parity#7418]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.7.11-stable-a5ed4cf-20171228/x86_64-macos/rustc1.22.1
> - **Which operating system?**: MacOS
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I expecte: there is no error :)
What I did (by my memory):

```
brew update
brew upgrade
brew tap ethereum/ethereum
brew install geth
brew tap paritytech/paritytech
brew install parity --stable

parity --base-path ./test-net-7 --chain dev ui
```
```
 Starting Parity/v1.7.11-stable-a5ed4cf-20171228/x86_64-macos/rustc1.22.1
2018-01-01 17:14:08  Keys path ./test-net-7/keys/DevelopmentChain
2018-01-01 17:14:08  DB path ./test-net-7/chains/DevelopmentChain/db/125ccdc70e48df86
2018-01-01 17:14:08  Path to dapps ./test-net-7/dapps
2018-01-01 17:14:08  State DB configuration: fast
2018-01-01 17:14:08  Operating mode: active
2018-01-01 17:14:08  Configured for DevelopmentChain using InstantSeal engine

Open: http://127.0.0.1:8180/#/auth?token=YcA6-RgOp-MnAA-Hfqq
to authorize your browser.
Or use the generated token:
YcA6-RgOp-MnAA-Hfqq
2018-01-01 17:14:08  Public node URL: enode://1b503236bfde36a7ed826ebfce06f4ed9ddb9360d726088483e4393cf763fde6bb7b9425e76e45cc687c37c0aacfac1dac1af039de70d399b7812d296c48dafe@192.168.1.10:30303
```

In Safari i click Applications, then Parity/Web3 Console and receive (same in Chrome)
```
14:09:51.766
Error: CONNECTION ERROR: Couldn't connect to node http://127.0.0.1:8545/rpc/.
```
If i try geth there is no error:
```
$ geth attach http://localhost:8545/rpc/
Welcome to the Geth JavaScript console!

instance: Parity//v1.7.11-stable-a5ed4cf-20171228/x86_64-macos/rustc1.22.1
coinbase: 0x00a329c0648769a73afac7f9381e08fb43dbea72
at block: 1 (Mon, 01 Jan 2018 12:23:28 MSK)
 modules: eth:1.0 net:1.0 parity:1.0 parity_pubsub:1.0 pubsub:1.0 rpc:1.0 secretstore:1.0 traces:1.0 web3:1.0

>  
```
![2018-01-01 17 20 32](https://user-images.githubusercontent.com/1756215/34468357-27b0560e-ef18-11e7-967e-dc1e61c7b799.png)

**Comment by 5chdn** [comment]
Please run parity in development mode with `--force-ui` if you want to use the interface. Thanks :)

**Comment by WYANG008** [comment]
i encountered the same error. do you solve it?

**Comment by klimenko** [comment]
--force-ui didn't help me
as result I used geth as console

**Comment by Sofoca** [comment]
I can confirm that `--force-ui`  doesn't fix the problem. Happens to me on both Kovan and Ropsten chains. My current workaround is `geth attach http://localhost:8545/rpc/` which works like a charm.

**Comment by tomusdrw** [comment]
Please try with `--jsonrpc-cors all`.

**Comment by Sofoca** [comment]
@tomusdrw Works, thanks!

**Comment by AntoniosHadji** [comment]
In config.toml, I used the following to enable the 
```ini
[rpc]  
cors="127.0.01:8180" 
```
