### ISSUE TITLE
Parity won't start

### ISSUE THREAD

**Issue by simbo18** [paritytech/parity#7420]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.4

> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hello, 
         Tried to upgrade to latest version, but get this msg 
![screenshot 12](https://user-images.githubusercontent.com/29782285/34473849-931f5ef8-efc7-11e7-81d4-061adf78de61.png)
Can anyone help?

**Comment by 5chdn** [comment]
Thanks

Duplicate of #7334

**Comment by 5chdn** [comment]
And please upgrade your node to 1.7.11 or 1.8.5
