### ISSUE TITLE
A token has a wrong total supply after registration

### ISSUE THREAD

**Issue by ekouris** [paritytech/parity#7430]
Hey guys! 

> I'm running:
>
> - **Which Parity version?**: Parity//v1.8.5-beta-54bae9a-20171228/x86_64-macos/rustc1.22.1
> - **Which operating system?**: MacOS
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no 

First of all - Happy New Year! 

**actual**
I have deployed a new token ERA with a total supply of 100,000,000,000
Then I have registered the ERA into the registry and it shows up as 1,000.00 instead 
![bildschirmfoto 2018-01-03 um 02 17 04](https://user-images.githubusercontent.com/203002/34506352-3f7f42b2-f02c-11e7-854a-fcce5c35683b.png)

**expected behavior**
I had expected to have the total supply available after the registry.
Have I messed something up while registering, e.g. number of decimals? 
![bildschirmfoto 2018-01-03 um 02 16 52](https://user-images.githubusercontent.com/203002/34506355-477e6c2c-f02c-11e7-9f41-32cc9833d788.png)

Could you please help re-registering / fixing the total supply? 

Thanks!

Evgeni

**Comment by 5chdn** [comment]
Yes.

**Comment by ekouris** [comment]
Thanks a lot - just for my better understand 2 more questions
- Could you point me to a place where I can better learn about the difference between "deployed" and "registered" tokens? 
- My understanding is that I cannot send the unregistered tokens to any other accounts, nor publish contracts on these. But as soon as I register a token I could start leveraging the Ethereum network & parity tools, is this a correct understanding?

**Comment by 5chdn** [comment]
Deployed tokens - they are live on the blockchain. You can send unregistered tokens by executing the token contract directly. 

Registered tokens - they are listed in some kind of record that allows lookup. This allows the Parity wallet to interact with the tokens because it knows where to direct the transactions at.

**Comment by 5chdn** [comment]
Removed ERA.

**Comment by ekouris** [comment]
Thanks a lot!
