### ISSUE TITLE
Access to Parity

### ISSUE THREAD

**Issue by goodfake** [paritytech/parity#7431]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.6.8
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no / yes - i'm not sure what does it mean 
> - **Did you try to restart the node?**: no / yes - i'm not sure what does it mean 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi! So in June 2017 i installed my parity. After not using my computer for last 6 months i tried to access my parity but whenever i try to run it through desktop icon it shows in right corner parity icon and it dissapear after few seconds. My problem is that parity doesn't turn on like it used to and im scared that if i install newer version i will lose my saved account ( i lost my  10-12 security words ). Any solution what could i do ?

**Comment by 5chdn** [comment]
Please upgrade to 1.7.11 or 1.8.5 :)

You wont lose access to your accounts.

**Comment by Lemon-Essential** [comment]
how to reach 5chdn? my twitter is @sduncan621...need help! have my 12 word phrase and password but parity wallet dissapeared and restoring procedure does restore lost wallet when I restore with 12 word phrase and different new password :( I am nubie and do not know what my Parity version is although I deleted previous version and installed a new version with win-installer yesterday from parity.io ...the restore process will however the correct previous wallet address that I am trying to recover the contents of but the wallet itself  does not appear under the accounts section once I press the done button at the end of the restore process :(  Can I please get some help/advice?  thanx a million

**Comment by kirushik** [comment]
@Lemon-Essential I think the best you can try is to ask for help on https://gitter.im/paritytech/parity
Tbh, I'm not sure I understood anything about your problem from this report, sorry — so maybe your chances of getting reply on Gitter will increase if you'll take your time to explain your problem more precisely before posting.

**Comment by 5chdn** [comment]
@Lemon-Essential can you direct-message me on Riot or Gitter?
