### ISSUE TITLE
add support for libressl 2.5.5

### ISSUE THREAD

**Issue by spaceywolfi** [paritytech/parity#7443]
currenlty parity build fails when not having the compatible version of openssl and/or libressl
please add support for libressl 2.5.5

**Comment by 5chdn** [comment]
Please share the exact error message. The rust-openssl crate supports libressl. https://github.com/sfackler/rust-openssl/pull/538

**Comment by spaceywolfi** [comment]
```This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5.0, 2.5.1, 2.5.2, 2.5.3, and 2.5.4, but a different version of OpenSSL was
found. The build is now aborting due to this version mismatch.```

I have libressl-2.5.5_1 installed

**Comment by 5chdn** [comment]
:+1:
