### ISSUE TITLE
Parity doesn't open /// Invalid argument: you have to open all column families 

### ISSUE THREAD

**Issue by goodfake** [paritytech/parity#7445]
> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: not sure what does it mean
> - **Did you try to restart the node?**:  not sure what does it mean

Description of issue 

Hi! So in June 2017 i installed my parity ( 1.6.8 ver ). After not using my computer for last 6 months i tried to access my parity but whenever i try to run it through desktop icon it shows in right corner parity icon and it dissapear after few seconds. I got advice to upgrade my version so i did it to 1.8.5 ver ( now when i want to uninstall program it shows both 1.6.8 and 1.8.5 ).

When i run newest version through 'ptray.exe' only small icon in right corner shows for a second and dissapear

When i run newest version through 'parity' (icon ( 38.610 mb )) small black windows shows up for 0.2 second where it says:

Migrating database from version 11 to 12
Invalid argument: You have to open all column families. Column families not opened: col0, col1, col2, col3, col4, col5, col6

not sure if there is anything furrther because it was hard to capture that screen. 
![parity error](https://user-images.githubusercontent.com/35054086/34545665-51811f16-f0e6-11e7-8791-fd719b09143c.png)

( I lost my 10-12 words ), thanks for any interest in my problem!

**Comment by 5chdn** [comment]
Does this happen if you start your parity node again?

If yes, try `parity.exe db kill` - this will reset your database but it will not remove your accounts.

**Comment by goodfake** [comment]
Im not sure if by "start your parity node again " you mean i run 'parity' application ( icon which has 38.610 mb ) if so that's the case everytime. 

could you explain me how  can i  db kill of parity.exe ?  Im total newbie, thanks for your time , appreciate that

**Comment by goodfake** [comment]
Unfortunately after writing down those lines it ask me if i want to make some changes i click yes --
for very short time ( less then second ) black window shows up and immediately closes. 

I tried to run icons in C:\Program Files\Parity\Parity but both don't work 

![parity error](https://user-images.githubusercontent.com/35054086/34567351-db27f294-f159-11e7-9024-0d77351046d0.png)
