### ISSUE TITLE
Parity going in and out of sync. 

### ISSUE THREAD

**Issue by viardomc** [paritytech/parity#7446]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**: Mac OS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

My parity keeps on going in and out of sync and there is a problem finding stable number of connected peers (is this normal?). I have just sent ETH from binance to parity and while the transaction has been confirmed successful in etherscan.io it's still not reflecting in parity ETH wallet. Will this be resolved once sync becomes stable? I've tried to restart and re-install but both are still not successful in syncing parity. Last night it was around I was down by around 400,000-500,000 blocks and today I am down by around 200,000 blocks. Will this get faster? Any help would be very much appreciated!

**Comment by 5chdn** [comment]
Duplicate of #7436
