### ISSUE TITLE
Panicked at "State Root of Best Header is Always Valid".

### ISSUE THREAD

**Issue by sambgord** [paritytech/parity#7447]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: no; not sure how

Hello - 

I continue to get the following message: "Connecting to the Parity Node. If this informational message persists, please ensure that your Parity node is running and reachable on the network."
My clock is synchronized as well.
<img width="950" alt="parity screenshot" src="https://user-images.githubusercontent.com/35054073/34550155-21807af8-f0d4-11e7-85cf-1959a043cb18.PNG">

**Comment by 5chdn** [comment]
Can you locate the Parity tray Icon, right-click it, and shut down the process.

Afterwards, please start Parity again and let me know if this issue persists.

**Comment by sambgord** [comment]
I've right-clicked on the Parity try icon, but do not see an option to shut down the process.

**Comment by 5chdn** [comment]
![capture](https://user-images.githubusercontent.com/15729797/34566711-e4e924a0-f15f-11e7-80ff-d4479fa16f69.PNG)

**Comment by sambgord** [comment]
I don't have that icon showing at the bottom left of my screen.

**Comment by sambgord** [comment]
bottom right*

**Comment by sambgord** [comment]
i'm able to get the ptray icon to show at the bottom right when i double click on the ptray icon located in the folder where my downloads were sent to. however, when i try to start parity, it disappears.

**Comment by 5chdn** [comment]
Please open a command prompt by clicking "Start" > and enter "cmd", hit ENTER.

Type 

    cd "C:\Program Files\Parity\Parity\"

And

    parity.exe

And show me the output (could be an error message).

**Comment by sambgord** [comment]
Okay. I will be out for the day, but will follow those instructions when I get back to my computer later and will follow-up with you in results. Thanks!

**Comment by sambgord** [comment]
Here is the output.
<img width="320" alt="capture" src="https://user-images.githubusercontent.com/35054073/34587886-d810a888-f16f-11e7-9944-bc4eb56aa95a.PNG">

**Comment by sambgord** [comment]
I've reinstalled to save it in the location you referenced above. See my new output.
<img width="322" alt="capture" src="https://user-images.githubusercontent.com/35054073/34587975-427721b6-f170-11e7-8c32-7bac3baaf441.PNG">

**Comment by sambgord** [comment]
nevermind. i see what you're saying. sorry for the confusion. i will send a new output

**Comment by sambgord** [comment]
<img width="943" alt="capture" src="https://user-images.githubusercontent.com/35054073/34588108-edbd0694-f170-11e7-9ec0-8a0a2ac1607c.PNG">

**Comment by sambgord** [comment]
<img width="890" alt="capture" src="https://user-images.githubusercontent.com/35054073/34588133-0eda869e-f171-11e7-95c7-513ba25c2079.PNG">

**Comment by 5chdn** [comment]
Thanks for your report

**Comment by folsen** [comment]
Closing as a disk corruption issue (unreproducible).
