### ISSUE TITLE
Parity not syncing either

### ISSUE THREAD

**Issue by winsvega** [paritytech/parity#7448]
```
stack backtrace:
   0:     0x555767075a1c - <no info>

Thread 'IO Worker #3' panicked at 'DB flush failed.: "Corruption: bad entry in block"', /checkout/src/libcore/result.rs:906

```

I've tried geth and parity. nor of the clients syncing in fast mode. light client is barely working.
full sync takes insane amount of time. it seems that ethereum network is unsable at the moment.

**Comment by 5chdn** [comment]
Unfortunately, yes.
