### ISSUE TITLE
No snapshots available after ~ block 4600000

### ISSUE THREAD

**Issue by slavicd** [paritytech/parity#7458]
> I'm running:
>
> - **Which Parity version?**: 1.7.11
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

It looks like no snapshots after #520 (block ~4600000) are available for warp restore. Same happens with the current beta (1.8.4).

**Comment by 5chdn** [comment]
Yeah, we are aware of that issue. #7436
