### ISSUE TITLE
parity --help|x crashes

### ISSUE THREAD

**Issue by SjonHortensius** [paritytech/parity#7464]
> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**: Linux
> - **How installed?**: from source

This is a extremely minor issue, but parity segfaults and tells me to report this. `parity --help|x` (piping to any non-existing binary) will crash saying:

```
stack backtrace:
   0:     0x55fea5c3735c - <unknown>

Thread 'main' panicked at 'Error writing Error to stdout: Error { repr: Os { code: 32, message: "Broken pipe" } }', src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

This issue was previously reported (#4295) and marked as fixed, but it seems this is broken again.

**Comment by 5chdn** [comment]
It's a rust bug and the upstream developer decided not to fix it.

https://github.com/rust-lang/rust/issues/24821
