### ISSUE TITLE
access to account - Lost Password / 12 words 

### ISSUE THREAD

**Issue by goodfake** [paritytech/parity#7466]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no / yes - don't know what does it mean
> - **Did you try to restart the node?**: no / yes - don't know what does it mean ( i had info synchronizing )

Hi, so i had this problem that my parity didn't run properly after 6 months of not using it , i had to reset my database by parity.exe db kill but i didn't remove my accounts. I found as well my UTC keys if it matters. 

My question is if is there any solution to get access to my account/tokens without knowing password/12 secure words ? 

I know my password +- but i couldn't figure it out i tried like 100 different combinations but i feel like 1 letter somewhere is missing, thanks

**Comment by 5chdn** [comment]
> My question is if is there any solution to get access to my account/tokens without knowing password/12 secure words ?

Unfortunately, not.

> I know my password +- but i couldn't figure it out i tried like 100 different combinations but i feel like 1 letter somewhere is missing, thanks

There are commercial wallet recovery services available on the internet. If you roughly remember the password, you have good chances to get this recovered.
