### ISSUE TITLE
How to use mining in private test setup with PARITY?

### ISSUE THREAD

**Issue by aditbhrgv** [paritytech/parity#7470]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.4
> - **Which operating system?**:  Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi,

Thanks for reading my post. I have some questions:

1. How should I develop a private test network with mining enabled ? I tried using the dev chain but it doesn't perform mining. I want a network of parity nodes with 2 or more  nodes as miners competing for rewards.

2. How should I play around with gas parameters i.e setting gas price, gas limit etc. to deploy a smart contract ?

3. Can I use parity with geth ?

Thanks

**Comment by 5chdn** [comment]
A private development testnet automatically seals the blocks once transactions are broadcasted. All you need to do is running `parity --chain dev`.

If you want to connect more than 1 node to a private network, please consider setting up a proof-of-authority network. Have a look at the tutorial: https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial

You can basically use the default gas parameters.

To use Parity with Geth, you might find this article helpful: https://dev.to/5chdn/solving-the-problem-with-ethereum-cross-client-private-networks

**Comment by 5chdn** [comment]
Then you have to point a miner at your parity node: https://paritytech.github.io/wiki/Mining

Or connect a mining Geth node.

I'm not sure if I understand the 2nd question correctly. Could you expand on that?

**Comment by aditbhrgv** [comment]
For ex: If I doesn't specify enough gas price required to mine a block, the transaction should fail and should not pass through..

Like, to execute a transaction or to deploy a contract  I need some amount of gas specified by the miner for computing terms, I want to specify lower gas than that, so that My contract is not deployed successfully.. This is a negative test i want to test.. How to do it? Maybe I'm wrong conceptually, you can correct me anywhere you think :)

**Comment by aditbhrgv** [comment]
Regarding point 1, to do POW, I started  Parity as  "parity --chain dev --author <account> --stratum" 
And "ethminer -S 127.0.0.1:8008" . 

I tried to do a transaction and it got mined instantaneously because its a Dev chain and it doesnt require mining. 
How should I do mining with ethminer in a local private network. 
The document https://paritytech.github.io/wiki/Mining assumes that you start ethminer after you start parity on a public blockchain network. 

I want to do mining on a local setup instead of public setup. How to do this ?

**Comment by aditbhrgv** [comment]
Hi 

I tried to follow POA tutorial and in the same way I created same network with 3 nodes(user, node0 and node1) but instead of POA engine, I used Ethash engine for testing POW. 

I used stratum Ethminer to do mining. 

I have 2 concerns:

1 . I set "user" account in my setup as Miner which gets all the rewards. It is doing mining successfully but sometimes it takes a lot of time to mine. IS it normal ? On what factors does the speed of mining depend ? 

2. I don't understand why "user" account is credited with 5 Ether for mining. Where does this parameter comes from ? 

3. After I initiate a Send transaction from suppose USer account to Node0 account, the miner does the mining and the transaction is sucessfully completed. But thereafter, the miner account tends to receive 5 Ether continuously until Ethminer is running. Why is it so ? I don't know why the miner should get rewards once it has completed mining. 

I attach logs screenshots here. 

![partiyui](https://user-images.githubusercontent.com/19718391/34667733-9872bede-f46a-11e7-90d3-a8265d8d7d94.png)
![mining](https://user-images.githubusercontent.com/19718391/34667739-9ddd06ea-f46a-11e7-8ecd-0bb71872bbca.png)
![logs1](https://user-images.githubusercontent.com/19718391/34667745-a2bd71c2-f46a-11e7-96de-6b98281461bb.png)
![logs2](https://user-images.githubusercontent.com/19718391/34667751-a7f86250-f46a-11e7-83f6-c28a62aef835.png)

**Comment by 5chdn** [comment]
>  It is doing mining successfully but sometimes it takes a lot of time to mine. IS it normal ?

Yes PoW is bruteforcing hashes and the results are found randomly. https://en.wikipedia.org/wiki/Normal_distribution

> On what factors does the speed of mining depend ?

The difficulty formula. You can use `duration_limit` to reduce the block time target afaik.

> I don't understand why "user" account is credited with 5 Ether for mining. Where does this parameter comes from ?

The `block_reward` parameter in your chain spec.

>  I don't know why the miner should get rewards once it has completed mining.

The miner keeps mining until you shut it down.

**Comment by aditbhrgv** [comment]
But If the transaction is completed, what is miner mining ? Why it keeps on doing mining ?

**Comment by aditbhrgv** [comment]
One more ques, 

How to use multiple miners ? 
I can't provide --author <> option with multiple miner addresses..
