### ISSUE TITLE
Parity and Status Tokens/Ethereum

### ISSUE THREAD

**Issue by goodfake** [paritytech/parity#7478]
_Before filing a new issue, please **provide the following information**._

> I'm running:

**Which Parity version?**: 1.8.5> - 
**Which operating system?**: Windows  10
**How installed?**: via installer / 
> - **Are you fully synchronized?**: no / yes - I don't know what does it mean 
> - **Did you try to restart the node?**: no / yes - I don't know what does it mean 

Hi, I had lots of troubles with parity and couldn't access it but lately I found my password in 'test password' but I'm not sure if I'm logged in 

according to screen below it shows 0 eth but on link below it shows 0.002 ( I sent 0.002 yesterday )
https://etherscan.io/address/0x00d06979548aaec38430837f07dd67f0ea2a0746 

I had as well on my parity account status tokens which I don't see and not sure what happened with them - is it possible that I'm not logged in properly into my account ? How to check if I have any 'status' tokens left ? 

Thanks again for your time and help :) 

  
![parity](https://user-images.githubusercontent.com/35054086/34636396-291d7d5e-f298-11e7-8974-2d97538175fc.png)

**Comment by jimscarver** [comment]
the yeelo bars top right of your screen mean you are not synced yet. Click them to see how far behind you are.  Just leave parity running until you catch up. If it seems to not be progressing (current block does not change) exit parity (rightclick icon in tray) and restart parity

**Comment by Lemon-Essential** [comment]
how to reach 5chdn? my twitter is @sduncan621. and I have messenger so my Facebook is https://www.facebook.com/JuliusStevenDuncan  ..need help folks! I have my 12 word phrase and password but parity wallet dissapeared and restoring procedure does restore lost wallet when I restore with 12 word phrase and different new password :( I am nubie and do not know what my Parity version is although I deleted previous version and installed a new version with win-installer yesterday from parity.io ...the restore process will however the correct previous wallet address that I am trying to recover the contents of but the wallet itself  does not appear under the accounts section once I press the done button at the end of the restore process :(   ...I am 100% synced up btw... Can I please get some help/advice?  thanx a million

**Comment by kirushik** [comment]
@goodfake I'm closing this for now; if you'll still miss some of your Ether after you're fully synchronized — please write a comment here, and we'll reopen the issue.

PS. Ethereum doesn't store the account states on the blockchain, it stores the __transactions__ changing those states there. it means, when you sync, you're replaying all the historical transactions (of all accounts) one-by-one, changing the state of the accounts in your local DB. This is what "syncing" actually means for Ethereum clients. You will see zero balance on your account unless your client will reach and replay the transaction which changed it — so it's OK to see the zero balance while your sync state is yellow. If it reaches green and the balance is still empty — that would be a panicking time =). But this is highly unlikely to happen, and that would be a bug we would (and should) want to fix.
