### ISSUE TITLE
rpc interface is very slow when parity import block

### ISSUE THREAD

**Issue by bitcodernull** [paritytech/parity#7479]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.11
> - **Which operating system?**:  Linux
> - **How installed?**:  binaries
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes
parity  config params:
`pruning = "archive"
tracing = "on"
fat_db = "off"
cache_size = 2048`

Problem:
when the pairy import new block , the rpc is very slow, send_tx/gasprice  will be used about 20s~40s

**Comment by kamilk91** [comment]
if you are using HDD disk please set in config.toml 

`db_compaction = "hdd"`

**Comment by folsen** [comment]
Unfortunately this is just a matter of computation power, importing a block takes a lot of effort (especially running archive, trace & fatdb) and if your computer can't do it quickly enough then other things (like tx processing) will slow down.

I would recommend running a lighter full node to send transactions from if your archive node has a hard time keeping up.

Closing for now, but will keep in mind for future profiling work and general optimisations.
