### ISSUE TITLE
Parity refuses to finish syncing

### ISSUE THREAD

**Issue by christopher8827** [paritytech/parity#7480]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.11
> - **Which operating system?**: Windows 10
> - **How installed?**: via Windows binary
> - **Are you fully synchronized?**: no 
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Expected behaviour: Parity should finish syncing
Actual behaviour: Parity does not finish syncing despite being open for several days. It seems to be stuck on warp restore at around 80% or there would be no changes in the block number. Connected peers is usually 25/25 and Time is Synchronized. 

I also get the error when opening the Web3 console: _Error: CONNECTION ERROR: Couldn't connect to node http://127.0.0.1:8545/rpc/._

Steps taken to reproduce:
1. Open Parity in Chrome
2. Wait for sync
3. Sync never completes.

**Comment by jimscarver** [comment]
when it gets stuck restart parity. if the current block number is changing all is well.

**Comment by christopher8827** [comment]
Hey, it looks like its fully sync'd. However, there seems to be another problem. I expected the account balances to be fully updated but it doesn't seem to reflect the actual amount in the accounts in Parity.

I checked on Etherscan, and it still shows the old amount in Parity: https://etherscan.io/address/0x89C8686FdfC714500049Ab0e24f6f5cc4dd409bC

**Comment by 5chdn** [comment]
Please upgrade to 1.8.6 this should resolve your issues.
