### ISSUE TITLE
erc20 tokens no longer displayed or tradable

### ISSUE THREAD

**Issue by jimscarver** [paritytech/parity#7481]
> I'm running:
>
> - **Which Parity version?**: /v1.8.0-beta-9882902-20171015/x86_64-windows-msvc/rustc1.20.0
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**:  yes

ERC20 tokens are no longer visible in accounts or selectable in a transfer. 

The problem may coincide with an auto update to 1.8

**Comment by oftfrfbf** [comment]
I was having the same issue even after updating Parity via the upgrade button and then also after reinstalling the latest stable release. My solution came from installing the latest windows update (KB4056892) and doing a system restart. The problem resolved itself afterwards, and I could access my tokens once again.

Version: Parity//v1.7.11-stable-a5ed4cf-20171228/x86_64-windows-msvc/rustc1.22.1
OS: Windows 10
Installer: via installer
Synchronized: fully synchronized
Restart: yes

**Comment by toldenburger** [comment]
Same issue;

most tokens show up, however at least 5 different tokens are no showing up under the selected account, neither are they transferable.

Version: Parity//v1.8.6-beta-2d051e4-20180109/x86_64-macos/rustc1.22.1
OS: MacOS 10.13.2
Installer: via installer
Fully synchronized
Restart: OS & App.

**Comment by 5chdn** [comment]
@jimscarver please update to 1.8.6 - which token is not transferable? 

@toldenburger are the tokens registered in the token registry?

**Comment by jimscarver** [comment]
I upgraded with
https://parity-downloads-mirror.parity.io/v1.8.6/x86_64-pc-windows-msvc/InstallParity.exe
twice to be sure.
The browser still shows:
Parity//v1.7.11-stable-a5ed4cf-20171228/x86_64-windows-msvc/rustc1.22.1
"C:\Program Files\Ethcore\Parity\parity.exe" -v from the command line gets
the same thing.
Upgrading to 1.8.6 does not seem to be working.

I still see no tokens in accounts or addresses.  Keeping track of and
transferring tokens from accounts has been my main use of parity. Help.

**Comment by 5chdn** [comment]
Stop Parity and remove your old installation first.

**Comment by toldenburger** [comment]
All missing tokens have been registered in the registry.

**Comment by 5chdn** [comment]
Are they visible now?

**Comment by toldenburger** [comment]
Perhaps I should have worded that better.
I had already added all the tokens in the registry.
Still missing 5 different tokens...
Do you think an uninstall and reinstall might help?

**Comment by jimscarver** [comment]
If I uninstall and reinstall parity in order for the 1.8.6 upgrade to work can I retain my accounts, address book and contracts?,

**Comment by toldenburger** [comment]
Thanks for helping out. What address are you looking for? I don’t see how my ETH account address will help?

**Comment by toldenburger** [comment]
Any update on this issue? 
It is closed but the issue remains.

**Comment by 5chdn** [comment]
@toldenburger please share an address so I can look into this

I cannot investigate otherwise.

**Comment by toldenburger** [comment]
I asked previously what address you are looking for.

**Comment by jimscarver** [comment]
Suddenly my tokens showed up today. When I restarted the web browser and
all the tokens were gone again. I restarted the node and the tokens were
still gone. I did a shift-reload of the page and tokens magically
re-appeared.

**Comment by 5chdn** [comment]
@toldenburger I'm sorry, I am asking for the address that holds the tokens that are not displayed.

**Comment by nueverest** [comment]
I downgraded from 1.9.1 to 1.8.8 to attempt to see tokens again.

However, all tokens that I registered in the Parity registry on the Kovan testnet disappeared?

**Comment by 5chdn** [comment]
Please use 1.8.9
