### ISSUE TITLE
Parity crashes when attempting to start a private network

### ISSUE THREAD

**Issue by lsaether** [paritytech/parity#7482]
> I'm running:
>
> - **Which Parity version?**: 1.8.5-beta
> - **Which operating system?**: Windows / MacOS / __Linux__
> - **How installed?**: via installer / homebrew / __binaries__ / from source
> - **Are you fully synchronized?**: no / __yes___
> - **Did you try to restart the node?**: no / __yes__

I'm trying to run a private network using parity. I configured my genesis file to look like this:
```
{
    "name": "Bowery",
    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "12",
                "validators": {
                    "list": [
                        "0x50b46ac692821cf0605192e452e28c8389e138ca",
                        "0x289386c7ebb6c5bc062cfc957e124d54a9aa1609"
                    ]
                },
                "blockReward": "8080808080808080808"
            }
        }
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x0",
        "gasLimit": "0x2fefd8"
    },
    "params": {
        "networkID": "0x67",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "gasLimitBoundDivisor": "0x0"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": { "balance": "1", "builtin": { "name":   "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0x0000000000000000000000000000000000000002": { "balance": "1", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0x0000000000000000000000000000000000000003": { "balance": "1", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0x0000000000000000000000000000000000000004": { "balance": "1", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x50b46ac692821cf0605192e452e28c8389e138ca": {
            "balance": "1000000000000000000"
        },
        "0x289386c7ebb6c5bc062cfc957e124d54a9aa1609": {
            "balance": "1000000000000000000"
        }
    }
}
```

I generated these validator accounts by fist inputting null addresses and running `parity --chain bowery_gen.json account new`. `bower_gen.json` is the relative path to the json file I pasted above. When starting the parity node with the command `parity --chain bower_gen.json` I receive the following message: 

```

stack backtrace:
   0:     0x560a2676ba1c - <no info>
Thread 'IO Worker #3' panicked at 'assertion failed: your_bits != 0', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bigint-4.2.0/src/uint.rs:1227
This is a bug. Please report it at:
    https://github.com/paritytech/parity/issues/new
[1]    581 abort (core dumped)  parity --chain bowery_gen.json

```

I was following the documentation [here](https://paritytech.github.io/wiki/Chain-specification). The docs were a bit sparse so I may be doing something wrong here. Any guidance is appreciated!

**Comment by lsaether** [comment]
Immediately after submitting this issue I had a hunch the problem was with the`gasLimitBoundDivisor` paramter being set to "0x0". Changing this variable to "0x1" solves the crash and starts the node. However, I did not find this parameter on the documentation page and only added it in when creating the accounts asked for it. I'm confused about what this parameter actually is and I believe it needs to be documented.

**Comment by asymmetric** [comment]
From the [source](
https://github.com/asymmetric/parity/tree/bc8216a82c7a5db80710bb6863d6be7af7e26151/ethcore/src/spec/spec.rs#L114):

> Gas limit bound divisor (how much gas limit can change per block)

**Comment by 5chdn** [comment]
We should at least check if the divisor is 0x0.

**Comment by asymmetric** [comment]
Yeah, but I think it could make sense to centralize this sort of check in one place, rather than having it spread over the codebase. Or do you think we should just fix this one bug for now?

**Comment by 5chdn** [comment]
No need to check it all over the codebase, it should be sufficient to check this while loading the chain spec and produce a useful error message.
