### ISSUE TITLE
Stratum Option

### ISSUE THREAD

**Issue by ahrcoin** [paritytech/parity#7484]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:  version1.8.4-beta-c74c8c1-20171211/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**:  Linux
> - **How installed?**: via installer / homebrew
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: n/a

Background
I am running a pool for Musicoin with stratum mining enabled.  I have yet to receive any blocks and its been around a week.

My config.toml is set up to unlock my address and some other options enabled.

I just noticed that there is a -stratum option in the configuration......if I did not have this enabled under [mining] category as "true", would that prevent my mining pool from obtaining a block?  Or is this required to obtain blocks with miners using stratum mining.

Is this the correct method for the true/false options in config.toml:
"stratum = true" 

or should it be "stratum = "true""

Thank you

**Comment by 5chdn** [comment]
Hi. Stratum is a mining protocol.

Have a look at our wiki. https://paritytech.github.io/wiki/Mining

You can mine with stratum enabled or disabled, depending on whatever works best for you.

I would strongly advise against unlocking your account. Why are you doing this?
