### ISSUE TITLE
Security issues:  Please implement feature of using Parity client together with google 2fa authenticator

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#7487]
Please implement feature of using Parity client together with google 2fa authenticator.

Is this possible/meaningful?
Thanks

**Comment by 5chdn** [comment]
You can use the Parity mobile signer for iOS and Android if you want an airgapped solution.

https://play.google.com/store/apps/details?id=com.nativesigner&hl=en

https://itunes.apple.com/us/app/parity-signer/id1218174838?mt=8

**Comment by zumbatan** [comment]
@5chdn -thx. But this app is last updated in July 2017 and not released officially on the playstore. When do you plan for first stable release?  

And why is this app requiring so much unecessary but highly sensitive permissions-like phone device ID???  who are the responsible devs---please consider to elimiate any unecessary permission. appreciated

**Comment by 5chdn** [comment]
This is the source code, https://github.com/paritytech/parity-signer

@debris is the responsible developer :)

**Comment by debris** [comment]
> And why is this app requiring so much unecessary but highly sensitive permissions-like phone device ID??? who are the responsible devs---please consider to eliminate any unecessary permission. appreciated-

@zumbatan I guess these are react-native defaults... I've created issues in mobile app repo
