### ISSUE TITLE
stack backtrace

### ISSUE THREAD

**Issue by Orecic** [paritytech/parity#7490]
stack backtrace:

Thread 'IO Worker #2' panicked at 'DB flush failed.: "IO error: /Users/mingbingchen/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/847634.log: Too many open files in system"', src/libcore/result.rs:906

**Comment by debris** [comment]
which version of parity are you using? We've recently made many modifications to the database to improve it's performance and it's important to us to know if this issue is relevant
