### ISSUE TITLE
Parity didn't sync and now will not open after attempted update.

### ISSUE THREAD

**Issue by SonicJaxx** [paritytech/parity#7491]
> I'm running:
>
> - **Which Parity version?**: 1.8.0
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: no

Thread 'IO Worker #2' panicked at 'DB flush failed.: "IO error: Failed to WriteF
ile: C:\\Users\\Rob\\AppData\\Local\\Parity\\Ethereum\\chains\\ethereum\\db\\906
a34e69aec8c0d\\overlayrecent\\db/024445.sst: There is not enough space on the di
sk.\r\n"', src\libcore\result.rs:860

This is a bug. Please report it at (here)

1. Basically what happened was I had some ETH sent to my parity wallet yesterday but it did not register. 
2. I checked Etherscan and it was at my address. I searched online and found that I needed to synchronise my parity for it to show. 
3. I didn't fully understand what this meant so I clicked to update my parity in the parity browser. Nothing seemed to happen, after a while I restarted my computer and now Parity wouldn't open at all.
4. I searched for a solution online and found https://github.com/paritytech/parity/issues/6042 way of launching Parity
5. I launched Parity in the Command Prompt and it seemed as if it was updating itself. But if failed. 
6. Now I am here, I am not great with technology. I appreciate any and all help I recieve.

**Comment by drew683** [comment]
same. update failed. restarting current parity version results in the webpage showing "loading" although nothing appears to be happening.

**Comment by kirushik** [comment]
@SonicJaxx can you please provide a screenshot of your Command Prompt with parity failing to start? Without an error message displayed there we won't be able to pinpoint and fix the issue.

**Comment by kirushik** [comment]
@drew683 Looks like your issue is a separate one, if you can see a web interface your node should be running since it serves at least Web UI files. Can you please open a separate issue here, providing more details of the bug there?

**Comment by 5chdn** [comment]
1.8.6 addresses your sync issues.

You might need to reset your database though.
