### ISSUE TITLE
current master does not build on windows

### ISSUE THREAD

**Issue by Trolldemorted** [paritytech/parity#7502]
> I'm running:
>
> - **Which Parity version?**: bdc3d6fee049111e54802cc132488270e2458036
> - **Which operating system?**: W10 Pro N 64bit
> - **Which rustc version?**: rustc 1.21.0 (3b72af97e 2017-10-09)

I just cloned the repo, executed cargo build --release and the linker fails because it cannot find the symbol `rocksdb_options_set_disable_data_sync`.

**Comment by 5chdn** [comment]
Ouch. On it.

**Comment by Trolldemorted** [comment]
While we are at it: you might want to setup continuous ingetration builds for all platforms - e.g. appveyor should be free for opensource projects.

**Comment by 5chdn** [comment]
We are using gitlab and it's running builds for all platforms.

https://gitlab.parity.io/parity/parity/pipelines/17021

**Comment by 5chdn** [comment]
https://github.com/paritytech/rust-rocksdb/pull/13

**Comment by 5chdn** [comment]
https://github.com/spacejam/rust-rocksdb/pull/139

**Comment by 5chdn** [comment]
confirmed working. can be closed once this is forward-ported to staging and master.
