### ISSUE TITLE
Parity's browser UI on localhost should have a distinct name

### ISSUE THREAD

**Issue by kirushik** [paritytech/parity#7505]
Currently it's hard to distinguish a logo+title of local Parity instance from a logo+title of a main Parity website in browser's quicklaunch and bookmarks menus — and that can be easily improved by changins the title.

Maybe "Your local Parity browser" will do?

**Comment by jacogr** [comment]
Need to see how we launch the UI in 1.10

**Comment by Tbaut** [comment]
Problem solved with Parity UI :tada:
