### ISSUE TITLE
(feature request) clickable transaction hash, or don't abbreviate

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#7513]
This is for your GUI guys.

I'm running: Parity/v1.7.12-stable-f96d152-20180109 installed via *.deb file

The wallet GUI is great, I like it.   
But as the Ethereum network now seems almost as broken as the Bitcoin network, 
waiting for transaction confirmations, and waiting for a tx to enter the mempool 
has become a frequent task. And for that I obviously use etherscan.

IDEA:

In your little (too narrow) popup "Transaction sent to network with hash" ...

I would like to click on the transaction hash, and be directed to the etherscan page.  
Or at least get the transaction hash into the clipboard, to be able to manually paste it.  

At the moment, in v1.7.12, I have to inspect the sourcecode to get the transaction hash 
out of the client - which is tedious, needs many steps, and is error-prone.

Example:

with sourcecode inspection, I get to:
```
<div class="requests__inline___n4i6s"><span>Transaction sent to network with hash</span><div class="requests__fill___3TjYl requests__hash___2O_y0"><abbr class="shortenedHash__hash___29L47" title="0x4c59d937f0caf0061b4d35a4bf8ae46739b4a75911da35b18846c631f1971a69">4c59d9…971a69</abbr></div></div>
```

then I can extract that "title" property 0x4c59d937f0caf0061b4d35a4bf8ae46739b4a75911da35b18846c631f1971a69
(because you do not show the whole but only `4c59d9…971a69` which is useless)

only now I can paste it into etherscan:
https://etherscan.io/tx/0x4c59d937f0caf0061b4d35a4bf8ae46739b4a75911da35b18846c631f1971a69

**Please make that procedure easier, thanks.**

**Comment by 5chdn** [comment]
Just head to the signer tab, there you have clickable transaction ids.

Or use the TX QUEUE dapp (applications view).

**Comment by partyspy** [comment]
Am I wrong I just don't see any Signer Tab?
