### ISSUE TITLE
Parity crashes when usb wireless dongle for the keyboard/mouse is removed

### ISSUE THREAD

**Issue by zabirauf** [paritytech/parity#7516]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?v1.7.8-stable-d5fcf3b-20171025
> - **Which operating system?**: Windows
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have a wireless keyboard and mouse connected (specifically Microsoft Sculp Ergonomic Keyboard). I have parity running with the following command `parity.exe ui --base-path PATH_TO_BASE_DIRECTORY`. When I take out my wireless dongle for the keyboard mouse parity crashes. Not sure how it is linked but I'm able to consistently reproduce the issue.

![image](https://user-images.githubusercontent.com/1104560/34765640-e3f4d7c4-f5a6-11e7-8b1c-e8de1feb213b.png)

I see the following in the event logs

```
Fault bucket 1723688955156595548, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: parity.exe
P2: 0.0.0.0
P3: 59f07900
P4: parity.exe
P5: 0.0.0.0
P6: 59f07900
P7: c0000005
P8: 0000000000e52ebe
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER5C5.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER673.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER66F.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER69F.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_parity.exe_ae225145735dc7c4eb453db6f25b6ba7036cf_c98f36eb_2b3409cb

Analysis symbol: 
Rechecking for solution: 0
Report Id: bef8afb9-a58d-4ba0-91c5-c88f78de6812
Report Status: 268435456
Hashed bucket: 6b717adcf6f028a387ebc5f8e35f835c
```

```
Faulting application name: parity.exe, version: 0.0.0.0, time stamp: 0x59f07900
Faulting module name: parity.exe, version: 0.0.0.0, time stamp: 0x59f07900
Exception code: 0xc0000005
Fault offset: 0x0000000000e52ebe
Faulting process id: 0x514c
Faulting application start time: 0x01d389f5da4ed017
Faulting application path: C:\Users\Zohaib\Downloads\parity.exe
Faulting module path: C:\Users\Zohaib\Downloads\parity.exe
Report Id: bef8afb9-a58d-4ba0-91c5-c88f78de6812
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by 5chdn** [comment]
I can reproduce this one :)

**Comment by folsen** [comment]
Almost seems like it would be a problem with the HID API (https://github.com/paritytech/hidapi-rs) on windows rather than any Parity specific code. But we only deal with USB for hardware wallets, so if there's any problem in out code it would be in the hw module.

**Comment by niklasad1** [comment]
@zabirauf 

Do you feel comfortable testing out a debug build that may solve this issue?
I can not verify it because I don't have access to a wireless keyboard

**Comment by zabirauf** [comment]
@niklasad1 Sure, i can test the build

**Comment by niklasad1** [comment]
@zabirauf 
Great,

You can get the binary [here](https://www.dropbox.com/s/h0f40lf70n7yowl/parity.exe?dl=0)

``` bash
# Checksum
$ openssl dgst -sha256 -hex parity.exe
SHA256(parity.exe)= 9cd67095a822c09900727f29f2e209b77e4a05d21c9d7219c37d7bdc3b112c47
```
Alternatively, you can fetch the source from [here](https://github.com/niklasad1/parity/tree/hardware-wallet/usb_fix)

**Comment by niklasad1** [comment]
@zabirauf Have you been able to test if the new binary fixes your problem?

I ran it on Windows with a Wireless keyboard and it didn't crash. I tried to connect and disconnect the keyboard a couple of times, would be great if you could verify this soon.

Thanks

**Comment by zabirauf** [comment]
@niklasad1 I've tested it and it seems to be working fine with your build.

**Comment by 5chdn** [comment]
:+1:
