### ISSUE TITLE
Download page lacks version information

### ISSUE THREAD

**Issue by miohtama** [paritytech/parity#7524]
I am trying to download the latest Parity version.

The current download page does not offer information 

- what version I am downloading or 

- what is the latest version

This is greatly reduced user experience compared to old parity.io site.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/49922/34781274-b2353bb4-f625-11e7-8f73-d97d36ddf77b.png">

**Comment by 5chdn** [comment]
Should also state what's being downloaded: installer, binary, ethkey, ethstore, etc...

**Comment by debris** [comment]
this has been resolved
