### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'Invalid parent hash'

### ISSUE THREAD

**Issue by xxmonsterx** [paritytech/parity#7525]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

Just waiting for warp sync..

2018-01-10 09:15:19  Syncing   #86605 d424…73fc     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed    #86605   19/25 peers     52 KiB chain   63 MiB db  0 bytes queue   19 KiB sync  RPC:  1 conn,  0 req/s,  82 µs
2018-01-10 09:15:21  Stage 3 block verification failed for #86622 (71fe…f9d4)
Error: Block(UncleParentNotInChain(e4d6a0d62cc456bd1ffbf2e2674d179a27a9abc235423aec04ab9e83c6fc0a3a))

====================

stack backtrace:
   0:     0x7ff6bc5d72f2 - hid_error
   1:     0x7ff6bc5d77d3 - hid_error
   2:     0x7ff6bbc3e674 - <no info>
   3:     0x7ff6bc71ebc4 - hid_error
   4:     0x7ff6bc71ea39 - hid_error
   5:     0x7ff6bc71e912 - hid_error
   6:     0x7ff6bc1fce4b - hid_error
   7:     0x7ff6bc086828 - <no info>
   8:     0x7ff6bbf65ebd - <no info>
   9:     0x7ff6bbf6b3fa - <no info>
  10:     0x7ff6bc720052 - hid_error
  11:     0x7ff6bbfbb516 - <no info>
  12:     0x7ff6bc71ca5c - hid_error
  13:     0x7ffb2c398102 - BaseThreadInitThunk

Thread 'IO Worker #2' panicked at 'Invalid parent hash: 26f1c63d4f1b91128493ec553c5084fce5a1e6e6b241f5b7b5aa8818f28454b4', ethcore\src\blockchain\blockchain.rs:1023

**Comment by folsen** [comment]
Closing as unreproducible. Probably a disk corruption issue.
