### ISSUE TITLE
AuRa: TemporarilyInvalid - block too early

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#7527]
> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: -
> - **Which network are you connected to?**: local
> - **Did you try to restart the node?**: yes

I have an AuRa network consisting of a single validator and a few ordinary nodes, they were all running on 1.8.4. Today I upgraded some of the ordinary nodes to 1.8.6 (replaced `parity` binary with the new version) and they stop syncing with this errors like this:
```
2018-01-10 21:16:09 UTC Verifier #0 TRACE engine  verify_block_external: block too early
2018-01-10 21:16:09 UTC Verifier #0 WARN client  Stage 4 block verification failed for #226896 (cf36…c81c)
Error: Block(TemporarilyInvalid(OutOfBounds { min: None, max: Some(1515618965), found: 1515618970 }))
```
If I downgrade them to 1.8.5 or 1.8.4 it doesn't reproduce. Time is in sync on all nodes (`chrony` is used). Nodes that were not upgraded are running ok.

**Comment by bjornwgnr** [comment]
@phahulin could you please check if the same happens with 1.7.12?

**Comment by rphmeier** [comment]
I don't think the same error would fire, but the block would get outright rejected with a different error. I am fairly surprised that the step is out of sync on the nodes though. We should suppress printing for this error.

**Comment by phahulin** [comment]
@bjornwgnr @rphmeier 
The same error reproduces on 1.7.12 - it synced a few blocks and then stopped:
```
2018-01-11 07:13:49 UTC Verifier #1 TRACE engine  verify_block_external: block too early
2018-01-11 07:13:49 UTC Verifier #1 WARN client  Stage 4 block verification failed for #234024 (317c…d7d6)
Error: Block(TemporarilyInvalid(OutOfBounds { min: None, max: Some(1515654825), found: 1515654830 }))
```
Note: to start on 1.7.12 I had to add `gasLimitBoundDivisor` to `params` section in chain.json.

**Comment by phahulin** [comment]
Also updated validator's node to 1.8.6 and it runs ok then. Went back to 1.8.4 validator - error happens again. So it seems you can't mix 1.8.6 with previous versions on the same network.
