### ISSUE TITLE
All four latest "stable" Parity clients are not able to fully sync!?! 

### ISSUE THREAD

**Issue by zumbatan** [paritytech/parity#7528]
> I'm running:
>
> - **Which Parity version?**: ALL latest stable Parity versions, from 1.7.9 till 1.7.12
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 

Actual:  after installing all four abovementioned latest parity versions (multiple times) , not ANY one of them was able to sync or warp the blockchain! this is incredible cosmic flaw of such high regarded crypto wallet!! how can you justify that four latest "stable" versions are not able to fully warp and sync, they always stop at 30% or 70% or 50%...  where does this root problem lie here exactly and how do you intend to solve this? More importantly, WHEN do you think it will be solved??

Appreciate your work, but syncing a wallet to the blockchain is the paramount function of a wallet, and yet your "stable" versions have hard time to cope with...   really hope this annoyance is quickly solved.

Thanks a lot!
@5chdn

**Comment by 5chdn** [comment]
Do the following,

- reset your database with `parity db kill`
- delete your `chains/ethereum/network/nodes.json`
- upgrade to 1.8.6

Magically, your client should sync :)
