### ISSUE TITLE
(feature request) trigger token information - button

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#7537]
Very often when I start parity (v1.7.12) only the ETH but not the token balances are shown in ACCOUNTS.

Then killing parity, and restarting sometimes helps. But not always.

What about a button "update token information", that triggers a download of the necessary information?

Thanks.

**Comment by 5chdn** [comment]
This issue is related to the size of the token registry. It needs a while to fetch all balances.

Related #6783

**Comment by drandreaskrueger** [comment]
thanks a lot, @5chdn 

you might want to reopen this issue, thanks.


> It needs a while to fetch all balances.

Define "a while" please.

I have cleaned cookies, used `window.localStorage.clear()` and since then I am waiting. 

Looking into the console now, seeing 
```
starting Tokens Provider
could not register SW after 2.5s
SW is setup
(*)
started Tokens Provider
```
 - is that the task that collects the token balances?

What about a some progress bar? It is already taking 8 minutes now. Is that shorter or longer than " a while" ?



Also, found this (*) error:

```
index.f1464c4a65.js:1 balances::fetchTokensBalances TypeError: Cannot read property 'gt' of undefined
    at index.f1464c4a65.js:1
    at Array.filter (<anonymous>)
    at index.f1464c4a65.js:1
    at Array.reduce (<anonymous>)
    at index.f1464c4a65.js:1
    at <anonymous>
```

as it says `balances::fetchTokensBalances` that could be a problem, right?


I have since problem only since I upgraded to the 1.8.7-stable version.

Parity/v1.8.7-stable-e3d32a4ab-20180123/x86_64-linux-gnu/rustc1.23.0 on Linux

**Comment by drandreaskrueger** [comment]
same error, more details

```
index.f1464c4a65.js:1 balances::fetchTokensBalances TypeError: Cannot read property 'gt' of undefined
    at index.f1464c4a65.js:1
    at Array.filter (<anonymous>)
    at index.f1464c4a65.js:1
    at Array.reduce (<anonymous>)
    at index.f1464c4a65.js:1
    at <anonymous>
(anonymous) @ index.f1464c4a65.js:1
Promise.catch (async)
(anonymous) @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
Promise.then (async)
(anonymous) @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
Promise.then (async)
value @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
Promise.then (async)
value @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
Promise.then (async)
l @ index.f1464c4a65.js:1
i.emit @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
Promise.then (async)
value @ index.f1464c4a65.js:1
t @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
t @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1
(anonymous) @ index.f1464c4a65.js:1

```

**Comment by drandreaskrueger** [comment]
v1.8.9-"stable" helped.

Thanks.
