### ISSUE TITLE
Your node is still syncing...

### ISSUE THREAD

**Issue by CeeDeeGee** [paritytech/parity#7538]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.8
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi. I am pretty New at this, so please fogive my lack of techical understanding/Language. I download and installed Parity Two days ago and tranferred a small amount of funds to my parity wallet. After two days of syncing I am still receiving the "Your node is still syncing, the values you see might be outdated. Wait until it's fully synced." message. I read in some other thread that this might take some take, but after two days my node is still syncing and the funds have yet to appear in my wallet. Is there anything I can do? Appreciate all the help I can get.

**Comment by duncfusion** [comment]
I'm having the same issue. I transferred some ETH to my account 2 days ago in order to participate in an ICO. Coinbase confirmed the transfer as complete and it shows up on Etherscan, but there's nothing to show for in Parity. Can anyone help us both please?!

**Comment by Mercy1968** [comment]
Having the same issue but nobody seems to care...thanks Parity

**Comment by kirushik** [comment]
@CeeDeeGee @duncfusion Running a full local Parity node requires you to get and replay all the blockchain blocks from the very beginning of Ethereum. That might take a long time, and days are not something unexpected on slower machines. (Disk IO is a bottlneck here most of the time; getting an SSD drive definitely makes things better.)

You can try:
1) first of all, please update to the latest Parity version; there's a version 1.8.6 out there already, which includes some important sync improvements which might make it easier for you to sync.
2) running that latest software, you might want to ensure that Warp sync is working, and your node is using it — looking at the logs will help; if Warp sync is still failing for you on our latest releases, we will be definitely interested in your logs, so we can solve the remaining cornercases with sync.

3) If you need an Ethereum node **urgently**, you might want to postpone setting up your own full node of the network, and make your first transactions from a "thin" web-wallet. We're running https://wallet.parity.io, where you can restore your account from a seed phrase and start using a fully-synced node right away. (Don't worry, all your crypto keys are only stored clientside, in your browser, and our server only operates on already-signed transactions your browser emit. This means, we won't have any access to your funds, even if you're using our server).
