### ISSUE TITLE
1.9.0 version of the problem or my parameters wrong?

### ISSUE THREAD

**Issue by johnsneakers** [paritytech/parity#7540]
i build parity from git clone, version is 1.9.0 unstable

i check problem all day...  
my problem is:
when i send_transcation other address ,  parity return err:

" Error importing transaction: Transaction(InsufficientBalance { balance: 1000100000000000, cost: 2331100000000000 }) "

------------------

the balance is true ,  but cost is unpredictable this is my post parameter:
value : 100000000000
gas: (i use eth_estimateGas(from, to, value) return value)
gasPrice:(i use eth_gasPrice return value)
password:(my password)

all parameters i had hex encode and check is true,  but  i get error everytime.

pls help me,  i try to all day but isn't work.

**Comment by lght** [comment]
You don't appear to have a large enough balance to send the transaction. Are you expecting the cost to be lower, or am I misunderstanding the issue?

**Comment by johnsneakers** [comment]
@lght 
i run parity code : 
parity --mode active  --pruning fast --db-compaction ssd --cache-size 1024 --jsonrpc --jsonrpc-apis "web3,eth,personal"


i have enough balace :  1000100000000000 (0.0010001)
i want to send 0.0001 eth to other address,  but error show :
Error importing transaction: Transaction(InsufficientBalance { balance: 1000100000000000, cost: 33400000000000000 })   i juse send 0.0001 eth  , why cost 2331100000000000 (0.0023311) ???
i dont know how calc this val

**Comment by lght** [comment]
I understand now, the extra cost you see is likely the gas price * gas used. 

If you would like another source for how much a transaction will cost, you can check https://ethgasstation.info/calculatorTxV.php.

Use the value from `eth_estimateGas()` as `Gas used`, and then you can play with different gas prices for the resulting transaction cost breakdown.
