### ISSUE TITLE
Parity is not synching chain, waiting for the ether 1 day now

### ISSUE THREAD

**Issue by Mercy1968** [paritytech/parity#7543]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.8
> - **Which operating system?**: Windows / 64
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no / 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I can't see the ETH tokens I have sent. The issue seems to be under node health section where it shows;
Chain Synchronized (no)
here is the hash information
https://etherscan.io/tx/0x06c614773626cde43e7fc8b8f429ccbfa1d5c4d7993d8dfca55996b0342c9181
Hope we can solve it urgently, want to send ETH to an ICO that is about to close, thanks

**Comment by folsen** [comment]
Update your version of parity to the latest and maybe try resetting the database and hope that you get a warp sync going.

**Comment by Mercy1968** [comment]
Hi, thanks for the reply..ı just reinstalled the new version, recovered the ether wallet adres but chain still does not sync and time sync needed as well but don't know how to do that

**Comment by Mercy1968** [comment]
Could you tell me how to fix; ''Your clock is not in sync. Detected difference is too big for the protocol to work: 690ms. Synchronize your clock.'' (690ms) I am not a computer expert, sorry and why still the chain is not syncing

**Comment by Mercy1968** [comment]
Hi Fredrik, do you have any help desk that can help right now? I am really worried about the ETH and to miss out the ICO ending soon,,

**Comment by Mercy1968** [comment]
Anybody helps?

**Comment by Mercy1968** [comment]
https://user-images.githubusercontent.com/35359823/34868487-0084ad16-f795-11e7-866c-4fd947fb83ee.PNG

**Comment by ddorgan** [comment]
Your time is not in sync, please run:

w32tm /resync

**Comment by roninkaizen** [comment]
time sync could also be done with opening chrome at
https://time.is
after opening, 
keep this page 3 min open 
and your time is going to be synced-
violà

**Comment by 5chdn** [comment]
Your chain is perfectly synched, see the left status icon (green).
