### ISSUE TITLE
How use Parity as wallet for website?

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity#7550]
I give for Ether acoount address for each user and now I can't understand how get list new transactions for all accounts. 
For example in bitcoind you can use -walletnotify for receive transactions, but in parity I can't understand how do this.
Also in bitcoind I can call RPC getbalance and it return balance of ALL accounts and addresses, but in Parity I need call list accounts and call getbalance for each account - this is stupid.
Also when I call info for transaction in Parity this doesn't return me confirmations count.
Also bitcoind have rpc user and password, but in Parity I can't set password for rpc.

As result I install on my website bitcoin, litecoin, dogecoin, dash, bitcoin cash, zcash....and I HATE ETHEREUM API.

**Comment by 5chdn** [comment]
Whenever I spill blood on my keyboard over stuff I do not understand I remember these words by Linus Torvalds:

> "Those who can - do; those who can't - complain."

I'm happy to solve your issues you have and help you onboarding to the Ethereum APIs, but I do not feel comfortable if you hate our API already and think Parity is stupid. Maybe Ethereum StackExchange or Reddit are your friends here.

**Comment by PavelNiedoba** [comment]
All famfamfam points are relevant. If you care about Eth price and want to use it for business, consider reopening (creating separate issues). Everybody who wants to accept Eth payments are fighting these same issues. See https://ethereum.stackexchange.com/questions/8547/how-to-explore-all-transactions-for-a-given-account, https://ethereum.stackexchange.com/questions/64438/how-to-get-list-of-all-transactions-on-all-accunts-in-parity-wallet.
