### ISSUE TITLE
Can parity only allow connecting to v6 ips?

### ISSUE THREAD

**Issue by HaitianLiu** [paritytech/parity#7551]
> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: MacOS
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

I'm using v6 ip address, and I want parity only allows making sync connections to peers with v6 ips.

Can I make it happen? 

Thank you  🙏🏻

**Comment by 5chdn** [comment]
No, Parity defaults to all IP address ranges on all available network devices.

You can, however, limit it to private or public address ranges with the `--allow-ips` flag if this helps.
