### ISSUE TITLE
Parity Sync Issues - 48 Hours and Still No Ether

### ISSUE THREAD

**Issue by ryanTen10** [paritytech/parity#7554]
> I'm running:
>
> - **Which Parity version?**: 1.7.8
> - **Which operating system?**: Windows 10 fresh install
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: I have restarted Parity a number of times and rebooted PC, does this qualify? 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I installed Parity 1.7.8 via the installer. 

While it was beginning to sync I sent ether from Coinbase. This transaction has been validated by etherscan. 

48 hours have passed and I have not received any Ether. I have kept my PC on and connected to the internet throughout. 

Parity is still trying to sync, the bars are yellow although twice in the last few hours the bars have went to green, chain sync = yes, then it resets and starts syncing again. 

I am also getting 'Your clock is not in sync' error randomly. Rebooting my PC sometimes resolves this. 

Any ideas how to go about fixing this? Is it possible I could lose my Ether? I'm starting to get slightly worried.... 

Any help is greatly appreciated. 
Many thanks

![image](https://user-images.githubusercontent.com/34130036/34918757-ee3c1d94-f94f-11e7-8ef0-2adba60744af.png)

**Comment by ryanTen10** [comment]
[1/14/2018, 5:23:48 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 19/25 peers 5 MiB chain 78 MiB db 0 bytes queue 5 MiB sync RPC: 1 conn, 3 req/s, 5015 µs

[1/14/2018, 5:23:58 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 19/25 peers 5 MiB chain 78 MiB db 0 bytes queue 6 MiB sync RPC: 1 conn, 3 req/s, 3884 µs

[1/14/2018, 5:24:08 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 20/25 peers 5 MiB chain 78 MiB db 0 bytes queue 7 MiB sync RPC: 1 conn, 3 req/s, 6370 µs

[1/14/2018, 5:24:18 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 19/25 peers 5 MiB chain 78 MiB db 0 bytes queue 7 MiB sync RPC: 1 conn, 3 req/s, 4320 µs

[1/14/2018, 5:24:28 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 20/25 peers 5 MiB chain 78 MiB db 0 bytes queue 8 MiB sync RPC: 1 conn, 5 req/s, 4931 µs

[1/14/2018, 5:24:38 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 18/25 peers 5 MiB chain 78 MiB db 0 bytes queue 8 MiB sync RPC: 1 conn, 3 req/s, 3730 µs

[1/14/2018, 5:24:48 PM]
 UTC Syncing #4188250 3e16…6115 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188250 17/25 peers 5 MiB chain 78 MiB db 0 bytes queue 9 MiB sync RPC: 1 conn, 3 req/s, 3523 µs

[1/14/2018, 5:24:58 PM]
 UTC Syncing #4188298 a93f…c922 4 blk/s 621 tx/s 23 Mgas/s 0+ 263 Qed #4188563 20/25 peers 6 MiB chain 78 MiB db 21 MiB queue 6 MiB sync RPC: 1 conn, 5 req/s, 3391 µs

[1/14/2018, 5:25:08 PM]
 UTC Syncing #4188463 b0a5…e823 16 blk/s 1340 tx/s 66 Mgas/s 0+ 228 Qed #4188692 19/25 peers 7 MiB chain 78 MiB db 23 MiB queue 5 MiB sync RPC: 1 conn, 5 req/s, 7378 µs

[1/14/2018, 5:25:18 PM]
 UTC Syncing #4188578 bd5d…de07 11 blk/s 1319 tx/s 52 Mgas/s 0+ 112 Qed #4188692 15/25 peers 7 MiB chain 78 MiB db 12 MiB queue 5 MiB sync RPC: 1 conn, 5 req/s, 7291 µs

[1/14/2018, 5:25:28 PM]
 UTC Syncing #4188650 7252…5141 7 blk/s 889 tx/s 35 Mgas/s 0+ 40 Qed #4188692 20/25 peers 6 MiB chain 78 MiB db 4 MiB queue 7 MiB sync RPC: 1 conn, 4 req/s, 15688 µs

[1/14/2018, 5:25:38 PM]
 UTC Syncing #4188692 a270…1c89 4 blk/s 503 tx/s 19 Mgas/s 0+ 0 Qed #4188692 22/25 peers 6 MiB chain 77 MiB db 0 bytes queue 7 MiB sync RPC: 1 conn, 6 req/s, 8761 µs

[1/14/2018, 5:25:48 PM]
 UTC Syncing #4188692 a270…1c89 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188692 16/25 peers 6 MiB chain 77 MiB db 0 bytes queue 7 MiB sync RPC: 1 conn, 4 req/s, 4761 µs

[1/14/2018, 5:25:58 PM]
 UTC Syncing #4188692 a270…1c89 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188692 16/25 peers 6 MiB chain 77 MiB db 0 bytes queue 8 MiB sync RPC: 1 conn, 5 req/s, 4788 µs

[1/14/2018, 5:26:08 PM]
 UTC Syncing #4188692 a270…1c89 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4188692 18/25 peers 6 MiB chain 77 MiB db 0 bytes queue 8 MiB sync RPC: 1 conn, 4 req/s, 4892 µs

[1/14/2018, 5:26:18 PM]
 UTC Syncing #4188693 585d…0445 0 blk/s 15 tx/s 0 Mgas/s 61+ 22 Qed #4188788 21/25 peers 6 MiB chain 78 MiB db 5 MiB queue 7 MiB sync RPC: 1 conn, 4 req/s, 4348 µs

[1/14/2018, 5:26:28 PM]
 UTC Syncing #4188807 543f…08d2 11 blk/s 1740 tx/s 57 Mgas/s 0+ 262 Qed #4189071 22/25 peers 6 MiB chain 78 MiB db 23 MiB queue 3 MiB sync RPC: 1 conn, 4 req/s, 12255 µs

[1/14/2018, 5:26:38 PM]
 UTC Syncing #4188951 d0dd…353e 14 blk/s 1583 tx/s 64 Mgas/s 0+ 118 Qed #4189071 21/25 peers 6 MiB chain 78 MiB db 9 MiB queue 3 MiB sync RPC: 1 conn, 3 req/s, 15363 µs

[1/14/2018, 5:26:48 PM]
 UTC Syncing #4189069 99ae…e2c0 11 blk/s 1003 tx/s 50 Mgas/s 0+ 0 Qed #4189071 18/25 peers 7 MiB chain 78 MiB db 0 bytes queue 3 MiB sync RPC: 1 conn, 3 req/s, 9744 µs

[1/14/2018, 5:26:58 PM]
 UTC Syncing #4189071 99d4…f35c 0 blk/s 27 tx/s 1 Mgas/s 0+ 0 Qed #4189071 15/25 peers 6 MiB chain 78 MiB db 0 bytes queue 3 MiB sync RPC: 1 conn, 8 req/s, 144 µs

[1/14/2018, 5:27:08 PM]
 UTC Syncing #4189071 99d4…f35c 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4189071 15/25 peers 6 MiB chain 78 MiB db 0 bytes queue 5 MiB sync RPC: 1 conn, 7 req/s, 1493 µs

[1/14/2018, 5:27:18 PM]
 UTC Syncing #4189071 99d4…f35c 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4189071 18/25 peers 6 MiB chain 78 MiB db 0 bytes queue 6 MiB sync RPC: 1 conn, 5 req/s, 131 µs

[1/14/2018, 5:27:28 PM]
 UTC Syncing #4189071 99d4…f35c 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4189071 18/25 peers 6 MiB chain 78 MiB db 0 bytes queue 6 MiB sync RPC: 1 conn, 5 req/s, 173 µs

[1/14/2018, 5:27:38 PM]
 UTC Syncing #4189071 99d4…f35c 0 blk/s 0 tx/s 0 Mgas/s 0+ 0 Qed #4189071 22/25 peers 6 MiB chain 78 MiB db 0 bytes queue 8 MiB sync RPC: 1 conn, 7 req/s, 167 µs

[1/14/2018, 5:27:48 PM]

**Comment by ryanTen10** [comment]
Again - Fully synced - still no Ether

![image](https://user-images.githubusercontent.com/34130036/34919477-c9493f5a-f95c-11e7-8862-340ae8686038.png)


5 mins later back to unsynced 

![image](https://user-images.githubusercontent.com/34130036/34919524-6ef8b35e-f95d-11e7-8198-9576935e2729.png)

**Comment by Eegee** [comment]
Synchronize your PC's time with `w32tm /resync` or by installing NetTime.

**Comment by ryanTen10** [comment]
Thanks for your reply Eegee. 

Please could you explain how to run w32tm/resync. Is that via cmd prompt? Sorry I'm pretty new to this. 

Thanks yes I will try updating to 1.7.12... I only downloaded Parity two days ago from their website but hopefully the update will help.

**Comment by Eegee** [comment]
Yes, that's via cmd prompt.
Though I like 3rd party tool [NetTime](http://timesynctool.com/) better. Easy to install as a Windows service and regularly syncs without much hassle.

**Comment by ryanTen10** [comment]
Okay great thanks for your help! 

I'll give that a go now, fingers crossed.

**Comment by ryanTen10** [comment]
Still having issues with this unfortunately. 

I have installed NetTime which has resolved the time sync issue. 

I'm still unable to fully sync and my Ether is still not showing (over 72 hours syncing).
I have just attempted to download Parity 1.7.12 and noticed my local drive is pretty much full, like 20Mb left. 

Parity has taken up around 100GB of space. Any ideas what I should do now? 
This is my first experience with software wallets and so far it's been a nightmare. 

I have a harddrive in my D drive with 400Gb free space. Do I need to restart this whole process? 

Any help is really appreciated. 
Thanks

**Comment by ryanTen10** [comment]
Is there a risk here that I could lose all my Etherum?

**Comment by Eegee** [comment]
Syncing can just be very slow, many struggle with it unfortunately. My Parity currently is behind as well and now it is warp syncing but it still takes quite some time.

You should not need to restart the sync process, you can move the data folder to your D drive:
First shut down Parity if it's still running.
Then, via Windows Explorer, move the data folder (which should be in  `%appdata%\Parity\Ethereum\`  (%appdata% maps to C:\Users\ _username_ \AppData\Roaming ) ) to your D: drive in some logical place and give it a sensible name, like for instance D:\ParityDB

Then you could do:
- start Parity.exe with the [extra parameter](https://paritytech.github.io/wiki/Configuring-Parity#cli-options) `-d D:\ParityDB`  (or `--base-path D:\ParityDB`, that's the same) next time. Don't forget to add this parameter to any shortcut you use to start Parity.
- or you could make a directory junction to let Windows/Parity think you still have the data in the original location on C: , with:
`mklink /J C:\Users\(usernamehere)\AppData\Roaming\Parity\Ethereum D:\ParityDB`
(you probably need to do this in an elevated (administrator) cmd prompt)

Regarding the first option: you should also be able to alter the base data path configuration setting via [a config.toml file](https://paritytech.github.io/wiki/Configuring-Parity#config-file), but I haven't tried that myself so you should try that for yourself.

You won't lose any Ether, it's registered on the blockchain as you saw with Etherscan.
Just make sure you have [exported/backed up your wallet](https://paritytech.github.io/wiki/Backing-up-&-Restoring) or have a backup of the keys subdirectory (which is in `%appdata%\Parity\Ethereum` as well) , and still know your passwords of course.

**Comment by 5chdn** [comment]
If you experience sync issues, please use 1.8.6 instead of 1.7.12.

But make sure you kill your database first and remove your `nodes.json`.

**Comment by ryanTen10** [comment]
Thanks @Eegee, I will give that a go this evening. Hopefully that should work. 

@5chdn Please can you explain how to kill my database? Are you suggesting I should install 1.8.6 then restart the syncing process? 

Many thanks

**Comment by 5chdn** [comment]
Yes.

1. Install 1.8.6 and stop it (Tray - Quit).
2. Run `parity.exe db kill` from a command prompt.
3. Additionally remove your `nodes.json` file from your Parity directory (should be easily searchable).
4. Restart Parity.

**Comment by ryanTen10** [comment]
Thanks @5chdn. Would you recommend installing this in my D drive as mentioned above?

Or would it be fine to install on my local drive. It has around 60Gb of free space.

**Comment by ryanTen10** [comment]
Might be worth mentioning, I just noticed that my data folder looks to be stored in  C:\Users\Ryan\AppData\Local\Parity as opposed to C:\Users\Ryan\AppData\Roaming\Parity. 

Is this correct? My local\parity is over 60Gb whereas the roaming parity folder is around 900 bytes.   

I seen in another thread that the chain data folder is suppose to be in Roaming\Parity. 
Again apologies if this is a really noob question. Still trying to get my head around all of this and want to make sure everything is in order before I restart the syncing process. 

Thanks for all help thus far.

**Comment by ryanTen10** [comment]
Not sure if this is worth mentioning but my data folder is not in Roaming\Parity\Ethereum it is instead in AppData\Local\Parity.

**Comment by ryanTen10** [comment]
Hi @Eegee,

Thanks I have successfully made a directory junction to let Windows/Parity think I have the data in the original location on C: , with:
mklink /J C:\Users\(usernamehere)\AppData\Roaming\Parity\Ethereum D:\ParityDB

I then installed 1.8.6, ran parity.exe db kill and removed my nodes.json file.

I began the resync process then annoyingly after a few hours noticed my C: drive was again starting to max out. It seems my data folder is not in  is not in Roaming\Parity\Ethereum it is instead in AppData\Local\Parity. 

Is this normal that my data folder does not sit in  \AppData\Roaming?

The directory junction I have made effectively  does nothing, all the data is going to my C drive.

Any help is greatly appreciated.  
Thanks


![img02](https://user-images.githubusercontent.com/34130036/35270567-72c9c452-0027-11e8-9829-b519d0e6319f.png)


![img01](https://user-images.githubusercontent.com/34130036/35270577-7ea3f202-0027-11e8-9e2c-de327afbb91b.png)

**Comment by Eegee** [comment]
I'm sorry, I might have switched those two directories around. Anyway, I meant the larger directory of the two, with the chains subdirectory in it . So yes it's normal there are two directories. 

Also, as I told earlier I've been syncing myself as well last week, and I really wasn't able to catch up with my 5400 rpm HDD replacement, so I had to go back to my SSD. So this is just some information for you that you most likely need to sync on SSD if you want to be able to catch up. Let's hope we'll be able to sync with regular HDDs again in the future. 
for

**Comment by ryanTen10** [comment]
Okay thanks for your reply. 

In that case it looks like I might just need to continue syncing on my SSD C: drive as I can't afford a new SSD at the minute and really want to get my ether. 

My C drive SSD has around 40gig free and I can potentially free up another 30/40 gig. Would this be enough space for me to sync to the node and recieve my Ethereum? 

Thanks

**Comment by Eegee** [comment]
On my pc the directory currently is 40GB, so I would advise to try and free some of that 30/40 gig first
