### ISSUE TITLE
"You are not connected to any peers. There is most likely some network issue. Fix connectivity."

### ISSUE THREAD

**Issue by kciryt** [paritytech/parity#7556]
I started off running Parity fine, then eventually was only connected to a single peer.  This dropped off to 0 peers and now the display shows "You are not connected to any peers. There is most likely some network issue. Fix connectivity."

 I'm running:

 - **Which Parity version?**: Parity/v1.10.0-unstable-e7f3666-20180113/x86_64-linux-gnu/rustc1.23.0
 - **Which operating system?**: Ubuntu 16.04.1 LTS
 - **How installed?**: from source
 - **Are you fully synchronized?**: no
 - **Which network are you connected to?**: Kovan
 - **Did you try to restart the node?**: yes

My issues seems to be identical to https://github.com/paritytech/parity/issues/6945 which was marked as "Fixed", though there doesn't seem to be a solution shared.

Here is a log of a run attempt with ./target/release/parity --testnet --config testnet_config.toml
[parity-testnet.log](https://github.com/paritytech/parity/files/1629836/parity-testnet.log)

Not sure how typical it is to encounter peers with a different genesis block, but it is happening a lot:

genesis hash mismatch (ours: a3c5…2cb9, theirs: b2a5…6659)

**Comment by 5chdn** [comment]
Please remove your nodes.json and try again!

**Comment by awgneo** [comment]
I have this issue as well and it requires me having to delete my nodes.json file multiple times per day or else my parity instance becomes unusable. I am on v1.8.6 on Kovan. My instance hovers around 6-9 peers and gradually drops to zero over the course of a few hours. I have a mainnet instance (also v1.8.6) on a cloned setup and it never experiences this issue.

**Comment by kciryt** [comment]
@awgneo, this describes exactly my issue.  Though deleting the nodes.json file solves the immediate problem, that this emerges so predictively is an issue--the suggested hack/fix is not a sustainable solution. @5chdn, I suggest this issue be reconsidered if problem is not currently known and documented.

**Comment by awgneo** [comment]
I am able to get fully synchronized via warp, however; for me, this problem only manifests itself after warp sync is complete.

**Comment by 5chdn** [comment]
This is probably the issue #7531

**Comment by neelimabhukya** [comment]
You are not connected to any peers. There is most likely some network issue. Fix connectivity.
