### ISSUE TITLE
Token Registry limits name to 3 characters

### ISSUE THREAD

**Issue by butterstuff** [paritytech/parity#7558]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Mac OS
> - **How installed?**: homebrew
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes
_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Attempting to have the SPANKCHAIN token added to the Parity token registry and, due to the 3 character limit and another coin with a similar moniker (SPANK coin), there are limited options.  

Would it be possible and if so, too difficult to allow a 4th character in the registry?

**Comment by cgruber** [comment]
Having the same issue with LATX.  ERC20 token symbols are, these days, frequently longer than three letters.  

Indeed, even the [sample token in the comments of the ERC20 token standard][1] is "FIXED" (5 letters) and the solidity type for an ERC20 token symbol is "string". 

[1]: https://theethereum.wiki/w/index.php/ERC20_Token_Standard

**Comment by 5chdn** [comment]
Thanks for your thoughts, please discuss the new token registry here:

https://github.com/paritytech/contracts/issues/83

**Comment by 5chdn** [comment]
Duplicate of #4698
