### ISSUE TITLE
chain sync takes forever

### ISSUE THREAD

**Issue by ephei** [paritytech/parity#7569]
Hi i just installed Parity the chain sync takes forever, anybody who can help me out?

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by Submariner78** [comment]
Same here!

**Comment by roninkaizen** [comment]
good morning,

reading your "lines" -
is giving me following questions-

why NOT providing the MOST ESSENTIAL information about your setup/config drives me to the conclusion, that you do not know it.
Do not waste a second and read the manual:
https://paritytech.github.io/wiki/

and PLEASE provide information about the mentioned system to make it possible to help.
Not even operating system nor information about the used network is given-
how should solution look like- for you? some angel came around and implements changes?
