### ISSUE TITLE
Could you unregister my token?

### ISSUE THREAD

**Issue by nueverest** [paritytech/parity#7570]
> I'm running:
>
> - **Which Parity version?**: 1.8.6-beta
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I deployed and registered a token via the Parity Deploy and Register applications.

I need to undeploy and unregister this token.  How do I do this?

I replied to a closed thread 2 days ago but no one has responded.

I'm only seeing 127 tokens as opposed to 127,000,000.

Please unregister our token or change decimals if you can.
Creator: 0x002cB47bf231ec986A1D6dCB5995A77bBDABBBD4
Token: 0xb9fd87c44f5046c73D60492614793872b6Ac23c1
PHT
Purple Heart Token

Registration event: 0x5F0281910Af44bFb5fC7e86A404d0304B0e042F1

**Comment by nueverest** [comment]
It would be nice to see feedback during the Deployment process about what the actual (human-readable) supply will be while filling out the form instead of the uint256 base 1,000,000 number.  

It would also be nice to be able unregister and undeploy a coin in a decentralized fashion.

**Comment by 5chdn** [comment]
Removed PHT
