### ISSUE TITLE
I just need a wallet - not a node!

### ISSUE THREAD

**Issue by Submariner78** [paritytech/parity#7571]
> I'm running:
>
> - **Which Parity version?**1.8.6
> - **Which operating system?**: MacOS 10.13.2
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

Hi
Beginner level here, sorry!

I was jut looking into creating a wallet that supports bitclave coins, and I got stuck into the node world! Problem is that I transfered some ETH (0,4) to my Parity wallet (0x001CdB1aeB89A1852b3b2bCfA4F7Cf79BBD33449) but I don't see them. I don't need to create a node just to store my Ether on the wallet. 
Could you help?

FYI: I selected "parity doesn't sync" in the settings as my computer was 2 slow and couldn't fully sync with the node after 48h.

Thx
![capture d ecran 2018-01-15 a 18 54 22](https://user-images.githubusercontent.com/35440389/34965885-89a018b4-fa25-11e7-9ff4-ec5f18c09e8a.png)

**Comment by Submariner78** [comment]
Here are the confirmation and details:

![capture d ecran 2018-01-16 a 00 48 50](https://user-images.githubusercontent.com/35440389/34973701-19d26cbc-fa57-11e7-8c14-907c061e3272.png)

**Comment by Submariner78** [comment]
Thanks for your help!

**Comment by 5chdn** [comment]
I think what you want is https://wallet.parity.io ;)

**Comment by Submariner78** [comment]
But I have one already! 
I'm confused  :/

Let me try to create an other one https://wallet.parity.io

**Comment by Submariner78** [comment]
YEAAAAH!

So I create the NEW wallet, 
exported my OG wallet as a Jason file,
imported  it (the Jason file) in the NEW wallet,
and boom!

:)

![capture d ecran 2018-01-16 a 08 48 31](https://user-images.githubusercontent.com/35440389/34992115-10892cca-fa9a-11e7-9075-557b0d9f5356.png)

**Comment by 5chdn** [comment]
wallet.parity.io is hosted by us. The local one is hosted by yourself.

See https://paritytech.github.io/wiki/Public-Node

And https://paritytech.github.io/wiki/Wallet.Parity.Io
