### ISSUE TITLE
Opus Token not appearing in balance

### ISSUE THREAD

**Issue by xiamaz** [paritytech/parity#7573]
I'm running: Parity 1.7.12 on Debian Stretch (installed via deb)
fully synchronized, connected via ethereum, restarting node did not help

Expected behavior: The balance appears in the smart contract monitor and the address of the opus smart contract has been registered in parity. Thus the token balance for OPT should be visible in the balance.

Actual behavior: No OPT is shown.

**Comment by 5chdn** [comment]
Please share your account to investigate (you can direct message me on Gitter or Riot).

**Comment by roninkaizen** [comment]
as many people mention this with various tokens within their clients, 
allmost disappearing within minutes to seconds,
i cannot confirm this behavior to my limited ressources,
but heard actually (after Block#4985000) again and again, that coins disappear-
which really is annoying-
even the rewatching of the token emitting contract, like it worked for me,
gave no solution to the-
so please keep it open, and keep incoming reports still being read.

PS: is there a new mate "visible"-https://github.com/devops-parity ?

**Comment by yuggo** [comment]
same issue, first with 1.7.6 now same problem after updating to 1.8.7
macOS (High Sierra), installed through pkg

**Comment by 5chdn** [comment]
Yes, all versions are affected, please stay tuned for 1.8.8 or 1.9.1 with a fix.
