### ISSUE TITLE
new documentation

### ISSUE THREAD

**Issue by roninkaizen** [paritytech/parity#7574]
I'm running:

Which Parity version?**: 1.9.0
Which operating system?**: Linux
How installed?**: from source
Are you fully synchronized?**:  yes!
Which network are you connected to?**: ethereum foundation
Did you try to restart the node?**: no / no / no

Looking at
https://paritytech.github.io/wiki
i found a broken link-
https://paritytech.github.io/wiki/Deploying-DApps-to-Parity-Wallet
leads to nowhere.
as i was not able to propose any changes to the sidebar entry-
i do it here and apply for 0.00001 ether from the bug bounty program 8-)....

..wrong channel, what i realized too late
it may be moved to the wiki submodule issues within the wiki itself-

**Comment by 5chdn** [comment]
Hi Ronin, you can report documentation issues here: https://github.com/paritytech/wiki

Or fix them directly by submitting a pull-request :)
