### ISSUE TITLE
Check left-over references to .parity directory

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7575]
> I'm running:
>
> - **Which Parity version?**: 1.7.11
> - **Which operating system?**: Linux
> - **How installed?**: via installer binary
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: Private Blockchain
> - **Did you try to restart the node?**: N/A

Can someone explain the versions/reasons/etc. behind having .parity directory vs .local/share/io.parity.ethereum?

I have multiple servers that don't consistently use the same file structure and it's making me crazy writing scripts that apply to all of them (such as when I have to update the chain spec file on all the servers, or delete the nodes.json files).

What's worst is that even though they are all running 1.7.11 binary, sometimes Parity creates one type of directory and sometimes the other and I don't see a pattern.  Insight would be helpful.

**Comment by 5chdn** [comment]
`.parity` is not used anymore (for more than a year now). You can nuke it after backing up your keys.

**Comment by stone212** [comment]
@5chdn The servers are brand new and they have 1.7.11 on them and they use the .parity directory.  So something is off here.

Also: exactly which key(s) do I need to back up?  Please be specific.  I know .parity/network/key but is there something else?

**Comment by 5chdn** [comment]
Your account's keys obviously :)

That's an interesting find. Could you remove it and check if it reappears? Because it should not.

**Comment by stone212** [comment]
> Your account's keys obviously :)

Ah, good.  There could have been something else as well so it's good we have the whole list in this thread.  network key an account keys.

> That's an interesting find. Could you remove it and check if it reappears? Because it should not.

As of yesterday before I posted the comment, I removed the .local folders.  Then I restarted Parity.  The .parity folders disappeared and the .local/share/.io.... folder reappeared.  That is why I asked:

"Will the .parity directory be moved by Parity to .local/share/io....?"

Because that is what seems to have happened.  

Except on one of the servers, where the .parity directory is still there.

> Could you remove it and check if it reappears?

I did that.  I removed .parity directory.  I re-ran Parity.  The .parity directory came back immediately.  No .local directory was created or exists at all.  Again, this is an Ubuntu server running 1.7.11 binary.

**Comment by stone212** [comment]
And when I remove all directories and restart the node, Parity 1.7.11 creates a .parity directory but no .local/share/io... directory.

**Comment by stone212** [comment]
Holy cow.  One at least one of the (identical) servers creates a .local/share/.io... directory and not .parity.  Also an Ubuntu server running 1.7.11 binary.  In fact, it was installed using the same BASH script that the others were installed with.

**Comment by 5chdn** [comment]
Weird. Is there some kind of config file present?

**Comment by 5chdn** [comment]
Interestingly, the upgrade script contains a reference to `.parity`.

https://github.com/paritytech/parity/blob/master/parity/upgrade.rs#L103

But there are no updates for 1.7.11 triggered yet.

**Comment by stone212** [comment]
Good question but no config file (just a custom chain spec invoked with --chain /path/to/chainspec.json).  Please believe that I know how strange this sounds.  It sounds strange to me.

These servers were all created with the same script originally (a BASH script that logs onto each server, apt-get upgrades, downloads and installs parity, creates the parity user, downloads the chain spec and reserved-peers file, creates a parity crontab that runs "@reboot /home/parity/invokeParity.sh", creates the /home/parity/invokeParity.sh script, changes ownership of the /home/parity dir to parity.parity, and reboots).

I have manually removed and played with the directories since finding an inconsistency.  (The inconsistency came when I wanted the script to delete the network/nodes.json files, and I realized that on some servers, these were in .parity/ dirs and on others, in .local/share/io..!)  So these servers are *very* similar.  And although I am not above making a stupid mistake, I'm very competent to handle this many servers, and I am not someone who thinks that things just "happen" by themselves.

If you have a meaningful suggestion I will try it.  But let me also ask this: On Parity 1.7.11, what *should* the default behavior be under the following circumstances:

1 - Parity has never been run before and there is no .parity dir and no .local/... dir?

2 - Parity is invoked for a user that already has a .parity directory?

3 - Parity is invoked for a user that already has a .local/share/io... directory?

4 - Parity is invoked for a user that has both a .parity and a .local/share/io... directory with different network keys?

**Comment by stone212** [comment]
> Interestingly, the upgrade script contains a reference to .parity.

What is an upgrade script in this context?  Is it to upgrade from one version to another, or is it the script that Parity automatically runs to update Parity data from an older version to newer?
I don't read rust so I am lost trying to understand "pub fn upgrade_data_paths" here https://github.com/paritytech/parity/blob/master/parity/upgrade.rs#L200 and I also don't understand line 103 that you posted, although it definitely does mention .parity and you've said that versions for more than a year haven't used .parity.

That just can't be true because I didn't know about Parity a year ago and typically I've seen the .parity directory on binaries, and .local/share/io... on versions I compile from source.  (Which is an important detail I didn't mention before).

`let legacy_root_path = replace_home("", "$HOME/.parity");`

Is that trying to determine what the legacy Parity directory is?

**Comment by 5chdn** [comment]
I just learned this is a valid fallback if Parity cannot detect your `$XDG_DATA_HOME`. Can you check the output of that environment variable? Can you check if your distro uses `xdg-user-dirs` package?

**Comment by stone212** [comment]
@5chdn 
All of the servers show a blank value for all users when I run:

`parity@adminnode:~$ echo $XDG_DATA_HOME

parity@adminnode:~$
`

Some of the servers have the xdg-user-dirs package installed.  Some do not which means that it is not a dependency of the amd64 deb packages.

What I do not remember is whether the servers that do not have that package installed are also the ones that I had the trouble with.  (I am trying to manage these remotely with scripts as much as possible, so even the ones without the problem now have symlinks from .parity to .local/share/io.parity.ethereum).

**Comment by 5chdn** [comment]
What's the output of `echo $HOME` ?

**Comment by stone212** [comment]
```
parity@adminnode:~$ echo $HOME
/home/parity

parity@adminnode:~$
```
