### ISSUE TITLE
How can I receive transactions to my account without walletnotify?

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity#7585]
I install to my website bitcoin, litecoin, dogecoin, dash, bitcoin cash, zcash and I want install parity for receive payments in ETH.
But I can't understand: How can I receive transactions to my account without walletnotify? I give ethereum account for each user of my website and I can't understand how receive transaction with RPC API?

**Comment by 5chdn** [comment]
Hi, please look at the following discussions on StackExchange:

- https://ethereum.stackexchange.com/questions/17818/ethereums-version-of-walletnotify-to-monitor-a-bunch-of-addresses
- https://ethereum.stackexchange.com/questions/18387/how-to-monitor-all-your-addresses-and-send-payments-out-immediately-to-a-main-ad
- https://ethereum.stackexchange.com/questions/33446/wallet-notify-in-ethereum
