### ISSUE TITLE
Parity failed to compile.

### ISSUE THREAD

**Issue by janus** [paritytech/parity#7592]
_Before filing a new issue, please **provide the following information**._

 I'm running:

 - **Which Parity version?**: 1.10.0
 - **Which operating system?**:  Linux
 - **How installed?**:  from source (https://github.com/paritytech/parity/)
 - **Are you fully synchronized?**: N/A
 - **Which network are you connected to?**: N/A
 - **Did you try to restart the node?**:N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

rustc version : 1.22.1
- git clone https://github.com/paritytech/parity.git
- cd parity
- cargo build --release
Spits below error message

   Compiling xml-rs v0.3.6
error: cannot find macro `bitflags!` in this scope
error[E0412]: cannot find type `IndentFlags` in this scope
     |
86 |     indent_stack: Vec<IndentFlags>,
     |                       ^^^^^^^^^^^ not found in this scope
error[E0433]: failed to resolve. Use of undeclared type or module `IndentFlags`
error[E0425]: cannot find value `WROTE_TEXT` in this scope
error[E0425]: cannot find value `WROTE_MARKUP` in this scope
error[E0425]: cannot find value `WROTE_NOTHING` in this scope

Summary, failed to compile parity. Could someone help me out?

**Comment by GoodMirek** [comment]
I have just successfully made a clean build of commit 25b19835e316f53366df67b66244a8eee95bc865
```
./parity --version
Parity
  version Parity/v1.10.0-unstable-25b19835e-20180117/x86_64-linux-gnu/rustc1.22.1
```
Build system: Fedora 27, up-to-date with updates track

Rust, cargo and other dependencies have been installed via RPM package manager from distribution repository. Attached is build output [parity-dev_build.txt](https://github.com/paritytech/parity/files/1638567/parity-dev_build.txt) and list of installed RPM's [rpm-qa.txt](https://github.com/paritytech/parity/files/1638481/rpm-qa.txt).

As troubleshooting, I would suggest to run a clean virtual machine, install all dependencies, pull the latest commit and try again there. If the issue persists, complete build output and list of installed RPM/DEB packages can help analyzing the issue.

**Comment by GoodMirek** [comment]
It seems the build of commit 25b1983 is importing old blocks way much faster than the build I have created from master 2-3 days ago :+1:

**Comment by 5chdn** [comment]
@janus please upgrade rust to 1.23.0
