### ISSUE TITLE
'IO Worker #0' panicked at 'DB flush failed.: "Error converting string"', src\libcore\result.rs:860thread ':IO Worker #34' panicked at

### ISSUE THREAD

**Issue by MichaelA2014** [paritytech/parity#7595]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.7.8-stable-d5fcf3b-20171025/x86_64-windows-msvc/rustc1.20.0
> - **Which operating system?**: Windows 7 x64  16gb ram
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

Hello. I am running parity via command line. After running it for 10-20 minutes I get the following error:
`thread 'IO Worker #0' panicked at 'DB flush failed.: "Error converting string"', src\libcore\result.rs:860thread ':IO Worker #34' panicked at '
thread 'DB flush failed.: "Error converting string"thread 'IO Worker #2', IO Worker #1' panicked at 'src\libcore\result.rs' panicked at 'DB flush failed.: "Error converting string":DB flush failed.: "Error converting string"', 860', src\libcore\result.rs:src\libcore\result.rs:4:860
`

I set the following config 
`[network]

min_peers = 30

max_peers = 80

--cache-size = 2048`

What should I do?

**Comment by 5chdn** [comment]
Upgrade your client to 1.7.12 or 1.8.6 - this is a bug fixed already :)
