### ISSUE TITLE
Unable to deploy library contract with a function using Struct param type

### ISSUE THREAD

**Issue by dannystox** [paritytech/parity#7597]
_Before filing a new issue, please **provide the following information**._

I'm running:

> - **Which Parity version?**: 1.7.12
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm trying to deploy the following simple library contract with the Parity console:

library MyLib {

     struct Data {
        uint param;
    }

    function myFunction(Data storage _self) public {
        _self.param = 0;
    }
}

In the contract details screen I'm inserting the contract name, and after clicking create I'm getting the following error in the browser console:

**Uncaught Error: Cannot convert MyLib.Data storage to valid ParamType**
at a (index.f1464c4a65.js:1)
    at new e (index.f1464c4a65.js:1)
    at index.f1464c4a65.js:1
    at Array.map (<anonymous>)
    at Function.value (index.f1464c4a65.js:1)
    at new e (index.f1464c4a65.js:1)
    at index.f1464c4a65.js:1
    at Array.map (<anonymous>)
    at Function.value (index.f1464c4a65.js:1)
    at t.e (index.f1464c4a65.js:1)

Seems like Parity cannot handle an abi with a function that uses the `storage` keyword together with a struct param type.

**Comment by debris** [comment]
I believe it is related to https://github.com/paritytech/ethabi/issues/75 and is a problem with solc itself https://github.com/ethereum/solidity/issues/3409
