### ISSUE TITLE
`estimateGas` doesn't sum up the needed gas to make inner calls

### ISSUE THREAD

**Issue by denisgranha** [paritytech/parity#7602]
I'm not running any node, I'm performing transactions against a Gnosis Multisig in the Kovan Network with Metamask 3.13.4
Basically what I found is that need to send more gas in the transaction than what is actually consumed, if I send a more accurate amount of gas to perform the transaction it will throw an out of gas

The transactions are the following:
1. Create the Gnosis Multisig through https://wallet.gnosis.pm and metamask in Kovan
e.g: https://kovan.etherscan.io/tx/0x14cc9d933ac197612d9fb2e1f1ff73041a6a555f765b8ef5374b910523ab8cad

2. Add multisig owner with accurate gas amount 240k gas: https://kovan.etherscan.io/tx/0x3a7ddd5ed7bae3c2ad8343e42e0d32b0cf1759cfc3c6d946d6cd21c31ae41160

3. Add multisig owner with high gas amount 1M: https://kovan.etherscan.io/tx/0xc42a3e9310f37a42b4688a3ef80501d8743deaddb5b4b0bdbbad4419ba18af61

You can see that the add owner transaction consumes around 222k gas in the third transaction but it returns out of gas when sending 240k gas, why do we need to send more gas than what is actually consumed? seems like a bug / strange behaviour

For reference:

This is the main function https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L189

That does an inner call against the same Multisig Contract [in this line](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L233) against the [add owner function](https://github.com/gnosis/MultiSigWallet/blob/master/contracts/MultiSigWallet.sol#L122)

**Comment by denisgranha** [comment]
It's not a bug in the gas consumed https://github.com/ethereum/go-ethereum/issues/15911

But it's an issue with the estimateGas

**Comment by pgrzesik** [comment]
@denisgranha Can you provide more details about issues with estimateGas ? We're experiencing problems with estimateGas as well

**Comment by denisgranha** [comment]
Basically when there are inner calls to other contracts, estimateGas doesn't sum up the needed gas to make the inner call (needs more than what is actually consumed)

**Comment by folsen** [comment]
Closing in favor of https://github.com/paritytech/parity/issues/6982
