### ISSUE TITLE
How to change total supply of deployed token?

### ISSUE THREAD

**Issue by gadimbaylisahil** [paritytech/parity#7604]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.7.12
> - **Which operating system?**: MacOS
> - **How installed?**: via installer / homebrew 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
Hi guys, i was playing around and deploying my token where I made an incorrect calculation in token supply. Desired supply was 2,500,000 Tokens but forgot to multiply it with 10^decimal points.
How can I change it?

**Comment by 5chdn** [comment]
I can remove the entry for you

What's the TLA and address?

**Comment by gadimbaylisahil** [comment]
FAT
address: https://etherscan.io/address/0x3dd2b79a8874b474aaeaf4fad9fd4a80f37f2f88

**Comment by 5chdn** [comment]
Removed FAT
