### ISSUE TITLE
Parity 1.8.6 not pruning

### ISSUE THREAD

**Issue by ahrcoin** [paritytech/parity#7606]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

i sync the snapshot which takes ~12-15 gb of storage. The syncing of blocks seems to work fin as well which takes me to about 16gb used. Once it starts importing blocks it fills up 20 go in ~12-24 hours. It does not seem to be pruning like it should.

**Comment by ahrcoin** [comment]
I should elebaorate at the time when it starts importing I have filled up 16gb and the importing quickly fills up the 48gb ssd and then fails because of no space available. I have deleted and re synced multiple times with same result.

**Comment by andresilva** [comment]
The pruned database will probably take around 50GB. After you finish the initial snapshot sync it still needs to download ancient blocks for full verification, that's why the database keeps growing. If there was no pruning (archive mode) the DB would be an order of magnitude bigger (> 500GB).
