### ISSUE TITLE
When will trigger Parity to send new work(--notify-work) ?

### ISSUE THREAD

**Issue by bitkevin** [paritytech/parity#7608]
> I'm running:
>
> - **Which Parity version?**: v1.7.12-stable-f96d152-20180109
> - **Which operating system?**: Linux
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I am trying to use Parity for mining and using "--notify-work" to receive new work, I am wondering when will it trigger notify? 

Sure that when new height block coming will trigger, but notice that sometimes also trigger with the same height.

**Comment by Emperornero** [comment]
I don't have an answer for your question here, but solo mining is a very bad idea at this point in time unless you have a couple hundred GigaHashes at your disposal.  You need to look for a mining pool to join.

**Comment by bitkevin** [comment]
@Emperornero Thanks, actually I am building mining pool now.

**Comment by rphmeier** [comment]
Sometimes new transactions coming in will trigger a re-seal. Check the `--reseal-on-txs` option.
