### ISSUE TITLE
Request has been rejected because of queue limit.

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity#7611]
> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I can't send transaction, parity returns error "Request has been rejected because of queue limit."

**Comment by tomusdrw** [comment]
You already have 50 transactions that you need to confirm in Parity Signer. Consider using `--unlock` or `personal_sendTransaction` when sending large amounts of transactions, filling up the password manually 50 times is not feasible anyway.

**Comment by famfamfam** [comment]
But this is not my transactions in Parity signer...

**Comment by phahulin** [comment]
Today one of our users communicated with us that they encountered the same problem. From their words they're using `personal_sendTransaction` to sign and send txs and were getting this error when node was processing a lot of txs. As txs load decreased, error stopped.
We were unable to reproduce this error ourselves yet, but noticed that there seems to a [single place in source code](https://github.com/paritytech/parity/blob/e95b09348386d01b71901365785c5fa3aa2f7a6d/rpc/src/v1/impls/signing.rs#L136) where this error is generated, however all possible errors are handled in the same way there. Could it be that under a load, some other error is generated, or account is somehow not getting unlocked properly?

**Comment by tomusdrw** [comment]
@phahulin The code path you linked is not reacheable when using `personal_sendTransaction` and also in such case the password always need to be provided so it does not matter if the account is unlocked or not.

Could you please let us know a bit more detailed scenario of that bug? I.e. was the account unlocked via CLI or using `personal_unlockAccount`? Was `eth_sendTransaction` being used?

**Comment by s1241** [comment]
I try to deploy a smart contract and every time i receive "queue limit" error.

Here is what i do:

```
Web3 = require("web3")
web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8545"));
const bytecode = '0x606 ....
const abi = [ ....
web3.eth.personal.unlockAccount('0xa95523067A3bfF1B8aeB41F85D58C7fe2b88fde3', 'logic')
var thisContract = new web3.eth.Contract(abi, {
    from: '0xa95523067A3bfF1B8aeB41F85D58C7fe2b88fde3',
    gasPrice: '20000000000'
});
thisContract.deploy({ data: bytecode }).estimateGas(function(err, gas) { console.log(gas); });
2021348
thisContract.deploy({ data: bytecode }).send({
        from: '0xa95523067A3bfF1B8aeB41F85D58C7fe2b88fde3',
        gas: 2021348,
        gasPrice: '3000000000'
    },
    function(error, transactionHash) {
        console.log(error);
        console.log(transactionHash);
        console.log('function exec');
    }).then(function(newContractInstance) {
    console.log('Contract Instance:' + newContractInstance.options.address);
});
```


and every time i receive following error, even when i unlock account several times.

```
> Error: Returned error: Request has been rejected because of queue limit.
    at Object.ErrorResponse (/home/ubuntu/parityewf/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /home/ubuntu/parityewf/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/home/ubuntu/parityewf/node_modules/web3-providers-http/src/index.js:77:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ubuntu/parityewf/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/ubuntu/parityewf/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/ubuntu/parityewf/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/home/ubuntu/parityewf/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
undefined
function exec
(node:14469) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Returned error: Request has been rejected because of queue limit.
```

This may be helpful : https://tobalaba.etherscan.com/address/0xa95523067A3bfF1B8aeB41F85D58C7fe2b88fde3

**Comment by tomusdrw** [comment]
@s1241 `unlock` is extremely unsafe and should be avoided. By default in Parity it only unlocks the account for one transaction. If you send multiple transactions you either need to run in `--geth` compatibility mode or better just use `personal_sendTransaction` instead of `eth_sendTransaction`.
For service-like deployments you can run with `--unlock` CLI parameter, but make sure to correctly set up your node security (i.e. disallow external connections to RPC)

**Comment by s1241** [comment]
@tomusdrw Thank you very much for your response. however i need a bit more explanation :)
Would you please let me know exactly which part of my commands (above) must be changed ? thank you

**Comment by tomusdrw** [comment]
@s1241 You have 3 options:
1. Run Parity with `--geth`
2. Run Parity with `--unlock <address> --password <password-file>` and remove `personal.unlock` call from your script
3. or remove `personal.unlock` call from the script and ask on `web3` issue tracker how to use `personal_sendTransaction` instead of `eth_sendTransaction`. I'm pretty sure it's possible, but I'm not a web3 expert.

**Comment by borovik96** [comment]
I have the same issue when trying to send tx, I get the same error. I do not have unsigned transactions on my node, also I unlock account before sending tx. When I get all transaction from my node by RPC method - there are no txs from the address on which I get the error. Will appreciate any advice. Thanks!
