### ISSUE TITLE
Aura reportBenign of offline node doesn't work properly

### ISSUE THREAD

**Issue by VladLupashevskyi** [paritytech/parity#7627]
> I'm running:
>
> - **Which Parity version?**: v1.7.12-stable
> - **Which operating system?**: MacOS / Linux
> - **How installed?**: via homebrew / binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private AuRa chain
> - **Did you try to restart the node?**: yes

I'm running PoA aura chain with 5 validators using reporting contract. When one validator goes offline every other validator starts to report benign except one that receives the offline validator block. So I have 3 reports per cycle, but expected 4.

To reproduce the issue you have to have:
1. Reporting validator contract with 5 validators, functions reportBenign and reportMalicious can just fire events.
2. 5 validator nodes running
3. Turn off one node
4. Look at events and you find out that only 3 nodes report per cycle

**Comment by nicexe** [comment]
Reproduced the problem with 4 validators (3 sealing + 1 non-sealing).  
2 of them are reporting benign instead of 3

**Comment by folsen** [comment]
This should be reported as an issue on the relevant contract, probably https://github.com/parity-contracts/kovan-validator-set
