### ISSUE TITLE
Best practices for handling internal transactions (balance affecting calls)

### ISSUE THREAD

**Issue by AdvancedStyle** [paritytech/parity#7631]
When using parity RPC what is the best way to check a block for internal transactions against a list of addresses.

For example if you have a list of 100,000 addresses, it's quite easy to check for standard transactions, just get the block data and loop the transactions.

But what is the best way to extract data related to internal transactions (ie contract calls that add ETH to an address balance).  The best approach that I can think of is:
- Loop the block transactions searching through the data input for an address match (performance inefficient)
- For any hits, check the address balance before and after the block to see if the balance was changed.

The problem is this seems very inefficient and possibly becomes unworkable once the address set or block size becomes too large.

Note that I think that the trace module could be used but this has some problems:
- Seems to require keeping a massive (1TB+) copy of the blockchain
- Requires doing a trace_transaction on all transactions (performance intensive)

**Comment by 0v1se** [comment]
I'm interested in this too.
Although, I guess, tracing information is not so big. here is more information about size needed: 
https://ethereum.stackexchange.com/questions/28541/current-disk-space-requirements-for-a-pruned-parity-node (a bit outdated, september 2017)

**Comment by AdvancedStyle** [comment]
I think trace will not work well, because then you'd need to run a trace for every transaction in the block, and then run that against every address, which would be very slow.

**Comment by 0v1se** [comment]
@AdvancedStyle yes, you should check every transaction in block. But I don't think it's the problem. Currently there is about 11-12 transactions per second.
For checking addresses you can use something like Bloom filter (I think it can work)

**Comment by 0v1se** [comment]
@AdvancedStyle there is one more method in parity's RPC: [trace_block](https://paritytech.github.io/wiki/JSONRPC-trace-module#trace_block)

So, you have pretty simple algorithm:
1. check if new block is generated
2. call trace_block
3. iterate over results and check for transfers

no need to call trace_transaction for every transaction in block
from my experience: 
performance is good
takes not too much space

Though I would prefer purging trace database from time to time (I need only new traces)

**Comment by AdvancedStyle** [comment]
In the end I did it as follows, which although quite hackish appears to be the best performance for a large number of addresses.

# Step 1:  get_block via RPC

# Step 2: Loop through the transactions in the block, any that have an input != 0x then run a regex on the input to find any Ethereum addresses.

# Step 3: Run the addresses found from the regex again your list of wallet addresses to find any matches.

# Step 4: If any match is found, then check the balance of that address before the block and after the block to see how much it has changed.

This can be done on a pruned blocked chain and without trace mode enabled.

** To avoid issues be sure to ignore or account for any addresses which have also received standard transactions within the same block; which may have increased the balance of that address.

**Comment by 0v1se** [comment]
I think step2 is wrong. Even if input is "0x" it can be contract call (fallback function is called)

**Comment by AdvancedStyle** [comment]
Maybe should use the raw data instead of the input then.

**Comment by ankitarora121** [comment]
What is the final call on this issue? What's the best way to detect internal transactions in a block? I'd love to try it out myself but my node full sync will take a decent while. Both the above commenters proposed different solutions. Trace_block seems like a bulletproof way to do it, right?

**Comment by wenhuanglin** [comment]
@0v1se  thanks for the advice! I have a question regarding "purging trace database from time to time (I need only new traces)". How do you do it with node setting (--tracing on)?
