### ISSUE TITLE
How to move parity chain data from C driver to D driver?

### ISSUE THREAD

**Issue by lalalalaluk** [paritytech/parity#7638]
I'm running
parity version v1.7.10 on Win10

How to move parity chain data from C driver to D driver?

should i uninstall parity and re-install ?

**Comment by 5chdn** [comment]
You can use a config file to define the base path.

First, move your Parity data from `C:\Users\You\AppData\Local\Parity` to `D:\Parity`.

After that, create a config file in

    %UserProfile%\AppData\Roaming\Parity\Ethereum\config.toml

With the following parameters:

    [parity]
    # Blockchain and settings will be stored in D:\Parity.
    base_path = "D:\\Parity"

Starting Parity now defaults to these settings.

See https://paritytech.github.io/wiki/Configuring-Parity

And https://paritytech.github.io/wiki/FAQ-Backup,-Restore,-and-Files.html
