### ISSUE TITLE
Dealing with sendMultiSig contract method call

### ISSUE THREAD

**Issue by khelle** [paritytech/parity#7640]
Hi, today I received following transaction from Bitstamp https://etherscan.io/tx/0x344d4ef6bedbd7ef6e591c833c5df1652503ef4c1e4027764c63a79dcc4b62e1 . If I am not mistaken this is generated by multisig contract available in parity client. Where can I find ABI file to deal with this contract transaction programmatically? If I am wrong and this is not parity-generated multisig address, please say that and close this issue.

**Comment by 5chdn** [comment]
This does not look like a Parity multi-signature contract.
