### ISSUE TITLE
Parity not opening

### ISSUE THREAD

**Issue by zaarrs030** [paritytech/parity#7643]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Windows 7
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hey guys,

I am new to this and had issues with syncing to the chain from the beginning. Until now I did no see the Ethereum I have sent to my parity and start to believe that it's "lost". However, now I cannot even start parity. When clicking on the ptray.exe file, the parity icon appears in the task bar for 1 second just to disappear again. When clicking on parity.exe the command window opens for a second to disappears again as well (see screen shot).
![parity execution](https://user-images.githubusercontent.com/35630329/35184248-5f2f3926-fdf3-11e7-984e-2ce143975813.jpg)

I have uninstalled and installed different versions meanwhile and always had the same result.

Please help and advise on how I could make it work again.

**Comment by zaarrs030** [comment]
I just found that it might help to kill the db or deleting the entire directory ".local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d".

Can anybody explain how to delete a directory correctly?

Thank you for your time.

**Comment by zaarrs030** [comment]
Hey guys,

it's me again. Deleting the db has worked perfectly. Parity is running again and synchronizing at the moment.

This one can be closed. Thanks again.

**Comment by 5chdn** [comment]
Cool!

#7334
