### ISSUE TITLE
error: Found argument '--can-restart' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by LordOfBongo** [paritytech/parity#7644]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hey guys,

Im a total noob when it comes to parity or coding. I tried to start parity one day and i got the following messages:
![parity signer new-token](https://user-images.githubusercontent.com/35643950/35189499-e3432cce-fe4b-11e7-96eb-6157d00bf6ad.png)

When trying to generate a new token I got the following error:
![parity](https://user-images.githubusercontent.com/35643950/35189503-f91b648a-fe4b-11e7-8c22-c75ffd3ebd8c.png)

As I said im new to this and donät have a clue how to monve on from here. Any help is much appreciated.

**Comment by 5chdn** [comment]
Please upgrade to 1.8.6 :)

This is already fixed :tada:
