### ISSUE TITLE
After I switch to ether classic network on the Settings page, the item selected is gone.

### ISSUE THREAD

**Issue by HuangFJ** [paritytech/parity#7646]
> I'm running:
>
> - **Which Parity version?**: 1.7.11
> - **Which operating system?**: MacOS
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum classic
> - **Did you try to restart the node?**: yes

![this was the screenshot](https://user-images.githubusercontent.com/106249/35191835-bda22c80-febf-11e7-9b9c-1b676c9b7d4d.png)

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/70
