### ISSUE TITLE
Do not send transactions to the network

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity#7647]
I run parity with supervisor like 
parity --no-ui --tracing off --min-peers 50 --max-peers 100 --no-ancient-blocks --no-serve-light --jsonrpc-port 8435 --pruning fast --db-compaction ssd --jsonrpc-apis all --ws-interface local --jsonrpc-interface local --ui-interface all --cache-size 1024

I send new transaction to network with personal_unlockAccount and eth_sendTransaction this works fine and return TxID
But in real parity do not send it to network (I can't see my tx in etherscan)

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**:  Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

**Comment by famfamfam** [comment]
Im delete --no-ui, changed --ui-interface to local and reload parity.
Then new old transactions was deleted and new transactions shows in etherscan...

This is bug or what?

**Comment by famfamfam** [comment]
Can't answer now... But I was have the same error nearly 3 hours ago, and after restart parity and call eth_sendTransaction it in etherscan I see double spent transactions... One of those was rejected by network some time later...

**Comment by roninkaizen** [comment]
did you try to reduce your cli-
maybe the transactions are still "there" hanging in your node-tx-queue-
then i would try to cancel them, what also could result to heavy clickery-
other choice would be to downgrade to 1.7.13-
just to have a stable but little slow running node-

**Comment by 5chdn** [comment]
Yes, go to applications > txqueue viewer.
