### ISSUE TITLE
Transaction propagation strategies discussion

### ISSUE THREAD

**Issue by akru** [paritytech/parity#7648]
Hello everyone!

I want to start here discussion about one question: how transactions should be propagated and client options for control it.

The first, local transactions. Currently parity client have no options to control of local transaction propagation. For example, miner/validator pool wants to split block bounty for workers and send a lot of transaction. Pool interested in sealing txs in self block because it's free for him. But transactions from pool propagated to another peers and another pool can mine it. Currently client can only manipulate gasprice to prevent transaction settlement, some mining pools set 1GWei gasprice, but it is probabilistic solution not works at all.

The second, external transactions. In some cases miner/validator is prefer to settlement of specified transactions kind, for example, miner/validator receive bounty by contract if transaction will be sealed in his block. This case shows that not only gasprice can be used for txs ranking.

I have two proposals:

1. Add option to control local transaction propagation, in first view simple `disable-local-propagation` will be very useful;
2. Enable smart contract driven ranking algo for transactions like smart contract driven consensus.

**Comment by 5chdn** [comment]
We already support both:

1. Just send zero gas price transactions as local transactions (using eth_sendRawTransaction - such transactions won't be accepted by any other peer in the network)
2. Smart contract acceptance is implemented (nodes decide which zgp transactions to accept), but I think it works globally and he want's to have some kind of additional ranking boosting for some kinds of transactions. For this it's better to setup a off-chain solution:
    - Redis with PubSub
    - On RAW transaction sent over Redis do: eth_sendRawTransaction on the mining node (this will prioritize it locally)

**Comment by akru** [comment]
So, it’s big difference: transaction isn’t propagated or isn’t accepted & mined by majority of peers. What behavior is expected now? 
In your answer It’s also question about zero fee transactions, it’s possible now to send transaction with zero fee? It will be propagated?

**Comment by tomusdrw** [comment]
@akru Every node attempts to propagate all transactions from the queue (even the ones with zero-gas price).

By default nodes won't accept such transactions at all and won't re-propagate them. To answer your question - we don't support a way to have transactions in the queue and never propagate them (I'm struggling to understand the use case for this in general case; In your use case you want to save traffic on propagation?)

**Comment by akru** [comment]
In one of my specific case I want to save local generated transactions on node to seal it in local mined block.

**Comment by tomusdrw** [comment]
@akru And it's possible by using zero gas price transactions that won't be accepted by other peers (and especially other miners). I understand it's a bit of a workaround for you, since you don't want the transactions to be propagated at all, but don't understand yet why it's not enough.

**Comment by akru** [comment]
@tomusdrw Could you answer me one simple question: will zero fee transaction mined or not?
