### ISSUE TITLE
Parity exposes the current account address by default.

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#7653]
Parity exposes the current account address in the global web3 injection. Is there a switch to make it not do so? I'd rather not advertise my wallet address to any site I visit.

See https://twitter.com/backus/status/954921568198574080

**Comment by gaia** [comment]
Should I move this to https://github.com/paritytech/parity-extension ?

**Comment by tomusdrw** [comment]
You ca go to `Dapps -> Permissions` and disable all accounts there.
Whitelisting websites will be implemented in in Parity Extension soon as well.

**Comment by 5chdn** [comment]
> Should I move this to https://github.com/paritytech/parity-extension ?

Yes. :)
