### ISSUE TITLE
SLOW SYNC?

### ISSUE THREAD

**Issue by DiegoMorichelli** [paritytech/parity#7654]
I am syncing about 1000 blocks in an hour , how can i speed it up?
can i restart the syncing on 1)my device or 2)on another device to sync in FAST SYNC ?If yes how?
please answer i am risking to lose 2 ICOs because of this problem.
WINDOWS 10 / LATEST PARITY VERSION / 7 MBS per sec.

**Comment by 5chdn** [comment]
Don't miss ICOs! Use https://wallet.parity.io if your computer is too slow to process the chain!
