### ISSUE TITLE
Newb questions about the sync process

### ISSUE THREAD

**Issue by s1xpool** [paritytech/parity#7655]
> I'm running:
>
> - **Which Parity version?**: 1.7.8
> - **Which operating system?**: Windows10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

Please excuse my newbie questions, although I must admit I didn't find the answers in the FAQ or via google.

I installed parity today (like 8h ago) and whenever I open the webapp (http://127.0.0.1:8180/#/status), I'm told that I'm still syncing. I click the top left icon that looks like Wifi-Bars and I see "Chain synchronized (no)". Connected Peers: 40/50. Peers reads 0/40/50 and Hash Rate 0B H/s. 

Is there a way I can see the progress of the sync? And should the hash rate of 0B H/s concern me? Does anything else look off to you? Am I supposed to just wait? Is it contra-productive if I mine while waiting?

Thanks in advance!

**Comment by lloy0076** [comment]
In the lower right hand side of the browser window (where the status page is) you should see two large numbers OR something about % syncing NEXT TO the word "Foundation" in green.

You can also click the ">" looking button to see the logs.

You'll probably be hit by #6372 and other sync issues.

I have noticed that after a while, Parity simply stops doing anything on Windows no matter how I start it (via a `cmd` shell, using the `ptray` icon or what not) and honestly, I'm not convinced it will **ever** sync.

Good luck!

**Comment by roninkaizen** [comment]
dear s1xpool,
did you notice that another much more actual version is available?
some of your mentioned questions are allmost "answered"-
please have a second look at 
https://github.com/paritytech/parity/releases and please select a more actual version to install.
Also feel free to read parts of the documentation findable at
https://paritytech.github.io/wiki/

There are also various youtube videos telling you about the ethereum blockchain synchronsation-
take yourself the needed time to get in deeper "touch" with the ethereum-technology.
And also feel free to ask your questions at
https://gitter.im/paritytech/parity-
there are several very experienced users helping each other to get in "touch" with the mainchain, and keeping it updated all the time.
thanks for reading and understanding

**Comment by 5chdn** [comment]
> Is there a way I can see the progress of the sync?

It's in the footer (x,xxx,xxx/y,yyy,yyy) or on the status page. You can also scroll down and enable the logs by clicking the small triangle ("play").
