### ISSUE TITLE
Stage 3 Block verification failed (TooManyUncles) on raspberry

### ISSUE THREAD

**Issue by jbentke** [paritytech/parity#7657]
> I'm running:
>
> - **Which Parity version?**: 1.7.12, 1.8.4, 1.8.6, 1.10.0
> - **Which operating system?**: Linux
> - **How installed?**: binaries / from source
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: Tobalaba
> - **Did you try to restart the node?**: yes

I tried synching the chain but I get `Stage 3 block verification failed for #2170980 (3e705262) Error: Block(TooManyUncles(OutOfBounds { min: None, max: Some(0), found: 1 }))`

I tried it with 4 different Versions of Parity. I tried deleting the data and changing the --datadir to be sure. 

On my mac everything syncs fine.

**Comment by tomusdrw** [comment]
@jbentke Uncles for PoA networks are disabled by default. Please verify if the `chainspec` file you are using is correct. It should contain `maximumUncleCount` and `maximumUncleCountTransition` if uncles on that chain were disabled at some point.
