### ISSUE TITLE
Add new methods in API

### ISSUE THREAD

**Issue by famfamfam** [paritytech/parity#7662]
Can you add this methods to parity api:
1) parity_accounts
Which returns array with accounts and balances
`["account":"balance",...]`
Now we use eth_accounts + eth_getBalance for each, but this requires very long time (about 4 min for 3000 accounts)
2) parity_listTransactions
Which returns array with all transactions for specific account
3) parity_newTransactions
Which return array with new incoming and outgoing transactions, like walletnotify in bitcoind.
Or may be you can add --walletnotify option... 

We use Ethereum for website with about 100k users, but we have problems with it... Now we have to use hooks for solve it, but this is bad way.
Thanks.

**Comment by 5chdn** [comment]
3000 requests should take less than a second. We have to check this.

**Comment by tomusdrw** [comment]
1. Use batch requests and send all `eth_getBalance` in a batch
2. Not possible without tracing, regular transactions are not only way to call other contracts or call balances (think contracts)
3. See #6426
