### ISSUE TITLE
Did I have some limit for access parity?

### ISSUE THREAD

**Issue by shinsy1023** [paritytech/parity#7673]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.12
> - **Which operating system?**: MacOS
> - **How installed?**: homebrew
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum classic
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I can loop only about 260 times.

```
var block, tx, i, j;

for (i = 1968857; i < web3.eth.blockNumber; i++){
	block = web3.eth.getBlock(i)
	console.log(i);
	for (j = 0; j < block.transactions.length; j++){
		tx = web3.eth.getTransaction(block.transactions[j]);
		if (tx.from == account || tx.to == account){
			console.log(tx.hash);
		}
	}
}
```

I want to find every transaction which some wallet do
but I cannot loop all

It's same started at 0, 1920000, 2000000, 5000000.

Did I have some limit for access parity method?

**Comment by 5chdn** [comment]
What exactly happens after 260 times?

Nothing?

Anything in the Parity logs?

**Comment by shinsy1023** [comment]
Yes, I didnt have anything. but I solve it using recursive and callback.

I think it make sync process forced
