### ISSUE TITLE
Unable to download Win installer from Parity.IO web site

### ISSUE THREAD

**Issue by ImperatorRuscal** [paritytech/parity#7678]
The link being served is to an ethkey.exe file (via one of CloudFlare's CDN points).  The file is much smaller than I had expected, but it did pass the SHA-1 checksum.  When executing it warns of unreachable code, calls it a bug, and says to report here.

Since this is GitHub and I'm not a complete newbie I dropped by your Releases and got the current InstallParity.exe which works perfectly.  My guess is it is just a bad link in the main web site and wanted to report that (and, without better contact info on that page, my report circled back around to here).

For good measure:
> I'm running:
>
> - **Which Parity version?**:   error while attempting to install current release from main web page
> - **Which operating system?**: Windows 10
> - **How installed?**: attempting installer from bin listed at Parity.IO web site - no joy
> - **Are you fully synchronized?**: 
> - **Which network are you connected to?**: 
> - **Did you try to restart the node?**:

**Comment by 5chdn** [comment]
:man_facepalming: 

I'm sorry, we messed up our website download-section :)

On it.

**Comment by 5chdn** [comment]
Fixed
