### ISSUE TITLE
Careless user didn't properly escape when handling stdout

### ISSUE THREAD

**Issue by jhallbox** [paritytech/parity#7681]
Debian 4.8.4-1

Parity/v1.8.6-stable-1eab85a-20180117/x86_64-linux-gnu/rustc1.23.0

.deb install, fully synced
------------------

Was grepping parity --help and forgot to escape thus breaking the pipe.

-- BAD 

me@mine:~/googleskunkworks.co$ parity --help |grep "--no"
grep: option '--no' is ambiguous; possibilities: '--no-filename' '--no-messages' '--no-group-separator'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

====================

stack backtrace:
   0:     0x55f4d8f6326c - <no info>

Thread 'main' panicked at 'Error writing Error to stdout: Error { repr: Os { code: 32, message: "Broken pipe" } }', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

-- GOOD

me@mine:~/googleskunkworks.co$ parity --help |grep "\--no"

**Comment by jhallbox** [comment]
This forum escaped my escape.

**Comment by 5chdn** [comment]
@axelchalon is this a bug?

**Comment by jhallbox** [comment]
I won't tell you if it is a bug or not, however the problem is common and
the exception error asks for it to be reported as a bug.

**Comment by tomusdrw** [comment]
It's a bug in Rust see: https://github.com/rust-lang/rust/issues/24821

Duplicate of #4295

**Comment by jhallbox** [comment]
Ok so it seems to be a problem with Rust error handling when stdout is broken & some print statements are used.

Seems possible to fix in parity by changing how those print calls are made.
