### ISSUE TITLE
sync stoped

### ISSUE THREAD

**Issue by Fcgreco** [paritytech/parity#7684]
See below

**Comment by Fcgreco** [comment]
> I'm running:
> Parity/1.8.6/1.22.1/ma
> MacOS: High Sierra
> Via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

It had been syncing for 1 full day but Parity stopped sync at 74,68% warp restore. Today I’ve quit and started it again but it stopped sync again, but now on 21,36% warp restore. I have Ether in my wallet Parity but isn’t showed to me, until node get 100% synced. What's the problem? There is another way to show my ether funds in Parity Wallet?

**Comment by 5chdn** [comment]
Yes, warp sync is not feasible on Ethereum anymore. Just leave it syncing normally.

Meanwhile, you can use https://wallet.parity.io to recover and send transactions.

**Comment by Fcgreco** [comment]
Thank U!
I've just click on the wallet link above, It is asking me to create new account. I need to create a new account?
Because I have already one... and this account (wallet), that I was syncing, is the same that I sent some Ether. What is the procedures to recover these Ethers

**Comment by 5chdn** [comment]
You can import your old one after creating a new account.

**Comment by Fcgreco** [comment]
Thanks, I did it.
Where can I import the old account funds? I've tried to do but without success, I'm just seem the wallet in the Addressbook... I'm trying here: GETH KEYSTORE, but it shows me: There are currently no importable keys available from the Geth keystore, which are not already available on your Parity instance

Sorry I'm new on Parity. Thank's for help!

**Comment by 5chdn** [comment]
Just click JSON and import your local wallets.
