### ISSUE TITLE
Parity only connecting to 2-3 peers out of 25 set in settings.

### ISSUE THREAD

**Issue by MichaelA2014** [paritytech/parity#7690]
_Before filing a new issue, please **provide the following information**._

> I'm running: Windows 7 x64. 
>
> - **Which Parity version?**: Parity/1.8.7/1.23.0/wi
> - **Which operating system?**: Windows 
> - **How installed?**: via installer downloaded from GitHub
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

I updated parity to the latest release from GitHub.  1.8.7 stable. In older version I saw connected to 20-25 out of 25 peers. In this version I am only connected to 1 to 3 peers and synching is soo slow. Is there anything in settings I need to change to boost the speed a bit? 

Thank you
![parity_slow](https://user-images.githubusercontent.com/15806130/35363135-1db6165c-012e-11e8-899c-286d89e1d36f.png)

**Comment by ronix73** [comment]
Stop Parity then just remove `nodes.json` from chains/ethereum/network/nodes.json

**Comment by roninkaizen** [comment]
![better seed](https://user-images.githubusercontent.com/17592883/35489492-c0f0d340-0497-11e8-8dbe-7ec93b63e893.png)

and try using the mentioned buttons i a way that seems appropriate for your needs.

**Comment by 5chdn** [comment]
This should be fixed in 1.8.9 and 1.9.2, please report back if this still occurs.

**Comment by drandreaskrueger** [comment]
> This should be fixed in 1.8.9 and 1.9.2

Could this possibly be the same problem that we see over there? --> https://github.com/energywebfoundation/energyweb-client/issues/24#issuecomment-399896244

They seem to have forked from parity 1.8.0 ...

**Comment by 5chdn** [comment]
most likely. :)
