### ISSUE TITLE
error: Could not compile `protobuf` during installation with cargo

### ISSUE THREAD

**Issue by nsvdev** [paritytech/parity#7692]
Hello.

Uname -a: `linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux`

I've tried to install parity like that:
`curl https://sh.rustup.rs -sSf | sh`
`git clone https://github.com/paritytech/parity`
`cd parity`
`~/.cargo/bin/cargo build --release --verbose`

And at thet last step this error occured:

`error: Could not compile "protobuf".`
`Caused by:`
`  process didn't exit successfully: "rustc --crate-name protobuf /root/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-1.4.1/src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C panic=abort -C metadata=de3d3d079f1ec76c -C extra-filename=-de3d3d079f1ec76c --out-dir /root/parity/target/release/deps -L dependency=/root/parity/target/release/deps --cap-lints allow" (signal: 9, SIGKILL: kill)
`

What am I doing wrong?

**Comment by guanqun** [comment]
You probably need to install protobuf compiler

```
apt-get install protobuf-compiler
```

You can see more instruction here for this crate: https://github.com/stepancheg/rust-protobuf

**Comment by 5chdn** [comment]
Please check the README or the Wiki for installation instructions and required dependencies.
