### ISSUE TITLE
docs dead link (Deploying-DApps-to-Parity-Wallet)

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#7693]
try this:
* https://paritytech.github.io/wiki/
  * Developing
    * Deploying Dapps to Parity Wallet

link is dead:

https://paritytech.github.io/wiki/Deploying-DApps-to-Parity-Wallet

**Comment by drandreaskrueger** [comment]
for the GUI point and click steps

parity ui --> contracts --> watch --> 

* contract_address
* contract_name 
* ABI

... is there actually an easy (scriptable) way?

I want to add 16 contracts in one go, and provide such a prepared parity client to an enduser.

Thanks

**Comment by 5chdn** [comment]
Sorry it is: https://paritytech.github.io/wiki/Deploying-Dapps-to-Parity-Wallet

**Comment by drandreaskrueger** [comment]
@5chdn thx

what I [asked up there](https://github.com/paritytech/parity/issues/7693#issuecomment-360451212), can it be done? How?

Thanks

**Comment by 5chdn** [comment]
> I want to add 16 contracts in one go, and provide such a prepared parity client to an enduser.

Not that I am aware of.
