### ISSUE TITLE
ERC20 tokens show up sometimes, but usually they dont

### ISSUE THREAD

**Issue by flartels** [paritytech/parity#7696]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.7.13
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ... Dont know the answer
> - **Did you try to restart the node?**: no / yes How do I restart the node? I did switch parity on/off and tried multiple versions

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have about 15 ERC20 tokens in my account, but 95% of the times these tokens do not show up when I start Parity. In etherscan I see all the tokens in the account, they are just now showing and I am not able to transfer them. This has been an issue for at least a month now. Please help

**Comment by ronix73** [comment]
I have same problems with over 4 ETH address.  I use Parity 1.9.0
When I open Parity is like a lottery (show or not). How we can fix this issues ?

**Comment by gaia** [comment]
same problem on 1.9.0. Tokens never show up.

**Comment by Sceat** [comment]
Same here, no token at all in 1.9.0

**Comment by newmzy** [comment]
Me too, using 1.8.7 or 1.9.0 Windows 10 X64.

I guess if I want to transact tokens I will have to import a .json of my account into myetherwallet.com - that's pretty sucky. Was working fine a week ago.

**Comment by 5chdn** [comment]
Please, use v1.8.7-stable if you heavily rely on the Parity Wallet.

Please, use https://wallet.parity.io if you have issues with a local node.

Please, prepare any other alternatives you can think of to transact Ether/Tokens/Assets or want to interact with contracts. We will remove the wallet as you know it soon and discontinue to run the public nodes. Parity 1.10 will not come with a built-in wallet anymore, and versions after 1.11 and beyond will start shipping with a very minimal light-compatible wallet.

Meanwhile, you can report issues and discuss your experiences at the external repository for the wallet dApp here: https://github.com/Parity-JS/dapp-wallet
