### ISSUE TITLE
Parity connecting to very few peers

### ISSUE THREAD

**Issue by ddorgan** [paritytech/parity#7697]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.x - happens on version from 1.8.2 to 1.8.6 
> - **Which operating system?**: Linux
> - **How installed?**: deb package
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

Sometimes parity is only connected to a small number of peers, maybe 1 or 2. Sometimes it has no connections at all. I tried upgrading parity to the latest (1.8.7) but the issue continues. 

Once I remove the file chains/ethereum/network/nodes.json then the issue seems to go away. The nodes.json also has quite a lot of entries (+175k). I can provide an example if needed.

Once the file is removed the node will sync as expected, reaching 25 peers.

Expected behaviour is that a normal sync can happen without having to remove this file.

**Comment by roninkaizen** [comment]
would plan a job,
stopping parity every 6 hours, 
wait until done,
deleting that the nodes.json file,
restarting parity
end

**Comment by nueverest** [comment]
I had the same issue on upgrading to 1.9.

Deleting nodes.json fixed it for me.

**Comment by 5chdn** [comment]
#7716 should have addressed this (hopefully).
