### ISSUE TITLE
Origin: null causes unexpected CORS rejection

### ISSUE THREAD

**Issue by dpyro** [paritytech/parity#7698]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.8.7-stable-29dc3ca-20180123/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**: MacOS
> - **How installed?**: Docker
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes

Metamask sends the non-configurable `Origin: null` header when accessing a JSON-RPC. This results in the response: `Origin of the request is not whitelisted. CORS headers would not be sent and any side-effects were cancelled as well.`

With `cors = "*"`
Accepts all Origin including empty *except* `Origin: null`.
With `cors = "all"`
Accepts all Origin including empty *except* `Origin: null`.
With `cors = "null"`
Accepts *only* `Origin: null`.

**Comment by tomusdrw** [comment]
Use `cors = "all,null"`
