### ISSUE TITLE
VM trace caching

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#770]
Eventually, optimise VM tracing through an LRU memoised disk-backed cache.

**Comment by 5chdn** [comment]
This _optimization_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still realistic to implement it _some day maybe_. If so, please add an assignee and a milestone, or close otherwise.

**Comment by gavofyork** [comment]
meh.
