### ISSUE TITLE
Contract 0xfec94608dea1f3609e4a93e56e01477d8a86de46 created twice?

### ISSUE THREAD

**Issue by jakublipinski** [paritytech/parity#7700]
While browsing traces generated by parity I encountered an interesting case:

**Contract [`0xfec94608dea1f3609e4a93e56e01477d8a86de46`](https://etherscan.io/address/0xfec94608dea1f3609e4a93e56e01477d8a86de46) was created twice.** 

First time, in the transaction: [`0xc0d8d11c5da64e025ac0bb0cc286ede65c2a0b7afeeb455f04d6479cc98edb7a`](https://etherscan.io/vmtrace?txhash=0xc0d8d11c5da64e025ac0bb0cc286ede65c2a0b7afeeb455f04d6479cc98edb7a&type=parity). The transaction failed with `Out of gas` but accroding to the traces the contract was successfuly created. 

Second time, the same contract with the same code was created in the transaction: [`0x9c3ef34611bd24e254b2b6f339e2f196a57042e8261c069af944248d982c67b4`](https://etherscan.io/vmtrace?txhash=0x9c3ef34611bd24e254b2b6f339e2f196a57042e8261c069af944248d982c67b4&type=parity).

From [what I understand](https://ethereum.stackexchange.com/questions/13458/is-there-any-way-to-re-deploy-to-the-same-address-a-contract-that-wasnt-deplo/13459#13459) the contract got the same address because it was created within another contract. The contract address is generated from the creator contract address and its nonce. Since the previous creator contract transaction ended up with `Out of gas` the nonce was not increased and thus the same contract address.

Since `Etherscan` incorrectly (in my opinion) [shows that the contract was created in the transaction which failed](https://etherscan.io/address/0xfec94608dea1f3609e4a93e56e01477d8a86de46) with `Out of as` I contacted them and explained the issue. Their answer was:

> According to the Parity Trace, the contract creation was successful for the step https://etherscan.io/vmtrace?txhash=0xc0d8d11c5da64e025ac0bb0cc286ede65c2a0b7afeeb455f04d6479cc98edb7a&type=parity
>
>Unless the parity trace is invalid the data we are showing is the correct one.
>
>There is a possibility of a rare case like the one you brought forward.
>
>As a free Blockexplorer service, we can only provide and display information on transactions that occur on the Ethereum Blockchain. If you need further clarification of this nature, you would need to turn to Geth or Parity forum/channels.

What really happened? Was the contract really created in the first transaction? Shouldn't it be reverted? Does `Etherscan` show it correctly? What would happen if in the second transaction the contract is generated with a different code? What would happen with its storage?

(The issue was originally [reported at Ethereum StackExchange](https://ethereum.stackexchange.com/questions/36964/same-contract-created-twice-0xfec94608dea1f3609e4a93e56e01477d8a86de46) but moved here since it seems to be parity related)

**Comment by 5chdn** [comment]
It's not a Parity question, the answer on SE seems appropriate.
