### ISSUE TITLE
Signing a transaction with ledger nano s not possible on parity 1.9

### ISSUE THREAD

**Issue by gbunea** [paritytech/parity#7701]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.0
> - **Which operating system?**:  MacOS 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:   yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Impossible to sign a transaction with ledger nano S on parity 1.9.0 BETA. 

<img width="626" alt="screen shot 2018-01-26 at 21 57 26" src="https://user-images.githubusercontent.com/15690364/35459059-695af96e-02e7-11e8-8a9c-5a7f61839966.png">

**Comment by sorccu** [comment]
I am also experiencing this issue. I can verify that the parameters and description provided by the original reporter are accurate.

**Comment by 5chdn** [comment]
Please, use v1.8.7-stable if you heavily rely on the Parity Wallet.

Please, use https://wallet.parity.io if you have issues with a local node.

Please, prepare any other alternatives you can think of to transact Ether/Tokens/Assets or want to interact with contracts. We will remove the wallet as you know it soon and discontinue to run the public nodes. Parity 1.10 will not come with a built-in wallet anymore, and versions after 1.11 and beyond will start shipping with a very minimal light-compatible wallet.

Meanwhile, you can report issues and discuss your experiences at the external repository for the wallet dApp here: https://github.com/Parity-JS/dapp-wallet
