### ISSUE TITLE
2PR, BET, HSC, ROS, WIT tokens appearing in all my accounts

### ISSUE THREAD

**Issue by jonbesga** [paritytech/parity#7702]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.8.7-stable-29dc3ca2d-20180123/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**:  Linux - ArchLinux
> - **How installed?**: via installer (pacman)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Some weird 2PR, BET, HSC, ROS, WIT tokens are appearing in all my accounts. Every time I create a new account, these tokens appears with huge amounts of every token.

**Comment by roninkaizen** [comment]
chrome?
if so deactivated all extensions?

**Comment by 5chdn** [comment]
Please, use v1.8.7-stable if you heavily rely on the Parity Wallet.

Please, use https://wallet.parity.io if you have issues with a local node.

Please, prepare any other alternatives you can think of to transact Ether/Tokens/Assets or want to interact with contracts. We will remove the wallet soon and discontinue to run the public nodes.
