### ISSUE TITLE
Parity climbs to max ram usage, takes hours to stop (e.g. after control-c), multiple fresh installs

### ISSUE THREAD

**Issue by Raekye** [paritytech/parity#7705]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: [1.9.0-beta](https://github.com/paritytech/parity/releases/tag/v1.9.0), previously 1.8.6-beta (still had issue)
> - **Which operating system?**: Windows
> - **How installed?**: via installer, HDD drive (not `C:`)
> - **Are you fully synchronized?**: no (previously was, presumably will if I give it a LOT of time)
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Expected behavior**: 

- After asking Parity to quit (e.g. control-c or through the taskbar), exits cleanly in a short amount of time (1-2 minutes max)
- Parity doesn't use ~14-16 GB of ram when `cache_size` is 1024-4096

---
**Update 1**: I did a clean sync setting `db_path` instead of using a symlink. At block 4,880,237 and slowly syncing, but RAM and max and after trying to quit it (computer lagging hard) still waiting for it to "finish"

**Update 2**: Left it running overnight. Still not fully synced, but "only" took 3 hours for finishing work. Ram usage still maxing out (and staying maxed for the 3 hours it takes to finish work).

**Update 3**: Tried running nodes on a linux server, both 1.9.0-beta and 1.8.7-stable. After control-c, "Finishing work" completes in a short amount of time (under ~10-15s). Is this a common/known windows issue?

---
I start Parity via the command line/bat file - just `parity.exe` in the folder I installed. Within an hour, my computer is extremely sluggish and I can see ram is maxed (have 16 GB, reaches max even with no other programs). If I control-c kill the program, it gets "stuck" on "Finishing work, please wait..." If I leave the parity running for an ~hour or more, it takes 6+ hours to "finish":

- if I try to quit before the second "syncing block" message, it's instant.
- if I try to quit after the second "syncing block" message, it takes a few seconds
- if I try to quit after a minute, it takes ~5 minutes

As for versions:

- While on 1.7.11-stable, I was completely unable to sync, despite multiple re-installs and wiping the DB, and was also experiencing this type of issue (extremely slow to finish work, and unbounded memory usage).
- I did a fresh warp sync on 1.8.6-beta - still had this issue **before full syncing, after fully syncing, and catching up after fully syncing**
- Upgraded to 1.9.0-beta today and still having this issue, so reporting

Parity is installed on a different drive - my HDD, and I have symlinked `%UserProfile%\AppData\Local\Parity\Ethereum` to a folder on said HDD drive. I know SSD is better but I have limited space on my SSD

I do not notice any abnormal or error logs; what should I try to do to gather more information?

---
Here is my `config.toml`. Previously, I had `cache_size = 4096`. Lowering to 1024 had no noticeable effects
```
[parity]
mode = "passive"
light = false

[network]
min_peers = 50
max_peers = 100
snapshot_peers = 25

[footprint]
tracing = "off"
pruning = "fast"
cache_size = 1024
db_compaction = "hdd"
```

**Comment by debris** [comment]
I believe this was solved by @andresilva some time ago. I'm closing it
