### ISSUE TITLE
Blocked connection from chrome extension

### ISSUE THREAD

**Issue by xtien** [paritytech/parity#7706]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.0 beta
> - **Which operating system?**:  Linux ubuntu 16.04 LTS
> - **How installed?**: via .deb installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I keep getting "Blocked connection from chrome-extension://himekenlppkgeaoeddcliojfddemadig using invalid token." on 1.9.0 beta I just installed. I restarted the node, didn't help. Closing the parity tab in chrome helped. 
The log I see shows the x/50 peer lines, but no "Imported" lines, like I saw in 1.8.7.

**Comment by 5chdn** [comment]
Yes, that's the chrome browser extension trying to make connections to your parity node.
