### ISSUE TITLE
UI top bar shows incorrect sync info

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/parity#7709]
> I'm running:
>
> - **Which Parity version?**: 1.9
> - **Which operating system?**: MacOS
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

Right after upgrading to 1.9.0-beta node is not warp-syncing:
> [2018-01-27 21:31:15] Syncing #4889823 5765…4881 4 blk/s 828 tx/s 30 Mgas/s 0+ 997 Qed #4890821 25/25 peers 10 MiB chain 119 MiB db 176 MiB queue 46 MiB sync RPC: 3 conn, 1 req/s, 66 µs
> [2018-01-27 21:31:05] Syncing #4889778 9859…9575 4 blk/s 929 tx/s 32 Mgas/s 0+ 1041 Qed #4890821 24/25 peers 6 MiB chain 122 MiB db 183 MiB queue 46 MiB sync RPC: 3 conn, 16 req/s, 62 µs

but UI consistently shows "55.26% warp restore" in the top bar (the percentage number isn't changing).

**Comment by bjornwgnr** [comment]
Restart of node triggered a fresh warp-sync and top bar info is now correct.

**Comment by 5chdn** [comment]
https://github.com/Parity-JS/dapp-wallet :)
