### ISSUE TITLE
Stage 4 Block Verification failed 

### ISSUE THREAD

**Issue by lsaether** [paritytech/parity#7713]
On Parity 1.9.0-beta running on Ubuntu 17.10, when trying to stay up to sync with the Kovan testnet I keep getting an error that looks like this:
```
Stage 4 block verification failed for #5612476 (ed7a…d592)
Error: Block(TemporarilyInvalid(OutOfBounds { min: None, max: Some(1517163384), found: 1517163388 }))
```

I've tried restarting the node a few times, each time it will sync properly for a short while then throw this error and stops syncing new blocks. I've tried deleting my kovan/db/ folder, and double checking that my time is in sync but neither of those things provided a solution.

**Comment by 5chdn** [comment]
Yes we messed this up. Stay tuned for 1.9.1 or downgrade to 1.8.7 - thanks.
