### ISSUE TITLE
"Password is not correct" after restore

### ISSUE THREAD

**Issue by AndrazP** [paritytech/parity#7714]
1.9.0-Beta, Mac OS, from binary, fully synchronized. Firefox and Chrome

Tried several times to restore my password following this steps:
https://ethereum.stackexchange.com/questions/30244/lost-password-on-parity-i-do-have-the-recovery-12-word-phrases-thankfully
After every restore the application still reports "This password is not correct". Tried different passwords. Password is entered correctly.

**Comment by 5chdn** [comment]
Please, use v1.8.7-stable if you heavily rely on the Parity Wallet.

Please, use https://wallet.parity.io if you have issues with a local node.

Please, prepare any other alternatives you can think of to transact Ether/Tokens/Assets or want to interact with contracts. We will remove the wallet as you know it soon and discontinue to run the public nodes. Parity 1.10 will not come with a built-in wallet anymore, and versions after 1.11 and beyond will start shipping with a very minimal light-compatible wallet.

Meanwhile, you can report issues and discuss your experiences at the external repository for the wallet dApp here: https://github.com/Parity-JS/dapp-wallet
