### ISSUE TITLE
Tokens Vanish after Drive Transfer

### ISSUE THREAD

**Issue by ZigzagoonBalloon** [paritytech/parity#7722]
_Before filing a new issue, please **provide the following information**._

> I'm running: 
> - **Which Parity version?**: 1.8.7/1.9.0 beta (Tried both)
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum. Foundation
> - **Did you try to restart the node?**: yes

I recently moved parity's data from my SSD to my HDD. After resyncing, the storj that I am using the wallet is not showing up. Also, some Penis (?) was showing before and now it is gone, not that I care about that. The address and account both appear to be showing up. In 1.9.0 the icon for ethereum stopped loading as seen in the screenshot.

My address: https://etherscan.io/address/0x00F1110873Da6e8F80D072A29605289e88FA61ED#tokentxns

![screenshot 2018-01-30 02 13 57](https://user-images.githubusercontent.com/29400797/35517812-a662176a-0563-11e8-8a69-54e97ff4cd16.png)
![screenshot 2018-01-30 02 14 05](https://user-images.githubusercontent.com/29400797/35517813-a6ad750c-0563-11e8-955f-082ba4ffac47.png)
![screenshot 2018-01-30 02 16 20](https://user-images.githubusercontent.com/29400797/35517814-a6dda31c-0563-11e8-9bae-606799d7ad41.png)

**Comment by HappyMaster** [comment]
Same issue, tokens disappeared from all accounts without doing anything. In the console have `balances::fetchTokensBalances TypeError: Cannot read property 'gt' of undefined`.

**Comment by 5chdn** [comment]
fixed in #7742
