### ISSUE TITLE
UI: Node Status Dapp / Date is no longer visible next to the Best Block

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#7724]
![image](https://user-images.githubusercontent.com/738724/35527396-e6fda214-052a-11e8-988f-475babf64681.png)

I have obviously lots of blocks to catch up. In previous versions, we could see the time + date of the latest block. Currently, we can see only the time, which, without date, is rather useless.

This is obviously a minor issue :)

> I'm running:
>
> - **Which Parity version?**: Parity v1.9.0-20180108 unstable
> - **Which operating system?**: Windows / **MacOS** / Linux
> - **How installed?**: via installer / homebrew / binaries / **from source**
> - **Are you fully synchronized?**: **no** / yes
> - **Which network are you connected to?**: **ethereum** / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / **yes**

**Comment by 5chdn** [comment]
Hey @chevdor - Please, use v1.8.7-stable if you heavily rely on the Parity Wallet. This will enable the old status dashboard.

We will remove the wallet as you know it soon and discontinue to run the public nodes. Parity 1.10 will not come with a built-in wallet anymore, and versions after 1.11 and beyond will start shipping with a very minimal light-compatible wallet.
