### ISSUE TITLE
Alternative to Parity for ETH wallets and ERC-20 tokens

### ISSUE THREAD

**Issue by newmzy** [paritytech/parity#7725]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.7
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: no

In another post elsewhere one of the members of your team stated that future versions of Parity will not support full nodes, or be suitable for use as ETH wallets or for storing ERC-20 tokens. Please suggest an alternative so I may move my ETH and tokens elsewhere. I guess I could use Eidoo wallet for tokens and my Ledger Nano S for ETH. Where is the public announcement about these future dramatic changes to Parity.

**Comment by folsen** [comment]
I'm pretty sure you have misunderstood something. Parity will always support full nodes. We will be focusing a lot on stabilizing light-client and providing a light-client wallet in the future that is more suitable for the average user that just wants to manage ETH and tokens and not actually interact with DApps.

There are many good alternatives though, especially if you have a Ledger Nano, MyEtherWallet for instance.

**Comment by rphmeier** [comment]
@jamespic we do fully intend to support the same RPC interfaces as currently. The only things that will be changing are the extraction of the UI to a community-managed organization (which provides look-and-feel primitives as well as development libraries for others to create DApps) and a stronger focus on the light client for users.
