### ISSUE TITLE
Parity Mac Closes immediately after opening

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#7728]
I installed the OSX installer. On completing, it opened a browser page to
http://127.0.0.1:8180/ -- which was unexpected!

Then I tried running parity on command line, nothing. 

I run "Parity Ethereum.app" from spotlight and I see an icon flash in the OSX toolbar at top for 1 second, then closes.

**Comment by AyushyaChitransh** [comment]
As discussed previously in #7143 you might try running parity from `/Applications/Parity\ Ethereum.app/Contents/MacOS/parity`

Currently you are not able to run parity most probably because parity does not exist in your `$PATH`.

**Comment by awbacker** [comment]
I had this, upgraded from 1.7 and there was a key in the config.toml that the new version didn't like.  The UI version shows now errors.  Running from the command line should let you see enough output to figure out what crashed.

**Comment by quantumproducer** [comment]
I've managed to get the CLI working through compiling source

**Comment by 5chdn** [comment]
You can also use homebrew.
