### ISSUE TITLE
Syncing to testnet

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#7729]
What is the latest testnet to sync to? How can I sync with parity?

**Comment by AyushyaChitransh** [comment]
You can sync to kovan testnet, which is the PoA testnet running for parity.

As you mentioned earlier in #7728 you are unable to use parity CLI, you can try with this:

`/Applications/Parity\ Ethereum.app/Contents/MacOS/parity --chain kovan`

**Comment by quantumproducer** [comment]
Thank you
