### ISSUE TITLE
What does mean "In queue: Future" in the "Your local transactions"?

### ISSUE THREAD

**Issue by bluebu** [paritytech/parity#7730]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.10.0-20180119
> - **Which operating system?**: Linux  Centos 7.4
> - **How installed?**: via installer from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**:   foundation
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When the node run about 2 hours, there are always some transactions to be shown "In queue: Future",  what does it mean?  
After restart,  they are still "In queue: Future",  will these transactions go on to be mined by other nodes?
Or does it mean these transactions are error transactions, can I delete them?

![1517272062611](https://user-images.githubusercontent.com/277465/35541792-77adbb34-0597-11e8-93cb-74d6a2b06941.jpg)

**Comment by AyushyaChitransh** [comment]
Transactions done from an account are sequentially numbered, and these sequence numbers are called nonce. When some account sends a transaction of a higher sequence number, that transaction is said to be in future.

If you want to delete those transactions, you can use `parity --no-persistent-txqueue` as described on [ethereum.stackexchange](https://ethereum.stackexchange.com/a/17764/16048)

**Comment by bluebu** [comment]
Cool, @AyushyaChitransh!  
thx for your reply,  quite clear, I have solved my problem

**Comment by bittylicious** [comment]
We are finding this happening alot, often blocking many transactions afterwards. We don't specify a gas price (just leave it up to Parity) and definitely not a nonce, yet we see this regularly. Any ideas why?

**Comment by 5chdn** [comment]
Nonces are a known annoyance but there is not much the client can do about this if a transaction is not mined - for instance - blocking all following transactions, this has to be watched carefully in a 2nd layer application and handled appropriately.

**Comment by Tbaut** [comment]
@bittylicious as discussed in the chat, please open a new issue as soon as you get a trace of these "stuck transactions" to see if this is a bug.

**Comment by partyspy** [comment]
Looks like a bug. But adding `--no-persistent-txqueue` did resolve the transfer-stucking problem.
