### ISSUE TITLE
Pub/Sub newHeads is not compatible with geth

### ISSUE THREAD

**Issue by tjade273** [paritytech/parity#7731]
> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: all
> - **Did you try to restart the node?**: yes

The Geth ethclient.go RPC client sends an empty dictionary as the second argument to `eth_subscribe` with `newHeads`.

https://github.com/ethereum/go-ethereum/blob/762f3a48a00da02fe58063cb6ce8dc2d08821f15/ethclient/ethclient.go#L298

The Parity server expects no second argument, leading to an error:
> "Expected no parameters."

https://github.com/paritytech/parity/blob/e95b09348386d01b71901365785c5fa3aa2f7a6d/rpc/src/v1/impls/eth_pubsub.rs#L263

The documentation includes examples with and without the empty dictionary.  

https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB

**Comment by debris** [comment]
Closing, cause both clients are now compatible
