### ISSUE TITLE
No space left on device IO error (please report this)

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#7733]
stack backtrace:
   0:        0x10c86c30e - backtrace::backtrace::trace::h3ce07ad9d77bd61b
   1:        0x10c86c34c - backtrace::capture::Backtrace::new::h90d1a5d85090e3fc

Thread 'IO Worker #2' panicked at 'DB flush failed.: Error(Msg("IO error: No space left on deviceWhile appending to file: /Users/quantum/Library/Application Support/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/overlayrecent/db/025195.log: No space left on device"), State { next_error: None, backtrace: None })', src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6

**Comment by 5chdn** [comment]
Please free up some disk space! :)
