### ISSUE TITLE
invalid type: string "null", expected a sequence for key `rpc.cors`

### ISSUE THREAD

**Issue by naddison36** [paritytech/parity#7734]
> - **Which Parity version?**: 1.9.0
> - **Which operating system?**: MacOS
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: my own dev chain
> - **Did you try to restart the node?**: yes

After upgrading to Parity 1.9.0 I get the following error when I start partity
``invalid type: string "null", expected a sequence for key `rpc.cors` ``

This is coming from my config
```
[rpc]
disable = false
port = 8646
interface = "local"
cors = "null"
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]
```

My config is based off the Parity wiki https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml which uses the config of `cors = "null"`

What should the toml config be for cors if it is not needed?

I can comment out `cors = "null"` and my node starts ok.

Expected behaviour: The default [config.toml](https://github.com/paritytech/parity/wiki/Configuring-Parity#default-configtoml) file listed on the Parity wiki should be usable with Parity 1.9.0.

**Comment by vincentserpoul** [comment]
agree on the docs to be changed.
The valid value would be 
```
cors= []
```
as cors is not anymore a string (which didn't really makes sense anyway)

**Comment by 5chdn** [comment]
Feel free to submit a PR: https://github.com/paritytech/wiki/blob/master/Configuring-Parity.md#default-configtoml

**Comment by naddison36** [comment]
Raise PR https://github.com/paritytech/wiki/pull/14

**Comment by 5chdn** [comment]
Thanks!
