### ISSUE TITLE
Parity dev chain spec does not support Byzantium

### ISSUE THREAD

**Issue by vincentserpoul** [paritytech/parity#7735]
> I'm running:
>
> - **Which Parity version?**: 1.8.x, 1.9.x.
> - **Which operating system?**: MacOS & Linux
> - **How installed?**: docker
> - **Are you fully synchronized?**: dev
> - **Which network are you connected to?**: dev
> - **Did you try to restart the node?**: yes

**steps to reproduce**
To reproduce: deploy a contract with not enough gas and call getTransactionReceipt on it.
when you call getTransactionReceipt, instead of having status 0x00 or 0x01 according to [stackoverflow](https://ethereum.stackexchange.com/questions/28077/how-do-i-detect-a-failed-transaction-after-the-byzantium-fork-as-the-revert-opco) following byzantium), you get a null status.

**actual** 
transactionReceipt.status: null
**expected behavior**
transactionReceipt.status: 0x00

**Comment by AyushyaChitransh** [comment]
I faced this bug previously and it was corrected by using `eip658Transition` in genesis file. #6887 reports similar behavior.

**Comment by vincentserpoul** [comment]
should the dev genesis include this?

**Comment by AyushyaChitransh** [comment]
I think that dev genesis should also include that to show correct behavior. I run my private network and have to include this in my genesis file to get correct status.

**Comment by tomusdrw** [comment]
Seems like a bug in spec file indeed.

**Comment by 5chdn** [comment]
What is this?

https://github.com/paritytech/parity/blob/master/ethcore/res/instant_seal.json#L29

A registrar? It conflicts with the byzantium built-ins.

**Comment by tomusdrw** [comment]
@5chdn seems so, although I think `registrar` address is still missing in the spec file for this to work.

**Comment by 5chdn** [comment]
ok, I'll give it a try
