### ISSUE TITLE
Parity floater is not working in dApps

### ISSUE THREAD

**Issue by shubhamy** [paritytech/parity#7736]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity v1.9.0-20180125 beta
> - **Which operating system?**: MacOS
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Seeing this instead of floating parity bar.

<img width="228" alt="screen shot 2018-01-30 at 2 02 38 pm" src="https://user-images.githubusercontent.com/6676622/35555790-51b7eb50-05c6-11e8-983f-ee92265e28b6.png">

**Comment by shubhamy** [comment]
The screenshot is from etherdelta.

**Comment by shubhamy** [comment]
Back then, I opened up the parity and went to etherdelta.com. There I was seeing this.

**Comment by Tbaut** [comment]
I get it, you were using the web3 browser. This is not possible anymore with >v1.9. It is now advised to use the chrome plugin: https://chrome.google.com/webstore/detail/parity-ethereum-integrati/himekenlppkgeaoeddcliojfddemadig?hl=fr
