### ISSUE TITLE
Can Parity be used with Solidity remix or IntelliJ IDEA?

### ISSUE THREAD

**Issue by aditbhrgv** [paritytech/parity#7737]
_Before filing a new issue, please **provide the following information**._

> I'm running:
Which Parity version?: 1.8.4
Which operating system?: Linux
How installed?: via installer
Are you fully synchronized?: no
Did you try to restart the node?: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi, 

1. I want to use Solidity Remix online browser or INTELLJ  with Parity and not the inbuilt solidity editor within Parity.
How can I use it ? 

 2. I also want to use 2 miners with Parity. I am using ethminer and stratum to do POW mining  but it allows to specify only one miner, not multiple. 
How can I specify multiple miners in a test network   ?

Thanks in advance

**Comment by 5chdn** [comment]
1. Parity does not fully support all required RPC APIs for Remix, see https://github.com/ethereum/remix/issues/754

2. Just run two instances of ethminer pointed at either of the Parity nodes.
