### ISSUE TITLE
Parity transactions stuck at 6 months ago

### ISSUE THREAD

**Issue by Joaoha** [paritytech/parity#7738]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.0-20180125 beta
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum FOUNDATION
> - **Did you try to restart the node?**: yes

I've been using parity 1.7 for a very long time, last week my token balances stopped being shown next to the ETH balance, as they normally do.
I thought that it would recover as I've noticed sometimes that the tokens would not show until a certain amount of time would pass after starting the wallet.

After a few days with no balance update. I decided to upgrade and when to version 1.8 then I noticed that my transaction log was only showing transactions from 6 months ago. No recent transactions... 
again I thought it could be a bug and decided to upgrade again to version 1.9 stated above. 
Still no token balance and no recent transactions. 
Did multiple reboots in the meantime. 
Used different browsers. 
Tried a different PC with Parity version 1.6.
Deleted the chain and resyncd.

Still no Token balances and no Recent Transactions...
Etherscan.io shows token balances and transactions just fine for my address...

And Etherdelta also shows my balance properly.
Can anyone help with this please?

Thanks

Address: 0x14c66B69F1f3018BC67F7C6BEfdBB80869E2Cb85

**Comment by shuttle842** [comment]
I am experiencing same issue. currently running parity 1.9, 1.8.6 was working fine

i have tried to resync several times. my last transaction shown is 7 months old

**Comment by villesundell** [comment]
I am having the same: tokens not showing, and the last transaction is 6 months ago (was used last week), and with another account 2 months ago (was used 30 minutes ago).

I haven't updated recently. I am running: Parity/v1.8.5-beta-54bae9a-20171228/x86_64-linux-gnu/rustc1.22.1

This started just now, I recall it worked like 12 to 20 hours ago.

**Comment by a-boertien** [comment]
Same issue here.

Yesterday I had tokens showing against an account, now they are not showing.
My last transactions showing are from 2 years ago

Tried to upgrade to 1.9, then downgraded to 1.8.7 stable

**Comment by shubhamy** [comment]
Same issue here. Tokens are not showing against any account. It only shows ethereum.

**Comment by 5chdn** [comment]
Fixed in #7742
