### ISSUE TITLE
Can't verify parity account via sms or email - verification code is not sent.

### ISSUE THREAD

**Issue by udiromano** [paritytech/parity#7740]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.7.12-stable-f96d152-20180109/x86_64-macos/rustc1.22.1
> - **Which operating system?**:MacOS 
> - **How installed?**: via installer homebrew
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

**Actual behaviour**
Created parity account, transferred ether to it,
tried to verify the account via SMS or email,
Non of them worked, didn't get the token as expected.

**Expected behaviour**
Get the code via sms so you'll be able to feed it into the parity signer...

**steps to reproduce**
Install & fully sync parity
create an account
send some ether to it
try to verify
put your phone number in International format or email address
wait for verification code forever.

**Comment by 5chdn** [comment]
@ddorgan can you check the status?

**Comment by wnz99** [comment]
I had the same issue. The SMS code is not send. But it could be related to Kovan network rather than Parity as it seems that at present the only way to get Kovan Eth is posting on the Kovan faucet gitter.

**Comment by tomusdrw** [comment]
@udiromano Please send us an e-mail with your address to debug at admin@parity.io

@wnz99 SMS or Email verification is disabled. You need to verify the account on the mainnet and then use the same in the Kovan faucet.

**Comment by Tbaut** [comment]
Duplicates https://github.com/paritytech/parity/issues/8312
