### ISSUE TITLE
Tokens not visible in my Parity wallet

### ISSUE THREAD

**Issue by Eriksn1970** [paritytech/parity#7743]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.7.8.
> - **Which operating system?**: Windows 
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?** ...
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

hi I am using a Parity wallet. Untill yesterday all my tokens were visible in my wallet. per today not anymore. I have refreshed/removed cache/history. It's fully synced but still no tokens. Any advice?

**Comment by gaia** [comment]
see https://github.com/paritytech/parity/issues/7719

**Comment by 5chdn** [comment]
#7742 should address this, stay tuned.
