### ISSUE TITLE
parity crashes at first launch

### ISSUE THREAD

**Issue by tekspirit** [paritytech/parity#7750]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.1
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
just downloaded parity and ran it, to get
====================

stack backtrace:
   0:     0x7ff74ce299da - <no info>
   1:     0x7ff74ce29e73 - <no info>
   2:     0x7ff74ce28f46 - <no info>
   3:     0x7ff74ce3e5d3 - <no info>
   4:     0x7ff74cdb1172 - <no info>
   5:     0x7ff74cdb573d - <no info>
   6:     0x7ff74ce3ec62 - <no info>
   7:     0x7ff74ce3e882 - <no info>
   8:     0x7ff74ce53a80 - <no info>
   9:     0x7ff8a0138364 - BaseThreadInitThunk

Thread 'main' panicked at 'internal error: entered unreachable code', ethkey\cli\src/main.rs:221

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by 5chdn** [comment]
Please get the latest installer from our github release page and try again. The website was serving wrong binaries for some days. https://github.com/paritytech/parity/releases
