### ISSUE TITLE
internal error, entered uncreachable code

### ISSUE THREAD

**Issue by mecs13** [paritytech/parity#7760]
_Before filing a new issue, please **provide the following information**._

> I'm running: windows 10
>
> - **Which Parity version?**:  (downloaded jan 30
> - **Which operating system?**: Windows / 
> - **How installed?**: from parity .org, i received an app called "ethkey" 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum / ropsten / k
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

i clicked the app and expected it to run a gui but i got a window with an error reading: 

====================

stack backtrace:
   0:     0x7ff757d399da - <no info>
   1:     0x7ff757d39e73 - <no info>
   2:     0x7ff757d38f46 - <no info>
   3:     0x7ff757d4e5d3 - <no info>
   4:     0x7ff757cc1172 - <no info>
   5:     0x7ff757cc573d - <no info>
   6:     0x7ff757d4ec62 - <no info>
   7:     0x7ff757d4e882 - <no info>
   8:     0x7ff757d63a80 - <no info>
   9:     0x7ffcae601fe4 - BaseThreadInitThunk

Thread 'main' panicked at 'internal error: entered unreachable code', ethkey\cli\src/main.rs:221

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

i am runniung an MSI

**Comment by 5chdn** [comment]
Please download the latest installer from our github repository.

https://github.com/paritytech/parity/releases
