### ISSUE TITLE
Failures parameter in nodes.json blocks connection to some peers

### ISSUE THREAD

**Issue by shendenkov** [paritytech/parity#7761]
> I'm running:
>
> - **Which Parity version?**: 1.7.11, 1.7.12
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private PoW
> - **Did you try to restart the node?**: yes

I am not sure that it is a bug. Probably not.
I am working on private network with about 30 nodes. In nodes.json file failures always increases. And after some period of work my node not connect to these peers which have a lot of failures.
I can not understand what does these failures mean and what can I do to decrease them. Always delete this file it is not a good solution for me.
Can you suggest me how to decrease these failures? Thank you in advance.

**Comment by 5chdn** [comment]
We just had a fix merged, #7716 

If you have the time, could you test a latest build from master?

**Comment by shendenkov** [comment]
I started Parity 1.10.0-unstable without --reserved-peers option and after some time few of the bootnodes catch more failures than others and they hit the second half of the nodes.json file. When peers in this file has become more than 1024 then the last were deleted.
Also this file still save all found peers. Even from other networks. And as I understand if peers from small private network will be completely removed from nodes.json file then my node will never connects to them. Or I'm wrong?
Can a private network work without --reserved-peers option? And what exactly means 'attempts' and 'failures'?
