### ISSUE TITLE
API for ERC20 balance for public address?

### ISSUE THREAD

**Issue by hdelatorre** [paritytech/parity#7762]
* What's your Parity version?
Parity v1.9.0-20180125 beta

* What's your operating system and version?
MacOS high Sierra 10.13.3

* How did you install parity?
brew

* Is your node fully synchronized?
yes

* Did you try turning it off and on again?
yes

Is there an API to parity where I can send a random public address and it'll give me back the balance of ERC20 tokens associated with that address?

**Comment by 5chdn** [comment]
No, you would have to query the token registry entries for the address.

https://paritytech.github.io/wiki/Token-Registry
