### ISSUE TITLE
Tokens not showing or available for transfer, but show on etherscan

### ISSUE THREAD

**Issue by wakurth** [paritytech/parity#7764]
I was running parity 1.7 and stopped being able to see/view tokens I've purchased (e.g. I store ETH in my wallet, along with things like SUB). My ETH and other tokens have always showed up and have always been able to send tokens and see my balance. Now... all of a sudden... I can't. I then tried to upgrade to v1.9 .. which seemed to work just fine aside from the fact - still no tokens. For example SUB is an official registered token, so there shouldn't be any issues there (I read a number of posts about registered tokens). I also don't see my PRO or PNS tokens that are usually there (didn't before updating to 1.9 as well). Anyone know if there's an option I need to enable or something?

Edit:
Also, the ETH balance stays up to date, and by blocks seem to be synced up, but the Transactions page is 12 days old. It's like it can't call etherscan? No idea.

Edit:
Tried rolling back to Parity 1.7.13-stable, tried 1.8.7-stable ... all of them seem to have the same behavior

**Comment by AyushyaChitransh** [comment]
From gitter [comment](https://gitter.im/paritytech/parity?at=5a71a5bb6117191e61d70167)

> Token registry size met a threshold that causes all wallets to fail displaying token balances, fix in #7742

**Comment by 5chdn** [comment]
:)

**Comment by wakurth** [comment]
@5chdn - so, I cloned the repo. switched to the beta branch. compiled a release. and it still isn't showing tokens for me :/

**Comment by 5chdn** [comment]
yea you need to compile with `--no-default-features --features ui` to get the UI changes
