### ISSUE TITLE
EOS and BNT token balances zero

### ISSUE THREAD

**Issue by Thruxtonite** [paritytech/parity#7769]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**v1.9.0
> - **Which operating system?**Windows 10 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
Upgraded to v1.9.0 and also transfered 9113 EOS tokens into PARITY wallet. This was 3 days ago. Etherscan shows the transaction. The Parity wallet has no eos tokens and no BNT tokens which were stored in the wallet.
I have transferred Eth in and out of Parity wallet without problems.
Wallet address is
0x008B226fdC47dE4ADD766BB4D9e2D08d12DBf293

**Comment by 5chdn** [comment]
This is broken currently and fixed in #7742 - please stay tuned for the 1.9.1 release.
