### ISSUE TITLE
can not export state data with --at argument

### ISSUE THREAD

**Issue by wliment** [paritytech/parity#7770]
> I'm running:
>
> - **Which Parity version?**:   version Parity/v1.8.7-stable-e322fd8-20180124/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

actual:
```
$ parity export state --at 100 --no-storage  --no-code   balance.json
2018-02-01 11:22:51  Configured for Foundation using Ethash engine
**Specified block not found**
```
i sync block on fat-db mode. 
and this commond run without error:
`parity export state --no-storage  --no-code   balance.json
`

how to user the `--at 100` arg

**Comment by 5chdn** [comment]
what's your pruning mode, fast or archive?

**Comment by wliment** [comment]
@5chdn  

parity run with this command
` parity --fat-db on`

and console output 
"State DB configuration: fast +Fat"

**Comment by wliment** [comment]
@5chdn 
if i run this ` parity --pruning=archive --fat-db=on`
 Do i need delete the orgin synced blocks?

**Comment by 5chdn** [comment]
yes, for archive sync you will need to reset your DB
