### ISSUE TITLE
Online Wallet version

### ISSUE THREAD

**Issue by emaddaou** [paritytech/parity#7771]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Online version at https://wallet.parity.io/

Hi guys,

Please help me figure out how to restore my online wallet. If you visit the Online wallet of parity, it doesn't offer you an option to restore your wallet unless you create a new one till you are able to see the options available. Please allow the people to restore their wallet without creating a new one. 

Thank you :)

Imad

**Comment by 5chdn** [comment]
Yeah, you first have to create a new one.

We are in the process of shutting down the wallet and the public node, so this won't be fixed anymore.

**Comment by emaddaou** [comment]
Thanks for the update. Please write a note on the site to let people know. thanks.
