### ISSUE TITLE
Ethkey.exe fail to launch on Windows 10

### ISSUE THREAD

**Issue by psc478** [paritytech/parity#7772]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows 10
> - **How installed?**: via ethkey.exe downloaded from parity.io
> - **Are you fully synchronized?**: N/A
> - **Which network are you connected to?**: N/A
> - **Did you try to restart the node?**: N/A

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Please see attached. This error occurs upon me attempting to launch ethkey.exe. This was after I trouble-shooted the issue of receiving "the code execution cannot proceed because vcruntime140.dll was not found" upon trying to launch ethkey.exe, and a google search recommending I go here: https://www.microsoft.com/en-us/download/details.aspx?id=52685 to download vc_redist.x64.exe and vc_redist.x86.exe to resolve that issue. After doing so and running both of them, I then rebooted and attempted to run ethkey.exe and got the error you see now. I then launched vc_redist.x64.exe and clicked "repair," thinking that perhaps the error originating from installing both files rather than just one or the other, and still received the error you see now.
<img width="673" alt="paritybug" src="https://user-images.githubusercontent.com/30033360/35664126-48360032-06e6-11e8-8344-02f7218ddbc9.png">

**Comment by 5chdn** [comment]
In case you want parity, please download the parity installer not ethkey.

**Comment by kiwina** [comment]
lol that's whats on the website to download

**Comment by MrPTR** [comment]
Same issue here on Windows 10 (Parity 1.9.1 beta and the installer).
MSVCP140.dll and VCRUNTIME140.dll is missing. Visual C++ up to date. And with previous versions the same bug.

**Comment by folsen** [comment]
Problem was due to an issue on the website, not with any program.
