### ISSUE TITLE
EOS no longer showing in Parity wallet

### ISSUE THREAD

**Issue by cockneyninja** [paritytech/parity#7773]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version? 1.8.7
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer 
> - **Are you fully synchronized? / yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. 
I had successfully claimed my EOS tokens in my parity wallet. I upgraded to the 1.9 client and my account for lack of a better explanation was no longer showing. Recovered using phrase ETH balance showing No EOS. If I query my wallet address using etherscan.io my EOS tokens are shown. 
I have also installed the 1.8.7 client on another machine same behaviour no EOS. Can someone advise how I re-import or display my EOS.
Thanks

**Comment by 5chdn** [comment]
Fixed in #7742 #7755 - please stay tuned for 1.8.8

**Comment by cockneyninja** [comment]
@5chdn am I correct in thinking if I roll back to an older stable release this will also resole the issue and show my EOS tokens registered to my Parity wallet.
Thanks for your fast response

**Comment by 5chdn** [comment]
Nope. all current and previous versions are affected

**Comment by cockneyninja** [comment]
Hi @5chdn I have installed 1.8.8 and my EOS hasn't appeared. Are there additional steps required? I have confirmed they are linked to my wallet address by querying eitherscan.io
Thanks

**Comment by 5chdn** [comment]
Please upgrade to 1.8.9 :D
