### ISSUE TITLE
parity disk space usage

### ISSUE THREAD

**Issue by wallaceturner** [paritytech/parity#7774]
I'm running ./parity with the default options on a clean ubuntu VPS. Everything is working fine however disk usage is creeping up: (now at about 53Gb)

```
51G     .local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db
51G     .local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent
2.6G    .local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot/current
2.6G    .local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/snapshot
```

According to [this post][1] and also [this][2] (both by @5chdn) it could be around 25Gb.
Perhaps those numbers are now outdated and 50+ is the new minimum?
Is there anything you can do to reduce the disk space ? We will not be querying blocks older than 3 months. 

[1]:https://ethereum.stackexchange.com/questions/143/what-are-the-ethereum-disk-space-needs
[2]:https://dev.to/5chdn/the-ethereum-blockchain-size-will-not-exceed-1tb-anytime-soon-58a

**Comment by 5chdn** [comment]
Yes, 50GB is also what I see on my nodes, there is not much we can do, unfortunately.

**Comment by CherryDT** [comment]
Incredible how fast it goes - now we are talking about **500G** and not a whimpy 50G anymore...
