### ISSUE TITLE
No tx fee calculation

### ISSUE THREAD

**Issue by kiwina** [paritytech/parity#7784]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:1.9.1-20180201
> - **Which operating system?**: Window
> - **How installed?**: binaries 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
dosn't calculate transaction fee

**Comment by 5chdn** [comment]
Please use 1.8.9, thanks.
