### ISSUE TITLE
JSON-RPC: eth_getWork stuck on a single block

### ISSUE THREAD

**Issue by Nashatyrev** [paritytech/parity#7787]
I'm running:
- 1.9.0-beta
- Linux
- Insalled via `bash <(curl https://get.parity.io -Lk)`
- **Are you fully synchronized?**:  yes
- **Which network are you connected to?**: ethereum
- **Did you try to restart the node?**: yes

Steps: 
- run node till sync with enabled JSON-RPC api
- start calling `eth_getWork` 10 times per second (like normally miner or pool does)

Expected behavior: 
- new work returned is based on the latest imported block

Actual behavior:
- At some point (normally within 1 hour of running) `eth_getWork` stops returning a fresh block to mine and always returns the same obsolete work

Not reproducible on `1.8.8`

**Comment by debris** [comment]
@tomusdrw can this be related to the new transaction pool?

**Comment by tomusdrw** [comment]
1.9 does not have the new queue. perhaps an issue with `using_queue` crate?
Does the client import new blocks, maybe it just doesn't have enough peers?

**Comment by tomusdrw** [comment]
Closed via #8656
