### ISSUE TITLE
Tokens not showing up in Parity

### ISSUE THREAD

**Issue by twarlord** [paritytech/parity#7789]
> I'm running:

> - **Which Parity version?**: 1.8.7
> - **Which operating system?**:  MacOS Sierra
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I am unable to see any of my tokens in my Parity wallet. They were showing up one day and then they just vanished. I tried unistalling parity and reinstalling it. I have cleared the cache in my browser even tried a new browser. Eventually i deleted my parity db and keys and restored my wallets again. Now in the process of resynching but still not showing my tokens though it has past the date the tokens started being added to the wallets.

Tokens show up on etherscan but i cannot view them in parity. Even when i connect my Ledger Nano it only shows the ETH and none of the Tokens.

**Comment by 5chdn** [comment]
Please upgrade to 1.9.1 or 1.8.8 #7742 #7755 #7777

**Comment by twarlord** [comment]
Worked, thanks
