### ISSUE TITLE
UI fails to load properly on 1.9.[0,1]

### ISSUE THREAD

**Issue by awbacker** [paritytech/parity#7791]
> I'm running:
> - **Which Parity version?**: v1.9.1-20180201 beta
> - **Which operating system?**: MacOS
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

The Parity UI appears to be broken on OSX in all 3 major browsers.  

### Issues

* Wallet and Browse both have blank icons (icon failing to load)
* Wallet app shows a blank screen (or shows "localhost refused to connect" in chrome)
* Parity appears to be running its own nginx on port 80?

### What I have done to try to fix it:

* Run from the command line using an alternate port
* Installed an nginx proxy to redirect calls to localhost:80 to `8180`
  * Sets the host header to `127.0.0.1:8180` 

### What I See

* Requests are directed to two urls:  `127.0.0.1:8180` and `localhost:80` (yes, 80)
* Chrome shows content type errors
* In private mode nothing works (no icons at all)
* Content returnd from the icon requests is html (after redirecting via local proxy)

I've attached screenshots to demonstrate the issues.  Most are from chrome, since firefox and safari seem to not report the errors in the console even though they also fail to load properly.

**Console Errors:**
```
bundle.js:1 ServiceWorker error Error: ServiceWorker is not available in your browser.
bundle.js:1 setupWorker TypeError: s is not a constructor
```

![Console Errors](https://user-images.githubusercontent.com/103330/35730423-106cb0de-084d-11e8-8d5a-c1bcfbf452eb.png)

![Requests Tab](https://user-images.githubusercontent.com/103330/35730550-7fb0f374-084d-11e8-98bc-a1cf9092f9c5.png)

![Home Page](https://user-images.githubusercontent.com/103330/35729755-b35a84d6-084a-11e8-95ba-b267cdaf9fc7.png)

**This is the content returned when getting sw.js**
```
$> http http://127.0.0.1:8180/sw.js
HTTP/1.1 200 OK
Content-Security-Policy: default-src 'self'; [...too much...]
Content-Type: text/html
Date: Fri, 02 Feb 2018 11:13:32 GMT
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<script src="/parity-utils/inject.js"></script><!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Parity</title>
    <style>
      html {
        background: white;
        background-repeat: round;
      }
      // [deleted styles, for brevity 
    </style>
  <link rel="shortcut icon" href="parity-logo-black-no-text.png"><link href="bundle.css" rel="stylesheet"></head>
  <body>
    <div id="container">
      <div class="loading">Loading</div>
    </div>
  <script type="text/javascript" src="bundle.js"></script></body>
</html>
```

**Comment by amaurymartiny** [comment]
Investigating this issue. Can you provide the following information?

1. The output of the command
`curl --data '{"method":"parity_dappsUrl","id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`
in your terminal.

2. On the homepage. You say you have requests from `127.0.0.1:8180` and `localhost:80`. Could you make a screenshot of the Network tab in Chrome console?

3. In the Wallet dapp. `an error about "localhost refused" in chrome` -> Can you copy this error? A screenshot of the Network tab in the wallet dapp would be useful too.

No need to install an nginx proxy for all this. Thanks for your help.

**Comment by gaia** [comment]
running 1.9.1-20180201, I have the same issue. it only runs properly when i use localhost, not 127.0.0.1 (connecting from my windows laptop via sshtunnel to the vps where parity runs). via IP it doesn't even show my accts in the wallet dapp

1) {"jsonrpc":"2.0","result":"127.0.0.1:8545","id":1}

2) using 127.0.0.1: https://i.imgur.com/OHWWLL2.png, https://i.imgur.com/OHWWLL2.png, https://i.imgur.com/4qLiOJF.png

3) I don't have any "refused" errors.

**Comment by ivantomac** [comment]
I'm getting this issue as well, running Parity 1.9.2 using --light on Linux and using Firefox, fully synced.

I get "ServiceWorker error > Error: ServiceWorker is not available in your browser." followed by "setupWorker > TypeError: s is not a constructor".

Parity just shows a blank page with the logo in the center and nothing else.

Couple of hours ago I could have sworn it was working so I'm not sure what broke.

**Comment by awbacker** [comment]
@amaurymartiny 
### `#1` Connection refused on `:8545`, but `8546` is open.  

* My config.toml had `[rpc] \n  port=12003 \n ...` in it.  I changed that to `8545`
* Curl returns the same body as `httpie` does, just w/o the headers visible
 
```
$ http post 127.0.0.1:8545 method=parity_dappsUrl id=1 jsonrpc="2.0"
HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 05 Feb 2018 03:35:46 GMT
Transfer-Encoding: chunked
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": "localhost"
}

$ sudo lsof -PiTCP -sTCP:LISTEN
parity    1329 andrew   40u  IPv4 0x999ec89ce234a137      0t0  TCP localhost:12002 (LISTEN)
parity    1329 andrew   45u  IPv4 0x999ec89ce258c6b7      0t0  TCP *:30303 (LISTEN)
parity    1329 andrew   87u  IPv4 0x999ec89ce22d3a97      0t0  TCP localhost:8546 (LISTEN)
parity    1329 andrew   89u  IPv4 0x999ec89ce24b9a97      0t0  TCP localhost:8545 (LISTEN)
parity    1329 andrew   90u  IPv4 0x999ec89ce2353d57      0t0  TCP localhost:8180 (LISTEN)
```

### `#2` Connections to localhost:80 and 127.0.0.1:8080
You can see the localhost request in the screenshot where the `icon.png` request is called out.   Its requesting from `localhost/ui/dapps`.  I've added additional screenshot if that helps:

_I added an nginx proxy just to see if pointing :80 towards some other port would make the UI work.  I'm happy to try that redirect again, if it can help.  I know it shouldn't be required, but during troubleshooting..._

![image](https://user-images.githubusercontent.com/103330/35787556-0db18b2a-0a6a-11e8-960b-48bda72bad82.png)

---- 

![Bigger Network Tab](https://user-images.githubusercontent.com/103330/35787462-5b4a2226-0a69-11e8-84ce-2abae2f35c11.png)

----

![sw.js failing to load :8180](https://user-images.githubusercontent.com/103330/35787542-f59dfea6-0a69-11e8-983a-e22875c75888.png)

### `#3` Localhost Refused Connection

* No unexpected or failing requests
* No output in the console
* Network tab *only* has 3 icons being loaded, one is the `frowny face` 
* When the browser is active the text `localhost refused to connect` is shown
* Then the browser is inactive (e.g. click on desktop) the text disappears and the background color gets darker...

![Active Window](https://user-images.githubusercontent.com/103330/35787658-bba294b8-0a6a-11e8-84a6-974e74bd846e.png)

![Inactive Window](https://user-images.githubusercontent.com/103330/35787665-c6073ac6-0a6a-11e8-9383-f935f13ccdb9.png)

![Requests](https://user-images.githubusercontent.com/103330/35787690-fc020480-0a6a-11e8-9921-0427624e160d.png)

**Comment by amaurymartiny** [comment]
@awbacker There's something wrong in the response of your command `http post 127.0.0.1:8545 method=parity_dappsUrl id=1 jsonrpc="2.0"`. I'm suspecting some config in your `config.toml`, could you post it here?

@gaia @ivantomac I think the ServiceWorker issue is a separate one, I'll have a look too.

**Comment by awbacker** [comment]
@amaurymartiny Here is the config.toml.  I considered posting it with the last one, but it seemed to be getting super long already.  Should have done it :D 

```
# This config should be placed in following path:
#   $HOME/Library/Application Support/io.parity.ethereum/config.toml

[rpc]
port = 8545
hosts = ["localhost", "127.0.0.1"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore", "parity_accounts"]

[stratum]
#enable = true
port = 12002
interface = "127.0.0.1"

[mining]
# Account address to receive reward when block is mined.
author = "0x00.........."
extra_data = "parity-mined-for-testing"
```

**Comment by amaurymartiny** [comment]
Thanks! Try removing the line `hosts = ["localhost", "127.0.0.1"]` and restart the node to see if the error is still there.

**Comment by awbacker** [comment]
Success!    (sort of)

The wallet app has a functioning UI, and the icons on the main page are all filled in now!  However, it does not show my wallet or address book.  Rolling back to 1.87 does though (I did that yesterday, but put 1.9 on again).

**Comment by awbacker** [comment]
@amaurymartiny Thanks so much for the help!  I should have closed this myself last night.
