### ISSUE TITLE
Token Balance Incorrect

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#7797]
> I'm running:
>
> - **Which Parity version?**: 1.9.1-20180201
> - **Which operating system?**: Windows (client) / Ubuntu (parity)
> - **How installed?**: via curl
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Thank you guys for restoring token balances into parity!

One of the tokens I hold shows an incorrect balance. Etherscan shows the correct balance. There are a couple thousand in Etherscan and a fraction of 1 in Parity

**Comment by 5chdn** [comment]
That's probably a malformed token registry entry with the wrong number of decimals. Let me know which token and I nuke it from the registry.

**Comment by gaia** [comment]
it's ZIL

**Comment by Nogreedy** [comment]
@5chdn 

Hello,
Same problem for me with ZIL (ZILLIQA).
18 decimals is not equal to 12 decimals...
https://etherscan.io/token/0x05f4a42e251f2d52b8ed15e9fedaacfcef1fad27

**Comment by 5chdn** [comment]
@gaia @Nogreedy fixed!

**Comment by gaia** [comment]
Indeed, thanks Rando!!!

**Comment by Nogreedy** [comment]
@5chdn Thanks, it's OK now.
You're great.
