### ISSUE TITLE
Wallet Transaction History Outdated

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#7798]
> I'm running:
>
> - **Which Parity version?**: 1.9.1-20180201
> - **Which operating system?**: Windows (client) / Ubuntu (parity)
> - **How installed?**: via curl
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

The newest transaction in account is 6 months old. There have been plenty since then, and the balances reflect them, but the history doesn't update.

**Comment by 5chdn** [comment]
Yeah, that's an etherscan bug, not much we can do about this.
