### ISSUE TITLE
Error reading node table file 1.8.8

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7799]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.8 stable
> - **Which operating system?**: Linux
> - **How installed?**:  binary (amd64)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private blockchain
> - **Did you try to restart the node?**: yes

Running a node that was previously running 1.7.11 but is now upgraded to 1.8.8.

When starting Parity from the command line this error comes up directly after displaying the ETH price:

`Error reading node table file: ErrorImpl { code: Message("missing field `attempts`"), line: 3, column: 185 }`

If I delete .parity/chains/<chainName>/network/nodes.json and restart, there is no error.

I assume this has to do with the new nodes.json format but I am not sure if this means that 1.8.8 can't read the old format.  Is it required that I manually delete the file as part of the upgrade to 1.8.8?

**Comment by LefterisJP** [comment]
+ 1. I also got this when updated to 1.8.8.

But it has not affected the syncing in any way or form, mainnet continues to sync normally.

**Comment by andresilva** [comment]
That's expected since we made some changes to the json format. Yes, 1.8.8 won't be able to read the old format and your existing `nodes.json` file will be ignored but there's no action needed on your part.

**Comment by stone212** [comment]
@andresilva Yes you are correct.  I added it as an issue so the error could me made more clear.  Or called a "warning" instead.  For a systems administrator, the word "Error" means "Danger Will Robinson".
