### ISSUE TITLE
Parity transactions stuck at 6 months ago

### ISSUE THREAD

**Issue by Joaoha** [paritytech/parity#7802]
I'm running:

Which Parity version?: v1.9.2-20180201 beta
Which operating system?: Windows
How installed?: via installer
Are you fully synchronized?: yes
Which network are you connected to?: ethereum FOUNDATION
Did you try to restart the node?: yes
I've been using parity 1.7 for a very long time, after applying the latest 1.9 fix my transaction log is only showing transactions from 6 months ago. No recent transactions...

Did multiple reboots in the meantime.
Used different browsers.
Tried a different PC with Parity version 1.6.
Deleted the chain and resyncd.

Still No Recent Transactions...

Etherscan.io shows transactions just fine for my address...

Thanks

Address: 0x14c66B69F1f3018BC67F7C6BEfdBB80869E2Cb85

Issue #7738 was closed but only the token balance was fixed in issue #7738.

**Comment by iFA88** [comment]
Run parity with `--no-persistent-txqueue` parameter and for every start the tx queue will be truncated.

**Comment by iFA88** [comment]
Parity loads the transactions from etherscan. Maybe you are on different network?

**Comment by Joaoha** [comment]
thanks for the reply.
I'm on Foundation network, I can interact with any ICO, I can send and receive transactions from my account and if I check etherscan I can see the recent transactions.
It is only Parity that is not showing any transaction that has been made less than 6 months ago.

Screenshot from Parity just now.
![image](https://user-images.githubusercontent.com/35165691/35781782-673cb794-0a53-11e8-8269-751ab4ae4081.png)

screenshot from etherscan just now.
![image](https://user-images.githubusercontent.com/35165691/35781802-b6b53cb0-0a53-11e8-8193-6e430e9872fb.png)

**Comment by iFA88** [comment]
This is an etherscan bug.
https://api.etherscan.io/api?module=account&action=txlist&address=0x14c66B69F1f3018BC67F7C6BEfdBB80869E2Cb85&offset=25&page=1&sort=desc

**Comment by 5chdn** [comment]
Thanks for confirming

**Comment by Joaoha** [comment]
I see the issue as been closed. but I do not understand the comment.
it is a etherscan bug, what does this mean? will etherscan fix it and then parity will work fine?
why are the transactions on etherscan still showing up but not on parity if it is a etherscan bug? can you please explain just a bit more so we can understand, and also any idea when this could be fixed?

Cheers

**Comment by iFA88** [comment]
The transaction history is loaded from etherscan.io . You should contact with etherscan, that the API  `https://api.etherscan.io/api?module=account&action=txlist&address=0x14c66B69F1f3018BC67F7C6BEfdBB80869E2Cb85&offset=25&page=1&sort=desc` gives wrong (older) data back.

If you want check your transactions please visit:
https://etherscan.io/address/0x14c66b69f1f3018bc67f7c6befdbb80869e2cb85

**Comment by hhs17** [comment]
The API is updated, it returning latest transaction when sorting by desc.

**Comment by 5chdn** [comment]
Yeah, it's working now, cool!
