### ISSUE TITLE
Tokens suddenly not visible

### ISSUE THREAD

**Issue by yaeljawel** [paritytech/parity#7804]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: MacOS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: yes

Hi there, I used to have CAP tokens in my Parity wallet and they were always visible. Upon checking now, they are not anymore so I cant send them to another address. I've checked etherscan and they are still there.

**Comment by komlanvi** [comment]
I have the same issue running Parity 1.8.5 on Ubuntu 16.04!

**Comment by yaeljawel** [comment]
@komlanvi please let me know if you manage to find a solution.

**Comment by sbuljac** [comment]
Same issue for me for the last couple of days

**Comment by yaeljawel** [comment]
I have just upgraded to version 1.9.2 and tokens are visible again.
