### ISSUE TITLE
JSON-RPC Api different behavior with Geth, which is correct ?

### ISSUE THREAD

**Issue by gagarin55** [paritytech/parity#7806]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**: Linux
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm calling Parity json-rpc:
```
    const callData = {
        from: "0x0000000000000000000000000000000000000000",
        gasPrice: "0x04a817c800",
        gas: "0x5208",
        to: "0x0000000000000000000000000000000000000000",
        value: "0x0de0b6b3a7640000",
        data: "",
    }
    let gas: number = web3.eth.estimateGas(callData);
```

**Result:** Invalid params: Invalid bytes format. Expected a 0x-prefixed hex string with even length.

In the same time Geth/v1.7.3-stable-8c95ba44/linux-amd64/go1.9.2

proceeds this request without error.

**Comment by 5chdn** [comment]
Looks like web3 is malforming the calldata, can you debug that?

Not a parity issue.
