### ISSUE TITLE
Token I created in Parity not showing up / disappeared

### ISSUE THREAD

**Issue by vrozsnyay** [paritytech/parity#7811]
Hello,
I just created a Token in Parity then registered it with Parity. I even added an image, after which the token showed up in my Parity account, displaying the correct number and all.
Then I had to leave, turned computer off. When I returned I started up and started parity. Low and behold all my account data disappeared.
I managed to get the account data back, but now it does not show my token. It shows the actions that I created the token, added the image, registered it, etc. yet the token itself is not in my Parity account.
At the same time when I do a search for the Token it tells me that the account I have open owns all tokens.
I just wanted to send a token to someone to test the send method but since the token is not in my account I can't send. 
I have an ICO coming up but as I can't see the token  I will not be able to send to those who participation in the ICO.
Please help.
Thank you.

Running on Windows. Don't know the Parity version, installed it end of January, was the latest version. Installed via installer. Fully synced. Main ethereum network. Restarted token still not showing up.

_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by 5chdn** [comment]
Please upgrade to 1.8.9 :)
