### ISSUE TITLE
Nonce not incremented for contract deploy?

### ISSUE THREAD

**Issue by kcbt** [paritytech/parity#7813]
> I'm running:
>
> - **Which Parity version?**: 1.9.1 beta
> - **Which operating system?**: Linux (Ubuntu 14.04)
> - **How installed?**: binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private network with Aura consensus
> - **Did you try to restart the node?**: no

**expected behavior**
A contract can be deployed through a JSON RPC call (eth_sendRawTransaction with data filled in from parity_composeTransaction) using the nonce provided by the parity_composeTransaction method. The same contract can be deployed again (with a different nonce) from the same originating address.

**actual**
The first contract deploy proceeds as expected. The second contract deploy fails due to "Transaction with the same hash was already imported." Upon investigation, it appears that the nonce did not change (and eth_getTransactionCount also returns 0).

**steps to reproduce**

1. Select an arbitrary contract and deploy it on http://remix.ethereum.org to get its content (details > input) for data.
2. Call parity_composeTransaction with the origin address, a value of 0, and the data from (1).
3. In geth library, call NewContractCreation with the nonce, gas price, and gas limit from (2) and the contract content from (1).
4. Sign the transaction and convert the signed transaction to hex.
5. Call eth_sendRawTransaction with the result of (4).
6. Call eth_getTransactionReceipt using the hash provided in (5).

**questions**

Is there a separate counter to be consulted for contract deploys? If so, is there a recommended JSON RPC method for retrieving that nonce value?

**Comment by folsen** [comment]
Closing in favor of https://github.com/paritytech/parity/issues/8672
