### ISSUE TITLE
Gas price too low via rpc call

### ISSUE THREAD

**Issue by VladLupashevskyi** [paritytech/parity#7815]
> I'm running:
>
> - **Which Parity version?**: 1.8.9 stable and 1.9.2 beta
> - **Which operating system?**: MacOs
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: PoA private chain
> - **Did you try to restart the node?**: yes

I am running node in my private PoA network with 5 validators and when I am trying to get gasPrice via rpc call it returns me default gasPrice: in case of 1.8.9 stable - 166868896 wei, 1.9.2 beta - 0 wei. This bug is floating, so sometimes I am getting gasPrice which is set by all validators (22 Gwei) which is expected.

I think it gets those values from mining setting, but I don't have mining/sealing enabled.

**Comment by andresilva** [comment]
The gas price is calculated as the 50th percentile (configurable) of all transactions included in the last 100 blocks. It's expected for this value to fluctuate. I don't understand what the issue is.
