### ISSUE TITLE
Parity 1.9.2 multiple issues.

### ISSUE THREAD

**Issue by Serpent6877** [paritytech/parity#7817]
Parity 1.9.2 Beta
Ubuntu 16.04 (Dual Xeon L5520 w/24GB RAM  & Samsung 256GB SSD)
Binary release install.
Fully synched since v 1.8.1
Ethereum Classic & Musicoin
Node restarted. Removed nodes.json

Basic config:

[parity]
chain = "classic"
base_path = "/opt/etcpool/parityetc"
identity = "MyIdentity"

[network]
port = 38000
allow_ips = "public"
nat = "extip:<Public IP #1>"
min_peers = 50
max_peers = 75
#reserved_peers = "/opt/etcpool/peers"

[rpc]
port = 18000
interface = "local"
apis = ["eth", "net", "parity", "rpc"]

[websockets]
disable = true

[dapps]
disable=true

[footprint]
pruning = "fast"
pruning_memory = 64
cache_size_db = 128

[misc]
log_file = "logs/parity.log"
color = false

[account]
unlock = ["<my etc address>"]
password = ["/opt/etcpool/mypass"]

[ui]
disable = true

[mining]
author = "<my etc address>"

Upgraded from Parity 1.8.6 to 1.9.2.

I am running four parity instances along with multiple geth running pools. No issues with geth instances. There is five public IP's on this server.

First Parity issue: Parity does not seem to use the specified address in the NAT config. It insists on using all IP's as seen in netstat:

tcp        0      0 0.0.0.0:38000           0.0.0.0:*               LISTEN      19942/parity
udp        0      0 0.0.0.0:38000           0.0.0.0:*                           19942/parity

Second issue (which is more of a major one): I can not get more than a few peers to connect after the latest updates. I have removed the nodes.json file and restarted several times. Currently for the last hour I have been sitting at 1 peer. On my musicoin which has been running for two days I only have 9 peers. 

I tried setting a raw default config to see if it was port or IP related and still the same peering issue.

Any help appreciated.

Brad

**Comment by Serpent6877** [comment]
Additionally I did a db kill on the ETC DB. But still only 1 peer.

**Comment by atlanticcrypto** [comment]
I am experiencing the same issue on Parity1.9.1 on Eth mainnet. Same exact settings, distribution build and build hardware as nodes running v1.8.6. 1.8.6 nodes all have 500+ connections, 1.9.1 drops peers everytime it gets to 30-50. I will be downgrading until this issue is solved.

**Comment by Serpent6877** [comment]
@atlanticcrypto Look here #7531 . I am trying to report as best I can to them. Not seeming to get anywhere.

**Comment by 5chdn** [comment]
By default, Parity listens on all network devices. This is not configurable afaik.

Peering issues should be resolved, please upgrade to 1.9.5 or 1.10.0.
