### ISSUE TITLE
Switch to tree-based storage for NodeTable

### ISSUE THREAD

**Issue by figitaki** [paritytech/parity#7818]
In the original Kademlia paper, upon which the node discovery aspect of the devp2p protocol is based, the authors propose a binary tree for storing buckets. The go-ethereum project has a [comment](https://github.com/ethereum/go-ethereum/blob/master/p2p/discv5/table.go#L175) regarding this optimization. Currently the NodeTable uses a `HashMap` to store nodes, and the actual buckets are implemented in discovery using a `Vec`. I believe switching over to the tree based architecture would hypothetically allow for faster node discovery, and decrease the response time for `FIND_NODE` packets.

**Comment by 5chdn** [comment]
Hi @figitaki - we appreciate your comments on node-discovery improvements in devp2p, but we are currently unable to focus on optimizations of non-issues. If you want to dig into Rust, however, we welcome any pull request that improves the overall performance of Parity.
