### ISSUE TITLE
Transaction sended twice with only one sign (Parity 1.9.2)

### ISSUE THREAD

**Issue by 4budab1** [paritytech/parity#7819]
I'm running:

Which Parity version?: v1.9.2
Which operating system?: Windows 10 x64
How installed?: parity_1.9.2_installer.exe
Are you fully synchronized?: yes(all defaults, Warp-synced)
Did you try to restart the node?: no

I signed only once, but transaction sended twice to same address(Gladly sum was very low)
My acc: https://etherscan.io/address/0x067bdb1b056d09ac884b17b3ec02f32fd15c261b

TxHashes:(5041694 block)
1)https://etherscan.io/tx/0x257453ee5ef2b411853b12c6466c8341d3702a60915878d50f883044cda95187
2)https://etherscan.io/tx/0x1d2d288ccc5fbbd30983cac9aa8dd4b765a3918193aa698e25a7006944492214

i found same issues 
https://github.com/paritytech/parity/issues/7369
https://github.com/paritytech/parity/issues/7483

**Comment by 5chdn** [comment]
@jacogr @amaurymartiny

**Comment by 4budab1** [comment]
Same issue, user don't report in here 
https://github.com/ethereum/mist/issues/3541

**Comment by 4budab1** [comment]
https://etherscan.io/tx/0xfb4cfd72fe4c962acdb4d2e8677918c5a11038263839810ba5d01c89b3e1d6a9
Previously, i sended this transaction, waited while it appears on etherscan pending, then closed parity.

Next day i sended these one which doubled somehow

> TxHashes:(5041694 block)
> 1)https://etherscan.io/tx/0x257453ee5ef2b411853b12c6466c8341d3702a60915878d50f883044cda95187
> 2)https://etherscan.io/tx/0x1d2d288ccc5fbbd30983cac9aa8dd4b765a3918193aa698e25a7006944492214

**Comment by tomusdrw** [comment]
Might not be UI-only issue, worth investigating RPC part as well.

**Comment by epheph** [comment]
I also experienced this behavior on mainnet while using the UI:

`Parity v1.9.2-20180201 beta`

I did have 2 tabs open, perhaps that could have contributed? My specific transaction wasn't that bad to send twice, but it seems like a very serious issue for other transaction types

**Comment by 5chdn** [comment]
Fixed in 1.10
