### ISSUE TITLE
Deployment on mainnet fails

### ISSUE THREAD

**Issue by travs** [paritytech/parity#7834]
I'm running:
* `version Parity/v1.8.9-stable-1952d05d9-20180201/x86_64-linux-gnu/rustc1.23.0`
* linux `4.14.13-1-ARCH`
* installed from binary
* fully synced
* mainnet
* tried to restart the node

Trying to deploy [this contract](https://github.com/melonproject/protocol/blob/60847cec6a4b5799cabb59520cc43dcdb0426a9f/src/version/Version.sol) to the mainnet, and I get an error.
The log from parity is [here](https://git.io/vAfj0).

It occurs during gas estimation it seems.

**EDIT: 16:35 UTC**
Corrected the specs at top of the issue.
- OS changed from ubuntu to `4.14.13-1-ARCH`
- parity version changed from 1.9.0 to 1.8.9 (latest version of arch `parity` package in main repos)

cc: @jacogr

**Comment by 5chdn** [comment]
> Requires higher than upper limit of 79925460

You are exceeding the block gas limit. How are you deploying it?

**Comment by travs** [comment]
@5chdn Doing something [like this](https://github.com/melonproject/protocol/blob/before-live/utils/deploy/contracts.js#L221).
This runs out of gas on the mainnet, but does not run out on a parity devchain, or on kovan, which I find puzzling.

Also if I allow gas estimation, like this 
```
deployContract("version/Version", opts, [pkgInfo.version, deployed.Governance.address, deployed.EthToken.address]);
```

Then the gas estimation fails as above (but again, *only* on the mainnet).

**Comment by tomusdrw** [comment]
Most likely the contract is to big to be deployed on the mainnet (mainnet has a 24kb contract size limit, https://github.com/paritytech/parity/blob/321d4aee85b499cebd31c398ebdc953b1f669f06/ethcore/res/ethereum/foundation.json#L154). It seems it's compiled without optimizations, can you enable them and try again?

**Comment by travs** [comment]
@tomusdrw 
Ah ok I was not aware of this size limit, thank you.
I believe I was running with optimization enabled (`solc --optimize`), which gave a contract size of 50kB.
Without optimization, I get 84kb.

Maybe something weird is going on in the compilation step, though I'm not sure what it could be.

I think you have identified the issue though, and it does not seem to be with parity, so I will pursue it elsewhere I guess.
Thanks again!
