### ISSUE TITLE
(Problem) Parity doesn't display exact balance for an account

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#7837]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-macos/rustc1.23.0
> and 1.8.5
> - **Which operating system?**: MacOS
> - **How installed?**: via installer / homebrew 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: [sokol](https://github.com/poanetwork/poa-chain-spec/blob/sokol/spec.json)
> - **Did you try to restart the node?**:  yes

Screenshot speaks for itself

![image](https://user-images.githubusercontent.com/9360827/35952317-4865819c-0c34-11e8-8acc-761b12fa8898.png)
https://sokol-explorer.poa.network/account/0xb8988b690910913c97a090c3a6f80fad8b3a4683

**Comment by 5chdn** [comment]
It will show the correct balance when creating a transaction.

The parity wallet will be split out, please raise your issues here: https://github.com/Parity-JS/dapp-wallet
