### ISSUE TITLE
Real install instructions

### ISSUE THREAD

**Issue by fulldecent** [paritytech/parity#7838]
On the project home page:

> Parity is designed for mission critical use in enterprise environments.

But on the README.md the only install instruction for Ubuntu is:

    bash <(curl https://get.parity.io -Lk)

---

I know this is the future, and already 30 years past 1984 and security isn't even a word any more. But just like to point out there is at least person left in this world that thinks `bash <(curl ...` installation is not reasonable for mission critical use in enterprise environments.

**Comment by 5chdn** [comment]
- Detailed instructions https://paritytech.github.io/wiki/Setup
- All releases https://github.com/paritytech/parity/releases
