### ISSUE TITLE
Parity aborts- Ubuntu 16.04 server

### ISSUE THREAD

**Issue by Ben-and-Ellen** [paritytech/parity#7839]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: /v1.8.9-stable-1952d05-20180201/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**:  Ubuntu 16.04 server
> - **How installed?**: via binaries 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

====================
Parity was running fine. ethminer was receiving and accepting transactions. Then after this transaction was reported by parity: 

2018-02-07 21:46:10  Syncing #5047675 6e4c…b01f     0 blk/s   50 tx/s   2 Mgas/s      0+ 2723 Qed  #5050401   24/25 peers   6 MiB chain 121 MiB db 337 MiB queue 2 MiB sync  RPC:  0 conn,  0 req/s,  56 µs

the next output was:

stack backtrace:
   0:     0x56131da94b6c - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "IO error: While open a file for appending: /home/myname/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/006477.log: No such file or directory"', /checkout/src/libcore/result.rs:906

when I try to restart parity, I get the following error:

Error upgrading parity data: CannotCreateConfigPath

**Comment by Ben-and-Ellen** [comment]
$ whoami
xxx

$ ls -lsha ~/.local/share/io.parity.ethereum/
4.0K drwxrwxr-x 8 xxx xxx 4.0K Feb  9 16:40 .
4.0K drwxrwxr-x 4 xxx xxx 4.0K Feb 20 08:31 ..
4.0K drwxrwxr-x 2 xxx xxx 4.0K Feb  9 13:42 cache
4.0K drwxrwxr-x 3 xxx xxx 4.0K Feb  9 11:10 chains
4.0K drwxrwxr-x 2 xxx xxx 4.0K Feb  7 15:21 dapps
4.0K drwxrwxr-x 3 xxx xxx 4.0K Feb  7 15:21 keys
4.0K drwxrwxr-x 2 xxx xxx 4.0K Feb  7 15:21 network
4.0K drwxrwxr-x 2 xxx xxx 4.0K Feb  7 15:21 signer

So this issue hasn't repeated in the last two weeks. I was using a 500Gb spinning hdd and I switched to a 500Gb SSD drive and I haven't seen the issue again.

**Comment by 5chdn** [comment]
Ok cool!
