### ISSUE TITLE
Receiving new blocks with same block number but different block hash

### ISSUE THREAD

**Issue by huangkuan** [paritytech/parity#7850]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.2
> - **Which operating system?**: Ubuntu 10.16
> - **How installed?**: bash <(curl https://get.parity.io -kL)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
I am using web3.js to listen to "newblockheaders" event and often get blocks with same block number but different block hash. The number of transactions are also different between these two "duplicated" blocks. 

Any idea why it's happening? The one comes in later is usually the one that's being logged on etherscan.io. Any tips will be greatly appreciated!

**Comment by 5chdn** [comment]
It's totally normal that miners find _same_ blocks at the same time. These blocks are usually included as _uncles_ later. 

https://ethereum.stackexchange.com/questions/34/what-is-an-uncle-ommer-block

**Comment by lbrep** [comment]
I have one node with geth version 1.8, in a private chain. It has two different blocks with height 63 but different hashes. The current height is at 656, but you can query both blocks by eth.getBlock("0xade3223....") and similiarly the other one. and you will see that blockNumber is same for both but hash is different. 
How is this possible? You are welcome to access and diagnose the chain.

**Comment by globalchainapi** [comment]
How did you solve the problem? Can you tell me? I use Golang's RPC to subscribe
This is also the case.

**Comment by globalchainapi** [comment]
@Tbaut  How did you solve the problem?
