### ISSUE TITLE
Unable to transfer from Trezor hardware wallet

### ISSUE THREAD

**Issue by justin-** [paritytech/parity#7852]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.2-beta-0feb0bb6e-20180201/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**: Debian testing
> - **How installed?**: parity_1.9.2_debian.deb
> - **Are you fully synchronized?**: Yes
> - **Which network are you connected to?**: Ethereum Foundation
> - **Did you try to restart the node?**: Yes

I am unable to transfer from my Trezor hardware wallet running firmware 1.6.0.

Steps to reproduce:

1. Start parity and access the web interface
2. Enter the Trezor PIN
3. Navigate to the accounts tab and select the Trezor account
4. Click the transfer button
5. Enter a recipient address and an amount to transfer then click send
6. A "Parity Signer: Pending" dialog will appear, click the "Confirm Request" button

Expected behavior: A prompt to confirm the transaction should appear on the Trezor device

Actual behavior: The Trezor screen remains unchanged and the following error appears in the parity web interface
>[-32602] Invalid params: invalid type: null, expected a string.

Possibly related to #6781

**Comment by laradji** [comment]
I think i have the same issue with my nano S and the last parity stable 1.8.9

**Comment by ghettodev** [comment]
I'm having this issue on all versions of Parity after 1.8.10, including betas.

> Which Parity version?:  > Parity/v1.8.10
> Which operating system?: Ubuntu 17.10
> How installed?: parity_*_ubuntu.deb
> Are you fully synchronized?: Yes
> Which network are you connected to?: Ethereum Foundation
> Did you try to restart the node?: Yes

**Comment by Tbaut** [comment]
Should be solved in 1.10, can you confirm ?

**Comment by ghettodev** [comment]
Can confirm, works in 1.10 versions.
