### ISSUE TITLE
[-32021] Account password is invalid or account does not exist.

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#7853]
> I'm running:

> - **Which Parity version?**: 1.8.8
> - **Which operating system?**: Linux
> - **How installed?**: via installer binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private blockchain
> - **Did you try to restart the node?**: yes

Transferring ETH from one address to another.  The FROM address has no account password.  I initate the transfer.  Parity UI (Parity Signer) asks me for the password.  But I have no password for this account so I click "Confirm Request".  A red error message says:

`[-32021] Account password is invalid or account does not exist.`

Can I add a password to the account?

How do I proceed with this transaction?

**Comment by 5chdn** [comment]
Yes, go to the account > password view and test or change your password.

**Comment by stone212** [comment]
Thank you.  I never used the GUI (except to confirm transactions) so I was thinking it had to be an RPC call or "parity account <some-command>".  If there is an RPC call then maybe the doc is missing because I could not find it?

**Comment by 5chdn** [comment]
https://paritytech.github.io/wiki/JSONRPC-parity_accounts-module#parity_changepassword

This?

**Comment by stone212** [comment]
The answer to your question is probably yes but I tried this before posting and this solution does not appear to be working so I assumed it was a deprecated json method based on the error.  Here is what I mean by "not working":

```
curl --data '{"method":"parity_changePassword","params":["<address>","","<new-password>"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

Note that the Old Password field is blank because there is no old password.  I assumed that the "method" that was not found was "parity_changePassword" and that maybe this just
