### ISSUE TITLE
When upgrading from 1.8.x to 1.9.x do we need to db kill?

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#7854]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.2
> - **Which operating system?**: Linux
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: any
> - **Did you try to restart the node?**:  yes

This is a question, not an issue: when upgrading from 1.8.4 to 1.9.2 do we need to `db kill` and resync? Reason: as I understand RocksDB was upgraded to a newer when switching to 1.9.x + also saw a few issues that were resolved with resyncing from scratch.

**Comment by andresilva** [comment]
The RocksDB update was rolled out on 1.8.6. You won't need to perform a `db kill` but performance might be temporarily affected while RocksDB is performing the initial full compaction (which can take some hours to finish completely). Everything should still work, but a bit slower.
