### ISSUE TITLE
Ethereum funds still 0 after transaction

### ISSUE THREAD

**Issue by voltmoe** [paritytech/parity#7857]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.9
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

As title states, transferred ethereum to parity wallet about 14 hours ago, and my wallet balance on parity is 0. Eth scan says transaction is 'in'.

I'll provide more info as requested.

**Comment by 5chdn** [comment]
> Are you fully synchronized?: no

Wait until you are fully synchronized.
