### ISSUE TITLE
Deploying ERC20 contract in a private chain using Deploy Token DAPP

### ISSUE THREAD

**Issue by rogerganga** [paritytech/parity#7858]
> I'm running:
>
> - **Which Parity version?**: 1.8.9
> - **Which operating system?**: Windows 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: no 

Newbie to parity here. I have deployed a private Ethereum chain and using parity as my client.
I tried to deploy ERC20 token using Deploy token DAPP in parity. No result obtained.
I tried to register ERC20 token using Register token DAPP in parity. No result obtained.

**Actual**
No Tokens are visible in the UI.

![image](https://user-images.githubusercontent.com/26567484/36073327-a563af94-0f69-11e8-8df9-0cbc4ccabaee.png)

**Expected**
Tokens should be visible in the UI.
![image](https://user-images.githubusercontent.com/26567484/36073318-8335ae36-0f69-11e8-9a87-eedf285af7bd.png)

Has anyone faced the same issue before? If yes, can you pl explain on resolve this issue?
Thanks!!

**Comment by 5chdn** [comment]
Yes, you are missing all the registries on the development chain.

1. First of all, you need a registry. You can use the following tools to deploy it: http://127.0.0.1:8180/chaindeploy.html
2. After deploying the registry, note the public address and add it as `registrar` to your chain specification.
3. Restart your node and navigate back to http://127.0.0.1:8180/chaindeploy.html and it should recognize your registry (green tick).
4. Proceed with the rest of the registries and dapps, etc. pp.

Note you should have another window open with the signer (or unlock your account via CLI).
