### ISSUE TITLE
Refactor Aura behavior with/without empty steps

### ISSUE THREAD

**Issue by andresilva** [paritytech/parity#7875]
The Aura consensus engine supports distinct behavior regarding the creation of empty blocks whether empty step messages are enabled or not (after a transition). We should refactor `AuthorityRound` into two separate modules, one for pre-transition logic and one for post, with the `AuthorityRound` struct simply delegating into either one as necessary (https://github.com/paritytech/parity/pull/7605#issuecomment-364998928).

**Comment by folsen** [comment]
@andresilva Closing this issue because #7605 is merged, reopen if there's more work to be done with a specifics of that work.
