### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'DB flush failed

### ISSUE THREAD

**Issue by rarigita** [paritytech/parity#7877]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.0-20180125
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

====================

stack backtrace:
   0:     0x5589d17b59ac - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 234660013, got 3268526911  in /home/XXXXX/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/034939.sst offset 19996486 size 53295"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abortado (`core' generado)

**Comment by 5chdn** [comment]
Please upgrade to 1.9.2 and reset your database. Thanks

**Comment by rarigita** [comment]
Crash again, imposible to sync
====================

stack backtrace:
   0:     0x55e34825b9ac - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 234660013, got 3268526911  in /home/XXXXX/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/034939.sst offset 19996486 size 53295"), State { next_error: None, backtrace: None })', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abortado (`core' generado)

**Comment by rarigita** [comment]
Reset = delete and resync the chain?

**Comment by 5chdn** [comment]
Yes.

**Comment by rarigita** [comment]
Upgraded to 1.9.2, deleted the chain, synced overnight. All ok by now. Thanks.
