### ISSUE TITLE
all my balances not appearing, although my node fully synced

### ISSUE THREAD

**Issue by fidaaayoub** [paritytech/parity#7885]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.5
> - **Which operating system?**:  MacOS 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum (chain FOUNDATION)
> - **Did you try to restart the node?**:  HOW? i tried restarting the whole macbook
_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

i am logging in today to my wallet, it has been fully synced, but it is not showing any of the coins i have. everything is not even appearing with any balance.

how to fix that?

**Comment by 4budab1** [comment]
type your address here and on etherscan buddy

**Comment by fidaaayoub** [comment]
I typed in etherscan and was able to see what is in

But how i can transfer out

Best Regards,

Fidaa Ayoub, PMP

**Comment by chevdor** [comment]
There seem to be a recent issue indeed.
While badges do appear, tokens no longer show up (version Parity/v1.10.0-unstable-bc8216a82-20180128/x86_64-macos/rustc1.23.0).

The seem to be an issue while fetching the balances of the tokens:
```
v1: starting Tokens Provider...
15:35:44.387 index.31005421e8.js:1 could not register SW after 2.5s
(anonymous) @ index.31005421e8.js:1
15:35:47.132 bundle.js:1 balances::fetchTokensBalances TypeError: Cannot read property 'gt' of undefined
    at bundle.js:1
    at Array.filter (<anonymous>)
    at bundle.js:1
    at Array.reduce (<anonymous>)
    at bundle.js:1
    at <anonymous>
(anonymous) @ bundle.js:1
15:35:47.133 bundle.js:1 started Tokens Provider
15:35:48.282 index.31005421e8.js:1 balances::fetchTokensBalances TypeError: Cannot read property 'gt' of undefined
    at index.31005421e8.js:1
    at Array.filter (<anonymous>)
    at index.31005421e8.js:1
    at Array.reduce (<anonymous>)
    at index.31005421e8.js:1
    at <anonymous>
```

**Comment by fidaaayoub** [comment]
How to fix it though 

Best Regards,

Fidaa Ayoub, PMP

**Comment by chevdor** [comment]
The same parity version works fine on Kovan (ie all the tokens show up).

So I suspect an issue that is specific to one token.

@fidaaayoub This is most likely a bug in the UI so either you find it and fix it with a PR or you will have to wait until this is fixed. In the meantime, if you worry about your tokens, you may 'watch' the contract corresponding with your token and check your balance there.

**Comment by fidaaayoub** [comment]
Thanks,

I actually need to get some of them out to sell for ICOs lol so not much can wait 

Best Regards,

Fidaa Ayoub, PMP

**Comment by chevdor** [comment]
@fidaaayoub then don´t wait, _watch_ (Contracts/Watch) the contract and use its `transfer` method to send tokens to the address of your choice.
I will look similar to this (without the orange warning):
![image](https://user-images.githubusercontent.com/738724/36213149-3e0c1f4a-11a6-11e8-9740-8d97ccc3ae1c.png)

**Comment by fidaaayoub** [comment]
@chevdor  this for being supportive mate,,,
when i clicked watch. it asks for the contract address to watch.  i am not sure what contract address////
basically these are dent coins.  i used to watch the contract during the ICO period. but after that, the contract was over and tokens were sent to my wallet.

**Comment by rphmeier** [comment]
@fidaaayoub The contract address to watch is the token contract address. Probably can be found on etherscan with a quick search.

**Comment by 5chdn** [comment]
This is fixed in 1.8.9. please upgrade!

**Comment by chevdor** [comment]
@5chdn I think there is a bug or a regression.
I am using Parity/v1.10.0-unstable-bc8216a82-20180128/x86_64-macos/rustc1.23.0 and I see a similar issue.
The issue only occurs on mainnet and it seems to solve itself when the tokens are used.
Did the data in the local storage change?
That would explain the error messages:
```
index.31005421e8.js:1 balances::fetchTokensBalances TypeError: Cannot read property 'gt' of undefined
    at index.31005421e8.js:1
    at Array.filter (<anonymous>)
    at index.31005421e8.js:1
    at Array.reduce (<anonymous>)
    at index.31005421e8.js:1
    at <anonymous>
(anonymous) @ index.31005421e8.js:1
```

**Comment by 5chdn** [comment]
What else can I try? Could write it vertically:

> This
> Is
> Fixed
> In
> 1.8.9

> Please 
> Upgrade

:)

Note, 1.10 does not contain any user interface at all, so you must be at least several weeks behind. :)

**Comment by chevdor** [comment]
Indeed, 28.01... I thought I had something fresher....
Let me rebuild and see if that helps. Vertically was nice, thanks 😄

**Comment by chevdor** [comment]
@5chdn I was on 1.10 from 28.01 and I can guaranty there was a UI. The UI was however broken recently (see #7948).

I rebuilt now with UI and can confirm it works all good as we can see below.

![image](https://user-images.githubusercontent.com/738724/36391480-f96c53e6-15a6-11e8-88e7-c50b142910cb.png)
