### ISSUE TITLE
account verification stuck at Request (step 3)

### ISSUE THREAD

**Issue by boneyard93501** [paritytech/parity#7902]
<pre>
1.9.2-20180201 beta (docker image parity/parity:v1.9.2)
server: Ubuntu 16.04 LTS, Docker  17.12.0-ce, build c97c6d6
client: OS X 10.11.6 client (Chrome Version 64.0.3282.167)
synched
ethereum
multiple node restarts
</pre>

initiated account verification, paid up, and received sms code but ui did not progress past step 3, Request, with message: <i>"Requesting a code from the Parity server and waiting for the puzzle to be put into the contract"</i>

expected behavior: progress to step 4, Enter Code.

**Comment by boneyard93501** [comment]
any chance i can get the account verified by manual intervention? the eth went out in step 3, i got the confirmation code ... but no verified kovan account.  thx

**Comment by rbeach** [comment]
I am experiencing this issue as well

v1.11.0-20180312 unstable
OSX 10.12.6
synced
ethereum

I received the parity verification code via SMS, and the transaction is also showing as a success:
https://etherscan.io/tx/0x27c145615213c961e0ea7a0f2ff5266c4a91d706a8de5990bf9b55aea7036902

**Comment by Tbaut** [comment]
@rbeach @boneyard93501 if you have received the code per email/sms you can go back to your account>verify and once you enter your email/sms the UI will make a request to the relevant contract and jump directly to the confirmation step where you can enter the code.

**Comment by rbeach** [comment]
After repeating the steps as listed, when I get to step 3, the parity signer creates a new request, requesting an additional .007 ether. Since the first transaction already posted, I already sent .007 ether for the first one

**Comment by Tbaut** [comment]
Interresting, I got it working that way with email.
Then you can try to manually confirm the code :

1. Enable "Contracts" tab in Parity Wallet (go to "Settings")
2. Add a SMS Verifier contract:
Address: 0x673f0dec1416803a39d50760c697fb26f4c539b0
ABI: https://etherscan.io/address/0x673f0dec1416803a39d50760c697fb26f4c539b0#code
3. Invoke `confirm` function with sha3 of the code (look for ascii to hex converters)
