### ISSUE TITLE
Requires higher than upper limit of 60000000 error while trying to estimateGas

### ISSUE THREAD

**Issue by chebykin** [paritytech/parity#7904]
> I'm running:
>
> - **Which Parity version?**: Tried both 1.9.2-beta and 1.8.9
> - **Which operating system?**: MacOS and Ubuntu
> - **How installed?**: via homebrew and .deb package for Ubuntu
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: private aura
> - **Did you try to restart the node?**: yes

### Description
I'm getting  an error while trying to estimateGas for `addSupport` transaction. Not sure is this a problem with the contract I use or with Parity AuRa engine itself.

### Actual behaviour
When I try to estimateGas for `addSupport` transaction, I'm getting **Requires higher than upper limit of 60000000** error. Contract I use is https://github.com/paritytech/contracts/blob/master/validator_contracts/MajoritySet.sol

#### Logs from parity
```2018-02-14 15:17:10 TRACE rpc Request: {"id":2637171441,"jsonrpc":"2.0","params":[{"from":"0x3c6463e6bb1d5879c54a2240545e3a629cf09358","to":"0xaa488f54fa157e8dfee11561ea40b2ba6ef161ba","value":"0x0","data":"0xbc201a9d0000000000000000000000000daa3d4b5a83ec4175277027483657165452a242"}],"method":"eth_estimateGas"}```

```2018-02-14 15:17:10 DEBUG rpc Response: {"jsonrpc":"2.0","error":{"code":-32015,"message":"Transaction execution error.","data":"Internal(\"Requires higher than upper limit of 47000000\")"},"id":2637171441}```

Notice that these logs are from a bit different setup and in this case the number is 47000000.

### Expected behaviour
I get response with an estimated gas cost.

### Steps to reproduce
I've created the repo with a network config https://github.com/chebykin/parity-issue-gas-estimation.git. Clone the repo, run parity and try to invoke a gas estimation request.

```sh
git clone https://github.com/chebykin/parity-issue-gas-estimation.git
cd parity-issue-gas-estimation
parity --config config.toml
```

```curl 'http://0.0.0.0:8545/' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-binary '{"id":2637170607,"jsonrpc":"2.0","params":[{"from":"0x3c6463e6bb1d5879c54a2240545e3a629cf09358","to":"0xaa488f54fa157e8dfee11561ea40b2ba6ef161ba","value":"0x0","data":"0xbc201a9d0000000000000000000000000daa3d4b5a83ec4175277027483657165452a242"}],"method":"eth_estimateGas"}'```

**Comment by rphmeier** [comment]
It used to be that we allowed gas estimation to run indefinitely until a value was returned. The result of that was that nodes often got stuck in infinite loops. Right now there is a hard cap on estimation at 10 * the current block limit.

**Comment by chebykin** [comment]
I have found the cause. I just was too eager to estimate gas on a brand new chain with no blocks mined yet. After the first block is mined the gas estimation is done with no errors.
