### ISSUE TITLE
Recoverable Wallet dApp: INVALID DAPP

### ISSUE THREAD

**Issue by gaia** [paritytech/parity#7923]
> I'm running:
>
> - **Which Parity version?**: v1.9.2-20180201 beta
> - **Which operating system?**: Windows
> - **How installed?**: curl
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Opening the Recoverable Wallet dApp returns

INVALID DAPP
DOWNLOADED BUNDLE DOES NOT CONTAIN A VALID CONTENT.
ManifestNotFound

**Comment by 5chdn** [comment]
This app is not authored by Parity, not much we can do about this.
