### ISSUE TITLE
Latest 1.9.2-beta-0febobb parity doesn't work on jsonrpc-cors "all" parameter

### ISSUE THREAD

**Issue by richgrove** [paritytech/parity#7925]
The parity client is running on,

Starting Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0

on the ubuntu linux os.  It was installed using the 
\bash <(curl https://get.parity.io -kL)

Parity command line is:
parity --chain=kovan --datadir=/data/parity-data  --jsonrpc-apis all --jsonrpc-cors all --jsonrpc-hosts all --jsonrpc-interface all

I configured the nginx like:
server {
     listen 80 default_server;
     listen [::]:80 default_server;

    # Geth proxy that password protects the public Internet endpoint
    location /eth {
        #auth_basic "Restricted access to this site";
        #auth_basic_user_file /etc/nginx/protected.htpasswd;

        # Proxy to geth note that is bind to localhost port                        
        proxy_pass http://localhost:8545;
    }
}

When I ran the rpc access at:
http://_server_ip_add_/eth
I got the site can't be reached, giving 'http://127.0.0.1:8180'.   I saw the similar issue, 
https://github.com/paritytech/parity/issues/7541
was fixed in the 1.9.2-beta.   But, I am running this version and see the same problem.

**Comment by 5chdn** [comment]
It's fixed but not released yet, stay tuned for 1.9.3 or 1.10.0 :)

**Comment by tomusdrw** [comment]
@richgrove can you send more details? Site can't be reached just means that the request never even hit the node. Parity will respond with an error page if it's misconfigured not silently ignore the request.

Please send:
1. Parity log
2. Nginx log
3. Curl logs with `-v` flag that you expect to be working or a screenshot of browser window with Chrome Developer Tools opened on Network tab.
