### ISSUE TITLE
Password file not working

### ISSUE THREAD

**Issue by diadal** [paritytech/parity#7946]
Before filing a new issue, please **provide the following information**._

> I'm running: Ubuntu 16.04
>
> - **Which Parity version?**:v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0

> - **Which operating system?**: Linux
> - **How installed?**: bash <(curl https://get.parity.io -Lk)
> - **Are you fully synchronized?**: No
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

2018-02-19 13:31:11  Starting Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0
2018-02-19 13:31:11  Keys path /root/.local/share/io.parity.ethereum/keys/Foundation
2018-02-19 13:31:11  DB path /root/.local/share/io.parity.ethereum/chains/ethereum/db/2435353r3
2018-02-19 13:31:11  Path to dapps /root/.local/share/io.parity.ethereum/dapps
2018-02-19 13:31:11  State DB configuration: fast
2018-02-19 13:31:11  Operating mode: active
No valid password to unlock account 9cb1…b2c0. Make sure valid password is present in files passed using `--password` or in the configuration file._

In my passfile.txt I type the account password do I need to convert to password to any other formate ??

**Comment by 5chdn** [comment]
Please share your exact node configuration, also, could you try a different account with a different password?

**Comment by diadal** [comment]
I use default config I also try this echo "123456789" > ./passfile && parity --unlock 0x9cb1...word=passfile thesame error 

[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "none"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

chain = "homestead"
base_path = "$HOME/.local/share/io.parity.ethereum"
db_path = "$HOME/.local/share/io.parity.ethereum/chains"
keys_path = "$HOME/.local/share/io.parity.ethereum/keys"
identity = ""
light = false

[account]
unlock = ["0x9cb1.....c00ce11eb2c0"]
password = ["/root/.safe/password.txt"]
keys_iterations = 10240

[ui]
force = false
disable = false
port = 6454
interface = "127.0.0.1"
path = "$HOME/.local/share/io.parity.ethereum/signer"

[network]
port = 30303
min_peers = 25
max_peers = 50
nat = "any"
id = 1
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false

reserved_only = false
reserved_peers = "./peers.txt"

[rpc]
disable = false
port = 3434
interface = "local"
cors = ["nono"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[websockets]
disable = false
port = 7565
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]

[dapps]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/dapps"

[secretstore]
disable = false
nodes = []
http_interface = "local"
http_port = 8082
interface = "local"
port = 8083
path = "$HOME/.local/share/io.parity.ethereum/secretstore"

[ipfs]
enable = false
port = 5001
interface = "local"
cors = []
hosts = ["none"]

[mining]
author = "0x9cb183.....24ac00ce11eb2c0"
engine_signer = "0x9cb183.......24ac00ce11eb2c0"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
work_queue_size = 20
relay_set = "cheap"
usd_per_tx = "0.0025"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "4700000"
gas_cap = "6283184"
tx_queue_size = 8192
tx_queue_gas = "off"
tx_queue_strategy = "gas_factor"
tx_queue_ban_count = 1
tx_queue_ban_time = 180 #s
tx_gas_limit = "6283184"
tx_time_limit = 100 #ms
extra_data = "Parity"
remove_solved = false
notify_work = ["http://localhost:3001"]
refuse_service_transactions = false

[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 500
cache_size_db = 64
cache_size_blocks = 8
cache_size_queue = 50
cache_size_state = 25
cache_size = 128 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "auto"
scale_verifiers = true
num_verifiers = 6

[snapshots]
disable_periodic = false

[vm]
jit = false

[misc]
logging = "own_tx=trace"
log_file = "/var/log/parity.log"
color = true

**Comment by diadal** [comment]
after removing 

[mining]
author = "0x9cb183.....24ac00ce11eb2c0"
engine_signer = "0x9cb183.......24ac00ce11eb2c0"
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
work_queue_size = 20
relay_set = "cheap"
usd_per_tx = "0.0025"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "4700000"
gas_cap = "6283184"
tx_queue_size = 8192
tx_queue_gas = "off"
tx_queue_strategy = "gas_factor"
tx_queue_ban_count = 1
tx_queue_ban_time = 180 #s
tx_gas_limit = "6283184"
tx_time_limit = 100 #ms
extra_data = "Parity"
remove_solved = false
notify_work = ["http://localhost:3001"]
refuse_service_transactions = false

It works but I need to enable [mining]

**Comment by 5chdn** [comment]
You have a different password in your config file, did you check that, too?

Glad it works now!
