### ISSUE TITLE
What makes a node a warp-sync node?

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#7951]
> I'm running:
>
> - **Which Parity version?**: 1.9.2
> - **Which operating system?**: Linux
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: sokol
> - **Did you try to restart the node?**: no

When connecting to our network, some nodes can be warp-synced from (you download snapshots first, then latest blocks), but others - can't (you start downloading blocks from 0). Why is it, what makes a node _warp-syncable_ (pardon my french)? both nodes appear to be fully synced (at least they have the same height).

**Comment by 5chdn** [comment]
Warp-Sync is hardly possible on Ethereum anymore as the state is growing so fast. The issue you experience is pretty much summarized on our wiki:

https://paritytech.github.io/wiki/Known-Issues-Priorities

Key issues are #7863 and #7436 here: There are not enough nodes in the network providing recent snapshots. 

We are working hard on solutions, but it looks very much like the future belongs to the light clients.
