### ISSUE TITLE
Get the light client to compile for Android

### ISSUE THREAD

**Issue by tomaka** [paritytech/parity#7954]
So that it can later be used as a library by Android applications, or as some sort of background service (if that's possible).

**Comment by rphmeier** [comment]
https://github.com/paritytech/parity/issues/4842

**Comment by tomaka** [comment]
Here's my WIP branch: https://github.com/paritytech/parity/compare/master...tomaka:android-build?expand=1

Notes on the various changes that were made:

- The change to the `daemonize` library is non-controversial and could easily be upstreamed, however the library doesn't seem to be maintained anymore.
- The `hidapi-rs` crate doesn't support Android. I disabled it entirely in order to make Parity compile, but if we want to support hardware wallets we need to make it work eventually. This is probably a lot of work.
- The fix to `ring` is a small hack to make compiling the C code work ; however the change is probably quite controversial and I'm not sure that it will be upstreamable.
- The fix to `rocksdb` turns `fread_unlocked` into `fread`, which does exactly the same but is slightly slower. This is `fread_unlocked` doesn't seem to be supported by the Android NDK. We can probably introduce this small hack in our fork.
- There is no obvious alternative to `xdg-open` on Android. We could do it through the JNI but it's quite complicated. The easiest way to solve this properly is #4842.
- I turned `get_if_addrs` into a no-op in order to make it compile.

**Comment by niklasad1** [comment]
Cool, [libusb](https://github.com/libusb/libusb/wiki/FAQ#does-libusb-support-android) is supported by android but might require a rooted android phone to get access to the USB interface which probably eliminates this option as well.

**Comment by tomaka** [comment]
After https://github.com/paritytech/daemonize/pull/1 is merged, all major issues will be fixed except for the `ring` library.

There is however a problem that may require attention: in order to make things compile, we need some symbols from libc.so that were only added in Android 8.0 (API version 26) which was released in August 2017 and is not available on all devices yet.

Alternatively we can apply patches to the code so that these functions are not required. We should be able to get down to API version 24 (Android 7.0, August 2016) or even 21 (Android 5.0, November 2014).
