### ISSUE TITLE
parity --help | nonexistent

### ISSUE THREAD

**Issue by ldct** [paritytech/parity#7959]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.3-beta
> - **Which operating system?**: MacOS
> - **How installed?**: via homebrew
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: foundation

`parity --help | nonexistent` exits with

```
zsh: command not found: nonexistent

====================

stack backtrace:

Thread 'main' panicked at 'Error writing Error to stdout: Error { repr: Os { code: 32, message: "Broken pipe" } }', src/libcore/result.rs:916

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

[1]    45644 abort      parity --help |
       45645 exit 127   nonexistent
```

**Comment by 5chdn** [comment]
It's a rust bug and the upstream developer decided not to fix it.

https://github.com/rust-lang/rust/issues/24821

**Comment by 5chdn** [comment]
Duplicate of #7681

Duplicate of #7464

Duplicate of #4295
