### ISSUE TITLE
Thread "IO worker #0" error when launch parity with one node

### ISSUE THREAD

**Issue by mmysgp** [paritytech/parity#7960]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.0-unstable-5b4abec2d-20180219/x86_64-windows-msvc/rustc1.23.0
> - **Which operating system?**: Windows
> - **How installed?**: from source
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

C:\Users\wyo\parity\target\release>parity --chain spec.json -d ./validator0 --force-sealing --engine-signer "0x3771a5e5c4260ce28be09be4a8a7aa421e15704b" --port 30300 --jsonrpc-port 8540 --ui-port 8180 --dapps-port 8080 --ws-port 8546 --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts --password "node.pwds"
Option '--dapps-port' is deprecated. Please use '--jsonrpc-port' instead.
Spec json is invalid: missing field `gasLimitBoundDivisor` at line 18 column 2

C:\Users\wyo\parity\target\release>parity --chain spec.json -d ./validator0 --force-sealing --engine-signer "0x3771a5e5c4260ce28be09be4a8a7aa421e15704b" --port 30300 --jsonrpc-port 8540 --ui-port 8180 --dapps-port 8080 --ws-port 8546 --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts --password "node.pwds"
Option '--dapps-port' is deprecated. Please use '--jsonrpc-port' instead.
2018-02-21 09:09:03  Genesis constructor execution at 0000…0005 failed: Stack underflow CALLDATACOPY 3/0.
2018-02-21 09:09:03  Starting Parity/v1.10.0-unstable-5b4abec2d-20180219/x86_64-windows-msvc/rustc1.23.0
2018-02-21 09:09:03  Keys path .\validator0\keys\ethereum
2018-02-21 09:09:03  DB path .\validator0\chains\ethereum\db\5fffef45a185e03f
2018-02-21 09:09:03  Path to dapps .\validator0\dapps
2018-02-21 09:09:03  State DB configuration: fast
2018-02-21 09:09:03  Operating mode: active
2018-02-21 09:09:04  Configured for ethereum using AuthorityRound engine
2018-02-21 09:09:05  Genesis constructor execution at 0000…0005 failed: Stack underflow CALLDATACOPY 3/0.
2018-02-21 09:09:05  Error generating genesis epoch data: Cannot decode address[]. Snapshots generated may not be complete.
2018-02-21 09:09:06  Multi-threaded server is not available on Windows. Falling back to single thread.
2018-02-21 09:09:06  Multi-threaded server is not available on Windows. Falling back to single thread.
2018-02-21 09:09:11  Public node URL: enode://7b2a19f24039dc3c6375dc512228b83e0bb0ecf58782a926f39b50926ab0c21777ee6fb786e3ef6af1084d37e608e0f7f36f49936905b2a1091bffb63a487137@127.0.0.1:30300

====================

stack backtrace:
   0:     0x7ff763dbd2f1 - <error_chain::State as core::fmt::Debug>::fmt::h15e1534a21b8bb77
   1:     0x7ff763dbd83e - backtrace::capture::Backtrace::new::hd1eaee8a1d42286d
   2:     0x7ff76373d6d6 - panic_hook::set::haae178cbc34c7e59
   3:     0x7ff763de69d3 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:578
   4:     0x7ff763de6851 - std::panicking::begin_panic<alloc::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ff763de6732 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ff763de66a5 - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ff763def61f - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ff7637eff89 - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
   9:     0x7ff7638ad776 - <ethcore::engines::authority_round::AuthorityRoundParams as core::convert::From<ethjson::spec::authority_round::AuthorityRoundParams>>::from::h2596cda76d0b44ee
  10:     0x7ff7638b4c22 - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::generate_seal::ha3f8e145af276c9e
  11:     0x7ff7638f28d0 - <ethcore::miner::miner::Miner as ethcore::miner::MinerService>::update_sealing::ha1239e7e7a2235fd
  12:     0x7ff7638b2f7e - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::step::h2219e5c46a90e02c
  13:     0x7ff7638b2bc8 - <ethcore::engines::authority_round::TransitionHandler as ethcore_io::IoHandler<()>>::timeout::h84aae18fdd267046
  14:     0x7ff7637d3ae7 - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
  15:     0x7ff7637d4a4a - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
  16:     0x7ff763de7df2 - panic_abort::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_abort\lib.rs:40
  17:     0x7ff7637f0ff1 - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
  18:     0x7ff763de495c - std::sys::imp::thread::{{impl}}::new::thread_start
                        at C:\projects\rust\src\libstd\sys\windows\thread.rs:54
  19:     0x7ffc3b7b2774 - BaseThreadInitThunk

Thread 'IO Worker #2' panicked at 'proof produced by this engine; therefore it is valid; qed: Util(UtilError(Decoder(RlpExpectedToBeList), State { next_error: None, backtrace: None }))', src\libcore\result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-02-21 09:09:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs

..\parity\target\release>parity --chain spec.json -d ./validator0 --force-sealing --engine-signer "0x3771a5e5c4260ce28be09be4a8a7aa421e15704b" --port 30300 --jsonrpc-port 8540 --ui-port 8180 --dapps-port 8080 --ws-port 8546 --jsonrpc-apis web3,eth,net,personal,parity,parity_set,traces,rpc,parity_accounts --password "node.pwds"
Option '--dapps-port' is deprecated. Please use '--jsonrpc-port' instead.
2018-02-21 09:09:50  Genesis constructor execution at 0000…0005 failed: Stack underflow CALLDATACOPY 3/0.
2018-02-21 09:09:50  Starting Parity/v1.10.0-unstable-5b4abec2d-20180219/x86_64-windows-msvc/rustc1.23.0
2018-02-21 09:09:50  Keys path .\validator0\keys\ethereum
2018-02-21 09:09:50  DB path .\validator0\chains\ethereum\db\5fffef45a185e03f
2018-02-21 09:09:50  Path to dapps .\validator0\dapps
2018-02-21 09:09:50  State DB configuration: fast
2018-02-21 09:09:50  Operating mode: active
2018-02-21 09:09:50  Configured for ethereum using AuthorityRound engine
2018-02-21 09:09:51  Multi-threaded server is not available on Windows. Falling back to single thread.
2018-02-21 09:09:51  Multi-threaded server is not available on Windows. Falling back to single thread.

====================

stack backtrace:
   0:     0x7ff763dbd2f1 - <error_chain::State as core::fmt::Debug>::fmt::h15e1534a21b8bb77
   1:     0x7ff763dbd83e - backtrace::capture::Backtrace::new::hd1eaee8a1d42286d
   2:     0x7ff76373d6d6 - panic_hook::set::haae178cbc34c7e59
   3:     0x7ff763de69d3 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:578
   4:     0x7ff763de6851 - std::panicking::begin_panic<alloc::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ff763de6732 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ff763de66a5 - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ff763def61f - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ff7637eff89 - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
   9:     0x7ff7638ad776 - <ethcore::engines::authority_round::AuthorityRoundParams as core::convert::From<ethjson::spec::authority_round::AuthorityRoundParams>>::from::h2596cda76d0b44ee
  10:     0x7ff7638b4c22 - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::generate_seal::ha3f8e145af276c9e
  11:     0x7ff7638f28d0 - <ethcore::miner::miner::Miner as ethcore::miner::MinerService>::update_sealing::ha1239e7e7a2235fd
  12:     0x7ff7638b2f7e - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::step::h2219e5c46a90e02c
  13:     0x7ff7638b2bc8 - <ethcore::engines::authority_round::TransitionHandler as ethcore_io::IoHandler<()>>::timeout::h84aae18fdd267046
  14:     0x7ff7637d3ae7 - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
  15:     0x7ff7637d4a4a - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
  16:     0x7ff763de7df2 - panic_abort::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_abort\lib.rs:40
  17:     0x7ff7637f0ff1 - <ethcore_migrations::v10::ToV10 as migration::Migration>::migrate::h64265c4560c4484e
  18:     0x7ff763de495c - std::sys::imp::thread::{{impl}}::new::thread_start
                        at C:\projects\rust\src\libstd\sys\windows\thread.rs:54
  19:     0x7ffc3b7b2774 - BaseThreadInitThunk

Thread 'IO Worker #0' panicked at 'proof produced by this engine; therefore it is valid; qed: Util(UtilError(Decoder(RlpExpectedToBeList), State { next_error: None, backtrace: None }))', src\libcore\result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-02-21 09:09:40     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,  0 req/s,   0 µs

[Json file.zip](https://github.com/paritytech/parity/files/1742512/Json.file.zip)

**Comment by rphmeier** [comment]
A number of apparent issues with the `spec.json`:

> Spec json is invalid: missing field gasLimitBoundDivisor at line 18 column 2


> 2018-02-21 09:09:05 Genesis constructor execution at 0000…0005 failed: Stack underflow CALLDATACOPY 3/0.
2018-02-21 09:09:05 Error generating genesis epoch data: Cannot decode address[]. Snapshots generated may not be complete.

Can you post it here?

**Comment by phoax** [comment]
I think that in you Json file
`"0x0000000000000000000000000000000000000005": { "balance": "1", "constructor" : "0x3771a5e5c4260ce28be09be4a8a7aa421e15704b" },`
It should be the contract long bytecode instead of the `0x3771a5e5c4260ce28be09be4a8a7aa421e15704b ` address

**Comment by vieiralc** [comment]
@phoax Where can I find this contract long bytecode?

**Comment by phoax** [comment]
@vieiralc, you can put your Smart Contract on [remix.ethereum.org](https://remix.ethereum.org), then go on Compile > Details.
Then it should be on BYTECODE section, the long Bytecode is the object value.
