### ISSUE TITLE
The address is not a regular token contract address

### ISSUE THREAD

**Issue by quake3a** [paritytech/parity#7966]
> - **Which Parity version?**: 1.8.10
> - **Which operating system?**: Windows 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

Hi! 
I am trying to register a new erc20 token in the Parity Token Registry: https://etherscan.io/token/0x2ccbff3a042c68716ed2a2cb0c544a9f1d1935e1

However I get the following error:
The address is not a regular token contract address

Please suggest how to fix this issue!

**Comment by 5chdn** [comment]
You need a token supply > 0

**Comment by quake3a** [comment]
@5chdn sorry, however it is : 56,921,773.1719715 DMT ($42,551,928.46)
please check: https://etherscan.io/token/0x2ccbff3a042c68716ed2a2cb0c544a9f1d1935e1

**Comment by 5chdn** [comment]
Are you fully synchronized? What's your latest block number?

**Comment by quake3a** [comment]
@5chdn 
Unfortunately not
Sync freezes at 34%. Nothing helps
I have read #6372 and #6371, but am not 100% sure of the workaround.
Please assist

**Comment by 5chdn** [comment]
does wallet.parity.io work for you?

**Comment by quake3a** [comment]
Thx 
it works 👍

**Comment by quake3a** [comment]
hey @5chdn 
unfortunately even wallet.parity.io does not help.
I can't even sign the transaction for token registry
please help:
![photo_2018-03-05_13-25-57](https://user-images.githubusercontent.com/36665661/36973173-87b070be-207a-11e8-8911-6de849d13857.jpg)
![photo_2018-03-05_13-27-18](https://user-images.githubusercontent.com/36665661/36973175-8bb664f2-207a-11e8-9620-d3581ceb77e3.jpg)

**Comment by 5chdn** [comment]
What's the issue?

**Comment by quake3a** [comment]
I can not fully synchronized with the chain on wallet.parity.io and register the token... 
Can not sign the transaction for the registration.

**Comment by quake3a** [comment]
oh :( 
what you could recommend me ?

**Comment by 5chdn** [comment]
Couldn't you just sync a node and wait till it's done?

**Comment by quake3a** [comment]
Right, i can't sync a node.
Waiting for a 2 days since start. It's still 33%

**Comment by 5chdn** [comment]
33% of what? which is your latest block number?

**Comment by quake3a** [comment]
#4,321,010
and it is very very slowly raising

**Comment by 5chdn** [comment]
Are you on HDD or SSD?

**Comment by ammar4243** [comment]
I'm waiting for 8 days but Node still only Sycned 4,169,084.... how i can Increase the Speed of Nodes?

**Comment by Tbaut** [comment]
@ammar4243 This discussioin is closed. Please have a look at https://wiki.parity.io/FAQ#how-to-get-parity-in-sync-quickly or pay us a visit on our [Gitter channel](https://gitter.im/paritytech/parity) should you have further questions.
