### ISSUE TITLE
Having trouble sending tokens from parity to Binance

### ISSUE THREAD

**Issue by kkrasick** [paritytech/parity#7973]
_Before filing a new issue, please **provide the following information**._

> I'm running:
> v. 1.6.8-beta
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux --- Windows
> - **How installed?**: via installer / homebrew / binaries / from source --- installed from source I believe
> - **Are you fully synchronized?**: no / yes -- yes to my knowledge
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes -- yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

There reads an error message saying the transaction could not go through because there was not enough gas in which case I increased the gas substantially and continued to get the same error message.

Any additional help or guidance would be much appreciated so I can transfer my coins to another exchange

Thanks in advance for your help,
Kyle

**Comment by 5chdn** [comment]
Please upgrade to the latest version :)

**Comment by kkrasick** [comment]
Hi @5chdn - do I need to reinstall parity so that it will update to the latest version or is there a specific link I need to follow to upgrade?

Thanks for your help,
Kyle

**Comment by 5chdn** [comment]
Just install the new version over the old one :)
