### ISSUE TITLE
Unregistered my token ARG

### ISSUE THREAD

**Issue by pirasath1985** [paritytech/parity#7975]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:1.9
> - **Which operating system?**: Windows 
> - **How installed?**: via installer  from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?  ethereum 
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I would like to unregistered my token , I have so many error from my contract source code can you please removed my token registration , Please see below my token information

Sym: ARG
Name: Organicco
Contract Address : 0x4acedbb500bebf6119770e4ad03ffc2bae75cc1a.
Owner: Organicco ACC

Thank you for your help

**Comment by 5chdn** [comment]
Yes hold on, 5 min :)

**Comment by 5chdn** [comment]
And it's gone.

**Comment by pirasath1985** [comment]
Thank you for your help
