### ISSUE TITLE
What's the best way to debug the issue of Parity node not being able to receive new blocks from time to time

### ISSUE THREAD

**Issue by huangkuan** [paritytech/parity#7981]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.2
> - **Which operating system?**: Ubuntu 10.16
> - **How installed?**: bash <(curl https://get.parity.io -kL)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
I am running a parity node on Amazon cloud server and often run into the situation where the node is not receiving new blocks from time to time. I have to restart it and then it will start syncing again. Sometimes, even I restart, it will take 20 to 30 minutes to be able to resync. I have also made sure that the time on the server is synced.

I am porting new blocks into a traditional database and the constant interruption makes the process very difficult. Any tips would be greatly appreciated.

**Comment by Tbaut** [comment]
@huangkuan the best way would be to provide us with the logs of your node and a trace when this happens, running parity with `-lsync=trace` (very verbose).
Please make sure to update your client and report here if it happens again.
