### ISSUE TITLE
Add documentation for trace_filter rpc method

### ISSUE THREAD

**Issue by debris** [paritytech/parity#7989]
https://github.com/paritytech/parity/pull/6312#issuecomment-367993889

**Comment by 5chdn** [comment]
https://github.com/paritytech/wiki/blob/master/JSONRPC-trace-module.md#trace_filter

**Comment by debris** [comment]
it's about missing docs for these 2 fields:
https://github.com/paritytech/parity/pull/6312/files#diff-7f20173ee8722071ddcdd91cb7aca348R153

**Comment by folsen** [comment]
@Tbaut Could you please move this issue (or just fix it 😇❤️) to the wiki repo?
