### ISSUE TITLE
Parity ui shows "There are currently no accounts or addresses to display." when hardware wallet is present

### ISSUE THREAD

**Issue by 0v1se** [paritytech/parity#7996]
> I'm running:
>
> - **Which Parity version?**: 1.8.10
> - **Which operating system?**: Linux
> - **How installed?**: via pacman (arch linux)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**: yes

I've got hardware wallet (trezor).
Accounts tab shows my trezor wallet, but there is also
"There are currently no accounts or addresses to display."

minor issue

**Comment by 5chdn** [comment]
Could you provide a screenshot?

**Comment by creamjun** [comment]
solved.

I tried console command. "parity account list"
so I found parsing error in keystore.

I guess Parity sometimes saves the keystore incorrectly.

**Comment by 0v1se** [comment]
@5chdn sure

![image](https://user-images.githubusercontent.com/32102012/36833068-3ccca9f2-1d3f-11e8-808e-4240ca577fa7.png)

**Comment by 5chdn** [comment]
Closing as UI is discontinued. Please try with 1.10 and the Parity UI from https://github.com/Parity-JS/shell/releases
