### ISSUE TITLE
Why using TLA as key in Token Registry?

### ISSUE THREAD

**Issue by Aludirk** [paritytech/parity#8000]
Why using TLA as key in Token Registry? Is there any technical limitation?

Since there exist some tokens that using more than 3 letters for the abbreviation, and as I know there is no such limitation from the Ethereum community.

We have deployed a coin with 4 letters abbreviation and if I go to make a TLA for our token, it will lead to confusion for our users.

**Comment by 5chdn** [comment]
Hi, thanks for your comment, please discuss the new TokenReg here: https://github.com/paritytech/contracts/issues/83

**Comment by Aludirk** [comment]
is the TokenReg stop maintained?
404 for this repository: https://github.com/paritytech/contracts/

**Comment by 5chdn** [comment]
@Aludirk sorry it moved here: https://github.com/parity-contracts/token-registry
