### ISSUE TITLE
Stateless Sharding Implementation

### ISSUE THREAD

**Issue by jamesray1** [paritytech/parity#8001]
Update 26/3/2018: For details, please see https://github.com/Drops-of-Diamond/Diamond-drops. I have started development.

Previous details have been moved to the above repo.

**Comment by NikVolf** [comment]
Hi James! Currently no, but i’m going to start prototyping at end of March, will be happy to collaborate at that time

**Comment by jamesray1** [comment]
Hi Nikolay, cool, I'll probably get started before then, depending on how long it takes to learn Rust and familiarise with Parity.

**Comment by jamesray1** [comment]
@5chdn may you please leave this open to make it easier to find others to help with this?

**Comment by jamesray1** [comment]
I'm planning to fork https://github.com/Drops-of-Diamond/parity.

ATM I'm up to https://doc.rust-lang.org/book/second-edition/ch04-03-slices.html in the Rust book.

**Comment by postables** [comment]
I just recently began digging into Rust myself, and this sounds quite interesting. I'd be happy to help out if any way possible.

**Comment by debris** [comment]
if you need any intro to parity codebase and/or rust, just message me on riot @marek:matrix.parity.io or send a mail to marek@parity.io

**Comment by jamesray1** [comment]
@postables cool, here is a link to an intro doc: https://github.com/Drops-of-Diamond/parity/blob/Sharding/Sharding-info.md.

**Comment by jamesray1** [comment]
@debris thanks Marek, I sent you an email.

**Comment by poolisa01** [comment]
Currently learning Rust, willing to support in whatever form I can. Let's make #ETH Scale!

**Comment by jamesray1** [comment]
@poolisa01 cool, get back to me when you finish! (As outlined above, I'm still learning it too.)

**Comment by postables** [comment]
Thanks James, I'll take a look over it Tonight!

**Comment by jamesray1** [comment]
Thanks Afri.

**Comment by misrab** [comment]
Am getting increasingly into Rust (by programming basic algos) and Sharding. Reach out whenever!

**Comment by jamesray1** [comment]
@misrab, best if I start working on it myself before I actually talk to others about working on it. But others are welcome to take the initiative and start working on it before I do.

**Comment by jamesray1** [comment]
Another update: https://gitter.im/Drops-of-Diamond/Lobby?at=5ab474e15f188ccc15e892ff

**Comment by jamesray1** [comment]
I just updated the header comment.

**Comment by jamesray1** [comment]
Hi everyone, work is well underway. I started developing the sharding manager contract in Rust, then realised that it was better to develop just one SMC in Vyper, which is easier to develop while referring to the [sharding phase 1 spec](https://ethresear.ch/t/sharding-phase-1-spec/1407). Feel free to reach out on Gitter [here](https://gitter.im/Drops-of-Diamond/Development) for dev queries or [here](https://gitter.im/Drops-of-Diamond/Lobby). There will be lots of work to do on sharding over the next few years at least, and more help is needed!

**Comment by folsen** [comment]
@jamesray1 I'm going to leave this issue open because I want to hear updates, if you want to move your updates to another format please close this issue as it is too vague/broad for anyone to pick and work on directly. I will however change the labels.

**Comment by jamesray1** [comment]
For updates you can follow https://twitter.com/DropsOfDiamond, releases will be published there (there's a new release today on blob serialization). For plans you can have a look at the issues and projects in https://github.com/Drops-of-Diamond/diamond_drops.
