### ISSUE TITLE
Thread '<unnamed>' panicked at 'overflow converting duration to nanoseconds'

### ISSUE THREAD

**Issue by jennazenk** [paritytech/parity#8003]
> - **Which Parity version?**: v1.9.0-beta-53ec114-20180125/x86_64-macos/rustc1.23.0
> - **Which operating system?**: MacOS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

When running `parity --chain foundation`, I got the following: 

```
stack backtrace:

Thread '<unnamed>' panicked at 'overflow converting duration to nanoseconds', src/libcore/option.rs:874
```

Restarting the node fixed it, just letting you guys know!

**Comment by debris** [comment]
It's probably quite serious. There are multiple places in our codebase when we create `Duration::from_secs` and add it to `Instant` or `SystemTime`. rust std executes the addition by converting `Duration` to nanoseconds which may cause unhandled overflows.

**Comment by azulmarino** [comment]
Hit on Parity v1.9.4-20180228 beta

**Comment by folsen** [comment]
The issue was identified to probably come from expontential backoff time additions in auto-updater. There may however be other cases where it's from adding times with different resolutions, see rust-lang/rust#48980
