### ISSUE TITLE
Parity 1.8.6+ increased orphan rates

### ISSUE THREAD

**Issue by Njcrypto** [paritytech/parity#8004]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6stable, 1.8.9stable
> - **Which operating system?**: Ubuntu Server 16.04.3
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

Expected behavior: latency driven orphans translate into uncles.
Actual behavior: latency driven orphans stay as orphans, even with an uncongested network and not full uncle queue on orphaned blocks.

I am at a loss for how to trouble shoot this problem. Prior to the recent upgrades to 1.8.6+ we only receive orphan blocks during times of EXTREME network congestion where we are typically the third orphan in a block, and fall outside the uncle reward.

Since the upgrades, and our peer counts getting demolished (as discussed in other threads), we are observing an orphan rate closer to 6%, with uncle rates declining dramatically. This tells me that blocks that would have historically been uncles are coming through as orphans.

Internal pool is large, and we haven't historically had this issue. The only outside communication through our facilities is through the node servers, and there is no latency issue on these machines. That's what makes me believe this has to be a parity driven issue?

Bueller? Bueller?

**Comment by folsen** [comment]
@Njcrypto We did some investigation on our side but couldn't think of any potential cause. Does this issue still persist? If so we may need some help investigating.
