### ISSUE TITLE
No sync at all

### ISSUE THREAD

**Issue by JSTRDI** [paritytech/parity#8013]
> I'm running: 4x1080Ti, i7 7980X, 128GB DDR4
>
> - **Which Parity version?**: v1.8.10-stable
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

My Parity doesn't want to sync. http://prntscr.com/iktd61
Mined all night and no changes, no ETH on the wallet.

Node log:
[28.02.2018, 11:53:40]
 Syncing #4316098 2390…bf09 8 blk/s 952 tx/s 46 Mgas/s 0+ 405 Qed #4316506 25/25 peers 7 MiB chain 251 MiB db 41 MiB queue 10 MiB sync RPC: 1 conn, 14 req/s, 43102 µs

[28.02.2018, 11:53:30]
 Syncing #4316009 c2f9…d2fe 9 blk/s 1004 tx/s 54 Mgas/s 0+ 397 Qed #4316410 25/25 peers 7 MiB chain 251 MiB db 39 MiB queue 10 MiB sync RPC: 1 conn, 15 req/s, 36955 µs

[28.02.2018, 11:53:20]
 Syncing #4315909 c70b…81a3 9 blk/s 1009 tx/s 55 Mgas/s 0+ 402 Qed #4316315 25/25 peers 6 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 23 req/s, 56283 µs

[28.02.2018, 11:53:10]
 Syncing #4315812 7f8e…b3e3 9 blk/s 1051 tx/s 53 Mgas/s 0+ 439 Qed #4316252 25/25 peers 7 MiB chain 251 MiB db 42 MiB queue 10 MiB sync RPC: 1 conn, 23 req/s, 56035 µs

[28.02.2018, 11:53:00]
 Syncing #4315715 b76d…cc5f 9 blk/s 914 tx/s 49 Mgas/s 0+ 408 Qed #4316125 25/25 peers 6 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 23 req/s, 42635 µs

[28.02.2018, 11:52:50]
 Syncing #4315621 5563…cec1 10 blk/s 928 tx/s 60 Mgas/s 0+ 436 Qed #4316061 25/25 peers 7 MiB chain 251 MiB db 42 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 100 µs

[28.02.2018, 11:52:40]
 Syncing #4315514 fb43…dfd2 10 blk/s 870 tx/s 63 Mgas/s 0+ 449 Qed #4315966 25/25 peers 7 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 100 µs

[28.02.2018, 11:52:30]
 Syncing #4315406 004c…eeb1 10 blk/s 987 tx/s 62 Mgas/s 0+ 463 Qed #4315872 25/25 peers 7 MiB chain 252 MiB db 41 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 100 µs

[28.02.2018, 11:52:20]
 Syncing #4315304 cbbb…0c95 8 blk/s 1041 tx/s 53 Mgas/s 0+ 503 Qed #4315808 25/25 peers 6 MiB chain 251 MiB db 43 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 100 µs

[28.02.2018, 11:52:10]
 Syncing #4315216 0468…38ed 8 blk/s 1160 tx/s 49 Mgas/s 0+ 495 Qed #4315712 25/25 peers 6 MiB chain 251 MiB db 43 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 100 µs

[28.02.2018, 11:52:00]
 Syncing #4315131 d6b1…f771 7 blk/s 1103 tx/s 45 Mgas/s 0+ 452 Qed #4315585 25/25 peers 6 MiB chain 251 MiB db 42 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 100 µs

[28.02.2018, 11:51:50]
 Syncing #4315063 d5ad…d159 6 blk/s 1006 tx/s 44 Mgas/s 0+ 426 Qed #4315491 25/25 peers 6 MiB chain 251 MiB db 43 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 102 µs

[28.02.2018, 11:51:40]
 Syncing #4314994 48f8…dbbe 6 blk/s 933 tx/s 40 Mgas/s 0+ 334 Qed #4315331 25/25 peers 6 MiB chain 251 MiB db 39 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 92 µs

[28.02.2018, 11:51:30]
 Syncing #4314929 e341…aae0 7 blk/s 916 tx/s 48 Mgas/s 0+ 334 Qed #4315267 25/25 peers 6 MiB chain 251 MiB db 41 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 72 µs

[28.02.2018, 11:51:20]
 Syncing #4314855 6108…8e16 8 blk/s 850 tx/s 43 Mgas/s 0+ 315 Qed #4315172 25/25 peers 6 MiB chain 251 MiB db 39 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 72 µs

[28.02.2018, 11:51:10]
 Syncing #4314767 6e07…b465 8 blk/s 922 tx/s 45 Mgas/s 0+ 340 Qed #4315109 25/25 peers 6 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 2 req/s, 92 µs

[28.02.2018, 11:51:00]
 Syncing #4314681 4ab0…af9f 10 blk/s 882 tx/s 64 Mgas/s 0+ 360 Qed #4315045 25/25 peers 6 MiB chain 251 MiB db 39 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 92 µs

[28.02.2018, 11:50:50]
 Syncing #4314575 491b…d2e2 11 blk/s 823 tx/s 66 Mgas/s 0+ 406 Qed #4314983 25/25 peers 6 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 72 µs

[28.02.2018, 11:50:40]
 Syncing #4314463 1e8c…3a1e 10 blk/s 915 tx/s 64 Mgas/s 0+ 486 Qed #4314951 25/25 peers 6 MiB chain 251 MiB db 43 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 100 µs

[28.02.2018, 11:50:30]
 Syncing #4314354 298e…b688 12 blk/s 970 tx/s 65 Mgas/s 0+ 498 Qed #4314855 25/25 peers 7 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 92 µs

[28.02.2018, 11:50:20]
 Syncing #4314233 c0b1…1d52 9 blk/s 960 tx/s 60 Mgas/s 0+ 522 Qed #4314759 25/25 peers 6 MiB chain 252 MiB db 41 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 100 µs

[28.02.2018, 11:50:10]
 Syncing #4314136 d7b1…af37 9 blk/s 1058 tx/s 59 Mgas/s 0+ 495 Qed #4314632 25/25 peers 6 MiB chain 251 MiB db 39 MiB queue 11 MiB sync RPC: 1 conn, 1 req/s, 100 µs

[28.02.2018, 11:50:00]
 Syncing #4314042 94ff…4d86 11 blk/s 980 tx/s 64 Mgas/s 0+ 493 Qed #4314538 25/25 peers 6 MiB chain 251 MiB db 41 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 124 µs

[28.02.2018, 11:49:49]
 Syncing #4313932 e6f0…41c9 10 blk/s 1053 tx/s 71 Mgas/s 0+ 477 Qed #4314410 25/25 peers 6 MiB chain 251 MiB db 40 MiB queue 10 MiB sync RPC: 1 conn, 0 req/s, 124 µs

[28.02.2018, 11:49:39]
 Syncing #4313823 fc5d…45b8 10 blk/s 1017 tx/s 58 Mgas/s 0+ 426 Qed #4314251 25/25 peers 6 MiB chain 251 MiB db 39 MiB queue 10 MiB sync RPC: 1 conn, 1 req/s, 124 µs

**Comment by 5chdn** [comment]
Looks good! `10 blk/s 1053 tx/s 71 Mgas/s` means your client processes 10 blocks with 1053 transactions and 71 million gas per second. Patience, young padawan!
