### ISSUE TITLE
Parity kills my Internetconnection

### ISSUE THREAD

**Issue by theBergmann** [paritytech/parity#8020]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.7
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: homebrew / binaries
> - **Are you fully synchronized?**: not sure, default
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

When I start Parity, after a few seconds my network is shut down. My router (fritzbox) restarts / loses internet / telefone connection.

I have a relatively slow internet connections, something like 20mbit/s, which is why I guess an initial data burst kills my connections. Is there a way to reduce data spikes?

After trying some times, it finally works.

**Comment by jamesray1** [comment]
Are you using a WiFi or Ethernet connection. If the latter, try the former.

**Comment by theBergmann** [comment]
I use WiFi. Unfortunately, I live in a rural area of High Tech Germany and my max 20mbit is the best I can get here.

It seems Parity pushes the download rate to a limit, which either shuts down my router, slows down my internet at all or throttles the bandwidth of my system as a client of the router.

Here's a screenshot of the burst in bandwidth with minimal connectivity after. I guess this slows down the sync at all. After running parity, my internet was literally unusable until I rebooted.

https://btcoins.files.wordpress.com/2018/03/parity-conn.png

**Comment by theBergmann** [comment]
Short update: I installed trickle (https://wiki.ubuntuusers.de/Trickle/) do restrict bandwidth of parity, it is easy to use, and it seems to work relatively well. So I guess you can close this case.

**Comment by jamesray1** [comment]
Great, you should be able to close it yourself! I don't have write access so I can't.

My speed test result: 
<a href="http://www.speedtest.net/result/7100960864"><img src="http://www.speedtest.net/result/7100960864.png"/></a>

Parity syncing:
![screenshot from 2018-03-01 22-29-58](https://user-images.githubusercontent.com/16969914/36842554-1d48d874-1da0-11e8-9bd3-9fef40b1e12b.png)

(The internet is too slow while I'm using it, so I just pause it and run it overnight.) However, I may also give Trickle a try!

**Comment by jamesray1** [comment]
Looking at `trickle -h`, it seems like there is no way to set the bandwidth conditionally. For instance, use as much bandwidth as is available after all other appplications in use; don't compete with bandwidth of other applications.

**Comment by theBergmann** [comment]
Oh, you have an even slower internet as me. Strange that parity only kills my connection. Maybe a problem with the router or the ISP. But since I use trickle it runs stable and without effecting my internet.

**Comment by theBergmann** [comment]
I did not try -h. My try the configuration

trickle -d 950 -u 165 -t 0.2 -l 20 -w 256 parity

which still produces some spikes (I expected it would not), but at least it keeps bandwidth consumption on a level which does not affect the performance of the rest of my system.

**Comment by jamesray1** [comment]
I used `trickled -d 5000 -u 400`, then
```
$ cd parity/target/release
$ trickle ./parity
```
I can now use the internet without it slowing to a crawling halt!

**Comment by jamesray1** [comment]
The `-h` option is just for help.

**Comment by theBergmann** [comment]
Cool. I asked for help, and you tried to help, and we ended with getting both help. Love this.

5000 seems to high, (=40mbit), but if it works ...

**Comment by jamesray1** [comment]
I made a PR: #25.
