### ISSUE TITLE
add tests for ethstore-cli

### ISSUE THREAD

**Issue by debris** [paritytech/parity#8027]
to avoid issues like #8026

**Comment by izgzhen** [comment]
I'd like to help on this issue :)

**Comment by debris** [comment]
great! :)

**Comment by izgzhen** [comment]
I wonder if we should move `execute` in `main.rs` to library, which can be pulled in conveniently to test code, or should I invoke the built binary directly and test it as a process?

**Comment by debris** [comment]
I would prefer tests invoking built binary
