### ISSUE TITLE
JSON-RPC: Wrong specification or implementation?

### ISSUE THREAD

**Issue by gagarin55** [paritytech/parity#8028]
1.
According to documentation of [eth_getBlockByNumber](https://github.com/paritytech/wiki/blob/master/JSONRPC-eth-module.md#eth_getblockbynumber) when `pending` block requested result should have null in `number` field.

> number: QUANTITY - the block number. null when its pending block.

But in the code of Parity I've found that it always [returns number of next block](https://github.com/paritytech/parity/blob/ec7282d05c0639064e0b5ea8cfbd08a0f6af4375/ethcore/src/block.rs#L261) :

```
impl<'x> OpenBlock<'x> {
	/// Create a new `OpenBlock` ready for transaction pushing.
	...
        let number = parent.number() + 1;
        ...

```

Could you please clarify can `number` has `null` value or not ?

2.

Another question is about `miner` field. Could it has `null` value or not ?

**Comment by 5chdn** [comment]
Pull requests welcome :)

**Comment by sorpaas** [comment]
@gagarin55 Looks like `miner` field cannot be `null`. If I understand it correctly, if it is not set, the default will be `0x00...00`.
