### ISSUE TITLE
Increase Gas-floor-target on Kovan to 8000000

### ISSUE THREAD

**Issue by retotrinkler** [paritytech/parity#8037]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.3-beta-804ddfe-20180219/x86_64-linux-gnu/rustc1.24.0
> - **Which operating system?**: Linux
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**actual**

Gas-floor-target at 4700000

    --gas-floor-target=[GAS]
        Amount of gas per block to target when sealing a new block. (default: 4700000)

**expected**

Gas-floor-target at 8000000 https://ethstats.net/

**Comment by 5chdn** [comment]
Might be worth to bump the default for all networks to 8M.

**Comment by 5chdn** [comment]
https://github.com/kovan-testnet/config/pull/8

**Comment by rphmeier** [comment]
> Increase Gas-floor-target on Kovan to 8000000

changing network parameters only requires collaboration on the part of authorities, not changing client defaults.
