### ISSUE TITLE
Documentation Page Github-Hint 404 Error

### ISSUE THREAD

**Issue by ashellwig** [paritytech/parity#8040]
Version Information (I know this is irrelevant but in keeping with tradition, why not give the details of my `Parity` version anyway)
> I'm running:
> - **Which Parity version?**: v1.10.0-unstable-c060d9584-20180209/x86_64-linux-gnu/rustc1.24.1
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: irrelevant

Issue details:
> **actual**
> * Error: 404 File Not Found
![parity-github-hint-issue](https://user-images.githubusercontent.com/25649488/36901395-3d17b118-1de4-11e8-809d-013b27df5c4c.png)

> **expected behavior**:
> * A page to render containing information

> **steps to reproduce**:
> * Visit the documentation home page at [https://wiki.parity.io/](https://wiki.parity.io/)
> * Click [Parity GitHub Hint](https://wiki.parity.io/Parity-github-hint) under `Developing` > `Writing DApps`

**Comment by kirushik** [comment]
Hey, @ashellwig, nice catch!

Our wiki lives in a separate repo [paritytech/wiki](https://github.com/paritytech/parity), I've already created a PR to fix it there: paritytech/parity#28
