### ISSUE TITLE
Getting blocks and transactions performance

### ISSUE THREAD

**Issue by adyshimony** [paritytech/parity#8043]
Hi all,

I am running v1.9.3-beta on ubuntu, fully sync.
Running as  parity --no-warp --cache-size 2048, network ethereum.
Web3 1.0.0-beta.27.

I am indexing all transactions to a local db, for fast data query.

In the last blocks, the fetching is very very slow... I guess cause its a lot of data.
Asking for 100 block (include transactions) takes around 10 seconds. 
The real problem is running on every transaction from the blocks, getting transaction receipt.

For tx for blocks #5176100 - #5176199 : 17966, duration in sec:, 141.098
I am saving to DB in bulk mode, so I need to wait for all results to return before save.
I am fetching all transaction receipt for every block, wait (promise.all) and the the next block.
Trying to wait for all the transaction (17966) results in longer times.

Is there anything I can do to make it faster?
Any configuration?
I am working with IPC connection.

Thanks,
Ady.

**Comment by J-A-M-E-5** [comment]
What I'm doing is I am caching those calls. This way I only need to run them once slowly. I wrote my own file format to handle it as I didn't want to have 6,000,000+ files representing every block, or every block of transaction receipts/logs. You basically record everything to some big files, and note the position/length of what you recorded. Can start recording the JSON, but obviously a future refactor would be to save the raw data as it would be smaller. Once you have these files this is a good source to build your database from which you'll probably do quite a lot when testing, and also for a backup to generate your database without worrying about node syncing times or even running a node.

**Comment by adyshimony** [comment]
Thanks, actually this is what I am doing, indexing it to couchdb. 
I wanted to index it faster if possible.
