### ISSUE TITLE
Change Token Decimals

### ISSUE THREAD

**Issue by bbjunaid** [paritytech/parity#8044]
Hi,

I registered a token RFR:

Contract: 0xd0929d411954c47438dc1d871dd6081f5c5e149c

I used wrong decimal places 18. It should be 4.

Can someone please fix it, I cannot seem to edit token registry.

Thanks,
Bilal

**Comment by bbjunaid** [comment]
Well?

**Comment by 5chdn** [comment]
Removed it. You can correct the decimals now :)
