### ISSUE TITLE
Disk utilization with pruning

### ISSUE THREAD

**Issue by kondratovich** [paritytech/parity#8049]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.8.11-stable-21522ff-20180227/x86_64-linux-gnu/rustc1.24.0
> - **Which operating system?**: Linux
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm using pruning option `fast`. While sync, parity has been utilized constant disk space. After sync disk utilization started to grow up like on `archive` option.
Is there an option to configure parity to clean up old blocks over time? So disk utilization become bounded.

Thank you.

**Comment by rphmeier** [comment]
currently there is no support for block pruning, only state. Still, the state is expected to grow over time so even that won't give you bounded disk usage.
