### ISSUE TITLE
Parity doesn't maintain database upon upgrade

### ISSUE THREAD

**Issue by gravcat** [paritytech/parity#8050]
> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: Ubuntu Linux 16.04
> - **How installed?**: via installer / repository
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: foundation
> - **Did you try to restart the node?**: yes

Issue:

Parity resyncs from scratch when an upgrade is performed. I use the same arguments including the same data directory when performing the upgrade, but the node re-syncs from scratch as if it never noticed.

Expected behavior:

Parity picks up where it left off prior to the upgrade, continuing with the existing working data.

----

Has anyone else experienced this issue, and is there a workaround or procedure I'm simply not aware of to maintain the data? Especially important if I want to upgrade rapidly, resyncing takes a long time even on big servers.

**Comment by 5chdn** [comment]
Please share how you configure your node and how you upgraded it.
