### ISSUE TITLE
Transaction counter is updated, but no transactions visible

### ISSUE THREAD

**Issue by gmile** [paritytech/parity#8063]
I'm running:

- **Which Parity version?**: v1.9.2-20180214 beta
- **Which operating system?**: Linux
- **How installed?**: binaries (via docker-compose)
- **Are you fully synchronized?**: yes
- **Which network are you connected to?**: private
- **Did you try to restart the node?**: yes

---

Expected behaviour:

* I can see transactions for a given address,
* I can see created contracts.

Observed behaviour:

* I cannot see transactions for a given address,
* I cannot see created contracts.
* I can see transaction counter going up.
* I can see an approval dialog window asking me for password every time I make a transaction.

---

I'm trying to issue some "Contract creation" transactions. Some observations: 

* parity UI will ask me to approve a transaction by showing a dialog window prompting for a password,
* parity UI will not show transactions in questions under account I'm issuing transactions from,
* new contract addresses will not appear anywhere,
* new contracts will not appear under "Contracts" tab,
* _N best block_ in the header is growing, I take that as the mining is happening,
* transaction receipts look like [this](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-receipt-1-json) and [this](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-receipt-2-json), and have `logsBloom` with all zeroes in them. **This is probably important**, but I don't know how to interpret it – transactions are not actually included in the chain for some reason? Not enough gas or smth?
* at the same time sending contracts to ropsten network seems works fine ([1](https://ropsten.etherscan.io/tx/0xad33bc1456f7b60da7d945164005737a0df5c3bc0ff3b1dda1130db27f9c7a6d),[2](https://ropsten.etherscan.io/tx/0x1bf6cd12aa64f0e14869405356bfe46d567fc0e03f52431f810c974c830675e1) and [3](https://ropsten.etherscan.io/tx/0x3a332b93ddd8a440bcfed28c24787c99fcae8d359e056a554433b48d606d05a2)).

My private blockchain consists of 3 parity nodes + 1 parity "client" node. All parity nodes are identical are ran with the following command line options (each node has slightly different `authority.toml` contents, see below):

```
parity --chain /parity/spec.json --config /parity/authority.toml --fat-db=on -d /parity/data
```

Parity client ran with the following command line options:

```
parity --geth --chain /parity/spec.json --config /parity/client.toml -d /parity/data --fat-db=on --ui-interface "0.0.0.0" --ui-no-validation ui
```

Here is the configs:

* [spec.json](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-spec.json)
* [authority-1.toml](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-authority-1-toml)
* [authority-2.toml](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-authority-2-toml)
* [authority-3.toml](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-authority-3-toml)
* [client.toml](https://gist.github.com/gmile/6e0977348763e688566f3f5613021b55#file-client.toml)

I'm posting this upfront in case the issue is very common and someone experienced can catch it really quickly. Meanwhile I'll try to come up with reproducible example.

**Comment by vincentserpoul** [comment]
I have the same issue as you, running 1.9.3, private PoA setup.
the mining seems to be happening, but no contract address is given.

**Comment by gmile** [comment]
@vincentserpoul I was able to work around this by creating contracts from the UI, that's all I know...

I'd love to find see documentation covering contract creation by means of JSON-RPC, but I was unable to find any. Meanwhile I'll close this issue to keep the tracker clean, since the problem was somewhat worked around.
