### ISSUE TITLE
missing transaction history

### ISSUE THREAD

**Issue by pdarcos** [paritytech/parity#8064]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity v1.9.0-20180125 beta
> - **Which operating system?**: Linux Mint 18.1 Serena
> - **How installed?**: via deb package
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Using a Nano S hardware wallet.
After installing the debian package it took me a long time to sync (days) but now that it is synced I'm surprised to see only 1 transaction in the transaction history.

If I look at the same address in etherscan.io in another tab the whole transaction history is correctly displayed so I assume this must be a parity bug.

In Parity, my Nano S also shows "4 outgoing transactions" although I have no clue what that is about since I shouldn't have any outgoing transactions at the moment.
I also don't see any of my ERC20 tokens displayed anywhere but that may be related to the missing transactions, no?

Any help?

Thanks

**Comment by 5chdn** [comment]
The UI is discontinued, please test 1.10 with https://github.com/Parity-JS/shell/releases and let me know if this issue persists.
