### ISSUE TITLE
`Method not found` while trying to invoke `importRawKey`

### ISSUE THREAD

**Issue by aleksuss** [paritytech/parity#8069]
> I'm running:
> - **Which Parity version?**: 1.8.11
> - **Which operating system?**: Linux
> - **How installed?**: docker container
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

While I trying to invoke method `importRawKey` I get an error from partity like this: 
 ```
> web3.personal.importRawKey("0x000000....0000", "password")
Error: Method not found
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

Is the method removed ? If so, does exist another way to import an account from a private key ? Thanks

**Comment by stanislaw-raczynski-dac** [comment]
I guess @aleksuss realized the solution was obvious and closed the issue, but it would have been nice to know the solution anyway.

**Comment by joshua-mir** [comment]
@stanislaw-raczynski-dac https://wiki.parity.io/JSONRPC-parity_accounts-module#parity_newaccountfromsecret
