### ISSUE TITLE
gasprice is higher than https://ethstats.net/

### ISSUE THREAD

**Issue by bitcodernull** [paritytech/parity#8072]
_Before filing a new issue, please **provide the following information**._

> I'm running:
> 
> - **Which Parity version?**: 1.8.11
> - **Which operating system?**: linux
> - **How installed?**: binaries 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum /
> - **Did you try to restart the node?**:yes

_Your issue description goes here below.

i get the gasprice by  eth_gasPrice  api, the gas price is higher than https://ethstats.net/
https://ethstats.net/ is 3~4 Gwei,   eth_gasPrice return 20Gwei

thanks

**Comment by 5chdn** [comment]
I don't know how ethstats is calculating the gas price, but you can always manually adjust it if you think it's too high.
