### ISSUE TITLE
Tutorial Part 6

### ISSUE THREAD

**Issue by vieiralc** [paritytech/parity#8080]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.9.4-20180228 beta
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: I don't know, Here says FOUNDATION
> - **Did you try to restart the node?**: 

I'm following the parity dapp tutorial part 6 which is creating a new contract. But I can't deploy any contracts because I don't have ethers. I tried to connect to ropsten but I get the message "You are not connected to any peers. There is most likely some network issue. Fix connectivity."

How can I get some ethers to deploy smart contracts and then interact with them on parity??

**Comment by Tbaut** [comment]
Did you get connected to some peers in the mean time ?
If not, please follow the instruction listed [here](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#what-can-i-do-when-parity-has-trouble-getting-in-sync) and more specifically step 2, making sure that your time is exact.

Once you are fully synced, you can get some rEth (Ropsten Ether) using faucets such as [Metamask faucet](https://faucet.metamask.io/), [faucet.bitfwd](https://faucet.bitfwd.xyz/) or [faucet.ropsten](http://faucet.ropsten.be:3001/)

**Comment by rphmeier** [comment]
It's also possible to use a local "dev" chain where only you are connected, and transactions are mined instantly, by running with `parity --config dev`. There is an account in the UI there with empty password that has a huge premine.

**Comment by vieiralc** [comment]
@Tbaut No I didn't connect to any peers. My pc is 3.1 seconds late. I'll try to sync here, thanks

**Comment by vieiralc** [comment]
@rphmeier I've tried to run `parity --config dev` but I get the error:  There was an error reading your config file at: dev The sustem cannot find the file specified.

**Comment by vieiralc** [comment]
@Tbaut  How do I sync my pc with time.is? It is just change the time manually? Isn't there any other way? Because it's always a few milliseconds late D:

**Comment by vieiralc** [comment]
@Tbaut Ok I have it  fully synced now
