### ISSUE TITLE
Is public node is not supported in 1.9?

### ISSUE THREAD

**Issue by hopkinskong** [paritytech/parity#8083]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.4-beta
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Is 1.9 does not support public node? I don't know where should I import my account:
![image](https://user-images.githubusercontent.com/2718385/37269846-4c6b0a4a-2607-11e8-9135-3a6e056969ff.png)

The status bar at the top seems not displaying information correctly (0 peers):
![image](https://user-images.githubusercontent.com/2718385/37269874-640cf780-2607-11e8-8cb9-eb705ea9eaf2.png)

Bunch of JS errors (I suppose it's JSON-RPC errors):
![image](https://user-images.githubusercontent.com/2718385/37269891-75c23f1c-2607-11e8-8989-0ff20f3f73d6.png)

Running with:
`./parity --warp --mode active --tracing off --pruning fast --db-compaction hdd --cache-size 1024 -d ../../parity_data --public-node --ui-interface 127.0.0.1 --ui-port 20000 --ws-interface 127.0.0.1 --ws-port 21000 --ws-origins http://127.0.0.1:21000 --jsonrpc-port 22000`

Note that in `1.8.x`, I don't need to open `jsonrpc-port` as blocking `:8545` still no issue.

**Comment by hopkinskong** [comment]
@5chdn 

Viewing "Node Status" also result in blank page, with following errors:
![image](https://user-images.githubusercontent.com/2718385/37270022-0b159da2-2608-11e8-97d4-f324587edaf1.png)

**Comment by Tbaut** [comment]
@hopkinskong I could not reproduce the issue. Could you make sure that you only run 1 instance of the UI (no other tab with parity and no other browser ?).
It looks like you have a port conflict, could you make sure there are not used by another application or try using other ports ?

**Comment by hopkinskong** [comment]
@Tbaut 

The issue is reproducible when I am using **SSH Tunneling**:
 
![image](https://user-images.githubusercontent.com/2718385/37287731-721ade26-2640-11e8-8aa0-01034da879e7.png)

Is there other ports I need to forward besides from these 3 ports?

Viewing locally seems better (not fine though...) as despite there is something to see, the information appears to be incorrect:
![image](https://user-images.githubusercontent.com/2718385/37287889-d1eef738-2640-11e8-9801-a5f6b3c85a50.png)

The parity is running with 24/25 nodes connected:
![image](https://user-images.githubusercontent.com/2718385/37287938-f5ccb94c-2640-11e8-936d-b55fc1c0d8dc.png)

BTW, How do I add my account in public node?

**Comment by hopkinskong** [comment]
@Tbaut Some extra (weird) info.

If I view the *Node Status* page locally first, **THEN** view the *Node Status* page via SSH tunnel, the page will appear (but still with invalid information). The page will still work via SSH tunnel until I restart parity, then the page will immediately disappear. Loading the page locally first will then some sort of "activate" the page again and allow SSH tunnel viewing that page...

**Comment by 5chdn** [comment]
Yes, public node is discontinued.
