### ISSUE TITLE
Panic (deadlock) on Parity shutdown when using AuthorityRound engine

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity#8088]
Environment: linux + branch with up-to-date master merged-in (`origin/secretstore_doc_key_via_contract`) + PoA of three nodes (configs are generated using [this script](https://github.com/svyatonik/sstore_test/blob/master/poa_integration/config_generate_list.sh)).

When trying to stop parity instances, I often see:
```bash
thread '<unnamed>' panicked at 'failed to join thread: Resource deadlock avoided (os error 35)', /checkout/src/libstd/sys/unix/thread.rs:178:12
```

The reason is that we're trying to drop IO service from IO worker thread. Here are stacks of two threads that are trying to join each other: https://gist.github.com/svyatonik/5f1251da6990df46b7033ff843b7a9ee . In this case, IO worker thread was the last thread holding reference to the `Arc<AuthorityRound>` [in this block](https://github.com/paritytech/parity/blob/58a1671076246a8478581e0508ffc624217ea242/ethcore/src/engines/authority_round/mod.rs#L705). `Arc<AuthorityRound>,` in turn was the last holder of IO service reference => when `Arc<AuthorityRound>` goes out of scope, we're sending `IoMessage::Shutdown` message to [service thread](https://github.com/paritytech/parity/blob/58a1671076246a8478581e0508ffc624217ea242/util/io/src/service.rs#L446) and start joining this thread. The [reaction to this message]() is [clearing](https://github.com/paritytech/parity/blob/58a1671076246a8478581e0508ffc624217ea242/util/io/src/service.rs#L266) and [joining](https://github.com/paritytech/parity/blob/58a1671076246a8478581e0508ffc624217ea242/util/io/src/worker.rs#L136) all the IO workers (including the one who's currently dropping the service) => deadlock, which is detected by `pthread_join`.

**Comment by saulbein** [comment]
Having same issue on linux environment, with Parity 1.10.4, on Kovan, with large number of addresses
