### ISSUE TITLE
Is it possible to sync up to a certain block and then idle?

### ISSUE THREAD

**Issue by J-A-M-E-5** [paritytech/parity#8091]
I've read the doc and wiki and don't see a way so I guess this will require a code modification, which being new to Rust I'm willing to try and experiment with.

Let me explain what I'm trying to do. I am processing all transactions logs with some code and I would like to be able to set a low pruning number, e.g. 16 so I can conserve as much diskspace as possible as I will have to retire my full node now its approaching 1tb and run with pruning and fat-db.

I realise in worst case scenario a really popular address can change state 16 times in the last 16 blocks if it appeared in every block, so if my code were to crash or the sync was to run fast or something the state could change 17+ times before I got a chance to process it and I would be in sync-hell!

So what I'd like to do is ideally with a RPC call or something say upToBlock(n) so my code controls just how far Parity gets syncing. I'd rather do this without having to auto-restart Parity every 16 blocks. Then once I've got there I can call the RPC code again to set the number a bit higher.

I've looked at the code and seen that parity/ethcore/src/client/chain_notify.rs is a potential place to put some logic to just sit and idle if height = my_max_block.

Am I going about this the right way?  Are chain notifications the way to do this?

Thanks in advance.

**Comment by 5chdn** [comment]
1. Start Parity
2. Write a script that monitors the block number via RPC
3. Kill Parity once your block is reached
4. Restart Parity in `--mode offline`

**Comment by jiangxjcn** [comment]
@J-A-M-E-5 
Could you give me some suggestion about how to suspend syncing when reaching a certain height？
