### ISSUE TITLE
PR draft: faster sync

### ISSUE THREAD

**Issue by jamesray1** [paritytech/parity#8097]
> - **Which Parity version?**: version Parity/v1.9.4-beta-6f21a32-20180228/x86_64-linux-gnu/rustc1.24.0
> - **Which operating system?**: Linux
> - **How installed?**: via deb: parity_1.9.4_ubuntu_amd64.deb
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes, as well as following the syncing tips [here](https://github.com/paritytech/wiki/pull/32/files).

If the first syncing line of the output has `Syncing  #<block_number>`, restart the sync.

```
while {
    // the first line of output that contains "{} Syncing",timestamp is followed by "  #"}
     {
        // restart sync
     }
```

This will then keep trying until the first line of output that contains `"{} Syncing",timestamp` is followed by `" snapshot"`, which will break the loop and continue normal execution.

**Comment by debris** [comment]
hi @jamesray1 ! Could you clarify what is this issue about? I don't understand if this is a bug report or feature request 😉

**Comment by rphmeier** [comment]
@jamesray1 the sync code currently attempts to warp sync whenever possible. I agree the heuristics can be improved but I don't think adding logic based on parsing the output of the program (which itself is just a representation of the internal state) is the right way to go about it.

**Comment by jamesray1** [comment]
Yeah, I realised that there might be a better way to do it, which is why it was an issue / draft PR.

**Comment by 5chdn** [comment]
Partially addressed in #8228 

For the other warp-sync issues see a listing at https://wiki.parity.io/Known-Issues-Priorities

**Comment by jamesray1** [comment]
I'm still syncing on my desktop and laptop. I'm up to #4139126 on the desktop and# 2464590 on the laptop.

**Comment by 5chdn** [comment]
Nice!

**Comment by jamesray1** [comment]
Well, kinda, but not really, it's taking a very long time!

**Comment by 5chdn** [comment]
Yeah, the story of my life :(

It's worth getting decent SSDs with huge capacity at some point if you plan to play around with Ethereum a lot.

**Comment by jamesray1** [comment]
Haha. Yeah, my desktop is Intel Core i3 with a smallish SSD. 

![screenshot from 2018-03-27 22-11-41](https://user-images.githubusercontent.com/16969914/37964066-eb62ab52-320b-11e8-9afe-841327775c92.png)

I've got upgrading my desktop on the to-do list, and I am working on sharding full-time, so that is playing around with Ethereum a lot.

https://wiki.parity.io/Known-Issues-Priorities is a good list! I suggest adding sharding to it.

**Comment by jamesray1** [comment]
Do you have any suggestions for a good desktop computer tower?

**Comment by debris** [comment]
I'm not an expert in hardware, bo for me, anything below i7 + 16gb ram is unusable for dev work

**Comment by 5chdn** [comment]
Yeah, the latest Core i7 is a must, 2 TB SSD, and since you want a tower, just squeeze in as much RAM as possible, I would go for at least 64 GB.
