### ISSUE TITLE
IPC error: Nodes on DEMOPOA Tutorial should run simultaneously?

### ISSUE THREAD

**Issue by vieiralc** [paritytech/parity#8106]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.7.8-stable
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no / not connected to any Peers (0/25)
> - **Which network are you connected to?**: DEMOPOA.
> - **Did you try to restart the node?**:  yes

I'm following the DEMOPOA tutorial ([this one](https://github.com/paritytech/parity/wiki/Demo-PoA-tutorial)). And it says to run `node0` and `node1`. My doubt is: should they run simultaneously? Because when I try to run node1 when node0 is already runnig the node1 just can't start and I get the message: 

IPC error: Access is denied. (os error 5)
thread 'IO Worker #2' panicked at '

**Comment by NikVolf** [comment]
Have you tried to update to v1.8.11-stable ?

**Comment by vieiralc** [comment]
No I didn't. Well now it's working don't know why. Thanks
