### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by jamesray1** [paritytech/parity#8111]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.4-beta-6f21a32-20180228/x86_64-linux-gnu/rustc1.24.0
> - **Which operating system?**: Linux
> - **How installed?**: via parity_1.9.4_ubuntu_amd64.deb
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

These errors occurred after I deleted the ~/.local/io.parity.ethereum folder along with older versions of Parity that I had, to clear disk space. Unfortunately I didn't realize that it would also delete the data for the latest version. After restarting the errors still occur. However, the folder has been created again. Will I need to uninstall Parity and reinstall it to clear these errors?

```
[13627:13649:0314/075045.527391:ERROR:connection.cc(1947)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA auto_vacuum
[13627:13649:0314/075045.527469:ERROR:connection.cc(1947)] Web sqlite error 5, errno 0: database is locked, sql: PRAGMA journal_mode = TRUNCATE
```

**Comment by rphmeier** [comment]
@jamesray1 you're seeing this error in the Parity console?

**Comment by jamesray1** [comment]
No, in Bash. I didn't check the browser UI.

**Comment by jamesray1** [comment]
After restarting I didn't get the error.

**Comment by ddorgan** [comment]
@jamesray1 Looks like a common error for a chrome corrupt profile.

Can you verify that when you start parity you have no errors and you get peers and it begins to sync. If so we can close this ticket.

**Comment by jamesray1** [comment]
Yes, after starting Parity there were no errors and I got peers and it began to sync.
