### ISSUE TITLE
Parity randomly stops syncing, restarts syncing after CTRL+C

### ISSUE THREAD

**Issue by joejordan** [paritytech/parity#8115]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.11
> - **Which operating system?**: Windows 10
> - **How installed?**: binaries
> - **Are you fully synchronized?**: until it freezes, yes
> - **Which network are you connected to?**: ethereum mainnet
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I run Parity via the command line in Powershell, I'm usually synced with the network, but occasionally the executable "freezes" for lack of a better word. No new imported blocks are received, and the web interface indicates that I'm getting further and further behind on the blockchain. If I CTRL+C in the terminal window, it will usually unfreeze the executable and will resume syncing the blockchain like normal... until it happens again. Does this happen to anyone else?

The command line I'm using to start up Parity is as follows:
.\parity.exe --chain mainnet --port 8545 --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 1024

**Comment by 5chdn** [comment]
Does this also happen in other shells?
