### ISSUE TITLE
Method parity_postTransaction not supported

### ISSUE THREAD

**Issue by vieiralc** [paritytech/parity#8116]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.7.8
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: DEMOPOA
> - **Did you try to restart the node?**: yes

I'm following the [Dapp tutorial](https://github.com/paritytech/parity/wiki/Dapp-Tutorial), I'm creating a smart contract for voting in solidity and when I click on the vote option the Parity Signer is not called so I can type the password and aprove the transaction. 

This is the error on chrome developers tools: 
![image](https://user-images.githubusercontent.com/19657718/37424517-627db12c-279f-11e8-891e-3fdec6b24cb6.png)

And this is my code: 

```
import React from 'react';
import {Bond} from 'oo7';
import {Rspan} from 'oo7-react';
import {bonds} from '../../../node_modules/oo7-parity';
import {
	InputBond,
	HashBond,
	BButton,
	TransactionProgressLabel
} from '../../../node_modules/parity-reactive-ui';

const CounterABI = [
	{"constant":false,"inputs":[{"name":"_option","type":"uint256"}],"name":"vote","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},
	{"constant":true,"inputs":[{"name":"","type":"address"}],	"name":"hasVoted","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},
	{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"votes","outputs":[{"name":"","type":"uint256"}],			"payable":false,"stateMutability":"view","type":"function"},
	{"anonymous":false,"inputs":[{"indexed":true,"name":"who","type":"address"},{"indexed":true,"name":"option","type":"uint256"}],"name":"Voted","type":"event"}
];
const Options = ['Red', 'Green', 'Blue'];
const ContractAddress = '0x7BA4324585CB5597adC283024819254345CD7C62';

export class App extends React.Component {
	
	constructor(){
		super();
		this.counter = bonds.makeContract(ContractAddress, CounterABI);
		this.state = { tx: null };
	}
	
	render() {

		return (
			<div>
				{Options.map((n, i) => (
					<div key={i}>
						<Rspan style={{
								borderLeft: this.counter
												.votes(i)
												.map(v => `${1 + v * 10}px black solid`)
						}}>
					
							<a
								style={{float: 'left', minWidth: '3em'}}
								href='#'
								onClick={() => this.counter.vote(i)}
							>
								{n}
							</a>
					
						</Rspan>
					</div>
				))}
			</div>
		);

	}
}
```

I'm runnig parity with `parity --config node0.toml`

I'm also using these config files: https://github.com/keorn/parity-poa-tutorial

**Comment by Tbaut** [comment]
@vieiralc could you please [upgrade your parity to 1.9.4](https://github.com/paritytech/parity/releases) and tell us if the problem is still there.

**Comment by vieiralc** [comment]
@Tbaut I've upgrade to 1.9.4 and the error -32000 "Method parity_postTransaction not suported" disappear but now I have the error -32015: Transaction execution error eth_estimateGas

![image](https://user-images.githubusercontent.com/19657718/37480559-4f288ede-285e-11e8-94b3-3904b2635e74.png)

**Comment by vieiralc** [comment]
I running parity with a config toml file. I'm now running with the flags `--config dev`
And it is working fine
I think the problem may be my toml configuration
