### ISSUE TITLE
CLI for WS connections capacity. 

### ISSUE THREAD

**Issue by ianaya89** [paritytech/parity#8117]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.8.2-beta-1b6588c-20171025
> - **Which operating system?**:  Linux
> - **How installed?**: apt-get
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am running some parity nodes and interacting with them using web3 and WS provider. After ~100 connections I get the error:

 ```
Unable to build WebSocket connection WS Error <Capacity>: Unable to add another connection to the event loop.
```

I just want to check if this is an expected behaviour and if you have any information about concurrent connections capacity because I couldn't find it.

BTW, I am running more than one node for different kind of applications and I get the same issues with most of them.

**Comment by tomusdrw** [comment]
@ianaya89 It's indeed current limitation of websocket server: https://github.com/tomusdrw/ws-rs/blob/master/src/lib.rs#L132 we don't allow more than 100 concurrenct connections. I think it makes sense to expose this as a CLI parameter, though.

That said, if web3 is opening a new connection for EVERY transaction you are sending and not closing the previous ones there is something clearly wrong.

**Comment by ianaya89** [comment]
@tomusdrw Makes sense. I think would be great a CLI parameter to set concurrent ws connections. 
Regarding web3, is probably something wrong there. Thanks for your help!

**Comment by robdoesstuff** [comment]
I work with an environment with a distributed worker backend. Each worker is its own process, so at scale it's easy to have thousands of workers, each managing its own outbound connections. When testing, I found that parity is roughly 18 times faster at processing WS requests than keepalive HTTP and 72 times faster at WS than non keep alive HTTP, so it makes sense to want to use WS always for it, but the limit of 100 connections is a problem. We have to pool nodes no matter what, but I'm finding one node can handle something like 8000 requests per second over WS, which would be more than enough for a few hundred workers which only intermittently make rpc requests, but I can't get that many WS connections up simultaneously. We could pool more parity nodes but it's a great waste of resources and sync issues are the next issue with a pool, so muxing may be the short term solution - but if you could make the max connections a configurable item, that would be amazing! Also you should look into the http rpc performance issue, it's pretty bad.

**Comment by robdoesstuff** [comment]
FWIW this is a little more than an "F3-annoyance" - seriously impacts application architecture on scaled apps.

**Comment by Tbaut** [comment]
For the record, @robdoesstuff told me on gitter later on : 

> BTW I've rerun my benchmarks after I found that the tool I was using was the bottleneck and not parity
I've seen numbers now using wrk to benchmark keepalive HTTP to parity ranging from 26000 req/s up to almost 50000
so actually parity can be extremely fast
but still we're having connection timeouts on the same machine that benches 26k

He posted an issue : #8141

**Comment by robdoesstuff** [comment]
I seemed to have maxed out around 250 HTTP connections while testing - this should also be configurable or people will end up writing and running external multiplexors
