### ISSUE TITLE
Parity.exe has been stopped.

### ISSUE THREAD

**Issue by xsslong** [paritytech/parity#8119]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.8.11-stable-21522ff86-20180227/x86_64-windows-msvc/rustc1.24.0
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

My node is still syncing, There's always a program crash, Parity.exe has been stopped.

![image](https://user-images.githubusercontent.com/16704850/37448954-6e681b5c-2863-11e8-9a66-fd767bce34f6.png)

**Comment by Tbaut** [comment]
@xsslong could you please try the [latest release](https://github.com/paritytech/parity/releases) and if this still happens give us the logs from the windows command line ?

**Comment by xsslong** [comment]
Application has been upgraded to the latest version, parity_1.9.4_windows_installer,  but still happens, Prompt: There are unprocessed exceptions, illegal instructions.Program cannot be debugged.
![image](https://user-images.githubusercontent.com/16704850/37501345-fb508e50-2908-11e8-91f5-8586de0f6007.png)

**Comment by Tbaut** [comment]
Could you please run with the [command line](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#how-to-launch-parity-using-the-command-line-on-windows-), and post here the logs when it crashes ?
