### ISSUE TITLE
Parity json-rpc module crashes with a huge amount of requests

### ISSUE THREAD

**Issue by chebykin** [paritytech/parity#8123]
> I'm running:
>
> - **Which Parity version?**: 1.9.3
> - **Which operating system?**: Ubuntu
> - **How installed?**: docker image
> - **Which network are you connected to?**: custom with aura consensus

I'm trying to send a huge amount (~10K) of requests (personal_sendTransaction) at once to Parity `json-rpc` endpoint and it crashes with the following message:

```
2018-03-15 12:05:39  Incoming streams error, closing sever: Error { repr: Os { code: 23, message: "Too many open files in system" } }
2018-03-15 12:05:40  Couldn't open disk map for writing: Too many open files in system (os error 23)
2018-03-15 12:05:41  Couldn't open disk map for writing: Too many open files in system (os error 23)
```
I will try to use a persistent connection to handle this issue, as it was described in the tickets above.

But I believe that this is a bug with Parity's module too. If I send too many http requests for ex. to Apache or Nginx, they stay alive with accordingly decreased response time. So why does Parity `json-rpc` module just crash?

Relate issues are #6575 and #6516

**Comment by tomusdrw** [comment]
@chebykin If you want to handle more connections you need to increase your system's `ulimit`, I believe it would be the same for Nginx and Apache (depending on mpm)

**Comment by tomusdrw** [comment]
@chebykin I think I found a culprit, fixed upstream: https://github.com/paritytech/jsonrpc/pull/244

**Comment by chebykin** [comment]
@tomusdrw Thank you! I'm closing this one since it doesn't relate to this repo anymore.
