### ISSUE TITLE
DOTs not visible in Accounts Overview address

### ISSUE THREAD

**Issue by MDSchaeffer** [paritytech/parity#8131]
Parity v1.9.0-20180125
MacOS 10.12.6 (16G1212)
installed via installer
Fully synchronized
Connected to Foundation
I have tried to restart the node

Expected: I am not able to see associated Parity DOT tokens.  These were purchased through crowdsale and were visible at one point.  

Actual: I cannot see DOT tokens held.  I am able to see other, Parity Registered, tokens.  

Steps to reproduce: **Accounts Overview** -> when viewing individual address tile

**Comment by Tbaut** [comment]
@MDSchaeffer could you please upgrade Parity to the [latest release](https://github.com/paritytech/parity/releases) and let us know if you still have the problem ?

**Comment by MDSchaeffer** [comment]
upgraded to Parity v1.9.4-20180228 beta, problem resolved.  Thanks @Tbaut !
