### ISSUE TITLE
RPC call net_peerCount inconsistent on Linux, very slow to return or times out, maybe blocking broadcasts?

### ISSUE THREAD

**Issue by robdoesstuff** [paritytech/parity#8141]
> I'm running:
>
> - **Which Parity version?**: 1.9.2
> - **Which operating system?**: Linux
> - **How installed?**: Docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum + kovan
> - **Did you try to restart the node?**: yes

**Expected** - consistent response time (< 100ms at a very low load of 1/s), no timeouts, no broadcast timeouts.

**Actual** - here is the output from running wrk using a jsonrpc lua that requests net_peerCount

```
Running 10s test @ http://...
  16 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   235.64ms  318.50ms   1.96s    96.98%
    Req/Sec    38.08     44.89   230.00     91.61%
  1805 requests in 10.01s, 296.13KB read
  Socket errors: connect 0, read 0, write 0, timeout 349
Requests/sec:    180.25
Transfer/sec:     29.57KB
```

The same server does 30k requests/sec with no timeouts on eth_call queries.

This behavior was exhibited on hosts at both AWS and Packet.net. It does not reproduce locally for me on Mac OSX. 

The same test run on OSX yields:

```
  16 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     9.04ms    2.99ms  60.59ms   91.79%
    Req/Sec     1.35k   247.34     1.99k    69.25%
  214908 requests in 10.02s, 34.43MB read
  Socket errors: connect 0, read 47, write 0, timeout 0
Requests/sec:  21443.24
Transfer/sec:      3.44MB
```

**Summary:**
OSX performing 21k/s with no timeouts vs Linux 180/s with many timeouts... Something is wrong with the linux version in this regard. I've also noticed a correlation with logging. When I run trace logging, I see the timeouts when the logging stops periodically, then the logging resumes and the responses also resume. It was obvious enough to where I was able to only watch trace logs and I could call when the test was going to fail. Sure enough, I'd switch over to the test window and see the long responses or timeouts. **My concern is that there is an underlying condition on Linux that net_peerCount is only showing the symptoms of, because when we get many timeouts in a row, we also notice that our broadcasts have sometimes timed out.** Because of that, I think this should be investigated with priority. 

I recently ran with `--no-ui --auto-update=none --no-download --force-direct --no-ipc --no-ws --no-secretstore --db-compaction ssd` in an attempt to isolate it. All testing is being done with HTTP Keepalive.

Here is a link to the test runner used here:

https://github.com/wg/wrk

And here is how you can use it to test jsonrpc:

Place the following contents into the file jsonrpc-peers.lua
```
wrk.method = "POST"
wrk.body   = '{"jsonrpc": "2.0", "method": "net_peerCount", "params": [], "id": 1}'
wrk.headers["Content-Type"] = "application/json"
```
Then run with `./wrk -t16 -c200 -d10s -s ./jsonrpc-peers.lua http://localhost:8545`

Please let me know if you need any additional info.

**Comment by folsen** [comment]
@robdoesstuff The request time will vary greatly depending on how many peers you're connected to. Creating all the data necessary and returning it (which can be quite a lot of data) is very different if your list contains 300 peers vs if it's 0 where it would essentially be a noop.

Can you verify that the difference persists even though the peer count is the same on both nodes (or both have for instance 0 peers).

**Comment by triamazikamno** [comment]
@folsen net_peerCount is just a counter, why would it need to create all the data?

**Comment by folsen** [comment]
@triamazikamno Because it iterates over the peers and filters them then counts https://github.com/paritytech/parity/blob/master/ethcore/sync/src/chain/mod.rs#L463

It's very possible there's a way to optimise this, but the original issue claims it's a linux issue when it might just be a general optimisation issue.

**Comment by triamazikamno** [comment]
@folsen Oh I see, makes total sense them
