### ISSUE TITLE
please zip your .../chains/ethereum/db/906a34e69aec8c0d folder and upload (manual bootstrapping, because Zeno's paradox) - thanks!

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#8145]
Please 

any 24/7 full node ...

... please go into your `~/.local/share/io.parity.ethereum/chains/ethereum/db` folder, and zip the  `906a34e69aec8c0d` folder, and upload it somewhere please.

Then I can download that, and use the age-old Bitcoin type of `bootstrapping via blockchain file` method to catch up.

Why? See this issue:  https://github.com/paritytech/parity/issues/7801#issuecomment-373926695

Thanks.  
Happy St Patrick's Day!

> I'm running:

Parity 1.9.4 on Debian Linux

**Comment by Tbaut** [comment]
@drandreaskrueger Parity is an Ethereum client, meant to synchronize the full chain and verify it to provide the best possible security. It **is** meant to be run 24/7. If you only want to move the eth out of your account and are not interested about running a full node, then what you need is a light client. It is less secure, but easier and quicker to use. Parity has a experimental light client version. To use it, launch parity with the flag `--light`.

Alternatively and if the light client isn't working for you (as this is still an experimental version), you can still use https://wallet.parity.io (just create a dummy account at startup) and you can either import your accounts with a JSON file or recover an account with the recovery phrase.

For any other question, feel free to ask on our [Gitter chat](https://gitter.im/paritytech/parity)

**Comment by drandreaskrueger** [comment]
> To use it, launch parity with the flag --light.

Thanks a lot, @Tbaut - I'll try that.

>  Parity has a experimental light client version. 

What does experimental mean in this context?
Unstable? Buggy? Insecure? 

>  It is meant to be run 24/7.

I wasn't aware of that, thanks.

I suggest to be transparent about it:

> https://www.parity.io/
> The fastest and most secure way of interacting with the Ethereum blockchain. 
> Our client powers much of the infrastructure of the public Ethereum network 
> and is used by companies and users alike.

  \+

Parity is meant to be run 24/7.   
If you plan to connect only occasionally, this is not the right tool for you.   
For that we suggest ... instead.   

Thanks.

**Comment by drandreaskrueger** [comment]
>  not interested about running a full node

interest is not the criterion.

I do switch off my computer when I am not using it.  50 Watts.

And while Parity is syncing, the little remaining CPU power of the machine is pretty useless.

How well does parity run on a RaspberryPi?

Thanks.

**Comment by drandreaskrueger** [comment]
> https://wallet.parity.io (just create a dummy account at startup) 

nice one, thanks.

> and you can either import your accounts with a JSON file 
> or recover an account with the recovery phrase.

when I do that on my local machine, it creates a file in my local folder.

Is that the same with your webwallet wallet.parity.io ?

Then why do you suggest that?   
You would get hold of all my private keys. 
Intention = ?


Or:

Have you implemented the webwallet like NXT / ARDOR did, so that everything private never leaves my browser?  
Then great - What are the switches to start such a webwallet locally, which keeps everything private in the browser, and uses the parity server only for already signed stuff.

Thanks.

**Comment by drandreaskrueger** [comment]
> For any other question, feel free to ask on our Gitter chat

A chat has amnesia. You might want to rethink pointing to that for solutions that more than one person might be benefit from.

**Comment by drandreaskrueger** [comment]
>  Tbaut closed this a day ago

I trust you have some internal scheme to remind you to check already closed issues for follow up answers and questions.

**Comment by drandreaskrueger** [comment]
>  zip the 906a34e69aec8c0d folder, and upload it somewhere please.

I still think that is a good idea.

When I have a machine/rPi to run a full node ... to [sync 390k blocks after a --warp](https://github.com/paritytech/parity/issues/7801#issuecomment-373923000) **would take ages**. What speaks against automating a bootstrap file upload?

Probably snapshot syncing was designed to provide exactly that?

But when you look into that [(closed) issue 7801](https://github.com/paritytech/parity/issues/7801#issuecomment-373926584) you might find out that `--warp` is currently broken ?  What can be done about that?  Or am I misunderstanding the --options?

**Comment by Tbaut** [comment]
@drandreaskrueger I advised you to talk on gitter to follow-up. You missed a lot of information (mostly available in our [wiki](https://wiki.parity.io) ) that I kindly proposed to summarize to you in a chat. Feel free to reach out.

**Comment by drandreaskrueger** [comment]
Thanks for your help, @Tbaut. 

Once the "... stuck at #2088992" bug is fixed, I am happy to just run parity in lightmode.

**Comment by drandreaskrueger** [comment]
I have now helped myself to a **bootstrap file**

*  [parity-mainchain_20180423 .zip](https://mega.nz/#!VzwwyLzL!nto17YDIuD1rCzg7h4ST6ew8skQLE5dbhogdbvzC7J4) bootstrap file

   * (might be gone, because superseded by a newer file; 50 GB max; see these instructions:
* short [manual](https://gist.github.com/drandreaskrueger/88cf4e27c69272e68d44076aaf9a8844) how I did that

For now, I keep a cloud machine running, so that I can always zip & download a synced chain. Download time is 3 hours - but that is better than never ever getting it synced again.

**Comment by 1blockologist** [comment]
Thank you for the real and honest criticism @drandreaskrueger that is refreshing to see in this space

How does the lite client work out for you, I am considering it
