### ISSUE TITLE
--light client stuck at #2088992

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#8148]
> I'm running:
```
parity --light ui
2018-03-18 22:39:56 UTC Starting Parity/v1.9.4-beta-6f21a32b2-20180228/x86_64-linux-gnu/rustc1.23.0
```
on Debian Linux ; installed from latest github release. Mainnet. Yes, tried restarting.

---

### --light client is stuck at #2088992

see bottom half of issue 8145 comment https://github.com/paritytech/parity/issues/8145#issuecomment-374042321

**Comment by drandreaskrueger** [comment]
solution was: Wait 2 days, then try again.

**Comment by Tbaut** [comment]
In such cases, restarting the light client would help.
This issue will be worked around with https://github.com/paritytech/parity/pull/8075

**Comment by drandreaskrueger** [comment]
Oh, misunderstanding. Of course I [had](https://github.com/paritytech/parity/issues/8148#issue-306292347) restarted parity, several times:

> Yes, tried restarting.

But that did not help.

What did help was waiting 2 days, and now trying again.

**Comment by drandreaskrueger** [comment]
I have given up on that.

Instead I have now helped myself to a **bootstrap file**

*  [parity-mainchain_20180423 .zip](https://mega.nz/#!VzwwyLzL!nto17YDIuD1rCzg7h4ST6ew8skQLE5dbhogdbvzC7J4) bootstrap file

   * (might be gone, because superseded by a newer file; 50 GB max; see these instructions:
* short [manual](https://gist.github.com/drandreaskrueger/88cf4e27c69272e68d44076aaf9a8844) how I did that

For now, I keep a cloud machine running, so that I can always zip & download a synced chain. Download time is 3 hours - but that is better than never ever getting it synced again.

**Comment by Tbaut** [comment]
As stated before, Parity v1.11 should solve this problem.

**Comment by drandreaskrueger** [comment]
when stable?

**Comment by Tbaut** [comment]
Will go live next week as beta (light mode is experimental for 1.9 and 1.10 too).

**Comment by drandreaskrueger** [comment]
Great. Looking forward to light being stable, and incl. token transfers.

Until that dream becomes reality \*g\* --> https://gist.github.com/drandreaskrueger/88cf4e27c69272e68d44076aaf9a8844

**Comment by drandreaskrueger** [comment]
is the token balances & transfer now working in the light client?  
Thanks.
