### ISSUE TITLE
StateDiff does not contain refunded address account

### ISSUE THREAD

**Issue by cleanunicorn** [paritytech/parity#8158]
> I'm running:
>
> - **Which Parity version?**: 1.10.0-nightly-793624b
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

`trace_replayTransaction` does not contain in the `stateDiff` the account that ETH was refunded to after suicide.
I am expecting the account `0x6c6677787779626e676572657265726572657374` to be part of the `stateDiff` section and to contain its balance change

Transaction hash 0x5816cb0c95789787803ba22bf73e5d1be8a1bc21ac8c91523ce128ac3bb7a157

It's one of the DOS txs

```
"stateDiff ": {
    "0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01": {
        "balance": {
            "*": {
                "from": "0x1789f998fe8fc5ebbe", 
                "to": "0x178a2ee36a37676bbe"
            }
        }, 
        "code": "=", 
        "nonce": "=", 
        "storage": {}
    }, 
    "0xd3e32594cedbc102d739142aa70d21f4caea5618": {
        "balance": {
            "*": {
                "from": "0x54cb7eeea86dfdb3", 
                "to": "0x5496348300cc7db3"
            }
        }, 
        "code": "=", 
        "nonce": {
            "*": {
                "from": "0x8ed", 
                "to": "0x8ee"
            }
        }, 
        "storage": {}
    }
}
```

```
"trace": [
...

{
    "action": {
        "address": "0x31c2c092b367e53b0e989fa2960ae4e493ce5cd1", 
        "balance": "0x1", 
        "refundAddress": "0x6c6677787779626e676572657265726572657374"
    }, 
    "result": null, 
    "subtraces": 0, 
    "traceAddress": [
        47, 
        146, 
        0
    ], 
    "type": "suicide"
}
```

In this request there are 7716 suicide events and none of the refund addresses are added in the `stateDiff`

I've used this request to get the data

```
POST http://localhost:8545 HTTP/1.1
content-type: application/json

{
    "method": "trace_replayTransaction",
        "params":
    [
        "0x5816cb0c95789787803ba22bf73e5d1be8a1bc21ac8c91523ce128ac3bb7a157", 
        [
            "stateDiff",
            "trace"
        ]
    ], 
    "id": 1, 
    "jsonrpc": "2.0"
}
```

**Comment by debris** [comment]
that's an interesting finding. tbh I don't how is it possible, but it should be fairly easy to fix

**Comment by cleanunicorn** [comment]
I've added a few more info. There are 7716 refunds and none of the destination accounts are added in the `stateDiff`
All of the refunds are for 1 wei

**Comment by izgzhen** [comment]
@debris let me try to investigate into this :)

**Comment by debris** [comment]
sure @izgzhen ! Ask me anything if you need any help :)

**Comment by izgzhen** [comment]
From what I found, https://github.com/paritytech/parity/blob/04931618ed840decdaa7e90c20d2855c74355763/ethcore/transaction/src/transaction.rs#L40-L47 might be related.

There is no `Suicide` action in this `enum Action`.

**Comment by debris** [comment]
@izgzhen it's not related. If transaction rlp has destination, it's a call to a contract. If it does not, it's creating a new one. There is no other option :)

**Comment by izgzhen** [comment]
https://github.com/paritytech/parity/blob/04931618ed840decdaa7e90c20d2855c74355763/ethcore/src/externalities.rs#L357-L381

Maybe we should insert the `refund_address` into the `self.substate.touched`?
