### ISSUE TITLE
Ethkey always generates addresses prefixed with "00" when using --brain

### ISSUE THREAD

**Issue by dmdque** [paritytech/parity#8161]
## Actual
ethkey generates key with address starting with "00"

## Expected
ethkey generates fully random key

When using `ethkey` to generate keys with `ethkey generate random --brain`, the generated addresses always start with "00". Is this expected? Are these addresses fully random?

I'm running `ethkey` from `a59f6d9b`, built from source.

**Comment by tomusdrw** [comment]
Yes, the keys are random. The algorithm is described here:
https://github.com/ethereum/wiki/wiki/Brain-Wallet
and implementation can be found here:
https://github.com/paritytech/parity/blob/4a7940ea485daa091041d6ae3534021c1d4bf4b3/ethkey/src/brain.rs#L51

That also makes the addresses icap-compatible.

**Comment by 5chdn** [comment]
See also https://ethereum.stackexchange.com/questions/15411/parity-account-addresses-all-having-prefix-0x00
