### ISSUE TITLE
Missing "re-org" message

### ISSUE THREAD

**Issue by tjayrush** [paritytech/parity#8170]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
 Mac
> - **Which Parity version?**: 0.0.0
1.9.1
> - **Which operating system?**: Windows / MacOS / Linux
MacOS
> - **How installed?**: via installer / homebrew / binaries / from source
installer shell script
> - **Are you fully synchronized?**: no / yes
yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
mainnet
> - **Did you try to restart the node?**: no / yes
no.

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Usually, when there's a re-org, it shows a reorg message in the console. I happened to notice the odd behavior shown clearly in the image below. It's probably just a bug in the display, but I would feel more comfortable if it reported when there was a re-org.

<img width="1490" alt="screen shot 2018-03-20 at 7 56 59 pm" src="https://user-images.githubusercontent.com/5417918/37689028-42b92482-2c79-11e8-80d4-d3bd63511ffe.png">

**Comment by 5chdn** [comment]
It can not reorg at depth 0 from what I understand if both blocks (received within 1 second) are valid. The miner of the next block 5292043 can include one of the two previous blocks as an uncle, so this is not a reorganization per se.
