### ISSUE TITLE
Parity Wallet Remote Access Not working properly

### ISSUE THREAD

**Issue by Emperornero** [paritytech/parity#8172]
I'm running:
**Which Parity version?**: 1.9.4
**Which operating system?**: Windows
**How installed?**: via installer
**Are you fully synchronized?**: yes
**Which network are you connected to?**: ethereum 
**Did you try to restart the node?**: yes

Running with following flags

parity.exe --warp --no-ancient-blocks --pruning=fast --pruning-history=8  --pruning-memory=32 --db-compaction="hdd" --jsonrpc-interface all --jsonrpc-hosts all --ui-interface 0.0.0.0 --ui-no-validation --public-node

Have ports 8180, 8545, and the other one forwarded.

When attempting to access wallet UI over LAN I asked for Validation Token, after putting in new token, the page acts like it's loading, then just greys out the validation line. 

Wallet Remote Access guide directions do not work with SSH or hosting option.

Any ideas?

**Comment by Tbaut** [comment]
You are most likely missing the flag `--ws-origin all`. If this doesn't solve your problem, can you give the errors from the terminal and the console browser?

**Comment by tomusdrw** [comment]
@Emperornero port 8546 is required as well. See details here: https://wiki.parity.io/Wallet-Remote-Access.html

**Comment by Emperornero** [comment]
Seems the Wallet Remote Access Page has been updated since I looked at it a week ago.   I was missing the --unsafe-expose flag.

This machine is direct connected to my main computer, I just like to keep a full node synced without taking up disk space or cpu usage on my main rig, so this will work great.  

Issue can be closed.  Thanks.

**Comment by tomusdrw** [comment]
@Emperornero `--unsafe-expose` on non-firewall protected node is a terrible idea, where did you read that it's required? If you only have the node in your local network it's still accessible by everyone in that particular network.

Wallet dapp is using 8546 interface (WebSockets) to work, other dapps not necessarily.

**Comment by Emperornero** [comment]
All external ports but 30303 are blocked on the node.  The Wallet Access Page suggested that, it has not been working without that.  

I'll try remapping to direct IP instead of using 0.0.0.0 .  I'm able to access the UI however it's not saving account information after importing.
