### ISSUE TITLE
Parity does not use the gas values it shows in the UI when using "advanced sending options"

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#8174]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.0-unstable-9e294d577-20180320/x86_64-macos/rustc1.24.1
> - **Which operating system?**: Windows / **MacOS** / Linux
> - **How installed?**: via installer / homebrew / binaries / **from source**
> - **Are you fully synchronized?**: no / **yes**
> - **Which network are you connected to?**: ethereum / ropsten / **kovan** / ...
> - **Did you try to restart the node?**: no / **yes**

I am deploying a contract. It requires ~588k gas. Parity estimates around 700k gas.
I am deploying the contract with the same arguments and those do NOT throw.

If I don´t use the **advanced sending options** for sending the tx, the contract deploys all fine:
https://kovan.etherscan.io/tx/0x7a2623afe89dd5389ce392edea0e16be360fbf19a6620b3a64712291085f4a76

Now in **advanced sending** mode, I see:
- gas: estimated 588k, will send 706446 (fine)
- price: 22000000010 (whatever :))
The UI confirms the values:
![image](https://user-images.githubusercontent.com/738724/37707258-d5316160-2d02-11e8-87a8-dc95c08cfd13.png)

And... demo effect... now it works: https://kovan.etherscan.io/tx/0x4a52daf0a93660ac325f6939d0d9e67e5b09b1baf77aa7bbe685e7c51276100c

I have done the same a few times and got those tx:
- https://kovan.etherscan.io/tx/0x7d719bfb0a7e17523fdb779ed6bf2c81f8cb23392cc80707ae165f8cf0f8d16e
- https://kovan.etherscan.io/tx/0x22fa1901d1bccabc8665c785b01f4859599cdfd127d93d2456da875f740926f2
- https://kovan.etherscan.io/tx/0x8b3679d94397cd06b0e8eabff1bbbbf71a1f1a5676995f2b62cb8c51741f2006
- https://kovan.etherscan.io/tx/0xda8d7e7cba20e5e83467497330a258a9b1144eb82ed65111fa13bf48137a8235

I don´t understand where the gas value in the tx (190088) comes from. Surely this is the reason why the tx fails as this is not enough. The question is where does this value comes from and why such low value.

It seems that the issue has been fixed by NOT using the **advanced sending** more once.

**Comment by chevdor** [comment]
I just saw the same issue on mainnet:

- start parity
- make a tx to deploy an ERC20 for instance
- directly use the **advanced sending option**
- see if your tx go thru.

I would rather not share the mainnet tx but the amount of gas sent was ~189k

**Comment by Tbaut** [comment]
Moved to the right repo: https://github.com/parity-js/shell/issues/103
