### ISSUE TITLE
Auto-updater upgradability verification

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#8178]
When updating a major release (say 1.8-stable -> 1.9-stable) there might be breaking changes with CLI flags or config entries.
Auto-updater should first test if new binary will be able to execute with the same parameters and only update if it's successful. Otherwise it should print a warning message every now and then.

**Comment by niklasad1** [comment]
I will wait with this one until #7272 is merged seem to be significant changes

**Comment by folsen** [comment]
@niklasad1 @andresilva Is this now addressable, do you still intend to take this Niklas or do you want to unassign yourself?

**Comment by andresilva** [comment]
Yes, I don't expect any more changes on the auto-updater for now so I think this is  addressable.

**Comment by niklasad1** [comment]
I’m on it, will fix it soon has taken some time to understand to updater code though!

**Comment by andresilva** [comment]
You should also have a look at `parity/main.rs`, I think most changes will have to be done there (that code is a bit hairy right now). The updater downloads new binaries to `io.parity.ethereum-updates` and updates a file named `latest` in that directory to point to the latest version. By default, when parity starts it checks this file and launches that binary instead.

**Comment by LYY** [comment]
I'm using parity on centos 7. Today parity had auto-updated, but restarted failed. It seems like download general linux version, not centos version.

I deleted error logs, it looks like this:

```
./parity: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./parity)
./parity: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./parity)
./parity: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./parity)
./parity: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./parity)
```
