### ISSUE TITLE
use debug_struct to print trie

### ISSUE THREAD

**Issue by debris** [paritytech/parity#8184]
discussion: https://github.com/paritytech/parity/pull/8166#discussion_r175972677

**Comment by gnunicorn** [comment]
@debris just to be clear, what we want to do here:
1. switch all debug statements to pretty-printing with `{:#}`
2. add debug_struct formatters where missing

Correct?

I am a bit unclear what should happen to the `writeln` and what it should be replaced with. Do want to replace it with `println!`? Arent' `writeln!` and `println!` using the same formatter (internally), thus `{:#}` is also supported with writeln?

**Comment by debris** [comment]
hi @gnunicorn . 

1. yes
2. I want entire trie to be formatted only with `debug_struct`.  The is no need to use `writeln!` or `println!` inside fmt function at all
