### ISSUE TITLE
Does the AccountDBMut::combine_key works in the correct way?

### ISSUE THREAD

**Issue by EighteenZi** [paritytech/parity#8208]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

In the method 'AccountDBMut::insert', we call 'combine_key', and then call db.emplace.
If AccountDBMut's db is 'MemoryDB', and the value is new, the 'emplace' method will call entry.insert(),
and the key got from 'combine_key' is not used....

Who can help on this ?

**Comment by rphmeier** [comment]
yes, it does work, please read more carefully.

**Comment by EighteenZi** [comment]
Sorry...
I misunderstood the meaning of "HashMap.entry".
Thans a lot.
