### ISSUE TITLE
Help Updating Please

### ISSUE THREAD

**Issue by RJW1875** [paritytech/parity#8210]
> - **Which Parity version?**: 1.7.11 stable
> - **Which operating system?**: MacOS 10.13.3
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Just wondering how to update without losing all the chain-data as the auto-update doesn't seem to be working. Current version works fine; but would like to go to 1.9. Is it as simple as uninstalling and installing the newer file?

Cheers

**Comment by brandoncurtis** [comment]
Yep!  You can install 1.9 over 1.7.11 and it should work perfectly.
