### ISSUE TITLE
Best block shows time but no date

### ISSUE THREAD

**Issue by UGatgithub** [paritytech/parity#8212]
Checking the Node information on Windows I see something like:

#5,215,466
Best block, at 01.09.22

which looks to me like there is a date missing to be displayed.

I'm running:

Which Parity version?: v1.9.5-stable-ff821daf1-20180321/x86_64-windows-msvc/rustc1.24.1
Which operating system?: Windows
How installed?: via installer
Are you fully synchronized?: no not synced completely yet
Which network are you connected to?: Ethereum
Did you try to restart the node?: yes, I don’t think this issue is specific for my machine

**Comment by 5chdn** [comment]
@Tbaut  Please move this to https://github.com/Parity-JS/dapp-status/issues

**Comment by Tbaut** [comment]
Moved to https://github.com/Parity-JS/dapp-status/issues/2

**Comment by UGatgithub** [comment]
1.11.4 beta still shows this issue!
