### ISSUE TITLE
tokens never shown (v1.9.4 & 1.9.5 --light)

### ISSUE THREAD

**Issue by drandreaskrueger** [paritytech/parity#8215]
I have tried to restart it a few times, but with

    parity --light ui

... tokens are never showing.

Perhaps this console output helps you?
```
...
v1: starting Tokens Provider...
index.c773c59f7a.js:1 [lookupAddress] tokenreg: 0x5F...
index.c773c59f7a.js:1 [lookupAddress] githubhint: 0x27...
index.c773c59f7a.js:1 [lookupAddress] signaturereg: 0x44...
index.c773c59f7a.js:1 could not register SW after 2.5s
(anonymous) @ index.c773c59f7a.js:1
setTimeout (async)
(anonymous) @ index.c773c59f7a.js:1
t @ vendor.js:1
a @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
index.c773c59f7a.js:1 [lookupAddress] badgereg: 0xF7...
index.c773c59f7a.js:1 Resolving tokens by timeout.
(anonymous) @ index.c773c59f7a.js:1
setTimeout (async)
(anonymous) @ index.c773c59f7a.js:1
t @ vendor.js:1
a @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
Promise.then (async)
c @ index.c773c59f7a.js:1
t.default @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
index.c773c59f7a.js:1 v1: started Tokens Provider
bundle.js:1 eth_call([{"data":"0x606060...0000a"},"latest"]): -32015: Transaction execution error.
value @ bundle.js:1
index.c773c59f7a.js:1 Error: eth_call: -32015: Transaction execution error.
    at e.value (VM161 inject.js:1)
(anonymous) @ index.c773c59f7a.js:1
Promise.catch (async)
value @ index.c773c59f7a.js:1
e @ index.c773c59f7a.js:1
value @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
(anonymous) @ vendor.js:1
(anonymous) @ vendor.js:1
t.default @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
t @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
(anonymous) @ index.c773c59f7a.js:1
bundle.js:1 eth_call([{"data":"0x606060...00080"},"latest"]): -32015: Transaction execution error.
value @ bundle.js:1
index.c773c59f7a.js:1 tokens::fetchTokens Error: eth_call: -32015: Transaction execution error.
    at e.value (VM161 inject.js:1)
...
```

> I'm running:
>
> - **Which Parity version?**: 

Parity/v1.9.4-beta-6f21a32b2-20180228/x86_64-linux-gnu/rustc1.23.0  

also tried  
Parity/v1.9.5-stable-ff821daf1-20180321/x86_64-linux-gnu/rustc1.24.1  
... = same

> - **Which operating system?**: Linux
> - **How installed?**: via github release 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

> **actual** 

no tokens shown

> **expected behavior** 

tokens shown.

**Comment by drandreaskrueger** [comment]
> the light client is not compatible with the wallet yet. 

WHAT?

*meh*

Then I am only 60% helped now. I have value in tokens. Am I the only one?


? --> How to move my tokens now  that

(a) parity --warp is [unable to catch up](https://github.com/paritytech/parity/issues/7801), but  
(b) the [light client is not compatible](https://github.com/paritytech/parity/issues/8215#issuecomment-376180479)

?

In https://github.com/paritytech/parity/issues/8145#issuecomment-373943610 I had been told to give up on the full node, and instead go for the light client.  
Now you tell me to give up on the light client, and go for the full node, right?

Then there is really only one way out:

PLEASE  please please someone

[please zip your .../chains/ethereum/db/906a34e69aec8c0d folder and upload (manual bootstrapping, because Zeno's paradox) - thanks! #8145](https://github.com/paritytech/parity/issues/8145#issuecomment-373943610)

then I take that file, drop it into my `.../chains/ethereum/db/906a34e69aec8c0d` folder, and sync for a few days until I am there. And then I can never ever switch off my computer again, so I should use a 2A raspberryPi - but that question of mine has also not been answered.

Closing un- or not-fully-solved issues ...

**Comment by 5chdn** [comment]
> feature request: allow to send already, before chain is fully synced

That's technically not possible because the client does not know about your balances and the transaction nonces before fully syncing the chain.

**Comment by 5chdn** [comment]
> Closing un- or not-fully-solved issues ... = ? But when you add labels & milestones, you still keep track of them, right?

We are tracking the light client RPCs required for the wallet to work in #6202 

For a full list of issues we are working on to ease your synchronization experience, please see https://wiki.parity.io/Known-Issues-Priorities

**Comment by drandreaskrueger** [comment]
Any progress on the light client? Does it show tokens now?

I have now helped myself to a **bootstrap file**

*  [parity-mainchain_20180423 .zip](https://mega.nz/#!VzwwyLzL!nto17YDIuD1rCzg7h4ST6ew8skQLE5dbhogdbvzC7J4) bootstrap file

   * (might be gone, because superseded by a newer file; 50 GB max; see these instructions:
* short [manual](https://gist.github.com/drandreaskrueger/88cf4e27c69272e68d44076aaf9a8844) how I did that

For now, I keep a cloud machine running, so that I can always zip & download a synced chain. Download time is 3 hours - but that is better than never ever getting it synced again.

**Comment by 1blockologist** [comment]
This is hilarious, I love these honest criticisms

Something that every wallet does is not technically possible with Parity. I know why this is, but it 'merely' needs a lite mode that is analogous to every other lite client out there.

I'm also here for the progress update

**Comment by 5chdn** [comment]
> Just make a remote node that people can connect to 

No, but thanks :)

**Comment by drandreaskrueger** [comment]
> progress update

yes please, me too

**Comment by 5chdn** [comment]
Please ask direct questions. Parity does not even have any wallet anymore at this point.

**Comment by drandreaskrueger** [comment]
how move tokens?
