### ISSUE TITLE
`eth_getFilterLogs` does not return most logs between blocks 5,200,000 and 5,300,000

### ISSUE THREAD

**Issue by brandoncurtis** [paritytech/parity#8217]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.5-stable-ff821da-20180321/x86_64-linux-gnu/rustc1.24.1
> - **Which operating system?**: Linux
> - **How installed?**: via .deb installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

`parity --pruning=archive --fat-db=on --tracing=on`

## Expected Behavior

`eth_getFilterLogs` should return all of the logs that match the filter.

## Actual Behaviour

`eth_getFilterLogs` only returns a tiny subset of the logs between blocks 5,200,000 and 5,300,000.

We're currently at block 5,382,200.  This is a full-archive node, and I believe the last snapshot process may have been interrupted by a power outage.

I've reset the node multiple times to no effect.  

No matter the filter I define, the logs stop shortly after 5,200,000 and start shortly before 5,300,000:
```
5201718
5201718
5201738
5201742
5201758
5201780
5201791
5201791
5201791
5299928
5299930
5299957
5299957
5299966
5299968
5299971
5300000
```

When I request blocks or transactions or even logs from this period, they return fine.

## Request

I know I can fix this problem by wiping the database and completely starting over, but this seems like a pretty serious bug—history is silently broken!—and I'd like to do some debugging to figure it out.  Please advise.

**Comment by debris** [comment]
Thanks for the report @brandoncurtis . We will investigate the issue. We'll also add a possibility to recreate traces for fatdb nodes #8221

**Comment by folsen** [comment]
Update: We know there is a very rare corner-case bug that affects bloom filters on re-orgs, a partial solution has already been implemented but a full solution is being worked on and coming out soon.

**Comment by 5chdn** [comment]
@debris @folsen what's the status of this?

**Comment by debris** [comment]
it's already merged and integrated

**Comment by alesl** [comment]
It seems this is still an issue, v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0:

```
curl -s --data '{ "method": "eth_getLogs", "params": [ { "fromBlock": "0x6197A2", "toBlock": "0x6197B6", "topics": [ "0x022c0d992e4d873a3748436d960d5140c1f9721cf73f7ca5ec679d3d9f4fe2d5" ] } ], "id": 1, "jsonrpc": "2.0" }' -H "Content-Type: application/json" -X POST http://localhost:8545
```

**Comment by debris** [comment]
@alesl can you open a new issue with the full description of the problem? including all the command line params. It would help us diagnose the problem. thanks!
