### ISSUE TITLE
Unlock Password 

### ISSUE THREAD

**Issue by boxofscraps** [paritytech/parity#8218]
> I'm running:
>
> - **Which Parity version?**: 1.9.5-ff821daf1da42865f229aee35f2e74e7b2dd8db2
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

I am trying to unlock my account.  First, I added the public address for accounts to unlock in toml config. I then set the password file location to "%UserProfile%/password.file" for the toml configuration. 

I keep getting the error: invalid type: string "%UserProfile%/password.file", expected a sequence for key `account.password`.

My password.file is located in my %UserProfile% directory. Inside my password.file, I have my private key in quotes.

**Comment by brandoncurtis** [comment]
To unlock an account, put this in your config.toml:
```
[account]
unlock = ["0xYOURADDRESS"]
password = ["/path/to/your/password.file"]
```
in password.file, put your password in plaintext.

Place the keyfile for 0xYOURADDRESS in $PARITYDIR/keys/kovan/yourkeyfile.

You can use a tool like https://github.com/ethereum/eth-keyfile or https://github.com/ethereumjs/keythereum to convert your raw private key into a password-protected keyfile.

**Comment by boxofscraps** [comment]
I obtained a keystore file from myetherwallet and placed it in %UserProfile%\AppData\Roaming\Parity\Ethereum\keys\kovan.

for the password.file, I have just put in the password for the keystore.  Which one should it be? Nothing is working.  I have tried the same process with a second wallet to no success. 
My file path for toml is : password = "%UserProfile%/password.file" . Perhaps something needs to be backslash? 

The example found here shows sample paths for linux but not windows. https://wiki.parity.io/Configuring-Parity. Also just replace the password path with the password directly with something like password = 'password' got the same error. 
invalid type: string ".... expected a sequence for key `account.password`

**Comment by Tbaut** [comment]
@boxofscraps getting a bash shell such as [git bash](https://gitforwindows.org/) would probably help a lot to run linux commands. You can try withing the command line with `--unlock "0xYOURADDRESS" --password <(echo "YOURPASSWORD")`

**Comment by axelchalon** [comment]
The value of `password` needs to be an array.

In your toml use this:
`password = ["%UserProfile%/password.file"]`
instead of this:
`password = "%UserProfile%/password.file"`

**Comment by boxofscraps** [comment]
I suggest that Parity Config Tool should be updated to reflect that path for address needs to be an array. 
https://paritytech.github.io/parity-config-generator/

**Comment by boxofscraps** [comment]
Now I am getting the error: Unable to read password file. Ensure it exists and permissions are correct.
My password.file only has my password, no spaces. (I used echo password > password.file. When I copy the text from my password.file into myetherwallet, it is able to unlock my address.

**Comment by Tbaut** [comment]
I gues the problem is the path to your password file. Make sure it doesn't contain any macro such as %UserProfile% or $HOME. I just tested it successfully with relative and direct path. I'll update the wiki.
