### ISSUE TITLE
portshift not accounted for in "signer new-token" console link

### ISSUE THREAD

**Issue by p-s-dev** [paritytech/parity#8226]
when running command line to generate a token...
/parity/parity signer new-token

it prints a link to visit.  This link uses the standard port.  It does not take in to account if the node is running with shifted ports.

Open: http://127.0.0.1:8180/#/auth?token=123

> I'm running:
>
> - **Which Parity version?**: v1.9.5-stable
> - **Which operating system?**: Linux
> - **How installed?**: via docker

Actual:
`/parity/parity --ports-shift 7777 `
`/parity/parity signer new-token`
Open: http://127.0.0.1:8180/#/auth?token=123

Expected:
`/parity/parity --ports-shift 7777 `
`/parity/parity signer new-token`
Open: http://127.0.0.1:15957/#/auth?token=123

**Comment by tomusdrw** [comment]
Is the port-shift configured in a config file? If no, what does `parity --ports-shift 100 signer new-token` return?

**Comment by 5chdn** [comment]
The node does not know about your ports-shift unless you tell it about it.

```
parity signer new-token --ports-shift 4165
Loading config file from /home/user/.local/share/io.parity.ethereum/config.toml

Open: http://127.0.0.1:12345/#/auth?token=123
to authorize your browser.
Or use the generated token:
123
```
