### ISSUE TITLE
Thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335

### ISSUE THREAD

**Issue by romemore** [paritytech/parity#8232]
> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Linux 
> - **How installed?**: binaries 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

Node running via docker/stable-release on Ubuntu 16.04
Occured during synchronization(~81%)

**Comment by Tbaut** [comment]
Duplicates, @romemore please follow and if you can, help us answer open questions from https://github.com/paritytech/parity/issues/7340
