### ISSUE TITLE
[RPC] Error while generating receipt of transactions: Transaction with the same hash was already imported.

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#8237]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.10.0-unstable-66755be8f-20180206/x86_64-linux-gnu/rustc1.23.0
--

> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: Yes
> - **Which network are you connected to?**: On private/custom network
> - **Did you try to restart the node?**: yes

I'm trying to send many transactions from a account rapidly. It works to some extent. I am able to successfully send ~200 txns(transfer eth from one EOA to another). But when I try to send more txns, I get an error response from the client stating that 

> Transaction with the same hash was already imported.

or

> Error: Invalid JSON RPC response: ""

But when I check the explorer, I see that all txns have gone through. Even the ones which said `Transaction with the same hash was already imported.`

To elaborate, I am confident that this is not the case, all txns have different hash. The [script](https://gist.github.com/AyushyaChitransh/dca2cfc85755b20e373aa18b1648f9e1) I am using to send transactions gets the account nonce, and then prepare the txns with incremental nonce and send signed txns.

**Comment by tomusdrw** [comment]
Do you mind running with `-lrpc=trace,txqueue=debug,miner=debug`?

Could you check if the behaviour occurs as well when running with `--jsonrpc-threads 0`

**Comment by AyushyaChitransh** [comment]
Yes sure, I'll update more details on this by tomorrow.

**Comment by AyushyaChitransh** [comment]
> Check if the behaviour occurs as well when running with `--jsonrpc-threads 0`

Yes. The issue still exists. Out of 700 txns, 341 txns were mined in first block 354 were mined a block later. The issue was that I received error response `Error: Invalid JSON RPC response: ""` from RPC for 331 txns. 

 > Running with `--jsonrpc-threads 0 -lrpc=trace,txqueue=debug,miner=debug`

 - For the first run, all 700 txns were mined without error. 
 - Then I sent again. Out of that, I received error in 41/700 txns. But all 700 were mined.
 - Then I sent again. Now I got error in 493/700 txns. But all 700 were mined.
 - Then I sent again. Now I recieved error in 66/700 txns. But all 700 were mined.

I have posted the trace, debug logs in [gist](https://gist.github.com/AyushyaChitransh/d82848438d4e096cf35753718663a56e).

**Comment by tomusdrw** [comment]
@AyushyaChitransh `Error: Invalid JSON RPC response: ""` is a different error than `Transaction with the same hash was already imported.`

The first one is generated by web3 and it's most likely caused by your request timeing out (since you are spamming a lot of requests at the node, some of them might be processed out of order and with some timeout). Please increase the timeout period, or send requests in waves (generate 10k, submit and wait) to make sure you are receiving all the responses.

The second error is interesting, would be awesome to get a log that actually contains this.
