### ISSUE TITLE
Expanse Node don't sync to peers

### ISSUE THREAD

**Issue by olzhas498** [paritytech/parity#8243]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Expanse-Wallet-win32-0-9-4
> - **Which operating system?**: Windows 10 x64
> - **How installed?**: from source https://expanse.tech/
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: i don't know
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

![image](https://user-images.githubusercontent.com/35574087/38013816-f3345eba-327f-11e8-8895-f5d48f886166.png)
![image](https://user-images.githubusercontent.com/35574087/38015701-081fa4e6-3286-11e8-937b-750b082463e8.png)

**Comment by Tbaut** [comment]
You're here on Parity repo. Feel free to post any Parity related issue :)

**Comment by 5chdn** [comment]
It's a valid issue though because it also affects Parity.

@chrisfranko do you have _any_ working bootnodes?

**Comment by 5chdn** [comment]
Nevermind, the Parity bootnodes are working.

**Comment by olzhas498** [comment]
Hello! Help me. How do I Sync Node?

**Comment by Tbaut** [comment]
@olzhas498 If your question is related to Parity, Please have a look at [our wiki](https://wiki.parity.io/Getting-Synced) and feel free to ask anything on our [Gitter channel](https://gitter.im/paritytech/parity)

**Comment by chrisfranko** [comment]
We are in the process of launching a handful of new bootnodes because the
ones that are there are bogged down. Give me a few days and ill submit a
PR. Thanks. I apologize for the inconvenience. The problem is because we
moved from azure to digital ocean to save some money so half of them are
down.
