### ISSUE TITLE
health api with disabled dapps

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#8245]
> I'm running:
>
> - **Which Parity version?**: 1.10.0
> - **Which operating system?**: Linux
> - **How installed?**: via binaries
> - **Are you fully synchronized?**: -
> - **Which network are you connected to?**: -
> - **Did you try to restart the node?**: -

If `[dapps]` are disabled with `disable = true`, endpoint `/api/health` does not work (at least I don't know how to use it in this case)
```
$ curl http://localhost:8545/api/health
Used HTTP Method is not allowed. POST or OPTIONS is required
$ curl -X POST http://localhost:8545/api/health
Supplied content type is not allowed. Content-Type: application/json is required
$ curl -X POST -H 'Content-Type: application/json' http://localhost:8545/api/health
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```
Is there another way to retrieve node health status?

**Comment by 5chdn** [comment]
If you disable the dapps server, the health status is not available, correct.

If you want status about your node, please either enable the dapps server for health api or use the rpc apis.
