### ISSUE TITLE
Add option in trace_filter to skip empty/spam traces

### ISSUE THREAD

**Issue by Zvezdin** [paritytech/parity#8253]
Throughout the blockchain, there are many transactions that generate thousands upon thousands of traces, each one with `zero gas provided`, `zero gas usage` and `zero value transfer`. Please refer to the following etherscan parity trace: https://etherscan.io/vmtrace?txhash=0x3e20787055fdd28e5134ec8125743b89acf5422655410d770695528f8e7a9d4a&type=parity

Since they have no gas usage, nor value transfer, they don't seem to change the blockchain state. When using `trace_filter` to get historical traces, these spam ones amount to millions in just a few blocks (for example, the block range `2329500` to `2329999`) and the receiving side often can't handle that length. 

I think that it's a good idea to have an option / flag in the parameters of `trace_filter` that tells parity to not send these spam traces as a response.

**Comment by Tbaut** [comment]
@Zvezdin, these transactions with a big amount of subtraces should definitely fit in memory, even though they might not always be meaningful for your use case, they remain valid. These blocks are most probably the victims of the spam attack that happened on the network. We believe that the filtering of these transactions should happen on the client side and will not implement any filter for this anytime soon.
