### ISSUE TITLE
Single click doesn't work inside the UI

### ISSUE THREAD

**Issue by Varunram** [paritytech/parity#8255]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.5-unstable-ff821daf1-20180321/x86_64-macos/rustc1.24.1
> - **Which operating system?**: MacOS
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: Musicoin
> - **Did you try to restart the node?**: Yes

Expected Behaviour: Able to access different tabs with a single click
Actual Behaviour: Can access tabs only with a double click

**Comment by 5chdn** [comment]
Can you try the external wallet dapp with 1.10? https://github.com/Parity-JS/shell/releases

1.9 UI is discontinued.

**Comment by Varunram** [comment]
Will do, thanks.
