### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by vieiralc** [paritytech/parity#8263]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.4
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: dev
> - **Did you try to restart the node?**: yes

I'm following the Dapp tutorial but when I open the dapp on the browser nothing is shown and I get the following errors: 
![image](https://user-images.githubusercontent.com/19657718/38102213-faef15c6-3358-11e8-878b-c5c51dfe69e0.png)

**Comment by tomusdrw** [comment]
Hi @vieiralc please add `allowJsEval: true` to your `manifest.json`. We've recently disallowed `eval` by default.
To avoid that you should configure your build process to produce JS without `eval` (possibly it's just sourcemaps, so make sure to configure them differently).

**Comment by vieiralc** [comment]
@tomusdrw Thanks, it worked!
