### ISSUE TITLE
getBalance with argument of "pending" reports wrong balance

### ISSUE THREAD

**Issue by bittylicious** [paritytech/parity#8271]
I'm running:

> - **Which Parity version?**: 0.0.0

Parity/v1.9.5-stable-ff821daf1-20180321/x86_64-linux-gnu/rustc1.24.1

> - **Which operating system?**: Windows / MacOS / Linux

Linux Debian 9

> - **How installed?**: via installer / homebrew / binaries / from source

Official .deb

> - **Are you fully synchronized?**: no / yes

Yes

> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...

ethereum

> - **Did you try to restart the node?**: no / yes

No

Using the "pending" argument with getBalance, e.g. getBalance(<account>, 'pending'), appears to just return the actual balance (as per 'latest') instead of actually the balance of just pending transactions.

```
> eth.getBalance('0x2773a4d62ca464438236fb8799ab6da8b32446a3', 'latest');
20075430639333206193
> eth.getBalance('0x2773a4d62ca464438236fb8799ab6da8b32446a3', 'pending'); 
20075430639333206193
```

I can confirm that there doesn't just happen to be the same amount of Ether unconfirmed as there is confirmed. I would have expected the 'pending' call to return zero.

**Comment by tomusdrw** [comment]
Parity does not create pending block by default. Please try with `--force-sealing`. Upcoming 1.11 version will display warnings to make it easier to detect such behaviour.

**Comment by bittylicious** [comment]
Thanks. I'm happy to consider this invalid then.
