### ISSUE TITLE
Why does Parity complain 'Unable to make a connection to the Parity Secure API'?

### ISSUE THREAD

**Issue by hliu1020** [paritytech/parity#8273]
> I'm running:
>
> - **Which Parity version?**: 1.7.0
> - **Which operating system?**:  Linux, client using Mac
> - **How installed?**: via docker
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I run Parity on a remote server running Ubuntu 14.04 using Docker like this
    
    docker run -ti -d -p 8180:8180 -p 8545:8545 -p 8546:8546 
    -p 30303:30303 -p 30303:30303/udp parity/parity:v1.7.0 
    --ui-interface all --jsonrpc-interface all'

Then I visit http://[my remote server IP]:8180 from my laptop but run into the following errors

    Unable to make a connection to the Parity Secure API. 
    To update your secure token or to generate a new one, run parity signer new-token ...

So I generate a new token by running

    docker exec -it 3166d2e80682 /parity/parity signer new-token --ui-interface [The IP which I want to visit]
And I ensure the new token has been generated by checking the file authcodes

    docker exec -it 3166d2e80682 cat ~/.local/share/io.parity.ethereum/signer/authcodes

But Parity node still complains

    Unable to make a connection to the Parity Secure API. 
    To update your secure token or to generate a new one....

There is no firewall between my laptop and remote server and I want to know whether the method to generate token is wrong?

**Comment by Tbaut** [comment]
Could you please try by binding a volume like this `-v ~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/` ?
