### ISSUE TITLE
parity_removeTransaction - Method not found

### ISSUE THREAD

**Issue by kryvel** [paritytech/parity#8274]
Hi, 
wiki says that the module "parity" contains method parity_removeTransaction
But actually it doesn't work without module "parity_set" added to "apis = []' configuration option.

Wiki [parity](https://wiki.parity.io/JSONRPC-parity-module.html) page
Wiki [parity_set](https://wiki.parity.io/JSONRPC-parity_set-module.html) page

curl --data '{"method":"parity_removeTransaction","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST 127.0.0.1:8888
`{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}`

Is it bug in Parity or just outdated wiki pages ?

> I'm running:
>
> - **Which Parity version?**: v1.10.0-beta-0a9d41e29-20180320/x86_64-linux-gnu/rustc1.24.1
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

**Comment by 5chdn** [comment]
Created a ticket on the wiki tracker

**Comment by Tbaut** [comment]
The answer is given in OP, just add `parity_set` to the list of available APIs using the flag `--jsonrpc-apis`
