### ISSUE TITLE
Light node connection on a private network parity

### ISSUE THREAD

**Issue by jack750155** [paritytech/parity#8275]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Windows 10
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: Private Network
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have this configuration:
  - 2 full nodes (Geth implementation)
  - 1 Bootnode (Geth implementation)
This network correctly works. I tried to connect a full node with Parity implementation and Im connected well. I can get the new block, etc..

I want now to do the same with a light node. I tried this command:

`parity --chain D:\new_parity.json --light`

But I dont have the connection to the bootnode and so the peers. Only got that:

> 2018-03-30 17:01:16     0/50 peers    0 bytes cache  0 bytes queue  RPC:  2 conn,  1 req/s, 153 µs
> 2018-03-30 17:01:46     0/50 peers    0 bytes cache  0 bytes queue  RPC:  2 conn,  1 req/s, 130 µs
> 2018-03-30 17:02:16     0/50 peers    0 bytes cache  0 bytes queue  RPC:  2 conn,  1 req/s, 136 µs
> 2018-03-30 17:02:46     0/50 peers    0 bytes cache  0 bytes queue  RPC:  2 conn,  2 req/s, 202 µs

If someone already tried it, and can help me :)

**Comment by jack750155** [comment]
[EDIT]
I forgot to write the --lightserver VALUE on my first full nodes, so I light client couldn't be connected to them. :)

**Comment by rphmeier** [comment]
@jack750155 note that the Geth and Parity light client protocols are different (both experimental, will likely be merged at some point) so Parity light clients will only be able to connect to Parity full nodes. Probably the issue is that since the bootnodes are geth, they don't accept the Parity light client or connect it to the Parity full client.
