### ISSUE TITLE
Ability to cancel/edit future transactions has been removed in 1.9

### ISSUE THREAD

**Issue by bittylicious** [paritytech/parity#8282]
I'm running:

> - **Which Parity version?**: 0.0.0

1.9.5

> - **Which operating system?**: Windows / MacOS / Linux

Linux Debian 9

> - **How installed?**: via installer / homebrew / binaries / from source

Official .deb

> - **Are you fully synchronized?**: no / yes

Yes

> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...

ethereum

> - **Did you try to restart the node?**: no / yes

Yes

I am having an issue where transactions were are getting stuck in the "In queue: Future" state - see https://github.com/paritytech/parity/issues/8265

In 1.8.11, these transactions were visible in the Signer tab, and I could cancel or edit these to actually push them through manually.

However, in 1.9, this functionality is no longer present and it appears impossible, using the WebUI, to edit transactions in this state.

I can confirm that there appears to be no way to:

- Edit/cancel these from the TxQueue viewer DApp
- Edit/cancel these from the signer tab (there is no longer a signer tab)
- See these under the alarm/bell icon
- Clicking the alarm/bell icon does not show these transactions

So, it looks as though this functionality is now not present, which may be an oversight.

**Comment by 5chdn** [comment]
Should be moved but can't find the txqueue dapp repository, @jacogr @amaurymartiny ?

cc @Tbaut

**Comment by amaurymartiny** [comment]
Here: https://github.com/parity-js/dapp-localtx

**Comment by 5chdn** [comment]
Thanks, moved to https://github.com/parity-js/dapp-localtx/issues/1

**Comment by bittylicious** [comment]
Are you sure this should be moved? The LocalTX app never had this functionality; only the Signer tab in main Parity did.

I do agree it makes sense to put it in the LocalTX app though.

**Comment by bittylicious** [comment]
OK fine, just was hoping this was clarified. It's sort of a bug in the main Parity app (regression) but the enhancement/fix should probably go in the Dapp.
