### ISSUE TITLE
Use/inject web3 1.0.0 or any version of choice

### ISSUE THREAD

**Issue by 1blockologist** [paritytech/parity#8286]
How would I tell Parity to use a different web3 version if I wanted to?

Such as on the console

If that feature isn't there, then please implement it.

Last checked on Parity 1.9.5 on OSX

**Comment by Tbaut** [comment]
web3.js 1.0  [is not yet released](https://web3js.readthedocs.io/en/1.0/web3.html) so the console won#t use it yet.
Still, nothing prevents you to [install it on your machine with npm](https://web3js.readthedocs.io/en/1.0/getting-started.html#adding-web3-js) and [pointing it](https://web3js.readthedocs.io/en/1.0/web3.html#web3) to use your parity local node.

**Comment by 1blockologist** [comment]
Is it possible to do it the other way around, pulling it in within the parity console?

**Comment by Tbaut** [comment]
Unfortunately not sorry.
