### ISSUE TITLE
Parity UI not accepting new token when run with docker?

### ISSUE THREAD

**Issue by whitenoiseL** [paritytech/parity#8288]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Linux ubuntu
> - **How installed?**: via docker
> - **Which network are you connected to?**: private chain

I was trying to run a private chain via docker. It ran and mined pretty well.  Then I want to deploy a smart contract to it. When I tried to do it by browser, it asked me to enter a newly generated token. However, nothing happened after I did that. 
![image](https://user-images.githubusercontent.com/16938270/38194307-4c11e598-36a9-11e8-8107-5e17ac200b74.png)
Is there a way to solve this? Or are there any other ways to deploy smart contracts without using browser?

**Comment by Tbaut** [comment]
If you have a look at the browser console or the parity logs, you'll probably see that the WS calls from the UI are blocked.
You should make sure to tunnel the proper ports and allow the UI to get accessed from another IP. You may eventually also need to mount your local docker file. Give it a try with (some flags might not be needed/safe in your environment) : `sudo docker run --rm -ti --name parity -p 8180:8180 -p 8545:8545 -p 30303:30303 -p 8546:8546 -v ~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/ parity/parity:beta --ws-interface all  --jsonrpc-interface all --ws-origins all --ui-interface all`

**Comment by whitenoiseL** [comment]
Thanks a lot!!! I stupidly missed a port which caused the request kept being denied. Now it works!
