### ISSUE TITLE
Where did Parity download the Ethereum blockchain to?

### ISSUE THREAD

**Issue by JBeckintosh** [paritytech/parity#8291]
> I'm running:
>
> - parity version: 1.9.5-stable
> - operating system: Windows
> - installed via installer
> - fully synchronized: no
> - connected network: ethereum
> - Did you try to restart the node?: no

My C: filled up when synchronizing with Parity. For space reasons, I want to delete the ethereum blockchain that must have been downloaded, however I don't know where it is.

A lot of suggestions online say that it should be C:/users/{Username}/AppData/Parity or in some .parity file, neither of which are there.

I recognised that I wouldn't have enough space to download the blockchain into C: so I installed Parity in the D: and I have an Ethereum folder, which uses MkLink to connect to a folder in D: where the Ethereum chaindata is actually saved.

Hopefully this helps enough to find an answer. Please ask if more information is needed. I'd really like to clean up the space on my computer.

**Comment by Tbaut** [comment]
If you have installed Parity with the installer, without changing any install directory, and launched Parity with the windows application (not the command line) then your chain should be indeed in `C\Users\'username'\appdata/Parity/Ethereum`. AppData is a hidden directory, so make sure to enable these. Alternatively, do a search for ethereum (also within hidden files), you#ll find it.

Note that uninstalling Parity would have removed the chain.

**Comment by JBeckintosh** [comment]
I've checked, and the ethereum chain data is not there. I still have no idea where it is, or where it could be

**Comment by JBeckintosh** [comment]
This is not closed!

**Comment by Tbaut** [comment]
The default path has been given to you, this was your question. Now if your setup isn't standardyou should do a proper "windows search" including hidden files, there's not much more we can do for you here.

**Comment by mining-visualizer** [comment]
@Tbaut The information you gave was not correct.  The actual default path is `C:\Users\'username'\AppData\Roaming\Parity\Ethereum`  (note the 'Roaming' element)

**Comment by Tbaut** [comment]
Thanks, I edited
