### ISSUE TITLE
Trouble syncking Parity. DB flush failed.

### ISSUE THREAD

**Issue by rhofset** [paritytech/parity#8293]
> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Thread 'IO Worker #2' panicked at 'DB flush failed.: Error(Msg("Corruption: block checksum mismatch: expected 214673060, got 3257567002  in C:\\Users\\xxx\\AppData\\Local\\Parity\\Ethereum\\chains\\ethereum\\db\\906a34e69aec8c0d\\overlayrecent\\db/937740.sst offset 63629859 size 12657"), State { next_error: None, backtrace: None })', src\libcore\result.rs:916

**Comment by Tbaut** [comment]
Duplicate https://github.com/paritytech/parity/issues/7748
