### ISSUE TITLE
Stuck transaction block!

### ISSUE THREAD

**Issue by whitenoiseL** [paritytech/parity#8303]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: linux ubuntu
> - **How installed?**: via docker
> - **Which network are you connected to?**: private chain
> - **Did you try to restart the node?**: yes

One of my transactions which sends ether to contract stuck suddenly. The mining is running fine and other transactions can be deployed as usual. And when I try to deploy another function which sends the ether in the contract to an account, the gas limitation error occurs.
![_20180404183548](https://user-images.githubusercontent.com/16938270/38303081-890ae334-3837-11e8-932c-0758b9202809.png)
![_20180404183841](https://user-images.githubusercontent.com/16938270/38303085-8c266804-3837-11e8-9105-7b2f94a32d63.png)

Anyone have idea how to solve this?

**Comment by Tbaut** [comment]
The error message indicates that you are not sending enough gas.
To change the gas amount, click on `Edit conditions/gas/gasPrice` and make sure to have a higher value as the minimal estimated one (21272).
To understand better how gas and gasPrice works in Ethereum, have a look at https://myetherwallet.github.io/knowledge-base/gas/what-is-gas-ethereum.html
