### ISSUE TITLE
Registering new token in an account for erc 20 via CLI

### ISSUE THREAD

**Issue by Barun-Sharma** [paritytech/parity#8314]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**:  Linux
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I am able to successfully create account from Ubuntu CLI. I want to create wallet for each user in my application which should exchange only OMG token, to do so I need to add OMG in the token registry. 

Is there a way to add OMG to token registry of newly created account from CLI.

**Comment by 5chdn** [comment]
The token registry can be found at `0x5F0281910Af44bFb5fC7e86A404d0304B0e042F1` and the ABI should be available on Etherscan, but I think OMG is already registered.
