### ISSUE TITLE
Parity Stable branch does not compile on OSX

### ISSUE THREAD

**Issue by mudlee** [paritytech/parity#8315]
Hi all. Parity stable branch does not compile for me on OSX with the newest (1.25.0) rust.

> I'm running:
>
> - **Which Parity version?**: stable branch as a date of 5th April 2018
> - **Which operating system?**: MacOS
> - **How installed?**: from source

See the output here: [https://gist.github.com/mudlee/829364a63a6acbd359705cd2c11a7f8f](https://gist.github.com/mudlee/829364a63a6acbd359705cd2c11a7f8f)

**Comment by niklasad1** [comment]
Hi, you are using an old version of `app_dirs` it should be version `1.2.1`.

if you are running the latest version try:
```bash
$ cargo clean && cargo build
```

**Comment by mudlee** [comment]
But... how should upgrade? The rust is the latest (installed today than rustup update), and I cloned out this repo today. The master compiles well, the stable does not.

**Comment by rphmeier** [comment]
Indeed. We would need to either release an update to our stable and beta branches, or you can build them using an old version of the rust compiler (new versions of `rustc` broke old versions of `app_dirs`)

**Comment by mudlee** [comment]
I see, please notify me in this issue if its been patched. thx!

**Comment by niklasad1** [comment]
@mudlee Should be fixed now

**Comment by mudlee** [comment]
Yes it does build now, thx!
