### ISSUE TITLE
[RPC] Return more information by `eth_getTransactionReceipt`

### ISSUE THREAD

**Issue by AyushyaChitransh** [paritytech/parity#8321]
> I'm running:
>
> - **Which Parity version?**: Parity//v1.10.0-unstable-fb4582a90-20180205/x86_64-linux-gnu/rustc1.23.0
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private network
> - **Did you try to restart the node?**: NA

As of now, the response given by `eth_getTransactionReceipt ` is as follows:

```
{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "transactionHash": "0xb903239f8543d04b5dc1ba6579132b143087c68db1b2168786408fcbce568238",
    "transactionIndex": "0x1", // 1
    "blockNumber": "0xb", // 11
    "blockHash": "0xc6ef2fc5426d6ad6fd9e2a26abeab0aa2411b7ab17f30a99d3cb96aed1d1055b",
    "cumulativeGasUsed": "0x33bc", // 13244
    "gasUsed": "0x4dc", // 1244
    "contractAddress": "0xb60e8dd61c5d32be8058bb8eb970870f07233155", // or null, if none was created
    "logs": [{ ... }, { ... }, ...]] // logs as returned by eth_getFilterLogs, etc.
  }
}
```

It would be more informative if we have some more fields like:

 - from
 - to
 - gasPrice
 - Timestamp

We can refer to documentation of [web3.eth.getTransactionReceipt](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt) for more details.

Its just speculative as to which details we need. For example, we can do away with the timestamp.

**Comment by tomusdrw** [comment]
This info is available on the transaction itself, just use the hash to query a transaction. IMHO doesn't make sense to duplicate the data in those RPC calls.

**Comment by debris** [comment]
Agreed with @tomusdrw. `eth_getTransactionReceipt` is standardised and it's the same for all ethereum implementations. If you want to change it, please propose appropriate changes either to [ethereum wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) or create an EIP for that.

**Comment by Tbaut** [comment]
@debris the [ethereum wiki ](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionreceipt) does specify the transaction hash as a result of `eth_getTransactionReceipt` :)

**Comment by tomusdrw** [comment]
@Tbaut We do return transaction hash, the issue is mentions other transaction fields such as: from, to, gasPrice, timestamp (most likely block timestamp)

**Comment by Tbaut** [comment]
Need a coffee :)
