### ISSUE TITLE
"No valid password for the consensus signer" appearing randomly on startup

### ISSUE THREAD

**Issue by rustyx** [paritytech/parity#8328]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.5-stable-ff821daf1-20180321/x86_64-windows-msvc/rustc1.24.1
> - **Which operating system?**: Windows 10 x64
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: own chain (PoA)
> - **Did you try to restart the node?**: yes

I followed the [PoA tutorial](https://github.com/paritytech/wiki/blob/master/Demo-PoA-tutorial.md) and the two nodes are working, but both nodes will randomly refuse to start with the following error message:

```
Loading config file from node0.toml
2018-04-06 20:45:08  Starting Parity/v1.9.5-stable-ff821daf1-20180321/x86_64-windows-msvc/rustc1.24.1
2018-04-06 20:45:08  Keys path \tmp\parity0\keys\DemoPoA
2018-04-06 20:45:08  DB path \tmp\parity0\chains\DemoPoA\db\d6e60b1a32ec5efe
2018-04-06 20:45:08  Path to dapps \tmp\parity0\dapps
2018-04-06 20:45:08  State DB configuration: fast
2018-04-06 20:45:08  Operating mode: active
No valid password for the consensus signer 00bd…7c9e. Make sure valid password is present in files passed using `--password` or in the configuration file.
```

I checked that no other instance of `node0` is running.

The config is like [in the demo](https://github.com/paritytech/parity-poa-tutorial).

node0.toml:

```
[parity]
chain = "parity-poa.json"
base_path = "/tmp/parity0"
auto_update = "none"
[network]
port = 30303
[rpc]
port = 8545
cors = ["http://localhost/", "https://remix.ethereum.org/"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8180
[websockets]
port = 8645
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "none"
```

node1.toml:

```
[parity]
chain = "parity-poa.json"
base_path = "/tmp/parity1"
auto_update = "none"
[network]
port = 30304
[rpc]
port = 8546
cors = ["http://localhost/", "https://remix.ethereum.org/"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[websockets]
port = 8646
[ipc]
disable = true
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
reseal_on_txs = "none"
```

node.pwds:

```
node0
node1
```

The commands I use to start the nodes:

```
start parity --config node0.toml
start parity --config node1.toml
```

When I don't use the `start` command, i.e. I start `parity` from an already open console, the chance of this failure greatly reduces.

**Comment by themandalore** [comment]
Hey guys, 2 questions:
a) why is it still like this in the demo_POA
b)  what's the correct way to split them?

**Comment by Tbaut** [comment]
You can create 2 password files and pass each file to the authority node.

**Comment by hal149** [comment]
Hey!
First stop the chain,
You have to comment ('#') in the node0.toml and node1.toml :+1: 
```
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
reseal_on_txs = "none"
```
Start your chain,
Recreate account with the same parameters,
Stop the chain,
un-comments in node0/1.toml
Start the chain.

Have a nice day :)
