### ISSUE TITLE
Parity in light mode, auto return ETH when received

### ISSUE THREAD

**Issue by congnghiakhiem** [paritytech/parity#8336]
I use a parity wallet in light mode. I sent 0.01 Eth successfully. Then I sent 0.2 Eth successfully.
But it return 0.166528186212708 Eth automatically.
I tried to send more Eth, but it still return 0.166528186212708 Eth to the source address.
When its balance is 0.07483406893645824 Eth, I tried to send out 0.025 Eth. It return a transaction hash. But this transaction hash is unable to locate by etherscan.io :(

**Comment by Tbaut** [comment]
Can you please anser the questions : 
> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

And give more insights about how you send your ETH (RPC, UI ?), and eventually give some Tx Hash for us to have a look.
>I tried to send more Eth, but it still return 0.166528186212708 Eth to the source address.

What do you mean exactly with "return", did the Eth get out, and then in again (can you provide a Tx Hash also to verify it ?)

**Comment by debris** [comment]
> I tried to send more Eth, but it still return 0.166528186212708 Eth to the source address.

I removed labels, cause it's technically not possible

**Comment by congnghiakhiem** [comment]
I'm running:

Which Parity version?: version Parity/v1.11.0-unstable-54c9c38-20180402/x86_64-linux-gnu/rustc1.25.0
Which operating system?: CentOS Linux release 7.4.1708 (Core)
How installed?: from source
Are you fully synchronized?: no (light = true)
Which network are you connected to?: default
Did you try to restart the node?: yes
