### ISSUE TITLE
Cannot unlock account

### ISSUE THREAD

**Issue by Pzixel** [paritytech/parity#8339]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Linux
> - **How installed?**: docker image
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm trying to unlock account on the node via `--unlock` option in parity.

My steps:

1. Geth attach to the machine
1. Type `personal.newAccount()`. Copy Account address `0x4d871ec265596529da5940b3bfa6375faa6e00a9`
1. Enter passphrase `mypassword`
1. `echo "mypassword" > ./parity/config/passwords.txt`
1. add following to docker-compose:
```yml
    command:
      --unlock 0x4d871ec265596529da5940b3bfa6375faa6e00a9
      --password /parity/config/passwords.txt
      ...
    volumes:
      - ./parity/config:/parity/config:ro
      ...
```
1. run nodes

#### Expected behaviour
node starts with unlocked account.

#### Actual behaviour

```
authority0_1  | Loading config file from /parity/config/authority.toml
authority0_1  | Option '--dapps-interface' is deprecated. Please use '--jsonrpc-interface' instead.
authority0_1  | 2018-04-09 15:28:52 UTC Starting Parity/v1.9.5-stable-ff821da-20180321/x86_64-linux-gnu/rustc1.24.1
authority0_1  | 2018-04-09 15:28:52 UTC Keys path /root/.local/share/io.parity.ethereum/keys/parity-poa-playground
authority0_1  | 2018-04-09 15:28:52 UTC DB path /root/.local/share/io.parity.ethereum/chains/parity-poa-playground/db/d24f9ddc2dd71e78
authority0_1  | 2018-04-09 15:28:52 UTC Path to dapps /root/.local/share/io.parity.ethereum/dapps
authority0_1  | 2018-04-09 15:28:52 UTC State DB configuration: fast
authority0_1  | 2018-04-09 15:28:52 UTC Operating mode: active
authority0_1  | No valid password for the consensus signer 00bd…7c9e. Make sure valid password is present in files passed using `--password` or in the configuration file.
```

I've checked `run.rs` and found nothing that may cause this behaviour, but I don't understand what should I fix to make it work.

**Comment by Tbaut** [comment]
@Pzixel the message mentions that the consensus signer doesn't get unlocked. This is related to your `authority.toml`. Make sure to have the password for both `00bd…7c9e` **and** `4d871...00a9` in your `passwords.txt` as the `--password` flag will override anything you set in `authority.toml`

**Comment by Pzixel** [comment]
@Tbaut thank you for response. My authority accounts doesn't have password at all. Does app expect that it's possible?

**Comment by Tbaut** [comment]
I don't think that Parity expects it. Could you try to set up your authorities with some passwords?

**Comment by Pzixel** [comment]
@Tbaut yes, it currently works with passwords, however accounts may actually have no passwords so it may be considered as a bug.

**Comment by Tbaut** [comment]
It is somehow unexpected I agree, but low prio as not advised. Also using `--unlock` isn't secure, consider using `personal_sendTransaction` if this suits your needs.
