### ISSUE TITLE
Increase blocksize limit for the dev chain

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#8342]
Currently, it does not seem possible to pass arguments while using `--chain dev` to influence the gas limit per block. Did I miss an option?

The limit seems to be current set around ~6.6M

Since the network runs now around 8M, I would suggest to bump the limit for the specs of the dev chain to 10~12M.

**Comment by Tbaut** [comment]
As explained in the chat, please
- copy this file locally: https://github.com/paritytech/parity/blob/master/ethcore/res/instant_seal.json 
- modify the `gasLimit` parameter to what is acceptable for your needs
- launch parity with the flag `--chain /path/to/modified_instant_seal.json`

**Comment by chevdor** [comment]
ok, but that does not address the issue.
Why keeping dev at a low value, way below le 8M of mainnet?

**Comment by chevdor** [comment]
Thank you @Tbaut !

**Comment by 5chdn** [comment]
> Why keeping dev at a low value, way below le 8M of mainnet?

Main network was at 3 million for quite a long time.
