### ISSUE TITLE
Allow defining call data for chain spec contract constructors

### ISSUE THREAD

**Issue by andresilva** [paritytech/parity#8358]
Currently the contract constructors that are defined in the chain spec cannot have any call data, which means the contract must have a no-arg constructor.

**Comment by folsen** [comment]
@andresilva what's the motivation behind this?

**Comment by andresilva** [comment]
The issue isn't entirely correct. The chainspec allows defining constructor bytecode to instantiate new accounts at specific addresses: 

https://github.com/paritytech/parity/blob/master/ethcore/res/authority_round_block_reward_contract.json#L58

If you have a constructor that takes arguments you'll have to append the encoded arguments to the bytecode (there's no separate field in the JSON file for the arguments). TBH since this interface is low-level enough and this is the same way arguments are encoded when creating a contract it's probably ok to leave it as is and close the issue.
