### ISSUE TITLE
parity crash on launch

### ISSUE THREAD

**Issue by scott-lew-is** [paritytech/parity#8374]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Windows 
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Can't start parity today, worked fine yesterday, getting this error message today:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	parity.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5ab22e07
  Fault Module Name:	parity.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5ab22e07
  Exception Code:	c000001d
  Exception Offset:	0000000000ec8734
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	16d4
  Additional Information 2:	16d43347f21070c7bfb2282afd72ac60
  Additional Information 3:	259b
  Additional Information 4:	259b491735ecf3e80f318ae320a01640

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by Tbaut** [comment]
@scott-lew-is can you [launch parity with the command line](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#how-to-launch-parity-using-the-command-line-on-windows) and post here the results?
