### ISSUE TITLE
Parity doesn't open

### ISSUE THREAD

**Issue by aydem673** [paritytech/parity#8375]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I installed parity yesterday. It didn't fully sync as it was stuck at 65.58 at some time and i closed it after that. Today, when i try to open, i get the endless message of "connecting to the parity node. if this message persists please ensure that your parity node is running..." Also, when i try to open parity.exe i get the error attached.
![ekran alintisi](https://user-images.githubusercontent.com/23107162/38630416-8d4b6d96-3dbf-11e8-8409-8442c55acf94.PNG)

**Comment by Tbaut** [comment]
This is a similar problem as https://github.com/paritytech/parity/issues/7447
Please follow this issue.
