### ISSUE TITLE
Parity Ethereum Classic - core dumped

### ISSUE THREAD

**Issue by papayena** [paritytech/parity#8379]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.11.0-unstable-0a170ef-20180411/x86_64-linux-gnu/rustc1.25.0
> - **Which operating system?**: Linux Ubuntu 17.10
> - **How installed?**: via one-line-installer (bash <(curl https://get.parity.io -L)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum classic
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Node was running for a few hours after has been fully synchronized.

**Then I got the error below:**
stack backtrace:
   0:     0x55d5a6eb86ac - backtrace::backtrace::trace::he2a53911ce7ca877
   1:     0x55d5a6eb6f62 - backtrace::capture::Backtrace::new::h02665953184203ca
   2:     0x55d5a643d8eb - panic_hook::panic_hook::h3c62f8c3aaeaf957

Thread 'Verifier #0' panicked at 'DB flush failed.: Error(Msg("IO error: While open a file for appending: /home/user/snap/parity/10447/.local/share/io.parity.ethereum/chains/classic/db/906a34e69aec8c0d/overlayrecent/db/002875.log: Permission denied"), State { next_error: None, backtrace: None })', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

**Comment by niklasad1** [comment]
I guess you don't have write privileges to the file `/home/user/snap/parity/10447/.local/share/io.parity.ethereum/chains/classic/db/906a34e69aec8c0d/overlayrecent/db/002875.log`.

You have to either change the privileges on the `file` itself or execute `parity` as a user/group with write privileges to the file!
