### ISSUE TITLE
Parity 1.9.5 fast sync killed , on #2430730 , #2430755

### ISSUE THREAD

**Issue by trustfarm-dev** [paritytech/parity#8384]
**Which Parity version?**: Parity/v1.9.5-stable-ff821da-20180321/x86_64-linux-gnu/rustc1.24.1
**Which operating system?**: Ubuntu 16.04.03
**How installed?**: .deb package in release folder.
**Are you fully synchronized?**: no
**Which network are you connected to?**: ethereum
**Did you try to restart the node?**: yes several times. retry with scratch

**actual** : 
Parity doesn't sync on +Fast +FatDB +Tracing options.
**Terminal Logs**

followings solved by increase swap.
But, another position has same problem.

Another solved method:: 
sync with same option in different PC (windows) over the block 3M , and overwrite linux chains.
and run on linux works.

But, I think it is problem, when memory short, inform more detail informations log out.
So, more good way of setup and changing configuration for progress.

```
2018-04-12 21:29:50  Syncing #2425690 978e…4cdc     0 blk/s    0 tx/s   0 Mgas/s      0+11810 Qed  #2437501   31/100 peers   75 KiB chain 14 GiB db 70 MiB queue 23 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-04-12 21:29:59  Syncing #2425691 440e…1b3c     0 blk/s    0 tx/s   0 Mgas/s      0+11810 Qed  #2437501   31/100 peers   93 KiB chain 14 GiB db 70 MiB queue 23 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

Killed
```
**Tried options**
default just pruning options : 
     parity --pruning=fast --fat-db=on --tracing=on --db-compaction=ssd 
2nd~4th - with change of cache size : 
     parity --pruning=fast --fat-db=on --tracing=on --db-compaction=ssd --snapshot-peers=50 --min-peers=100 --max-peers=300 --pruning-history=100000  --cache-size-db=1024 --cache-size=16384

5th :
parity --fat-db=on --tracing=on --db-compaction=ssd --snapshot-peers=50 --min-peers=100 --max-peers=300 --pruning-history=100000 --cache-size-db=1024 --cache-size=16384 --can-restart -l debug --log-file paritylog.txt

All has killed.

debug logs shared on : https://drive.google.com/file/d/1OJlT6e5OTaOK4dOLAIvxBu6B_-cZvztw/view?usp=sharing

**Comment by sorpaas** [comment]
Looks like the standard error near the suicide-attack blocks and running out of memory.

@trustfarm-dev Can you increase your swap memory size and make sure you have at least 8GB of memory in total?

**Comment by trustfarm-dev** [comment]
@sorpaas 
thanks for fast reply.
16GB real memory. run with ubuntu desktop
16GB default swap.

-- NOW change swap size to additional 16GBswapfile , totally 48GB.

```
and overcome suiside call ddos block.
sudo dd if=/dev/zero of=/tmp/16GBswapfile.img bs=1024 count=32M
sudo chmod 600 /tmp/16GBswapfile.img

# adds /etc/fstab for swap
/tmp/16GBswapfile.img                   swap swap sw 0 0

# mkswap
sudo mkswap /tmp/16GBswapfile.img

# swap on 
sudo swapon /tmp/16GBswapfile.img 
```

**Comment by trustfarm-dev** [comment]
increased swap space to more 32GB , it has overcome ddos block.

@5chdn @sorpaas ,
How about skip checking give to known ddos block , when fast or archive mode of sync?
We already known that's several blocks of normal transactions' snapshots.
thanks.

In case of full archive mode of ETH syncing is not possible , over 1months in my server.

**Comment by 5chdn** [comment]
You can't build an archive without actually processing the blocks.

Also, the spam blocks are no issue anymore. The real annoyance will be blocks 4_000_000 +

So, if your server has issues with the spam blocks, upgrade your hardware immediately. You should be able to sync the first 4 million blocks with an archive node within 48 hours on a decent enterprise-grade SSD.

**Comment by trustfarm-dev** [comment]
I've trying several nodes for sync chains.

Now, I'm using freshen 1T SSD and 64GB mem , windows server.
and trying to sync full , with above your comments.

check my configurations.
https://drive.google.com/file/d/1P8b7LhiwNAvZOJYKBrJ9rPSGysunb9py/view?usp=sharing 

@5chdn

**Comment by trustfarm-dev** [comment]
after  #2717788 block  , sync well.
I've used already synced archive chain after above blocknumber, then syncs well.

**Comment by trustfarm-dev** [comment]
2018-04-13 00:46:36  Syncing #2430730 9088…970f     0 blk/s    0 tx/s   0 Mgas/s      0+24572 Qed  #2455305   66/100 peers   15 MiB chain 29 GiB db 160 MiB queue 14 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-04-13 00:46:45  Syncing #2430739 57a9…aa68     1 blk/s   20 tx/s   0 Mgas/s      0+24564 Qed  #2455305   67/100 peers   15 MiB chain 29 GiB db 159 MiB queue 14 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
killed

**Comment by trustfarm-dev** [comment]
still #2430755 spam block makes sync fail.
How to disable or skip if spam blocks?

logs :: https://drive.google.com/open?id=12xqQEXNQZJHlt35cKDl9V05GbKZwTrYf

**Comment by trustfarm-dev** [comment]
@sorpaas  , plz check updated issue descriptions. 
thnx

**Comment by sorpaas** [comment]
@trustfarm-dev What filesystem do you use? Can you run `df -h` and see how much free space do you have?

**Comment by trustfarm-dev** [comment]
ext4 . freespace is not a ploblem.
```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
tmpfs           1.6G  156M  1.4G  10% /run
/dev/sda1       220G   86G  123G  42% /
tmpfs           7.7G  119M  7.6G   2% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/sdb1       3.6T  352G  3.1T  11% /srv
tmpfs           1.6G  144K  1.6G   1% /run/user/1000
```

123GB free space on SSD. 

now, copy 3.9M fast +FatDB , from windows server (same configuration), and now faster than windows server. 

```
2018-04-16 19:07:28  Syncing #4168336 9703…626f    10 blk/s  960 tx/s  46 Mgas/s      0+  696 Qed  #4169036   102/300 peers   300 MiB chain 644 MiB db 67 MiB queue 33 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

```
and, fast chain storage is followings::

```
trustfarm@ujsrv10:~/.local/share/io.parity.ethereum$ du -h
67M	./cache
8.0K	./keys/ethereum
12K	./keys
4.0K	./signer
4.0K	./dapps
33G	./chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db
33G	./chains/ethereum/db/906a34e69aec8c0d/overlayrecent
4.0K	./chains/ethereum/db/906a34e69aec8c0d/snapshot
33G	./chains/ethereum/db/906a34e69aec8c0d
33G	./chains/ethereum/db
704K	./chains/ethereum/network
33G	./chains/ethereum
33G	./chains
8.0K	./network
33G	.
```

**Comment by sorpaas** [comment]
There's no panic message in the Parity log. So if it's killed, it means it's the kernel that did that. So I guess it still means you don't have enough memory. You mentioned you have 64GB memory on the host. Can you make sure you increased memory size for the VM?

And next time if the kill happens, please run `dmesg -T | grep 'killed process'` which will print the kernel logs for OOM killer.

**Comment by trustfarm-dev** [comment]
@sorpaas  , All is killed by OOM.
So, I tried close desktop GUI Program, it go.
and, Recent 5.27M blocks, in case of fast sync that's very slow in Ubuntu and Windows.
Anyway close this issue now.
thnx.
