### ISSUE TITLE
Docker - Can't establish a connection to the server at ws://127.0.0.1:8546

### ISSUE THREAD

**Issue by lucachaco** [paritytech/parity#8387]
I managed to open the UI at localhost but in the console i get this error. Please see in the console the options i use to run parity

> I'm running:
>
> - **Which Parity version?**: 1.11
> - **Which operating system?**: Linux
> - **How installed?**: via installer  from source
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: no / yes

![ws error](https://user-images.githubusercontent.com/85146/38688329-04397e36-3e36-11e8-8214-9f055d25f036.PNG)

**Comment by Tbaut** [comment]
Try to remove `--ui-interface all`

**Comment by lucachaco** [comment]
Hmm doesnt work

**Comment by lucachaco** [comment]
If I remove --ui-interface all it would not even load the ui. I am using docker

**Comment by lucachaco** [comment]
Ok, It work somehow with this combination `./parity --force-ui --ui-interface all --jsonrpc-interface all --ws-interface all --ws-origins all --ws-hosts all`

**Comment by Tbaut** [comment]
I updated your title to mention you're in a Docker since I wasn't stated anywhere ;)
