### ISSUE TITLE
Fetching Block Headers from Parity's Rocks DB in Go

### ISSUE THREAD

**Issue by rmulhol** [paritytech/parity#8389]
> I'm running:
>
> - **Which Parity version?**: 0.0.0
Parity/v1.11.0-unstable-d7a7f03-20180406/x86_64-macos/rustc1.25.0
> - **Which operating system?**: Windows / MacOS / Linux
MacOS
> - **How installed?**: via installer / homebrew / binaries / from source
From source
> - **Are you fully synchronized?**: no / yes
yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
Ethereum
> - **Did you try to restart the node?**: no / yes
Yes

Hi! Posting here after referral from Parity Gitter. Feel free to redirect me elsewhere.

I'm trying to figure out how to read Block Header RLP data from Rocks DB in Go. I've been able to fetch this data from Level DB using tools in [go-ethereum](https://github.com/ethereum/go-ethereum/blob/ca64a122d33008c155c35a9d0e78cfbcafb1820a/core/database_util.go#L162) and have been using that to check my work.

To get after the headers in Rocks from Go, I've started using [gorocksdb](https://github.com/tecbot/gorocksdb/blob/1a1769a927137cecbf1d0af1c16744fd3adc1621/db.go#L252). I'm querying for `COL_HEADER` with the block hash, and I've replicated the swapping logic from Parity's [decompression engine](https://github.com/paritytech/parity/blob/master/util/rlp_compress/src/lib.rs#L53).

However, the data I'm getting back is ever so slightly malformed. The first 18 bytes do not match what I get back from LevelDB. For example, for block 5390000, here are hex representations of the bytes I get back: 

LevelDB:
```
0xf9020ea06234902ba11d4bfeafd9907e63288243634850e7b20346dcfa76718db0871b3fa096d34a860533c56fd981a8ef236368c26bd1dc7c076d81a51c33b529c68a987094ea674fdde714fd979de3edf0f56aa9716b898ec8a05b5d9e7b7a3cc4bc426cd5e0e13c38c7b14601e24e2e81d7c433dd6fdeaa3f06a0c4f4e0ca9e72ac1d0c857ee40ef38d2153733799113f58cdd5505342227bc52aa0cb688283fdd24feee5ab7241a74d66e9273eb6212292384b712bdce83ea9628eb90100058662ae246a2a5551093414001582990504909d202042d048640341002981680924870110a0417dc2105aa2905b24ae020a8b400b9995081600d6050233008999ca10758224d481ca905228c0a4244001901108015ac26104b98501aa4800041010a400a35202408940623b20382e221e0603800c4786019090435110607000a01951c0605411203060a00dd0418da804ab85010e6885bc4203a0148863ec340b7542085152f400038812b0f1d49d00140584a596048a20028b01a48868150487289453894c8021011a00104ba860a60002a024330872cd282918190004a015071031012822110b810c7180c116a93c402dbc0740020140d09572a88089c982870bab3abda4fcec83523eb0837a121d8379eb59845ac729ea8d65746865726d696e652d657534a07c308a559d58150b4b648f5e640af1c4b4b70fdfba9fe49906e113ee930b3446884aaac6680fd13b3c
```

RocksDB:
```
0x0000000000000000000000000000000033008243634850e7b20346dcfa76718db0871b3fa096d34a860533c56fd981a8ef236368c26bd1dc7c076d81a51c33b529c68a987094ea674fdde714fd979de3edf0f56aa9716b898ec8a05b5d9e7b7a3cc4bc426cd5e0e13c38c7b14601e24e2e81d7c433dd6fdeaa3f06a0c4f4e0ca9e72ac1d0c857ee40ef38d2153733799113f58cdd5505342227bc52aa0cb688283fdd24feee5ab7241a74d66e9273eb6212292384b712bdce83ea9628eb90100058662ae246a2a5551093414001582990504909d202042d048640341002981680924870110a0417dc2105aa2905b24ae020a8b400b9995081600d6050233008999ca10758224d481ca905228c0a4244001901108015ac26104b98501aa4800041010a400a35202408940623b20382e221e0603800c4786019090435110607000a01951c0605411203060a00dd0418da804ab85010e6885bc4203a0148863ec340b7542085152f400038812b0f1d49d00140584a596048a20028b01a48868150487289453894c8021011a00104ba860a60002a024330872cd282918190004a015071031012822110b810c7180c116a93c402dbc0740020140d09572a88089c982870bab3abda4fcec83523eb0837a121d8379eb59845ac729ea8d65746865726d696e652d657534a07c308a559d58150b4b648f5e640af1c4b4b70fdfba9fe49906e113ee930b3446884aaac6680fd13b3c
```

As you can see, everything matches except for the very beginning. Where the LevelDB RLP data begins with `0xf9020ea06234902ba11d4bfeafd9907e6328`, the RocksDB RLP data begins with `0x000000000000000000000000000000003300`. Interestingly, the RocksDB data appears to be chopping off roughly half of the parent hash: `0x6234902ba11d4bfeafd9907e63288243634850e7b20346dcfa76718db0871b3f`, of which the substring `8243634850e7b20346dcfa76718db0871b3f` is present in both sets of data.

Of course this mismatch could be derived from just about anywhere in my stack, but I'm wondering whether anything jumps out to those of you who have worked closely with hooking Parity up to Rocks DB. Does the parent hash need to be fetched from somewhere else? Is there another decompression step I might be missing? Has anyone built a working way to read block headers from Rocks DB outside of Parity that I could inspect? Appreciate any insights!

**Comment by rmulhol** [comment]
Update: it seems that the missing 18 bytes can be resolved by some gorocksdb plumbing. However, I'm still seeing issues that I believe relate to errors in attempting to replicate Parity's `rlp_compress` functionality.

As near as I can tell, successful decompression requires that (InvalidRLPs)[] be replaced with (CommonRLPs)[] if the InvalidRLP appears in a place where it (is_data)[]. Importantly, data that looks like an InvalidRLP can appear in places where it is not data (e.g. in the value for a block's LogsBloom), in which case it should _not_ be replaced.

This leads me to a few further questions:

- Is this formulation accurate? I'm a little skeptical as to whether that `is_data` check is the crux for determining whether bytes matching a value in the InvalidRLPs ought to be decompressed/replaced or returned as raw, as it seems possible that the method would return true even in cases where the data coming back from Rocks is already decompressed.
- Is there any general documentation that addresses strategies for decompressing Parity's RocksDB data outside of Rust?
- How do you determine what CommonRLP should replace a given InvalidRLP? Just match by index. As there are many more InvalidRLPs than CommonRLPs declared, do InvalidRLPs with an index beyond the terminal index in CommonRLPs simply get swapped with the final CommonRLP?

Thanks!

**Comment by 5chdn** [comment]
Might be worth asking on https://ethereum.stackexchange.com to attract a broader audience.
