### ISSUE TITLE
Have network-specific critical flag for auto-updater

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#8392]
Currently we have a single `critical` flag defined in `util/version/Cargo.toml`.
This is a pain if the update is critical on say kovan, but not on mainnet.

Instead we should store separate flags for each network and update https://github.com/paritytech/push-release to read those.

**Comment by tomusdrw** [comment]
I'd bump priority on this one.

**Comment by ascjones** [comment]
Should we aggregate network specific auto-updater settings e.g

```
[package.metadata.networks]
foundation = { forkBlock = 4370000, critical = false }
ropsten = { forkBlock = 10, critical = false }
kovan = { forkBlock = 6600000, critical = false }
```

or just add another section with critical flags for each network? Is the existing critical flag is only used by `push-release`?

**Comment by tomusdrw** [comment]
1. IMHO aggregate looks nicer.
2. Critical is only used by push-release
