### ISSUE TITLE
CLI signer does not work

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#8393]
The CLI signer does not work, sends invalid requests to RPC. IMHO it's important to get it working since we are separating the UI and there will be no other way to confrim the request.

**Comment by ascjones** [comment]
@tomusdrw still need to update to a new version of primitives in order to complete the fix

**Comment by ascjones** [comment]
This issue keeps closing automatically by github from the other repo issue, probably because of the fix keyword.
