### ISSUE TITLE
ReceiptError & TrieError & Error

### ISSUE THREAD

**Issue by EighteenZi** [paritytech/parity#8395]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: latest
> - **Which operating system?**:  Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I came into the usage of `Error` types.

In executive.rs,  the return type of 'transact_with_tracer'  is 
```
Result<Executed<T::Output, V::Output>, ExecutionError>
```
and in the method, a lot of 'Err(**_From::from_**(**_ExecutionError_**::XXXX' are used.
But the input type of 'From::from' is TrieError, as follows.
```
impl From<Box<trie::TrieError>> for ExecutionError {
	fn from(err: Box<trie::TrieError>) -> Self {
		ExecutionError::Internal(format!("{}", err))
	}
}
```
I have 2 questions: 
1. The ExecutionError::XXXX is already of the same type with the Return type, Why using `From::from` ?
2. the `state.nonce()` needs `From::from`, why is not used?

Are there some advanced Rust skills used there?

Thanks a lot.

**Comment by tomusdrw** [comment]
1. Probably legacy, in the past the output of the method might have been `ethore::Error` not more specific `ethcore::ExecutionError`.
2. Does it use `?` operator? That one does `From::from` automatically.
