### ISSUE TITLE
Unregistering of some badges

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#8396]
Discussed with @Tbaut.

Please unregister the following badges on mainnet:
- [ ] id: 7
- [ ] id: 11

Happy to prove that I am the owner if you check (which I hope you do !)

**Comment by 5chdn** [comment]
Who is the owner of the badgeregistry?

**Comment by chevdor** [comment]
`0x3FF047E5E803e20f5eF55eA1029aDB89618047Db`

**Comment by 5chdn** [comment]
Good news, I removed them! :)
