### ISSUE TITLE
TestMinerService should support the mining API

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity#840]
So that we can write unit tests for the mining stuff.

**Comment by 5chdn** [comment]
This _tests_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days this is still on the roadmap and _nice to have_. If so, please add an assignee, or close otherwise.

**Comment by rphmeier** [comment]
I would say this is obsolete; we're moving more towards a generalized "sealing" API which is decently well tested.
