### ISSUE TITLE
After finished block syncing, parity occasionally running with 100% CPU

### ISSUE THREAD

**Issue by yihuang** [paritytech/parity#8404]
In the log I see something like:

``Transaction mined (hash ...)``

Is parity doing cpu mining by default? The json-rpc api is very slow, causing timeout error. 
I only want to run a full node with json-rpc api, my current argument is follow, is that correctly?

```
 --jsonrpc-apis=all --cache-size=2048 --geth --mode=active --min-peers=50 --max-peers=100 --db-compaction=ssd
```

**Comment by 5chdn** [comment]
@yihuang parity does not contain any miner. `transaction mined`, means _someone_ confirmed your transaction and sealed a block.
