### ISSUE TITLE
refactor parity-dapps-glue crate

### ISSUE THREAD

**Issue by debris** [paritytech/parity#8405]
Currently `parity-dapps-glue` uses `quasi`, which is no longer maintained - [serde-deprecated/quasi](https://github.com/serde-deprecated/quasi). Let's use refactor it to use `proc-macro`, `syn` and `quote` instead

cc @tomusdrw

**Comment by folsen** [comment]
Closing because UI is moving.

**Comment by sorpaas** [comment]
I think we probably still need to keep this issue open for a while. Currently `parity-dapps-glue` crate is still in the code -- we would either need to remove it or do the refactoring described in this issue.

**Comment by tomusdrw** [comment]
What is the glue still used for? As a workaround we can just hardcode the generated code instead of rewriting it.

**Comment by sorpaas** [comment]
@tomusdrw For our current code we're only using the `WebApp` trait and `Info` struct. They're perfectly fine to be moved to `parity-dapps` crate. The only issue is that if someone wants to create a new builtin dapp (https://github.com/paritytech/parity/tree/master/dapps/js-glue) in a customized version of parity, they rely on the js-glue crate right now.

No matter what we do, this will eventually be fixed when Parity UI takes over all dapps functionalities and we should then be able to remove the js-glue crate.

**Comment by folsen** [comment]
Ping @axelchalon this might be something semi-related to what you're working on and of interest for you to look at?

**Comment by axelchalon** [comment]
Hey, I don't think parity-dapps-glue is used for anything anymore. Built-in dapps are now completely handled by Parity UI.

I was thinking that as soon as the [Parity UI network dapps PR](https://github.com/parity-js/shell/pull/144) is reviewed and merged, we can remove the whole dapps crate (incl. parity-dapps-glue) and dapps-related cli/config options in one fell swoop.

**Comment by axelchalon** [comment]
parity-dapps-glue removed in https://github.com/paritytech/parity/pull/9017
