### ISSUE TITLE
ETC node reboots with about 20 nodes but after 1 week dwindles down to about 2.  Why peer count degrades in time?

### ISSUE THREAD

**Issue by cseberino** [paritytech/parity#8415]
I'm running Parity 1.9.5 on Ubuntu Linux 16.04 installed via the Debian package.
I'm fully synced and connected to ETC (CLASSIC).
I'm running Parity with these switches...
`/parity --chain classic --jsonrpc-apis eth,net,parity,personal,web3 --ipfs-api --ipfs-api-hosts all`

Issue is that when I restart Parity it obtains about 20 peer node connections but then
after 1 or 2 weeks it dwindles down to 2 or 3.

How maintain high number of peer connections?

**Comment by Tbaut** [comment]
@cseberino could you try with the flags `--min-peers 25 --max-peers 50` to force parity to constantly try to have at least 25 peers?

**Comment by cseberino** [comment]
Tbaut:  I added those 2 switches overnight yet my Parity node is stuck at 6 node now.

**Comment by Tbaut** [comment]
Does your application require to have more? With not so good internet connection, I am used to seeing a lower amount of peers. 
If you want to dig deeper you can run your node with `-l sync=trace` (very verbose) and post it in a gist.

**Comment by cseberino** [comment]
Tbaut:  Thanks for the help.  Indeed those switches produced a huge amount of output.  To answer your questions, I don't *need* to have more.  (I currently have 8.)  I just don't know what is normal and if my inability to get 25 on ETC network is indicative of a mistake in my setup or not.  If you say that is expected I'm ok with it.

If I have any concern it is just that the count may drop to 1 or 2 or even zero.  That is main reason to want to hold at 25 peer connections is possible.

**Comment by Tbaut** [comment]
I understand. If you do drop to 1/2 peers, please launch parity with the flags `-l sync=trace` and post the output here. We'd reopen the issue.

**Comment by 5chdn** [comment]
#7531
