### ISSUE TITLE
Return appropriate error when data>300kb for own transactions

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity#8417]
Following discussions at https://github.com/paritytech/parity/issues/8301

The limitation currently is imposed on the network layer (see MAX_TRANSACTION_SIZE) and we just ignore incoming transactions larger than 300kb, probably would be good to:

- return error for own transactions exceeding that limit (additional check in verification pipeline)
- make it configurable (spec?)

**Comment by debris** [comment]
@grbIzl could you look into this?

**Comment by grbIzl** [comment]
Sure!

**Comment by folsen** [comment]
@grbIzl Did your PR fix this issue? If so please close.

**Comment by grbIzl** [comment]
Closed by #8473
