### ISSUE TITLE
Parity default paths changed. (app-dirs)

### ISSUE THREAD

**Issue by cosminstefane** [paritytech/parity#8418]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.6 and 1.10.1
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I updated parity first to 1.9.6 after running 1.9.5. For some reason it doesn't load up the config.toml file. Even when I use -c options it tells me the config is not a preset. I need to run parity with some settings, including non-standard location for the DB. Tried 1.10.1 and it's the same.

**Comment by Tbaut** [comment]
You most probably have changed the work directory and your config file isn't found. How do you launch parity ? can you paste the logs here?
Try `parity --config /absolute/path/to/config.toml`

**Comment by cosminstefane** [comment]
I did and it works. I believe the default locations have been changed on windows somehow. I noticed I also noticed neither one of my accounts are "imported" into parity either.
1.10.1 Keys path C:\Users\XXX\AppData\**Local**\Parity\Ethereum\keys\Foundation
1.9.5   Keys path C:\Users\XXX\AppData\**Roaming**\Parity\Ethereum\keys\Foundation
For some reason the location changed from ROAMING as before to LOCAL...

This is not expected behavior for upgrade.
I have tried 1.9.6 and location also changed in LOCAL.

**Comment by cosminstefane** [comment]
Already did, thanks!
