### ISSUE TITLE
Unable to downgrade from 1.9.5 to 1.8.11 on Mac

### ISSUE THREAD

**Issue by fifinger** [paritytech/parity#8420]
I am trying to downgrade from 1.9.5 stable to 1.8.11 in order to get back Ledger Nano functionality which broke when upgrading. 

I have repeated this procedure several times but am unable to downgrade
- Quit parity
- open activity monitor to ensure no parity process is still running
- delete the Parity Ethereum.app from the Applications folder
- run the 1.8.11 installer (I have even once tried the 1.8.10 installer out of frustration)
- reboot

after reboot I am greeted by 
![image](https://user-images.githubusercontent.com/35303633/38869625-9cc0fa80-424b-11e8-885e-6f2bab3480e9.png)

The command line parity -v returns  version Parity/v1.9.5-stable-ff821da-20180321/x86_64-macos/rustc1.24.1

**Comment by niklasad1** [comment]
Hey,
You can force parity to run the originally downloaded version of parity by:

```$ parity --force-direct```

**Comment by fifinger** [comment]
Thanks niklasad1, that seems to work. Is there a way to make this permanent? This only works as long as I keep the terminal window open. When I start parity from GUI again I go back to 1.9.5.

**Comment by Tbaut** [comment]
@fifinger the HW wallet issue should be fixed soon (v1.11 hopefully). This shouldn't last long until you can upgrade. I'll close this issue since your problem has been worked around ;)
