### ISSUE TITLE
UI: "Connected to only one peer" banner keeps on shifting the UI

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#8422]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.0-unstable-0a170efaa-20180411/x86_64-macos/rustc1.25.0
> - **Which operating system?**: Windows / **MacOS** / Linux
> - **How installed?**: via installer / homebrew / binaries / **from source**
> - **Are you fully synchronized?**: no / **yes**
> - **Which network are you connected to?**: ethereum / ropsten / **kovan** / ...
> - **Did you try to restart the node?**: no / **yes**

For whatever reason, my node is now alternating between having 1 and 2 peers. This is not great but that´s what it is now.

The way the UI is built makes very annoying as the red banner saying "You are connected to only one peer. Your node might not be reliable. Check your network connection." is shifting the UI down and up and down and up. This makes parity totally unusable as you will likely click on the wrong UI element.

A simple workaround would be to show the banner as overlay and stop shifting the UI down.

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/58
