### ISSUE TITLE
Multisig transfer from NanoLedgerS fails

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#8423]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.0-unstable-0a170efaa-20180411/x86_64-macos/rustc1.25.0
> - **Which operating system?**: Windows / **MacOS** / Linux
> - **How installed?**: via installer / homebrew / binaries / **from source**
> - **Are you fully synchronized?**: no / **yes**
> - **Which network are you connected to?**: ethereum / ropsten / **kovan** / ...
> - **Did you try to restart the node?**: no / **yes**

From a multisig, attempting to sign a first tx over the daily limit is made impossible:
![image](https://user-images.githubusercontent.com/738724/38880139-4cbc6622-4265-11e8-8f3c-7934caee4830.png)

This fails even before any confirmation can be seen on the Ledger.

**Comment by chevdor** [comment]
I tested a regular transfer from the ledger and it works fine.

**Comment by Tbaut** [comment]
Hy @chevdor, could you please reproduce the issue with the UI console open (press ctrl+shift+i and select console) and post a screenshot here?

**Comment by chevdor** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/738724/38922737-2c458362-42f9-11e8-97e8-7f791f208be3.png)

**Comment by folsen** [comment]
Closing as UI is moving.

**Comment by chevdor** [comment]
Would not it be better to move this instead of just closing and forgetting? 
That´s quite a regression to lose Ledger Nano S support.

In general, any UI Issue should be re-opened in the UI repo before being closed, otherwise, you null all the efforts of people, like me, who took the time to:
- open an issue to report a problem
- provide requested details about the issue

We have seen unfortunately decrease in the quality of the paritytech software over time and closing issues without addressing them won´t improve the situation. While I understand the motivation to close issues, closing them without an outcome is not a good practise but I am sure you know that @folsen :)

**Comment by folsen** [comment]
@chevdor totally understand, but we will not "lose Ledger Nano S support", Ledger Nano S should still work, as you showed. A lot has changed in the past month, there is no way of knowing if this issue still persists in the Electron Wrapped UI. No one in the Parity team has been able to reproduce this issue in the past month.

I appreciate the work you've put into this report, but there is neither enough detail in this report for us to reproduce it, nor is it up to date, nor is it in the right place. Super happy to move this to an open an issue for you on the UI repo if you are still able to reproduce it with the new UI.

**Comment by chevdor** [comment]
Thanks for the clarification @folsen, from the last interactions, I understand it was more a planned todo than an issue no one could reproduce.

Isn´t there a 'cannot reproduce' or similar label for those then? This would at least provide (beside your explanation above, thanks for that) a bit of context if someone would ever run into such an issue again.

I will be more than happy to report  the issue in the UI repo if I ever run into it again, hoping of course that it won´t be the case.

**Comment by chevdor** [comment]
Also easier for your guys :) "Cannot reproduce" is never a nice outcome but sometimes that´s what it is. It is easier to put a label than to have to provide a nice explanation as you just did :) Also easier to get to the point for an 'external reader'.

**Comment by 5chdn** [comment]
> we should have an unreproducible label.

it's called "unconfirmed" to put it nicely ;-)
