### ISSUE TITLE
Build from source - error

### ISSUE THREAD

**Issue by alessalessio** [paritytech/parity#8429]
_Before filing a new issue, please **provide the following information**._

I'm running:
- **Which Parity version?**: latest stable
- **Which operating system?**:  Ubuntu 14.4
- **How installed?**: from source
- **Are you fully synchronized?**: yes
- **Which network are you connected to?**:  none. it is breaking during the compilation
- **Did you try to restart the node?**: not applicable

![image](https://user-images.githubusercontent.com/14346782/38927880-0c00ecda-42ff-11e8-9668-67da615ee5e4.png)

**Comment by rphmeier** [comment]
Please make sure you have the latest `rustc`.

**Comment by alessalessio** [comment]
I have the latest version
![image](https://user-images.githubusercontent.com/14346782/38933709-ae99eac0-4311-11e8-8211-71b09cf844f5.png)

**Comment by rphmeier** [comment]
given that the latest stable version is 1.25 (https://www.rust-lang.org/en-US/), I can say with certainty that you do not.

**Comment by alessalessio** [comment]
![image](https://user-images.githubusercontent.com/14346782/38933991-6e4a8974-4312-11e8-8f3f-9c0fdb43c0db.png)

**Comment by rphmeier** [comment]
better to install via (rustup)[https://rustup.rs/]; the `apt` repositories are unofficial and appear to be lagging behind
