### ISSUE TITLE
Can't access node over LAN via Remote Access options anymore

### ISSUE THREAD

**Issue by Emperornero** [paritytech/parity#8430]
I'm running:

> - **Parity client version**: 1.10.1
> - **Parity UI version**: v0.1.1 beta
> - **Operating system**: Windows
> - **Installed via**: installer 
> - **Fully synchronized**:  yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: no / yes

Not really an issue rather.

With browser UI access being depreciated in 1.10.1, that means the node can't be accessed over LAN via Remote Access, which means you can't run the node on one computer and the client on another which reduces security.

I'm using --force-ui to regain the functionality.

I store none of my keys on the node computer, now I have to compromise by exposing them to the node 100% of the time.

Please either return this functionality or add a remote access IP option for Parity UI, as the new implementation seems like a downgrade/mistake.

**Comment by Tbaut** [comment]
Parity UI is able to show the UI for a node launched on a remote server, as long as the Parity client is launched with the right flags (and I'm not talking about `--force-ui` here).
Parity UI is listening to the standard WS port. Please share your parity and network configuration for us to help.

**Comment by Emperornero** [comment]
parity --force-ui --mode=active --warp-barrier 5400000 --no-ancient-blocks --pruning=fast --pruning-history=8  --pruning-memory=32 --db-compaction="hdd" --ws-interface 192.168.1.7 --jsonrpc-interface 192.168.1.7 --ui-interface 192.168.1.7 --ws-hosts all --ws-origins all
pause

Is what I'm running with.

Is there a flag for Parity UI for specifying the WS host?

**Comment by Tbaut** [comment]
@Emperornero have a look at https://github.com/parity-js/shell/pull/46 regarding `--
ws-port` and `--ws-interface`.

**Comment by Emperornero** [comment]
I see now.

It might be best to add something on the page when it shows the "Browser UI Depreciated" message regarding this for Parity UI.   I would of done this myself but couldn't find documentation about it.

**Comment by Tbaut** [comment]
It should also be documented: https://github.com/paritytech/wiki/issues/81
