### ISSUE TITLE
can't download installer for Parity for Windows

### ISSUE THREAD

**Issue by dkent600** [paritytech/parity#8433]
When I go to https://www.parity.io and click on the button "Download Parity for Windows" nothing happens.  I've tried in Edge and Chrome, same behavior.

**Comment by Tbaut** [comment]
@dkent600 Thanks for telling us. We will fix it. In the meantime, you can find the windows installer here : https://github.com/paritytech/parity/releases

**Comment by Tbaut** [comment]
Should be fixed now (make sure to refresh the page with ctrl+R to clear your cache).

**Comment by dkent600** [comment]
Yup, it works, thanks.
