### ISSUE TITLE
ethcore-bytes is not used

### ISSUE THREAD

**Issue by jamesray1** [paritytech/parity#8436]
Search results show that ethcore-bytes only appears in cargo.toml files: https://github.com/paritytech/parity/search?p=1&q=ethcore-bytes&type=&utf8=%E2%9C%93.

Since it is unused, you may as well remove it from the cargo.toml files.

**Comment by niklasad1** [comment]
Hey, 

It is used as `[ dependency]` in the other crates specifies.
