### ISSUE TITLE
Pass CLI options through from ptray.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#8437]
> I'm running:
>
> - **Which Parity version?**: 1.9.6
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Running `ptray --light` does not appear to run `parity.exe` with the `--light` option.  Since there doesn't appear to be any other way to enable the light client, this means the only way to run Parity as a light client is via the command line, which has no system tray icon.

As a user, I want to be able to update my shortcut to run Parity as a light client, without having to have a console window open or jump through a large number of hoops to get the system tray icon.

**Comment by tomusdrw** [comment]
Setting `light=true` in a config file should also be possible: https://paritytech.github.io/parity-config-generator/#config=eyJfX2ludGVybmFsIjp7ImNvbmZpZ01vZGUiOiJhZHZhbmNlZCJ9LCJwYXJpdHkiOnsibGlnaHQiOnRydWV9fQ==

**Comment by MicahZoltu** [comment]
Thanks.  This may be a viable workaround, but it doesn't solve the problem of "as a non-techy user I can't _easily_ run Parity as a light client".  Even having to update the shortcut is probably too much for a novice user, but it is a good first step to updating the installer to have a shortcut for `--light`.

**Comment by folsen** [comment]
Closing this as UI (and subsequently installers of various kinds) are moving to its own repo. Ideally whether or not you want a light client should be configured when you start the UI / download the electron wrapper for the first time.
