### ISSUE TITLE
How to check transaction situation via CLI

### ISSUE THREAD

**Issue by s1241** [paritytech/parity#8440]
_Before filing a new issue, please **provide the following information**._

> I'm running: 
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows 
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I did a transaction and got transaction hash. How can I check this transaction is mined (or confirmed) via CLI (command-line interface) ? What is related command for this? Here is transaction hash that i received: 0x0e16981f972c8069398a7aa6c6402b8183063cfd157c3714582101e3ee071a30

**Comment by Tbaut** [comment]
We'd be able to advise you better if you filled the required information in your first post (parity version, your OS, the chain you're syncing).
Regarding your question, have a look at the `blockHash` and `status` fields from [eth_gettransactionreceipt](https://wiki.parity.io/JSONRPC-eth-module.html#eth_gettransactionreceipt). If your transaction was mined, the blockHash shouldn't be `null` and the status should be `0x1`.
