### ISSUE TITLE
Parity UI Warp Restore Stuck at 66.85%

### ISSUE THREAD

**Issue by mgbvox** [paritytech/parity#8459]
> I'm running:
> Parity UI v1.10.1-20180413 beta
> MacOS (High Sierra v10.13.4)
> Installed via installer
> Not synchronized - this is the problem
> - **Which network are you connected to?**: Not sure how to check, but the purpose is to work with ethereum.
> - **Did you try to restart the node?**: I've quit and restarted the app several times to no avail; the sync keeps freezing at a random point of progress.

I installed Parity UI via the installer .DMG; left it syncing on my iMac (High Sierra v10.13.4) returned to find it at 66.85% sync. Left again, came back four hours later - still at 66.85%. There appears to be only one log, made at 12:25:05 2018-04-22 (four hours ago, ish), which says: "Syncing snapshot 843/1261 #868400 26/50 peers 994 KiB chain 66 MiB db 0 bytes queue 10 KiB sync RPC: 1 conn, 1 req/s, 50 µs"

Activity monitor says parity's been running for a while and received a good deal of information, plus I've heard the fan running pretty hard all this time, so SOMETHING seems to be working... just not sure what. 
<img width="799" alt="screen shot 2018-04-22 at 4 44 01 pm" src="https://user-images.githubusercontent.com/26420601/39099668-732be13a-464c-11e8-986a-b40c9ac1a173.png">

Followup Q: will I still be able to interface with Parity UI from the Terminal? I'm trying to get started with Vyper, and it's been incredibly difficult/information-sparse, to say the least. Any pointers on how to get Vyper up and running in the simplest way possible would be amazing. My background is in biology and pythonic data science, not network/node-based stuff like this.

**Comment by Tbaut** [comment]
@mgbvox the warp sync should not hang more than a couple minutes. If it does, please [launch parity within the Terminal](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#how-to-launch-parity-using-the-command-line-on-mac-osx) to read eventual errors and post them here.

**Comment by 5chdn** [comment]
That's a UI glitch and should be tracked in the https://github.com/Parity-JS/shell/ repository: The UI does not reset the warp sync status if it fails.

The warp sync issues are listed here. https://paritytech.github.io/wiki/Known-Issues-Priorities

**Comment by mgbvox** [comment]
@Tbaut I did as you recommended, and it looks like syncing will finish! Thanks for the recommendation.
