### ISSUE TITLE
wiki website is down

### ISSUE THREAD

**Issue by lucachaco** [paritytech/parity#8465]
The wiki https://wiki.parity.io/ is not available anymore

**Comment by lucachaco** [comment]
![screenshot 16](https://user-images.githubusercontent.com/85146/39151997-13c315e8-4704-11e8-91bf-34194b644154.png)

**Comment by Tbaut** [comment]
Hmm it looks like a local issue, please visit the cached website and try again in a couple hours:
![image](https://user-images.githubusercontent.com/33178835/39153184-a96c9254-474a-11e8-8cf3-bf4698a3fe09.png)
