### ISSUE TITLE
ZeroMQ Support

### ISSUE THREAD

**Issue by stephendliang** [paritytech/parity#8466]
Does Parity (or Geth or Cpp-ethereum) support zeromq sub socket functionality the same way bitcoind lets you subscribe to new raw transactions and blocks? I've seen the JSON-RPC format, but I think that is too ineffecient

**Comment by 5chdn** [comment]
No :)

**Comment by debris** [comment]
No and we'll not implements it anytime soon. Although we'll definitely consider it in future
