### ISSUE TITLE
Unable to deploy the contract

### ISSUE THREAD

**Issue by vidhyaramani** [paritytech/parity#8469]
_

My code is running successfully no error. Got the truffle migrate results.  I have checked in migrations.js and deploy_contract.js 
deployer.deploy is same as my program name.

So,do i need to change anything?
y my program is not deploying?

**Comment by Tbaut** [comment]
Would you mind answering these questions and give us more details:

_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by vidhyaramani** [comment]
'm running:

    Which Parity version? node: version 9.9.0, npm: 5.8.0, truffle: version 4.1.6, ganache-cli(TestRPC): version 6.1.0, solidity: 0.4.18, solidity compiler(solcjs): 0.4.22
    Which operating system?: Windows 
    How installed?: via installer 
    Are you fully synchronized?:  yes
    Which network are you connected to?: ethereum /truffle/solidity
    Did you try to restart the node?: yes

**Comment by Tbaut** [comment]
You'll probably need to give us more information, step y step of what you did, error you see, or anything for us to be able to help you since we can not guess what could go wrong :)

**Comment by Tbaut** [comment]
@vidhyaramani This doesn't look like a problem on parity side. Could you please investigate with Truffle team ?
