### ISSUE TITLE
Web3 Console Not Functioning

### ISSUE THREAD

**Issue by mgbvox** [paritytech/parity#8472]
>I'm running:
>Parity UI v1.10.1-20180413 beta
>MacOS (High Sierra v10.13.4)
>Installed via installer
>
>Which network are you connected to?: Not sure how to check, but the purpose is to work with. >ethereum.
>Did you try to restart the node?: Yes.

When attempting to run the syncing check describes in the FAQs on the Parity UI Web3 Console, I got the following errors:

<img width="1198" alt="screen shot 2018-04-24 at 10 37 29 am" src="https://user-images.githubusercontent.com/26420601/39194550-fffe3206-47ab-11e8-867f-f8d342f5e61f.png">

I would assume this means I haven't installed web3 - but how can I be sure? I can't seem to find a list of prerequisite programs to have installed if you're trying to set up Parity as your default method of interacting with Ethereum (I do not run an ethereum node on my computer, as I do not have the space to do so - it's Parity or nothing).

I'm coming at this from a very basic level, so please describe this simply.

**Comment by Tbaut** [comment]
Moved to https://github.com/parity-js/shell/issues/72
