### ISSUE TITLE
Cannot connect to peers 

### ISSUE THREAD

**Issue by ChittaMadhobi** [paritytech/parity#8479]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: version Parity/v1.7.9-stable-12940e4-20171113/x86_64-windows-msvc/rustc1.20.0
> - **Which operating system?**: Windows 10  
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum / ropsten 
> - **Did you try to restart the node?**: yes (tried even rebooting the system)

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

> started with this command: parity --warp --chain ropsten --ntp-servers pool.ntp.org:123 --jsonrpc-apis "web3,eth,net,personal" --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 8098 --snapshot-peers 50 
Getting the following kind of output:
2018-04-24 21:25:04    #2491213    0/25 peers     92 KiB chain   60 MiB db  0 bytes queue   83 KiB sync  RPC:  1 conn,  0 req/s, 240 µs
2018-04-24 21:25:39    #2491213    0/25 peers     92 KiB chain   60 MiB db  0 bytes queue   83 KiB sync  RPC:  1 conn,  0 req/s, 240 µs

Running for half-hour.

It had worked before but did not start it for few months (busy working in other areas).  When starting the browser, it gives the error "You are not connected to any peers. There is most likely some network issue. Fix connectivity."

**Comment by Tbaut** [comment]
Please upgrade your parity client: https://github.com/paritytech/parity/releases
Make sure to read this about the move to 1.10: https://wiki.parity.io/Parity-Wallet
Note that `--warp` and ` --pruning fast` are now set by default. No need to specify them.
