### ISSUE TITLE
Parity ropsten chain syncing stuck at 2953152

### ISSUE THREAD

**Issue by josepajay** [paritytech/parity#8485]
> I'm running:
> - **Which Parity version?**: 1.9.7
> - **Which operating system?**:  Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ropsten
> - **Did you try to restart the node?**:  yes

I am trying to sync ropsten chain in parity with tracing on. Sync gets stuck at 2953152 for more than a day.  Please see the logs here  https://gist.github.com/josepajay/b9b8aa49a20052cbe7cf08cf7a99f0f7

**Comment by 5chdn** [comment]
Your node was only running for 26 seconds. What happens if you remove your `nodes.json` and keep it running for 1+ hours?

https://ropsten-stats.parity.io/

**Comment by josepajay** [comment]
@5chdn  As I have already mentioned I have been running parity for more than two days and its still stuck at 2953152. Even though the initial gist was the log of parity in 26 seconds, this is the behaviour it follows even when running for hours.  Please check this new gist https://gist.github.com/josepajay/eaf0f437f631460ca3cd9c939cc1736d

I tried removing nodes.json file (/chains/test/network/nodes.json and started node but still no luck

**Comment by clowestab** [comment]
Our Ropsten nodes are also getting stuck at 2953152. Been running for weeks.

**Comment by 5chdn** [comment]
And what if your remove your database and try again?

**Comment by clowestab** [comment]
I am reluctant to do that as I am running fully traced and archived nodes. Re-syncing will take a very long time. Is the implication that that is the only resolution?

**Comment by Tbaut** [comment]
@clowestab are you running with `--pruning archive`? There was a fork on Ropsten a couple weeks ago. Running with such a flag could avoid letting your node stuck.

**Comment by josepajay** [comment]
I got this sync issue resolved by running node publicly in aws.

**Comment by folsen** [comment]
Closing as it is most likely a result of the fork and resyncing would fix.
