### ISSUE TITLE
What is the best way to collect metrics at the moment?

### ISSUE THREAD

**Issue by chebykin** [paritytech/parity#8487]
* chain: private aura
* parity version: 1.9.7

I'm looking for collecting and passing the following metrics to aggregation services like [`statsd`](https://github.com/etsy/statsd) or [`telegraf`](https://github.com/influxdata/telegraf):

- tx queue size (total count each second)
- "external_tx": "Importing external transactions" event https://github.com/paritytech/parity/blob/45116099c5a0fa7e37a4cb7e70656a7f07244932/ethcore/src/miner/miner.rs#L872
- "own_tx": "Importing transaction: {:?}" event https://github.com/paritytech/parity/blob/45116099c5a0fa7e37a4cb7e70656a7f07244932/ethcore/src/miner/miner.rs#L896
- "txqueue": "Imported transaction to current: {:?}" event https://github.com/paritytech/parity/blob/45116099c5a0fa7e37a4cb7e70656a7f07244932/ethcore/src/miner/transaction_queue.rs#L1333

Both HTTP and WS interfaces are hanging when a big amount of txs is spread through the network even on non-mining and non-rpc-receiving nodes, so they are useless for collecting this data.

My only suggestion is to parse log file and pass the data to aggregation services, but maybe there is a better solution?

**Comment by tomusdrw** [comment]
@chebykin you can try out version 1.11 it has a new queue implementation that should be significantly faster than the previous one.

If that still doesn't work for you parsing logs will be the best option (with 1.11 the log structure is a bit different).
In general you are only interested in `txqueue` logs, `external_tx` and `own_tx` will be duplicated with `txqueue`, but alllow you to distinguish between your own transactions and external ones (coming from the network).

**Comment by folsen** [comment]
Closing as @tomusdrw has answered the question, please reopen if there are followup questions.
