### ISSUE TITLE
I'm trying to register a token and when I register it says "The address is not a regular token contract address"

### ISSUE THREAD

**Issue by Toadria** [paritytech/parity#8494]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/1.8.2/1.21.0/ma
> - **Which operating system?**: MacOS 
> - **How installed?**: via installer /  from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:  yes

Hello Parity Team,

I'm trying to register several tokens bought at ICOs, in many of these I continue to receive the same message:

"The address is not a regular token contract address". Further, if I try to watch those same contracts, the balance is 0 vs whatever the amount should be. Can you please help?

**Comment by Tbaut** [comment]
The `totalSupply` need to be greater than 0.

**Comment by Toadria** [comment]
When giving the address I can't see where to put the total supply?

**Comment by Tbaut** [comment]
Are you sure you're fully synced? what's the address of the token contract?

**Comment by Toadria** [comment]
I'm fully synced. The address is the following:

0x919c9b9621b3da0809431b213c431a796cb8fa1f

**Comment by Tbaut** [comment]
This is not an ERC20 token contract address, what you are looking for is most probably https://etherscan.io/token/0x57ad67acf9bf015e4820fbd66ea1a21bed8852ec BTW it's already registered on mainnet:
![image](https://user-images.githubusercontent.com/33178835/39312226-554c0336-496f-11e8-9bde-ddae52180612.png)

**Comment by Toadria** [comment]
I've just copied from etherscan, see attachded. Also, when I watch that contract the balance on parity is $0. I have done this with other tokens and it show the right balance?
<img width="1110" alt="screen shot 2018-04-26 at 15 35 08" src="https://user-images.githubusercontent.com/38754432/39312570-cb8fda0c-4967-11e8-893c-9e9c58f984bd.png">
![Uploading Screen Shot 2018-04-26 at 15.27.25.png…]()

**Comment by Toadria** [comment]
However, I have another contract with balance 20,000 in etherscan and in parity, 2. Can you help?
<img width="1402" alt="screen shot 2018-04-26 at 15 52 02" src="https://user-images.githubusercontent.com/38754432/39313619-614b3a62-496a-11e8-93f8-466e2879cec4.png">
![Uploading Screen Shot 2018-04-26 at 15.49.47.png…]()

**Comment by Toadria** [comment]
<img width="1161" alt="screen shot 2018-04-26 at 15 49 47" src="https://user-images.githubusercontent.com/38754432/39313881-fcb5349e-496a-11e8-821f-3455e846fbdf.png">
