### ISSUE TITLE
Parity UI 0.1.1.0: change data dir?

### ISSUE THREAD

**Issue by imkane** [paritytech/parity#8496]
I'm not sure why or how, but my Parity Windows app recently prompted me to install the UI app, which I download from some Github repo yesterday. I'm pretty sure the release was fairly recent, like sometime in April.

Now I cannot find where in the heck I download this "Parity UI" from. I was hoping to log an issue there or even find some documentation.

![screenshot - 4_26_2018 8_21_50 am](https://user-images.githubusercontent.com/2041683/39315375-5d7c0ee6-492b-11e8-8857-420b63c03ac9.png)

**I want to change its "data directory"**, but neither of these command-line params are working:
`--db-path=`
`--datadir=`
I can see files growing rapidly in the default `\AppData\Local\Parity\Ethereum` directory.

Any ideas?

FYI it's installed to `C:\Program Files\Parity Technologies\Parity UI\Parity UI.exe`

**Comment by Tbaut** [comment]
Parity UI is just a user interface for the Parity Ethereum client. To use another data dir, you need to launch parity (the node) with the command line and use `--datadir` flag to change your data directory. 
Here are more info about the UI move : https://paritytech.io/creating-a-lighter-experience/

**Comment by imkane** [comment]
Ok thanks, I got the new --datadir working now :)

But now after running the node from a Windows command line, the UI isn't working, I'm stuck at this page. I have to use ANOTHER command line window to generate the token, but it's never accepted. How are we supposed to run the Node + UI?

![screenshot - 4_26_2018 1_32_50 pm](https://user-images.githubusercontent.com/2041683/39330495-aeb79034-4956-11e8-94ae-c53605b14dac.png)

And then if I try to access Parity in my browser, I get this error:

![screenshot - 4_26_2018 1_32_59 pm](https://user-images.githubusercontent.com/2041683/39330509-b83fdb34-4956-11e8-9d07-165776948929.png)
