### ISSUE TITLE
Including transaction hashes into replay_block_transactions.

### ISSUE THREAD

**Issue by allquantor** [paritytech/parity#8499]
Right now, RPC call `replay_block_transactions` does not contain TxHash for trace, state diff. 

As far I can see from [here](https://github.com/paritytech/parity/blob/14361cc7b154af46ea0efca79d1c297d32181b40/ethcore/src/client/client.rs#L1587) they are available in scope.

Is there a way to get them out together with this call? 
Especially when you are interested on tracing historical blocks this information would be beneficial instead of querying `replay_transaction` for each one inside the block

**Comment by sorpaas** [comment]
I think this is duplicate of #8725
