### ISSUE TITLE
--datadir not actually working

### ISSUE THREAD

**Issue by imkane** [paritytech/parity#8500]
re: https://github.com/paritytech/parity/issues/8496

Sorry, I was mistaken. Only these folders are appearing when I change the default --datadir:

![screenshot - 4_26_2018 1_40_34 pm](https://user-images.githubusercontent.com/2041683/39330820-aa83b212-4957-11e8-9be1-955029e36c34.png)

And they only take up 249 bytes. Everything else seems to be continued to be stored in:
`\AppData\Local\Parity\Ethereum`

**Comment by Tbaut** [comment]
Using `--base-path=` should achieve what you want. Can you try?

**Comment by imkane** [comment]
That worked - thanks!
