### ISSUE TITLE
Thread '<unnamed>' panicked at 'arithmetic operation overflow'

### ISSUE THREAD

**Issue by mpolci** [paritytech/parity#8502]
I'm running:

- **Which Parity version?**: 1.9.7  (Parity/v1.9.7-stable-7919629f3-20180423/x86_64-linux-gnu/rustc1.25.0)
- **Which operating system?**: Linux Debian 9 
- **How installed?**: binaries (official .deb package)
- **Are you fully synchronized?**: yes
- **Which network are you connected to?**: ethereum
- **Did you try to restart the node?**: yes

The parity daemon crash with the following error:

     Thread '<unnamed>' panicked at 'arithmetic operation overflow', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bigint-4.2.0/src/uint.rs:1227

After parity restarted it runs for a minute then hangs again. The problem seems happen only with heavy load.

**Comment by mpolci** [comment]
I discovered that the error happened every time after a call to web3.eth.sendRawTransaction() (web3 connected via IPC)

**Comment by Tbaut** [comment]
Would you mind providing the signed transaction that causes this issue?
