### ISSUE TITLE
IO Worker panic

### ISSUE THREAD

**Issue by Tasselhoff** [paritytech/parity#8507]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.7-stable-7919629-20180423/x86_64-linux-gnu/rustc1.25.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
During snapshot, using command as follows:
./par.sh: line 2: 11217 Aborted                 (core dumped) parity --cache-size 8192 --db-compaction ssd --mode active --warp --author xxx --stratum --stratum-port=9009 --no-ancient-blocks --max-peers=5000 --min-peers=2000 --jsonrpc-threads=8 --jsonrpc-server-threads=3 --tx-queue-mem-limit=0 --can-restart

2018-04-27 16:50:55  Syncing snapshot 582/1294  #5371148   100/2000 peers   34 MiB chain 88 MiB db 0 bytes queue 39 MiB sync  RPC:  1 conn,  1 req/s, 154802 µs

====================

stack backtrace:
   0:     0x555d4b904f2c - <no info>

Thread 'IO Worker #3' panicked at 'index 555 out of range for slice of length 128', libcore/slice/mod.rs:785

This is a bug. Please report it at:...

**Comment by Tbaut** [comment]
Duplicates https://github.com/paritytech/parity/issues/7536
