### ISSUE TITLE
Connecting to dockerized instance

### ISSUE THREAD

**Issue by tms1337** [paritytech/parity#8508]
Hey guys and girls,
Could somebody possibly help me, I am not providing usual info thats required since I am running official dockerized version. I am using MacOS High Sierra.

I am running parity with

`docker run -d -p 8545:8545 parity/parity --jsonrpc-cors all --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 512`

, but cant seem to connect from localhost by running `geth attach` for example or using `web3` from node.

When using web3, it seems like I connect, but I get undefined values for `web3.eth.syncing
` for instance.

I am connecting with this snippet:
```
var Web3 = require('../index.js');
var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));
```

**Comment by Tbaut** [comment]
The default port for Jsonrpc API is 8546. Please make sure to forward this port and to connect to it with setProvider. Some more info on the best way to access to a parity instance in a docker: https://wiki.parity.io/Docker.html
