### ISSUE TITLE
Amount of Axpire Token in Parity different from amount in Etherscan

### ISSUE THREAD

**Issue by Toadria** [paritytech/parity#8510]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/1.8.2/1.21.0/ma
> - **Which operating system?**: MacOS
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Hi There,

I've recently added several tokens in my parity wallet. One of these Axpire, shows in parity a different amount. In Etherscan it clearly shows I have 20,000, whilst in Parity it shows only 0.0002! Can you please advise?
<img width="1188" alt="screen shot 2018-04-28 at 21 47 54" src="https://user-images.githubusercontent.com/38754432/39400759-a8c726ce-4b2e-11e8-9aa8-09bb2a59df6b.png">
<img width="1297" alt="screen shot 2018-04-28 at 21 47 42" src="https://user-images.githubusercontent.com/38754432/39400760-a8ebc826-4b2e-11e8-8c1e-ede16a65fa33.png">

**Comment by Toadria** [comment]
Also, I've just noticed that in the total supply it shows 35 million whilst Axpire has 350 million. Can someone help to rectify?

**Comment by Tbaut** [comment]
Your token has 8 decimals. So 20,000x10^-8 or 0.0002 is the same. The way Etherscan shows the tokens is misleading IMO.
