### ISSUE TITLE
Does Parity support the PIRL chain?

### ISSUE THREAD

**Issue by saltyminer** [paritytech/parity#8512]
> I'm running:
>
> - **Which Parity version?**: Parity 1.9.7-stable
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: PIRL (well, I want to be)
> - **Did you try to restart the node?**: n/a

After reviewing the https://wiki.parity.io/Chain-specification page and doing some digging around it looks like Parity does not support PIRL.  If it is possible to use PIRL where can I find more info on how to set the json config?  If it is not supported, is this on the roadmap?  I looked at the projects and did some searching, but I did not find any relevant info.

**Comment by Tbaut** [comment]
PIRL isn't supported out of the box but you can still use parity to sync with it if it is based on ethereum. Have a look at our [Wiki about chain specifications](https://wiki.parity.io/Chain-specification) to learn how to build it.
