### ISSUE TITLE
Thread 'IO Worker #1' panicked at 'arithmetic operation overflow' if RewardContract is activated

### ISSUE THREAD

**Issue by ahiatsevich** [paritytech/parity#8516]
_Before filing a new issue, please **provide the following information**._

I'm running:

- **Which Parity version?**: v1.12.0-unstable-44c68221a-2018042
- **Which operating system?**: MacOS
- **How installed?**: from source, `master` branch
- **Are you fully synchronized?**: yes
- **Which network are you connected to?**: private local network: bootnode + 3 parity nodes
- **Did you try to restart the node?**: yes
- Consensus: AuthorityRound(Aura) + RewardContract

When I'm trying to execute `any` tx, nodes always crash with 
```
2018-04-29 19:50:10  Imported #4 0x7e42…f078 (0 txs, 0.00 Mgas, 2 ms, 0.56 KiB)
2018-04-29 19:50:20  Imported #5 0x3271…d879 (0 txs, 0.00 Mgas, 1 ms, 0.56 KiB)
2018-04-29 19:50:27  Fallback to `BlockId::Latest`

====================

stack backtrace:
   0:        0x1066ce244 - backtrace::backtrace::trace::h9ec331e2bbe150c3
   1:        0x1066c946c - backtrace::capture::Backtrace::new_unresolved::h08ad000a3750ef95
   2:        0x1066c93be - backtrace::capture::Backtrace::new::h7ed8d26429ebf908

Thread 'IO Worker #1' panicked at 'arithmetic operation overflow', /Users/ahiatsevich/.cargo/registry/src/github.com-1ecc6299db9ec823/ethereum-types-0.3.1/src/uint.rs:32

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

But if `RewardContract` is disabled, everything works fine:
```
0  Imported #7 0x6b60…3444 (0 txs, 0.00 Mgas, 3 ms, 0.56 KiB)
2018-04-29 19:36:36  Fallback to `BlockId::Latest`
2018-04-29 19:36:40  Transaction mined (hash 0x7ac7e631cb35ded9b17ab48e0e85018d3e7326c871c488778ad09471aa544187)
2018-04-29 19:36:40  Imported #8 0xf727…df60 (1 txs, 0.28 Mgas, 6 ms, 1.49 KiB)
2018-04-29 19:36:50  Imported #9 0x4cb5…5f13 (0 txs, 0.00 Mgas, 1 ms, 0.56 KiB)
2018-04-29 19:37:00  Imported #10 0xf95b…8aee (0 txs, 0.00 Mgas, 1 ms, 0.56 KiB)
```

**steps to reproduce**:
- build parity from source, `master` branch
- start bootnode and 3 parity nodes
- wait for 1st (2nd, 3rd, 11th, does not matter) mined block
- execute any tx via `truffle console`, for example `truffle(local)> Migrations.new()`
- as a result, all parity nodes are down with `arithmetic operation overflow`.

Genesis file: [side-chain-demo.json.txt](https://github.com/paritytech/parity/files/1959953/side-chain-demo.json.txt)
Node config: 
[node1.toml.txt](https://github.com/paritytech/parity/files/1959959/node1.toml.txt)

**Comment by ascjones** [comment]
Is this fixed by https://github.com/paritytech/parity/commit/af90fbfb3344fdc2447d97d4c48dcdfd69899a4f

**Comment by ahiatsevich** [comment]
Yes, this is. Thanks. Verified `Parity/v1.12.0-unstable-80528c534-20180524/x86_64-macos/rustc1.25.0`
