### ISSUE TITLE
Remove potentially redundant log column for light client

### ISSUE THREAD

**Issue by fulldecent** [paritytech/parity#8519]
This column is duplicated with this column. The end result is wasted screen space. And in my case unnecessary.

![screen shot 2018-04-30 at 5 37 12 pm](https://user-images.githubusercontent.com/382183/39436042-34430ba4-4c9d-11e8-96ca-1170e739c290.png)

Remove the latter to save space.

**Comment by tomusdrw** [comment]
With full node, the second column shows the highest block number seen in the network.

You seem to be running light node, perhaps it indeed makes sense to remove that for light client.
