### ISSUE TITLE
failed to join thread: Resource deadlock avoided (os error 35)', libstd/sys/unix/thread.rs:178

### ISSUE THREAD

**Issue by x3medima17** [paritytech/parity#8523]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:  Parity/v1.10.2-beta-f4ae813-20180423/x86_64-linux-gnu/rustc1.25.0
> - **Which operating system?**:  Linux
> - **How installed?**: Docker (parity/parity)
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**:  yes

I am trying to run a private Ethereum network using docker containers.
You can find all files that I am using here: https://gist.github.com/x3medima17/102c69b83ce4e931c824463d89abc087

When I run `deploy.sh` sometimes I get this error:
```
====================

stack backtrace:
   0:     0x5604a1fc0a5c - <no info>
   1:     0x5604a1fbf312 - <no info>
   2:     0x5604a161482b - <no info>

Thread '<unnamed>' panicked at 'failed to join thread: Resource deadlock avoided (os error 35)', libstd/sys/unix/thread.rs:178

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

/eth/entrypoint.sh: line 4:     7 Aborted                 /parity/parity account import --chain /eth/genesis.json --keys-path /tmp/parity${NODE}/keys /eth/keys


====================

stack backtrace:
   0:     0x55db8789ca5c - <no info>
   1:     0x55db8789b312 - <no info>
   2:     0x55db86ef082b - <no info>

Thread '<unnamed>' panicked at 'failed to join thread: Resource deadlock avoided (os error 35)', libstd/sys/unix/thread.rs:178

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```
As I was asked, I report it here

**Comment by Tbaut** [comment]
Thanks for reporting. This issue is a duplicate from https://github.com/paritytech/parity/issues/8088 Please follow it.
