### ISSUE TITLE
Question: Reward call

### ISSUE THREAD

**Issue by rstormsf** [paritytech/parity#8526]
https://github.com/paritytech/parity/blob/d1f5284fe665665a98f36ad73606c4a72c25f3d3/rpc/src/v1/types/trace.rs#L367-L378

what is Reward call ?

I assume it's used when `suicide` was executed  to refund eth to sender? 
https://kovan.etherscan.io/vmtrace?txhash=0x5a645a1e1fa892f90b3bcce48a270855dfc19cda46e3b3f81948463eae04d936&type=parity

example of suicide with `refundAddress`

**Comment by Tbaut** [comment]
I believe these are trace for uncle and mining rewards, I don't think it's visible anywhere yet as suggested in https://github.com/paritytech/parity/issues/4858
