### ISSUE TITLE
I want only my application node can access my parity node by RPC

### ISSUE THREAD

**Issue by past2017** [paritytech/parity#8533]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.5-stable-ff821da-20180321
> - **Which operating system?**:   Linux
> - **How installed?**:  binaries
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum  
> - **Did you try to restart the node?**:  yes

My application server and my parity node are all deployed on public network, and I want only my application server can access my parity node by RPC
Is there some way to realize it? By now i do it by iptables
thank you very much

**Comment by Tbaut** [comment]
To restrict access to a specific domain, you can use the flags : 
```
--jsonrpc-cors=[URL]
        Specify CORS header for JSON-RPC API responses. Special options: "all",
        "none". (default: none)
```

for a specific IP : 
```
--jsonrpc-interface=[IP]
        Specify the hostname portion of the JSONRPC API server, IP should be an
        interface's IP address, or all (all interfaces) or local. (default: local)
```

However, it is asvised to not open the apis and use a ssh tunnel instead as described here: https://wiki.parity.io/Wallet-Remote-Access.html

**Comment by Tbaut** [comment]
cc @ddorgan  if you have anything to add.

**Comment by ddorgan** [comment]
@past2017 I think the instructions that @Tbaut sent on are very accurate for your case. 

If you're doing something complex could you describe how the  infrastructure is setup please. E.g. how many VM's, what networks they're connected to etc...

In the easiest case your application would be on the same system as parity and you could just allow jsonrpc or websocket access to 127.0.01, if they're on a different machine then jsonrpc/websocket access should be blocked from the internet and --jsonrpc-cors or -ws-origin can be used to further tighten security.

**Comment by past2017** [comment]
@ddorgan sorry, i did not describe this issue clearly
for example, i have 2 application server named A and B and a parity node named C, they are all VMs
A have local network IP 192.168.0.11
B have local netowrk IP 192.168.0.12
C have local network IP 192.168.0.13
and maybe the local network also have some other vm named D who have ip like 192.168.0.14, i cannot control it
**I want to only A and B can access C by RPC and no any other vms can access C by RPC.**

In C I will start parity as --jsonrpc-interface=192.168.0.13
So A and B can access C by RPC but I am afraid the D also can access it by RPC that it is not expected

If there is a way to achieve it, sorry i do not know how to use --jsonrpc-cors or -ws-origin and if these two arguments can do it?

Thank you so much

**Comment by ddorgan** [comment]
@past2017 I think there are two possible solutions here....

1. Use --jsonrpc-cors to specify to domain name which it will accept connections from. This for example could be appserver.domain.com ... and then have the IP's 192.168.0.11 and 192.168.0.12 resolve to this domain name. 

or

2. So with this version it wouldn't be as secure on the parity layer but would make up for this in ip filtering. Use this option with caution. Basically you could allow 192.168.0.13 accept connections from anybody on 8545 but then use iptables to restrict access to 192.168.0.11/12 only. 

Hope this helps.

**Comment by past2017** [comment]
@ddorgan got it, thank you very much

**Comment by past2017** [comment]
@ddorgan sorry to disturb you again, there is another issue i want to get your help
I have a ETH pool with 1.6 TH hash and use parity as mine wallet
But it is always high uncle rate with about 30% and 0.5% orphan block rate
I run my parity as 
**parity --no-ui --no-serve-light --no-ws --max-peers 100 --reserved-peers=static_node_list/static-nodes-eth-parity.json --port 30302 --jsonrpc-port 8588 --no-dapps --log-file ./parity.log --jsonrpc-hosts all --pruning fast --jsonrpc-interface all --author 0xb75D1e62b10E4ba91315C4aA3fACc536f8A9 --remove-solved --cache-size-db 2048 --relay-set strict --force-sealing --tx-queue-size 28 --db-path /home/eth/ethDatabase/db**
And I deploy serveral sync wallet node in different location  like Japan,America,Europe
My vm have 8 CPU/32 G ram/20Mbps bandwidth and it looks not a resource bottleneck 
I have no idea with it, please help me, thank you very much

**Comment by Tbaut** [comment]
@past2017 this issue is close and your question isn't related. Please post a new issue.

**Comment by past2017** [comment]
@ddorgan @Tbaut I  have filed another issue #8593 , please help me,thanks very much
