### ISSUE TITLE
Killing via Ctrl+C hangs on latest master

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity#8540]
Happens randomly.

From @Tbaut 
> just happened on a synced node (wasn't synced before) with Parity/v1.12.0-unstable-b100945-20180502

**Comment by trappist** [comment]
Happens reliably here. It prints `Finishing work, please wait...` and never exits, I have to kill -9.

**Comment by dvdplm** [comment]
Happens sporadically here (~1/day) using a variety of flags.

**Comment by niklasad1** [comment]
@tomusdrw can we close this now when #8751 is merged?

**Comment by tomusdrw** [comment]
Yeah, let's re-open if the issue persists.
