### ISSUE TITLE
No config file entry for --no-ancient-blocks switch

### ISSUE THREAD

**Issue by MarkusTeufelberger** [paritytech/parity#8549]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.2
> - **Which operating system?**: Linux
> - **How installed?**: Docker
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: none
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I would expect to have a `ancient_nodes = true` setting or similar in the default config file.

From what I can find, this setting is only available as a command line switch. This clashes with the  "Each CLI option maps to a setting in the TOML file [...]" statement at https://wiki.parity.io/Configuring-Parity

**Comment by Tbaut** [comment]
I guess you are right, can't find it [in the code](https://github.com/paritytech/parity/blob/1cd93e4cebeeb7b14e02b4e82bc0d4f73ed713d9/parity/cli/mod.rs#L425)
PR welcome :)

**Comment by MarkusTeufelberger** [comment]
Sure, but apparently there's a bot that checks some kind of CLA? I can't even see the CLA without logging in on your website and it is not documented in any obvious place (README or CONTRIBUTING file) what this CLA is supposed to be or entail.

Is it really that "welcome"? :-/

**Comment by tomusdrw** [comment]
The entry is not there for security reasons, running without `ancient_blocks` is not something that you should do. IMHO it's better not to make it easier than it is right now.

Please consider a light client if you can't store the entire blockchain.

**Comment by MarkusTeufelberger** [comment]
In that case please document this and/or move respective CLI options that can't be set in the config file to a dedicated section in the `--help` overview.

**Comment by MarkusTeufelberger** [comment]
That's one way to do it...

Thanks.
