### ISSUE TITLE
osx "Start at Logon" unable to disable

### ISSUE THREAD

**Issue by p-s-dev** [paritytech/parity#8551]
Version: Parity/v1.10.2-beta-f4ae813-20180423/x86_64-macos/rustc1.25.0
OS: macOS
installed: PKG release
fully synchronized?: no
Did you try to restart the node?: yes

Once "Start at Logon" is turned on, it can not be toggled-off.

expected:
 - The "Start at Logon" open can be enabled and disabled

**Comment by Tbaut** [comment]
Should be logged in the UI repo instead: https://github.com/parity-js/shell/issues/88
