### ISSUE TITLE
An question about Snapshot & AccountDB.

### ISSUE THREAD

**Issue by EighteenZi** [paritytech/parity#8554]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.2
> - **Which operating system?**:  Linux
> - **How installed?**:  from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

When creating AccountDB,  'account.**address_hash**(address)' is always used in Mangled mode, so the AccountDB store the hash of account address.

When taking Snapshot in 'chunk_state', **account_key** is got from `account_trie.iter()`, and is my option, it is the account's address.
And then constructs the AccountDB by  `AccountDB::from_hash(db, account_key_hash)`, 
**account_key_hash = H256::from_slice(&account_key),** 
account_key_hash is not keccak(account_key).

I am confused. What is the real value of `account_key` from `account_trie.iter()`, address or address_hash?

Thanks a lot.

**Comment by rphmeier** [comment]
duplicate

**Comment by Tbaut** [comment]
https://github.com/paritytech/parity/issues/8566
