### ISSUE TITLE
failed to run custom build command for `parity-ui-old-dev v1.9.0

### ISSUE THREAD

**Issue by yuelipeng** [paritytech/parity#8559]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.1
> - **Which operating system?**: MacOS
> - **How installed?**:  from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

cargo build --no-default-features --features ui

Compiling ethcore v1.9.0 (file:///Users/yuelipeng/parity/ethcore)
error: failed to run custom build command for `parity-ui-old-dev v1.9.0 (file:///Users/yuelipeng/parity/js-old)`
process didn't exit successfully: `/Users/yuelipeng/parity/target/debug/build/parity-ui-old-dev-3dba748b71bcce5e/build-script-build` (exit code: 101)
--- stderr
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= integrity checksum failed when using sha1: wanted sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM= but got sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==. (11423 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/regenerate/-/regenerate-1.3.3.tgz failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yuelipeng/.npm/_logs/2018-05-07T14_59_19_099Z-debug.log
thread 'main' panicked at 'There was an error installing dependencies.', /Users/yuelipeng/parity/target/debug/build/parity-dapps-glue-e5a301c9d6ed5c8c/out/lib.rs:476:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by Tbaut** [comment]
The UI was removed recently and will not be supported anymore.
