### ISSUE TITLE
Pirl support using Parity?

### ISSUE THREAD

**Issue by Trystaero** [paritytech/parity#8561]
Which Parity version?: Parity 1.9.7-stable
Which operating system?: Windows
How installed?: via installer
Are you fully synchronized?: no
Which network are you connected to?: PIRL (Would like to anyway)
Did you try to restart the node?: n/a

After reviewing the https://wiki.parity.io/Chain-specification page and Google'ing a bit, it looks like Parity does not support PIRL.  I would like to add PIRL but i'm not able to get the json config to work with current parameters. Is there a support page I missed in my searching endeavor? Has PIRL been evaluated for parity support in the future?

Thank you for your time!

**Comment by Tbaut** [comment]
Thanks for logging your issue.
>Has PIRL been evaluated for parity support in the future?

Parity remains quite open in terms of chain support but PIRL hasn't been considered as far as I could see. Nevertheless, we welcome PR and getting a working genesis file is a must for the team to add it to default chains.
>Is there a support page I missed in my searching endeavour? 

The specifications you linked is the most up to date doc we have. I recommend having a look at other [ethereum based chains](https://github.com/paritytech/parity/tree/master/ethcore/res/ethereum) also.



I'll close the issue but feel free to ask you questions here, we can reopen if needed.

**Comment by saltyminer** [comment]
Hi @Tbaut you can find the PIRL genesis file here on their [github](https://github.com/pirl/pirl/blob/master/genesis.json).  Let me know if you need anything else to add PIRL support.

**Comment by Tbaut** [comment]
As I said above, please submit a PR.
