### ISSUE TITLE
JSON RPC service seems to die when under load and not recover

### ISSUE THREAD

**Issue by zabirauf** [paritytech/parity#8562]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.2
> - **Which operating system?**: Linux (Ubuntu 16.04)
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I have a script running that is making a lot (in order of 1000s) of RPC calls to localhost parity node.

**Expected behavior**
I expect the Parity node to be reliable and have it return response or wait till it can i.e. queue the request

**Actual behavior**
The JSON RPC service seems to die and does not recover unless parity is restarted. Event trying to attach geth `geth attach rpc:http://127.0.0.1:8545` results in the following error

```
Fatal: Failed to start the JavaScript console: api modules: Post http://127.0.0.1:8545: dial tcp 127.0.0.1:8545: connect: connection refused
```

I have setup parity as systemd service. When I see the logs, I see following error

```
UTC Incoming streams error, closing sever: Os { code: 24, kind: Other, message: "Too many open files" }
```

Turning the script off and restarting parity solves the issue, but it repros as soon as the script starts sending bunch of requests.

**Comment by tomusdrw** [comment]
This is a limitation of your system. You can modify number of open files using `ulimit -n 8000`
