### ISSUE TITLE
Does the 'SnapShot' really works??

### ISSUE THREAD

**Issue by EighteenZi** [paritytech/parity#8566]
In my option, the Account Trie stores the Address-Account pair, and the AccountDB uses the hash of address to create the Mangled key.
`trie.insert(address, &account.rlp())?;`  state/mod.rs: 798L
`let accountdb = self.factories.accountdb.readonly(self.db.as_hashdb(), account.address_hash(a));` state/mod.rs: 964L

But when i read the code of snapshot, i became confused.
Looking the code in 'chunk_state',
`
let account_trie = TrieDB::new(db, &root)?;
for item in account_trie.iter()? {
    let (account_key, account_data) = item?;
    let account = ::rlp::decode(&*account_data);
    let account_key_hash = H256::from_slice(&account_key);
    let account_db = AccountDB::from_hash(db, account_key_hash);
}
`
account_key is type of Address, and account_key_hash is type of H256, not the hash of Address.

Please help me on this confusion.
Thanks a lot.

**Comment by rphmeier** [comment]
well, yes, it clearly works. note that the ethereum state trie uses address hashes as its key.

**Comment by EighteenZi** [comment]
Oh i see, i read the code of 'TrieDB', and ethereum uses the 'SecTrieDB'.
Sorry for the trouble.
Thanks.
