### ISSUE TITLE
Improve docs on registrar + fee whitelist (service transactions) smart contracts set up

### ISSUE THREAD

**Issue by lopezm94** [paritytech/parity#8567]
Hello, I'm trying to set up a white listing contract for users to have 0 gas transactions as depicted [here](https://wiki.parity.io/Permissioning#gas-price). For the first step, which is to have a registrar contract on the chain, I've got some doubts about the set up:

- Is registrar specification valid for Aura consensus? (In the [docs](https://wiki.parity.io/Proof-of-Work-Chains.html) the registrar param appears inside ethash parameters, not engine)
- Is the [example](https://github.com/paritytech/contracts/blob/master/Registry.sol) API contract provided the real one? (The [ABI specified in the parity client](https://github.com/paritytech/parity/blob/master/registrar/res/registrar.json) dictates otherwise). It might be good to link [here](https://github.com/paritytech/contracts/blob/master/SimpleRegistry.sol) from the docs instead.
- Another thing which is confusing about the registrar contract is the following: `registering address of this contract in registry with ‘service_transaction_checker’ name` however the [reserve](https://github.com/paritytech/contracts/blob/master/SimpleRegistry.sol#L78) function in `SimpleRegistry.sol` has only one param, the closest function would be [proposeReverse](https://github.com/paritytech/contracts/blob/master/SimpleRegistry.sol#L121) function which has a `name` and `address` param.

I will gladly make a PR to the docs after I can get this understood and working in a private POA chain.

Thanks in advance

**Comment by lopezm94** [comment]
Could you guys give me a hint on how to proceed with the registrar set up? I don't know how much priority this issue has but I would like to solve it soon if possible.

**Comment by lopezm94** [comment]
Ok, I think I found the part of the source code I was looking for:

```rust
impl RegistryInfo for Client {
	fn registry_address(&self, name: String, block: BlockId) -> Option<Address> {
		let address = self.registrar_address?;

		self.registrar.functions()
			.get_address()
			.call(keccak(name.as_bytes()), "A", &|data| self.call_contract(block, address, data))
			.ok()
			.and_then(|a| if a.is_zero() {
				None
			} else {
				Some(a)
			})
	}
}
```

The address key is harcoded as `"A"` when calling the contract function.

**Comment by Tbaut** [comment]
Thanks for the feedback @lopezm94 .  If you have some spare time and would like to share the acquired knowledge, feel free to submit a PR in our wiki https://github.com/paritytech/wiki to document things better.

**Comment by Tbaut** [comment]
BTW you can use the Registry Dapp in Parity UI, this might help.

**Comment by maxidev** [comment]
+1 had the exact same problem when dealing with service transactions. Will be useful at least an explanation here so we can update the docs.
Regards.
