### ISSUE TITLE
How to reduce uncle/orphan block rate of my eth pool

### ISSUE THREAD

**Issue by past2017** [paritytech/parity#8593]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.9.5-stable
> - **Which operating system?**:  Linux
> - **How installed?**: via  binaries  
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**:   yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**environment information:**
I have a eth pool with 1.6 TH , there are 1 miner wallet node and 10 sync wallet node
The miner wallet node is located in China
The 10 sync wallet node is located in China,Japan,America,Hongkong,Europe
All wallet node is aliyun VM and have 8core/32G RAM/20Mbps bandwidth

**actual**
The uncle block rate is 30% or more and orphan is 0.5%

**exptected behavior**
The uncle block rate is 20% or more and orphan is 0.2%

**steps to reproduce**
Run parity on all wallet node as below
parity --no-ui --no-serve-light --no-ws --max-peers 100 --reserved-peers=static_node_list/static-nodes-eth-parity.json --port 30302 --jsonrpc-port xxxx --no-dapps --log-file ./parity.log --jsonrpc-hosts all --pruning fast --jsonrpc-interface all --author 0xD1e62b10E4ba91315C4aA3fACc536f8 --remove-solved --cache-size-db 2048 --relay-set strict --force-sealing --tx-queue-size 188 --db-path /home/eth/ethDatabase/db

Please help me to reduce the uncle/orphan rate, thank you very much

**Comment by RSAManagement** [comment]
HDD or SSD?

**Comment by past2017** [comment]
@RSAManagement SSD Coud Disk
