### ISSUE TITLE
Can someone give me an idea of how long it takes to sync a full archive node?

### ISSUE THREAD

**Issue by antikantian** [paritytech/parity#8597]
> - **Which Parity version?**: 1.10.2-beta
> - **Which operating system?**: Ubuntu 16.04.4
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

We need an archive node up and running to continue some dev work, and I just need to get an estimate of how long this process is going to take, or at least *should* be taking, so that we can better plan our work priorities for this month.

We started this sync on a fresh instance, and we're currently at 8 days, 6 hours, and 38 minutes, and on block #2434031.  I expect some delay on this block range, but I have no idea what kind of timeframe is reasonable, if there is going to be a substantial speedup after block ~2.7 mil, or if this sync rate is way out of line and we need to drop down a version, etc.

Any hint as to what the sync times are for an archive node would be much appreciated.  Also, an idea of the current archive chain size would be great.  We've provisioned 1TB at present.

**Comment by Tbaut** [comment]
>if there is going to be a substantial speedup after block ~2.7 mil

There will be definitely a substantial speed up.

>We've provisioned 1TB at present.

This might not be enough anymore. The space requirement for a `tracing+fat db` was over 1TB a month ago, I expect archive only node to be over 1TB now as well.

>Any hint as to what the sync times are for an archive node

This very much depends on your configuration. I personally can't give you any better info than a couple weeks. Maybe @5chdn can give you a hint as we've been synching a trace+archive node recently.

**Comment by antikantian** [comment]
@Tbaut Ok, thanks.  That time reference was pretty much what I was looking for.  I just wanted to make sure our sync wasn't taking drastically longer than normal.
