### ISSUE TITLE
Parity UI old and archived?

### ISSUE THREAD

**Issue by devinrsmith** [paritytech/parity#8599]
The readme says that Parity UI will now be a separate app, but the repository seems to indicate that it's old and archived, https://github.com/paritytech/parity-ui. I'm a bit confused. 

Also, the "follow these steps" link to keep using the UI in the browser is 404ing: https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.md#the-parity-ui-application-isnt-working-the-way-i-want

**Comment by Tbaut** [comment]
Thanks for the heads-up. The repo for the UI is: https://github.com/parity-js/shell/ and the link to the wiki: https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization#the-parity-ui-application-isnt-working-the-way-i-want I'll correct it
