### ISSUE TITLE
Registering KIN ERC-20 token with parity 

### ISSUE THREAD

**Issue by rsl15** [paritytech/parity#8608]
I'm running:

version: v1.11.0-20180508 beta
operating system: MacOS 10.12.6
How installed: via installer 
Are you fully synchronized: no 
Which network are you connected to: ethereum 
Did you try to restart the node: no 
Connected Peers: 26/50
Time synchronized: 1117ms

I sent my KIN from Yobit exchange to a local parity wallet expecting it to appear since it's a  ERC20 token, and come to find out KIN is not listed in the Parity token registry so it doesn't show up in parity wallets.
Any advice on how to fix it? Parity is currently syncing and half way trough. Although Yobit keeps showing "In Process" it would be great if anyone please guide me through the process of registering the token with parity?

Parity ETH Address: [https://etherscan.io/address/0x0067C351cA049772bA8e20a5b453BBB03bC125Da](https://etherscan.io/address/0x0067C351cA049772bA8e20a5b453BBB03bC125Da)

KIN token data
[https://etherscan.io/token/0x818fc6c2ec5986bc6e2cbf00939d90556ab12ce5](https://etherscan.io/token/0x818fc6c2ec5986bc6e2cbf00939d90556ab12ce5)

**Comment by Tbaut** [comment]
KIN is present in the Mainnet Token registry. If your node is fully synced, you should see your tokens. 
![image](https://user-images.githubusercontent.com/33178835/39991590-5768792e-5770-11e8-936c-3623e293e246.png)
