### ISSUE TITLE
How to keep state trie data from a specified block

### ISSUE THREAD

**Issue by catalsdevelop** [paritytech/parity#8609]
> I'm running:
>
> - **Which Parity version?**: 1.9.5
> - **Which operating system?**: CentOS 7
> - **How installed?**: via docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I am using a full sync mode right now, it's very slow. 11 days just  to 4.7M, while disk cost reached 480G. 
I just want to retrieve transaction receipt data after block 5M. Is there any way that sync faster, save disk storage and keep state data from a specified block number?  After dig wiki, I got `--pruning-history`, but this args make state in memory and it is the `latest` number of blocks state data to keep when pruning, any solutions?

**Comment by Tbaut** [comment]
You mention "state trie" in your title and "transaction receipt" in your message. The latter does not need `--pruning-history` or `--pruning archive`. Any node launched with the default flags will be able to query transaction receipts. 
>while disk cost reached 480G

Please describe the flags used. A full node should be able to sync the top of the chain within less than a day (using warp sync and [warp-barrier](https://wiki.parity.io/FAQ-Basic-Operations,-Configuration,-and-Synchronization.html#why-is-warp-synchronization-so-fast)). The full sync (verifying all the blocks) is much longer, but still uses ~70GB.

**Comment by catalsdevelop** [comment]
sorry for my bad english writing, @Tbaut . Maybe I am misunderstanding the `state tire` and `transaction state`. What I need is rpc interfaces such as *eth_getBalance* and *balance_of_contract* at a certain block with web3.js. When use default warp sync mode, I got the follows error in web3.js
```
This request is not supported because your node is running with state pruning. Run with --pruning=archive., Error: Returnederror: This request is not supported because your node is running with state pruning. Run with --pruning=archive
```
Switch to a full sync mode node, everything was fine.

warp sync flags
```
--chain mainnet
--peers 25
--snapshot-peers 20
--db-compaction ssd
--cache 4096
--warp-barrier 5300000
--rpcaddr 0.0.0.0 --rpccorsdomain "*"
--ws-origins all --ws-interface 0.0.0.0
```

full sync flags, now chain data reach to 550G, block number just to 4.84M
```
--chain mainnet
--no-warp
--pruning archive
--tracing on
--fat-db on
--peers 25
--snapshot-peers 25
--db-compaction ssd
--cache 4096
--rpcaddr 0.0.0.0 --rpccorsdomain "*"
--ws-origins all --ws-interface 0.0.0.0
```

**Comment by catalsdevelop** [comment]
thx, @Tbaut. Seems like only use my full sync flags' solution
