### ISSUE TITLE
Pruning question

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#8613]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.7
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

Hello, I'm trying to access a contract I deployed last week. With parity's default pruning behavior, if I begin syncing now, will this be a problem? When I attempt to read from my contract with web3: https://github.com/ethereum/web3.js/issues/1629

It isn't clear to me if parity syncs all smart contract data.

**Comment by Tbaut** [comment]
The pruning affects the state tree, it does not interfere with contracts. Once the blockchain is fully synced (and particularly the block containing your contract) it will be accessible and you will be able to interract with it.

**Comment by quantumproducer** [comment]
Thank you. So State Tree is just records of transactions?

**Comment by Tbaut** [comment]
No, the state tree contains the state (the balance) of all account of the Ethereum blockchain for a given block. [Here is an article that gives a better overview](https://medium.com/cybermiles/diving-into-ethereums-world-state-c893102030ed)
