### ISSUE TITLE
Add support for HTTPS clients

### ISSUE THREAD

**Issue by Pzixel** [paritytech/parity#8617]
> I'm running:
>
> - **Which Parity version?**: 1.9.7
> - **Which operating system?**: Linux
> - **How installed?**: Docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I'm trying to deploy my sample application on github pages. The problem is that github pages required `https` and I cannot perform http requests which seems to be working on my local machine.

When I'm trying to access network via https, I get an error:

> geth attach  https://localhost:8545/
> Fatal: Failed to start the JavaScript console: api modules: Post https://localhost:8545/: http: server gave HTTP response to HTTPS client

It's kinda blocker to me because I cannot use "GitHub Pages" to host my sample app because all browsers refuses to perform HTTP requests from HTTPS page.

**Comment by Tbaut** [comment]
You realise that you are on parity repo right?
What is your question?

**Comment by Pzixel** [comment]
Yes.

This is clearly implementation detail that parity ignores client tries to establish SSL connection and just return a plain text instead. It doesn't work with clients that expect HTTPS error.

For me as client it looks that I'm unable to call parity API if my client forces me to use HTTPS, which is a real issue when I host my site somewhere and trying to access parity via JSONRPC API.

**Comment by folsen** [comment]
Parity can't embed an SSL certificate in the distributed binary for obvious reasons, so the only thing you could use is a self-signed certificate if you're on localhost, but if you're running it remotely (as `my.parity.node` indicates) then the solution is for you to set up something like nginx with an SSL certificate as a proxy in front of the parity node.

You can also use various SSL termination services like cloudflare. See https://en.wikipedia.org/wiki/TLS_termination_proxy for more details.
