### ISSUE TITLE
Cannot create config path

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#8638]
parity --light --base-path "/mnt/tryit"
Error upgrading parity data: CannotCreateConfigPath

I've tried --base-path="/mnt/tryit"
--base-path /mnt/tryit
--base-path=/mnt/tryit

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer Snap
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum /

**Comment by Tbaut** [comment]
I can't reproduce on linux with v1.11.1 with ` --base-path` and `-d`
```
$ parity --base-path ~/Playground --light
2018-05-16 16:22:05  Starting Parity/v1.11.1-beta-6654d02-20180515/x86_64-linux-gnu/rustc1.25.0
2018-05-16 16:22:05  Keys path /home/user/Playground/keys/Foundation
2018-05-16 16:22:05  DB path /home/user/Playground/chains/ethereum/db/906a34e69aec8c0d
2018-05-16 16:22:05  Path to dapps /home/user/Playground/dapps
2018-05-16 16:22:05  Running in experimental Light Client mode.
```

Please make sure you have the rights to create and modify this directory.

**Comment by Tbaut** [comment]
you are running parity as root, this is not recommended, please try with a normal user.

**Comment by quantumproducer** [comment]
Not recommended, but is it expected to work? I'll try creating a normal user..

**Comment by quantumproducer** [comment]
```
dev@tunnel:/mnt/tryit$ parity

Command 'parity' not found, but can be installed with:

sudo snap install parity

dev@tunnel:/mnt/tryit$ snap install parity
error: access denied (try with sudo)
dev@tunnel:/mnt/tryit$ sudo snap install parity
snap "parity" is already installed, see "snap refresh --help"
dev@tunnel:/mnt/tryit$ snap refresh
error: access denied (try with sudo)
dev@tunnel:/mnt/tryit$ sudo snap refresh
All snaps up to date.
dev@tunnel:/mnt/tryit$ ls
dev@tunnel:/mnt/tryit$ snap parity
error: unknown command "parity", see "snap --help"
dev@tunnel:/mnt/tryit$ snap install parity
error: access denied (try with sudo)
dev@tunnel:/mnt/tryit$ sudo snap install parity
snap "parity" is already installed, see "snap refresh --help"
dev@tunnel:/mnt/tryit$
```

**Comment by Tbaut** [comment]
This is I think a problem with the snap. Could you try to install it with [the binaries](https://wiki.parity.io/Setup#binaries) if you are on Ubuntu?

**Comment by quantumproducer** [comment]
@Tbaut thanks - that seems likely. I am letting the main sync run as it looks like it will actually fit on my HDD with compression.
