### ISSUE TITLE
Docs: Difference between service and normal transaction?

### ISSUE THREAD

**Issue by lopezm94** [paritytech/parity#8639]
On the [permissioning site](https://wiki.parity.io/Permissioning.html) service transactions are [described](https://wiki.parity.io/Permissioning.html#how-it-works-3) as 0 gas price transactions. But I can already do zero gas price transactions in a PoA network, what is the purpose of service transactions then? Do they have a different mining priority than normal transactions?

**Comment by Tbaut** [comment]
You are mixing 2 different things:
- PoA network
You can set a gas price to 0, but this won't be per account. All transactions on the network will be for free.

- Permissioned network (can well be based on PoA)
You are able to set a gas price to 0 **per account**, these accounts only will be able to perform transaction freely (these are called service transactions). 
Service transactions are free transaction in a network where not all transactions are free. There mining priority isn't affected AFAIK.
