### ISSUE TITLE
Double-send

### ISSUE THREAD

**Issue by cowpig** [paritytech/parity#8646]
I'm running: 
version: Parity v1.10.4-20180514
OS: Ubuntu 18.04 LTS
installed via: snap
fully synched: yes
connected to: ethereum

I used the UI to send ETH, and parity sent it twice. 

When it asked me for confirmation it was very laggy, so I think I hit 'enter' more than once after entering the password to unlock the account.

Luckily this was a shapeshift xfer so it was refunded...

I imagine this is unrelated, but my console log is flooded with this:
```
parity_lockedHardwareAccountsInfo([]): -32023: Error communicating with hardware wallet.
commons.js:1:2541882
HardwareStore::scanTrezor 
Object { code: -32023, type: "ACCOUNT_ERROR", method: "parity_lockedHardwareAccountsInfo", text: "Error communicating with hardware wallet.", stack: "", … }
commons.js:1:825972
```

If there's any other info that will help debug this I'm happy to provide it.

**Comment by 5chdn** [comment]
Are you using the built-in UI or the external UI? If external, which version?

**Comment by cowpig** [comment]
I type `parity ui` into my terminal, and then use `http://127.0.0.1:8180/#/v1` in my browser. I wasn't aware there was a different UI I could be using.

**Comment by Tbaut** [comment]
>I wasn't aware there was a different UI

If you type `parity ui` in v1.10.4 you should see this screen (just tested):

![image](https://user-images.githubusercontent.com/33178835/40164373-a0faccfe-59b9-11e8-87d0-10b7aacfece2.png)

Can you tell what flags you were using?
Do you remember if you had 2 tabs open?

**Comment by cowpig** [comment]
I wasn't using any flags, literally just use (and used) `parity ui`, and this is what I see:
![screenshot from 2018-05-17 16-07-35](https://user-images.githubusercontent.com/1253515/40201261-930dab42-59ec-11e8-9971-31502e4a453d.png)

I don't remember for sure whether I had two parity tabs open, but I don't believe I did.

**Comment by folsen** [comment]
@amaurymartiny should this issue be closed with your latest PR?

**Comment by amaurymartiny** [comment]
Yes, we can close this issue, my PR fixes double clicking on the confirm button described in the original post - will be out in Parity UI 0.3.

However, in the future, if there are still double spend problems, @tomusdrw proposed to also have a look at the RPC level.

**Comment by folsen** [comment]
@tomusdrw could you open a new ticket for the RPC level problem? Sounds like it could be a good easy pick issue?

**Comment by tomusdrw** [comment]
Done #8799
