### ISSUE TITLE
not able to build v1.8.4 anymore

### ISSUE THREAD

**Issue by ed2k** [paritytech/parity#8647]
test@t420:~/parity$ git reset --hard v1.8.4
HEAD is now at c74c8c1 [beta] Backports + HF block update (#7244)

root@02c36d3afc27:/build/local# cargo build --release --verbose
    Updating git repository `https://github.com/paritytech/js-precompiled.git`
error: failed to load source for a dependency on `parity-ui-precompiled`        

Caused by:
  Unable to update https://github.com/paritytech/js-precompiled.git?branch=beta#26c6b48b

Caused by:
  revspec '26c6b48bfc83bb26445f6d72646773b6d5838fe4' not found; class=Reference (4); code=NotFound (-3)

**Comment by 5chdn** [comment]
Yes, the UI was removed and 1.8 is not supported anymore.
