### ISSUE TITLE
v1.10.0 - Thread '<unnamed>' panicked at 'Error registering user timer: TimerError

### ISSUE THREAD

**Issue by Shekelme** [paritytech/parity#8655]
I got this error message:

> stack backtrace:
>    0:     0x557bbed7d86c - <no info>
> 
> Thread '<unnamed>' panicked at 'Error registering user timer: TimerError { kind: TimerOverflow, desc: "too many timer entries" }', /checkout/src/libcore/result.rs:916
> 
> This is a bug. Please report it at: ...

 I'm running:
 - **Which Parity version?**: v1.10.0-beta-0a9d41e-20180320
 - **Which operating system?**: Linux Mint 18.2
 - **How installed?**: binaries
 - **Are you fully synchronized?**:  yes
 - **Which network are you connected to?**: ethereum
 - **Did you try to restart the node?**:  yes, it says:

`Client service error: Client(Database(Error(Msg("IO error: While lock file: /home/kazna/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/LOCK: Resource temporarily unavailable"), State { next_error: None, backtrace: None })))`

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by Tbaut** [comment]
Thanks for the report, could you tell us what flags you're using to launch parity?
Does this error always happen when you launch it?

**Comment by Shekelme** [comment]
I don't use any flags, just launching it with "parity" in terminal. This is the first time I got this error message. After killing the parity process I was able to start it again successfully.

**Comment by Tbaut** [comment]
Thanks, if it's a one time issue I'll close it then and we can reopen if it happens again.
