### ISSUE TITLE
Huge db file crashes parity

### ISSUE THREAD

**Issue by BillSantos** [paritytech/parity#8660]
> I'm running:
>
> - **Which Parity version?**: v1.10.3-stable-b9ceda3-20180507/x86_64-linux-gnu/rustc1.25.0
> - **Which operating system?**: 4.13.0-41-generic #46~16.04.1-Ubuntu
> - **How installed?**: via apt binaries (.deb file)
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

Parity crashed with the following output.

Also, the db file in ~/.local/ has grown to 78 GB! **How do I set parity to pare the size of this file??**

====================

stack backtrace:
   0:     0x55f0f735403c - <no info>

Thread 'IO Worker #1' panicked at 'DB flush failed.: Error(Msg("IO error: No space left on device While appending to file: /home/username/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/270000.sst: No space left on device"), State { next_error: None, backtrace: None })', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

**Comment by debris** [comment]
This error is very descriptive and it's actually not a bug. You simply run out of space on your disk. Please read [this article](https://dev.to/5chdn/the-ethereum-blockchain-size-will-not-exceed-1tb-anytime-soon-58a) about parity blockchain size and adjust your parity configuration to your needs and hardware capabilities

**Comment by Tbaut** [comment]
Our wiki has updated requirements and overview: https://wiki.parity.io/Setup#ethereum-mainnet-hardware-requirements

**Comment by BillSantos** [comment]
Thanks debris & Tbaut. That was just what I needed!
