### ISSUE TITLE
Difference in contract execution between local POA Chain and DevelopmentChain

### ISSUE THREAD

**Issue by se3000** [paritytech/parity#8661]
> I'm running:
>
> - **Which Parity version?**: 1.9-1.11
> - **Which operating system?**: Linux/Mac
> - **How installed?**: Docker/Homebrew
> - **Are you fully synchronized?**: yes (development chains)
> - **Which network are you connected to?**: local POA / DevelopmentChain
> - **Did you try to restart the node?**: yes

When deploying and testing our contract suite on Parity, we run into an unexpected `bad instruction` error when running against our local POA network. As of 1.9, this also happened against the DevelopmentChain, but as of 1.10 it works on the development chain, but for some reason I get the failure on the POA chain. I assume that execution within the EVM should be the same, so I assume it's a bug, but if not let me know what I should change. We have verified that this error does not occur on Ropsten, so at this point it is only on the POA chain.

When testing our example [Consumer contract](https://github.com/smartcontractkit/chainlink/blob/master/solidity/contracts/examples/Consumer.sol#L28), it blows up after calling `transferAndCall`, in the [inherited contract](https://github.com/smartcontractkit/chainlink/blob/master/solidity/contracts/Chainlinked.sol#L42-L43). If I'm reading it right, the internal transactions succeed, but then fail as soon as returning. If you're skeptical of the `transferAndCall` method on the token, I tried it with calls to other methods on the token(`transfer` and `approve`) and they failed similarly. 

The [successful transaction trace is available here](https://gist.github.com/se3000/ad146bcb7c82ca9ed8298e12412a5bfc) and the [successful vm trace is here](https://gist.github.com/se3000/1326544ca076f5a58270b34c78db3b53), both while running `parity --config=dev --rpcport=18545 --rpcapi all --tracing on`. The failure comes when running against a local POA network, [node config here](https://github.com/smartcontractkit/devnet/blob/master/miner.toml) and [chain config here](https://github.com/smartcontractkit/devnet/blob/master/smartNet.json). The [failed transaction trace is here](https://gist.github.com/se3000/e08065a7cdc1d063219c19451b30f198) and the [failed vm trace is here](https://gist.github.com/se3000/e4e9adacfbfdee74c2684a58c1a90b27).

I briefly discussed this issue in the POA gitter and @Tbaut recommended I open an issue. The tests to get this running don't work with truffle against DevelopmentChain, due to an [issue with truffle](https://github.com/trufflesuite/truffle/issues/389) and how it handles instant sealing, but I've verified with manual deployment and some automated tests in ruby. Reproducing is a bit complicated, because the consumer relies on two contracts, one of which relies on the other. Happy to provide more in depth instructions, upload my ruby tests, or run things myself and post whatever diagnostics you need.

Thanks!

**Comment by edevil** [comment]
Have you tried enabling some of the EIPs on your genesis file? My params section looks like this:
```
  "params": {
    "gasLimitBoundDivisor": "0x400",
    "maximumExtraDataSize": "0x20",
    "minGasLimit": "0x1388",
    "networkID" : "0x42424242",
    "eip155Transition": 0,
    "validateChainIdTransition": 0,
    "eip140Transition": 0,
    "eip211Transition": 0,
    "eip214Transition": 0,
    "eip658Transition": 0
  },
```

I've had ```TRACE executive  res=Err(BadInstruction { instruction: 253 })``` errors in the past and these seemed to influence them.

**Comment by ddorgan** [comment]
@se3000 have you tried adding the Byzantium options to your spec file?

**Comment by se3000** [comment]
@edevil @ddorgan I haven't, I'll try that shortly and get back to you.
