### ISSUE TITLE
rpc eth_getBlockByNumber eth_getBlockByHash eth_getTransactionByHash for some old block return null

### ISSUE THREAD

**Issue by zformular** [paritytech/parity#8663]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: docker parity/parity:latest
> - **Which operating system?**: Linux
> - **How installed?**: via installer docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
actual: 
  return null

expected behavior:
  return block data, transaction data

steps to reproduce:
  don't no, i just request rpc
![1526710691893](https://user-images.githubusercontent.com/1741302/40265753-25c2c62c-5b71-11e8-8db1-e262197e26ce.jpg)

**Comment by dvdplm** [comment]
I cannot reproduce this.

```
$ curl -X POST -H 'Content-type: application/json' --data '{"jsonrpc":"2.0", "method":"eth_blockNumber", "params":[], "id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","result":"0x563b19","id":1}
```

and 

```
$ curl -X POST -H 'Content-type: application/json' --data '{"jsonrpc":"2.0", "method":"eth_getBlockByNumber", "params":["0x563b19", true], "id":1}' http://127.0.0.1:8545
{"jsonrpc":"2.0","result":{"author":"0x5a0b54d5dc17… … …
```

Are you sure you're synch'd?

**Comment by folsen** [comment]
This might be because you haven't finished downloading ancient blocks, I can't remember if it returns null or gives an error but I think it returns null. If you warp-synced then wait until you have downloaded ancient blocks and try again.

**Comment by Tbaut** [comment]
close as stale.
