### ISSUE TITLE
This is a bug, please report it.

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#8667]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: version Parity/v1.10.4-unstable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.26.0
> - **Which operating system?**: Linux
> - **How installed?**: via snap
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

```
2018-05-19 13:04:02 UTC   #2168216    7/25 peers   146 MiB chain 250 MiB db 0 bytes queue 443 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-05-19 13:04:21 UTC Imported #5640623 6e1a…b793 (143 txs, 7.97 Mgas, 557.96 ms, 32.27 KiB)
2018-05-19 13:04:37 UTC   #2168216    0/25 peers   147 MiB chain 250 MiB db 0 bytes queue 444 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-05-19 13:04:56 UTC Syncing #5640623 6e1a…b793     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5640622    1/25 peers   147 MiB chain 250 MiB db 0 bytes queue 445 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-05-19 13:05:03 UTC Imported #5640624 de5c…db73 (151 txs, 7.99 Mgas, 452.83 ms, 20.68 KiB)

====================

stack backtrace:
   0:     0x5590b88093ac - backtrace::backtrace::trace::hdfa43e66dfd107c7
   1:     0x5590b8807b92 - backtrace::capture::Backtrace::new::h45c91cf66d445176
   2:     0x5590b7e1beda - panic_hook::panic_hook::h69b7996814f06671

Thread '<unnamed>' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)
```

The last few days I've been checking and it's crashed a few times, just says "Killed" and I restart it. This time I saw this error message.

I am running with: parity --pruning fast --db-compaction hdd --cache-size=2048 --rpc --warp

**Comment by Tbaut** [comment]
Thanks for reporting it, it's a duplicate from https://github.com/paritytech/parity/issues/8444, please follow it.

Note that `--warp` and `--rpc` do nothing as they are on per default.

**Comment by quantumproducer** [comment]
@Tbaut could this be related to
"2018-05-22 02:58:10 UTC Syncing #1299793 b60d…ff95    83 blk/s  425 tx/s  11 Mgas/s      0+ 6588 Qed  #1306382   31/50 peers   6 MiB chain 2 GiB db 40 MiB queue 13 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
Killed"

I return and it just says "Killed".. I can start it fine. Why would this happen?

**Comment by 5chdn** [comment]
"Killed" usually means your machine is out of memory.

**Comment by quantumproducer** [comment]
@5chdn isn't that handled with --cache-size=1024 ? That sets 1 GB aside, right?

**Comment by 5chdn** [comment]
That does not prevent your machine from running out of memory though.

**Comment by 5chdn** [comment]
How much memory does your machine have?
