### ISSUE TITLE
web3.personal.unlockAccount call issue

### ISSUE THREAD

**Issue by HatimTim** [paritytech/parity#8668]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**: Ubuntu 16.04
> - **How installed?**: via deb binaries 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ropsten 
> - **Did you try to restart the node?**: yes

I'm using web3 **1.0.0-beta.34** to connect to parity node.
The parity node is started with:
```
parity --chain=ropsten --jsonrpc-apis "web3,eth,personal,parity_accounts"
```
and also using
```
parity --chain=ropsten
```
The account unlock using the below command is not successful
```
web3.personal.unlockAccount("0x00C...", "password", 1000);
```
The error below is generated:
TypeError: Cannot read property 'unlockAccount' of undefined

Please help to solve this issue . Thanks

**Comment by Tbaut** [comment]
As of web3.js v1.0, you have to go through `eth` in order to reach personal from nodejs:

`web3.eth.personal.unlockAccount("0x..", "<passs>", 1000);`
