### ISSUE TITLE
help to upgrade example contract to new version ......

### ISSUE THREAD

**Issue by JokerCatz** [paritytech/parity#8673]
previous discussion : https://github.com/paritytech/parity/issues/8651

the example contract is too old and has many bug(like overflow attack ... ) , the new version of contract must support `eip658Transition` and use `SafeMath` , & the function define must add `public` keyword , not support `throw` anymore ... so I try to make a new version like this

    pragma solidity ^0.4.18;
    contract Token {
        uint256 public totalSupply;
        function balanceOf(address _owner) public constant returns (uint256 balance);
        function transfer(address _to, uint256 _value) public  returns (bool success);
        function transferFrom(address _from, address _to, uint256 _value) public returns (bool success);
        function approve(address _spender, uint256 _value) public returns (bool success);
        function allowance(address _owner, address _spender) public constant returns (uint256 remaining);
        event Transfer(address indexed _from, address indexed _to, uint256 _value);
        event Approval(address indexed _owner, address indexed _spender, uint256 _value);
    }
    library SafeMath {
        function add(uint a, uint b) internal pure returns (uint c) {
            c = a + b;
            require(c >= a);
        }
        function sub(uint a, uint b) internal pure returns (uint c) {
            require(b <= a);
            c = a - b;
        }
        function mul(uint a, uint b) internal pure returns (uint c) {
            c = a * b;
            require(a == 0 || c / a == b);
        }
        function div(uint a, uint b) internal pure returns (uint c) {
            require(b > 0);
            c = a / b;
        }
    }
    contract StandardToken is Token {
        using SafeMath for uint;
        function transfer(address to, uint tokens) public returns (bool success) {
            balances[msg.sender] = balances[msg.sender].sub(tokens);
            balances[to] = balances[to].add(tokens);
            emit Transfer(msg.sender, to, tokens);
            return true;
        }
        function transferFrom(address from, address to, uint tokens) public returns (bool success) {
            balances[from] = balances[from].sub(tokens);
            allowed[from][msg.sender] = allowed[from][msg.sender].sub(tokens);
            balances[to] = balances[to].add(tokens);
            emit Transfer(from, to, tokens);
            return true;
        }
        function balanceOf(address _owner) public constant returns (uint256 balance) {
            return balances[_owner];
        }
        function approve(address _spender, uint256 _value) public returns (bool success) {
            allowed[msg.sender][_spender] = _value;
            emit Approval(msg.sender, _spender, _value);
            return true;
        }
        function allowance(address _owner, address _spender) public constant returns (uint256 remaining) {
          return allowed[_owner][_spender];
        }
        mapping (address => uint256) balances;
        mapping (address => mapping (address => uint256)) allowed;
    }
    contract HumanStandardToken is StandardToken {
        function () public {
            require(false);
        }
        string public name;
        uint8 public decimals;
        string public symbol;
        string public version = 'H0.1';
        constructor(
            uint256 _initialAmount,
            string _tokenName,
            uint8 _decimalUnits,
            string _tokenSymbol
            ) public {
            balances[msg.sender] = _initialAmount;
            totalSupply = _initialAmount;
            name = _tokenName;
            decimals = _decimalUnits;
            symbol = _tokenSymbol;
        }
        function approveAndCall(address _spender, uint256 _value, bytes _extraData) public returns (bool success) {
            allowed[msg.sender][_spender] = _value;
            emit Approval(msg.sender, _spender, _value);
            require(_spender.call(bytes4(bytes32(keccak256("receiveApproval(address,uint256,address,bytes)"))), msg.sender, _value, this, _extraData));
            return true;
        }
    }

please help me to fix it , and sorry I don't know what project(github) include the example code (`StandardToken.sol` , `HumanStandardToken.sol`) , maybe ParityUI or somewhere , so I create a issue here , many thanx

**Comment by Tbaut** [comment]
This is definitely a [Parity UI](https://github.com/Parity-JS/shell/issues) related issue. I don't think this will be addressed any time soon though. Feel free to copy it to this repo.

**Comment by JokerCatz** [comment]
okay , I just think it need be fix & add to issue , I'll copy to there
