### ISSUE TITLE
Current size of synced blockchain?

### ISSUE THREAD

**Issue by quantumproducer** [paritytech/parity#8676]
How can I calculate how much disk space I need for a parity sync?
My 80 GB drive just got filled from warp syncing.

**Comment by iFA88** [comment]
Foundation network:
-warp full sync ~21GB
-normal mode full sync ~105GB
-full node ~1115 GB

**Comment by iFA88** [comment]
If you don't need old blocks use `--no-ancient-blocks` flag.

**Comment by quantumproducer** [comment]
@iFA88 very helpful, thank you. Does a warp node require a full sync (105 GB) and then downsize to 21 GB?

**Comment by Tbaut** [comment]
Please find updated numbers here: https://wiki.parity.io/Setup#ethereum-mainnet-hardware-requirements.

@iFA88 I do not agree with your naming.
A full node is what you get without any flag (~80GB). A full node with archive state tree is ~1.1TB

It is also useful to mention that `--no-ancient-blocks flag` isn't secure as the client does not perform the full blockchain verification from the genesis block.

**Comment by 5chdn** [comment]
> -warp full sync ~21GB

That's the size without ancient blocks.

**Comment by quantumproducer** [comment]
@Tbaut , running wirth --pruning=light says "unstable". Is this the same as insecure, or is light a reliable way to sync?

I need to get smart contract data from a recent contract.

**Comment by Tbaut** [comment]
@quantumproducer the `--light` flag is statistically less secure than a full node where you verified all blocks from the genesis but the level of security remains very high as any transaction you do would be verified by fetching data from full nodes and verifying it against merkle roots. 

`Unstable` is related to the release stability. Here it simply means that potential bugs remain. You should definitely give it a try and see if it works for you.

**Comment by quantumproducer** [comment]
Thank you @Tbaut . --light seemed to sync faster but eventually stopped working.
My current solution is : increased storage space, running with fast, and a cache size of 1024. It reached block 5,000,000 in a few days, slow moving from here (is this expected?)

But it hasn't crashed and seems to be gradually incrementing :)

**Comment by Tbaut** [comment]
@quantumproducer let's not mix discussions. Feel free to have a look at our [Gitter channel](https://gitter.im/paritytech/parity) to continue the discussion.

**Comment by Mnuzz** [comment]
Just a note: A gGoogle search for "parity node size" yields this page as result #3. However, the link to https://wiki.parity.io/Setup#ethereum-mainnet-hardware-requirements posted by @Tbaut on May 21, 2018, no longer contains this information about the storage requirements of various types of Parity nodes. 

The information can now be found on the FAQ. https://wiki.parity.io/FAQ#what-are-the-parity-ethereum-disk-space-needs-and-overall-hardware-requirements

**Comment by Tbaut** [comment]
Thanks for the heads-up, I'll update it.

**Comment by 5chdn** [comment]
http://didtheethereumblockchainreach1tbyet.5chdn.co

**Comment by vietthang207** [comment]
Hi all, I just have a small question. I want my node to have all snapshot from block 5000000, is there a way to config that?

**Comment by joshua-mir** [comment]
@vietthang207 what do you mean by that? Warp sync snapshots? You should know that your node only keeps a single (the latest) snapshot that it creates every 5k blocks. I'm not sure what you are trying to achieve with a snapshot from block 5M.

**Comment by vietthang207** [comment]
@joshua-mir So what happened when I query historical snapshots that were not stored in the hard disk. Will parity take the closest snapshot and blocks to calculate that ancient snapshots? Will it find an archive node and query that?

**Comment by vietthang207** [comment]
@joshua-mir Sorry, I misunderstanding state and snapshot. As my company form for only more than 1 year, we don't need data before that point and I think I can save some storage by a partial archive nod.

**Comment by joshua-mir** [comment]
Please create a new issue so we can discuss/track this @vietthang207

**Comment by k06a** [comment]
@5chdn not works
