### ISSUE TITLE
Discovery on private PoA Network

### ISSUE THREAD

**Issue by S3bb1** [paritytech/parity#8685]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**:Linux
> - **How installed?**: docker
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: private PoA Network
> - **Did you try to restart the node?**: yes

We're currently running 5 PoA Nodes on AWS and Azure on docker with a private chain. 3 of the nodes are defined in the nodes section of the chain definition. The 2 other nodes are currently finding each other (after hours) through discovery. When i start a parity client locally on my notebook i only find the 3 nodes in the definition and not the other 2 which aren't defined in the nodes section. All Ports (30303 TCP/UDP) are open on the Cloud Machines. Can you help with this ?

**Comment by Tbaut** [comment]
Thanks for your report. Discovery can take time, how long did you let your local node running and discovering?
Could you please add the `-l discovery=trace,network=trace` flags to your local node and post here a couple minutes of logs?

**Comment by S3bb1** [comment]
Hi, the local node runs about 6 to 8 hours. I try to get a log and will post it.

**Comment by S3bb1** [comment]
after adding more nodes, discovery seems to be working okay and faster. I'll reopen the issue when the problem reappears. Thank you.
