### ISSUE TITLE
Question: TX with future nonce

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity#8694]
Greetings.
If I or another else broadcast a transaction with future nonce (example the next should be 3 but I give 4) when will be dropped from my `Parity/v1.11.1-beta-6654d0216-20180515/x86_64-linux-gnu/rustc1.25.0` node when I use the following flags: `-no-ancient-blocks --min-gas-price=1000000000 --tx-queue-mem-limit=128 --tx-queue-size=128000 --reseal-on-txs=all --force-sealing` ?

**Comment by Tbaut** [comment]
Local transactions are not dropped unless you specify it with the flag:
```
    --no-persistent-txqueue
        Don't save pending local transactions to disk to be
        restored whenever the node restarts.
```

**Comment by iFA88** [comment]
The node has received a transaction with a future nonce and very high gas price. If I query the pending transactions, this  "wrong" transaction is inside and causes problem for my fee calculator.
I have cleared that with `--no-persistent-txqueue` but this is only temporary solution.

**Comment by iFA88** [comment]
Please reopen this, because this was not a local transaction.

**Comment by Tbaut** [comment]
The transaction queue in Parity is built in such a way that your local transactions will always be prioritized. There was recently a bug that prevented this to happen, a fix has been prepared and will be added in a future minor release: https://github.com/paritytech/parity/pull/8691
So even if your queue is full of external future transactions, if a new local transaction is added, one of the future external ones will be dropped. 
External future transactions are not necessarily dropped, if the queue is not full it will be kept.

**Comment by Tbaut** [comment]
Your logic to check the pending queue is obviously not ideal. 
>If the Node get a non-local TX with a future nonce why not will be dropped?

For a lot of reasons, one of them being because we are in a p2p network and getting external txs from the network, they are not ordered and we need to buffer them.

**Comment by iFA88** [comment]
> Your logic to check the pending queue is obviously not ideal.

I query one time all pending transaction from the node with `parity_pendingTransactions` and then I use filter to get new pending TX's. Do you have any better idea?

> For a lot of reasons, one of them being because we are in a p2p network and getting external txs from the network, they are not ordered and we need to buffer them.

Alright, that's a good point, we need buffer that forever? At this moment the node has `60851` pending TX and from that `184` TX has "nonce hole".

**Comment by Tbaut** [comment]
Is there any reason you don't use [eth_estimategas](https://wiki.parity.io/JSONRPC-eth-module#eth_estimategas)? That'd be my suggestion.
Regarding the pending TXs, if that's a resource problem for you, you can reduce the queue size, mem limit etc using : 

```
    --tx-queue-mem-limit=[MB]
        Maximum amount of memory that can be used by the
        transaction queue. Setting this parameter to 0 disables
        limiting. (default: 4)

    --tx-queue-size=[LIMIT]
        Maximum amount of transactions in the queue (waiting to be
        included in next block). (default: 8192)

    --tx-queue-per-sender=[LIMIT]
        Maximum number of transactions per sender in the queue. By
        default it's 1% of the entire queue, but not less than 16.

    --tx-queue-gas=[LIMIT]
        Maximum amount of total gas for external transactions in
        the queue. LIMIT can be either an amount of gas or 'auto'
        or 'off'. 'auto' sets the limit to be 20x the current block
        gas limit. (default: off)
```

**Comment by iFA88** [comment]
EstimateGas? You mean i should run `estimateGas` for every pending transaction? Why? This will take 15-20 mins for the first time and for every block I should run again, because maybe calls a contract and we don't know whats happenning in other blocks. This is a terrible idea.
I don't have any resource problem :) I already use the following flags: `--min-gas-price=1000000000 --tx-queue-mem-limit=1024 --tx-queue-size=128000`

**Comment by Tbaut** [comment]
I get it, you have several ways of achieving what you need without checking the pending queue. In Parity UI we used the average gasPrice from the transactions in previous blocks AFAIK, this is much more reliable as it will follow the trend of actually mined transactions. I believe you already know about the [eth_gasprice method](https://wiki.parity.io/JSONRPC-eth-module#eth_gasprice) or  [ ethgasstation API](https://github.com/ethgasstation/ethgasstation-api)?

**Comment by iFA88** [comment]
Please let me ask an anohther:
Is there any way to find out which pending transactions is no more in the queue? In few hours I receive about 30'000 pending TX with `eth_getFilterChanges` on `eth_newPendingTransactionFilter` filter which are not even in block and not anymore in the queue.. they simple varnishes.
I can use `eth_getTransactionByHash` for check pending TX, but this is huge performance loss.

Thank you!

**Comment by Tbaut** [comment]
@iFA88 we are completely diverging from the OP here. Please join the [Gitter channel](https://gitter.im/paritytech/parity) to continue this discussion or post another issue.

**Comment by Parean** [comment]
Hi Tbaut! Could you please tell me if transactions with too high nonce are propagated to other nodes from local queue by parity? I want to understand what happens with tx when I create tx with too high nonce. It's saved in a local queue, but do other nodes get the information about this tx? I don't know, can I remove tx from the queue before it's mined and be sure that it won't be mined later by some node that received that tx before I removed it.
