### ISSUE TITLE
Online installer not working in FRESH Ubuntu 16.04

### ISSUE THREAD

**Issue by jrischma** [paritytech/parity#8698]
Hi, i cant install parity, say: 
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   170    0   170    0     0     88      0 --:--:--  0:00:01 --:--:--    88
100  4278  100  4278    0     0   2018      0  0:00:02  0:00:02 --:--:--  2018
Release selected is: beta
basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 0.0.0 is newer than the version you attempting to install:

Ubuntu 16.04.4 x64
```
thanks
```
basename --version
basename (GNU coreutils) 8.25
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by dvdplm** [comment]
Hi! Thank you for the report. What was the command you ran to get the reported output please?

**Comment by jrischma** [comment]
Hi , i try with 
1. bash <(curl https://get.parity.io -Lk)
2. bash <(curl https://get.parity.io -Lk) -r stable

with 1 or 2 show the error

for that i use "sudo snap install parity" but now i cant get a stable version, always snap install unstable version, so i remove parity and run "bash <(curl https://get.parity.io -Lk) -r stable" now install but when i check the version show "bash: /snap/bin/parity: No such file or directory"

so, How can i get a stable version and fix this error ??

**Comment by ddorgan** [comment]
@jrischma did you install the snap package before doing the one liner install? The one liner doesn't use snap so maybe remove this snap package and re-try.

**Comment by jrischma** [comment]
@Tbaut , yes thanks, is possible change the path ? how ?

**Comment by ddorgan** [comment]
@jrischma try running ```snap remove parity ``` and then try to run it again.

**Comment by jrischma** [comment]
i run 
1. snap remove parity
2. bash <(curl https://get.parity.io -Lk) -r stable

but the PATH not change

**Comment by ddorgan** [comment]
@jrischma ok not sure what's up with your system. 

If you run ```/usr/bin/parity ``` it works as expected, right? 

Can you also give us the output of ``` which parity ``` and ``` env ``` please.

**Comment by Meshugah** [comment]
I've got the same error. 
which returns `/usr/bin/parity`

**Comment by Tbaut** [comment]
@Meshugah can you confirm that the problem you have is the one from the first post?
https://github.com/paritytech/parity/issues/8698#issue-325863282

**Comment by Meshugah** [comment]
Yes, this is the same one as in the original post.

**Comment by Tbaut** [comment]
@Meshugah what do the following command return:
- `/usr/bin/parity -v` 
- `parity -v`
- `bash <(curl https://get.parity.io -Lk)`
