### ISSUE TITLE
transaction(block) is reverted 

### ISSUE THREAD

**Issue by wcw84** [paritytech/parity#8701]
Hi
> I'm running:
>
> - **Which Parity version?**: version Parity/v1.8.11-stable-21522ff-20180227/x86_64-linux-gnu/rustc1.24.0> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum

I run my Dapp based on my parity node, and my script will check very newest block every 5 seconds again and again.
And it found a weird problem: 

```json
{
    "jsonrpc": "2.0",
    "result": [{
                "action": {
                    "callType": "call",
                    "from": "0x0a3260db7f3fc3c86eae69bebed813b9ef988493",
                    "gas": "0x441d8",
                    "input": "0x",
                    "to": "0x39cc3250eecfbbd270a241f6a3255a92b780b492",
                    "value": "0x29a2241af62c0000"
                },
                "blockHash": "0xac5efb42984301637b234e089f9f609a8a604aa99824da716d81cf24944d42ed",
                "blockNumber": 5661999 ,
                "result": {
                    "gasUsed": "0x174eb",
                    "output": "0x"
                },
                "subtraces": 0,
                "traceAddress": [],
                "transactionHash": "0x9b481b191b295787f88854aba85d41b578a4f81b688db1f2f4d0f348e5f05cac",
                "transactionPosition": 28,
                "type": "call"
            }
```

The message above show the transaction "0x9b481b191b295787f88854aba85d41b578a4f81b688db1f2f4d0f348e5f05cac" is in block 5661999 and succeed. 
But now you can check it from the [etherscan](https://etherscan.io/tx/0x9b481b191b295787f88854aba85d41b578a4f81b688db1f2f4d0f348e5f05cac), 
![image](https://user-images.githubusercontent.com/7152596/40463170-345b6d28-5f46-11e8-8335-3015509bfe48.png)
The transaction failed actually, and it is in block 5662001 but not 5661999. It seems that the block 5661999 I received from parity at that time was reverted after a while.

Actually all i need is the block confirmed, How to avoid the problem above?

Any help will be appreciated.

**Comment by Tbaut** [comment]
Your version of Parity is EOL, please upgrade to benefit from the latest improvements :)

Where did you see it succeeding? Am I right in thinking that the log you gave was the result of a trace_transaction call?

Getting a transaction receipt:
```
{
    "jsonrpc": "2.0",
    "result": {
        "blockHash": "0xcf33ace5b1ad528d9521297b12f7a1041d686fd0b9d3f4872f66f06a305ca2e3",
        "blockNumber": "0x566531",//5662001
        "contractAddress": null,
        "cumulativeGasUsed": "0x16c58c",
        "gasUsed": "0x5aac",
        "logs": [],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "root": null,
        "status": "0x0",//fail
        "transactionHash": "0x9b481b191b295787f88854aba85d41b578a4f81b688db1f2f4d0f348e5f05cac",
        "transactionIndex": "0x19"
    },
    "id": 1
}
```

**Comment by wcw84** [comment]
@Tbaut 
OK, i will upgrade.
Yes, the log is the result of trace_transaction in my log file, as I said above, I have a script which will check the latest block every 5 seconds, and logged to file.
 And I am sure the transaction succeed firstly, because I also opened etherscan after I sent out the transaction, and I saw it succeed indeed.

**Comment by Tbaut** [comment]
I assume that there was a chain reorganisation and that your transaction was situated on an uncle block. Your block (with your transaction) was got included in a new block later on. [This helps to understand](https://ethereum.stackexchange.com/questions/21146/what-happens-to-transactions-in-orphaned-forked-blocks).
