### ISSUE TITLE
Interact with parity through the CLI

### ISSUE THREAD

**Issue by raphadko** [paritytech/parity#8718]
I'm running parity on a VPS, without a GUI, and I'vve been trying (without success) to run commands on parity through a CLI - basic stuff like generating wallets and addresses, without parity UI.
 
Is there a way to send commands from the cli to Parity? Is there documentation for the available commands?

**Comment by Tbaut** [comment]
You can also create and list accounts using the CLI:
```
$ parity account --help
parity-account 
Manage accounts

USAGE:
    parity account <SUBCOMMAND>

FLAGS:
    -h, --help    Prints help information

OPTIONS:


SUBCOMMANDS:
    import    Import account
    list      List existing accounts
    new       Create a new acount
```

But the [parity_accounts module](https://wiki.parity.io/JSONRPC-parity_accounts-module) should fit all your needs as stated by @saulbein.
