### ISSUE TITLE
How to speed up syncing?

### ISSUE THREAD

**Issue by zformular** [paritytech/parity#8724]
_Before filing a new issue, please **provide the following information**._

> I'm running: docker
>
> - **Which Parity version?**: docker parity
> - **Which operating system?**: Linux
> - **How installed?**: parity
> - **Are you fully synchronized?**:yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

net：5M

actual
syncing very slow, unable to catch up.

expected behavior
catch up the highest block
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1741302/40635994-76bd56c6-632f-11e8-8507-75a240f1e707.png">
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/1741302/40636001-802e84fa-632f-11e8-826f-65e6005734e3.png">

**Comment by Tbaut** [comment]
- What version of parity is it?
- Can you share the flags you use to launch parity?
- Are you on HDD or SSD?
- You must have a bottleneck with the disk IO or the network bandwidth. Can you share the result of `iostat -x 1` and tell what kind of internet connection you have?
