### ISSUE TITLE
Request failed with status code 521

### ISSUE THREAD

**Issue by vieiralc** [paritytech/parity#8730]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:  v1.10.4-20180514 stable
> - **Which operating system?**: Windows 32bits
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: dev
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

![image](https://user-images.githubusercontent.com/19657718/40678041-c61491fa-6355-11e8-87ac-4ebaef42f3a3.png)

**Comment by Tbaut** [comment]
Please reopen the issue in https://github.com/Parity-JS/shell/issues  and attach the logs as asked in the error message :)
