### ISSUE TITLE
Parity don't get peers from bootnode in private blockchain env

### ISSUE THREAD

**Issue by http403** [paritytech/parity#8732]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**: Linux +LXC
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: yes

**Description**:
I'm trying to build my own private chain for learning smart contract. However, Parity doesn't get peers on bootnode while Geth can. I have to specify nodes as reserved node to get it in sync. I tried to install parity in locally as well as LXC environment. No luck at all. I'm using `bootnode` that ship with `geth v1.8.9-stable-ff9b1461`.

**Actual Behaviour**
Unable to get peers with bootnode.

**Expected Behaviour**
Get nodes with bootnode without specifying reserved node.

**Steps to reproduce**

1. start a bootnode in LXC
2. specify enode address in `--bootnodes` argument
3. doesn't sync

**Comment by ddorgan** [comment]
@http403 also can you connect from one node to the boot node on port 30303?

**Comment by http403** [comment]
@Tbaut I don't have any bootnode running parity since they all run in separate LXC container. [Log](https://gist.github.com/http403/6cc6ea8816c6290b5a29694a1590d40e)
Command line I used:
```sh
parity --chain=parity-genesis.json -d=testnet --db-path=testnet_db --network-id=654654 --bootnodes=enode://81ea3bbd51fc56cae4b4e74ac1e333d10c533100ed49a73f1c4751af74242f48b936689f83775c814c02758bc797f584fd7da60d89dcf451a70bd230fdef07fa@10.174.114.154:30301 --tracing=on --pruning=archive --fat-db=on -l sync=trace,network=trace --log-file=parity.log
```
@ddorgan Yes, but Geth client only. Parity doesn't want to connect. I can verify this in bootnode log.

**Comment by 5chdn** [comment]
@http403 there is not much happening on the Parity side. The log indicates the Geth bootnode did a `Hup` - _hang up_ which basically means it closed the connection on their side.

You should investigate the Geth logs and eventually figure out why Geth does not want to accept the Parity connection.

**Comment by http403** [comment]
@aaroncolaco I'm sorry as I totally forgot I opened this issue and not updating my findings. Did you initialize all the client with the **same genesis block**? Parity (and Geth) won't synchronize if the genesis block isn't the same even you specified a bootnode server. I wasn't able to get peers is because I forgot this import step. It is totally irrelevant to Parity.
