### ISSUE TITLE
Parity is dead slow

### ISSUE THREAD

**Issue by SergeyZYX** [paritytech/parity#8742]
Hello. 

I want to make a full copy of ethereum database on my server, so synching in fat mode. I have not so fast hdd 5400rpm. As of now I am already synching for about 2 weeks and it's on 4'800'000 block. About 1 million blocks to go. Disk load near 100%. Taking current synch speed it's gonna take about 2 weeks more to complete synch. 

This is how I start it from command line:

./parity --db-compaction=hdd --fat-db=on --cache=512 --mode=active --ui-port=8191 --min-peers=2 --max-peers=5 --snapshot-peers=7

Is there any way to speed it's up? I can't figure out. Thanks.

parity v1.10.4
centos 7
build from sources

**Comment by Tbaut** [comment]
As stated in our wiki: [parity hardware requirements](https://wiki.parity.io/Setup#ethereum-mainnet-hardware-requirements). We strongly advise against HDD (not even mentioning slower HDD). As more recent blocks get bigger, you might never be able to reach the top of the chain. 
As a side note:
```
 --fat-db=[BOOL]
        Build appropriate information to allow enumeration of all
        accounts and storage keys. Doubles the size of the state
        database. BOOL may be one of on, off or auto. (default:
        auto)
```
`--fatdb on` doesn't give you a better copy of the "ethereum database". It makes the sync slower and disables the warp-sync. Make sure that it's really what you need.
