### ISSUE TITLE
Can parity json rpc respond a http HEAD request? 

### ISSUE THREAD

**Issue by antimoth** [paritytech/parity#8759]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**: Linux
> - **How installed?**: via installer binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

### when send a HEAD request using 'curl', an empty response received.
```
admin@ethereum01-prd-hz:~$ curl -i --head "http://10.6.0.62:8645"
curl: (52) Empty reply from server
admin@ethereum01-prd-hz:~$ 
```

### but requestes a geth client, the response is 
```
admin@ethereum01-prd-hz:~$ curl -i --head "http://10.6.0.62:8180"
HTTP/1.1 415 Unsupported Media Type
Content-Type: text/plain; charset=utf-8
Vary: Origin
X-Content-Type-Options: nosniff
Date: Fri, 01 Jun 2018 09:48:43 GMT
Content-Length: 57

admin@ethereum01-prd-hz:~$ 
```

### Is there a feature to support the HEAD request? or How to set the parity to support the HEAD request?

**Comment by tomusdrw** [comment]
What's the issue exactly? Responding without content to `HEAD` request is actually what should be done, trying running `curl` with `-v` option to see the headers.
For health checks we also support `http://localhost:8545/api/health` endpoint - it will return non-200 in case we detect peering or time sync problems.

**Comment by Tbaut** [comment]
Documentation issue was opened here https://github.com/paritytech/wiki/issues/119

**Comment by antimoth** [comment]
but it isn't a normal http response, no protocol, no status code, etc.
