### ISSUE TITLE
Upgrade Parity from source did not work

### ISSUE THREAD

**Issue by Feuda** [paritytech/parity#8760]
> I'm running:
>
> - **Which Parity version?**: 1.7.10
> - **Which operating system?**: Linux
> - **How installed?**: via installer from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I want to upgrade Parity from 1.7.10 to 1.10.4, I pulled the latest code from branch 'stable' and ran` $ cargo build --release  
`, after successfully processed, `parity -v ` shows that Parity version is still 1.7.10

**Comment by Tbaut** [comment]
Your binary of the new version you built is in `. /target/release/parity`. Your path uses most probably `/usr/bin/party`. You should copy the new version in  `/usr/bin/party`.
