### ISSUE TITLE
Bug_report: trace_replayBlockTransactions responds with error to set pruning to archive at block 0

### ISSUE THREAD

**Issue by ankitchiplunkar** [paritytech/parity#8762]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.4-stable
> - **Which operating system?**: Ubuntu 18.04
> - **How installed?**: Simple one-line installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
I am not able to use the JSON-RPC command  trace_replayBlockTransactions at block 0

```
(venv) blah@blah:~/ether_sql$ curl --data '{"method":"trace_replayBlockTransactions","params":["0x0",["trace"]],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","error":{"code":-32000,"message":"This request is not supported because your node is running with state pruning. Run with --pruning=archive."},"id":1}
```
The above command should return a null Array

```
{"jsonrpc":"2.0","result":[],"id":1}
```

This might be linked to a previous issue: https://github.com/paritytech/parity/issues/7547
The difference is that I can view traces using other functions:

```
(venv) blah@blah:~/ether_sql$ curl --data '{"method":"trace_block","params":["0x0"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":[],"id":1}

```

**Comment by 5chdn** [comment]
Fixed in #8891
