### ISSUE TITLE
[JSONRPC] cURL error 28: Operation timed out after 1001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by candro** [paritytech/parity#8767]
> I'm running:
>
> - **Which Parity version?**: Parity 1.10.3-stable
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: es
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Method eth_sendTransaction returned:
cURL error 28: Operation timed out after 1001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Request:** 
```
{
  "id": 1778857526,
  "jsonrpc": "2.0",
  "method": "eth_sendTransaction",
  "params": [
    {
      "from": "0x19306913ea183b8489270f1684193ab7abeec5e8",
      "to": "0xC2F9aA1469C56981D2802Fb904b4AE9aC02639d3",
      "value": "0x11"
    }
  ]
}
```
**Parity config:** 
> [parity]
> no_consensus = true
> 
> [rpc]
> disable = false
> port = 8545
> interface = "127.0.0.1"
> apis = ["all"]
> 
> [websockets]
> disable = true
> 
> [ipc]
> disable = true

**Comment by Tbaut** [comment]
I'm surprised you use `no_consensus = true`. Why?

**Comment by candro** [comment]
I found the case. After calling the method **eth_sendTransaction** or **eth_signTransaction**, this "call" is placed in the signer. You can get the list through the **signer_requestsToConfirm** method, and you already have to confirm it using **signer_confirmRequest**.  This is not the correct behavior or documentation is not complete.

**Comment by Tbaut** [comment]
Thanks for the feedback. If no account got unlocked, or you are not using [personal_sendTransaction](https://wiki.parity.io/JSONRPC-personal-module#personal_sendtransaction), then this behavior is expected. I don't think we have any tutorial inherently right or wrong. Feel free to submit a PR in the wiki if you think some info could have helped you.
