### ISSUE TITLE
identity NOT work ...

### ISSUE THREAD

**Issue by jrischma** [paritytech/parity#8768]
I'm running:
 - Parity/v1.10.4-stable-39b9f1e-20180514/x86_64-linux-gnu/rustc1.25.0
-  Ubuntu 16.04.4 LTS 
- bash <(curl https://get.parity.io -L) -r stable
- **Are you fully synchronized?**:  yes
- **Which network are you connected to?**: ethereum Classic
- **Did you try to restart the node?**:  yes

parity --chain classic .... --extra-data "ETC.CHILEMINERS.CL"  --identity "ETC.CHILEMINERS.CL"

![image](https://user-images.githubusercontent.com/11020812/40879950-aa627b24-6676-11e8-96e3-d86b9dd65fc5.png)

why not show **"Name: ETC.CHILEMINERS.CL"** ????

thanks!

**Comment by Tbaut** [comment]
duplicates https://github.com/paritytech/parity/issues/6852

**Comment by 5chdn** [comment]
Addressed in #8830?
