### ISSUE TITLE
stack backtrace:    0:     0x562b95f5bdbc - <no info>

### ISSUE THREAD

**Issue by TheTesla** [paritytech/parity#8769]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**: Linux (Ubuntu 16.04)
> - **How installed?**: via installer (deb file)
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

ran:

```
parity --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 4096 --fast-and-loose --peers 1500
```

**Comment by Tbaut** [comment]
Can you please paste the whole error message?

**Comment by Tbaut** [comment]
By the way, you are using `--fast-and-loose` which corrupts the DB most probably each time you'll stop the node.
