### ISSUE TITLE
Creating separate repos for ethkey and maybe other crates

### ISSUE THREAD

**Issue by elichai** [paritytech/parity#8772]
Hi,
I'm using ethkey for key generation, signing and other of the tools it provides inside my core.
I wonder why not put it in a different git repository and maybe even upload it to crates.io so it will be easier to use.
Right now I copied it manually so I'll need to update it manually because I can't even clone and update from upstream because it's a directory inside parity.

I think it would be better if every crate you have that is useful for others too will get it's own repo.

Thanks,
Elichai.

**Comment by niklasad1** [comment]
@elichai 

Actually you can use `ethkey directly` by specifying the following in your `Cargo.toml`:

```rust
[dependencies]
ethkey = { git = "https://github.com/paritytech/parity.git" }
```

But yes, would probably be easier for everyone if it was published on `crates.io`

**Comment by elichai** [comment]
it will work even though one of ethkey's dependencies is a relative path? `ethcore-crypto = { path = "../ethcore/crypto" }`

**Comment by niklasad1** [comment]
Yes, according to the cargo docs 

> Cargo will fetch the git repository at this location then look for a Cargo.toml for the requested crate anywhere inside the git repository (not necessarily at the root).

**Comment by elichai** [comment]
ok, I'll use that. although If you will make a different repository for great tools like that It would be great :)
(and the docs for ethkey can be better, maybe I'll try to make a PR for them )

**Comment by Tbaut** [comment]
:) PR in the wiki are always welcome: https://github.com/paritytech/wiki/
