### ISSUE TITLE
[JSONRPC] eth_getBlockByXXX return nothing for some old blocks

### ISSUE THREAD

**Issue by kchernyshev** [paritytech/parity#8775]
> - **Which Parity version?**: Parity v1.10.4-20180514 stable
> - **Which operating system?**: Windows
> - **How installed?**: via installer
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

JSON rpc calls work fine for recent blocks 
e.g. (using EthJsonRpc for python)
c.eth_getBlockByNumber(5726015)
c.eth_getBlockByHash("0xd7807183f083dbeb453c610a0b44737542ca9de28943fb633f02147727b5073a")

but if I try to fetch an older block, it returns nothing:
c.eth_getBlockByNumber(2502000)
c.eth_getBlockByHash("0x90a608af9ae76de675ec90bbd87a5ec435fe3bd3d50ba3fe8eafa599586690cf")

{'id': 1,
 'jsonrpc': '2.0',
 'method': 'eth_getBlockByNumber',
 'params': ['0x262d70', False]}

{'id': 1, 'jsonrpc': '2.0', 'result': None}

**Comment by kchernyshev** [comment]
Oh, I see, that makes sense, yes

**Comment by iFA88** [comment]
You should know after warp sync follows the normal sync also as default. If you run your node about 3-4 days, you will have a full node.
