### ISSUE TITLE
Change name/description of fast_and_loose.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/parity#8779]
The config option fast-and-loose has a name and documentation that currently implies that the node can be restarted, it just isn't resilient to failure.  This makes it sound like a great solution for running a dev chain or test chain, and lead me (and others #7910) to try to use it that way only to find out after much troubleshooting that that isn't the case.

My particular use case is to create a Parity docker image that has some base contracts pre-delpoyed to it that I can then test against.  For example, one might create a Dockerfile like:
```Dockerfile
FROM parity/parity:v1.11.1

WORKDIR /
COPY dev-key.json /parity/keys/DevChain/dev-key.json
COPY chain-spec.json /parity/chain-spec.json
COPY config.toml /parity/config.toml
RUN echo "" > /parity/password

COPY deploy-contracts.sh /app/deploy-contracts.sh
RUN chomd 555 /app/deploy-contracts.sh
RUN /parity/parity --config /parity/config.toml \
    && /app/deploy-contracts.sh \
    && kill -TERM %1

ENTRYPOINT [ "/parity/parity", "--config", "/parity/config.toml" ]
```

I would expect fast-and-lose to generally work here because I stop Parity once cleanly after deploying contracts, then when the container is run in the future it will start from that state (with contracts deployed).  However, with fast-and-loose in `config.toml`, this doesn't actually work.

The poor naming/documentation around this feature resulted in notable engineering time spent debugging.

Side note: It would be preferable if there were a mode that actually did what this implied, and supported clean exits but made no guarantees about unclean exits.  That would allow the above use-case to actually work.

**Comment by Tbaut** [comment]
>Side note: It would be preferable if there were a mode that actually did what this implied, and supported clean exits but made no guarantees about unclean exits. That would allow the above use-case to actually work.

As said in the chat, any feature that would allow to speed-up parity while not giving any guarantee for unclean exit would be on by default. I agree that the `--help` could give an extra warning. PR welcome :)

**Comment by 5chdn** [comment]
`--fast-and-loose` does not cause any issues if you do a clean exit. But you often do not have control over how parity exits. Of course, it always tries to cleanly close the database and shut down. But what if your kids pull the power plug or your Bitcoin ransomware forces a reboot on your machine? Just try to avoid that flag. #8963

**Comment by MicahZoltu** [comment]
> `--fast-and-loose` does not cause any issues if you do a clean exit.

This does not appear to be true and is the source of all of this confusion.  If you clean exit (e.g., SIGINT or SIGTERM) Parity will drop the DB if using `--fast-and-loose`.  It appears `--fast-and-loose` doesn't actually write anything to disk or something.

I'm totally fine with `--fast-and-loose` corrupting the database on the way out during a power failure or SIGKILL.  My expectation (as a user) though was that  SIGINT/SIGTERM would result in the DB correctly closing down and no data loss.
