### ISSUE TITLE
RETURNDATACOPY op bounds

### ISSUE THREAD

**Issue by ayrat555** [paritytech/parity#8781]
![img](https://i.imgur.com/fiGe0OQ.png)
I think `RETURNDATACOPY` shouldn't return an error if current index is bigger than output data size. it should fill those indices with zeros.

https://github.com/paritytech/parity/blob/98b7c07171cd320f32877dfa5aa528f585dc9a72/ethcore/evm/src/interpreter/mod.rs#L576

```rust
	instructions::RETURNDATACOPY => {
	{
		let source_offset = stack.peek(1);
		let size = stack.peek(2);
		let return_data_len = U256::from(self.return_data.len());
		if source_offset.saturating_add(*size) > return_data_len {
			return Err(vm::Error::OutOfBounds);
		}
	}
	Self::copy_data_to_memory(&mut self.mem, stack, &*self.return_data);
}
```

**Comment by holiman** [comment]
If I understand the question above correctly, it is as it should be. 

https://eips.ethereum.org/EIPS/eip-211

> This opcode has similar semantics to CALLDATACOPY, but instead of copying data from the call data, it copies data from the return data buffer. Furthermore, accessing the return data buffer beyond its size results in a failure; i.e. if start + length overflows or results in a value larger than RETURNDATASIZE, the current call stops in an out-of-gas condition. In particular, reading 0 bytes from the end of the buffer will read 0 bytes; reading 0 bytes from one-byte out of the buffer causes an exception.
