### ISSUE TITLE
JSON RPC eth_getBlockByNumber slow on local machine (1-2 req/s)

### ISSUE THREAD

**Issue by kchernyshev** [paritytech/parity#8789]
> I'm running:
>
> - **Which Parity version?**: v1.10.4-stable-39b9f1e25-20180514/x86_64-windows-msvc/rustc1.25.0
parity.exe --cache-size 5000 --fast-and-loose --mode offline

> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

So querying an offline local node seems ridiculously slow (it's 2018 after all), I expected that requests to a simple key-value storage would be executed much faster.

**Comment by menxit** [comment]
Are you using tcp? Try to use udp in order to avoid the overhead of communication:

```js
const Web3 = require('web3')
const web3 = new Web3('ws://localhost:8546')

const printBlock = async (i) => {
  const block await web3.eth.getBlock(i)
  console.log(block)
}

printBlock(100)
```

**Comment by Tbaut** [comment]
Please test with the above code and give us some more info on how you do your queries.
