### ISSUE TITLE
same nonce when I use eth_sendRawTransaction twice ...

### ISSUE THREAD

**Issue by JokerCatz** [paritytech/parity#8797]
Parity v1.9.6 / Ubuntu / docker , I know this is old version ... I did not try this to new version

I sign a transaction by myself use low gas_price , broadcast it use `eth_sendRawTransaction` at mainchain & I use `eth_getTransactionCount 0xWALLET pending` to get pending nonce to sign

after half hour or more , I sign same transaction again , same from wallet / to wallet / gas limit , but more gas price , but the `eth_getTransactionCount 0xWALLET pending` give me same value , so my second transaction is overwrite first transaction ...

so how to avoid this ? , the `eth_getTransactionCount 0xWALLET pending` will give me pending nonce right ? or just tx-queue is timeout ? or how to add the limit to wait it join the mainchain?

I try to add 

    --tx-queue-mem-limit=0
    --tx-queue-size=65535
    
is this helpful ? or I need move to new version ?

**Comment by Tbaut** [comment]
This is not really related to parity, or to your version. What you should probably use is [`parity_nextnonce`](https://wiki.parity.io/JSONRPC-parity-module#parity_nextnonce) or keep the nonce in a local variable and iterate it for each transaction. Your 2nd transaction will need to wait for the first to be mined if the nonce is higher than the first transaction.

**Comment by JokerCatz** [comment]
okay I got it , and I search found like this

https://github.com/ethereum/go-ethereum/issues/2880

it looking good for using `parity_nextnonce` , many thanx :)
