### ISSUE TITLE
Is parity node backwards compatible with the go-ethereum golang APIs?

### ISSUE THREAD

**Issue by postables** [paritytech/parity#8811]
Getting tired of dealing with geth node issues and have been considering switching to parity. However my main concern is incompatabilities with the go-ethereum golang API. Is there full compatability, if not what works and doesn't work?

**Comment by folsen** [comment]
All the standardised APIs (e.g. those under the `eth_*` namespace, should all be identical, if they aren't it's a bug that you can report here).

Parity has some stuff under the `parity_*` namespace just like geth has some of their own stuff too. Ideally you should be able to build your dapps such that they only use standardised APIs.
