### ISSUE TITLE
TxQueue viewer says "mined" while getTransactionReceipt shows status false

### ISSUE THREAD

**Issue by pangwa** [paritytech/parity#8827]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.12.0-unstable-3d7641735-20180602/x86_64-macos/rustc1.26.1
> - **Which operating system?**:  MacOS 
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private poa
> - **Did you try to restart the node?**: yes

I'm following the demo poa chain tutorial(https://wiki.parity.io/Demo-PoA-tutorial) to setup a private poa chain.  The transactions stays local in the mined status. 
Also the status of the transaction stays false using web3 api: web3.eth.getTransactionReceipt(transId).then(ret => console.log(ret))

**Comment by AyushyaChitransh** [comment]
@pangwa The issue you are facing because byzantium features were not enabled in your network. They can be enabled by setting EIP658transition in the genesis file.

**Comment by Tbaut** [comment]
I had the problem on kovan I think a couple days ago. I'll try to reproduce and share a script soon.

**Comment by pangwa** [comment]
@AyushyaChitransh confirmed, Adding eip658 config resolved this issue.
now my demo-spec.json looks like below:
`
{
    "name": "DemoPoA",
    "engine": {
        "authorityRound": {
            "params": {
                "stepDuration": "5",
                "validators": {
                    "list": [
                        "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e",
                        "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
                    ]
                }
            }
        }
    },
    "params": {
        "gasLimitBoundDivisor": "0x400",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "eip161dTransition": "0x0",
        "eip649Reward": "0x29A2241AF62C0000",
        "eip100bTransition": "0x0",
        "eip649Transition": "0x0",
        "eip658Transition": 0,
        "networkID": "0x2323"
    },
    "genesis": {
        "seal": {
            "authorityRound": {
                "step": "0x0",
                "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x20000",
        "gasLimit": "0x5B8D80"
    },
    "accounts": {
        "0x0000000000000000000000000000000000000001": {
            "balance": "1",
            "builtin": {
                "name": "ecrecover",
                "pricing": {
                    "linear": {
                        "base": 3000,
                        "word": 0
                    }
                }
            }
        },
        "0x0000000000000000000000000000000000000002": {
            "balance": "1",
            "builtin": {
                "name": "sha256",
                "pricing": {
                    "linear": {
                        "base": 60,
                        "word": 12
                    }
                }
            }
        },
        "0x0000000000000000000000000000000000000003": {
            "balance": "1",
            "builtin": {
                "name": "ripemd160",
                "pricing": {
                    "linear": {
                        "base": 600,
                        "word": 120
                    }
                }
            }
        },
        "0x0000000000000000000000000000000000000004": {
            "balance": "1",
            "builtin": {
                "name": "identity",
                "pricing": {
                    "linear": {
                        "base": 15,
                        "word": 3
                    }
                }
            }
        },
        "0x004ec07d2329997267Ec62b4166639513386F32E": {
            "balance": "10000000000000000000000"
        }
    }
}
`
