### ISSUE TITLE
parity hung after startup - extra parity process running in io.parity.ethereum-updates

### ISSUE THREAD

**Issue by wallaceturner** [paritytech/parity#8833]
> I'm running:
>
> - **Which Parity version?**: version Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1
> - **Which operating system?**:  Linux
> - **How installed?**: sudo dpkg -i parity_1.11.3_ubuntu_amd64.deb
> - **Are you fully synchronized?**: was prior to restart
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: es

I restarted parity and the log stops at

> 2018-06-07 02:53:54  State DB configuration: fast
> 2018-06-07 02:53:54  Operating mode: active
> 2018-06-07 02:53:54  Configured for Foundation using Ethash engine
> 2018-06-07 02:53:54  Updated conversion rate to Î1 = US$605.56 (7863638 wei/gas)

After this point no more log output is produced however the CPU usage as reported by `top` is very high. The CPU usage is not being used by `parity` but rather by `io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d`

That is, there is an extra parity process that i have not noticed before
`/home/me/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d`

What is going on?

**Comment by jasonOramo** [comment]
Same things is happened for me. The cpu is quite high (more than 60%)

**Comment by niklasad1** [comment]
@wallaceturner @jasonOramo 

This actually intended behaviour your `parity clients` have been updated and executes the new version in a separate process which is `io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8`in your case.

The `orignal parity process` is just `idle` and is waiting for in case `parity` actually needs to restarted and so on. 

Is `parity` using significantly more CPU after the update?

**Comment by wallaceturner** [comment]
Can you say why this has closed?
This has happened to me again. What is happening is my hosting provider shutdowns my VM due to high CPU... after I reboot it and start parity, parity is hung

```

2018-07-04 08:50:46  Configured for Foundation using Ethash engine
2018-07-04 08:50:47  Updated conversion rate to Î1 = US$468.77 (10158297 wei/gas)
2018-07-05 09:15:29  Starting Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1
2018-07-05 09:15:29  Keys path /home/troy/.local/share/io.parity.ethereum/keys/Foundation
2018-07-05 09:15:29  DB path /home/troy/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-07-05 09:15:29  Path to dapps /home/troy/.local/share/io.parity.ethereum/dapps
2018-07-05 09:15:29  State DB configuration: fast
2018-07-05 09:15:29  Operating mode: active
2018-07-05 09:15:29  Configured for Foundation using Ethash engine
2018-07-05 09:15:30  Updated conversion rate to Î1 = US$474.39 (10037953 wei/gas)
```

So after at least 24hrs... nothing more has been written to the logfile but parity continues to use a huge amount of memory and CPU - its clearly doing something but nothing more has been written to the log file. What else can i do? i dont want to re-sync the node i would like to get to the bottom of this
Is there any other log file I can look at?

**Comment by Tbaut** [comment]
Make sure you kill every parity process. 
Make sure to install the latest parity available: https://github.com/paritytech/parity/releases and launch it again. You will surely not need to resync.

**Comment by wallaceturner** [comment]
I was already using the latest - in fact i downgraded to latest stable (v1.10.8)... and its still stuck doing something (24hrs+)
nothing additional in log file, last line is as before:
```2018-07-06 07:54:25  Starting Parity/v1.10.8-stable-bd20c45-20180628/x86_64-linux-gnu/rustc1.27.0
2018-07-06 07:54:25  Keys path /home/troy/.local/share/io.parity.ethereum/keys/Foundation
2018-07-06 07:54:25  DB path /home/troy/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-07-06 07:54:25  Path to dapps /home/troy/.local/share/io.parity.ethereum/dapps
2018-07-06 07:54:25  State DB configuration: fast
2018-07-06 07:54:25  Operating mode: active
2018-07-06 07:54:25  Configured for Foundation using Ethash engine
2018-07-06 07:54:26  Updated conversion rate to Î1 = US$462.82 (10288891 wei/gas)
```

**Comment by wallaceturner** [comment]
it is not technically 'hung' - i'm just trying to describe what is happening... the process starts and logs to the file then starts showing cpu/ram usage so its doing something - however it never logs anything additional NOR does the RPC/API server start listening (Yes i am running it with the correct args to do this)
I can simply 'fix' this by re-syncing the entire node but this takes days and days and this has occurred prior and would think it would be a good one to find and fix

**Comment by Tbaut** [comment]
How do you launch parity?

>I can simply 'fix' this by re-syncing the entire node

As long as we don't know what is happening, it's not clear whether a resync would fix it. To test it without deleting the whole db, you can try to launch it with `-base-path ./whatever_directory` so that it starts from scratch without deleting the original DB.

**Comment by wallaceturner** [comment]
Heres how i start parity
```
parity --peers=200 --jsonrpc-interface all --ws-interface all --jsonrpc-cors=all -l info --log-file parity.log
```

after 4 days parity is still running but the JSON/RPC/WS interfaces are still not listening.
what other log files can i check to see what its doing ?

**Comment by wallaceturner** [comment]
Ok I am running it now with `-l=debug`
The following is *an example* of what is appearing in the log. There are many many more rows like this (it is continually doing this)
```2018-07-08 21:47:01  main DEBUG miner  Skipping adding transaction to block because of gas limit: eb5492090489001a577b5b824824bb9f771bc01f3990815f7adc0824de7ddf7b (limit: 7992222, used: 7889415, gas: 210000)
2018-07-08 21:47:01  main DEBUG miner  Skipping adding transaction to block because of gas limit: 7a867877ed55bbccbd2fca98246d50c8b6ddb6f648469fa55e0c788cfbc58798 (limit: 7992222, used: 7889415, gas: 210000)
```

sometimes after many rows it will output this:
```2018-07-08 21:47:02  main DEBUG txqueue  Imported transaction to current: 895ce3973769ef3200efb089b0319c5442f04677681be935e184faddd9eaa280
2018-07-08 21:47:02  main DEBUG txqueue  status: TransactionQueueStatus { pending: 658, future: 0 }
2018-07-08 21:47:02  main DEBUG own_tx  Imported to Current (hash 895ce3973769ef3200efb089b0319c5442f04677681be935e184faddd9eaa280)
```

then it will resume with
```
2018-07-08 21:47:02  main DEBUG miner  Skipping adding transaction to block because of gas limit: dd2443a011933cdf5d08b647dfab100b3473f0c04c0867d8c12e43b758a16413 (limit: 7992222, used: 7889415, gas: 210000)
2018-07-08 21:47:02  main DEBUG miner  Skipping adding transaction to block because of gas limit: 5256751a6a2940903805829ab20f31d2eddf68ec2f7da99520419d148530505d (limit: 7992222, used: 7889415, gas: 210000)
...
```

please note, rpc interfaces never come up (ports 8545/6)

**Comment by Tbaut** [comment]
These errors don't seem related to your problem.
Could you post the beginning of the log file (the best is to put it in a gist)? What happens after startup is important.

**Comment by wallaceturner** [comment]
yes ok, here is [the gist][1]

the command to start parity was
```
parity --peers=200 --jsonrpc-interface all --ws-interface all --jsonrpc-cors=all -l=debug --log-file=parity.log &
```

[1]: https://gist.githubusercontent.com/wallaceturner/baef13088de2a5c5afbfdd9a008dee2e/raw/968917770cd6c60fdf966d9506301d0dccfd4236/gistfile1.txt

**Comment by wallaceturner** [comment]
@Tbaut 
the RPC/JSON interface never boots up - that to me sounds like a clue. is there something i can investigate my side? I can install a special build if you have one available to further track down the issue

**Comment by Tbaut** [comment]
Did you try as I recommended with `--base-path ./whatever_directory`. This will simulate a new sync (in the new directory).

**Comment by wallaceturner** [comment]
@Tbaut  Yes it worked but it just started syncing the entire chain again from scratch

**Comment by Tbaut** [comment]
That was the goal. Ok then it's most probably a problem with your DB and a resync is inevitable. It takes a couple hours with warp sync so I think that's your best bet.

**Comment by wallaceturner** [comment]
I don't think its right to close this. Invariably someone else is going to run into this issue again (likely me) - requiring an entire re-sync (especially on a production environment) is not an acceptable long term solution.

**Comment by Tbaut** [comment]
A DB corruption can have a lot of sources that are most of the time this is due to a HW problem. This is just closed as we will not investigate it in the near future. Be sure that it can be reopened should it happen again.

**Comment by wallaceturner** [comment]
ok its happened again - this time without a parity crash (i stopped it cleanly)
its exactly same problem as before... looks to start up correctly however the logging never 'makes' it to the final stage, that is the part where it says '
```
2018-07-20 02:11:27  Updated conversion rate to Î1 = US$458.46 (10386740 wei/gas)
```
but its missing the usual next line in the log
```
  Public node URL: enode://
```



is there something I can do?

**Comment by Tbaut** [comment]
Can you confirm it's from a freshly synced node? Did you reproduce it on the latest stable or beta?

**Comment by MysticRyuujin** [comment]
So uh, I just experienced this issue too...

I had a fresh sync, everything was fine. Rebooted, Basically hung, no RPC available... Parity is using a lot of CPU, etc.

`Parity-Ethereum/v2.6.5-beta-753b923-20191112/x86_64-linux-gnu/rustc1.39.0`

**Comment by dvdplm** [comment]
@MysticRyuujin did your node eventually start? For configurations with a long pruning history the startup phase can take a while,  especially if running on underpowered hardware. Can you report back with your full config/cli flags, hardware/OS? And any logs you might have would be great too. Thanks!
