### ISSUE TITLE
Unable to call http://127.0.0.1:8545/api/health in dockerized parity

### ISSUE THREAD

**Issue by nlandeker** [paritytech/parity#8838]
> I'm running:
>
> - **Which Parity version?**: v1.10.6
> - **Which operating system?**: official docker image
> - **How installed?**: docker
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Parity startup config:
```
/parity/parity --chain mainnet --nat none --db-compaction ssd --cache-size 2048 --allow-ips all --min-peers 50 --max-peers 75 --max-pending-peers 64 --snapshot-peers 30 --no-dapps --no-hardware-wallets --no-secretstore --no-ipc --ui-interface local --ui-port 8180 --ui-hosts none --jsonrpc-interface all --jsonrpc-port 8545 --jsonrpc-hosts all --jsonrpc-cors "*" --ws-interface all --ws-port 8546 --ws-hosts all --ws-origins all --base-path /root/.local/share/io.parity.ethereum/
```

When calling `curl 'http://127.0.0.1:8545/api/health'` json response should be returned.

**actual**
This is the response i get with calling `curl 'http://127.0.0.1:8545/api/health'`:
Used HTTP Method is not allowed. POST or OPTIONS is required

This is the response i get with calling `curl -s -X POST http://127.0.0.1:8545`
Supplied content type is not allowed. Content-Type: application/json is required

This is the response i get with calling `curl -s -X POST -H 'Content-Type: application/json' http://127.0.0.1:8545/api/health`
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}

I can confirm that api calls work with this call:
`curl -s -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":74}' http://127.0.0.1:8545`

**expected behaviour**

Getting the JSON response with health data.

**steps to reproduce the issue**

1. pull official parity docker image
2. run with above defined parameters

**Comment by Tbaut** [comment]
Confirmed on 1.11.3 too.

**Comment by sorpaas** [comment]
`node_health` is a dapp, so it fails because of you have `--no-dapps` flag in startup. Removing that should fix your issue.
