### ISSUE TITLE
Get pending block return null.

### ISSUE THREAD

**Issue by adyshimony** [paritytech/parity#8839]
I'm running:

 Parity version 1.11.3-beta
Which operating system ubuntu
How installed bash <(curl https://get.parity.io -LK)
Are you fully synchronized? yes
Network ethereum
Did you try to restart the node? yes

Trying to get pending block, return null.
let block = await web3.eth.getBlock('pending') return null
****
Latest is working good.
let block = await web3.eth.getBlock('latest')

* same code is running good on another machine with version 1.9.3.

Thanks,

Ady.

**Comment by Njcrypto** [comment]
They changed the RPC response in 1.11.x - you have to use an earlier version if you want to continue using this functionality (still works with 1.10.6) - or use the 4th parameter from the eth_getWork response.

**Comment by adyshimony** [comment]
Why to break API? I don't get it... I need to change a lot of places in my code.
Thanks for the info, I will use getWork.

**Comment by adyshimony** [comment]
Well I don't get it, latest return the same as pending, what I am missing here?
