### ISSUE TITLE
Would you like more nodes for stats.parity.io and/or kovan-stats.parity.io

### ISSUE THREAD

**Issue by XertroV** [paritytech/parity#8840]
@secure-vote runs 3x parity archive nodes on both kovan and mainnet in 3 DCs (EU, NA, and AUS). We have them set up for our own stats dashboards atm (https://stats.eth.secure.vote and https://stats.kovan.eth.secure.vote). I'd happily add the config needed to put them on your stats pages too if you're interested.

Email if you need: max@secure.vote

**Comment by Tbaut** [comment]
Always happy to have some more nodes here. I'll email you.

**Comment by 5chdn** [comment]
Please, CC me. Do you also run Ropsten nodes?

**Comment by XertroV** [comment]
@5chdn - happy to. Yes but only 1 at the moment since we don't use the network much. It's an archive node too though. (Also run 1 classic node)

**Comment by 5chdn** [comment]
https://ropsten-stats.parity.io/ :)
