### ISSUE TITLE
Support/Question: Delete multiple signer requests pending

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#8848]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.9.x
> - **Which operating system?**: Linux
> - **How installed?**: via installer binaries
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

After a long time I logged into the Parity UI of a node on a private blockchain.  I see multiple requets to unlock the account and transfer funds.  NOTE: This is actually supposed to happen as I have a test script running that should do this.

But how would I reject all 300 requests with one command if it was not supposed to happen?  Clicking "reject" 300 times is not ideal.

Thank you.

**Comment by roninkaizen** [comment]
maybe starting parity after such an event with     
--no-persistent-txqueue
this should bring the intended solution
