### ISSUE TITLE
--help option returns 1, not 0

### ISSUE THREAD

**Issue by MarkusTeufelberger** [paritytech/parity#8851]
> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Linux
> - **How installed?**: binaries
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: none
> - **Did you try to restart the node?**: no

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Expected behavior:

`ethkeys --help` (and the other binaries too) display a help message and exist the binary with code 0.

Actual behavior:

All binaries return with 1 instead. This usually indicates some failure mode.

**Comment by gnunicorn** [comment]
Thanks for reporting, @MarkusTeufelberger.

Confirming this is happening and is not as we want it to be. Looks like we are not properly using docopts to figure out, whether we have a fatal or non-fatal exit. I have a patch for that.

@MarkusTeufelberger 
> and the other binaries too

Can you tell me which ones show that behaviour? `parity`  itself works as expected (on master). If I am submitting a patch I'd like to fix it wherever we might have that issue.

**Comment by MarkusTeufelberger** [comment]
Did you try the official binaries or are you building from master? I tried the binaries (1.10.6 as mentioned above) and all 4 had this behavior in a ubuntu:18.04 docker container from dockerhub.

**Comment by gnunicorn** [comment]
@MarkusTeufelberger yes, I am checking this against `master` -= ignoring where it has been fixed already.

I was able to confirm the bug on the CLI of whisper, ethstore and ethkey. parity and evmbin are not effected (in master). And I've send in a PR to fix them, so the behaviour should be fixed in the next release!

**Comment by MarkusTeufelberger** [comment]
Thanks! :-)
