### ISSUE TITLE
Tracing API methods not working in public mode

### ISSUE THREAD

**Issue by stevenroose** [paritytech/parity#8860]
> I'm running:
>
> - **Which Parity version?**: v1.10.6 (latest stable); also tested v1.11.3
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: yes

I restarted the node with `--tracing on`, and have `apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts", "signer", "parity_set", "secretstore"]` in my config.toml file. Here is the complete setup: https://gist.github.com/stevenroose/5e180e4b7cee9f718de659f9dc8f6929

However, none of the `trace_` methods (documented [here](https://wiki.parity.io/JSONRPC-trace-module), even though there the module is called `trace` instead of `traces`) work. These are the calls I tried:
- `trace_replayTransaction`
- `traces_replayTransaction`
- `trace_transaction`
- `traces_transaction`

All of these produce the same error:
```json
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

**Comment by stevenroose** [comment]
I just tried the same after upgrading to the beta (`version Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.1`) and I get the same results for the `trace_` calls. The `allTransactions` call works there. I'll remove it from the issue.

**Comment by stevenroose** [comment]
The reason seems to be that I had it configured as a public node.

**Comment by stevenroose** [comment]
It worked after I set `public_node = false`.

The documentation of this configuration variable, doesn't mention anything on tracing, though:
> Start Parity as a public web server. Account storage and transaction signing will be delegated to the UI.

**Comment by Tbaut** [comment]
I guess it's more a bug than a documentation problem. As `--public-node` is deprecated and will be completely removed, the documentation will follow.

**Comment by tcsiwula** [comment]
Same error on build ``` version Parity/v1.11.3-beta-a66e36b-20180605/x86_64-macos/rustc1.26.1 ```
