### ISSUE TITLE
Parity docker image  stable or latest

### ISSUE THREAD

**Issue by natamartchouk** [paritytech/parity#8865]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.6-stable or higher
> - **Which operating system?**: Linux/Ubuntu 16.04
> - **How installed?**: docker image: parity/parity:stable or parity/parity:latest
> - **Are you fully synchronized?**: no, because parity doesn't start
> - **Which network are you connected to?**: kovan
> - **Did you try to restart the node?**: yes

**Expected behavior:**
Parity docker container starts.

**Actual**
Parity docker container keeps restarting with the following failures

`/root/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /root/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d)
/root/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by /root/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d)
/root/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by /root/.local/share/io.parity.ethereum-updates/parity-1.10.6-bc0d134bb43c65a5b82bd18c311319c7036d2c8d)`

Actually mentioned libraries are installed:
`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

...
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_DEBUG_MESSAGE_LENGTH`

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI

...
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_TM_1
CXXABI_FLOAT128`

**Steps to reproduce**
Run the docker container with the  image `parity/parity:stable` or `parity/parity:latest` with  `command: --chain kovan --rpcapi "eth,net,web3,personal" --rpcaddr all --ui-interface all --ws-interface all --ws-hosts all --force-ui --unsafe-expose --allow-ips public --no-discovery` 

Temporarily we are running the parity with `--force-direct`, but it would be good to be able to run the updated version.

**Comment by interfect** [comment]
I'm having to pass `--auto-update=none` to work around this and get any version of Parity older than 1.10.6 to run. This is maybe due to the recent consensus issue and an ensuing critical update?

**Comment by 5chdn** [comment]
Yes. Please don't run any older version of Parity unless you are aware of the risks. Disabling auto-update is what you usually want in this case otherwise.

**Comment by 5chdn** [comment]
@natamartchouk I'm sorry, the latest, beta, and stable docker tags are currently broken. they will be fixed once we release a new update, this is fixed in #8822 - please hold on and check out version tags directly if possible :)

**Comment by natamartchouk** [comment]
Ok, thx, @5chdn
