### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by jrischma** [paritytech/parity#8871]
Hi, i have a problem by idiot xD

1. sudo snap install parity -> with this i install partity, but was installed a beta version
2. i remove parity with snap
3. i install parity with bash <(curl https://get.parity.io -L) -r stable

when i remove parity i lost my wallet, can i recover my wallet ? how?

thanks

**Comment by 5chdn** [comment]
You can simply restore your wallet from your backups or using the recovery phrase. You have backups, do you? :)

Snapcraft uses a different data directory I fear.
