### ISSUE TITLE
should use https for package URL in release notes

### ISSUE THREAD

**Issue by shao1555** [paritytech/parity#8874]
there are many `http` url links  download links in https://github.com/paritytech/parity/releases/tag/v1.11.3 .

e.g. `http://d1h4xl4cr1h0mo.cloudfront.net/v1.11.3/x86_64-unknown-linux-gnu/parity_1.11.3_ubuntu_amd64.deb`

to improve security, you should use `https://d1h4xl4cr1h0mo.cloudfront.net/` instead of `http://`.

**Comment by 5chdn** [comment]
Fixed, thanks!
