### ISSUE TITLE
eth_sendRawTransaction return "jsonrpc": "2.0",  "error": {   "code": -32010,   "message": "There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee."

### ISSUE THREAD

**Issue by ciphertang** [paritytech/parity#8894]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.3-beta-a66e36b-20180605/x86_64-linux-gnu/rustc1.26.1
> - **Which operating system?**:  Linux
> - **How installed?**: rpm
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes
My parity start config:
parity --no-ui --no-ws --no-warp --min-peers=25 --cache-size=4096 --jsonrpc-hosts=all --jsonrpc-port=18545 --jsonrpc-interface=0.0.0.0 --jsonrpc-cors=* --jsonrpc-server-threads=100 --jsonrpc-threads=4 --min-gas-price=1 --log-file=/opt/logs/parity/parity.log

I saw the issue have been fixed on 1.11.3 ,but I also have this problem on 1.11.3

**Comment by Tbaut** [comment]
Links to https://github.com/paritytech/parity/pull/8691
@tomusdrw can you have a look?

**Comment by tomusdrw** [comment]
@ciphertang How many transactions are you sending? Perhaps the pool is full with your own/local transactions - in such case you need to increase the pool size.
Also it seems that your node is open to the external network, perhaps others are using this to propagate their own transactions through your node, see #8820

**Comment by ciphertang** [comment]
I check the parity_localTransactions method ,there are so many Transactions. I changed the port but  it didn‘t resolve the problem. 
I reinstall the client with 1.10.6-stable,there are also many pending Transactions,but it can send Transaction normally.
How to increase the pool size?

**Comment by ciphertang** [comment]
I have setted two-way ssl (no client cert can't connect the rpc)and changed the port  ,but why can i  also see many localTransactions is pending.

**Comment by Tbaut** [comment]
This might be related to this issue: https://github.com/paritytech/parity/issues/8820
What are you currently doing with your node, is it expected to get so many local transactions?
