### ISSUE TITLE
error: Found argument '--tx-queue-per-sender' which wasn't expected, or isn't valid in this context. Did you mean --tx-queue-gas?

### ISSUE THREAD

**Issue by smashin** [paritytech/parity#8900]
Hi

> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private
> - **Did you try to restart the node?**: yes

Option error occurs when Parity starts.

**Comment by Tbaut** [comment]
This flag is only available from 1.11.X
