### ISSUE TITLE
Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData'

### ISSUE THREAD

**Issue by nafem** [paritytech/parity#8903]
> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Windows 
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

2018-06-14 17:54:44  State DB configuration: fast
2018-06-14 17:54:44  Operating mode: active
2018-06-14 17:54:44  Couldn't read disk map: invalid type: unit variant, expected struct variant at line 1 column 25
2018-06-14 17:54:44  Configured for Foundation using Ethash engine

====================

stack backtrace:
   0:     0x7ff6b8f3973c - hid_error
   1:     0x7ff6b8f38ed3 - hid_error
   2:     0x7ff6b8778b00 - <no info>
   3:     0x7ff6b9012c86 - hid_error
   4:     0x7ff6b9012a20 - hid_error
   5:     0x7ff6b9012942 - hid_error
   6:     0x7ff6b90238bd - hid_error
   7:     0x7ff6b89264f9 - <no info>
   8:     0x7ff6b8a2573a - hid_error
   9:     0x7ff6b894ec43 - <no info>
  10:     0x7ff6b893c2a0 - <no info>
  11:     0x7ff6b8212f26 - <no info>
  12:     0x7ff6b821c3eb - <no info>
  13:     0x7ff6b854d74c - <no info>
  14:     0x7ff6b85503f7 - <no info>
  15:     0x7ff6b8415b76 - <no info>
  16:     0x7ff6b901287d - hid_error
  17:     0x7ff6b901c742 - hid_error
  18:     0x7ff6b900e8c3 - hid_error
  19:     0x7ff6b855096a - <no info>
  20:     0x7ff6b93975f0 - hid_write
  21:              0x3a4 - <no info>

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', libcore\result.rs:945

**Comment by dvdplm** [comment]
Hi, that looks like a data corruption error. Can you restore a known-good DB from a backup or resync?

**Comment by nafem** [comment]
Thanks. 
Resyncing solved the issue.
