### ISSUE TITLE
eth_call some contract stuck and high CPU

### ISSUE THREAD

**Issue by cedricfung** [paritytech/parity#8904]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1
> - **Which operating system?**:  Linux
> - **How installed?**: curl
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

curl --data '{"method":"eth_call","params":[{"data":"0x95d89b41","to":"0x532975d56cf18f597480e2521246b273ad9ae348"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545

This will cause the parity CPU high and never respond. If I run this a few times, the parity won't accept any new RPC calls, I have to restart it.

**Comment by Tbaut** [comment]
I don't think that your call is valid, you should pad the function signature to the left to 32 bytes.
Could you describe which function you want to call and what parameter?

Just tested a random call:

```
curl --data '{"method":"eth_call","params":[{"data":"0xa0e67e2b0000000000000000000000000000000000000000000000000000000000000000","to":"0x71da31e0a3100f964f5bd3b498cafbf26e82e46c"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```
Result:
```
{"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000b34f87a1fda8ff1cf412acb8e8f40583968b7172000000000000000000000000dfd2418ade41eb2b9b79add7d62e6780e963b3e7000000000000000000000000fdf6ddd2585e8a9bc34cd3c02729c52126878139","id":1}
```

**Comment by cedricfung** [comment]
I try to test whether the contract will respond to some method, all other contracts work as expected only the one I posted stuck. 

I tried to pad the function signature to 32 bytes, the bug still exists.

```
curl --data '{"method":"eth_call","params":[{"data":"0x95d89b410000000000000000000000000000000000000000000000000000000000000000","to":"0x532975d56cf18f597480e2521246b273ad9ae348"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
```

**Comment by cedricfung** [comment]
The signature 95d89b41 is ERC20 symbol function, I want to know whether the contract is a valid ERC20 contract with all information. The contract which causes the bug is 0x532975d56cf18f597480e2521246b273ad9ae348

**Comment by Tbaut** [comment]
I have difficulties to follow you. There is no `ERC20 symbol function` in the [ERC20 standard](https://theethereum.wiki/w/index.php/ERC20_Token_Standard) and there is no `symbol function` in the [contract's code](https://etherscan.io/address/0x532975d56cf18f597480e2521246b273ad9ae348#code). It looks like you're trying to call a function that simply does not exist.

**Comment by cedricfung** [comment]
It's not in the standard, but it's how most ERC20 tokens are using it. Almost all ERC20 tokens have a symbol function.

Anyway, no matter what the function is, parity should not stuck and consume high CPU. Is parity expected to stuck whenever people call a function not exist in a contract? Isn't it a bug?

**Comment by Tbaut** [comment]
I agree. It's reproducible on 1.11.3 also with `curl --data '{"method":"eth_call","params":[{"data":"0x95d89b410000000000000000000000000000000000000000000000000000000000000000","to":"0x532975d56cf18f597480e2521246b273ad9ae348"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545`

**Comment by andresilva** [comment]
Can you check whether this is `parity` specific or does it also happen in `geth`? It would be easier if you could provide a smaller reproduction case (minimal set of contract functionality that triggers the issue).

**Comment by Tbaut** [comment]
@debris had ideas regarding this as it might be related to the way we call functions in the EVN with unlimited gas.

**Comment by cedricfung** [comment]
I don't have geth, but I have called this function to the etherscan API, it
works

**Comment by andresilva** [comment]
It does work on Etherscan but doesn't return the appropriate result. Just returns "0x" because the contract runs out of gas. Currently in parity we have effectively unlimited gas for local calls, so if your contract is stuck on some loop it will keep looping "forever" (or just a really long time). I've capped the gas limit to make sure this doesn't happen (#8943). In the meantime you can enforce a gas limit yourself when doing the request:

```
❯ curl --data '{"method":"eth_call","params":[{"data":"0x95d89b41","to":"0x532975d56cf18f597480e2521246b273ad9ae348","gas":"0x100000000"}],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST http://localhost:8545
{"jsonrpc":"2.0","error":{"code":-32015,"message":"VM execution error.","data":"Reverted 0x"},"id":1}
```

**Comment by cedricfung** [comment]
Yes, the gas limit fixes the problem
