### ISSUE TITLE
parity auto updater hash mismatch

### ISSUE THREAD

**Issue by S3bb1** [paritytech/parity#8921]
> I'm running:
>
> - **Which Parity version?**: 1.10.4
> - **Which operating system?**: Windows / Linux
> - **How installed?**:  binaries 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private net

We've setup the operations contract on our private net. All works fine but when we publish a new version to the operations contract, parity refuses the update due to "HashMismatch"

for example the 1.10.7 release.

used the sha256 from https://vanity-service.parity.io/parity-binaries?version=stable

executed transactions on Operations Contract:
![image](https://user-images.githubusercontent.com/763247/41588062-0217d7c8-73b1-11e8-9681-1e918830dbbd.png)
![image](https://user-images.githubusercontent.com/763247/41588063-03c0aeb0-73b1-11e8-83ae-195d8de48774.png)

executed transactions on GitHubHint Contract
![image](https://user-images.githubusercontent.com/763247/41588078-0ed6cac8-73b1-11e8-8722-e085a18ab5be.png)

partiy log:
 
> 2018-06-19 10:57:18  IO Worker #0 INFO import  Imported #35653 bb11…08e2 (1 txs, 0.07 Mgas, 79.44 ms, 0.84 KiB)
>2018-06-19 10:57:18   WARN parity_updater::updater  Unable to fetch update (1.10.7-stable-ba79…5d35): NoResolution
>2018-06-19 10:57:45  IO Worker #0 INFO import     1/25 peers      3 MiB chain   63 MiB db  0 bytes queue   10 KiB sync  RPC:  2 conn,  1 req/s,  86 µs
>2018-06-19 10:57:57   INFO own_tx  Transaction mined (hash a3b69309355fd7686f31ae0829ae359be5f778843a00033f0c92bed875e7ff92)
>2018-06-19 10:57:57   TRACE updater  Current release is 1.10.6-stable-bc0d…2c8d (bc0d134bb43c65a5b82bd18c311319c7036d2c8d)
>2018-06-19 10:57:57   TRACE updater  Looking up this_fork for our release: parity/bc0d134bb43c65a5b82bd18c311319c7036d2c8d
>2018-06-19 10:57:57   TRACE updater  Latest release in our track is v1.10.7-stable-ba79…5d35 it is critical (x86_64-pc-windows-msvc binary is c2a9…f73d)
>2018-06-19 10:57:57   INFO updater  Attempting to get parity binary c2a9…f73d
>2018-06-19 10:57:57   TRACE updater  Fork: this/current/latest/latest-known: #356010/#35654/#35622/10
>2018-06-19 10:57:57   INFO import  Imported #35654 8fa2…b627 (1 txs, 0.14 Mgas, 8.86 ms, 0.87 KiB)
>2018-06-19 10:58:07   WARN parity_updater::updater  Unable to fetch update (1.10.7-stable-ba79…5d35): HashMismatch { expected: c2a9117e477dc4e42af9b90feddc1ad5822b4e39b047eb375acb1491ebd9f73d, got: 92906a96fa7d186b36b82d912b08d794f1b1bca1fe77267fa9a110db21c9d394 }
>2018-06-19 10:58:15  IO Worker 3 INFO import     1/25 peers      3 MiB chain   63 MiB db  0 bytes queue   10 KiB sync

**Comment by andresilva** [comment]
@S3bb1 The auto-updater is expecting a SHA3 hash. Sorry for the lack of documentation, I'll work on some documentation for this soon. You can use the parity binary to do the SHA3.

```
❯ curl https://d1h4xl4cr1h0mo.cloudfront.net/stable/x86_64-pc-windows-msvc/parity.exe -o parity.exe
❯ parity tools hash parity.exe
92906a96fa7d186b36b82d912b08d794f1b1bca1fe77267fa9a110db21c9d394
```

**Comment by 5chdn** [comment]
> used the sha256 from https://vanity-service.parity.io/parity-binaries?version=stable

Note, `stable` =/= `v1.10.7`, that are (not always but often) different binaries with different code

**Comment by 5chdn** [comment]
- latest stable **release**: https://vanity-service.parity.io/parity-binaries?version=stable-release
- latest beta **release**: https://vanity-service.parity.io/parity-binaries?version=beta-release
- latest stable _branch head_: https://vanity-service.parity.io/parity-binaries?version=stable
- latest beta _branch head_: https://vanity-service.parity.io/parity-binaries?version=beta

**Comment by S3bb1** [comment]
>Note, stable =/= v1.10.7, that are (not always but often) different binaries with different code

yep recognized that. I've read the documentation here https://github.com/paritytech/push-release and there it says 
> (the build binary's Keccak-256 hash, 64-character hex) 
on the parameter for the checksum

thx for figuring it out!
