### ISSUE TITLE
parity cannot transfer local transaction

### ISSUE THREAD

**Issue by sunrye** [paritytech/parity#8922]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

It's very strange,our parity node can't transfer local transactions, but it can sync blocks and it can also receive transactions generated by other nodes

**Comment by Tbaut** [comment]
Please update your issue with:

```
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes
```

as well as a clear description of what you do to send transactions, how do you do it, using the UI, RPC, what methods? what error message?
