### ISSUE TITLE
Please unregister MyB token

### ISSUE THREAD

**Issue by jjperezaguinaga** [paritytech/parity#8945]
👋 hi! We did a token swap a few weeks ago, and now our MyB token is officially MYB token 🎉 

We are about to finish registering our token into your registry, so now we kindly ask you to remove our old one to avoid any confusions.

Old rusty MyB token - https://etherscan.io/address/0x94298f1e0ab2dfad6eeffb1426846a3c29d98090
New shinny MYB token - https://etherscan.io/address/0x5d60d8d7ef6d37e16ebabc324de3be57f135e0bc

We verified our token swap online - https://twitter.com/MyBit_DApp/status/993879392433602560.

Thank you! 🙏

**Comment by kyledewy** [comment]
Hey @Tbaut, unless I'm missing something it seems the unregister function has an onlyOwner modifier instead of an onlyTokenOwner modifier. 

```
function unregister(uint _id)
		external
		whenToken(_id)
		onlyOwner
	{
		emit Unregistered(tokens[_id].tla, _id);
		delete mapFromAddress[tokens[_id].addr];
		delete mapFromTLA[tokens[_id].tla];
		tokens[_id].deleted = true;
		tokenCount = tokenCount - 1;
	}
```


```
	modifier onlyOwner {
		require(msg.sender == owner);
		_;
	}
```

```
	modifier onlyTokenOwner(uint _id) {
		if (tokens[_id].owner != msg.sender)
			return;
		_;
	}
```

**Comment by 5chdn** [comment]
Yeah, unfortunately the owner can not unregister it.

**Comment by jjperezaguinaga** [comment]
@5chdn thanks for reopening the issue. Unfortunately we can’t register the new contract until the old one is removed. We appreciate your support!

**Comment by 5chdn** [comment]
Removed it. Sorry for the Delay. https://etherscan.io/tx/0x720d7f487239a9f59d44d18047a3d156175a0d36b909f24fa29a5b344b230398

**Comment by jjperezaguinaga** [comment]
@5chdn thank you!
