### ISSUE TITLE
Slow performance POA

### ISSUE THREAD

**Issue by artjoma** [paritytech/parity#8960]
Parity:

        Which Parity version?: 1.10.7
        Which operating system?: Ubuntu server 16.04
        How installed?: via installer
        Which network are you connected to?: private POA.
        Did you try to restart the node?: yes

Hi folks ! I have a question about tuning and optimization Parity settings for POA network with block every 4sec. My network has 3 simple Parties and 3 validators. All machines work on AWS boxes. Every machine has 8G RAM, 4cores, 1T SSD.  My load test generates txs, sign and publish (40 green threads) to Parity. Tx invokes a function in smartcontract: generate 4 money transfers and 4 events. Throughput is ~110tx per block with 300-500txs, CPU used 20-30%. Sometimes I see blocks with 900 - 1200txs per block(how ?). When test stop publish txs, Parity 20-30seconds process txs from personal queue and blocks has 100-200txs or 50txs. My question is: how to configure a Parity to process more txs without buffering in the queue. Cheers!

Parity settings:
parity -d /opt/parity/test -c /opt/parity/test/config.toml --logging info --db-compaction ssd --tracing off --gasprice 1000 --gas-floor-target 100000000000 --pruning fast --tx-queue-size 32768 --tx-queue-mem-limit 0 --no-warp --jsonrpc-threads 8 --no-hardware-wallets --no-dapps --no-secretstore-http --cache-size 4096 --scale-verifiers --num-verifiers 16

**Comment by 5chdn** [comment]
1. What's your actual block gas limit? What's your gasLimit in Genesis? Try starting with a high value, as Parity can only increase it by +1/1024 each block towards the desired gas-floor-target.
2. Reduce the bock time. Try 2 seconds.

**Comment by artjoma** [comment]
Block with 501txs
gasLimit: 100000000000
gasUsed: 56866112
size: 122549

**Comment by 5chdn** [comment]
Interesting. At what rate are you generating the transactions? How many per second?

Are there any obvious network bottlenecks between the nodes?

**Comment by artjoma** [comment]
Test generate ~210tx/s. No, any network issues found. All peers located in same DC.

**Comment by artjoma** [comment]
Any suggestions?

**Comment by 5chdn** [comment]
I don't see what's the question here. If you want more transactions per second you should generate more. It does not look like your blocks are full yet.

**Comment by artjoma** [comment]
But Parity buffer txs, doesn't include to block. I can generate 800tx/s but the picture will be the same. Only growing an internal Parity pending txs queue but not a block gasUsed (txs count).
