### ISSUE TITLE
g55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555hhhhhhhh

### ISSUE THREAD

**Issue by cle1000** [paritytech/parity#8966]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Windows / MacOS / Linux
> - **How installed?**: via installer / homebrew / binaries / from source
> - **Are you fully synchronized?**: no / yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: no / yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by cle1000** [comment]
Sorry for the invalid issue. But actually it was not my fault

![cat](https://user-images.githubusercontent.com/5902525/41821424-e6953390-77e0-11e8-9240-c3c17b17944b.jpg)

**Comment by 5chdn** [comment]
Amazing. :cat2:

**Comment by roninkaizen** [comment]
this is very
new - 
cak (cat.at.keyboard) .cak -
nicest picture of an issuer ever seen although the topic 
could have been --miaow=1 --cak= 1
