### ISSUE TITLE
(parity-ui:1693): Gtk-WARNING **: cannot open display:

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#8971]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity UI (also confusingly called Parity-JS): Parity UI v0.1.4-stable
> - **Which operating system?**: Debian
> - **How installed?**: via .deb
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

1. Install Parity-UI

2. type "sudo apt-get -f install" to install dependencies

3. type "sudo apt-get install libasound2" because that is not included somehow

4. type "parity-ui" as root or as parity user

Result:

`(parity-ui:1693): Gtk-WARNING **: cannot open display:`

Preferred Result:

Parity UI should say "Running" or something and I can then go to localhost:8108 and see the familiar Parity UI.

If there are other libraries I should install or if there is another command to use then please add it to the documentation (https://wiki.parity.io/Parity-Wallet) or explain to me and I will add it to the documentation if that is easier in some way?

**Comment by 5chdn** [comment]
Please report this in the UI repository https://github.com/Parity-JS/shell/issues

**Comment by stone212** [comment]
@5chdn Done.  I did look for a parity-UI project under paritytech.  It is confusing that the Parity-JS project is not under paritytech and also that Parity-JS is the term for Parity UI.  That's two related organizational bugs.
