### ISSUE TITLE
parity crash 

### ISSUE THREAD

**Issue by wcw84** [paritytech/parity#8982]
My parity node crashed, and after restart, it run normally. 

Parity
  version Parity/v1.10.6-stable-bc0d134-20180605/x86_64-linux-gnu/rustc1.26.1

crash Log:
![image](https://user-images.githubusercontent.com/7152596/41893629-01b5d8cc-794f-11e8-8d27-b8df1c9511c3.png)

**Comment by Tbaut** [comment]
Thanks for reporting the issue. This is probably due to a disk/RAM error.
We can reopen if this happens too often.
