### ISSUE TITLE
Kovan only 3 peers

### ISSUE THREAD

**Issue by adyshimony** [paritytech/parity#8987]
I'm running v1.9.3-beta on unbuntu 16.04, not synced yet, chain - kovan, restarted node.

I am getting only 3 peers on kovan, is that normal?

* nodes.json deleted and node restarted didn't help.

Thanks,
Ady.

**Comment by adyshimony** [comment]
Now I have 0 peers. Again, deleting nodes.json is not helping.

**Comment by 5chdn** [comment]
I have good news for you! Just upgrade your client to 1.10.7 or 1.11.4 and all your issues are belong to history!

**Comment by adyshimony** [comment]
v1.11.3-beta solved it, thanks

**Comment by adyshimony** [comment]
v1.11.3-beta working great, I have now 25/25 peers.
