### ISSUE TITLE
Syncing slow and overload disk

### ISSUE THREAD

**Issue by Vagabondtq** [paritytech/parity#8988]
> I'm running:
> 
> - **Which Parity version?**: v1.10.7-stable-ba79cad-20180619/x86_64-linux-gnu/rustc1.26.2
> - **Which operating system?** Linux: Centos 7
> - **How installed?**: from source
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

My parity config

> db_compaction = "ssd"
> pruning = "archive"
> fat_db = "off"
> cache_size = 4096

Computer uptime more than 5 days, and i get: **4.731.002** blocks and disk is: **452G/500Gb SDD**
now, syncing very slow and disk is full. Where did I go wrong? eth blocks occupy more drive space.
When disk full 500Gb, what should I do?

Please help me

**Comment by 5chdn** [comment]
Please enable `pruning = "fast"`. An archive node requires more than 1 TB disk space.

**Comment by ordian** [comment]
https://wiki.parity.io/FAQ#what-are-the-parity-disk-space-needs-and-overall-hardware-requirements
