### ISSUE TITLE
Question: How is parity calculating web3.eth.getGasPrice()

### ISSUE THREAD

**Issue by amexperts** [paritytech/parity#8989]
At the moment when I check it is always a lot higher than other places (ethgasstattion, ethstats etc).
I am using this to determine what gasprice to send transactions.. however, it seems this is making us pay a lot more than we need to.. parity reports 20 - others only 4 or 5.

**Comment by Tbaut** [comment]
The gas price is determined by the last few blocks median gas. Other platforms have other ways to do. Feel free to change your logic and take less, or half of it. It might be spot on for some time, and far off some other times.

**Comment by 5chdn** [comment]
See also https://wiki.parity.io/JSONRPC-parity-module#parity_gaspricehistogram
