### ISSUE TITLE
Log explanation

### ISSUE THREAD

**Issue by wnz99** [paritytech/parity#8990]
Hi,
I have searched on this GitHub and on the documentation but could not find a definitive answer.

Could anyone please explain the precise menaining of each columns in the logs?

For example:

> 2018-06-27 07:25:43 UTC Syncing #3807132 0xcbb2…69e5     0 blk/s   43 tx/s   1 Mgas/s      0+ 5245 Qed  #3812381   71/100 peers      2 MiB chain    1 MiB db  163 MiB queue    9 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
> 2018-06-27 07:25:53 UTC Syncing #3807148 0x642a…36a6     1 blk/s   62 tx/s   2 Mgas/s      0+ 5229 Qed  #3812381   74/100 peers      3 MiB chain    2 MiB db  162 MiB queue    9 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
> 2018-06-27 07:26:03 UTC Syncing #3807169 0x2d58…5678     2 blk/s   47 tx/s   2 Mgas/s      0+ 5209 Qed  #3812381   74/100 peers      4 MiB chain    2 MiB db  162 MiB queue    9 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
> 2018-06-27 07:26:13 UTC Syncing #3807186 0xec8a…ca4b     1 blk/s   66 tx/s   3 Mgas/s      0+ 5193 Qed  #3812381   74/100 peers      5 MiB chain    2 MiB db  161 MiB queue    9 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
> 2018-06-27 07:26:23 UTC Syncing #3807211 0x1ca2…fc78     2 blk/s   62 tx/s   3 Mgas/s      0+ 5169 Qed  #3812381   76/100 peers      8 MiB chain    2 MiB db  161 MiB queue    9 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

I would like to write a small bash script to monitor Parity, I/O on disks and related stats.

Thank you.

**Comment by 5chdn** [comment]
https://ethereum.stackexchange.com/questions/10491/what-does-parity-logs-means :)

**Comment by wnz99** [comment]
Thank you, I googled for the wrong terms I suppose. May I suggest to add this information to Parity wiki? I also had look in there and could not find anything.

**Comment by ordian** [comment]
https://wiki.parity.io/FAQ#what-does-paritys-command-line-output-mean

**Comment by wnz99** [comment]
great, so I missed that one too.... thanks.
