### ISSUE TITLE
How should I synchronize Ethereum and RDB?

### ISSUE THREAD

**Issue by usd-yamazaki** [paritytech/parity#8992]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.5-stable-ff821da-20180321/x86_64-linux-gnu/rustc1.24.1
> - **Which operating system?**: Ubuntu 16.04.2 LTS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private PoA (Aura)
> - **Did you try to restart the node?**: yes

I recorded events that occurred on Smart Contract in RDB,
I want to make it searchable by SQL from another system.

If you record events that occurred on that day once a day in a batch program,
It is necessary to deal with deletion of events by reorg that occurred since the last process,
It seems that there is no function to detect reorg that occurred in the past.

How should I synchronize Ethereum and RDB?

**Comment by 5chdn** [comment]
Just don't log any events until a block has 32 confirmations. Long reorgs are very unlikely. Be creative. :)
