### ISSUE TITLE
web3.js:1 WebSocket connection to 'ws://localhost:8546/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by amexperts** [paritytech/parity#8993]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

I am writing a frontend to interact with the node. But am getting the error above. This is only seen in the browser console. and the odd thing is, that on the same server - I am connecting fine with pretty much the same credentials... so something is not letting the browser talk to websocket.

browser code: (fails)
`const web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8546'));`

I have started parity with:
`parity --datadir /mnt/ethereum/parity --min-peers 50 --db-compaction ssd --cache 4096 --port 3132 --jsonrpc-port 8548 --jsonrpc-apis safe --ws-interface all --ws-origins all --ws-hosts all`

**Comment by Tbaut** [comment]
That's probably a cors problem `--jsonrpc-cors all` should let you do what you want. It's not secure to let "all", Please make sure to specify your domain later on.
