### ISSUE TITLE
Can not transfer my ERC20 Tokens?! | Tokens.net (DTR)

### ISSUE THREAD

**Issue by janincenio** [paritytech/parity#8997]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.2
> - **Which operating system?**: MacOS
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Dear Parity-Team,

I can not transfer my DTR Tokens from my parity Wallet. I have tried it through regular Transaction (->Accounts->Transfer) and via Contracts (->Execute->transfer(_to: address, _value: uint256)).
When I check the Query, Parity shows me the right balance, however I can not select anything but ETH (Etherium) within the transfer formular. 

I would be happy if someone could help out - Appreciate it

**Comment by Tbaut** [comment]
Can you please upgrade to [the latest release](https://github.com/paritytech/parity/releases). There is a change since v1.10 regarding the UI. Have a look here to see how to download and use Parity UI: https://wiki.parity.io/Parity-Wallet

**Comment by janincenio** [comment]
Hey Tbaut, thanks for the quick response. I have downloaded the latest v.11.4 with the UI, but nothing has changed. Still displayed in ETH, I still see no possibility to send DTR Tokens.

**Comment by 5chdn** [comment]
> Are you fully synchronized?: no

Please, synchronize your client first. Once done, you will be able to transfer your tokens.
