### ISSUE TITLE
Proposal, distributed snapshotdb making.

### ISSUE THREAD

**Issue by trustfarm-dev** [paritytech/parity#9034]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**:  1.xx.xxx ~ latest
> - **Which operating system?**: All Platform
> - **How installed?**: Release binary and self-compiled all. 
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**actual**
When node try to warp sync , snapshotdb will be fetched by anonymous peer node, which have it generated snapshotdb.

In snapshotdb holder node, will have a very little node. so, if ethereum accounts (current approximately over 30M) , in Fast SSD with High Performance Server needs to 1.5 ~ 2days when generating snapshotdb.

if snapshotdb generating node restart node , snapshot generating job is canceled.
And, many peer (selfish/unstable/notcontinious) doesn't  want to generate snapshotdb for warp.

So, if time goes , very little snapshotdb holders exists. then, Very Hard to warp sync on newer parity node.

**suggestion** 
For solve this kind of things, make partial deterministic generating snapshotdb on peer.
snapshotdb is fragemented with node.

   -  examples.   
      - one node only generate snapshotdb to 0~500K accounts, 
      - theother node only generate snapshotdb to 500K~1M accounts, 
      - and next node only generate snapshotdb to 1M ~ 1.5M accounts, 
      - ...
        it is randomly started offset with peer's enode checksum + blocknumber + time.
    and snapshotdb holder marking it's number.

<br>
    newly starting peer node will get number and peernodes, and fetch snapshot db. and gathering.

It will helpful, shorterm  , generation and distribution snapshotdb owning peers.

**reference materials**
I've did state export, it will do with offset based. for continuous jobs.
[reference commits](https://github.com/trustfarm/rteo/commit/7c9e640b00dc814057994ce37c9c29ef9fa88f14)

**Comment by Tbaut** [comment]
Would you mind participating in this discussion as it's very much related: https://github.com/paritytech/parity/issues/8565 ?
