### ISSUE TITLE
trace_transaction not producing the right gas used 

### ISSUE THREAD

**Issue by shihao-guo** [paritytech/parity#9039]
> I'm running:
>
> - **Which Parity version?**: 1.10.6
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: no 

When I run the `trace_transaction` module through RPC in parity like this
`curl --data '{"method":"trace_transaction","params":["0x9040e7355b4b9237c114c748702285bc79260463dd72042a23a14c2d751d172f"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`

I get the following result 
```
{
    "jsonrpc": "2.0",
    "result": [{
        "action": {
            "callType": "call",
            "from": "0xda92c68565b6f8b4ee5ce619fabd880f6e485604",
            "gas": "0x10d88",
            "input": "0x",
            "to": "0x4651e15e902c54f1d4ef6dcf354a7c485a03658e",
            "value": "0xc3663566a58000"
        },
        "blockHash": "0xf3b124f68d65172f34c7e43219c36be0958066b1248542a442ea54718f0d9e83",
        "blockNumber": 5901388,
        "result": {
            "gasUsed": "0x0",
            "output": "0x"
        },
        "subtraces": 0,
        "traceAddress": [],
        "transactionHash": "0x9040e7355b4b9237c114c748702285bc79260463dd72042a23a14c2d751d172f",
        "transactionPosition": 0,
        "type": "call"
    }],
    "id": 1
}
```

The `gas` field in `action` is 69000, while `gasUsed` in `result` section is 0. I'm not sure if this is the expected behavior because on etherscan it says `gasLimit` is 90000 and `gas used` is 21000

You can see the transaction here https://etherscan.io/tx/0x9040e7355b4b9237c114c748702285bc79260463dd72042a23a14c2d751d172f and trace in a block explorer with the same issue here https://www.etherchain.org/tx/9040e7355b4b9237c114c748702285bc79260463dd72042a23a14c2d751d172f/parityTrace

**Comment by Tbaut** [comment]
This is indeed the expected behavior. Any transaction will use min 21000 gas. Depending on the input of the Tx and the function called (for smart contract calls), gas will be consumed. 
You submitted 90000, used 21000 for the Tx (implicit), and not contract was called (with no input), so 0 was used.

More info on how things works in this nice answer: https://ethereum.stackexchange.com/questions/31443/what-do-the-response-values-of-a-parity-trace-transaction-call-actually-repres

**Comment by shihao-guo** [comment]
Thanks! it was very helpful
