### ISSUE TITLE
How to permanently unlock geth accounts?

### ISSUE THREAD

**Issue by Logeshwaran21** [paritytech/parity#9067]
> I'm running:
>
> - **Which Parity version?**: v1.11.3
> - **Which operating system?**: Linux
> - **How installed?**: via from source
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**:  ropsten 
> - **Did you try to restart the node?**:  yes

**Comment by Tbaut** [comment]
Are you using `--geth` flag?
you can unlock accounts with a *.toml or the `--unlock`. More info https://wiki.parity.io/Configuring-Parity
