### ISSUE TITLE
[Aura] Transactions from non-sealing nodes don't get confirmed

### ISSUE THREAD

**Issue by MaxXor** [paritytech/parity#9068]
> I'm running:
>
> - **Which Parity version?**: v1.11.5-beta
> - **Which operating system?**: Linux
> - **How installed?**: docker
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: private aura network
> - **Did you try to restart the node?**:yes

I deployed a small contract in a private PoA aura network and try to execute a function of the contract. However the transaction I've submitted keeps pending forever. Below you can find the transaction. I've allowed free transactions in the parity config (`usd_per_tx = "0"`). The deployment of the contract worked fine with 0 gasPrice. So maybe it's something else?

Transaction:
> {"jsonrpc":"2.0","result":{"blockHash":null,"blockNumber":null,"chainId":"0x11","condition":null,"creates":null,"from":"0x13be977b835a0a525c9ffe516a77f85f830a4b43","gas":"0x12c97f","gasPrice":"0x0","hash":"0xe05be374f25f1d9f8e635c5e04b430e163b0604a17453a9bc1037cdd6542c486","input":"0x582a286361757d2f663342d28c9a5f41a4efcac072bc3f9e3d8ea59010848a6a52f1f9da","nonce":"0x9","publicKey":"0x016f001773430d0a5d96f1b7d3b103995f5cf496de6cf2bca8216256859fe69b009aca5be9b4826837ff6f43531b57d75947566c0c606c01651c1767dfac0c7d","r":"0x550191a369d297d8644add3dbdea5f373ba565ea4bde6708fed7d43b0492e942","raw":"0xf88409808312c97f94256757a0ccb2c506aedd9bf261726f664feb4fda80a4582a286361757d2f663342d28c9a5f41a4efcac072bc3f9e3d8ea59010848a6a52f1f9da46a0550191a369d297d8644add3dbdea5f373ba565ea4bde6708fed7d43b0492e942a0188699e4dbf3a30336c06873c0902feec1e23c8b0189b9ba823945d15a08d705","s":"0x188699e4dbf3a30336c06873c0902feec1e23c8b0189b9ba823945d15a08d705","standardV":"0x1","to":"0x256757a0ccb2c506aedd9bf261726f664feb4fda","transactionIndex":null,"v":"0x46","value":"0x0"},"id":1}

**Comment by MaxXor** [comment]
After debugging this issue for a while I found out that only transactions from non-validator addresses are pending forever. When I submit the same transaction from validator address it gets sealed into a block immediately. Is there any configuration option to change this behavior or is this a bug?

**Comment by Tbaut** [comment]
Are you sure that you non validator node is connected to the network and synced?

**Comment by MaxXor** [comment]
I am directly connected to the validator node, but using a third-party wallet MetaMask. I loaded some Ether on the MetaMask wallet and try to call contract functions. I can find the transaction in the mempool of the validator node, so it gets correctly submitted, but never included in a block. If I try it from a validator account and use the same transaction extra data it is working. So I guess the is some kind of problem with non-validator addresses.

**Comment by Tbaut** [comment]
Your validator account is probably unlocked on the validator node. I guess the problem is more on the signing part. I've just tried a similar setup with Metamask and my node is not a validator but still could send and broadcast the Tx... Is your contract function callable by any account and not restricted to the owner for instance?

**Comment by MaxXor** [comment]
It's perfectly fine callable from anyone ([see here](https://github.com/MaxXor/iuk-blockchain/blob/4eede6b1d54869cd350333705e4b7a4e30445288/contracts/Documents.sol#L36)). I don't use any non-validator nodes. I generated a fresh wallet address in MetaMask, sent some Ether to it and try to call the contract function by broadcasting the transaction to one of the validator nodes. Maybe we have a misunderstanding with validator and non-validator nodes?

**Comment by Tbaut** [comment]
I think I understand correctly.
Can you send a normal transaction (not a contract call) from this non-validator account?

**Comment by MaxXor** [comment]
I've tried now again with the updated parity v1.11.6-beta and it all is working fine now.
