### ISSUE TITLE
parity signer new-token displays old information

### ISSUE THREAD

**Issue by stone212** [paritytech/parity#9073]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.10.7
> - **Which operating system?**: Ubuntu
> - **How installed?**: binary (deb)
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: eth
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Using the new ParityUI I am directed to create a new token.  I do:

> $ parity signer new-token

The new token appears and I can use it in the Parity UI.  But there is also this message:

> 
> Open: http://127.0.0.1:8180/#/auth?token=FU9b-YqaT-FdRN-1dOw
> to authorize your browser.

Because the browser UI does not work any more I think this message should be deleted?

**Comment by sorpaas** [comment]
This should be fixed in #8783. I don't remember we backported it to current beta or stable yet, but this will land on next beta, at least. :)
