### ISSUE TITLE
Sending out a token that is NOT registered?

### ISSUE THREAD

**Issue by NinjaTurtle007** [paritytech/parity#9091]
Is there a way to send out a token that is not registered with the Token Registry Dapp?

Most project don't seem to register their tokens and I don't feel like paying the fee for all of them.

**Comment by Tbaut** [comment]
>Is there a way to send out a token that is not registered with the Token Registry Dapp?

Yes. You need to know the contract and (and its ABI if it's not an ERC20 standard) to watch it, and call the transfer function. (some more info [here](https://wiki.parity.io/Smart-Contracts)) Or you can use MyCrypto Desktop with your key files, which could be somewhat much easier.
