### ISSUE TITLE
IO Worker #0 panicked at DB flush failed. DB is corrupt and not repairable.

### ISSUE THREAD

**Issue by LefterisJP** [paritytech/parity#9123]
**Which Parity version?**: v1.10.8-stable-bd20c45898-20180628/x86_64-linux-gnu/rustc1.27.0
**Which operating system?**: Linux
**How installed?**:  Package manager
**Are you fully synchronized?**:  yes -- up until the time of the crash. Now DB is corrupt
**Which network are you connected to?**: ethereum mainnet
**Did you try to restart the node?**: yes

My node was running fine for a long time but then I noticed that it crashed with the following output:

```
====================

stack backtrace:
   0:     0x560dd40314bc - <unknown>
   1:     0x560dd4030ae2 - <unknown>
   2:     0x560dd36c30fa - <unknown>

Thread 'IO Worker #0' panicked at 'DB flush failed.: Error(Msg("IO error: While fdatasync: /home/lefteris/ethereum/parity_chains_mainnet/ethereum/db/906a34e69aec8c0d/overlayrecent/db/MANIFEST-197636: Input/output error"), State { next_error: None, backtrace: None })', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

When I attempted to restart the DB is corrupt and not repairable and I get the following:

```
2018-07-14 12:44:39  DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col5, col0, col6, col2, col3, attempting repair
Client service error: Client(Database(Error(Msg("Received null column family handle from DB."), State { next_error: None, backtrace: None })))
```

I guess the only thing I can do now is a full resync. I know the stack trace that was output is not really much but I hope it can help in finding the issue.

**Comment by Tbaut** [comment]
This is a duplicate from #7748
This error indicates a DB corruption most likely due to a memory error. Could you please make sure that your memory passes a memtest?
