### ISSUE TITLE
[WIP] Add EOS Classic support

### ISSUE THREAD

**Issue by eosclassicteam** [paritytech/parity#9156]
We would like to add EOS Classic mainnet as a side chain of Ethereum,

However our current logic for rewarding miners isn't compatible with parity client

We need the following logic for our chain consensus

- [ ] **Check if it is EOS Classic chain ( Need hash check for genesis block )** - We need this feature for PR
- [ ] If it is EOS Classic chain use new reward logic ( We use modification logic of MCIP-3 starting from genesis block ) https://github.com/eosclassicteam/parity/compare/v1.11.7...eosclassicteam:eosclassic#diff-0a229ee5988e1a97f1bb37dbb2f7028dR316
- [ ] Add reward hardfork on block num 150,000 ( Decrease the reward up to 1/10 )
https://github.com/eosclassicteam/parity/compare/v1.11.7...eosclassicteam:eosclassic#diff-0a229ee5988e1a97f1bb37dbb2f7028dR307
- [ ] Implement Reward halving logic every 2,500,000 block ( We added EOSC-1017 , which is a modification of ECIP-1017 logic ) https://github.com/eosclassicteam/parity/compare/v1.11.7...eosclassicteam:eosclassic#diff-0a229ee5988e1a97f1bb37dbb2f7028dR287

https://github.com/eosclassic/go-eosclassic/blob/master/consensus/ethash/consensus.go#L617

This is our main go-eosclassic fix for our following reward criteria, and we've tested on our private testnet to see if they work fine

We've prepared a hack-fix of parity client to support EOS Classic mainnet ( https://github.com/eosclassicteam/parity/compare/v1.11.7...eosclassicteam:eosclassic ) , however we need hash check to make sure the following logic works only with our chain, not with Ethereum or Ethereum Classic chain.

Also adding test script would be appreciated, for now we don't have enough manpower to work with rust-lang development, again we would like to see EOS Classic mainnet running on Parity client ❤️

**Comment by eosclassicteam** [comment]
@5chdn

**Comment by 5chdn** [comment]
Thanks, just create a PR once you are finished.

**Comment by eosclassicteam** [comment]
@5chdn We need help 😂

**Comment by 5chdn** [comment]
Any specific question?

**Comment by eosclassicteam** [comment]
@5chdn Yes here is our question https://github.com/paritytech/parity-ethereum/pull/9158 We will give the bounty for parity team if needed 😄
