### ISSUE TITLE
QUASI-Redundant calculation, target = max(min_difficulty, target); in fn calculate_difficuty

### ISSUE THREAD

**Issue by efaysal** [paritytech/parity#987]
Roughly the mathematics of max operations are here: 

c is the added power, b is your traget, a is the initial difficulty: 

 If c>0, max(a,max(a,b)+c)=
i) if a< b then b+c
ii) if b < a then a+c
This will never ever set the system to its initial difficulty (a).

if you use directly max(a,b+c)
i) if a< b+c then b+c
ii) if b + c < a then a
This will set a possibility that the system may be set to its initial difficulty again, as Homestead YP formulation.

This is quasi redundant  target = max(min_difficulty, target);

better to suppress it  and just keep what follows:

let period = ((parent.number + 1) / EXP_DIFF_PERIOD) as usize;
        if period > 1 {
            target = max(min_difficulty, target + (U256::from(1) << (period - 2)));
        }
It will be more concise with Homestead YP.

**Comment by gavofyork** [comment]
PR accepted :)

**Comment by 5chdn** [comment]
This _refactoring_ labelled issue is inactive since last year. 

@paritytech/core-devs Please, confirm within 7 days it is still realistic to implement it _some day maybe_. If so, please add an assignee and a milestone, or close otherwise.
