### ISSUE TITLE
100% static binary

### ISSUE THREAD

**Issue by arkpar** [paritytech/parity#999]
Support `x86_64-unknown-linux-musl` target build

**Comment by rainbeam** [comment]
I suppose there's two things here: 1) allow linking against musl, 2) enable a fully static binary. Linking against musl *should* make the fully static aim much easier, but there might be other problem libraries.

**Comment by petevine** [comment]
Coming to ARM soon. https://github.com/rust-lang/rust/pull/33189

**Comment by Vurich** [comment]
I'm pretty certain that nanomsg relies on glibc extensions, so we'd have to remove our dependency on that. If you try to compile `parity` with a `musl` target you get missing definitions all over the place.
